### ISSUE TITLE
SG300 problem with configuration saving

### ISSUE THREAD

**Issue by andrejgorin** [ktbyers/netmiko#1004]
Hello, Ktbyers!
First of all, thank you for a wonderful product. 
I'm wondering, is there any way to 'write memory' on Cisco SG300 switches? When trying to issue commands 'write memory' or 'copy run start' I got:

`Traceback (most recent call last):
  File "lldp_snmp.py", line 204, in <module>
    conn_process(host)
  File "lldp_snmp.py", line 167, in conn_process
    execute_from_commands(hostname, **device_params)
  File "lldp_snmp.py", line 86, in execute_from_commands
    wrimem = ssh.send_command(save)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 1188, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: LA\-22\-z012\-sg300\#`

I guess, because of this:

`ams1-14-t012-csb#write memory 
Overwrite file [startup-config].... (Y/N)[N] ?Y
Copy succeeded
LA-22-z012-sg300#`

**Comment by ktbyers** [comment]
Use the `save_config()` method. It should handle this prompting automatically.

Just re-open this if this fix doesn't work.
