### ISSUE TITLE
Mikrotik new driver issues

### ISSUE THREAD

**Issue by notonlyvandalzzz** [ktbyers/netmiko#1016]
Trying to implement basic level of Mikrotik support right now, and it's acting weird.
When set_base_prompt() returns only '' (skipping prompts check) i have this, removed auth lines for clarity:
`DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 262144 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: 

  MMM      MMM       KKK                          TTTTTTTTTTT      KKK
  MMMM    MMMM       KKK                          TTTTTTTTTTT      KKK
  MMM MMMM MMM  III  KKK  KKK  RRRRRR     OOOOOO      TTT     III  KKK  KKK
  MMM  MM  MMM  III  KKKKK     RRR  RRR  OOO  OOO     TTT     III  KKKKK
  MMM      MMM  III  KKK KKK   RRRRRR    OOO  OOO     TTT     III  KKK KKK
  MMM      MMM  III  KKK  KKK  RRR  RRR   OOOOOO      TTT     III  KKK  KKK

  MikroTik RouterOS 6.27 (c) 1999-2015       http://www.mikrotik.com/

[?]             Gives the list of available commands
command [?]     Gives help on the command and list of arguments

[Tab]           Completes the command/word. If the input is ambiguous,
                a second [Tab] gives possible options

/               Move up to base level
..              Move up one level
/command        Use command at the base level
[user@MKT_1100_GW075_1] > 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'ip route print\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: ip route print`
And nothing more, instead of displaying route list its just echoes input and thats all. 
One more thing to mention: as you see, it shows regular prompt right after connection, but doesn't shows it after several \n chars being sent, that's why i've disabled prompt check. And i'm using '+t' suffix in login name to disable terminal ability check from Mikrotik side.
netmiko version is 2.3.0

**Comment by ravenich** [comment]
If we use `+ct` at the login string (from mikrotik's wiki: c for disable colours, t for disable auto detection of terminal capabilities) and `'default_enter': '\r\n'` error is:
`DEBUG:netmiko:repr = '\r\n\r\r\r\r\x1b[9999B[admin@MikroTik] > '`

**Comment by dBitech** [comment]
Please find attached a patch to add prelim Microtik support via a new driver. 
[netmkio-microtik.patch.txt](https://github.com/ktbyers/netmiko/files/3127211/netmkio-microtik.patch.txt)

**Comment by carlniger** [comment]
Thank you @dBitech for getting this rolling. Going to close this issue. Feel free to comment on the PR #1203 if we need to discuss anything else!
