### ISSUE TITLE
ValueError: Router prompt not found: Error: Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:

### ISSUE THREAD

**Issue by goldfishhh** [ktbyers/netmiko#1019]
I have encountered some problems under the huawei_ssh.py file.

Huawei's device will have a prompt when logging in for the first time: < Error: Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]: >
Our existing scripts are not recognized and will pop up ValueError: 

`ValueError: Router prompt not found: Error: Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:   `

I tried adding the following command under the <huawei_ssh.py>  **def set_base_prompt** module:

_if prompt.find("Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:")>=0:_
 _print("Match <Please choose 'YES' or 'NO' first before pressing 'Enter'. _[Y/N]:>")_
 _self.write_channel("N" + self.TELNET_RETURN)_
 _self.write_channel("N"+self.RETURN)_
 _print( self.read_channel())__

But the problem remains
Pop up as

`Match <Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:>

Traceback (most recent call last):
  File "D:/python/huawei.py", line 13, in <module>
    Net_connect = ConnectHandler(**huawei123)
  File "C:\Users\fish\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\ssh_dispatcher.py", line 190, in ConnectHandler
    Return ConnectionClass(*args, **kwargs)
  File "C:\Users\fish\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 248, in __init__
    Self.session_preparation()
  File "C:\Users\fish\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\huawei\huawei_ssh.py", line 15, in session_preparation
    Self.set_base_prompt()
  File "C:\Users\fish\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\huawei\huawei_ssh.py", line 88, in set_base_prompt
    Raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: Error: Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:`

Please help solve the problem, thank you！

**Comment by vladola** [comment]
I think this might be because the value of the `prompt` variable didn't change after your test (although it's unclear... could you post your full code from `D:/python/huawei.py`? ). 

What you could do is insert the following @ [this line ](https://github.com/ktbyers/netmiko/blob/develop/netmiko/huawei/huawei_ssh.py#L70)

```python
if "[Y/N]" in prompt:
    print("First time logging in")
    self.write_channel("N"+self.RETURN)
prompt = self.read_channel()
prompt = self.normalize_linefeeds(prompt)
# If multiple lines in the output take the last line
prompt = prompt.split(self.RESPONSE_RETURN)[-1]
prompt = prompt.strip()
```

It's ugly but it should work.

**Comment by ktbyers** [comment]
How are you even connecting to the device--if the device is not configured? Does the device just have a default IP address and username/password or are you accessing it via a terminal server?

Regards, Kirk

**Comment by goldfishhh** [comment]
> I think this might be because the value of the `prompt` variable didn't change after your test (although it's unclear... could you post your full code from `D:/python/huawei.py`? ).
> 
> What you could do is insert the following @ [this line ](https://github.com/ktbyers/netmiko/blob/develop/netmiko/huawei/huawei_ssh.py#L70)
> 
> ```python
> if "[Y/N]" in prompt:
>     print("First time logging in")
>     self.write_channel("N"+self.RETURN)
> prompt = self.read_channel()
> prompt = self.normalize_linefeeds(prompt)
> # If multiple lines in the output take the last line
> prompt = prompt.split(self.RESPONSE_RETURN)[-1]
> prompt = prompt.strip()
> ```
> 
> It's ugly but it should work.

**Comment by goldfishhh** [comment]
I modified the code under huawei_ssh.py, I reversed the order of self.set_base_prompt() and self.disable_paging(command="screen-length 0 temporary"), he can now use it normally.

_**def session_preparation(self):
self._test_channel_read()
#self.disable_paging(command="screen-length 0 temporary")
#Set ter len 0
self.NOlenth()
self.set_base_prompt()**_

**Comment by goldfishhh** [comment]
> How are you even connecting to the device--if the device is not configured? Does the device just have a default IP address and username/password or are you accessing it via a terminal server?
> 
> Regards, Kirk

Thank you very much for your reply:
Huawei's few low-end devices can do what you said for configuration-free login, but the problem I encountered is that after configuring AAA and ssh on most switches, if you do not enter <undo local-user policy password in AAA view. Change > .Default command will ask you to change your password when you log in for the first time: <Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:>
But huawei_ssh.py of netmiko I can't skip this step (you can't enter Y or N).
I guess it should be **_self.set_base_prompt()_** detection failed.
I tried to modify this file two days ago and found it.Exchange the position of the two lines of code, it will work
before:
_**def session_preparation(self): 
self.set_base_prompt()
self.disable_paging(command="screen-length 0 temporary")**_
It check first.
after:
_**def session_preparation(self): 
self.disable_paging(command="screen-length 0 temporary") 
self.set_base_prompt()**_
Location swapping can log in, although there are still errors, but it does not affect the normal operation of the program.
Although the problem is solved, I don't quite understand why.
Please can you tall me why?
Thank you very much

**Comment by goldfishhh** [comment]
> I think this might be because the value of the `prompt` variable didn't change after your test (although it's unclear... could you post your full code from `D:/python/huawei.py`? ).
> 
> What you could do is insert the following @ [this line ](https://github.com/ktbyers/netmiko/blob/develop/netmiko/huawei/huawei_ssh.py#L70)
> 
> ```python
> if "[Y/N]" in prompt:
>     print("First time logging in")
>     self.write_channel("N"+self.RETURN)
> prompt = self.read_channel()
> prompt = self.normalize_linefeeds(prompt)
> # If multiple lines in the output take the last line
> prompt = prompt.split(self.RESPONSE_RETURN)[-1]
> prompt = prompt.strip()
> ```
> 
> It's ugly but it should work.

Thank you very much for your reply:

I will find time to try it out.

**Comment by ktbyers** [comment]
@goldfishhh Please try to properly format your code on GitHub, I am having trouble reading it.

I think probably the solution is to use the `terminal_server` device_type. The terminal_server device_type is just a generic device_type that does nothing in session_preparation. You would then use `.read_channel()` and `write_channel` to bootstrap your device up to a proper state such that it could be used by the normal huawei driver. 

.read_channel and write_channel are low-level methods that let you interact directly with the SSH-channel. So this implies you will need terminate commands with an <enter> key. Also you will have to insert time.sleep between write_channel calls and when you try to read back the response using read_channel.

Let me know if this won't work for some reason.

**Comment by zgcorpuz** [comment]
I am currently encountering the same problem. Does this issue fixed?

**Comment by poyantu** [comment]
@ ktbyers
i have same problem too and i don't understand this issues

log
--
Warning: The initial password poses security risks.
The password needs to be changed. Change now? [Y/N]:
Error: Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:
Error: Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:exit
--

python log
--
Traceback (most recent call last):
  File "getconfig.py", line 13, in <module>
    net_connect = HuaweiSSH(**Huawei)
  File "/home/nara/test/lib64/python3.6/site-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/home/nara/test/lib64/python3.6/site-packages/netmiko/base_connection.py", line 323, in _open
    self._try_session_preparation()
  File "/home/nara/test/lib64/python3.6/site-packages/netmiko/base_connection.py", line 738, in _try_session_preparation
    self.session_preparation()
  File "/home/nara/test/lib64/python3.6/site-packages/netmiko/huawei/huawei.py", line 14, in session_preparation
    self.set_base_prompt()
  File "/home/nara/test/lib64/python3.6/site-packages/netmiko/huawei/huawei.py", line 74, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: Error: Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:
--

Please help solve the problem, thank you

**Comment by ktbyers** [comment]
@zgcorpuz You probably should open a separate issue and describe your issue (post your relevant code and the exception you get).
