### ISSUE TITLE
Configure ProxyCommand not via SSH Config File

### ISSUE THREAD

**Issue by numbnut** [ktbyers/netmiko#1024]
Hi,
I would like to use the ProxyCommand directive to created a proxied SSH connection. I followed your tutorial using an ssh config file. Since I want to implement a generic solution I would like to avoid hard coding configuration options like proxy IPs in the SSH config file. I really would like to directly set the ProxyCommand somehow, but after looking at the code I don't see a solution. Maybe I'm missing something, you could point me to. I think in generall it would be nice to have solution which does not depend on SSH config files.

My current workarounds are:
1. Create a generated temporary file containing the ssh ProxyCommand.
2. Executing a script on the proxy, which creates a SSH connection to the target device.

I hope my point is clear. Thank you for the great project!

**Comment by TomCos** [comment]
Can you clarify better?  Maybe an example of perfect state vs current state for the current process?

**Comment by ktbyers** [comment]
@numbnut Yes, you could just dynamically write an SSH config file and then use this file.

I am open to a PR to pass in more of an in-memory file, if you want to create something like that.


Regards, Kirk

**Comment by numbnut** [comment]
@TomCos @ktbyers Thanks for the feedback and sorry for the late response. I think creating a memory backed file really sounds like a workaround I wouldn't like to implement. It is good to know that there is no other way to configure a ProxyCommand than to use an SSH config file. Give me some more time and if I think that it makes sense, I will come back with a PR.
