### ISSUE TITLE
Change prompt_terminator for Certain Device Type

### ISSUE THREAD

**Issue by numbnut** [ktbyers/netmiko#1025]
Hi,
I want to access a Sun machine via SSH, which isn't a supported device type. Using the linux device type works fine as long as I patch the pri_prompt_terminator=">". I would like to have a solid solution and avoid patching the file. I didn't find a solution to change the prompt_terminator for a certain device type. What would you suggest? If there is no proper way to alter the prompt_terminator, I could try to contribute a new "sun" device type. Would you accept such a contribution and if yes, do you have any hints which principals to respect, when contributing such a new device type?

**Comment by vladola** [comment]
This should be made possible once https://github.com/ktbyers/netmiko/pull/984 is merged.

**Comment by Fatalerr** [comment]
hello @numnut ,
could you please give me a hint how to patch the pri_prompt_termintor or prompt? I have a special device with following prompt, it is a single '<'.  how can I patch to support it ?  I had checked the issue #984 but no help to my case.  thanks in advance.

```
MAIN LEVEL COMMAND <___>
< 
```

**Comment by ktbyers** [comment]
Pull request supporting these environment variables for Linux device type was merged yesterday:

LINUX_PROMPT_PRI = os.getenv("NETMIKO_LINUX_PROMPT_PRI", "$")
LINUX_PROMPT_ALT = os.getenv("NETMIKO_LINUX_PROMPT_ALT", "#")
LINUX_PROMPT_ROOT = os.getenv("NETMIKO_LINUX_PROMPT_ROOT", "#")
