### ISSUE TITLE
ValueError: Failed to enter configuration mode (using netmiko)

### ISSUE THREAD

**Issue by vpotu** [ktbyers/netmiko#1027]
I have some issue regarding the Netmiko module can anyone please help me out. I got this error "ValueError: Failed to enter configuration mode". I am using the Netmiko 2.3.0 version and the python version is 2.7.12. I have also attached the python program and output. So please have a look at it and please help me out as soon as possible.

My python script is:

from netmiko import ConnectHandler

Router1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.146.140',
    'username': 'vineetha',
    'password': 'cisco',
    'secret': 'my_secret',
    #'global_delay_factor': 2,
}

net_connect = ConnectHandler(**Router1)
f1 = open ('Router1')
file1 = f1.read().splitlines()
print file1

for line1 in file1:
        print line1
        #net_connect.enable()
        net_connect.send_config_set(line1, delay_factor=4)
        #net_connect.send_command(line1)

config_commands = ['end', 'wr', 'exit']
output = net_connect.send_config_set(config_commands)
print output

My Router1 file is:

enable
cisco
conf t
int loop 0
ip address 1.1.1.1 255.255.255.255
no shut
int f1/0
ip address 10.1.1.1 255.255.255.252
no shut
exit

The output I have got is:

root@NetworkAutomation-1:~# python w
['enable', 'cisco', 'conf t', 'int loop 0', 'ip address 1.1.1.1 255.255.255.255', 'no shut', 'int f1/0', 'ip address 10.1.1.1 255.255.255.252', 'no shut', 'exit', '']
enable
Traceback (most recent call last):
  File "w", line 20, in <module>
    net_connect.send_config_set(line1, delay_factor=4)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1429, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 42, in config_mode
    pattern=pattern)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1347, in config_mode
    raise ValueError("Failed to enter configuration mode.")
ValueError: Failed to enter configuration mode.

**Comment by vpotu** [comment]
can someone help me as soon as possible

**Comment by ktbyers** [comment]
responded via email.

**Comment by sleppelm** [comment]
I have a similar issue, what was your solution?

Thanks

**Comment by ktbyers** [comment]
@sleppelm You should create a separate issue and post your code and exception. The above code looks incorrect on how to properly enter `enable()` using Netmiko
