### ISSUE TITLE
device_type: hp_procurve - set_base_prompt yields wrong result with more recent firmware

### ISSUE THREAD

**Issue by DerInti** [ktbyers/netmiko#1029]
Model: Pro Curve J9624A 
OS Version: RA.16.04.0008
Netmiko v2.3.0
Issue: 
Since this version of the Procurve Version the prompt set by set_base_prompt looks like this:
hostname# hostname# resulting in failures during 'disable_paging' when expecting the prompt.

My quick and (very) dirty workaround was to patch set_base_prompt in base_connection.py with 
```
if ' ' in prompt:
    prompt = prompt.split(' ')[-1]
```
tbh I have no insight of any negative impact of this  change to other device_types or corner cases.
Maybe anyone can give a hint how to find the reason for this issue (and I will be happy to issue an pull request)

regards,
DerInti

**Comment by carlniger** [comment]
@DerInti have you happened to give this a shot on the more recent develop branch by any chance?  I'll tag this pending close for now but let us know if its still an issue. If it is, could you let us know what changed in the prompt between the previous version(s) and that 16.x version you mentioned?

**Comment by carlniger** [comment]
inactive, closing. feel free to reopen if necessary.
