### ISSUE TITLE
question: delay_factor and authentication timeout

### ISSUE THREAD

**Issue by Sh4mSh4m** [ktbyers/netmiko#1036]
Hi,

Running Nornir with netmiko on a high number (25+) of CISCO 2960X switches we encounter what seems to be authentication errors. Authentication on our devices is set on a TACACS server. Manually, connections can take up to several seconds.

We use "send_command". When reaching out to several devices, this results in some devices failing due to missing connection (likely due to timeout). From previous issues discussed here I understand delay_factor is a global setting managing several different timeouts. I expect it include the one regarding the initial ssh connection.

Therefore, if I m to connect to 100+ devices and if performance is not my goal but reliability, should I bump up the delay_factor to overcome possible delays regarding authentication.

Also, is there any recommanded way to have a retry mechanism if a task fails ?

Thanks,

Regards,

**Comment by Sh4mSh4m** [comment]
Hi,

Running Nornir with netmiko on a high number (25+) of CISCO 2960X switches we encounter what seems to be authentication errors. Authentication on our devices is set on a TACACS server. Manually, connections can take up to several seconds.

We use "send_command". When reaching out to several devices, this results in some devices failing due to missing connection (likely due to timeout).  From previous issues discussed here I understand delay_factor is a global setting managing several different timeouts. I expect it include the one regarding the initial ssh connection.

Therefore, if I m to connect to 100+ devices and if performance is not my goal but reliability, should I bump up the delay_factor to overcome possible delays regarding authentication.

Also, is there any recommanded way to have a retry mechanism if a task fails ?

Thanks,

Regards,

**Comment by ktbyers** [comment]
I would probably view 1000+ as a large number (i.e. 25+ isn't really a large number of devices to automate). This is for reference for other individuals that read this issue in the future.

Your TACACS+ server has to be able to handle the load and respond quickly enough. If you are trying to use AAA and authorize each individual command you will very likely have problems.

You might want to try inserting a small delay between when you start each thread (like .1 seconds or .3 seconds). You will probably have to experiment a bit here.  I have seen this pattern help people in the past (i.e. significantly reduce the TACACS+ authentication issue).

If that works, we might want to enable a way of doing this in Nornir.

You could also try increasing the 'auth_timeout' argument to Netmiko's ConnectHandler. Make sure you are using the latest released netmiko. Using this argument should hopefully provide more time for authentication to complete successfully.

Delay factor/global delay factor won't really help you as that is all post SSH connection.

The way you would retry would just be to catch the authentication exception and add all of the failed devices into a list. You could then just retry on those failed devices. I think this is probably also tracked by Nornir in some way so you could probably extract it directly there. But handing it in Python wouldn't be too hard either.

Let me know what you find.

**Comment by Sh4mSh4m** [comment]
Thanks for the reply. I ll keep you updated soon on the following experiment:
- Using group tasking; I'm thinking introducing a random delay prior to running the task (i.e. before "task.run(...)"). My assumption is that each node execute the parent function and therefore the task.run() at different times.

Thanks, again !

**Comment by ktbyers** [comment]
I am going to close this issue, just re-open if there is something to work on here.
