### ISSUE TITLE
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out:

### ISSUE THREAD

**Issue by sriram0706** [ktbyers/netmiko#1041]
Hello Kirk,

Netmiko is an excellent library and I have been using it for quite a while. I have a question with respect to handling exceptions on Netmiko.

1. Wrong password entered (raises NetMikoAuthenticationException)
2. SSH disabled on a router (raises NetMikoSSHException)
3. Device unreachable (raises NetMikoSSHException)

When a user enters a wrong password, Netmiko raises NetMikoAuthenticationException. However, if a host is unreachable or SSH is disabled on the router, Netmiko raises the same exception (NetMikoSSHException). Is there a way to handle both exceptions separately?

**Comment by ktbyers** [comment]
NetmikoSSHException? That doesn't exist in Netmiko? Did you mean a different exception?

Is the exception string the same or different between the two cases? If the exception string is different, you should be able to detect and handle them differently in your exception handler.
