### ISSUE TITLE
Netmiko LOG netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out:

### ISSUE THREAD

**Issue by joseluisquisan** [ktbyers/netmiko#1044]
Hello,

Im newbie with python and netmiko, Writing asking if you could help me with a python script.

I have to config " 'access-list 30 permit 10.251.0.0 0.0.0.255" in a bunch of 700 Switches. As a test I config the file "myswitches" with only 2 ip's , and an error occours. I dont know why, if i can ping, ssh to the switches. If iI put just 1 ip the file "myswitches", the script works perfectly.

I have Python
(base) C:\Users\soc5-itq\Documents\LAB>python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:09) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

I need if you could save my life,

I got this error:-----------------------------------------------
(base) C:\Users\soc5-itq\Documents\LAB>python configswitchssh.py
Traceback (most recent call last):
  File "configswitchssh.py", line 27, in <module>
    net_connect = ConnectHandler(**iosv_l2)
  File "build\bdist.win-amd64\egg\netmiko\ssh_dispatcher.py", line 228, in ConnectHandler
  File "build\bdist.win-amd64\egg\netmiko\base_connection.py", line 311, in __init__
  File "build\bdist.win-amd64\egg\netmiko\base_connection.py", line 861, in establish_connection
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 10.250.209.11
:22
----------------------------------------------------------------

This is my code
```

#!/usr/bin/env python

from netmiko import ConnectHandler
from datetime import datetime
from datetime import date

f = open ('myswitches.txt')

for line in f:
    hostname = line

    iosv_l2 = {
        'device_type': 'cisco_ios',
        'ip': hostname,
        'username': '**************',
        'password': '**************',
        'global_delay_factor': 3,
    }

    commands = [
        'enable',
        'access-list 30 permit 10.251.0.0 0.0.0.255',
        'do wr',
    ]

    start_time = datetime.now()
    net_connect = ConnectHandler(**iosv_l2)
    print ("Configurando Switch: " + str(hostname))
    net_connect.enable()
    output = net_connect.send_config_set(commands)
    net_connect.disconnect()
    print output
    end_time = datetime.now()
    total_time = end_time - start_time
    print ("Tiempo total del Script " + str(total_time))

```
-------------------------------------------------
myswitches.txt

10.250.209.11
10.250.209.12

**Comment by YauheniKr** [comment]
Hello, its because when read ip address from file each string except last finished with whitespace character "\n" and netmiko take ip address as '10.250.209.11\n' what incorrect
Simple way to fix ichange:
`hostname = line `-> `hostname = line.strip()`
Should work fine.

**Comment by joseluisquisan** [comment]
Excellent! It works , Thank you. Have a nice new year.
