### ISSUE TITLE
send_command_timing stops at same time no matter what delay or loops is set to

### ISSUE THREAD

**Issue by TomCos** [ktbyers/netmiko#1045]
Having an odd issue, wanted to see if anyone has seen this before.  When using send_command_timings, I keep hitting the same wait time upper limit, regardless of what I set the delay_factor or the max_loops to.  It keeps stopping at 4 minutes, on the dot.  The code is fairly simple:

ssh_netmiko.send_command_timing(command_string=command, delay_factor=20, max_loops=500)

I had the same results at delay_factor=10, max_loops=150 and delay_factor=30, max_loops=500.
Any ideas?

**Comment by carlniger** [comment]
@TomCos is this happening on a "show-tech" or some other long running command? I just tested on netmiko 2.3.3 w/ the various values you provided and although I don't have a super slow output to actually wait a long time for completion for, the delays are incrementing the higher the delay_factor is which seems good :) let us know if this is still an issue.

**Comment by TomCos** [comment]
@carlniger thanks for the reply.  The actual command I was running it on was a Nexus device doing the 'install all' which takes a while depending on how many features are enabled, if there are FEX attached, etc.

**Comment by carlniger** [comment]
@TomCos are you by any chance using fast_cli? Also did you modify the global_delay_factor? I re-checked this quickly and don't see anything very obvious hitting me in the face :)

**Comment by TomCos** [comment]
Yes I was modifying the global delay factor.  I did move this solution to capture the except string, but it did give me some trouble obviously.  If you're not seeing any issues, no point chasing it.  Shouldn't the local delay factor override the global one though?

**Comment by carlniger** [comment]
Yeah mostly I was asking because if you have fast_cli set it will try to pick the lowest of the delays set so I didn't know if that was hiding issues from us -- was looking [here](https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L958-L967) specifically. Appreciate the info, will close it but holler if its worth digging into more, thanks @TomCos !
