### ISSUE TITLE
Is delay factor needed for showing running config of multiple interfaces on a Cisco switch?

### ISSUE THREAD

**Issue by EarlZapanta** [ktbyers/netmiko#1046]
Hi @ktbyers ,

Apologies for this easy question perhaps.. I'm trying to modify/improve a VLAN change utility I got the from @nfordhk (https://github.com/nfordhk/Network-Automation/blob/master/vlanChangeUtility.py) where I wan't to have an option to modify VLAN config of multiple ports. Before modifying the config though, I wan't it to show the running config of the interfaces the user wants to modify. Below is my current code: 

elif numIntOption == '2':
                interfaces = input('\nWhich interfaces would you like to modify? (e.g. g0/2 g0/3 (separated by a space)) ')
                intList = list(interfaces.split())
                i = 0
                sizeOfList = len(intList)
                print ('\nShowint Current Configuration...')
                while i < sizeOfList:
                    output = net_connect.send_command('show run int ' + intList[i], '\n', expect_string = r'#', delay_factor = 2)
                    i += 1

I get this error after inputting the ports:

Traceback (most recent call last):
  File "test.py", line 98, in <module>
    output = net_connect.send_command('show run int ' + intList[i], '\n', expect_string = r'#', delay_factor = 2)
TypeError: send_command() got multiple values for argument 'expect_string'

Can you help me with the correct way to do it in this context? Is there a need to apply the delay factor here or not anymore? I actually checked out your delay factor tutorial here:(https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html) but I'm kinda confused how to apply it in this context. I would like to ask for your expert advice/help, please. 

Appreciate your time and support. Thank you!

**Comment by EarlZapanta** [comment]
Hi @ktbyers , 

Sorry for the dumb question above. I already got it to input the 'sh run int' command using a loop but I keep getting the 'Invalid input detected' error below:

Please select the VLAN change option:
1. Single interface
2. Multiple interfaces
2

Which interfaces would you like to modify? (e.g. g0/2 g0/3 (separated by a space)) g0/1 g0/4 g0/6
Showing Current Interface Configuration...
False #written to check if I'm in config mode or not
CoreSW# #written to check the prompt
                   ^
% Invalid input detected at '^' marker.

                   ^
% Invalid input detected at '^' marker.

                   ^
% Invalid input detected at '^' marker.


Please select the VLAN change option:
1. Single interface
2. Multiple interfaces


My current code is:

elif numIntOption == '2':
                interfaces = input('\nWhich interfaces would you like to modify? (e.g. g0/2 g0/3 (separated by a space)) ')
                intList = list(interfaces.split())
                i = 0
                sizeOfList = len(intList)
                print ('Showing Current Interface Configuration...' )
                checkMode = net_connect.check_config_mode()
                print(checkMode)
                findPrompt = net_connect.find_prompt()
                print(findPrompt)
                shRunInt = 'sh run int '
                while i < sizeOfList:
                    output = net_connect.send_command(shRunInt + intList[i], expect_string =r'#', delay_factor =2)
                    print(output)
                    i += 1

**Comment by ktbyers** [comment]
I am going to close the above. It is unreadable.

If there is an open question, please reformat using triple backticks for posting code.
