### ISSUE TITLE
Issue with Netmiko and linewrap on ASA

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#105]
I found some more time to build a python script around your netmiko library.
The script is used to enter commands in multiple cisco asa's.
One strange thing I found was, that when I enter a really long command, I also see that command in the output.
I dont know if it a limitation to netmiko, paramiko, or my terminal =)
I will give you an example:
Please see attached txt file for the whole output.
If I send this command:
show run | inc clock|logging|aaa|http|ssh|telnet|ntp
I will get the command back on the first line of the output, example:
>>> print output                                                                                                                                         show run | inc clock|logging|aaa|http|ssh|te$
clock timezone CET 1

**Comment by ogenstad** [comment]
I haven't tested this but my guess would be the terminal width command. It is set to 80 by default. If it's set lower you would get the above behavior. It can be between 40 and 511. I don't think it can be changed during runtime and it would require a config change.

Chances are that the above config doesn't use the default with of 80.

**Comment by ktbyers** [comment]
This should be fixed by this commit https://github.com/ktbyers/netmiko/commit/5c5c05f92bb49f149a8845281e2a352cb4a5c0d2
