### ISSUE TITLE
WLC incorrect login returns false error

### ISSUE THREAD

**Issue by jrecords** [ktbyers/netmiko#1052]
If wrong username/password is given using 'cisco_wlc' device type:

raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: 'User:'

Instead of Invalid login credentials.

**Comment by ktbyers** [comment]
I am not sure this is worth fixing. 

The WLC has the very strange behavior where it adds the extra `login as` message (which forces Netmiko to add special code to handle the login).

```
        login as: user

        (Cisco Controller)

        User: user

        Password:****
```

We loop a certain amount of times and if we ever send the password, the we assume it is correct and then move on to the next step. Above you are failing on the next step.

We could add a check after sending the password whether we successfully read a `>` as one possible solution. Is the `>` guaranteed to always be present post-login (or is that configurable)?

**Comment by OzNetNerd** [comment]
@ktbyers, I've raised https://github.com/ktbyers/netmiko/pull/1107 for this issue.

**Comment by ktbyers** [comment]
Error message improved in #1107
