### ISSUE TITLE
Inconsistent SSH with ProxyCommand in python2 and python3

### ISSUE THREAD

**Issue by eoprede** [ktbyers/netmiko#1053]
Hello,

This is really not a huge deal as workaround is extremely simple and we should be using python3 in general, but I figured I'd share this mostly FYI.

Fragment of SSH config:
```
host sw1a.abc
        User admin
        IdentityFile ~/.ssh/id_rsa
        KexAlgorithms +diffie-hellman-group1-sha1
        HostKeyAlgorithms +ssh-dss
        ProxyCommand ssh proxy.abc -W 10.0.5.88:22
```
Code creating connection:
```
net_connect = ConnectHandler(device_type="cisco_nxos",host='sw1a.abc',username=un,password=pw,ssh_config_file='~/.ssh/config')
```
Python 3.6.0 - just works as expected.
Python 2.7.10 - fails
```
Traceback (most recent call last):
  File "run_commands.py", line 46, in <module>
    net_connect = ConnectHandler(device_type="cisco_nxos",host='sw1a.abc',username=un,password=pw,ssh_config_file='~/.ssh/config')
  File "/Library/Python/2.7/site-packages/netmiko/ssh_dispatcher.py", line 100, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 144, in __init__
    self.establish_connection()
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 482, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_nxos sw1a.abc:22
```
netmiko          2.3.0
paramiko         2.4.2
MacOS 10.14.2

I unfortunately can't try the netcat proxy command as my jumpbox doesn't have it. Direct connections to switches work just fine in both python2 and 3.

**Comment by ktbyers** [comment]
Okay, I have not seen any issues with SSH proxy and Python2, but as you said Python2 support is going away this year, so it probably isn't worth digging into much more (unless possibly it is reported as a wider problem in some way).
