### ISSUE TITLE
Need to send command to device at login before getting to prompt

### ISSUE THREAD

**Issue by mims1979** [ktbyers/netmiko#1055]
So I have a cisco IOS device.  When you ssh to it, it has a menu mgmt command so that it displays a menu of options.  It's a console server so basically it's saying enter "1" for the first device, 2 for second, etc.  In order to get to the actual prompt you have to enter "x" at that point you are dropped to:

devicename#

When trying to access this device it always fails with:

ValueError: Router prompt not found: 'Selection:'

I tried adding an except valueerror to send_command x but netmiko clears the connection when error is raised I guess so it doesn't sent it.

Anyone have an idea how to get around this issue.  And example of login is below:

 Line 388    Terminal-type vt100    

             OOB Management
______________________________________________________________________
 1.  device1                 17.
 2.  device2                 18.
 3.  device3                 19.
 4.                               20.
 5.                               21.
 6.                               22.
 7.                                23.
 8.                                24.
 9.                                25.
10.                                26.
11.                                27.
12.                                28.
13.                                29.
14.                                30.
15.                                31.
16.                                32.
______________________________________________________________________
 Exit from Menu       : press x key
 Disconnect session   : press CTRL Shift 6 then X, type "disc" to disconnect

Selection: x
devicename#

**Comment by ktbyers** [comment]
You will need to use the `terminal_server` device type and then use write_channel() and read_channel() to handle the menu interface.

Once you are fully connected to the end device (i.e. the device that you are reaching via the terminal server, then you can use redispatch to switch the device_type to the proper netmiko device_type).

There should be some examples of this in the GitHub issues (probably search on redispatch).

**Comment by mims1979** [comment]
Perfect:

        if self.devicetype == "terminal_server":
            self.conn.write_channel("\n")
            self.conn.read_until_pattern("Selection:")
            self.conn.write_channel("x\n")
            self.conn.read_until_pattern("#")
            redispatch(self.conn, device_type='cisco_ios')

Thanks for the quick response!

**Comment by ktbyers** [comment]
Nice!
