### ISSUE TITLE
Small device input buffers and send_config_set failures

### ISSUE THREAD

**Issue by jtdub** [ktbyers/netmiko#1058]
We've recently encountered issues where we send a long list of commands to `send_config_set` and a remote device appears to fill up the input buffers on the device, causing it to not properly execute commands.

This appears to be an artifact of how `send_config_set` operates, by sending the entire list of commands to the device, then grabbing the entire output afterwards.

I believe in instances such as this, we could batch the commands, grab output, then proceed to the next batch of commands until the entire list of commands has been executed.

My thought is something like this:
```
def send_config_set(
    self,
    config_commands=None,
    exit_config_mode=True,
    delay_factor=1,
    max_loops=150,
    strip_prompt=False,
    strip_command=False,
    config_mode_command=None,
    batch_commands=False,
    batch_length=10,
):
    import math
    """
    Send configuration commands down the SSH channel.
    config_commands is an iterable containing all of the configuration commands.
    The commands will be executed one after the other.
    Automatically exits/enters configuration mode.
    :param config_commands: Multiple configuration commands to be sent to the device
    :type config_commands: list or string
    :param exit_config_mode: Determines whether or not to exit config mode after complete
    :type exit_config_mode: bool
    :param delay_factor: Factor to adjust delays
    :type delay_factor: int
    :param max_loops: Controls wait time in conjunction with delay_factor (default: 150)
    :type max_loops: int
    :param strip_prompt: Determines whether or not to strip the prompt
    :type strip_prompt: bool
    :param strip_command: Determines whether or not to strip the command
    :type strip_command: bool
    :param config_mode_command: The command to enter into config mode
    :type config_mode_command: str
    :param batch_commands: Break the list of commands into batches for execution
    :type batch_commands: bool
    :param batch_length: Maximum length of each command batch
    :type batch_length: int
    """
    delay_factor = self.select_delay_factor(delay_factor)
    if config_commands is None:
        return ""
    elif isinstance(config_commands, string_types):
        config_commands = (config_commands,)

    if not hasattr(config_commands, "__iter__"):
        raise ValueError("Invalid argument passed into send_config_set")

    batch_length = batch_length if batch_commands else len(config_commands)
    batches = math.ceil(len(config_commands) / batch_length)
    start_batch = 0
    end_batch = batch_length
    fast_cli = False if batches > 1

    # Send config commands
    cfg_mode_args = (config_mode_command,) if config_mode_command else tuple()
    output = self.config_mode(*cfg_mode_args)
    for batch in range(batches):
        for cmd in config_commands[start_batch:end_batch]:
            self.write_channel(self.normalize_cmd(cmd))
            if self.fast_cli:
                pass
            else:
                time.sleep(delay_factor * 0.05)
        start_batch = end_batch
        end_batch += batch_length

        # Gather output
        output += self._read_channel_timing(
            delay_factor=delay_factor, max_loops=max_loops
        )

    if exit_config_mode:
        output += self.exit_config_mode()
    output = self._sanitize_output(output)
    log.debug("{}".format(output))
    return output
```

I plan on enhancing our in house integration tests to attempt to replicate this issue, so that I can try this out to see if it works properly. If it works and you don't have a better solution, I'll look at creating a PR.

**Comment by ktbyers** [comment]
@jtdub Does the problem go away with delay_factor i.e. allowing more time for the device to process the incoming commands?

I guess what I am wondering is if it is entirely an input issue i.e. if you slow-down the input rate enough does the problem go away.

Or is the problem somehow related to reading the output i.e. something along the lines of no more input commands will be processed until the previous output is read.

I would have thought it would have been the former (but definitely an assumption on my part).

**Comment by jtdub** [comment]
I'm working on replicating the issue. Once I'm able to, I'll let you know.

**Comment by jtdub** [comment]
In our debugging output, we were seeing things like:
```
aggra-lab-7010-1.ord1(config-acl)#  15350 permit ip 10.0.5.255/32 a
 16560 permit ip 10.0.6.120/32 a
                                                                  ^
% Ambiguous command at '^' marker.
```
`a` is `any`, but for some reason truncated on input. It happened when remediating ACL's in place.

It looks like less of an input buffer issue and more of an issue with the device not necessarily liking the modification of in production access-lists. I'm still trying to reliably reproduce the issue, however.

**Comment by jtdub** [comment]
Never mind above... I kept thinking `time.sleep(delay_factor + 0.05)` instead of `time.sleep(delay_factor * 0.05)`

**Comment by ktbyers** [comment]
Assuming fast_cli=False, then select_delay_factor will always choose the greater of global_delay_factor and delay_factor. Both of these default to 1.

The default channel_write delay is .05 seconds (1 * .05) i.e. 20 commands get written per second by default.

Once again assuming fast_cli=False, then setting global_delay_factor=.2 should have no effect if delay_factor is 1 (at least as far as send_config_set method goes).

Let me know if that makes sense (and makes sense given what you are seeing).

**Comment by ktbyers** [comment]
Ooops, didn't see your second post...until after I commented.

**Comment by aedwardstx** [comment]
From how I understand the issue, the device seems to have an input command buffer that is roughly 100 lines long in the case of a 3064 running 6.0(2)U6(6). When the buffer is filled, additional commands sent on the SSH channel get tail dropped. What would seem to be needed is a mechanism that counts the number of prompts that come back and maintains the number of unacknowledged commands at some sensible level. I’ve written and tested a bit of code that does this. 

CommandBufferArbiter
```
class CommandBufferArbiter:
    """
    Acts as a send command rate limiter that maintains the “command buffer” at chunk_size number of commands.
    It would allow sending of chunk_size commands, when it sees X prompts come back, it allows another X command(s).
    If it doesn’t see a prompt come back in some time, it figures “I must have missed it” and sends another command.
    This continues until the config set is depleted.
    """

    def __init__(self, hostname, chunk_size=10, timeout=5, hostname_splice=16):
        print('starting CBA')
        self.hostname = hostname
        self.chunk_size = chunk_size
        self.timeout = timeout
        self.hostname_splice = hostname_splice

        self.unacknowledged_commands = 0
        self.timer = None

        # lines that have already been checked for prompts
        self.completed_lines = []
        # lines that have yet to be checked for prompts
        self.pending_lines = []
        # The current line that has not yet been completed with a terminating EOL
        self.incomplete_line = ''

    def _line_has_prompt(self, line):
        if line.startswith(self.hostname[:self.hostname_splice]):
            return True
        return False

    def _count_prompts(self):
        count = 0
        while len(self.pending_lines):
            line = self.pending_lines.pop(0)
            if self._line_has_prompt(line):
                count += 1
            self.completed_lines.append(line)
        return count

    def _process_output(self, output):
        output_lines = output.splitlines()

        # If the output starts with a new line, close out the incomplete line
        if output.startswith('\n'):
            output_lines.insert(0, self.incomplete_line)
            self.incomplete_line = ''

        if output_lines:
            # Concatenate the incomplete line with the first line in the output
            output_lines[0] = self.incomplete_line + output_lines[0]
            self.incomplete_line = ''

            # Consider the last line incomplete if the output does not end with a new line
            if not output.endswith('\n'):
                self.incomplete_line = output_lines.pop()

        self.pending_lines.extend(output_lines)

    def how_many_more_commands_can_be_sent(self, output):
        import time

        print(f"DEBUG CBA how_many_more_commands_can_be_sent output:\n{output}")
        print(f"DEBUG CBA how_many_more_commands_can_be_sent unacknowledged_commands {self.unacknowledged_commands}")
        self._process_output(output)
        number_or_prompts = self._count_prompts()

        # If we see at least one prompt, reset the timer, subtract from unacknowledged_commands
        if number_or_prompts:
            self.unacknowledged_commands -= min(number_or_prompts, self.unacknowledged_commands)
            self.timer = time.time()
        # If our timer has expired, acknowledge one command
        elif self.timer and time.time() - self.timer > self.timeout:
            if self.unacknowledged_commands:
                print(f"DEBUG CBA how_many_more_commands_can_be_sent expiring an unacknowledged_command")
                self.unacknowledged_commands -= 1
            self.timer = time.time()

        number_of_commands_to_send = self.chunk_size - self.unacknowledged_commands

        print(
            'DEBUG CBA how_many_more_commands_can_be_sent',
            len(self.completed_lines),
            len(self.pending_lines),
            self.incomplete_line,
            self.unacknowledged_commands,
            number_of_commands_to_send,
            number_or_prompts
        )
        self.unacknowledged_commands += number_of_commands_to_send
        return number_of_commands_to_send

    def all_output(self):
        return "\n".join(
            self.completed_lines +
            self.pending_lines
        ) + self.incomplete_line
```

In `netmiko/base_connection.py` under `send_config_set()` use it like this
```
commands = iter(config_commands)

cba = CommandBufferArbiter(hostname)
while True:
    done = False
    number_of_commands_to_send = cba.how_many_more_commands_can_be_sent(self.read_channel())

    for _ in range(number_of_commands_to_send):
        try:
            command = self.normalize_cmd(next(commands))
            print(f"Pushing: {command.strip()}")
            self.write_channel(command)
        except StopIteration:
            done = True
            break
        time.sleep(0.05)

    if done:
        break

    time.sleep(0.05)

output += cba.all_output()
```

**Comment by jtdub** [comment]
So, bumping up the delay_factor *can* work for this issue, however, it's difficult to know how long it's going to take a device to process commands, so that we can send them slow enough in some instances.

Doing something like @aedwardstx command buffer arbiter is more efficient in instances such as this.

**Comment by ktbyers** [comment]
Yes, I don't think I would integrate that into Netmiko. 

In other words, I think that input buffer control through counting should properly be outside of Netmiko. 

Here are the things that make me really reluctant to include it:
1. It would be very hard/impractical to know the input buffer sizing for various platforms.
2. The code adds a lot of complexity and I think there would probably be a lot of bugs/maintenance from it across time.
3. I don't think it is that common of a problem (at least that is my sense of it). I am open to hearing I am wrong on this, however.
4. I think there are other solutions that are reasonable including:
    a. Using file-based operations for large change sets (for example, SCP + config replace on IOS)
    b. Using the above-mentioned additional delay.
    c. Chunking your config changes outside of Netmiko and then waiting for the entire chunk to complete. Downside is this would be harder to do in something like Ansible (i.e. Netmiko being used in Ansible).

**Comment by aedwardstx** [comment]
I'll be monkey patching a more mature version of what I shared into our code base. Once done, I'll submit a PR so you can make a final decision. 

Addressing your points:
1. We don't need to know the buffer sizes, the `chunk_size` can be set to 10. This ensures that there are only 10 unacknowledged commands pending at a time.  
2. I'll be working out the kinks for IOS, NXOS, IOS-XR, and EOS which I imagine is the bulk of your user base. I'll be using this code to operate against 10,000+ devices. The entry point for this method could be separate `send_config_set_with_arbiter` as to not muddy the waters.
3. I think every network engineer has had the experience of pasting a large config too quickly and application of that config getting garbled or commands dropped. The lack of something intelligently pacing config commands sent impacted the application of an ACL on several devices in our environment. We frequently see cases where ACL entries are slow to apply since the device has to program TCAM on the fly. 
4.
    a. Appealing idea but `send_config_set` should still be a reliable method.
    b. The Arbiter method removes the need to constantly tune timers. Instead, it sends config as fast as possible and slows down automatically when it needs to.
    c. Netmiko `send_config_set` should be reliable for one shot configuration changes regardless of the size of the change set.

**Comment by ktbyers** [comment]
@aedwardstx Let me think about this a bit more...

**Comment by ktbyers** [comment]
Okay, I agree we should do a fix here, but I think the current proposed fix is significantly too complicated (which will likely cause me a lot of ongoing maintenance problems and related GitHub issues).

I will see if I can implement an alternative solution using arguments to send_config_set though it is probably not going to happen for at least a couple of weeks.

**Comment by aedwardstx** [comment]
@ktbyers Which aspect of the proposed change gives you the most pause? Is it the `CommandBufferArbiter` class or the separate send_config method `send_config_set_with_arbiter`? Maybe there is something I can do to simplify the solution in the meantime.

**Comment by ktbyers** [comment]
I got pretty tied up over the last couple of weeks. I will see if I can follow up some more on this issue over the next week.

**Comment by jcox-dev-99** [comment]
Good morning,

Did anything ever come of this issue?

**Comment by ktbyers** [comment]
It got put on the back-burner. I think we probably want to solve the underlying problem, but in a much simpler form (albeit slower).

**Comment by jcox-dev-99** [comment]
I understand. Is there anything underlying that would stop me from setting up multiple send_config_set commands back to back?

**Comment by ktbyers** [comment]
Nope. you could still run into a buffering issue  but you could put check in between your send_config_sets() to make sure the buffering has cleared.

**Comment by jcox-dev-99** [comment]
Awesome. Have you had any inconsistencies with ‘crypto key generate rsa general modulus 1024’ as a single command within send_config_set?

I’ve had some issues but I’m questioning now if that might have been buffer issues and I was chasing the wrong ghost.

**Comment by ktbyers** [comment]
@jcox-dev-99 I doubt `crypto key generate rsa general modulus 1024` is this issue. Can you maybe create a separate GitHub issue describing the problem you are running into?

**Comment by jcox-dev-99** [comment]
Yeah I really think I was overrunning the buffer and was chasing the crypto command because I knew it created a pause and could potentially create an error on the expect string. Hopefully I’ll get some time today to move my config sets into separate batches and that should tell the tale. If it turns out to be something else I’ll create a new issue. Thanks for the help!

**Comment by ktbyers** [comment]
Adding same comment here as I put on the PR #1085 

----------
I know this is not exactly what you were looking for, but we fixed this problem by essentially going to a command-buffer of one i.e. Netmiko won't write the next command in send_config_set until the last one has been properly echoed/handled by the device.

That fix is in the Netmiko develop branch and there is a modification to the behavior here:

#1447 

I need to make some slight changes to that PR1447 as I have hard-coded a terminating char '#' in there, but I will update that shortly.
