### ISSUE TITLE
CiscoSwitch config with opengear console server 

### ISSUE THREAD

**Issue by kashyappatel1988** [ktbyers/netmiko#1062]
HI All, 
I have an opengear console where a cisco switch is connected with console cable. I am able to send commands via Paramiko however Netmiko is having issue. Like all console it requires press return to get started ( enter keys before getting the device prompt).  Any one has experienced it before? 

Below is the code.   

console = {
'device_type': 'cisco_ios',
'host': '*********',
'username': 'root',
'password': ****,
'port' : 3019
}

connection = ConnectHandler(**console)
cmd1 = connection.send_command('\r')
print cmd1
cmd2 = connection.send_command('en')
print cmd2
cmd3 = connection.send_command('show version')
print cmd3
connection.disconnect()

here are errors i am getting 
Traceback (most recent call last):
  File "/Users/kaspatel/Documents/PythonScripts/switch-turnup/console-cisco-ssh.py", line 16, in <module>
    connection = ConnectHandler(**console)
  File "/Library/Python/2.7/site-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 271, in __init__
    self._try_session_preparation()
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 650, in _try_session_preparation
    self.session_preparation()
  File "/Library/Python/2.7/site-packages/netmiko/cisco/cisco_ios.py", line 16, in session_preparation
    self._test_channel_read(pattern=r'[>#]')
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 851, in _test_channel_read
    raise NetMikoTimeoutException("Timed out waiting for data")
netmiko.ssh_exception.NetMikoTimeoutException: Timed out waiting for data

**Comment by eoprede** [comment]
Here's how I am handling connecting to Fortinet FW via console server for initial provisioning (hence defaults passwords, etc):
```
SLEEP=1
def establish_connection(un, pw, host, ssh_config_file=None, fw_un='admin', fw_pw=''):
    net_connect = ConnectHandler(device_type="terminal_server",host=host,username=un,password=pw,ssh_config_file=ssh_config_file)
    time.sleep(SLEEP)
    net_connect.write_channel("\r")
    time.sleep(SLEEP)
    response = net_connect.read_channel()
    time.sleep(SLEEP)
    if "login:" in response:
        net_connect.write_channel(fw_un+"\r")
        time.sleep(SLEEP)
        response = net_connect.read_channel()
        time.sleep(SLEEP)
        if "Password:" in response:
            net_connect.write_channel(fw_pw+"\r")
            time.sleep(SLEEP)
            response = net_connect.read_channel()
    if "#" in response:
        print ('Connected')
        redispatch(net_connect, device_type='fortinet')
        return net_connect
    else:
        print ("Cound not connect")
        return None

```

**Comment by ktbyers** [comment]
@kashyappatel1988 The general solution for this type of problem in Netmiko is to use a device_type="terminal_server".

The terminal_server device_type does not do anything post SSH connection so your connection shouldn't break post SSH connection due to assumptions about the behavior.

And then to use the write_channel() and read_channel() methods to navigate the terminal server and to login to the end device.

After you are fully logged in to the end device, then use `redispatch` to switch the Netmiko class to the proper Netmiko class.

If you search on `redispatch` in the Netmiko issues, you should see examples of this pattern.

**Comment by kashyappatel1988** [comment]
thanks a lot @ktbyers and @eoprede ... device_type="terminal_server"  perfectly works for opengear console server.
