### ISSUE TITLE
Fail to recognize new prompt when connecting to ftd

### ISSUE THREAD

**Issue by c3101** [ktbyers/netmiko#1067]
When connecting to the ftd, the prompt changes from :
Firepower-module1>
to just a '>'

#code:
fw_con = ConnectHandler(device_type='autodetect', host=FirewallHostName, username=username, password=passwd)
output = fw_con.send_command("connect ftd")

produces this error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./nm.py", line 80, in ConnectToFirewall
    if not DoFTD(FirewallHostName):
  File "./nm.py", line 166, in DoFTD
    if Do4110(fw_con, FirewallHostName):
  File "./nm.py", line 257, in Do4110
    output = fw_con.send_command("connect ftd")
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 1188, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: Firepower\-module1\>

Output from a normal command line ssh session....

Password:
Last login: Wed Jan 16 11:05:19 SAST 2019 from xx.xx.xx.xx on pts/0

Copyright 2004-2018, Cisco and/or its affiliates. All rights reserved.
Cisco is a registered trademark of Cisco Systems, Inc.
All other trademarks are property of their respective owners.

Cisco Fire Linux OS v6.2.3 (build 13)
Cisco Firepower 4110 Threat Defense v6.2.3.3 (build 76)

Cisco Firepower Extensible Operating System (FX-OS) Software.
TAC support: http://www.cisco.com/tac

            Cisco Security Services Platform
                  Type ? for list of commands
   Firepower-module1>connect ftd
   Connecting to ftd console... enter exit to return to bootCLI
   \> system support diagnostic-cli
   Attaching to Diagnostic CLI ... Press 'Ctrl+a then d' to detach.
   Type help or '?' for a list of available commands.

Is there any work-around?? I _really_ need to get this going....
Kindly assist.

**Comment by daanvdsanden** [comment]
You can try the following: 
```python
output = fw_con.send_command("connect ftd", expect_string=r'^>\s*$')
```
Netmiko will than not look for the prompt, but for the regexp in the expect string.

**Comment by carlniger** [comment]
Closing this as @daanvdsanden solution should work nicely. Feel free to reopen if needed.
