### ISSUE TITLE
helo master ktbyer need help

### ISSUE THREAD

**Issue by fraedi** [ktbyers/netmiko#1069]
hello 

iam fraedi from indonesia
iam studying network programming, and now i have problem to push command in huawei switch using netmiko
can u help me?
this is the code :
from netmiko import ConnectHandler

huawei = {
    'device_type': 'huawei',
    'ip': '1.1.1.1',
    'username': 'xxx',
    'password': 'yyy',
    'port' : 22,            # optional, defaults to 22
	'timeout':10,			
    'secret': 'secret',     # optional, defaults to ''
    'verbose': False,       # optional, defaults to False
}

net_connect = ConnectHandler(**huawei)

ssh.enable()

config_commands = [ 'interface Ethernet0/0/4',
                    'description Test' ]

output1 = net_connect.send_config_set(config_commands)
print(output1)

and this is the output from CLI

[fraedi@terminal2 ~]# ssh xxx@1.1.1.1
xxx@1.1.1.1's password:

Info: The max number of VTY users is 5, and the number
      of current VTY users on line is 1.
<JATENG--HUAWEI.S2700-CPE-01>system-view
Enter system view, return user view with Ctrl+Z.
[JATENG--HUAWEI.S2700-CPE-01]interface Ethernet 0/0/4
[JATENG--HUAWEI.S2700-CPE-01-Ethernet0/0/4]description Test
[JATENG--HUAWEI.S2700-CPE-01-Ethernet0/0/4]quit
[JATENG--HUAWEI.S2700-CPE-01]quit
<JATENG--HUAWEI.S2700-CPE-01>exit

and this is the ouput error on server :
[cm@rancid cm]$ python2.7 test1.py
Traceback (most recent call last):
  File "isolir_netmiko_huawei.py", line 16, in <module>
    net_connect = ConnectHandler(**huawei)
  File "/usr/local/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/usr/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 743, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: huawei 1.1.1.1:22
[cm@rancid cm]$

thankyou 
Fraedi | IDN

**Comment by kafooo** [comment]
Your script cannot connect to 1.1.1.1 -> can you try to ssh to your router directly from machine where your script is?

**Comment by fraedi** [comment]
heloo kybyers

thanks, it solved after i add acl to this devices,
you're great!!

thank you
Fraedi | IDN

Pada tanggal Jum, 18 Jan 2019 pukul 15.52 kafooo <notifications@github.com>
menulis:
