### ISSUE TITLE
Exception while executing configure terminal related commands for mellanox switch.

### ISSUE THREAD

**Issue by govind-rathod1987** [ktbyers/netmiko#1074]
Exception while executing configure terminal related commands for mellanox switch.

when enabled the debug logs, found that the command to enter the "config terminal" of mellanox switch is partial and requires additional command to enter the "config terminal".
correct sequence of command after successful ssh to mellanox switch is:
1> enable
2> configure terminal
thus, the small change in "mellanox_ssh.py" code is required as below (#change required 1 and #change required 2):

    def config_mode(self, config_command='config term', pattern='#'):       
        #change required 1
          enter_enable = 'enable'
        """Enter into config_mode."""
        output = ''
        if not self.check_config_mode():
           #change required 2
            self.write_channel(self.normalize_cmd(enter_enable))
            self.write_channel(self.normalize_cmd(config_command))
            output = self.read_until_pattern(pattern=pattern)
            if not self.check_config_mode():
                raise ValueError("Failed to enter configuration mode.")
        return output
With this change the configure terminal relates command gets executed successfully.

added the debug logs for ssh test to mellanox switch  before and after code change.

[After_code_change.log](https://github.com/ktbyers/netmiko/files/2778756/After_code_change.log)
[Error_without_code_change.log](https://github.com/ktbyers/netmiko/files/2778757/Error_without_code_change.log)

**Comment by ktbyers** [comment]
@govind-rathod1987 Why not just call the .enable() method prior to calling the .config_mode() method?

**Comment by govind-rathod1987** [comment]
@ktbyers  that looks more modular, you can update the code with the suggested solution.
Im ok with it.

**Comment by ktbyers** [comment]
You would need to do this in your Python code. Netmiko assumes you are in enable mode when you execute the config_mode() method (so you would have to manually call .enable() if that is not the case).
