### ISSUE TITLE
TCPDump

### ISSUE THREAD

**Issue by maheshkudva** [ktbyers/netmiko#1078]
Hi

Firstly, this is not an issue but more of support request

I use netmiko in proxy mode. I connect to a jumpserver and then do ssh to the device. I can run any commands that give fixed output. How can I get tcpdump/packet capture to work? The data stream is continuous until its broken by a "ctrl+c". 

Theoretically the below should  work

`brkdmp = "False"`
`net_connect.write_channel("tcpdump -l -i eth1 src x.x.x.x \n") `
`while brkdmp == "False":`
` time.sleep(5)`
` print(net_connect.read_channel())`

How do we break since the console would be in actually in printing mode? How can we send a signal or a key back to the program setting the variable "brkdmp" to "True"?

**Comment by ktbyers** [comment]
You probably would send the same command down the SSH channel as you do when you are manually SSH'ing.

So given what you described above, you would need to send `cntr-c` down the SSH channel (i.e. using the write_channel() method.

Feel free to re-open if that doesn't work.
