### ISSUE TITLE
No Exception For Refused Connections

### ISSUE THREAD

**Issue by BigPat** [ktbyers/netmiko#1079]
Hello, I am working on a script that logs into a hostlist (also using threading) and then if the connection fails then I have it build a new hostlist to utilize a jump box/proxy server to try again.  In my environment we have ACLs in place on **line vty** that prevent access for devices on certain networks.  

When my first attempt to SSH to the device fails it gives the exception seen below:
`Connection   to device timed-out: cisco_nxos 10.10.10.10:22`

However, when I try to manually login to the device via SSH it give the following error: 
`The remote system refused the connection.`

Is there any way that you can add this as an exception to the ConnectHandler  on a future update?  

I work in a big environment and I skipped fixing the ACLs on these devices thinking they were decommissioned or refreshed and now people cant login.

**Comment by ktbyers** [comment]
Feel free to create a PR on it. I suspect this is probably pretty hard to do, however.

**Comment by petermcd** [comment]
This is actually quite easy, PR coming

**Comment by MikeJurecki** [comment]
@petermcd thank you for reaching out I look forward to seeing the PR.
