### ISSUE TITLE
Fix Netmiko setup.py such that it works properly with Poetry

### ISSUE THREAD

**Issue by dmfigol** [ktbyers/netmiko#1081]
I've encountered the following problem when installing `netmiko` via `poetry`:
https://github.com/sdispater/poetry/issues/844

While it seems it is a poetry resolver problem, I also think it is possible to resolve this on `netmiko` side:
enum34 is not compatible with python 3.4+, but there is package `enum-compat` https://github.com/jstasiak/enum-compat which takes care of this difference

The problem manifests itself when some other library uses incompatible changes in `enum` module, for example `aiohttp`

**Comment by ktbyers** [comment]
Here is what I have in the Netmiko setup.py:

```
if sys.version_info < (3,):
    requirements.append("enum34")
    requirements.append("ipaddress")
```

It looks like enum-compat is just a wrapper library which installs enum34 for older versions of Python. 

Have you tested enum-compat with poetry? 

It looks like enum-compat uses essentially the same pattern that I have in Netmiko (i.e. simple logic that causes install_requires to be modified based on the Python version).

https://github.com/jstasiak/enum-compat/blob/master/setup.py

**Comment by ktbyers** [comment]
I think using Environment Markers will also imply that Netmiko can no longer build a universal wheel (one that supports Python2 and Python3) so I will have to build a wheel for each Python version.

**Comment by dmfigol** [comment]
> Have you tested enum-compat with poetry?

I've just tested it. It will not work unfortunately.
```
-> % poetry add enum-compat
Using version ^0.0.2 for enum-compat

Updating dependencies
Resolving dependencies... (0.7s)


Package operations: 2 installs, 0 updates, 0 removals

Writing lock file

  - Installing enum34 (1.1.6)
  - Installing enum-compat (0.0.2)
```

>I think using Environment Markers will also imply that Netmiko can no longer build a universal wheel (one that supports Python2 and Python3) so I will have to build a wheel for each Python version.

I am not 100% sure as I can't find all internal details how env markers work. My understanding is that it would still be a single wheel, but markers would propagate to the wheel metadata

By the way, have you considered getting rid of `enum34` completely? If I examined netmiko codebase correctly, `enum` is not `netmiko` dependency, but is included just to make `cryptography` work for some old versions, so what it really means is that it is upstream's `cryptography` job to fix it.

**Comment by ktbyers** [comment]
@dmfigol Good point, I need to look at the history of Netmiko-enum34 and determine whether it is still needed or not. 

Regardless though I will have to fix the environment marker issue...as the ipaddress library also needs to be installed for Python27 only.

**Comment by carlmontanari** [comment]
I think this may be a resolved issue for the develop branch due to the move to 3.6+ only or now that I'm thinking about it there was probably an update to poetry. In any case I just created a new poetry project and listed netmiko as a dependency and ran `poetry install` and it installed netmiko 2.4.2 successfully! So I'll close this for now, but we can re-open if I missed something.
