### ISSUE TITLE
Best way to capture errors when using send_config_set

### ISSUE THREAD

**Issue by rohitchormale** [ktbyers/netmiko#1084]
Hi, I have just started to use netmiko and would like to thank all contributors for such good project. 

Recently I faced a below issue. 

Suppose I am sending multiple config commands using send_config_set and few intermediate commands fail, is there a way to abort successive commands ? or just parse whole output on my end somehow ? (may be using something like textfsm) or any better alternative ?

**Comment by ktbyers** [comment]
You could issue some set of commands and then check what happens. From this make decisions to execute additional commands.

```python
output = net_connect.send_config_set(cmds)
if '% invalid command' in output:
    raise ValueError()
# the send more commands
```

send_config_set doesn't have any checking in the middle. That could possibly be an interesting idea to implement (i.e. some search pattern that would be looked for after each config command). But that doesn't currently exist.

You can parse the output that comes back using Python Regex or TextFSM. Probably Python Regex would make more sense here, but you could do either.

**Comment by rohitchormale** [comment]
@ktbyers sounds good. if possible, will send PR soon.

**Comment by carlniger** [comment]
Going to close this and continue any conversation in #1241 Chime in over there with any feedback!
