### ISSUE TITLE
send_command output first character truncated? HPE switches

### ISSUE THREAD

**Issue by fleemiko** [ktbyers/netmiko#1086]
not sure if this is similar to the one with Truncated Output #232..

I have the following code:
hostname = sw
sw = {'device_type': 'hp_procurve', 'ip': sw, 'username': USER, 'password': PASSWORD, 'verbose': False, }
ssh_session = ConnectHandler(**sw)
output = ssh_session.send_command_expect("show ver", expect_string=None)
output += ssh_session.send_command_expect("show time")
print (hostname, output, sep='\n')

the output I got:

192.168.168.5
Image stamp:    /ws/swbuildm/rel_xanadu_zeus_qaoff/code/build/bom(swbuildm_rel_xanadu_zeus_qaoff_rel_xanadu_zeus)
                Sep  5 2018 11:58:53
                KB.16.07.0002
                264
Boot Image:     Primary

Boot ROM Version:    KB.16.01.0008
Active Boot ROM:     Primary
hu Jan 31 13:14:55 2019

note that the first character of "sh time" was truncated... it should read "Thu"...  I tried with send_command_expect but the issue persist. Is this still an issue with short-running command?

or, am I missing something?

Thanks!!!

**Comment by ktbyers** [comment]
Can you print out repr(output)?

```
print(repr(output))
```

And post what you see to here.

**Comment by carlniger** [comment]
Going to close and continue this in #1135
