### ISSUE TITLE
TextFSM relative path not supported for NET_TEXTFSM

### ISSUE THREAD

**Issue by robobeaver6** [ktbyers/netmiko#1089]
I have an environment variable set to the index path  
```python
os.environ["NET_TEXTFSM"] = "lib/ntc-templates/templates"
```
netmiko/utilities.py sets the index_file variable as the path from the environment variable joined to 'index'
```python
def get_structured_data(raw_output, platform, command):
    """Convert raw CLI output to structured data using TextFSM template."""
    template_dir = get_template_dir()
    index_file = os.path.join(template_dir, 'index')
    textfsm_obj = clitable.CliTable(index_file, template_dir)
```

netmiko/_textfsm/_clitable.py then joins the template_dir and the index_file (which already has the full path), resulting in an incorrect path.  
```
fullpath = os.path.join(self.template_dir, self.index_file)
```
The final path is `'lib/ntc-templates/templates/lib/ntc-templates/templates/index'`
which is incorrect, due to the directory being joined twice. 

This is netmiko  v2.3.0

**Comment by ktbyers** [comment]
Okay, strange. I would have thought I tested this...but let me review it.

**Comment by robobeaver6** [comment]
if it is of any use, I was calling Netmiko from Nornir using the following command:
```python
table_advertised_routes = task.run(task=netmiko_send_command,
                                                   name=f'Get Recieved Routes from {task.host} - {peer_ip}',
                                                   command_string=command,
                                                   use_textfsm=True,
                                                   severity_level=logging.DEBUG)
```

**Comment by ktbyers** [comment]
Okay, probably in the interim you will need to install ntc-templates into your home directory as Netmiko will by default search there. I will then need to fix the environment variable issue.

Thanks for reporting this.

**Comment by robobeaver6** [comment]
I hust changed netmiko/utilities.py line 234 so index_file didn't join to the template_dir:
```python
def get_structured_data(raw_output, platform, command):
    """Convert raw CLI output to structured data using TextFSM template."""
    template_dir = get_template_dir()
    # index_file = os.path.join(template_dir, 'index')
    index_file = 'index'
```
This seemed to work fine in the interim.  Not sure if it breaks anything else, but it is working for me.

**Comment by ktbyers** [comment]
@robobeaver6 I dug into this some more, the issue is you need to use an absolute path and not a relative path here:

```
os.environ["NET_TEXTFSM"] = "lib/ntc-templates/templates"
```


os.path.join works fine if you use an absolute.

```
>>> import os
>>> os.path.join('/Users/ktbyers/ntc-templates/templates/', '/Users/ktbyers/ntc-templates/templates/index')
'/Users/ktbyers/ntc-templates/templates/index'
```

relative paths are not supported here. I don't think we would want to support them, but I am open to arguments to the contrary.

You could say it is still a bug here in that possibly wasn't what was originally intended with the code (not sure I see any negative consequences to it except that we should raise an exception on a relative path).

For (my) future reference os.path.join with the last element as an absolute path will just use that last element (and drop everything else). Since in this case the index_file is an absolute path to the index file, it will just get used (in the call to CliTable).

**Comment by robobeaver6** [comment]
Thanks for the update.  The primary reason I am using relative path, is that the templates are installed with the Nornir scripts.  We have several users that will install it from git, and I can not predict the location that they will be run from, hence relative to the project folder.

**Comment by ktbyers** [comment]
So you are expecting to look for ntc-templates relative to the directory you are running the Python program from?

So in your case:

```
"lib/ntc-templates/templates"
```

You have some directory like the following?

```
.
./my_python_program.py
./lib/ntc-templates/templates
```

Just want to make sure I understand your setup.

**Comment by robobeaver6** [comment]
Yes, that is correct.  The templates are distributed with the program, because they are not the standard ones.

**Comment by ktbyers** [comment]
Sounds good...that makes sense. We should update this so that a relative path would work. We will also need to add this into the unit tests.
