### ISSUE TITLE
ip vs host in BaseSSHConnection

### ISSUE THREAD

**Issue by ogenstad** [ktbyers/netmiko#109]
While it might break stuff wouldn't it make more sense to use host instead of ip to set the target device in BaseSSHConnection?

Perhaps keeping ip as a named argument which can be deprecated later.

**Comment by ktbyers** [comment]
@ogenstad The 'ip' field should work with both an ip address and a hostname (although I agree its naming is confusing).

One possible solution would be to add a new supported field (hostname) and then check first for 'ip' and if 'ip' is not used check for 'hostname'. This would not break current code and would make the naming cleaner.

**Comment by ogenstad** [comment]
Yes that makes sense.

**Comment by ktbyers** [comment]
This is fixed 6165484177b626cb370b6d04c1351e620d1e65de

Can use either host or ip to create a Netmiko connection object.
