### ISSUE TITLE
 Request to modify condition: .netmiko.yml to be located in either your home directory or your current working directory

### ISSUE THREAD

**Issue by kalmanoharan** [ktbyers/netmiko#1092]
Current requirement specified is that .netmiko.yml file must be in the current directory or in your home directory.

Is there a way to hardcode .netmiko.yml file location in the script similar changing to os.environ['NETMIKO_DIR'] ?

Because its going to be hard to keep a copy of .netmiko.yml for all my team mates home directory.

========================
 Kirk Byers about 20 hours ago 
Yes, the current Netmiko/Netmiko-tools requires .netmiko.yml to be located in either your home directory or your current working directory.

In order to change that you would probably have to make a change in netmiko/utilities.py.

I am open to some sort of a PR or GitHub discussion on the issue, but that is the way it works currently.

Regards, Kirk

=========

**Comment by carlniger** [comment]
see #1258, closing
