### ISSUE TITLE
Cisco ASA: Key-based auth causes login loop

### ISSUE THREAD

**Issue by inflatador** [ktbyers/netmiko#1093]
netmiko==2.3.0
paramiko==2.4.2
both installed via pip

I'm running into an issue where netmiko logs in successfully to the ASA with SSH keys, but doesn't seem to realize that it's logged in successfully, and issues a "login" command, which leads to an endless loop of login prompts.

```DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: User rack logged in to aanetmiko00
Logins over the last 2 days: 38.  Last login: 23:17:50 UTC Feb 12 2019 from 1.2.3.4
Failed logins since the last login: 0.  Last failed login: 22:20:08 UTC Feb 12 2019 from 1.2.3.4
Type help or '?' for a list of available commands.
aanetmiko00>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
aanetmiko00>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'login\n'
DEBUG:netmiko:read_channel: login
Username:
DEBUG:netmiko:write_channel: b'rack\n'
DEBUG:netmiko:read_channel: rack
Password:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
%Login failed
Username:
DEBUG:netmiko:write_channel: b'rack\n'
DEBUG:netmiko:read_channel: rack
Password:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
%Login failed
 ```

Example code:

```

# ASA key-based auth, does not work
	my_asav = {
				"host": hostname,
				"username": username, 
				"device_type": "cisco_asa",
				"allow_agent": False,
				"use_keys": True,
				"key_file": "/home/rack/.ssh/id_rsa"
			  }


# ASA password auth, works

# 	my_asav = {
# 				"host": hostname,
# 				"username": username,
# 				"password": password,
# 				"device_type": "cisco_asa",
# 				"allow_agent": False,
# 				"use_keys": False
# 			  }


# Linux SSH-based auth, works 
# 	my_asav = {
# 				"host": hostname,
# 				"username": username, 
# 				"allow_agent": False,
# 				"use_keys": True,
# 				"key_file": "/home/rack/.ssh/id_rsa",
# 				"device_type": "linux"
# 			  }
# 
```

**Comment by daanvdsanden** [comment]
The ASA device-type assumes that you want to go into privilige mode by either a login or enable secret and checks if the prompt ends with a '#' ([This link briefly describes the option to get into priviliged mode](https://serverfault.com/a/335346)). So you either need to provide the password for the user rack (looking at the logs an empty password is incorrect) or provide and/or configure an enable secret.
If you do not want to go into privilige mode to execute commands the code needs a small update.

**Comment by inflatador** [comment]
@daanvdsanden  thanks, that is every interesting. Is there maybe a way to tell netmiko to go into enable mode (assuming no password to go into enable mode) instead of issuing the login command?
```asav_connect.enable()``` doesn't seem to work.

**Comment by ktbyers** [comment]
So your enable secret is an empty string...just to verify?

We have an issue in that case. 

The issue is that the 'secret' in Netmiko defaults to an empty string. For the ASA driver we check if the secret is not set (which means an empty string).

If that is the case, then we try to use `login`.

```
    def session_preparation(self):
        """Prepare the session after the connection has been established."""
        self._test_channel_read()
        self.set_base_prompt()
        if self.secret:
            self.enable()
        else:
            self.asa_login()
```

It would work for a non-null secret, but an empty secret where you want to go into enable is a problem.

This issue is a bit coupled with that the ASA generally requires higher privileges to change terminal characteristics (so not elevating privileges automatically is also an issue).

**Comment by daanvdsanden** [comment]
Just set the correct secret. If the enable secret is empty in your asa config, you could also try to assign the value "\n" to the secret. This  will evaluate to true in above if statement. And should flow through the rest of the code without problems. Not sure if this is the most secure way of working.

**Comment by inflatador** [comment]
@ktbyers confirming that the enable secret is an empty string.

@daanvdsanden  Thanks for the workaround, and understood about security concerns. I am coming from a Linux background, thinking in terms of "sudo -i" for a sudoer. 
I'll try setting the secret as "\n" and see if I can get it to work that way. If it does, I'm fine with closing this issue out. Will update as soon as I can.

**Comment by ktbyers** [comment]
@inflatador Yes, there is a good chance setting the secret argumet in Netmiko to `\n` will work...let us know if that works and fixes your issue.

```
# ASA key-based auth, does not work
	my_asav = {
				"host": hostname,
				"username": username, 
				"device_type": "cisco_asa",
				"allow_agent": False,
				"use_keys": True,
				"key_file": "/home/rack/.ssh/id_rsa",
                                 "secret": "\n",
			  }
```

**Comment by inflatador** [comment]
@ktbyers I can confirm that setting "secret" to "\n" works around the issue. Thanks again for your prompt attention, it is very much appreciated.
