### ISSUE TITLE
cisco_tp_tcce.py does not handle VCS xcommands well

### ISSUE THREAD

**Issue by jgiambo** [ktbyers/netmiko#1094]
When Attempting to create and administrator group on Cisco VCS the output of Cisco VCS is not expected by netmiko.  

xCommand AdminGroupAdd Name: "Administrators" AccessAPI: On AccessWeb: On Enabled: On

*r Result (status=OK)
     ID: 2
*r/end

I successfully addressed this by adding 
expect_string = r'^(\*r\/end|OK|ERROR|Command not recognized\.)$' on line 55 

expect_string = r'(\*r\/end|OK|ERROR|Command not recognized\.)' on line 82.  

No PR as honestly this is my first day trying to use netmiko so im not sure I fully grasp what is happening here but it worked so good enough for me.

**Comment by carlniger** [comment]
@jgiambo thanks for documenting here. If this is something you need we're open to PRs. If you do create a PR please include running the test suite and some output from a real device in the comments!
