### ISSUE TITLE
Inconsistent calculation of max_loops in base_connection.py?

### ISSUE THREAD

**Issue by sulisu** [ktbyers/netmiko#1097]
In the current develop branch, base_connection.py
The first max_loops has no int, while the second one has. Is it inconsistent?

```
    def _read_channel_expect(self, pattern="", re_flags=0, max_loops=150):
        if max_loops == 150:
            max_loops = self.timeout / loop_delay

    def _read_channel_timing(self, delay_factor=1, max_loops=150):
        if delay_factor == 1 and max_loops == 150:
            max_loops = int(self.timeout / loop_delay)
```

**Comment by carlniger** [comment]
@sulisu good eye. I'm assuming this didn't impact anything for you? if it did, let us know. otherwise ill get this into a pr this week to ensure consistency.
