### ISSUE TITLE
Test channel read and pattern behavior not expected

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1098]
https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L919

This looks like a bug:

```
        while i <= count:
            new_data += self._read_channel_timing()
            if new_data and pattern:
                if re.search(pattern, new_data):
                    break
            elif new_data:
                break
```

If you have pattern set you break when pattern is detected, but then you break if there is any new_data whatsoever.

**Comment by daanvdsanden** [comment]
Looks ok to me. When there is a pattern set it will loop until the pattern is found in the new_data variable (it can take multiple loops before the pattern is added to the new data variable.). If no pattern is set the loop breaks at the moment data is read.

**Comment by ktbyers** [comment]
Yes, you are right I misread it...I had in my head it was an independent if clause instead of an elif.
