### ISSUE TITLE
Naming convention for netmiko.ssh_dispatcher.CLASS_MAPPER

### ISSUE THREAD

**Issue by ogenstad** [ktbyers/netmiko#110]
Are there any thoughts on naming conventions for the platforms used? Most of them are using [vendor]_[os], but the Cisco WLC adds _ssh while Huawei and Juniper just uses the vendor and not the os.

**Comment by ktbyers** [comment]
Yes, it should be vendor_platform(os).

I will probably just add the additional keys to make it more consistent (i.e. cisco_wlc, juniper_junos, etc.). I will still leave the old keys so as not to break existing code.

**Comment by ktbyers** [comment]
Huawei needs platform name.
a10 needs platform name.
linux has no platform name.
enterasys
extreme
fortinet.

**Comment by ktbyers** [comment]
I am not actively working on this. If someone else wants to suggest improvements or implement improvements I am open to it.
