### ISSUE TITLE
No prompt after reload

### ISSUE THREAD

**Issue by TheScriptKid** [ktbyers/netmiko#1101]
Hello together,

I'm stucking in a problem, where I need some help:

My project is about deleting the config of an IOS device and reloading for getting it back to factory default config. Unfortunately, after the reload, I'm struggling getting the commands to the device. I can still push the "no" after the reload with the prompt of the configuration dialog, but after that, the script can't get the prompt and thus there is no push of further commands possible. 

A workaround is disconnecting and connecting back to the device, but I think, that you can solve that problem better. Here is my script:

```
#!/usr/bin/env python

from netmiko import ConnectHandler
from datetime import datetime
import time

device = {
    'device_type': 'cisco_ios_telnet',
# changes terminal length to '0' and terminal width to '511'
    'ip': 'x.x.x.x',
# 'username': 'pyclass',
# 'password': getpass(),
    'port': 23
}

# Object for measuring time executing script
start_time = datetime.now()

time.sleep(100)
net_connect = ConnectHandler(**device)

# Just deleted the part of erasing the config 

# Step 3 - Configure device after reload
# Pushing 'no' after the question of the configuration dialogue
output_initialization = net_connect.send_command_timing('\nno\n', strip_command=False, strip_prompt=False)
# Another time.sleep for additional trailing prompt
time.sleep(150)

############### There it starts to fail####################
get_prompt = net_connect.set_base_prompt()
# Get into real prompt
output_real_prompt = net_connect.send_command('\n\n\n')
print("Device configured")

# Stopping time measuring for script
end_time = datetime.now()

# Output time needed for executing script
print("Total time: {}".format(end_time - start_time))

# Disconnect from device
net_connect.disconnect()

```
Thank you in advance!

**Comment by ktbyers** [comment]
I am not understanding your question/issue? Can you re-phrase what you are stuck on?

You will need to re-connect using ConnectHandler after the reload (unless you are connecting via a terminal server or something else that maintains the connection).

**Comment by carlniger** [comment]
@TheScriptKid I think @ktbyers comments here address this so I'm going to close this issue. Feel free to re-open and restate the issue if its still a problem for you.
