### ISSUE TITLE
Taking action depending on the command in send_config_set(config_commands)

### ISSUE THREAD

**Issue by vinaypillutla** [ktbyers/netmiko#1103]
Is there any way to check for a particular command in send_config_set(config_commands) and take action depending on what the command is?

For e.g. If the command in send_config_set(config_commands) is a reload command, after the command is executed, I would want my Python script to sleep for a few seconds(time.sleep) and establish a new connection to the target machine and then continue with the remaining commands in send_config_set(config_commands).

**Comment by OzNetNerd** [comment]
I don't think that's possible. Another approach would be to:

1. use `send_config_set` to send multiple commands.
2. Send the `reload` command separately.
3. Sleep.
4. Use `send_config_set` to send multiple commands.

**Comment by ktbyers** [comment]
Yes, I think you would want to do what @OzNetNerd outlined above.

I would probably use `send_command_timing()` to send the `reload` command. After the reload command you will then need to wait the reload time and then setup a new Netmiko connection.

At that point, you could continue with additional `send_config_set` commands.

**Comment by vinaypillutla** [comment]
Okay. Thanks a lot!
