### ISSUE TITLE
Add the ability login to a device from a console server

### ISSUE THREAD

**Issue by tybruno** [ktbyers/netmiko#1104]
Currently, there will be a timeout when trying too login to a device (ios) with an enable password from a console server using netmiko. I am aware that using the 'terminal_server' device_type and `redispatch()` can fix this problem. However, this is an issue when using Napalm. Is there any other solutions that work with Napalm?

**Comment by carlniger** [comment]
@tybruno AFAIK this isn't possible with Napalm, see [this issue](https://github.com/napalm-automation/napalm/issues/682). As you mentioned you can of course do this with Netmiko via `redispatch` you should also be able to do this in Nornir with the Netmiko connection plugin.

**Comment by ktbyers** [comment]
Yes, NAPALM doesn't support that use case. You could probably write some glue code for NAPALM to make it work, but you would have to write that glue code.

**Comment by carlniger** [comment]
inactive. closing. feel free to reopen if there needs to be further discussion!
