### ISSUE TITLE
ImportError: No module named Netmiko on MAC

### ISSUE THREAD

**Issue by magic9669** [ktbyers/netmiko#1109]
I'm using a MAC which comes with Python2.7.  I installed Python3 but I Cannot import Netmiko for some reason.  I tried following some other suggestions on here but no luck.  I get the following:

>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'netmiko'

Any assistance would be appreciated.  Thanks.

**Comment by ktbyers** [comment]
I would probably try `python3 -m pip install netmiko`


Kirk

**Comment by magic9669** [comment]
Hmmm.  Seemed like that installed but still getting the same error unfortunately.

**Comment by magic9669** [comment]
Even more interesting.  When I run it with python3 or python3.7, it works.  When I run it with python2 or python2.7, it works.  If I were to just type python, that's where I now get the error.  My default version is 2.7.10

**Comment by c-hill1** [comment]
For your shebang line, specify python 3

**Comment by ktbyers** [comment]
Okay, it sounds like the issue here is just a Python issue i.e. you are installing the library into one Python, but using the other Python.

The standard solution for this is virtual environments. There should be lots of resources regarding this online.
