### ISSUE TITLE
netmiko connection to multiple switches

### ISSUE THREAD

**Issue by mkazam** [ktbyers/netmiko#1111]
Can you please advise if there is something wrong with the below config, i can SSH to both switches but the script only works on switch b?
If this is not the right place to post this type of issue, just let me know where instead.
Thank you, MK

#!/usr/bin/env python

from netmiko import ConnectHandler

stack_a = {
    'device_type': 'cisco_ios',
    'ip': '1.1.1.1',
    'username': 'admin',
    'password': 'cisco',
}

stack_b = {
    'device_type': 'cisco_ios',
    'ip': '1.1.1.2',
    'username': 'admin',
    'password': 'cisco',
}

with open('switch_cmds_1') as f:
    lines = f.read().splitlines()
print lines

all_devices = [stack_a, stack_b]

for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    output = net_connect.send_config_set(lines)
print output

**Comment by OzNetNerd** [comment]
What do you mean it only works on switch b? Do you get an error when it runs against switch a? If so, can you please provide the relevant output?

**Comment by mkazam** [comment]
Hi, no errors, just seems to ignore switch a, see output below for sw 1.1.1.2- some details change for privacy: i know im using the set config cmd for show cmds, just learning at the moment.
kabir@ecl-vm-kabir:~$ python python4.py 
['do sh version | i Version', 'do  sh ip int br | ex una']
config term
Enter configuration commands, one per line.  End with CNTL/Z.
ABCD(config)#do sh version | i Version
Cisco IOS Software [Denali], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.3.3, RELEASE SOFTWARE (fc3)
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
GPL code under the terms of GPL Version 2.0.  For more details, see the
BOOTLDR: CAT3K_CAA Boot Loader (CAT3K_CAA-HBOOT-M) Version 3.56, RELEASE SOFTWARE (P)
Switch Ports Model              SW Version        SW Image              Mode   
ABCD(config)#do  sh ip int br | ex una
Interface              IP-Address      OK? Method Status                Protocol
Vlanx                     x.x.x.x      YES NVRAM  up                    up

**Comment by mkazam** [comment]
If I change to output = net_connect.send_config_from_file(lines)
I get the folowing error:
kabir@ecl-vm-kabir:~$ python python9.py  
[' sh version | i Version', '  sh ip int br | ex una']
Traceback (most recent call last):
  File "python9.py", line 27, in <module>
    output = net_connect.send_config_from_file(lines)
  File "/home/kabir/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 1383, in send_config_from_file
    with io.open(config_file, "rt", encoding='utf-8') as cfg_file:
TypeError: invalid file: [' sh version | i Version', '  sh ip int br | ex una']

If I try net_connect.send_command(lines), I get this error:
kabir@ecl-vm-kabir:~$ python python9.py
[' sh version | i Version', '  sh ip int br | ex una']
Traceback (most recent call last):
  File "python9.py", line 27, in <module>
    output = net_connect.send_command(lines)
  File "/home/kabir/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 1149, in send_command
    command_string = self.normalize_cmd(command_string)
  File "/home/kabir/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 1261, in normalize_cmd
    command = command.rstrip()
AttributeError: 'list' object has no attribute 'rstrip'

**Comment by OzNetNerd** [comment]
I understand you're learning at the moment, but you need to get into the habit of reading the error messages carefully :)

In regards to the first error:

```
with io.open(config_file, "rt", encoding='utf-8') as cfg_file:
TypeError: invalid file: [' sh version | i Version', ' sh ip int br | ex una']
```
You're passing in the _filename_ `[' sh version | i Version', ' sh ip int br | ex una']`. I believe your filename is actually `switch_cmds_1`.

In regards to the second error:

```
AttributeError: 'list' object has no attribute 'rstrip'
```

The error stating that it has received a `list`. However, `send_command` requires a string.

In regards to the script ignoring switch A - that's not possible. Something has to happen. e.g If Netmiko cannot reach it, you'd get a `Timeout Exception`. If Netmiko could reach it, then you'd get output similar to what you're seeing for Switch B.

**Comment by mkazam** [comment]
Hi Will,
Thank you, I appreciate the comments, I think I will come back to that particular script when I have more knowledge, I managed to come up with a workaround for now, as below:

for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    output = net_connect.send_command('sh ip int br | ex una')
    print output
    output = net_connect.send_command("show run | inc logging")
    print output
Regards, mk

**Comment by mkazam** [comment]
resolution as above.

**Comment by OzNetNerd** [comment]
I'm glad to hear you were able to resolve the issue @mkazam. Please feel free to drop me a message or tag me if you need any more assistance. I'm happy to help.
