### ISSUE TITLE
Netmiko dictionary object for device type problem

### ISSUE THREAD

**Issue by hokay89** [ktbyers/netmiko#1112]
I've been working with David Bombal's GNS3 academy course where we're incorporating multithreading and threadpools for use with netmiko. The script for the most part works great and greatly improves the efficiency by connecting to multiple devices at once rather than sequentially.

The script however seems to have one flaw that the course claims it is in fact capable of doing. That is determining device type based on information extracted from a device file, and using that information to make connections by passing the appropriate device type dispatcher and running specific commands for that device.

After doing a lot of testing it seems that this script actually does not work with multiple device types. Even though we have the if / elif statements in there for different devices, the script just defaults to cisco_ios every time. I discovered this when i was testing the script and tried to add the cisco_asa deivce. This script is treating everything as cisco_ios.

I was able to successfully use the script on my asa when i set the default else: to cisco_asa, or remove all the if statements entirely and just do device_type='cisco_asa' Without doing that, when the script connects to the asa it seemingly works, however when you look at the output file you get this: ERROR: % Invalid input detected at '^' marker. Which indicates that the script is inserting a command into the enable prompt. If it was truly using the correct device_type as it does when you define the default as cisco_asa it would enter the secret in the enable prompt and then pass the command.

Sorry about the novel here. Any assistance would be greatly appreciated. I am very new to python and using it to automate some of my daily tasks at work has helped a lot. THANK YOU

from simplecrypt import decrypt
from pprint import pprint
from netmiko import ConnectHandler
import json
from time import time

from multiprocessing.dummy import Pool as ThreadPool

#------------------------------------------------------------------------------
def read_devices( devices_filename ):

    devices = {}  # create our dictionary for storing devices and their info

    with open( devices_filename ) as devices_file:

        for device_line in devices_file:

            device_info = device_line.strip().split(',')  #extract device info from line

            device = {'ipaddr': device_info[0],
                      'type':   device_info[1],
                      'name':   device_info[2]}  # create dictionary of device objects ...

            devices[device['ipaddr']] = device  # store our device in the devices dictionary
                                                # note the key for devices dictionary entries is ipaddr

    print ('\n----- devices --------------------------')
    pprint( devices )

    return devices

#------------------------------------------------------------------------------
def read_device_creds( device_creds_filename, key ):

    print ('\n... getting credentials ...\n')
    with open( device_creds_filename, 'rb') as device_creds_file:
        device_creds_json = decrypt( key, device_creds_file.read() )

    device_creds_list = json.loads( device_creds_json.decode('utf-8'))

    # convert to dictionary of lists using dictionary comprehension
    device_creds = { dev[0]:dev for dev in device_creds_list }

    return device_creds

#------------------------------------------------------------------------------
def config_worker( device_and_creds ):

    # For threadpool library we had to pass only one argument, so extract the two
    # pieces (device and creds) out of the one tuple passed.
    device = device_and_creds[0]
    creds  = device_and_creds[1]
	
	
    if   device['type'] == 'junos-srx': device_type = 'juniper'
    elif device['type'] == 'cisco-ios': device_type = 'cisco_ios'
    elif device['type'] == 'cisco-xr':  device_type = 'cisco_xr'
    elif device['type'] == 'cisco-asa':  device_type = 'cisco_asa'
    else:                               device_type = 'cisco_ios'    # attempt Cisco IOS as default

    print ('---- Connecting to device: {0}'.format(device['ipaddr']))
	
    session = ConnectHandler( device_type=device_type, ip=device['ipaddr'], 
														username=creds[1], password=creds[2], secret=creds[2] )

    #session = ConnectHandler( device_type=device_type, ip='172.16.0.1',  # Faking out IP address for now
    #                                                   username=creds[1], password=creds[2] )

    if device_type == 'juniper':
        #---- Use CLI command to get configuration data from device
        print ('---- Getting configuration from device')
        session.send_command('configure terminal')
        config_data = session.send_command('show configuration')
		
    if device_type == 'cisco_asa':
        #---- Use CLI command to get configuration data from device
        print ('---- Getting configuration from device')
        config_data = session.send_command('show run')

    if device_type == 'cisco_ios':
        #---- Use CLI command to get configuration data from device
        print ('---- Getting configuration from device')
        config_data = session.send_command('show run')
   

    if device_type == 'cisco_xr':
        #---- Use CLI command to get configuration data from device
        print ('---- Getting configuration from device')
        config_data = session.send_command('show configuration running-config')

    #---- Write out configuration information to file
    config_filename = 'config-' + device['ipaddr']  # Important - create unique configuration file name

    print ('---- Writing configuration: ', config_filename)
    with open( config_filename, 'w' ) as config_out:  config_out.write( config_data )

    session.disconnect()

    return

#==============================================================================
# ---- Main: Get Configuration
#==============================================================================

devices = read_devices( 'devices-file' )
creds   = read_device_creds( 'encrypted-device-creds', 'cisco' )

num_threads_str = input( '\nNumber of threads (5): ' ) or '5'
num_threads     = int( num_threads_str )

#---- Create list for passing to config worker
config_params_list = []
for ipaddr,device in devices.items():
   config_params_list.append( ( device, creds[ipaddr] ) )

starting_time = time()

print ('\n--- Creating threadpool, launching get config threads\n')
threads = ThreadPool( num_threads )
results = threads.map( config_worker, config_params_list )

threads.close()
threads.join()

print ('\n---- End get config threadpool, elapsed time=', time()-starting_time)

**Comment by OzNetNerd** [comment]
I haven't had a chance to go through your code yet, but FYI - you'd likely be better off using [ssh_autodetect](https://github.com/ktbyers/netmiko/blob/develop/netmiko/ssh_autodetect.py) or [NAPALM](https://github.com/napalm-automation/napalm).

**Comment by ktbyers** [comment]
@hokay89 I am just going to close this issue; I don't think there is a Netmiko issue here. 

I can possibly see if you can help, but you would need to restate a much simpler description of your problem (probably sans-threading and what you think Netmiko is doing incorrectly).

Regards, Kirk
