### ISSUE TITLE
Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position 0: invalid start byte start byte

### ISSUE THREAD

**Issue by zsdz** [ktbyers/netmiko#1114]
I want to use netmiko to control my network device Huawei USG5320.The device is old,it only support ssh 1.5,but paramiko support ssh 1.5,if I use port:22,got error:Protocol major versions differ: 2 vs .1

so I want to try to use port:23,the telnet.I can connect to this device by both ssh and telnet in cli

when use port:23,I got error: Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position 0: invalid start byte start byte

I don't know how to fix this,Thanks!

the netmiko version is 2.3.0

**Comment by OzNetNerd** [comment]
Can you please post a copy of your code?

**Comment by zsdz** [comment]
It's very easy:

from netmiko import ConnectHandler

USG5320 = {
    'device_type': 'huawei',
    'ip':   '',
    'username': 'test',
    'password': 'password',
    'port' : 23,         
}

net_connect = ConnectHandler(**USG5320)

output = net_connect.send_command('display ver')
print(output)

Maybe I have a very big that paramiko can only use ssh not telnet?If is that I am very sorry

**Comment by ktbyers** [comment]
There is no Huawei telnet support so the above won't work. You would have to submit a PR to add the telnet support.

Regards, Kirk

**Comment by ktbyers** [comment]
The issue here is that SSH is being used by Netmiko and the port is being set to 23 (the telnet port) which then fails.
