### ISSUE TITLE
can't get to enable mode

### ISSUE THREAD

**Issue by theLORD97** [ktbyers/netmiko#1115]
Here is my code. 

import time
from netmiko import ConnectHandler
#from netmiko import Netmiko
import re
import pprint
import os
#import xlsxwriter
import datetime
import smtplib
import mimetypes
from getpass import getpass

hostfile="/opt/scripts/Lord/tacacs_project/cisco_list.txt"
username = 'admin'
password = getpass()
platform = 'cisco_ios'
secret = 'secret'

###### Open file that contains the list of devices
with open(hostfile) as f:
    for line in f:
        host = line.strip()
        try:
            print ("Connecting")
            device = ConnectHandler(device_type=platform, ip=host, username=username, password=password, secret=secret)
            print ('Connected to Cisco box, gathering info.....')
            device.send_command('enable \n')
            #time.sleep(1)
            pwd = device.send_command(password+'\n')
            print (device.find_prompt())

Output

[root@ocg-sh-netscript1 tacacs_project]# python cisco_connect.py
Connecting
Connected to Cisco box, gathering info.....
clgsab76cpswt002>    -->>>> this is not enable mode
[root@ocg-sh-netscript1 tacacs_project]#

**Comment by theLORD97** [comment]
if i try to use the 
from netmiko import Netmiko, i get an error on that line even though Netmiko is fully installed



[root@ocg-sh-netscript1 tacacs_project]# python cisco_connect.py
Traceback (most recent call last):
  File "cisco_connect.py", line 3, in <module>
    from netmiko import Netmiko
ImportError: cannot import name Netmiko

**Comment by OzNetNerd** [comment]
`device.enable()` will do the trick.

`netmiko.Netmiko` does not exist which is why you're getting an import error.

**Comment by ktbyers** [comment]
@theLORD97 Do you have a file named netmiko.py (i.e. are you causing a name conflict with the netmiko library)

That import should work fine:

```
$ python
Python 3.6.7 (default, Dec 21 2018, 20:32:34) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from netmiko import Netmiko
>>> Netmiko
<function ConnectHandler at 0xb7799614>
```

The Netmiko class is just another name for ConnectHandler.

**Comment by OzNetNerd** [comment]
ahh, I never noticed [this line.](https://github.com/ktbyers/netmiko/blob/develop/netmiko/__init__.py#L24)

**Comment by ktbyers** [comment]
@OzNetNerd Yes, at one point I thought it would be worthwhile to replace ConnectHandler to Netmiko since it gets used so frequently. So I put that in place, but then changing names is hard so its there, but ConnectHandler still is what people use the vast majority of the time (me included).

**Comment by theLORD97** [comment]
Thanks guys, sorry i should have responded.. i figured it out....

**Comment by carlniger** [comment]
inactive. closing.
