### ISSUE TITLE
python setup.py install bash: python: command not found

### ISSUE THREAD

**Issue by rkega** [ktbyers/netmiko#1124]
Hello,

Just like other posts start... I'm new and having issues following the steps to install netmiko on windows 10 found here [https://www.jaacostan.com/2018/09/how-to-install-netmiko-on-windows.html](url)

When I get to step 8) execute python setup.py install from Git Bash Window. Once the installation is completed, go to your Windows Command prompt or Anaconda shell and check Netmiko from Python Interpreter shell.
I get this out put

 MINGW64 ~/netmiko (develop)
$ python setup.py install
bash: python: command not found

Can anyone please point me in the right direction? thank you

![error](https://user-images.githubusercontent.com/48309907/53937428-ee910e80-4061-11e9-9859-161af6f1510c.jpg)

**Comment by rkega** [comment]
Figured out the issue I had to point it to my install I guess of python before the running the python setup.py install command

fid found on this site step 7

[https://italchemy.wordpress.com/2018/02/16/python-installing-netmiko-on-windows-10-pc-for-automation/](url)

**Comment by rkega** [comment]
Hope this helps someone else

**Comment by NetworkNoob1010** [comment]
I'm running into the same issue.  How do I fix this?  The link you put is now dead.,  Thank you

**Comment by NetworkNoob1010** [comment]
> Figured out the issue I had to point it to my install I guess of python before the running the python setup.py install command
> 
> fid found on this site step 7
> 
> [https://italchemy.wordpress.com/2018/02/16/python-installing-netmiko-on-windows-10-pc-for-automation/](url)

I'm running into the same issue. How do I fix this? The link you put is now dead., Thank you

**Comment by ktbyers** [comment]
You need to specify the path to Python or update your windows environment so that it is on the path.

**Comment by NetworkNoob1010** [comment]
> You need to specify the path to Python or update your windows environment so that it is on the path.

Thanks Kirk!  Sorry, but can you possibly elaborate on that a little?  So you mean move the cd to point to the python file, then try the python install?
