### ISSUE TITLE
Ruckus fastiron does not reliably enter enable mode.

### ISSUE THREAD

**Issue by spdkils** [ktbyers/netmiko#1125]
I support devices across the world. Slow and slightly unreliable connections can miss setup on Brocade with it's current implementation.

The current method is a blind call to enable, and if it doesn't work, paging doesn't work. If paging doesn't work, almost nothing works, and you're not in a 'known' position. No error is made, and no second attempt is made to get a good initialization.

I suggest a slight change to the setup to deal with this. I've tested it and it works, the exact error raised etc, I'm ambivalent to.
```        self.set_base_prompt()
        self.enable() #<--- no net
        self.disable_paging(command="skip-page-display")
```

to something like....
```        self.set_base_prompt()
        for _ in range(3):
            self.enable()
            if self.check_enable_mode():
                break
        else:
             msg = "Unable to enter enable mode. blah blah blah fix it"
             raise ValueError(msg)

        self.disable_paging(command="skip-page-display")
```

**Comment by ktbyers** [comment]
Why doesn't the call to `enable` work? Have you tried adjusting `global_delay_factor` so that it works sufficiently reliably?

If enable() fails, doesn't an exception already get raised?

**Comment by spdkils** [comment]
```    def enable(
        self, cmd="enable", pattern=r"(ssword|User Name)", re_flags=re.IGNORECASE
    ):
...
...
                if "ssword" in new_data:
                    self.write_channel(self.normalize_cmd(self.secret))
                    output += self.read_until_prompt()
                    return output <----------- No raise.... just return.
....
...
....
# Below code never gets hit because the early return...
        if not self.check_enable_mode():
            msg = (
                "Failed to enter enable mode. Please ensure you pass "
                "the 'secret' argument to ConnectHandler."
            )
            raise ValueError(msg)
```

**Comment by spdkils** [comment]
Man that above comment it horrible. :( Sorry.

There is a return in the rukus enable, that early outs before the raise of the valueerror.
I suspect that is the problem I hit, I had to open up the code again to look.

**Comment by ktbyers** [comment]
```
 49                     output += self.read_until_prompt()
 50                     return output
```

Okay, we can change line 50 to be a break and then have the return output come after the check_enable_mode:

```
        if not self.check_enable_mode():
            msg = ( 
                "Failed to enter enable mode. Please ensure you pass "
                "the 'secret' argument to ConnectHandler."
            )   
            raise ValueError(msg)
return output         # add this
```

Do you want to submit a pull request on that?


Kirk

**Comment by spdkils** [comment]
There is a pull request. I looked at this several ways. I was going to try and do a one line fix. But after looking at how the loop was dead anyway. It also wasn't looping the check... I just simplified it and ensured it gave you known output states.

**Comment by carlniger** [comment]
Closing since there is a PR for this.
