### ISSUE TITLE
textFSM - output not in expected format

### ISSUE THREAD

**Issue by kevindasilva03** [ktbyers/netmiko#1126]
Possible bug...

Connecting with device type cisco_xe running the following command
mac_int_output = net_conn.send_command(f"show mac address-table", use_textfsm=True)
Results is a string of the entire MAC table.

Just for kicks... I reconnected to the XE device using device type cisco_ios and I get the following:

[{'destination_address': '0008.e3ff.fca8',
  'type': 'static',
  'vlan': '950',
  'destination_port': 'Switch'}]

The result is only the first MAC entry in the table, but the format is what I'm looking for.

How do I go about troubleshooting this further.

Please advise and thanks for your help!

**Comment by ktbyers** [comment]
ntc_templates doesn't have an index for 'cisco_xe' i.e. they only have a category of 'cisco_ios'. You should be able to just switch to 'cisco_ios' for the device_type since that is identical to 'cisco_xe' from a Netmiko perspective.

**Comment by kevindasilva03** [comment]
Thanks Kirk for the quick reply. Just to confirm, when using 'cisco_ios' and the output is only the first line, this is a textFSM issue? If so, I will follow up with them.

Thanks again!

**Comment by ktbyers** [comment]
Okay, I might have misunderstood your issue (or you second issue anyways)...so you are saying you set this to "cisco_ios" and you only get one entry back and you are expecting more than one entry?

```
[{'destination_address': '0008.e3ff.fca8',
'type': 'static',
'vlan': '950',
'destination_port': 'Switch'}]
```

**Comment by kevindasilva03** [comment]
That is correct...

**Comment by kevindasilva03** [comment]
Sample command output:

dd-r-vss#sh mac address-table
Unicast Entries
 vlan     mac address     type        protocols               port
---------+---------------+--------+---------------------+-------------------------
 950      0008.e3ff.fca8    static ip,ipx,assigned,other Switch
1105      0008.e3ff.fca8    static ip,ipx,assigned,other Switch
1105      0008.e3ff.fcac   dynamic ip,ipx,assigned,other Port-channel30
1106      0008.e3ff.fca8    static ip,ipx,assigned,other Switch
1106      002a.6a8b.e343   dynamic ip,ipx,assigned,other TenGigabitEthernet1/1/1
1171      0008.e3ff.fca8    static ip,ipx,assigned,other Switch
1171      001b.baf8.ca15   dynamic ip,ipx,assigned,other Port-channel41
1171      001b.baf8.ca31   dynamic ip,ipx,assigned,other Port-channel41

**Comment by ktbyers** [comment]
I would first see the raw data of what Netmiko is getting back:

```
mac_int_output = net_conn.send_command(f"show mac address-table")
```

And print that variable out.

To isolate whether it is a Netmiko issue or a TextFSM issue.

**Comment by kevindasilva03** [comment]
See below. Sample of output.


In [30]: mac_int_output = net_conn.send_command("show mac address-table")

In [31]: mac_int_output
Out[31]: 'Unicast Entries\n vlan     mac address     type        protocols               port\n---------+---------------+--------+---------------------+-------------------------\n 950      0008.e3ff.fca8    static ip,ipx,assigned,other Switch                     \n1105      0008.e3ff.fca8    static ip,ipx,assigned,other Switch                     \n1105      0008.e3ff.fcac   dynamic ip,ipx,assigned,other Port-channel30             \n1106      0008.e3ff.fca8    static ip,ipx,assigned,other Switch                     \n1106      002a.6a8b.e343   dynamic ip,ipx,assigned,other TenGigabitEthernet1/1/1    \n1171      0008.e3ff.fca8    static ip,ipx,assigned,other Switch                     \n1171      001b.baf8.ca15   dynamic ip,ipx,assigned,other Port-channel41             \n1171      001b.baf8.ca31   dynamic ip,ipx,assigned,other Port-channel41             \n1171      001d.affe.7d33   dynamic ip,ipx,assigned,other Port-channel21             \n1171      005f.8691.4ac9   dynamic ip,ipx,assigned,other Port-channel21             \n1171      005f.8691.4ace   dynamic ip,ipx,assigned,other Port-channel21             \n1171      005f.8691.4ada   dynamic ip,ipx,assigned,other Port-channel43             \n

**Comment by ktbyers** [comment]
Looking at the TextFSM template...it looks like probably a TextFSM bug:

```
TYPE3
  ^\s+${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+\S+\s+${DESTINATION_PORT} -> Record
```

I think `^\s+` needs changed to `^\s*` (i.e. when the VLAN is 4 digits, then there is no leading whitespace).

`cisco_ios_show_mac-address-table.template`

**Comment by kevindasilva03** [comment]
I've made the modification, still no go, but I've opened an issue with them to have it reviewed.

Thanks for your time. It's much appreciated!

**Comment by ktbyers** [comment]
Works for me (using your output data):

```
python /home/kbyers/VENV/py3_venv/local/lib/python3.6/site-packages/textfsm.py ../ntc-templates/templates/cisco_ios_show_mac-address-table.template show_mac.txt 
FSM Template:
Value DESTINATION_ADDRESS ([0-9a-fA-F]{4}\.[0-9a-fA-F]{4}\.[0-9a-fA-F]{4})
Value TYPE (\w+)
Value VLAN (\w+)
Value DESTINATION_PORT (\S+)

Start
  ^Destination\s+Address\s+Address\s+Type\s+VLAN\s+Destination\s+Port -> TYPE1
  ^\s+vlan\s+mac address\s+type\s+learn\s+age\s+ports -> TYPE2
  ^\s+vlan\s+mac address\s+type\s+protocols\s+port -> TYPE3
  ^Vlan\s+Mac Address\s+Type\s+Ports -> TYPE4

TYPE1
  ^${DESTINATION_ADDRESS}\s+${TYPE}\s+${VLAN}\s+${DESTINATION_PORT} -> Record

TYPE2
  ^[\*|\s]\s+${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+\S+\s+\S+\s+${DESTINATION_PORT} -> Record

TYPE3
  ^\s*${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+\S+\s+${DESTINATION_PORT} -> Record

TYPE4
  ^\s+${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+${DESTINATION_PORT} -> Record


FSM Table:
['DESTINATION_ADDRESS', 'TYPE', 'VLAN', 'DESTINATION_PORT']
['0008.e3ff.fca8', 'static', '950', 'Switch']
['0008.e3ff.fca8', 'static', '1105', 'Switch']
['0008.e3ff.fcac', 'dynamic', '1105', 'Port-channel30']
['0008.e3ff.fca8', 'static', '1106', 'Switch']
['002a.6a8b.e343', 'dynamic', '1106', 'TenGigabitEthernet1/1/1']
['0008.e3ff.fca8', 'static', '1171', 'Switch']
['001b.baf8.ca15', 'dynamic', '1171', 'Port-channel41']
['001b.baf8.ca31', 'dynamic', '1171', 'Port-channel41']
['001d.affe.7d33', 'dynamic', '1171', 'Port-channel21']
```

**Comment by ktbyers** [comment]
```diff
 TYPE3
-  ^\s+${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+\S+\s+${DESTINATION_PORT} -> Record
+  ^\s*${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+\S+\s+${DESTINATION_PORT} -> Record
```

**Comment by ktbyers** [comment]
Type2 and Type4 might also need to be edited as well.

**Comment by kevindasilva03** [comment]
I updated the template, but when I ran the command as you did, it's not showing the update. Is it pulling from cache or buffer?

python textfsm.py .../ntc-templates/templates/cisco_ios_show_mac-address-table.template .../show_mac.txt

FSM Template:
Value DESTINATION_ADDRESS ([0-9a-fA-F]{4}\.[0-9a-fA-F]{4}\.[0-9a-fA-F]{4})
Value TYPE (\w+)
Value VLAN (\w+)
Value DESTINATION_PORT (\S+)

Start
  ^Destination\s+Address\s+Address\s+Type\s+VLAN\s+Destination\s+Port -> TYPE1
  ^\s+vlan\s+mac address\s+type\s+learn\s+age\s+ports -> TYPE2
  ^\s+vlan\s+mac address\s+type\s+protocols\s+port -> TYPE3
  ^Vlan\s+Mac Address\s+Type\s+Ports -> TYPE4

TYPE1
  ^${DESTINATION_ADDRESS}\s+${TYPE}\s+${VLAN}\s+${DESTINATION_PORT} -> Record

TYPE2
  ^[\*|\s]\s+${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+\S+\s+\S+\s+${DESTINATION_PORT} -> Record

TYPE3
  ^\s+${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+\S+\s+${DESTINATION_PORT} -> Record

TYPE4
  ^\s+${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+${DESTINATION_PORT} -> Record


FSM Table:
['DESTINATION_ADDRESS', 'TYPE', 'VLAN', 'DESTINATION_PORT']
['0008.e3ff.fca8', 'static', '950', 'Switch']

FROM THE TEMPLATE:
  1 Value DESTINATION_ADDRESS ([0-9a-fA-F]{4}\.[0-9a-fA-F]{4}\.[0-9a-fA-F]{4})
  2 Value TYPE (\w+)
  3 Value VLAN (\w+)
  4 Value DESTINATION_PORT (\S+)
  5
  6 Start
  7   ^Destination\s+Address\s+Address\s+Type\s+VLAN\s+Destination\s+Port -> TYPE1
  8   ^\s+vlan\s+mac address\s+type\s+learn\s+age\s+ports -> TYPE2
  9   ^\s+vlan\s+mac address\s+type\s+protocols\s+port -> TYPE3
 10   ^Vlan\s+Mac Address\s+Type\s+Ports -> TYPE4
 11
 12 TYPE1
 13   ^${DESTINATION_ADDRESS}\s+${TYPE}\s+${VLAN}\s+${DESTINATION_PORT} -> Record
 14
 15 TYPE2
 16   ^[\*|\s]\s*${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+\S+\s+\S+\s+${DESTINATION_PORT} -> Record
 17
 18 TYPE3
 19   ^\s*${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+\S+\s+${DESTINATION_PORT} -> Record
 20
 21 TYPE4
 22   ^\s*${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+${DESTINATION_PORT} -> Record

**Comment by kevindasilva03** [comment]
Please disregard... I found my error... Thank for you help!!

Kevin
