### ISSUE TITLE
paramiko.ssh_exception.SSHException: Incompatible version (1.5 instead of 2.0)

### ISSUE THREAD

**Issue by dweber42** [ktbyers/netmiko#1127]
Hi @ktbyers ,

I have a simple Python script using Netmiko to iterate through a list of hosts of various OS's, redirect to respective functions for each OS w/ the correct netmiko device_type / device commands, to collect syslog servers. Trouble is I have dozens of legacy IOS routers running only SSH v1. Many have an old IOS version that cannot support SSH v2 at all. 

Have you come across a solution to allow SSH v1. Seems this is not possible by design for Paramiko.

Thank you!

[multi_os_syslog_audit.py.txt](https://github.com/ktbyers/netmiko/files/2944045/multi_os_syslog_audit.py.txt)

script output:

[root@cacti python_multi_os_syslog_updates]# python multi_os_syslog_updates.py 

************* 2019-03-07 17:03:16 PST - starting multi oS device syslog audit now...*************

mr1.xxxxxxx.xxxxxxx.net iosxr

logging XXX.XX.XX.XXX vrf default severity info port default
logging XXX.XX.XX.XXX vrf default severity info port default
logging XXX.XX.XX.XXX vrf default severity info port default

disconnected from mr1.xxxxxxxxxx.xxxxxxxxx.net now

br1.xxxxxxxxxx.xxxxxxxxx.net ios
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "multi_os_syslog_updates.py", line 314, in <module>
    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)    #Connect to device
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 207, in __init__
    self.establish_connection()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 689, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 545, in start_client
    raise e
paramiko.ssh_exception.SSHException: Incompatible version (1.5 instead of 2.0)

**Comment by OzNetNerd** [comment]
Paramiko likely doesn't support 1.5. Have a read of [this](http://www.paramiko.org/faq.html#paramiko-doesn-t-work-with-my-cisco-windows-or-other-non-unix-system).

**Comment by ktbyers** [comment]
Nope, as @OzNetNerd nerd stated Paramiko doesn't support SSH version1.

SSH version2 is ~13 years old. I think SSHv1 also has some significant security issues. So nope we don't support it. I doubt we will ever support it.

Regards, Kirk

**Comment by dweber42** [comment]
ok,  @OzNetNerd & @ktbyers, thank you for confirming that. Just added a try & except for each function to create a list to be dealt with manually.

**Comment by lutfisan** [comment]
```
Exception: Incompatible version (2.99 instead of 2.0)
Traceback (most recent call last):
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/home/cacti/miniconda3/envs/ipam/lib/python3.7/site-packages/paramiko/transport.py", line 2240, in _check_banner
    raise SSHException(msg.format(version))
paramiko.ssh_exception.SSHException: Incompatible version (2.99 instead of 2.0)
```

hey @ktbyers I get this error

**Comment by ktbyers** [comment]
@lutfisan It looks like you need to do the fix outlined here:

https://blog.rabin.io/sysadmin/ansible-cisco-ios-module-incompatible-version-2-99-instead-of-2-0
