### ISSUE TITLE
switch - some commands output fine and some don't??

### ISSUE THREAD

**Issue by jacob600** [ktbyers/netmiko#1133]
Hello,

I am using the script right, exactly as it is, with the exception that I only have one ip address that I am testing against.
https://github.com/vigilne/networks-are-awesome/blob/master/aruba/aruba_base_pyscript

My commands file is this:
#cat commands.txt
show vlan 10
show version
show time
show uptime

The first two commands output fine but the last two get run together and there are a bunch of extra (config) prompts at the end. There also appears to be extra " marks when it reads the commands.txt file.  This script works as intended if remove the last two commands in the text file. How can I fix this?

Here is the output:
Opening commands from text file.
['show vlan 10', 'show version', 'show time\\n', 'show uptime\\n', '', '', '', '', '']
Establishing SSH connection to devices and running commands.
config termswlab01(config)# show vlan 10
 Status and Counters - VLAN Information - VLAN 10

  VLAN ID : 10
  Name : Lab_Srv
  Status : Port-based
  Voice : No
  Jumbo : Yes
  Private VLAN : none
  Associated Primary VID : none
  Associated Secondary VIDs : none

  Port Information Mode     Unknown VLAN Status
  ---------------- -------- ------------ ----------
  15               Tagged   Learn        Up
  21               Tagged   Learn        Up

swlab01(config)# show version
Image stamp:    /ws/swbuildm/rel_ukiah_qaoff/code/build/tam(swbuildm_rel_ukiah_qaoff_rel_ukiah)
                Dec 21 2017 23:56:16
                KA.16.04.0011
                552
Boot Image:     Primary

Boot ROM Version:    KA.15.10
Active Boot ROM:     Primary

swlab01(config)# show time\nInvalid input: time\n
swlab01(config)# show uptime\nInvalid input: uptime\n
swlab01(config)# swlab01(config)# swlab01(config)# swlab01(config)# swlab01(config)# swlab01(config)# endswlab01#
Script complete.

Debug snippet:
swlab01(config)# show version
Image stamp:    /ws/swbuildm/rel_ukiah_qaoff/code/build/tam(swbuildm_rel_ukiah_qaoff_rel_ukiah)
                Dec 21 2017 23:56:16
                KA.16.04.0011
                552
Boot Image:     Primary

Boot ROM Version:    KA.15.10
Active Boot ROM:     Primary

swlab01(config)# show time\nInvalid input: time\n
swlab01(config)# show uptime\nInvalid input: uptime\n
swlab01(config)# swlab01(config)# swlab01(config)# swlab01(config)# swlab01(config)# swlab01(config)# endswlab01#
DEBUG:paramiko.transport:EOF in transport thread
^[[38;120^[[38;120R^[[38;120admin@server1:~$ ;120;120R;120R;120RR

**Comment by OzNetNerd** [comment]
A couple of suggestions:
1. Your iterating over `ips` in order to create `aruba` dicts. You're then appending the dicts to`devices` and then iterating over `devices`. My advice would be to skip the second iteration as there's no need for it.
2. Use [`send_config_from_file`](https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1486)

**Comment by jacob600** [comment]
@OzNetNerd  I changed it to use the send_config_file and I used the option with .strip(). Those two items cleared up most of the formatting issues. Keep in mind, that I am very new to python(3). 
I understand your comments about the double iteration but I do not know how to fix it.  Could you show me how the modified coded should like look?

Also, I still don't know why the script enters config mode if it is just "show" commands.  There doesn't appear to be a "send_command_from_file" option.

 @ktbyers ktbyers added the Netmiko 1_0  label on Jul 3

Here is what the code for the loop looks like now:
```
# Loop used to ssh to items in devices list and execute commands
for ip in ips:
    net_connect = ConnectHandler(**aruba)
    output = net_connect.send_config_from_file(config_file='commands.txt')
    print(output)

print("Script complete.")
# end of script
```

**Comment by OzNetNerd** [comment]
@jacob600, here's a quick example of what you could do:

```
# Imports functions used in script
import getpass
from netmiko import ConnectHandler

# Prompts for username and password
username = input("Enter username: ")
p = getpass.getpass("Enter password: ")

aruba = {
    'device_type': 'hp_procurve',
    'username': username,
    'password': p,
    }

# opens file containing commands to be run on devices
print("Opening commands from text file.")

with open('commands.txt') as c:
    lines = c.read().splitlines()
print(lines)

# Creates list of ip addresses of devices
ips = ["172.16.1.10", "172.16.2.10", "172.16.3.10"]

# Loop used to generate device dictionaries from ips list and
# stores dictionary entry in devices list
for ip in ips:
    aruba['ip'] = ip

    print("Establishing SSH connection to devices and running commands.")
    net_connect = ConnectHandler(**aruba)
    output = net_connect.send_config_set(lines)
    print(output)

print("Script complete.")
# end of script
```

**Comment by jacob600** [comment]
@OzNetNerd - This is great. I really appreciate it. I'm sure it's a simple script for your but for a noob like me, it's huge from a learning curver perspective. 

After lots of research and looking at code, I realized that there isn't a bulk SEND command yet but it looks to be in the works. 
I have been working on a FOR loop to cycle through the IPs one at a time and then cycle through the commands  one at a time, per IP, using "net_connect.send_command".  I've been fighting this thing for hours but I get a bit closer about every 30 mins... lol. I  hate to say it but  I'll have to ask for help one more time but I'll make that a new post.

Thank you again!

**Comment by OzNetNerd** [comment]
No worries at all @jacob600. It's my pleasure.

You're correct. There doesn't seem to be a bulk send command option. When I get some time, I'll write one up and submit a PR.

> I have been working on a FOR loop to cycle through the IPs one at a time and then cycle through the commands one at a time, per IP, using "net_connect.send_command".

Excellent. That's the way I'd do it, so you're definitely on the right track.

>  I've been fighting this thing for hours but I get a bit closer about every 30 mins

That's great to hear. Keep persevering and your knowledge will continue to grow at an increasingly rapid rate. 

>  I hate to say it but I'll have to ask for help one more time but I'll make that a new post.

Sounds good to me :) I'll be happy to take a look.
