### ISSUE TITLE
passing variables from dictionary in a config_set command.  

### ISSUE THREAD

**Issue by cramphal** [ktbyers/netmiko#1134]
looking for help on passing a variable on a connection.send_config_set.  I tried creating a dictionary for the variables and passing them this way:
connection.send_config_set(['interface loopback0','ip address' device['loopbackip'] '255.255.255.255'])

however I get a synyax error. if I plug the variable in manually, it works. 

any help would be appreciated.

**Comment by OzNetNerd** [comment]
You're very close!

Here's a working example:
```
> device = {
    'loopbackip': '1.1.1.1'
}
> cmds = ['interface loopback0','ip address ' + device["loopbackip"] + ' 255.255.255.255']
> print(cmds)
['interface loopback0', 'ip address 1.1.1.1 255.255.255.255']
```

**Comment by cramphal** [comment]
you're the best! works like a charm 👍
