### ISSUE TITLE
HP procurve - truncating characters

### ISSUE THREAD

**Issue by jacob600** [ktbyers/netmiko#1135]
The output of the last two commands (show time & show uptime) seems to run together. How to fix?
I'm actually running four commands total (sh vlan 10, sh ver, show time & show uptime) from a commands.txt but for  now, I modified the code to issuing these commands independently in hopes of finding a solution and then either reverting back to using the commands.txt file or a combination of reading from a file and the manual commands.

@OzNetNerd - This is a continuance from #1133 that you helped me with. Different issue. As you can see,  I did get the loop code working but it doesn't feel right to me. Any feedback is appreciated.

**Similar issues but no posted solution:**
https://github.com/ktbyers/netmiko/issues/847
https://github.com/ktbyers/netmiko/issues/1086

```
with open('commands.txt') as c:
    lines = c.read().strip().splitlines()
    # lines  = c.read().splitlines().strip()
print(lines)

for ip in ips:
    aruba['ip'] = ip

    print("Establishing SSH connection to devices and running commands.")
    net_connect = ConnectHandler(**aruba)
    output = net_connect.send_command("show ver")
    output += net_connect.send_command("show time")
    print (output)
    #print (hostname, output, sep='\n')
    f = open('sshsep0001.txt', 'a')
    f.write(output)
    f.close()
#       print(output)
    net_connect.disconnect
```

**Normail cli output - what it should look like**
swlab01# sh version

Image stamp:
 /ws/swbuildm/rel_ukiah_qaoff/code/build/tam(swbuildm_rel_ukiah_qaoff_rel_ukiah)
                Jun 19 2018 19:50:43
                KA.16.04.0016
                655
Boot Image:     Primary

Boot ROM Version:    KA.15.10
Active Boot ROM:     Primary

swlab01# sh time
Wed Mar 13 00:04:32 2019
swlab01# show uptime
0001:04:32:56.43
swlab01#

**log file shows this:**
Active Boot ROM:     Primary
ue Mar 12 23:56:59 2019001:04:22:22.25
Boot ROM Version:    RA.15.11Mon Jan  1 01:17:15 19900000:01:17:05.37
*** the last commands above are run together (show time & show uptime)

**result of print(output) with debug**
'ed Mar 13 00:01:27 2019'
'001:04:26:50.24'
Script complete.

**Comment by ktbyers** [comment]
Can you include the `session_log` output. You can create this by adding the following argument to ConnectHandler

```python
ConnectHandler(normal_args, session_log="my_output.txt")
```

**Comment by jacob600** [comment]
the prompt is missing a character but the log looks good. It is attached.
Boot ROM Version:    KA.15.10
Active Boot ROM:     Primary
ed Mar 13 15:06:09 2019
Script complete.

[my_output.txt](https://github.com/ktbyers/netmiko/files/2963451/my_output.txt)

**Comment by ktbyers** [comment]
What do you see with:

```python
print(repr(output))
```

**Comment by jacob600** [comment]
Defintely. Here you go.

['show vlan 10', 'show version', 'show time', 'show uptime']
Establishing SSH connection to devices and running commands.
'Image stamp:    /ws/swbuildm/rel_ukiah_qaoff/code/build/tam(swbuildm_rel_ukiah_qaoff_rel_ukiah)\n                Jun 1
9 2018 19:50:43\n                KA.16.04.0016\n                655\nBoot Image:     Primary\n\nBoot ROM Version:    KA
.15.10\nActive Boot ROM:     Primary\ned Mar 13 16:08:33 2019'
Script complete.

**Comment by jacob600** [comment]
Two more notes. If I run the script against two ip addresses using a file, only the first switch gets the truncated effect. The output for the "show time" and "show uptime" command from the second switch is fine.  Also, the "show version" and "show time/uptime" don't have a blank line after their output  like "sh ver" does. This can be seen in my output above. If that is useful.....

**Comment by ktbyers** [comment]
@jacob600 Which version of Netmiko do you have? Are you using Netmiko 2.3.3?

Also what happens if you set global_delay_factor to 2 or to 4. I am not really seeing why this is happening (on initial look).

**Comment by jacob600** [comment]
1) Version of netmiko.  what is proper way to show version? I couldn't get any commands I tried (google search) to figure it out so I did a pip install to see what warnings got displayed.

python3 -m pip install netmiko
Requirement already satisfied: netmiko in ./.local/lib/python3.6/site-packages (2.3.3)
Requirement already satisfied: paramiko>=2.4.2 in /usr/local/lib/python3.6/dist-packages (from netmiko) (2.4.2)

2) Should I able to run "netmiko-show" from my ubuntu cli? I can't which is why I asked.

3) Tried both of these options but no luck.
aruba = {
    'device_type': 'hp_procurve',
    'username': username,
    'password': p,
    'global_delay_factor': 2,
    }

print("Establishing SSH connection to devices and running commands.")
    net_connect = ConnectHandler(**aruba)
    output = net_connect.send_command("show ver")
    expect_string=r'# ',
    delay_factor=2
    output += net_connect.send_command("show time")
    print (output)

**Comment by jacob600** [comment]
@ktbyers - Update. It appears the missing character is only happening on the HP Aruba 3800.  The script does work properly on my 2920. I'll dig into this more offline.

38000 (KA.16.04.0016) & 2920 (RA.16.01.0007)

**Comment by ktbyers** [comment]
One possible cause is the stripping of ANSI escape codes. It might be interesting to disable this and see if the problem goes away.

https://github.com/ktbyers/netmiko/blob/develop/netmiko/hp/hp_procurve.py#L32

**Comment by jacob600** [comment]
I add this code snippet but it didn't work.
```
from netmiko.cisco_base_connection import CiscoSSHConnection
class HPProcurveSSH(CiscoSSHConnection):
    def session_preparation(self):
        """
        Prepare the session after the connection has been established.
        Procurve uses - 'Press any key to continue'
        """
        delay_factor = self.select_delay_factor(delay_factor=0)
        time.sleep(1 * delay_factor)
        self.write_channel("\n")
        time.sleep(1 * delay_factor)
```

**Comment by ktbyers** [comment]
Okay, let me know if you test disabling the ANSI escape codes by toggling that line 32 I referenced above to False.

**Comment by jacob600** [comment]
@ktbyers My apologies. I did try ansi=false with no success. I also tried changing the console prompt to v1t00 and none with no success as well. Finally, I tried several variations using expect_string but no luck. It's always like this:
Boot ROM Version:    KA.15.10
Active Boot ROM:     Primary

un Mar 17 12:03:25 2019     <--- First letter truncated

**Comment by carlniger** [comment]
@jacob600 could you post the full debug log of this if it is still an issue please? See this [link](https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel)

**Comment by cheney-3** [comment]
I have this same issue. Did a fair amount of debugging today. I noticed this issue happens with HP 3800 switches that run KA.16.04 but not KA.16.01. There may be other versions as well, but, I did not test them all.

What I have noticed is the ANSI ESC code of ESC[E  is not sent by some HP (so far, the 16.04 version). In the module strip_ansi_escape_codes, only code_next_line is replaced with RETURN. So what happens is the variable output does not receive a RETURN and is concatenated with the next output read by the read_channel in send_command.

What I did see was these HP 3800 sending what looks like the CRLF method. I will see code_form_feed (ESC[1L) and code_carriage_return (ESC[1M]). I am not an ANSI guy, but I believe this is the same as ESC[E.

I believe this is an issue for the initial show command. It appears the show command is echoed back into the read_channel along with the legitimate output. 

The following not-so-clean :) code seemed to fix this for me in the function strip_ansi_escape_codes:

`

        # Locate this line in the function and add command after:
        output = string_buffer        
        
        # Fix possible CRLF Style of "New Line"
        old_crlf=False
        code_form_feed_str = chr(27) + r"[1L"
        code_carriage_return_str = chr(27) + r"[1M"
        if code_form_feed_str in output:
            if code_carriage_return_str in output:
                if code_next_line not in output:
                    old_crlf=True
        # End Flagging Section

        
        for ansi_esc_code in code_set:      
            output = re.sub(ansi_esc_code, "", output)

        # CODE_NEXT_LINE must substitute with return
        output = re.sub(code_next_line, self.RETURN, output)
        
        # Add this section to review the CRLF Flag and add \n if needed
        if old_crlf:
            output += '\n'
`

Here is some log output from the debugging log prior to this change:

24/09/2019 17:56:06 write_channel: b'show run | i sntp server\n'
24/09/2019 17:56:06 read_channel: 
24/09/2019 17:56:06 read_channel: 
24/09/2019 17:56:06 read_channel: [24;12Hshow run |[24;12H[?25h[24;22H[24;22H i sntp se[24;22H[?25h[24;32H[24;32Hrver[24;32H[?25h[24;36H[1;0H[1M[24;1H[1L[24;36H[24;1H[2K[24;1H[?25h[24;1H[1;24r[24;1H
24/09/2019 17:56:06 In strip_ansi_escape_codes
**_!!! In this next line, there is [1M and [1L, but not [E_**
24/09/2019 17:56:06 repr = '\x1b[24;12Hshow run |\x1b[24;12H\x1b[?25h\x1b[24;22H\x1b[24;22H i sntp se\x1b[24;22H\x1b[?25h\x1b[24;32H\x1b[24;32Hrver\x1b[24;32H\x1b[?25h\x1b[24;36H\x1b[1;0H\x1b[1M\x1b[24;1H\x1b[1L\x1b[24;36H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[1;24r\x1b[24;1H'
24/09/2019 17:56:06 new_output = show run | i sntp server   **_<- Where's the \n?_**
24/09/2019 17:56:06 repr = 'show run | i sntp server'
24/09/2019 17:56:06 read_channel: 
24/09/2019 17:56:07 read_channel: 
24/09/2019 17:56:07 read_channel: 
24/09/2019 17:56:07 read_channel: 
24/09/2019 17:56:07 read_channel: 
24/09/2019 17:56:07 read_channel: 
24/09/2019 17:56:08 read_channel: 
24/09/2019 17:56:08 read_channel: sntp server priority 1 10.1.1.1

sntp server priority 2 10.99.99.99

[1;24r[24;1H[24;1H[2K[24;1H[?25h[24;1H[24;1HHP-3800-1# [24;1H[24;12H[24;1H[?25h[24;12H
24/09/2019 17:56:08 In strip_ansi_escape_codes
24/09/2019 17:56:08 repr = 'sntp server priority 1 10.1.1.1\r\nsntp server priority 2 10.99.99.99\r\n\x1b[1;24r\x1b[24;1H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[24;1HHP-3800-1# \x1b[24;1H\x1b[24;12H\x1b[24;1H\x1b[?25h\x1b[24;12H'
24/09/2019 17:56:08 new_output = sntp server priority 1 10.1.1.1

sntp server priority 2 10.99.99.99

HP-3800-1# 
24/09/2019 17:56:08 repr = 'sntp server priority 1 10.1.1.1\r\nsntp server priority 2 10.99.99.99\r\nHP-3800-1# '
24/09/2019 17:56:08 In strip_ansi_escape_codes
**_!!! And this next line shows where "server" and "sntp" are one word_**
24/09/2019 17:56:08 repr = 'show run | i sntp serversntp server priority 1 10.1.1.1\r\nsntp server priority 2 10.99.99.99\r\nHP-3800-1# '
24/09/2019 17:56:08 new_output = show run | i sntp serversntp server priority 1 10.1.1.1

sntp server priority 2 10.99.99.99

HP-3800-1#

**Comment by ktbyers** [comment]
This issue is stale...a new issue needs created if this problem is still ongoing.
