### ISSUE TITLE
Output truncated for mellanox switch.

### ISSUE THREAD

**Issue by govind-rathod1987** [ktbyers/netmiko#1142]
I am trying to get in to the docker of Mellanox switch and check the currently running processes, but the output is truncated, here is my code:

net_connect = ConnectHandler(**mlnx_sw)
config_commands = ["docker", cmd1, "ps -aux"]
output = net_connect.send_config_set(config_commands, delay_factor=5)
print(output)
print (repr(output))
 the output with both the print is same like below:

@Switch-1:~/smarc/xxxxial_config]#ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\n
root         1  0.0  0.0  11628  1456 pts/0    Ss   04:44   0:00 /bin/bash /conf\n
root         9  0.0  0.0 105980  4004 pts/0    S    04:44   0:00 /usr/sbin/sshd \n
root        11  0.0  0.1 117688 11744 ?        Ss   04:44   0:04 /usr/bin/python\n
root        12  0.0  0.0  11764  1680 pts/0    S+   04:44   0:00 /bin/bash\n
root       151  0.0  0.0  11764  1836 pts/5    Ss+  10:30   0:00 bash\n
root       277  0.0  0.1 1305388 8848 ?        Ssl  10:36   0:00 /usr/local/libe\n
root       289  0.0  0.0  11764  1936 pts/1    Ss+  10:41   0:00 bash\n
root       382  0.0  0.0  11764  1888 pts/2    Ss+  10:49   0:00 bash\n
root       449  5.0  0.0  11764  1892 pts/3    Ss   11:36   0:00 bash\n
root       498  0.0  0.0  47436  1668 pts/3    R+   11:36   0:00 ps -aux\n
 
the actual output expected is 
Switch-1 /]#ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  11628  1456 pts/0    Ss   04:44   0:00 /bin/bash /config/ssanboot.sh
root         9  0.0  0.0 105980  4004 pts/0    S    04:44   0:00 /usr/sbin/sshd -D
root        11  0.0  0.1 117688 11744 ?        Ss   04:44   0:04 /usr/bin/python /usr/bin/supervisord -c /etc/supervisord.conf
root        12  0.0  0.0  11764  1680 pts/0    S+   04:44   0:00 /bin/bash
root       151  0.0  0.0  11764  1836 pts/5    Ss+  10:30   0:00 bash
root       277  0.0  0.1 1305388 8848 ?        Ssl  10:36   0:00 /usr/local/libexec/slapd -F /etc/ldap/sns/slapd.d/
root       289  0.0  0.0  11764  1936 pts/1    Ss+  10:41   0:00 bash
root       382  0.0  0.0  11764  1888 pts/2    Ss   10:49   0:00 bash
root       499  0.0  0.0  47436  1668 pts/2    R+   11:39   0:00 ps -aux

**Comment by carlniger** [comment]
@govind-rathod1987 you will probably need to `redispatch` to `linux` for the device_type as the terminal handling for Mellanox is of course going to be a bit different and may cause things to break. There may be other issues, but let's start there and see what happens.

Also managing/getting info from the container is probably not the best use case for Netmiko as there are probably more suited tools (Ansible maybe, or any other Linux/Docker tools), so it may be worth taking a second to step back and evaluate other options!

**Comment by carlniger** [comment]
Inactive, closing.

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.
