### ISSUE TITLE
using netmiko on Juniper EX vs MX

### ISSUE THREAD

**Issue by theLORD97** [ktbyers/netmiko#1143]
Hey Kirk, 

Is there anything special i need to do in order to run Netmiko on Juniper EX devices. For some reason it only will log into the Juniper MX class but no the EX class. 

any ideas?

```python
hostfile="/opt/scripts/Lord/tacacs_project/juniper_list.txt"
username = 'admin'
password = getpass()
platform = 'juniper_junos'

###### Open file that contains the list of devices
with open(hostfile) as f:
    for line in f:
        host = line.strip()
        try:
            print ("Connecting")
            device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
            time.sleep(1)
            print ('Connected to Juniper box, gathering info.....')
            version = device.send_command('show version')
            ports = device.send_command('show interfaces descriptions')
            mgmt = device.send_command('show conf interfaces vlan unit 101 | display set')
            mgmt_mx = device.send_command('show configuration interfaces irb | display set')

```

**Comment by ktbyers** [comment]
@theLORD97 Can you post the exception stack trace of a failed connection on a Juniper EX?

**Comment by theLORD97** [comment]
[root@ocg-sh-netscript1 tacacs_project]# python juniper_connect.py
Connecting
Connected to Juniper box, gathering info.....
configuring  tlirababppswt002 please stand by

there was an error connecting to tlirababppswt002


----------------------------------------------------------------------------------------------------


import time
from netmiko import ConnectHandler
#from netmiko import Netmiko
import re
import pprint
import os
#import xlsxwriter
import datetime
import smtplib
import mimetypes
from getpass import getpass



hostfile="/opt/scripts/Lord/tacacs_project/juniper_list.txt"
username = 'ssoares'
password = 'XXXXX'
platform = 'juniper_junos'

###### Open file that contains the list of devices

with open(hostfile) as f:
    for line in f:
        host = line.strip()
        try:
            print ("Connecting")
            device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
            time.sleep(1)
            print ('Connected to Juniper box, gathering info.....')
            version = device.send_command('show version')
            ports = device.send_command('show interfaces descriptions')
            mgmt = device.send_command('show conf interfaces vlan unit 101 | display set')
            mgmt_mx = device.send_command('show configuration interfaces irb | display set')

           *** bunch of other if statements in here *****


        except:
            #err = str(e)
            print "there was an error connecting to "+host+' \n\n'
            print (100*'-')
            f = open('Juniper_Exceptions.txt', 'a+')
            f.write('Could not connect to '+ host + '\n')
            f.close()

    device.disconnect()

**Comment by theLORD97** [comment]
I've tried multiple EX and MX devices and it seems to ONLY log into the MX ones.

**Comment by ktbyers** [comment]
You need to get rid of you blank exception handler so I see the actual exception message i.e. you need to get rid of your `try/except` (as you are hiding the error message).

**Comment by theLORD97** [comment]
sorry i'm confused, what did you want me to do?

**Comment by ktbyers** [comment]
You are hiding all of the error messages as far as why the EX is failing--here:

```
        try:
            print ("Connecting")
            device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
            time.sleep(1)
            print ('Connected to Juniper box, gathering info.....')
            version = device.send_command('show version')
            ports = device.send_command('show interfaces descriptions')
            mgmt = device.send_command('show conf interfaces vlan unit 101 | display set')
            mgmt_mx = device.send_command('show configuration interfaces irb | display set')

           *** bunch of other if statements in here *****


        except:
            #err = str(e)
            print "there was an error connecting to "+host+' \n\n'
            print (100*'-')
            f = open('Juniper_Exceptions.txt', 'a+')
            f.write('Could not connect to '+ host + '\n')
            f.close()
```

You need to get rid of the try/except and you probably need to test only against one failing device.

**Comment by theLORD97** [comment]
Hmmmmmm, once i removed the try/except statement it worked for the Juniper EX switches too.

**Comment by theLORD97** [comment]
i need to have that Try/Except in there tho, any ideas as to why it works when i remove those?

**Comment by ktbyers** [comment]
I would run it several times against an EX device that is known to fail and see if you can reproduce the failure (or not).

If you can't get the failure doing that, I would then try running it against all of the devices with no try/except (multiple times until you can reproduce the failure).

**Comment by OzNetNerd** [comment]
> i need to have that Try/Except in there tho

FYI @theLORD97, your code should specify which exception(s) you want to catch. Using the blanket `except` is not Pythonic (in other words, is bad practice).

The added bonus of doing this is that unexpected exceptions will still print to the console. Which in this case would make troubleshooting the issue much easier.

**Comment by theLORD97** [comment]
Hmmmmmmmmm, even more confused now...

I ran the same script as the very beginning Kirk and now it seems to be logging in and working fine. 

thanks for the tip OzNetNerd, i will fix the except portion of the code.

**Comment by ktbyers** [comment]
Okay, I am going to close this. If you are able to reproduce the problem and a stack trace, please feel free to re-open.

**Comment by theLORD97** [comment]
ok thanks, i'm going to run it on 200 devices tonight, so i'll keep you posted.... 

thx guys
