### ISSUE TITLE
ExtremeExosSSH.set_base_prompt()

### ISSUE THREAD

**Issue by dracoboros** [ktbyers/netmiko#1144]
Running "show system" in Extreme OS makes the device runs other commands like:

show switch
show version
show temperature

However, when "show temperature" is executed, Netmiko assumes the prompt value as "show temperature" as It can be seen in the following Traceback:

```
Traceback (most recent call last):
  File "<omitted>", line 21, in <module>
    out += conn.send_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/extreme/extreme_exos.py", line 53, in send_command
    self.set_base_prompt()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/extreme/extreme_exos.py", line 37, in set_base_prompt
    cur_base_prompt = super(ExtremeExosBase, self).set_base_prompt(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/base_connection.py", line 959, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: 'show temperature'
```

I tried to mess up with find_prompt but not success to make it work.

If you need any further information, please feel free to ask for it.

**Comment by dracoboros** [comment]
a-me-sw-ula-142-x460-01.1 # show temperature 
Field Replaceable Units               Temp (C)   Status   Min  Normal   Max
---------------------------------------------------------------------------
Switch         : X460-24t               31.50    Normal   -10    0-45  60
XGM3-2sf-A-1   :                        44.00    Normal   - 5    0-60  65
XGM3-2sf-A-1   : 
a-me-sw-ula-142-x460-01.2 #

**Comment by dracoboros** [comment]
the session_log output with sensitive information omitted:

```
hostname-exos.1 # 

hostname-exos.1 # disable clipaging

hostname-exos.2 # disable cli prompting

hostname-exos.3 # 

hostname-exos.3 # show system


show switch
SysName:          hostname-exos
SysLocation:      
SysContact:       
System MAC:       
System Type:      

SysHealth check:  Enabled (Normal)
Recovery Mode:    All
System Watchdog:  Enabled

Current Time:     
Timezone:        
Boot Time:        
Boot Count:       
Next Reboot:      None scheduled
System UpTime:     

Current State:    OPERATIONAL             
Image Selected:   primary                 
Image Booted:     primary                 
Primary ver:                      
                  
Secondary ver:       

Config Selected:  primary.cfg                                          
Config Booted:    primary.cfg                                          

primary.cfg       
                  

show version


Switch      :  
XGM3-2sf-A-1: 
PSU-1       : 
PSU-2       : 

Image   : 
          
BootROM : 
Diagnostics :

show temperature
```

**Comment by ktbyers** [comment]
@dracoboros Can you post your code (at least around this line):

```
  File "<omitted>", line 21, in <module>
    out += conn.send_command(cmd)
```

Have you tried running the individual commands: "show switch", "show version", "show temperature". Do those work if run independently?

**Comment by dracoboros** [comment]
When I run in ipython I get the properly output, however in a for loop it does not work.

**Comment by ktbyers** [comment]
Okay, I need to see your code (around that line 21).

**Comment by dracoboros** [comment]
My bad about last comment, I did not excluded the "show system" in the for loop.

However, when I replaced the "show system" for the other "show" commands the code stucked when "show ports description" was executed with the following traceback:

Traceback (most recent call last):
  File "<omitted>", line 21, in <module>
    out += conn.send_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/extreme/extreme_exos.py", line 53, in send_command
    self.set_base_prompt()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/extreme/extreme_exos.py", line 37, in set_base_prompt
    cur_base_prompt = super(ExtremeExosBase, self).set_base_prompt(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/base_connection.py", line 959, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: 'configure diffserv replacement priority 5 code-point 46'

the original show commands list is:
```
show system 
show process
show configuration
show ports description
show ports no-refresh 
show ports configuration no-refresh
show ports vid
show ports vlan
```

**Comment by ktbyers** [comment]
Does `show ports description` work if you execute it entirely by itself (i.e. without any other show commands being executed)?

**Comment by dracoboros** [comment]
It works fine.

In the next step, I had tried the "show system" (which output is very long) and it did not return everything. No exception was raised, however, the output was incomplete.

The "show" commands in Extreme OS are usually very slow, I tried to alter the find_prompt() method, but no success.

**Comment by dracoboros** [comment]
using <code>send_commaand_timing</code> worked even in for loops.

Since show commands in Extreme devices are usually slow, the delay helped to get the job done.

**Comment by dracoboros** [comment]
Just find out that <code>self.set_base_prompt()</code> inside <code>send_command</code> was causing the problem described in this issue.

**Comment by ktbyers** [comment]
@dracoboros Can you post the relevant section of your code? 

I think we need that special version of send_command for EXOS due to how EXOS has the index number that increments at the end of the prompt:

```
hostname-exos.1 # 

hostname-exos.1 # disable clipaging

hostname-exos.2 # disable cli prompting

hostname-exos.3 # 

hostname-exos.3 # show system
```

**Comment by dracoboros** [comment]
@ktbyers I have deleted the send_command from ExtremeExosBase (so it is using the parent class function)

and my code is:

```python
for cmd in cmds:
    print('Executing', cmd)
    out += conn.send_command(cmd)
```

I figure out why this workaround worked.

When the command <code>disable cli prompting</code> is executed, it stops to increment the prompt.

**Comment by dracoboros** [comment]
hostname was been captured in <code>if re.search(search_pattern, "".join(past_three_reads))</code> in send_command.

Creating PR to fix it.

**Comment by carlniger** [comment]
Closing since there is a PR for this, can discuss any further bits over there!
