### ISSUE TITLE
Netmiko SSH session with pubkey and password

### ISSUE THREAD

**Issue by volkovski** [ktbyers/netmiko#1149]
Hello,

is there any way to use in one netmiko session both pubkey or password auth ? Logic behind this is to try first pubkey auth and if it fails use pass auth ? Is it possible ? Thank you.

method_ssh = {
  'device_type': 'cisco_xr',
  'ip': 'IP',
  'username': 'username',
  'password': 'password',
  'allow_agent': True,
  'use_keys': True,
  'key_file': '/home/****/.ssh/id_rsa.pub',
  'verbose': True,
  'timeout': 5
}

**Comment by OzNetNerd** [comment]
As you may know, Netmiko uses [Paramiko in the background](https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L938). According to the [paramiko docs](http://docs.paramiko.org/en/2.4/api/client.html#paramiko.client.SSHClient.connect), it is supported:

> Authentication is attempted in the following order of priority:
> * The pkey or key_filename passed in (if any)
> * Any key we can find through an SSH agent
> * Any “id_rsa”, “id_dsa” or “id_ecdsa” key discoverable in ~/.ssh/
> * Plain username/password auth, if a password was given
>
> If a private key requires a password to unlock it, and a password is passed in, that password will be used to attempt to unlock the key.

**Comment by ktbyers** [comment]
Netmiko's authentication is all handled via Paramiko. You could alternatively write a try/except handler and try the first case then handle the exception and try it again.
