### ISSUE TITLE
Netmiko Module Installation issue

### ISSUE THREAD

**Issue by CDWAdamMason** [ktbyers/netmiko#1154]
Hello Kt, I seem to have an issue where my ide doesn't recognize the netmiko namespace during my import statements and the rest of my code as well (PyCharm/VSCode). I tried to research why and noticed that it isn't installing the module during the pip installation process to what I believe to be the correct parent folder. I believe my IDE's currently read from "c:\users\adam\appdata\roaming\python\python37\site-packages". 

Also based on the output below, it seems that it may not actually even be installing netmiko for some strange reason. I checked to insure there wasn't overlapping namespace with a saved file such as netmiko.py or netmiko.pyc, and there isn't.

Can you confirm the below installation process is correct?

```
`C:\Windows\system32>python -m pip install netmiko -vvv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Created temporary directory: C:\Users\Adam\AppData\Local\Temp\pip-ephem-wheel-cache-1elt2wfm
Created temporary directory: C:\Users\Adam\AppData\Local\Temp\pip-req-tracker-hkvxzegd
Created requirements tracker 'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-req-tracker-hkvxzegd'
Created temporary directory: C:\Users\Adam\AppData\Local\Temp\pip-install-6ataeln9
Requirement already satisfied: netmiko in c:\program files\python37\lib\site-packages (2.3.3)
Requirement already satisfied: setuptools>=38.4.0 in c:\program files\python37\lib\site-packages (from netmiko) (39.0.1)
Requirement already satisfied: paramiko>=2.4.2 in c:\users\adam\appdata\roaming\python\python37\site-packages (from netmiko) (2.4.2)
Requirement already satisfied: scp>=0.10.0 in c:\users\adam\appdata\roaming\python\python37\site-packages (from netmiko) (0.13.2)
Requirement already satisfied: pyyaml in c:\users\adam\appdata\roaming\python\python37\site-packages (from netmiko) (5.1)
Requirement already satisfied: pyserial in c:\users\adam\appdata\roaming\python\python37\site-packages (from netmiko) (3.4)
Requirement already satisfied: textfsm in c:\users\adam\appdata\roaming\python\python37\site-packages (from netmiko) (0.4.1)
Requirement already satisfied: bcrypt>=3.1.3 in c:\users\adam\appdata\roaming\python\python37\site-packages (from paramiko>=2.4.2->netmiko) (3.1.6)
Requirement already satisfied: pyasn1>=0.1.7 in c:\users\adam\appdata\roaming\python\python37\site-packages (from paramiko>=2.4.2->netmiko) (0.4.5)
Requirement already satisfied: pynacl>=1.0.1 in c:\users\adam\appdata\roaming\python\python37\site-packages (from paramiko>=2.4.2->netmiko) (1.3.0)
Requirement already satisfied: cryptography>=1.5 in c:\users\adam\appdata\roaming\python\python37\site-packages (from paramiko>=2.4.2->netmiko) (2.6.1)
Requirement already satisfied: six>=1.4.1 in c:\users\adam\appdata\roaming\python\python37\site-packages (from bcrypt>=3.1.3->paramiko>=2.4.2->netmiko) (1.12.0)
Requirement already satisfied: cffi>=1.1 in c:\users\adam\appdata\roaming\python\python37\site-packages (from bcrypt>=3.1.3->paramiko>=2.4.2->netmiko) (1.12.2)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\users\adam\appdata\roaming\python\python37\site-packages (from cryptography>=1.5->paramiko>=2.4.2->netmiko) (0.24.0)
Requirement already satisfied: pycparser in c:\users\adam\appdata\roaming\python\python37\site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.4.2->netmiko) (2.19)
Cleaning up...
Removed build tracker 'C:\\Users\\Adam\\AppData\\Local\\Temp\\pip-req-tracker-hkvxzegd'

C:\Windows\system32>C:\Users\Adam\AppData\Local\Programs\Python\Python37-32\Lib\site-packages
````

**Comment by CDWAdamMason** [comment]
Edit: I happen to notice when reading through the 

Requirement already satisfied: netmiko in c:\program files\python37\lib\site-packages (2.3.3)

which I some how missed earlier. I was able to find the module and copy it over manually to my roaming  site packages directory. Is there any install option to help assist with this in the future when working with pip from the command line, possibly an environmental variable?

**Comment by CDWAdamMason** [comment]
edit: When I went to compile my code I got a error message which I can only correlate to this posting https://bitbucket.org/cffi/cffi/issues/258/importerror-_cffi_backendso-symbol-not and I suspect is a result of me manually moving netmiko from one directory to another.

`Exception has occurred: ImportError
cannot import name '_bcrypt' from 'bcrypt' (C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\bcrypt\__init__.py)
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\bcrypt\__init__.py", line 25, in <module>
    from . import _bcrypt
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\paramiko\ed25519key.py", line 17, in <module>
    import bcrypt
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\paramiko\transport.py", line 90, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\netmiko\base_connection.py", line 22, in <module>
    import paramiko
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\netmiko\cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\netmiko\a10\a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\netmiko\a10\__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\netmiko\ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Users\Adam\AppData\Roaming\Python\Python37\site-packages\netmiko\__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Users\Adam\documents\!code\Python\.vscode\tkyup.py", line 4, in <module>
    from netmiko import ConnectHandler
  File "C:\Users\Adam\AppData\Local\Programs\Python\python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Adam\AppData\Local\Programs\Python\python37-32\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Adam\AppData\Local\Programs\Python\python37-32\Lib\runpy.py", line 263, in run_path`

**Comment by ktbyers** [comment]
@CDWAdamMason Your first issue is usually an IDE issue. For example, you are using a different Python for install than your IDE is using.

Your second issue, I would probably reinstall the latest 'bcrypt' using pip.

This makes me concerned. I would avoid doing this:

```
I was able to find the module and copy it over manually to my roaming site packages directory.
```

I would pretty strongly recommend you use PIP for all package management or you are likely going to have issues.

**Comment by CDWAdamMason** [comment]
> @CDWAdamMason Your first issue is usually an IDE issue. For example, you are using a different Python for install than your IDE is using.
> 
> Your second issue, I would probably reinstall the latest 'bcrypt' using pip.
> 
> This makes me concerned. I would avoid doing this:
> 
> ```
> I was able to find the module and copy it over manually to my roaming site packages directory.
> ```
> I would pretty strongly recommend you use PIP for all package management or you are likely going to have issues.

Is there a way to select installation path when using pip? I really am not strong enough with python yet to excel at making a script without intellisense with your docustring descriptions

**Comment by ktbyers** [comment]
I would think you could just install the packages using your IDE (or alternatively use 'python -m pip' where 'python' is the Python that your IDE uses).

Yes, totally not an issue using an IDE--it can be very beneficial.


Regards, Kirk
