### ISSUE TITLE
Nexus 9k - Maintenance Mode Prompt - Failed to detect

### ISSUE THREAD

**Issue by AuthenticAMD** [ktbyers/netmiko#1156]
Running netmiko 2.3.3

Unfortunately I am running the code on a isolated system so I can only reproduce output by typing it out.

There is a feature on the Cisco Nexus 9000 series called graceful insertion and removal. It will shutdown routing and vPC process for you to bring the device into a maintenance mode. It will also change the prompt from something like n9k-sw1# to n9k-sw1(maint-mode)#.
When it does the prompt switch, netmiko can no longer detect the prompt, with send_command. 

Thoughts on why this would happen?

```python
# This is setting device into maintenance mode. This works as expected
conn.send_command('config terminal', expect_string=r'#')
conn.send_command('system mode maintenance maint-delay 0', expect_string=r'#')
conn.send_command('system mode maintenance snapshot-delay 0', expect_string=r'#')
conn.send_command('no system mode maintenance always-use-custom-profile', expect_string=r'#')
conn.send_command('system mode maintenance', expect_string=r'\[no\]')
conn.send_command('yes', delay_factor=3, expect_string=r'#')
conn.send_command('end', expect_string=r'#')

# Find new prompt. Works as expected. Finds the prompt as 'n9k-sw1(maint-mode)#'.
prompt = conn.find_prompt()

# Test a command. Fails to find prompt with error: "OSError: Search pattern never detected in send_command_expect: n9k-sw1(maint-mode)#"
conn.send_command('show int status', expect_string=prompt)
```

**Comment by AuthenticAMD** [comment]
It seems like the netmiko is not expecting characters '(' and ')' in the prompt without being escaped. If I do the following, it seems to work fine.

prompt = conn.find_prompt() ! This has the prompt as 'n9k-sw(maint-mode)#'
prompt = prompt.replace("(", "\(")
prompt = prompt.replace(")", "\)")
! Prompt is now 'n9k-sw1\(maint-mode\)#

**Comment by ktbyers** [comment]
@AuthenticAMD This will very likely fail:

```
conn.send_command('show int status', expect_string=prompt)
```

Your prompt very likely has special regular expression characters in it--so you will need to do something like:

```python
import re

conn.send_command('show int status', expect_string=re.escape(prompt))
```

That is also why your manual escaping was needed.
