### ISSUE TITLE
https://pynet.twb-tech.com/blog/automation/netmiko-scp.html

### ISSUE THREAD

**Issue by kochargs** [ktbyers/netmiko#1159]
Regarding https://pynet.twb-tech.com/blog/automation/netmiko-scp.html
Can't i reference the SCP server via ip address instead.

I can run the code from a machine but that same machine can't become SCP server. 
Can this code cater to this ?

I am able to do it via expect_String manually but i was hoping since this module already has inbuilt checks and all i could use this for my purpose.

Thanks

**Comment by ktbyers** [comment]
@kochargs On the IP address question--you mean here?

```
cisco = { 
    'device_type': 'cisco_ios',
    'host': 'device1.domain.com',
    'username': 'admin',
    'password': password,
    'file_system': 'flash:'
}
```

Yes, you can just switch from a DNS name to an IP address in the "host" field.

Question 2:
----
I can run the code from a machine but that same machine can't become SCP server.
Can this code cater to this ?
----

The network device is the SCP server--so no this code doesn't support the Linux Server being the SCP server (if I understood your question)?


Kirk

**Comment by kochargs** [comment]
I meant for a topology like this .....

router_that_needs_ios----------------SWITCH-----------------SCP_server(IOS hosted here)
                                                               |
                                                               |
                                           Python running on this machine

I could write something like this

cisco = { 
    'device_type': 'cisco_ios',
    'host': 'router_that_needs_ios',
    'username': 'admin',
    'password': password,
    'file_system': 'flash:'
}

But how do i tell the code to pick the IOS from the SCP server instead and not from the machine that is running the python code ??

**Comment by kochargs** [comment]
If i write a test code like this, it gets the job done but i would like to be able to use the inbuilt module and the inbuilt checks for this purpose instead.

Routers = {
            'device_type': 'cisco_ios_ssh',
            'ip': device_that_needs_ios_upgrade,
            'username': 'tiger',
            'password': 'lab',
            'secret': 'lab',
            'verbose': True,
            }
net_connect = ConnectHandler(**Routers)
hostname = net_connect.find_prompt()
print "SSH to " + hostname[0:-1],  " successful"


cmd = 'copy scp://tiger@192.168.62.134/vios_l2-adventerprisek9-m unix:'
srv_pass = 'lab'

print "sending 1st command"
output = net_connect.send_command(cmd, expect_string=r'Destination filename')
print output
print "sending 2nd command"
output = net_connect.send_command('\n', expect_string=r'Password')
print output
print "third command"
output = net_connect.send_command(srv_pass, expect_string=r'#', delay_factor=5)
print output

**Comment by ktbyers** [comment]
The Netmiko SCP code is entirely push from the Linux server to the network device so it requires SCP server process to be running on the networking device.

So your above solution won't work with those built-in methods. You can do the above and it is reasonably common, but you won't be able to use the built-in methods with that.

**Comment by kochargs** [comment]
Alright, thanks for clarification. I guess i should be able to add the checks and verification manually in the code. Btw if i were in need of only copying IOS to a bunch of devices and not upgrade them, just putting the IOS on flash of each device, what is the best method you would recommend using custom scripts ? I don't have any off the shelf usual solutions for this purpose.

**Comment by ktbyers** [comment]
On this question:

```
Btw if i were in need of only copying IOS to a bunch of devices and not upgrade them, just putting the IOS on flash of each device, what is the best method you would recommend using custom scripts ?
```

I would use the Netmiko SCP file transfer mechanism to stage the OS in the flash.
