### ISSUE TITLE
Truncated first line of the show output

### ISSUE THREAD

**Issue by kubikus** [ktbyers/netmiko#1160]
Hi,
Because the switch display only few lines of each show command and doesn't support all lines concurrently (doesn't support the "terminal length 0" command), it is need to touch the space key to display more lines.
I implemented a while loop which checks whether there is still the prompt requesting touch of the space. It works however, the netmiko doesn't add the first line of the telnet data into the output string.
As you can see on the attached screen, the PC receives the telnet packet, which contains the "MAC-Learning   :Yes" string on the first line (highleted in the red rectangle). However, the string is not seen in the output of print(output) which I logged into a file (see the right side of the screen).

Could you please check it and tell me why is the line truncated? Is it due to some not supported hexa character?

The example is for telnet, but it is same for ssh (cisco_ios). 

Screen:
https://ibb.co/r7Dfd7g

> EC= {
>     "host": "10.33.222.4",
>     "username":"admin",
>     "password": password,
>     "device_type":"cisco_ios_telnet",
>     "secret": password,
> }

> output = net_conn.send_command_timing(r"show interface status")
> end = re.search("---$", output).group(0)
> print("before while")
> print(output)
> #check whether there is still request for space
> while end == "---":
>    #send space to continue
>    output += net_conn.send_command_timing(" ", normalize=False)
>    print("while loop:")
>    print(output)
>    #when no space request then returned exception
>    try:
>       end = re.search("---$", output).group(0)
>    except AttributeError:
>       end = "thats all"
> print(output)   

Best regards
Jakub

**Comment by kochargs** [comment]
Hi Jakub,

Although netmiko has inbuilt term len 0 command but since the switch in question doesn't support that command, you should be exploring more about send_command(cmd, expect_string = '') to make it work. A sample of which can be found here
https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html

**Comment by kubikus** [comment]
Hi kochargs,
I can use the expect_string to check the end. However, my while loop works fine. The PC receives correct data (include the first line), but the netmiko doesn't add the line into the string.

**Comment by kochargs** [comment]
You could try this for a deeper look into the read channel.

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

**Comment by kubikus** [comment]
On the base of the logging, it seems like the Netmiko truncates lines which contain backspace (0x08 char).
https://ibb.co/ZzCxDLz

Do you know the reason?

>   LACP                   : Disabled
> 
> --- [Space] Next page, [Enter] Next line, [A] All, Others to exit ---
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b' '
> DEBUG:netmiko:read_channel:                         
> DEBUG:netmiko:read_channel:                                                MAC-Learning           : Yes
> 
>  Current Status: 
> 
>   Link Status

**Comment by kochargs** [comment]
I think this was a limitation where netmiko won't handle backspace character in the command echo
found it here ( i don't know what is meant by echo of command here )
https://github.com/ktbyers/netmiko/pull/939

Hopefully someone sees it soon and provides a proper RCA and a fix for this

**Comment by kubikus** [comment]
Hi kochargs,
thank you very much, you really helped me.
When you told me that something similar had been addressed in the past, then I checked the code of the Netmiko and found the "def strip_command(,,)" function in the base_connection.py file.
The function checks whether the output contains backspaces and if so, then doesn't add the first line into the output. 
I changed the code to add even the first line and now I see all lines in my output.
The first line received by the Cisco switches probably contains only backspaces and it would display just empty line. However, I do tests on the Edge-core switches where the first line contains backspaces and also text, so the original code truncates this needed text.

```
#orig code:
#new_output = output_lines[1:]

#my code:
new_output = output_lines[0:]
```

**Comment by kochargs** [comment]
Happy to help, glad you were able to figure out the solution. I am too new to python/programming to be able to provide any solution all by myself.
