### ISSUE TITLE
Using LinuxSSH Transfer?

### ISSUE THREAD

**Issue by Abed1985** [ktbyers/netmiko#1161]
I would like to create a script on host-local to login to another linux server (host-remote) and issue the below commands for transfering a file with a single line or multiple lines , example on remote server:

abooda@host-remote:/data/log/network/client$ cd  /data/log/network/client
abooda@bne-syslog-03:/data/log/network/client$ scp client_firewall.log-20190403.gz host-local:/home/abooda/Ansible-Playbooks/client_cpe.log
abooda@host-local's password: 
client_firewall.log-20190403.gz                                                                                                                                              100% 8526KB   8.3MB/s   00:00    
abooda@host-remote:/data/log/network/client$

-password authentication for the 1st session , then another authentication per scp file transfer , and maybe their is multiple. is this doable with LinuxSSH transfer ? I have no idea if this is doable and how it works , can you please provide an example ?

**Comment by kochargs** [comment]
Sounds like this could help
https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

**Comment by Abed1985** [comment]
Thanks , but this is not what am looking for . Am looking for scp using the limuzssh transfer built in netmiko or a work around this

**Comment by Abed1985** [comment]
I will use pysftp for the purpose its very handy :)
