### ISSUE TITLE
Problem with Arista enable/configure terminal

### ISSUE THREAD

**Issue by gaussk32** [ktbyers/netmiko#1168]
I have a problem i connect to an Arista device but i got an error if I try to get in configure terminal mode this is my code:

```python
#!/usr/bin/env python
from netmiko import Netmiko
from getpass import getpass
from time import sleep
nxos1 = {
    "host": "172.16.12.6",
    "username": "gag",
    "password": "xxxxx",
    "device_type": "arista_eos",
    "secret":"xxxx"
}

commands = ["conf t","show version"]
net_connect = Netmiko(**nxos1)

print()
net_connect.enable()
sleep(1)
output = ''
for cmd in commands:
     output += net_connect.send_command(cmd, delay_factor=4)
print(output)
```

and i get this error:
()
Traceback (most recent call last):
  File "multipleArista.py", line 23, in <module>
    output += net_connect.send_command(cmd, delay_factor=2)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1188, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: ARISTA\.TIJ\.Shelter\#

**Comment by ktbyers** [comment]
You are going into config mode here which will cause the prompt to change:

```
commands = ["conf t", "show version"]
```

If you just want to execute `show version` then use send_command("show version").

If you want to execute config changes then use send_config_set(cfg_commands) and Netmiko will automatically handle entering/exiting config mode.
