### ISSUE TITLE
ImportError: cannot import name 'Netmiko' from 'netmiko' (unknown location)

### ISSUE THREAD

**Issue by jgeleta** [ktbyers/netmiko#1169]
Hello,

I am working on a shared jump server and my scripts cannot load Netmiko for anyone except for myself. The paths Python will check are identical:

 'C:\\Program Files\\Python37\\python37.zip',
 'C:\\Program Files\\Python37\\DLLs',
 'C:\\Program Files\\Python37\\lib',
 'C:\\Program Files\\Python37',
 'C:\\Program Files\\Python37\\lib\\site-packages']

And while I get this:
>>> from netmiko import Netmiko
>>>

My coworkers get this:
>>> from netmiko import Netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Netmiko' from 'netmiko' (unknown location)

I do not have any files called netmiko.py or netmiko.pyc and netmiko was installed here: C:\Program Files\Python37\Lib\site-packages\netmiko

**Comment by ktbyers** [comment]
I would look at the following for the working case:

```
$ python
Python 3.6.8 (default, Mar 18 2019, 18:57:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__file__
'/home/ktbyers/VENV/py3_venv/local/lib/python3.6/site-packages/netmiko/__init__.py'
```

And also verify that the Python being used is identical in both cases.

**Comment by jgeleta** [comment]
Hello,

We're using the same version of Python: Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit(AMD64)] on win32. But where I receive the following:

>>> import netmiko
>>> netmiko.__file__
'C:\\Program Files\\Python37\\lib\\site-packages\\netmiko\\__init__.py'
>>>

My colleague receives this:
>>> import netmiko
>>> netmiko.__file__
>>>

**Comment by jgeleta** [comment]
Hello,

This turned out to be a Windows permission issue. Although my colleagues had permission to access the subfolders, the way the permissions were cascaded down to those subfolders required them to manually click the folder, confirm they want to access the folder and then proceed. We changed how the subfolder inherited permissions and now everyone can use the Python37 subfolders.

Thanks for the help.
