### ISSUE TITLE
Save Running Configuration

### ISSUE THREAD

**Issue by spirrello** [ktbyers/netmiko#117]
Hi,

When I run the following command in my python script it never seems to finish successfully.  Have you seen this problem yet?

net_connect.send_command("write mem")

net_connect.send_command("write)

**Comment by ktbyers** [comment]
What platform / OS version are you doing this on? This works for me on a Cisco 881 running IOS version  Version 15.4(2)T1.

>>> from netmiko import ConnectHandler
>>> net_connect = ConnectHandler(**pynet1)
SSH connection established to x.x.x.x:22
Interactive SSH session established
>>> net_connect.send_command("write mem")
u'Building configuration...\n'
>>> net_connect.send_command("write")
u'Building configuration...\n'

What happens when you execute the command manually (i.e. what do you see in the SSH session)?

**Comment by spirrello** [comment]
Thanks for the quick response.  It is working, one of my other processes was keeping this line in my script from completing.  Thanks!

Sent from Outlook<http://aka.ms/Ox5hz3>




On Wed, Sep 23, 2015 at 9:56 AM -0700, "Kirk Byers" <notifications@github.com<mailto:notifications@github.com>> wrote:


What platform / OS version are you doing this on? This works for me on a Cisco 881 running IOS version Version 15.4(2)T1.

from netmiko import ConnectHandler
net_connect = ConnectHandler(**pynet1)
SSH connection established to x.x.x.x:22
Interactive SSH session established
net_connect.send_command("write mem")
u'Building configuration...\n'
net_connect.send_command("write")
u'Building configuration...\n'

What happens when you execute the command manually (i.e. what do you see in the SSH session)?

-

**Comment by vipbhati** [comment]
Hi,

I am trying to save the memory of a router IOS. It gives me the following error :

![image](https://cloud.githubusercontent.com/assets/25195283/22055935/8b68cc0a-dd83-11e6-8b4b-5457498f6c62.png)

When I execute the command manually , i need to hit enter after the "confirm" message:
Router#wr mem
Warning: Attempting to overwrite an NVRAM configuration previously written
by a different version of the system image.
Overwrite the previous NVRAM configuration?[**confirm**]


I am using Cisco IOS Software, 7200 Software (C7200-ADVENTERPRISEK9-M), Version 15.2(4)S4, RELEASE SOFTWARE (fc2).

Is there a way to save the config ?

**Comment by TomCos** [comment]
This is a duplicate of this
https://github.com/ktbyers/netmiko/issues/610
