### ISSUE TITLE
Netmiko and multithreading pools 

### ISSUE THREAD

**Issue by Abed1985** [ktbyers/netmiko#1170]
Can Anybody tell me whats wrong with this ? what am missing here ? 

```
import yaml

import warnings
from multiprocessing.dummy import Pool as ThreadPool
from netmiko import Netmiko

warnings.filterwarnings("ignore")


filename = "devices.yml"

with open (filename) as f:
    output = yaml.load(f)
for key,value in output.items():
    dev = value
    print(dev)


def get_prompt (dev):
    net_conn = Netmiko(**dev)
    prompt = net_conn.find_prompt()
    print (prompt)


num_threads_str = input("Number of threads : ")
num_threads = int(num_threads_str)


threads = ThreadPool (num_threads)
results = threads.map ( get_prompt , dev )

threads.close()
threads.join()

def get_prompt (dev):
    net_conn = Netmiko(**dev)
    prompt = net_conn.find_prompt()
    print (prompt)


num_threads_str = input("Number of threads : ")
num_threads = int(num_threads_str)


threads = ThreadPool (num_threads)
results = threads.map ( get_prompt , dev )

threads.close()
threads.join()
```

```
abooda@server$ ipython3 **-i** show_mac2.py 
{'host': 'x.x.x.x', 'username': 'abooda', 'password': 'xxxxx', 'device_type': 'cisco_ios'}
{'host': 'x.x.x.x', 'username': 'admin', 'password': 'HPxxxxw1tch', 'device_type': 'hp_procurve'}
{'host': 'x.x.x.71', 'username': 'sadmin', 'password': '#xxxx#', 'device_type': 'huawei'}
{'host': 'x.x.x.20', 'username': 'admin', 'password': 'H!jxxxcK23', 'device_type': 'dell_os6'}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Network-Discovery/MAC-CDP-LLDP/show_mac2.py in <module>
     28 
     29 threads = ThreadPool (num_threads)
---> 30 results = threads.map ( get_prompt , dev )
     31 
     32 threads.close()

/usr/lib/python3.6/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    286         in a list that is returned.
    287         '''
--> 288         return self._map_async(func, iterable, mapstar, chunksize).get()
    289 
    290     def starmap(self, func, iterable, chunksize=None):

/usr/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    668             return self._value
    669         else:
--> 670             raise self._value
    671 
    672     def _set(self, i, obj):

/usr/lib/python3.6/multiprocessing/pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    117         job, i, func, args, kwds = task
    118         try:
--> 119             result = (True, func(*args, **kwds))
    120         except Exception as e:
    121             if wrap_exception and func is not _helper_reraises_exception:

/usr/lib/python3.6/multiprocessing/pool.py in mapstar(args)
     42 
     43 def mapstar(args):
---> 44     return list(map(*args))
     45 
     46 def starmapstar(args):

~/Network-Discovery/MAC-CDP-LLDP/show_mac2.py in get_prompt(dev)
     18 
     19 def get_prompt (dev):
---> 20     net_conn = Netmiko(**dev)
     21     prompt = net_conn.find_prompt()
     22     print (prompt)

**TypeError: ConnectHandler() argument after ** must be a mapping, not str**

In [1]:              
```

while this works fine :

```
import yaml
import pprint
import warnings
from netmiko import Netmiko
warnings.filterwarnings("ignore")
filename = "devices.yml"
with open (filename) as f:
    output = yaml.load(f)
for key,value in output.items():
    net_conn = Netmiko(**value)
    print (net_conn.find_prompt())
```

issue with loading the device to the netmiko this way ? it doesnt work unless i put the value in the dictionary directly in the netmiko function ?

**Comment by OzNetNerd** [comment]
I haven't had a chance to go through your code. FYI though, there's a working multithreading example [here](https://github.com/ktbyers/netmiko/blob/develop/examples/use_cases/case16_concurrency/threads_netmiko.py) which may be of use to you.

**Comment by ktbyers** [comment]
@Abed1985 On quick glance, I think you are using map wrong given the value you assign to dev

```
# assigning of dev
for key,value in output.items():
    dev = value
    print(dev)

# Second location
results = threads.map ( get_prompt , dev )
```

**Comment by Abed1985** [comment]
> 
> 
> @Abed1985 On quick glance, I think you are using map wrong given the value you assign to dev
> 
> ```
> # assigning of dev
> for key,value in output.items():
>     dev = value
>     print(dev)
> 
> # Second location
> results = threads.map ( get_prompt , dev )
> ```

Thanks Ktbyers , what I am not sure , can you please point that out . I am assigning dev as the value from the dictionary then threading on each dev value in threads.map ? is that wrong , below is a clean code again :

`import yaml

import warnings
from multiprocessing.dummy import Pool as ThreadPool
from netmiko import Netmiko

warnings.filterwarnings("ignore")


filename = "devices.yml"

with open (filename) as f:
    output = yaml.load(f)

for key,value in output.items():
    dev = value
    print(dev)


def get_prompt (dev):
    net_conn = Netmiko(**dev)
    prompt = net_conn.find_prompt()
    print (prompt)


num_threads_str = input("Number of threads : ")
num_threads = int(num_threads_str)


threads = ThreadPool (num_threads)
results = threads.map ( get_prompt , dev )

threads.close()
threads.join()
`

**Comment by ktbyers** [comment]
Given what you are doing...map() is expecting a list of device dictionaries not a single device dictionary. If you want to have it work for a single device, you can possibly do the below:

```
# note dev has been wrapped in a list
results = threads.map ( get_prompt , [dev] )
```

With what you are currently doing map() is calling get_prompt using the keys() of dev. So for example it will call get_prompt and pass in only the string "host". Then it will call get_prompt() again and pass in only the string "username", et cetera.

See here for documentation on map:

https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.pool

**Comment by Abed1985** [comment]
Many thanks !! I modified the code per below and working :) 

`
import yaml

import warnings
from multiprocessing.dummy import Pool as ThreadPool
from netmiko import Netmiko

warnings.filterwarnings("ignore")


filename = "devices.yml"

with open (filename) as f:
    output = yaml.load(f)
dev_2 = []
for key,value in output.items():
    dev = value
    dev_2.append(dev)
    print(dev)

print (dev_2)

def get_prompt (dev):
    net_conn = Netmiko(**dev)
    prompt = net_conn.find_prompt()
    print (prompt)


num_threads_str = input("Number of threads : ")
num_threads = int(num_threads_str)


threads = ThreadPool (num_threads)
results = threads.map ( get_prompt , dev_2 )

threads.close()
threads.join()`
