### ISSUE TITLE
Is it possible to select enable level?

### ISSUE THREAD

**Issue by avloboda** [ktbyers/netmiko#1172]
When creating a connection, is it possible to select the enable secret level? For example, if an 'enable secret level 14' is set on a device itself, but not on the user account.

So to get into privilege mode, the user has to input _enable 14 password_

Is it possible for Netmiko to navigate that and select the enable secret level?

**Comment by ktbyers** [comment]
@avloboda Can you show what this looks like for the user account in a manual SSH session?

**Comment by avloboda** [comment]
`$ssh johndoe@192.168.1.1`
`Password: accountpasswordhere`
`>`
`>enable 14`
`Password: enablepasswordhere`
`#`user is now in privileged EXEC mode


On IOS, the commands that would require the above sequence would look like this:
`(config)#enable secret level 14 password`
`(config)#username johndoe secret password`

I'm not sure if this is what you were looking for, let me know if I can provide more information. Thank you.

**Comment by OzNetNerd** [comment]
This should do the trick:

```
conn = ConnectHandler(
    device_type='cisco_ios',
    ip=ip,
    username=username,
    password=password,
    secret=enable_secret
)

conn.enable(cmd='enable secret level 14 password')
```

**Comment by OzNetNerd** [comment]
This should do the trick:

```
conn = ConnectHandler(
    device_type='cisco_ios',
    ip=ip,
    username=username,
    password=password,
    secret=enable_secret
)

conn.enable(cmd='enable secret level 14 password')
```

**Comment by ktbyers** [comment]
What @OzNetNerd posted should work.

**Comment by stevenixng** [comment]
I'm trying to get this to work, but my problem is the connection is made and `enable` is ran (and fails) before the script gets to `conn.enable(cmd='enable 10')`.

How can I have ConnectHandler not run `enable` when `secret` is provided, or set the command to `enable 10` during connection?

**Comment by ktbyers** [comment]
@stevenixng What is the context where this is happening? Which platform are you using or are you using some other framework this happens in?

**Comment by stevenixng** [comment]
Thanks for taking the time to respond. Here is how I am using it with a Cisco ASA. No other framework.

```
from netmiko import ConnectHandler

net_connect = ConnectHandler(device_type='cisco_asa',
                             host=hostname,
                             username=username,
                             password=password,
                             secret=secret)
net_connect.enable(cmd='enable 10')
```

**Comment by nautics889** [comment]
> @stevenixng What is the context where this is happening? Which platform are you using or are you using some other framework this happens in?

What he ment is that in `CiscoAsaSSH` in [`.session_preparation()` method](https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_asa_ssh.py#L26) the connection object is trying to enter enable mode in case `secret` was provided:
```
    def session_preparation(self) -> None:
        ...
        if self.secret:
            self.enable()
        else:
            self.asa_login()
        ...
```
Futhermore `.enable()` method in a snippet above is called withod specifying any custom command, so `cmd` would be as default (`"enable"`) as it's defined in a method's signature:
```
def enable(
        self,
        cmd: str = "enable",  # that is the point
        pattern: str = "ssword",
        enable_pattern: Optional[str] = r"\#",
        re_flags: int = re.IGNORECASE,
    ) -> str:
```

So anyway when you create `ConnectHandler` for Cisco with secret, like:
```
net_connect = ConnectHandler(device_type='cisco_asa',
                             host=hostname,
                             username=username,
                             password=password,
                             secret=secret)
```
the enable mode will be activated without specifying privilege level.

**Comment by ktbyers** [comment]
Probably could overwrite the class:

```python
from netmiko.cisco.cisco_asa_ssh import CiscoAsaSSH

class MyAsaClass(CiscoAsaSSH):
    def enable(
        self,
        cmd = "enable 10",          # whatever command you want to put there
        **kwargs
    ) -> str:
        return super().enable(
            cmd=cmd, **kwargs
        )
 ```

I am not seeing an easier way to do that, but the above should (roughly) work. I say roughly as I didn't test it, but it should show the pattern that would work.
