### ISSUE TITLE
Accedian - manager-commands-mode

### ISSUE THREAD

**Issue by sm3ulc** [ktbyers/netmiko#1181]
The Accedian SkyDir server has "configuration-mode" but it is named  "manager-commands-mode" instead, resulting in the following change of prompt:

Manager#
Manager# mgr-commands
Manager/mgr#

Possible to add this? I'll be happy to support with testing.

**Comment by carlniger** [comment]
You may want to check out "expect_string" as documented about mid way down [this blog post]( https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html). Ive not heard of Accedian, but a quick search looks like its maybe just a *nix server w/ some special prompt -  maybe you can administer it w/ Ansible or similar too which may be easier.

**Comment by sm3ulc** [comment]
Thanks! I'll check it out.
