### ISSUE TITLE
Specific Username/Password Combo yields "Socket is Closed" on Cisco 8510 WLC

### ISSUE THREAD

**Issue by David00** [ktbyers/netmiko#1184]
This issue is a continuation of the problem I reported here:
https://www.reddit.com/r/learnpython/comments/bgzajr/im_having_the_strangest_issue_with/

In summary:
I have a short Netmiko script that works with one set of credentials but doesn't work with a different set of credentials.  (See the code in my original Reddit post). Both sets of credentials work in a non-scripted manner (via PuTTY or terminal SSH).  

When Netmiko is using the non-working credential set, I see the following output (with Verbose: True in the device definition)

    SSH connection established to 172.28.113.165:22
    Interactive SSH session established
    Socket is closed

I've enabled Netmiko logging per ktbyers' recommendation and here is the logging output for the working credential set and the non-working credential set.
[SuccessfulAuth.log](https://github.com/ktbyers/netmiko/files/3117611/SuccessfulAuth.log)
[UnSuccessfulAuth.log](https://github.com/ktbyers/netmiko/files/3117612/UnSuccessfulAuth.log)

It seems that the attempt with the credentials that don't work is trying to send the username again when the password is requested.

**Comment by David00** [comment]
Here's some additional info and perhaps confirmation as to what the unsuccessful auth log is showing.

Logins to the device I'm trying to login to are controlled via TACACS. I've checked the TACACS server logs and can confirm that it is reporting an incorrect password. This supports the behavior seen in the unsuccessful log where Netmiko seems to be sending the username instead of the password.

**Comment by ktbyers** [comment]
Fixed here:

#1185

**Comment by ktbyers** [comment]
This is the old code, before the fix I submitted above:

```
        while i <= 12: 
            output = self.read_channel()
            if output:
                if "login as" in output or "User" in output:
                    self.write_channel(self.username + self.RETURN)
                elif "Password" in output:
                    self.write_channel(self.password + self.RETURN)
                    break
                time.sleep(delay_factor * 1)
```

Basically it searches for the string "User" in the output. Unfortunately, your username has "User" in it. Consequently, it keeps thinking the WLC is prompting for the username and the code keeps sending the username :-)

I fixed by qualifying it with a colon i.e. "User:"

So you can either switch your username to something that doesn't have "User" in it or alternatively, you can install the `develop` branch once I merge the above PR.


Regards, Kirk

**Comment by David00** [comment]
Aha! Yes, my actual username does have the string "User" in it. Corporate controlled usernames - ugh.  I see that you've merged 1185 into `develop` so I'll pull that now and give it a try. Might take me a little while as I'm still new to Git :)

Will this eventually make its way into the build that `pip` installs? 

Thanks again for your prompt assistance!

**Comment by ktbyers** [comment]
You can install it as follows:

```
pip install git+https://github.com/ktbyers/netmiko@bce8698bda871464359ac499e510c08ba7b56dc2#egg=netmiko
```

You might need to `pip uninstall netmiko` first.

Yes, it will eventually be in the released version of Netmiko, but not sure when I will do the next release.

The above command will freeze you at the develop branch as of the time of that WLC commit.

**Comment by David00** [comment]
Thanks ktbyers. I ended up just downloading the zip and replacing everything in my virtualenv site-packages folder for netmiko. Took me awhile to get my account "unlocked" from my corporate company side, but now that it is, I can confirm the fix is working for me. Thanks again!
