### ISSUE TITLE
Cisco_WLC TextFSM NTC Templates Unable to find - need to use device_type: cisco_wlc_ssh

### ISSUE THREAD

**Issue by jvanderaa** [ktbyers/netmiko#1186]
With the NTC-Templates, they are named cisco_wlc_ssh. So if Netmiko has a device_type of `cisco_wlc` then the NTC-Template does not get found. Should this be handled as an update within Netmiko code or look to have the NTC-Templates name changed?

This works to find the NTC Templates in the home directory:
```
"device_type": "cisco_wlc_ssh",
```

While this will not:
```
"device_type": "cisco_wlc",
```

**Comment by ktbyers** [comment]
Just use `cisco_wlc_ssh` on the Netmiko side--that should be supported as well in Netmiko. 

It could be fixed in ntc-templates, but it is probably not worth it (since there is no telnet driver for Cisco WLC).
