### ISSUE TITLE
Check and modify running config using re.search

### ISSUE THREAD

**Issue by nexty5870** [ktbyers/netmiko#1188]
Hi, I'm running out of idea on the below python script I've worked on,

what the script does is:

1) do a show running config
2) search for the hostname 
3) use a regex expression to get confirm it match some standard
if it match, no prob, if it doesn't match if statement

on that if statement the user input the new hostname, and the hostname got changed and should return to the main menu

however the script hang, after 5 min it return the following error:

IOError: Search pattern never detected in send_command_expect: TESttt\(config\)\#

but I can confirm that the script did change the hostname, it just never return to the main function

I believe this is because netmiko "cash" the instance

here is my function

```
def hostname_check():
    pattern = re.compile(r"^([A-Z]{5})\-(\bSW[0-9][0-9])\-[0-9][0-9]\-(?:MDF|IDF)")
    conn.config_mode()
    run_conf = conn.send_command('show running-config')
    hostname_g = re.search(r"\bhostname\s(?P<quote>['\"])(?P<string>.*?)\"",str(run_conf))
    hostname = hostname_g.group().split(" ")[1]    
    hostn = pattern.match(eval(hostname))
    if hostn:
        print('Hostname is matching the standard!')
        print (hostn.group())
    else:
        print"""
               ----------------------------------
                Hostname is not configured proprely\n
                    1.Configure hostname
                    2.Main menu\n
               ----------------------------------"""
        s = input ('select: ')
        if s == 1:
            newhost = raw_input('Input your Hostname (MARSHA-00-00-MDF/IDF): ')
            conn.send_command('hostname ' + newhost)
            print('OK')
            conn.exit_config_mode()
            main()
        else:
            conn.exit_config_mode()
            main()
```

note the Print'OK', 

if I try to change the hostname for the actual hostname set on the switch, it print the OK and continue to the main()

is there a way to somehow have it working if a config is change after the initial show running config is performed?

thanks

**Comment by carlniger** [comment]
@nexty5870 Hi. I'd recommend not parsing the whole show run just to find the hostname,  you can simply use `conn.find_prompt()` or `conn.base_prompt`, or simply run a "show hostname" (depending on your platform of course). 

As for netmiko not picking up the prompt, if you run this as a `send_config_set` rather than a send command your problem will likely be resolved: `conn.send_config_set(['hostname some_cool_hostname'])`

**Comment by nexty5870** [comment]
@carlniger Hey! I've spend the whole day scratching my head! it worked!!!! thanks for that, I'm new with netmiko so not sure that my method is the best ( clearly not ) 

show hostname is not available ( this is an Aruba switch for testing ) 

does the conn.find_prompt() is meant to be finding some specific string? 

thanks a lot
