### ISSUE TITLE
Import Error: module 'netmiko' has no attribute 'ConnectHandler'

### ISSUE THREAD

**Issue by ricardo-ml** [ktbyers/netmiko#1191]
I want to use netmiko in my project. so i install netmiko by pip install command. but i cann't use connect handler.  
My OS: windows 7
Python version: 3.6.8
netmiko version: 2.3.3

My code:
from netmiko import ConnectHandler
cisco = {
    'device_type':'cisco_ios',
    'ip':'10.1.1.10',
    'port':22,
    'username':'admin',
    'password': 'test1234',
    'secret':'test1234',
}
conn = ConnectHandler(**cisco)
output = conn.send_command('sh int ip b')
print(output)

Error Message:
Traceback (most recent call last):
      File "C:\Users\Lenovo\Desktop\netmiko.py", line 1, in <module>
        from netmiko import ConnectHandler
      File "C:\Users\Lenovo\Desktop\netmiko.py", line 1, in <module>
        from netmiko import ConnectHandler
ImportError: cannot import name 'ConnectHandler'

**Comment by ktbyers** [comment]
@ricardo-ml It looks like you created a file named netmiko.py and consequently it is trying to use that and not the Netmiko library.

**Comment by ricardo-ml** [comment]
@ktbyers  It fixed.  Thank you so much.
