### ISSUE TITLE
unable to pass configs where mode changes

### ISSUE THREAD

**Issue by cobeank** [ktbyers/netmiko#1194]
Trying to execute a simple script to add a vlan to a Cisco NXOS switch.  The configuration I want entered is the following:

vlan 3000
  name TEST_VLAN

I'm using the following script...

vlan = input("Please enter the VLAN number: ")
vlan_name = input("Enter the name of the VLAN: ")

command1 = ("vlan " + vlan)
command2 = ("name " +  vlan_name)

def inform():
    print("Sending the following configuration commands to the Nexus switches:")
    print( )
    print(command1)
    print(command2)
    print( )
    print( )
    print("*" * 80)

##########################################
# Begin pushing configuration Change #####
##########################################

def push_change(my_device):
    net_connect = ConnectHandler(**my_device)
    net_connect.find_prompt()
    output1 = net_connect.send_config_set(command1, command2)
    print(output1)
    print( )
    print("Saving config")
    print( )
    net_connect.save_config()

############################################
############################################

def show_main():
    start_time = datetime.now()

    for my_device in devices:
        my_proc = Process(target=push_change, args=(my_device,))
        my_proc.start()

the first command is entered in "config" mode.  The second command is entered in "vlan-config" mode.  The problem I'm having is that the switch exits config mode after the first command and re-enters it to input the second command, but is in the wrong mode, so the command fails.

How can I stay in vlan configuration mode to enter subsequent commands?

**Comment by carlniger** [comment]
You need to provide `send_config_set` a list as the argument. See #1189 

For your code this works: `output1 = net_connect.send_config_set([command1, command2])`
