### ISSUE TITLE
Problem with a concurrence and cpu

### ISSUE THREAD

**Issue by dobicz** [ktbyers/netmiko#1199]
Hello,

I'm using the example: https://github.com/ktbyers/netmiko/blob/develop/examples/use_cases/case16_concurrency/processes_netmiko_queue.py, the idea is to simultaneously run a command that returns the routing table of the equipment, so far well, detail is that the routing table is very large, in some cases I have almost 60 thousand rows. It seems like a problem with the queue, my program never stops running, I did a test by manually placing a parameter in the queue only and the app ran normally.

Is there anything I can do to solve this problem?

Another problem I have is with regard to CPU, it goes up a lot when I run the application, even with an equipment, I made a comparison directly running the same command on linux via ssh and I have the same problem, output, while ssh gets printing the output of the command the cpu is high.

I'm doing a system that collects about 150 devices, I need to decrease the use of cpu, does anyone know what I can do to change this behavior?

**Comment by ktbyers** [comment]
There is a deadlock condition you can run into with multiprocesses and passing large amounts of data. You can probably use the following as a solution:

https://github.com/twin-bridges/pynet-ons-template/blob/master/threads_procs/proc_avoid_deadlock.py

See the first answer here for more details:

https://stackoverflow.com/questions/31665328/python-3-multiprocessing-queue-deadlock-when-calling-join-before-the-queue-is-em

cc: @carlniger

**Comment by dobicz** [comment]
Hi, tks for answer, so... the first link not exists... 

I will see the statckoverflow question...

**Comment by ktbyers** [comment]
@dobicz Here you go:

https://github.com/ktbyers/pynet-ons-feb19/blob/master/threads_procs/proc_avoid_deadlock.py


Kirk
