### ISSUE TITLE
Direct access to router's OS

### ISSUE THREAD

**Issue by chrislrobson** [ktbyers/netmiko#120]
Netmiko will fail when connecting directly to a router's OS (aka not the routing engine). 
Fix by the following code snippet but needs review:
line 125     
      def set_base_prompt(self, pri_prompt_terminator='#',
                        os_prompt_terminator="%",
                        alt_prompt_terminator='>', delay_factor=.5):
and line 165
            if prompt[-1] == os_prompt_terminator:
                self.commandline_mode()

**Comment by chrislrobson** [comment]
oops for got a piece o the patch...kind of important :-)

    def check_commandline_mode(self, check_string='>'):
        '''
        Checks if the device is in commandline mode or not
        Returns a boolean
        '''
        output = self.send_command('\n', strip_prompt=False, strip_command=False)
        if check_string in output[:-1]:
            return True
        else:
            return False

**Comment by chrislrobson** [comment]
OOPS again more forgot code...its been a long day....

   def commandline_mode(self, commandline_command='cli'):
         '''
         Enter into commandline_mode.  Typically this happen when ssh'ed
         to a virutal machine'ed router
    
         First check whether currently already in configuration mode.
         Enter config mode (if necessary)
         '''
         output = ''
         if not self.check_commandline_mode():
             output = self.send_command(commandline_command, strip_prompt=False, strip_command=False)
             if not self.check_commandline_mode():
                 raise ValueError("Failed to enter commandline mode")
    
         return output
    
    def exit_commandline_mode(self, exit_commandline='exit'):
        '''
        Exit from commandline mode.
        '''
        output = ''
        if self.check_commandline_mode():
            output = self.send_command(exit_commandline, strip_prompt=False, strip_command=False)
            if self.check_commandline_mode():
                raise ValueError("Failed to exit commandline mode")

        return output

**Comment by ktbyers** [comment]
@chrislrobson What platform were you testing on?

**Comment by chrislrobson** [comment]
The router I'm connecting (ssh'ing to, aka netmiko'ing to) is a Juniper 
vSRX running as a VMWare guest.  (You can get a free version for testing 
from Juniper).  My python script is running on a Fedora 22 host (also a 
guest but on a VirtualBox VM).  aka

Fedora 22(VB guest) <------> vSRX(VM guest)

since vSRX is a VM, when you ssh to it, your presented with the FreeBSD 
OS prompt not the routing engine prompt.  Aka... "username%" and not 
"username>"  Then you have to "cli" to the routing engine.

Also, the patch tests with python2.7 but I just moved to python3.5 and 
having some problems.....working it

l8r
chris

**Comment by chrislrobson** [comment]
fyi.....  There are several platforms I've ssh'ed to were one is 
presented with the OS prompt such as...

Juniper, Bay-Microsystems, old marconi's, Ericcsons and any 
soft-router.....aka linux, freebsd, vmwork...etc

**Comment by chrislrobson** [comment]
Patch for GIT-version-17Oct tested good

--- ./base_connection-ORIG.py	2015-10-17 17:23:02.318670890 -0400
+++ ./base_connection-OSFix.py	2015-10-17 17:21:55.520684197 -0400
@@ -143,6 +143,7 @@
 
 
     def set_base_prompt(self, pri_prompt_terminator='#',
+                        os_prompt_terminator="%",
                         alt_prompt_terminator='>', delay_factor=.5):
         '''
         Sets self.base_prompt
@@ -178,8 +179,14 @@
             prompt = prompt.split('\n')[-1]
             prompt = prompt.strip()
 
+            # If the ssh was to a OS directly issue
+            # command to go into routing engine
+            if prompt[-1] == os_prompt_terminator:
+                self.commandline_mode() 
+
             # Check that ends with a valid terminator character
-            if not prompt[-1] in (pri_prompt_terminator, alt_prompt_terminator):
+            elif not prompt[-1] in (pri_prompt_terminator,
+                                  alt_prompt_terminator):
                 raise ValueError()
         except (IndexError, ValueError):
             if debug:
@@ -413,6 +420,34 @@
 
         return newline.sub('\n', a_string)
 
+    def commandline_mode(self, commandline_command='cli'):
+         '''
+         Enter into commandline_mode.  Typically this happen when ssh'ed
+         to a virutal machine'ed router
+    
+         First check whether currently already in configuration mode.
+         Enter config mode (if necessary)
+         '''
+         output = ''
+         if not self.check_commandline_mode():
+             output = self.send_command(commandline_command, strip_prompt=False, strip_command=False)
+             if not self.check_commandline_mode():
+                 raise ValueError("Failed to enter commandline mode")
+    
+         return output
+    
+    @staticmethod
+    def exit_commandline_mode(self, exit_commandline='exit'):
+        '''
+        Exit from commandline mode.
+        '''
+        output = ''
+        if self.check_commandline_mode():
+            output = self.send_command(exit_commandline, strip_prompt=False, strip_command=False)
+            if self.check_commandline_mode():
+                raise ValueError("Failed to exit commandline mode")
+
+        return output
 
     def enable(self):
         """Disable 'enable()' method."""
@@ -470,6 +505,17 @@
         else:
             return False
 
+    def check_commandline_mode(self, check_string='>'):
+        '''
+        Checks if the device is in commandline mode or not
+
+        Returns a boolean
+        '''
+        output = self.send_command('\n', strip_prompt=False, strip_command=False)
+        if check_string in output[:-1]:
+            return True
+        else:
+            return False
 
     def send_config_from_file(self, config_file=None, **kwargs):
         '''

**Comment by ktbyers** [comment]
@chrislrobson Can you give me an example SSH session on the Juniper vSRX for what you are trying to do? Obviously, strip out anything that is confidential.

**Comment by chrislrobson** [comment]
Here is a snippet,

         cpfData = cpf.split( " " )
         imported_module = importlib.import_module( moduleName )
         if debugFlag:
           print(cpfData[0])
         networkDeviceProfileObject = getattr(imported_module, cpfData[0] )
         iComms = InitializeSSHConnectToNetworkDevice()
         iComms.initializeSSHConnectToNetworkDevice( dut,
networkDeviceProfileObject,
                                                  debugFlag )


   def initializeSSHConnectToNetworkDevice( self, dut,
                                         networkDeviceProfile,
                                         debugFlag = False ):
     sshConnectionHandle = 0
     cnt = 0
     sshConnectionHandle = ConnectHandler( **networkDeviceProfile )
     return

**Comment by ktbyers** [comment]
@chrislrobson I was looking for more of what you are trying to do at the router OS level? What do you do on the vSRX at the router OS?

**Comment by chrislrobson** [comment]
Kirk

Actual you can easily simulate this by simply connecting to any Linux box
running a ssh daemon
chris

**Comment by ktbyers** [comment]
Yes, but why do we care about this from a network automation perspective (i.e. what do you want to do to the Juniper device at the OS level)?

**Comment by chrislrobson** [comment]
Sorry for the late response, busy......anyway

To clarify, when working with devices like the xSVR (another example is 
soft-routers) when ssh'ing, one enters through the OS not directly to 
the routing engine.  So with the xSVR you will get a "[username]%" 
prompt not a "[username]>" thus netmiko will never find the initial prompt.

I will say the "quick and dirty" fix I have done does have a flaw, it 
assumes to get to the routing engine, the command "cli" needs to be 
executed.  I am an old old "C" programmer (my hay-day was back 
programming assembler and grew up pushing the new technology called K&R 
C *sigh*)  with very weak OOP experience ergo I didn't dig into putting 
this in the factory structure.  Thus it needs a "lot of love" as we used 
to say.......

Another issue I just ran across and is troubling.....  it seems the 
following code does not work.....

output = self.remote_conn.recv(MAX_BUFFER).decode('utf-8')

to be specific the ".decode('utf-8')" (or even .encode('utf-8') )

The function does not crash it just doesnt do anything....

The problem seems to have nothing to do with netmiko itself but 
python2.7(Linux).  To duplicate simply do....

pull a prompt string from the xSVR and it returns - u'username>' - note 
the unicode flag....  if you store in a local variable the string 
'username>'  its stored as a simple string (no - "u" flag).  You can see 
this either through pyCharm or print( repr(prompt) ).  Ergo any compare 
attempted fails.  Python3 forces everything to unicoding but I can't go 
there because of a package I use doesnt support 3 yet.  So I'm trying to 
figure out why encode and decode are not working.  That is I assume if 
you use .decode('utf-8') the "u" would get stripped out.
Any suggestions would be greatly appreciated......

humbly....chris  (note, yeah going through all the str's and doing 
"unicode(str)" would solve the problem, but I'd rather figure out why 
what is supposed to work isn't....)

**Comment by ktbyers** [comment]
@chrislrobson I talked to an engineer at Juniper about this and the direct OS access is just a function of logging in as root. If you add a user to your vSRX, you should be able to SSH directly into the routing engine (and not be required to use the 'cli' command).


I am also not understanding your unicode/string issue?

For both Python2 and Python3, you are going to get a unicode string back. This is required to make Netmiko compatible with Python3.

If you assign this string to a variable, you will still have a unicode string.

<pre>
        ... <more code, but not relevant to discussion> ...
        net_connect = netmiko_connection(switch)
        output = net_connect.find_prompt()
        print output
        print repr(output)
</pre>

When I execute this, I get:
<pre>
pynet-sw1#              # This is what it looks like when printed to screen, but it is still a unicode string.
u'pynet-sw1#'
</pre>

Also Python will regard a unicode string and a 'str' as equal in a string comparison (assuming the same letters):

<pre>
$ python
Python 2.7.10 (default, Aug 11 2015, 23:39:10) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a = u'whatever'
>>> a
u'whatever'
>>> b = 'whatever'
>>> b
'whatever'
>>> type(a)
<type 'unicode'>
>>> type(b)
<type 'str'>
>>> a == b
True
</pre>

<pre>
 if you store in a local variable the string
'username>'  its stored as a simple string (no - "u" flag).
</pre>

So this is not correct...referencing a unicode by a variable does not change the unicode to a 'str'. 

<pre>
That is I assume if
you use .decode('utf-8') the "u" would get stripped out.
</pre>

The decode('utf-8') does not wipe out the unicode. It basically says to read this data and interpret it as utf-8. Consequently, at the end of this you will have a unicode string.

If you post some of your code where you are seeing issues, we can probably work this out.


Kirk

**Comment by chrislrobson** [comment]
OK, so a "daaaa" moment and much thanks for reminding me about the root 
account thing...... I've been running to fast & furious with the project 
... aka... to many short cuts like not doing setup completely and that 
went right by me..... The upside is the deep dive into netmiko has been 
worth it.

As for the unicode thing, the issue was seeing the prompt printing all 
the time when using the method "send_command", but since switching to 
"send_command_expect" the prompt string output has disappeared (I think 
knock on wood).  I'll add the interfacing with the routing engine has 
improved (simpler/cleaner) after the switch as well.

So, I'll keep testing and poking around.....Chris

**Comment by ktbyers** [comment]
Sounds good Chris. I will close this issue. Let me know if there is a use case we need it for (I am open to it).
