### ISSUE TITLE
huawei - part of long command is displayed in output.

### ISSUE THREAD

**Issue by peteneme** [ktbyers/netmiko#1200]
'''
COMMAND: dis bgp vpnv4 vpn-instance VOIP_PRIVATE.OrangeFrance peer 81.52.178.21 verbose
bose

        BGP Peer is 81.52.178.21,  remote AS 28708
        Type: EBGP link
        BGP version 4, Remote router ID 0.0.0.0
        Update-group ID: 1
        BGP current state: Idle(Admin)
        BGP current event: Stop
        BGP last state: Idle
        BGP Peer Up count: 0
        Configured: Connect-retry Time: 32 sec
        Configured: Min Hold Time: 0 sec
 Received: Total 0 messages
                 Update messages                0
                 Open messages                  0
                 KeepAlive messages             0
                 Notification messages          0
                 Refresh messages               0
 Sent: Total 0 messages
                 Update messages                0
                 Open messages                  0
                 KeepAlive messages             0
                 Notification messages          0
                 Refresh messages               0
 Authentication type configured: None
 No keepalive received since peer has been configured
 Maximum allowed route limit: 1000
 Threshold: 90%, Parameter:  idle-timeout 20
 Minimum route advertisement interval is 0 seconds
 Optional capabilities:
 Route refresh capability has been enabled
 4-byte-as capability has been enabled
 Send community has been configured
 Peer Preferred Value: 0
 Routing policy configured:
 No import update filter list
 No export update filter list
 No import prefix list
 No export prefix list
 Import route policy is: VOIP-FT-OrangeFrance
 Export route policy is: VOIP_PRIVATE.OrangeFrance-OUT
 No import distribute policy
 No export distribute policy
 Tracking has been enabled, and the delay is 9s
'''
USED VERSION:
netmiko         2.3.3

CODE SNIPPET:
...
        ssh_connection = netmiko.ConnectHandler(device_type = router_type, \
            ip = DEVICE_HOST, port = int(DEVICE_PORT), \
            username = USERNAME, password = PASSWORD)
...
        last_output = ssh_connection.send_command(cli_line)

HUAWEI ROUTER VERSION:

Huawei Versatile Routing Platform Software
VRP (R) software, Version 5.170 (NE40E&80E V600R009C20SPC600)
Copyright (C) 2000-2017 Huawei Technologies Co., Ltd.
HUAWEI NE40E-X8 uptime is 53 days, 1 hour, 9 minutes
Patch version : V600R009SPH053

**Comment by carlniger** [comment]
Hi @peteneme - can you format your post so its a bit more clear? It sounds like your `last_output` var is missing some output? What is the expected vs what you are getting?

**Comment by peteneme** [comment]
No inside of variable last_output  I have read some characters on the start 
some whitespace characters (like '[1D') + "bose" (which belongs to inserting of commands to channel (cli_line) and not to output from ssh_connection.send_command().

It happens when commandline is longer than 75..80 characters.

When I was using paramiko such workarround helped me:  
'''
buff = chan.recv(9999)
buff = buff.decode("utf-8").replace('\x0d','').replace('\x07','').replace('\x08','').replace(' \x1b[1D','')
'''

**Comment by carlniger** [comment]
@peteneme Ok I think I'm tracking. This looks somewhat related to #1201 in that it looks like we're missing some CSI/ESC sequences, but to be sure, can you set this on your connect handler object (as @ktbyers mentioned in that linked issue):

`netmiko_object.ansi_escape_codes = True`

And let us know if that sorts it out (I think not because of the `\x1b[1D` code but let's double check).

**Comment by thinvhd** [comment]
I have the same error when working with Huawei Firewall.
Netmiko inserts **\x1b[1D** when commandline is longer than 80 characters.
```
HRP_M[DR-FW-01-policy-security-rule-TMP_ACCESS] source-address range 123.123.12. **\x1b[1D**1  123.123.10
HRP_M[DR-FW-01-policy-security-rule-TMP_ACCESS] destination-address 172.31.0.30  **\x1b[1D** 32
```

**Comment by carlniger** [comment]
@peteneme I'm going to close this for now as its inactive. Please feel free to reopen and let us know if the escape codes --> true doesn't sort this out for you.

Also, feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.

**Comment by hkml2000** [comment]
Hello,

I've the same issue, and it was not solver with "netmiko_object.ansi_escape_codes = True"

could you please help, how did you solve it ?

Thanks
