### ISSUE TITLE
Support for Cloudgenix ION's

### ISSUE THREAD

**Issue by nickolas1969** [ktbyers/netmiko#1201]
Kirk!

Long time to talk, but do I have a new device type for you that is clobbering us at Columbia Sportswear. We heavily use the Cloudgenix SD-WAN appliances and thier CLI is very much like a Linux Shell. With ANSI color prompts and all. We get two error types when trying to use Netmiko and a ION. First is a crypto library issue with SSH, but we worked around that. The second is the failure for Netmiko to ID the prompt. What can I do to help out the adoption process?

Nick

**Comment by ktbyers** [comment]
@nickolas1969 We could try to strip the ANSI escape codes, you can set this to true in a driver by:

```
netmiko_object.ansi_escape_codes = True
```

It is possible that we might need to add additional ANSI escape codes to our stripping method, however, depending on what that is doing.

This PR might also help (depending on what it uses for prompt terminators). If that helps, we can possibly see if we can get that merged quicker.

https://github.com/ktbyers/netmiko/pull/984/files

Let me know if either of those items help or not.


Regards, Kirk

**Comment by nickolas1969** [comment]
Kirk,

 

Here is the initial connection, you see both the initial crypto errors I get and the odd prompt at the end.

 

>>> from netmiko import ConnectHandler

>>> ssh = ConnectHandler(device_type='linux',ip='10.200.28.23',username='root',password=’password')          

/usr/local/lib/python3.5/dist-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.

  m.add_string(self.Q_C.public_numbers().encode_point())

/usr/local/lib/python3.5/dist-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point

  self.curve, Q_S_bytes

/usr/local/lib/python3.5/dist-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.

  hm.add_string(self.Q_C.public_numbers().encode_point())

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 173, in ConnectHandler

    return ConnectionClass(*args, **kwargs)

  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 188, in __init__

    self.session_preparation()

  File "/usr/local/lib/python3.5/dist-packages/netmiko/linux/linux_ssh.py", line 16, in session_preparation

    return super(LinuxSSH, self).session_preparation()

  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 546, in session_preparation

    self.set_base_prompt()

  File "/usr/local/lib/python3.5/dist-packages/netmiko/linux/linux_ssh.py", line 28, in set_base_prompt

    delay_factor=delay_factor)

  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 786, in set_base_prompt

    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))

ValueError: Router prompt not found: '\x1b[31mUS-475-ION-01-Replacement#\x1b[0m  \x08'

>>> 

 

 

--

Nick Ellson

Educating Layer 8, one user at a time…

**Comment by nickolas1969** [comment]
Kirk,

 

Ok, that first part was my error, and I saw this fix by using a direct call to netmiko.ConnectHandler

 

>>> ssh.ansi_escape_codes = True              

>>> ssh = netmiko.ConnectHandler(device_type='linux',ip='10.200.28.23',username='root',password='password')

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 173, in ConnectHandler

    return ConnectionClass(*args, **kwargs)

  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 188, in __init__

    self.session_preparation()

  File "/usr/local/lib/python3.5/dist-packages/netmiko/linux/linux_ssh.py", line 16, in session_preparation

    return super(LinuxSSH, self).session_preparation()

  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 546, in session_preparation

    self.set_base_prompt()

  File "/usr/local/lib/python3.5/dist-packages/netmiko/linux/linux_ssh.py", line 28, in set_base_prompt

    delay_factor=delay_factor)

  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 786, in set_base_prompt

    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))

ValueError: Router prompt not found: '\x1b[31mUS-475-ION-01-Replacement#\x1b[0m  \x08'

>>> 

 

So I think this shows the ANSI codes Cloudgenix must be using in their prompt that Netmiko is not catching.

 

 

 

--

Nick Ellson

Educating Layer 8, one user at a time…

**Comment by nickolas1969** [comment]
Here you can see that the prompt does end in the traditional # sign, but it is done up in RED ANSI codes.

 

So I do not think we need to tweak the environment variables in this case, but prolyl add to the ansi stripping routine?

 

 

 

nellson@ush-c2-netlab2:~/git/Network_Scripts/nellson$ ssh root@10.200.28.23

The authenticity of host '10.200.28.23 (10.200.28.23)' can't be established.

ECDSA key fingerprint is SHA256:1Au7OIS1dXZPCdhTVECp+YXifcOdTW5FWVHpEb616u8.

Are you sure you want to continue connecting (yes/no)? yes

Warning: Permanently added '10.200.28.23' (ECDSA) to the list of known hosts.

Password: 

Last login: Tue May  7 04:02:14 2019 from 10.42.43.251

 

US-475-ION-01-Replacement# exit

Connection to 10.200.28.23 closed.

--

Nick Ellson

Educating Layer 8, one user at a time…

**Comment by dBitech** [comment]
I've used the following regex to strip ansi codes in the past  `re.compile(r'(\x9B|\x1B\[)[0-?]*[ -\/]*[@-~]')`

**Comment by carlniger** [comment]
@nickolas1969 Regarding the crypto warning message -- I believe this is supposed to be getting fixed in a future version (or maybe I'm making that up in my head?), but you can suppress this either by installing cryptography 2.4.2, or something like this:

```
import warning 
warnings.filterwarnings(action='ignore',module='.*paramiko.*')
```

Obviously suppressing warnings is maybe not the best thing in the world, but if you want to have at it :)

@dBitech that looks handy! I was just looking at the same/similar from this [SO post](https://stackoverflow.com/questions/14693701/how-can-i-remove-the-ansi-escape-sequences-from-a-string-in-python) -- quick testing and this for sure strips the red prompt, but Im going to poke around a bit more. I don't think we have any testing for this but maybe stealing from that SO post and adding some testing around this wouldn't be the worst idea!

**Comment by carlniger** [comment]
closing. opened #1206
