### ISSUE TITLE
connect to sshd on windows server (openssh) requires changes

### ISSUE THREAD

**Issue by mrolfson** [ktbyers/netmiko#1205]
When using linux device in order to connect to a sshd server to windows server fails due to wrong prompt. I have located the issue (windows prompt is '>' and not '$','#' and made some extension in order to fix it. 
1. copy linux folder to new folder named windows.
2. rename file linux_ssh.py to windows_ssh.
3. rename classes LinuxXXX to WindowsXXX
4. modiy __init__.py so import windows_ssh instead and rename classes in _all_
5 add windows in ssh_dispatcher.py
How can I contribute, (commit)?

**Comment by carlniger** [comment]
@mrolfson if you'd like to open a PR you can follow the process [here](https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md) -- you'll need to include output from passing tests as well. 

Also if this is kind of a one off thing you may consider simply changing the expect prompt as @daanvdsanden shows in #1067 for example.

**Comment by ktbyers** [comment]
Is this the Windows Linux Subsystem or something else in Windows?

There is a separate PR in netmiko where we were going to support environment variables for prompt termination in Linux so probably should look at that (instead of separate driver)--if it is Windows Linux Subsystem.

**Comment by carlniger** [comment]
@mrolfson I'm going to close this for now but feel free to reopen or just let us know if its WSL and the PR that @ktbyers  mentioned will sort things for you, or if its "real" Windows and there needs to be further discussion!
