### ISSUE TITLE
Unable to SCP using Windows

### ISSUE THREAD

**Issue by bouchardh** [ktbyers/netmiko#1207]
When trying to copy a file from cisco_ios device to my local windows machine using SCP, I am getting this error:
```
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "C:\hbdata\network\lib\site-packages\netmiko\scp_functions.py", line 104, in file_transfer
    verifyspace_and_transferfile(scp_transfer)
  File "C:\hbdata\network\lib\site-packages\netmiko\scp_functions.py", line 18, in verifyspace_and_transferfile
    if not scp_transfer.verify_space_available():
  File "C:\hbdata\network\lib\site-packages\netmiko\scp_handler.py", line 160, in verify_space_available
    space_avail = self.local_space_available()
  File "C:\hbdata\network\lib\site-packages\netmiko\scp_handler.py", line 152, in local_space_available
    destination_stats = os.statvfs(".")
AttributeError: module 'os' has no attribute 'statvfs'
```
I am using Python 3.7.3 on Windows 10

**Comment by bouchardh** [comment]
I got around it by modifying the scp_handler.py file. I added platform to the list of imports and starting at line 151:
```
    if platform.system() == 'Windows':
        def local_space_available(self):
            """Return space available on local filesystem."""
            import ctypes
            free_bytes = ctypes.c_ulonglong(0)
            ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p("."), None, None, ctypes.pointer(free_bytes))
            return free_bytes.value
    else:
        def local_space_available(self):
            destination_stats = os.statvfs(".")
            return destination_stats.f_bsize * destination_stats.f_bavail

```

**Comment by ktbyers** [comment]
@bouchardh Do you want to submit a PR on this?

**Comment by bouchardh** [comment]
I honestly didi not know what a PR was before you asked... I guess it would be a good way to start.

If you don't mind a newbie contributing, I will do my best.

**Comment by bouchardh** [comment]
All right, I've done some reading and I think that I understand what I need to do. According to the doc, I need to create a branch but I doubt that anyone can just create a branch in any project so I cloned your project locally, created new branch scp_to_windows and modified the file.

I committed the changes and according to the pull request tutorial, I need to push to origin and create the Pull Request.

Is it that easy?

**Comment by ktbyers** [comment]
You would then typically push your branch up to your GitHub repository and then on your GitHub repository click on the `New Pull Request` button and submit it that way.


Regards, Kirk

**Comment by bouchardh** [comment]
Hopefully, everything is in order. 
Followed a great post on learn.adafruit.com from @kattni to get this going.

Thank you

**Comment by bouchardh** [comment]
Finally got black to accept the file... they are not kidding when they say uncompromising :)

I leaned a lot with this PR. Sorry about the large number of commits.

**Comment by carlniger** [comment]
Going to close this and handle the rest in the PR -- thank you!
