### ISSUE TITLE
Netmiko - file_transfer function - scp.SCPException Permission denied

### ISSUE THREAD

**Issue by DylanHamel** [ktbyers/netmiko#1208]
Hello, 
I'm testing for my company Nornir for Cumulus Linux.
Actually, I can generate a config file from a template but I can't push it on the Linux (Debian) with  Netmiko file_transfer functions.

I need to replace ``/etc/network/interfaces`` but I have the following error message :
```python
scp.SCPException: scp: /etc/network/interfaces: Permission denied
```

We would like to use Nornir (We currently use Ansible).
User is default Cumulus Linux user (cumulus) with sudo rights.

Is it possible to have a "become:" as in Ansible ? other ?
Thanks for your answer !

**Comment by carlniger** [comment]
@DylanHamel which device type are you using? Have you seen [this](https://github.com/ktbyers/netmiko/blob/develop/netmiko/linux/linux_ssh.py#L109)?  I've not played with it myself, but it may be useful. If you're looking at using Nornir you may also consider using the `command` [task plugins](https://nornir.readthedocs.io/en/stable/plugins/tasks/commands.html) or file (sftp) task plugin in nornir "natively". Maybe you can use native netmiko file transfer then Nornir `remote_command` to move the file into place (tested this w/ `sudo` and it works as expected nice and easy).

**Comment by DylanHamel** [comment]
Hello @DylanHamel, thank you !
It's with Cumulus Network OS. I use default user (cumulus). By default this user is in sudo group.
If you are directly connected on the Cumulus you can execute ``sudo vim /etc/network/interfaces`` and modified this file after enter the password.

I I tried the native function of Nornir ``r1 = leaves_gva.run(files.sftp`` the problem is the same.
```
/etc/network/interfaces: Permission denied
```

For example it works with Ansible with ``become:``
```yaml
- hosts: leaf
  become: true
  gather_facts: false
  roles:
    - config_leaf
```

I need to "become" root with Nornir ``files.sftp``function ...

Thanks for your time !!

**Comment by carlniger** [comment]
AFAIK there isn't a way to do this (privilege escalation as in ansible) w/ Netmiko or Nornir "natively". You could enable password-less sudo for your user if thats an option. Or you could copy the file to your user directory (no password required), then use netmiko to handle the password prompt ([example](https://github.com/ktbyers/netmiko/blob/develop/examples/handle_prompts/handle_prompts.py)). Would either of those options work?

**Comment by carlniger** [comment]
One last option -- you can copy the file to your host, then use Netmiko to change to root (still probably need to handle the prompt like in the previous comment) in the linux device_type ([here](https://github.com/ktbyers/netmiko/blob/develop/netmiko/linux/linux_ssh.py#L52)). I'm going to close this since I dont think there's anything else to do at the moment. Feel free to re-open if needed!
