### ISSUE TITLE
handling optional prompt in netmiko

### ISSUE THREAD

**Issue by amangoel9** [ktbyers/netmiko#1210]
how to handle the below prompt from Cisco IOS routers as its optional prompt???, it asks for (Confirm) only 1st time after boot up.

R1#write
Warning: Attempting to overwrite an NVRAM configuration previously written
by a different version of the system image.
Overwrite the previous NVRAM configuration?[confirm]

#####################################################
        print("========= Saving Configuration now =========")
        try:
            prompt = connection.send_command("write")
            print(prompt)
            if 'Warning' in prompt:
                print(connection.send_command("\n"))
                print("Config Saved")
            print("============ Configuration Saved =============")
        except:
            print("Failed to Save Configuration")
            pass        

###################Output##################################
========= Saving Configuration now =========
Failed to Save Configuration
Total time taken 0:02:00.718213 Seconds
------- END ---------
#############################################################

above code saves the configuration on router but never excutes print(prompt) and never prints "Config Saved" in output as well.

can anyone help me to handle this prompt.

**Comment by ktbyers** [comment]
Use either send_command_timing or the expect_string argument of send_command (see example here):

https://github.com/ktbyers/netmiko/blob/develop/examples/handle_prompts/handle_prompts.py

**Comment by carlniger** [comment]
Looks like this should be sorted so going to close. Feel free to re-open if needed.
