### ISSUE TITLE
netmiko/utilities.py:63: YAMLLoadWarning

### ISSUE THREAD

**Issue by Pluppo** [ktbyers/netmiko#1215]
When using netmiko-show from netmiko-tools, I get the following error:

```
/usr/lib/python3.6/site-packages/netmiko/utilities.py:63: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(fname)
```

This is just a warning, and the code runs fine, but it would be nice if this issue could get resolved.
Python version: 3.6.5
PyYAML version: 5.1
netmiko version: 2.3.3

**Comment by ktbyers** [comment]
Yes, it is fixed in `develop` branch.

Regards, Kirk

**Comment by Pluppo** [comment]
Excellent, thanks!

And sorry for not noticing the fix in the develop branch.

**Comment by ktbyers** [comment]
@Pluppo No worries :-)
