### ISSUE TITLE
Arista EOS issues using python code

### ISSUE THREAD

**Issue by penguin95025** [ktbyers/netmiko#1219]
from netmiko import ConnectHandler

device = {
    'device_type': 'arista_eos',
    'ip': '10.252.239.92',
    'username': 'admin',
    'password': 'xxxxx',
}

net_connect = ConnectHandler(**device)

config_commands = ['conf t','logging buffered 19999']

output = net_connect.send_config_set(config_commands)

print(output)

Traceback (most recent call last):
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\netmiko\base_connection.py", line 519, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ip_helper.py", line 14, in <module>
    output = net_connect.send_config_set(config_commands)
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\netmiko\base_connection.py", line 1554, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\netmiko\cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\netmiko\base_connection.py", line 1464, in config_mode
    if not self.check_config_mode():
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\netmiko\arista\arista.py", line 30, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\netmiko\base_connection.py", line 594, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\nerrab001c\AppData\Local\Programs\Python\Python37-32\lib\site-p
ackages\netmiko\base_connection.py", line 528, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data n
ot available.

**Comment by carlniger** [comment]
In the future, please format your code so it is easier to read - you can do this by enclosing things in triple back ticks, or using the "insert code" (<>) button. 

You may want to enable logging, you can read how to do that [here](https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel). What version of netmiko are you using?

**Comment by penguin95025** [comment]
Sure, thanks for your response. I am using netmiko version 2.3.3

**Comment by carlniger** [comment]
@penguin95025 did you get your issue fixed? If not, can you post your log output?

**Comment by carlniger** [comment]
Inactive, closing. 

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.
