### ISSUE TITLE
Ruckus Zonedirector support

### ISSUE THREAD

**Issue by axlroden** [ktbyers/netmiko#122]
The Ruckus Zonedirector has similar login method as Cisco WLC, are you able to create this custom class?

Shell output from a login with enable and config:
```
Please login: admin
Password:
Welcome to the Ruckus Wireless ZoneDirector 1200 Command Line Interface
ruckus> en
ruckus# config
You have all rights in this mode.
ruckus(config)# end
Your changes have been saved.
ruckus#
```

**Comment by axlroden** [comment]
I'we started writing this myself, I can't seem to get exit config mode to work .. 
The zonedirector will sometimes need multiple end to get outa sub sections of configs.

If I send end with my config_set then it works ok, but would be nice for it to handle it on it's own.

Any help would be appreciated, I plan to commit this when it is working.

**Comment by ktbyers** [comment]
@axlroden Can you post some more details what happens (your code and how the Zonedirector CLI operates).

**Comment by axlroden** [comment]
@ktbyers a bit more log output below. As you see if I am within a subsection of the config, I cannot exit out entirely unless I `quit` and not save any changes, I have to `end` twice, there are no other commands that can exit config from anywhere.

I have forked your repo, and you can see my current changes there.
https://github.com/axlroden/netmiko

```
ssh 172.16.16.98

Please login: admin
Password:
Welcome to the Ruckus Wireless ZoneDirector 1200 Command Line Interface
ruckus> en
ruckus# conf
You have all rights in this mode.
ruckus(config)# wlan test1
The WLAN service 'test1' has been created. To save the WLAN service, type 'end' or 'exit'.
ruckus(config-wlan)# end
The WLAN service 'test1' has been updated and saved.
Your changes have been saved.
ruckus(config)# end
Your changes have been saved.
ruckus# quit
Exit Ruckus CLI.

Connection to 172.16.16.98 closed.
```

**Comment by ktbyers** [comment]
@axlroden Sorry for delayed response on this...haven't forgotten about it.

**Comment by ktbyers** [comment]
@axlroden Please reopen this issue or submit a PR if you are still working on this.
