### ISSUE TITLE
Issue executing script with netmiko from Jenkins

### ISSUE THREAD

**Issue by dgo7** [ktbyers/netmiko#1221]
Hi,
I seem to be getting the following error when i am executing my script from Jenkins:
ImportError: cannot import name 'ConnectHandler'

Looking at existing issues, i can see suggestions that it could be because of existing netmiko.py or netmiko.pyc files but i did a find / -name netmiko.p* with no result.

Also note that my server has both python2.7.5 and python3.6.6 and my script is using python3 and i did a pip3 install netmiko to install netmiko.

Any suggestions would be appreciated.

Cheers,
D.

**Comment by ktbyers** [comment]
@dgo7 I would try the following--go into the Python interpreter shell, then:

```
import netmiko
netmiko.__file__
```

If the import netmiko doesn't work, then the Python you are using here doesn't have Netmiko installed.

The two most common causes of this problem are:
1. You have a netmiko.py or a netmiko.pyc somewhere in your Python path.
2. You installed Netmiko, but not into the Python your are trying to use here.


Regards, Kirk

**Comment by dgo7** [comment]
@ktbyers Thanks for prompt response.

I could import netmiko, although the attribute __file__ did not exist. I tried __path__, which gave me this output:
>>> netmiko.__
netmiko.__class__(          netmiko.__hash__(           netmiko.__path__
netmiko.__delattr__(        netmiko.__init__(           netmiko.__reduce__(
netmiko.__dict__            netmiko.__init_subclass__(  netmiko.__reduce_ex__(
netmiko.__dir__(            netmiko.__le__(             netmiko.__repr__(
netmiko.__doc__             netmiko.__loader__          netmiko.__setattr__(
netmiko.__eq__(             netmiko.__lt__(             netmiko.__sizeof__(
netmiko.__format__(         netmiko.__name__            netmiko.__spec__
netmiko.__ge__(             netmiko.__ne__(             netmiko.__str__(
netmiko.__getattribute__(   netmiko.__new__(            netmiko.__subclasshook__(
netmiko.__gt__(             netmiko.__package__
>>> netmiko.__path__
netmiko.__path__
>>> netmiko.__path__
_NamespacePath(['/usr/local/lib/python3.6/site-packages/netmiko'])
>>>

**Comment by ktbyers** [comment]
That doesn't look like the `netmiko` library

```
>>> import netmiko
>>> netmiko.__file__
'/Users/ktbyers/CODE/venv/python37_test/lib/python3.7/site-packages/netmiko/__init__.py'
>>> netmiko.__version__
'2.3.0'
```

You might want to go to that site-packages directory and see what it is.

**Comment by dgo7** [comment]
Here is a list of items within site-packages/netmiko:
[root@xxxxxxxxx]# pwd
/usr/local/lib/python3.6/site-packages/netmiko
[root@lapp-jenk-s10a netmiko]# ls
a10                       coriant      mellanox            scp_functions.py
accedian                  dell         mrv                 scp_handler.py
alcatel                   eltex        netapp              snmp_autodetect.py
apresia                   enterasys    netmiko_globals.py  ssh_autodetect.py
arista                    extreme      oneaccess           ssh_dispatcher.py
aruba                     f5           ovs                 ssh_exception.py
base_connection.py        fortinet     paloalto            terminal_server
calix                     hp           pluribus            _textfsm
checkpoint                huawei       py23_compat.py      ubiquiti
ciena                     __init__.py  __pycache__         utilities.py
cisco                     ipinfusion   quanta              vyos
cisco_base_connection.py  juniper      rad
citrix                    linux        ruckus

**Comment by ktbyers** [comment]
Okay, if you 'import netmiko' and then do `netmiko.__version__` from the Python shell what does it show?

**Comment by dgo7** [comment]
>>> netmiko.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'netmiko' has no attribute '__version__'
>>>

**Comment by ktbyers** [comment]
Okay, your environment is messed up in some way. I probably would start over in a clean virtual environment. Use `python -m pip install netmiko` to do the actual installation (so you can ensure the Python you are using is the same as the pip you are using. Depending on your setup and which Python you want to use it might be `python3`

**Comment by dgo7** [comment]
the command "from netmiko import ConnectHandler" works when executed as root on the python shell; On Jenkins i was executing it as a user hence why it was not working. I've tested it as root from Jenkins and it seems to work.

**Comment by ktbyers** [comment]
Okay, that is probably because Jenkins is using a different Python (at least that is what it looks like).
