### ISSUE TITLE
Multiple send_config_set over serial

### ISSUE THREAD

**Issue by jcox-dev-99** [ktbyers/netmiko#1226]
Hey Kirk, 

I'm attempting to send two send_config_set commands back to back over a serial connection.  The config is overrunning the devices input buffer when sent in one command.  

![image](https://user-images.githubusercontent.com/30243565/58180343-88368800-7c6f-11e9-92ca-fd2fe28eff85.png)

I've verified the above code builds the dictionaries correctly, and used the parameters of the second dictionary to create an isolated Netmiko connection, and it will connect and find_prompt().  When used in the above fashion, the second send_config_set doesn't connect, and throws  an authentication exception.

![image](https://user-images.githubusercontent.com/30243565/58180505-d9467c00-7c6f-11e9-9d1f-eaa642dba709.png)

Have you ran into anything like this before, or see something obviously incorrect?

Thanks in advance.

**Comment by jcox-dev-99** [comment]
Also, the first config set changes the hostname, so if I do not disconnect and reconnect, I get an expect string error.

**Comment by carlniger** [comment]
@jcox-dev-99 I've not done much w/ serial and netmiko, but it looks like its barking about auth -- I know you mentioned you tried that session by itself and it seems ok though. Did you try to send configs with that second session? Could be something as silly as priv levels or bad enable pass. Logging your session may be helpful -- [check this out](https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel)

As far as the hostname change, you can handle that by using `expect_string`  if you'd like, you can check out an example [here](https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html)

**Comment by ktbyers** [comment]
@jcox-dev-99 Yes, I wouldn't disconnect between the two sessions. 

I would probably do something like:

```
conn_ios.send_config_set(cfg_list)
conn_ios.set_base_prompt()
conn_ios.send_config_set(cfg_list2)
```

Let us know if that works. If not, please post the exception.

**Comment by jcox-dev-99** [comment]
Awesome, does set_base_prompt() reset what the expect string is looking for to the current hostname prompt?  I'll give it a shot tomorrow at work, thanks.

**Comment by ktbyers** [comment]
It should be the only place that is tracking state as far as the previous hostname.

**Comment by jcox-dev-99** [comment]
That works like a champ, thanks for the help guys.
