### ISSUE TITLE
Forcing a ssh connection  port 23 to cisco ios that is expecting telnet on port 23. SSH EXCEPTION errors

### ISSUE THREAD

**Issue by nonioAtoz** [ktbyers/netmiko#1228]
**I am using data credentials with connectHandler() method , and try to cath errors :
Im forcing a ssh connection on a device that only accept telnet connection on port 23**

data = {'ip': '192.168.6.254', 
                'port': 23, 
                'device_type': 'cisco_ios',
                'device_username': 'cisco', 
                'device_password': 'cisco', 
                 'device_secret': 'password'}
    try:
        with ConnectHandler(device_type= data["device_type"],
                                         ip=data["ip"],
                                         username=data["device_username"],
                                         password=data["device_password"],
                                         secret=data["device_secret"],
                                         port=data["port"]) as net_connect

    except (SSHException) as e:
        error_dictionary["TYPE"] = "SSH_exception"
        error_dictionary["MESSAGE"] = str(e)
        return error_dictionary, {}

    except (AuthenticationException) as e:
        error_dictionary["TYPE"] = "AuthenticationException"
        error_dictionary["MESSAGE"] = str(e)
        return error_dictionary, {}
        
    except (NetMikoTimeoutException) as e:
        error_dictionary["TYPE"] = "NetMikoTimeoutException"
        error_dictionary["MESSAGE"] = str(e)
         return error_dictionary, {}

    except (EOFError) as e:
        error_dictionary["TYPE"] = "EOFError"
        error_dictionary["MESSAGE"] = str(e)
        return error_dictionary, {}

    except Exception as unknown_error:
        error_dictionary["TYPE"] = "unknown error"
        error_dictionary["MESSAGE"] = str(unknown_error)
        return error_dictionary, {}

------------------------------------------------ERRRORS ----------------------
Exception: Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\paramiko\transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Program Files\Python37\lib\site-packages\paramiko\packet.py", line 373, in readline
<class 'paramiko.ssh_exception.SSHException'>
    return u(buf)
  File "C:\Program Files\Python37\lib\site-packages\paramiko\py3compat.py", line 156, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\paramiko\transport.py", line 1966, in run
    self._check_banner()
  File "C:\Program Files\Python37\lib\site-packages\paramiko\transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

-----------------------------------------------------------------------------------
**beside these error messages that apear in output console  i can catch the follwing message:
"Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position "**

**But the same code  with "port" set to 24 or diferente number it will catch error:
Connection to device timed-out: cisco_ios 192.168.6.254:24
How to catch the first case without an error on console**

**Comment by carlniger** [comment]
You need to use the appropriate telnet driver, so in this case: `cisco_ios_telnet`. [Here is an example](https://github.com/ktbyers/netmiko/blob/develop/examples/use_cases/case12_telnet/conn_telnet.py).

**Comment by nonioAtoz** [comment]
Thanks Carliner!
Carlniger , im building a web service and not using netmiko to scale automation of network devices . The services i am building expect that clients send off only  ip of the device and the configuration parameters, so clients dont know if a device have telnet or ssh active . The api will try both connections .  i can catch the errors without problem. I was curious about these specific case when using ssh connection port 23 on a device that expect telnet on port 23 give these error , but using a ssh connection port 24 or other port on a device expecting telnet 23 give a diferent error. For the first case i was expecting a message like " connection to device refused" and it is not the case.

**Comment by carlniger** [comment]
I dont believe this is really a netmiko issue, more a Paramiko/Python issue. If you want to catch the `SSHException` error from Paramiko you can do that:

```
from paramiko import SSHException
try:
    conn = ConnectHandler(**dev)
except SSHException as e:
    print('handled exception {}'.format(e))
```

This still prints the tracebacks to console. If you want to get rid of that entirely you could do some down and dirty redirection to devnull like [this](https://stackoverflow.com/questions/5925918/python-suppressing-errors-from-going-to-commandline) post suggests. 

I'm going to close this since its not netmiko related, but hopefully that helps.

**Comment by abhibilwankar** [comment]
**What will be the solution for this kind of ERROR?**
**What is the meaning of this error?**
File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 884, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paramiko\client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\paramiko\client.py", line 204, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\program_cisco_router.py", line 15, in <module>
    net_connect = ConnectHandler(ip=router['host'], username=router['user'],password=router['pass'],device_type=router['device_type'])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 317, in __init__
    self._open()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 322, in _open
    self.establish_connection()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 890, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios get_ip:22

**Comment by ktbyers** [comment]
@abhibilwankar Your DNS lookup failed:

`socket.gaierror: [Errno 11001] getaddrinfo failed`

Looks like you probably have a bug in your code as your hostname is called `get_ip` (which is probably not what you intended).

`netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios get_ip:22`

Probable cause of this is you used a string literal instead of calling a function (would be my guess).
