### ISSUE TITLE
Implement a device type for Alcatel-Lucent IPD 7750 routers

### ISSUE THREAD

**Issue by arnaudcoquelet** [ktbyers/netmiko#123]
Hi 

Would it be possible to create a device type for Alcatel-Lucent IPD 7750 routers ?
Something simple as that works:

```python
from netmiko.ssh_connection import SSHConnection

class IPD7750SSH(SSHConnection):
    def session_preparation(self):
        self.disable_paging(command="environment no more\n")
```

There is no enable/configure function (I'm not sure how you disable that)

Here is an example of the prompt:
```
*A:ftrvnsvsc1#
```
And when you start configuring, it will change to match the location in the configuration.
```
*A:ftrvnsvsc1# configure router  
*A:ftrvnsvsc1>config>router#
```

**Comment by ktbyers** [comment]
@arnaudcoquelet Yes, I have looked at a similar alcatel-lucent device before. I don't think I am willing to create it without a device to test against.

The way the prompt changes could be a bit of a challenge.

If you have a device that I can test against, then I would definitely consider doing it. Alternatively, you could write the code and submit a pull-request. See the VENDOR.md file in Netmiko for more detail.

**Comment by arnaudcoquelet** [comment]
I have a device to test if you want
The prompt that change seems to be working.

I will look into the vendor.md

Arnaud Coquelet
Alcatel-Lucent

**Comment by arnaudcoquelet** [comment]
Hi @ktbyers,

Since the Alcatel 7750/SROS does not have such modes as enable and config,
What do you do in this case with the config_mode(), exit_config_mode() and others ?
Should I just don't define them ?

**Comment by ktbyers** [comment]
Just define them in the sub-class and have them contain only a pass statement. This will cause them to be a no-op:

<pre>
def config_mode(self, *args, **kwargs):
     pass
</pre>

If you have a test Alcatel to work on, I definitely would be interested in working on this. Send an email to me. If you don't have my email address, just let me know.

**Comment by ktbyers** [comment]
SROS support was added by @arnaudcoquelet.
