### ISSUE TITLE
Escape Telnet

### ISSUE THREAD

**Issue by clatcho** [ktbyers/netmiko#1233]
#950

Use Case : log into cisco_ios devices, telnet to remote destinations, report outcome

Issue: Sending Ctrl + Shift + 6, then X does not escape telnet, it does however, escape a traceroute

Background: I found waiting for traceroutes to finish their 30 hops, or for a Telnet to timeout too time consuming, i had to tweak global delay initially to get a trace to work. Further investigation found that you can send 

<code>CNTL_SHIFT_6 = chr(30)</code>

And YES, this works perfectly with traceroute, but it does not work with Telnet ;(

<code>

def commander(connectBot,command):

    # Send Raw data down the SSH Channel
    connectBot.write_channel(command + '\n')

    # Wait for 10 seconds
    time.sleep(10)

    #Ctrl+Shift+6
    CNTL_SHIFT_6 = chr(30)

    # Sending Ctrl + Shift + 6
    connectBot.write_channel(CNTL_SHIFT_6)

    # Print the data
    print connectBot.read_channel()

def main():

    telnet	= "telnet 1.2.3.4 53 /source-interface Vlan10"
    traceroute = "traceroute 1.2.3.4 source vlan 10"

    # Establish a connection to the end device
    connectBot = cisco_connect('9.9.9.9')

    for i in range(3):
		commander(connectBot,telnet)

</code>

I am looping three time to demontrate that when performing sequential tests, i am unable to get the results i am looking for, instead of seeing the 'Open' from the telnet, you see your command over and over,

**Comment by ktbyers** [comment]
Telnet standard escape sequence is different that Cisco's escape sequence.

Telnet uses '^]' which is the group separator character. This is ASCII 29 so chr(29) in Python

```
>>> chr(29)
'\x1d'
>>> ord(chr(29))
29
```

You would need to use that to escape from a telnet connection.

**Comment by clatcho** [comment]
Thank you, much appreciated
