### ISSUE TITLE
linux driver on Dell server enable() to run 'sudo su'

### ISSUE THREAD

**Issue by shorton3** [ktbyers/netmiko#1234]
Hello,
I am passing a secret password to ConnectHandler() using the linux driver on a Dell server running Redhat. I am unclear whether or not enable() is automatically called (thus causing 'sudo su' to be invoked on my shell) when I pass in a non-blank secret password. Or, am I expected to explicitly call enable() on the device object returned from ConnectHandler()? Can someone please clarify. Thank you.

**Comment by carlniger** [comment]
@shorton3 You'll need to call enable on your connection object:

```
>>> conn.find_prompt()
'carl@macmini:~$'
>>> conn.enable()
'sudo su\r\nroot@macmini:/home/carl# '
>>> conn.find_prompt()
'root@macmini:/home/carl#'
```

Its probably worth pointing out that depending on what you're trying to do Netmiko is not really geared toward doing anything on servers so you may want to think about Ansible or something else.
