### ISSUE TITLE
OSError: Search pattern never detected in send_command_expect: <routername>\#

### ISSUE THREAD

**Issue by nishakashyap04** [ktbyers/netmiko#1235]
I am getting this error on running the below script. When I change the command to "show ip int brief", it works smoothly
RTR={
    'device_type':'cisco_ios',
    'ip':'None',
    'username':input('Enter Username : '),
    'password':getpass("Enter Password : ")
    }

output=''
with open('IPaccesslist.csv', newline='') as IP_file:
    read_IP = csv.reader(IP_file, delimiter=',')
    for IP in read_IP:
                print('Connecting to: ',IP[0])
                RTR['ip'] = IP[0]
                net_connect = ConnectHandler(**RTR)
                output = output + '\n' + net_connect.send_command("sh access-lists ACL-INET-PUBLIC") + '\n'
                print(output)
                net_connect.find_prompt()
        
with open('sh_access_lists.txt', 'w') as file:
    file.write(output)
    print('\n')

**Comment by carlniger** [comment]
@nishakashyap04 Please use triple ticks or the "code" button to format your code.

Is the ACL you are trying to show very long?  You may need to adjust the delay factors as outlined [here](https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html). You can try something like:

```
results = net_connect.send_command("cmd", delay_factor=20)
```

Or set the global delay factor when you create your connection object. Let us know if that helps.

**Comment by nishakashyap04** [comment]
Thanks Carlniger. I tried this and it worked
output = net_connect.send_command_timing("cmd", delay_factor = 3)

**Comment by nishakashyap04** [comment]
> @nishakashyap04 Please use triple ticks or the "code" button to format your code.
> 
> Is the ACL you are trying to show very long? You may need to adjust the delay factors as outlined [here](https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html). You can try something like:
> 
> ```
> results = net_connect.send_command("cmd", delay_factor=20)
> ```
> 
> Or set the global delay factor when you create your connection object. Let us know if that helps.

**Comment by nishakashyap04** [comment]
Thank you
