### ISSUE TITLE
declaration prompt handling

### ISSUE THREAD

**Issue by fariezs** [ktbyers/netmiko#1238]
hi, perhaps u could help me.

how to handle declaration prompt as below : -

associated sub-systems are
PROPRIETARY INFORMATION and remain the sole and exclusive property of me and may be
---- More ( Press 'Q' to break ) ----

Do you accept the declaration? YES to continue(YES/NO):Y

Error : 
Interactive SSH session established
Traceback (most recent call last):
  File "test_login.py", line 20, in <module>
    net_connect = ConnectHandler(**huawei)
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 228, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 313, in __init__
    self._try_session_preparation()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 723, in _try_session_preparation
    self.session_preparation()
  File "/usr/lib/python2.7/site-packages/netmiko/huawei/huawei_ssh.py", line 13, in session_preparation
    self.set_base_prompt()
  File "/usr/lib/python2.7/site-packages/netmiko/huawei/huawei_ssh.py", line 73, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: ---- More ( Press 'Q' to break ) ----

//script as below.
from netmiko import ConnectHandler
from datetime import datetime
import paramiko
import pexpect

start_time = datetime.now()
huawei = {
'device_type': 'huawei',
'ip': '192.168.1.1',
'username': 'abc',
'password': '123',
'global_delay_factor': 2,
'port': 22,
'verbose': True,
}

p = p.expect('break')
p.expect('break')
p.sendline('Q')
p.expect('YES/NO')
p.sendline('YES')
p.expect('HW')

net_connect = ConnectHandler(**huawei)
output = net_connect.send_command('display board 0')
print output

end_time = datetime.now()

**Comment by carlniger** [comment]
@fariezs is this prior to "completing" login basically? -- prompt for user/pass then you have to accept this type of banner/message? or is this just after the "display board 0" command you have in the post? If its the latter take a look at [this example of how to handle prompts](https://github.com/ktbyers/netmiko/blob/develop/examples/handle_prompts/handle_prompts.py) and let us know if that helps.

**Comment by ktbyers** [comment]
@fariezs You also need to eliminate the pexpect code (i.e. you need to choose one or the other i.e. either Netmiko or PExpect).

**Comment by fariezs** [comment]
> his prior to "c

Hi carlniger, thanks for response.

it is before completing the login. after input password success i need to handle the banner.
yes, you are correct, i have difficulties to complete/accept the banner.

[abc@vvv ~]# ssh abc@yyyy
abc@yyyy's password:

  -----------------------------------------------------------------------------
  User last login information:
  -----------------------------------------------------------------------------
  Access Type : SSH
  IP-Address  : 
  Login  Time : 2019-06-13 07:01:01+08:00
  Logout Time : 2019-06-13 07:01:28+08:00
  -----------------------------------------------------------------------------



NOTICE: This is a private communication system. Unauthorized access or use may  lead to
prosecution.

                                  **WARNING**

This is a system belonging to yyyyyyy systems are
provided for
processing of yyyyyy information only. All content of this system and its
associated sub-systems are
PROPRIETARY INFORMATION and remain the sole and exclusive property of yyyy and may be
---- More ( Press 'Q' to break ) ----
**////need to handle "break"**

monitored, intercepted, recorder, read, copied or captured in any manner and
disclosed in any manner,
by authorized personnel.

THERE IS NO RIGHT OF PRIVACY IN THIS SYSTEM.

Authorized yyyyy personnel may provide to law enforcement officials any potential evidence of crime
found on yyyy systems.

USE OF THIS SYSTEM BY ANY USER, AUTHORIZED OR UNAUTHORIZED, CONSITUTES
CONSENT TO THIS MONITORING, INTERCEPTION, RECORDING, READING, COPYING,
OR CAPTURING AND DISCLOSURE.

                                  **WARNING**



  Do you accept the declaration? YES to continue(YES/NO):y
**//need to accept the declaration**

yyyy>

**Comment by fariezs** [comment]
> @fariezs You also need to eliminate the pexpect code (i.e. you need to choose one or the other i.e. either Netmiko or PExpect).

thanks for the advice ktbyers

**Comment by fariezs** [comment]
> > @fariezs You also need to eliminate the pexpect code (i.e. you need to choose one or the other i.e. either Netmiko or PExpect).
> 
> thanks for the advice ktbyers

i removed the pexpect. the error as below.


[abc@yyyy python]# python test_login.py
SSH connection established to 10.10.10.10:22
Interactive SSH session established
Traceback (most recent call last):
  File "test_login.py", line 17, in <module>
    net_connect = ConnectHandler(**huawei)
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 228, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 313, in __init__
    self._try_session_preparation()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 723, in _try_session_preparation
    self.session_preparation()
  File "/usr/lib/python2.7/site-packages/netmiko/huawei/huawei_ssh.py", line 13, in session_preparation
    self.set_base_prompt()
  File "/usr/lib/python2.7/site-packages/netmiko/huawei/huawei_ssh.py", line 73, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: ---- More ( Press 'Q' to break ) ----

**Comment by carlniger** [comment]
@fariezs can you change the behavior so that the banner is disabled and/or comes after the login process? That is kind of a difficult problem to address.

You've got a few options if you can't change the banner/prompt behavior for whatever reason:

1. You can connect via the `terminal_server` device type and use `write_channel/read_channel` netmiko methods to handle the prompt. The terminal server device type doesnt really do any session preparation so you can handle this at the low channel level if you need to.
2. You can write in special login handler similar to [this](https://github.com/ktbyers/netmiko/blob/develop/netmiko/dell/dell_powerconnect.py#L84-L108), though this will likely not get pulled into Netmiko so you'd need to support that yourself
3. Change the banner/prompt if you can... it really is the *best* fix :) 

I'm going to close this for now since there likely isn't any action to take for this. Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.
