### ISSUE TITLE
Add netscreen support

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#124]

**Comment by kadecole** [comment]
I second this and can do testing when it is available.

**Comment by ktbyers** [comment]
@kadecole Sahil was working on this and is running into an issue. I will see if I can get him to post his code and then we can see if we can work out what is going wrong.

**Comment by networkpadwan** [comment]
@ktbyers I don't have access to device today. I will get the output on Monday (11/2).

**Comment by ktbyers** [comment]
@networkpadwan No problem, please post when you get a chance (probably better commit into your local branch so I can look at the code).

**Comment by networkpadwan** [comment]
#####################
Below output show that I am able to access the device locally.
#####################
maverick@maverick-G53SW:~$ ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=1.23 ms
^C
--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.238/1.238/1.238/0.000 ms
maverick@maverick-G53SW:~$ ssh netscreen@192.168.1.1
netscreen@192.168.1.1's password: 
PTY allocation request failed on channel 0
Remote Management Console
ns50-> exit
Connection to 192.168.1.1 closed.
maverick@maverick-G53SW:~$ 

###################
Code for paramiko

import paramiko

ip = '192.168.1.1'
username = 'netscreen'
password = 'netscreen'
remote_conn_pre = paramiko.SSHClient()
remote_conn_pre.set_missing_host_key_policy(paramiko.AutoAddPolicy())
remote_conn_pre.connect(ip, username=username, password=password, look_for_keys=False, allow_agent=False)
remote_conn = remote_conn_pre.invoke_shell()  
#As soon as I try to invoke shell I get the follwoing error
###################
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 369, in invoke_shell
    chan.get_pty(term, width, height, width_pixels, height_pixels)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 60, in _check
    return func(self, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 177, in get_pty
    self._wait_for_event()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 1086, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.
#############################################################
https://github.com/paramiko/paramiko/issues/96
https://github.com/paramiko/paramiko/issues/456

**Comment by ktbyers** [comment]
@networkpadwan Are you still interested in working on this?

**Comment by networkpadwan** [comment]
@ktbyers I was looking at the paramiko bug mentioned above. Looks like its still not solved. I will dig more into it this weekend and update this thread on 04/04

**Comment by networkpadwan** [comment]
@ktbyers I ran into the same error. Are you aware of any solution to above mentioned paramiko bugs?
O/P from the box:

Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 369, in invoke_shell
chan.get_pty(term, width, height, width_pixels, height_pixels)
File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 60, in _check
return func(self, args, *kwds)
File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 177, in get_pty
self._wait_for_event()
File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 1086, in _wait_for_event
raise e
paramiko.ssh_exception.SSHException: Channel closed.
#############################################################

**Comment by ktbyers** [comment]
@networkpadwan No, I don't know the solution to above. It is unclear on whether the problem is a Paramiko problem or a Netscreen problem (or a bit of both).

**Comment by ktbyers** [comment]
As far as I know no one is working on this...so am closing.
