### ISSUE TITLE
Failed to enter configuration mode. OneAccess 

### ISSUE THREAD

**Issue by gaussk32** [ktbyers/netmiko#1242]
I got an error with this code, what can i do?

#!/usr/bin/env python
from netmiko import Netmiko
from getpass import getpass

nxos1 = {
    "host": "x.x.x.x",
    "username": "admin",
    "password": "XXXXX",
    "device_type": "oneaccess_oneos",
}

cfg_file = "config_changes.txt"
net_connect = Netmiko(**nxos1)
print()
print(net_connect.find_prompt())
output = net_connect.send_config_from_file(cfg_file)
print(output)
print()

net_connect.save_config()
net_connect.disconnect()

and i got this output
()
>
Traceback (most recent call last):
  File "testOneacces.py", line 18, in <module>
    net_connect.send_config_set("SET { LIST { sysName = default-config-v2  } }")
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1554, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1465, in config_mode
    raise ValueError("Failed to enter configuration mode.")
ValueError: Failed to enter configuration mode.

This is my config file:
SET { LIST { sysName = default-config-v2  } } 
action "Activate Configuration"

**Comment by carlniger** [comment]
@gaussk32 when you ssh to this device normally how do you enter "config mode"? Based on the driver in Netmiko I'd assume just "conf t"? Can you do that successfully w/ the given user/password?

**Comment by gaussk32** [comment]
@carlniger on this devices to configure something there is no command to enter into "config mode" just anything with a SET at the start is a config command, but there is not a config command like "conf t"

**Comment by carlniger** [comment]
Ah ok. Looking at the driver for this it doesn't reflect that there is no config mode:  https://github.com/ktbyers/netmiko/blob/develop/netmiko/oneaccess/oneaccess_oneos.py

As it stands the "oneaccess" driver inherits from the  Cisco base connection so I think its trying to get into "config mode", then expecting a different prompt, and ultimately failing since none of that exists. You could try to use `send_command` instead to see if that works (as it doesnt try to get into config mode).

Do you happen to know if there are different flavors of the OneAccess devices/software? Maybe a different version has a config mode? I just dont have any context on the device or that particular driver so I'm wondering if it was created this way intentionally or if it should override the Cisco config mode methods.

**Comment by gaussk32** [comment]
@carlniger  the problem is i wanted to read a whole file into a string and then send it with net_connect.send_config_from_file(cfg_file)
send_command do not work for a conf file like this:
 SET
{
    SELECT ethernet1
    {
      SELECT hwPort[2]
      {
        LIST
        {
          swPort =
          {
            instance = 2
          }
        }
      }
      SELECT swPort[2]
      {
        LIST
        {
          ip =
          {
            vrfRouter = VRF_INET
            address = 192.168.50.1
            netMask = 255.255.254.0
            dhcpClient = disabled
          }
          mode = routing
        }
      }
    }
action "Activate Configuration"

**Comment by gaussk32** [comment]
` SET
{
    SELECT ethernet1
    {
      SELECT hwPort[2]
      {
        LIST
        {
          swPort =
          {
            instance = 2
          }
        }
      }
      SELECT swPort[2]
      {
        LIST
        {
          ip =
          {
            vrfRouter = VRF_INET
            address = 192.168.50.1
            netMask = 255.255.254.0
            dhcpClient = disabled
          }
          mode = routing
        }
      }
    }
action "Activate Configuration"
`

**Comment by carlniger** [comment]
Can you just read in the file and send it as a string in `send_command`? I don't have a OneAccess box I can poke around on but I dont see why that wouldn't work assuming the prompt isn't changing (which it sounds like it doesn't)

**Comment by carlniger** [comment]
I suspect you should be able to do the send_command method and read in the config file, so I'm going to go ahead and close this. Feel free to reopen if you're still working on it though.

**Comment by gaussk32** [comment]
the send command works only for one command not for a set of commands, so it is still failing
