### ISSUE TITLE
Timeout with send_config_set

### ISSUE THREAD

**Issue by MrFanciful** [ktbyers/netmiko#1245]
Hi

I'm starting to learn Netmiko and have, very early on, encountered a time out problem when using send_config_set.

When using the send_command method to send a Show command on a Cisco switch, it returns the info as expected, but when sending config commands with send_config_set, I get a timeout.

Script:

```python
from netmiko import ConnectHandler

switch1 = {
    'device_type': 'cisco_ios',
    'ip': '172.16.233.10',
    'username': 'user',
    'password': 'cisco'
}

net_connect = ConnectHandler(**switch1)
output = net_connect.send_command('sh ip int br')
print(output)

config_commands = ['int loop 0', 'ip address 10.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print(output)
```

Output:

```
/Users/User/.conda/envs/default/bin/python /Users/User/Documents/PycharmProjects/Network_Automation/Netmiko/netmiko1.py
Interface              IP-Address      OK? Method Status                Protocol
GigabitEthernet0/0     unassigned      YES unset  up                    up      
GigabitEthernet0/1     unassigned      YES unset  up                    up      
GigabitEthernet0/2     unassigned      YES unset  up                    up      
Vlan1                  172.16.233.10   YES NVRAM  up                    up      
Traceback (most recent call last):
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 519, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/User/Documents/PycharmProjects/Network_Automation/Netmiko/netmiko1.py", line 15, in <module>
    output = net_connect.send_config_set(config_commands)
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 1554, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 1461, in config_mode
    if not self.check_config_mode():
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 1448, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 594, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 528, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```
Process finished with exit code 1

I've connected to the same switch using the Python's telnetlib module and it connects fine so the issue appears to be something with paramiko/netmiko using SSH.

**Comment by carlniger** [comment]
@MrFanciful code looks good -- a couple things to check: does that user have appropriate permissions to get into config mode? is the device you're connecting to IOS/XE (looks like it, just confirming!). It looks like its not able to confirm it got "into" config mode so I'd guess permissions at a quick glance.

**Comment by carlniger** [comment]
Going to close for now. Please reopen if you're still running into any issues.

Also, feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc!

**Comment by torooDamaen** [comment]
> Hi
> 
> I'm starting to learn Netmiko and have, very early on, encountered a time out problem when using send_config_set.
> 
> When using the send_command method to send a Show command on a Cisco switch, it returns the info as expected, but when sending config commands with send_config_set, I get a timeout.
> 
> Script:
> 
> ```python
> from netmiko import ConnectHandler
> 
> switch1 = {
>     'device_type': 'cisco_ios',
>     'ip': '172.16.233.10',
>     'username': 'user',
>     'password': 'cisco'
> }
> 
> net_connect = ConnectHandler(**switch1)
> output = net_connect.send_command('sh ip int br')
> print(output)
> 
> config_commands = ['int loop 0', 'ip address 10.1.1.1 255.255.255.0']
> output = net_connect.send_config_set(config_commands)
> print(output)
> ```
> 
> Output:
> 
> ```
> /Users/User/.conda/envs/default/bin/python /Users/User/Documents/PycharmProjects/Network_Automation/Netmiko/netmiko1.py
> Interface              IP-Address      OK? Method Status                Protocol
> GigabitEthernet0/0     unassigned      YES unset  up                    up      
> GigabitEthernet0/1     unassigned      YES unset  up                    up      
> GigabitEthernet0/2     unassigned      YES unset  up                    up      
> Vlan1                  172.16.233.10   YES NVRAM  up                    up      
> Traceback (most recent call last):
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
>     out = self.in_buffer.read(nbytes, self.timeout)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
>     raise PipeTimeout()
> paramiko.buffered_pipe.PipeTimeout
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 519, in _read_channel_expect
>     new_data = self.remote_conn.recv(MAX_BUFFER)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
>     raise socket.timeout()
> socket.timeout
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/User/Documents/PycharmProjects/Network_Automation/Netmiko/netmiko1.py", line 15, in <module>
>     output = net_connect.send_config_set(config_commands)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 1554, in send_config_set
>     output = self.config_mode(*cfg_mode_args)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 50, in config_mode
>     config_command=config_command, pattern=pattern
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 1461, in config_mode
>     if not self.check_config_mode():
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
>     check_string=check_string, pattern=pattern
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
>     check_string=check_string, pattern=pattern
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 1448, in check_config_mode
>     output = self.read_until_pattern(pattern=pattern)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 594, in read_until_pattern
>     return self._read_channel_expect(*args, **kwargs)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 528, in _read_channel_expect
>     "Timed-out reading channel, data not available."
> netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
> ```
> 
> Process finished with exit code 1
> 
> I've connected to the same switch using the Python's telnetlib module and it connects fine so the issue appears to be something with paramiko/netmiko using SSH.

Please kindly help me if u had a fix to this issue. i am currently facing the same problem. i need help

**Comment by ktbyers** [comment]
@torooDamaen You should open a new issue if you are still having a problem.

**Comment by netauto123-py** [comment]
> @MrFanciful code looks good -- a couple things to check: does that user have appropriate permissions to get into config mode? is the device you're connecting to IOS/XE (looks like it, just confirming!). It looks like its not able to confirm it got "into" config mode so I'd guess permissions at a quick glance.

I was facing the same issue with exact same errors. As per your suggestions, I checked the privilege level and changed it to 15. This worked for me perfectly. Thank you very much

**Comment by priyavv01** [comment]
i got the same error due to special characters in the command list

**Comment by ktbyers** [comment]
@priyavv01 This issue is closed, please open a new issue if you are having an issue/problem.


Regards,

Kirk

**Comment by robin113x** [comment]
> Hi
> 
> I'm starting to learn Netmiko and have, very early on, encountered a time out problem when using send_config_set.
> 
> When using the send_command method to send a Show command on a Cisco switch, it returns the info as expected, but when sending config commands with send_config_set, I get a timeout.
> 
> Script:
> 
> ```python
> from netmiko import ConnectHandler
> 
> switch1 = {
>     'device_type': 'cisco_ios',
>     'ip': '172.16.233.10',
>     'username': 'user',
>     'password': 'cisco'
> }
> 
> net_connect = ConnectHandler(**switch1)
> output = net_connect.send_command('sh ip int br')
> print(output)
> 
> config_commands = ['int loop 0', 'ip address 10.1.1.1 255.255.255.0']
> output = net_connect.send_config_set(config_commands)
> print(output)
> ```
> 
> Output:
> 
> ```
> /Users/User/.conda/envs/default/bin/python /Users/User/Documents/PycharmProjects/Network_Automation/Netmiko/netmiko1.py
> Interface              IP-Address      OK? Method Status                Protocol
> GigabitEthernet0/0     unassigned      YES unset  up                    up      
> GigabitEthernet0/1     unassigned      YES unset  up                    up      
> GigabitEthernet0/2     unassigned      YES unset  up                    up      
> Vlan1                  172.16.233.10   YES NVRAM  up                    up      
> Traceback (most recent call last):
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
>     out = self.in_buffer.read(nbytes, self.timeout)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
>     raise PipeTimeout()
> paramiko.buffered_pipe.PipeTimeout
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 519, in _read_channel_expect
>     new_data = self.remote_conn.recv(MAX_BUFFER)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
>     raise socket.timeout()
> socket.timeout
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/User/Documents/PycharmProjects/Network_Automation/Netmiko/netmiko1.py", line 15, in <module>
>     output = net_connect.send_config_set(config_commands)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 1554, in send_config_set
>     output = self.config_mode(*cfg_mode_args)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 50, in config_mode
>     config_command=config_command, pattern=pattern
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 1461, in config_mode
>     if not self.check_config_mode():
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
>     check_string=check_string, pattern=pattern
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
>     check_string=check_string, pattern=pattern
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 1448, in check_config_mode
>     output = self.read_until_pattern(pattern=pattern)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 594, in read_until_pattern
>     return self._read_channel_expect(*args, **kwargs)
>   File "/Users/User/.conda/envs/default/lib/python3.7/site-packages/netmiko/base_connection.py", line 528, in _read_channel_expect
>     "Timed-out reading channel, data not available."
> netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
> ```
> 
> Process finished with exit code 1
> 
> I've connected to the same switch using the Python's telnetlib module and it connects fine so the issue appears to be something with paramiko/netmiko using SSH.

use this command
username <your username> privilege 15

**Comment by robin113x** [comment]
use this command
username privilege 15
