### ISSUE TITLE
Sending command with a tab.

### ISSUE THREAD

**Issue by SharonYeuda** [ktbyers/netmiko#1248]
Hi,

I'm trying to send a command to an HP switch for getting its speed-duplex options.

This is what I expect to get.
Tests(config)# interface 1 speed-duplex \t
 10-half               10 Mbps only, half duplex.
 100-half              100 Mbps only, half duplex.
 10-full               10 Mbps only, full duplex.
 100-full              100 Mbps only, full duplex.
 1000-full             1000 Mbps only, full duplex.
 auto                  Auto-negotiate link parameters.
 auto-10               10 Mbps only, auto-negotiate link parameters.
 auto-100              100 Mbps only, auto-negotiate link parameters.
 auto-2500             2500 Mbps only, auto-negotiate link parameters.
 auto-5000             5000 Mbps only, auto-negotiate link parameters.
 auto-2500-5000        2500 or 5000 Mbps only, auto-negotiate link parameters.
 auto-1000             1000 Mbps only, auto-negotiate link parameters.
 auto-10-100           10 or 100 Mbps only, auto-negotiate link parameters.
 auto-1000-2500        1000 or 2500 Mbps only, auto-negotiate link parameters.
 auto-1000-2500-5000   1000, 2500, or 5000 Mbps only, auto-negotiate link parameters.
 auto-10g              10 Gbps only, auto-negotiate link parameters.
Tests(config)#

But I get this output:
config term
Tests(config)# interface 1 speed-duplexIncomplete input: speed-duplex
Tests(config)# endTests# 

Here is the command I send 
print(connection.send_config_set('interface 1 speed-duplex \t'))

Does anyone have any idea how to get the output?

**Comment by SharonYeuda** [comment]
**I think I solved the issue!!!**

if I remove self.normalize_cmd from base_connection.py it's working.

        # Send config commands
        cfg_mode_args = (config_mode_command,) if config_mode_command else tuple()
        output = self.config_mode(*cfg_mode_args)
        for cmd in config_commands:
            # self.write_channel(self.normalize_cmd(cmd))
            self.write_channel(cmd)
            if self.fast_cli:
                pass
            else:
                time.sleep(delay_factor * 0.05)



**Is it possible to add a feature to disable the normalize_cmd if necessary?**

**Comment by SharonYeuda** [comment]
**Solution proposal**

    def send_config_set(
        self,
        config_commands=None,
        exit_config_mode=True,
        delay_factor=1,
        max_loops=150,
        strip_prompt=False,
        strip_command=False,
        config_mode_command=None,
        **normalize=True,**
    ):

        # Send config commands
        cfg_mode_args = (config_mode_command,) if config_mode_command else tuple()
        output = self.config_mode(*cfg_mode_args)
        for cmd in config_commands:
            **self.write_channel(self.normalize_cmd(cmd)) if normalize == True else self.write_channel(cmd)**
            if self.fast_cli:
                pass
            else:
                time.sleep(delay_factor * 0.05)


**And at the script**
print(connection.send_config_set('interface 1 speed-duplex \t',normalize="None"))

**Comment by carlniger** [comment]
@SharonYeuda I think an easier way to do this w/out modifying netmiko could be this:

```
conn = ConnectHandler(**dev)
conn.config_mode()
output = conn.send_command("interface 22 speed-duplex \t", normalize=False)
```

Can you see if that works for you? I only have one HP switch handy but here is what `print(output)` shows for me:

```
 10-half               10 Mbps, half duplex.
 100-half              100 Mbps, half duplex.
 10-full               10 Mbps, full duplex.
 100-full              100 Mbps, full duplex.
 1000-full             1000 Mbps, full duplex.
 auto                  Use Auto Negotiation for speed and duplex mode.
```

**Comment by SharonYeuda** [comment]
Hi Carl,
It works as you suggested.
Thanks a lot...
