### ISSUE TITLE
Search pattern never detected in send_command_expect:

### ISSUE THREAD

**Issue by jrleriche** [ktbyers/netmiko#1249]
Hi  Ktbyers,
 I am having an issue with my script . it does not write to my output file anything related to the command rather it give me me and error 
this is the error that i got 

File "C:\Users\LEJDEFF\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko-2.3.3-py3.7.egg\netmiko\base_connection.py", line 1320, in send_command_expect   OSError: Search pattern never detected in send_command_expect: I 

My script is as below 

```python
#!/usr/bin/env python
import netmiko
import sys
import datetime
from netmiko import ConnectHandler
from getpass import getpass

device = {
    'device_type': 'cisco_ios',
    'host': '172.24.237.130',
    'username': 'brunolepu401',
    'password': getpass(),
    
} 

net_connect = ConnectHandler(**device)
#open file to write command output
#file = open('_outputtexte', 'w')

# Execute commands
output = net_connect.send_command_expect('sh run', delay_factor=60)

# Write output to file above

filename = 'output' + '{0:%Y-%m-%d-%H-%M-%S}'.format(datetime.datetime.now()) + '.txt'
file = open(filename, 'w')
file.write(output)

#with open(filename) ad fh:
#line=fh.readline()
#line = fp.readline()
#   cnt = 1
#  while line:
#       print("Line {}: {}".format(cnt, line.strip()))
#       line = fp.readline()
#       cnt += 1

#print('Le nombre de sessions est de :',cnt )
file.close()
```

Can you please help Ktbyers

**Comment by carlniger** [comment]
@jrleriche what type of device are you connecting to? You may want to enable logging to try to get a better idea what's going on. Here is a quick [example](https://github.com/ktbyers/netmiko/blob/develop/examples/troubleshooting/enable_logging.py) how to do that.

**Comment by jrleriche** [comment]
I am trying to connect to some  C3850 cisco switches

**Comment by jrleriche** [comment]
And i dont need to enable because When I am login in I go straight to the  priviledged exec mode . M y issu is that I cannot  retrieve all the data from the output of the show run command.
Thanks Guys waiting for your help .

**Comment by carlniger** [comment]
@jrleriche I meant to enable logging as in the link provided. Netmiko is not seeing the prompt that it expects and that is why it is raising the exception. Also you probably should use `send_command` instead of the older `send_command_expect` -- both will work but `send_command` is the newer syntax.

**Comment by ktbyers** [comment]
Yes, I would add the `session_log` argument to ConnectHandler and then look at that file and see if it gives you clues as to what is happening. I would probably set delay_factor down to a more reasonable value like 5.

```
device = {
    'device_type': 'cisco_ios',
    'host': '172.24.237.130',
    'username': 'brunolepu401',
    'password': getpass(),
    'session_log': 'my_file.out',  
} 
```

Then inspect what is in the file `my_file.out`.

**Comment by jrleriche** [comment]
@carlniger , @ktbyers  I realized what the issue was it is just because of an authentication issue. It was not accepting the  command terminal length 0 from netmiko. then I was not  having anything in ly output file. the logging session showed everything. Thanks Guys

**Comment by lsotoj** [comment]
> @jrleriche what type of device are you connecting to? You may want to enable logging to try to get a better idea what's going on. Here is a quick [example](https://github.com/ktbyers/netmiko/blob/develop/examples/troubleshooting/enable_logging.py) how to do that.



Hello, the page gives 404 error! please help.

**Comment by ktbyers** [comment]
Logging setup is here:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

You can also look at the session log by adding the `session_log` argument to your device / ConnectHandler call:

```
device = {
    'device_type': 'cisco_ios',
    'host': '172.24.237.130',
    'username': 'brunolepu401',
    'password': getpass(),
    'session_log': 'my_file.out',  
} 
```
