### ISSUE TITLE
TP-Link switch T1500G - Unable to find prompt 

### ISSUE THREAD

**Issue by lifeofdave** [ktbyers/netmiko#1250]
I'm attempting to use Netmiko with a TP-link T1500G. There's no driver for this at present, however from what I've read the CLI is similar to Cisco, and if I can get my head round this I'm happy to create one. 

Using the code below I can connect, login and see the prompt in the debug: 

```
from netmiko import ConnectHandler
from cryptography.hazmat.primitives.asymmetric import dsa
from cryptography import utils as crypto_utils
import logging

def _override_check_dsa_parameters(parameters):
    """Override check_dsa_parameters from cryptography's dsa.py

    Without this the error below occurs:
    ValueError: p must be exactly 1024, 2048, or 3072 bits long

    Allows for shorter or longer parameters.p to be returned from the server's host key. This is a
    HORRIBLE hack and a security risk, please remove if possible!
    """
    if crypto_utils.bit_length(parameters.q) not in [160, 256]:
        raise ValueError("q must be exactly 160 or 256 bits long")

    if not (1 < parameters.g < parameters.p):
        raise ValueError("g, p don't satisfy 1 < g < p.")

dsa._check_dsa_parameters = _override_check_dsa_parameters

logging.basicConfig(filename="network_script.log", level=logging.DEBUG)
logger = logging.getLogger("Netmiko")

device = {
    "device_type": "cisco_ios",
    "ip": "192.168.178.99",
    "username": "davmin",
    "password": "u65mzO6w9ydr2",
    "global_delay_factor": 1,
    "port": 22,
    "timeout": 120,
    "use_keys": False,
    "key_file": "/Users/daveuser/.ssh/id_rsa.pub",
    "secret": "u65mzO6w9ydr2",
    "passphrase": "u65mzO6w9ydr2",
}


net_connect = ConnectHandler(**device)

```

However this results in an "ValueError: Unable to find prompt: " error. 

The log looks like this:

> DEBUG:paramiko.transport:starting thread (client mode): 0x2708320
> DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.2
> DEBUG:paramiko.transport:Remote version/idstring: SSH-1.99-IPSSH-6.6.0
> INFO:paramiko.transport:Connected (version 1.99, client IPSSH-6.6.0)
> DEBUG:paramiko.transport:kex algos:['diffie-hellman-group1-sha1'] server key:['ssh-dss'] client encrypt:['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] server encrypt:['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] client mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] server mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
> DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
> DEBUG:paramiko.transport:HostKey agreed: ssh-dss
> DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
> DEBUG:paramiko.transport:MAC agreed: hmac-sha1
> DEBUG:paramiko.transport:Compression agreed: none
> DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
> DEBUG:paramiko.transport:Switch to new keys ...
> DEBUG:paramiko.transport:Adding ssh-dss host key for 192.168.178.99: b'6e3ca110ab027f73d8aa7e40d0516ef8'
> DEBUG:paramiko.transport:userauth is OK
> INFO:paramiko.transport:Authentication (password) successful!
> DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
> DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
> DEBUG:paramiko.transport:Secsh channel 0 opened.
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:netmiko:read_channel: 
> 
> T1500G-10PS>
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:Pattern is: #
> DEBUG:netmiko:write_channel: b'exit\n'

This is how I manually connect and submit commands from the terminal

```
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 51: Applying options for 192.168.178.99
debug1: Connecting to 192.168.178.99 [192.168.178.99] port 22.
debug1: Connection established.
debug1: identity file id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 1.99, remote software version IPSSH-6.6.0
debug1: no match: IPSSH-6.6.0
debug1: Authenticating to 192.168.178.99:22 as 'admin'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group1-sha1
debug1: kex: host key algorithm: ssh-dss
debug1: kex: server->client cipher: aes128-cbc MAC: hmac-sha1 compression: none
debug1: kex: client->server cipher: aes128-cbc MAC: hmac-sha1 compression: none
debug1: sending SSH2_MSG_KEXDH_INIT
debug1: expecting SSH2_MSG_KEXDH_REPLY
debug1: Server host key: ssh-dss SHA256:h1gD8T017XJ19NjY3wD9Vob81jHYUJubf2M23KLU7OU
debug1: Host '[192.168.178.99]:22' is known and matches the DSA host key.
debug1: Found key in /Users/daveuser/.ssh/known_hosts:8
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_SERVICE_ACCEPT received
Authenticated with partial success.
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: id_rsa
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
admin@192.168.178.99's password:
debug1: Authentication succeeded (password).
Authenticated to 192.168.178.99 ([192.168.178.99]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network

T1500G-10PS>enable

T1500G-10PS#configure

T1500G-10PS(config)#interface gigabitEthernet 1/0/2

T1500G-10PS(config-if)#switchport pvid 2

T1500G-10PS(config-if)#
```

As I follow the session_preparation using the debugger, I can see that _test_channel_read succeeds, reading '\r\n\rT1500G-10PS>' from the channel, and matching it to the '[>#]' pattern, however set_base_prompt does not. It seems that read_channel in find_prompt returns an empty string, and I'm not sure why. 

As shown in paste from the terminal above, there's a newline between every "T1500G-10PS>" prompt, could this be the cause of this issue?

Any pointers much appreciated.

**Comment by carlniger** [comment]
@lifeofdave Thanks for the detailed information. After you get connected and are at the `>` prompt -- if you hit enter does the platform repaint the prompt on a new line? 

I think your assessment is correct that `set_base_prompt` is having a bad day :) Here is the log from a Cisco device I have handy:

```
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel:
3560CX>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
3560CX>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: 3560CX
```

After the SSH setup we see the `read_channel` find the prompt same as your log, but I think the next section is where we drop into `set_base_prompt` and netmiko sends the carriage return and in my case we see the prompt again, but we don't in your log. 

To answer your question about the newline -- we should be stripping whitespace so that *shouldn't* break it I don't think, but if the prompt isn't repainted after sending a carriage return *that* would be a problem. So I think the question for now is does the TP-Link repaint the prompt after each return?

**Comment by lifeofdave** [comment]
@carlniger Thanks for getting back to me

When I hit enter in a normal ssh session from the terminal, the prompt is repainted but with an empty line in-between each:

```
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network

T1500G-10PS>

T1500G-10PS>

T1500G-10PS>

T1500G-10PS>
```

**Comment by carlniger** [comment]
Thanks. I believe we should be handling stripping the new lines [here](https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1066), but a bit down from there we do return just the last line (after normalizing line feeds and such though). So its possible there is some interesting characters in there that we aren't normalizing/stripping.  Can you `print(repr(prompt))` before the line on 1066 in the previous link to see what we're actually dealing with.  Ultimately if we don't properly strip/normalize then we just pull the last character and bounce it off the primary/alt prompt terminators. Since it looks like we just get an empty string we've got something going wrong before then.

**Comment by lifeofdave** [comment]
Weirdly adding that print just results in the following being outputted

> ''

and that's it 🤔

**Comment by carlniger** [comment]
Heh. Sweet :)

Going back up the stack I'm not seeing an immediately obvious place where I would think to troubleshoot this. I'm guessing that the `output` var in `_read_channel` is never getting added to for whatever reason (for sure a guess)... Any chance there is one of these boxes I could connect to to test?

**Comment by lifeofdave** [comment]
However,
if I replace this line
`self.write_channel(self.RETURN)`
(https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L925)
with `self.write_channel("\r\n")`

The print statement outputs this
> '\r\n\r\n\rT1500G-10PS>'

Before resulting in this traceback
```
Traceback (most recent call last):
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 519, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidsinclair/projects/netzoom_platform/tests/netmiko_test1.py", line 43, in <module>
    net_connect = ConnectHandler(**device)
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 228, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 313, in __init__
    self._try_session_preparation()
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 723, in _try_session_preparation
    self.session_preparation()
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/cisco/cisco_ios.py", line 19, in session_preparation
    self.disable_paging()
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 989, in disable_paging
    output = self.read_until_prompt()
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 590, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 528, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```

Feels like progress :)

**Comment by carlniger** [comment]
You can set the return string when you instantiate the connection object: `response_return` --> `\r\n` (defaults to just `\n`) and see if that gets us any further. That is much much better though since we're actually getting ahead toward disabling paging and such :)

**Comment by lifeofdave** [comment]
Hmm if I add `'response_return':'\r\n',`, the print output is

> ''
and I get a new error

> Traceback (most recent call last):
>   File "/Users/davidsinclair/projects/netzoom_platform/tests/netmiko_test1.py", line 44, in <module>
>     net_connect = ConnectHandler(**device)
>   File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 228, in ConnectHandler
>     return ConnectionClass(*args, **kwargs)
>   File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 313, in __init__
>     self._try_session_preparation()
>   File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 724, in _try_session_preparation
>     self.session_preparation()
>   File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/cisco/cisco_ios.py", line 18, in session_preparation
>     self.set_base_prompt()
>   File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 1041, in set_base_prompt
>     prompt = self.find_prompt(delay_factor=delay_factor)
>   File "/Users/davidsinclair/virtualenvs/netzoom_3_6_7/lib/python3.6/site-packages/netmiko/base_connection.py", line 1080, in find_prompt
>     prompt = prompt.split(self.RESPONSE_RETURN)[-1]
> AttributeError: 'NoneType' object has no attribute 'split'

You are very welcome to connect a one of these boxes! That would be much appreciated. If you could then let me know how I can send you the details

**Comment by carlniger** [comment]
Heh I'll take new errors! Shoot me an email and we can connect on access: carl@twb-tech.com

**Comment by carlniger** [comment]
@lifeofdave sent you a note and link to a branch on my netmiko fork. If you want to take that and run w/ it (on your own or create a driver for it), have at it! I think we'll close this at this point though as this seems like a one off TP Link quirk. Let us know if you run into any other issues!
