### ISSUE TITLE
Aruba Controller AOS 8 SSH issue after login

### ISSUE THREAD

**Issue by shadyhasan** [ktbyers/netmiko#1252]
Hi 
I got an issue when trying to connect to Aruba Controller AOS 8.

I am a beginner in Python so appreciate your help.

Aruba = {
'device_type': 'aruba_os',
'ip': HOST,
'username': user,
'password': password
}

ssh_connect = ConnectHandler(**Aruba)
ssh_connect.send_command('configure terminal')
ssh_connect.send_command('interface gigabitethernet 0/0/0')

Output error:
Traceback (most recent call last):
  File "C:\Users\alaa_\Desktop\Python practising\wlc connect.py", line 40, in <module>
    ssh_connect.send_command('configure terminal')
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1295, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: \(WLC\-1323782\)\ \[mynode\]\ \#

Here is the device prompt:
(WLC-1323782) [mynode] #
(WLC-1323782) [mynode] #configure terminal
Enter Configuration commands, one per line. End with CNTL/Z
(WLC-1323782) [mynode] (config) #

Appreciate any help.

Thanks in advance.

**Comment by carlniger** [comment]
@shadyhasan If you want to send `show` commands then you can use that `send_command` method , however for configs Netmiko will handle getting into/out of config mode for you -- so if you want to send configurations use the `send_config_set` function with a list of configs that you want to send. Check out [this](https://github.com/ktbyers/netmiko/blob/develop/examples/configuration_changes/config_changes.py) example and let us know if that gets you sorted out.

**Comment by shadyhasan** [comment]
@carlniger thanks a lot for help.
After using send_command, the scripts executes the commands correctly on the controller but there are more than one exception after script finished:

Traceback (most recent call last):
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 519, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alaa_\Desktop\Python practising\wlc connect _test.py", line 22, in <module>
    output = ssh_connect.send_config_set(cfg_commands)
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1567, in send_config_set
    output += self.exit_config_mode()
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\cisco_base_connection.py", line 56, in exit_config_mode
    exit_config=exit_config, pattern=pattern
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1478, in exit_config_mode
    if self.check_config_mode():
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\aruba\aruba_ssh.py", line 37, in check_config_mode
    check_string=check_string, pattern=pattern
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\cisco_base_connection.py", line 38, in check_config_mode
    check_string=check_string, pattern=pattern
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1448, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 594, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\alaa_\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 528, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**The script is as follows:**
import xlrd 
import telnetlib
import getpass
import sys
from netmiko import ConnectHandler

HOST = '172.16.0.254'
user = 'admin'
password = 'admin1'

#create device template

Aruba = {
'device_type': 'aruba_os',
'ip': HOST,
'username': user,
'password': password
}

ssh_connect = ConnectHandler(**Aruba)
cfg_commands = ["hostname NEW_NAME", "write memory"]
output = ssh_connect.send_config_set(cfg_commands)
print(output)
ssh_connect.disconnect()

**So please advise**.

**Comment by shadyhasan** [comment]
Update:
If I removed the "hostname" command , no exceptions occur and it displays the output of commands execution.

I don't know why hostname command makes this exception.

Still waiting for help.

Thanks in advance...

**Comment by carlniger** [comment]
Does the "write memory" command cause the device to prompt you? I don't have any Aruba experience but it looks like the "write memory" process should be same/similar to IOS since it inherits from the Cisco class -- so it may be worth removing that from the "config_set" and simply send the hostname change then use the "save_config" method. 

Let us know if that helps out and if not please send the output of you changing the hostname manually so we can see what the prompts do.

**Comment by ktbyers** [comment]
Okay, I think the hostname change fails because it fails the check_config_mode method (basically at the end of send_config_set it tries to automatically exit config mode):

https://github.com/ktbyers/netmiko/blob/develop/netmiko/aruba/aruba_ssh.py#L35

And detecting this uses `self.base_prompt` which has now changed.

So we need to fix that L35 to do something that would work if a hostname has happened and properly detect we have exited config mode.

**Comment by shadyhasan** [comment]
Hello 
Sorry for the delay.

Here is the steps done on the device manually on the Aruba Controller version 8

(NEW_NAME) [mynode] #configure terminal
Enter Configuration commands, one per line. End with CNTL/Z

(NEW_NAME) [mynode] (config) #hostname TURBO_CONTR
(NEW_NAME) ^[mynode] (config) #
(NEW_NAME) ^[mynode] (config) #write memory

Saving Configuration...

Configuration Saved.
(TURBO_CONTR) [mynode] (config) #

Be noted that (as shown), write memory must be done in order for the command to take affect.

So kindly advise.

Thanks in advance.

**Comment by shadyhasan** [comment]
> Okay, I think the hostname change fails because it fails the check_config_mode method (basically at the end of send_config_set it tries to automatically exit config mode):
> 
> https://github.com/ktbyers/netmiko/blob/develop/netmiko/aruba/aruba_ssh.py#L35
> 
> And detecting this uses `self.base_prompt` which has now changed.
> 
> So we need to fix that L35 to do something that would work if a hostname has happened and properly detect we have exited config mode.

Hi 

> Okay, I think the hostname change fails because it fails the check_config_mode method (basically at the end of send_config_set it tries to automatically exit config mode):
> 
> https://github.com/ktbyers/netmiko/blob/develop/netmiko/aruba/aruba_ssh.py#L35
> 
> And detecting this uses `self.base_prompt` which has now changed.
> 
> So we need to fix that L35 to do something that would work if a hostname has happened and properly detect we have exited config mode.

Hi ktbyers
But the commands executed on the device correctly, the only issue the errors after script finished.
This is confirmed from my side.

Another point, I don't know if it is important or not.
Aruba controller version 8 has new command and prompt structure compared to all previous version. This is after HPE acquisition.

Thanks and sorry for the delay.

**Comment by ktbyers** [comment]
I think this is fixed here:

https://github.com/ktbyers/netmiko/pull/2246
