### ISSUE TITLE
SCP.py times out too quickly on Secure Copy of large files

### ISSUE THREAD

**Issue by eakikel** [ktbyers/netmiko#1254]
I am using the scp scp_transfer.transfer_file() function.
When running against older versions of EOS like 4.15 thru 4.19, the file transfer works smoothly

When it runs against EOS-4.20.11M the file transfers but errors out
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 335, in _recv_confirm
    msg = self.channel.recv(512)
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./copyarista.py", line 137, in copycode
    scp_transfer.transfer_file()
  File "/usr/local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 304, in transfer_file
    self.put_file()
  File "/usr/local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 317, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/usr/local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 40, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 154, in put
    self._send_files(files)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 250, in _send_files
    self._send_file(fl, name, mode, size)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 276, in _send_file
    self._recv_confirm()
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 337, in _recv_confirm
    raise SCPException('Timeout waiting for scp response')
scp.SCPException: Timeout waiting for scp response

**Comment by ktbyers** [comment]
Hmmmmm, strange I am pretty sure I have tested SCP using Netmiko and a similar EOS version as this.

Have you tested it without threading to see if it fails in a simpler use case?

**Comment by eakikel** [comment]
Removed the threading. Same issue
[kikele@osbaz2dev03087 ~]$ ./testscp.py 
  File "./testscp.py", line 41
    return
    ^
SyntaxError: 'return' outside function
[kikele@osbaz2dev03087 ~]$ ./testscp.py 
nyc-p17-era08-ds              *START TRANSFER
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 335, in _recv_confirm
    msg = self.channel.recv(512)
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./testscp.py", line 142, in <module>
    scp_transfer.transfer_file()
  File "/usr/local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 304, in transfer_file
    self.put_file()
  File "/usr/local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 317, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/usr/local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 40, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 154, in put
    self._send_files(files)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 250, in _send_files
    self._send_file(fl, name, mode, size)
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 276, in _send_file
    self._recv_confirm()
  File "/usr/local/lib/python3.6/site-packages/scp.py", line 337, in _recv_confirm
    raise SCPException('Timeout waiting for scp response')
scp.SCPException: Timeout waiting for scp response
[kikele@osbaz2dev03087 ~]$ 

#!/usr/local/bin/python3
import argparse, csv, os, sys, getpass, time, getopt, re, dns.resolver
import warnings
import json
from netmiko import ConnectHandler, FileTransfer

ip = "nyc-p17-era08-ds"
name= "nyc-p17-era08-ds"

username = "kikele"
password = "!S0pran0sa19"


EOSlist=[]
EOSlistaction=[]
EOSlistcnt = 0
bootcfg = ""
version = ""
filetocopy = "/opt/codes/arista/EOS-2GB-4.20.11M.swi"

regex = re.compile(r'.*\/(\S+)') 
match = regex.search(filetocopy)
basefile = match.group(1)
#    print("BASEFILE {0}".format(basefile))

#s    print("BEFCOPY,{0},{1},{2},{3},{4},{5}".format(name,ip,vendor,model,device_osver,username,password))

try:
  net_device = {
          "device_type": "arista_eos",
          "ip": ip,
          "username": username,
          "password": password,
          "secret": password,
          "port": 22,
  }
#      print("{0}-{1}-Logon".format(name,ip))
  ssh_conn = ConnectHandler(**net_device)
except:
  print("{0}-{1}*LOGON FAILED".format(name,ip)) 
# Get Version Info from Running Code
output_showver = ssh_conn.send_command("sh ver detail | json")
datastore = json.loads(output_showver)
running_version = datastore["version"]
running_internalVersion = datastore["internalVersion"]
#  print("VERSION {0} internalVersion {1}".format(running_version,running_internalVersion))

# Get Boot Config Info  
output_showboot = ssh_conn.send_command("sh boot-config | json")
datastore = json.loads(output_showboot)
boot_image = datastore["softwareImage"]
boot_image = boot_image.lstrip('flash:/')
#   print("{0} bootimage {1}".format(name,boot_image))

# Hidden Boot File Internal version
output_showfile = ssh_conn.send_command("sh file information flash:.boot-image.swi | json")
datastore = json.loads(output_showfile)
hidden_internalVersion = datastore["version"]

#  print (output_showver)
#  print (output_dir)
#  print (output_showboot)
#  print (output_showfile)

# Get Directory list and loop the all EOS versions
# Keep current running versions or the one we are going to upload  
output_dir = ssh_conn.send_command("dir EOS*swi") 
for dirline in output_dir.splitlines():
#        print ("LOGON**",logonline.decode('utf-8'))
#      direntry = dirline.decode('utf-8')
#           print ("DIRENTRY**",direntry.strip(),"**",t_name,"**") 
#        regex = re.compile(r'\s(EOS.*swi)', re.IGNORECASE)
#        if regex.search(direntry):
#            match = regex.search(direntry)
    regex = re.compile(r'\s(EOS.*swi)$', re.IGNORECASE)
    match = regex.search(dirline)
    if match:
        EOSfile = match.group(1)
        output_showfile = ssh_conn.send_command("sh file information flash:{0} | json".format(EOSfile))
        datastore = json.loads(output_showfile)
        if "version" not in datastore:
          file_internalVersion = "NULL"
        else:
          file_internalVersion = datastore["version"]
        # Check current running version and mark as keep
        if file_internalVersion == running_internalVersion:
          EOSlist.append(EOSfile)
          EOSlistaction.append("KEEP")
          EOSlistcnt += 1 
          outputline = str(name) + ",READ-DIR-ENTRY," + str(EOSfile) + "," + str(EOSlistcnt) + "\n"
        # Check if this is file we were planning on downloading and mark as keep
        elif EOSfile == basefile:
          EOSlist.append(EOSfile)
          EOSlistaction.append("KEEP")
          EOSlistcnt += 1 
          outputline = str(name) + ",READ-DIR-ENTRY," + str(EOSfile) + "," + str(EOSlistcnt) + "\n"
        # If file matches boot-config keept it
        elif EOSfile == boot_image:
          EOSlist.append(EOSfile)
          EOSlistaction.append("KEEP")
          EOSlistcnt += 1 
          outputline = str(name) + ",READ-DIR-ENTRY," + str(EOSfile) + "," + str(EOSlistcnt) + "\n"
        # Otherwise delete it
        else:
          EOSlist.append(EOSfile)
          EOSlistaction.append("DELETE")
          EOSlistcnt += 1 
          outputline = str(name) + ",READ-DIR-ENTRY," + str(EOSfile) + "," + str(EOSlistcnt) + "\n"
          

for row in EOSlist:
#   if EOSlistaction[EOSlist.index(row)] == "DELETE":
   outputline = ("SWITCH-{0} File-{1} {2}".format(name,row,EOSlistaction[EOSlist.index(row)]))
#     print (outputline)


try:
  dest_file_system = "/mnt/flash"
  source_file = filetocopy  
  dest_file = basefile
  
#    print("SOURCE FILE-{0}  DEST FILE-{1} DESTF FIlE SYSTEM-{2}".format(source_file,dest_file,dest_file_system))

  with FileTransfer(
          ssh_conn,
          source_file=source_file,
          dest_file=dest_file,
          file_system=dest_file_system,
      ) as scp_transfer:
      space_sw = 0
      while True:
        #
        if scp_transfer.check_file_exists():
          if scp_transfer.verify_file():
            print("{0:30}*File Already Exists and is verified".format(name))
            break 
          else:
            raise ValueError("**File Already Exists-MD5 failure between source and destination files")
        else:
          if scp_transfer.verify_space_available():
            print("{0:30}*START TRANSFER".format(name))
            scp_transfer.transfer_file()
            print("{0:30}*FINISH TRANSFER".format(name))
            if scp_transfer.verify_file():
        #                  print("{0}-{1}*Source and destination MD5 matches".format(name,ip)) 
                print("{0:30}*COPY COMPLETED".format(name))
                break 
            else:
                raise ValueError("**MD5 failure between source and destination files")

          else:
            if space_sw >0:
              raise ValueError("Insufficient space available on remote device")
            else:
              space_sw =1
              print("{0:30}*Delete Files".format(name))
              for row in EOSlist:
                if EOSlistaction[EOSlist.index(row)] == "DELETE":
                  output_deletefile = ssh_conn.send_command("delete flash:{0} ".format(EOSfile))
                  outputline = ("{0} DELETE FILE-{1} {2}".format(name,row,EOSlistaction[EOSlist.index(row)]))
                  print (outputline)

              

  
except ValueError as err:
  print("{0:30}*COPY HAS FAILED {1}".format(name,err)) 

ssh_conn.disconnect()

**Comment by ktbyers** [comment]
Okay, strange I checked my lab environment and it is using EOS-4.20.10M and I have no issues.

I read the above error as Paramiko complaining that there was no more data to read from the remote device (and it was expecting more data).

**Comment by eakikel** [comment]
I have tested a couple of versions of 4.19  with no issues
I have spot checked 3 different version of 4.20 code and they all fail. 

Tried setting blocking_timeout to 50 and that was no help

**Comment by eakikel** [comment]
One other thing. tried smaller file(6000 bytes) and it worked

The files I am having trouble with are 416mb EOS files

**Comment by eakikel** [comment]
TESTED with straight PARAMIKO.
Same problem. So problem is not directly with NETMIKO. It lies with PARAMIKO
Sample code below

[kikele@osbaz2dev03087 ~]$  dd if=/dev/zero of=file.txt count=110 bs=1048576
110+0 records in
110+0 records out
115343360 bytes (115 MB) copied, 0.317923 s, 363 MB/s
[kikele@osbaz2dev03087 ~]$ ssh kikele@nyc-p17-era08-ds del file.txt
Password: 
[kikele@osbaz2dev03087 ~]$ ./test-paramiko-scp.py 
nyc-p17-era08-ds-nyc-p17-era08-ds       COPY WAS Successful
[kikele@osbaz2dev03087 ~]$  dd if=/dev/zero of=file.txt count=125 bs=1048576
125+0 records in
125+0 records out
131072000 bytes (131 MB) copied, 0.403823 s, 325 MB/s
[kikele@osbaz2dev03087 ~]$ ssh kikele@nyc-p17-era08-ds del file.txt
Password: 
[kikele@osbaz2dev03087 ~]$ ./test-paramiko-scp.py 
nyc-p17-era08-ds-nyc-p17-era08-ds       COPY HAS FAILED
[kikele@osbaz2dev03087 ~]$


#!/usr/local/bin/python3
import argparse, csv, os, sys, getpass, threading, time, getopt, re, dns.resolver, paramiko, scp
import warnings
warnings.filterwarnings(action='ignore',module='.*paramiko.*')

name = "nyc-p17-era08-ds"
ip = "nyc-p17-era08-ds"
username = "kikele"
password = "*********"
filetocopy = "/home/kikele/file.txt"
from paramiko import SSHClient
from scp import SCPClient
warnings.filterwarnings(action='ignore',module='.*paramiko.*')
#strip out filename from full path
regex = re.compile(r'.*\/(\S+)') 
match = regex.search(filetocopy)
basefile = match.group(1)
#    print("BASEFILE {0}".format(basefile))

#s    print("BEFCOPY,{0},{1},{2},{3},{4},{5}".format(name,ip,vendor,model,device_osver,username,password))

try:
    ssh = SSHClient()
#        ssh.load_system_host_keys()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
#        ssh.load_host_keys(os.path.expanduser(os.path.join("~", ".ssh", "known_hosts")))
#        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(ip, username=username, password=password)
    with SCPClient(ssh.get_transport()) as scp:
        scp.put(filetocopy, "/mnt/flash/{0}".format(basefile))    

        print("{0}-{1} \tCOPY WAS Successful".format(name,ip)) 
except:
    print("{0}-{1} \tCOPY HAS FAILED".format(name,ip)) 
ssh.close()

**Comment by eakikel** [comment]
Further info.
I tracked it down to this issue in the paramiko scp client. Assume you are using that
https://github.com/jbardin/scp.py/issues/103

In my test program, I modified. the following line
adding  **socket_timeout=40**
The time 40 corresponds to file size I am trying to copy
Bigger files need larger time. With 40 I was able to transfer 550mb file
Is there anyway to handle this in netmiko
Thanks

**with SCPClient(ssh.get_transport(), socket_timeout=40) as scp:**

**Comment by ktbyers** [comment]
Okay, cool nice find...so it sounds like we just need to wire-in that SCP timeout in some way and increase it to a larger default value than 5 seconds.

**Comment by eakikel** [comment]
Sounds Good
Thanks

**Comment by netengdj** [comment]
while this is being fixed, how can we trap this exception?  I find that files are actually being transferred fine and something right at the end is generating this.  I tried to capture both scp.SCPexception and just SCPexception and neither one is valid.

**Comment by eakikel** [comment]
👍

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by carlmontanari** [comment]
Closing, see #1397

**Comment by eakikel** [comment]
copy the 3 modules you changed and tested with new session_timeout set to 60. It works!!

Thanks
