### ISSUE TITLE
no module named netmiko Windows.

### ISSUE THREAD

**Issue by nnosd** [ktbyers/netmiko#1284]
hi, 
Im brand new... and looking for help.
My problem is:
I got script written in PyCharm, netmiko is installed, all is correct, I can log in in to node and executed commands from PyCharm.

when I saved script to .py file and try to executed it, I get error no module named netmiko,
exactly same script work correct in PyCharm. 
any help or advice how to fix it?

**Comment by tonypnode** [comment]
Running in pycharm may have installed netmiko in a virtual environment. 
Check out
https://docs.python-guide.org/dev/virtualenvs/

to fix, activate the virtual environment in the commandline.

**Comment by carlniger** [comment]
@tonypnode is probably spot on. 

Going to close this as it isn't a netmiko issue. Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc (and general/python channels too) if you're still having any issues.
