### ISSUE TITLE
commit check

### ISSUE THREAD

**Issue by theLORD97** [ktbyers/netmiko#1288]
I'm trying to find a copy of a commit check code for netmiko where if its succesfully commit checks then i want to commit the code, but if it fails to print the display

I'm trying this but i don't see the commit check output

commit_check_commands = [ 'commit check' ]
commit_check = net_connect.send_config_set(commit_check_commands, exit_config_mode=False)  --> what are all the other options here, is there a list somewhere i can reference?
print (commit_check)

output
-----------
configure
Entering configuration mode
Users currently editing the configuration:
  ssoares terminal p0 (pid 66058) on since 2019-07-15 11:24:58 MDT, idle 00:05:07
      [edit]

[edit]
ssoares@acmeabaeppswt002# commit check
<i want to see the commit check succeeds portion here>

**Comment by carlniger** [comment]
The full documentation is here: https://ktbyers.github.io/netmiko/docs/netmiko/index.html

Not sure if you're looking at Junos or XR but here is the section for IOS-XR: https://ktbyers.github.io/netmiko/docs/netmiko/cisco/cisco_xr.html

And for Juniper: https://ktbyers.github.io/netmiko/docs/netmiko/juniper/juniper.html#netmiko.juniper.juniper.JuniperBase.commit

So looks like there is a commit check option in there for ya. Is that what you're looking for?

**Comment by theLORD97** [comment]
Thanks, I’ll read through it




[cid:image002.png@01D53BAC.0BAA46E0]


Sheldon Soares
Network Performance Engineer/Specialist


T +1 403 538 4164  /  C +1 403 710 7605
110, 220 12th Ave S.W. Calgary, AB T2R 0E9
AxiaFibreNet.com<http://axiafibrenet.com/>  /  LinkedIn<https://www.linkedin.com/company/axia-netmedia-corp.>  /  Twitter<https://twitter.com/axiafibre>

NOTE: This email message is intended only for the named recipient(s) above and may contain information that is privileged, confidential and/or exempt from disclosure under applicable law. If you have received this message in error or are not the named recipient(s), please immediately notify the sender via email or telephone, and delete this email message. Thank you.

**Comment by theLORD97** [comment]
So i'm not sure if that document really helped me that much, basically what i'm trying to achieve is;

When i do a commit check on a juniper box using the following code;
    commit_check_commands = [ 'commit check' ]
    commit_check = net_connect.send_config_set(commit_check_commands, exit_config_mode=False)
    sleep(5)
    print (commit_check)

Then i'm trying to search through the output and;
    if "succeed" in commit_check:
        do this
    else:
        do this

but the problem is when i print commit_check i only see this as an output
ssoares@acmeabaeppswt002#
commit check

what i should see is 
ssoares@acmeabaeppswt002# commit check
configuration check succeeds

**Comment by theLORD97** [comment]
here's an example of my code

    for interface in d[device].keys():
        print (interface)
        if "ge" in interface:
            cos_commands = [ 'set class-of-service interfaces '+ interface + ' apply-groups defaultQOS',
                             'set class-of-service interfaces '+ interface + ' scheduler-map standard_1G']
            output = net_connect.send_config_set(cos_commands, exit_config_mode=False)
            print (output)
        elif "xe" in interface:
            cos_commands = [ 'set class-of-service interfaces '+ interface + ' apply-groups defaultQOS',
                             'set class-of-service interfaces '+ interface + ' scheduler-map standard_10G']
            output = net_connect.send_config_set(cos_commands, exit_config_mode=False)
            print (output)
        else:
            print ("This is an AE bundle, please check number of links and assign scheduler-map manually")
            f = open('failed/AE_bundle.txt', 'a+')
            f.write(device + ' has an AE bundle on it, check QoS \n')
            f.close()

    commit_check_commands = [ 'commit check' ]
    commit_check = net_connect.send_config_set(commit_check_commands, exit_config_mode=False)
    sleep(5)
    print (commit_check)


    '''
    if "succeeds" in commit_check:
        commit = net_connect.send_command("commit and-quit")
        print (commit)
        print ("configuration saved on " + device)
        f = open('configured/configured.txt', 'a+')
        f.write(device +' has been configured \n')
        f.close()
    else:
        rollback = net_connect.send_command("rollback 0")
        print (rollback)
        print ("the following device " + device + " had a commit error and has been rolled back")
        f = open('failed/commit_error.txt', 'a')
        f.write('Commit check failed for ' + device + '\n')
        f.close()
    '''
    print ('\n')
    print (80*'-')

**Comment by carlniger** [comment]
Ok I think I'm tracking, how about this:


```
from netmiko import ConnectHandler


conn = ConnectHandler(host='srx1.lasthop.io', device_type='juniper_junos', username='pyclass', password='88newclass')
output = conn.send_config_set(['set system time-zone America/Denver'])
print(output)
output = conn.commit(confirm=False, check=True)
print(output)
```

The device has not that timezone configured when I start and since `confirm=False` it still doesn't when its done, but I can see the commit check output like:

```
pyclass@srx1# commit check
configuration check succeeds

[edit]
pyclass@srx1#
```

That what you're after?

**Comment by theLORD97** [comment]
i think that might be exactly what i want, as long as it just does the commit check and doesn't actually fully commit the config. 

Let me give it a try.

**Comment by carlniger** [comment]
Yep, with the `confirm=False` bits my timezone was unmodified but the candidate config had the updated one in there!

**Comment by theLORD97** [comment]
PERFECT... that did the trick... 

thanks alot man

**Comment by theLORD97** [comment]
got another problem now

**Comment by carlniger** [comment]
@theLORD97 In general we're trying to keep issues more focused on bugs/enhancements/development discussion stuff when possible, so if its not one of those things do ya mind popping onto our Slack channel [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY)?
