### ISSUE TITLE
Newer Firmware dont work - HP Procurve

### ISSUE THREAD

**Issue by inbroso** [ktbyers/netmiko#1291]
Newer firmware from 2017/18 do not work properly with netmiko,
the output gets cut and after some time it just crashes 

With older firmware from about 2013 it works perfectly fine

2017/18 looks like this: f.e. equest timed out. Instead of Request timed out
and then the error message is: OSError: Search pattern never detected in send_command_expect: 
tried many solutions out of the internet for this error message already, none worked

2013 looks like this: Request timed out

**Comment by carlniger** [comment]
Guessing this is all post Aruba/HP acquisition/merge stuff? Did you try the Aruba device type by any chance? I haven't done much w/ either HP or Aruba so not sure whats going on in that world. You're more than welcome to work on a PR to address this, otherwise there is not enough info here to do anything about it.

**Comment by ktbyers** [comment]
@inbroso Yes, second @carlniger comment. This is not enough information to help. We would probably at least need an exception stack trace and a copy of the corresponding Netmiko session_log.

Thanks.

**Comment by inbroso** [comment]
Yes it was an Aruba Device. How do I get the session_log? Im new in Python :/


And here is the whole output: 

ERROR:root:Traceback (most recent call last):
  File "c:/Users/*/Desktop/workspace/test/hpProcurve.py", line 101, in <module>
    output = net_connect.send_command('ping ' + temp + ' timeout 1')
  File "C:\Users\*\AppData\Local\Continuum\miniconda3\lib\site-packages\netmiko\base_connection.py", line 1301, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: ping\ 10\.*\.*1\.*\ timeout\ 1

**Comment by carlniger** [comment]
@inbroso [here](https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel) is an example for adding logging. Did you try changing device_type --> `aruba_os` just for kicks to see if that works better?

**Comment by inbroso** [comment]
With aruba_os it does not work at all.
Here are two logs, one for hp_procurve and one for aruba_os
[testARUBAOS.log](https://github.com/ktbyers/netmiko/files/3420741/testARUBAOS.log)
[testHPPROCURVE.log](https://github.com/ktbyers/netmiko/files/3420742/testHPPROCURVE.log)

**Comment by Linkk93** [comment]
I have tested some older and a newer HP Procurve hardware and firmware (now Aruba, but it's just a name change with the same OS). 

I have tested with: 
Procurve 2915-8G (J9562A, OS: A.15.16.0021)
Procurve 2520-8G (J9298A, OS: YC.16.08.0001)
Aruba 2930F-8G (JL258A, OS: WC.16.08.0003)

All switches could be connected with hp_procurve without problems, none worked with aruba_os. 

I have also tested aruba_os on Aruba WLAN equipment (Mobility Master and Mobility Controller), both running on ArubaOS 8.4.x. It did work for the mobility controller but not for the Mobility Master.

I guess aruba_os was for the actual (legacy) switches Aruba manufactured before the acquisition and Aruba WLAN equipment (which always was Aruba and never HP).

**Comment by ktbyers** [comment]
@inbroso I would try setting `global_delay_factor=4`. This is an argument to ConnectHandler. Use the HP ProCurve driver in Netmiko. Let us know what happens with that.

@Linkk93 Yes, that makes sense...I think the `aruba_os` device type is for legacy Aruba equipment.

**Comment by carlmontanari** [comment]
Going to close as it sounds like things are working from @Linkk93 testing.
