### ISSUE TITLE
Info returned by Palo Alto devices is partly missing

### ISSUE THREAD

**Issue by jesse-mcgraw** [ktbyers/netmiko#1294]
Netmiko v2.3.3
Palo Alto Chassis 7080, 5260 (panos version 8.1.6)

I suspect the issue I'm seeing is similar to issue #719 

For the example of sending "show system info", in looking at the debug output I see this:

```
DEBUG:netmiko:read_channel: show 
[Kuser@chassis(passive)> show system 
[Kuser@chassis(passive)> show system info

```
and the only command output I get back from netmiko is "show"

So the paloalto is sending the prompt and erasing it several times before showing the output of the command

I fixed this on my system by adding the following to PaloAltoPanosBase session_preparation:

self.disable_paging(command="set cli scripting-mode on")

```
class PaloAltoPanosBase(BaseConnection):
    """
    Implement methods for interacting with PaloAlto devices.

    Disables `enable()` and `check_enable_mode()`
    methods.  Overrides several methods for PaloAlto-specific compatibility.
    """

    def session_preparation(self):
        """
        Prepare the session after the connection has been established.

        Disable paging (the '--more--' prompts).
        Set the base prompt for interaction ('>').
        """
        self._test_channel_read()
        self.set_base_prompt(delay_factor=20)
        self.disable_paging(command="set cli pager off")
        self.disable_paging(command="set cli scripting-mode on")
        # Clear the read buffer
        time.sleep(0.3 * self.global_delay_factor)
        self.clear_buffer()
```

Perhaps there is a better, or more general, work-around but this works for me so I figured I'd offer it up for wider review

**Comment by carlniger** [comment]
@jesse-mcgraw do you know if that `set cli scripting-mode` is available on most/all PAN devices?

**Comment by jesse-mcgraw** [comment]
I don't, unfortunately. 

One other option is to expand the processing of the ANSI escape code �[K so that it erases the text from the output stream instead of just removing the escape code itself but that probably creates other problems.

**Comment by jesse-mcgraw** [comment]
It's not official but one of the engineers I heard from says "that should be available for any hw on any currently supported sw.... 6.x, 7.x, 8.x, 9.x"

**Comment by carlmontanari** [comment]
@ktbyers do we want to have this `set cli scripting-mode` set in the pan device type? Or have an option to set this or something? How do you want to handle this one? I can crank out a quick PR on it if ya want!

**Comment by jesse-mcgraw** [comment]
Has this been tested by anyone else?  I see it had some success in issue #1562 but perhaps it needs more vetting before being included

**Comment by ktbyers** [comment]
Yes, I think we should make that change. I am happy if someone wants to do additional testing on it, however.

We also need a Pull Request on it.
