### ISSUE TITLE
Huawei save_config should be changed to handle the confirmation

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1299]
```
Send 'save'

DEBUG:netmiko:read_channel: save
The current configuration will be written to the device.
Are you sure to continue?[Y/N]
```

Then you will get the abuve message and need to send a "Y" response.

From discussion on Slack, this is the general behavior of Huawei devices (this is for the 'huawei' device_type)

**Comment by eliphaslevy** [comment]
In our OLT MA5600T, there is the command "undo interactive" that suppresses these confirmations. Maybe works in these too.

Another (un)related note: the command "screen-length 0 temporary" does not work in this OLT, but I can get same effect with the command "scroll" and sending another empty command when it asks for the height, effectively setting it to zero.

**Comment by ktbyers** [comment]
@eliphaslevy On your note, you would probably have to make a different Netmiko driver for that platform (i.e. for Huawei devices that don't support `screen-length 0 temporary`).

**Comment by ktbyers** [comment]
The fix for this was merged in.
