### ISSUE TITLE
Find a way to autocheck pdoc3 for validity and common issues

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1307]
Presence of single quotes in docstring

Line lengths must be shorter than X (80 characters). Github unfortunately makes the readable area of the text very small.

Other set of things that are getting distorted.

**Comment by carlmontanari** [comment]
For point 2 above -- I dont think thats true of pdoc3 -- or are you just wanting to keep the line lengths shorter to make it all easier to read? I played w/ `pydocstyle` over the weekend and it would surely help here -- though we would still have to "fix" what it complains about of course.

**Comment by ktbyers** [comment]
Yes, it was more of a request that we need to make the line lengths short than X characters so that the docs are actually readable in GitHub.

**Comment by carlmontanari** [comment]
Closing, moving it over --> #1350
