### ISSUE TITLE
Should put a way to load ntc-templates when pip installed

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1308]
Here is a hack way of doing it:

```
from ntc_templates import parse
template_dir = parse._get_template_dir()
os.environ["NET_TEXTFSM"] = template_dir
```

It would be better, however, not to set the environment variable i.e. first try the environment variable, then call parse._get_template_dir(), then try to load them from ~/ntc-templates/templates.

Probably should pin Netmiko requirements.txt to install a specific version of ntc-templates.

**Comment by carlmontanari** [comment]
see #1413
