### ISSUE TITLE
ProxyCommand Support

### ISSUE THREAD

**Issue by coxley** [ktbyers/netmiko#131]
Should be a no-brainer since Paramiko supports this directly.

**Comment by coxley** [comment]
There are a couple options:

1. Have user provide raw ProxyCommand string via `proxy` kwarg
2. Have user provide path to ssh config (`/etc/ssh/ssh_config` or `~/.ssh/config`) and conform to connection settings they have configured.

I vote for no. 2 because it allows much more flexibility. With Paramiko you can load an openssh config and do `conf.lookup(hostname)` to get all the settings that would be required for that host. Useful because most users of ProxyCommand have it set up with wildcards, eg `*prod.example.com`.

Result would be smoother experience for user

**Comment by ktbyers** [comment]
I will have to look into this a bit. 

If you have a proposed solution, definitely free to submit a PR.

**Comment by coxley** [comment]
@ktbyers Coming up shortly, will like to get your feedback. :)

**Comment by ktbyers** [comment]
Sounds good.

**Comment by ktbyers** [comment]
This is done.
