### ISSUE TITLE
Not able to connect to remote switch through terminal server IP and port number

### ISSUE THREAD

**Issue by Baijnath-Singh** [ktbyers/netmiko#1310]
Hello Team,
   I have a switch which is connected to terminal server . I don't have mgmt IP configured on switch, hence from terminal server i can not do ssh to the switch. I have only terminal server IP address and port number for the connected switch. I am creating ConnectHandler obj with "terminal_server" as device type and passing the IP and port number. After that i am doing dispatch. Afterwards i am trying executing command but it is failing for me.
 I need immediate help :). Below is the code.

```python
import time
from netmiko import Netmiko
from netmiko import ConnectHandler
from getpass import getpass
from netmiko import redispatch


nxos1 = {
    "device_type": "terminal_server",
    "host": "X.X.X.X",
    "username": "username",
    "password": "password",
    "port": "XXXX",
    #"global_delay_factor": 2,
    "verbose": True,
    
}

net_connect = ConnectHandler(**nxos1)
net_connect.find_prompt()
net_connect.write_channel("\r")
time.sleep(1)
net_connect.write_channel("\r")
time.sleep(1)
output = net_connect.read_channel()
print(output)
print("logged in terminal server")


# Dynamically reset the class back to the proper Netmiko class
redispatch(net_connect, device_type='cisco_xe')

# Now just do your normal Netmiko operations
new_output = net_connect.send_command("show lldp neigh")
print(new_output)


new_output = net_connect.send_command("show hostname")
print(new_output)

net_connect.find_prompt()
```

**Comment by carlniger** [comment]
@Baijnath-Singh you'll need to post the stack trace and maybe (would be nice!) logs for us to be able to help you out (logging example [here](https://github.com/ktbyers/netmiko/blob/develop/examples/use_cases/case11_logging/conn_with_logging.py)). At a quick glance what you have looks pretty reasonable though so you are probably on the right track!

**Comment by ktbyers** [comment]
@Baijnath-Singh You say ConnectHandler on `nxos1`, but then you redispatch using `cisco_xe`.

What is the nature of the device you are connecting to? I.E. which platform is it?

**Comment by Baijnath-Singh** [comment]
Thanks a lot for all the responses. I made it working after adding the code to handle the connected switch prompt before redispatch.
i = 1
while i <= max_loops:
    output = net_connect.read_channel()
    #print(output, i)

    if 'login' in output:
        net_connect.write_channel(net_connect.username + '\r\n')
        time.sleep(1)
        output = net_connect.read_channel()
        #print("Found Username")
        #print(output, i)


    # Search for password pattern / send password
    if 'Password' in output:
        net_connect.write_channel(net_connect.password + '\r\n')
        time.sleep(.5)
        output = net_connect.read_channel()
        #print("Found Password")
        #print(output, i)
        # Did we successfully login
        if '>' in output or '#' in output:
            break

    net_connect.write_channel('\r\n')
    time.sleep(.5)
    i += 1

@ktbyers My terminal server is ios_xe and connected switch is nxos. Which platform type i should use in both ConnectHandler and redispatch?

**Comment by ktbyers** [comment]
`redispatch` should correspond to the device_type of the end device so in your case `cisco_nxos`.

Yes, with your pattern, you will have to manually handle the second login in code (so that looks correct).

**Comment by Baijnath-Singh** [comment]
Thanks a lot for the information.
I am facing one more problem, I am getting below back trace while connecting to the switch which is connected to the terminal server.
Traceback (most recent call last):
  File "my_netmiko-new.py", line 174, in <module>
    main()
  File "my_netmiko-new.py", line 170, in main
    dc.get_console_switch_lldp_neighbour(dct.irc_console_conn)
  File "my_netmiko-new.py", line 106, in get_console_switch_lldp_neighbour
    net_connect.find_prompt()
  File "/home/bsingh/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1092, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt: 

Though i resolved this issue after changing the base_prompt's alt_prompt_terminator from ">" to ":" in file base_connection.py.
   def set_base_prompt(
            self, pri_prompt_terminator="#", alt_prompt_terminator=":", delay_factor=1
    ):
Actually , In my device prompt has ":" as the last character at the time of login. e.g "X-X-X login:".
This fix is working but I don't want to have top up change done by me in the library. Please suggest me the right fix .

**Comment by ktbyers** [comment]
So does that imply that the `login` code that you posted earlier is failing? 


Kirk

**Comment by Baijnath-Singh** [comment]
Sorry I missed that to mention in earlier threads. But 'yes',  It was failing for me and I had to change base_prompt .

**Comment by ktbyers** [comment]
Have you looked at the `session_log` to see what is going wrong i.e. to see where things are getting out of sync with what you expect to be happening?

**Comment by Baijnath-Singh** [comment]
Thanks for the response .I would analyze session_log to check for any clue.
