### ISSUE TITLE
Cisco WLC: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by Arpanet69** [ktbyers/netmiko#1314]
Hi,

Am stuck for a few days now trying to setup a ssh connection with Cisco WLC. I started off with a basic connection script that i downloaded from your GitHub site. The problem is it doesnt connect and end up with the same error over and over again :). Following script that am using:

```
from __future__ import print_function, unicode_literals
from netmiko import Netmiko
from getpass import getpass

my_device = {
    "host": "hostname",
    "username": "username",
    "password": getpass(),
    "device_type": "cisco_wlc",
    'global_delay_factor': 4

}

net_connect = Netmiko(**my_device)

output = net_connect.send_command("show interface summary")
print(output)

net_connect.disconnect()
```
This comes with the following error:
`File "C:\Users\******\AppData\Roaming\Python\Python37\site-packages\paramiko\transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner`

What can i do to solve this issue?

Hope to hear from you!

Gr,
Arpanet86

**Comment by ktbyers** [comment]
@Arpanet69 Try increasing the `banner_timeout` to a much larger value and see if that helps you. This is an argument to ConnectHandler.

Make sure you are using the latest released version of Netmiko 2.4.1 as this added into Netmiko pretty recently.

**Comment by Arpanet86** [comment]
Hi ktbyers,

That worked for me!

hosts = {
    "host": "hostname",
    "username": "cisco",
    "password": getpass(),
    "device_type": "cisco_wlc",
    'global_delay_factor': 4

}

Thank you so much!

**Comment by nooneischgl** [comment]
Adding 'banner_timeout': 10 fixed this for me. Thanks!!
