### ISSUE TITLE
Using `?` to get all possible lists of commands in a router but not running it

### ISSUE THREAD

**Issue by whyjay17** [ktbyers/netmiko#1315]
Inside a router, if we type `?` after a command, it gives us a list of all possible subcommands.

```
output = net_connect.send_command("show {} ?".format(input_cmd))
output = output.split('\n')
```

If I do this, it gives me a list of all commands that can be followed by input_cmd. However, using `send_command` also runs the command. In the actual router, if I do `show ___ ?` it gives me a list of possible commands but does not run it. In `netmiko`, it gives me the list of all possible commands and then runs the command (e.g. `show aaa`) with out the `?`.

is there a way to get around this issue?

**Comment by ktbyers** [comment]
@whyjay17 You would probably have to do something using Netmiko's `write_channel` and `read_channel` methods and create a custom function function/read-write loop in some way.

send_command does a certain amount of normalization including adding an <enter> to the end of the command so that normalization is going to cause issues in your case.

**Comment by whyjay17** [comment]
thanks @ktbyers 
are there some examples of `write_channel` and `read_channel` that I can follow?

**Comment by carlniger** [comment]
@whyjay17 check [this out](https://github.com/ktbyers/netmiko/blob/c8570c4a466a3dace74c22733ed20b1eb86e7dbb/examples/use_cases/case13_term_server/term_server.py) for a terminal server example, but has use of write channel in there and should help get ya going! Basically read/write channel is just sending/reading from the (ssh/telnet) channel w/out the prompt normalization / determining when commands are done stuff that "normal" netmiko operations do

**Comment by whyjay17** [comment]
@carlniger Thank you!
However, I don't really see the difference between using this and the `send_command`. This is how I used it.

```
net_connect.write_channel("show aaa ?\r\n")
time.sleep(0.5)
output = net_connect.read_channel()
print(output)
```

This gives me the output of `show aaa ?` and also runs the command, which was my initial problem. How can I adjust this?

**Comment by ktbyers** [comment]
@whyjay17 You can't send the <enter> i.e. the `\r\n` or you will run into the same issue. The question mark from the CLI shouldn't require the enter i.e. it outputs when you hit the `?` mark.

**Comment by whyjay17** [comment]
@ktbyers I removed the `\r\n` 

```
net_connect.write_channel("show aaa locald trace ?")
time.sleep(0.5)
output = net_connect.read_channel()
print(output)
```

This gives me the list of commands and ends with

`RP/0/RP1/CPU0:R#show aaa locald trace`

Does this mean it's not running it?

**Comment by ktbyers** [comment]
@whyjay17 It should behave the same way it behaves on the CLI i.e. show you the next command available in your context (and help on those next commands) and then repaint the current command just prior the question mark.

So yes the command should NOT have been executed.


Regards, Kirk

**Comment by whyjay17** [comment]
Thanks @ktbyers! It solved my issue!
