### ISSUE TITLE
Inconsistent output with write_channel and read_channel

### ISSUE THREAD

**Issue by whyjay17** [ktbyers/netmiko#1316]
Thanks again for the help on https://github.com/ktbyers/netmiko/issues/1315

I am using `write_channel` and `read_channel` to parse the possible subcommands for all commands in a router.

I wrote this function below

```
def getCommandsList(input_cmd):
    res = []
    print('cmd = show {} ?'.format(input_cmd))
    net_connect.write_channel("show {} ?".format(input_cmd))
    time.sleep(0.5)
    output = net_connect.read_channel()
    output = output.split('\n')
    for i in range(len(output)):
        if i != 0 and i != len(output) - 1: # skip first and last since they are not commands
            line = output[i]
            line = line.lstrip()
            cmd, description = line.split(' ', 1)
            description = description.lstrip().replace('\r', '')
            print(cmd, description)
            res.append(str(cmd))
    return res
```

and for a single run, it works great.

```
Input: 'aaa' (show aaa ?)
Output: ['ikegroup', 'locald', 'login', 'password-policy', 'sync', 'task', 'taskgroup', 'trace', 'userdb', 'usergroup']
```

However, if I run it continuously, it gives me a weird output

```
Input: 'aaa ikegroup' (show aaa ikegroup)
Error:
Traceback (most recent call last):
  File "parse.py", line 50, in <module>
    print(getCommandsList('aaa ikegroup'))
  File "parse.py", line 35, in getCommandsList
    cmd, description = line.split(' ', 1)
ValueError: need more than 1 value to unpack
```

and when I print out the `output`, it gives me

`[u'show aaa ikegroup ?\r', u'\r                                 ^\r', u"% Invalid input detected at '^' marker.\r", u'RP/0/RP1/CPU0:FRETTA-1#show aaa show aaa ikegroup ']`

So, it seems like the output is inconsistent.

I am trying to do it recursively, but if the output is inconsistent, it will be very hard to do it.

Any help?

**===========MORE INFO================**

I tried to do this just to see the pattern of output:

```
net_connect.write_channel("show {} ?".format('aaa'))
time.sleep(0.5)
output = net_connect.read_channel()
print(output)
print('-------------')
net_connect.write_channel("show {} ?".format('aaa'))
time.sleep(0.5)
output = net_connect.read_channel()
print(output)
print('-------------')
net_connect.write_channel("show {} ?".format('aaa'))
time.sleep(0.5)
output = net_connect.read_channel()
print(output)
print('-------------')
```

this shows

```
-bash-4.2# python parse2.py
show aaa ?
  ikegroup         Show local IKE group(s)
  locald           locald sub system(cisco-support)
  login            login sub system
  password-policy  Show all the password policies configured in the system
  sync             aaa_lib_sync sub system(cisco-support)
  task             Show task information
  taskgroup        Show all the local taskgroups configured in the system
  trace            Show trace data for AAA sub system
  userdb           Show all local users with the usergroups each belong to
  usergroup        Show all the local usergroups configured in the system
RP/0/RP1/CPU0:FRETTA-1#show aaa
-------------
show aaa ?
                                 ^
% Invalid input detected at '^' marker.
RP/0/RP1/CPU0:FRETTA-1#show aaa show aaa
-------------
show aaa ?
                                 ^
% Invalid input detected at '^' marker.
RP/0/RP1/CPU0:FRETTA-1#show aaa show aaa show aaa
-------------
```
So it seems like I need a way to completely clear my input when I use the next `write_channel`.

**Comment by carlniger** [comment]
This is because you're never "hitting enter" or "backspace" to clear what you've written w/ `write_channel` so your session log should look something like this:

```
some_switch#show aaa show aaa ?
% Unrecognized command
some_switch#show aaa show aaa show aaa ?
% Unrecognized command
some_switch#show aaa show aaa show aaa
```

This is somewhat hacky but should do what you want:


```
conn.write_channel("show {} ?".format('aaa'))
time.sleep(0.1)
output = conn.read_channel()
conn.write_channel("\n")
time.sleep(0.1)
conn.clear_buffer()
print(output)
print('-------------')
conn.write_channel("show {} ?".format('aaa'))
time.sleep(0.1)
output = conn.read_channel()
conn.write_channel("\n")
time.sleep(0.1)
conn.clear_buffer()
print(output)
print('-------------')
```

Basically read the channel like you were already doing, then send newline to "clear" the stuff previously input, clear the buffer (read everything out of the channel), then carry on.

**Comment by ktbyers** [comment]
Yes, as @carlniger mentioned the router will automatically repaint the command so you have to get rid of that in some way.

Otherwise you are going to get `show aaa show aaa`

So you are going to have to delete the pending command in some way (it is not sufficient to just read--you will have to write the channel to delete the pending command).

What I typically do from the CLI is `cntl-a` and then `cntl-k` go to the beginning of the line and then delete all the characters from the cursor. This is on Cisco devices.

The key here is you need to see the behavior from the CLI and exactly mimic the behavior you want in Netmiko.

FYI, you are working on something that is reasonably tricky to do...

**Comment by whyjay17** [comment]
Thanks again @carlniger @ktbyers !
I've been using
```
redispatch(net_connect, device_type="cisco_ios")
new_output = net_connect.send_command("\n")
```
at the end of each loop instead and this seemed to work fine too.
Would `clear_buffer` be a better and fast way to do the same thing?

**Comment by ktbyers** [comment]
I am not seeing why you would use `redispatch` that would be strange to me.

clear_buffer() is an entirely a read operation so I probably wouldn't expect that to work (i.e. that just clears the data sent back to you from the device, but the command is still sitting pending on the device).

**Comment by whyjay17** [comment]
@ktbyers Thanks again!

**Comment by ktbyers** [comment]
@whyjay17 No worries...best wishes on your automating.

**Comment by whyjay17** [comment]
@ktbyers I am sorry, I should have asked this earlier, but how can I use `control-a` and 'control-k` using `write_channel`?

**Comment by ktbyers** [comment]
You will have to figure out what they translate to in terms of ASCII and then send that character code using `write_channel`.
