### ISSUE TITLE
default_enter not working for Aruba connection

### ISSUE THREAD

**Issue by xiaodonq** [ktbyers/netmiko#1318]
Follow up from issue https://github.com/ktbyers/netmiko/issues/890, i use same code but netmiko seems cannot support with default_enter, my code as below:

device = {
            'device_type': 'aruba_os',
            'ip': ip_address_of_device,
            'username': username,
            'password': password,
            'secret': password,
            'default_enter': '\r'
        }

        try:
            net_connect = netmiko.ConnectHandler(**device)
            net_connect.enable()
        except (AuthenticationException):
            print ('SSH Authentication failure on device ' + ip_address_of_device)
            continue
        command = 'configure t'
        command1 = 'mgmt-user admin root'
        aruba_pass = 'example_pass'
        print('Running lockdown commands on ' + ip_address_of_device)
        #print ("SSH prompt: {}".format(net_connect.find_prompt()))
        configure = net_connect.send_command_timing(command)
        print configure
        configure1 = net_connect.send_command_timing(command1)
        if 'Password:' in configure1:
             configure1 += net_connect.send_command_timing(aruba_pass)
             print configure1
        if 'Re-Type password:' in configure1:
             configure1 += net_connect.send_command_timing(aruba_pass)
             print configure1
        #output = net_connect.send_config_set(lockdown_commands)
        net_connect.disconnect()

Error message as below:
TypeError: __init__() got an unexpected keyword argument 'default_enter'

**Comment by ktbyers** [comment]
What version of Netmiko do you have installed?

Also need the full stack trace also.

**Comment by xiaodonq** [comment]
netmiko = 1.4.2, currently it stuck me to do trace as the defualt_enter not available.

**Comment by ktbyers** [comment]
Upgrade to newest version of Netmiko and try again.

**Comment by carlniger** [comment]
As Kirk said, use a more recent version of netmiko please. Default enter has been supported (as `\r`) for nearly a [year :)](https://github.com/ktbyers/netmiko/commit/2640137d564be207d5bbf9713b8a3949b7c5ced9#diff-4558ff5824bd2663cafb2dec7b886c3c ). Closing.
