### ISSUE TITLE
PEP8 Compliance

### ISSUE THREAD

**Issue by coxley** [ktbyers/netmiko#132]
PEP8 support is always a very nice-to-have, especially with a project receiving contributions. Fortunately `netmiko` is almost there with the following exceptions:

Flag | Issue
-------|--------
E303 | Too many blank lines
E501 | Line length > 79
F401 | Module imported, but never used

Looking at errors for the E303, it's because methods are consistently double-spaced where they should be single spaced within a class (global functions are double spaced).

E501 wouldn't be too tough to fix, a lot of what I saw was pretty straight forward.

F401 is a simple fix. It complains because `__init__.py` imports modules to be exported, but is never used beyond that. Since this is for the purpose of exporting, `__all__` should be set to a list containing these objects.

I can help/fix these if there's interest in making it conform to Python stylistic standards. :)

**Comment by ktbyers** [comment]
@coxley Yes, IMO the line length of < 80 is excessively short (so I am doing < 100). 

I am checking it using flake8 (which uses PEP8)

Here is my cat ~/.config/flake8
[flake8]
max-line-length = 100
ignore = E303,F401

E303 too many blank lines (4)       # this one doesn't matter
F401, module imported but unused    

The F401 issue PEP8 is complaining about my __init__.py files and how I am using the __init__.py to integrate the package together.

This is perfectly valid. 

I am open to suggestions for better solution on the integration of the different subdirectories in the package, but don't want to put artificial/unneeded code in just to get PEP8 to not complain.

**Comment by coxley** [comment]
Fair enough It might be worth creating a `tox.ini`/`setup.cfg` at the project level to be more obvious to contributors what style to use. Only one that might be confusing is F401. Not using `__all__` should be fine but generally you don't want unused imports littered outside `__init__.py`

Any reason for being against E303? Also, what about newline separated method arguments to prevent a change diffing the whole line/readability?

I haven't read enough of the source to be familiar with current drawbacks yet so it looks fine to me. :)

**Comment by ktbyers** [comment]
@coxley 

Okay, I added setup.cfg to main branch. Good idea.

Fair enough on the \_\_all\_\_ (we can just add this and re-enable the F401 check).

E303 is mainly because almost all the methods have two spaces between them and I don't see enough reason to go update it.

<pre>
Also, what about newline separated method arguments to prevent a change diffing the whole line/readability?
</pre>

Didn't understand the issue here? Can you expand upon it?

**Comment by coxley** [comment]
I was just asking your opinion stylistically and for diff benefit what you thought of:

```python
def my_func(
    host,
    username,
    password,
    port,
):
    '''
    This is my function
    '''
```

vs

```python
def my_func(host, username,
            password, port):
    '''
    This is my function
    '''
```

Doesn't really relate to PEP8 specifically since both are fine.

**Comment by ktbyers** [comment]
@coxley Yes, I actually prefer the multiple arguments on one line format. I think it is more readable this way. I don't like the one line per argument as then your function/method definitions get very large.

Also if you are trying to figure out the arguments, you will probably look in the comments anyways.

Obviously, just a matter of personal preference. Not a big deal either way.

**Comment by coxley** [comment]
I understand that, I just want to stay consistent stylistically in any future contributions. Could have a `CONTRIBUTING.rst/md` outlining your preferred flake8 settings and style standards, but might not matter much considering this discuission is here.

**Comment by ktbyers** [comment]
Yes, that is a good idea (the CONTRIBUTING.md file).


Kirk

On Wed, Nov 18, 2015 at 10:58 AM, Codey Oxley <notifications@github.com>
wrote:

> I understand that, I just want to stay consistent stylistically in any
> future contributions. Could have a CONTRIBUTING.rst/md outlining your
> preferred flake8 settings and style standards, but might not matter much
> considering this discuission is here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/132#issuecomment-157822507>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by ktbyers** [comment]
This is done. Didn't create any CONTRIBUTING.md. Using flake8 with the following setup.cfg file.

[flake8]
ignore = F401
max-line-length = 100
exclude = tests/*,build/*,examples/*

Need to fix the F401 issues by adding __all__, but haven't got to them.
