### ISSUE TITLE
f5_tmsh disconnect()

### ISSUE THREAD

**Issue by masadaco** [ktbyers/netmiko#1321]
I notice that ConnectHandler.disconnect() issued with devcie_type: "f5_tmsh" does not send any sort of exit command.  It is probably relying on the F5 to detect an orphaned SSH session.  Sometimes they do and sometimes they don't.  F5 also references a bug where abandoned SSH sessions do not release resources which over time degrade the box.  Suggest that "quit", locate bash prompt, and then "exit" be issued with .disconnect().

**Comment by ktbyers** [comment]
@masadaco Okay, do you want to submit a PR on this?

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/2225
