### ISSUE TITLE
issue with netmiko  

### ISSUE THREAD

**Issue by jrleriche** [ktbyers/netmiko#1322]
import netmiko
ModuleNotFoundError: No module named 'netmiko'  

I tried run a python script to connect to switches for a special work  and one morning i  run that script and here is what i got as error. I got it fisrt with my desktop , an a couple days after i started to sue my laptop with that script it works for a couple days until i get the same error. Please see below the error i got .
    import netmiko
ModuleNotFoundError: No module named 'netmiko'  

Can you please help me with that since i need that a lot

**Comment by ktbyers** [comment]
Did you install Netmiko?

i.e. what does `python -m pip list` show?

**Comment by jrleriche** [comment]
Yes I installed netmiko and I used to use it during the last 2 months 
here is the output of the  command

Package      Version
------------ -------
asn1crypto   0.24.0
bcrypt       3.1.6
cffi         1.12.3
cryptography 2.7
netmiko      2.3.3
paramiko     2.5.0
pip          19.1.1
pycparser    2.19
PyNaCl       1.3.0
pyserial     3.4
PyYAML       5.1.1
scp          0.13.2
setuptools   41.0.1
six          1.12.0
textfsm      0.4.1
wheel        0.33.4

**Comment by ktbyers** [comment]
And what does the following show:

```
$ python
Python 3.6.8 (default, Aug  2 2019, 17:42:44) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__file__
'/home/kbyers/VENV/py3_venv/local/lib/python3.6/site-packages/netmiko/__init__.py'
```

The most likely cause of this is that the `Python` that you are using does not match the `Python` you installed Netmiko into.

**Comment by jrleriche** [comment]
Then how do i  ge the problem solved ? Thanks in advance for your help  Kirk.

**Comment by ktbyers** [comment]
Are you on Windows, Linux, MacOS?

**Comment by jrleriche** [comment]
I am on Windows 10

**Comment by ktbyers** [comment]
Can you show the output from this:

```
And what does the following show (i.e. please post what happens when you do the following):

$ python
Python 3.6.8 (default, Aug  2 2019, 17:42:44) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__file__
'/home/kbyers/VENV/py3_venv/local/lib/python3.6/site-packages/netmiko/__init__.py'
```

**Comment by jrleriche** [comment]
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko._file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'netmiko' has no attribute '_file'
>>> import netmiko
>>> netmiko._file_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'netmiko' has no attribute '_file_'
>>>

**Comment by jrleriche** [comment]
Also how do i know which python version i installed netmiko into ?

**Comment by carlniger** [comment]
You can call pip for the specific python version like so: `python -m pip list | grep netmiko` that would let you know if you pip installed it for whatever `python` is linked to (python2.7 vs 3.4 or whatever `python` defaults to on your system). 

I'm going to close this as it isn't a Netmiko bug, but feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.
