### ISSUE TITLE
SSHException: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by imbouncin** [ktbyers/netmiko#1323]
Hi.
Im getting 'SSHException: Error reading SSH protocol banner' **after upgrade netmiko from 2.3.3 to 2.4.1**.
here's connection obj, pretty standard
conn = {
        'device_type': 'cisco_wlc_ssh',
        'host': controller,
        'username': user,
        'password': password,
}
I saw same issue topic but solutions from there didnt solve my problem.
So what I can try else?

**Comment by ktbyers** [comment]
Have you tried increasing the `banner_timeout` to a larger value like 30 or 60? That is usually the fix for this category of problem.

**Comment by imbouncin** [comment]
thanks. i increased banner timeout from 4 to 30 and script works now
