### ISSUE TITLE
Juniper driver strip_context_items() suggested change

### ISSUE THREAD

**Issue by shorton3** [ktbyers/netmiko#1328]
On Juniper MX2020, the extra CLI output is just {master} or {backup}. Recommend changing:
netmiko/netmiko/juniper/juniper.py  L205-206 (in your develop branch):

            r"\{master:.*\}",
            r"\{backup:.*\}",
to:
            r"\{master:?.*\}",
            r"\{backup:?.*\}",

thank you

**Comment by carlniger** [comment]
Is this applicable for all Junos versions/platforms? Also is there any scenario where the current regex would break things? Don't want to change things if we'll break anything else or its not broken!

**Comment by shorton3** [comment]
I can't say for all Junos versions/platforms. My understanding is that most all Junos devices exhibit this type of extra output regarding the redundancy roles.  Our Junos devices; however, display the {master} {backup} without the ":" and other extra text/digits, whereas other Junos devices output {master:0} or {backup:1}.  My recommendation to add the '?' allows your pattern match to work for both {master} and {master:0}, so should work for both cases, correct?

**Comment by carlniger** [comment]
Cool, yeah I think we'd end up with: `\{master:?.*\}` -- w/ the additional splat so the "dot" doesn't actually have to match anything. Open to a PR for it? If not no worries, and thanks for bringing it up!

**Comment by shorton3** [comment]
I'm not in an environment where I can contribute; sorry. Thanks for your attention.

**Comment by georgesnow** [comment]
if I get a chance. I can make the change and open PR for it.

**Comment by georgesnow** [comment]
I will also run it against the platforms I have available

**Comment by georgesnow** [comment]
I think also this might need to be updated cause is line in reference to Linecards?:

https://github.com/ktbyers/netmiko/blob/d33e5e9950c9678232553e48979141524ff1212b/netmiko/juniper/juniper.py#L202

the output is actually (capital L) and the regex isn't ignoring case: 
`{Linecard:0}`

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/2787
