### ISSUE TITLE
issues with try/except scripts

### ISSUE THREAD

**Issue by theLORD97** [ktbyers/netmiko#1329]
I'm seeing some very strange results with regards to the try/except loop..

Basically, i just have a list of devices to log in to and upgrade the SW. I have nested try's so that if it passes move on, if it fails hit the except and move to the next device...

What i'm finding is that when i run the script on the same devices multiple times, i will see different results; for example, one time it will pass, next time it will fail, 3rd time it will pass... it's not very reliable. 

[root@ocg-sh-netscript1 mrv_upgrades]# python connect.py
Password:
-----------------------------------------
Connected to htlkababclswt002
-----------------------------------------
Saved Config
----------------------------------------
Failed to upgrade FPGA
-----------------------------------------
Connected to cdgnabaaclswt002
-----------------------------------------
Saved Config
----------------------------------------
FPGA has copied successfully to cdgnabaaclswt002
----------------------------------------
Standby while FPGA upgrades, wait for prompt
----------------------------------------
FPGA upgrade complete
----------------------------------------
FPGA deleted from: cdgnabaaclswt002
----------------------------------------
Standby while the SW upgrades (up to 3 mins)
----------------------------------------
System software integration finished successfully
----------------------------------------
Scheduling Reboot for Midnight

----------------------------------------
----------------------------------------
Reboot Scheduled, device prep complete
----------------------------------------
-----------------------------------------
Connected to hlkrababclswt002
-----------------------------------------
Saved Config
----------------------------------------
Failed to upgrade FPGA

Just ran the same 3 again and see a completely different result

[root@ocg-sh-netscript1 mrv_upgrades]# python connect.py
Password:

-----------------------------------------
Connected to htlkababclswt002
-----------------------------------------
Saved Config
----------------------------------------
FPGA has copied successfully to htlkababclswt002
----------------------------------------
Standby while FPGA upgrades, wait for prompt
----------------------------------------
FPGA upgrade complete
----------------------------------------
FPGA deleted from: htlkababclswt002
----------------------------------------
Standby while the SW upgrades (up to 3 mins)
----------------------------------------
Failed to upgrade MOS

-----------------------------------------
Connected to cdgnabaaclswt002
-----------------------------------------
Saved Config
----------------------------------------
FPGA has copied successfully to cdgnabaaclswt002
----------------------------------------
Standby while FPGA upgrades, wait for prompt
----------------------------------------
FPGA upgrade complete
----------------------------------------
FPGA deleted from: cdgnabaaclswt002
----------------------------------------
Standby while the SW upgrades (up to 3 mins)
----------------------------------------
System software integration finished successfully
----------------------------------------
Scheduling Reboot for Midnight

----------------------------------------
----------------------------------------
Reboot Scheduled, device prep complete
----------------------------------------

-----------------------------------------
Connected to hlkrababclswt002
-----------------------------------------
Saved Config
----------------------------------------
Failed to upgrade FPGA

**Comment by carlniger** [comment]
Without a stack trace or a script I'm just going to close this, especially since it doesn't sound like a bug/issue. If you would like to reopen and provide some actionable info (stack trace and issue/bug w/ netmiko) feel free to do so, but please format the issue so it is readable.
