### ISSUE TITLE
SSH with Proxy DNS Issue

### ISSUE THREAD

**Issue by netengdj** [ktbyers/netmiko#1331]
I have an issue with the proxy support.  I have a proper SSH Config file, I can ssh to switches from Bash just fine.  However the switch names are not resolvable from the system where the SSH originates.  The proxy host though CAN resolve the names.  so from Bash the ssh command works as intended but Netmiko is trying to do a DNS pre check and generates an exception because the end switch is not resolvable on the script host.
is there a way to turn off this DNS check?  When i substitute the IP Address on the ConnectHandler line things work as expected.

this is the initial exception:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/netmiko/base_connection.py", line 782, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3.4/site-packages/paramiko/client.py", line 334, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.4/site-packages/paramiko/client.py", line 204, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM
  File "/usr/lib64/python3.4/socket.py", line 537, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

(company rules prevent me from posting code at this time but I am just trying this at the Interpreter with no real code to show you anyway.

net_connect = netmiko.ConnectHandler(device_type='arista_eos', host='switchname', username='user', password='pass', timeout=300, ssh_config_file = '/path/to/working/.ssh/config')

**Comment by carlniger** [comment]
A quick check makes it look like there is no flag for this in paramiko so I'm not sure we can address it w/ netmiko. Could you make an entry on /etc/hosts on your local system to 127.0.0.1 to give that something to resolve to make paramiko happy? I haven't used the proxy stuff in quite some time so not sure off the top of my head if that'll work but seems like it could be worth a shot at least!

**Comment by netengdj** [comment]
I am not allowed to change /etc/hosts on the Bastion that is the script host unfortunately.  Since this affects only a few switches I could just put them in there if I was allowed.

**Comment by daanvdsanden** [comment]
Can you share your ssh_config? I was experiencing similar issues in the past. I solved it by replacing ProxyJump (not supported in paramiko) with ProxyCommand.

**Comment by netengdj** [comment]
WOW ya know what someone else in my office pointed this out a little bit ago, that ProxyJump breaks netmiko.  OF COURSE the one directive I missed changing that on is the one my tests were hitting.  Thanks so much for reminding me of this.

**Comment by ktbyers** [comment]
Related PR https://github.com/ktbyers/netmiko/pull/908
