### ISSUE TITLE
Feature request: When using textfsm or genie templates, also return the raw CLI output

### ISSUE THREAD

**Issue by jesse-mcgraw** [ktbyers/netmiko#1332]
When using textfsm or genie to process output it might be useful to also return the unprocessed command output in addition to the processed output (instead of just one or the other)

This would be useful for logging or template verification purposes.

**Comment by carlniger** [comment]
Possible, certainly. I think, however, that having the `send_command` method return different amounts of things when given different options would be an undesirable change though. I'd be inclined to just run the command twice -- once with textfsm/genie and once without. I'd be curious what @ktbyers thinks on it.

**Comment by ktbyers** [comment]
Yes, I would just run the command twice. 

Another option is to run it once and just get the string back and then take the string and process it through Netmiko's genie and textfsm functions (though you probably would have to figure out which functions to call and maybe add a small amount of glue-code for this).

**Comment by carlniger** [comment]
Well I think that settles it! Going to close this out, hopefully one of those methods will work well enough for ya @jesse-mcgraw !

**Comment by jesse-mcgraw** [comment]
You guys were too quick for me  :)

I'll take a look into doing the processing on the raw output myself, that is probably the least invasive way to do what I'm after (logging of actual output and the ability to vet textfsm/genie parses of that output)

Thanks!

**Comment by homecyclist** [comment]
This works for me:

```
import os
from netmiko import ConnectHandler

# function that netmiko calls if use_textfsm=True:
from netmiko.utilities import get_structured_data 

# store ntc-templates on a subfolder where the script is located:
os.environ['NET_TEXTFSM'] = sys.path[0]+"\\ntc-templates\\templates" 

device = {
    'host'        : '10.0.1.1',
    'device_type' : 'cisco_ios',
    'username'    : 'cisco',
    'password'    : 'Ci$co123',
}

command = "show ip arp"
terminal = ConnectHandler(**device)

# get raw output
raw_out = terminal.send_command(command, use_textfsm=False) 

# get output same as if send_command() arg has use_textfsm=True:
textfsm_out = get_structured_data(raw_out, platform=terminal.device_type, command=command.strip())
```
