### ISSUE TITLE
HuaweiSSH to handle password change

### ISSUE THREAD

**Issue by jonito27** [ktbyers/netmiko#1334]
Hello!
I'm having the same issue that was already fix using telnet to Huawei Devices, when i try to connect via SSH the password change banner stop me to continue. i try adding the special_login_handler() but doesn't change.

**Comment by ccfgo** [comment]
add these codes in huawei.py
`time.sleep(self.global_delay_factor)
self.write_channel('n\n')
time.sleep(self.global_delay_factor)`
![image](https://user-images.githubusercontent.com/9542255/64473151-569ee980-d198-11e9-93bc-d06915e1a875.png)
![image](https://user-images.githubusercontent.com/9542255/64473241-e04eb700-d198-11e9-91f8-c36a0f93fcb8.png)

**Comment by Xianun** [comment]
> 在huawei.py中添加这些代码
> `time.sleep(self.global_delay_factor) self.write_channel('n\n') time.sleep(self.global_delay_factor)`
> ![图片](https://user-images.githubusercontent.com/9542255/64473151-569ee980-d198-11e9-93bc-d06915e1a875.png)
> ![图片](https://user-images.githubusercontent.com/9542255/64473241-e04eb700-d198-11e9-91f8-c36a0f93fcb8.png)

NICE
