### ISSUE TITLE
not sure what this error means, happens randomly when looping through a device list

### ISSUE THREAD

**Issue by theLORD97** [ktbyers/netmiko#1343]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 470, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "connect_new5.py", line 161, in <module>
    net_connect.send_config_set(reboot, exit_config_mode=True)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 1429, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/usr/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 42, in config_mode
    pattern=pattern)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 1345, in config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 542, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 478, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
`max_loops` defaults to 500 so 200 is actually providing less time.

How long does this operation taken when you do it manually.

```
Also that was in a try/except statement, if the timer maxed out it 
should have hit the except statment and move on, not crash the whole script right?
```

You didn't post your except statement...so it depends if you have the right exception handling (which it looks like you didn't since the exception happened).

**Comment by theLORD97** [comment]
Here's the last portion of the try/except.. Maybe i need to add a finally statement so it doesn't completed exit the script?  The whole process varies per device anywhere between 5-10 mins

if flag_copy:
                print("FPGA has copied successfully to %s " % (device))
                print("----------------------------------------")
                print('Standby while FPGA upgrades, wait for prompt')
                try:
                        upgrade = net_connect.send_command(command_string=upgrade_fpga, expect_string="version 0x2C5", delay_factor=20, max_loops=200)
                        sleep(5)
                        net_connect.send_command('\n')
                        print("----------------------------------------")
                        print("FPGA upgrade complete")
                        print("----------------------------------------")
                        g = open(fpga_file, 'a')
                        g.write('-----------------------')
                        g.write(device)
                        g.write('-----------------------\n')
                        g.write(upgrade + '\n')
                        g.close()
                        #removes FPGA after it has been upgraded
                        net_connect.send_command(rm_fpga)
                        print("FPGA deleted from: " + device)
                        print("----------------------------------------")
                        print("Standby while the SW upgrades (up to 5 mins)")
                        print("----------------------------------------")
                        sleep(4)
                        # Upgrades the MOS and looks for Success string before proceeding to reboot. Logs all errors to a file if failed.
                        try:
                                upgrade_mos = net_connect.send_command(command_string=upgrade_sw, expect_string="System software integration finished successfully", delay_factor=15, max_loops=200)
                                print("System software integration finished successfully")
                                print("----------------------------------------")
                                g = open(sw_file, 'a')
                                g.write('-----------------------')
                                g.write(device)
                                g.write('-----------------------')
                                g.write(upgrade_mos + '\n')
                                g.close()
                                sleep(10)
#                               p = net_connect.find_prompt()
#                               print(p)
                                print("Scheduling Reboot for Midnight")
                                print("----------------------------------------")
                                try:
                                        net_connect.send_config_set(reboot, exit_config_mode=True)
                                        print("----------------------------------------")
                                        print("Reboot Scheduled, device prep complete")
                                        print("----------------------------------------")
                                        g = open(reboot_file, 'a')
                                        g.write("Reboot has been scheduled for " + device + "\n")
                                        g.close()
                                        sleep(3)
                                except OSError as e:
                                        print(e)
                                        f = open(exception_file, 'a')
                                        f.write('REBOOT failed to device: ' + device + '\n')
                                        f.close()
                        except OSError as e:
                                print(e)
                                f = open(exception_file, 'a')
                                f.write('MOS UPGRADE failed to device: ' + device + '\n')
                                f.close()
                except OSError as e:
                        print(e)
                        f = open(exception_file, 'a')
                        f.write('FPGA UPGRADE failed to device: ' + device + '\n')
                        f.close()
        else:
                print("Failed to copy FPGA")
                f = open(exception_file, 'a')
                f.write('FPGA COPY failed to device: ' + device + '\n')
                f.close()

        net_connect.disconnect()

**Comment by theLORD97** [comment]
Should i put another except statement in there after the OSError one? That way it shouldn't break the script and move onto the next one.

**Comment by carlmontanari** [comment]
`Flat is better than nested.`

I would very much recommend flattening your code. You are only catching `OSError` which AFAIK netmiko never raises (and the exception it raises dont inherit from that base exception). If you want to catch `NetMikoTimeoutException` you need to catch that or just catch all exceptions w/  `Exception`. Going to close this as this is not a netmiko issue/bug.
