### ISSUE TITLE
net_connect.commit(and_quit=True) errors out: "Timed-out reading channel, data not available." netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by richakes** [ktbyers/netmiko#1352]
```python
import netmiko
import logging
import subprocess
from netmiko import ConnectHandler
import os
import time
#p = subprocess.run(["scp", "clab_srx","10.128.9.10:~"])
#sts = os.waitpid(p.pid, 0)

net_device = {
        'device_type' : 'juniper',
        'ip' : <removed>,
        'username' : <removed>,
        'password' : <removed>,
        'port' : 22,
        'timeout':5
        }

net_connect = ConnectHandler(**net_device)
net_connect.send_config_set('load replace clab_srx', exit_config_mode=False)
compare=net_connect.send_config_set('show | compare', exit_config_mode=False)
if str(compare) == "\n":
        print("No changes \n")
else:
        print(compare)
net_connect.commit(and_quit=True)
```

I am trying to run the above code.
But getting this error:

-bash-4.1$ python s4.py
show | compare

Traceback (most recent call last):
  File "/home/y/lib/python3.5/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/home/y/lib/python3.5/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/y/lib/python3.5/site-packages/netmiko/base_connection.py", line 529, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/home/y/lib/python3.5/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "s4.py", line 26, in <module>
    net_connect.commit(and_quit=True)
  File "/home/y/lib/python3.5/site-packages/netmiko/juniper/juniper.py", line 161, in commit
    output = self.config_mode()
  File "/home/y/lib/python3.5/site-packages/netmiko/juniper/juniper.py", line 79, in config_mode
    return super(JuniperBase, self).config_mode(config_command=config_command)
  File "/home/y/lib/python3.5/site-packages/netmiko/base_connection.py", line 1501, in config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/home/y/lib/python3.5/site-packages/netmiko/base_connection.py", line 604, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/y/lib/python3.5/site-packages/netmiko/base_connection.py", line 538, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

Any help would be really appreciated !

**Comment by carlmontanari** [comment]
Easy test would be to increase the delay factor -- could just be the device is taking a bit to do the compare. 

`"global_delay_factor": 2,` <- in your ConnectHandler. You could also try 4 for the delay factor. After that it may be useful to snag session logs if the problem persists.

**Comment by richakes** [comment]
still getting the same error even after including 

*******************************************************************************
this is what I have in the logs:

rkeswani@cfw4200>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'configure\n'
DEBUG:netmiko:Pattern is: rkeswani\@cfw4200
DEBUG:netmiko:_read_channel_expect read_data: configure
DEBUG:netmiko:_read_channel_expect read_data: ^M
warning: Clustering enabled; using private edit^M
warning: uncommitted changes will be discarded on exit^M

DEBUG:netmiko:_read_channel_expect read_data: Entering configuration mode^M

DEBUG:netmiko:_read_channel_expect read_data: ^M
{primary:node0}[edit]^M
rkeswani@cfw4200#
DEBUG:netmiko:Pattern found: rkeswani\@cfw4200 ^M
warning: Clustering enabled; using private edit^M
warning: uncommitted changes will be discarded on exit^M
Entering configuration mode^M
^M
{primary:node0}[edit]^M
rkeswani@cfw4200#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M
^M

rkeswani@cfw4200# load replace clab_srx
|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^Hload complete

{primary:node0}[edit]
rkeswani@cfw4200#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M
^M
{primary:node0}[edit]^M
rkeswani@cfw4200#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show | compare\n'
DEBUG:netmiko:read_channel: show | compare ^M

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:show | compare

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'configure\n'
DEBUG:netmiko:Pattern is: rkeswani@cfw4200
DEBUG:netmiko:_read_channel_expect read_data: configure^M

*******************************************************************************

**Comment by ktbyers** [comment]
I would get rid of your `timeout` setting.

Also I would an

```
wait_here = input("Pause here")
```

To the end of your script.


After you do this, can you re-post your debugging log?

**Comment by carlmontanari** [comment]
I'm going to close this for now, but feel free to re-open w/ Kirk's updates if this is still an issue!
