### ISSUE TITLE
nxos commit_merge doesn't catch warning

### ISSUE THREAD

**Issue by lazhao123** [ktbyers/netmiko#1357]
Hello,

In nexus switch, I setup password as "admin_new", it gives me warning, but commit_merge passed. The error is because _commit_merge( ) doesn't catch the warning.

The output shows:
config term
Enter configuration commands, one per line.  End with CNTL/Z.
N7k(config)# switchname N7k_new
N7k_new(config)# username admin password admin_new
WARNING: Password should contain characters from at least three of the following classes: lower case letters, upper case letters, digits and special characters.
N7k_new(config)# end
N7k_new# 

    def _commit_merge(self):
        try:
            output = self._send_config(self.merge_candidate)
            if output and "Invalid command" in output:        <<<<<< this fail to catch warning
                raise MergeConfigException("Error while applying config!")
        except Exception as e:
            self.changed = True
            self.rollback()
            raise MergeConfigException(str(e))

        self.changed = True
        # clear the merge buffer
        self.merge_candidate = ""

- should we add "WARNING" in output check?
- maybe when error/warning caught, the output should be included in MergeConfigException.
- is there any API to print output of commit?

**Comment by carlmontanari** [comment]
My 0.02$ would be that this should be entirely on the user to deal with. If you don't want to accept bad passwords, enable password strength check; if you don't care about that, disable it. If you really want to see the output from the command, manage passwords w/ Netmiko directly and parse the output on your own, then just use NAPALM for everything else config-wise.

**Comment by ktbyers** [comment]
Yes, this would be on the script creator to handle (i.e. should be outside of napalm).

**Comment by lazhao123** [comment]
@carlmontanari, I agree script can validate the user input to certain degree. But it would be good if script can get the command output. In customer site, we want to get log of command output. So I need to use netmiko instead of NAPALM to send configuration command to get output?

**Comment by ktbyers** [comment]
Yes, that is a bit problematic as it looks like the napalm code for `_commit_merge` does not generally return you the output of the operations.

One solution would be to create a Netmiko session_log and capture this. You could do this for both Netmiko and NAPAM-Netmiko (i.e. the napalm drivers that use Netmiko under the hood).

The other option would be to use straight Netmiko and capture it there.

The item you flagged is a bit of a problem in napalm (i.e. it would be good to be able to get the output of the interaction directly back in your python program).

**Comment by lazhao123** [comment]
It is not difficult for Napalm to show output. All you do is return output from Netmiko to caller.
for example,

In _load_cfg_from_checkpoint ( ), rollback_result contains output, but the function don't return the result to caller.
        try:
            rollback_result = self._send_command_list(commands, expect_string=r"[#>]")
        finally:
            self.changed = True
        msg = rollback_result
        if "Rollback failed." in msg:
            raise ReplaceConfigException(msg)

**Comment by ktbyers** [comment]
Need to have consistent behavior for every driver and probably should have consistent behavior for merge and replace operation...and we need tests for it.
