### ISSUE TITLE
Issues with 2960-X switches with .enable()

### ISSUE THREAD

**Issue by mcforman-auto** [ktbyers/netmiko#1368]
2960X's will not enter enable mode...

Code 

`from netmiko import ConnectHandler

switch_connect = ConnectHandler(device_type='cisco_ios', host=device_ip, username=switch_username, password=switch_password, secret=switch_secret, session_log='my_output.txt')

print(switch_connect.find_prompt())
switch_connect.enable()
print(switch_connect.find_prompt())`

my_output.txt

switch>
switch>terminal length 0
switch>terminal width 511
switch>
switch>
switch>
switch>

image=C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(2)E7, RELEASE SOFTWARE (fc3)

I can run the same code on other model of switches with no issues, but the 2960X's seem to give me the struggles. Anyone have similar issues? Or suggestions? 

No errors are generated, or trace backs.
exit code 0
 
I use the same credentials for my other model of switches, so it's not a credential issue.

**Comment by ktbyers** [comment]
Try setting global_delay_factor = 2 or 4. This is an argument to ConnectHandler.

So the issue is that you are not seeing any router prompt to output? It looks like from the above everything ran properly?

**Comment by mcforman-auto** [comment]
I've tried adjusting the global_delay_factor in the ConnectHandler, with the same results.

It does not generate an error when running but it does not enter global EXEC privilege mode.

The `print(switch_connect.find_prompt())` after `switch_connect.enable()` should print result in a shift out of user EXEC into global EXEC, which it does not as it would display the prompt "switch#".

I've done some Wireshark captures of the traffic (using the `device_type='cisco_ios_telnet` and I never even see the enable data being transmitted.

All of this is only true for these 2960-X switches. All other switches behave normally.

After some further testing I've found that the .enable() function works with other images of the 2960-X's.

Works on:
Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.0(2)EX5, RELEASE SOFTWARE (fc1)

So I'm guessing it may be something to do with the newer image on the switch we're currently deploying, which was mentioned in my first post.

Thoughts?

**Comment by ktbyers** [comment]
@mcforman-auto A bit weird.

This call here:

```
switch_connect.enable()
```

Should cause `enable` to be executed on the SSH channel which you are not seeing in the session_log.

I would probably put a Pdb breakpoint here and see what is happening:

```
    def enable(self, cmd="", pattern="ssword", re_flags=re.IGNORECASE):
        """Enter enable mode.

        :param cmd: Device command to enter enable mode
        :type cmd: str

        :param pattern: pattern to search for indicating device is waiting for password
        :type pattern: str

        :param re_flags: Regular expression flags used in conjunction with pattern
        :type re_flags: int
        """

        # add this line
        import pdb; pdb.set_trace()
        output = "" 
```

**Comment by ktbyers** [comment]
If you look at this `enable` method:

```python
        output = "" 
        msg = (
            "Failed to enter enable mode. Please ensure you pass "
            "the 'secret' argument to ConnectHandler."
        )    
        if not self.check_enable_mode():
            # This line should send 'enable' as the cmd
            self.write_channel(self.normalize_cmd(cmd))
            try: 
                output += self.read_until_prompt_or_pattern(
                    pattern=pattern, re_flags=re_flags
                )    
                self.write_channel(self.normalize_cmd(self.secret))
                output += self.read_until_prompt()
            except NetMikoTimeoutException:
                raise ValueError(msg)
            if not self.check_enable_mode():
                raise ValueError(msg)
        return output
```

You can see the comment I added where `enable` should get sent.

**Comment by mcforman-auto** [comment]
I've added the line to `base_connection.py`.

The break point did not get triggered.

When I packet capture (Wireshark) the script (using `cisco_ios_telnet` as device type), I can see the enable command being sent on other models of switches and on the same model of switches that run "older" images.

It is a bit weird.

-Little bit more info on my setup.
Version of Python (3.7.4)
I use PyCharm as my IDE.

**Comment by jcarrabine** [comment]
Ha! I was just about to post for the same issue. I don't have this issue with my Nexus switches which don't use enable, just my 2960X. I have had the <net_connect.enable()> in my code to try and it did not fix it. I also am telling <print(output)> where I get <% Invalid input detected at '^' marker>. in the terminal. I ran 

logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko"

and the logs show, among MANY other things the commands are being passed, but because of all the other debug text, I'm not sure how the terminal session is treating them. I am using the same Python version and IDE as OP. I also interface via TACACS, but again the Nexus works.

**Comment by ktbyers** [comment]
@jcarrabine Can you post me your logging output? You can strip anything that is confidential out of there.

**Comment by jcarrabine** [comment]
Sorry I have mis-spoken. I do NOT see enable or the secret being passed. I get an authentication pass at the beginning. Here is the output if its of any use. If you scroll down I have a very bare bones connection profile coded.



DEBUG:paramiko.transport:starting thread (client mode): 0x5f2c350
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.6.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] server encrypt:['aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] client mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] server mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.127.11.11: b'9001f67f0bf3b4e81e605c53711e2ce9'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:**Authentication (password) successful!**
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: 
ECC-IDF1-2960X>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
ECC-IDF1-2960X>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: ECC\-IDF1\-2960X
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: erminal length 0
               ^
% Invalid input detected at '^' marker.

ECC-IDF1-2960X>
DEBUG:netmiko:Pattern found: ECC\-IDF1\-2960X terminal length 0
               ^
% Invalid input detected at '^' marker.

ECC-IDF1-2960X>
DEBUG:netmiko:terminal length 0
               ^
% Invalid input detected at '^' marker.

ECC-IDF1-2960X>
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:Pattern is: ECC\-IDF1\-2960X
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: erminal width 511
               ^
% Invalid input detected at '^' marker.

ECC-IDF1-2960X>
DEBUG:netmiko:Pattern found: ECC\-IDF1\-2960X terminal width 511
               ^
% Invalid input detected at '^' marker.

ECC-IDF1-2960X>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: #
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: ECC-IDF1-2960X>
DEBUG:netmiko:write_channel: b'exit\n'






CODE:



from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")


cisco = {
    'device_type' : 'cisco_ios',
    'host' : '10.127.11.11',
    'username' : 'username',
    'password' : 'password',

}

net_connect = ConnectHandler(**cisco)
output = ""


print(output)
net_connect.disconnect()

**Comment by ktbyers** [comment]
Okay, yes these are different issues. Your code is never calling the `enable` method.

**Comment by ktbyers** [comment]
@jcarrabine Can you create a separate issue for yours...as I don't want to conflate problems.

**Comment by ktbyers** [comment]
FYI, 2960-X enable call is working fine in the debugging on this issue:

https://github.com/ktbyers/netmiko/issues/1374

There are other issues on the referenced problem related to the user's AAA config, but `enable` call is working fine.

**Comment by mcforman-auto** [comment]
My AAA calls local db.

Code has not changed other than the line you wanted me to add in base_connection.py.

My debug output is as follows:
_____________________________________________________________

DEBUG:netmiko:read_channel: 



User Access Verification



Username: 
DEBUG:netmiko:write_channel: b'username\r\n'
DEBUG:netmiko:read_channel: username

Password: 
DEBUG:netmiko:write_channel: b'password\r\n'
DEBUG:netmiko:read_channel: 



------ switch name ------>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

------ switch name ------>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

------ switch name ------>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0


DEBUG:netmiko:write_channel: b'terminal length 0\r\n'
DEBUG:netmiko:Pattern is: ------ switch name ------
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: terminal length 0

------ switch name ------>
DEBUG:netmiko:Pattern found: ------ switch name ------ terminal length 0

------ switch name ------>
DEBUG:netmiko:terminal length 0

------ switch name ------>
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:write_channel: b'terminal width 511\r\n'
DEBUG:netmiko:Pattern is: ------ switch name ------
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: terminal width 511

------ switch name ------>
DEBUG:netmiko:Pattern found: ------ switch name ------ terminal width 511

------ switch name ------>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

------ switch name ------>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:Pattern is: ------ switch name ------
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

------ switch name ------>
DEBUG:netmiko:Pattern found: ------ switch name ------ 

------ switch name ------>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

------ switch name ------>
DEBUG:netmiko:read_channel: 

____________________________________________________________________________________

**Comment by ktbyers** [comment]
Yes, your situation is strange as the `enable` call never happens. @mcforman-auto 

So your code is the following?

```python
from netmiko import ConnectHandler

switch_connect = ConnectHandler(device_type='cisco_ios', host=device_ip, username=switch_username, password=switch_password, secret=switch_secret, session_log='my_output.txt')

print(switch_connect.find_prompt())
switch_connect.enable()
print(switch_connect.find_prompt())
```

Can you execute this and show me the output of the execution?

**Comment by mcforman-auto** [comment]
switch>
switch>terminal length 0
switch>terminal width 511
switch>
switch>
switch>
switch>

**Comment by mcforman-auto** [comment]
`from netmiko import ConnectHandler
import yaml
import logging

yaml_credentials = yaml.safe_load(open('credentials.yml'))
switch_username = yaml_credentials['switchUser']['username']
switch_password = yaml_credentials['switchUser']['password']
switch_secret = yaml_credentials['switchUser']['secret']
router_username = yaml_credentials['routerUser']['username']
router_password = yaml_credentials['routerUser']['password']
router_secret = yaml_credentials['routerUser']['secret']

logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

device_ip = input("IP?")

switch_connect = ConnectHandler(device_type='cisco_ios', host=device_ip, username=switch_username,
                                password=switch_password, secret=switch_secret, session_log='my_output.txt')


print(switch_connect.find_prompt())
switch_connect.enable()
print(switch_connect.find_prompt())`

**Comment by ktbyers** [comment]
Yes, not the session_log the actual execution of the script.

Execute this code here:

```
from netmiko import ConnectHandler

# You will have to replace x.x.x.x with your hard-coded IP address or host name
# other values replace with hard-coded values
switch_connect = ConnectHandler(device_type='cisco_ios', host="x.x.x.x", username="admin", password="password", secret="secret", session_log='my_output.txt')

print(switch_connect.find_prompt())
switch_connect.enable()
print(switch_connect.find_prompt())
print(switch_connect.find_prompt())
print(switch_connect.find_prompt())
```

**Comment by ktbyers** [comment]
You can also execute this using Pdb and see what happens when you get to the `enable` call.

`python -m pdb my_code.py`

**Comment by mcforman-auto** [comment]
I believe I have located to source of my problem.

The character '#' exists in the hostname of some of my devices.

I haven't been able to pin it down exactly where the source of that is inside `base_connection` or `cisco_base_connection` where this check is, could you point me in the right direction?

I appreciate your responsiveness to all of this.

Moving forward going to have to make that character off limits in my hostname, now to come up with a solution to retrofit many devices...

**Comment by ktbyers** [comment]
There won't be a single place for that...you would probably have to track down different methods for that in Netmiko.

**Comment by mcforman-auto** [comment]
Thanks again, sorry for the trouble.
