### ISSUE TITLE
Send charcater after login

### ISSUE THREAD

**Issue by Noct3** [ktbyers/netmiko#1370]
Hello,

First of all, I am by no mean a python expert. This literally my first attemp at a script using netmiko.

I am trying to write a script that will connect to HP switches that are more oriented towards SMBs. They are HP 1910 (JE009A). I believe these came from the 3Com acquisiton.

I can SSH into the switch and enter the "command line" mode but I am then prompted to answer "Y" or "N". Here what it looks like:

```

root@VIMON0103:~# ssh admin@192.168.0.241
admin@192.168.0.241's password:

<SW0102> _cmdline-mode on
_All commands can be displayed and executed. Continue? [Y/N]_ y
Please input password:******
_Warning: Now you enter an all-command mode for developer's testing, some commands may affect operation by wrong use, please carefully use it with our engineer's direction._
<SW0102> system-view
_System View: return to User View with Ctrl+Z._
[SW0102]
```

Basically, I need to be able to initate the connection, enter the "_cmdline_mode on" command, answer "y" and then enter the password.

I am trying with the following script:

```
from netmiko import ConnectHandler

visw0102 = {
	'device_type': 'hp_comware',
	'ip': '192.168.0.241',
	'username': 'admin',
	'password': 'password',
}

net_connect = ConnectHandler(**visw0102)

output = net_connect.send_command('_cmdline-mode on')
print (output)
if 'continue' in output:
    output += net_connect.send_command_timing('y')
print (output)
output = net_connect.send_command('512900')
print (output)

```
_Note: 512900 is the default password to enter "command line" mode_

Then the script stops right there. It's like the 'y' character is not sent correctly or that it's not interpreted as the answer to the question.

Here's the output of the script:

```
root@VIMON0103:~# python3 test.py
All commands can be displayed and executed. Continue? [Y/N]
All commands can be displayed and executed. Continue? [Y/N]
          ^
 % Unrecognized command found at '^' position.
```

Is there a way I can send the 'y' character in a way that it would be handled correctly?

Thanks

**Comment by ktbyers** [comment]
Try this:

```python
output = net_connect.send_command_timing('_cmdline-mode on', strip_prompt=False, strip_command=False)
print (output)
if 'continue' in output:
    output += net_connect.send_command_timing('y', strip_prompt=False, strip_command=False)
print (output)
if 'ssword' in output:
    output = net_connect.send_command_timing('512900',  strip_prompt=False, strip_command=False)
print (output)
```

**Comment by Noct3** [comment]
Hi Kirk,

Thank you for you answer. I tried what your suggestion and it works but now I have another issue. Here's the full script including some other commands that I added using the same synthax:

```
from netmiko import ConnectHandler

visw0102 = {
    'device_type': 'hp_comware',
    'ip': '192.168.0.241',
    'username': 'admin',
    'password': 'password',
}

net_connect = ConnectHandler(**visw0102)

output = net_connect.send_command_timing(
    '_cmdline-mode on',
    strip_prompt=False,
    strip_command=False
)
print (output)
if 'continue' in output:
    output += net_connect.send_command_timing(
        'y',
        strip_prompt=False,
        strip_command=False
    )
print (output)
if 'ssword' in output:
    output = net_connect.send_command_timing(
        '512900',
        strip_prompt=False,
        strip_command=False
    )
print (output)
output = net_connect.send_command_timing(
        'system-view',
        strip_prompt=False,
        strip_command=False
        )
print (output)
output = net_connect.send_command_timing(
        'vlan 300',
        strip_prompt=False,
        strip_command=False
        )
print (output)
output = net_connect.send_command_timing(
        'name TEST2',
        strip_prompt=False,
        strip_command=False
        )
print (output)
```
Now here's what I get:

```

All commands can be displayed and executed. Continue? [Y/N]
_cmdline-mode on
All commands can be displayed and executed. Continue? [Y/N]
_cmdline-mode on
All commands can be displayed and executed. Continue? [Y/N]
y
Please input password:
********
Error: Invalid password.
<VISW0102>
name TEST2
          ^
 % Unrecognized command found at '^' position.
<VISW0102>
root@VIMON0103:~# 
```

The password is 512900 which is 6 characters but there seems to be 8 in the output. I did try removing the quotation mark as I though they might have been sent with the password but I got the same result.

Maybe I need to convert the password to something else? I assume it is sent as a string right now?


Thanks

**Comment by carlmontanari** [comment]
@Noct3 the password is just replaced with "********" in the log so you don't have to worry about sharing it on accident! So I'd say double and triple check your password!

**Comment by Noct3** [comment]
Hi Carl,

Thank you for you answer.

OK got it. The output also displays"******" when entering the password while connected using SSH (we can see it in my first post) so that's why I assumed there were too much characters when I was using the script.

I tried it a couple of times and made sure I had the correct password but it's still not working. That same password is working when connecting manually through SSH.

Is there a way I can log what's going on? That might help finding out what the issue is.


Thanks!

**Comment by carlmontanari** [comment]
@Noct3 you can edit this file to not replace the password so you can double check that its going through nicely: https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L399

**Comment by Noct3** [comment]
@carlmontanari Thanks Carl. I have been poking around the file for a while now but I am not really sure what I should modify for the password the be shown?

Thanks

**Comment by carlmontanari** [comment]
@Noct3 if you remove lines 402-405 the password won't get replaced with the asterisks. You'll need to modify this wherever netmiko is installed on your system in that file. You can find it easily by running the `__file__` method on netmiko in the repl like this:

```
>>> import netmiko
net>>> netmiko.__file__
'/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/netmiko/__init__.py'
>>>
```

If you're on a Mac your  output may look similar to this. In that netmiko directory find the `base_connection` file and update those lines to stop redacting the password.

**Comment by Noct3** [comment]
@carlmontanari Thanks Carl. I was able to confirm that I was editing the right file.

I did try commenting out these lines but the password still gets replaced. 

```
root@VIMON0103:~# python3
Python 3.5.2 (default, Jul 10 2019, 11:58:48)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__file__
'/root/.local/lib/python3.5/site-packages/netmiko/__init__.py'
>>>
```
I edited the `/root/.local/lib/python3.5/site-packages/netmiko/base_connection.py` file by commenting out lines 402-405 like this:

```
    def _write_session_log(self, data):
        if self.session_log is not None and len(data) > 0:
            # Hide the password and secret in the session_log
            #if self.password:
                #data = data.replace(self.password, "********")
            #if self.secret:
                #data = data.replace(self.secret, "********")
            self.session_log.write(write_bytes(data, encoding=self.encoding))
            self.session_log.flush()
```
I still can't see the password though:

```
root@VIMON0103:~# python3 test.py
_cmdline-mode on
All commands can be displayed and executed. Continue? [Y/N]
_cmdline-mode on
All commands can be displayed and executed. Continue? [Y/N]
_cmdline-mode on
All commands can be displayed and executed. Continue? [Y/N]
y
Please input password:
********
Error: Invalid password.
<VISW0102>
name TEST2
          ^
 % Unrecognized command found at '^' position.
<VISW0102>
root@VIMON0103:~# 
```
Any idea why it's still doing that?

Thanks!

**Comment by Noct3** [comment]
I think I figured it out. 

The `if` statement is case sensitive. I was telling it to look for "continue", but the actual prompt had a capital 'C' so it was skipping over it.

Once I figured that out, the rest of the script ran successfully. It's always the little things I guess.

Thank you very much for you help @ktbyers  and @carlmontanari!
