### ISSUE TITLE
Should default delay in find_prompt() be increased

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1373]
```
1066     def find_prompt(self, delay_factor=1):
1067         """Finds the current network device prompt, last line only.
1068 
1069         :param delay_factor: See __init__: global_delay_factor
1070         :type delay_factor: int
1071         """
1072         delay_factor = self.select_delay_factor(delay_factor)
1073         self.clear_buffer()
1074         self.write_channel(self.RETURN)
1075         time.sleep(delay_factor * 0.1)
```

So right now we wait `.1` second for the router to respond...should that be increased?

**Comment by carlmontanari** [comment]
I've not had an issue but can't say I'm dealing with super latent devices/links all that often. Since the delay factor is getting adjusted by the select_delay_factor method this is all tied to global delay factor anyway right?

**Comment by ktbyers** [comment]
Yes, but with a global_delay_factor of 10, we only wait a second.

 I think we might want to increase this slightly or put a bit more intelligence here (as if this gets messed up, then send_command will get messed up).

This one would be a good one to test with variable device latency if we have a method/library that can introduce variable latency in.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/1396
