### ISSUE TITLE
ssh autodetect cannot detect Cisco ios_xr

### ISSUE THREAD

**Issue by mbouwmee** [ktbyers/netmiko#1379]
Hi,
When using the ssh autodetect i cannot detect a Cisco ios_xr device.
Is this a known issue?

In the debug log information, I see the next:
____________________________________________
_DEBUG:netmiko:repr = '\r\nCisco IOS XR Software, Version 6.2.3[Default]\r\nCopyright (c) 2017 by Cisco Systems, Inc.\r\n\r\nROM: System Bootstrap, Version 3.04(20160919:102146)     [ASR9K ROMMON],_
______________________________________________

Regards,
Martien

**Comment by ktbyers** [comment]
It looks like it should work (looking at the code):

```python
   "cisco_xr": {
        "cmd": "show version",
        "search_patterns": [r"Cisco IOS XR"],
        "priority": 99, 
        "dispatch": "_autodetect_std",
    },
```

You probably need to post your Python code and a fuller capture of the log.

**Comment by mbouwmee** [comment]
Hi,
This is my Python code and a log.

regards,
Martien

#!/usr/local/py36-env/bin/python3


import threading
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import AuthenticationException
from netmiko.ssh_autodetect import SSHDetect
try:
    from Queue import Queue
except ImportError:
    from queue import Queue

def devicetype(netmiko_devicelist, username, password):
    '''Detect  devicetype'''
    error = ''
    connect_queue = Queue()
    for device, device_data in netmiko_devicelist.items():
        # Try to detemine autodetect device_types
        if device_data['device_type'] == 'autodetect':
            print('    Autodetect device_type : ' +device)
            device_data['username'] = username
            device_data['password'] = password
            device_data['secret'] = password
            my_thread2 = threading.Thread(target=detect, args=(device_data, device, connect_queue))
            my_thread2.start()

    main_thread2 = threading.currentThread()

    for a_thread in threading.enumerate():
        if a_thread != main_thread2:
            a_thread.join()

    while not connect_queue.empty():
        my_dict = connect_queue.get()
        for device, result_list in my_dict.items():
            #List=['0-ResultMsg', '1-ErrorMsg', '2-DeviceType']
            netmiko_devicelist[device]['device_type'] = result_list[2]
            print('    Device_type', device, ':', result_list[2])
            if result_list[1] != '':
                error += '\n' + 15*' ' + device + result_list[1]

    return netmiko_devicelist, error

def detect(device_data, device, connect_queue):
    '''Detect device type'''
    #List=['0-ResultMsg', '1-ErrorMsg', '2-DeviceType']
    result_list = []
    result_list.append('')
    result_list.append('')
    result_list.append('NotFound')
    try:
        guesser = SSHDetect(**device_data)
        best_match = guesser.autodetect()
        if best_match is None:
            result_list[1] = 'Error:, no auto device detection for device, ' + device
        else:
            result_list[2] = best_match
    except AuthenticationException:
        result_list[1] = ' Authentication failed.'
        print('    Authentication failed, device: ', device)
    except NetMikoTimeoutException:
        result_list[1] = ' Connection error. (IP, DNS-name,...)'
        print('    devdetect: Connection error, device: ', device)
    connect_queue.put({device: result_list})

	
devshow.log
DEBUG:paramiko.transport:starting thread (client mode): 0x9ec9b048
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.6.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-2.0
INFO:paramiko.transport:Connected (version 2.0, client Cisco-2.0)
DEBUG:paramiko.transport:kex algos:['ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 
'ecdh-sha2-nistp256', 'diffie-hellman-group14-sha1', 
'diffie-hellman-group1-sha1'] server key:['ssh-rsa'] 
client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] 
server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] 
client mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] 
server mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] 
client compress:['none'] 
server compress:['none'] 
client lang:[''] 
server lang:[''] 
kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for devicename..local: b'3be4597779b3ae3be66e4e9afa4c9371'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: ^M
*****************************************************^M
* Martien                                  devicename **^M
* Network_South                                     *^M
*****************************************************^M
^M
^M
^M
^M
RP/0/RSP0/CPU0:devicename#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show system\n'
DEBUG:netmiko:read_channel: show system^M
^M% Incomplete command.^M
RP/0/RSP0/CPU0:devicename#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'show system\r\n\r% Incomplete command.\r\nRP/0/RSP0/CPU0:devicename#'
DEBUG:netmiko:new_output = show system^M
^M% Incomplete command.^M
RP/0/RSP0/CPU0:devicename#
DEBUG:netmiko:repr = 'show system\r\n\r% Incomplete command.\r\nRP/0/RSP0/CPU0:devicename#'
DEBUG:netmiko:write_channel: b'show version\n'
DEBUG:netmiko:read_channel: show version^M
^MThu Sep 26 08:58:19.919 UTC^M

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'show version\r\n\rThu Sep 26 08:58:19.919 UTC\r\n'
DEBUG:netmiko:new_output = show version^M
^MThu Sep 26 08:58:19.919 UTC^M

DEBUG:netmiko:repr = 'show version\r\n\rThu Sep 26 08:58:19.919 UTC\r\n'
DEBUG:netmiko:write_channel: b'show sys version\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:new_output =
DEBUG:netmiko:repr = ''
DEBUG:netmiko:write_channel: b'display version\n'
DEBUG:netmiko:read_channel: ^[[K^M
Cisco IOS XR Software, Version 6.2.3[Default]^M
Copyright (c) 2017 by Cisco Systems, Inc.^M
^M
ROM: System Bootstrap, Version 3.04(20160919:102146) [ASR9K ROMMON],  ^M
^M
devicename uptime is 2 weeks, 20 hours, 23 minutes^M
System image file is "bootflash:disk0/asr9k-os-mbi-6.2.3/0x100000/mbiasr9k-rp.vm"^M
^M
cisco ASR9K Series (P4040) processor with 8388608K bytes of memory.^M
P4040 processor at 1500MHz, Revision 2.0^M
ASR-9001 Chassis^M
^M
2 Management Ethernet^M
4 TenGigE^M
4 DWDM controller(s)^M
4 WANPHY controller(s)^M
219k bytes of non-volatile configuration memory.^M
2880M bytes of hard disk.^M
3932144k bytes of disk0: (Sector size 512 bytes).^M
^M
Configuration register on node 0/RSP0/CPU0 is 0x102^M
Boot device on node 0/RSP0/CPU0 is disk0:^M
^[[K --More-- ^G^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^[[K^M
RP/0/RSP0/CPU0:devicename#how sys version^M
^M                           ^^M
% Invalid input detected at '^' marker.^M
RP/0/RSP0/CPU0:devicename#cat /etc/issue^M
^M                            ^^M
% Invalid input detected at '^' marker.^M
RP/0/RSP0/CPU0:devicename#display version^M
^M                             ^^M
% Invalid input detected at '^' marker.^M
RP/0/RSP0/CPU0:devicename#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[K\r\nCisco IOS XR Software, Version 6.2.3[Default]\r\nCopyright (c) 2017 by Cisco Systems, 
Inc.\r\n\r\nROM: System Bootstrap, Version 3.04(20160919:102146) [ASR9K ROMMON],  
\r\n\r\ndevicename uptime is 2 weeks, 20 hours, 23 minutes\r\nSystem image file is "bootflash:disk0/asr9k-os-mbi-6.2.3/0x100000/mbiasr9k-rp.vm"
\r\n\r\ncisco ASR9K Series (P4040) processor with 8388608K bytes of memory.
\r\nP4040 processor at 1500MHz, Revision 2.0\r\nASR-9001 Chassis
\r\n\r\n2 Management Ethernet
\r\n4 TenGigE\r\n4 DWDM controller(s)
\r\n4 WANPHY controller(s)
\r\n219k bytes of non-volatile configuration memory.
\r\n2880M bytes of hard disk.
\r\n3932144k bytes of disk0: (Sector size 512 bytes).
\r\n\r\nConfiguration register on node 0/RSP0/CPU0 is 0x102
\r\nBoot device on node 0/RSP0/CPU0 is disk0:
\r\n\x1b[K --More-- \x07\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x1b[K
\r\nRP/0/RSP0/CPU0:devicename#how sys version\r\n\r                           
^\r\n% Invalid input detected at \'^\' marker.
\r\nRP/0/RSP0/CPU0:devicename#cat /etc/issue\r\n\r                            
^\r\n% Invalid input detected at \'^\' marker.
\r\nRP/0/RSP0/CPU0:devicename#display version\r\n\r                             
^\r\n% Invalid input detected at \'^\' marker.\r\nRP/0/RSP0/CPU0:devicename#'
DEBUG:netmiko:new_output = ^M
Cisco IOS XR Software, Version 6.2.3[Default]^M
Copyright (c) 2017 by Cisco Systems, Inc.^M
^M
ROM: System Bootstrap, Version 3.04(20160919:102146) [ASR9K ROMMON],  ^M
^M
devicename uptime is 2 weeks, 20 hours, 23 minutes^M
System image file is "bootflash:disk0/asr9k-os-mbi-6.2.3/0x100000/mbiasr9k-rp.vm"^M
^M
cisco ASR9K Series (P4040) processor with 8388608K bytes of memory.^M
P4040 processor at 1500MHz, Revision 2.0^M
ASR-9001 Chassis^M
^M
2 Management Ethernet^M
4 TenGigE^M
4 DWDM controller(s)^M
4 WANPHY controller(s)^M
219k bytes of non-volatile configuration memory.^M
2880M bytes of hard disk.^M
3932144k bytes of disk0: (Sector size 512 bytes).^M
^M
Configuration register on node 0/RSP0/CPU0 is 0x102^M
Boot device on node 0/RSP0/CPU0 is disk0:^M
 --More-- ^G^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^H ^H^M
RP/0/RSP0/CPU0:devicename#how sys version^M
^M                           ^^M
% Invalid input detected at '^' marker.^M
RP/0/RSP0/CPU0:devicename#cat /etc/issue^M
^M                            ^^M
% Invalid input detected at '^' marker.^M
RP/0/RSP0/CPU0:devicename#display version^M
^M                             ^^M
% Invalid input detected at '^' marker.^M
RP/0/RSP0/CPU0:devicename#
DEBUG:netmiko:repr = '\r\nCisco IOS XR Software, Version 6.2.3[Default]
\r\nCopyright (c) 2017 by Cisco Systems, Inc.
\r\n\r\nROM: System Bootstrap, Version 3.04(20160919:102146) [ASR9K ROMMON],  
\r\n\r\ndevicename uptime is 2 weeks, 20 hours, 23 minutes
\r\nSystem image file is "bootflash:disk0/asr9k-os-mbi-6.2.3/0x100000/mbiasr9k-rp.vm"
\r\n\r\ncisco ASR9K Series (P4040) processor with 8388608K bytes of memory.
\r\nP4040 processor at 1500MHz, Revision 2.0
\r\nASR-9001 Chassis\r\n\r\n2 Management Ethernet
\r\n4 TenGigE\r\n4 DWDM controller(s)
\r\n4 WANPHY controller(s)
\r\n219k bytes of non-volatile configuration memory.
\r\n2880M bytes of hard disk.
\r\n3932144k bytes of disk0: (Sector size 512 bytes).
\r\n\r\nConfiguration register on node 0/RSP0/CPU0 is 0x102
\r\nBoot device on node 0/RSP0/CPU0 is disk0:
\r\n --More-- \x07\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\x08 \x08\
r\nRP/0/RSP0/CPU0:devicename#how sys version\r\n\r                           
^\r\n% Invalid input detected at \'^\' marker.
\r\nRP/0/RSP0/CPU0:devicename#cat /etc/issue\r\n\r                            
^\r\n% Invalid input detected at \'^\' marker.
\r\nRP/0/RSP0/CPU0:devicename#display version\r\n\r                             
^\r\n% Invalid input detected at \'^\' marker.\r\nRP/0/RSP0/CPU0:devicename#'
DEBUG:netmiko:write_channel: b'uname -a\n'
DEBUG:netmiko:read_channel: uname -a^M
^M                            ^^M
% Invalid input detected at '^' marker.^M
RP/0/RSP0/CPU0:devicename#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = "uname -a\r\n\r                            
^\r\n% Invalid input detected at '^' marker.\r\nRP/0/RSP0/CPU0:devicename#"
DEBUG:netmiko:new_output = uname -a^M
^M                            ^^M
% Invalid input detected at '^' marker.^M
RP/0/RSP0/CPU0:devicename#
DEBUG:netmiko:repr = "uname -a\r\n\r                            
^\r\n% Invalid input detected at '^' marker.\r\nRP/0/RSP0/CPU0:devicename#"
DEBUG:paramiko.transport:EOF in transport thread

**Comment by ktbyers** [comment]
@mbouwmee You need to strip it down to a simple use case with only the SSH auto-detection code and nothing else and no threading (i.e. you need to isolate the problem).

Also please make sure to format your code in markdown.

**Comment by carlmontanari** [comment]
Tested this on 5.3.1 and 6.5.3 and it worked without any issue. Going to close this but feel free to re-open w/ a trimmed down script/setup and formatted code so we can take a look!

**Comment by pstefanov** [comment]
I have run into a similar problem today. I had 2 IOS XR devices - one worked and the other one didn't. I found out that the reason for this is that netmiko sends by default "show version" and with IOS XR it should also send "show version brief" to satisfy the requirement for no paging as the output of show version on IOS XR can be long and several pages so this only works in certain scenarios e.g. less packages installed on IOS XR. Could we re-open this issue please and mark it as a bug?

**Comment by Trasmontinho** [comment]
Hello @pstefanov Check your software version. There's a bug on IOS XR on  6.5.2.BASE 6.5.3.BASE 7.0.1.BASE (CSCvo17475)

**Comment by ktbyers** [comment]
I think it probably should work with `show version` even if the output is paged (i.e. as long as the relevant identifier is in the first page of output which I think it should be).

It would be helpful to include the relevant log file so we could see what is going on (in the failing case)

@pstefanov 

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel
