### ISSUE TITLE
Error handling exeption when SSH is not enable on cisco device

### ISSUE THREAD

**Issue by assadniang** [ktbyers/netmiko#1383]
My issue is similar to this thread, but it was close and no resolution or workaround:
https://github.com/ktbyers/netmiko/issues/228

netmiko (2.4.2)
paramiko (2.6.0)

[an144a@mtlab-auto ~]$ python3 --version
Python 3.6.8
[an144a@mtlab-auto ~]$ 

I was testing the SSH error handling exeption on a cisco CSR1000V.

So I disabled SSH and just allowed Telnet on the device:

I get this on the output:
`######## Connecting to ptr517-vcsr ########
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

 SSH not enble on device.

Please ensure that SSH is enable on "ptr517-vcsr"

[an144a@mtlab-auto Python3]$ `

Here is the code:
`#!/usr/bin/env python
from netmiko import Netmiko
from getpass import getpass
from colorama import init
from colorama import Fore, Back, Style
from ntc_templates.parse import parse_output
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import NetMikoAuthenticationException
from paramiko.ssh_exception import SSHException
import time
import os
import re

#Connect (SSH) to the device and error handling
print('\n######## Connecting to ' + Fore.BLUE + Style.BRIGHT + device + Fore.RESET + ' ########' + Style.RESET_ALL)

try:
    net_connect = Netmiko(**vcsr)

except NetMikoTimeoutException:
    print ('\n' + Fore.RED + 'Device is not reachable.\n' + Fore.RESET)
    print('Please ensure that your device "' + device + '" is reachable.\n')
    quit()

except NetMikoAuthenticationException:
    print ('\n' + Fore.RED + ' Authentication failure.\n' + Fore.RESET)
    print('Please ensure that your device "' + device + '" user/pass is ' + Fore.GREEN + 'cisco/cisco.\n' + Fore.RESET)
    quit()

except SSHException:
    print ('\n' + Fore.RED + ' SSH not enble on device.\n' + Fore.RESET)
    print('Please ensure that SSH is enable on "' + device + '"\n')
    quit()
`
This is the error message you get when trying to connect from Linux:
`[an144a@mtlab-auto ~]$ ssh cisco@ptr517-vcsr
ssh_exchange_identification: Connection closed by remote host
[an144a@mtlab-auto ~]$`

**Comment by ktbyers** [comment]
Looks like you possibly need to handle EOFError as well.

Also please format your Python code when posting into GitHub. Python code without formatting is very hard to read.

**Comment by assadniang** [comment]
Sorry, I am a newbie here.

I did wrapped my Python code with "", not sure what happened.

**Comment by assadniang** [comment]
I will try the EOFError...
