### ISSUE TITLE
Command is send with carriage return before end of string

### ISSUE THREAD

**Issue by assadniang** [ktbyers/netmiko#1385]
Hello,

I am been struggling with this:
idtoken is a txt file which has a token id 112233444OHFTN23445...
I works if I do not have the 'force' at the end, but when it sends the 'force', it sends it on another line instead of the same line.

```
 f=open("token_id.txt", "r")
id_token = f.read()
f.close()
if force == 'yes':

        command = 'license smart register' + idtoken + ' force' 
        
        #print(command)

        output = net_connect.send_command_timing(command, delay_factor=5,max_loops=5)
        #print(output)
        print(Style.BRIGHT + '\n>>> Forcing registration...\n' + Style.RESET_ALL)
        
        time.sleep(5)
```

This is what it looks like when Netmiko sends the command, you can see it send the word 'force' on a separate line:

> Would you like to force the registration (yes/no) ? yes
> Force = yes
> license smart register idtoken ZjM0MGU0OTQtZDBlYi00YWN************ODAzMjc0%0ANDUwNzd8R3M0eE1hZG8xeWV6OGVId1VLcUJIb3lrU****************0ANDFJST0%3D%0A
>  force
> ation process is in progress. Use the 'show license status' command to check the progress and result

DEBUG:

> ptr555-vcsr#license smart register idtoken ZjM0MGU0OTQtZDBlYi00YWNmLThhYzctNTgxYmJiNjRiMTE3LTE1ODAzMjc0%0ANDUwNzd8R3M0eE1hZG8
> DEBUG:netmiko:read_channel: xeWV6OGVId1VLcUJIb3lrUHdjMG5OQ1R4d2lQWStJ%0ANDFJST0%3D%0A
> Registration process is in progress. Use the 'show license status' command to check the progress and result
> **ptr555-vcsr# force**
> % Bad IP address or host name% Unknown command or computer name, or unable to find computer address
> ptr555-vcsr#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 

This is what it is suppose to look like (one line):

> ptr555-vcsr# license smart register idtoken ZjM0MGU0OTQtZDBlYi0***** **force**
> 
> Registration process is in progress. Use the 'show license status' command to check the progress and result
> ptr555-vcsr#
> DEBUG:netmiko:read_channel:

**Comment by carlmontanari** [comment]
Guessing you are reading in a line return from your text file. Print the repr of the `id_token` after you've read it in to see if there is a new line, or just call `strip()` on `id_token`. 

Going to close as I don't think this is really a netmiko issue. If you find that netmiko is doing something it shouldn't feel free to let us know. 

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc as well as a python channel which is likely more appropriate for questions like this.

**Comment by assadniang** [comment]
Ok, thank you

Did not notice this was for issues related questions only.
Will ask the question on the Pynet slack community

**Comment by carlmontanari** [comment]
@assadniang no worries! slack is a better format for stuff like that and we try to keep the issues related to bugs or feature requests. hopefully see ya on slack!

**Comment by rikosintie** [comment]
I clicked on the slack invite link and it's expired. Is it possible to still join?

Thanks!

Michael Hubbard
Twitter - @rikosintie
blog - mwhubbard.blogspot.com
www.linkedin.com/in/mwhubbard
Minilock ID - 22LXKQertj4op8vCjpWNmGJyaGPryp3BEFv8d2y4rTzG4Q

**Comment by carlmontanari** [comment]
@rikosintie oh no! Ok try this and let me know if that’s happier: 
https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU

**Comment by rikosintie** [comment]
That worked, thanks!

Michael Hubbard
Twitter - @rikosintie
blog - mwhubbard.blogspot.com
www.linkedin.com/in/mwhubbard
Minilock ID - 22LXKQertj4op8vCjpWNmGJyaGPryp3BEFv8d2y4rTzG4Q
