### ISSUE TITLE
script failure when no prompt - CheckPoint

### ISSUE THREAD

**Issue by gichris1983** [ktbyers/netmiko#1388]
I'm working on some scripts that login to a remote device, perform a packet capture and FTP the results back to your workstation. All works well with Cisco devices but i've run into an issue on CheckPoint Firewalls.

When you initiate a capture on a CheckPoint, it doesn't go straight back to the command prompt. Rather, it just gives a number that increments as packets are collected. You have to do a CTRL + C to end the capture.

My script will get to the point where it pushes the command to start the packet capture but then it ultimately fails as it never finds a command prompt to proceed.

Forgive me if this is an easy or simple adjustment/fix. Been doing networking for many years but I'm a noob when it comes to Python. On that note, thanks for all you have done to make this transition much simpler for folks like me. 

From what I'm finding, it seems that since there is no command prompt coming back, the script fails. Is there a way to negate the requirement of a command prompt being present?

My goal is to send the capture command then get a prompt to hit enter when i want the capture to end, at which point net_connect.send_command_timing("\x03") is sent to do the CTRL + C and then the script is continued.

Thanks for your help,
Chris

**Comment by carlmontanari** [comment]
Hi @gichris1983 take a look at this [example](https://github.com/ktbyers/netmiko/blob/develop/examples/use_cases/case5_prompting/send_command_prompting.py) which may help out. 

If there is something that is consistent in the prompt (like "packets received" before it says the number of packets or something) you could look for that, then sleep your script and send the ctrl+c whenever you want. 

If that doesnt work you may end up needing to "go lower" and use the `read_channel` and `write_channel` methods which just read/write and don't care about prompts.

**Comment by gichris1983** [comment]
I'll give that a shot Carl. Thanks for such a quick response!

**Comment by carlmontanari** [comment]
Should have clarified -- the "if there is something that is consistent in the prompt you could look for that" bit I meant you could use something similar to that linked example. Sorry re-read that and it probably wasn't very clear.

**Comment by gichris1983** [comment]
no worries. i see where you were going with that. In this case there is a constant. It always starts with the number 0 as it increments as packets are captured. I just tried that and i'm in business. Thanks so much for your help!

**Comment by carlmontanari** [comment]
Boom, glad it was easy to get rolling. Going to close this out then!

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.

**Comment by gichris1983** [comment]
Cool deal. Thanks again!
