### ISSUE TITLE
Running send_command with variable not working.

### ISSUE THREAD

**Issue by nlspears** [ktbyers/netmiko#1402]
What am I doing wrong below. I am trying to run a show run command from the list intfaces using the variable x. I get no output.

```python
for line in ipfile:
    device['ip']=line.strip()
    print("Connecting to Device " + line)
    net_connect = ConnectHandler(**device)
    time.sleep(2)
    print ("Checking Interface Configurations")
    intfilter = net_connect.send_command("sh run | i Gi.")
    striplist = intfilter.rstrip()
    intfaces = []
    intfaces.append(striplist)
    for x in intfaces:
        intconfig = net_connect.send_command("sh run " + x)
        print(intconfig)
```

****the indentation doesn't seem to show up

**Comment by ktbyers** [comment]
Can you print the actual command you execute and post it here:

```
    for x in intfaces:
       cmd = "show run " + x
       print(cmd)
       intconfig = net_connect.send_command(cmd)
       print(intconfig)
```

**Comment by nlspears** [comment]
The output I get is this:

show run interface GigabitEthernet0/0
interface GigabitEthernet0/1
interface GigabitEthernet0/2
interface GigabitEthernet0/3
interface GigabitEthernet1/0
interface GigabitEthernet1/1
interface GigabitEthernet1/2
interface GigabitEthernet1/3
interface GigabitEthernet2/0
interface GigabitEthernet2/1
interface GigabitEthernet2/2
interface GigabitEthernet2/3
interface GigabitEthernet3/0
interface GigabitEthernet3/1
interface GigabitEthernet3/2
interface GigabitEthernet3/3

**Comment by nlspears** [comment]
Essentially what I am trying to accomplish is the "iplist" is a list of switch ip's. I want to log into each pull a list of interfaces, then run the sh run interface x/x on the list of interfaces in "intfaces"

**Comment by ktbyers** [comment]
I assume you meant `show run` for each of the above?

i.e.

```
show run interface GigabitEthernet0/0
show run interface GigabitEthernet0/1
show run interface GigabitEthernet0/2
show run interface GigabitEthernet0/3
```

**Comment by nlspears** [comment]
Yes, that is what I am trying to accomplish with the for loop.

**Comment by nlspears** [comment]
Here is the entire script for context.
##imports python modules needed to work
from netmiko import ConnectHandler
import time, sys, getpass, paramiko

##selects the correct Netmiko class based upon the device_type.
## I then define a network device dictionary consisting of a device_type, ip, username, and password.
user = raw_input("Enter your SSH username: ")
pword = getpass.getpass()

device = {
    'device_type': 'cisco_ios',
    #'ip': '192.168.43.10',
    'username': user,
    'password': pword,
    #'secret':'password'
}
ipfile=open("iplist.txt") #This file contains a list of switch ip addresses.
#print ("Please doublecheck your configuration in the config file. Please stop and figure out what you're about to do...")
#device['username']=input("Enter your SSH username:  ")
#device['password']=getpass.getpass()
configfile=open("configfile.txt") #opening the config file with the changes you want to push
configset=configfile.read() ##reads the config file
configfile.close() #closes the config file

for line in ipfile:
    device['ip']=line.strip()
    print("Connecting to Device " + line)
    net_connect = ConnectHandler(**device)
    time.sleep(2)
    print ("Checking Interface Configurations")
    intfilter = net_connect.send_command("sh run | i Gi.")
    striplist = intfilter.rstrip()
    intfaces = []
    intfaces.append(striplist)
    for x in intfaces:
       cmd = "show run " + x
       print(cmd)
       intconfig = net_connect.send_command(cmd)
       print(intconfig)

**Comment by ktbyers** [comment]
Print out `intfaces`...that output is not what you think it is:

```
    intfilter = net_connect.send_command("sh run | i Gi.")
    striplist = intfilter.rstrip()
    intfaces = []
    intfaces.append(striplist)
```

You have a bug here...

**Comment by nlspears** [comment]
I get the below:

[u'interface GigabitEthernet0/0\ninterface GigabitEthernet0/1\ninterface GigabitEthernet0/2\ninterface GigabitEthernet0/3\ninterface GigabitEthernet1/0\ninterface GigabitEthernet1/1\ninterface GigabitEthernet1/2\ninterface GigabitEthernet1/3\ninterface GigabitEthernet2/0\ninterface GigabitEthernet2/1\ninterface GigabitEthernet2/2\ninterface GigabitEthernet2/3\ninterface GigabitEthernet3/0\ninterface GigabitEthernet3/1\ninterface GigabitEthernet3/2\ninterface GigabitEthernet3/3']

Excuse my ignorance. I am very green at this. Isn't this just a list with line breaks? Else how do I clean it up?

**Comment by ktbyers** [comment]
It is a one element list...so you have one great big string stuffed inside the list.

When you loop through this, your loop variable `x` will be that great big string.

You probably want to use `splitlines()` to break up the string i.e. instead of using .rstrip() do something like:

```
    intfilter = net_connect.send_command("sh run | i Gi.")
    striplist = intfilter.strip()
    # no append--this will create a list
    intfaces = striplist.splitlines()
```

**Comment by nlspears** [comment]
That worked! It is now spitting out the configs of each interface. Thank you!
