### ISSUE TITLE
send_config_set or send_config_from_file not changing config of interface

### ISSUE THREAD

**Issue by nlspears** [ktbyers/netmiko#1404]
This is a continuation of my earlier post in #1402 .  The script is below. It runs through without error, but the interface configs don't seem to be sent. I've tried the config from file and config set. Below is the config from file.

##imports python modules needed to work
from netmiko import ConnectHandler
import time, sys, getpass, paramiko

user = raw_input("Enter your SSH username: ")
pword = getpass.getpass()

device = {
    'device_type': 'cisco_ios',
    #'ip': '192.168.43.10',
    'username': user,
    'password': pword,
    #'secret':'password'
}
ipfile=open("iplist.txt") #This file contains a list of switch ip addresses.
isefile=open("isefile.txt") #opening the config file with the changes you want to push
iseconfig=isefile.read() ##reads the config file
isefile.close() #closes the config file

for line in ipfile:
    device['ip']=line.strip()
    print("Connecting to Device " + line)
    net_connect = ConnectHandler(**device)
    time.sleep(2)
    print ("Checking Interface Configurations")
    intfilter = net_connect.send_command("sh run | i Gi.")
    striplist = intfilter.strip()
    intfaces = striplist.splitlines()
    for x in intfaces:
       intconfig = net_connect.send_command("sh run " + x + " | i dot1x")
       findise = intconfig.find("dot1x")
       if findise > 0:
           isefile = "isefile.txt"
           print(net_connect.find_prompt())
           print ("Applying Configuration to " + x)
           iseoutput1 = net_connect.send_config_from_file(isefile)
       else:
           print("Non-ISE interface")

**Comment by ktbyers** [comment]
These don't seem to be Netmiko issues (i.e. more issues with your program).
