### ISSUE TITLE
Review Fortinet disable paging solution

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#141]

**Comment by ktbyers** [comment]
Fortinet code since it has its own establish_connection will have an issue that it won't support use_keys.

It is pretty ugly to have to duplicate this code and update it in two place.

**Comment by brutus333** [comment]
One idea may be to monkey patch invoke_shell in the disable_paging method if we need to apply the terminal workaround.

**Comment by ktbyers** [comment]
establish_connection was removed from fortinet driver a while back so this should be resolved.
