### ISSUE TITLE
config_changes.py errors

### ISSUE THREAD

**Issue by telus-beep** [ktbyers/netmiko#1411]
Hi I am new to python and coding. When I run the code for config change from your example I get these errors. May you please provide me some input.

C:\Users\t940908\Desktop>python script.py
Password:
Traceback (most recent call last):
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 534, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 19, in <module>
    output = net_connect.send_config_set(cfg_commands)
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 1607, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 1514, in config_mode
    if not self.check_config_mode():
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\cisco\cisco_ios.py", line 32, in check_config_mode
    check_string=check_string, pattern=pattern
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\cisco_base_connection.py", line 38, in check_config_mode
    check_string=check_string, pattern=pattern
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 1501, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 609, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\t940908\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 543, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by carlmontanari** [comment]
I assume you are referring to [this](https://github.com/ktbyers/netmiko/blob/develop/examples/configuration_changes/config_changes.py) script? Looks like its maybe failing to get into/validate getting into configuration mode. What privilege level does the user you are connecting as have? Can you post your script? Also please use the formatting options to make things more readable --- enclosing code/traceback with "triple ticks" (under escape key on US keyboards).

**Comment by telus-beep** [comment]
I am sorry about the formatting, this is the script I am suing. the IP is Axed out.

#!/usr/bin/env python
from __future__ import print_function, unicode_literals

# Netmiko is the same as ConnectHandler
from netmiko import Netmiko
from getpass import getpass

my_device = {
    "ip": "x.x.x.x.",
    "username": "cisco",
    "password": getpass(),
    "device_type": "cisco_ios",
}

net_connect = Netmiko(**my_device)
cfg_commands = ["logging buffered 10000", "no logging console"]

# send_config_set() will automatically enter/exit config mode
output = net_connect.send_config_set(cfg_commands)
print(output)

net_connect.disconnect()

**Comment by telus-beep** [comment]
I am running this this script form cmd prompt, are you asking about the privilege level of cmd user?

**Comment by carlmontanari** [comment]
No worries!

I'm asking about the priv level of that `cisco` user. If you ssh to that host w/ that username -- do you end up w/ a `>` prompt or a `#` prompt?

**Comment by telus-beep** [comment]
Yes, that user is able to ssh into device and get the prompt.

**Comment by telus-beep** [comment]
I am trying to write a code which could update 450 cisco devices on our network. these are the requirements.
1.  copy ios from tftp to flash
2.  verify md5
3.  do the ios upgrade.
4.  need to change 4 lines of configuration.
5.  reload the device.
6. post check to verify interface, bgp and ospf are up.

**Comment by telus-beep** [comment]
> No worries!
> 
> I'm asking about the priv level of that `cisco` user. If you ssh to that host w/ that username -- do you end up w/ a `>` prompt or a `#` prompt?

I end up with > prompt.

sorry didn't read it carefully earlier.

**Comment by carlmontanari** [comment]
:)

Ok so I'm going to close this as we generally try to keep issues for bugs or feature enhancement discussion and things like that. But before closing...

Since you are getting dropped into "exec" mode (`>`) you will need to pass the enable secret password to the ConnectHandler as well. You can see how to deal w/ enable stuff [here](https://github.com/ktbyers/netmiko/blob/develop/examples/enable/enable.py)

For OS upgrade stuff, check out [this link](https://pynet.twb-tech.com/blog/nornir/os-upgrade-p1.html) -- it uses Nornir in addition to Netmiko, but the overall process stuff in this article should help you out. 

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues or want to chat about your project!

**Comment by telus-beep** [comment]
> :)
> 
> Ok so I'm going to close this as we generally try to keep issues for bugs or feature enhancement discussion and things like that. But before closing...
> 
> Since you are getting dropped into "exec" mode (`>`) you will need to pass the enable secret password to the ConnectHandler as well. You can see how to deal w/ enable stuff [here](https://github.com/ktbyers/netmiko/blob/develop/examples/enable/enable.py)
> 
> For OS upgrade stuff, check out [this link](https://pynet.twb-tech.com/blog/nornir/os-upgrade-p1.html) -- it uses Nornir in addition to Netmiko, but the overall process stuff in this article should help you out.
> 
> Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues or want to chat about your project!

Thanks for all the info.
