### ISSUE TITLE
Source Files

### ISSUE THREAD

**Issue by telus-beep** [ktbyers/netmiko#1412]
#!/usr/bin/env python
from __future__ import print_function, unicode_literals

from getpass import getpass
from netmiko import ConnectHandler, file_transfer

password = getpass()

cisco = { 
    'device_type': 'cisco_ios',
    'host': 'device1.domain.com',
    'username': 'admin',
    'password': password,
    'file_system': 'flash:'
}
arista = { 
    'device_type': 'arista_eos',
    'host': 'device2.domain.com',
    'username': 'admin',
    'password': password,
    'file_system': '/mnt/flash',
}
junos = { 
    'device_type': 'juniper_junos',
    'host': 'device3.domain.com',
    'username': 'admin',
    'password': password,
    'file_system': '/var/tmp',
}
nxos = { 
    'device_type': 'cisco_nxos',
    'host': 'device4.domain.com',
    'username': 'admin',
    'password': password,
    'file_system': 'bootflash:'
}

source_file = 'test1.txt'
dest_file = 'testa.txt'
direction = 'put'

for net_device in (cisco, arista, junos, nxos):
    file_system = net_device.pop('file_system')

    # Create the Netmiko SSH connection
    ssh_conn = ConnectHandler(**net_device)
    transfer_dict = file_transfer(ssh_conn,
                                  source_file=source_file, 
                                  dest_file=dest_file,
                                  file_system=file_system, 
                                  direction=direction,
                                  overwrite_file=True)
    print(transfer_dict)
    pause = input("Hit enter to continue: ")

What is the source and destination of these files?

**Comment by ktbyers** [comment]
source is the name and potentially path of the source_file you want to transfer to the remote device.

destination is the name of the file that you want on the remote network device.

**Comment by telus-beep** [comment]
Thanks for the reply. I am new to coding and python. Can I source the file from Cisco router which is acting as a tftp server? 
The ios is stored on flash of cisco router.

My project is this 
I am trying to write a code which could update 450 cisco devices on our network. these are the requirements.

1.copy ios from tftp to flash
2.verify md5
3.do the ios upgrade.
4.need to change 4 lines of configuration.
5.reload the device.
6.post check to verify interface, bgp and ospf are up.

**Comment by carlmontanari** [comment]
Source file would be local to where you are running your script.

Please use the Slack channel for questions.
