### ISSUE TITLE
New SCP timeout needs to be fixed to work with all the child classes

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1416]
$ grep 'FileTransfer' `find . -name '*.py'` | grep class
./cisco_base_connection.py:class CiscoFileTransfer(BaseFileTransfer):
./juniper/juniper.py:class JuniperFileTransfer(BaseFileTransfer):
./linux/linux_ssh.py:class LinuxFileTransfer(CiscoFileTransfer):
./cisco/cisco_asa_ssh.py:class CiscoAsaFileTransfer(CiscoFileTransfer):
./cisco/cisco_xr.py:class CiscoXrFileTransfer(CiscoFileTransfer):
./cisco/cisco_nxos_ssh.py:class CiscoNxosFileTransfer(CiscoFileTransfer):
./cisco/cisco_ios.py:class CiscoIosFileTransfer(CiscoFileTransfer):
./cisco/cisco_ios.py:class InLineTransfer(CiscoIosFileTransfer):
./arista/arista.py:class AristaFileTransfer(CiscoFileTransfer):
./scp_handler.py:class BaseFileTransfer(object):
./dell/dell_os10_ssh.py:class DellOS10FileTransfer(BaseFileTransfer):
./ciena/ciena_saos.py:class CienaSaosFileTransfer(BaseFileTransfer):

**Comment by ktbyers** [comment]
Relevant attribute:

```
       socket_timeout=10.0
```

**Comment by carlmontanari** [comment]
#1417
