### ISSUE TITLE
Connect to cisco device with "login" keyword

### ISSUE THREAD

**Issue by sohalevi** [ktbyers/netmiko#1418]
Hello,

I am new to netmiko, and I want to find out if it is possible to connect to a cisco device using netmiko if the ssh command in rbash is not allowed. Instead the command "login < ip address >" is allowed (which will use ssh as protocol), after which the password needs to be entered at the indicated password prompt.

Is this possible to accomplish in netmiko?

Thank you!
Levente

**Comment by carlmontanari** [comment]
@sohalevi Have you tried it? Netmiko doesn't use sub process to make calls to the users shell -- it creates a socket and creates a paramiko object (which also doesn't use sub process). So I'm not sure that having a locked down shell would matter... assuming you have appropriate permissions to install netmiko/paramiko/python/etc.

Let me know if I'm just misunderstanding?

**Comment by sohalevi** [comment]
@carlmontanari I think you are right, only I tried like this:

_```
username = input('Enter your username: ')
password = input('Enter your password: ')

jumpserver = {
    'device_type': 'terminal_server',
    'ip': 'X.X.X.X',
    'username': username,
    'password': password,
    'global_delay_factor': 5
}

cisco_test = {
    'device_type': 'cisco_ios',
    'host': 'Y.Y.Y.Y',
    'username': username,
    'password': password,
    'verbose': False,
}

net_connect = ConnectHandler(**jumpserver)
print(net_connect.find_prompt())


net_connect = ConnectHandler(**cisco_test)
time.sleep(5)
print(net_connect.find_prompt())

net_connect.send_command('show version | i uptime')
```_

Problem was I did not get through the second handler.



I found a solution online, to send login command to cisco device, and to redispatch to ios device:

`username = input('Enter your username: ')
password = input('Enter your password: ')

jumpserver = {
    'device_type': 'terminal_server',
    'ip': 'X.X.X.X',
    'username': username,
    'password': passw,
    'global_delay_factor': 5
}

#First connection
net_connect = ConnectHandler(**jumpserver)
print(net_connect.find_prompt())
host = 'Y.Y.Y.Y'

#Second connection
net_connect.write_channel('login ' + host + '\n')
time.sleep(2)
redispatch(net_connect, device_type='cisco_ios', session_prep=False)


print(net_connect.send_command('show version | i uptime'))`


This way it worked.

Still using the login command though. I do not know if it can be solved without login command, to only use and create a socket. I have no rights to modify what is on jumpserver.

**Comment by carlmontanari** [comment]
Yeah, sounds like redispatch is the answer for what you've got going on. Sounds like this is solved, so I'll close it!
