### ISSUE TITLE
"with ConnectHandler (**device)..... takes time to exit

### ISSUE THREAD

**Issue by shesh1123** [ktbyers/netmiko#1419]
Hi,

When I use ConnectHandler directly it works fine.

However when I use "with ConnectHandler(**device) as cli...." , the disconnect takes time.
It logs in and gets the output, but then its stuck for about 7 secs
I tried using fast_cli, but still no change.

When I use SSH instead of Telnet, its slightly fast, but still slow as compared to when using the normal "connection = ConnectHandler(**device).

Not sure if I should tweak something, or is this expected.
Any help would be appreciated.

Thanks.

EG:

This is normal:

```python
def get_connection(host):
    net_connect = ConnectHandler(host,username= "user",password= password,secret=password,device_type= "cisco_ios_telnet")
    net_connect.enable()
    print(net_connect.send_command(command))
    net_connect.disconnect()

get_connection('Router1')
```

This is slow to disconnect:

```python
for host in args.host:
    with ConnectHandler(host,username= "user",password= password,secret=password,device_type= "cisco_ios",fast_cli=True) as cli:
        result = cli.send_command(command)
        print (result)
```

**Comment by carlmontanari** [comment]
Same device? I've just tested with the following two super simple tests and had very similar results (sample set of one though!):

```
from netmiko import ConnectHandler
with ConnectHandler(host='172.31.254.1', device_type='cisco_ios', username='user', password='password') as conn:
    print(conn.send_command("show version"))
```

This took: `real	0m6.375s`


And.. without the context manager:

```
from netmiko import ConnectHandler
conn = ConnectHandler(host='172.31.254.1', device_type='cisco_ios', username='user', password='password')
print(conn.send_command("show version"))
conn.disconnect()
```

This took `real	0m6.944s`

FWIW the context manager exit just calls disconnect anyway: https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L326 

If this is an actual issue, please don't compare telnet to ssh or visa versa as there will obviously be differences there. Let us know if there is a repeatable and comparable difference and we can maybe take a closer look.

**Comment by shesh1123** [comment]
Hi Carl,

Thanks for reply.

I am using the non-context-manager version for now.

But will test the context-manager setup later on.

Will update, how it goes. Thanks

**Comment by carlmontanari** [comment]
Going to go ahead and close this, but feel free to reopen if you end up finding any big differences/delays.
