### ISSUE TITLE
Netmiko Command returning only partial output. Stops after 20 lines and prompts to continue

### ISSUE THREAD

**Issue by RDamuth** [ktbyers/netmiko#1420]
I am trying to use Netmiko to connect to a device and pull the ospf database. When I issue the command from a ssh terminal application(secure-crt in this case) the router returns the full database ( 20+ devices) with no prompt. When I use Netmiko after the router returns 20 lines it stops and requests to press any key to continue. I have tried some of the recommendations from other posts, but have had no luck. Attached is the script I wrote and the outputs from both logging and what the device shows. Any help would be appreciated. 

The code:
[get_ospf_database.py.txt](https://github.com/ktbyers/netmiko/files/3725356/get_ospf_database.py.txt)

Logging output:
[output_netmiko_ospf_.log](https://github.com/ktbyers/netmiko/files/3725369/output_netmiko_ospf_.log)

Secure-CRT output:
[output_with_ssh_client.txt](https://github.com/ktbyers/netmiko/files/3725373/output_with_ssh_client.txt)

**Comment by ktbyers** [comment]
@RDamuth Can you re-test this with the Netmiko `develop` branch. We have done a lot of work on the reliability on imporving the reliability of that.

Let me know if that works or fails.

**Comment by RDamuth** [comment]
Sorry, I am very new to python and Netmiko. Is that a separate installer or can it be run through the PIP installer. 

Thank you for your patience

**Comment by RDamuth** [comment]
It looks like what fixed it was changing the device type and removing the
enable secret from an earlier send command. I was following along with your
basic class and saw the device type I actually needed showed up. From there
is was only a few minutes of trial and error. It appears to be working now.
I am outputting the entire ospf database to my script.

Thanks you.
