### ISSUE TITLE
No User Input

### ISSUE THREAD

**Issue by Skizzzz** [ktbyers/netmiko#1425]
Im trying to make it so the user can input things such as username, ip, password...
I got this error
`Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Admin\Desktop\Code\testing.py", line 8, in find_int
    net_connect = Netmiko(**switch)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\netmiko\ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\netmiko\base_connection.py", line 317, in __init__
    self._open()
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\netmiko\base_connection.py", line 322, in _open
    self.establish_connection()
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\netmiko\base_connection.py", line 897, in establish_connection
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Authentication failure: unable to connect cisco_ios 192.168.1.68:22
Authentication failed.`

Here is the full code

`from netmiko import *
from tkinter import *

def find_int():

    global output

    net_connect = Netmiko(**switch)
    dot1x = "show ip interface brief"
    print()
    print(net_connect.find_prompt())
    output = net_connect.send_command(dot1x)
    net_connect.disconnect()
    print(output)
    Label(text = "").pack()
    Label(text = output, bg = "blue").pack()

def main_screen():

    global screen 
    global usernamepy
    
    screen = Tk()
    screen.geometry("600x500")
    screen.title("ISE")
    Label(text = "Company", bg = "gray", width = "600", height = "2").pack()
    Label(text = "").pack()

    usernamepy = StringVar()

    Label(text = "Username: ").pack()
    Entry(screen, textvariable = usernamepy).pack()
    Label(text = "").pack()
    Button(text = "Find Interfaces", height = "2", width = "10", command = find_int).pack()

    screen.mainloop
main_screen()

usernamepy = usernamepy.get()

switch = {
	"host": "192.168.1.68",
	"username": usernamepy ,
	"password": "password",
	"device_type": "cisco_ios",
	"port" : 22,
	"secret": "enable",
}`

**Comment by carlmontanari** [comment]
`Authentication failure: unable to connect cisco_ios 192.168.1.68:22 Authentication failed` is telling you your auth failed. I don't think this is a netmiko issue so I'm going to close this, but I would definitely recommend removing all of the complexity and just getting things working with netmiko first, then adding user input then adding tkinter.
