### ISSUE TITLE
API to update/Edit SSH_MAPPER_BASE dict

### ISSUE THREAD

**Issue by Faizan680** [ktbyers/netmiko#1426]
Hi, 

Is there a way we can update/edit "SSH_MAPPER_BASE" dict so that before using auto_detect we can call an API and add/remove entries of device-type in detection. This will help when we know in our network we are only going to detect maybe Cisco devices (ios, nxox or XR etc. ) and hence reduce the time it takes to detect device-type from minutes to sec.

**Comment by carlmontanari** [comment]
```
>>> netmiko.ssh_autodetect.SSH_MAPPER_BASE
{'alcatel_aos': {'cmd': 'show system', 'search_patterns': ['Alcatel-Lucent'], 'priority': 99, 'dispatch': 

SNIP

'ubiquiti_edgeswitch': {'cmd': 'show version', 'search_patterns': ['EdgeSwitch'], 'priority': 99, 'dispatch': '_autodetect_std'}}

>>> netmiko.ssh_autodetect.SSH_MAPPER_BASE = {"something": "anotherthing", "morestuff": "morethings"}
>>> netmiko.ssh_autodetect.SSH_MAPPER_BASE
{'something': 'anotherthing', 'morestuff': 'morethings'}
```

Don't see why not. Obviously the above is a silly example, but you could pop out all the platforms you don't care about before running your script. Going to close as I don't think this is really a bug/enhancement. 

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc if you've got more questions/comments!
