### ISSUE TITLE
Logging into a device with no username or no username and password

### ISSUE THREAD

**Issue by htulshan** [ktbyers/netmiko#1427]
I am trying a couple of combination with netmiko to connect to a cisco ios device.

I am not able to login into a device if it only asks for a password and no username,
Also unable to login into the device if there is no username and password configured.

Is it possible using netmiko?

**Comment by ktbyers** [comment]
What is your context? Telnet? Terminal server?



Kirk

**Comment by htulshan** [comment]
Sorry my bad, just realized that SSH will require a username, if no username is required from login you will not be able to login at all using ssh.
Also tested with telnet and it works as expected for ssh.

Thank you for the quick response though.
