### ISSUE TITLE
Slack invite invalid

### ISSUE THREAD

**Issue by jg555** [ktbyers/netmiko#1432]
Slack says a new invitation is needed. I have a few questions, I could use slack to ask them.

**Comment by ktbyers** [comment]
@carlmontanari You want to update the Slack invite on Netmiko the web page i.e. do a PR there?

**Comment by carlmontanari** [comment]
Opened #1433 -- Going to close, but @jg555 please let us know if that link is wonky since thats the one I used in the updated PR too :)
