### ISSUE TITLE
reuse/clone one jumphost connection for multiple connections

### ISSUE THREAD

**Issue by mims1979** [ktbyers/netmiko#1435]
Hi,

I'm in a situation where I have to access a jumphost first.  That jumphost requires a one time use password when initially connecting.  From there I issue SSH command to access my other hosts.  While I can connect, redispatch, disconnect, redispatch, connect to next host, redispatch.  All of that is done serially.  Is there a way to establish a connection to the jumphost (so I only have to enter the pin once) then clone that session and concurrently connect to multiple other hosts at the same time using that first jumphost connection?  This way I can connect and process multiple hosts at the same time.  I have it working now with direct SSH (through threading), but now that I have to use a jumphost it would require me to enter a one time pin for each connection to a new device.

**Comment by carlmontanari** [comment]
Sounds really not pleasant :) 

Short answer is I think "no". Or at least how you're describing I don't think. I would look at just executing the script *from* the jumphost instead as this sounds highly problematic and likely to be more complicated than its worth.

**Comment by ktbyers** [comment]
Short of installing code on the jumphost--I don't really see how you would make this work.

The main options I can see are:
1. Initiate multiple connection from your remote host (threads or multiple processes) and handle the one-time password multiple times.
2. Install code on the jump host and initiate connections from there.

I guess maybe you could try some sort an SSH-tunnel at the system level and have that handle the one-time password...that would be outside of netmiko, however. In other words, have a lower level system operation that hides the one-time-password from Netmiko. And then have Netmiko spawn multiple threads/processes and just use that SSH-tunnel.

You are definitely in the realm of hard problems, however.

**Comment by jtdub** [comment]
Does the jump host allow you to set up SSH keys, which would allow you to execute without the need for using a single user password? I use this method frequently.

**Comment by ktbyers** [comment]
Yes, that would be good and much easier...i.e. if you can eliminate the need for one-time password (while still having reasonably good security). 

Security people won't like this, but some of the obstacles they are putting up to automation are probably making security worse in the long-run.

**Comment by mims1979** [comment]
No, use of keys isnt permitted, and the jumpservers are only to be used as a jump server, adding scripts is forbidden.  I do know that the jumpservers only requires one auth, as long as a connection is present, it's possible to just clone a session as I do it in securecrt when connected.  I also use a client locally that connects and I can use it as a socks proxy for any additional connections needed throughout the day.  However, I'm not running the scripts locally, but on a remote server.  

I was hoping there was some way of cloning sessions the same or opening another channel once the connection is authenticated as I'm able to do locally.

**Comment by ktbyers** [comment]
Yep, definitely could be possible...and I know there are ways you can create new SSH channels from an existing SSH connection. Though for compatibility reasons to legacy devices (Cisco IOS)--there is a reasonable chance that won't work with Netmiko.

On quick glance it doesn't look like Paramiko supports a Socks Proxy.

I think you would probably need to look at some SSH-tunneling solution that hide all of this from Netmiko (if you wanted to use Netmiko to accomplish this). Or you would probably need to hack around a lot with Paramiko/Netmiko to see if you can come up with a workable solution.

**Comment by AsharLohmar** [comment]
Have you tried using the `ControlMaster` feature of ssh ?
I have something like this in my `~/.ssh/config` 
```
Host *
    ControlMaster auto 
    ControlPath  ~/.ssh/sockets/%r@%h-%p
    ControlPersist 18000
```
This way, after I make a connection to some host, as long as that `socket-files` is valid, the new connections are multiplexed/they piggyback that same connection/socket and no password is required.
The `ControlPersist` feature keeps the connection alive for that amount of time even after the last "session" is closed.
You could find some other neat tricks (and a better explanation) [here](https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing).

Another way around this that comes to mind would be to initiate a first connection to the jumphost with `DynamicForward`/ `-D`  that you launch in background, and then make the other hosts to `ProxyCommand` through that using `nc`.

Assuming:
```
Host *
    ControlMaster auto
    ControlPath  ~/.ssh/sockets/%r@%h-%p
    ControlPersist 18000
Host jumphost
    User <user>
    Hostname <host>
    DynamicForward 127.0.0.1:2226
Host <something> <something>
    ProxyCommand nc -F -x 127.0.0.1:2226 %h %p
```
so you'd have to first `ssh jumphost -qfN` to initiate the "tunnel/proxy" and send it to background, then you'll be able to connect to the `<something>` nodes.

**Comment by ktbyers** [comment]
Note, Paramiko and Netmiko should now support a Socks Proxy (this has changed since my earlier comment in 2019).


Regards, Kirk
