### ISSUE TITLE
netmiko fails w/ Cisco SG200 line

### ISSUE THREAD

**Issue by Rooster-OC** [ktbyers/netmiko#1440]
Have many SG200 line switches in network and SSH requires username entry twice (bug Cisco is not planning to fix).  Is there a way to edit the library or a code snippet to work around this to leverage netmiko for admin tasks?

**Comment by carlmontanari** [comment]
ssh does not prompt for username (it uses user on shell or whatever is passed before `@` or w/ `-l` flag), so I assume this is happening "after" the ssh session is "setup" basically?

I assume you are using the sg300 device type? If so you should be able to modify that to have a `special_login_handler` that operates similar to the WLC one as I think the WLC does this same thing (weird double credentials prompt thing). 

[Here](https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_wlc_ssh.py#L12) is the WLC special login handler.

[Here](https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L914) is where  the special login handler is getting called in the normal establish connection process.

**Comment by ktbyers** [comment]
There is a way on the SG200 to disable that double prompting behavior. 

I think it is this command:

```
ip ssh password-auth
```

You should configure that or you will need to do the special login handling that @carlmontanari mentioned which can get hard.

**Comment by Rooster-OC** [comment]
Carl,

Thanks for getting back to me.  Yes, after SSH is established, and with the sg300 device type configured.  I’ll give the WLC handler a try or the other option.  Would be great if this did the trick.  The SG line is very cost effective for access layer, but occasionally frustrates us like this.

I’ll let you know how this works.

Thx,
Greg

Gregory Powlin
Manager of Information Technology
County of Oswego
Public Safety Center
39 Churchill Road
Oswego, NY 13126
(315) 349-3525
greg.powlin@oswegocounty.com<mailto:greg.powlin@oswegocounty.com>

**Comment by Rooster-OC** [comment]
Reading emails staring with oldest.  Will try this first.  Thx, Greg

Gregory Powlin
Manager of Information Technology
County of Oswego
Public Safety Center
39 Churchill Road
Oswego, NY 13126
(315) 349-3525
greg.powlin@oswegocounty.com<mailto:greg.powlin@oswegocounty.com>

**Comment by carlmontanari** [comment]
Going to close this out, feel free to reopen if you're still having any issues.

Also, feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.
