### ISSUE TITLE
remote connectivity

### ISSUE THREAD

**Issue by sinxuang** [ktbyers/netmiko#1443]
I am able to launch the appium  through this command but still it gives me error.

from netmiko import ConnectHandler
def server():
    cisco_260 = {'device_type': "linux", 'ip': '192.x.x.x', 'username': "x", 'password': "x"}
    net_connect = ConnectHandler(**cisco_260)
    output = net_connect.send_command("appium --address 192.x.x.x --port 4723")
    return output
server()

Errors are
output = net_connect.send_command("appium --address 192.x.x.x --port 4723")
  File "", line 1337, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: user\@user\-HP\-Compaq\-Elite\-8300\-SFF\:

**Comment by carlmontanari** [comment]
Please read the readme and getting started guide ([here](https://pynet.twb-tech.com/blog/automation/netmiko.html)). It appears you are connecting to an HP device using linux as the device type. I'm not sure what appium is, but a quick google shows mobile app testing, so not really sure what you've got going on there?

Going to close this. If you want to reopen please provide more detail as to what is actually going on/what you are trying to do and format the issue so it is easier to read.
