### ISSUE TITLE
EOFERROR when ssh into Cisco_XR

### ISSUE THREAD

**Issue by wakelia2** [ktbyers/netmiko#1445]
Trying to send config to router using Behave. 
Having problems with the ConnectHandler, getting EOFERROR() when it tries to log into the device.
The command i am trying to send to a cisco_xr device is 'save configuration harddisk:<name>'.

```
def send_config(self, router_configuration):
        ssh_connection = ConnectHandler(
            ip=self.host,
            port=22,
            username=self.username,
            password=self.password,
            timeout=self.timeout,
            global_delay_factor=20,
            banner_timeout=self.banner_timeout,
            device_type=self._convert_type(self.device_params['name'])
            )
        ssh_connection.send_config_set(router_configuration, exit_config_mode=False, config_mode_command='configure exclusive')
        ssh_connection.commit()
        ssh_connection.disconnect()
```

Error message:

```
(automated_testing) [server]$ behave -vvv
Using default path "./features"
Trying base directory: /home/wakelia2/automated_testing/automated_testing/features
HOOK-ERROR in before_feature: EOFError:
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/behave/runner.py", line 545, in run_hook
    self.hooks[name](context, *args)
  File "features/environment.py", line 46, in before_feature
    context.connect_handler.send_config(context.backup_command)
  File "/home/wakelia2/automated_testing/automated_testing/classes/router.py", line 119, in send_config
    device_type=self._convert_type(self.device_params['name'])
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/netmiko/base_connection.py", line 322, in _open
    self.establish_connection()
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/netmiko/base_connection.py", line 884, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/paramiko/transport.py", line 2034, in run
    self.packetizer.write_all(b(self.local_version + "\r\n"))
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/paramiko/packet.py", line 367, in write_all
    raise EOFError()
```

**Comment by carlmontanari** [comment]
Stacktrace looks like it never completely establishes connection, so I think the command you are trying to send probably doesn't matter much at this point.

Are you able to get a connection established with just netmiko (meaning not "wrapped" with behave)? Looking briefly at the paramiko source it looks like this EOF gets raised if the session is never "alive" - so seems like the socket is up but no connection can be established. I would expect cipher mismatch stuff, creds an auth exception, etc., so I'm not sure what the EOF really means here.

In any case, get rid of the behave bits to start, and try to get a connection open w/out it. I'm guessing you'll run into the same error at that point. Also maybe worth just manually ssh'ing to the device with `-v` so you can see the key exchange bits and all that to make sure it all seems reasonable (i.e. something paramiko would automagically support).

**Comment by wakelia2** [comment]
Thanks for the reply.
I can establish a connection with netmiko out of the python terminal: 
```
>>> from netmiko import ConnectHandler
>>> ch = ConnectHandler(ip='address', port=22, username='', password='', timeout=90, device_type='cisco_xr')
>>> output = ch.send_command('show int description')
>>> output
'\nTue Nov  5 09:16:23.475 UTC\n\nInterface          Status      Protocol    Description\n--
```
when i manually ssh to the device with -v:
```
[wakelia2@server ~]$ ssh -v username@ipaddress
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: Connecting to router [router] port 22.
debug1: Connection established.
```
Everything looks good to me in using the -v, and the exchange keys are known in the hosts file.
Any idea on where to look next?

**Comment by carlmontanari** [comment]
I think at this point probably need to snag logging to see whats up... and hope we are getting far enough along to actually see something. If we don't see anything then it seems that something with behave/paramiko is going weird maybe -- not sure why/what/how that would be but clearly paramiko/netmiko works without behave so that would be my guess at that point.

In any case, [here](https://github.com/ktbyers/netmiko/blob/develop/examples/use_cases/case11_logging/conn_with_logging.py) is a quick example to setup logging. Will be curious what the result of that is...

**Comment by wakelia2** [comment]
Thanks, I already have a logger running for the program, unfortunately it is not capturing any output from this!
```
def get_logger(level=logging.DEBUG):
    logging.basicConfig(format='%(asctime)s-%(levelname)s: %(message)s', datefmt='%d-%m-%y %H:%M:%S')
    logger = logging.getLogger('program_name')
    logger.setLevel(level)
    return logger
```
The logger is just capturing print commands from other functions in the application, nothing concerning the netmiko output:
```
Device type is Junos.
Router name is router.
Starting Feature: bgp (router)
### Connecting to Router: router, address ###
Starting Scenario: 
### Router type is: cisco_xr ###
Ending Scenario: stuff
Starting Scenario: stuff
### Router type is: cisco_xr ###
Ending Scenario: stuff
Ending Feature: bgp (router)
```
Note that this error is happening on both Junos and cisco_xr

**Comment by carlmontanari** [comment]
I've got no idea why it doesn't work and really no idea why the logs down't show up! If it works without behave then I would say this isn't really a netmiko issue though, so I believe I am of no help at this point... :)

**Comment by wakelia2** [comment]
So i am seeing this EOF error for two different things i am trying with my project. But just playing with netmiko on the Python interpreter:
```
(automated_testing) [wakelia2@server automated_testing]$ python
Python 3.6.6 (default, Jan 26 2019, 16:53:05)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from netmiko import ConnectHandler
>>>
>>>
>>> ch = ConnectHandler(device_type="cisco_xr", ip="ip", username="", password="")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/netmiko/base_connection.py", line 322, in _open
    self.establish_connection()
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/netmiko/base_connection.py", line 884, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/paramiko/transport.py", line 2034, in run
    self.packetizer.write_all(b(self.local_version + "\r\n"))
  File "/home/wakelia2/automated_testing/lib64/python3.6/site-packages/paramiko/packet.py", line 367, in write_all
    raise EOFError()
EOFError
>>> ch = ConnectHandler(device_type="cisco_xr", ip="ip", username="", password="")
>>> 
```
Seems weird its temperamental, I was previously logged into the router with Connect Handler. Could this issue be that i am not disconnecting properly and therefore the next time i try to ssh in it causes this EOF Error?

**Comment by wakelia2** [comment]
I think the problem lies with the way i am trying to save a backup configuration file with netmiko, in the before_feature of a behave file. 

(function to create backup command for iosxr)

```
def create_backup(device_type):
    if device_type in ['Cisco_XR', 'cisco_xr', 'iosxr']:
        cisco_backup_command = 'copy running-config harddisk:nightcap_backup_{}.txt'.format(timestr)
        return cisco_backup_command
```

(before feature in the behave test)
```

def before_feature(context, feature):
    router_details = get_router_details(router_name)
    context.device_type = router_details['device_type']
    context.connect_handler = Router(context.device_ip, router_details['device_type'], router_details['code_version'])
    context.backup_command = create_backup(context.device_type)
    context.backup_config = context.connect_handler.send_command(context.backup_command)

```
Does the way i am sending the backup_command look correct? as this is what i think is causing the error.

**Comment by carlmontanari** [comment]
If sending the command that way works, then yes it looks right :) but yes, it does seems reasonable to me. What makes you think the backup is the issue? If the backup was taking forever or something like that then we would be seeing different exceptions most likely (not EOF). If you have tied up all your VTY lines then yeah EOF seems like its a possible result. You'd have to check that out. Netmiko/Paramiko will close/tear down the socket but if you hit an exception it probably isn't "gracefully" exiting from the device. In my experience when exceptions like that happen the devices (cisco/arista/whatever) usually close those VTY lines though, but worth checking out for sure.

**Comment by wakelia2** [comment]
I certainly think the command is correct as it works when i do it on the router CLI. However when i comment the two lines out:
```
context.backup_command = create_backup(context.device_type)
context.backup_config = context.connect_handler.send_command(context.backup_command)
```
The rest of my behave test case works. No EOF errors.

**Comment by wakelia2** [comment]
Another thought... If i have a Router class, with both of the following functions inside, would calling both functions separately  in a behave scenario cause the VTY errors you mentioned? Potentially opening two ConnectHandlers to the same device?

```
def send_config(self, router_configuration):
        ssh_connection = ConnectHandler(
            ip=self.host,
            port=22,
            username=self.username,
            password=self.password,
            timeout=self.timeout,
            global_delay_factor=4,
            blocking_timeout=16,
            banner_timeout=10,
            device_type=self._convert_type(self.device_params['name'])
            )
        self.logger.info("\n### Configuration sent to device: ### \n")
        self.logger.info(router_configuration)
        ssh_connection.send_config_set(router_configuration, exit_config_mode=False, config_mode_command='configure exclusive')
        self.logger.info(ssh_connection.commit())
        self.logger.info("\n### Commited configuration: ###\n")
        ssh_connection.disconnect()
        self.logger.info("\n### Disconnected from device ###\n")
 
    def send_command(self, router_configuration):
        ssh_connection = ConnectHandler(
            ip=self.host,
            port=22,
            username=self.username,
            password=self.password,
            timeout = self.timeout,
            global_delay_factor=4,
            blocking_timout=16,
            banner_timeout=10,
            device_type=self._convert_type(self.device_params['name'])
            )
        ssh_connection.send_command(router_configuration, expect_string="Destination file name")
        ssh_connection.send_command('\n',expect_string='#', delay_factor=2)
        self.logger.info("\n### Command sent to device: ### \n")
        self.logger.info(router_configuration)
        ssh_connection.disconnect()
        self.logger.info("\n### Disconnected from device ###\n")
```
Context for why i have both functions is because i would like to do all of my scenarios in Configure exclusive hence the first function, but for the copy running-config command i need to be in configure and not configure exclusive or cisco_xr locks the namespace and does not allow you to save the config.

**Comment by carlmontanari** [comment]
Was just chatting with @ktbyers about this. It sounds like pretty near to 100% of the time the EOF (raised by paramiko) during session establishment (in netmiko) is when the device or a firewall (or something in the middle) kills the connection for whatever reason. Obviously finding that reason is easier said than done, however at this point I think its nearly certain this isn't a netmiko issue so I'm going to go ahead and close this. If you do find out whats going on, please let us know!
