### ISSUE TITLE
Netmiko | Error: Telnet login failed:

### ISSUE THREAD

**Issue by sulaiman410** [ktbyers/netmiko#1446]
Excuse my indentation, I have this script because my devices have different login credentials- 

This script works fine, except when it gets to telnet section, it unable to login to devices, I this on multiple devices but it gives this error  Error: Telnet login failed:  _[ipaddress]_

```
import netmiko
from netmiko import ConnectHandler
from operator import itemgetter
from time import sleep
        try:
            net_connect = ConnectHandler(device_type='cisco_ios_ssh', ip=ip, username=username1, password=password1, secret=password1)
            connection_protocol = 'ssh'
        except:
                        try:
                                net_connect = ConnectHandler(device_type='cisco_ios_ssh', ip=ip, username=username2, password=password2, secret=password2)
                                connection_protocol = 'ssh'
                        except:

                                try:
                                        net_connect =  ConnectHandler(device_type='cisco_ios_telnet', ip=ip, username=username1, password=password1, port=23, verbose=False)
                                        connection_protocol = 'telnet'

                                except Exception as e:
                                        print "Error: " + str(e)
```

**Comment by carlmontanari** [comment]
Can you remove all of the nesting and just try to connect to that failing device "normally" then post the stack trace please.

**Comment by sulaiman410** [comment]
```
#!/usr/bin/python
import netmiko
import csv, getpass, operator, os, re, sys, telnetlib
from datetime import datetime, timedelta
from natsort import natsorted, ns
from netmiko import ConnectHandler
from operator import itemgetter
from time import sleep

net_connect =  ConnectHandler(device_type='cisco_ios_telnet', ip='100.x.x.x', username=username1, password=password1, port=23, verbose=False)
connection_protocol = 'telnet'
print ip+ "=== Telnet Successful"
net_connect.disconnect()

```
**Error**

Traceback (most recent call last):
  File "./del.py", line 15, in <module>
    net_connect =  ConnectHandler(device_type='cisco_ios_telnet', ip='100.x.x.x', username=username1, password=password1, port=23, verbose=False)
  File "/usr/lib/python2.7/site-packages/netmiko-2.0.1-py2.7.egg/netmiko/ssh_dispatcher.py", line 168, in ConnectHandler
  File "/usr/lib/python2.7/site-packages/netmiko-2.0.1-py2.7.egg/netmiko/base_connection.py", line 160, in __init__
  File "/usr/lib/python2.7/site-packages/netmiko-2.0.1-py2.7.egg/netmiko/base_connection.py", line 640, in establish_connection
  File "/usr/lib/python2.7/site-packages/netmiko-2.0.1-py2.7.egg/netmiko/cisco_base_connection.py", line 139, in telnet_login
netmiko.ssh_exception.NetMikoAuthenticationException: Telnet login failed: 100.x.x.x


I can login directly with telnet using same credentials-

**Comment by carlmontanari** [comment]
What version of netmiko do you have installed? Looking at current code base it looks like you're at least a few versions back. I dont know of any specific fixes that may have occurred, but it likely couldn't hurt to upgrade (but do note that we no longer support python 2.7 on the current develop branch). Otherwise, I would point you back to the exception that is saying authentication error and tell you to double and triple check ip/password/user for case/spelling/whitespace/etc.

**Comment by sulaiman410** [comment]
```
Name: netmiko
Version: 2.4.2
Summary: Multi-vendor library to simplify Paramiko SSH connections to network devices
Home-page: https://github.com/ktbyers/netmiko
Author: Kirk Byers
Author-email: ktbyers@twb-tech.com
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: scp, textfsm, setuptools, pyserial, paramiko
Required-by: 
```

so I know my username is password is correct, because I have used the same script for ssh and it works fine, and I have tried for other box as well, which require telnet, but it fails to authenticate. I can try similar code with py3.

**Comment by sulaiman410** [comment]
With python3 I am stuck here

```
    from netmiko import ConnectHandler
ModuleNotFoundError: No module named 'netmiko'
```

**Comment by ktbyers** [comment]
@sulaiman410 You probably need to enable the Netmiko session_log and see why the telnet login is failing. Basically, it is failing the process of username/password login using telnet (for some reason).

**Comment by sulaiman410** [comment]
Can you help me how to enable logging? 
I simplified the code to the point, it still gives the same error, this time I am trying on cisco iosXR device, which works fine with same credentials

```
#!/usr/bin/python
from netmiko import ConnectHandler

my_device = { 
    "device_type" : "cisco_ios_telnet", 
    "ip": "100.x.x.x",
    "username": "username",
    "password": "pass",
    "port": 23, 
}
net_connect = ConnectHandler(**my_device)
output = net_connect.send_command("show run")
print(output)
```

```
Traceback (most recent call last):
  File "./del.py", line 19, in <module>
    net_connect = ConnectHandler(**my_device)
  File "/usr/lib/python2.7/site-packages/netmiko-2.0.1-py2.7.egg/netmiko/ssh_dispatcher.py", line 168, in ConnectHandler
  File "/usr/lib/python2.7/site-packages/netmiko-2.0.1-py2.7.egg/netmiko/base_connection.py", line 160, in __init__
  File "/usr/lib/python2.7/site-packages/netmiko-2.0.1-py2.7.egg/netmiko/base_connection.py", line 640, in establish_connection
  File "/usr/lib/python2.7/site-packages/netmiko-2.0.1-py2.7.egg/netmiko/cisco_base_connection.py", line 139, in telnet_login
netmiko.ssh_exception.NetMikoAuthenticationException: Telnet login failed: 100.x.x.x
```

**Comment by carlmontanari** [comment]
You can set a "session_log" parameter in the connect handler (my_device dict you have in the snippets). Value is string path for file to write out.

**Comment by sulaiman410** [comment]
Just captured the log, seems like script does not press enter once it enters the username? because I never see a password prompt here 

```
$ cat my_output.txt 
Username:
Username:

Username:
Username:

Username:
Username:
```

**Comment by ktbyers** [comment]
It looks like you are using an old version of Netmiko:

`lib/python2.7/site-packages/netmiko-2.0.1-py2.7.egg/netmiko/ssh_dispatcher.py", line 168, in ConnectHandler`

You need to upgrade to Netmiko 2.4.2 or the develop branch.

Let us know if you are still seeing the same issue after upgrading.

**Comment by sulaiman410** [comment]
I am sorry, that was from when I was running 2.7, with python 3 I get the following

```
Traceback (most recent call last):
  File "./del.py", line 20, in <module>
    net_connect = ConnectHandler(**my_device)
  File "/usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 317, in __init__
    self._open()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 322, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 874, in establish_connection
    self.telnet_login()
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 171, in telnet_login
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Login failed: 100.x.x.x
```

**Comment by carlmontanari** [comment]
It (netmiko) is probably sending returns otherwise you would probably just be one `username:` prompt and then a timeout I would think. But if you think it is not sending a return you can set the `default_enter` arg to something other than the default telnet default of `\r\n`.

**Comment by ktbyers** [comment]
@sulaiman410 You probably would have to look at it in the Python debugger.

Here is the code where it should see your "Username" pattern and send the username. After that it should detect the password prompt and send the password.

You are not going through a terminal server or anything odd--correct? Just straight telnet to the device?

Error basically says the remote router closed the connection (the EOFError), but a bit odd that Netmiko didn't send the username as it should have detected the Username pattern you showed above.

Note, you didn't re-post the session_log so the only session_log I have is the one from the old Netmiko so I am assuming the behavior is the same.

**Comment by sulaiman410** [comment]
@ktbyers reading your post seems like were you about to share some code to try? There is no terminal servers, it is straight from my jumpbox to device itself, and sd I said I can telnet fine directly from my terminal. and yes the session log was above was with python3 and netmiko 2.4.2

@carlmontanari  would you help me in adding that return? where will that go in my script and what command?

Thanks

Sal

**Comment by ktbyers** [comment]
Nope, you need to go into Pdb and see what is going on. 

I meant to link to this in the earlier post.

https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco_base_connection.py#L93

The code I just linked to is not consistent with what you posted in the session_log so you will have to investigate it (using Pdb). 

Here is an article on Pdb for reference:

https://pynet.twb-tech.com/blog/python/pdb.html

My read of the code is we should have sent the username in response to "Username" string...so you'll have to figure out why that is not happening.

**Comment by sulaiman410** [comment]
So this is the debug log,

not sure if it helps, and gives a different picture?

```
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: Username:

DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: Username:


DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: Username:

DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: Username:


DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: Username:

DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: Username:


DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
% Authentication failed
```

**Comment by ktbyers** [comment]
You could try setting `global_delay_factor: 2` (or 4) and see if it makes any difference. This is an argument to ConnectHandler

You would probably need to go into Pdb at about this location:

https://github.com/ktbyers/netmiko/blob/v2.4.2/netmiko/cisco_base_connection.py#L102

I am not seeing on the face of it why Netmiko is not sending the `Username` (except possibly your device is really slow and hence the global delay factor recommendation).

**Comment by carlmontanari** [comment]
Going to close this out. If this is still an issue and there is any new information to share feel free to reopen.

**Comment by shrutikaponde** [comment]
Thanks!! Adding `global_delay_factor` solved my connection failed issue with napalm.
  
> You could try setting `global_delay_factor: 2` (or 4) and see if it makes any difference. This is an argument to ConnectHandler
> 
> You would probably need to go into Pdb at about this location:
> 
> https://github.com/ktbyers/netmiko/blob/v2.4.2/netmiko/cisco_base_connection.py#L102
> 
> I am not seeing on the face of it why Netmiko is not sending the `Username` (except possibly your device is really slow and hence the global delay factor recommendation).

This is my code snippet:
```
  from napalm import get_network_driver
  from pprint import pprint
  
  driver = get_network_driver('ios')
  conn_method = {'port': 5036, 'transport': 'telnet', 'global_delay_factor': 2, 'secret': 'nornir'}
  host = '127.0.0.1'
  user = 'nornir'
  passwd = 'nornir'
  
  # With context manager
  with driver(hostname=host, username=user, password=passwd, optional_args=conn_method ) as device:
      print('Getting facts')
      pprint(device.get_facts())
```
