### ISSUE TITLE
send_command output not consistent

### ISSUE THREAD

**Issue by saber-t00th** [ktbyers/netmiko#1449]
I just started with netmiko. 
I am connected to a CentOS 6 Linux machine and doing a simle "ll" command for long listing. But the output is not consistent. Many times, I do not get the correct information. 

============================================
Here is the output from my ipython console:

ssh.send_command("ll").split('\n')
Out[95]: 
['total 28',
 '-rw-rw-r--. 1 sabert00th sabert00th  1248 May  7  2019 cloudIPs6',
 '-rw-rw-r--. 1 sabert00th sabert00th   917 Oct 15 14:36 curltest',
 '-rw-rw-r--. 1 sabert00th sabert00th 10093 Sep  6 14:41 list',
 '-rwxrwxr-x. 1 sabert00th sabert00th   353 Sep 23 08:34 program.py',
 '-rwxrwxr-x. 1 sabert00th sabert00th  1511 Nov  5 16:02 test.py']

ssh.send_command("ll").split('\n')

Out[96]: ['abert00th@jumphost ~]$ ']

ssh.send_command("ll").split('\n')
Out[97]: 
['abert00th@jumphost ~]$ ',
 '[sabert00th@jumphost ~]$ ',
 '[sabert00th@jumphost ~]$ ']

ssh.send_command("ll").split('\n')
Out[98]: ['abert00th@jumphost ~]$ ', '[sabert00th@jumphost ~]$ ']

ssh.send_command("ll").split('\n')
Out[99]: ['abert00th@jumphost ~]$ ', '[sabert00th@jumphost ~]$ ']

ssh.send_command("ll").split('\n')
Out[100]: ['abert00th@jumphost ~]$ ', '[sabert00th@jumphost ~]$ ']

ssh.send_command("ll").split('\n')
Out[101]: 
['abert00th@jumphost ~]$ ',
 '[sabert00th@jumphost ~]$ ',
 '[sabert00th@jumphost ~]$ ']

ssh.send_command("ll").split('\n')
Out[102]: ['abert00th@jumphost ~]$ ', '[sabert00th@jumphost ~]$ ']

ssh.send_command("ll").split('\n')
Out[103]: 
['total 28',
 '-rw-rw-r--. 1 sabert00th sabert00th  1248 May  7  2019 cloudIPs6',
 '-rw-rw-r--. 1 sabert00th sabert00th   917 Oct 15 14:36 curltest',
 '-rw-rw-r--. 1 sabert00th sabert00th 10093 Sep  6 14:41 list',
 '-rwxrwxr-x. 1 sabert00th sabert00th   353 Sep 23 08:34 program.py',
 '-rwxrwxr-x. 1 sabert00th sabert00th  1511 Nov  5 16:02 test.py']

**Comment by carlmontanari** [comment]
We love netmiko (obviously) but if you are just trying to connect to a linux host and do "normal" linux things there are probably better options (ansible being the big one). 

With that out of the way... please format your posts, its tough to read w/out the formatting. What version of netmiko are you using, what does your code look like, what is the expected output.

**Comment by saber-t00th** [comment]
Hi Carl
The intention is to run multiple commands on multiple SRX devices via this linux jumphost. I want to make sure that when I loop over a list of SRX firewalls with a bunch of commands I am able to gather the entire output and it is not lost somewhere like it happened with the 'normal' long listing output.
Please excuse my formatting skills. I am sure I'll learn this 'markdown' soon enough as well. 

```
netmiko.__version__ is 2.4.2
```
I am running this from the ipython shell:

```
ssh = netmiko.ConnectHandler(**jumphost)
ssh.send_command("ll")
ssh.send_command("ll").split('\n')
```
The expected output is this
```
['total 28',
'-rw-rw-r--. 1 sabert00th sabert00th 1248 May 7 2019 cloudIPs6',
'-rw-rw-r--. 1 sabert00th sabert00th 917 Oct 15 14:36 curltest',
'-rw-rw-r--. 1 sabert00th sabert00th 10093 Sep 6 14:41 list',
'-rwxrwxr-x. 1 sabert00th sabert00th 353 Sep 23 08:34 program.py',
'-rwxrwxr-x. 1 sabert00th sabert00th 1511 Nov 5 16:02 test.py']
```
While I get just prompts most of the times.
```
ssh.send_command("ll").split('\n')
Out[99]: ['abert00th@jumphost ~]$ ', '[sabert00th@jumphost ~]$ ']

ssh.send_command("ll").split('\n')
Out[100]: ['abert00th@jumphost ~]$ ', '[sabert00th@jumphost ~]$ ']

ssh.send_command("ll").split('\n')
Out[101]:
['abert00th@jumphost ~]$ ',
'[sabert00th@jumphost ~]$ ',
'[sabert00th@jumphost ~]$ ']
```

Thanks

**Comment by carlmontanari** [comment]
Gotcha. Ok coolio, then I would recommend you just use the jumphost as an SSH proxy. Check out [this](https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html) article. I imagine the SRX prompt handling is likely more reliable/better than the linux device type since we obviously focus more on the network devices. I would also recommend upgrading to the latest development branch if ya can -- been some pretty good improvements on error handling/inputs that may be helpful. 

Will the proxy jump work for ya you think?

**Comment by carlmontanari** [comment]
Going to close this -- feel free to reopen if there is a bug/issue with ssh proxy stuff!
