### ISSUE TITLE
Netmiko unable to import

### ISSUE THREAD

**Issue by CDWAdamMason** [ktbyers/netmiko#1451]
I have searched my entire computer for any files pertaining to netmiko, and I can't find any that would cause any kind of name referencing issues. 

![image](https://user-images.githubusercontent.com/39139135/68508619-d69b0b80-023c-11ea-9840-8ad29234986b.png)

yet here it is declared
![image](https://user-images.githubusercontent.com/39139135/68508729-1bbf3d80-023d-11ea-9733-b720c24e5d46.png)

![image](https://user-images.githubusercontent.com/39139135/68508719-1235d580-023d-11ea-809e-b94f5884d553.png)

also side issue, I tried using the updated tutorial where it claims to do "from netmiko import netmiko" and it indicate that there is no method named netmiko inside of the library netmiko.

**Comment by ktbyers** [comment]
Needs to be:

```
from netmiko import Netmiko

net_connect = Netmiko(arguments)
```

**Comment by CDWAdamMason** [comment]
fixed.... I feel dumb, sorry.

**Comment by ktbyers** [comment]
No worries.
