### ISSUE TITLE
Cisco IOS-XE-Lite does not accept "ter len 0" in user exec mode

### ISSUE THREAD

**Issue by icovada** [ktbyers/netmiko#1454]
Cisco IOS-XE Lite version 16.10 and above doe not accept "terminal length 0" in user EXEC mode breaking netmiko.

Here is an output of a serial session:  

```
Switch>
Switch>
Switch>terminal length 0
Switch>terminal width 511
Switch>enable
Switch#cisco
Bad IP address or host name% Unknown command or computer name, or unable to find computer address
Switch#
Switch#
Switch#show run | section username
Switch#
Switch#show version
Cisco IOS XE Software, Version 16.09.03
Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT9K_LITE_IOSXE), Version 16.9.3, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2019 by Cisco Systems, Inc.
Compiled Wed 20-Mar-19 07:19 by mcpre


Cisco IOS-XE software, Copyright (c) 2005-2019 by Cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.  For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.


ROM: IOS-XE ROMMON
BOOTLDR: System Bootstrap, Version 16.10.1r [FC5], RELEASE SOFTWARE (P) 

Switch uptime is 2 hours, 13 minutes
 --More--
```

Adding "ter len 0" in privileged EXEC mode ("enable mode") works

**Comment by ktbyers** [comment]
That somewhat looks like a cisco bug...i.e. if the command is invalid, it should have failed with `%invalid command`.

Is the output paging actually disabled at privilege1 i.e. if you execute `show version` at privilege 1 do you still get `--More--`.

Probably the easy fix is to disable paging as part of the `enable()` invocation.

**Comment by icovada** [comment]
I have added a very crude `send_command("ter len 0\n")` after getting in privileged exec mode and it works

And yes I do still get `--More--` in priv 1

I should check this issue on the upgraded versions as soon as I get to plug them online

**Comment by carlmontanari** [comment]
Sounds like things are sorted so I'll go ahead and close! I think worst case is the priv1 just never has permission to do that, but I think it is probably reasonable to assume that the user that Netmiko uses should have at least some amount of priv level, so I guess my feel would be to keep things as is? But maybe in the future we could add that to enable method if it becomes an issue.

**Comment by ktbyers** [comment]
It looks like a Cisco bug...so let's see if other people run into this issue and how broad of a problem it is.

If other people run into this, please chime in on this issue.
