### ISSUE TITLE
Netmiko 2.4.2 failing for TextFSM

### ISSUE THREAD

**Issue by pkeyser** [ktbyers/netmiko#1457]
One of our servers was patched recently I am guessing and it appears to have broken Netmiko. We are running version 2.4.2 of Netmiko and 1.1.0 for TextFSM. Everything I can find says this issue was fixed in 2.4.1 but that doesn't seem to be the case here. The server is running RHEL 7.7.

```
Traceback (most recent call last):
  File "/usr/bin/netmiko-show", line 18, in <module>
    from netmiko import ConnectHandler
  File "/usr/lib/python2.7/site-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/lib/python2.7/site-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/lib/python2.7/site-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 32, in <module>
    from netmiko.utilities import (
  File "/usr/lib/python2.7/site-packages/netmiko/utilities.py", line 11, in <module>
    from netmiko._textfsm import _clitable as clitable
  File "/usr/lib/python2.7/site-packages/netmiko/_textfsm/__init__.py", line 3, in <module>
    from netmiko._textfsm import _clitable
  File "/usr/lib/python2.7/site-packages/netmiko/_textfsm/_clitable.py", line 40, in <module>
    import copyable_regex_object
ImportError: No module named copyable_regex_object
```

**Comment by ktbyers** [comment]
What do you see if you do the following:

```
>>> import textfsm
>>> textfsm.__version__
'1.1.0'
>>> from textfsm import copyable_regex_object
```

**Comment by ktbyers** [comment]
Netmiko 2.4.2 should try both patterns (both the old and the new pattern).

https://github.com/ktbyers/netmiko/blob/master/netmiko/_textfsm/_clitable.py#L35-L40

**Comment by pkeyser** [comment]
> What do you see if you do the following:
> 
> ```
> >>> import textfsm
> >>> textfsm.__version__
> '1.1.0'
> >>> from textfsm import copyable_regex_object
> ```

>>> import textfsm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/textfsm/__init__.py", line 11, in <module>
    from textfsm.parser import *
ImportError: No module named parser

**Comment by ktbyers** [comment]
Something looks messed up with your textfsm installation?

You might want to try a clean virtual environment and see if it works properly.

Textfsm 1.1.0 should have a file named parser.py. Here is the file I have:

/home/kbyers/VENV/py3_venv/lib64/python3.6/site-packages/textfsm/parser.py 

And here is what the repository shows:

https://github.com/google/textfsm/tree/master/textfsm

**Comment by pkeyser** [comment]
Yeah it is weird because all of those files exist. I will see what I can find out.

```
ls /usr/lib/python2.7/site-packages/textfsm/
clitable.py                copyable_regex_object.py   __init__.py                parser.py                  terminal.py                textfsm.py                 texttable.py
clitable.pyc               copyable_regex_object.pyc  __init__.pyc               parser.pyc                 terminal.pyc               textfsm.pyc                texttable.pyc
```

**Comment by pkeyser** [comment]
Seems to be solved now. I uninstalled textfsm via pip but there were still a couple of files left behind on the /usr/lib/python2.7/site-packages/textfsm/ directory. 

```
ls -l /usr/lib/python2.7/site-packages/textfsm/
total 80K
drwxr-xr-x.   2 root root  43 Nov 12 16:56 .
drwxr-xr-x. 177 root root 12K Nov 12 16:56 ..
-rw-r--r--.   1 root root 31K Apr 15  2015 textfsm.py
-rw-r--r--.   1 root root 32K Jan 23  2019 textfsm.pyc
```

Once I deleted those and the directory and installed textfsm again everything seems to be working as expected. Thanks for the help.
