### ISSUE TITLE
ssh to CentOS 7 (cisco 3375 for cmx)

### ISSUE THREAD

**Issue by venman123** [ktbyers/netmiko#1462]
First time posting an issue, apologies if I'm doing it wrong.
When using netmiko and device_type='cisco_ios', I get an issue with the prompt.

    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: '[cmxadmin@cmxadmin@cmx101 ~]$'
the value in the single quotes is the actual prompt, but I believe netmiko is looking for a standard router prompt.
Am I right?  If so, is there another module or a better way to ssh into this device?

here's the pertinent script info:
SSH_Client = ConnectHandler(device_type='cisco_ios', host='<IP of box>', username=username, password=password)

**Comment by ktbyers** [comment]
If the platform is fundamentally Linux, you probably should use a device_type of `linux`.

**Comment by venman123** [comment]
Thank you for the reply.
As a guess, I changed the device type to terminal_server and it worked.

Ven Taylor

**Comment by ktbyers** [comment]
Yes, I would still probably change it to "linux" device_type that will probably be a better choice for your platform.

**Comment by carlmontanari** [comment]
x2 :), but sounds sorted so going to close!
