### ISSUE TITLE
Junos and set cli complete-on-space off causes issues with invalid command

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1463]
File "threads_wait.py", line 32, in main
    output = net_connect.send_command("show ip arp")
  File "/home/student16/VENV/py3_venv/src/netmiko/netmiko/base_connection.py", line 1338, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))

This will fail because the `show ip arp` will get re-written to `show ipv6 `.

This is in `develop` branch.

**Comment by carlmontanari** [comment]
is this different than #1431?

**Comment by carlmontanari** [comment]
dup, closing. will get pr on this opened shortly!
