### ISSUE TITLE
IOError: Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by abnassiri** [ktbyers/netmiko#1465]
Dears
I run the script for census of the Nodes on the network, sometimes the script works well but sometimes it sends  error in object 
![image](https://user-images.githubusercontent.com/38040623/69475681-48905a80-0dd0-11ea-9fc4-31cbae8b23e8.png)

**Comment by abnassiri** [comment]
this the part of script
def extract_hostanme_type(loopback, area, exceptions):
   device_type = ["exception"]
   device ={}
   device['host'] = "" 
   device['ip'] = loopback
   device['username'] = 'xxx'
   device['password'] = 'xxx'
   device['secret'] = 'xxx'
   try: 
    if area == "cisco":
        device['device_type'] = "cisco_xe"
        try:
            net_connect = ConnectHandler(**device)
            output = net_connect.send_command("sh version | in uptime")
            if "Error: Unrecognized command" in output:
                 device['device_type'] = "huawei"
                 output = net_connect.send_command("display current-configuration configuration | in sysname")
                 hostname = formatting_router_ouput(output, "sysname", 1)
                 type = "huawei"
                 print (" leaving Huawei device ======={0}".format(loopback))
            elif "Error: Invalid parameter" in output:
                 device['device_type'] = "alcatel_sros"
                 output = net_connect.send_command("show chassis | match Name")
                 hostname = formatting_router_ouput(output, "Name", 2)
                 type = "alcatel_sros"
                 print (" Leaving Alcatel device ======={0}".format(loopback))
            else:
                hostname = formatting_router_ouput(output, "uptime", 0)
                print( " hostname equal to =  {0}".format(hostname))
                output = net_connect.send_command("sh version | in IOS")
                if "XR" in output:
                    type = "cisco_xr"
                else:
                    type = "cisco_xe"
                print( " leaving Cisco device ======={0}".format(loopback))
        except ValueError:
            try:
                 device['device_type'] = "alcatel_sros"
                 net_connect = ConnectHandler(**device)
                 output = net_connect.send_command("show chassis | match Name")
                 hostname = formatting_router_ouput(output, "Name", 3)
                 type = "alcatel_sros"
                 print( " Leaving Alcatel device ======={0}".format(loopback))
            except ValueError:
                 device['device_type'] = "huawei"
                 net_connect = ConnectHandler(**device)
                 output = net_connect.send_command("display current-configuration configuration | in sysname")
                 hostname = formatting_router_ouput(output, "sysname", 1)
                 type = "huawei"
                 print( " leaving Huawei device ======={0}".format(loopback))
                
    elif area == "huawei" :
        device['device_type'] = "huawei"
        try:
            net_connect = ConnectHandler(**device)
            output = net_connect.send_command("display current-configuration configuration | in sysname")
            print("="*80)
            if "% Invalid input detected" in output:
                 device['device_type'] = "cisco_xe"
                 output = net_connect.send_command("sh version | in uptime")
                 hostname = formatting_router_ouput(output, "uptime", 0)
                 output = net_connect.send_command("sh version | in IOS")
                 if "XR" in output:
                    type = "cisco_xr"
                 else:
                    type = "cisco_xe"
                 print(" accessing Cisco Device ======={0}=====Area Huawei===".format(loopback))
            else:
                print(" output")
                hostname = formatting_router_ouput(output, "sysname", 1)
                type = "huawei"
                print( " accessing Huawei Device ======={0}=====Area Huawei===".format(loopback))
        except ValueError:
            try:
                 device['device_type'] = "alcatel_sros"
                 net_connect = ConnectHandler(**device)
                 output = net_connect.send_command("show chassis | match Name")
                 hostname = formatting_router_ouput(output, "Name", 2)
                 type = "alcatel_sros"
                 print (" accessing Alcatel Device ======={0}=====Area Huawei===".format(loopback))

            except ValueError:
                 exceptions.append(device)
                 hostname = ""
                 type = ""
   except (NetMikoTimeoutException, NetMikoAuthenticationException, EOFError, SSHException):
        exceptions.append(device)
        hostname = ""
        type = ""
   return hostname, type

**Comment by ktbyers** [comment]
Please format your code in a readable way. Thanks.

Kirk

**Comment by abnassiri** [comment]
[23112019.txt](https://github.com/ktbyers/netmiko/files/3882897/23112019.txt)
this the code

**Comment by carlmontanari** [comment]
In general if you get `Search pattern never detected` you either have some latency/slowness (network or just the device itself) -- or in the case of using `send_command_expect` you never see the pattern you are expecting to see. For the former you can increase your `global_delay_factor` for the latter use a session log to see what netmiko is seeing and fix your expect pattern. Going to close this as its likely not a Netmiko bug. If you feel you have found a bug, feel free to reopen with properly formatted output including your code and the stack trace. 

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc -- this is generally a better place for questions that are not feature/bug related.
