### ISSUE TITLE
Can't configure interfaces on different routers in one script.

### ISSUE THREAD

**Issue by semer2k** [ktbyers/netmiko#1468]
Hi guys. I have a script and I want to configure l3 interfaces on R1 and R2 (point-to-point). 1.1.1.1 and 1.1.1.2. But when I started the script it return me smth like the R1 was skipped, but R2 configured normally. Please help me to understand my misconfig. 
IP of R1 - 172.17.17.17 (need to set up eth0/0 with ip 1.1.1.1)
IP of R2 - 172.17.17.18 (need to set up eth0/0 with ip 1.1.1.2)
ips of routers in file dev.txt
The code below: 

`import sys
import getpass
from netmiko import ConnectHandler

username = input("Username: ")
password = getpass.getpass()

with open('dev.txt') as IP_LIST:
    for ip in IP_LIST:
        print(' Connect to device '  + ip)
        device_params = {
            'device_type': 'cisco_ios',
            'ip': ip,
            'username': username,
            'password': password,
            'secret': 'cisco'
            }

        net_connect = ConnectHandler(**device_params)
        net_connect.enable()

      
    if ip == '172.17.17.17':
            config_commands = ['interface et0/0', 'ip address 1.1.1.1 255.255.255.252', 'no shutdown']
            output = net_connect.send_config_set(config_commands)
            print(output)
    elif ip == '172.17.17.18':
            config_commands = ['interface et0/0', 'ip address 1.1.1.2 255.255.255.252', 'no shutdown']
            output = net_connect.send_config_set(config_commands)
            print(output)

    print('\n Saving the configuration \n')
    output = net_connect.save_config()
    print(output)

`
The output that I have got is: 
Username: cisco
 Connect to device 172.17.17.17

 Connect to device 172.17.17.18
config term
Enter configuration commands, one per line.  End with CNTL/Z.
R2(config)#interface et0/0
R2(config-if)#ip address 1.1.1.2 255.255.255.252
R2(config-if)#no shutdown
R2#

 Saving the configuration

Building configuration...
[OK]

**Comment by carlmontanari** [comment]
Going to close as this is not a bug/enhancement.

Hard to tell exactly as formatting is a bit wonky, but looks like you loop over IPs but you only create a single ConnectHandler. You need to create a connection object per IP.

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel that is more appropriate for questions/comments/etc if you're still having any issues.
