### ISSUE TITLE
Netmiko takes too long!

### ISSUE THREAD

**Issue by nikabenashvili** [ktbyers/netmiko#1469]
Hello Guys,

I'm pretty new (couple of days) with netmiko and with python, but my netmiko takes ages to execute come commands. its still nice that I dont have to do that by hand, but it would be better if at list 2 seconds took command. I tried fast_cli=true, but its unreliable as code was getting some errors, probably sending commands was too fast. here is my code:

from netmiko import ConnectHandler
AS = []

###############################################################################################
###############################################################################################
def list():
    username = input('username:  ')
    password = input('password:  ')
    device = open("Devices.txt",'r')
    devices = device.read()
    devices = devices.splitlines()
    for ip in devices:
        AS.append({'device_type' : 'hp_procurve', 'ip' : ip,  'username' : username,'password' : password,})
    return AS

list()

for S in AS:
    ############################################################################################
    ##  Switch Level Configuration Starts Here  ################################################
    ############################################################################################
    connect = ConnectHandler(**S)
    connection = str(('connecting to ' + S['ip']))
    print(connection)
    conf = connect.send_config_set(['vlan  ' + '64 ' + 'name ' + 'Admin_net_L2-1'])
    print(conf)
    conf = connect.send_config_set(['vlan  ' + '96 ' + 'name ' + 'Admin_net_L2-2'])
    print(conf)
    conf = connect.send_config_set(['vlan  ' + '105 ' + 'name ' + 'Admin_net_L2-3'])
    print(conf)
    for i in range(1,28):
        #######################################################################################
        ##   Interface Level Configuration Starts Here    #####################################
        #######################################################################################
        lldp = connect.send_command('show lldp info remote ' + str(i) + '|i SysName')
        lldp = str(lldp)
        lldp = lldp.strip()
        lldp = lldp.strip('SysName      : ')
        #######################################################################################
        ##  Conditions of interface configurations start here    ##############################
        #######################################################################################
        if "BUDHI" in lldp:
            print('show lldp info remote ' + str(i) + '|i SysName')
            print(str(connect.send_command('show lldp info remote ' + str(i) + '|i SysName')))
            conf = connect.send_config_set(['interface ' + str(i), 'tagged vlan 64', 'tagged vlan 96', 'tagged vlan 105', 'name ' + lldp ])
            print(conf)
        else:
            continue
    lldp = str(connect.send_command("show lldp info remote"))
    file = open('show lldp.txt','a')
    file.write(connection)
    file.write(lldp)
    save = connect.save_config()
    disconnect = ConnectHandler.disconnect
    print(save)
    disconnect

###some bulshit###
end = input("get it? y/n ")
if end == "y":
    print("nice!")
    exit()
else:
    print("read again!")
    exit()

**Comment by ktbyers** [comment]
Please format your code so it is readable (see GitHub Markdown).

Try using the Netmiko `develop` branch.

Also I would try to send all the configuration commands using send_config_set once (i.e. send a list of commands).

If you want better performance, you should also try to consolidate the show commands (i.e. get one big LLDP output and parse it on the Python side).

I would try fast_cli=True on that `develop` branch (try it both on and off).

**Comment by ktbyers** [comment]
I am going to close if there is still an issue/problem re-open. Screen-scraping is inherently slow...so it will be slow to a certain extent.
