### ISSUE TITLE
grep commands in wlc ios using netmiko

### ISSUE THREAD

**Issue by bibin0dilli** [ktbyers/netmiko#1474]
I need help with my code...
I can successfully login to a wlc , and i am sending a command with grep option like grep include "bdr" "sh cdp nei"

The problem is after the command is executed , wlc shows a message to "press any key to continue" to show the output ..but the code just hangs in there...i am using send_command to run the grep ...let me know a way to fix this

Please help me...

**Comment by bibin0dilli** [comment]
![15753923517586765444722311283795](https://user-images.githubusercontent.com/58481777/70072129-6786bc00-161c-11ea-8a36-93d89141527a.jpg)

**Comment by carlmontanari** [comment]
Please don't post screenshots. Use the code formatting options here.

Going to close as this is not a bug/issue. To handle this see this example: https://github.com/ktbyers/netmiko/blob/develop/examples/use_cases/case5_prompting/send_command_prompting.py
