### ISSUE TITLE
Telnet ConnectHandler.disconnect() takes time to disconnect on cisco_ios

### ISSUE THREAD

**Issue by shesh1123** [ktbyers/netmiko#1478]
Hi,

I am running below script.

Even though the command is executed and output is pulled relatively fast, the disconnect() function is taking way too much time. 
--------------------------------------------------------
```python
host_list = ['host1','host2']
#ssh is enabled on host1 and disabled in host2

for host in host_list:
	start_time = time.time()
	net_connect = ConnectHandler(host,username= username,password= password,secret=password,device_type= "cisco_ios_telnet")
	output = net_connect.send_command("show ip ssh | inc abled")
	print (output)
	output_time= time.time() - start_time
	net_connect.disconnect()
	disco_time = time.time()-output_time
	print(f'output_time : {output_time}, disco_time : {disco_time}')
```
-------------------------------------------
Result:
shesh@test:~/local_script$ ./chg_ssh.py
SSH Enabled - version 1.99
output_time : 9.334260940551758, disco_time : 100.54348492622375
SSH Disabled - version 1.99
output_time : 9.35062575340271, disco_time : 100.52847290039062

--------------------------------------------

**Comment by ktbyers** [comment]
I am not seeing an issue?

```python
start_time = datetime.now()
net_connect = ConnectHandler(
    host=host, username=username, password=password, device_type="cisco_ios_telnet"
)
output = net_connect.send_command("show ip ssh | inc abled")
print (output)
output_time = datetime.now()
net_connect.disconnect()
disco_time = datetime.now()
print(f'output_time : {output_time - start_time}, disco_time : {disco_time - output_time}')
print(f'output_time : {output_time}, disco_time : {disco_time}')
```

```
$ python netmiko_test.py 
SSH Enabled - version 2.0
output_time : 0:00:09.331936, disco_time : 0:00:00.100724
output_time : 2019-12-10 09:39:36.873220, disco_time : 2019-12-10 09:39:36.973944
```

What version of Netmiko are you using?

**Comment by shesh1123** [comment]
>>> netmiko.__version__
'2.4.2'

**Comment by ktbyers** [comment]
You probably would need to look at the Netmiko session_log to see what is happening (as I am not seeing this behavior).

**Comment by shesh1123** [comment]
Hi Kirk,

Thank you for the prompy reply.
```
python
net_connect = ConnectHandler(host,username= username,password= password,secret=password,device_type= "cisco_ios_telnet",session_log='output.txt')
```
Below is the session log:

shesh@test:~/local_script$ cat output.txt
C

   ***********************   Authorised Users Only   ***********************

                This service is for authorised users only.

             Unauthorised or unlawful access to this system
              is strictly prohibited in all circumstances.

      All use of this system is monitored and malicious use will result
          in prosecution of the offender to the extent of the law.

   *************************************************************************


User Access Verification

Username: sheshtest
Password:

host2>
host2>
host2>terminal length 0
host2>terminal width 511
host2>
host2>show ip ssh | inc abled
SSH Disabled - version 1.99
host2>
host2>exit
shesh@test:~/local_script$

**Comment by ktbyers** [comment]
So you sit there for 200 seconds before your program exits?

**Comment by shesh1123** [comment]
the production script runs in the background, so i don't worry about the delay or completion.

However, its weird that its taking so much time to exit. I can't figure out why.

**Comment by shesh1123** [comment]
If I ssh to the same devices, it works fine.
:~/local_script$ ./chg_ssh.py
SSH Enabled - version 1.99
output_time : 0:00:05.284055, disco_time : 0:00:08.248649
SSH Enabled - version 1.99
output_time : 0:00:05.282649, disco_time : 0:00:08.233916
----------
Telnet is the only one thats getting delayed:
~/local_script$ ./chg_ssh.py
SSH Enabled - version 1.99
output_time : 0:00:09.333359, disco_time : 0:01:40.567475
SSH Enabled - version 1.99
output_time : 0:00:11.577861, disco_time : 0:01:40.557629

**Comment by shesh1123** [comment]
If I ssh to the same devices, it works fine.
:~/local_script$ ./chg_ssh.py
SSH Enabled - version 1.99
output_time : 0:00:05.284055, disco_time : 0:00:08.248649
SSH Enabled - version 1.99
output_time : 0:00:05.282649, disco_time : 0:00:08.233916

Telnet is the only one thats getting delayed:
~/local_script$ ./chg_ssh.py
SSH Enabled - version 1.99
output_time : 0:00:09.333359, disco_time : 0:01:40.567475
SSH Enabled - version 1.99
output_time : 0:00:11.577861, disco_time : 0:01:40.557629

**Comment by ktbyers** [comment]
Can you test on the netmiko `develop` branch and see if the behavior is the same?

**Comment by shesh1123** [comment]
Is that a different setup/version of netmiko or does it use specific arguments?I do see a develop branch in git, but not sure how to test it.  I am still learning, so please elaborate on how to test the develop branch. Thanks

**Comment by carlmontanari** [comment]
@shesh1123 -- `pip install git+https://github.com/ktbyers/netmiko.git@8495b5fdcd4ff4a7271f990a2e518bd8ad8e89bb` will install latest commit to develop (as of this moment)

**Comment by DavidP2190** [comment]
I am having the same issue with telnet, tried with latest develop branch and still exists.  Seems to be the cleanup function that it hangs at.

**Comment by ktbyers** [comment]
Might be related to this PR:

https://github.com/ktbyers/netmiko/pull/1556

I am going to close as I don't think there is a remaining issue. If there is an ongoing issue, please open a new Netmiko issue.
