### ISSUE TITLE
AttributeError: 'list' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by tomreilly** [ktbyers/netmiko#1484]
Hello, 
A complete noob with Netmiko, so appreciate your time in advance!
I currently manage a large number of Network devices via SOCKSv5 Tunnel through a Linux Bastion Host.
On my side, I am using a Windows 10 Linux subsystem (OpenSUSE) to create the SOCKSv5 tunnel... this is my ssh_config file -

Host BRONZE
  User <user>
  hostname <hostname>

Host * !BRONZE
  User <user>
  ProxyCommand /usr/bin/nc -x 127.0.0.1:1080 %h %p

This is the command I use to build the tunnel, using Dynamic Port Forwarding -

ssh -D 1080 -f -C -q -N BRONZE

I can SSH directly to any of my Managed Devices, matching the second entry in my ssh_config file above.
However, when I try and run a simple Netmiko script... the script does not even attempt to SSH over the tunnel. (verified in Packet Capture)
This is the script I use -

from netmiko import ConnectHandler
from getpass import getpass

with open('cli_commands') as f:
    commands_list = f.read().splitlines()

with open('devices') as f:
    devices_list = f.read().splitlines()

for devices in devices_list:
    print('Connecting to host" ' + devices)
    ip_address_of_device = devices
    ios_devices = {
      'device_type': 'cisco_ios',
      'ip': ip_address_of_device,
      'username': '<user>',
      'password': getpass(),
      'ssh_config_file': './ssh_config',
    }

    net_connect = ConnectHandler(**ios_devices)
    output = net_connect.send_command(commands_list)
    print(output)

This is the error I get - 

DG00018:~/Network_Automation/netmiko/SCRIPTS # python3 ssh_show_commands.py
Connecting to host" <ip>
Password:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 858, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3.6/site-packages/paramiko/client.py", line 362, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on <ip>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ssh_show_commands.py", line 21, in <module>
    net_connect = ConnectHandler(**ios_devices)
  File "/usr/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 228, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 312, in __init__
    self.establish_connection()
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 864, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios <ip>:22

I'm a little confused why I can SSH direct from my Linux Subsystem (using the SOCKSv5 tunnel), but my Netmiko script doesn't seem to attempt, or use the ssh_config file.

Any help appreciated?

**Comment by daanvdsanden** [comment]
Is the output of the command `DG00018:~/Network_Automation/netmiko/SCRIPTS # cat ssh_config` the displayed ssh config file?

The reason I ask is that you can use the ssh command to go via the bastion host (which usually uses the ~/.ssh/config file). But you are including './ssh_config' (which resolves to ~/Network_Automation/netmiko/SCRIPTS/ssh_config).

**Comment by tomreilly** [comment]
Thank you for your reply... I have resolved the above issue by amending my ~/.ssh/config file, however, I am now getting another error when trying to call a devices file, and a list of commands file...

Here is my Script - 

from netmiko import ConnectHandler
from getpass import getpass

password = getpass()

with open('commands_file') as f:
    commands_to_send = f.read().splitlines()

with open('devices_file') as f:
    devices_list = f.read().splitlines()

for devices in devices_list:
    print('Connecting to device ' + devices)
    ip_address_of_device = devices
    ios_devices = {
        'device_type': 'cisco_ios',
        'ip': ip_address_of_device,
        'username': '<user>',
        'password': password,
        'secret': password,
        'ssh_config_file': '~/.ssh/config'
    }

    net_connect = ConnectHandler(**ios_devices)
    output = net_connect.send_command(commands_to_send)
    print(output)
    net_connect.disconnect()


Here is the error I receive -

Traceback (most recent call last):
  File "netmiko6.py", line 30, in <module>
    output = net_connect.send_command(commands_to_send)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 1296, in send_command
    command_string = self.normalize_cmd(command_string)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 1428, in normalize_cmd
    command = command.rstrip()
AttributeError: 'list' object has no attribute 'rstrip'

Wondering if anyone can point me in the right direction?

**Comment by daanvdsanden** [comment]
Send_command expects a string and not a list. You can either use the method `send_config_from_file` ([see documentation](https://ktbyers.github.io/netmiko/docs/netmiko/index.html#netmiko.BaseConnection.send_config_from_file)) or iterate over your commands like:
```python
for command in commands_to_send:
    output = net_connect.send_command(commands_to_send)
    print(output)
```

**Comment by tomreilly** [comment]
I changed the Script to -

from netmiko import ConnectHandler
from getpass import getpass

password = getpass()

with open('commands_file') as f:
    commands_to_send = f.read().splitlines()
    print(commands_to_send)

with open('devices_file') as f:
    devices_list = f.read().splitlines()

for devices in devices_list:
    print('Connecting to device ' + devices)
    ip_address_of_device = devices
    ios_devices = {
        'device_type': 'cisco_ios',
        'ip': ip_address_of_device,
        'username': 'treilly',
        'password': password,
        'secret': password,
        'ssh_config_file': '~/.ssh/config'
    }

    net_connect = ConnectHandler(**ios_devices)
    for commands in commands_to_send:
        output = net_connect.send_command(commands_to_send)
        print(output)
        net_connect.disconnect()

But still get the below issue -

Traceback (most recent call last):
  File "netmiko6.py", line 32, in <module>
    output = net_connect.send_command(commands_to_send)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 1296, in send_command
    command_string = self.normalize_cmd(command_string)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 1428, in normalize_cmd
    command = command.rstrip()
AttributeError: 'list' object has no attribute 'rstrip'

**Comment by daanvdsanden** [comment]
I made a typo. Sorry, I have edited the response

**Comment by tomreilly** [comment]
Got it working with this Script -
Assuming this is what you meant by " iterate over your commands like:"


#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass

password = getpass()

with open('commands_file') as f:
    commands_to_send = f.read().splitlines()
    print(commands_to_send)

with open('devices_file') as f:
    devices_list = f.read().splitlines()

for devices in devices_list:
    print('Connecting to device ' + devices)
    ip_address_of_device = devices
    ios_devices = {
        'device_type': 'cisco_ios',
        'ip': ip_address_of_device,
        'username': 'treilly',
        'password': password,
        'secret': password,
        'ssh_config_file': '~/.ssh/config'
    }

    net_connect = ConnectHandler(**ios_devices)
    for commands in commands_to_send:
        output = net_connect.send_command(commands)
        print(output)
    net_connect.disconnect()


Thanks for your help :)
