### ISSUE TITLE
How do I send a KeyStroke with Netmiko

### ISSUE THREAD

**Issue by assadniang** [ktbyers/netmiko#1486]
Hello,

I am login to the router via console, and would like to get back to bash by sending 'CTRL + ]'

The ascii says it is '\x29', but I am not sur how I would send it with the raw net_connect.write_channel('...')

```
root@ptr546-jdm:~# virsh console vcsr-a
Connected to domain vcsr-a
Escape character is ^]


User Access Verification

Username: cisco
Password: 

ptr546-vcsr-a>en
ptr546-vcsr-a#
ptr546-vcsr-a#
ptr546-vcsr-a#
<-------- CTRL + ] to exit back to bash ------>
root@ptr546-jdm:~# 
```

**Comment by ktbyers** [comment]
I think the `^]` is ascii `\x1b`

https://condor.depaul.edu/sjost/lsp121/documents/ascii-npr.htm

So you would just write_channel('\x1b') and then do it what required after that.

**Comment by assadniang** [comment]
Thank you Kirk,

Works perfect...

```
net_connect.write_channel('\x1d')
time.sleep(2)
output = net_connect.read_channel()
print(output)
```

```
Router#
DEBUG:netmiko:write_channel: b'wr\n'
DEBUG:netmiko:read_channel: wr

Building configuration...

[OK]

Router#
DEBUG:netmiko:write_channel: b'\x1d'
DEBUG:netmiko:read_channel: 

root@ptr546-jdm:~# 
DEBUG:paramiko.transport:EOF in transport thread
```

**Comment by carlmontanari** [comment]
Going to close. Please use the Slack channel for general questions and use issues for bugs/feature issues. 

Find the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc
