### ISSUE TITLE
Netmiko adds space or '/n' to read_channel in Juniper Junos bash

### ISSUE THREAD

**Issue by assadniang** [ktbyers/netmiko#1490]
Hello,

Not sure if this is an issue or not. I have not been able to get around it or find a solution.

Basically, I am on the bash shell in a Juniper router, and issue a write_channel to do a simple file copy.
When I looked at the debug, it seems Netmiko adds a space or '\n' where there should not be one:

```
net_connect.write_channel('cp csr1000v-universalk9.16.06.04-serial.qcow2 csr1000v-universalk9.16.06.04-serial-9BCRSL7TN7J.qcow2\n')
time.sleep(5)    
output = net_connect.read_channel()
print(output)
print()
```

Output:

`al.qcow2 csr1000v-universalk9.16.06.04-serial-9BCRSL7TN7J.qcow2`

Debug:

```
DEBUG:netmiko:write_channel: b'cp csr1000v-universalk9.16.06.04-serial.qcow2 csr1000v-universalk9.16.06.04-serial-9BCRSL7TN7J.qcow2\n'
DEBUG:netmiko:read_channel: cp csr1000v-universalk9.16.06.04-seri 
al.qcow2 csr1000v-universalk9.16.06.04-serial-9BCRSL7TN7J.qcow2
```

If you look at the debug read_channel, there is a space or '/n' where there should not be one:
```
seri 
al.qcow2
```

I attached a picture to show how it looks like when I open the DEBUG in notepad.

I tried changing it to raw, but that did not help:
```
net_connect.write_channel(r'cp csr1000v-universalk9.16.06.04-serial.qcow2 csr1000v-universalk9.16.06.04-serial-9BCRSL7TN7J.qcow2\n')
time.sleep(5)    
output = net_connect.read_channel()
print(output)
print()
```

![netmiko_issue](https://user-images.githubusercontent.com/55926182/70869369-409f8280-1f58-11ea-82ae-44c9f07ad4e8.PNG)

**Comment by assadniang** [comment]
I solve the issue by adding this before issuing the write:

```
net_connect.write_channel('stty rows 56 cols 200\n')
 
    time.sleep(5)    
    output = net_connect.read_channel()
```
Not a Netmiko issue

**Comment by carlmontanari** [comment]
Cool, closing this then!
