### ISSUE TITLE
Error reading SSH protocol banner'>=' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by allan-silverstein** [ktbyers/netmiko#1493]
I'm using threads and when trying to connect to about 18 devices at the same time, this always seems to happen to 1 or 2 devices that I'm connecting to.  I tried setting the banner_time to 20 but that does not seem to help.  It even happens sometimes when just connecting to 5 devices....

Error reading SSH protocol banner'>=' not supported between instances of 'float' and 'str'

Any suggestions or ideas?

**Comment by ktbyers** [comment]
@allan-silverstein Not enough information there. Can you provide a full-stack trace?

**Comment by allan-silverstein** [comment]
Sorry about the delay... Thx 

transport.py 1760 ERROR Exception: Error reading SSH protocol banner'>='
not supported between instances of 'float' and 'str'
transport.py 1758 ERROR Traceback (most recent call last):
transport.py 1758 ERROR File
"/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/transport.py",
line 2152, in _check_banner
transport.py 1758 ERROR buf = self.packetizer.readline(timeout)
transport.py 1758 ERROR File
"/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/packet.py",
line 380, in readline
transport.py 1758 ERROR buf += self._read_timeout(timeout)
transport.py 1758 ERROR File
"/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/packet.py",
line 621, in _read_timeout
transport.py 1758 ERROR if now - start >= timeout:
transport.py 1758 ERROR TypeError: '>=' not supported between instances
of 'float' and 'str'
transport.py 1758 ERROR
transport.py 1758 ERROR During handling of the above exception, another
exception occurred:
transport.py 1758 ERROR
transport.py 1758 ERROR Traceback (most recent call last):
transport.py 1758 ERROR File
"/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/transport.py",
line 1980, in run
transport.py 1758 ERROR self._check_banner()
transport.py 1758 ERROR File
"/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/transport.py",
line 2157, in _check_banner
transport.py 1758 ERROR "Error reading SSH protocol banner" + str(e)
transport.py 1758 ERROR paramiko.ssh_exception.SSHException: Error
reading SSH protocol banner'>=' not supported between instances of
'float' and 'str'
transport.py 1758 ERROR 

On 19.12.2019 11:49, Kirk Byers wrote:

> @allan-silverstein [1] Not enough information there. Can you provide a full-stack trace? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

 

Links:
------
[1] https://github.com/allan-silverstein
[2]
https://github.com/ktbyers/netmiko/issues/1493?email_source=notifications&amp;email_token=AEMTIKSSH4L7A6LRCFV3QCLQZOQYVA5CNFSM4J5KWAUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHKG5MA#issuecomment-567570096
[3]

**Comment by daanvdsanden** [comment]
@allan-silverstein can you share an (anonimized) version of your device dict you use to connect to the device? It looks like you have set the banner_timeout to a string instead of a number. Se below snippet:
```python
device = { 
    'device_type': 'cisco_ios',
    'host': host,
    'username': username,
    'password': password,
    'banner_timeout': banner_timeout,
} 

net_connect = ConnectHandler(**device)
```
Make sure the variable banner_timeout is a float or integer and not a string.

**Comment by allan-silverstein** [comment]
Here is a snippet of my hosts.yml file… I set the banner because when I first started using netmiko I had quite a bit of inconsistency successfully connecting (I forget the exact error back then…).  After setting the banner time to 20, it seemed to have gone away.  As of late, I started adding more device, to now I’m at about 18 devices in our lab environment.  At this point it seems to happen to at least 1 device every run.  If there was a problem with the banner_timeout, then I would think it would happen every time for every device since the banner is set to 20 seconds for all devices?  No??

Note, I built my own device type by just subclassing off of BaseConnection.  However, I just swapped out a few methods such as paging and commit…, not the connect/login methods..

At this point, I can’t state the device_type as I’m under NDA. 

 

As a test, I could remove the banner timeout from the hosts.yml file for all devices and see if the problem goes away… Or I get a different problem.

 

Thx

Al  

 

 

ny21:

  device_type: mydev

  session_log: ny21.log

  ip: ny21

  username: xxx

  password: xxx

  banner_timeout: 20

ny22:

  device_type: mydev

  session_log: ny22.log

  ip: ny22

  username: xxx

  password: xxx

  banner_timeout: 20

**Comment by daanvdsanden** [comment]
```
transport.py 1760 ERROR Exception: Error reading SSH protocol banner'>=' not supported between instances of 'float' and 'str'
transport.py 1758 ERROR Traceback (most recent call last):
transport.py 1758 ERROR   File "/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/transport.py", line 2152, in _check_banner
transport.py 1758 ERROR     buf = self.packetizer.readline(timeout)
transport.py 1758 ERROR   File "/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
transport.py 1758 ERROR     buf += self._read_timeout(timeout)
transport.py 1758 ERROR   File "/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/packet.py", line 621, in _read_timeout
transport.py 1758 ERROR     if now - start >= timeout:
transport.py 1758 ERROR TypeError: '>=' not supported between instances of 'float' and 'str'
transport.py 1758 ERROR
transport.py 1758 ERROR During handling of the above exception, another exception occurred:
transport.py 1758 ERROR
transport.py 1758 ERROR Traceback (most recent call last):
transport.py 1758 ERROR   File "/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/transport.py", line 1980, in run
transport.py 1758 ERROR     self._check_banner()
transport.py 1758 ERROR   File "/home/as2863/python-venv/p1_netmiko_exper/lib/python3.7/site-packages/paramiko/transport.py", line 2157, in _check_banner
transport.py 1758 ERROR     "Error reading SSH protocol banner" + str(e)
transport.py 1758 ERROR paramiko.ssh_exception.SSHException: Error reading SSH protocol banner'>=' not supported between instances of 'float' and 'str'
transport.py 1758 ERROR
```
Without looking at the code it will be hard to understand why the exception is thrown. The exception message is very clear. It says that timeout is of the type `'str'` (string). Following the code back this is the banner_timout value in netmiko. The default is an integer, so if paramiko thinks it is a string it most probably is. And this means it was defined as a string somewhere in your code. Please make sure the value time_out value is assigned an integer or a float.

**Comment by allan-silverstein** [comment]
Took your recommendation and saw that I was opening the hosts.yml file 
using yaml.BaseLoader.  yaml.BaseLoader assigns all values as either a 
dictionary, list, or unicode string.   I used the baseloader a while ago 
for a different reason and it came back to bite me here...

Thx for pointing me in the right direction.

Al Silverstein


def open_yaml_file (file):
     '''
     Open YAML file and return contents of
     YAML file as a dictionary.
     '''

     ###########################################
     # Read in YAML file.
     # Note, yaml.load() returns YAML variables
     # as a dictionary object.
     ###########################################
     try:
         with open(file, 'r') as f:
#           doc = yaml.load(f)
             doc = yaml.load(f, Loader=yaml.BaseLoader)
#           doc = yaml.safe_load(f)
#           print("Here is the doc: ", doc)
             return doc
     except Exception as err:
         print("Problem reading in YAML input file: ", file)
         print(err)
         exit(1)
