### ISSUE TITLE
Netmiko working in script at shell/interpreter but connections fail running as cgi

### ISSUE THREAD

**Issue by gnasses** [ktbyers/netmiko#1502]
A script I use for basic server/device checkout works fine on my window install, and my RHEL install, even there via Jenkins, but I want to extend it to a cgi script so device owners can do self-service checkouts. I can run the scripts as ./servervalidation1.py and it executes fine, but the first connection times out when running as a GCI script. Enabling cgi tracebacks shows I get as far as "establish_connection" but then returns NetMikoTimeoutException: Connection to device timed-out: cisco_ios core01:22

I suspect there is something I am missing that I need or some other difference when calling this via cgi that I am not understanding. Apologies for the formatting, I cannot seem to get it to work as markdown like I usually am able. 

Here is the script up to the point it fails, including troubleshooting elements I added:
#!/usr/bin/python3
from __future__ import print_function, unicode_literals
import sys
import site
import datetime
import netmiko
from netmiko import Netmiko
import util
import os.path
import cgi
import cgitb
cgitb.enable()
form = cgi.FieldStorage()
hostname = 'testserver'
print("Content-Type: text/html\n\n")
print (netmiko.__file__)
print (netmiko.__version__)
print ("Network Test Results")
print ("Hostname: " + hostname)
print ("Date and time of Analysis:")
now = str(datetime.datetime.now())
print (now)
print ("<b>Basic Server/Device Network Validation Routine</b>")
#define core01 and 02
core01 = util.CiscoDeviceRO(host="core01")
core02 = util.CiscoDeviceRO(host="core02")
ping1 = ()
#while loop for error handling of invalid hostname, length arbitrarily set to 50
while len(ping1) <= 50:
    #connect to core devicess using Netmiko
    net_connect1 = Netmiko(**core01.__dict__)
    net_connect2 = Netmiko(**core02.__dict__)
    print ("netmiko connected")
    #ping the entered hostname        
    ping1 = net_connect1.send_command("ping " + hostname + " count 100")
    ping2 = net_connect2.send_command("ping " + hostname + " count 100")
    #print error message and restart loop or indicate testing in process
    if len(ping1) <= 50:
        print ("Could not resolve servername. Please try again.")
    else:
        print ("Testing " + hostname + "...")

Here is the function I call from my util.py to create the dictionary for the device connection: 

`class CiscoDeviceRO:`
`    def __init__(self, host, username='ro_account', password='ro_passwd', device_type='cisco_ios', timeout=120, auth_timeout=120):`
`        self.host = host`
`        self.username = username`
`        self.password = password`
`        self.device_type = device_type`
`        self.timeout = timeout`
`        self.auth_timeout = auth_timeout`

Here is the cgitb info I get when I try to run it from /var/www/cgi-bin. Again, sorry this output looks bad here:

/usr/local/lib/python3.6/site-packages/netmiko/__init__.py
2.4.2
Network Test Results
Hostname: testserver
Date and time of Analysis:
2020-01-04 09:29:29.652182
Basic Server/Device Network Validation Routine
--> -->
NetMikoTimeoutException	Python 3.6.8: /usr/bin/python3
Sat Jan 4 09:29:29 2020
A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.
 /var/www/cgi-bin/servervalidation1.py in <module>()
     35 while len(ping1) <= 50:
     36     #connect to EBRs using Netmiko
=>   37     net_connect1 = Netmiko(**core01.__dict__)
     38     net_connect2 = Netmiko(**core02.__dict__)
     39     print ("netmiko connected")
net_connect1 undefined, Netmiko = <function ConnectHandler>, core01 = <util.CiscoDeviceRO object>, core01.__dict__ = {'auth_timeout': 120, 'device_type': 'cisco_ios', 'host': 'core01', 'password': 'ro_passwd', 'timeout': 120, 'username': 'ro_user'}
 /usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py in ConnectHandler(*args=(), **kwargs={'auth_timeout': 120, 'device_type': 'cisco_ios', 'host': 'core01', 'password': 'ro_passwd', 'timeout': 120, 'username': 'ro_user'})
    244         )
    245     ConnectionClass = ssh_dispatcher(kwargs["device_type"])
=>  246     return ConnectionClass(*args, **kwargs)
    247 
    248 
ConnectionClass = <class 'netmiko.cisco.cisco_ios.CiscoIosSSH'>, args = (), kwargs = {'auth_timeout': 120, 'device_type': 'cisco_ios', 'host': 'core01', 'password': 'ro_passwd', 'timeout': 120, 'username': 'ro_user'}
 /usr/local/lib/python3.6/site-packages/netmiko/base_connection.py in __init__(self=<netmiko.cisco.cisco_ios.CiscoIosSSH object>, ip='', host='core01', username='ro_user', password='ro_passwd', secret='', port=22, device_type='cisco_ios', verbose=False, global_delay_factor=1, use_keys=False, key_file=None, pkey=None, passphrase=None, allow_agent=False, ssh_strict=False, system_host_keys=False, alt_host_keys=False, alt_key_file='', ssh_config_file=None, timeout=120, session_timeout=60, auth_timeout=120, blocking_timeout=8, banner_timeout=5, keepalive=0, default_enter=None, response_return=None, serial_settings={}, fast_cli=False, session_log=None, session_log_record_writes=False, session_log_file_mode='write', allow_auto_change=False, encoding='ascii')
    315 
    316         # Establish the remote connection
=>  317         self._open()
    318 
    319     def _open(self):
self = <netmiko.cisco.cisco_ios.CiscoIosSSH object>, self._open = <bound method BaseConnection._open of <netmiko.cisco.cisco_ios.CiscoIosSSH object>>
 /usr/local/lib/python3.6/site-packages/netmiko/base_connection.py in _open(self=<netmiko.cisco.cisco_ios.CiscoIosSSH object>)
    320         """Decouple connection creation from __init__ for mocking."""
    321         self._modify_connection_params()
=>  322         self.establish_connection()
    323         self._try_session_preparation()
    324 
self = <netmiko.cisco.cisco_ios.CiscoIosSSH object>, self.establish_connection = <bound method BaseConnection.establish_connection of <netmiko.cisco.cisco_ios.CiscoIosSSH object>>
 /usr/local/lib/python3.6/site-packages/netmiko/base_connection.py in establish_connection(self=<netmiko.cisco.cisco_ios.CiscoIosSSH object>, width=None, height=None)
    888                     device_type=self.device_type, ip=self.host, port=self.port
    889                 )
=>  890                 raise NetMikoTimeoutException(msg)
    891             except paramiko.ssh_exception.AuthenticationException as auth_err:
    892                 self.paramiko_cleanup()
global NetMikoTimeoutException = <class 'netmiko.ssh_exception.NetMikoTimeoutException'>, msg = 'Connection to device timed-out: cisco_ios core01:22'
NetMikoTimeoutException: Connection to device timed-out: cisco_ios core01:22
      args = ('Connection to device timed-out: cisco_ios core01:22',)
      with_traceback = <built-in method with_traceback of NetMikoTimeoutException object>

**Comment by ktbyers** [comment]
Doesn't really look like a Netmiko issue. Netmiko is just saying it connection to `core01` on port 22 timed-out. I assume `core01` is in DNS and resolves?

I would probably check that the server you are running the CGI on can access `core01` on port 22.

**Comment by gnasses** [comment]
Agree with your analysis, just very odd since the server can definitely resolve and access it, as it runs successfully if I just run it as ./script.py or similar scripts using Netmiko from shell via jenkins, just not as cgi script. Since there doesn’t seem anything obvious wrong or missing, I’ll try building an alternate environment and see what happens there. Thanks for taking a look.

**Comment by gnasses** [comment]
After digging through my logs, this ended up being an selinux issue, after adding an exception for Netmiko it works fine.
