### ISSUE TITLE
NetMikoTimeoutException at /

### ISSUE THREAD

**Issue by Shafeenes** [ktbyers/netmiko#1504]
i am new at netmiko software. i was trying to connect django and netmiko by passing device name, ip, username,password
as i dont have a wifi router at home i am trying to make virtual network using GNS3 software. i dont undertand how to fix my error. please help 

GNS3
![z](https://user-images.githubusercontent.com/59567149/71821280-c2d81e00-30a2-11ea-82ef-444f14f7aca5.JPG)

GNS3
![q](https://user-images.githubusercontent.com/59567149/71821282-c5d30e80-30a2-11ea-89b5-da0a27f316a9.JPG)

django file
![v](https://user-images.githubusercontent.com/59567149/71821286-c8356880-30a2-11ea-9c65-dc0e40588b4b.JPG)

this is the output 

![zzz](https://user-images.githubusercontent.com/59567149/71821393-18acc600-30a3-11ea-9673-8704c8a29987.JPG)

**Comment by daanvdsanden** [comment]
Are you able to connect to the router with an ssh client (putty or equivalent), with the hostname DESKTOP-CT4RSIT on port 22? If not, make sure you fix this first. There should be plenty of resources on the internet on how to connect to a router in GNS with Putty.

**Comment by Shafeenes** [comment]
no i am not able to do that as well it tell me that refused to connect

**Comment by carlmontanari** [comment]
Going to close this as it seems like a GNS3 thing, not a netmiko issue. 

Feel free to join us in the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for general questions/comments/etc -- generally a better place for questions (GitHub is generally better for bugs/feature work).
