### ISSUE TITLE
Exception: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by tomreilly** [ktbyers/netmiko#1507]
I BELIEVE THIS IS A KNOWN "ISSUE" / OCCURRENCE - BUT I COULD NOT FIND A THREAD WITH THE SOLUTION / WORK AROUND IN.
I have a simple script that the aim is to ssh remote access all the devices in a simple device file - if I am able to reach Privilege Exec mode... I print a "Login Successful!" message, if not... I have the simple Error Handling option (for now).
The first 2 devices are known working devices... and the script returns my printed message....
However, the 3rd devices is a device I know I cannot SSH to (this is to test my Error Handling)... and the 4th device is another device that is working as expected.
Below is the output I get from my script --
For the 3rd device... I can see my Error Handling working ("error message..."), and the script moves onto the 4th device... however I still get the traceback error above the output.
I was wondering if this is bug / not possible to remove... or if there is a way to remove this traceback error??
(below the output is a copy of the full script)

######################
OUTPUT FROM SCRIPT
######################

Connecting to Device <IP>...

Login Successful!

Connecting to Device <IP>...

Login Successful!

Connecting to Device 1.1.1.1...

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/packet.py", line 576, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

error message...
Connecting to Device <IP>...

Login Successful!

######################

My Script -

```python
##-- Import Appropriate Libraries
from netmiko import ConnectHandler
from getpass import getpass
from netmiko import NetMikoTimeoutException
from netmiko import NetMikoAuthenticationException
from netmiko import NetmikoTimeoutError
from netmiko import NetmikoAuthError
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko import NetMikoTimeoutException
from paramiko import SSHException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException

##-- Password Variable to Prompt User for Password using "getpass"
password = getpass()

##-- List of Devices to Test Remote Access
with open('remote_devices') as f:
    devices_list = f.read().splitlines()

for devices in devices_list:
    print('Connecting to Device ' + devices + '... ' + '\n')
    ip_address_of_device = devices
    ios_device = {
        'device_type': 'cisco_ios',
        'ip': ip_address_of_device,
        'username': '<USERNAME>',
        'password': password,
        'secret': password,
        'global_delay_factor': 4,
        'ssh_config_file': '~/.ssh/config'
    }

    try:
        net_connect = ConnectHandler(**ios_device)
        net_connect.enable()
        print('Login Successful! ' + '\n')
        net_connect.disconnect()

##-- Error Handling
    except Exception:
        print('error message...')
        continue
```

**Comment by daanvdsanden** [comment]
This is a paramiko "issue". 

For reference see: https://github.com/paramiko/paramiko/issues/643

**Comment by ktbyers** [comment]
Yes, that looks like it...I somewhat suspected it was that type of problem (as I remembered Paramiko did threading in certain situations).

It looks like your code actually does continue onward (given the output you displayed) so it is an issue with unwanted messages on std_err and not actually failing in functionality.

**Comment by tomreilly** [comment]
Thank you for your reply!
Do you know of any workaround... or a way to export the results in a nicer format ("hiding" the paramiko error output)?
Thanks,
Tom

**Comment by ktbyers** [comment]
I would probably look to fix the underlying issue which is causing this message `SSH protocol banner`

This is usually fixed by increasing the `banner_timeout` setting that you pass into Netmiko via ConnectHandler. I would probably try setting that to a value of 10 or 20 and see what happens.

That is probably what I would try.

I don't think there is really anything Netmiko can do about the message to std_err from the separate Paramiko thread (besides doing things like redirecting std_err to /dev/null or something like that, but of course that would hide real errors that you receive).

**Comment by tomreilly** [comment]
Thank you!
I will read up on banner_timeout 
:)

**Comment by carlmontanari** [comment]
Sounds like this is sorted out (at least as much as can be) then! Closing.
