### ISSUE TITLE
New Constructor - Hirschmann

### ISSUE THREAD

**Issue by jgreenhalgh51** [ktbyers/netmiko#1510]
Hi
Can you integrate show running or other command for Hirschmann OS ans HIOS ?
Best regards

**Comment by carlmontanari** [comment]
Adding a vendor is generally community driven. You can see the steps to do so [here](https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md). 

I don't know anything about HIOS but it may be possible to use an existing driver (vendor/platform type) to interact w/ the devices if the CLI is similar enough to something existing (Cisco/Juniper/whatever). You could also use the terminal_server device type which is kind of "lower level" and doesn't handle things like privilege escalation and such.

I'm going to close this as it isn't a feature discussion/bug. Feel free to join us in the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for general questions/comments/etc -- generally a better place for questions (GitHub is generally better for bugs/feature work).
