### ISSUE TITLE
Junos shell prompt not handled

### ISSUE THREAD

**Issue by scott-abt** [ktbyers/netmiko#152]
When logging into a Junos device with "root", it drops you to the shell instead of the operational CLI. This is sort of like when you have to "enable" in IOS to get to the CLI. There probably just needs to be some kind of handler in juniper_ssh.py, I think.

**Comment by ktbyers** [comment]
@scott-abt Let me know if you see any issues with this fix. It will automatically execute 'cli' if you are root@ the shell prompt %.

**Comment by scott-abt** [comment]
I think I'll have something to show the boss man tomorrow. Thanks again!

**Comment by scott-abt** [comment]
Hi,
I re-installed this morning, and I believe this is broken again. I get the "Router prompt not found" error when I try to log in with root now. Here's the whole exception message:

ValueError: Router prompt not found: root@NET-Sandbox:RE:0%

**Comment by ktbyers** [comment]
What version of Netmiko are you running?


Kirk

On Fri, Mar 11, 2016 at 11:23 AM, ScottG <notifications@github.com> wrote:

> Hi,
> I re-installed this morning, and I believe this is broken again. I get the
> "Router prompt not found" error when I try to log in with root now. Here's
> the whole exception message:
>
> ValueError: Router prompt not found: root@NET-Sandbox:RE:0%
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/152#issuecomment-195507676>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by scott-abt** [comment]
0.3.9 so saith pydoc3

**Comment by ktbyers** [comment]
Does it work if you use the released version netmiko.0.3.4?

Either:

pip install netmiko==0.3.4

of

https://github.com/ktbyers/netmiko/releases


Kirk

On Fri, Mar 11, 2016 at 12:54 PM, ScottG <notifications@github.com> wrote:

> 0.3.9 so saith pydoc3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/152#issuecomment-195546946>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by scott-abt** [comment]
Yep, that makes it work for me.

**Comment by ktbyers** [comment]
Okay, strange. I must have broke something in the recent changes. I am not
seeing it on quick glance so I will have to dig into it some more.


Kirk

On Fri, Mar 11, 2016 at 1:28 PM, ScottG <notifications@github.com> wrote:

> Yep, that makes it work for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/152#issuecomment-195562708>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by scott-abt** [comment]
I will make sure to work with the 0.3.4 version for now. Thanks!

**Comment by ktbyers** [comment]
It is all good, I just happened to break something last night / today :-)


Kirk

On Fri, Mar 11, 2016 at 2:59 PM, ScottG <notifications@github.com> wrote:

> I will make sure to work with the 0.3.4 version for now. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/152#issuecomment-195595166>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation
