### ISSUE TITLE
Avoid NET_TEXTFSM environment variable

### ISSUE THREAD

**Issue by yoonghm** [ktbyers/netmiko#1520]
Hi,

  We could install ntc-template via 
```bash
pip install ntc_templates
```
We cloud find the path of installed package via

```python
mport inspect
inspect.getfile(ntc_templates)
```
With these, we do not need to create `NET_TEXTFSM` environment variable which is platform dependent and make user code non-portable.

I could create a pull request to handle it.

**Comment by ktbyers** [comment]
I would be open to this if you want to do a PR...the pattern of preference should be:

1. Use NET_TEXTFSM
2. Try to find "pip" installed version
3. Fall back to looking in ~/ntc-templates/templates


This is for backwards compatibility and also I am not sure how frequently they are going to release new versions of ntc-templates to pypi. Also if you specify an environment variable it is pretty logical that it should have precedence.



Regards,

Kirk

**Comment by yoonghm** [comment]
I have put up a pull request on https://github.com/ktbyers/netmiko/pull/1831

**Comment by ktbyers** [comment]
This issue was solved here:

https://github.com/ktbyers/netmiko/pull/1961

Now support pip installed ntc-templates. Order is ENV_VAR > PIP installed ntc-templates > ~/ntc-templates/templates
