### ISSUE TITLE
Nokia SR-OS driver needs cleanup method defined that gracefully closes SSH session

### ISSUE THREAD

**Issue by thanhuwng** [ktbyers/netmiko#1522]
Hi

When we call `disconnect()` on Cisco SSH connection, there's an implicit `write_channel('exit\n)` before SSH connection is closed. However, when we call `disconnect()` on Nokia SSH connection, there's no `write_channel('logout\n')` before SSH connection is closed. When this is used on a `terminal_server` session, it can leave an open console session to a Nokia device after SSH connection is closed.

An explicit manual `write_channel('logout\n')` can be added before Nokia SSH connection closing, I'm just wondering whether we want to provide the same experience across Cisco and Nokia (and any other devices?) devices?

thanks
Hung

**Comment by ktbyers** [comment]
@thanhuwng Can you test this and see if it fixes your issue:

https://github.com/ktbyers/netmiko/pull/1525

**Comment by thanhuwng** [comment]
@ktbyers Yes it does, thanks.
