### ISSUE TITLE
send_config_set problem: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by martininka** [ktbyers/netmiko#1526]
Thanks a lot @ktbyers for this excellent library and your work on this!

I have an issue when using send_config_set using a Cisco IOS 88x router. We got a template that has around 65 commands, they work fine on cli, and netmiko delivers all commands successfully to the router (yes, all commands are present in the running config). 

But netmiko is stuck in waiting the router to be finished, this is the exception that I get:

` 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/...../conf.py", line 161, in <module>
    conn.send_config_set(tmpl1config, delay_factor=100, max_loops=1000)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1726, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 552, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
`

I already tried several things:

- In the ConnectHandler, added 'blocking_timeout': 100
- In send_config_set added the options: delay_factor=5, delay_factor=100, max_loops=16, max_loops=1000

Cheers

**Comment by ktbyers** [comment]
So `Netmiko` version 3.x by default is going to expect the configuration command to be echoed to the screen. This ensures Netmiko doesn't get out of sync with the underlying device (i.e. keep sending configuration commands even though the remote device might be too slow and buffering them).

So in your above output, Netmiko is failing on that:

```python
new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
```

In that line Netmiko is waiting for the command to be echoed and it is not coming back.

It would be interesting to turn on the Netmiko session_log which is an argument to ConnectHandler and see what is going on (`session_log: "output.txt"`) which will create a file named output.txt which will have the details of the session.

**Comment by ktbyers** [comment]
You can also in `send_config_set` set the following argument to False:

```
      cmd_verify=True,
```

This will turn of that command verification and fallback to the old Netmiko 2.X behavior.

Of course, I am pretty interested to see why it is failing so it would be very helpful to look at your session_log and see why the command verification is not working :-)

**Comment by martininka** [comment]
> So `Netmiko` version 3.x by default is going to expect the configuration command to be echoed to the screen. This ensures Netmiko doesn't get out of sync with the underlying device (i.e. keep sending configuration commands even though the remote device might be too slow and buffering them).
> 
> So in your above output, Netmiko is failing on that:
> 
> ```python
> new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
> ```
> 
> In that line Netmiko is waiting for the command to be echoed and it is not coming back.
> 
> It would be interesting to turn on the Netmiko session_log which is an argument to ConnectHandler and see what is going on (`session_log: "output.txt"`) which will create a file named output.txt which will have the details of the session.

This is the log:
```
DEBUG:netmiko:_read_channel_expect read_data: Router#
DEBUG:netmiko:Pattern found: #
Router#
DEBUG:netmiko:write_channel: b'config term\n'
DEBUG:netmiko:Pattern is: config\ term
DEBUG:netmiko:_read_channel_expect read_data: c
DEBUG:netmiko:_read_channel_expect read_data: onfig term
Enter configuration commands, one per line.  End with CNTL/Z.
Router(config)#
DEBUG:netmiko:Pattern found: config\ term config term
Enter configuration commands, one per line.  End with CNTL/Z.
Router(config)#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: #
DEBUG:netmiko:_read_channel_expect read_data:

DEBUG:netmiko:_read_channel_expect read_data: Router(config)#
DEBUG:netmiko:Pattern found: #
Router(config)#
DEBUG:netmiko:write_channel: b'snmp-server contact phase1\nno event manager applet start-up authorization bypass\nclock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00\nservice timestamps debug datetime localtime show-timezone msec year\nservice timestamps log datetime localtime show-timezone msec year\nno vpdn-group PPTP\nno interface Virtual-Template1\nint vl 1\n description -- xxx -- xxx\n no ip access-group outside-in in\nint vlan 10\n no autostate\nint vlan 20\n no autostate\nint vlan 30\n no autostate\n!\nno ip local pool PPTP_POOL\nno ip access-list extended pptpdialin-out\nno ip access-list extended outside-in\nno aaa authentication ppp default local\n!\nip access-list extended outside-in\n remark traffic from vpn-head\n permit ip host 1.2.3.4 any\n remark traffic from vpn-head\n permit ip host 1.3.4.5 any\n permit ip host 1.2.3.154 any\n permit ip host 1.2.3.149 any\n permit ip host 1.2.3.148 any\n remark dhcp/ssh traffic\n permit udp any eq bootps any eq bootpc\n permit tcp any gt 1024 any eq 22\n remark ping\n permit icmp any any echo\n permit icmp any any echo-reply\n permit tcp any any gt 1024\n permit udp any any gt 1024\n deny   ip any any log-input\n exit\n!\ncrypto isakmp policy 10\n encr aes\n authentication pre-share\n group 2\ncrypto isakmp keepalive 90\n!\ncrypto isakmp peer address 1.2.3.4\n set aggressive-mode password test123\n set aggressive-mode client-endpoint ipv4-address 10.99.99.0\n!\nip access-list extended vpn\n permit ip 10.99.99.0 0.0.0.255 172.16.99.0 0.0.0.255\n permit ip 10.98.99.0 0.0.0.127 172.16.99.0 0.0.0.255\n!\ncrypto ipsec transform-set ESP-AES-SHA esp-aes esp-sha-hmac\n mode tunnel\n!\ncrypto map ipsec 10 ipsec-isakmp\n set peer 1.2.3.4\n set transform-set ESP-AES-SHA\n set pfs group2\n match address vpn\n exit\n'
DEBUG:netmiko:Pattern is: snmp\-server\ contact\ phase1\
no\ event\ manager\ applet\ start\-up\ authorization\ bypass\
clock\ summer\-time\ CEST\ recurring\ last\ Sun\ Mar\ 2:00\ last\ Sun\ Oct\ 3:00\
service\ timestamps\ debug\ datetime\ localtime\ show\-timezone\ msec\ year\
service\ timestamps\ log\ datetime\ localtime\ show\-timezone\ msec\ year\
no\ vpdn\-group\ PPTP\
no\ interface\ Virtual\-Template1\
int\ vl\ 1\
\ description\ \-\-\ xxx\ \-\-\ xxx\
\ no\ ip\ access\-group\ outside\-in\ in\
int\ vlan\ 10\
\ no\ autostate\
int\ vlan\ 20\
\ no\ autostate\
int\ vlan\ 30\
\ no\ autostate\
!\
no\ ip\ local\ pool\ PPTP_POOL\
no\ ip\ access\-list\ extended\ pptpdialin\-out\
no\ ip\ access\-list\ extended\ outside\-in\
no\ aaa\ authentication\ ppp\ default\ local\
!\
ip\ access\-list\ extended\ outside\-in\
\ remark\ traffic\ from\ vpn\-head\
\ permit\ ip\ host\ 1\.2\.3\.4\ any\
\ remark\ traffic\ from\ vpn\-head\
\ permit\ ip\ host\ 1\.2\.3\.153\ any\
\ permit\ ip\ host\ 1\.2\.3\.154\ any\
\ permit\ ip\ host\ 1\.2\.3\.149\ any\
\ permit\ ip\ host\ 1\.2\.3\.148\ any\
\ remark\ dhcp/ssh\ traffic\
\ permit\ udp\ any\ eq\ bootps\ any\ eq\ bootpc\
\ permit\ tcp\ any\ gt\ 1024\ any\ eq\ 22\
\ remark\ ping\ 
\ permit\ icmp\ any\ any\ echo\
\ permit\ icmp\ any\ any\ echo\-reply\
\ permit\ tcp\ any\ any\ gt\ 1024\
\ permit\ udp\ any\ any\ gt\ 1024\
\ deny\ \ \ ip\ any\ any\ log\-input\
\ exit\
!\
crypto\ isakmp\ policy\ 10\
\ encr\ aes\
\ authentication\ pre\-share\
\ group\ 2\
crypto\ isakmp\ keepalive\ 90\
!\
crypto\ isakmp\ peer\ address\ 1\.2\.3\.4\
\ set\ aggressive\-mode\ password\ test123\
\ set\ aggressive\-mode\ client\-endpoint\ ipv4\-address\ 10\.99\.61\.0\
!\
ip\ access\-list\ extended\ vpn\
\ permit\ ip\ 10\.99\.61\.0\ 0\.0\.0\.255\ 172\.16\.99\.0\ 0\.0\.0\.255\
\ permit\ ip\ 10\.98\.61\.0\ 0\.0\.0\.127\ 172\.16\.99\.0\ 0\.0\.0\.255\
!\
crypto\ ipsec\ transform\-set\ ESP\-AES\-SHA\ esp\-aes\ esp\-sha\-hmac\
\ mode\ tunnel\
!\
crypto\ map\ ipsec\ 10\ ipsec\-isakmp\
\ set\ peer\ 1\.2\.3\.4\
\ set\ transform\-set\ ESP\-AES\-SHA\
\ set\ pfs\ group2\
\ match\ address\ vpn\
\ exit
DEBUG:netmiko:_read_channel_expect read_data: sn
DEBUG:netmiko:_read_channel_expect read_data: mp-server contact phase1
Router(config)#no event manager applet start-up authorization bypass
%EEM: No such applet start-up
Router(config)#clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00
Router(config)#service
DEBUG:netmiko:_read_channel_expect read_data:  timestamps debug datetime localtime show-timezone msec year
Router(config)#service timestamps log datetime localtime show-timezone msec year
Router(config)#no vpdn-gr
DEBUG:netmiko:_read_channel_expect read_data: oup PPTP
% VPDN configuration is not allowed until VPDN is enabled through 'vpdn enable'.
Router(config)#no interface Virtual-Template1
                                           ^
% Invalid input detected at '^' marker.

Router(config)#int vl 1
Router(config-if)# description -- Apothekennetz -- IPSec Barracuda
Router(config-if)# no ip access-group outside-in in
Router(config-if)#int vl
DEBUG:netmiko:_read_channel_expect read_data: an 10
Router(config-if)# no autostate
Router(config-if)#int vlan 20
Router(config-if)# no autostate
Router(config-if)#int vlan 30
Router(config-if)# no autostate
Router(config-if)#!
Router(config-if)#no ip local pool PPTP_POOL
Router(config)#no i
DEBUG:netmiko:_read_channel_expect read_data: p access-list extended pptpdialin-out
Router(config)#no ip access-list extended outside-in
Router(config)#no aaa authentication ppp default local
Authentication method list update failed!!
Router(config)#!
Router(config)#ip access-list extended outs
DEBUG:netmiko:_read_channel_expect read_data: ide-in
Router(config-ext-nacl)# remark traffic from vpn-head
Router(config-ext-nacl)# permit ip host 1.2.3.4 any
Router(config-ext-nacl)# remark traffic from vpn-head
Router(config-ext-nacl)# permit ip host 1.3.4.5 any
Router(config-ext-nacl)# permit ip hos
DEBUG:netmiko:_read_channel_expect read_data: t 1.2.3.154 any
Router(config-ext-nacl)# permit ip host 1.2.3.149 any
Router(config-ext-nacl)# permit ip host 1.2.3.148 any
Router(config-ext-nacl)# remark dhcp/ssh
Router(config-ext-nacl)# permit udp any eq bootps any eq boo
DEBUG:netmiko:_read_channel_expect read_data: tpc
Router(config-ext-nacl)# permit tcp any gt 1024 any eq 22
Router(config-ext-nacl)# remark ping
Router(config-ext-nacl)# permit icmp any any echo
Router(config-ext-nacl)# permit icmp any any echo-reply
Router(config-ext-nacl)# permit tcp any any gt 1024

DEBUG:netmiko:_read_channel_expect read_data: Router(config-ext-nacl)# permit udp any any gt 1024
Router(config-ext-nacl)# deny   ip any any log-input
Router(config-ext-nacl)# exit
Router(config)#!
Router(config)#crypto isakmp policy 10
Router(config-isakmp)# encr aes
Router(config-isakmp)# authentication pre-share
Router(config-isakmp)# group 2
Router(config-isakmp)#crypto isakmp keepalive 90
DEBUG:netmiko:_read_channel_expect read_data:
Router(config)#!
Router(config)#crypto isakmp peer address 1.2.3.4
Router(config-isakmp-peer)# set aggressive-mode password test123
Router(config-isakmp-peer)# set aggressive-mode client-endpoint ipv4-address 10.99.99.0
Router(config-isakmp-peer)#!
Router(config-isakmp-peer)#ip access-list
DEBUG:netmiko:_read_channel_expect read_data:  extended vpn
Router(config-ext-nacl)# permit ip 10.99.99.0 0.0.0.255 172.16.99.0 0.0.0.255
Router(config-ext-nacl)# permit ip 10.98.99.0 0.0.0.127 172.16.99.0 0.0.0.255
Router(config-ext-nacl)#!
Router(config-ext-nacl)#crypto ipsec transform-set ESP-AES-SHA esp-
DEBUG:netmiko:_read_channel_expect read_data: aes esp-sha-hmac
Router(cfg-crypto-trans)# mode tunnel
Router(cfg-crypto-trans)#!
Router(cfg-crypto-trans)#crypto map ipsec 10 ipsec-isakmp
Router(config-crypto-map)# set peer 1.2.3.4
Router(config-crypto-map)# set transform-set ESP-AES-SHA
Router(config-crypto-map)# set pfs group2
Router(config-crypto-map)# match address vpn
Router(config-crypto-map)#
DEBUG:netmiko:_read_channel_expect read_data: exit
Router(config)#
```

The cli errors can safely be ignored -- it is the result of the same template applied several times...

Thanks!

**Comment by martininka** [comment]
> You can also in `send_config_set` set the following argument to False:
> 
> ```
>       cmd_verify=True,
> ```
> 
> This will turn of that command verification and fallback to the old Netmiko 2.X behavior.
> 
> Of course, I am pretty interested to see why it is failing so it would be very helpful to look at your session_log and see why the command verification is not working :-)

hey, it works with cmd_verify=False :)

About the script flow: 
- open text file containing config template
- parse it with string.Template and fill in some variables
- pass the result to send_config_set

Maybe the problem is somewhere there?

**Comment by ktbyers** [comment]
@martininka Yes, it shouldn't be a single string (unless it is a single command). It should be a list of commands--so you should do a .splitlines() call on it (prior to sending it to send_config_set() i.e. convert it to a list of commands)

**Comment by martininka** [comment]
> @martininka Yes, it shouldn't be a single string (unless it is a single command). It should be a list of commands--so you should do a .splitlines() call on it (prior to sending it to send_config_set() i.e. convert it to a list of commands)

Thank you very much for your help! I'm pretty new to Python, I used Perl for a long time.

**Comment by azeryassine** [comment]
i have the problem in my script python because I send command in my file text.txt in my router cisco but I don't have the possibility of exit in command-line. exemple:

code python:

device.config_mode()
device.send_config_from_file(config_file="text.txt")
device.exit_config_mode()
text.txt

interface loopback 10.10.10.10
  description LO
  ip adress 10.10.10.10 255.255.255.0
exit
  vrf definition VRF 10
  description vrf
  ...
the exit command does not work.

the connection is closed.

**Comment by ktbyers** [comment]
@azeryassine You shouldn't do either:

```
device.config_mode()
```

Or

```
device.exit_config_mode()
```

Netmiko will do that automatically.

**Comment by ktbyers** [comment]
Let me know what happens when you eliminate that.

**Comment by azeryassine** [comment]
I still have the same problem my connection closes but it is because of EXIT.
but I need it to exit for example from config-line

**Comment by ktbyers** [comment]
@azeryassine Okay, open a new issue, your Python code, and your exception stack trace. The inner `exit` shouldn't cause an issue from Netmiko's perspective.

**Comment by ignatievia** [comment]
Hi, @ktbyers. Have the same problem with Mikrotik when sending a RouterOS script to the router. The script itself is incapsulated in one command as an argument so it's a really long string. Following your advice set cmd_verify=False and got this working.
Appreciate your work.
