### ISSUE TITLE
Banner and Cisco IOS fail when cmd_verify=True

### ISSUE THREAD

**Issue by chriseizus** [ktbyers/netmiko#1531]
I'm having following code to push cisco ios banner to the device.
After upgrade to 3.0, it no longer works. It works fine when switch back to 2.4.2

Exception: <class 'netmiko.ssh_exception.NetmikoTimeoutException'>: Timed-out reading channel, data not available.

I guess it is due to the new expect mechanism in send_config_set since when configuring multi line banner, the device_name# won't be returned yet until the last line of the banner applied.

Here is the code, please advise any solution.

ios_device = {
    'device_type': 'cisco_ios',
    'ip': "192.168.0.1",
    'username': "admin",
    'password': "cisco",
    'secret': "cisco"
}

net_connect = None

net_connect = ConnectHandler(**ios_device)

banner = [
    "banner login ^",
    "This is login banner",
    "^"
]

net_connect.enable()    # I'm using priviledge level 15 so enable is not really an issue
net_connect.send_config_set(banner)

**Comment by ktbyers** [comment]
@chriseizus 

Hmmm, I don't see why Netmiko would fail here on the face of it. 

It isn't actually verifying/checking for the trailing prompt, but instead is verifying each command (you sent) is echoed on the device.

I tested it using Netmiko 3.X and didn't see an issue:

```
$ python netmiko_test.py 
config term
Enter configuration commands, one per line.  End with CNTL/Z.
cisco1(config)#banner login ^
Enter TEXT message.  End with the character '^'.
This is login banner
^
cisco1(config)#end
cisco1#
```

That was using the following code:
```python
net_connect = ConnectHandler(
    host=host, username=username, password=password, device_type="cisco_ios_ssh"
)

banner = [
"banner login ^",
"This is login banner",
"^"
]

output = net_connect.send_config_set(banner)
print(output)
net_connect.disconnect()
```

**Comment by ktbyers** [comment]
Can you post the exception message that you receive?

**Comment by ktbyers** [comment]
You can ignore my earlier comment, it was incorrect and I deleted it.

Let me re-test it.

**Comment by ktbyers** [comment]
Okay, I reproduced the issue.

You can disable the cmd_verify behavior by doing:

```
net_connect.send_config_set(banner, cmd_verify=False)
```

I will need to figure out what to do here...

**Comment by chriseizus** [comment]
Nice for the prompt test. Will stay tuned for the resolving. Thanks

**Comment by ktbyers** [comment]
I wouldn't stay tuned as it might take me a while to fix. I.E. use the fix stated above.

Leave this issue open, however, so I can track the issue you referenced.

**Comment by chriseizus** [comment]
Ok, any caveat of using cmd verify false? Still a reliable push? Or I should be only dealing with banner using this?

**Comment by ktbyers** [comment]
It basically just falls back to the Netmiko send_config_set mode that existed prior to Netmiko 3.X.X.

**Comment by mkorn2021** [comment]
The most evident you are having a low-speed connection between you and your device. Consider setting a pause between operations that you sent to device

**Comment by chriseizus** [comment]
> The most evident you are having a low-speed connection between you and your device. Consider setting a pause between commands that you send to device

This has been validated by ktbyers as a bug.
Just so you know, it's nothing to do with connection speed. I'm testing in my lab. the swtich is beside me.

**Comment by ktbyers** [comment]
Should be fixed here:

https://github.com/ktbyers/netmiko/pull/2558

Netmiko will auto disable cmd_verify for banner configuration commands.
