### ISSUE TITLE
Python 2 version has Python 3 syntax

### ISSUE THREAD

**Issue by errieman** [ktbyers/netmiko#1532]
I installed the Python 2.7 version using pip2 install netmiko. When I try to import, the following happens:

```
File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax
```

**Comment by ktbyers** [comment]
Netmiko no longer supports PY27.

For PY27, you would need to `pip install netmiko==2.4.2`
