### ISSUE TITLE
new to programming and my code is failing, any direction appreciated

### ISSUE THREAD

**Issue by deggle1** [ktbyers/netmiko#1535]
```python
from netmiko import ConnectHandler
from getpass import getpass
import sys

user = input("Enter your remote account: ")
p = getpass()
vlan_id = input("Enter your the VLAN ID: ")

with open('nexus_devices.txt') as IP_Switches:
    for IP in IP_Switches:
        home = {'username': user,
                'password' : p,
                 'device_type': 'cisco_ios',
                 'host': IP,
                'secret': p,
                
                }
        
        Device_list = [ home ]
        for switches in Device_list:
            net_connect = ConnectHandler(**switches)
        print ('connecting to the ' + IP)
        net_connect.find_prompt()

        print ('Succesfully connected to ' + IP)
        print ('Entering the show vlan command')
        command = 'show run vlan ' + vlan_id

        output = net_connect.send_command (command)
        print(output)
```

**Comment by ktbyers** [comment]
What error/issue do you see when you run your code?

**Comment by deggle1** [comment]
it basically does not recognise the last lines. keeps giving me an error after logging in successfully
Enter your remote account: xxxx
Password: 
Enter your the VLAN ID: 2
connecting to the 192.168.1.110
Succesfully connected to 192.168.1.110
Entering the show vlan command
^
% Invalid input detected at '^' marker.

        command = 'show run vlan ' + vlan_id
        output = net_connect.send_command (command)

**Comment by ktbyers** [comment]
@deggle1 The `%Invalid input detected at marker` is coming back from the network device. 

My guess is that you are not in enable mode so you would need to add:

```
net_connect.enable()
```

Before you execute the `show run vlan 2` command.

**Comment by deggle1** [comment]
thanks a lot. it worked like a charm
