### ISSUE TITLE
ansi escape code in output causing send_command to not work

### ISSUE THREAD

**Issue by wfleisher** [ktbyers/netmiko#1538]
```
def sshConnection():
    file = open('sessionLog.txt', 'w+')
    while True:
        try:
            panIP = input("Panorama IP: ")
            fwIP = input("Firewall IP: ")
            username = input("Username: ")
            password = getpass()
            panosConn = ConnectHandler(device_type = "paloalto_panos", host = panIP, username = username, password = password, session_log = 'sessionLog.txt')
            break
        except (NetMikoAuthenticationException, NetMikoTimeoutException):
            print("Authentication Failed")
            pass
    panosConn.send_command('ssh host '+username+'@'+fwIP+'',  expect_string = r'Password')
    panosConn.send_command(''+password+'', expect_string = r'>')
    panosConn.find_prompt()
    panosConn.send_command('set cli pager off')
```

> Traceback (most recent call last):
>  File "C:\pyscripts\netmiko3\lib\site-packages\paramiko\channel.py", line 699, in recv
>    out = self.in_buffer.read(nbytes, self.timeout)
>  File "C:\pyscripts\netmiko3\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
>    raise PipeTimeout()
>paramiko.buffered_pipe.PipeTimeout
>
>    During handling of the above exception, another exception occurred:
>
>    Traceback (most recent call last):
>  File "C:\pyscripts\netmiko3\lib\site-packages\netmiko\base_connection.py", line 541, in _read_channel_expect
>    new_data = self.remote_conn.recv(MAX_BUFFER)
>  File "C:\pyscripts\netmiko3\lib\site-packages\paramiko\channel.py", line 701, in recv
>    raise socket.timeout()
>socket.timeout
>
>   During handling of the above exception, another exception occurred:
>
>   Traceback (most recent call last):
>  File ".\pacPeople.py", line 85, in <module>
>    main()
>  File ".\pacPeople.py", line 81, in main
>    panosConn = sshConnection()
>  File ".\pacPeople.py", line 45, in sshConnection
>    panosConn.send_command('ssh host '+username+'@'+fwIP+'',  expect_string = r'Password')
>  File "C:\pyscripts\netmiko3\lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 160, in send_command
>    return super().send_command(*args, **kwargs)
>  File "C:\pyscripts\netmiko3\lib\site-packages\netmiko\base_connection.py", line 1366, in send_command
>    new_data = self.read_until_pattern(pattern=re.escape(cmd))
>  File "C:\pyscripts\netmiko3\lib\site-packages\netmiko\base_connection.py", line 618, in read_until_pattern
>    return self._read_channel_expect(*args, **kwargs)
>  File "C:\pyscripts\netmiko3\lib\site-packages\netmiko\base_connection.py", line 552, in _read_channel_expect
>    "Timed-out reading channel, data not available."
>netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Using expect_string for ssh proxy through another device no longer working in ver 3.0.0 , was previously working in 2.4.2

**Comment by ktbyers** [comment]
@wfleisher What is the intermediate device that you are connecting through--i.e. what type of device is this?

**Comment by wfleisher** [comment]
Intermediate device is a Panorama appliance. End device is a palo alto firewall.

**Comment by ktbyers** [comment]
You can just obfuscate anything in the log file that is confidential.

**Comment by wfleisher** [comment]
[test.log](https://github.com/ktbyers/netmiko/files/4124842/test.log)
Here is the log file.

**Comment by ktbyers** [comment]
Is that your obfuscation there?

```
[Kusername@Panorama-Hostname(secondary-active)> ssh host username@10 .15.12.**
```

Did you add the extra space after the `10`?

Also, is the IP fully correct here. The lines I am talking about are here (I assume that ** is your obfuscation as well)?

```
DEBUG:netmiko:_read_channel_expect read_data: ssh 
[Kusername@Panorama-Hostname(secondary-active)> ssh host 
[Kusername@Panorama-Hostname(secondary-active)> ssh host username@10 .15.12.**

```

**Comment by wfleisher** [comment]
No only replaced the last octet.

**Comment by ktbyers** [comment]
Okay, it looks like there are ANSI escape codes in the output that are messing things up:

```
In [5]: repr(line)                                                                                                                                       
Out[5]: "'\\x1b[Kusername@Panorama-Hostname(secondary-active)> ssh host username@10 \\x08.15.12.**'"
```

We'll have to figure out what to do with that.

**Comment by ktbyers** [comment]
Netmiko 2.4.2 is different than Netmiko 3.0.0 here (Netmiko 3.0.0 is trying to verify the command echo whereas Netmiko 2.4.2 didn't)...so that part is expected.

Verifying the command echo fixes a lot of other Netmiko problems.

**Comment by wfleisher** [comment]
[test.log](https://github.com/ktbyers/netmiko/files/4200858/test.log)
Submitted a pull request with a fix for this. Attached is a log run with the added code.
[Pull request](https://github.com/ktbyers/netmiko/pull/1542)

**Comment by ktbyers** [comment]
Should be fixed here:

#2223
