### ISSUE TITLE
interactive y/n confirmation prompt issue

### ISSUE THREAD

**Issue by scottharney** [ktbyers/netmiko#154]
I'm working on a Cisco MDS 95xx (nxos) device to automate SAN zoning. when you go to activate the zoneset, if the amount of change is > or < a certain size you get a confirmation prompt. I've tried ~send_command_expect()~ and a few other tricks to work around this to no avail.  Here's an example output capture
```
sharn90@ubuntu-san-automation:~/source$ ./dozones.py --hostname 10.194.253.30 --filename jdcmds1_vsphere_zones_pilot_backout.txt
config term
Enter configuration commands, one per line.  End with CNTL/Z.
LAB-MDS2(config)# zoneset name ZS_MDS1 vsan 101
LAB-MDS2(config-zoneset)# zoneset activate name ZS_MDS1 vsan 101
WARNING: New Zoneset ZS_MDS1 is significantly bigger than current active Zoneset ZS_MDS1. Do you want to continue? (y/n) [n] end
LAB-MDS2# 
DRY RUN: activate command = ['zoneset activate name ZS_MDS1 vsan 101']
```
We don't necessarily know that we're going to trigger this condition so I was hoping the expect method of matching against a string ( `WARNING: New Zoneset ZS_MDS1 is significantly bigger than current active Zoneset ZS_MDS1. Do you want to continue? (y/n) [n] ') or the prompt would do the job

Here's the relevant code snippet
```
if activate and not dry_run:
  net_connect.config_mode()
    output = net_connect.send_command_expect(zoneset_command, expect_string=expect_string)
    print output
    net_connect.exit_config_mode()
```
zoneset_command and expect_string are defined in the code

**Comment by ktbyers** [comment]
@scottharney I think you could probably do this:

<pre>
import time

if activate and not dry_run:
    net_connect.config_mode()
    output = net_connect.send_command('zoneset name ZS_MDS1 vsan 101')
    net_connect.remote_conn.sendall('zoneset activate name ZS_MDS1 vsan 101\n')
    time.sleep(1)  
    output = net_connect.remote_conn.recv(65535).decode('utf-8')       
    if 'Do you want to continue' in output:
        net_connect.remote_conn.sendall('y\n')
        output = net_connect.remote_conn.recv(65535).decode('utf-8')       
</pre>

Basically you are controlling the channel more manually here using 'sendall' and 'recv'. You could make a function out of part of the above so that you could reuse the code in different contexts.

<pre>
def handle_mds_continue(net_connect, cmd):
    net_connect.remote_conn.sendall(cmd)
    time.sleep(1)
    output = net_connect.remote_conn.recv(65535).decode('utf-8')       
    if 'Do you want to continue' in output:
        net_connect.remote_conn.sendall('y\n')
        output += net_connect.remote_conn.recv(65535).decode('utf-8')
        return output       
</pre>

You could then call:
<pre>
output = handle_mds_continue(net_connect, cmd='zoneset activate name ZS_MDS1 vsan 101\n')
</pre>

Please test the above and make sure it works in your context...

**Comment by scottharney** [comment]
I was looking at how send_command() worked figuring I'd need to take a more manual control approach when you sent this.  Works fine and I used the suggested func call methodology.

**Comment by marsteel** [comment]
expect_string= can only be used when the expected string will definitely appear.
