### ISSUE TITLE
Allow to access last output

### ISSUE THREAD

**Issue by SaschaKrug** [ktbyers/netmiko#1547]
Hi, we currently have an issue with devices, who sometimes don't generate a prompt. Has nothing to do with netmiko, but we have to handle them. Send_command_timing() is an option, but would slow everything down.

What would be great, is the option to access the last output, even after exception. Like directly storing the received output in a class attribute, which gets reset on each of the send_commands. So even if it fails, we could get access to the last output he received. This could be used to improve logs or allows us to present an output, even if no prompt gets detected.

**Comment by ktbyers** [comment]
Have you looked at the `session_log`. You can also do an in-memory session_log so I suspect this information is already present.

**Comment by SaschaKrug** [comment]
Had a look into it and yes I could use it to get the last output, but it is cumbersome. Read the buffer and parse it for the right part. Last part could get tricky if prompts are missing. It feels not really correct to use it.

On the other hand, there is already the output variable, which contains the desired result. Only problem is, that it's not reachable anymore on exception.

**Comment by ktbyers** [comment]
I am pretty sure I wouldn't do this. I think it is going to add quite a bit of complexity.
