### ISSUE TITLE
Timed-out reading channel, data not available

### ISSUE THREAD

**Issue by kaabiayman** [ktbyers/netmiko#1549]
Hi guys,

I'm using the script below to push syslog config to nexus 6001 device,

but every i execute this script i got Timed-out reading channel, data not available

and when i change logging server 10.60.25.73 5 port 5140 use-vrf default facility syslog to 

logging server 10.60.25.73 5 port 5140 use-vrf the script works.

I checked both commands that they works fine on devices.

python version :3.7 , netmiko version 3

can you help please

```python
from    multiproc.MultiprocessingMain import mainMultiProcessing
import  socket
from    netmiko.ssh_exception   import  NetMikoTimeoutException, NetMikoAuthenticationException
from    paramiko                import  SSHException
from    devices.cisco.Cisco import Cisco

def main():
    device_name_filter= "tun-core-a"
    syslog_server_ip="10.60.25.73"
    field_and_filter=("name",device_name_filter)
    mainMultiProcessing(PushSyslogConfig, syslog_server_ip, field_and_filter, db_commit=True)

def PushSyslogConfig(device, username, password,arg, mp_queue):
    identifier = device.name+":"+device.management_ip
    return_data = {}
    syslog_server_ip="10.60.25.73"
    try:
        cisco_device=Cisco(device,username, password)
        config_set=[]
        if device.os_version.strip()  in [ "ios", "iosxe"]:
            config_set=['logging facility syslog',
                        'logging host '+syslog_server_ip+' transport udp port 5140'
                        ]
        elif device.os_version.strip()== "nxos":
            print ("test")
            config_set=['**logging server 10.60.25.73 5 port 5140 use-vrf default facility syslog**',
                        'logging timestamp milliseconds'
                        ]

        if 'wan-mpls' in device.name.lower() or 'wan-gre' in device.name.lower():
            config_set.append("logging source-interface lo30")
        elif 'core' in  device.name.lower():
            config_set.append("logging source-interface Vlan255")
        output= config_set
        output=cisco_device.runConfigCommandSet(config_set)
        #print output
        return_data[identifier] = (True, output, device )
    except (NetMikoTimeoutException, NetMikoAuthenticationException, ValueError, socket.error, SSHException) as e:
        return_data[identifier] = (False, e, device )
        mp_queue.put(return_data)
        return None
    mp_queue.put(return_data)





if __name__ == '__main__':

    main()
```

**Comment by ktbyers** [comment]
Can you see if you can reproduce the issue without any multiprocessing?

Also please post the full stack trace.

**Comment by kaabiayman** [comment]
Hi @ktbyers ,

thank for your help, when I run the python with multiprocessing i got 

python mainSyslogUpdate.py 
begin
end
test
TUN-CORE-A:10.216.255.253  :  Timed-out reading channel, data not available. 


$
$
$
$
$
$
$
$
$
$
                        END of a part

$
$
$
$
$
$
$
$
$
$

so no exception but command not applied but when i run it without multiprocessing everything works fine, is the issue coming from netmiko when communicate with multiprocessing or the root cause is multiprocessing ?


Thanks

**Comment by ktbyers** [comment]
So you are saying everything works fine without multiprocessing. Is that correct?

**Comment by kaabiayman** [comment]
yes that's correct

**Comment by ktbyers** [comment]
My guess would be you have an error in your multiprocessing code. Also sometimes you can run into issues with TACACS+/AAA and having a bunching of things trying to access network devices simultaneously.

I would probably look to a solution like Nornir to handle the concurrency for you as doing this yourself can get a bit hard.
