### ISSUE TITLE
Failed to enter configuration mode - slow device?

### ISSUE THREAD

**Issue by lamiskin** [ktbyers/netmiko#155]
Hi,

I have one device that seems to take slightly longer to enter configuration mode.

Throws the following exception:
```
    net_connect.config_mode()
  File "/usr/lib/python2.6/site-packages/netmiko/ssh_connection.py", line 49, in config_mode
    return super(SSHConnection, self).config_mode(config_command=config_command)
  File "/usr/lib/python2.6/site-packages/netmiko/base_connection.py", line 438, in config_mode
    raise ValueError("Failed to enter configuration mode")
ValueError: Failed to enter configuration mode
```

Switch type is cisco_ios:
```
Switch Ports Model              SW Version            SW Image
------ ----- -----              ----------            ----------
*    1 28    WS-C3750G-24PS     15.0(2)SE4            C3750-IPSERVICESK9-M
```

Adding a few seconds sleep in the check_config_mode solves the issue for me. It seems netmiko is just checking too quickly for this particular device.
```python
    def check_config_mode(self, check_string=''):
        '''
        Checks if the device is in configuration mode or not

        Returns a boolean
        '''
        time.sleep(3)
        output = self.send_command('\n', strip_prompt=False, strip_command=False)
        if check_string in output:
            return True
        else:
            return False
```

I am not suggesting just sleeping for a constant time as a solution, rather is it possible to use a delay_factor like other methods to achieve the same thing? Or even just re-checking after a few seconds, if it fails once?

**Comment by ktbyers** [comment]
@lamiskin Yes, we should probably put a little loop here so that it tries this more than once (with some amount of sleep after the first time).

**Comment by ktbyers** [comment]
@lamiskin Note, this adds a small delay here.

I don't want to add more delay since there is a trade-off of delay during normal operation and handling really slow devices.

You can also add the global_delay_factor argument during object creation to handle slow devices.

Make global_delay_factor be bigger than .5. This will add additional delays to operations on the device.
