### ISSUE TITLE
Variable issue when executing send_commandwith variable  and a pipe using netmiko API 

### ISSUE THREAD

**Issue by jrleriche** [ktbyers/netmiko#1555]
"sh int vlan" +vlan_id " | i Internet address"
+vlan_id being a variable picked from a list in a loop 
I always get an error when executing the following  command 
 output = net_connect.send_command("sh int vlan" +vlan_id " | i Internet address") 

Can you please help or tell me what is wrong with my command.

I will appreciate your great help

**Comment by ktbyers** [comment]
Did you try to test this in the Python REPL?

```python
vlan_id = 200
"sh int vlan" +vlan_id " | i Internet address"
```

Python isn't going to like that (i.e. you are not constructing a valid string).

**Comment by jrleriche** [comment]
How can i correct that .?
Excuse my  error . Thanks for your help

**Comment by jrleriche** [comment]
when i tried the following I had an error from the cisco device

        cmd = "sh int vlan" +vlan_id  + "| i Internet address"
        output = net_connect.send_command(cmd)

I get the following error                           ^
% Invalid input detected at '^' marker.

In that case it appears to be ok on python  but when it is executed  on the
cisco shell i get the error . can you please help in that . Thanks in
advance

**Comment by ktbyers** [comment]
Have you tried printing out `cmd` to see what it is (in Python)

This `% Invalid input detected at '^' marker.` is the network device telling you the command is invalid.

**Comment by ktbyers** [comment]
This doesn't look like a Netmiko issue...so I am going to close this.
