### ISSUE TITLE
redispatch using for loop to connect list of devices

### ISSUE THREAD

**Issue by uauyelbe** [ktbyers/netmiko#1559]
Hi,

I try to connect to list of devices using redispatch. At first I try to connect to jumpserver and then to to cisco device. It works fine if there is only one cisco device. But when I try to use it in for loop I cannot to connect to second device. My "ssh_connect" variable stores session from cisco device, and not jumpserver. And it tries to connect to second device directly from the first cisco device.
So how can I exit from cisco device and open new session from jumpserver?

I tried to store my jumpserver session in new variable and reassign it in for loop. But it didn't work))

Thank you in advance!

Below is my code:

from netmiko import ConnectHandler
from netmiko import redispatch
import time
from getpass import getpass
import yaml

pwd = getpass()
ipaddr = "10.10.10.1"

ssh_connect = ConnectHandler(
    device_type = "terminal_server",
    ip = ipaddr,
    username = "username",
    password = pwd,
    global_delay_factor = 2,
    session_log = "output.txt"
)

ssh_connect.write_channel("\n")
time.sleep(1)
ssh_connect.write_channel("\n")
time.sleep(1)
output1 = ssh_connect.read_channel()
print(output1)

with open("devices.yaml") as dev:
    f = yaml.load(dev, Loader=yaml.FullLoader)

    #ssh_connect.find_prompt()

    for hostname, ipaddr in f.items():
        ssh_connect.write_channel("ssh {}\r\n".format(ipaddr))

        time.sleep(1)

        print("trying to connect")
        time.sleep(2)
        #print(ssh_connect.find_prompt())
        ssh_connect.write_channel(ssh_connect.password + "\r\n")
        redispatch(ssh_connect, device_type='cisco_ios')
        print("connected")

        with open("result_{}.txt".format(hostname), "a") as res:
            out = ssh_connect.send_command("sh ip sla summary")
            res.write(out)
            print(str(ipaddr) + " done")

**Comment by ktbyers** [comment]
@uauyelbe You would need to write a function or some other code that each time handled the `exit` from the end cisco device and verified you were back at the jump server.

Then re-connect to new end cisco device and re-execute `redispatch` again.

It is possible you need to also `redispatch` back to terminal_server class each time you get back to the terminal server.

**Comment by ktbyers** [comment]
Nothing to do here for Netmiko...so closing.
