### ISSUE TITLE
Palo Alto enable "set cli scripting-mode on" by default in session_preparation

### ISSUE THREAD

**Issue by kirillmuravyev** [ktbyers/netmiko#1562]
Hello!
I am new to Python scripting with netmiko and Palo Alto. Great module BTW!!
I need to bulk upload of 4k+ rows to PAlo Alto and below is what I noticed.
I have noticed the below thing when using netmiko with Palo Alto with send_config_set command

```python
connect = PaloAltoPanosSSH(device_type='paloalto_panos', 
                 host=host, username=user, password=secret, port=port, 
                 session_log='log.txt')
connect.config_mode()
output = connect.send_config_set(
    config_commands=command_list[n-20:n], 
    exit_config_mode=False, 
    cmd_verify=False, 
    enter_config_mode=False, 
    strip_prompt=True, 
    strip_command=True
)
```

The output in log showed like this:
```
username@Panorama> configure
Entering configuration mode
[edit]                                                                          
username@Panorama# 
[edit]                                                                          
muravkir@Panorama# set 
[Kusername@Panorama# set device-group 
[Kusername@Panorama# set device-group "Local 
[Kusername@Panorama# set device-group "Local Internet 
[Kusername@Panorama# set device-group "Local Internet Breakout" 
[Kusername@Panorama# set device-group "Local Internet Breakout" address 
[Kusername@Panorama# set device-group "Local Internet Breakout" address test 
[Kmuravkir@Panorama# set device-group "Local Internet Breakout" address test ip-ne tmask 
[K[A[username@Panorama# set device-group "Local Internet Breakout" address test ip-ne 
tmask 255.255.255.255

[edit]        
```

Sometimes it cause issues with creating rogue device-groups.
I am doing bulk upload of about 4k+ rows pushing by 20 lines through python.
Could it be fixed somehow? Looks like Palo Alto aceepts 10 commands instead of a single one       `

**Comment by ktbyers** [comment]
This is in the netmiko log (i.e. you have Netmiko logging enabled)?

The above just looks like normal ANSI escape codes i.e. Palo Alto is adding them to make it more human readable. This will get displayed if looking at the Netmiko log.

So your actual issue is the below--correct?

`Sometimes it cause issues with creating rogue device-groups.`

I suspect that is caused by something else? Can you actually show me the netmiko session_log?

Which you can configure in ConnectHandler by adding the `session_log="output.txt"` argument?

Or do you get an exception?

**Comment by Kaboun** [comment]
Hi Kirk!
Thanks for the reply!
Actually that output in the first message is from session_log.
I did find the similar issue [#1294](https://github.com/ktbyers/netmiko/issues/1294)
And after adding following to PaloAltoPanosBase session_preparation:
`self.disable_paging(command="set cli scripting-mode on")`

I can see now different in the session log and it works much better!

```
username@Panorama> 
username@Panorama> set 
[Kusername@Panorama> set cli 
[Kusername@Panorama> set cli pager 
[Kusername@Panorama> set cli pager off
username@Panorama> set 
[Kusername@Panorama> set cli 
[Kusername@Panorama> set cli scripting-mode 
[Kusername@Panorama> set cli scripting-mode on
username@Panorama> 
username@Panorama> configure
Entering configuration mode
[edit]                                                                          
username@Panorama# 
[edit]                                                                          
username@Panorama# set device-group "Local Internet Breakout" address test ip-netmask 255.255.255.255

[edit]                                                                          
username@Panorama# set device-group "Local Internet Breakout" address test description 1.2.3.4
set device-group "Local Internet Breakout" address "AC Nielson" ip-netmask 138.108.25.17
set device-group "Local Internet Breakout" address "AC Nielson" description "ITSA ZZZZZZZ - 2014-01-28"
set device-group "Local Internet Breakout" address JDA description "ITSA ZZZZZZZZ - 2014-01-28"
set device-group "Local Internet Breakout" address JDA ip-range 64.26.250.52-64.26.250.53

[edit]                                                                          
username@Panorama# 
set device-group "Local Internet Breakout" address is.co.za ip-netmask 196.37.153.250
set device-group "Local Internet Breakout" address "TANGRAM UKRAINE LTD" ip-netmask 91.206.226.13
set device-group "Local Internet Breakout" address GXS.COM ip-netmask 204.90.130.26
[edit]
```

**Comment by Kaboun** [comment]
I have one more question about delay_factor. Can you explain how it works?
I am asking because when using send_config_from_file it looks like netmiko tries to send all the config at once to device thus causing problems with config proper setup.

**Comment by ktbyers** [comment]
@Kaboun Do you want to do a pull request on this?

Is this a new behavior on Palo Alto? I don't think we have ran into this issue with Palo Alto before (and historically we haven't had to strip ANSI escape codes).

So we should probably do a PR to enable that "set cli scripting-mode on".

And we also should add to that PR enabling the stripping of ANSI escape codes in the output.

**Comment by ktbyers** [comment]
@Kaboun I talk about delay_factor a lot here:

https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html

Do you still run into your issues with send_config_from_file when you have "set cli scripting-mode on" configured. From reading Palo-Alto docs that sounds like it might fix the problem.

I think the problem probably is that the Palo Alto can't keep up with how fast we are sending the config commands and then starts buffering them (and eventually dropping them). That would be my guess anyways.

Also related to this--what version of Netmiko are you using?

**Comment by Kaboun** [comment]
@ktbyers Thanks a lot!.
No, I am not having problem right now with "set cli scripting-mode on" command.
All is working very good!
