### ISSUE TITLE
send command should wait for prompt

### ISSUE THREAD

**Issue by eboman** [ktbyers/netmiko#157]
Currently i'm parsing outputs from cisco devices, i noticed when using show run commands the device needs to parse this in memory and thus taking some time, it seems the stream is cut before the data is send. 

Is there a way by using the find_prompt function to wait for a prompt before closing the stream?

**Comment by eboman** [comment]
as a workaround i use show start to circumvent this

**Comment by ktbyers** [comment]
@eboman What type of device was this?

There is a send_command_expect method where you can wait for a terminating prompt. You can also modify the delay_factor either in the send_command() or the global delay factor when creating the connection object. The delay_factor will increase how long it sleeps waiting for data.

**Comment by eboman** [comment]
in this case it is a 4948 but i suspect a 6500 will be even worse. Do you have an example command for the expect ?

**Comment by ktbyers** [comment]
send_command_expect("show run")

By default this will try to read all of the data until it encounters the router prompt in the output.

**Comment by ktbyers** [comment]
@eboman Did this fix work?

**Comment by eboman** [comment]
Hi, yes that seems to do the trick, is this documented somewhere ?

**Comment by jeffsilverm** [comment]
Yes, it is, but you have to somewhat read between the lines to get there.  See http://netmiko.readthedocs.io/en/latest/classes/base_connection.html and look at the send_command method.

Also, take a look at [Netmiko Documentation Release 1.0](https://media.readthedocs.org/pdf/netmiko/latest/netmiko.pdf) by Kirk Byers.

I am contemplating writing more documentation on netmiko, which I think is pretty cool, and I think would be more widely used if it was better understood.
