### ISSUE TITLE
"show run" on multiple routers using multiprocessing

### ISSUE THREAD

**Issue by eagleotstar** [ktbyers/netmiko#1570]
```python
from netmiko import ConnectHandler
import time
import multiprocessing as mp
from netmiko import Netmiko
from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import NetMikoAuthenticationException

def connect_and_run(device, cmd ='show run'):
    print('Connecting to device : ', device['ip'])
    connection = ConnectHandler(**device)

    print('Executing command: ', cmd)
    output = connection.send_command(cmd)
    print('#' * 50)
    prompt = connection.find_prompt()
    hostname = prompt[:-1]

    import datetime

    now = datetime.datetime.now()
    today = str(now.year) + '-' + str(now.month) + '-' + str(now.day)
    file = today + '-' + hostname + '.txt'

    with open(file, 'w') as backup:
        backup.write(output)
        print('Backup of ' + hostname + ' completed successfully')
        print('#' * 50)

    connection.disconnect()

if __name__ == '__main__':
    with open('iwan_backup.txt') as f:
        devices = f.read().splitlines()

    device_list = list()

    for ip in devices:
        try:
            cisco_device = {
            'device_type': 'cisco_ios',
            'ip': ip,
            'username': '***',
            'password': '**',
            'port': 22,
            'verbose': True
        }
            device_list.append(cisco_device)

            processes = list()
            for device in device_list:
                processes.append(mp.Process(target=connect_and_run, args=(device, 'sh run')))

            for p in processes:
                p.start()

            for p in processes:
                p.join()

        except:
            #print("SSH connection could not be established to " + ip)
            #print("#" * 50)
            with open('failSSHconn_backup.txt', 'a') as f:
                f.write(ip + '\n')
```

**Comment by eagleotstar** [comment]
I am running in to a problem when executing the above code.....the code runs fine for the devices which are reachable..but fails to run when unreachable.......I am using multiprocessing in this case....not sure where I am going wrong on this.....

**Comment by ktbyers** [comment]
What does `fails to run when unreachable` mean? Do you get some error, do you get some other side-effect?

**Comment by eagleotstar** [comment]
if the router is unreachable ...it should execute the below....but it doesn't
except:
            #print("SSH connection could not be established to " + ip)
            #print("#" * 50)
            with open('failSSHconn_backup.txt', 'a') as f:
                f.write(ip + '\n')

**Comment by ktbyers** [comment]
That is in the main process not the child process.

You won't get an exception in the main process given the situation you described. You would get an exception in the child process so you would need to move your try/except there.

**Comment by eagleotstar** [comment]
thanks , i will try that

**Comment by eagleotstar** [comment]
Here is where I messed up.... instead of using device['ip] , I just used directly ip   

 except:
        #print("SSH connection could not be established to " + device['ip'])
        #print("#" * 50)
        with open('failSSHconn_backup.txt', 'a') as f:
            f.write(device['ip'] + '\n')
        # print("Unable to connect to " + device['ip'])
