### ISSUE TITLE
Error connecting to switch allied telesis

### ISSUE THREAD

**Issue by vjuagar** [ktbyers/netmiko#1572]
Hi, I am developing an application to connect to an allied telesis switch and it gives me this error:

DEBUG:paramiko.transport:starting thread (client mode): 0x57b2eac0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.8.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_3.4p1.RL
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_3.4p1.RL)
DEBUG:paramiko.transport:kex follows? False
kex algos: ['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1']
server key: ['ssh-rsa']
client encrypt: ['aes128-cbc', '3des-cbc', 'arcfour', 'aes192-cbc', 'aes256-cbc']
server encrypt: ['aes128-cbc', '3des-cbc', 'arcfour', 'aes192-cbc', 'aes256-cbc']
client mac: ['hmac-sha1', 'hmac-md5']
server mac: ['hmac-sha1', 'hmac-md5']
client lang: b''
server lang: b''
client compress: ['none']
server compress: ['none']
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2049 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.63.152.128: b'221a3faed2f4e55f7801da1f7a03a16a'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (none) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: El_uso_de_este_dispositivo_esta_restringido_a_los_usuarios_expresamente_autorizados.Toda_actividad_en_este_equipo_esta_siendo_monitirizada.

User Name:
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

User Name:
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is User Name:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

User Name:
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:exit_config_mode: 
DEBUG:netmiko:write_channel: b'exit\n'
DEBUG:paramiko.transport:EOF in transport thread
Traceback (most recent call last):
  File "//Mac/Home/Desktop/netmiko conexion buena.py", line 27, in <module>
    net_connect = ConnectHandler(**device)
  File "C:\Python38\lib\site-packages\netmiko\ssh_dispatcher.py", line 250, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python38\lib\site-packages\netmiko\base_connection.py", line 312, in __init__
    self._open()
  File "C:\Python38\lib\site-packages\netmiko\base_connection.py", line 318, in _open
    self._try_session_preparation()
  File "C:\Python38\lib\site-packages\netmiko\base_connection.py", line 741, in _try_session_preparation
    self.session_preparation()
  File "C:\Python38\lib\site-packages\netmiko\base_connection.py", line 761, in session_preparation
    self.set_base_prompt()
  File "C:\Python38\lib\site-packages\netmiko\base_connection.py", line 1065, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: 'User Name:'
>>> 

Greetings and I hope someone can help me.

**Comment by vjuagar** [comment]
Hi, I have been doing tests and it seems that it does connect, but it does not pass the username and password.

I leave my code to see if someone can help me.

`from netmiko import ConnectHandler
import paramiko
import sys
import logging
logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)

paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
username = 'manager'
password = 'password'


ip = 'ip'


def session_preparation(self):
    self.set_base_prompt()
    self.disable_paging(command="screen-length 0 temporary")
    


device = { 'device_type': 'alliedtelesis_awplus', 'host': ip, 'username': username, 'password': password, 'global_delay_factor': 4,}
net_connect = ConnectHandler(**device)

output = net_connect.send_command("show run")

print (output)`

**Comment by ktbyers** [comment]
So you are making your own driver I assume?

`device_type = alliedtelesis_awplus`

It looks like that device does not have a standard SSH authentication which should be handled transparently by Paramiko.

This looks non-standard:

```
User Name:
```

You will probably have to do something similar to what was done here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/dell/dell_powerconnect.py#L79-L103

**Comment by vjuagar** [comment]
Hello Kirk , the connection with what you indicated to me worked, thanks.
