### ISSUE TITLE
function to test device alive

### ISSUE THREAD

**Issue by TanY0Y0** [ktbyers/netmiko#1574]
is there any fast inside function to test if device alive before connect to it in netmiko?
such as timeout in 5s when trying to connect device, i tried to use 'timout= 5', but it also affect time of interacting after connected, i just want test connectability at first time

**Comment by ktbyers** [comment]
Probably `auth_timeout` argument is the best one.

Let me know if that works for your case.

**Comment by ktbyers** [comment]
I am going to close this. Let me know if there is still an outstanding issue here.
