### ISSUE TITLE
Is there a build in functionality to view realtime output?

### ISSUE THREAD

**Issue by kerwbstomp** [ktbyers/netmiko#1576]
I can't seem to get write_channel, and read_channel to display realtime output for things like traceroute or ping.  Is there something I am missing in order to view these? Here is sample paramiko SSH code that allows that. 

stdin, stdout, stderr = ssh.exec_command('command')
for line in stdout:
    print line.rstrip()

I do not see something that would allow me to do the same in Netmiko.

**Comment by paulhenry10** [comment]
Hi,

You can try:

output = net_connect.send_command('command')
print(output)

**Comment by ktbyers** [comment]
General pattern in Netmiko would be to use the `write_channel` and `read_channel()` methods in conjunction with some loop (and probably a small sleep as your network device won't respond that quickly anyways).
