### ISSUE TITLE
Script timeout error - NetmikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by Andressg07** [ktbyers/netmiko#1577]
Hello all,

I'm running an script to configure ACLs on huawei devices. With short rules like these, all works fine:

acl basic 2002
description ACL
rule 5 permit source 1.1.1.1 0
rule 5 permit source 2.2.2.2 0

But, when I need to configure the whole wildcard Im getting this error:

_netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available._

From the debug file, I saw this:

[mintrab_bog100_piso10-acl-ipv4-basic-2001]
DEBUG:netmiko:write_channel: b' rule 5 permit source 172.20.10.0 0.0.0.255\n'
DEBUG:netmiko:Pattern is: rule\ 5\ permit\ source\ 172\.20\.10\.0\ 0\.0\.0\.255
DEBUG:netmiko:_read_channel_expect read_data:  rule 5 permit source 
DEBUG:netmiko:_read_channel_expect read_data: 172.20.10.0 0.0

.0.255

[mintrab_bog100_piso10-acl-ipv4-basic-2001]
DEBUG:paramiko.transport:EOF in transport thread

I think the problem is related to the long of the command, but I dont know how to address it. The rule is configured but the process abort and not continue with the othe rules.

********* This is the configuration I send ***********
acl basic 2001
description ACL VTY
rule 5 permit source 172.20.10.0 0.0.0.255
rule 10 permit source 172.20.22.50 0
rule 15 permit source 10.11.0.0 0.0.0.255

********* This is the configuration applied on device *******

Basic IPv4 ACL 2001, 1 rule,
ACL VTY
ACL's step is 5, start ID is 0
 rule 5 permit source 172.20.10.0 0.0.0.255

Thanks for your ideas. I tried increasing the global_delay_factor to 4 without success.

**Comment by ktbyers** [comment]
I assume you are using Netmiko 3.0.0?

Have you tried adding the `cmd_verify=False` argument to send_config_set().

**Comment by Andressg07** [comment]
Thanks, its working now.
