### ISSUE TITLE
Create a Security Policy

### ISSUE THREAD

**Issue by lykinsbd** [ktbyers/netmiko#1583]
We should create a [Security Policy](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) for Netmiko.  This is one of the newer features of Github, with the ability to have the policy defined in the `SECURITY.md` file in the root path.

This is primarily used for outlining to the user community your supported code trains (for vulnerability patching) and for defining how to report vulnerabilities.  It can also tie in to using [Github Security Advisories](https://help.github.com/en/github/managing-security-vulnerabilities/about-github-security-advisories), but using these for Netmiko can be discussed elsewhere in another issue.

Even if it is a very basic policy, i.e. "Email john_doe@email.address with reports", it helps set and shape community interactions with this library/product from a security and vulnerability perspective.

**Comment by ktbyers** [comment]
Close this as no one is working on it.
