### ISSUE TITLE
OSError: Search pattern never detected in send_command_expect:

### ISSUE THREAD

**Issue by paulhenry10** [ktbyers/netmiko#1584]
Hi everyone,

Im having an issue when trying to access my cisco switch specifically 4507 model.

Here's the error:
Traceback (most recent call last):
  File "everyday_backup.py", line 36, in <module>
    output = net_connect.send_command(command_string=command, strip_prompt=False, strip_command=False)
  File "C:\Users\pmcagayan\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1407, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: P3\.CAFOLC4507\-20\.222\#

There is no problem with other Cisco switch model like 2960 series.

Python version: 3.7.6
Netmiko version: 3.0.0

**Comment by ktbyers** [comment]
Can you enable Netmiko logging and include the log file so I can see more details on what is occurring:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by paulhenry10** [comment]
Hi sir Kirk,

Thank you for your quick response. I enable Netmiko logging and look at the log file generated before replying here. It turns out that our last activity which is to upgrade switch firmware is the culprit.

The first command i'm sending is "wr" - write memory to save configuration. It turns out that in cisco 4500 series, it needs user interaction when it is the first time to save config after firmware upgrade.

Thank you sir and more power to you. :)
[test.log](https://github.com/ktbyers/netmiko/files/4228745/test.log)
