### ISSUE TITLE
Juniper timeout exception

### ISSUE THREAD

**Issue by mbouwmee** [ktbyers/netmiko#1585]
Hi,
When sending a "wrong" commands to a juniper device I receive a timeout exception.
When I configure this command manually, the command is not accepted, and the response from the device is ok.
In the script I search in the output for "^" character knowing a wrong command is send.
But I cannot explain the timeout I receive
After sending the wrong command the next command is not send to the device.

(wrong command with an typo)
set policy-options policy-statement LAS003-IN term 1 then xxlocal-preference 200
(next command to send)
delete policy-options policy-statement LAS003-OUT term 1 then as-path-prepend

Below You can find the code I am using and debug information.

Need advise what to do?

Best regards,
Martien

        ....
		
        if device_data['device_type'] == 'juniper_junos':
            result_list[0] += net_connect.send_config_set(command_list, exit_config_mode=False)
            result_list[0] += net_connect.commit(and_quit=True)**
        elif device_data['device_type'] == 'cisco_xr':
            result_list[0] += net_connect.send_config_set(command_list)
            result_list[0] += net_connect.commit()
        else:
            result_list[0] += net_connect.send_config_set(command_list)
            result_list[0] += net_connect.save_config()
        net_connect.disconnect()

    except AuthenticationException:
        result_list[1] = 'Authentication failed.'

    except NetMikoTimeoutException:
        result_list[1] = 'Timeout error occured.'

    if '^' in result_list[0]:
        ........

martien@atstnlccr1#
DEBUG:netmiko:write_channel: b'delete policy-options policy-statement LAS002-OUT term 1 then as-path-prepend\n'
DEBUG:netmiko:Pattern is: delete\ policy\-options\ policy\-statement\ LAS002\-OUT\ term\ 1\ then\ as\-path\-prepend
DEBUG:netmiko:_read_channel_expect read_data: de
DEBUG:netmiko:_read_channel_expect read_data: lete policy-options policy-statement LAS002-OUT term 1 then as-path-prepend

[edit]
martien@atstnlccr1#
DEBUG:netmiko:Pattern found: delete\ policy\-options\ policy\-statement\ LAS002\-OUT\ term\ 1\ then\ as\-path\-prepend delete policy-options policy-statement LAS002-OUT term 1 then as-path-prepend

[edit]
martien@atstnlccr1#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: martien\@atstnlccr1
DEBUG:netmiko:_read_channel_expect read_data:

DEBUG:netmiko:_read_channel_expect read_data:
[edit]
martien@atstnlccr1#
DEBUG:netmiko:Pattern found: martien\@atstnlccr1

[edit]
martien@atstnlccr1#
DEBUG:netmiko:write_channel: b'set policy-options policy-statement LAS003-IN term 1 then xxlocal-preference 200\n'
DEBUG:netmiko:Pattern is: set\ policy\-options\ policy\-statement\ LAS003\-IN\ term\ 1\ then\ xxlocal\-preference\ 200
DEBUG:netmiko:_read_channel_expect read_data: se
DEBUG:netmiko:_read_channel_expect read_data: t policy-options policy-statement LAS003-IN term 1 then xxlocal-preference
                                                                             ^
syntax error.
martien@atstnlccr1# set policy-options policy-statement LAS003-IN term 1 then xxlocal-preference200
                                                                             ^
syntax error.

[edit]
martien@atstnlccr1#

**Comment by mbouwmee** [comment]
Hi,
I solved this by using : cmd_verify=False argument in send_config_set()
But I am wondering when to use this or when do not use it.

Martien

**Comment by ktbyers** [comment]
@mbouwmee Okay, it is because Juniper's CLI distorts the command echo for invalid commands:

```
if I send:

set policy-options foo hello world

Juniper will actually echo:

pyclass@srx1> set policy-options
                  ^
syntax error, expecting <command>.
pyclass@srx1> set policy-optionsfoo
                  ^
syntax error, expecting <command>.
pyclass@srx1> set policy-optionsfoohello
                  ^
syntax error, expecting <command>.
pyclass@srx1> set policy-optionsfoohelloworld

```

The problem here is Netmiko wants to verify the command it sent was echoed to the screen (to verify it is in the proper state of the CLI session).

set cli complete-on-space off is already configured.

I will have to put in some fix for this...I don't see any way to disable this behavior in Juniper.

**Comment by ktbyers** [comment]
Did not fix this. It is really a Juniper behavior issue.

Probably would just try to catch command errors (i.e. end-user sending invalid commands) by catching the command echo failures.

**Comment by Suhaib000** [comment]
Hi @ktbyers 

I face the same issue after sending multiple commands sometimes send them and sometimes the next command is not sent to the device while (cmd_verify = True) 

I am using netmiko==4.1.2

is there any fix in the latest release while  (cmd_verify = True)?

**Comment by ktbyers** [comment]
@Suhaib000 The issue referenced here was the person sending invalid commands (i.e. what they sent was not a valid Juniper command).

Is that your situation or do you have a different issue?

**Comment by Suhaib000** [comment]
I send valid commands that run without issues in the router's CLI, but when using Netmiko, they sometimes run successfully and other times stop at a specific command until timeout.

**Comment by ktbyers** [comment]
@Suhaib000 Okay, you will probably have to show some examples including the full exception stack trace. Make sure you don't abbreviate commands (i.e. use the fully-expanded version of the commands).

**Comment by Suhaib000** [comment]
here is my code 
I replaced the IP numbers with x 
using  this code sometimes stops after pushing the first command and did not push the rest and receive a timeout exception 

and sometimes all of them executed successfully 


#==========================================================
from netmiko import ConnectHandler

virtual_srx = {
    'device_type': "juniper",
    'host':   "x.x.x.x",
    'username': "username",
    'password': "password",
}

net_connect = ConnectHandler(**virtual_srx)

commands = ['set policy-options policy-statement Seabone term Dial from route-filter x.x.0.0/24 exact', 'set policy-options policy-statement Seabone term Dial from route-filter x.x.x.0/24 exact', 'set policy-options policy-statement Seabone term Dial from route-filter x.x.x.0/24 exact', 'set policy-options policy-statement Seabone term Dial from route-filter x.x.x.0/24 exact','set policy-options policy-statement Seabone term Dial then accept','insert policy-options policy-statement Seabone term Dial before term reject', 'commit ']

output = net_connect.send_config_set(
    commands,
    exit_config_mode=False,
)

net_connect.disconnect()
print(output)
#==========================================================





here is the error message:

"""
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'set\\ policy\\-options\\ policy\\-statement\\ Seabone\\ term\\ Dial\\ from\\ route\\-filter\\ x\\.x\\.0\\.0/24\\ exact' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
"""
