### ISSUE TITLE
Connect timeout vs read timeout

### ISSUE THREAD

**Issue by Alex131089** [ktbyers/netmiko#1586]
Hello, 

it is documented that `timeout` (https://ktbyers.github.io/netmiko/docs/netmiko/base_connection.html) is "Connection timeout.", however this is not true, this value is reused multiple times as (an unexisting)  `read_timeout`, at least in `_read_channel_expect`, `_read_channel_timing`, `send_command_timing`, `send_command`.

In Paramiko, where it is correctly used, this is described as the TCP connect timeout (http://docs.paramiko.org/en/stable/api/client.html#paramiko.client.SSHClient.connect), which is what is expected.

But in the `_read_channel*` and `send_command*` functions, they are misused.

I believe that's not right as theses are 2 different things. For example you might want to wait a short time to connect to the equipment but wait longer for the reply.
If I set `timeout=5`:
* I skip quickly on unreachable hosts (they might take longer to answer, but that's fine: TCP connection is established, I know they're alive, the rest is controlled by another timeout, like `banner_timeout`)
* But because it is also used as a `read_timeout`, the `save_config()` call fails on slower/bigger equipments: it only waits 5 sec, never read the post-save prompt, raise an exception.

I think a `read_timeout` should exist for the last purpose.

Best,
Alexandre

**Comment by ktbyers** [comment]
Netmiko has the following timeouts (as far as arguments to ConnectHandler):

timeout = both a read timeout and a TCP connection timeout (based to Paramiko at connect)
banner_timeout = passed to Paramiko as banner_timeout
auth_timeout = passed to Paramiko as auth_timeout
blocking_timeout = used as blocking time to wait for more data to be available (as part of larger loop). Set using Paramiko's `settimeout`
session_timeout = Amount of time to wait for given operation to complete when using locking (generally used with Salt+Netmiko).

So for backwards compatibility timeout would need to remain as the read_timeout, but we could create a separate tcp_timeout if it is necessary (i.e. if auth_timeout and banner_timeout are not sufficient).

At this point backwards compatibility with Netmiko would be significantly more important than compatibility with Paramiko (as far as timeout meanings).

Documentation needs updated to reflect the use of timeout as a read timeout.

Let me know if you see contradictions or inconsistencies in what I am saying here (as this part is fairly complex).
