### ISSUE TITLE
Support for VyOS operator mode: need 3 different prompt_terminator?

### ISSUE THREAD

**Issue by KaraRyougi** [ktbyers/netmiko#1591]
In operator mode, the prompt terminator is ``>`` instead of ``$`` or ``#``. 

The current framework only supports a ``pri_prompt_terminator`` and an ``alt_prompt_terminator``. Maybe ``alt_prompt_terminator`` can be a list?

**Comment by ktbyers** [comment]
Are all three of these prompts used: `$ # >`

In which contexts are each one of them used?

Thanks.

**Comment by KaraRyougi** [comment]
When an account with Operator priviledge logs into VyOS, the prompt is always `>`. (However according to VyOS this mode will soon be deprecated...)

Admin account uses `$` in normal mode , and `#` in configuration mode. (which is currently well-supported)

**Comment by ktbyers** [comment]
Can you show me a code example including the exception for what breaks (especially on the original Netmiko connection).

How do you go from operator mode into the Admin account?

**Comment by ktbyers** [comment]
I am going to close this as no one is actively working on it...if anyone is still interested in this issue, let me know and we can re-open it or create a new issue.

**Comment by ktbyers** [comment]
Should be fixed here:

https://github.com/ktbyers/netmiko/pull/2673

**Comment by ktbyers** [comment]
Should be fixed here:

https://github.com/ktbyers/netmiko/pull/2673
