### ISSUE TITLE
Specific attributes for netmiko in nornir inventory or call enable()

### ISSUE THREAD

**Issue by narcotico-g** [ktbyers/netmiko#1594]
Hello,

I have a lot of old Procurve switches only with telnet, where disable paging and enable mode doesn't work in automatic way.

Reading a similar post, I could solve it using the next lines:

```python
con = netmiko.ConnectHandler(
    device_type="hp_procurve_telnet" 
    ip=ip, username=username, 
    password=password, 
    secret=password
)
con.enable(default_username=user)
con.send_command ("terminal len 1000") //for disable paging
r = con.send_command (command)
print (r)
```

Now, I would like to use it with nornir (I am learning it yet). I guess if I can overwrite default_username for enable function, it is done (from nornir inventory, it would be perfect).

If it is not possible with inventory attributes, how can send it in the call to do something similar to next line?
target_host.run (task=netmiko_send_command, command_string=command, enable=True, default_username=user)

At the same time, is there a doc with all possible netmiko attributes for nornir inventory?

Thanks.

**Comment by ktbyers** [comment]
@narcotico-g I am a bit unclear on your question?

When you connect with Netmiko + Nornir in your old device scenario. Does the Netmiko connection itself fail or do you only fail on later tasks?

Nornir + Netmiko should accept all ConnectHandler arguments for Netmiko connections (this would be in `connection_options > netmiko > extras`.

netmiko_send_command should accept all Netmiko `send_command` arguments. This `default_username` is not a valid Netmiko `send_command` argument.

Netmiko API docs are here:

https://ktbyers.github.io/netmiko/docs/netmiko/base_connection.html

**Comment by narcotico-g** [comment]
Summarizing,

I had 2 problems:

1) It was hard to find how use attributes in nornir (basically the next lines). When I found them, no problem, working fine.
` connection_options:
    netmiko:
      extras: {"secret": xxx}`

2) I need to change enable default_username with these devices (it is not "manager", it is the same as I use for login with radius authentication). The problem is that base_connection has no this option or param and I can not change it. So I overwrite netmiko_send_command and it is working fine.
However I do not like to modify original files for next updates. In this case I can not see any issue or incompatibility, it is simple. I would like to take a look and you consider add it.

`from typing import Any

from nornir.core.task import Result, Task

def netmiko_send_command(
    task: Task,
    command_string: str,
    use_timing: bool = False,
    enable: bool = False,
    default_username = 0,
    **kwargs: Any
) -> Result:
    """
    Execute Netmiko send_command method (or send_command_timing)

    Arguments:
        command_string: Command to execute on the remote network device.
        use_timing: Set to True to switch to send_command_timing method.
        enable: Set to True to force Netmiko .enable() call.
        kwargs: Additional arguments to pass to send_command method.

    Returns:
        Result object with the following attributes set:
          * result: Result of the show command (generally a string, but depends on use of TextFSM).
    """
    net_connect = task.host.get_connection("netmiko", task.nornir.config)
    if enable:
        if default_username:
          net_connect.enable (default_username=default_username)
        else:
          net_connect.enable()
    if use_timing:
        result = net_connect.send_command_timing(command_string, **kwargs)
    else:
        result = net_connect.send_command(command_string, **kwargs)
    return Result(host=task.host, result=result)
`
------------------------------------------------------------------------------------------
Explain of my procurve scenarios (all of them with radius authentication):
1) Procurve 2524 and 2512 (only support ssh1, so I use with telnet). These devices need authenticate 2 times (login + enable). With radius authentication, enable user and password are the same in my case (these are I called old Procurve before) and not default user "manager".

At the same time they use different command for disable paging. Do you have a method for testing a new device type for adding to Netmiko? or with this minimal difference, do you consider better another choice like another param? It would be similar at above case.

2) All other models are working fine with telnet and ssh2. They have configured a command to enter in privilege mode after login (this command does not exist in the 2524 and 2512 models), so I do not need to use default_username in these cases.

Thanks.

**Comment by ktbyers** [comment]
In Nornir, the process would be to create a custom task and invoke `enable` with the arguments you want prior to executing send_command.

Here is an example of creating a Nornir-Netmiko custom task:

https://github.com/twin-bridges/nornir_course/blob/master/bonus1/collateral/netmiko_direct_task/netmiko_direct.py#L6

So the standard 'hp_procurve' device_type doesn't work for disabling paging? What is the command for disabling paging on these devices?

Item #2, you should be able to work around with the custom task/enable invocation (if I read that correctly).

**Comment by narcotico-g** [comment]
Nornir-Netmiko custom task, very interesting and I will use for this and future cases.

However, I would like netmiko_send_command() support different default_username (as "manager" is supported). It would think different if enable() was not called from netmiko_send_command().
-------------
About disable paging I was wrong. I have reviewed in detail and the problem is not the command. 
The problem is the command is sent in session_preparation() before enable(), so it has no effect and I have to do manually.
In these devices it is necessary to be in enable mode for using "no page" command.

```
DEBUG:netmiko:Pattern is: no\ page
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output =
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel:
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[24;0H\x1bE\x1b[24;1H\x1b[24;13H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[1;24r\$
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output =
SWT0072073> no page
Invalid input: no
^MSWT0072073>
DEBUG:netmiko:repr = '\r\nSWT0072073> no page\r\nInvalid input: no\n\rSWT0072073> '
DEBUG:netmiko:read_channel:
SWT0072073> no page
Invalid input: no
^MSWT0072073>
DEBUG:netmiko:Pattern found: no\ page
SWT0072073> no page
Invalid input: no
^MSWT0072073>
DEBUG:netmiko:
SWT0072073> no page
Invalid input: no
^MSWT0072073>
```

**Comment by ktbyers** [comment]
I am going to close this--just re-open if there is some pending action here.
