### ISSUE TITLE
netmiko3.0.0 problem in read telnet echo command

### ISSUE THREAD

**Issue by TanY0Y0** [ktbyers/netmiko#1605]
netmiko version: 3.0.0 github develop branch
i use telnet to link ZTE device by ` device_type: cisco_ios_telnet `,
it break at ` session_preparation() ->  read_until_pattern() ` ,
it said ` pattern not found in output: terminal\ length\ 0 `,
but i found it in wireshark cap，client send `Don‘t Echo Won't....`, is this affect?

here is my code:
```python
import netmiko
import logging
import time
logging.basicConfig(filename='test_10.0.10.26_telnet.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

start = time.time()
zte_conn = netmiko.Netmiko(
    ip='10.0.10.26', 
    username='zte', 
    password='zte', 
    device_type='cisco_ios_telnet', 
    fast_cli=True,
)
end = time.time()
print('connect cost:' + str(end - start))
print(zte_conn.send_command('terminal length 0'))
zte_conn.disconnect()
```
above is error info:
```python


---------------------------------------------------------------------------

NetmikoTimeoutException                   Traceback (most recent call last)

<ipython-input-1-949e816e0a42> in <module>
     12     password='zte',
     13     device_type='cisco_ios_telnet',
---> 14     fast_cli=True,
     15 )
     16 end = time.time()

/home/self_code/netmiko/ssh_dispatcher.py in ConnectHandler(*args, **kwargs)
    260         )
    261     ConnectionClass = ssh_dispatcher(kwargs["device_type"])
--> 262     return ConnectionClass(*args, **kwargs)
    263 
    264 

/home/self_code/netmiko/base_connection.py in __init__(self, ip, host, username, password, secret, port, device_type, verbose, global_delay_factor, use_keys, key_file, pkey, passphrase, allow_agent, ssh_strict, system_host_keys, alt_host_keys, alt_key_file, ssh_config_file, timeout, session_timeout, auth_timeout, blocking_timeout, banner_timeout, keepalive, default_enter, response_return, serial_settings, fast_cli, session_log, session_log_record_writes, session_log_file_mode, allow_auto_change, encoding, sock)
    316 
    317         # Establish the remote connection
--> 318         self._open()
    319 
    320     def _open(self):

/home/self_code/netmiko/base_connection.py in _open(self)
    322         self._modify_connection_params()
    323         self.establish_connection()
--> 324         self._try_session_preparation()
    325 
    326     def __enter__(self):

/home/self_code/netmiko/base_connection.py in _try_session_preparation(self)
    745         """
    746         try:
--> 747             self.session_preparation()
    748         except Exception:
    749             self.disconnect()

/home/self_code/netmiko/cisco/cisco_ios.py in session_preparation(self)
     15         self._test_channel_read(pattern=r"[>#]")
     16         self.set_base_prompt()
---> 17         self.disable_paging()
     18         self.set_terminal_width(command="terminal width 511")
     19         # Clear the read buffer

/home/self_code/netmiko/base_connection.py in disable_paging(self, command, delay_factor)
   1020         self.write_channel(command)
   1021         # Make sure you read until you detect the command echo (avoid getting out of sync)
-> 1022         output = self.read_until_pattern(pattern=re.escape(command.strip()))
   1023         log.debug(f"{output}")
   1024         log.debug("Exiting disable_paging")

/home/self_code/netmiko/base_connection.py in read_until_pattern(self, *args, **kwargs)
    616     def read_until_pattern(self, *args, **kwargs):
    617         """Read channel until pattern detected. Return ALL data available."""
--> 618         return self._read_channel_expect(*args, **kwargs)
    619 
    620     def read_until_prompt_or_pattern(self, pattern="", re_flags=0):

/home/self_code/netmiko/base_connection.py in _read_channel_expect(self, pattern, re_flags, max_loops)
    562             i += 1
    563         raise NetmikoTimeoutException(
--> 564             f"Timed-out reading channel, pattern not found in output: {pattern}"
    565         )
    566 

NetmikoTimeoutException: Timed-out reading channel, pattern not found in output: terminal\ length\ 0

```

here is the log:
[test_10.0.10.26_telnet.log](https://github.com/ktbyers/netmiko/files/4296950/test_10.0.10.26_telnet.log)

here is the wireshark cap:
[zte_netmiko_telnet_cap.zip](https://github.com/ktbyers/netmiko/files/4297176/zte_netmiko_telnet_cap.zip)

**Comment by TanY0Y0** [comment]
i got it

**Comment by ktbyers** [comment]
@TanY0Y0 What was your fix/solution?

Kirk

**Comment by TanY0Y0** [comment]
i looked over the `telnetlib.py`, and found that in default way, when `telnetlib.read_xxxx()`  function is used, it will detect the telnet server's negotiate options, which are server sends at first，and then 
`telnetlib` will return `DONT` or `WONT` to these options. the point is some server will send `WILL ECHO` at first, and then get the `DONT ECHO` from `telnetlib` , accept this finally echo the `WONT ECHO`. this is why after connecting, device dont echo any command anymore.

`telnetlib` provide a way --`set_option_negotiation_callback()`  to set `negotiate options`  manually,
and i did it, and worked. this function **must be inserted after `Telnet() class` and before `read_xxx() function`** 

i wish this function can be added to `BaseConnection`, now i creat it in my device_type class, next step i want to figure out if the `screen width` can be adjusted by this way.

**Comment by ktbyers** [comment]
Okay, your response is strange, I have a cisco_ios_telnet that I connect to frequently and I don't see these characteristics (i.e. echo works by default).

Do you have a log capture of this behavior?

Can you also share your code that fixed it?

**Comment by TanY0Y0** [comment]
here is my demo:
```python
from telnetlib import (
IAC,
DO,
WILL,
Telnet,
)
import time


def telnet_option_call(telnet_sock, cmd, opt):
    if cmd == WILL:
        telnet_sock.sendall(IAC + DO + opt)
    # pass


HOST = "10.0.10.26"
username = 'zte'
password = 'zte'

tn = Telnet(HOST)
tn.set_debuglevel(1)
tn.set_option_negotiation_callback(telnet_option_call)
tn.read_until(b"sername:")
tn.write(username.encode('ascii') + b"\n")
if password:
    tn.read_until(b"assword:")
    tn.write(password.encode('ascii') + b"\n")

tn.read_until(b"#")
tn.write(b"terminal length 0\n")
# tn.write(b"exit\n")
time.sleep(0.1)
print(tn.read_very_eager().decode('ascii'))
tn.close()
```

three option set wireshark caps：
[telnetlib_opton_test_cap.zip](https://github.com/ktbyers/netmiko/files/4301704/telnetlib_opton_test_cap.zip)

1. in default case
telnetlib send `DONT` and `WONT` to all server options
result: server accepts, echo `DONT ECHO`
2. pass option negotiate
dont echo anything to server
result: server default dont echo if client dont echo `DO`
3. echo server `DO ECHO`
server accepts and can echo commands

**Comment by ktbyers** [comment]
I don't think Telnetlib defaults to "DONT ECHO" in general (otherwise, I would have a bunch of other things fail). So that doesn't sound correct to me.

I really suspect this is more an aspect of the ZTE device and perhaps its interaction with telnetlib.

Anyways you would need to create a driver to support it. This is not a platform Netmiko has a driver for.

Process for adding a driver is here:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md

The "ruckus/ruckus_fastiron.py" has a similar pattern to enable the telnet echo so I recommend you copy that pattern.

https://github.com/ktbyers/netmiko/blob/develop/netmiko/ruckus/ruckus_fastiron.py#L78

**Comment by TanY0Y0** [comment]
er... i 100% confirmed that `telnetlib` will replies to server `DONT` or `WILL` option by default, if server send `DO` or `WILL` option at the fisrt time,but if server dont send these, `telnetlib` also dont replies.

here is the source code in `telnetlib.py -> process_rawq()`:
```python
                    if cmd in (DO, DONT):
                        self.msg('IAC %s %d',
                            cmd == DO and 'DO' or 'DONT', ord(opt))
                        if self.option_callback:
                            self.option_callback(self.sock, cmd, opt)
                        else:
                            self.sock.sendall(IAC + WONT + opt)
                    elif cmd in (WILL, WONT):
                        self.msg('IAC %s %d',
                            cmd == WILL and 'WILL' or 'WONT', ord(opt))
                        if self.option_callback:
                            self.option_callback(self.sock, cmd, opt)
                        else:
                            self.sock.sendall(IAC + DONT + opt)
```
we can see, if `telnetlib` receive server's `DO` or `WILL` option, besides we didnt use `option_callbask()` to manually reply option, it will echo `self.sock.sendall(IAC + DONT/WONT + opt)` to server.

as you said, you havent met with `ECHO` problems before, but i think either the device didnt send any `WILL` option or the device ignore the `DONT ECHO` option, only these two reasons.

Anyway, i will add a new type, but i think it is necessary to let you know the truth, happy discussed with you，thanks！
