### ISSUE TITLE
netmiko timesout to display long object group output

### ISSUE THREAD

**Issue by eagleotstar** [ktbyers/netmiko#1607]
from netmiko import Netmiko
from netmiko import ConnectHandler
import getpass
import time

user = input('Enter Username:')
pswd = getpass.getpass()

net_connect = Netmiko(host='10.24.2.200', port=22, username=user, password=pswd, device_type='cisco_ios')

output = net_connect.send_command('sh object-group id Forrest_General_Local')
print(output)

net_connect.disconnect()

================================================================================================================================

I am trying to write a script where to display the object group in a firewall is part of the script......the problem if the object group is too big with more than 5 host ...the program returns an error

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/arane/network_automation/firewall/test_add_host.py", line 12, in <module>
    output = net_connect.send_command('sh object-group id Forrest_General_Local')
  File "C:\Users\arane\network_automation\venv\lib\site-packages\netmiko\base_connection.py", line 1337, in send_command
    search_pattern

**object-group network Forrest_General_Local**
 network-object host 10.66.44.5
 network-object host 10.46.34.30
 network-object host 10.66.44.10
 network-object host 10.66.44.11
 network-object host 10.66.44.12
 network-object host 10.66.44.13
 network-object host 10.66.44.14
 network-object host 10.66.44.17
 network-object host 10.66.44.18
<--- More --->

When i set the page line to 0 , the code runs just fine.....but is there a workaround where i can run this code without changing the page line to zero.

i already tried this **output = net_connect.send_command('sh object-group id Forrest_General_Local', delay_factor=2, max_loop=100)**.....but it didn't work.

**Comment by ktbyers** [comment]
```
When i set the page line to 0 , the code runs just fine.....
but is there a workaround where i can run this code without changing the page line to zero.
```

Netmiko should execute `terminal length 0` automatically. Can you explain a bit more why you can't do this?

**Comment by eagleotstar** [comment]
the object group is on the Cisco ASA ....my default terminal width is 511 and pager lines is set to 24 ....

now i have object group with 2 host and 10 host...._send_command
 **object-group network myobject  >>>>>> works fine**
 network-object host 10.88.44.1
 network-object host 10.88.44.5
 network-object host 10.88.44.10
 network-object host 10.88.44.9
 network-object host 10.88.44.100
 network-object host 10.88.44.3


**object-group network Forrest_General_Local** >>> doesnt work because the object group is too big
network-object host 10.66.44.5
network-object host 10.46.34.30
network-object host 10.66.44.10
network-object host 10.66.44.11
network-object host 10.66.44.12
network-object host 10.66.44.13
network-object host 10.66.44.14
network-object host 10.66.44.17
network-object host 10.66.44.18
<--- More --->

when I do expect_string="<--- More --->"  it does return the output,but only half of the object group

**Comment by ktbyers** [comment]
You are using the wrong device_type:

```
net_connect = Netmiko(host='10.24.2.200', port=22, username=user, password=pswd, device_type='cisco_ios')
```

You need to use the `cisco_asa` device_type.

**Comment by eagleotstar** [comment]
thanks for the response Kirk !!!
