### ISSUE TITLE
Dell/Force10 does not work with Cisco IOS Driver -- SSH after a few times causes switch to blackout (no HTTP/SSH/serial)

### ISSUE THREAD

**Issue by nunocarrulo** [ktbyers/netmiko#161]
After using netmiko a couple times in the same switch always disconnecting from session it cause the switch to not respond to any SSH, HTTP or serial connections.

**Comment by jfilliben** [comment]
Perhaps you are not properly closing the connections? Most routers/switches only allow a limited number of concurrent sessions. A way to test would be to log into the device manually and (if Cisco IOS) do 'show connections' while your script runs. If you notice multiple sessions using your script's credentials, this is likely the problem.

Take a look at this blog post for a 'clean' way to handle connections -- http://packetpushers.net/using-python-context-managers/

**Comment by ktbyers** [comment]
@nunocarrulo Does the switch keep functioning normally from a packet forwarding perspective (i.e. is it only a management access issue)?

What type of switch is it (vendor/model)?


Kirk

**Comment by nunocarrulo** [comment]
Yes, it keeps working. I just can't access it no manage it. It's strange because it blocks me also http and serial does not work either. Via http I get this output 'Transfer is in progress, please wait...'.

I'm using the example of cisco_ios because it is similar to cisco. However they are Dell switches and I cannot find any version of Dell or F10 in the supported versions. Anyway the scripts work, I can access it (ssh credentials + enable), get some info and configure something. It's just after using it for a while this happens.

You have any idea what this might be ?


Regards,

Nuno B.


________________________________
De: Kirk Byers <notifications@github.com>
Enviado: 7 de janeiro de 2016 16:56
Para: ktbyers/netmiko
Cc: Rui Braz
Assunto: Re: [netmiko] SSH after a few times causes switch to blackout (No HTTP, SSH or serial) (#161)


@nunocarrulo<https://github.com/nunocarrulo> Does the switch keep functioning normally from a packet forwarding perspective (i.e. is it only a management access issue)?

[https://avatars1.githubusercontent.com/u/9117361?v=3&s=400]<https://github.com/nunocarrulo>

nunocarrulo<https://github.com/nunocarrulo>
github.com
nunocarrulo has 1 repository written in Java, Python, and Shell. Follow their code on GitHub.



What type of switch is it (vendor/model)?

Kirk

-

**Comment by nu110** [comment]
Sounds to me like the ssh or management plane process might be having some trouble, which may well be linked to http.

No surprise the data plane continues forwarding traffic since most of what happens there will be hardware / ASIC driven. I had a similar issue with a Cisco 3750-X this week, a telnet session on 127.0.0.4 (?) for some reason was consuming 75% CPU for some time. Clearing the vty line fixed the issue, traffic was being forwarded by the switching hardware quite happily all day long though.

**Comment by ktbyers** [comment]
@nunocarrulo This could be related to issue #151 (i.e. I don't gracefully exit the SSH session currently at the CLI level). I just close the SSH session. This should be fixed, but I haven't done it yet.

You might want to just gracefully exit the SSH session manually. You should be able to do this using:

remote_conn.sendall('exit\n')

Obviously this assumes Cisco and that you are in privilege-exec/user-exec mode (i.e. not in configuration mode).

**Comment by nunocarrulo** [comment]
@ktbyers So your close method just uses paramiko close method. This means that paramiko method 'close()' isn't closing ssh connection gracefully as well ? In the 'transport' module they just close the socket meanwhile in the 'agent' module I didn't understand it quite well.

In my case I have to send 'end' followed by 'quit'. The first exists from any level I'm at, for example 'config', 'interface gi1/0/1'). The second closes the connection.


However I'm still not sure that that's the problem because when I ran my script it got stuck when accessing the switch and didn't print anything else. By this I mean that it didn't reach the point of closing the connection, meaning that my problem may not reside there. As far as I remember it happens after I get the message ('Interactive SSH session established') or at the 'enable()' method. I can't say for sure because I didnt had any prints in between that. I didnt perform more testing because I don't want/can't block any more switches.

________________________________
De: Kirk Byers <notifications@github.com>
Enviado: 9 de janeiro de 2016 17:16
Para: ktbyers/netmiko
Cc: Rui Braz
Assunto: Re: [netmiko] SSH after a few times causes switch to blackout (No HTTP, SSH or serial) (#161)


@nunocarrulo<https://github.com/nunocarrulo> This could be related to issue #151<https://github.com/ktbyers/netmiko/issues/151> (i.e. I don't gracefully exit the SSH session currently at the CLI level). I just close the SSH session. This should be fixed, but I haven't done it yet.

[https://avatars1.githubusercontent.com/u/9117361?v=3&s=400]<https://github.com/nunocarrulo>

nunocarrulo<https://github.com/nunocarrulo>
github.com
nunocarrulo has 1 repository written in Java, Python, and Shell. Follow their code on GitHub.



You might want to just gracefully exit the SSH session manually. You should be able to do this using:

remote_conn.sendall('exit\n')

Obviously this assumes Cisco and that you are in privilege-exec/user-exec mode (i.e. not in configuration mode).

-

**Comment by nu110** [comment]
I have a couple of old Dell switches sat in the store room at the office if
you'd like me to give your script a try, a 3324 and a 3424. Not sure if
they're even working or need password recovering etc. But if it might be of
use I'm happy to help if I can.

**Comment by nunocarrulo** [comment]
I don't know if the script will work on these ones, but we can try. I'm afraid it won't even connect the SSH session. Anyhow here is the script code: <https://codeshare.io/j2pFA> https://codeshare.io/j2pFA


Thank you. Post me whether if it works or not on those ones.

________________________________
De: nu110 <notifications@github.com>
Enviado: 11 de janeiro de 2016 12:02
Para: ktbyers/netmiko
Cc: Rui Braz
Assunto: Re: [netmiko] SSH after a few times causes switch to blackout (No HTTP, SSH or serial) (#161)

I have a couple of old Dell switches sat in the store room at the office if
you'd like me to give your script a try, a 3324 and a 3424. Not sure if
they're even working or need password recovering etc. But if it might be of
use I'm happy to help if I can.

On Mon, Jan 11, 2016 at 11:55 AM, nunocarrulo <notifications@github.com>
wrote:

> @ktbyers So your close method just uses paramiko close method. This means
> that paramiko method 'close()' isn't closing ssh connection gracefully as
> well ? In the 'transport' module they just close the socket meanwhile in
> the 'agent' module I didn't understand it quite well.
>
> In my case I have to send 'end' followed by 'quit'. The first exists from
> any level I'm at, for example 'config', 'interface gi1/0/1'). The second
> closes the connection.
>
>
> However I'm still not sure that that's the problem because when I ran my
> script it got stuck when accessing the switch and didn't print anything
> else. By this I mean that it didn't reach the point of closing the
> connection, meaning that my problem may not reside there. As far as I
> remember it happens after I get the message ('Interactive SSH session
> established') or at the 'enable()' method. I can't say for sure because I
> didnt had any prints in between that. I didnt perform more testing because
> I don't want/can't block any more switches.
>
> ________________________________
> De: Kirk Byers <notifications@github.com>
> Enviado: 9 de janeiro de 2016 17:16
> Para: ktbyers/netmiko
> Cc: Rui Braz
> Assunto: Re: [netmiko] SSH after a few times causes switch to blackout (No
> HTTP, SSH or serial) (#161)
>
>
> @nunocarrulo<https://github.com/nunocarrulo> This could be related to
> issue #151<https://github.com/ktbyers/netmiko/issues/151> (i.e. I don't
> gracefully exit the SSH session currently at the CLI level). I just close
> the SSH session. This should be fixed, but I haven't done it yet.
>
> [https://avatars1.githubusercontent.com/u/9117361?v=3&s=400]<
> https://github.com/nunocarrulo>
>
> nunocarrulo<https://github.com/nunocarrulo>
> github.com
> nunocarrulo has 1 repository written in Java, Python, and Shell. Follow
> their code on GitHub.
>
>
>
> You might want to just gracefully exit the SSH session manually. You
> should be able to do this using:
>
> remote_conn.sendall('exit\n')
>
> Obviously this assumes Cisco and that you are in privilege-exec/user-exec
> mode (i.e. not in configuration mode).
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/ktbyers/netmiko/issues/161#issuecomment-170260824>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/161#issuecomment-170519508>.
>

-
Reply to this email directly or view it on GitHub<https://github.com/ktbyers/netmiko/issues/161#issuecomment-170520723>.

[https://avatars1.githubusercontent.com/u/9117361?v=3&s=400]<https://github.com/ktbyers/netmiko/issues/161#issuecomment-170520723>

SSH after a few times causes switch to blackout (No HTTP, SSH or serial) · Issue #161 · ktbyers/netmiko<https://github.com/ktbyers/netmiko/issues/161#issuecomment-170520723>
github.com
After using netmiko a couple times in the same switch always disconnecting from session it cause the switch to not respond to any SSH, HTTP or serial connections.

**Comment by ktbyers** [comment]
@nunocarrulo @nu110 Okay, this sounds more like Dell/Force10 isn't working using the Cisco IOS driver.

Can you list the Dell model numbers that you observed this behavior with?

**Comment by nunocarrulo** [comment]
I've teste mainly with Dell N2000 switches. I have some HP switches pro curve but I will not test with them until I get switches that are off the network. I chose cisco_ios because I've configured in both and in my opinion they are kinda similar.


________________________________
De: Kirk Byers <notifications@github.com>
Enviado: 11 de janeiro de 2016 20:53
Para: ktbyers/netmiko
Cc: Rui Braz
Assunto: Re: [netmiko] SSH after a few times causes switch to blackout (No HTTP, SSH or serial) (#161)


@nunocarrulo<https://github.com/nunocarrulo> @nu110<https://github.com/nu110> Okay, this sounds more like Dell/Force10 isn't working using the Cisco IOS driver.

[https://avatars1.githubusercontent.com/u/9117361?v=3&s=400]<https://github.com/nunocarrulo>

nunocarrulo<https://github.com/nunocarrulo>
github.com
nunocarrulo has 1 repository written in Java, Python, and Shell. Follow their code on GitHub.



Can you list the Dell model numbers that you observed this behavior with?

-

**Comment by ktbyers** [comment]
@nunocarrulo So this sounds like a Dell/Force10 issue i.e. Netmiko has no driver for Force10. You assumed Cisco IOS would just work for Dell/Force10, but it looks like it doesn't.

I would be happy to add in Dell/Force10 support, but need someone to do the work, test it, and submit the PR.

If you have a test device, we can possibly debug what is going on. But obviously I don't want to cause issues with your live network.

I am pretty confident HP ProCurve would work (using the ProCurve driver). I have tested this quite a bit.

**Comment by ericleahy** [comment]
Just wanted to add something on the Dell Networking/F10 switches. The N2000 runs on a different OS, DNOS6, than any of the more higher level Dell Networking switches, C series, S series, Z series switches, DNOS9. I have ran scripts using paramiko against the OS9 without any issues and I have just tried it with netmiko and not hitting any issues with the OS9. Might be a OS6 issue?
@ktbyers I have a few Dell Networking/F10 switches in a lab we can work on to add Dell/F10 support fully?

**Comment by nu110** [comment]
Haven't been back in the office yet, but sounds like the switches I
mentioned aren't relevant so I'll leave it.

**Comment by ktbyers** [comment]
@ericleahy Can I get SSH access to them? Either that or you can work on adding a Dell-F10 driver (see https://github.com/ktbyers/netmiko/blob/master/VENDOR.md).

**Comment by ericleahy** [comment]
@ktbyers I can get you SSH access if you would like?

**Comment by ktbyers** [comment]
@ericleahy Sounds good. Do you have my email address?

**Comment by ericleahy** [comment]
@ktbyers ericleahy83@gmail.com

**Comment by ktbyers** [comment]
Okay just emailed you.

**Comment by ktbyers** [comment]
Linking to issue #128

**Comment by ktbyers** [comment]
@nunocarrulo I don't have any DNOS6 devices so I don't have any way of figuring out what is going on here.

I did add Dell-F10 DNOS9 support (but it is current the same as cisco IOS from a Netmiko perspective).

**Comment by nunocarrulo** [comment]
@kirkbyers Thank you. I'll perform a few tests including on HP devices and Dell devices that were not upgraded to DNOS6. This way I can be sure that it the OS is the problem.

Anyway, if you want I might be able to perform some tests regarding Dell DNOS6.


________________________________
De: Kirk Byers <notifications@github.com>
Enviado: 17 de janeiro de 2016 01:10
Para: ktbyers/netmiko
Cc: Rui Braz
Assunto: Re: [netmiko] Dell/Force10 does not work with Cisco IOS Driver -- SSH after a few times causes switch to blackout (no HTTP/SSH/serial) (#161)


@nunocarrulo<https://github.com/nunocarrulo> I don't have any DNOS6 devices so I don't have any way of figuring out what is going on here.

[https://avatars1.githubusercontent.com/u/9117361?v=3&s=400]<https://github.com/nunocarrulo>

nunocarrulo<https://github.com/nunocarrulo>
github.com
nunocarrulo has 2 repositories written in Java, Python, and Shell. Follow their code on GitHub.



I did add Dell-F10 DNOS9 support (but it is current the same as cisco IOS from a Netmiko perspective).

-

**Comment by ktbyers** [comment]
@nunocarrulo It sounds like I might be able to get access to a DNOS6 switch (courtesy of @ericleahy).

**Comment by nunocarrulo** [comment]
@kirkbyers @ericleahy Great. Thanks a lot.

By the way thanks for adding support for Dell/F10 devices. It will be very useful.


________________________________
De: Kirk Byers <notifications@github.com>
Enviado: 17 de janeiro de 2016 19:28
Para: ktbyers/netmiko
Cc: Rui Braz
Assunto: Re: [netmiko] Dell/Force10 does not work with Cisco IOS Driver -- SSH after a few times causes switch to blackout (no HTTP/SSH/serial) (#161)


@nunocarrulo<https://github.com/nunocarrulo> It sounds like I might be able to get access to a DNOS6 switch (courtesy of @ericleahy<https://github.com/ericleahy>).

[https://avatars1.githubusercontent.com/u/9117361?v=3&s=400]<https://github.com/nunocarrulo>

nunocarrulo<https://github.com/nunocarrulo>
github.com
nunocarrulo has 2 repositories written in Java, Python, and Shell. Follow their code on GitHub.



-

**Comment by nunocarrulo** [comment]
@ktbyers How's the library for Dell/F10 devices going ?

**Comment by ktbyers** [comment]
We are mainly tracking it here #128. Obviously welcome to submit PRs and to add support.

I am going to close this issue and just leave open #128.
