### ISSUE TITLE
cisco router as a jump host

### ISSUE THREAD

**Issue by mischgun** [ktbyers/netmiko#1610]
Hello Kirk,

Sorry, I am new at GitHub and was not able to find where i can ask a question, probably Issues is not a right place.

So my question is: is it possible to use a cisco router as a jumps host with netmiko?

**Comment by tars01** [comment]
I am just looking at this exact scenario today. I have been looking at issue #761 and trying to tweak the code as it's similar (I want to use Cisco router as a jump host) I want to SSH to a router, then from there I need to make telnet connections to other routers.

So far this is my code, I can get it to SSH to the router acting as the jump host. I can then initiate the telnet command from that router but I am having problems connecting after that. Below is my code:

`from __future__ import unicode_literals, print_function
import time
from netmiko import ConnectHandler, redispatch

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")


cisco = {
    'device_type': 'cisco_ios',
    'host': '192.168.0.120',
    'username': 'admin',
    'password': 'admin',
     }

net_connect = ConnectHandler(**cisco)


#output = net_connect.send_command("telnet 100.10.10.1")
output = net_connect.write_channel("telnet 100.10.10.1"  + '\r\n')
time.sleep(.5)

#Manually handle the Username and Password
max_loops = 10
i = 1
while i <= max_loops:
    output = net_connect.read_channel()

    if 'Username:' in output:
        net_connect.write_channel(net_connect.username  + '\r\n')
        time.sleep(1)
        output = net_connect.read_channel()

    # Search for password pattern / send password
    if 'Password' in output:
        net_connect.write_channel(net_connect.password + '\r\n')
        time.sleep(.5)
        output = net_connect.read_channel()
        # Did we successfully login
        if '>' in output or '#' in output:
            break

new_output = net_connect.send_command("show ip int brief")
print ('new_output')
`
I have enabled debugging and here is my log [log.txt](https://github.com/ktbyers/netmiko/files/4315132/log.txt) but I am struggling to get it working. 

Any help appreciated.

**Comment by tars01** [comment]
@mischgun Please see the following link that Kirk wrote:
https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

Kirk, if you have anything similar for connecting via an Cisco router then onward connections using Telnet/SSH that would be great, thanks.

**Comment by mischgun** [comment]
> 
> 
> @mischgun Please see the following link that Kirk wrote about using an SSH proxy:
> https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html
> 
> Kirk, if you have anything similar for connecting via an Cisco router then onward connections using Telnet/SSH that would be great, thanks.

Hi tars01, 
I have found something 
https://github.com/ktbyers/netmiko/issues/470

**Comment by ktbyers** [comment]
Yep...look at using "redispatch" like the example your referenced there.

**Comment by tars01** [comment]
Thanks @ktbyers and @mischgun 

I managed to get it to run show commands but can't get it to apply any commands in conf t. I will keep trying, thanks.
