### ISSUE TITLE
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner when the router is down via SSH tunnel

### ISSUE THREAD

**Issue by ciscorat** [ktbyers/netmiko#1612]
Hi,

I am connecting to a device via ssh tunnel just fine. During a reload, I am getting the following traceback:

`Exception: Error reading SSH protocol banner`
`Traceback (most recent call last):`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner`
`    buf = self.packetizer.readline(timeout)`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline`
`    buf += self._read_timeout(timeout)`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 622, in _read_timeout`
`    raise socket.timeout()`
`socket.timeout`
``
`During handling of the above exception, another exception occurred:`
``
`Traceback (most recent call last):`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run`
`    self._check_banner()`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner`
`    raise SSHException(`
`paramiko.ssh_exception.SSHException: Error reading SSH protocol banner`

Since it's part of try/except, the script doesn't break.
I'm having hard time with paramiko "establishing" ssh connection to a device that is down and throwing the stack backtrace.
When the router comes up the connection is established just fine.
Here is the output of the debug:

`DEBUG:paramiko.transport:starting thread (client mode): 0xdd2bb80`
`DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1`
`ERROR:paramiko.transport:Exception: Error reading SSH protocol banner`
`ERROR:paramiko.transport:Traceback (most recent call last):`
`ERROR:paramiko.transport:  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner`
`ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)`
`ERROR:paramiko.transport:  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline`
`ERROR:paramiko.transport:    buf += self._read_timeout(timeout)`
`ERROR:paramiko.transport:  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 622, in _read_timeout`
`ERROR:paramiko.transport:    raise socket.timeout()`
`ERROR:paramiko.transport:socket.timeout`
`ERROR:paramiko.transport:`
`ERROR:paramiko.transport:During handling of the above exception, another exception occurred:`
`ERROR:paramiko.transport:`
`ERROR:paramiko.transport:Traceback (most recent call last):`
`ERROR:paramiko.transport:  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run`
`ERROR:paramiko.transport:    self._check_banner()`
`ERROR:paramiko.transport:  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner`
`ERROR:paramiko.transport:    raise SSHException(`
`ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Error reading SSH protocol banner`
`ERROR:paramiko.transport:`
`Connect to 9.0.6.202 failed`

The code:
try:
	net = ConnectHandler(**lab)
	print(f"""Connected to {lab["ip"]}\n""")
	prompt = net.find_prompt()
except:
	print(f"""Connect to {lab["ip"]} failed\n""")
	exit()

I have followed paramiko's posts regarding this exception and patched proxy.py and transport.py accordingly, but neither of the cases was referring to a device down case.

Thanks

**Comment by ktbyers** [comment]
So this is after a reload? Have you verified you have waited long enough for the device to be back up?

Also you might want to try setting the "banner_timeout" argument to ConnectHandler to a larger value (maybe 30 or 60).


Kirk

**Comment by ciscorat** [comment]
Hi Kirk,

The banner time out is set:

{'device_type': 'cisco_nxos', 'username': '<hidden>', 'ssh_config_file': '.ssh/config', 'password': '<hidden>', 'banner_timeout': 15, 'global_delay_factor': 10, 'ip': '9.0.6.202'}

That code is the beginning to just make sure there is connectivity as a condition to start.
 Later on I will be reloading and wait for the script to come up.
Every one of these attempts will display the traceback which I rather it was not.
One baffles me is paramiko doesn't really escape from the ssh and proceed with the code waiting for the ssh banner.
Here is the "test if device is ip" code:

# Waiting for the switch to come up
boot_timer = time.time()
upstate = False
while not upstate:
	sys.tracebacklimit = None
	try:
		net = ConnectHandler(**lab)
	except:
		upstate = False
		elapsed_time = time.time() - boot_timer
		ms = str(list(str(elapsed_time).split('.')[-1].strip(""))[0] + list(str(elapsed_time).split('.')[-1].strip(""))[1] + list(str(elapsed_time).split('.')[-1].strip(""))[2])
		print('Elapsed time:', str(elapsed_time).split('.')[0] + ":" + ms + " ms", flush=True)
		pass
	else:
		upstate = True
		print("Switch is up")

**Comment by ktbyers** [comment]
Paramiko uses threading here...so you likely won't be able to catch the exception (as it happens in a different thread). That is my guess as to what is happening.

Probably should use some other mechanism to verify the device is up.

**Comment by ciscorat** [comment]
Oh, and when the switch come us the script continues just fine

Elapsed time: 154:216 ms
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Elapsed time: 169:235 ms
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Elapsed time: 184:335 ms
Elapsed time: 216:005 ms
Switch is up
+++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by ciscorat** [comment]
just saw your answer. I'll try something different.

Thanks!

**Comment by ktbyers** [comment]
I have seen individuals have similar issues before due to this Paramiko threading.

**Comment by ktbyers** [comment]
I am going to close as I don't think there is anything else to do here.
