### ISSUE TITLE
New format string shorthand syntax breaks compatiblity with older python versions

### ISSUE THREAD

**Issue by a25484189** [ktbyers/netmiko#1614]
Hello,

first: Thanks for your awesome work!
Netmiko is very useful for me, and solved a lot of problems i had.

But, although it breaks my heart to file an issue about this,
i think the project should switch back to the regular way of specifying format strings.

In Python3.6 the shorthand syntax `f"{var}"` was introduced to improve readability of format strings compared to the regular way of using `"{}".format(var)` .
I actually am a huge fan of this syntax and think its quite an improvement.

But this actually breaks compatibility with Python versions before 3.6 .
I understand that netmiko aims at 3.6 and 3.7 but, for example on ubuntu 16.04 LTS, Python3.5 is (sadly) still the regular python interpreter.

Since the new way is just a shorthand, and the regular way of specifying format strings is not deprecated or anything, i would suggests sticking to that since it enables a lot of devices to run netmiko out of the box.

I also made a pull request for this at #1613 ,
and i hope you decide to merge it.

Kind regards

**Comment by ktbyers** [comment]
@a25484189 Similar to the comment I made on the pull request...

Unfortunately, we don't support Python3.5. You need to use Python 3.6 or greater or alternatively Netmiko 2.4.2.

We intentionally switched almost entirely over to f-strings.

You should also be able to install Python 3.6 and build a Python 3.6 virtual environment.

Regards...Kirk

**Comment by a25484189** [comment]
Too bad, but understandable.
I'm fine with fixing the version to 2.4.2
In my personal opinion the moden f-strings are the way to go as well.
Keep up the great work =)
