### ISSUE TITLE
3.0.0 broken for many OS w/python3.5 

### ISSUE THREAD

**Issue by rob-barnes** [ktbyers/netmiko#1615]
File "[.......]/.local/lib/python3.5/site-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"

SyntaxError: invalid syntax

3.0.0 broken for many OS w/python3.5 
... like Ubuntu 16.04, which is not out of support until April 2021
which is used by tons of servers in the world.
all because of fstrings?
I regret ever using netmiko as a solution for the last few years, because deployments have almost always been met with new dependency problems.

please remove fstring dependency and support python 3.5... and quit playin around

**Comment by ktbyers** [comment]
You should be able to install Python 3.6 and use it in a virtual environment (you should be able to do this without affecting the system Python).

Alternatively, you can just install and use Netmiko 2.4.2.
