### ISSUE TITLE
Cisco router as terminal server and end device with different credentials

### ISSUE THREAD

**Issue by tars01** [ktbyers/netmiko#1618]
Kirk

I have been trying to use a Cisco router as a terminal server. I have been basing my script off examples I have seen logged in previous issues here and articles you have written: http://ktbyers.github.io/netmiko/COMMON_ISSUES.html

My process is as follows. I connect to a Cisco router, from there I need to telnet to Cisco cpe devices hanging off the router. I have actually managed to get this working fully and it works. The problem is it when I run the telnet command from the Router (terminal server) it's taking the username and password from the cisco_ios connect handler. So if the Cisco router (terminal server) and the end cpe device have the same passwords it works fine The problem is they are different. How can I specify different usernames and passwords just for my telnet commands? (I have commented where the issue is in my code below)

I thought maybe I could create a new connect handler with different credentials then just reference that e.g. :  net_connect.write_channel(net_connect_cpe.username + '\n')

The problem is I only need to specify the username and password, there is no IP address to be specified for the end cpe as that is taken care of in my script. Even if I did specify an IP address then when declaring it the Connect Handler it would then try and establish a session to that cpe ip and this won't be possible. I just need to be able to override the username and password for the cpes (they are all the same credentials) 

My code below:
==================
```python
ios_device = {
    'device_type': 'cisco_ios',
    'ip': ip_address_of_device,
    'username': 'admin',
    'password': 'admin',
    }


net_connect = ConnectHandler(**ios_device)

def cpe_telnet_function(cpe_ip, hostname_var, vrf=None):
    global cpe_telnet_result

    if vrf:
        telnet_output = net_connect.write_channel('telnet ' + cpe_ip + ' /vrf ' + vrf + '\r\n')
        time.sleep(5)
    else:
        telnet_output = net_connect.write_channel('telnet ' + cpe_ip + '\r\n')
        time.sleep(5)

    # Manually handle the Username and Password
    max_loops = 2
    i = 1
    while i <= max_loops:
        telnet_output = net_connect.read_channel()
        time.sleep(2)

        if 'refused' in telnet_output:
            cpe_telnet_result = 'refused'
            return

        if 'unreachable' in telnet_output:
            cpe_telnet_result = 'unreachable'
            return

        if 'No route to host' in telnet_output:
            cpe_telnet_result = 'No route to host'
            return

        if 'Username:' in telnet_output:
            net_connect.write_channel(net_connect.username + '\n') #this is where I am having a problem
            time.sleep(1)
            telnet_output = net_connect.read_channel()

        # Search for password pattern / send password
        if 'Password:' in telnet_output:
            net_connect.write_channel(net_connect.password + '\n') #this is where I am having a problem
            time.sleep(1)
            telnet_output = net_connect.read_channel()
            # Did we successfully login
            if '>' in telnet_output or '#' in telnet_output:
                cpe_telnet_result = ('auth_successful')
                break
            else:
                cpe_telnet_result = ('auth_failed')
                time.sleep(30)
                return
        else:
            cpe_telnet_result = ('unspecified_error')
            return

        i += 1

    show_run = net_connect.send_command("show run") #show run on end device
    time.sleep(2)
    print(show_run)
    net_connect.write_channel('exit' + '\r\n') #drop out of end cpe device back to Cisco terminal server
    time.sleep(5)
```

**Comment by ktbyers** [comment]
You can just overwrite the attributes in the middle of the connection (i.e. after you have connected to the terminal server, but before connecting to the router).

```python
net_connect.password = "new_pass"
net_connect.usename = "my_user"
```

Let me know if that works...

**Comment by tars01** [comment]
Hi Kirk,

Thank you, that actually works well. It's created another problem though. When the script carries on outside the function it works for a while then it fails. I can only assume that the ssh session has timed out so netconnect has attempted a new one and it's failed because the original credentials are different now. 

`    get_ip = net_connect.send_command('sh run interface ' + interface + ' | inc ip address')
  File "/home/mark/development_env/lib/python3.6/site-packages/netmiko/base_connection.py", line 1407, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: \%\ Authentication\ failed`

To try and rectify it, I set the credentials back to the original ones at the end of the function:

(inside function at the end)
    #set credentials back to cisco_ios credentials
    net_connect.username = "admin"
    net_connect.password = "admin"

It still fails though. I think because when I set the credentials back at the end of the function it's only within the function and not globally. 

I tried to make them Global variables at the top of the function but Python doesn't like it because of the netconnect part:

def cpe_telnet_function(cpe_ip, hostname_var, vrf=None):
    global cpe_telnet_result
    global net_connect.username
    global net_connect.password

Python error:
`(development_env) ➜  cpe-script python cmc-cpe.04.py
  File "cpe.04.py", line 59
    global net_connect.username
                      ^
SyntaxError: invalid syntax`

Any idea around this? 

Thank you

**Comment by ktbyers** [comment]
It looks like you probably need to add some `time.sleep` into your code and then clear the buffer `net_connect.clear_buffer`. 

This is after you have this event:

```
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is % Authentication failed
```

That `% Authentication failed` on the earlier device.

**Comment by tars01** [comment]
Hi Kirk

That didn't seem to work. I carried on troubleshooting then I added the below command to try help me identify what's happening but it seems to have started working now:

`telnet_output = net_connect.find_prompt()`

Not 100% sure why though, anyway I'm happy it's working, thanks!

Do you perhaps have some detailed documentation about all the options for netmiko?

One more question, when you enabling the debugging, how come the logs sometimes appear out of order and the commands are spread over multiple lines? 

Thanks for your help, I'm closing the issue.
