### ISSUE TITLE
Netmiko can't configure NX-OS

### ISSUE THREAD

**Issue by WindfuryARS** [ktbyers/netmiko#1619]
I used to use below script to configure box, but when I use py3, it's able to configure box only, but can't execute show cmd. Anyone could take a look?

```python
from netmiko import ConnectHandler
from datetime import datetime
import time
import sys
import os


def config_cmd():
    cisco = {
        'device_type': 'cisco_nxos',
        'host': '10.75.61.29',
        'username': 'admin',
        'password': 'cisco%123'
    }

    all_device = [cisco]


    for i in all_device:
        net_connect = ConnectHandler(**i)
        net_connect.send_config_set('conf ter ; interface loo500 ; ip address 200.1.1.1/32 ; copy r s')
        output = net_connect.send_command('show run interface loop400')
        print("\n\n----- config done  -----")
        print("\n\n----- new ip address  -----")
        print(output)
        print("----- End -----")
        with open("/Users/hancai/Desktop/config_hc", "w") as f:
            f.write(output)

while True:
    config_cmd()
    time.sleep(60)
```

HANCAI-M-C2TY:~ hancai$ python3 /Users/hancai/Desktop/ssh_device_config.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hancai/Desktop/ssh_device_config.py", line 31, in <module>
    config_cmd()
  File "/Users/hancai/Desktop/ssh_device_config.py", line 21, in config_cmd
    net_connect.send_config_set('conf ter ; interface loo500 ; ip address 200.1.1.1/32 ; copy r s')
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1726, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 552, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
```
net_connect.send_config_set('conf ter ; interface loo400 ; ip address 100.1.1.1/32 ; copy r s')
```

You shouldn't be doing either the "conf ter" or the "copy r s" as part of "send_config_set".

Netmiko will do the "conf ter" automatically for send_config_set()

Use the "save_config()" method for "copy r s"

Can you try it with those two changes? Also can you try the current Netmiko `develop` branch with those two changes as well?

**Comment by WindfuryARS** [comment]
> ```
> net_connect.send_config_set('conf ter ; interface loo400 ; ip address 100.1.1.1/32 ; copy r s')
> ```
> 
> You shouldn't be doing either the "conf ter" or the "copy r s" as part of "send_config_set".
> 
> Netmiko will do the "conf ter" automatically for send_config_set()
> 
> Use the "save_config()" method for "copy r s"
> 
> Can you try it with those two changes? Also can you try the current Netmiko `develop` branch with those two changes as well?


It's working! Thank you for great help. BTW, if I want to reload box, which method is correct?

**Comment by ktbyers** [comment]
Look at `send_command_timing` for doing the `reload`. You will have to handle any confirmations the device sends to you i.e. "Do you want to do this (Y/N)"...
