### ISSUE TITLE
Best way to use netmiko with Python 3.5 async / await keyword?

### ISSUE THREAD

**Issue by sivabudh** [ktbyers/netmiko#162]
Hello,

I am learning how to use this library with Tornado and Python 3.5 async / await keywords. I am not too entirely sure what's the best way to use netmiko with async / await.

Shall I simply wrap each netmiko api with a Future, and call await on each one?

**Comment by ktbyers** [comment]
@sivabudh Don't know...I haven't used async/await.

Personally I would probably just use threads or processes.

If you come up with a solution let me know and we can post it into the ./examples folder.

Kirk

**Comment by selfuryon** [comment]
@sivabudh, You can just use [netdev](https://github.com/selfuryon/netdev) library. It very similar to netmiko by public API but inside it uses asyncio so you can use it in an asynchronous way.

**Comment by ktbyers** [comment]
@selfuryon @sivabudh Yes, I would look at `netdev` if you want to use asyncio.

**Comment by sivabudh** [comment]
@selfuryon Whao. netdev looks cool. Did you take inspiration from netmiko?

**Comment by selfuryon** [comment]
@sivabudh Yes, netmiko was very useful for our company and I'd like it :) I researched asyncio at the same time so I decided to make a library like netmiko but only with using asynchrony.

**Comment by netvfi** [comment]
Is there any way to use netdev with RAS keys instead of passwords for login ?
