### ISSUE TITLE
Connection refused not captured

### ISSUE THREAD

**Issue by petermcd** [ktbyers/netmiko#1623]
If a device chooses to refuse a connection Netmiko is not currently capturing the relevant exception from Paramiko. We identified this under a circumstance in which the wrong credentials were being tried in a short amount of time causing the device to lock out on the 4th attempt, This is generating output such as:

```
:paramiko.transport:Exception: 
 reading SSH protocol banner[Errno 104] Connection reset by peer<br>
:paramiko.transport:Traceback (most recent call last):<br>
:paramiko.transport:  File /PATH_TO_FILES/lib/python3.6/site-packages/paramiko/transport.py, line 2211, in _check_banner<br>
:paramiko.transport:    buf = self.packetizer.readline(timeout)<br>
:paramiko.transport:  File /PATH_TO_FILES/lib/python3.6/site-packages/paramiko/packet.py, line 380, in readline<br>
:paramiko.transport:    buf  = self._read_timeout(timeout)<br>
:paramiko.transport:  File /PATH_TO_FILES/lib/python3.6/site-packages/paramiko/packet.py, line 607, in _read_timeout<br>
:paramiko.transport:    x = self.__socket.recv(128)<br>
:paramiko.transport:ConnectionReset
: [Errno 104] Connection reset by peer<br>
:paramiko.transport:<br>
:paramiko.transport:During handling of the above exception, another exception occurred:<br>
:paramiko.transport:<br>
:paramiko.transport:Traceback (most recent call last):<br>
:paramiko.transport:  File /PATH_TO_FILES/lib/python3.6/site-packages/paramiko/transport.py, line 2039, in run<br>
:paramiko.transport:    self._check_banner()<br>
:paramiko.transport:  File /PATH_TO_FILES/lib/python3.6/site-packages/paramiko/transport.py, line 2216, in _check_banner<br>
:paramiko.transport:    
 reading SSH protocol banner   str(e)<br>
:paramiko.transport:paramiko.ssh_exception.SSHException: 
 reading SSH protocol banner[Errno 104] Connection reset by peer<br>
:paramiko.transport:REDACTED
: paramiko.ssh_exception.SSHException: 
 reading SSH protocol banner[Errno 104] Connection reset by peer 
```

Some of the above information has been redacted but gives you the idea of what is happening.

This issue has previously been reported on issue #795

**Comment by tars01** [comment]
You have to enable exception handling:

`from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException

    try:
        net_connect = ConnectHandler(**ios_device)
    except (AuthenticationException):
        print('Authentication failure: ' + ip_address_of_device)
        application_log.write(ip_address_of_device + ', Authentication failure' + '\r\n')
        continue
    except (NetMikoTimeoutException):
        print('Timeout to device: ' + ip_address_of_device)
        application_log.write(ip_address_of_device + ', Timeout to device' + '\r\n')
        continue
    except (EOFError):
        print('End of file while attempting device ' + ip_address_of_device)
        continue
    except (SSHException):
        print('SSH Issue. Are you sure SSH is enabled? ' + ip_address_of_device)
        application_log.write(ip_address_of_device + ', Possible ssh issue' + '\r\n')
        continue
    except Exception as unknown_error:
        print('Some other error: ' + str(unknown_error))
        application_log.write(ip_address_of_device + ', Unknown issue' + '\r\n')
        continue`

**Comment by ktbyers** [comment]
Replaced with more generic issue:

https://github.com/ktbyers/netmiko/issues/1627
