### ISSUE TITLE
Cisco ASA fails on long configuration commands

### ISSUE THREAD

**Issue by roshanraj30** [ktbyers/netmiko#1625]
I've created a script which creates a huge object-group (2800+ IP Addresses and Subnet) in Cisco ASA. The send_config_set works fine when 'network-object host x.x.x.x' are encountered in the list, but as soon as a subnet/network appears in the list like 'network-object x.x.x.x 255.255.255.0', the subnet get added in the ASA but I get an error netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available., due to this the rest of the config is not executed

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compare.py", line 185, in <module>
    net_connect.send_config_set(newlistconf)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1726, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 552, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.`

I verified that the command are working fine if I directly login into the ASA and enter them.
I added a 'global_delay_factor': 4 but still facing the same issue.

I've attached the list of the object-group and netmiko debug logs (note that the error object already exists is because I was to lazy to remove the old commands)

[object-group list.txt](https://github.com/ktbyers/netmiko/files/4349914/object-group.list.txt)
[test.log](https://github.com/ktbyers/netmiko/files/4349915/test.log)

**Comment by ktbyers** [comment]
Try adding the following argument to ConnectHandler:

`allow_auto_change = True`

And see if that fixes the issue.

Basically, the broader issue is that the command `terminal width 511` is a configuration command on the ASA and people didn't want this automatically changed by Netmiko (so you have to say that it is okay).

The more particular issue is that with the default terminal width, the ASA tries to make the output more human readable by modifying it (for long commands). This messes up Netmiko.

**Comment by roshanraj30** [comment]
Thanks a lot, that solved my issue!

> Try adding the following argument to ConnectHandler:
> 
> `allow_auto_change = True`
> 
> And see if that fixes the issue.
> 
> Basically, the broader issue is that the command `terminal width 511` is a configuration command on the ASA and people didn't want this automatically changed by Netmiko (so you have to say that it is okay).
> 
> The more particular issue is that with the default terminal width, the ASA tries to make the output more human readable by modifying it (for long commands). This messes up Netmiko.
