### ISSUE TITLE
Build a better handler in send_command for long-running (slow) commands

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#163]

**Comment by wmann** [comment]
Is there a way to improve buffers or timeouts. I'm trying to fetch a show run from different HP Procurve switches? It works well on the access switches with about 4 KB of config. But I'm not able to fetch the show run from the CORE switches. Te config of the CORE switches is about 24 KB.

**Comment by ktbyers** [comment]
@wmann Can you provide more details on what happens? Does it only get part of the data or does it generate an error/exception?

If you get an error/exception, please post it.

**Comment by verbosemode** [comment]
My workaround for "verify /md5" for example is setting delay_factor to 1.0 and max_loops to 30. This results in a timeout which is close to 30 (~31.5) seconds. Maybe adding a "timeout" parameter to the method which implicitly modifies delay_factor and max_loops would do the trick.

**Comment by wmann** [comment]
I don't get any error.
On the switch where it works it looks like this

### BEGIN OUTPUT ###
config term
ACCESS(config)# show run

Running configuration:

; J9776A Configuration Editor; Created on release #YA.15.17.0009
; Ver #07:c3.84.9c.63.ff.37.27:50
hostname "ACCESS"
....
complete config
...


ACCESS(config)# end
ACCESS# 
### END OUTPUT ###

on the CORE the output looks like this

### BEGIN OUTPUT ###
config term
CORE1(config)# show run

Running configuration:

end
CORE1# ### END OUTPUT ###

If I ran the show run command manually after the output "Running configuration" there is a delay of a few seconds before the config shows up.

**Comment by wmann** [comment]
Google brought me also to Issue #97 which might be same. Could you please provide me a hint how and where to adjust the delay_factor?

**Comment by verbosemode** [comment]
@wmann Sorry for hijacking the conversation. My comment was rather on the issues topic than on the problem with incomplete configs. Which basically means my comment won't help in your case

**Comment by wmann** [comment]
@verbosemode delay_factor was totally what I was looking for. I figured out how to increase the delay factor for the "show run" from 0.5 to 2 and now it is able to get the full config from switch. 
I have another prob but this has nothing to do with long running commands so I will open another post.

Thanks for your support

**Comment by ktbyers** [comment]
@wmann You could also use the send_command_expect() method for slow running commands. This command will essentially wait until the router prompt is detected to complete (so it handles slow running commands better).

The delay_factor option is also totally valid.
