### ISSUE TITLE
Ciena SAOS Error when creating State-Dumps with corefiles / datapath

### ISSUE THREAD

**Issue by raffzwo** [ktbyers/netmiko#1635]
Hi there,
I recently started programming a bit with Python and have now created a program that creates state dumps on Ciena devices and copies them to my server via SFTP. However, I get the following error when I include the include-corefiles or include-datapath option.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
>     out = self.in_buffer.read(nbytes, self.timeout)
>   File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
>     raise PipeTimeout()
> paramiko.buffered_pipe.PipeTimeout
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
>     new_data = self.remote_conn.recv(MAX_BUFFER)
>   File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
>     raise socket.timeout()
> socket.timeout
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "script.py", line 72, in create_sd
>     create_sd_dp_cf(sw_connection, ip)
>   File "script.py", line 157, in create_sd_dp_cf
>     sw_output = sw_connection.send_command('system state-dump file-name ' + ip + '_sd_dp_cf_timestamp_' + str(date.hour) + '_' + str(date.minute) + '_' + str(date.second) + ' include-datapath include-corefiles', delay_factor=5)
>   File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1366, in send_command
>     new_data = self.read_until_pattern(pattern=re.escape(cmd))
>   File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 618, in read_until_pattern
>     return self._read_channel_expect(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 552, in _read_channel_expect
>     "Timed-out reading channel, data not available."
> netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

I have already looked at posts from other users and if I did everything correctly, their fixes didn't really help me. For example increasing the global delay timer. I found that in another post here. Of course, it cannot be ruled out that I missed something. Any help is appreciated.
If you want me to provide any information, just let me know.
Thanks a lot!

**Comment by ktbyers** [comment]
You need to turn cmd_verify off (or investigate why it is failing on this Ciena device).

You can do this in Netmiko 3.1.0 (which was just released) by using the send_command "cmd_verify=False" argument or by using the "global_cmd_verify=False" argument to ConnectHandler.

If you want to investigate more why cmd_verify is failing, let me know...

**Comment by raffzwo** [comment]
This looks very good. Thank you for the quick update.
