### ISSUE TITLE
find_prompt fails if Cisco Nexus devices have enabled "terminal color persist"

### ISSUE THREAD

**Issue by smnmtzgr** [ktbyers/netmiko#164]
Hi Kirk, at first thanks for your great work!
I've found an issue that happens when the user which is used for netmiko connects to a Cisco NX-OS device and has enabled "terminal color persist" on this device. 
The prompt of the device cant be found correctly in this situation because it doesnt end with the primary or secondary character (# or >). The colored prompt is formatted as described here: https://en.wikipedia.org/wiki/ANSI_escape_code

Logically your function doesnt find the prompt. I think there are 2 solutions for this:
1) Dont use colors for the user running ansible ("no terminal color persist"). :)
2) Change the function find_prompt to work with colored prompts (I think this would be too much overhead).

At last I want to give you an example (VSM-LAN-K has enabled "terminal color persist" for my user):

python (interactive shell):
<pre>
>>> from netmiko import ConnectHandler
>>> net_connect = ConnectHandler(device_type='cisco_nxos', ip='10.10.10.1', username='admin', password='password')
SSH connection established to 10.10.10.1:22
Interactive SSH session established
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 65, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 63, in __init__
    self.session_preparation()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 77, in session_preparation
    self.set_base_prompt()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 281, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: VSM-LAN-K#
</pre>

**Comment by ktbyers** [comment]
@smnmtzgr And the problem goes away when 'terminal color persist' is disable?

**Comment by smnmtzgr** [comment]
Yes it goes away. Thats definitively the problem. My co-worker made a fix to it: https://github.com/Benedikt1992/netmiko/commit/71e50105569977bbeb62c280ae00030264900a16

The "terminal color persist" is a per user-based command. If you enter "no terminal color persist" (thats default) there is no colored prompt in NX-OS and all is fine.

**Comment by ktbyers** [comment]
@smnmtzgr Yes, I don't think we should do anything here. The default on the NEXUS is to have this disabled so someone would have had to enable this.

An alternate fix would be to send a direct command to unconfigure this and then reconfigure this at the end of the session. 

You would have to override the default code, however, as the initial connection fails.
