### ISSUE TITLE
Error para salir de  console(config-if)#

### ISSUE THREAD

**Issue by vjuagar** [ktbyers/netmiko#1644]
Hello, I have a problem to exit the configuration mode of an interface, I cannot get out of the configuration of the same, I have tried to send the command "exit" and "end", neither has worked for me and the command "net_connect.exit_config_mode () "has not worked for me either.
Greetings

**Comment by ktbyers** [comment]
Standard process would be to use `send_config_set(list_of_commands)` and then netmiko will automatically enter and exit config mode.
