### ISSUE TITLE
upgrade from version 2.4.1 to upper version limit send_command() char length

### ISSUE THREAD

**Issue by lucamotterle** [ktbyers/netmiko#1651]
In version 2.4.1 I'm able to send command with a length counting more than 100 chars. After upgrading, I tested 3.0.0 and 3.1, command seems limit to 40 char max.

Thanks

**Comment by ktbyers** [comment]
@lucamotterle Can you re-test your issue using the `develop` branch and see if you still see issues?

**Comment by lucamotterle** [comment]
I will do a test next week.

Thanks

**Comment by Dr-Packet** [comment]
@lucamotterle - Did the suggestion resolve your issue?

**Comment by lucamotterle** [comment]
It works with the develop branch.

Thanks

**Comment by reddyarun474** [comment]
I am facing the same issue with netmiko version 3.4.0, can someone suggest me a workaround for it.
In my case I am having 770 char length using it on f5_linux device.

**Comment by ktbyers** [comment]
@reddyarun474 You should open a new issue. You will need to provide some more details on what the issue you are running into is.

A full stack exception trace is helpful.

**Comment by reddyarun474** [comment]
Raised new issue #2445. Please have a look once.
