### ISSUE TITLE
Nornir/Netmiko - Piped device commands fail after update to Netmiko 3.0

### ISSUE THREAD

**Issue by friday963** [ktbyers/netmiko#1656]
After updating from netmiko 2.4.2 to netmiko 3.0 (python 3.7.4)  I'm unable to run commands with pipes.  I'm getting netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.  After seeing some suggestion I added cmd_verify=False but it continued to fail.  I've had this behavior for two vendors Alcatel Lucent, and Juniper.  Here is the function I'm calling and the output.

`    def getVlansOnIntf(self, intf):
        """

        :param intf: local interface you want to check for vlans present.
        :return: return all vlans as a list if they are present.  If none are present return none.
        """
        vlans = self.hosts.run(
            task=netmiko_send_command,
            command_string=f"""show configuration interface {intf} | display set | match vlan-id""", cmd_verify=False
        )
        print_result(vlans)
        vlanlist = re.findall("vlan-id\s+(\d+)", vlans[self.hostname][0].result)
        if vlanlist:
            return vlanlist
        else:
            return None`

`netmiko_send_command************************************************************
* PX3-HE-CAR-Automate01 ** changed : False *************************************
vvvv netmiko_send_command ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv INFO
show configuration interface ae1
                                                  ^
syntax error.

autoeng@PX3-HE-CAR-Automate01> show configuration interface ae1   |interface ae1 interface ae1dinterface ae1iinterface ae1sinterface ae1pinterface ae1linterface ae1ainterface ae1yinterface ae1 interface ae1sinterface ae1einterface ae1tinterface ae1 interface ae1|interface ae1 interface ae1minterface ae1ainterface ae1tinterface ae1cinterface ae1hinterface ae1 interface ae1vinterface ae1linterface ae1ainterface ae1ninterface ae1-interface ae1iinterface ae1dinterface ae1
error: syntax error: ae1

^^^^ END netmiko_send_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by ktbyers** [comment]
Are you still having this issue?

**Comment by friday963** [comment]
The problem still exists, however I moved back to netmiko 2.4.2 to escape the issue since the project needed to move forward.  I can close this if you want since it would be difficult for me to reproduce the issue at this stage of my project.
