### ISSUE TITLE
How can I put the "enable password" when login with SSH?

### ISSUE THREAD

**Issue by dennisjian** [ktbyers/netmiko#166]
Hi Kirk, 

If the user I used to login to a Cisco router is not privilege 15 and a "enable" password is required, how can I put in that "eanble password'?

I noticed that I can use "•	net_connect.enable() " to enter the enable mode. But can it take the "password" argument? 

Thanks & regards,

Dennis

**Comment by ktbyers** [comment]
@dennisjian Add a 'secret' argument when you create the connection argument. Then just call the .enable() method.

**Comment by 1-61803** [comment]
@ktbyers, could you please add to the [tutorial](https://pynet.twb-tech.com/blog/automation/netmiko.html) that `.enable()` is required for most show commands and for configuration mode. A 'secret' key/argument might led to think that the connection automatically handles this, when it's not — it certainly did to me.

**Comment by ktbyers** [comment]
It is on the README here:

```
https://github.com/ktbyers/netmiko
```

Regards, Kirk

**Comment by 1-61803** [comment]
@ktbyers, well, in the README it's not in context. And it would do no harm adding it to the tutorial in the right place.

**Comment by mferreira85** [comment]
Hello,

Please how can i add the super password on the hp_comware lines?

Thank you,
Marcelo

**Comment by ktbyers** [comment]
@mferreira85 There is a bug on `super` and Comware see:

https://github.com/ktbyers/netmiko/issues/542

You would have to manually do it until this gets fixed. You can use `write_channel` and `read_channel` methods to manually do it (or possibly the `send_command_timing` method).

**Comment by mferreira85** [comment]
Excellent @ktbyers Thank you!

I would also like to congratulate you for this great code! It's helping a lot.

Thank you,
Marcelo
