### ISSUE TITLE
Vyatta needs terminal width set

### ISSUE THREAD

**Issue by achhabr1** [ktbyers/netmiko#1660]
I have vyatta OS box which I am trying to configure via send_config_from_file method. I ran across some errors and while reading up on other issues had to revert it Netmiko 2.XX behavior by setting cmd_verify=False. 

Here is output of my session log. I am not able to identify what might be causing this. 

<----- This is with cmd_verify= False ----->

********@wb-xsm-1006:~$ exit
tail: output.txt: file truncated
Welcome to AT&T vRouter 
Version:      1908f
Description:  AT&T vRouter 5600 1908f VNF
Linux wb-xsm-1006 4.19.0-trunk-********-amd64 #1 SMP PREEMPT Debian 4.19.93-0********5+1.3 (2020-01-29) x86_64
********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ configure

[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# set protocols ospf process 65 area 0 network '10.33.50.0/'
[edit]
********@wb-xsm-1006# set protocols ospf process 65 parameters router-id '10.33.50.
.2'
[edit]
********@wb-xsm-1006# set routing routing-instance sdn_102 protocols ospf process 1
102 area 0 network 10.33.51.0/24
set routing routing-instance sdn_102 protocols ospf process 102 parameters router-id 10.33.51.2
[edit]
********@wb-xsm-1006# set routing routing-instance sdn_102 protocols ospf process 1
102 parameters router-id 10.33.51.2
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# commit
[security vpn ipsec ike-group nmt-ike-group dead-peer-detection timeout 120]
Warning: Keep-alive timeout only applied to IKEv1 connections.

[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# exit
exit
********@wb-xsm-1006:~$ 

<------ This is cmd_verify = True ------->
 
********@wb-xsm-1006:~$ exit
tail: output.txt: file truncated
Welcome to AT&T vRouter 
Version:      1908f
Description:  AT&T vRouter 5600 1908f VNF
Linux wb-xsm-1006 4.19.0-trunk-********-amd64 #1 SMP PREEMPT Debian 4.19.93-0********5+1.3 (2020-01-29) x86_64
Last login: Mon Apr  6 17:26:05 2020 from fd:192:168:64::4
********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ set terminal length 0
********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ configure

[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# load /config/wb-xsm-1006-base-config.conf
Configuration loaded from '/config/wb-xsm-1006-base-config.conf' will replace the existing configuration
Use 'compare' to view the changes, or 'commit' to make them active
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# commit
[security vpn ipsec ike-group nmt-ike-group dead-peer-detection timeout 120]
Warning: Keep-alive timeout only applied to IKEv1 connections.

[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# exit
exit
********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ configure

[edit]
********@wb-xsm-1006# 
[edit]
**********@wb-xsm-1006# set protocols ospf process 65 area 0 network '10.33.50.0/'
[edit]
********@wb-xsm-1006# set protocols ospf process 65 parameters router-id '10.33.50.
.2'
[edit]
********@wb-xsm-1006# exit
^C**

I could not understand why it didn't read the whole file. 

Here is more python debugger info 

connect = <netmiko.vyos.vyos_ssh.VyOSSSH object at 0x7fd90a975c18>
file_name = '/home/ac043s/software/python_development/vyatta/automation/tests/config_files/ospf/cfgospf001-1006.txt'

    def apply_config_from_file(connect, file_name):
    
        apply_config_flag = True
    
        try:
            param = {
                'cmd_verify': True
            }
            output = connect.send_config_from_file(config_file=file_name, **param)
            logging.info(output)
            time.sleep(0.1)
    
            output = connect.commit(delay_factor=5)
            logging.info(output)
    
            output = connect.exit_config_mode()
            logging.info(output)
        except:
            logging.info("Error while applying configuration!")
            apply_config_flag = False
>           sys.exit(0)
E           SystemExit: 0

../../vyatta_modules.py:25: SystemEx

vyatta@wb-xsm-1006:~$  (vyatta_modules.py:53)
2020-04-06 13:29:26 [    INFO] Configuring wb-xsm-1006 for test case OSPF001 (test_OSPF001.py:47)
2020-04-06 13:29:51 [    INFO] Error while applying configuration! (vyatta_modules.py:23)

‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï test_OSPF_001 ‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï‚Äï

self = <paramiko.Channel 0 (open) window=2096921 -> <paramiko.Transport at 0xa975da0 (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>, nbytes = 65535

    def recv(self, nbytes):
        """
        Receive data from the channel.  The return value is a string
        representing the data received.  The maximum amount of data to be
        received at once is specified by ``nbytes``.  If a string of
        length zero is returned, the channel stream has closed.
    
        :param int nbytes: maximum number of bytes to read.
        :return: received data, as a ``str``/``bytes``.
    
        :raises socket.timeout:
            if no data is ready before the timeout set by `settimeout`.
        """
        try:
>           out = self.in_buffer.read(nbytes, self.timeout)

/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/paramiko/channel.py:699: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <paramiko.buffered_pipe.BufferedPipe object at 0x7fd90a979a90>, nbytes = 65535, timeout = -0.00018215179443359375

    def read(self, nbytes, timeout=None):
        """
        Read data from the pipe.  The return value is a string representing
        the data received.  The maximum amount of data to be received at once
        is specified by ``nbytes``.  If a string of length zero is returned,
        the pipe has been closed.
    
        The optional ``timeout`` argument can be a nonnegative float expressing
        seconds, or ``None`` for no timeout.  If a float is given, a
        `.PipeTimeout` will be raised if the timeout period value has elapsed
        before any data arrives.
    
        :param int nbytes: maximum number of bytes to read
        :param float timeout:
            maximum seconds to wait (or ``None``, the default, to wait forever)
        :return: the read data, as a ``str`` or ``bytes``
    
        :raises:
            `.PipeTimeout` -- if a timeout was specified and no data was ready
            before that timeout
        """
        out = bytes()
        self._lock.acquire()
        try:
            if len(self._buffer) == 0:
                if self._closed:
                    return out
                # should we block?
                if timeout == 0.0:
                    raise PipeTimeout()
                # loop here in case we get woken up but a different thread has
                # grabbed everything in the buffer.
                while (len(self._buffer) == 0) and not self._closed:
                    then = time.time()
                    self._cv.wait(timeout)
                    if timeout is not None:
                        timeout -= time.time() - then
                        if timeout <= 0.0:
>                           raise PipeTimeout()
E                           paramiko.buffered_pipe.PipeTimeout

/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/paramiko/buffered_pipe.py:164: PipeTimeout

During handling of the above exception, another exception occurred:

self = <netmiko.vyos.vyos_ssh.VyOSSSH object at 0x7fd90a975c18>
pattern = "set\\ protocols\\ ospf\\ process\\ 65\\ parameters\\ router\\-id\\ \\'10\\.33\\.50\\.2\\'", re_flags = 0, max_loops = 1000

    def _read_channel_expect(self, pattern="", re_flags=0, max_loops=150):
        """Function that reads channel until pattern is detected.
    
        pattern takes a regular expression.
    
        By default pattern will be self.base_prompt
    
        Note: this currently reads beyond pattern. In the case of SSH it reads MAX_BUFFER.
        In the case of telnet it reads all non-blocking data.
    
        There are dependencies here like determining whether in config_mode that are actually
        depending on reading beyond pattern.
    
        :param pattern: Regular expression pattern used to identify the command is done \
        (defaults to self.base_prompt)
        :type pattern: str (regular expression)
    
        :param re_flags: regex flags used in conjunction with pattern to search for prompt \
        (defaults to no flags)
        :type re_flags: int
    
        :param max_loops: max number of iterations to read the channel before raising exception.
            Will default to be based upon self.timeout.
        :type max_loops: int
        """
        output = ""
        if not pattern:
            pattern = re.escape(self.base_prompt)
        log.debug(f"Pattern is: {pattern}")
    
        i = 1
        loop_delay = 0.1
        # Default to making loop time be roughly equivalent to self.timeout (support old max_loops
        # argument for backwards compatibility).
        if max_loops == 150:
            max_loops = int(self.timeout / loop_delay)
        while i < max_loops:
            if self.protocol == "ssh":
                try:
                    # If no data available will wait timeout seconds trying to read
                    self._lock_netmiko_session()
>                   new_data = self.remote_conn.recv(MAX_BUFFER)

/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/netmiko/base_connection.py:550: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <paramiko.Channel 0 (open) window=2096921 -> <paramiko.Transport at 0xa975da0 (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>, nbytes = 65535

    def recv(self, nbytes):
        """
        Receive data from the channel.  The return value is a string
        representing the data received.  The maximum amount of data to be
        received at once is specified by ``nbytes``.  If a string of
        length zero is returned, the channel stream has closed.
    
        :param int nbytes: maximum number of bytes to read.
        :return: received data, as a ``str``/``bytes``.
    
        :raises socket.timeout:
            if no data is ready before the timeout set by `settimeout`.
        """
        try:
            out = self.in_buffer.read(nbytes, self.timeout)
        except PipeTimeout:
>           raise socket.timeout()
E           socket.timeout

/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/paramiko/channel.py:701: timeout

During handling of the above exception, another exception occurred:

connect = <netmiko.vyos.vyos_ssh.VyOSSSH object at 0x7fd90a975c18>
file_name = '/home/ac043s/software/python_development/vyatta/automation/tests/config_files/ospf/cfgospf001-1006.txt'

    def apply_config_from_file(connect, file_name):
    
        apply_config_flag = True
    
        try:
            param = {
                'cmd_verify': True
            }
>           output = connect.send_config_from_file(config_file=file_name, **param)

../../vyatta_modules.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <netmiko.vyos.vyos_ssh.VyOSSSH object at 0x7fd90a975c18>
config_file = '/home/ac043s/software/python_development/vyatta/automation/tests/config_files/ospf/cfgospf001-1006.txt', kwargs = {'cmd_verify': True}
cfg_file = <_io.TextIOWrapper name='/home/ac043s/software/python_development/vyatta/automation/tests/config_files/ospf/cfgospf001-1006.txt' mode='rt' encoding='utf-8'>

    def send_config_from_file(self, config_file=None, **kwargs):
        """
        Send configuration commands down the SSH channel from a file.
    
        The file is processed line-by-line and each command is sent down the
        SSH channel.
    
        **kwargs are passed to send_config_set method.
    
        :param config_file: Path to configuration file to be sent to the device
        :type config_file: str
    
        :param kwargs: params to be sent to send_config_set method
        :type kwargs: dict
        """
        with io.open(config_file, "rt", encoding="utf-8") as cfg_file:
>           return self.send_config_set(cfg_file, **kwargs)

/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/netmiko/base_connection.py:1665: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <netmiko.vyos.vyos_ssh.VyOSSSH object at 0x7fd90a975c18>
config_commands = <_io.TextIOWrapper name='/home/ac043s/software/python_development/vyatta/automation/tests/config_files/ospf/cfgospf001-1006.txt' mode='rt' encoding='utf-8'>
exit_config_mode = False, kwargs = {'cmd_verify': True}

    def send_config_set(self, config_commands=None, exit_config_mode=False, **kwargs):
        """Remain in configuration mode."""
        return super().send_config_set(
>           config_commands=config_commands, exit_config_mode=exit_config_mode, **kwargs
        )

/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/netmiko/vyos/vyos_ssh.py:100: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <netmiko.vyos.vyos_ssh.VyOSSSH object at 0x7fd90a975c18>
config_commands = <_io.TextIOWrapper name='/home/ac043s/software/python_development/vyatta/automation/tests/config_files/ospf/cfgospf001-1006.txt' mode='rt' encoding='utf-8'>
exit_config_mode = False, delay_factor = 1, max_loops = 150, strip_prompt = False, strip_command = False, config_mode_command = None, cmd_verify = True
enter_config_mode = True

    def send_config_set(
        self,
        config_commands=None,
        exit_config_mode=True,
        delay_factor=1,
        max_loops=150,
        strip_prompt=False,
        strip_command=False,
        config_mode_command=None,
        cmd_verify=True,
        enter_config_mode=True,
    ):
        """
        Send configuration commands down the SSH channel.
    
        config_commands is an iterable containing all of the configuration commands.
        The commands will be executed one after the other.
    
        Automatically exits/enters configuration mode.
    
        :param config_commands: Multiple configuration commands to be sent to the device
        :type config_commands: list or string
    
        :param exit_config_mode: Determines whether or not to exit config mode after complete
        :type exit_config_mode: bool
    
        :param delay_factor: Factor to adjust delays
        :type delay_factor: int
    
        :param max_loops: Controls wait time in conjunction with delay_factor (default: 150)
        :type max_loops: int
    
        :param strip_prompt: Determines whether or not to strip the prompt
        :type strip_prompt: bool
    
        :param strip_command: Determines whether or not to strip the command
        :type strip_command: bool
    
        :param config_mode_command: The command to enter into config mode
        :type config_mode_command: str
    
        :param cmd_verify: Whether or not to verify command echo for each command in config_set
        :type cmd_verify: bool
    
        :param enter_config_mode: Do you enter config mode before sending config commands
        :type exit_config_mode: bool
    
        """
        delay_factor = self.select_delay_factor(delay_factor)
        if config_commands is None:
            return ""
        elif isinstance(config_commands, str):
            config_commands = (config_commands,)
    
        if not hasattr(config_commands, "__iter__"):
            raise ValueError("Invalid argument passed into send_config_set")
    
        # Send config commands
        output = ""
        if enter_config_mode:
            cfg_mode_args = (config_mode_command,) if config_mode_command else tuple()
            output += self.config_mode(*cfg_mode_args)
    
        if self.fast_cli:
            for cmd in config_commands:
                self.write_channel(self.normalize_cmd(cmd))
            # Gather output
            output += self._read_channel_timing(
                delay_factor=delay_factor, max_loops=max_loops
            )
        elif not cmd_verify:
            for cmd in config_commands:
                self.write_channel(self.normalize_cmd(cmd))
                time.sleep(delay_factor * 0.05)
            # Gather output
            output += self._read_channel_timing(
                delay_factor=delay_factor, max_loops=max_loops
            )
        else:
            for cmd in config_commands:
                self.write_channel(self.normalize_cmd(cmd))
    
                # Make sure command is echoed
>               new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))

/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/netmiko/base_connection.py:1750: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <netmiko.vyos.vyos_ssh.VyOSSSH object at 0x7fd90a975c18>, args = ()
kwargs = {'pattern': "set\\ protocols\\ ospf\\ process\\ 65\\ parameters\\ router\\-id\\ \\'10\\.33\\.50\\.2\\'"}

    def read_until_pattern(self, *args, **kwargs):
        """Read channel until pattern detected. Return ALL data available."""
>       return self._read_channel_expect(*args, **kwargs)

/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/netmiko/base_connection.py:627: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <netmiko.vyos.vyos_ssh.VyOSSSH object at 0x7fd90a975c18>
pattern = "set\\ protocols\\ ospf\\ process\\ 65\\ parameters\\ router\\-id\\ \\'10\\.33\\.50\\.2\\'", re_flags = 0, max_loops = 1000

    def _read_channel_expect(self, pattern="", re_flags=0, max_loops=150):
        """Function that reads channel until pattern is detected.
    
        pattern takes a regular expression.
    
        By default pattern will be self.base_prompt
    
        Note: this currently reads beyond pattern. In the case of SSH it reads MAX_BUFFER.
        In the case of telnet it reads all non-blocking data.
    
        There are dependencies here like determining whether in config_mode that are actually
        depending on reading beyond pattern.
    
        :param pattern: Regular expression pattern used to identify the command is done \
        (defaults to self.base_prompt)
        :type pattern: str (regular expression)
    
        :param re_flags: regex flags used in conjunction with pattern to search for prompt \
        (defaults to no flags)
        :type re_flags: int
    
        :param max_loops: max number of iterations to read the channel before raising exception.
            Will default to be based upon self.timeout.
        :type max_loops: int
        """
        output = ""
        if not pattern:
            pattern = re.escape(self.base_prompt)
        log.debug(f"Pattern is: {pattern}")
    
        i = 1
        loop_delay = 0.1
        # Default to making loop time be roughly equivalent to self.timeout (support old max_loops
        # argument for backwards compatibility).
        if max_loops == 150:
            max_loops = int(self.timeout / loop_delay)
        while i < max_loops:
            if self.protocol == "ssh":
                try:
                    # If no data available will wait timeout seconds trying to read
                    self._lock_netmiko_session()
                    new_data = self.remote_conn.recv(MAX_BUFFER)
                    if len(new_data) == 0:
                        raise EOFError("Channel stream closed by remote device.")
                    new_data = new_data.decode("utf-8", "ignore")
                    if self.ansi_escape_codes:
                        new_data = self.strip_ansi_escape_codes(new_data)
                    log.debug(f"_read_channel_expect read_data: {new_data}")
                    output += new_data
                    self._write_session_log(new_data)
                except socket.timeout:
                    raise NetmikoTimeoutException(
>                       "Timed-out reading channel, data not available."
                    )
E                   netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/netmiko/base_connection.py:561: NetmikoTimeoutException

During handling of the above exception, another exception occurred:

**Comment by ktbyers** [comment]
Does Vyatta have a way to set the terminal width?

**Comment by achhabr1** [comment]
looks like they do 

vyatta@wb-xsm-1006:~$ set terminal 
Possible completions:
  key       Set key behaviors
  length    Set terminal rows
  pager     Set to use default pager (less)
  width     Set terminal columns

      
vyatta@wb-xsm-1006:~$ set terminal width 
Possible completions:
  <NUMBER>  Set terminal to given number of columns

      
vyatta@wb-xsm-1006:~$ set terminal width

**Comment by ktbyers** [comment]
Do they accept a value of 511 or 512 here?

If you do this, does it fix the issue?


Kirk

**Comment by achhabr1** [comment]
vyatta does art it without going in to operational mode. I see it getting setup as soon as the connection open up. Is there a way I can at least modify this behavior and test. I did it manually but it not make any difference.

**Comment by achhabr1** [comment]
I added this and seems like the problem is solved thanks 

param = {
            'cmd_verify': True
        }
        output = connect.set_terminal_width(command='set terminal width 512')
        logging.info(output)
        
        output = connect.send_config_from_file(config_file=file_name, **param)
        logging.info(output)

Linux wb-xsm-1006 4.19.0-trunk-********-amd64 #1 SMP PREEMPT Debian 4.19.93-0********5+1.3 (2020-01-29) x86_64
Last login: Mon Apr  6 18:12:31 2020 from fd:192:168:64::4
********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ set terminal length 0
********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ configure

[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# load /config/wb-xsm-1006-base-config.conf
Configuration loaded from '/config/wb-xsm-1006-base-config.conf'
No configuration changes to commit
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# commit

  No configuration changes to commit

[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# exit
exit
********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ set terminal width 512

********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ configure

[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# set protocols ospf process 65 area 0 network '10.33.50.0/24'
[edit]
********@wb-xsm-1006# set protocols ospf process 65 parameters router-id '10.33.50.2'
[edit]
********@wb-xsm-1006# set routing routing-instance sdn_102 protocols ospf process 102 area 0 network 10.33.51.0/24
[edit]
********@wb-xsm-1006# set routing routing-instance sdn_102 protocols ospf process 102 parameters router-id 10.33.51.2
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# commit
[security vpn ipsec ike-group nmt-ike-group dead-peer-detection timeout 120]
Warning: Keep-alive timeout only applied to IKEv1 connections.



[edit]
********@wb-xsm-1006# 
[edit]
********@wb-xsm-1006# exit
exit
********@wb-xsm-1006:~$ 
********@wb-xsm-1006:~$ exit

**Comment by ktbyers** [comment]
Okay, we should do a pull request and embed this into the Vyatta driver.

**Comment by ktbyers** [comment]
Should be fixed in this PR:

https://github.com/ktbyers/netmiko/pull/1673
