### ISSUE TITLE
send_command for long commands in linux resulted in 'Timed-out reading channel, data not available.' for netmiko >= 3.x

### ISSUE THREAD

**Issue by kielpi** [ktbyers/netmiko#1661]
Following conversation with Centos7 resulted in timeout:

`
DEBUG:netmiko:write_channel: b'ssh -o ConnectTimeout=5 -o NumberOfPasswordPrompts=1  -o KexAlgorithms=diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss  -o ServerAliveInterval=5 admin@192.168.0.1\n'
DEBUG:netmiko:Pattern is: ssh\ \-o\ ConnectTimeout=5\ \-o\ NumberOfPasswordPrompts=1\ \ \-o\ KexAlgorithms=diffie\-hellman\-group1\-sha1\ \-o\ HostKeyAlgorithms=\+ssh\-dss\ \ \-o\ ServerAliveInterval=5\ admin@192\.168\.0\.1
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'ssh -o ConnectTimeout=5 -o NumberOfPasswordPrompts=1  -o KexA \rlgorithms=diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss  -o ServerAli \rveInterval=5 admin@192.168.0.1\r\n'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = ssh -o ConnectTimeout=5 -o NumberOfPasswordPrompts=1  -o KexA 
lgorithms=diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss  -o ServerAli 
veInterval=5 admin@192.168.0.1

DEBUG:netmiko:repr = 'ssh -o ConnectTimeout=5 -o NumberOfPasswordPrompts=1  -o KexA \rlgorithms=diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss  -o ServerAli \rveInterval=5 admin@192.168.0.1\r\n'
DEBUG:netmiko:_read_channel_expect read_data: ssh -o ConnectTimeout=5 -o NumberOfPasswordPrompts=1  -o KexA 
lgorithms=diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss  -o ServerAli 
veInterval=5 admin@192.168.0.1
`

Synchronization code" added to send_command in Netmiko 3.x cause timeout as search pattern for long command cannot be matched due to its distortion when terminal length is less than command length. Function returns 0 length string despite attached log. To make matter worse set_terminal_width do not resolve the issue. Also commands on Linux can be much longer then possible console width. 
[log.txt](https://github.com/ktbyers/netmiko/files/4452265/log.txt)

Till 2.4.2 everything was fine.

This is new code in base_connection
`        new_data = ""

        cmd = command_string.strip()
        # if cmd is just an "enter" skip this section
        if cmd and cmd_verify:
            # Make sure you read until you detect the command echo (avoid getting out of sync)
            new_data = self.read_until_pattern(pattern=re.escape(cmd))
            new_data = self.normalize_linefeeds(new_data)
            # Strip off everything before the command echo (to avoid false positives on the prompt)
            if new_data.count(cmd) == 1:
                new_data = new_data.split(cmd)[1:]
                new_data = self.RESPONSE_RETURN.join(new_data)
                new_data = new_data.lstrip()
                new_data = f"{cmd}{self.RESPONSE_RETURN}{new_data}"
`

cannot cross the line

`new_data = self.read_until_pattern(pattern=re.escape(cmd))`

**Comment by kielpi** [comment]
[log.txt](https://github.com/ktbyers/netmiko/files/4452269/log.txt)

**Comment by ktbyers** [comment]
Duplicate with this issue:

https://github.com/ktbyers/netmiko/issues/1544

Need to set the terminal width and this needs set automatically in the Netmiko driver (longer-term).
