### ISSUE TITLE
Netmiko and Textfsm Path and Env Issue Windows

### ISSUE THREAD

**Issue by alepodj** [ktbyers/netmiko#1664]
I am currently trying to set up a test with Netmiko and Textfsm in Windows 10, but no matter what path I try to setup the textfsm environment variable, it still doesn't pick it up and throws an error:

> Valid ntc-templates not found, please install https://github.com/networktocode/ntc-templates
and then set the NET_TEXTFSM environment variable to point to the ./ntc-templates/templates
directory.

I tried setting the environment variable manually via system properties --> environment variables, but still get the same message. I tried absolute as well as relative paths and no go. Ideally a relative path as the template folder will alway be alongside the script calling it. It might be something simple but im totally missing it right now.

**The folder structure:**

[![enter image description here][1]][1]

[1]: https://i.stack.imgur.com/9O686.png

**My Code:**

```
import os, json
from netmiko import Netmiko
from netmiko import NetMikoAuthenticationException

templates = os.path.dirname(os.path.abspath(__file__)) + '\\ntc-template\\templates\\'
os.environ['NET_TEXTFSM']= templates
print(os.environ['NET_TEXTFSM'])

###############################################################
#Can i set the env var from within the scirpt using python?
#os.system(f'cmd /c "set NET_TEXTFSM={templates}"')
###############################################################

switch = {'device_type': 'cisco_ios',
            'ip': '192.168.0.20',
            'username': 'cisco',
            'password': 'cisco',
            'secret': 'cisco',
            'timeout': 10000,
            'session_timeout': 10000}

try:
    c = Netmiko(**switch)
    c.enable()
    show_ip_arp = c.send_command('show ip arp', use_textfsm=True)
    print(json.dumps(show_ip_arp))
except Exception as e:
    print(e)
```

I was hoping anyone points to what might be wrong or missing. I would love to avoid having to set up any environment variables via cmd unless it can be automated as well. The idea is whoever opens this py file gets all that's needed to use textfsm.

**Comment by alepodj** [comment]
if i throw the ntc-templates folder and its contents in the user root it works as expected:

```
(Ex.: C:\Users\username\ntc-templates\templates)
```

So the default user home directory search is working for me. Cant seem to be able to provide any other custom paths/directories

**Comment by alepodj** [comment]
Textfsm 0.4.1 and ntc_templates as a python package was the way to go.
------------------------------------------
pip install --upgrade textfsm==0.4.1
https://github.com/networktocode/ntc-templates#pypi

**Comment by ktbyers** [comment]
Yes, you should only be using `textfsm >= 1.1.0` at this point. Are you using the latest version of Netmiko (3.1.0)?

I think this should all work fine, but let me know if it isn't.

**Comment by alepodj** [comment]
Hi ktbyers thanks for taking a look at this.

The issue persists with a new version of textfsm as follows:

####pip freeze

```
...
netmiko==3.1.0
ntc-templates==1.4.0
textfsm==1.1.0
...
```

####Script

```
import os, json
import ntc_templates
from ntc_templates.parse import parse_output
from netmiko import Netmiko
from netmiko import NetMikoAuthenticationException

switch = {'device_type': 'cisco_ios',
            'ip': '192.168.0.20',
            'username': 'cisco',
            'password': 'cisco',
            'secret': 'cisco',
            'timeout': 10000,
            'session_timeout': 10000}

try:
    c = Netmiko(**switch)
    c.enable()
    show_ip_arp = c.send_command('show ip arp')
    show_ip_arp_parsed = parse_output(platform="cisco_ios", command="show ip arp", data=show_ip_arp)
    print(show_ip_arp_parsed)
except Exception as e:
    print(e)
```

####Error

```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\ntc_templates\parse.py", line 5, in <module>
    from textfsm import clitable
  File "C:\Python37\lib\site-packages\textfsm\clitable.py", line 41, in <module>
    from textfsm import texttable
  File "C:\Python37\lib\site-packages\textfsm\texttable.py", line 42, in <module>
    from textfsm import terminal
  File "C:\Python37\lib\site-packages\textfsm\terminal.py", line 25, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/projects/IT-Tools-Dash/dev/netmiko/netmiko_test.py", line 3, in <module>
    from ntc_templates.parse import parse_output
  File "C:\Python37\lib\site-packages\ntc_templates\parse.py", line 7, in <module>
    import clitable
ModuleNotFoundError: No module named 'clitable'
```

...but if i forcefully downgrade textfsm to 0.4.1 then everything just works.

**Comment by ktbyers** [comment]
@alepodj You need to get rid of this:

`from ntc_templates.parse import parse_output` and do this instead:

```python
  show_ip_arp = c.send_command('show ip arp', use_textfsm=True)
```

You are trying to combine Netmiko code and ntc_templates Python code and they have two different solutions for the TextFSM breaks on Windows problem.

**Comment by Tes3awy** [comment]
I am still reproducing the same issue on my Windows machine

**Environment**

```
Python 3.9.4
testfsm==1.1.0
netmiko==3.4.0
ntc-templates==2.0.0
```

---

**Code snippet**

```python
from netmiko import ConnectHandler
import textfsm

cisco_device = {
    "device_type": "cisco_ios",
    "host": "sandbox-iosxe-latest-1.cisco.com",
    "username": "developer",
    "password": "C1sco12345",
    "port": 22,
}

with ConnectHandler(**cisco_device) as net_connect:
    device_info = net_connect.send_command("show version", use_textfsm=True)

print(device_info)
```

---

**Exception**

```python
Traceback (most recent call last):
  File "D:\Cisco Automation\device_info_to_excel-main\connect.py", line 13, in <module>
    device_info = net_connect.send_command("show version", use_textfsm=True)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 1550, in send_command
    structured_output = get_structured_data(
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\utilities.py", line 344, in get_structured_data
    template_dir = get_template_dir()
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\utilities.py", line 281, in get_template_dir
    with importresources_path(
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\importlib\resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 995, in open_resource
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ntc_templates\\templates'
```

Any solution or workaround? Thank you!

**Comment by ktbyers** [comment]
@Tes3awy What does this show?

```
$ python
Python 3.8.5 (default, Sep 14 2020, 19:19:31) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ntc_templates
>>> ntc_templates.__file__
```

**Comment by Tes3awy** [comment]
> 
> 
> @Tes3awy What does this show?
> 
> ```
> $ python
> Python 3.8.5 (default, Sep 14 2020, 19:19:31) 
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import ntc_templates
> >>> ntc_templates.__file__
> ```

It shows: `'C:\\Users\\username\\AppData\\Roaming\\Python\\Python39\\site-packages\\ntc_templates\\__init__.py'`

**Comment by ktbyers** [comment]
And does this directory exist?

```
C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ntc_templates\\templates
```

Your error above is complaining that that directory doesn't exist.

I would probably do the following:

```
pip uninstall ntc-templates
pip install ntc-templates
```

**Comment by Tes3awy** [comment]
> 
> 
> And does this directory exist?
> 
> ```
> C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ntc_templates\\templates
> ```
> 
> Your error above is complaining that that directory doesn't exist.
> 
> I would probably do the following:
> 
> ```
> pip uninstall ntc-templates
> pip install ntc-templates
> ```

I finally found a solution to this issue:

1. Go to **Control Panel** > **View advanced system settings** and click on **Environment Variables**.
2. Under **System variables** ~~(not User variables for username)~~ click **New** and add the following variable:
    Variable name: **NET_TEXTFSM**
    Variable value: **%APPDATA%\Python\Python39\site-packages\ntc_templates\templates**

Restart your text editor. If it didn't work, restart your PC and try again.

I was able to get to this solution by removing ntc-templates (`pip uninstall ntc-templates`). When I run my code without ntc-templates installed, I get an error message suggesting what I presented here. And the solution works like a charm.

Thanks @ktbyers! Have a great day

**Comment by musamakhalid88** [comment]
Thanks below mention method also work for me.

Go to Control Panel > View advanced system settings and click on Environment Variables.
Under System variables (not User variables for username) click New and add the following variable:
Variable name: NET_TEXTFSM
Variable value: %APPDATA%\Python\Python39\site-packages\ntc_templates\templates
Restart your text editor. If it didn't work, restart your PC and try again.
