### ISSUE TITLE
Unable to ssh nortel 5000 series switches

### ISSUE THREAD

**Issue by siddeshpawar** [ktbyers/netmiko#1665]
how to make the avaya_ers_ work for the nortel 5000 series switches too, currently i am working with avaya (nortel ) series switches 4548 series. successfully able to ssh the 4000 series switch? how should i script such that it opens a session?

**Comment by kadecole** [comment]
The ERS 5000 should work similar to the ERS 4000 series for login. I find it best to turn off the menu option for login with the command `cmd-interface cli` on the nortel 5000 side.

**Comment by siddeshpawar** [comment]
yes these works, but can we work some how with the send commands?, as using paramiko i am able to establish the session 
import paramiko
>>> ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> ssh.connect(IP,port=22, username = 'USERNAME', password = 'PASSWORD')
stdin, stdout, stderr = ssh.exec_command('show ip')
UNABLE TO get output, session gets timeout with sshException raised.

**Comment by ktbyers** [comment]
@siddeshpawar I am confused are you asking how to make it work with Paramiko or with Netmiko?

Kirk

**Comment by siddeshpawar** [comment]
Yes that work.

**Comment by siddeshpawar** [comment]
We can close that issue.
