### ISSUE TITLE
Function net_connect.send_command, rstrip error

### ISSUE THREAD

**Issue by wmann** [ktbyers/netmiko#167]
As the HP Procurve switches could run show commands in config mode. There was no problem using net_connect.send_config_set command for show commands. This works fine.

Code looks like this:
SSHClass = netmiko.ssh_dispatcher(device_type=switch['device_type'])
net_connect = SSHClass(**switch)
show_commands = ['show run']
output = net_connect.send_config_set(show_commands, delay_factor=2)

This works fine. Now I want to use the send_command function. I replaced send_config_set with send_command so the code looks like this

SSHClass = netmiko.ssh_dispatcher(device_type=switch['device_type'])
net_connect = SSHClass(**switch)
show_commands = ['show run']
output = net_connect.send_command(show_commands, delay_factor=2)

With this function I get the following error:

Traceback (most recent call last):
  File "script.py", line 33, in <module>
    output = net_connect.send_command(show_commands, delay_factor=2)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 355, in send_command
    command_string = command_string.rstrip("\n")
AttributeError: 'list' object has no attribute 'rstrip'

Any idea how to fix this?

Best Regards
wmann

**Comment by ktbyers** [comment]
@wmann 
show_commands needs to be a string and not a list.

So change this:
show_commands = ['show run']

To this:
show_commands = 'show run'

**Comment by wmann** [comment]
I should learn more python ;-(

**Comment by wmann** [comment]
But this 
show_commands = ['show system', 'show interfaces transceiver']
seems to work. So if there is only one command only a string. When multiple then a list?

**Comment by wmann** [comment]
Damn, it might be to late for coding today.
Haven't changed the function in the second command. So how can I use a string and use multiple show commands?

**Comment by ktbyers** [comment]
@wmann 

Just use a for loop and gather the output.

show_commands = ['show system', 'show interfaces transceiver']
output = ''
for cmd in show_commands:
     output += net_connect.send_command(cmd, delay_factor=2)

# Each time through the loop 'cmd' will be set to one of the commands.
# output will have the results of the multiple commands
