### ISSUE TITLE
Issue in Multi Backup config to a file using Python Netmiko

### ISSUE THREAD

**Issue by kingakii** [ktbyers/netmiko#1674]
hi,
here is the code that i was trying to run and every time it gives error
`from netmiko import ConnectHandler
import time
import datetime

IP_List = open('net_devices.txt')
for IP in IP_List:
    SWS = {'device_type': 'cisco_ios',
           'ip': IP,
           'username': 'admin',
           'password': 'cisco',
           'secret': 'cisco',
    }

    print ('\n ##### connection to device' + IP.strip() + '##### \n')
    net_connect = ConnectHandler(**SWS)
    net_connect.enable()
    print('\n Initiate Configuration Backup \n')
    output = net_connect.send_command('show run')
    print(output)
    Save_File = open('Switches-' + IP, 'w')
    Save_File.write(output)
    Save_File.close    
    print('\n Finished Config Backup \n')

`
here is the error
`##### connection to device192.168.100.93##### 

 Initiate Configuration Backup 

Traceback (most recent call last):
  File "C:\Users\username\OneDrive\Documents\SSH-to-Multiple-Devices.py", line 22, in <module>
    Save_File = open('Switches-' + IP, 'w')
OSError: [Errno 22] Invalid argument: 'Switches-192.168.100.93\n'
>>> `

actually the file is created by this name "Switches-192.168.100.93" and there is a config but by default it is not saving as a txt file, and other devices backup is not there. net_devices.txt has 3 devices IP. 
kindly assist me to successfully run this code also if possible kindly guide me to backup config using Hostname (device hostname)

**Comment by friday963** [comment]
When you open a file handle for writing python isn't assuming the file type.  You'll need to specify the file type and append ".txt" to the "open" object.  As if I'm understanding you correctly you you want to save the file with the hostname ?  If so there is a "find_prompt" method that you can call to retrieve that.  Once you do you can stick that in the "open" object so it saves the file as "Switches-yourexamplehostname.txt'.  I've added both to your code below.

`print ('\n ##### connection to device' + IP.strip() + '##### \n')
net_connect = ConnectHandler(**SWS)
net_connect.enable()
hostname = net_connect.find_prompt()  <- Get the hostname
print('\n Initiate Configuration Backup \n')
output = net_connect.send_command('show run')
print(output)
Save_File = open('Switches-' + hostname + ".txt", 'w') <- Specify the handle type as .txt
Save_File.write(output)
Save_File.close    
print('\n Finished Config Backup \n')`

**Comment by kingakii** [comment]
that works nicely but 2 things are here.
1st i am getting file name "switch-hostname#.txt" its getting it but with hash. 
2nd what are the things that i can get using find_prompt()

**Comment by friday963** [comment]
You could just strip the hash off with the .strip method.  I don't
understand your second question.

**Comment by kingakii** [comment]
Thanks brother @friday963
