### ISSUE TITLE
Integrating ZTE os to Netmiko

### ISSUE THREAD

**Issue by zaraki04** [ktbyers/netmiko#1675]
Hi, 

I am planing to integrate our ZTE equipment to netmiko. Any idea how. Newbie here, hoping for your help. Thank You

**Comment by friday963** [comment]
Hope this finds you well.  Kirk does outline steps for contributing to the project which you'll find below.  

1. https://github.com/ktbyers/netmiko#contributing
2. https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md
3. https://github.com/ktbyers/netmiko/blob/develop/TESTING.md
