### ISSUE TITLE
Missing ConnectHandler and Modules

### ISSUE THREAD

**Issue by zaraki04** [ktbyers/netmiko#1677]
Hi Team,

NEed your help, seems connecthandler and other modules are missing. Did I miss something in my installation? or is there a way I can update to have some module. Hoping for assistance. Please see image below

Thank You

![netmiko31](https://user-images.githubusercontent.com/63898094/79632949-16273580-8195-11ea-8cd2-5cdf48ffb4cd.PNG)

**Comment by ktbyers** [comment]
You very likely have a file named "netmiko.py" or cached versions of this (i.e. .pyc files). So you are not actually loading the netmiko library, but instead your file.

You can see which file you are using with:

`netmiko.__file__`

**Comment by zaraki04** [comment]
> You very likely have a file named "netmiko.py" or cached versions of this (i.e. .pyc files). So you are not actually loading the netmiko library, but instead your file.
> 
> You can see which file you are using with:
> 
> `netmiko.__file__`

Thank you for your response. How can I fix this. I type `netmiko.__file__` here is the result. nothing showed up. I apologize for lots of questions. 


![python3](https://user-images.githubusercontent.com/63898094/79643179-5659d880-81d4-11ea-9a12-dc868adbe6f7.PNG)

**Comment by friday963** [comment]
What do you see if you run a pip list in your virtualenv ? Is netmiko listed in there as you would expect?

**Comment by zaraki04** [comment]
> What do you see if you run a pip list in your virtualenv ? Is netmiko listed in there as you would expect?

Hi,
As I checked in piplist netmiko is not there. 

![piplist](https://user-images.githubusercontent.com/63898094/79680074-4a0a6580-823e-11ea-9731-d340fe15910e.PNG)

**Comment by zaraki04** [comment]
> > You very likely have a file named "netmiko.py" or cached versions of this (i.e. .pyc files). So you are not actually loading the netmiko library, but instead your file.
> > You can see which file you are using with:
> > `netmiko.__file__`
> 
> Thank you for your response. How can I fix this. I type `netmiko.__file__` here is the result. nothing showed up. I apologize for lots of questions.
> 
> ![python3](https://user-images.githubusercontent.com/63898094/79643179-5659d880-81d4-11ea-9a12-dc868adbe6f7.PNG)

Also in addition, i checked __init__.py file is located at C:\Users\Moonleaf\netmiko\netmiko is there any issue about this?

**Comment by friday963** [comment]
There's your problem

> 
> 
> > What do you see if you run a pip list in your virtualenv ? Is netmiko listed in there as you would expect?
> 
> Hi,
> As I checked in piplist netmiko is not there.
> 
> ![piplist](https://user-images.githubusercontent.com/63898094/79680074-4a0a6580-823e-11ea-9731-d340fe15910e.PNG)

There's your problem. You don't have the netmiko package.  I'm not even sure how you are able to import it without an error.  Just do a pip install netmiko in that virtualenv and you should be good.

**Comment by zaraki04** [comment]
> There's your problem
> 
> > > What do you see if you run a pip list in your virtualenv ? Is netmiko listed in there as you would expect?
> > 
> > 
> > Hi,
> > As I checked in piplist netmiko is not there.
> > ![piplist](https://user-images.githubusercontent.com/63898094/79680074-4a0a6580-823e-11ea-9731-d340fe15910e.PNG)
> 
> There's your problem. You don't have the netmiko package. I'm not even sure how you are able to import it without an error. Just do a pip install netmiko in that virtualenv and you should be good.

Hi,

This is great, it solved the problem. Appreciate your help on this. Thank You
