### ISSUE TITLE
NameError on python Netmiko script 

### ISSUE THREAD

**Issue by kingakii** [ktbyers/netmiko#1678]
`from getpass import getpass
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetmikoAuthenticationException
from netmiko.ssh_exception import NetmikoTimeoutException
from netmiko.ssh_exception import SSHException

username = input('Enter Username:')
password = getpass()
secret = getpass()

with open ('commands_file_switch1.txt') as f:
    commands_list_switch1 = f.read().splitlines()
with open ('commands_file_switch2.txt') as f:
    commands_list_switch2 = f.read().splitlines()

with open ('device_file.txt') as f:
    device_list = f.read().splitlines()

for devices in device_list:
    print ('connecting to device" '  + devices)
    ip_list_from_file = devices

    ios_devices = {
        'device_type': 'cisco_ios',
        'ip': ip_list_from_file,
        'username': username,
        'password': password,
        'secret': secret,
        
    }

    try:
        net_connect = ConnectHandler(**ios_devices)
        net_connect.enable()
    except NetmikoAuthenticationException:
        print ('Authentication Failure: ' + ip_list_from_file)
        continue
    except 'NetmikoTimeOutException':
        print ('Timeout to device: ' + ip_list_from_file)
        continue
    except SShException:
        print ('SSH is not Enable: ' + ip_list_from_file)
        continue
# Type of Devices
    list_versions = ['I86BI_LINUX-ADVENTERPRISEK9-M',
                     'I86BI_LINUXL2-IPBASEK9-M',
                     ]

    # check software versions
    for software_ver in list_versions:
        print ('Check For' + software_ver)
        output_version = net_connect.send_command('show version')
        int_version = 0 # Reset Interger Value
        int_version = output_version.find(software_ver) #check software version
        if int_version > 0:
            print ('software version found: ' + software_ver)
            break
        else:
            print ('Did not Found' + software_Ver)

        if software_ver == 'I86BI_LINUX-ADVENTERPRISEK9-M':
                print ('Running' + software_ver + 'commands')
                output = net_connect.send_config_set(commands_list_switch1)
        elif software_ver == 'I86BI_LINUXL2-IPBASEK9-M':
            print ('Running' + software_ver + 'commands')
            output = net_connect.send_config_set(commands_list_switch2)
            print (output)
    
        
`
`Warning (from warnings module):
  File "C:\Python\Python38-32\lib\getpass.py", line 100
    return fallback_getpass(prompt, stream)
GetPassWarning: Can not control echo on the terminal.
Warning: Password input may be echoed.
Password: cisco
Warning: Password input may be echoed.
Password: cisco
connecting to device" 192.168.100.93
Check ForI86BI_LINUX-ADVENTERPRISEK9-M
Traceback (most recent call last):
  File "C:/Users/akbar/OneDrive/Documents/run_command_by_version.py", line 59, in <module>
    print ('Did not Found' + software_Ver)
NameError: name 'software_Ver' is not defined`

kindly assist me to execute successfully this script.
1. software_ver is not define 
2. while typing the password is shows in clear txt. can not be **** or .....

**Comment by ktbyers** [comment]
You have a bug in your program:

```
    else:
        print ('Did not Found' + software_Ver)
```

Capitalization matters so that capital-V makes it be a different variable.

**Comment by kingakii** [comment]
that was really silly but here lots of errors generated

`Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Python\Python38-32\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1570, in enable
    output += self.read_until_prompt()
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 623, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 560, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/akbar/OneDrive/Documents/run_command_by_version.py", line 34, in <module>
    net_connect.enable()
  File "C:\Python\Python38-32\lib\site-packages\netmiko\cisco_base_connection.py", line 18, in enable
    return super().enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "C:\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1572, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/akbar/OneDrive/Documents/run_command_by_version.py", line 38, in <module>
    except 'NetmikoTimeOutException':
TypeError: catching classes that do not inherit from BaseException is not allowed`

**Comment by ktbyers** [comment]
@kingakii Did you work this out?
