### ISSUE TITLE
[NX-OS] terminal color persist

### ISSUE THREAD

**Issue by NetSecParano** [ktbyers/netmiko#168]
Hello,
Terminal prompt cannot be found if the user activated "terminal color persist" on a Nexus. 
On the function set_base_prompt, when prompt[-1] is checked, it fails because prompt[-1] return a char used to display the color. 

You could maybe sanitaze and withdraw those additionnal chars before checking the prompt.
Or, easier, just send "no terminal color" before (maybe at the same time as the "terminal lenght 0").

Anyways, thank you for the great work :+1

**Comment by ktbyers** [comment]
Fix here https://github.com/ktbyers/netmiko/commit/dcf323c9d9e1c9b138e1ba654b4d09ac2c832de8
