### ISSUE TITLE
Feature-Request: Cisco VOSS Support?  CUCM CLI access request.

### ISSUE THREAD

**Issue by briantology** [ktbyers/netmiko#1680]
Hello there, I am a heavy user of Netmiko and this library has made our workflows much more streamlined and optimized.  We use it for switches, WLCs, routers, voice gateways, pretty much any IOS or IOSXE device with a CLI.

We also have a rather large Cisco UC implementation which has a robust Linux CLI available to us.  Voice gateways, CUBES and other UC edge devices normally have a heavy reliance on the Cisco UC suite of applications that is lead by the primary call processor Cisco Unified Communications Manager and having access to the CLI of that CUCM 

It's a long shot, but in the unlikely case you're interested, is there any possibility of getting UC-CORE-APPLIANCE as a device type?  Cisco Unity Connection, IM&P, CUCM, CER, UCCX, and a few others all share the same kind of underlying CLI.

Being able to issue a "Show Version Active" right from the CLI would help alot because the exposed APIs that Cisco offers us rely on SOAP and SOAP is, uh, ugly.

Thank you for reading my request, whether or not you decide to investigate, your library is outstanding.

-Briantology.

**Comment by ktbyers** [comment]
@briantology Someone would need to write the driver for it. The process for doing that is detailed here:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md

And the testing process is detailed here:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md



Regards, Kirk

**Comment by briantology** [comment]
Thank you for the response, I will check the documentation you have provided and see if there is anyway I can assist.

Regards Kirk.
