### ISSUE TITLE
Encryption and Authentication 

### ISSUE THREAD

**Issue by zaraki04** [ktbyers/netmiko#1683]
Hi Team,

I would like to know what kind of ssh encryption method( 3des, aes128, or blowfish) and authentication method( md5, or sha1), SSH version(1 or 2) does netmiko use? appreciate anyone's help.

thank you

**Comment by ktbyers** [comment]
SSH version 2 only. Hashing and encryption depend on what is negotiated between the two peers. You would need to look up in Paramiko what it defaults to for both encryption and hashing.
