### ISSUE TITLE
Abort connection when not Cisco

### ISSUE THREAD

**Issue by tars01** [ktbyers/netmiko#1687]
Kirk

I have an issue with with cisco_ios connect handler. I am running a discovery on lots of Cisco CPE devices on my network. Some of them are MikroTik. I'm trying to have it so that when it detects a MikroTik prompt it just aborts that device. I have written some code to do this but it seems to not detect the prompt correctly because my code doesn't execute. 

Please see a snippet of the code

![image](https://user-images.githubusercontent.com/29687497/80025306-527dcd00-84d8-11ea-82d4-5b5aa1f0fafa.png)

Here is what happens though, it just sits at the prompt and doesn't execute my code to ctrl+shift+6+x (I connected manually to the device and it does support breaking out of the session with that combination)

Logs

DEBUG:netmiko:write_channel: b'telnet 10.0.10.100\r\n'
DEBUG:netmiko:read_channel: telnet 10.0.10.100
Trying 10.0.10.100 ... Open

MikroTik v6.45.3 (stable)

^@Login: Password: 
DEBUG:netmiko:write_channel: b'\x1e'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: Login failed, incorrect username or password

Login: Password: 
Login failed, incorrect username or password

Login: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is Login:
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: Password: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is Password:
DEBUG:netmiko:read_channel: 

To be honest I have noticed similar problems related to this where it doesn't always work, e.g. detecting 'tacacs not available' etc in the banner. The expected string I have it search for is always there when I look in the debug though. 

Any help appreciated.

**Comment by ktbyers** [comment]
What is the context here--you are bouncing into an intermediate device and then telnetting from there?

You stated "ctrl+shift+6+x", but your code looks like it only sent "ctrl+shift-6" (i.e. no + x)?


Kirk

**Comment by tars01** [comment]
Hi Kirk

Yes that's correct. I'm ssh'ing to a Cisco router then from there i am telnetting to Cisco CPE devices (occasionally one of the devices is not Cisco) But for these non-Cisco devices I have tested manually with ctrl+shit+6+x and it does log them out of the telnet session when at the login prompt. Actually for the Cisco devices for the vast majority of the time It works fine but I have noticed that very occasionally they don't drop out of the telnet session also.(FYI I am doing hundreds of devices)

I thought that CNTL_SHIFT_6 was a built in feature of Netmiko to perform that function? I saw it from someone else code so i just used the same example, maybe I missed something else in their code? I have tried both of the below examples and had mixed results. (the bottom one I believe is ctrl+shift+6+x in asci)

`net_connect.write_channel(CNTL_SHIFT_6)`

`net_connect.send_command_timing('\x036')`

I found the second example here:
https://www.reddit.com/r/networking/comments/c73odu/netmiko_question_how_to_send_ctrlc_to_cisco/

My aim is to drop out of telnet sessions when the authentication fails etc and it's stuck at the login prompt so if you have a different approach or suggestions that would be great.

Any help appreciated.

**Comment by ktbyers** [comment]
I would do both of these using `write_channel` and not `send_command_timing` (as send_command_timing might do other things that are problematic):

```python
net_connect.write_channel(CNTL_SHIFT_6)
time.sleep(.4)
net_connect.write_channel('x')
# See what happened...
time.sleep(1)
output = net_connect.read_channel()
```

Let me know if that works or not.

**Comment by tars01** [comment]
Ok great, thanks Kirk. I will give this a try. I will close this for now as it will take me a while to be able to know if this has made a difference or not.
