### ISSUE TITLE
"send_config_set" - Handle promt from config mode

### ISSUE THREAD

**Issue by nhandh09** [ktbyers/netmiko#1688]
Hi there,

I did research and can handle prompt from global mode (python code) below:

_output = net_connect.send_command_timing(commandGL, strip_command=False, strip_prompt=False)
            if "confirm" in output:
                    output += net_connect.send_command_timing(
                        "\n", strip_command=False, strip_prompt=False
                    )
            if "yes" in output:
                output += net_connect.send_command_timing(
                    "y", strip_command=False, strip_prompt=False
                )
                if "confirm" in output:
                    output += net_connect.send_command_timing(
                        "\n", strip_command=False, strip_prompt=False_

But when I came to config mode (send_config_set), it didn't work, I posted command I want to enter and python code below, could someone help me figure it out:

_CISCO-ROUTER#sh running-config | inc user
username cmc_mtn privilege 15 password 7 13061A1106180A787B7678
CISCO-ROUTER#conf t
Enter configuration commands, one per line.  End with CNTL/Z.
CISCO-ROUTER(config)#no user
CISCO-ROUTER(config)#no username cmc_mtn
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]
CISCO-ROUTER(config)#

Python code:
                cfg_lines=['no username cmc_mtn']
                net_connect = ConnectHandler(**devices)
                net_connect.enable()
                output = net_connect.send_config_set(cfg_lines)
                print (output)_

Many thanks for help!

**Comment by ktbyers** [comment]
It is because Cisco IOS has a bug here (or a mis-design) and prompts you for additional confirmation (even though we have told Cisco IOS not to prompt us).

Consequently, you won't be able to directly use `send_config_set` to remove usernames.

One solution is to do the following:

```python
output = net_connect.config_mode()
output += net_connect.send_command(
    "no username foo1", 
    expect_string=r"confirm", 
    strip_prompt=False, 
    strip_command=False
)
output += net_connect.send_command(
    "y", 
    expect_string=r"#",
    strip_prompt=False, 
    strip_command=False
)
output += net_connect.exit_config_mode()
```

Here is the output from doing that:
```
$ python remove_user.py 
config term
Enter configuration commands, one per line.  End with CNTL/Z.
cisco5-tmp(config)#no username foo1
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]y
cisco5-tmp(config)#end
cisco5-tmp#**
```

**Comment by nhandh09** [comment]
Well noted bug related cisco os ktbyers!

Thanks for the solution you suggested, which worked fine.
