### ISSUE TITLE
How to detect failure in a send_config_set() call

### ISSUE THREAD

**Issue by ramdyne** [ktbyers/netmiko#169]
Hi,

I want to send number of config commands to a Cisco IOS device in one call to send_config_set(). How do I detect in my code that all commands have succeeded or some (or all) have failed?

-- 
Andreas

**Comment by ktbyers** [comment]
@ramdyne 

Yes, that is a bit problematic. You could probably write a wrapper (some sort of a for loop) that executes each command and looks for an error string back.

Also you could check the merge function in NAPALM for Cisco IOS (see https://pynet.twb-tech.com/blog/automation/napalm-ios.html). This hasn't been merged in the main NAPALM yet, however (so you would need to use my NAPALM branch https://github.com/ktbyers/napalm/tree/cisco_ios_scp).
This would rollback on an error.

**Comment by ramdyne** [comment]
Doing the for-loop looks like the safest bet for now :-)

Anyway, thanks!.

**Comment by ramdyne** [comment]
Having send_config_set() do that would be very nice indeed :-)
Perhaps something like 
```python
(result, output) = ssh.send_config_set(config_set)
```
or even

```python
(result, output, failed_line_number) = ssh.send_config_set(config_set)
```

**Comment by ktbyers** [comment]
@ramdyne Hmmm, that is an interesting idea.

I have also been thinking about improving the send_config_set() so the delays are much shorter between each command.

In other words:
get into config mode / verify in config mode             # a bit slow
execute each command                 # fairly rapidly one after the other
exit out of config mode                   # a bit slow

**Comment by pnicolette** [comment]
With 500+ lines of ACL to write into an ASA, be great to have a send_config_set() pacing rate option nearly as quick as multilline paste in a PuTTY SSH session.  Thanks MUCH for netmiko, btw.

**Comment by ktbyers** [comment]
@pnicolette Check out Netmiko 0.4.2 (master branch on GitHub). This should be much-much faster now for multi-line configuration changes. Probably >10X faster.

**Comment by pnicolette** [comment]
@ktbyers On our test ASA5505, Netmiko 0.4.2 adds 100 lines to a network object group in under 7 seconds. Perfect!

**Comment by ktbyers** [comment]
:+1:  Nice.
