### ISSUE TITLE
juniper_junos handle prompt on config mode

### ISSUE THREAD

**Issue by nhandh09** [ktbyers/netmiko#1692]
Dear Ktbyers,

I also tried to handle prompt on my srx config mode when I create user on that (with plain text password), but still stuck on that. My code posted below for encrypted password and also commit (which worked fine), but is anyway there for me to put password on my script for plain text option?

nhandinh@SRX1#set system login  user cmc_mtn class super-user authentication plain-text-password
New password:
Retype new password:
[edit]

_python code:
                 junos_command = [set system login user cmc_mtn class super-user authentication 
                                    encrypted-password   $1$J7pr.Dcr$DPgW75V.R0ahIl5eE9UpZ.]
                output = net_connect.send_config_set(junos_command , exit_config_mode=False)
                output += net_connect.commit(and_quit=True)
                print (output)_

Many thanks and regards

**Comment by ktbyers** [comment]
Probably need to use something similar to the following:

```python
output = net_connect.config_mode()
junos_command = "set system login user cmc_mtn class super-user authentication plain-text-password"
output += net_connect.send_command_timing(junos_cmd, strip_prompt=False, strip_command=False)
if "ssword" in output:
    new_output = net_connect.send_command_timing("your_password"), strip_prompt=False, strip_command=False)
    if "ssword" in new_output:
        output += new_output
        output += net_connect.send_command_timing("your_password"), strip_prompt=False, strip_command=False)
output += net_connect.commit(and_quit=True)
print (output)
```

Something close to that anyways...

**Comment by nhandh09** [comment]
Many thanks Ktbyers! Code you given worked well!

Regards, Nhan!
