### ISSUE TITLE
Unable to run commands after config mode on Huawei OLT

### ISSUE THREAD

**Issue by jogindergur** [ktbyers/netmiko#1693]
Hi There,
I have a SSH connection to my OLT and enabled it. After turning config mode, I'm not able to hit any command to OLT. Either my way is wrong or something wrong with library. Kindly assist me in this matter. 

`print(SSH.send_command('interface gpon 0/0'))`

Error is:

```
MA5608T(config)#
Traceback (most recent call last):
  File "f:/Happy/work/python/hello.py", line 28, in <module>
    print(SSH.send_command('interface gpon 0/0'))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1429, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command_expect: MA5608T\(config\)\#
```

Hi @ktbyers and @Fikirsiz am able to fetch temperature of my OLT but when I try to enter in other configuration it shows me OSError. Please help me! I have used expect_string but nothing works for me.

**Comment by Fikirsiz** [comment]
Hi, attach here all the lines of code that are used to interact with the device.

**Comment by Fikirsiz** [comment]
In enable mode you need to use this method for send config command:
>>> ssh.send_config_set("interface gpon 0/0")
'interface gpon 0/0\n\nMA5608T_10.210.0.12(config-if-gpon-0/0)#return\n\nMA5608T_10.210.0.12#'

**Comment by jogindergur** [comment]
Thank You! I was using wrong method for Huawei as I used for Cisco.
