### ISSUE TITLE
Read Channel exception using Netmiko for Palo-alto firewall vpn user count 

### ISSUE THREAD

**Issue by MurthyChamarthi** [ktbyers/netmiko#1694]
i wrote python program using Netmiko for Palo firewall user count report.  The following exception is throwing with error. 

./Palo-vpn-count.py
Password:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Palo-vpn-count.py", line 25, in <module>
    output = NetConnect.send_command('show global-protect-gateway statistics')
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netmiko/paloalto/paloalto_panos.py", line 160, in send_command
    return super().send_command(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 1389, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by MurthyChamarthi** [comment]
**********************************\n*         UNAUTHORIZED ACCESS TO THIS NETWORK DEVICE IS PROHIBITED        *\n***************************************************************************\n'
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: Last login: Fri Apr 24 15:20:40 2020 from cycitlxmgtp01.exeterfinance.com

Number of failed attempts since last successful login: 0



DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
adm-muchamarthi@CYCFW-PA5220EF-PRI(active)>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is xxxxxxxxxxxxxxI(active)>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: set cli pager off

DEBUG:netmiko:write_channel: b'set cli pager off\n'
DEBUG:netmiko:Pattern is: set\ cli\ pager\ off
adm-muchamarthi@CYCFW-PA5220EF-PRI(active)> set cli pager off

adm-muchamarthi@CYCFW-PA5220EF-PRI(active)> set cli pager off

adm-muchamarthi@CYCFW-PA5220EF-PRI(active)> set cli pager off

DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel:xxxxxxxxxxxxxx(active)>
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
adm-muchamarthi@CYCFW-PA5220EF-PRI(active)>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxI(active)>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show global-protect-gateway statistics\n'
DEBUG:netmiko:Pattern is: show\ global\-protect\-gateway\ statistics
xxxxxxxxxxxxxxxxx)> show global-protect-gateway statistics


DEBUG:netmiko:_read_channel_expect read_data: GlobalProtect Gateway: Global Protect Gateway:
        Current Users: 835
        Previous Users: 1814

Total Current Users: 835
Total Previous Users: 1814

**Comment by ktbyers** [comment]
@MurthyChamarthi I made a set of changes to the palo alto driver in this PR:

https://github.com/ktbyers/netmiko/pull/2227

Can you let me know if you are still seeing an issue here?

If you are still running into an issue, just re-open this GitHub issue.
