### ISSUE TITLE
is there a way to SSH to a generic device?

### ISSUE THREAD

**Issue by ccie57960** [ktbyers/netmiko#1697]
Let say I have an generic IP device (router, switch, IP camera IoT device, etc) and I want to automate some task via SSH/Netmiko. I would like to: 

- SSH via Netmiko (with only IP, user and password)
- 'expect promptA'
-  do something (send command 'B')
- 'expect outputC'
- etc

**Comment by ktbyers** [comment]
@ccie57960 You can use the `terminal_server` device_type. This is a generic device type which means Netmiko doesn't really do anything automatically post-login.

You could then use `send_command` and the `expect_string` argument.
