### ISSUE TITLE
Regex support with "expect_string=" ?

### ISSUE THREAD

**Issue by stvnkem** [ktbyers/netmiko#1698]
Hello,

I am trying to build my own function to search for the returned prompt. Looks like RE is not supported.

Exception: Search pattern never detected in send_command_expect: \[~ipi-\w+-r-\w+-\d+-acl4-advance-IGMP_Report_whitelist_ACL]

Edit: workaround without regex: '-acl4-advance-IGMP_Report_whitelist_ACL]'

How can I do that?

Thanks!
Istvan

**Comment by ktbyers** [comment]
You need to include your relevant code including your regex pattern. `expect_string` for `send_command` is fed-into Python's RE library so regular expressions should work properly there.

**Comment by stvnkem** [comment]
Hello,

Here is the relevant code:

def def_send_single_cmd_plain_expectstr(cmd, excepted_str:str, ssh_session, hostname) -> bool:
    '''
        Sends command on a reliable way. The output is STRING. Returns BOOL.
    '''
    logging.warning(f'Sending "{cmd}" command to {hostname}.')
    retry_send = 0
    exception = False
    while retry_send < 3:
        try:
            output = ssh_session.send_command(cmd, expect_string=excepted_str, delay_factor=1)
        except Exception as e:
            logging.error(f'Exception: {e} | {hostname}')
            time.sleep(0.5)
            exception = True
            logging.error(f'Retry send command {retry_send} | {cmd} | {hostname}')
            retry_send += 1
            continue
        else:
            exception = False
            break
    if exception:
        logging.error(f'Exception happened while executing {cmd} on {hostname} and returned None')
        return False
    else:
        try:
            logging.warning(f'Recording the output: {cmd} | {hostname} | {output}')
        except Exception as e:
            logging.error(f'Exception: {e} | {hostname}')
            pass
        return True

if def_send_single_cmd_plain_expectstr('snmp-agent sys-info location ABC_XX_Config_v_02_05', '\[~ipi-\w+-r-al-\d+\]', ssh_session, hostname) is True:

Exception:
ERROR :: 2020-04-28 12:24:54,649 :: 284 :: Thread-1 ::  def_send_single_cmd_plain_expectstr :: Exception: Search pattern never detected in send_command_expect: \[~ipi-\w+-r-al-\d+\] | ipi-xyz123-r-al-65

**Comment by stvnkem** [comment]
Well, I found it:

`expect_string=rf'{excepted_str}'`

**Comment by ktbyers** [comment]
So is this a bug in the Netmiko code?

If so are you testing on the `develop` branch? 

I think we fixed the `*` issue on Huawei in the `develop` branch.

**Comment by stvnkem** [comment]
> So is this a bug in the Netmiko code?
> 
> If so are you testing on the `develop` branch?
> 
> I think we fixed the `*` issue on Huawei in the `develop` branch.

I am testing with 3.1.0. I am not sure, it may not be a bug. I created my own function to send a list of commands and retry/log each of them in case of a send failure. I do check whether the cmd was sent by expecting a manually defined prompt. I did not know about the change of prompt.
I modified the Regex pattern, it is working fine now.
