### ISSUE TITLE
Pattern not found in output: #

### ISSUE THREAD

**Issue by m6461** [ktbyers/netmiko#1704]
Hi,

I just started on netmiko; thanks to all of you, especially Kirk, for this. 

The problem I am facing is as below: Here is the exeption I am having for a test config-change in one of the ports:

Traceback (most recent call last):
  File "remoteConfigurePort.py", line 27, in <module>
    device.send_config_set(config_commands)
  File "C:\Program Files\Python38\lib\site-packages\netmiko\base_connection.py", line 1704, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Program Files\Python38\lib\site-packages\netmiko\cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(config_command=config_command, pattern=pattern)
  File "C:\Program Files\Python38\lib\site-packages\netmiko\base_connection.py", line 1595, in config_mode
    if not self.check_config_mode():
  File "C:\Program Files\Python38\lib\site-packages\netmiko\cisco\cisco_ios.py", line 29, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "C:\Program Files\Python38\lib\site-packages\netmiko\cisco_base_connection.py", line 30, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "C:\Program Files\Python38\lib\site-packages\netmiko\base_connection.py", line 1582, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Program Files\Python38\lib\site-packages\netmiko\base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\netmiko\base_connection.py", line 563, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, pattern not found in output: #

The source code is given below: 

```python
config_commands = ['interface gigabitEthernet 1/0/35','switchport access vlan 20']
start = time.time()
for i in ipdb:    
    for cmd in commands:
        device = ConnectHandler(device_type='cisco_ios_telnet', ip=i, username='***', password='***') 
        device.send_config_set(config_commands)
        print ("Done!")
        device.disconnect()
```

**Comment by ktbyers** [comment]
What are you doing here with these two loops?

```python
for i in ipdb:    
    for cmd in commands:
```

**Comment by m6461** [comment]
I kept the IPs in ipdb list - I have a number of devices to look for. Also, for each device, I have multiple commands to run; the commands are in commands list. 

ipdb = ['x.x.x.x']
commands = ["show cdp nei", "show version"]

**Comment by m6461** [comment]
Tried without the for loop, showing the same error. I don't think this is caused by the loop. It is showing netmiko.ssh_exception.NetmikoTimeoutException: but I am trying 'cisco_ios_telnet'

**Comment by nullbitzero** [comment]
Hi,
try this command line

device = ConnectHandler(device_type='cisco_ios_telnet', ip=i, username='***', password='***') 
find_prompt=device.send_command('\n')
if not '#' in find_prompt: #-->optional
   device.enable()#--->optional according to your device telnet
device.send_config_set(config_commands,expect_string='#')
print ("Done!")
device.disconnect()

good luck!
nullbit0

**Comment by m6461** [comment]
Hi @nullbitzero ,
Thanks. The idea worked! I changed a few parts though. 

device = ConnectHandler(device_type='cisco_ios_telnet', ip=i, username='***', password='***',secret='***')
device.enable()
device.send_config_set(config_commands)
print ("Done!")
device.disconnect()

May I know the reasons why I need run device.enable( )? How far I recall, send_config_set( ) should work directly in the configure terminal mode.

**Comment by nullbitzero** [comment]
Hi @m6461 ,

In a telnet session a switch or router, first enter user mode ('>') where you enter the command enable to switch to privileged mode ('#').
To use the send_config_set () method you must be previously in the privilege, this is how the code is thought.

https://www.cisco.com/E-Learning/bulk/public/tac/cim/cib/using_cisco_ios_software/02_cisco_ios_hierarchy.htm

nullbit0

**Comment by osmelquintero** [comment]
The connection is rejected
