### ISSUE TITLE
Autodetect as factory function with object overload

### ISSUE THREAD

**Issue by Yakuza-UA** [ktbyers/netmiko#1711]
First of all, I'd like to thank for this great module! Sometime ago I had to create a similar thing based on Paramiko, but of course my end result is not as powerful as this module. Although, I do miss one thing, which I implemented in my module - factory function, which detects the platform and re-instantiates the object using appropriate class. By doing this, I save time required to re-establish connection. 

I first create a generic class and execute 'show version', which is then retireved and raw output is quickly parsed to identify IOS version. Once identified, I re-instantiate the object using more specific class and I pass current instance to the construct to let it copy attributes to the new object, including Paramiko session. It saves GREAT amount of time as connection establishment is the most time consuming process. Here's my code:

    def create(host: str, username: str, password: str) -> Union[NetworkDeviceIOS, NetworkDeviceIOSXE, NetworkDeviceNXOS]:
        """Detect network device type and return appropriate instance

        Factory Function which instantiates a generic NetworkDevice object,
        detects hardware/software type, then instantiates and returns more
        specific object.

        Parameters
        ----------
        host : str
            Network device IP address

        username : str
            SSH username

        password : str
            SSH password
        
        Returns
        -------
        NetworkDevice, NetworkDeviceIOSXE, NetworkDeviceNXOS
        Instance depends on the software type (IOS-XE, NX-OS, IOS)

        """
        device = NetworkDevice(host, username, password)
        device.verbose = __verbose__

        # Try to connect,
        #  if fails return None
        #  if succeeds return generic NetworkDevice object
        if not device.connect(__con_timeout__, __cli_timeout__):
            return None

        output = device.execute('show version', cache=True)

        if not output:
            return None

        # Detect software
        software = None
        for line in output:
            if line.find('IOS-XE') != -1:
                return NetworkDeviceIOSXE(instance=device)
            elif line.find('NX-OS') != -1:
                return NetworkDeviceNXOS(instance=device)
            elif line.find('IOS') != -1:
                software = 'IOS'

        if software:
            return device

As you can see, I can use NetworkDevice construct with host, username, password, or I can also pass an instance of this class, or its child to re-instantiate it, such as shown below

    class NetworkDevice():
        """Generic NetworkDevice Class

        Methods available to all device types.
        Only SSH is supported. Telnet might be introduced in future releases.
        Pass `host`, `username`, `password` to instantiate new object
        Pass `instance` to re-instantiate object as an instance of more
        specific class

        Parameters
        ----------
        host : str, optional
            Network device's IP address
        
        username : str, optional
            SSH username
        
        password : str, optional
            SSH password
        
        instance : NetworkDevice, optional
            An instance of NetworkDevice class to re-instantiate as more
            specific class, such as NetworkDeviceIOSXE, NetworkDeviceNXOS, etc

        """

        def __init__(self, host=None, username=None, password=None, instance=None):
            # Object is instantiated from existing object:
            #   copy all attributes from existing object
            #   this trick is required to detect Device IOS type
            if instance:
                self.__dict__.update(instance.__dict__)
            else:
                self.host = host
                self.username = username
                self.password = password
                self.verbose = False
                self.type = None
                self.interfaces = []

                self.ssh = {
                    'client': None,
                    'channel': None,
                    'stdin': None,
                    'stdout': None,
                    'cache': {},
                    'context': 'exec'
                }

Let me know if it does make sense and sounds like a good feature. With my module I don't have to connect to the same device TWICE and I don't have to specify its type (usually I don't know, I only have IP address, username and password). Detection happens during runtime and has very small overhead

**Comment by Yakuza-UA** [comment]
I have noticed there's redispatch function, but I was unable to use it.

I have tried to use Autodetect, such as in example

```python
import netmiko
device = {
    'device_type': 'autodetect',
    'host': 'x.x.x.x',
    'username': 'xxxxxx',
    'password': 'yyyyyy'
}
guesser = netmiko.SSHDetect(**device)
best_match = guesser.autodetect()

new_conn = netmiko.redispatch(guesser, best_match)
```

However, I've got the following error

```
Traceback (most recent call last):
  File "/home/admin/sdc_new/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 756, in _try_session_preparation
    self.session_preparation()
  File "/home/admin/sdc_new/venv/lib/python3.7/site-packages/netmiko/cisco/cisco_ios.py", line 15, in session_preparation
    self._test_channel_read(pattern=r"[>#]")
  File "/home/admin/sdc_new/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 953, in _test_channel_read
    delay_factor = self.select_delay_factor(delay_factor=0)
  File "/home/admin/sdc_new/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 999, in select_delay_factor
    if self.fast_cli:
AttributeError: 'CiscoIosSSH' object has no attribute 'fast_cli'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin/sdc_new/venv/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 276, in redispatch
    obj._try_session_preparation()
  File "/home/admin/sdc_new/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 758, in _try_session_preparation
    self.disconnect()
  File "/home/admin/sdc_new/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 1889, in disconnect
    self.close_session_log()
  File "/home/admin/sdc_new/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 1909, in close_session_log
    if self.session_log is not None and self._session_log_close:
AttributeError: 'CiscoIosSSH' object has no attribute 'session_log'
```

So, I am not sure if redispatch is something that I can use to achieve the desired logic.

**Comment by Yakuza-UA** [comment]
Ok, I can't use an instance of SSHDetect as it's not a real 'thing'.... damn

**Comment by ktbyers** [comment]
Yeah, I don't think I want to do that.

I largely view autodetect as a one-time mechanism for discovering the device_type and NOT an ongoing solution that you use on a day-to-day basis.

There is redispatch that you could maybe wire in some way, but definitely the autodetect code currently doesn't consider this (so you would have to make your own modifications to account for that).

**Comment by Yakuza-UA** [comment]
Thanks for coming back, at least I know there's no such feature.
