### ISSUE TITLE
Cisco WLC Login using Netmiko Python

### ISSUE THREAD

**Issue by viskrish** [ktbyers/netmiko#1716]
Hi All,
I am just learning python and trying to code for logging into cisco wlc to take a command output. The below code throws errors after entering username and pwd which i mentioned below. Could someone help me how to fix this? 
-----------------------------------------------
from netmiko import ConnectHandler
from getpass import getpass

user1 = input('Enter username: ')
pass1 = getpass('Enter Password: ')

CWLC = {
    'host': 'x.x.x.x',
    'port': 22,
    'username': 'user1',
    'password': 'pass1',
    'device_type': 'cisco_wlc_ssh'
    }

net_connect = ConnectHandler(**CWLC)
net_connect.enable()
a = net_connect.send_command("show wlan summary")
print(a)
net_connect.disconnect()
-----------------------------------------------

Errors:

Enter username: XXXX
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Enter Password: XXXX

Traceback (most recent call last):
  File "INE Python/venv/lib/python3.7/site-packages/netmiko/cisco/cisco_wlc_ssh.py", line 103, in session_preparation
    self.set_base_prompt()
  File "INE Python/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 1081, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: 'User:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Try1.py", line 22, in <module>
    net_connect = ConnectHandler(**CWLC)
  File "INE Python/venv/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 259, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "INE Python/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "INE Python/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 333, in _open
    self._try_session_preparation()
  File "/INE Python/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 756, in _try_session_preparation
    self.session_preparation()
  File "INE Python/venv/lib/python3.7/site-packages/netmiko/cisco/cisco_wlc_ssh.py", line 106, in session_preparation
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Authentication failed: x.x.x.x

**Comment by m6461** [comment]
Which WLC model are you using? 

For a cisco WLC (XE - you may check that from show version), I used the following:

cmd = ["show ap summary"]
device = ConnectHandler(device_type='cisco_xe', ip=i, username='***', password='***')
output = device.send_command_expect(cmd)

I did not use "device.enable( )" - since we run show ap summary directly. if you give "device.enable( )", you might have to provide secret key as the parameter of the connection as below:

device = ConnectHandler(device_type='cisco_xe', ip=i, username='***', password='***',secret='***')

Please let me know if it worked!

**Comment by viskrish** [comment]
thank you very much.. this worked. 

> Which WLC model are you using?
> 
> For a cisco WLC (XE - you may check that from show version), I used the following:
> 
> cmd = ["show ap summary"]
> device = ConnectHandler(device_type='cisco_xe', ip=i, username='_**', password='**_')
> output = device.send_command_expect(cmd)
> 
> I did not use "device.enable( )" - since we run show ap summary directly. if you give "device.enable( )", you might have to provide secret key as the parameter of the connection as below:
> 
> device = ConnectHandler(device_type='cisco_xe', ip=i, username='_**', password='**_',secret='***')
> 
> Please let me know if it worked!

Thank you very much. It worked.
