### ISSUE TITLE
Nokia SR-OS fails with socket timeout

### ISSUE THREAD

**Issue by suyog-sdn** [ktbyers/netmiko#1717]
Hi All,

I am trying to configure 'nokia-sros' device, while opening config file. 

```python
from netmiko import ConnectHandler
from getpass import getpass
import paramiko
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import AuthenticationException
with open('device_list.txt') as ip_list:
	for ip in ip_list:
		rtr = {
			   'device_type':'nokia_sros',
			   'username':'xxxx',
			   'password':'xxx',
			   'ip': ip,
			   'global_delay_factor': 4,
			   }
			  
		print("Connecting to the device "+ ip.strip() + '####\n')
		net_connect = ConnectHandler(**rtr)
		
		with open('config_vsc.txt') as config_lines:
			config = config_lines.read()
		
		output = net_connect.send_config_set(config)
		print(output)
		
		output = net_connect.send_command(b'show router interface')
		print(output.decode('ascii'))
		#print(output)
```		

========================================
However, following error triggered:
*Traceback (most recent call last):
  File "C:\Users\Suyog.Varun\cisco_devnet\venv\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\Suyog.Varun\cisco_devnet\venv\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout*
During handling of the above exception, another exception occurred:

*Traceback (most recent call last):
  File "C:\Users\Suyog.Varun\cisco_devnet\venv\lib\site-packages\netmiko\base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\Suyog.Varun\cisco_devnet\venv\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout*

Please assist in this.

**Comment by ktbyers** [comment]
Please format your markdown properly.


Thanks, Kirk

**Comment by suyog-sdn** [comment]
> Please format your markdown properly.
> 
> Thanks, Kirk

As suggested, formatted the content.

**Comment by hellt** [comment]
Hi @suyog-sdn 
please tell me what version of SR OS are you running? And if you run it classic or model-driven mode?

**Comment by ktbyers** [comment]
Socket timeout would probably make me think, the IP-address is unreachable for SSH.
