### ISSUE TITLE
Huawei/ Alcatel send_command() output split into 2 lines after 80 characters

### ISSUE THREAD

**Issue by nontha** [ktbyers/netmiko#1718]
Output of `send_command` splits into 2 lines, and this gives me issues in reading the output.
It is observed that the output splits into two, when the line exceeds 80 characters (with spaces).

code:
```
device = {'device_type': 'huawei', 'host':ip_Add, 'username': 'user','password': 'pass' }
	device1 = ConnectHandler (**device)
	command1 = 'display interface description'
	output1 = device1.send_command (command1)
```
output:
```
GE0/0/0                       down    down     HUAWEI, GigabitEthernet0/0/0 Inte
                                               rface                  
GE1/0/0                       up      down     ## WTX-0034_Joresbinna_OD_MSAN ##
GE1/0/0.17                    up      up       ## RAD_CPE_MGT_WTX-0034_Joresbinn
                                               a ##                   
GE1/0/0.18                    up      up       ## ONE_ACCESS_CPE_MGT_WTX-0034_Jo
                                               resbinna##            
GE1/0/0.31                    up      up       ## WTX-0034_Joresbinna_OD_MSAN_MG
                                               T ##   
```
Required output:
```
GE0/0/0                       down    down     HUAWEI, GigabitEthernet0/0/0 Interface                  
GE1/0/0                       up      down     ## WTX-0034_Joresbinna_OD_MSAN ##
GE1/0/0.17                    up      up       ## RAD_CPE_MGT_WTX-0034_Joresbinna ##                   
GE1/0/0.18                    up      up       ## ONE_ACCESS_CPE_MGT_WTX-0034_Joresbinna##            
GE1/0/0.31                    up      up       ## WTX-0034_Joresbinna_OD_MSAN_MGT ##   
```
Can someone give me a solution to overcome this issue? Is there any method to increase the width of the output?

**Comment by ktbyers** [comment]
It is probably Huawei that is doing this (i.e. Huawei is inserting an extra newline to make it more readable based on what they believe the terminal width is). It is likely a consequence of terminal width setting.

Can you test it with the `develop` branch? We made some changes here recently.

**Comment by nontha** [comment]
Thanks! I'm quite new to this area of networking. 
I tried with applying` screen-width 200` with **huawei**, but the output was the same. 

The similar output was experienced when I tried with an **Alcatel device**. It also got splitted after 80 characters.
code:
```
from netmiko import ConnectHandler

device = {'device_type': 'alcatel_sros', 'host':'15.19.41.20', 'username': 'user','password': 'pass' }
device1 = ConnectHandler (**device)
command1 = 'show port description'
output1 = device1.send_command (command1)
print (output1)
```
sample output (note the line 2/2/6 got splited after 80 characters):
```
2/2/6          Reserved_for_Nontabur234-Natiyakumdola_10G_sahlaehjffadff_dafgag
               asdgg_adfa453
2/2/7          10/100/Gig Ethernet SFP
2/2/8          10/100/Gig Ethernet SFP
```
I do not have any other type to test with, hope you could look into this matter. 
(Note: This is only seen with the script outputs, not with direct CLI command outputs)

**Comment by ktbyers** [comment]
Okay, I will need the Netmiko log file which you can obtain using this process:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Also make sure you are using Netmiko 3.1.0 when testing.

Kirk

**Comment by nontha** [comment]
Netmiko version: 3.1.0
log file:
[test.log](https://github.com/ktbyers/netmiko/files/4582864/test.log)

**Comment by ktbyers** [comment]
@nontha What does the Huawei CLI output actually look like for `'display interface description'`

In other words, what is the actually output that you get using the CLI here?

**Comment by yoonghm** [comment]
This is not generic. Perhaps you could just implement a python function to join a line with previous line if it has has leading white spaces.

**Comment by ktbyers** [comment]
@yoonghm Unfortunately, that would distort/modify the output for a whole bunch of show commands so there is no way practically to do this.

You should use something like TextFSM to parse the output and handle the line-wrap there.

**Comment by nontha** [comment]
@ktbyers :I found that this is an issue with Huawei device versions.
**V600R007:** (splits with 47 spaces - after 80 characters, to a new line.)
```
GE2/0/17                      down    down     HUAWEI, GigabitEthernet2/0/17 Int
                                               erface                 
GE2/0/18                      down    down     HUAWEI, GigabitEthernet2/0/18 Int
                                               erface                 
GE2/0/19                      down    down     HUAWEI, GigabitEthernet2/0/19 Int
                                               erface  
```               
**V600R009:** (in a single line with 47 spaces when>80 characters.)
```
GE3/0/2                       down    down     HUAWEI, GigabitEthernet3/0/2 Inte                                               rface
GE3/0/3                       down    down     HUAWEI, GigabitEthernet3/0/3 Inte                                               rface
GE3/0/4                       down    down     HUAWEI, GigabitEthernet3/0/4 Inte                                               rface
```
**V800R011**-NO ISSUE:
```
GE3/0/2                       down    down     HUAWEI, GigabitEthernet3/0/2 Interface
GE3/0/3                       down    down     HUAWEI, GigabitEthernet3/0/3 Interface
GE3/0/4                       down    down     HUAWEI, GigabitEthernet3/0/4 Interface
```
Tried increasing the screen width, no change in the output.

**Comment by ktbyers** [comment]
@nontha 

Okay so this sounds like a Huawei issue then (since it is not honoring the terminal width).

What is the Huawei command for setting the terminal width?

**Comment by ktbyers** [comment]
Okay, this doesn't look like a Netmiko issue per-se. It looks like a Huawei issue.

If there is a way to set the screen-width on Huawei on the SSH vty, let me know. The only thing I saw was `screen-width` and that looked like it only applied to the console and not to VTY ports.
