### ISSUE TITLE
SSH Proxy support not working

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#172]
SSH Proxy support is not working. I have it working linux > to linux > to linux (using netmiko), but when I try to do linux > to linux > to cisco it fails with the below.

paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

I can get linux > to linux > to cisco working from command line.

On the Cisco side, it looks like it sends the banner:

Feb  2 13:15:17.572 PST: SSH0: starting SSH control process
Feb  2 13:15:17.572 PST: SSH0: sent protocol version id SSH-2.0-Cisco-1.25
Feb  2 13:15:24.508 PST: SSH0: protocol version id is - SSH-2.0-paramiko_1.15.2
Feb  2 13:15:24.508 PST: SSH2 0: send:packet of  length 416 (length also includes padlen of 11)
Feb  2 13:15:24.508 PST: SSH2 0: send:packet of  length 72 (length also includes padlen of 7)
Feb  2 13:15:24.608 PST: SSH0: Session disconnected - error 0x00

On the Paramiko side, it looks like it thinks there is no banner to be read.

~/.ssh/config looks as follows:

host 50.76.53.27:22
  user pyclass
  hostname 50.76.53.27
  Port 22
  ProxyCommand ssh kbyers@hostname.domain.com nc %h %p

There were some other errors that I had to fix to get the ssh_config parsing working. Fixes for these are committed in https://github.com/ktbyers/netmiko/commit/649dbcd4e10eb497e285662e4410ae45038fd15a

**Comment by ktbyers** [comment]
FYI @coxley

**Comment by coxley** [comment]
@ktbyers Can you post the code snippet used to test? I'll try it on some gear of mine.

**Comment by ktbyers** [comment]
```python
#!/usr/bin/env python

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("my_log")

logger.debug('This message should go to the log file')

from netmiko import ConnectHandler
from getpass import getpass

ip_addr = raw_input("Enter IP Address: ").strip()
device = {
    'device_type': 'cisco_ios',
    'ip': ip_addr,
    'username': 'pyclass',
    'password': getpass(),
    'port': 22,
    'ssh_config_file': '~/.ssh/config',
    'verbose': False,
}
#linux = {
#    'device_type': 'linux',
#    'ip': ip_addr,
#    'username': 'kbyers',
#    'password': getpass(),
#    'port': 22,
#    'ssh_config_file': '~/.ssh/config',
#    'verbose': False,
#} 

net_connect = ConnectHandler(**device)
output = net_connect.send_command('show user')
print output
print
```

**Comment by ktbyers** [comment]
@coxley I could get it to work using the above 'linux' device currently commented out (i.e. linux to linux to linux).

I have some other things in my ~/.ssh/config file (than what I posted above), but I don't think they are relevant.

Note, I also intentionally disabled SSH key auth between linux_start_srv > linux_middle_srv (i.e. forced it be password auth). 

I only tried 'cisco' and 'linux' for Netmiko device type (didn't try 'juniper' or other vendors).

**Comment by ktbyers** [comment]
@coxley It works if I do this (i.e. connect using the ~/.ssh/config file including the ProxyCommand)

```
$ ssh 50.76.53.27:22
kbyers@host.domain.com's password: 
Password: 
pynet-rtr1#
```

**Comment by ktbyers** [comment]
Here is also the log messages that are generated:

```
DEBUG:my_log:This message should go to the log file
DEBUG:paramiko.transport:starting thread (client mode): 0xb69b7cacL
DEBUG:paramiko.transport:Banner:
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/home/gituser/VENV/py27_netmiko/local/lib/python2.7/site-packages/paramiko/transport.py", line 1586, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/home/gituser/VENV/py27_netmiko/local/lib/python2.7/site-packages/paramiko/transport.py", line 1717, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
```

**Comment by ktbyers** [comment]
@coxley FYI, I tested this on Juniper and it works for Juniper...so it looks like a Cisco specific behavior (yuck).

**Comment by ktbyers** [comment]
@jedelman8 FYI, this might be a Cisco specific issue or Cisco IOS specific. I have it working linux to linux to linux and linux to linux to juniper.

Failing linux to linux to Cisco IOS.

**Comment by ktbyers** [comment]
@coxley @jedelman8 I was able to fix this by adding a delay into Paramiko. It looks like there is a timing issue here. See:

https://github.com/paramiko/paramiko/issues/675

**Comment by coxley** [comment]
Interesting. I'm able to get it working on both Force10 (DNOS9) and Juniper.

Timing kind of makes sense - there was a weird bug in trigger recently which was fixed by adding an extra 0.1s timeout to Arista I think.

**Comment by ktbyers** [comment]
Recently received an update on my Paramiko issue post, it sounds like maintainer might incorporate a fix for this (although he thought it was strange that it happened).

**Comment by lundybernard** [comment]
I am also having this issue, attempting to connect through a proxy to a cisco device.
every once in a while, it will work successfully, but it usually fails.

I have the proxy server set up with SSH keys, it may be of note that it throws one of those "WARNING - This device is the property of..." banners, before forwarding to the device.
the device its self just gives a password: prompt, and I am able to log in without issue.

ssh/config:
`
Host myciscohost*
    HostName 10.10.10.10
    ProxyCommand ssh myproxyhost nc %h %p
`
python:
`
device = {
    'device_type':'cisco_ios',
    #'host':'myciscohost',
    'ip':'10.10.10.10',
    'username':'myuser',
    'password':'mypass',
    'ssh_config_file':'~/.ssh/config',
    'global_delay_factor': 4
    }
net_connect = ConnectHandler(**device)
output = net_connect.send_command('show users')
`

**Comment by lundybernard** [comment]
Still working on this issue.  I switched over to python3.5, which gives a bit more info in the stack trace(below):

It looks like, ultimately the error is coming from paramiko's packet.py Packetizer._read_timeout() method.  but I dont think that the actual timeout is the problem.
I raised the timeouts in _check_banner() to ridiculous levels:
```python
    def _check_banner(self):
        # this is slow, but we only have to do it once
        for i in range(100):
            # give them 15 seconds for the first line, then just 2 seconds
            # each additional line.  (some sites have very high latency.)
            if i == 0:
                timeout = 300# MONKEY_PATCH self.banner_timeout
            else:
                timeout = 100# MONKEY_PATCH
            try:
                buf = self.packetizer.readline(timeout)
            except ProxyCommandFailure:
                raise
            except Exception as e:
                raise SSHException('Error reading SSH protocol banner' + str(e))
```
and I still get the same error (after a long delay), so It looks like something else is causing the connection to die prematurely.

==============================================================================
Traceback (most recent call last):
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/paramiko/transport.py", line 1854, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/paramiko/packet.py", line 326, in readline
    buf += self._read_timeout(timeout)
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/paramiko/packet.py", line 496, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/show.py", line 28, in <module>
    net_connect = ConnectHandler(**device)
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 88, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/netmiko/base_connection.py", line 68, in __init__
    self.establish_connection(verbose=verbose, use_keys=use_keys, key_file=key_file)
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/netmiko/base_connection.py", line 165, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/paramiko/client.py", line 325, in connect
    t.start_client()
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/paramiko/transport.py", line 492, in start_client
    raise e
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/paramiko/transport.py", line 1710, in run
    self._check_banner()
  File "/home/lbernard/miniconda3/envs/cisco3/lib/python3.5/site-packages/paramiko/transport.py", line 1858, in _check_banner
    raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

**Comment by ktbyers** [comment]
@lundybernard What type of Cisco device is it?

Does it fix it if you make the delay longer (using the below fix in transport.py). Try making it be 1/2 a second?

```
$ diff transport.py.new transport.py
486,487d485
<         # delay starting thread for SSH proxies
<         event.wait(0.2)
```

**Comment by 2marshall** [comment]
Which location should I be modifying this transport.py file from?

I'm guessing it's this file?

/usr/share/pyshared/paramiko/transport.py

I created a new transport.py.new file and threw in the code you were showing here into the transport.py.new file, ran the diff command but didn't notice a difference.

486,487d485
<         # delay starting thread for SSH proxies
<         event.wait(0.2)

I'm getting a similar issue. I know that the ssh proxy is working with using a straight SSH connection because I've tested outside of python. But within paramiko I get these errors when sshing to an ASA. The weird thing is that with one of the ASA's I can connect just fine using this same script. the other ASA sends this error and never established connection

The code on the "non working" asa is at 8.4(7) the code on the "working" asa is 8.2(5)

Traceback (most recent call last):
  File "config_download_firewalls.py", line 57, in <module>
    ssh_conn_setup.connect(nodeip, username=username, password=enablepass, look_for_keys=False, allow_agent=False)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 251, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/util.py", line 278, in retry_on_signal
    return function()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 251, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out

**Comment by lundybernard** [comment]
Still trying to get this working.
@2marshall, I think I finally deciphered the DIFF and got it working
diff looks like this:
```
486,487d485
<         # delay starting thread for SSH proxies
<         event.wait(5) # MONKEY_PATCH
```
which means you need to change this code around like 486 to look like this:
```python
        # synchronous, wait for a result
        self.completion_event = event = threading.Event()
        # delay starting thread for SSH proxies
        event.wait(3)  # MONKEY_PATCH added wait
        while True:
            #event.wait(0.1) # MONKEY_PATCH increase timeout, was not needed and really slows things down
            if not self.active:
```
Note that the extra event.wait goes BEFORE self.start(), that was throwing me off.
I had to increase the wait time to a full 3 seconds for it to work reliably on my test device (still need to run tests against the full range of devices on our network to find out how many of them will fail with/without the delay)
I suspect the delay is necessary because my proxy takes a long time to forward me to the destination host.  It can take a full count-to-4 after the proxy displays its banner before it gives me the end device's password prompt.

**Comment by lundybernard** [comment]
@ktbyers 
Device types i've tried so far:
    CISCO3945-CHASSIS (revision 1.0)  # 3 of these

after I got your patch in the correct location, I tried a few wait settings.  < 2 fails, 5 works 
I settled on 3 for now.

I can put together some more extensive testing if need be.  let me know if there are any particular device types that you need me to run against, as I can probably find them on my network.

**Comment by 2marshall** [comment]
I had issues with an ASA on 8.4 code and a VXR 7206.

Jesse Shumaker
IT Professional
A+ Net+ CCNA
480.862.5579

**Comment by lundybernard** [comment]
Note:
connecting to the ASR1006 failed with this error when I attempted to connect to it through an un-keyed proxy.  
netmiko kindly asks for my password for the proxy, then asks for confirmation to connect to the unrecognized host (I thought it ignored key checking by default), then it fails.
Keying the proxy fixed the problem.

**Comment by 2marshall** [comment]
hmm... that wait didn't' seem to matter.

can you just send me your transport.py file? also what version of paramiko do you have loaded?

jesseshumaker@gmail.com

**Comment by 2marshall** [comment]
I just keep getting this

Traceback (most recent call last):
  File "config_download_asa.py", line 57, in <module>
    ssh_conn_setup.connect(nodeip, username=username, password=enablepass, look_for_keys=False, allow_agent=False)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 251, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/util.py", line 278, in retry_on_signal
    return function()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 251, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out

**Comment by ktbyers** [comment]
@2marshall At the time I was testing this I was using Paramiko 1.16.0. I haven't regression tested it with Paramiko 2.0.

Your above error looks to be unrelated to this problem. That looks like a connection error? Are you able to connect correctly when not using an SSH proxy?


@lundybernard So it seems like you were observing the same thing that I observed? i.e. that adding a delay generally fixed the problem though the amount of delay required varied. Let me know if this is not correct.

**Comment by 2marshall** [comment]
Kirk,

Yes I can connect just fine when not using the ssh proxy. it works perfectly when just typing ssh [ip address]. the connection jumps from the jumphost to the ASA firewall. I have this same error on both this 5585 ASA and a VXR 7006.

looks like I'm paramiko 1.5.1. could this be the issue?

**Comment by ktbyers** [comment]
@2marshall I don't know if that is the cause of the difference, but you definitely need to test on either Paramiko 1.16.0 or Paramiko 2.0.0.

Probably should be testing on Paramiko 2.0.0 as this is most likely a Paramiko issue (and should be using most recent code).

**Comment by lundybernard** [comment]
@ktbyers Yes, it looks like I'm seeing the same problem you described, and your fix worked, although I had to use a significantly longer timeout (this network is known to be fairly laggy, so its not surprising)

**Comment by ktbyers** [comment]
@lundybernard Okay, thanks.

**Comment by 2marshall** [comment]
hmm same issues for me on version 1.16. I wonder if it's a security mechanism of the ASA because I'm proxying through another host so the source of the packet is being manipulated. 

Do you guys think that if I just setup a paramiko session to the jumphost and than did another nested paramiko session within, if that would allow me communication to these remote devices? I'm debating trying this but was wondering if anyone has attempted this before with success...?

thanks

**Comment by ktbyers** [comment]
@2marshall  What do you mean by a nested Paramiko session?

**Comment by 2marshall** [comment]
I would login via to the jumpbox with the first Paramiko session and then create a for loop within that session that would start another paramiko session for each node I need to connect to and execute the needed commands within.

**Comment by ktbyers** [comment]
@2marshall I don't think that will work (you will end up creating a SSH session from the origin box).

You would have to have Paramiko and Netmiko installed on the jumpbox. You could then use Paramiko to fire off a script on the jumpbox...but usually this is a security issue/not allowed on the jumpbox.

**Comment by 2marshall** [comment]
Hmm.. I gotta figure out howto get this ssh proxy working than. upgraded to 1.16 the same version you had used and made the event.wait(3) changes but still get his error:

Traceback (most recent call last):
  File "config_download_asa.py", line 57, in <module>
    ssh_conn_setup.connect(nodeip, username=username, password=enablepass, look_for_keys=False, allow_agent=False)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-1.16.0-py2.7.egg/paramiko/client.py", line 292, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python2.7/dist-packages/paramiko-1.16.0-py2.7.egg/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/usr/local/lib/python2.7/dist-packages/paramiko-1.16.0-py2.7.egg/paramiko/client.py", line 292, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out

**Comment by ktbyers** [comment]
@2marshall That looks more like an unable to connect SSH message. Is the jumphost allowed to SSH into the relevant network devices (via ACLs)?

**Comment by 2marshall** [comment]
The Firewall I can't connect to has the IP 192.168.41.1. I can just do ssh username@192.168.41.1 and I get a password prompt from that firewall. So I know the ProxyCommand is working fine and there's connectivity. It's something with how paramiko is handling this. Here is the config

host jumphost-company     # AZNOC Jumphost
  user jshumaker
  hostname 10.15.6.29
  port 22

host 192.168.41.1          # Prod ASA
  user jshumaker
  hostname 192.168.41.1
  Port 22
  ProxyCommand ssh jumphost-company nc %h %p

**Comment by ktbyers** [comment]
@2marshall Can you post your Netmiko code (stripped of any confidential information).

**Comment by 2marshall** [comment]
@ktbyers 

Here's the code. I'm just using paramiko until I can get the connections established to all nodes successfully. Once that is complete I'll re-work the code with netmiko. Thanks Kirk

```python
#!/usr/bin/python

##
## Importing Required Modules
##

import getpass
import sys
import os
import time
import datetime
import fileinput
import tftpy
import paramiko

##
## Grabbing Today's Date in Month Day Year format 09092014
##

config_date = str(datetime.datetime.today().strftime('%m%d%Y'))
config_time = str(datetime.datetime.today().strftime('%I%M%S%p'))

##
## Login credentials and Stores these for later use
##

username = 'me'
password = 'password'
enablepass = 'enablepass'
shcmd = 'more system:running'
tftpsrv = '192.168.7.5'

##
## Parsing asa-hosts file for nodeips and than running paramiko sessions against each nodeip
##

with open('/scripts/config_download/Company/asa-hosts', 'r+') as nodelist:
	nodelistcleaned = [line.rstrip('\n') for line in nodelist]
	for nodeip in nodelistcleaned:


		ssh_conn_setup = paramiko.SSHClient()
		ssh_conn_setup.set_missing_host_key_policy(paramiko.AutoAddPolicy())
		ssh_conn_setup.connect(nodeip, username=username, password=enablepass, look_for_keys=False, allow_agent=False)

		print ""
		print "!! SSH Session Established with " + nodeip + " !!"
		print ""

		##
		## Assigns a variable to the Interactive Session we are creating
		##

		ssh_conn_estblsh = ssh_conn_setup.invoke_shell()

		print ""
		print "!! Interactive Session Established with " + nodeip + " !!"
		print ""

		##
		## Begin Command Typing and Capturing Output
		##

		outputbuffer = ssh_conn_estblsh.recv(20000)
		print outputbuffer
		time.sleep(2)
		ssh_conn_estblsh.send("en\n")
		ssh_conn_estblsh.send(enablepass + "\n")
		time.sleep(2)
		outputbuffer = ssh_conn_estblsh.recv(20000)
		print outputbuffer
		ssh_conn_estblsh.send("termin pager 0\n")

		ssh_conn_estblsh.send(shcmd + "\n")
		time.sleep(15)
		receievedconfig = ssh_conn_estblsh.recv(100000000)
					
		with open('/scripts/config_download/Company/' + nodeip + '-' + config_date + '-' + config_time + '-running-config' , 'w+', 1) as runningconfig:
				runningconfig.writelines(receievedconfig)
				os.system("tftpy_client.py  -H " + tftpsrv + " -p 69 -u " + nodeip + '-' + config_date + '-' + config_time + '-running-config')

```

**Comment by ktbyers** [comment]
@2marshall 

```
 I'm just using paramiko until I can get the connections established to all nodes successfully. Once that is complete I'll re-work the code with netmiko.
```

It looks like you have issues with your Paramiko code. I don't think your issue pertains to the above SSH Proxy banner issue.

A couple of things I see (on quick glance)...you aren't passing in an ssh config file (so Paramiko won't even use ~/.ssh/config). Your TFTP will probably be problematic. I would get rid of that while troubleshooting the issue.

You should first start with no SSH proxy and then try to get that working reliably. You can then try to add in the SSH proxy support.

You are redoing a lot of things that are already in Netmiko so it is probably going to be quite a bit of work.

**Comment by 2marshall** [comment]
Kirk,

Thanks for your continued guidance.

In comment to this

"A couple of things I see (on quick glance)...you aren't passing in an ssh config file (so Paramiko won't even use ~/.ssh/config). Your TFTP will probably be problematic. I would get rid of that while troubleshooting the issue."

From the asa-hosts file above If I remove the 192.168.41.1 IP leaving only 10.3.1.1 the script works great from start to finish. So I know the script is working. From the cli of my Debian client I can also just do an `ssh username@192.168.41.1` and I can get a login to the 192.168.41.1 firewall. So the proxy statements within the ~/.ssh/config are working just because the native OpenSSH client uses them by default. Paramiko must still leverage this ~/.ssh/config file regardless of if you place in a pointer to your ~/.ssh/config file.

Since the Paramiko method work fine for other hosts and the direct OpenSSH method via the CLI works for this troubled 192.168.41.1 firewall host I'm still boggled as to why using Paramiko with this 192.168.41.1 sends this connect timeout issue. It's like somehow the traffic is lost when Paramiko is in control of the channel.

**Comment by ktbyers** [comment]
@2marshall 

```
From the asa-hosts file above If I remove the 192.168.41.1 IP leaving only 10.3.1.1 the script works great from start to finish. So I know the script is working. 
```

Yes, you are probably just SSHing directly to the 10.3.1.1 device. You are probably not using SSH proxy. 


```
From the cli of my Debian client I can also just do an ssh username@192.168.41.1 and I can get a login to the 192.168.41.1 firewall. So the proxy statements within the ~/.ssh/config are working just because the native OpenSSH client uses them by default. 
```

You are probably correct that your SSH proxy is working from the CLI, but the above doesn't tell you that. You also have to verify that you are going through the intermediate box in some way (like by looking at your netstat connections). Although maybe you know that you can't SSH to the other box directly, but you should still verify this.


```
Paramiko must still leverage this ~/.ssh/config file regardless of if you place in a pointer to your ~/.ssh/config file.
```

No, I am pretty sure this is not correct and I don't see reasoning that would lead you to believe this (versus just directly connectiong to 10.3.1.1). Remove the ~/.ssh/config file and test the behavior the script to 10.3.1.1 in both cases. You can also verify this with netstat.

```
Since the Paramiko method work fine for other hosts and the direct OpenSSH method via the CLI works for this troubled 192.168.41.1
```

From what you have described and from your code, I still think your script is the cause of the problem and not Paramiko.

**Comment by 2marshall** [comment]
Yep paramiko isn't using the ssh config. I just verified this. Ugh. here I based all my testing off a theory I had of my own which I thought I had proven. 

We can close out this ticket I'll work on rewriting  things in netmiko with reference to the ssh config file.

thanks Kirk for your direction. always helpful :) I'll get around to taking your python automation class one of these day as well. I'm actually going to Cisco Live! in July and signed up for mostly SDN and network programability classes. "The writing is on the wall" with regards to the future of where our industry is heading.

**Comment by ktbyers** [comment]
@2marshall :-)

Yes, I will keep this issue open as the original issue still exists.

You can see this method in Netmiko's base_connection.py file to see what we did for the ssh config file handling:

```
     def _use_ssh_config(self, connect_dict):
```

Have a good time at Cisco Live.


Kirk

**Comment by ktbyers** [comment]
This is no longer an issue with newer version of Paramiko.

I tested:
Python3.4 and Paramiko 2.1.1
Python2.7 and Paramiko 2.1.2
