### ISSUE TITLE
[share]copy running-config tftp:/xxx.xxx.xxx.xxx/filename

### ISSUE THREAD

**Issue by YMont** [ktbyers/netmiko#1721]
Hi Kirk,
I just want to say thank for you and netmiko'hub and share my mistake.

First, I want to use netmiko do "copy running-config to tftp from router"
But, cmd ="copy running-config tftp:/xxx.xxx.xxx.xxx/filename" was wrong
I read your article and I realize "expect_string" method
(Here : https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html)
(Note: If command so long must be divide many small command)

Now, share my solution.
===========================================================
#!/usr/bin/env python
import datetime
import os
import re
import netmiko
from netmiko import ConnectHandler

print("Please wait seconds. Connecting ... \n")

my_device = {
        "host": "xxx.xxx.xxx.xxx", 
        "username": "xxx",
        "password": "xxx",
        "device_type": "cisco_ios",
    }
starttime = datetime.datetime.now()
net_connect = ConnectHandler(**my_device)
net_connect.enable()

print(net_connect.find_prompt())
cmd ="copy running-config tftp:"
result = net_connect.send_command(
    cmd,
    expect_string=r"Address or name of remote host",
    )
result+=net_connect.send_command("xxx.xxx.xxx.xxx",expect_string=r"Destination filename")
result+=net_connect.send_command("filename",expect_string=r"#")

print(result)
endtime = datetime.datetime.now()
print("total time: {}".format(endtime - starttime))

net_connect.disconnect()
===========================================================
Result:
R1#
Address or name of remote host []? Destination filename [R1_config]? !!
2882 bytes copied in 0.292 secs (9870 bytes/sec)

total time: 0:00:07.257475

**Comment by ktbyers** [comment]
Was there a question here?

**Comment by YMont** [comment]
No~
Thanks
