### ISSUE TITLE
fast_cli and exiting configuration mode fails on NX-OS

### ISSUE THREAD

**Issue by lazhao123** [ktbyers/netmiko#1725]
Hi,

I use fast_cli=True and send_config_set() to send few commands to config interfaces, but I got exception "Failed to exit configuration mode"

The commands are: ["int ether1/1", "no switchport", "no description"]
Stack trace:
  File "C:\........\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1739, in send_config_set
    output += self.exit_config_mode()
  File "C:\........\Python\Python37\lib\site-packages\netmiko\cisco_base_connection.py", line 44, in exit_config_mode
    return super().exit_config_mode(exit_config=exit_config, pattern=pattern)
  File "C:\........\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 1622, in exit_config_mode
    raise ValueError("Failed to exit configuration mode")
ValueError: Failed to exit configuration mode

I checked the netmiko source.

    def check_config_mode(self, check_string="", pattern=""):
        self.write_channel(self.RETURN)
        # You can encounter an issue here (on router name changes) prefer delay-based solution
        if not pattern:
            output = self._read_channel_timing()
        else:
            output = self.read_until_pattern(pattern=pattern)  <== this exit after seeing #, note1
        return check_string in output   <=============    this return True

I found, check_string is ")#"
output is:
'\rHHHHHHH(config-if)# no description\r\r\nend\r\n'

The function returns True.

I think output should be something like '\rHHHHHHH(config-if)# no description\r\r\nend\r\nHHHHHHH #', netmiko should check pattern backwards.

note1: If read completely, output should include ".... #". That indicates config mode is exited.

**Comment by lazhao123** [comment]
Hello Kirk,

Can you please look at this issue?

TIA

**Comment by ktbyers** [comment]
Yes, you probably need to turn fast_cli off. 

Those two lines should not be on the same line together.

In other words, your device is responding too slowly and that is causing Netmiko to lose track of the state of the CLI session.

**Comment by lazhao123** [comment]
The device is a new cisco nexus 9k. On CLI, it responds very quick.
for 3 sub-commands like ["int eth 1/1", 'no channel-group', 'no switchport', 'no description'], without fast_cli, it takes 9.5 sec. with fast_cli, it give exception.

But if I give 2 sub-commands such as ["int eth 1/1", 'no switchport', 'no description'], with fast_cli, it takes 1.9 sec and no exception. Looks like fast_cli has issue to handle 3 or more sub-commands.

9.5 sec and 1.9 sec is big difference.

**Comment by ktbyers** [comment]
The fixes we would put into to make fast_cli work would be to make it slower. You could try setting global_delay_factor=.5 and see if that worked potentially. But it will slow things down somewhat.

IIRC under fast_cli=True global_delay_factor=.1 (so you would need to make it something larger than that like .2 or .4/.5 et cetera).

**Comment by lazhao123** [comment]
Thank you, Kirk.
I set global_delay_factor = 0.5, it works.
