### ISSUE TITLE
Dell-OS10 does not properly echo commands sent down SSH channel

### ISSUE THREAD

**Issue by rainap-ui** [ktbyers/netmiko#1737]
Hi 
I'm a newbie at python/netmiko trying to configure a logging server on dell OS10 as below
from netmiko import ConnectHandler

device = {
    "host": "100.64.x.x",
    "username": "praina",
    "password": "S*****",
    "device_type": "dell_os10",
}

net_connect = ConnectHandler(**device) 
config_commands = ["logging server 100.64.x.x severity log-info"]
output = net_connect.send_config_set(config_commands)
print(output)

Error :

C:\Users\praina\Desktop>python\Python38-32\python.exe script.py
Traceback (most recent call last):
  File "C:\Users\praina\Desktop\python\Python38-32\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\praina\Desktop\python\Python38-32\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\praina\Desktop\python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\praina\Desktop\python\Python38-32\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 24, in <module>
    output = net_connect.send_config_set(config_commands)
  File "C:\Users\praina\Desktop\python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1704, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "C:\Users\praina\Desktop\python\Python38-32\lib\site-packages\netmiko\cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(config_command=config_command, pattern=pattern)
  File "C:\Users\praina\Desktop\python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1598, in config_mode
    output += self.read_until_pattern(pattern=re.escape(config_command.strip()))
  File "C:\Users\praina\Desktop\python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\praina\Desktop\python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 551, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

C:\Users\praina\Desktop>

**Comment by Menotomy** [comment]
At least for the second error, in my experience, if it times out when sending a command it means the command is incorrect and is causing some error in the device itself, or the device itself is responding incorrectly. 

I'm not familiar with Dell OS but make sure your config is correct. The command has the IP 100.64.x.x, not sure if you did that for the purpose of an example to hide the actual IP but I'm not sure that would be accepted by the device.

**Comment by ktbyers** [comment]
@rainap-ui Can you get me the Netmiko log file for this issue?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by rainap-ui** [comment]
Hi 
@Menotomy I've deliberately hidden the IPs , i can vouch for the command as thats how we do it manually
 
@ktbyers - 
[test.log](https://github.com/ktbyers/netmiko/files/4655376/test.log)

**Comment by ktbyers** [comment]
Does Dell OS10 have some sort of a command autocompletion?

```
DEBUG:netmiko:write_channel: b'config term\n'
DEBUG:netmiko:Pattern is: config\ term
DEBUG:netmiko:_read_channel_expect read_data: configure term
DEBUG:netmiko:_read_channel_expect read_data: inal
```

Above we write `config term`, but the device echoes `configure terminal`.

Is there a way to turn off this command autocompletion behavior?

**Comment by rainap-ui** [comment]
DEBUG:paramiko.transport:starting thread (client mode): 0x34819e8
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_8.0 PKIX[12.0.1]
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.0)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-256', 'rsa-sha2-512', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey agreed: ssh-ed25519
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-ed25519 host key for 100.64.x.x: b'cd11e4f900a450281e06f372f0c1a1a3'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: b'| **********************************************************\n| *            UNAUTHORIZED ACCESS PROHIBITED              *\n| *                        WARNING                         *\n| *                                                        *\n| * Unauthorized access to this device is prohibited, and  *\n| * violators will be prosecuted to the fullest extent of  *\n| * the law. Activity on this device, and attempted access,*\n| *                      is logged.                        *\n| **********************************************************\n'
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: Linux SW1 4.9.189 #1 SMP Debian 4.9.189-3+deb9u1 x86_64



The programs included with the Debian GNU/Linux system are free software;

the exact distribution terms for each program are described in the

individual files in /usr/share/doc/*/copyright.



Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent

permitted by applicable law.










DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 


DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

SW1# 

SW1# 

SW1# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is SW1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: terminal\ length\ 0
DEBUG:netmiko:_read_channel_expect read_data: te
DEBUG:netmiko:_read_channel_expect read_data: rminal length 0

SW1# 
DEBUG:netmiko:Pattern found: terminal\ length\ 0 terminal length 0

SW1# 
DEBUG:netmiko:terminal length 0

SW1# 
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

SW1# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'config term\n'
DEBUG:netmiko:Pattern is: config\ term
DEBUG:netmiko:_read_channel_expect read_data: configure terminal


DEBUG:netmiko:_read_channel_expect read_data: SW1(config)# 
DEBUG:paramiko.transport:EOF in transport thread

**Comment by rainap-ui** [comment]
I've attaced the log file @ktbyers , thank you

**Comment by ktbyers** [comment]
@rainap-ui Can you test this fix?

https://github.com/ktbyers/netmiko/pull/1743

**Comment by rainap-ui** [comment]
Thanks it works.
