### ISSUE TITLE
Enable Mode on ASA?

### ISSUE THREAD

**Issue by spirrello** [ktbyers/netmiko#174]
Hi Kirk,

I'm trying to setup a connection with an ASA and the following isn't working, actually locking out my service account.  

net_obj = ConnectHandler(device_type = 'cisco_asa', ip = '10.192.2.2', username = 'netadmin', password='password)

#Do I need the following line or should the connecthandler recognize it needs to go into enable mode?  #Do I need to pass the password to do this?
net_obj.enable()

**Comment by ktbyers** [comment]
@spirrello 

What is your normal workflow using SSH on this ASA?

SSH in then enable and separate enable secret?

Assuming this is the workflow, then you would need to do what you did above. You would also need to pass in a secret='secret' argument).

Then call the .enable() method.


Can you also clarify what you mean by 'locking out my service account"?

**Comment by spirrello** [comment]
That's what it was, i was missing the "enable" parameter.  Thanks!

**Comment by spirrello** [comment]
Sorry....I meant I was missing the "secret" parameter.

**Comment by ktbyers** [comment]
@spirrello So you couldn't SSH in after the first attempt failed (i.e. "locking out" service account)?

**Comment by spirrello** [comment]
Because I wasn't passing the secret parameter I ended up locking out my
service account in Active Directory after trying so many times.
