### ISSUE TITLE
SR-OS command echo and configuration commands adds quotes around interfaces

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1740]
Adding @hellt

**Comment by ktbyers** [comment]
Relevant original issue:

https://github.com/ktbyers/netmiko/issues/1723

there were two separate issues in issue #1723 (one Juniper and one SR-OS)

**Comment by ktbyers** [comment]
From the debug output on the SR-OS device:

```
DEBUG:netmiko:write_channel: b'show router ospf interface x-ge3/1/1 detail\n'
DEBUG:netmiko:Pattern is: show\ router\ ospf\ interface\ x\-ge3\/1\/1\ detail
DEBUG:netmiko:_read_channel_expect read_data: show router ospf interface "x-ge3/1/1" detail

DEBUG:netmiko:_read_channel_expect read_data:
```

**Comment by hellt** [comment]
@Enochsoul we are looking for a less intrusive solution for the raised issue, but for now please quote your interface names like

```
print(nc.send_command("show router ospf interface x-ge3/1/1 detail"))
```

**Comment by hellt** [comment]
@Enochsoul after looking at this more carefully I should say there is no _easy_ way to let users not using the quotes around the named objects with Classic CLI

> MD-CLI is not affected by that issue, still I would recommend to use quotes for the named objects as this is the canonical way our shell implements

If using quotes is a huge blocking point, there is a `global_cmd_verify=False` knob that can be turned. Though the negative effect of this might be substantial in some cases, so its better to use quotes =)

**Comment by ktbyers** [comment]
Closing as I think the solution will be one of the following:

1. Use the canonical command form i.e. enclose the interfaces in quotes or
2. Or set global_cmd_verify=False (or possibly use send_config_set with the cmd_verify=False argument).

**Comment by Enochsoul** [comment]
Thanks for looking into it guys.  After a bunch of messing around, my solution had been to use send_command_timing(), and that seemed to work, but your suggested solution is probably a better one.  I should have realized that the SROS CLI auto quotes that network interface field, and changing up the code to include quotes shouldn't be a problem.
