### ISSUE TITLE
I have issue when trying to read config commands from file with netmiko, it works when I put config commands in code manually but from file keep getting this error? Please Help if anyone knows? 

### ISSUE THREAD

**Issue by dusanuksanovic** [ktbyers/netmiko#1744]
![netmiko_send_config_set](https://user-images.githubusercontent.com/65740142/82612413-174be800-9bc3-11ea-9d93-391b5c0055c5.PNG)

**This is my simple code:**

from netmiko import ConnectHandler
username = input("Put your username: ")
password = input("Put your password: ")
    
sw1 = {'device_type':'cisco_ios',
        'ip': '192.168.122.100',
        'username': username,
        'password': password}
    
sw2 = {'device_type':'cisco_ios',
        'ip': '192.168.122.102',
        'username': username,
        'password': password}
    
    
    
switches = [sw1, sw2]
    
with open("list_of_comm_switch") as f:
    conf_commands = f.read().splitlines()
print(conf_commands)
    
for switch in switches:
    conn = ConnectHandler(**switch)
    print("Creating CONFIGURING commands")
    output = conn.send_config_from_file("list_of_comm_switch")
    print(output)

**Comment by daanvdsanden** [comment]
The code and the traceback don't match up. The traceback is failing on the line:
``` output = connection.send_config_set(conflict_command)```
However in your code snippet you have:
``` output = conn.send_config_from_file("list_of_comm_switch") ```

But to get back to your problem what commands are in your file? Are you doing any commands that could kill the connection with the switch?

**Comment by narayanankl** [comment]
@dusanuksanovic , try below the setting which helped my issue which is excatly what you described above.

adding below the two statemests helped me to run my first basic script successful.

net_connect.enable()
'secret': 'test123'
+++++++++++++++++++++++++++++++++++++++++++
from netmiko import ConnectHandler
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

ios_l2 = {'device_type': 'cisco_ios', 'ip': '192.168.122.200', 'username': 'test', 'password': 'test123', 'secret': 'test123'}

net_connect = ConnectHandler(**ios_l2)
output = net_connect.send_command('show ip int brief')
print(output)
net_connect.enable()
config_commands = ['int lo 200']
output = net_connect.send_config_set(config_commands)
print(output)

**Comment by ktbyers** [comment]
Not enough information here--the configuration commands were never specified. Also the exception screenshot and the code shown are not consistent.
