### ISSUE TITLE
netmiko/Cisco IOS Parsing error with textfsm:  textfsm.parser.TextFSMError: State Error raised.

### ISSUE THREAD

**Issue by rapowell** [ktbyers/netmiko#1745]
Hello,
    I opened up an issue with the ntc-templates group (https://github.com/networktocode/ntc-templates/issues/718) and after some discussion, we believe the error I'm coming across is related to how Netmiko is pulling in the ntc_templates.  Would you be able to shed some light on this and how it might be resolved?  Thanks.

**Comment by ktbyers** [comment]
Commented on the original issue.
