### ISSUE TITLE
Blank output from HP switches

### ISSUE THREAD

**Issue by Jordanh517** [ktbyers/netmiko#175]
I'm trying to make a crawler to pull the config from a bunch of HP switches.

However im running into a bit of an issue.

When looking at two switches;
ProCurve J9147A 2910al-48G Switch
Software revision W.14.03

One of them the output is pulled correctly, the other receives nothing.

```
def hp(devices):
    for device in devices:
        hp_dev['ip'] = device['ip']
        filename = device['location'] + device['name'] + "_" + date + ".txt"
        print device['name'] + "   " + device['ip']

        try:
            net_connect = ConnectHandler(**hp_dev)
            net_connect.find_prompt()
            output = net_connect.send_command("show run")
            print output

        except SSHException as e:
            print("Error connecting to {} -- {}".format(hp_dev['ip'], e))
```

Using that code I can see that it is establishing a connection but when printing 'output' it is blank.

Any suggestions?

**Comment by ktbyers** [comment]
@Jordanh517 Does each switch work if you try them individually or does one of them always fail. I.E. if you try this on each switch:

<pre>
            net_connect = ConnectHandler(**hp_dev)
            net_connect.find_prompt()
            output = net_connect.send_command("show run")
            print output
</pre>

It could be that the 'show run' command is taking too long to output on one of the switches. You could try:

<pre>
            output = net_connect.send_command("show run", delay_factor=2)
</pre>

Or could try:

<pre>
            output = net_connect.send_command_expect("show run")
</pre>

Let me know what you find.

**Comment by Jordanh517** [comment]
@ktbyers Fantastic! Both of your suggestions fix the issue.

Looking at the configs for the ones that didn't previously work; they are a fair bit larger than the ones that did work. So I think it was an issue with it taking a bit too long to run.

Thanks!
