### ISSUE TITLE
Aruba 2530 exception Timed-out reading channel, data not available on send_config_set()

### ISSUE THREAD

**Issue by GameMaster47** [ktbyers/netmiko#1751]
Greetings,

I'm running a script to configure a vlan on a switch based on a list of MACs, and for one of the switches I've been seeing a iregular behavior. Sometimes the script runs without raising exceptions and the configuration is applied, but sometimes it raises an error during the send_config_set().
I have a lab with a HP procurve 2620 and a Aruba 2530, and i'm using 'hp_procurve' as the device type for both. The exception only occurs on the Aruba switch.

I've tried changing the 'global_delay_factor' to 2 and 4, but have the same behavior.

Please find attached the exception trace and the session log of the device.

This is the code I'm executing:
```
       sw = {
            'ip':switch['IPAddress'] ,
            'username': USERNAME,
            'password': PASS,
            'device_type': switch['device_type'],
            'global_delay_factor':4,
            'session_log':'session.log'
        }
        conn = ConnectHandler(**sw)
        lldp = conn.send_command_timing("show lldp info remote")
        logger.info(lldp)
        showMac = conn.send_command_timing("show mac-address")
        logger.info(showMac)
        showTrunk = conn.send_command_timing("show trunks")
        logger.info(showTrunk)
        trunkDict = dict(re.findall('(\d+).*(Trk\d+)',showTrunk))
        for mac in macs:
            mac_lldp = mac.lower().replace("-", " ")
            mac_cam = f'{mac.lower().replace("-", "")[0:6]}-{mac.lower().replace("-", "")[6:12]}'
            if mac_lldp in lldp:
                match = re.findall(f'(\d+)\s+\|\s+{mac_lldp}', lldp)
                print(f'this MAC was scrapped from LLDP : {mac} | interface(s) {match}')
                [ports.add(trunkDict[port]) if port in trunkDict else ports.add(port) for port in match]
            elif mac_cam in showMac:
                match = re.search(f'{mac_cam}\s+(\w*\d+)?', showMac)
                print(f'this MAC was scrapped from CAM: {mac} | interface(s) {match.group(1)}')
                if match.group(1) in trunkDict:
                    ports.add(trunkDict[match.group(1)])
                else:
                    ports.add(match.group(1))
            else:
                logger.error("MAC Not Found on this Device. It might be temporarily down. Please refer to the logs to investigate further")
        if ports != False:
            print(f"Configuring vlan {H20_VLANID} on the following interfaces {','.join(ports)}")
       conn.send_config_set([f"vlan {H20_VLANID}", f"name {H20_VLANNAME}", f'tagged ethernet {",".join(ports)}'])`

```
[session.log](https://github.com/ktbyers/netmiko/files/4671965/session.log)
[exception.txt](https://github.com/ktbyers/netmiko/files/4671978/exception.txt)

Kind regards,

**Comment by BapRx** [comment]
Hi, I was about to open an issue when I found out I wasn't the only one having issues.
I have the same behavior with my switches, my script is working fine with the procurve but not with our aruba 2530.

I noticed a very strange behavior, everything is OK when the logging module is configured to log to stdout:
```
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname).4s | %(funcName)s() : %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
```
but functions like conn.enable(), conn.check_enable_mode(), conn.send_config_set() etc are always failing with timeout when I log to a file:
```
logging.basicConfig(
    filename=time.strftime("%Y-%m-%d_%H-%M.log"),
    filemode="w",
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname).4s | %(funcName)s() : %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
```

• Are you logging to a file and if so can you try without to check if you can reproduce this behavior?
• I just started using this tool so I'm not able to say if this behavior appeared after an upgrade. Did you use this tool before?

Tested with :
Python 3.7.3, netmiko==3.1.1, paramiko==2.7.1
Python 3.8.3, netmiko==3.1.0, paramiko==2.7.1

**Comment by GameMaster47** [comment]
Hello,

I was indeed logging with level=DEBUG to a file, and also generating a session_log file that is a parameter for the ConnectHandler function. 

I'm relatively new to netmiko so I've not been able to try out with different versions of this tool but I'm using:
Python 3.8.2,netmiko==3.1.1, paramiko==2.7.1

Your input was very  appreciated and I've done some testing based on it.

Testing only with the aruba switch:
Basically i've done 20 iteractions with logging only to stdout and with a delay_factor of 2.
The result was 1 Timeout exception in 20 iteractions, taking about 26 minutes to complete

Then, I've done the same but with logging to a file, delay_factor of 2 and without the session_log parameter on ConnectHandler: 
I've got 2 timeout Exceptions in 20 iteractions, with ruffly the same time.

Lastly I've done the same iteractions with logging to console, delay_factor of 2 and with session_log parameter on the ConnectHandler:
I've got no timeouts this time.

So, as a last test I run the script again but this time with both switches.
delay_factor of 2,
session_log on
logging.DEBUG to file

This time I, for the 20 iterations I've got 5 timeouts, all of them raised by the aruba session.
This still seems pretty "random" behaviour to me...

One thing I've notice is that when the timeout happens I got this on the debug:


`
DEBUG:netmiko:write_channel: b'config term\n'
DEBUG:netmiko:Pattern is: config\ term
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[232;18Hconfig ter\x1b[1000;18H\x1b[?25h\x1b[1000;28H\x1b[232;28Hm\x1b[1000;28H\x1b[?25h\x1b[1000;29H\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;29H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HSW002-HPT960902(config)# \x1b[1000;1H\x1b[232;26H\x1b[1000;1H\x1b[?25h\x1b[1000;26H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = config termSW002-HPT960902(config)# 
DEBUG:netmiko:repr = 'config termSW002-HPT960902(config)# '
DEBUG:netmiko:_read_channel_expect read_data: config termSW002-HPT960902(config)# 
DEBUG:netmiko:Pattern found: config\ term config termSW002-HPT960902(config)# 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;26H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HSW002-HPT960902(config)# \x1b[1000;1H\x1b[232;26H\x1b[1000;1H\x1b[?25h\x1b[1000;26H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = SW002-HPT960902(config)# 
DEBUG:netmiko:repr = 'SW002-HPT960902(config)# '
DEBUG:netmiko:read_channel: SW002-HPT960902(config)# 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'vlan 20\n'
DEBUG:netmiko:Pattern is: vlan\ 20
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[232;26Hvlan 20\x1b[1000;26H\x1b[?25h\x1b[1000;33H\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;33H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HSW002-HPT960902(vlan-20)# \x1b[1000;1H\x1b[232;27H\x1b[1000;1H\x1b[?25h\x1b[1000;27H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = vlan 20SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:repr = 'vlan 20SW002-HPT960902(vlan-20)# '
DEBUG:netmiko:_read_channel_expect read_data: vlan 20SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:Pattern found: vlan\ 20 vlan 20SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:write_channel: b'name Hotspot2.0\n'
DEBUG:netmiko:Pattern is: name\ Hotspot2\.0
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[232;27Hname Hotsp\x1b[1000;27H\x1b[?25h\x1b[1000;37H\x1b[232;37Hot2.0\x1b[1000;37H\x1b[?25h\x1b[1000;42H\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;42H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = name Hotspot2.0
DEBUG:netmiko:repr = 'name Hotspot2.0'
DEBUG:netmiko:_read_channel_expect read_data: name Hotspot2.0
DEBUG:netmiko:Pattern found: name\ Hotspot2\.0 name Hotspot2.0
DEBUG:netmiko:Pattern is: (?:SW002\-HPT960902|#)
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HSW002-HPT960902(vlan-20)# \x1b[1000;1H\x1b[232;27H\x1b[1000;1H\x1b[?25h\x1b[1000;27H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:repr = 'SW002-HPT960902(vlan-20)# '
DEBUG:netmiko:_read_channel_expect read_data: SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:Pattern found: (?:SW002\-HPT960902|#) SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:write_channel: b'tagged ethernet 43,40,Trk1\n'
DEBUG:netmiko:Pattern is: tagged\ ethernet\ 43,40,Trk1
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[232;27Htagged eth\x1b[1000;27H\x1b[?25h\x1b[1000;37H\x1b[232;37Hernet 43,4\x1b[1000;37H\x1b[?25h\x1b[1000;47H\x1b[232;47H0,Trk1\x1b[1000;47H\x1b[?25h\x1b[1000;53H\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;53H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = tagged ethernet 43,40,Trk1
DEBUG:netmiko:repr = 'tagged ethernet 43,40,Trk1'
DEBUG:netmiko:_read_channel_expect read_data: tagged ethernet 43,40,Trk1
DEBUG:netmiko:Pattern found: tagged\ ethernet\ 43,40,Trk1 tagged ethernet 43,40,Trk1
DEBUG:netmiko:Pattern is: (?:SW002\-HPT960902|#)
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HSW002-HPT960902(vlan-20)# \x1b[1000;1H\x1b[232;27H\x1b[1000;1H\x1b[?25h\x1b[1000;27H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:repr = 'SW002-HPT960902(vlan-20)# '
DEBUG:netmiko:_read_channel_expect read_data: SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:Pattern found: (?:SW002\-HPT960902|#) SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;27H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HSW002-HPT960902(vlan-20)# \x1b[1000;1H\x1b[232;27H\x1b[1000;1H\x1b[?25h\x1b[1000;27H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:repr = 'SW002-HPT960902(vlan-20)# '
DEBUG:netmiko:read_channel: SW002-HPT960902(vlan-20)# 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'end\n'
DEBUG:netmiko:Pattern is: end
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[232;27Hend\x1b[1000;27H\x1b[?25h\x1b[1000;30H\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;30H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HSW002-HPT960902# \x1b[1000;1H\x1b[232;18H\x1b[1000;1H\x1b[?25h\x1b[1000;18H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = endSW002-HPT960902# 
DEBUG:netmiko:repr = 'endSW002-HPT960902# '
DEBUG:netmiko:_read_channel_expect read_data: endSW002-HPT960902# 
DEBUG:netmiko:Pattern found: end endSW002-HPT960902# 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;18H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HSW002-HPT960902# \x1b[1000;1H\x1b[232;18H\x1b[1000;1H\x1b[?25h\x1b[1000;18H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = SW002-HPT960902# 
DEBUG:netmiko:repr = 'SW002-HPT960902# '
DEBUG:netmiko:read_channel: SW002-HPT960902# 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:exit_config_mode: endSW002-HPT960902# 
DEBUG:netmiko:config termSW002-HPT960902(config)# vlan 20SW002-HPT960902(vlan-20)# name Hotspot2.0SW002-HPT960902(vlan-20)# tagged ethernet 43,40,Trk1SW002-HPT960902(vlan-20)# endSW002-HPT960902#
`

When it fails is always at this step:

`
DEBUG:netmiko:write_channel: b'config term\n'
DEBUG:netmiko:Pattern is: config\ term
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x1b[232;18Hconfig ter\x1b[1000;18H\x1b[?25h\x1b[1000;28H\x1b[232;28Hm\x1b[1000;28H\x1b[?25h\x1b[1000;29H\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;29H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HSW002-HPT960902(config)# \x1b[1000;1H\x1b[232;26H\x1b[1000;1H\x1b[?25h\x1b[1000;26H'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = config termSW002-HPT960902(config)# 
DEBUG:netmiko:repr = 'config termSW002-HPT960902(config)# '
DEBUG:netmiko:_read_channel_expect read_data: config termSW002-HPT960902(config)# 
DEBUG:netmiko:Pattern found: config\ term config termSW002-HPT960902(config)# 
DEBUG:netmiko:Pattern is: SW002\-HPT960902\#
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
`

**Comment by BapRx** [comment]
Hello,
I have good news! I solved my problem and I hope that what I found will help you as well.

After a while troubleshooting the two files `netmiko/base_connection.py` and `netmiko/hp/hp_procurve.py` I found out that the source of my issue was in the find_prompt() function:

https://github.com/ktbyers/netmiko/blob/8d3b2bf79d68c125038a87799245d5ec0da1c8fd/netmiko/base_connection.py#L1081-L1095

The delay_factor is by default 1 so function waits 0.1s for the prompt to be printed before calling `self.read_channel()`.
Well, 0.1s doesn't seem to be enough because the variable was always empty.

I then forced sleep_time to 1 and my problem disappeared. I'd encourage you to try playing with the delay_factor to see if it solves your issue.
There is a few ways to do this :
• Set the delay_factor globally from your code, this will be applied to every function using this delay:
```
sw= {
    "host": "10.10.10.10",
    "username": input("Please enter your username: "),
    "password": getpass("Please enter your password: "),
    "device_type": "hp_procurve",
    "secret": "enasecret",
    "global_delay_factor": 2, # Choose the value you want, knowing that it will be multiplicated by 0.1.
}
ssh = ConnectHandler(**sw)
```

• Another option would be to call the `set_base_prompt` function after creating the connection but since ConnectHandler() does it already (in `session_preparation()`) would be a duplicated task execution:
```
sw= {
    "host": "10.10.10.10",
    "username": input("Please enter your username: "),
    "password": getpass("Please enter your password: "),
    "device_type": "hp_procurve",
    "secret": "enasecret"
}
ssh = ConnectHandler(**sw)
ssh.set_base_prompt(
    pri_prompt_terminator="#",
    alt_prompt_terminator=">",
    delay_factor=5
)
```
• Finally the real fix for me would be to edit the `netmiko/hp/hp_procurve.py `module to set a default delay only when calling `self.set_base_prompt()`:
```
self.set_base_prompt(delay_factor=5)
```

I tested my script with or without logging and I hadn't had any issue so far. I guess the debug to console was wasting just enough time for the prompt to be printed!

**Comment by BapRx** [comment]
Just FYI here's a simple benchmark of 10 iteration of a simple script:

1. connect
2. enable()
3. check_enable_mode()
4. disconnect()

I tried my solutions above in the same order:
• ./local_password_change.py -s 10.10.10.10 1.36s user 0.75s system 0% cpu **10:13.40 total**
• ./local_password_change.py -s 10.133.3.28  1.50s user 0.73s system 0% cpu **3:44.60 total**
• ./local_password_change.py -s 10.133.3.28  1.23s user 0.72s system 0% cpu **3:43.12 total**

**Comment by BapRx** [comment]
Just FYI here's a simple benchmark of 10 iteration of a simple script:

1. connect
2. enable()
3. check_enable_mode()
4. disconnect()

I tried my solutions above in the same order:
• ./local_password_change.py -s 10.10.10.10 1.36s user 0.75s system 0% cpu **10:13.40 total**
• ./local_password_change.py -s 10.10.10.10 1.50s user 0.73s system 0% cpu **3:44.60 total**
• ./local_password_change.py -s 10.10.10.10 1.23s user 0.72s system 0% cpu **3:43.12 total**

**Comment by GameMaster47** [comment]
Sorry,

Didn't have the time to further look into this, so I just used a while loop for retry that multiplies by two for each iteration that fails.

I'll try to replicate your implementation and see if it fixes this. I might still leave the while loop just to make sure.

Best regards

**Comment by GameMaster47** [comment]
Hi,

Good news! your solution also worked for me. Thanks for your help BapRx.
