### ISSUE TITLE
Nokia Sros MDCLI only support on Python 3.x (not 2.7)

### ISSUE THREAD

**Issue by WhistMo** [ktbyers/netmiko#1755]
Nokia Sros MDCLI only support on Python 3.x (not 2.7)
In python 2.7, it is not supported. For example, fail to enter configuration mode (as the check pattern is wrong).

Could you help to support MDCLI on Python 2.7 as well?

Many thanks

**Comment by ktbyers** [comment]
Python 2.7 is no more (i.e. it is no longer supported by the Python maintainers).

So no, you would have to write that support yourself.


Regards, Kirk
