### ISSUE TITLE
Netmiko requires Python 3.6 or greater.

### ISSUE THREAD

**Issue by Newonegit** [ktbyers/netmiko#1761]
Hi guys, I'm only trying to test netmiko code for ssh connection to an emulated L2 switch on GNS3, but I'm receiving an error, I'm not an expert so I believe you can help me with this.

This is the code:

from netmiko import ConnectHandler

iosv_l2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.200',
    'username': 'cisco123',
    'password': 'cisco'
}

net_connect = ConnectHandler(**iosv_l2)
output = net_connect.send_command('show ip int brief')
print (output)

config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print (output)

for n in range (2,21):
    print ("Creating VLAN " + str(n))
    config_commands = ['vlan ' + str(n), 'name Python_VLAN ' + str(n)]
    output = net_connect.send_config_set(config_commands)
    print (output)

root@NetworkAutomation-1:~# python Netm1.py

Traceback (most recent call last):
  File "Netm1.py", line 1, in <module>
    from netmiko import ConnectHandler
  File "/usr/local/lib/python2.7/dist-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python2.7/dist-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python2.7/dist-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax

I've got this versions of netmiko and paramiko:
Name: netmiko
Version: 3.1.0

Name: paramiko
Version: 2.7.1

Please give me some advice guys, I'll really appreciate your ideas.

**Comment by aleksandr-bembel** [comment]
The syntax of f-string, that used by netmiko is introduced in python 3.6, but you try to use python 2.7. As I understand netmiko 2.4.2 is last version that supports Python 2.7.

**Comment by ktbyers** [comment]
Yep, newer Netmiko requires Python3.6 or greater.
