### ISSUE TITLE
Nokia_SROS adding backspace characters to output

### ISSUE THREAD

**Issue by Enochsoul** [ktbyers/netmiko#1764]
I'm using the textfsm processing to pull command output tables, and I noticed that on some devices it wasn't returning the expected output but on others it was.  Further examination from the Netmiko debug logs I found that the return seemed to be including backspace control characters that were messing up the output spacing and throwing off the textfsm parse.

The code doesn't seem to matter, as I get the same result from an interactive python env as I do in a built script, so here's what I'm doing and the output I'm seeing.

**Not working:**
```
>>> net_connect = Netmiko(host='10.187.165.188', username='ipmetro-script', password='*******', device_type='nokia_sros')
>>> output = net_connect.send_command('show router ospf neighbor')
>>> print(output)
===============================================================================
Rtr Base OSPFv2 Instance 0 Neighbors
===============================================================================
Interface-Name                   Rtr Id          State      Pri  RetxQ   TTL
   Area-Id
-------------------------------------------------------------------------------
  x-ge1/1/25                       10.187.165.155  Full       1    0       39
   0.0.0.0
    ge1/1/20                         10.186.16.2     Full       1    2       38
   0.0.0.0
  -------------------------------------------------------------------------------
No. of Neighbors: 2
===============================================================================
>>> net_connect.disconnect()

```
Each of the interface names should be right against the left margin, but they are spaced away.  Here's one that works properly, with the exact same command, though the device is a different type of hardware:

**Working**
```
>>> net_connect = Netmiko(host='10.187.166.141', username='ipmetro-script', password='*******', device_type='nokia_sros')
>>> output = net_connect.send_command('show router ospf neighbor')
>>> print(output)                                                                                                   
===============================================================================
Rtr Base OSPFv2 Instance 0 Neighbors
===============================================================================
Interface-Name                   Rtr Id          State      Pri  RetxQ   TTL
   Area-Id
-------------------------------------------------------------------------------
x-ge1/1/1                        10.187.166.134  Full       1    0       37
   0.0.0.0
x-ge2/1/1                        10.187.166.135  Full       1    0       31
   0.0.0.0
x-ge1/2/1                        10.187.166.191  Full       1    0       35
   0.0.0.0
-------------------------------------------------------------------------------
No. of Neighbors: 3
===============================================================================
>>> net_connect.disconnect()
```

Attached the relevant Netmiko logs as well.  I've tried post-processing with the strip_backspace() method, but it doesn't seem to work, and defeats the purpose of doing textfsm inline with the send_command(unless of course I'm using it incorrectly, which I'll admit is as likely as anything else since I'm a network engineer first and reasonably new to this automation journey).
[backspace control logs.txt](https://github.com/ktbyers/netmiko/files/4691904/backspace.control.logs.txt)

Thanks in advance for any insight you can provide.

**Comment by ktbyers** [comment]
Adding @hellt

**Comment by ktbyers** [comment]
When you say the `strip_backspaces` doesn't seem to work--can you provide some more details on what that means?

Also is this your own TextFSM template or one from ntc-templates?

**Comment by ktbyers** [comment]
On a failing device what does this show:

```python
net_connect = Netmiko(host='10.187.165.188', username='ipmetro-script', password='*******', device_type='nokia_sros')
output = net_connect.send_command('show router ospf neighbor')
output = net_connect.strip_backspaces(output)
print(output)
print("-" * 80)
print(repr(output))
print("-" * 80)
```

**Comment by Enochsoul** [comment]
I'm using my own textfsm template.  There aren't that many Nokia SROS templates in ntc-templates, but the output works on other devices that don't seem to send the backspace control(or netmiko handles it differently?)

Here's the output from your commands:
```
>>> output = net_connect.send_command("show router ospf neighbor")
>>> output = net_connect.strip_backspaces(output)
>>> print(output)

===============================================================================
Rtr Base OSPFv2 Instance 0 Neighbors
===============================================================================
Interface-Name                   Rtr Id          State      Pri  RetxQ   TTL
   Area-Id
-------------------------------------------------------------------------------
  x-ge1/1/25                       10.187.165.155  Full       1    0       33
   0.0.0.0
    ge1/1/20                         10.186.16.2     Full       1    0       35
   0.0.0.0
  -------------------------------------------------------------------------------
No. of Neighbors: 2
===============================================================================
>>> print("-" * 80)
--------------------------------------------------------------------------------
>>> print(repr(output))
'  \n===============================================================================\nRtr Base OSPFv2 Instance 0 Neighbors\n===============================================================================\nInterface-Name                   Rtr Id          State      Pri  RetxQ   TTL\n   Area-Id\n-------------------------------------------------------------------------------\n  x-ge1/1/25                       10.187.165.155  Full       1    0       33\n   0.0.0.0\n    ge1/1/20                         10.186.16.2     Full       1    0       35\n   0.0.0.0\n  -------------------------------------------------------------------------------\nNo. of Neighbors: 2\n==============================================================================='
>>> print("-" * 80)
--------------------------------------------------------------------------------
```
I did the same thing as your requested commands, but I'm pretty sure I was still seeing the command characters.  Your output doesn't show the characters, but the extra spaces remain.

**Comment by ktbyers** [comment]
Okay, one last thing, can you print:

```print
net_connect = Netmiko(
    host="10.187.165.188",
    username="ipmetro-script",
    password="*******",
    device_type="nokia_sros",
)
output = net_connect.send_command("show router ospf neighbor")
print(repr(output))
```

In other words, I want to see what the unmodified output looks like.


Thanks, Kirk

**Comment by ktbyers** [comment]
Also which version of Netmiko are you using?

**Comment by hellt** [comment]
Hi @Enochsoul 
can you share what HW and its SR OS version you're running which results in a failed output result?

**Comment by Enochsoul** [comment]
@ktbyers 
I was running 3.1.0 when I first noticed, and while troubleshooting initially upgraded to 3.1.1.  Python version 3.6.9.  Here's the other output you requrested:
```
>>> print(repr(output))
'  \n===============================================================================\nRtr Base OSPFv2 Instance 0 Neighbors\n===============================================================================\nInterface-Name                   Rtr Id          State      Pri  RetxQ   TTL\n   Area-Id\n-------------------------------------------------------------------------------\n  x-ge1/1/25                       10.187.165.155  Full       1    0       33\n   0.0.0.0\n    ge1/1/20                         10.186.16.2     Full       1    0       35\n   0.0.0.0\n  -------------------------------------------------------------------------------\nNo. of Neighbors: 2\n==============================================================================='
```
@hellt 
The device in the examples is a 7210 SAS-Mxp, though I've tested against a 7210 SAS-M and gotten the same results.  Both were running TiMOS 10.0.R4.

**Comment by hellt** [comment]
@Enochsoul I'll wait for @ktbyers comments wrt to the backspace chars not having effect, maybe that is something he saw with other devices.

On the other hand, this is 10 years old software, clearly it handles the CLI render a bit differently. Lets see if there is a way in netmiko to handle that...

as an interim measure I am afraid you would need to either remove the spaces yourself, or create a TextFSM template that will expect spaces to either be or not be

**Comment by ktbyers** [comment]
So if I am reading this issue/output correctly what I am seeing is that SR-OS is adding backspaces and spaces into the output.

Netmiko can strip the backspaces as per the calls to the `strip_backspaces`, but that would still leave the extra spaces (which will cause the output to be not visually aligned properly).

@hellt Let me know if this is different than your read of the output.

The easiest solution is probably just to account for different number of spaces in the TextFSM output.

Is this a model-driven CLI device or a classical CLI device.

Regards, Kirk

**Comment by hellt** [comment]
@ktbyers yes, I am reading it the same. The software version of that is way too old (10yrs back) to even ask "wtf is happening" internally.

the only thing that comes to my mind is to make an additional function for such old releases that will count the number of backspace chars per line and will remove the same number of spaces from the left for such lines.

I would name that func _the_old_software_strikes_back()_

**Comment by ktbyers** [comment]
Yeah, I think it should just be in the TextFSM template. It is just whitespace so really shouldn't be a problem in the template (in general).

Okay, I am going to close this as I don't think there is anything to do on the Netmiko side.
