### ISSUE TITLE
Netmiko Threading 

### ISSUE THREAD

**Issue by jkartheek999** [ktbyers/netmiko#1765]
I am trying to use a script where in the code will login to network devices update in a file whether the authentication is success or failure. The code works fine when python is running sequential. When using threading to login in parallel, the script is skipping line from the ip.txt file. It is skipping all the odd lines and picking only the even line IP address and confirming (success/failure). Not sure what change i need to make for reading all the lines. Attaching the code.
[MultiAut.txt](https://github.com/ktbyers/netmiko/files/4693052/MultiAut.txt)
[newip.txt](https://github.com/ktbyers/netmiko/files/4693057/newip.txt)

**Comment by ktbyers** [comment]
Have you thought about using Nornir + Netmiko so you can use Nornir's built-in threading mechanisms?

**Comment by jkartheek999** [comment]
I have very limited knowledge on python. It will be very helpful if you can advice me how can i script the multi threading and integrate my existing script with nornir?

Thanks for your help

**Comment by ktbyers** [comment]
I would start with the Nornir tutorial which should be readily available online. If you have very limited Python knowledge then I would definitely recommend you don't try to write your own threading code and instead use Nornir or potentially Ansible.

**Comment by jkartheek999** [comment]
Thank you. I will go through the online tutorial.
