### ISSUE TITLE
establish ssh connection from Router to another Router 

### ISSUE THREAD

**Issue by shafi03** [ktbyers/netmiko#177]
can establish another ssh to Router using netmiko? in our setup, we telnet the second router from direct connected router. 

  

![untitled](https://cloud.githubusercontent.com/assets/17315267/13154956/79d959d6-d68c-11e5-8737-ad3d6839df9d.png)

**Comment by ktbyers** [comment]
@shafi03 So you SSH to R1 and then telnet to R2?

**Comment by shafi03** [comment]
Yes either telnet or ssh to R2

**Comment by ktbyers** [comment]
@shafi03 SSH might work if you ssh Proxy. I have never tried it through a router, however. I have tried it through a Linux host.

I am probably going to try to write something up about this in a couple of weeks.

This article talks about ProxyCommand:

http://www.cyberciti.biz/faq/linux-unix-ssh-proxycommand-passing-through-one-host-gateway-server/

Go to the section pertaining to a ./ssh/config file. You would need to pass the SSH config file in as an argument.

**Comment by shafi03** [comment]
@ktbyers Thanks.. I really appricate your help.

**Comment by ktbyers** [comment]
@shafi03 Also see:

https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html
