### ISSUE TITLE
default terminal height too high

### ISSUE THREAD

**Issue by roku6000** [ktbyers/netmiko#1771]
Since netmiko 3.1.1, the default terminal width and height are set. ([c205dce](https://github.com/ktbyers/netmiko/commit/c205dce6f4aaf10ac68023f705528fc745a48c76))
(width: 511, height: 1000)

I think the default terminal height should be set to 511.
IOS/IOS-XR supports terminal height up to 512. (NX-OS: 511)
<pre>
RP/0/RP0/CPU0:TEST-XR#terminal length ?
  <0-512>  Number of lines on screen (0 for no pausing).
</pre>
If the terminal height is set to 513 or higher in IOS-XR, the following log will be output.
<pre>
SSHD_[68086]: %SECURITY-SSHD-3-ERR_ERRNO : Failed to set window size: %s 'tty-infra' detected the 'fatal' condition 'An invalid operation has been requested'
</pre>

**Comment by ktbyers** [comment]
Okay, this is just a warning, however, everything else continues fine--correct?

**Comment by ktbyers** [comment]
Note, this pertains to the following (i.e. vt100 width and height).

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L918-L920

Netmiko still separately sets `terminal length 0` and `terminal width 511` for IOS-XR.

**Comment by roku6000** [comment]
Yes, just a waning.
Netmiko works fine and doesn't affect the IOS-XR.

**Comment by roku6000** [comment]
Fixed in this commit.
https://github.com/ktbyers/netmiko/pull/1876
