### ISSUE TITLE
paramiko.ssh_exception.SSHException: No existing session

### ISSUE THREAD

**Issue by ajwillo** [ktbyers/netmiko#1775]
Hello,

I can see multiple closed tickets for this issue, which suggest increasing timeout will resolve, however I have the timeout at 8 seconds and I still get the issue sporadically.

is it possible to integrate an exception for this?

I currently use the below, but as the exception is within paramiko not netlike I think this is the reason why my script then fails on this device?

is it possible to raise an exception that wouldn't cause a script to fail?

    except NetmikoTimeoutException:
    except NetmikoAuthenticationException:
    except Exception as e:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/itapp/itapp/config/tasks.py", line 512, in config_ise_remedials
    conn = ConnectHandler(**device_details)
  File "/usr/local/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 259, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 332, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.7/site-packages/netmiko/base_connection.py", line 901, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 412, in connect
    server_key = t.get_remote_server_key()
  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 834, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session`

**Comment by ktbyers** [comment]
Sure:

```python
try:
    some_python_code
except Exception:
    pass
```

Note, your SSH session is dead, however, so you won't be able to use it subsequently. Also note, Paramiko uses threads here so you still might see output (probably on standard error). 

Have you increased the relevant timeout to a larger value?


Kirk

**Comment by ktbyers** [comment]
You probably need to post a broader section of your code for me to help much...

**Comment by ajwillo** [comment]
here's the function,

im using celery to create an array of tasks, group the results and email me output.
however every now and then ill see a task fail with the SSH exception as above.

I would of thought that "except Exception as e:" would of caught it but for some reason it does not, I get the paramiko error. its sporadic though so not reproducible every time

Thanks 

`creds = get_credentials('device monitoring account')
    if 'Error:' in str(creds):
        return creds

    device_details = {
            'device_type': 'cisco_ios',
            'ip': ip,
            'username': creds.username,
            'password': creds.password,
            'port' : 22,
            'secret': '',
            'verbose': False,
            'timeout': 8,
            'global_delay_factor': 3
        }
    conn = ConnectHandler(**device_details)
    try:
        # archive the config
        data = conn.send_command('archive config')
        # get the config
        data = conn.send_command('term len 0')
        config_data = conn.send_command('show run')
        # turn config into list so can be parsed
        config= config_data.split('\n')

        parse = CiscoConfParse(config)
        # find auth open ports
        auth_open = parse.find_parents_w_child("^interface", "authentication open")
        # create a command set for ports
        command_set = []
        for intf in auth_open:
            command_set.append(intf)
            command_set.append('no authentication open')
        # send the commands
        conn.send_config_set(command_set)

        # disconnect from device
        conn.disconnect()
        results = '{} ports set to no auth open {}'.format(hostname, len(auth_open))
        # upload the results, will be able to collate results with task_id
        device_info = {
            'hostname': hostname,
            'device_id': device_id,
            'ip': ip,
            'results': results
            }
    except NetmikoTimeoutException:
        results = 'Error: {} - {} - Timed out trying to connect to device'.format(hostname, ip)
        device_info = {
            'hostname': hostname,
            'device_id': device_id,
            'ip': ip,
            'results': results
            }
    except NetmikoAuthenticationException:
        results = 'Error: {} - {} - Unable to login to device'.format(hostname, ip)
        device_info = {
            'hostname': hostname,
            'device_id': device_id,
            'ip': ip,
            'results': results
            }
    except Exception as e:
        results = 'Error: {} - {} - {}'.format(hostname, ip, e)
        device_info = {
            'hostname': hostname,
            'device_id': device_id,
            'ip': ip,
            'results': results
            }

    return device_info`

**Comment by ktbyers** [comment]
I would expect your exception handling did catch it AND you are still seeing messages on standard error due to the threading.

I am pretty sure this is a common pattern in this Paramiko context.

So are you sure it didn't go into your exception handling code and get handled properly. In other words, that exception stack trace in the context of multiple threads potentially does not tell you whether or not your exception handler handled it or not.

**Comment by ajwillo** [comment]
I dont think it was handled, as I would of seen the below

`results = 'Error: {} - {} - {}'.format(hostname, ip, e)`

also I have a traceback on the failed task and the task failed. on others where the task timesout I get the correct errors in the tasks

here's the task failing in flower

<img width="1539" alt="Screenshot 2020-06-05 at 16 55 43" src="https://user-images.githubusercontent.com/24481217/83897544-9efe2e80-a74d-11ea-9116-3f63e0ca68da.png">

**Comment by ktbyers** [comment]
This is possibly relevant to your issue:

```
The exception is being handled, paramiko just logs the exception and you are seeing the logging output. You could disable logging with logging.getLogger('paramiko.transport').disabled = True
```

**Comment by ajwillo** [comment]
where would I apply this? do I need to import anything?

**Comment by ktbyers** [comment]
In your Python code probably where you import ConnectHandler:

```python
import logging
logging.getLogger('paramiko.transport').disabled = True
```
