### ISSUE TITLE
Trouble Running Debug/Packet Captures Commands with Netmiko

### ISSUE THREAD

**Issue by trevorjackson** [ktbyers/netmiko#1777]
I am running into an issue that I think is similar to the issue that was discussed here:

https://github.com/ktbyers/netmiko/issues/1538

I am trying to use netmiko to configure and run a packet capture on Palo Alto Firewalls. Here are the commands I am attempting to run:

                "debug dataplane packet-diag show setting",
                "debug dataplane packet-diag set filter on",
                "debug dataplane packet-diag set filter index 1 match destination-port 22",
                "debug dataplane packet-diag set filter index 2 match source-port 22",
                "debug dataplane packet-diag set capture stage transmit byte-count 10000000 file " + router + "-transmit.pcap",
                "debug dataplane packet-diag set capture stage drop byte-count 10000000 file " + firewall + "-drop.pcap",
                "debug dataplane packet-diag set capture stage receive byte-count 10000000 file " + firewall + "-receive.pcap",
                "debug dataplane packet-diag set capture stage firewall byte-count 10000000 file " + firewall + "-firewall.pcap",
                "debug dataplane packet-diag set capture on",
                "debug dataplane packet-diag show setting"

I suspect the issue is related to the fact that the commands after "debug dataplane packet-diag set filter on" do not echo anything to the command line at all - the first two commands run without issue, but at the third command (or later if I removed that command) the output hangs for a few seconds and then I get a series of errors:

fwall debug dataplane packet-diag show setting

--------------------------------------------------------------------------------
Packet diagnosis setting:
--------------------------------------------------------------------------------
Packet filter
  Enabled:                   yes
  Match pre-parsed packet:   no            
  Index 1: 0.0.0.0/0[0]->0.0.0.0/0[22], proto 0
           ingress-interface any, egress-interface any, exclude non-IP
--------------------------------------------------------------------------------
Logging
  Enabled:                   no
  Log-throttle:              no
  Sync-log-by-ticks:         yes            
  Features:
  Counters:
--------------------------------------------------------------------------------
Packet capture
  Enabled:                   yes
  Snaplen:                   0
  Username:                              
--------------------------------------------------------------------------------

fwall debug dataplane packet-diag set filter on

debug packet filter: on

fwall debug dataplane packet-diag set filter index 1 match destination-port 22

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\firewall_commands\venv\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\user\PycharmProjects\firewall_commands\venv\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\firewall_commands\venv\lib\site-packages\netmiko\base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\user\PycharmProjects\firewall_commands\venv\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/firewall_commands/venv/PA_Packet_Capture.py", line 99, in <module>
    print(connection.send_command(x) + "\n")
  File "C:\Users\user\PycharmProjects\firewall_commands\venv\lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 160, in send_command
    return super().send_command(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\firewall_commands\venv\lib\site-packages\netmiko\utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\firewall_commands\venv\lib\site-packages\netmiko\base_connection.py", line 1389, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "C:\Users\user\PycharmProjects\firewall_commands\venv\lib\site-packages\netmiko\base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\firewall_commands\venv\lib\site-packages\netmiko\base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Process finished with exit code 1

 

Here is the code I am using:

connection = netmiko.ConnectHandler(firewall, device_type="paloalto_panos", username=username, password=password)

show_command = ["debug dataplane packet-diag show setting",
                "debug dataplane packet-diag set filter on",
                "debug dataplane packet-diag set filter index 1 match destination-port 5100",
                "debug dataplane packet-diag set filter index 2 match source-port 5100",
                "debug dataplane packet-diag set capture stage transmit byte-count 10000000 file " + firewall + "-transmit.pcap",
                "debug dataplane packet-diag set capture stage drop byte-count 10000000 file " + firewall + "-drop.pcap",
                "debug dataplane packet-diag set capture stage receive byte-count 10000000 file " + firewall + "-receive.pcap",
                "debug dataplane packet-diag set capture stage firewall byte-count 10000000 file " + firewall + "-firewall.pcap",
                "debug dataplane packet-diag set capture on",
                "debug dataplane packet-diag show setting"]

for x in show_command:
   if x != None and x != "n":
        print(firewall + " " + x + "\n")
        print(connection.send_command(x) + "\n")
        print(connection.send_command("\n"))
        
I have attached a netmiko log of the issue occurring. Any help would be greatly appreciated.

[test.log](https://github.com/ktbyers/netmiko/files/4736950/test.log)

**Comment by ktbyers** [comment]
Yes, for what you are doing, you should definitely set:

`global_cmd_verify=False`

This is an argument to ConnectHandler. You will need Netmiko 3.1.1 for this.

There might be other issues, but I would start there.

**Comment by trevorjackson** [comment]
Thank you so much for the fast response and this tip. I will give it a try.

On Jun 6, 2020, at 12:11 PM, Kirk Byers <notifications@github.com> wrote:

﻿

Yes, for what you are doing, you should definitely set:

global_cmd_verify=False

This is an argument to ConnectHandler. You will need Netmiko 3.1.1 for this.

There might be other issues, but I would start there.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fktbyers%2Fnetmiko%2Fissues%2F1777%23issuecomment-640091198&data=02%7C01%7Ctjackson%40cricpa.com%7Ce647affb61a748227baf08d80a3cac80%7C286e6b2e41b84f62ae11cdc496907899%7C1%7C1%7C637270602997956043&sdata=j3XxZCwfIVx1jBgGZ%2B0fqU4scTUc%2BBX%2BgivOttdZkxQ%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADEHUZ4EJC2QU5YFDECTDRDRVJ2ETANCNFSM4NT75IEA&data=02%7C01%7Ctjackson%40cricpa.com%7Ce647affb61a748227baf08d80a3cac80%7C286e6b2e41b84f62ae11cdc496907899%7C1%7C1%7C637270602997956043&sdata=z6J9SBiUs%2FW2IJD8z5QIzj7es1g7s7HMriQ3Lx2Jvsc%3D&reserved=0>.


It Figures: The CRI Podcast is officially here! Subscribe<http://itfigurespodcast.com/> on your favorite platform to listen to these free, 10 to 20-minute episodes hosted by CRI partners who work at the forefront of the accounting industry.

[cid:image432878.PNG@05a35558.47afdfd9]<http://www.CRIcpa.com>

Trevor Jackson, CCNP Routing & Switching, Voice
Senior Network Architect
Carr, Riggs & Ingram, LLC
500 Grand Boulevard
Suite 210
Miramar Beach, FL 32550
Voice: 850-337-3214
Fax: 850-424-7118
Mobile: 850-543-4149
CRIcpa.com<http://CRIcpa.com>






**************************************************************************************************

The information contained in this message may be privileged and confidential and protected from disclosure. It is intended exclusively for the individual or entity to which it is addressed. This communication may contain information that is proprietary, privileged or confidential or otherwise legally exempt from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer. Thank you. Carr, Riggs & Ingram, LLC

**Comment by trevorjackson** [comment]
Thanks a lot. That suggestion did the trick perfectly.

**Comment by mura2006** [comment]
Im trying to run the below debug command on the PaloAlto Device , getting the error "Unknown command: debug"
try:
    print('~' * 79)
    print('Connecting to device:', device['ip'])
    connection = netmiko.ConnectHandler(**device)
    print(connection.send_command('set cli pager off'))
    print(connection.send_command('set cli scripting-mode on'))
    print ("done")

    for i in range(0, 10):
        print(connection.send_command('debug dataplane packet-diag show setting'))

**Comment by ktbyers** [comment]
In Netmiko this is typically done by passing in a secret argument to ConnectHandler and then calling the `enable` method.

**Comment by mura2006** [comment]
Thank you!  I elevated the permission level and it worked
    On Friday, February 18, 2022, 05:41:24 PM EST, Kirk Byers ***@***.***> wrote:  
 
 


@mura2006 This:
 "Unknown command: debug"

Looks to be from the device. Are you at the right privilege level to execute that command? Do you need to elevate privileges in some way?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
