### ISSUE TITLE
SSH Auto Detect "issue"

### ISSUE THREAD

**Issue by doug1as** [ktbyers/netmiko#1779]
I'am trying to do a auto discovery process with steps in this link: [https://ktbyers.github.io/netmiko/docs/netmiko/ssh_autodetect.html](url)

But i always receiving this return:

[user@hostname pwd]$ ./ssh_autodetect.py 
**None
{}**

I tried auto detect for Brocade NOS, Cisco IOS XR, HPE Comware, but doesn't work with none.
Logs Attached.
[ssh_autodetect.Brocade_NOS.log](https://github.com/ktbyers/netmiko/files/4746244/ssh_autodetect.Brocade_NOS.log)
[ssh_autodetect.HP_Comware.log](https://github.com/ktbyers/netmiko/files/4746245/ssh_autodetect.HP_Comware.log)
[ssh_autodetect.IOS_XR.log](https://github.com/ktbyers/netmiko/files/4746246/ssh_autodetect.IOS_XR.log)

This is my script:

#!/usr/bin/env python3

from netmiko.ssh_autodetect import SSHDetect
from netmiko.ssh_dispatcher import ConnectHandler
import logging

#Generating log file for analysis when needed
logging.basicConfig(filename='ssh_autodetect.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

remote_device = {'device_type': 'autodetect',
                 'host': 'HOSTNAME',
                 'username': 'MY_USER',
                 'password': 'MY_PASS',
                 'ssh_config_file': '~/.ssh/config-NAME'}

guesser = SSHDetect(**remote_device)
best_match = guesser.autodetect()
#Name of the best device_type to use further
print(best_match) 
#Dictionary of the whole matching result
print(guesser.potential_matches)

**Comment by ktbyers** [comment]
These two platforms do not look like they are supported for auto-detect--someone would need to add support for them:

Brocade_NOS
HP_Comware

On IOS-XR, maybe try to adjust this time.sleep to 8 seconds and see if that fixes the issue?

https://github.com/ktbyers/netmiko/blob/develop/netmiko/ssh_autodetect.py#L295
