### ISSUE TITLE
Issues adding a banner to IOS switches using ansible-napalm

### ISSUE THREAD

**Issue by richardjohnallsopp** [ktbyers/netmiko#1780]
Hey I've written a pretty extensive automation suite for managing all our ISO switching which works great on all the 3850 and 9300 switches. Recently I wanted to add a banner to the process in order to warn users the stacks are managed by our automation platform. I'm facing an issue completing this as the playbook is failing now with the following error:

```
TASK [Install IOS config] ********************************************************************************************************************************
fatal: [target_switch]: FAILED! => changed=false 
  msg: 'cannot load config: Timed-out reading channel, data not available.'
```
I have a line of j2 that inserts the text found in a txt file into the base template before rendering. I used vim to add the ascii control character:
```
banner login ^C
| ***************************************************************************
| * STOP!! THIS SWTICH STACK IS MANAGED VIA ANSIBLE NETWORK AUTOMATION!     *
| * DON'T MAKE ANY CONFIGURATION CHANGES DURING THIS SESSION, DIRECT ACCESS *
| * TO THE STACK IS FOR TROUBLESHOOTING & INFOMATION GATHERING ONLY.        *
| *                                                                         *
| * For config changes please use the git repo found here                   *
| *                                                                         *
| *                                                                         *
| * All access to this device is logged.                                    *
| ***************************************************************************
^C
```
I know it has to be this as otherwise it works great.

Rich

**Comment by ktbyers** [comment]
Are you doing a NAPALM merge operation or a replace operation?

Banners are really hard to get right. Have you made sure your cntl-C character is the correct ASCII code (see NAPALM IOS docs on banners). Note, this is not just a "^" and a "C", it is its own special ASCII code.

Have you tried to execute the Cisco IOS command that NAPALM does for the merge manually from the CLI (note, I am assuming a merge operation here) and see which error is generated?

**Comment by richardjohnallsopp** [comment]
Hey thanks for getting back to me, I’m doing a config replace, the playbook renders the new config file each time you run it and applies that to the switch. I did see the documentation on ASCII character and used vi to add it by typing ctrl+v then c. If I cat the file in Ubuntu it does show correctly, and in WSL and VS code for windows it shows as ETX if I enable render special characters. 

I’m assuming that it’s not the character that’s the issue as I was getting an error saying it couldn’t apply the first line of the banner text. I then fixed that on a Linux system and tried again, but now I see the error above.

**Comment by ktbyers** [comment]
Okay, I would see what you get when you manually execute the CLI command:

```
configure replace flash:/candidate_config.txt force revert trigger error
```

Note, it might be flash: or bootflash: or possibly something else so you will need to verify this.

Also verify the candidate_config.txt file on the network device is correct before you try to load it (i.e. sanity check that it is the file you want to load by inspecting the file).

I am assuming this is a test/QA device that you are working on...

**Comment by richardjohnallsopp** [comment]
It is a test box, but it’s remote so I think I need to pick it up before doing this as it might break the switch. I will check that the candidate file is rendered correctly on the switch though.

**Comment by richardjohnallsopp** [comment]
Mmmm I pulled the candidate config from the box and the character is showing incorrectly:
```
!
banner login ALT+94C
| ***************************************************************************
| * STOP!! THIS SWTICH STACK IS MANAGED VIA ANSIBLE NETWORK AUTOMATION!     *
| * DON'T MAKE ANY CONFIGURATION CHANGES DURING THIS SESSION, DIRECT ACCESS *
| * TO THE STACK IS FOR TROUBLESHOOTING & INFOMATION GATHERING ONLY.        *
| *                                                                         *
| * For config changes please use the git repo found here                   *
| * https://github.ol.epicgames.net/IT/ansible-cisco-ios                    *
| *                                                                         *
| * All access to this device is logged.                                    *
| ***************************************************************************
ALT+94C 
!
```
This is Windows code for the character.

**Comment by richardjohnallsopp** [comment]
I'm wondering if this is a result of the way WSL and VS Code handle these characters?

**Comment by richardjohnallsopp** [comment]
Is there anyone that uses WSL and VS Code that have found a way around this?

**Comment by ktbyers** [comment]
@richardjohnallsopp Did you ever work this out?

**Comment by richardjohnallsopp** [comment]
> @richardjohnallsopp Did you ever work this out?

Hey, I figured out why it wasn't working which is due to the way WSL and VS code render the characters which is represented in the config file I build. To me this is something that Ansible-Napalm could handle for us as it's not the same experience across all the drivers. I don't want to not use WSL and VS code, but for now I'm not sure how to escalate this further. Whats frustrating is that it's handled in the Ansible module - https://docs.ansible.com/ansible/latest/modules/ios_banner_module.html, but this doesn't work for my workflow.

**Comment by richardjohnallsopp** [comment]
I would love to solve this too as I have a lot of switches to convert and while we're in a hybrid state of old crapness and new hotness I'd like to add a banner warning for which devices are under automation and which aren't.

**Comment by richardjohnallsopp** [comment]
@ktbyers Hey man, I had some help from @rbcollins123 on this and made some progress. We wrote a python filter to generate the correct character, however with the etx character set the install_config process fails to load the config file: Here is the traceback:

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_napalm_install_config_payload_CuihZe/__main__.py", line 283, in main
    device.load_replace_candidate(filename=config_file)
  File "/home/flynn/.local/lib/python2.7/site-packages/napalm/ios/ios.py", line 303, in load_replace_candidate
    file_system=self.dest_file_system,
  File "/home/flynn/.local/lib/python2.7/site-packages/napalm/ios/ios.py", line 279, in _load_candidate_wrapper
    file_system=file_system,
  File "/home/flynn/.local/lib/python2.7/site-packages/napalm/ios/ios.py", line 601, in _inline_tcl_xfer
    TransferClass=InLineTransfer,
  File "/home/flynn/.local/lib/python2.7/site-packages/napalm/ios/ios.py", line 692, in _xfer_file
    transfer.transfer_file()
  File "/home/flynn/.local/lib/python2.7/site-packages/netmiko/scp_handler.py", line 304, in transfer_file
    self.put_file()
  File "/home/flynn/.local/lib/python2.7/site-packages/netmiko/cisco/cisco_ios.py", line 216, in put_file
    pattern=r"\(tcl\)", max_loops=max_loops
  File "/home/flynn/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 543, in _read_channel_expect
    "Timed-out reading channel, data not available."
```
If we replace the 'etx' character in our filter with an '@' symbol then the file is loaded fine but the install_config fails at the banner section.

Rich

**Comment by richardjohnallsopp** [comment]
@ktbyers can you give us some assistance with this? It would make life so much easier while we’re in the hybrid environment to identify which stacks are managed with the automation and which aren’t :-)

**Comment by richardjohnallsopp** [comment]
@ktbyers Any update on this? wondering if it's possibly fixed in later versions of Ansible Napalm or Paramiko?

**Comment by ktbyers** [comment]
@richardjohnallsopp Your failure above is with `inline_transfer` i.e. it is not even getting to the loading the configuration and is failing on the file transfer. Have you tried to use the Secure Copy Transfer? Does that file transfer mechanism work?


Kirk

**Comment by richardjohnallsopp** [comment]
@ktbyers Thanks man, setting `inline_transfer: false` fixed this and banners are now applied :-) Thanks again!
