### ISSUE TITLE
Cannot import bcrypt

### ISSUE THREAD

**Issue by Jigs01** [ktbyers/netmiko#1783]
ImportError: cannot import name '_bcrypt' from 'bcrypt' (C:\Users\username\AppData\Roaming\Python\Python37\site-packages\bcrypt\__init__.py)

i am getting this error wile importing netmiko

is there any solution?

**Comment by ktbyers** [comment]
I would try to uninstall and reinstall bcrypt using pip.

**Comment by maximoyanez** [comment]
hola, una pregunta, encontraste la solucion?

**Comment by ktbyers** [comment]
@maximoyanez You probably should create a new issue and specify the problem you are running into and the error message you are seeing.
