### ISSUE TITLE
is_alive() not always accurate

### ISSUE THREAD

**Issue by rbarrette** [ktbyers/netmiko#1784]
Hello all,

In using netmiko with a project I am currently working on. I came across what appears to be an edge case when using the is_alive() method to check status of the current (ssh) session. If connectivity is lost with the end device or it goes unresponsive, is_alive() is not always reliable in detecting the change in state.

Description-

This is pretty easy to simulate using a GNS3 lab. I have only validated this with XR device types, but I would assume this would effect all device types that use the BaseConnection module since that is where the is_alive() method is located. It looks like is_alive() attempts to validate the connection (for SSH sessions) by sending a null byte. I have not had much time to dig much deeper into the source yet to see what calls are being made beyond write_channel. Below is a scenario the replicates the issue and works around it by using find_prompt()

Scenario -

1. Establish connection with device using Netmiko
2. Validate connection with the device using is_alive method - Returns true.
3. Stop or pause the device in GNS3 (simulating an unexpected reboot or hang)
4. Call the is_alive method again(several times), notice it still returns True. 
5. Call the find_prompt() method, this will result in the following traceback below with a OSError exception being raised. OSError: Socket is closed
6. Call is_alive() again, this time it returns the correct response of False.

```
test2 is a netmiko device object

>>> test2.netmiko.is_alive()
True
>>> test2.netmiko.find_prompt()
'RP/0/0/CPU0:ios#'
>>> test2.netmiko.is_alive()
True

NOTE --- I killed the device in GNS3 here ---

>>> test2.netmiko.is_alive()
True
>>> test2.netmiko.is_alive()
True
>>> test2.netmiko.is_alive()
True
>>> test2.netmiko.is_alive()
True
>>> test2.netmiko.find_prompt()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rbarrette/py_venvs/gns3/lib/python3.8/site-packages/netmiko/base_connection.py", line 1107, in find_prompt
    self.write_channel(self.RETURN)
  File "/home/rbarrette/py_venvs/gns3/lib/python3.8/site-packages/netmiko/base_connection.py", line 436, in write_channel
    self._write_channel(out_data)
  File "/home/rbarrette/py_venvs/gns3/lib/python3.8/site-packages/netmiko/base_connection.py", line 394, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "/home/rbarrette/py_venvs/gns3/lib/python3.8/site-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
  File "/home/rbarrette/py_venvs/gns3/lib/python3.8/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/home/rbarrette/py_venvs/gns3/lib/python3.8/site-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed
>>> test2.netmiko.is_alive()
False
```

**Comment by rbarrette** [comment]
Kirk,

Thanks for the quick response. That is pretty much what I have been doing! It is a little awkward to just swallow that OSError tho. I posted a small stripped down block of code below just in case anyone else needs to do something similar in the future. Would you be open to a PR that would potentially change the behavior of is_alive()? I might play around and see if I can improve it if somewhat. I wonder if sending multiple null bytes would make a difference. The other option I was thinking of would be sending a return down the channel. I know that 2nd option is a slightly bigger change and could effect things depending on how others use the method. Let me know your thoughts!

```
try:
    _ = self.netmiko.find_prompt()
except OSError:
    pass
if self.netmiko.is_alive() is False:
    try:
        self._reconnect_netmiko() # This is custom method - some logging, then calls establish_Connection() with retries
    except NetmikoTimeoutException:
        raise SomeCustomAppExecption() 
```

-Robert

**Comment by ktbyers** [comment]
I don't think sending a return down the channel would work as Netmiko doesn't know whether the current-SSH session is in the middle of something else (where sending an enter would be problematic).

It might work in your particular code, however (as you have control over what is going on).

In other words, I don't think it will work as a fix in the Netmiko-library itself, but it potentially could work in your specific code.

**Comment by ktbyers** [comment]
Purging old issues...
