### ISSUE TITLE
TELNETDetect like SSHDetect

### ISSUE THREAD

**Issue by thoms27** [ktbyers/netmiko#1785]
Hello,

Firstly, thank you for your job. I use every day Netmiko to save my devices (Cisco, Huawei etc).
I use SSHDetect to detect OS, but fews of them have only Telnet :-( 
Do you know if something like TELNETDetect or better TELNET-SSHDetect is planned ?

Thank you in advance.

Best Regards,

Thomas V.

**Comment by ktbyers** [comment]
No, I don't think I would be interested in that (in Netmiko). Obviously someone could modify the existing code and covert it over, but it is not really something I would be interested in doing.

**Comment by Kani999** [comment]
@thoms27 - Did you edit the code? 
Currently, I'm considering it, because I have to check a lot of devices and detect their OS. 
And detecting the incompatible devices with sshv2 would help me a lot.
