### ISSUE TITLE
prompt is not stripped in config mode with very long hostnames

### ISSUE THREAD

**Issue by 991jo** [ktbyers/netmiko#1786]
I have an issue where the output sanitization does not work with very long hostnames on Cisco routers. When the hostname is > 20 characters long the prompt is not removed from the output of commands.

I am running Python 3.8.3 and Netmiko 3.1.1, but the bug also affects netmiko 3.0.0.
I am testing against a Cisco C1111 (IOS-XE 16.12.3) and an ASR920-24SZ-IM (16.9.5f).

Example code here:

```
from netmiko import Netmiko

connection = Netmiko(host="A.B.C.D",
                     username="admin",
                     device_type="cisco_ios",
                     password="somepassword",
                     secret="somesecret")

output1 = connection.send_command("show run | incl asdfgasdfg")

connection.config_mode()
output2 = connection.send_command("do show run | incl asdfgasdfg")
connection.exit_config_mode()

print(f"'{output1}'")
print(f"'{output2}'")
```

When the router has a short hostname like `short` or any other hostname with <= 20 characters the output is:
```
''
''
```

When I change the hostname to `veryveryverylonghostname` or an other hostname with >20 characters the output is:
```
''
'veryveryverylonghost(config)#'
```
20 characters is the boundary above which cisco cuts of the hostname in config mode but displays it normal in exec mode.

**Comment by ktbyers** [comment]
Why are you executing `show commands` from config_mode using Netmiko's send_command()?

In general, should be `send_config_set` for config commands.

You probably would have to re-execute the `set_base_prompt()` method after going into config mode. I would try that and see what happens.

**Comment by 991jo** [comment]
The `show` commands are only an example, because it was the first thing I came up with to reproduce this in a clean way. I am usually using the send_config_set method for config changes unless I need more control e.g. when a command needs additional input.

An other reason I am sometimes using send_command is because it returns only the output of that command (unless the hostname is to long). Running the same command via `set_config_set` returns a lot more:

```
'config term
Enter configuration commands, one per line.  End with CNTL/Z.
short(config)#do show run | incl asdfgasdfg
short(config)#end
short#'
```
This is not nice if you want to work with the output of a command. Or to put it in an other way: The sanitization that is not working in the given case with send_command is not done at all with `send_config_set`.

Back to topic: using `set_base_prompt` fixes the issue but I have to execute it again once I leave the config mode.

```
output1 = connection.send_command("show run | incl asdfgasdfg")

connection.config_mode()
connection.set_base_prompt()
output2 = connection.send_command("do show run | incl asdfgasdfg")
connection.exit_config_mode()
output3 = connection.send_command("show run | incl asdfgasdfg")

print(f"'{output1}'")
print(f"'{output2}'")
print(f"'{output3}'")
```
prints
```
''
''
'veryveryverylonghostname#'
```

Executing `set_base_prompt` every time I enter or leave config mode is very tedious.

**Comment by ktbyers** [comment]
```
An other reason I am sometimes using send_command is because it returns only the output of that command (unless the hostname is to long). Running the same command via set_config_set returns a lot more:
```

Yes, this is by-design/intentional i.e. that is in-general what I want from the output of send_config_set.

```
This is not nice if you want to work with the output of a command. Or to put it in an other way: The sanitization that is not working in the given case with send_command is not done at all with send_config_set.
```

Yes, netmiko does not try to sanitize `send_config_set()` output as it would be very hard in general given the frequently changing prompts across a broad set of platforms (and most people don't want/need this...at least that is my sense of it).

```
Executing set_base_prompt every time I enter or leave config mode is very tedious.
```

Yes, just create functions that do the send_config_set()

All of this is expected i.e. Netmiko is operating normally/as per design. You have just gotten into a case where you are doing something fairly atypical for config (i.e. you want sanitized send_config_set output where you only have the command-echo and not the prompts).

**Comment by 991jo** [comment]
I dont care if `send_config_set` sanitizes the output or not. This is just an argument why I could not use it in my case.
There are commands in config mode from which I want to use the output.

Back to my initial problem: The sanitization for send_command does not work once the hostname gets to long. Calling `set_base_prompt()` fixes that but is has to be done again after leaving the config mode.
When I am calling `send_command` I expect it to remove the prompt. Since it is working with short hostnames I also expect it to work in the corner case of a longer hostname.

**Comment by ktbyers** [comment]
@991jo Can you show me a failure example of send_command that does not involve using send_command in config mode?

**Comment by 991jo** [comment]
no, because it only fails in config mode.

**Comment by ktbyers** [comment]
Okay, Netmiko is behaving properly then i.e. you would need to make the calls to `set_base_prompt()` to get send_command to strip the output in the way you want in config mode.

**Comment by 991jo** [comment]
Okay, let me put it this way: The send_command method does not do what the documentation says it should do.

From the docs:
> Execute command_string on the SSH channel using a pattern-based mechanism. Generally used for show commands. By default this method will keep waiting to receive data until the network device prompt is detected. The current network device prompt will be determined automatically.

1. the docs say that is generally used for show commands which leaves room to use it for other things.
The docs to not say that I can not nor should not use it in config mode.

2. the docs say that the network device prompt will be detected automatically. To me that sounds a lot like I should not have to call `set_base_prompt`.

The docs also contain this part:
> :param strip_prompt: Remove the trailing router prompt from the output (default: True). :type strip_prompt: bool

This does not happen in all cases as demonstrated.

Is this a bug in the code or an error in the documentation?

**Comment by ktbyers** [comment]
Fair enough...PRs are welcome on the docs.

There could be an edge case here so PRs are welcome on the code as well.

**Comment by ktbyers** [comment]
Okay, I looked at it some more as there was a certain aspect that made me a bit more concerned it might be a bug:

```
$ python netmiko_test.py 
interface GigabitEthernet0/0/0
interface GigabitEthernet0/0/1
interface GigabitEthernet0/1/0
interface GigabitEthernet0/1/1
interface GigabitEthernet0/1/2
interface GigabitEthernet0/1/3
cisco3cisco3cisco3ci(config)#
```

With a very long hostname...that is the output from the command. So as your issue referenced it does not strip the trailing prompt here.

The behavior of `strip_prompt()` is to use `self.base_prompt` which is what is set by the `set_base_prompt` call. This is set on a more static basis. So if your prompt changes (as it does when going into config mode), then this potentially needs to be `reset` by making additional calls to `set_base_prompt`.

So the net effect of all this is...is at worse it is a documentation issue:

This section here:

```
the docs say that the network device prompt will be detected automatically. To me that sounds a lot like I should not have to call set_base_prompt.
```

Is referring to a different context and not to the strip_prompt behavior (i.e. it is referring to the actual command termination i.e. when send_command is done). You can logically ask why that can't be used and fed-into strip prompt, but that would be a big change and likely break a lot of things (definitely some assumptions I am making here...but regardless I wouldn't make that change for this very-edge case).

So...it is a documentation issue.

**Comment by MikeJurecki** [comment]
@ktbyers I have a similar issue except mine is due to how long F5 prompts are.  I have tried `set_base_prompt()` and it just errors out every time.  Any suggestions?

**Sample Prompt:**  username@(f5-device-hostname)(cfg-sync Standalone)(Active)(/Common)(tmos)# 

**Exception:** 
Router prompt not found: 'username@(f5-device-hostname)(cfg-sync Standalone)(Active)(/Common)(t'

**Comment by ktbyers** [comment]
@MikeJurecki Can you post the full exception stack trace (that will help me see where in the code the issue is happening)?
