### ISSUE TITLE
bcrypt is not installed or working properly

### ISSUE THREAD

**Issue by rawatkuldeep23** [ktbyers/netmiko#1789]
i ran the script:

from netmiko import Netmiko

connection = Netmiko(host='10.223.128.23', port ='23', username = 'admin, password = 'Password@123', device_type = 'cisco_ios')

and getting below output:

C:\Users\200845\PycharmProjects\My_Project\venv\Scripts\python.exe C:/Users/200845/PycharmProjects/My_Project/sonu.py
Traceback (most recent call last):
  File "C:/Users/200845/PycharmProjects/My_Project/sonu.py", line 1, in <module>
    from netmiko import Netmiko
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\a10\__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\a10\a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\cisco_base_connection.py", line 2, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\netmiko\base_connection.py", line 18, in <module>
    import paramiko
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\paramiko\transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\paramiko\dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\paramiko\pkey.py", line 31, in <module>
    import bcrypt
  File "C:\Users\200845\PycharmProjects\My_Project\venv\lib\site-packages\bcrypt\__init__.py", line 25, in <module>
    from . import _bcrypt
ImportError: cannot import name '_bcrypt'

Process finished with exit code 1

Can @ktbyers please help me to understand the errors and help in fixing these errors.

Thanks..!!

**Comment by ktbyers** [comment]
I would probably:

```
pip uninstall bcrypt
pip install bcrypt
```

And make sure that works properly.

**Comment by rawatkuldeep23** [comment]
Thanks @ktbyers 

here is the output;

C:\Users\200845\PycharmProjects\My_Project\venv\Lib>pip uninstall bcrypt
Uninstalling bcrypt-3.1.7:
  c:\users\200845\appdata\local\programs\python\python36\lib\site-packages\bcrypt-3.1.7-py3.6-win-amd64.egg
Proceed (y/n)?
Your response ('') was not one of the expected responses: y, n
Proceed (y/n)? y
  Successfully uninstalled bcrypt-3.1.7

C:\Users\200845\PycharmProjects\My_Project\venv\Lib>pip install bcrypt
Collecting bcrypt
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/bcrypt/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/bcrypt/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/bcrypt/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/bcrypt/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/bcrypt/
  Could not fetch URL https://pypi.python.org/simple/bcrypt/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/bcrypt/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)) - skipping
  Could not find a version that satisfies the requirement bcrypt (from versions: )
No matching distribution found for bcrypt

C:\Users\200845\PycharmProjects\My_Project\venv\Lib>python --version
Python 3.6.5

C:\Users\200845\PycharmProjects\My_Project\venv\Lib>pip --version
pip 9.0.3 from c:\users\200845\appdata\local\programs\python\python36\lib\site-packages (python 3.6)


Kindly suggest further

**Comment by ktbyers** [comment]
You need to upgrade your pip version to the newest pip version:

```
pip install pip==20.1.1
pip install bcrypt
```

Note, none of these issues are really Netmiko issues.

**Comment by rawatkuldeep23** [comment]
@ktbyers Not sure, why i am getting this error;

C:\Users\200845>pip install pip==20.1.1
Collecting pip==20.1.1
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)) - skipping
  Could not find a version that satisfies the requirement pip==20.1.1 (from versions: )
No matching distribution found for pip==20.1.1

C:\Users\200845>pip install pip==20.1.1 --trusted-host pypi.org --trusted-host files.pythonhosted.org
Collecting pip==20.1.1
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /simple/pip/
  Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)) - skipping
  Could not find a version that satisfies the requirement pip==20.1.1 (from versions: )
No matching distribution found for pip==20.1.1

i really appreciate your help.
Can we change the URL to download/import it?
Kindly suggest further.. Many thanks..!!

**Comment by ktbyers** [comment]
This should be pretty well documented online. It is not a Netmiko issue, but a general Python/PIP issue that you need to work through on your system.
