### ISSUE TITLE
TypeError: usap_ftp_software_upload() argument after ** must be a mapping, not function

### ISSUE THREAD

**Issue by ghost** [ktbyers/netmiko#1803]
This code is broken into functions. So i will paste the function then paste the main program and error at the end respectively..Please help me. I have done a lot of research but i cant still fix the issue. 
The error is below:
C:\network_automation_2\venv\Scripts\python.exe C:/network_automation_2/usap_asa_firewall_upgrade.py
>>>> 2020-06-21 12:13:19.295572
Traceback (most recent call last):
  File "C:/network_automation_2/usap_asa_firewall_upgrade.py", line 12, in <module>
    usap_ftp_software_upload(**asa_firewall)
TypeError: usap_ftp_software_upload() argument after ** must be a mapping, not function
#########################################################################

def asa_devices_to_upgrade():
    with open('asadevices.txt', 'r') as f:
        file_content = f.read().splitlines()

    devices = list()

    for item in file_content:
        tmp = item.split(',')
        devices.append(tmp)

    for asa in devices:
        asa_firewall = {'device_type': 'cisco_asa',
                  'ip': asa[3],
                  'port': '22',
                  'username': asa[0],
                  'password': asa[1],
                  'secret': asa[2],
                  'verbose': 'True'
                  }
        return asa_firewall
######################################################################

from netmiko import ConnectHandler
from getpass import getpass
import time
from datetime import datetime
start_time = datetime.now()
start = time.time()
#host = input('Enter ip address: ')
ftp_user = 'reuben'
ftp_pass = 'cisco'
ftp_ip = '192.168.120.23'
target_software = 'asa984-22-lfbff-k8.SPA'
def usap_ftp_software_upload(**device):
    global ftp_user
    global ftp_pass
    global ftp_ip
    global target_software
    net_connect = ConnectHandler(**device)
    cmd = f'copy ftp://{ftp_user}:{ftp_pass}@{ftp_ip}/{target_software}  ' f'disk0:/{target_software}'
    output = net_connect.send_command(cmd, expect_string=r'Address or name of remote host')
    output += net_connect.send_command('\n', expect_string=r'Source username')
    output += net_connect.send_command('\n', expect_string=r'Source password')
    output += net_connect.send_command('\n', expect_string=r'Source filename')
    output += net_connect.send_command('\n', expect_string=r'Destination filename')
    output += net_connect.send_command('\n', expect_string=r'#', delay_factor=2)
    print(output)
    net_connect.disconnect()
    end_time = datetime.now()
    end = time.time()
    print(f'Total execution time is {end - start} seconds')
#########################################################################
from netmiko import ConnectHandler
from netmiko import file_transfer
from datetime import datetime
import threading
import sys

import time
start_time = datetime.now()
print(">>>> {}".format(start_time))
start = time.time()

old_file = 'asa984-15-lfbff-k8.SPA'
old_dest_file = 'asa984-15-lfbff-k8.SPA'
source_file = 'asa984-22-lfbff-k8.SPA'
dest_file = 'asa984-22-lfbff-k8.SPA'
device = dict()
file_system = 'disk0:'
direction = 'put'

def connect_and_change(**device):
    #print('\n* Step1: Upload Software to ASA ')

    global source_file
    global dest_file
    global direction
    global file_system
    global old_file
    global old_dest_file
    connection = ConnectHandler(**device)
    connection.enable()
    print('\n*STEP 2 - Remove Old Software Version from boot variable.\n')
    output_ = connection.send_command('show run boot')
    if source_file not in output_:
        print('removing old boot file.............')
        confs = ['no ' + output_, "write mem"]
        output_2 = connection.send_config_set(confs)
        print(output_2)
        print('\nsuccessfully removed old software version from boot variable...')
    else:
        print('asa software already on latest version\n')
        print('exiting now.........')
        sys.exit()

    print('\nSTEP 3 - Set boot variable')
    set_boot_system = 'boot system {}/{}'.format(file_system, dest_file)
    set_boot_system_2 = 'boot system {}/{}'.format(file_system, old_dest_file)
    output = connection.send_config_set([set_boot_system])
    output_2 = connection.send_config_set([set_boot_system_2])
    print(output)
    print(output_2)

    print('\n* Step 4 - Verify Boot System.\n')
    boot_system = connection.send_command("show boot")
    print(boot_system)

    print('\nSTEP 5 - Save Configuration and Reload Cisco ASA\n')
    commands = ['write mem', 'reload', 'y']
    output = connection.send_config_set(commands)

    print(output, '\n')

    end = time.time()
    print("\n>>>> {}".format(datetime.now() - start_time))
    print(f'Total execution time: {end - start} seconds')

    print('#' * 30)

    connection.disconnect()
##########################################################################

import threading
#creating threads
def create_threads(dict1, function):

    threads = []

    for device in dict1:
        th = threading.Thread(target=function, args=(device,)) # args is a tuple with a single element
        th.start()
        threads.append(th)

    for th in threads:
        th.join()
#########################################################################
Main program calling other functions

import sys

from usap_asa_devices_to_upgrade import asa_devices_to_upgrade
from usap_ftp_software_upload import usap_ftp_software_upload
from usap_connect_and_change import connect_and_change
from create_threads import create_threads

asa_firewall = asa_devices_to_upgrade

try:
    usap_ftp_software_upload(**asa_firewall)

except KeyboardInterrupt:
    print('\n\n* Program aborted by user. Exiting....\n')
    sys.exit()
create_threads(asa_firewall, connect_and_change)
##########################################################################

Error:

C:\network_automation_2\venv\Scripts\python.exe C:/network_automation_2/usap_asa_firewall_upgrade.py
>>>> 2020-06-21 12:13:19.295572
Traceback (most recent call last):
  File "C:/network_automation_2/usap_asa_firewall_upgrade.py", line 12, in <module>
    usap_ftp_software_upload(**asa_firewall)
TypeError: usap_ftp_software_upload() argument after ** must be a mapping, not function

**Comment by reuben3010** [comment]
Kirk,
I figured the issue out.

But i have another question.
if the program has the following lines below
output += net_connect.send_command('\n', expect_string=r'%Warning. There is a file already exisiting with this name')
output += net_connect.send_command('n', expect_string=r'#', delay_factor=2)

My question is, if the program does not see '%Warning. There is a file already exisiting with this name' , does it skip that line or it gets stuck?

The reason for my question is that incase the software image is already on the firewall i want the program not to fail but continue execution. 
Do i include the '%Warning. There is a file already exisiting with this name'  and when the program does not encounter it, it skips it,or is there a way to accomplish this?

**Comment by ktbyers** [comment]
```
output += net_connect.send_command('\n', expect_string=r'%Warning. There is a file already exisiting with this name')
```

It will get stuck...if the given output may or may not exist, then you should add a conditional statement:

```python
if "Warning" in output:
    output += net_connect.send_command('\n', expect_string=r'Warning')
```

**Comment by reuben3010** [comment]
Okay. Thanks for the reply, Kirk. I will try it and let you know if it worked..

**Comment by reuben3010** [comment]
Kirk,
That did not work. :(

**Comment by ktbyers** [comment]
Doesn't look like a Netmiko issue.
