### ISSUE TITLE
unwarrented ANSI strip on NXOS

### ISSUE THREAD

**Issue by ciscorat** [ktbyers/netmiko#1804]
Hi,

Seems like ANSI strip kicks in when is unwarranted:
I'm using the following:

YDEKEL-M-D6YG:~ ydekel$ python3 -V
Python 3.8.1
YDEKEL-M-D6YG:~ ydekel$ python3
Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__version__
'3.0.0'
>>>

When sending this specific command, the ANSI strip kicks in for a backspace but I don't understand why.
It seems unwarranted, is there away to turn it off? i could not find any

DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3.1.lib32_n9000\n'
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3. \x081.lib32_n9000\r\r\n'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3.1.lib32_n9000

DEBUG:netmiko:repr = 'show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3. \x081.lib32_n9000\r\r\n'
DEBUG:netmiko:read_channel: show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3.1.lib32_n9000

DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''

So eventually the command that is sent is:
show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3. 1.lib32_n9000
That space fails the command

Thanks in advanced

**Comment by ktbyers** [comment]
Netmiko sends exactly what you put in. The stripping/normalization is only on the echo of the command from the device.

So here (if I am reading it right), the issue is that NX-OS adds both a `backspace and a space` and Netmiko is only stripping off the backspace.

Probably the easy fix is to disable `cmd_verify=False` on the `send_command` call (I am assuming you are using send_command() here).

**Comment by ciscorat** [comment]
Hey Kirk,

Well, I'm already using it:

output = net.send_command(f'show install pkg {smu}', cmd_verify=False, strip_command=False)

I'm getting the same results with and w/out cmd_verify=False
Actually, w/out, the command fails 
:netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
That's the reason I disabled cmd verify.
Any idea?

**Comment by ktbyers** [comment]
Can you post the actual exception you receive when cmd_verify=False?

**Comment by ciscorat** [comment]
the exception only occurs w/out cmd_verify=False

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python/eNSE/NXK-SMU_Installation_MOP_Gen.py", line 211, in <module>
    output = net.send_command(f'show install pkg {smu}')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 1379, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/base_connection.py", line 551, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
Okay, so it works if `cmd_verify=False`?


Kirk

**Comment by ciscorat** [comment]
with cmd_verify=False i have the ANSI strip kicks in and insert a space:

DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3.1.lib32_n9000\n'
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3. \x081.lib32_n9000\r\r\n'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3.1.lib32_n9000

DEBUG:netmiko:repr = 'show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3. \x081.lib32_n9000\r\r\n'
DEBUG:netmiko:read_channel: show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3.1.lib32_n9000

DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''

**Comment by ciscorat** [comment]
Or maybe its the NXOS and I misspoken

**Comment by ciscorat** [comment]
i think its in the driver. I changed the device type to cisco_xr from cisco_nxos and i have even more escapes:

DEBUG:netmiko:[find_prompt()]: prompt is AP07-PT-9508-01(maint-mode)#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3.1.lib32_n9000\n'
DEBUG:netmiko:Pattern is: show\ install\ pkg\ nxos\.CSCvi07117\-n9k_ALL\-1\.0\.0\-9\.3\.1\.lib32_n9000
DEBUG:netmiko:_read_channel_expect read_data: show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3.1.lib32_n90
DEBUG:netmiko:_read_channel_expect read_data: 00

DEBUG:netmiko:Pattern found: show\ install\ pkg\ nxos\.CSCvi07117\-n9k_ALL\-1\.0\.0\-9\.3\.1\.lib32_n9000 show install pkg nxos.CSCvi07117-n9k_ALL-1.0.0-9.3.1.lib32_n9000

DEBUG:netmiko:read_channel:

Now i removed the device type to let it fall back to default but instead, it seems like the device type is required:
Traceback (most recent call last):
  File "Python/eNSE/NXK-SMU_Installation_MOP_Gen.py", line 201, in <module>
    net = ConnectHandler(**nm)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
    if kwargs["device_type"] not in platforms:
KeyError: 'device_type'

**Comment by ktbyers** [comment]
Okay, with cmd_verify=False there is no exception and you just don't like that the output has an extra-space in it?

I am just trying to make sure I understand the issue.

Note, it is very, very unlikely Netmiko is adding the space--it is very likely the NX-OS device that is adding a backspace and a space (and Netmiko strips the backspace, but can't strip the space).

**Comment by ciscorat** [comment]
ok, it makes sense. thanks for the prompt response

**Comment by ktbyers** [comment]
No worries...just let me know if I am interpreting something incorrectly here, however...
