### ISSUE TITLE
netmiko timeout / #445 didn't solve me

### ISSUE THREAD

**Issue by wright-james** [ktbyers/netmiko#1805]
Hi all!  I reinstalled cryptology as above suggested.  Same problem sadly.  The first device I ran into this issue was resolved by forcing aes256-cbt.  I feel like maybe this was an anomoly though because the second is being stubborn.  1st was cisco 3650, second was 9300, which is weird.  It's new and I can connect to it just fine from my box with SSH?

Also, other scripts work.  It seems like I get an issue if I do "show (whatever)" and the output is blank.  I can workaround but would like to know if anyone can help.

Any Help Appreciated,

Jim

code:

from netmiko import ConnectHandler
from sys import argv
import getpass
import time

script, first, second=argv

p = getpass.getpass(prompt="Enter Password: ")

for n in range (int(first) , int(second)):
        ip="10.0{0}.255.2".format(n)

#connect to device
        device = ConnectHandler(device_type='cisco_ios', ip=ip, username='(username)', password=p)
        print(ip)

        output = device.send_command('sh access-list | i Tele')
        print(output)

        device.disconnect()

**Comment by ktbyers** [comment]
Can you post the exception stack-trace and the details on the failure?

**Comment by wright-james** [comment]
Thanks, sure thing, and here you are:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 892, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 204, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ShowMLS01.py", line 16, in <module>
    device = ConnectHandler(device_type='cisco_ios', ip=ip, username='jim.wright', password=p)
  File "/usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 252, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 318, in __init__
    self._open()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 323, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 898, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: Connection to device timed-out: cisco_ios 10.09.255.2:22


> Hi all! I reinstalled cryptology as above suggested. Same problem sadly. The first device I ran into this issue was resolved by forcing aes256-cbt. I feel like maybe this was an anomoly though because the second is being stubborn. 1st was cisco 3650, second was 9300, which is weird. It's new and I can connect to it just fine from my box with SSH?
> 
> Also, other scripts work. It seems like I get an issue if I do "show (whatever)" and the output is blank. I can workaround but would like to know if anyone can help.
> 
> Any Help Appreciated,
> 
> Jim
> 
> code:
> 
> from netmiko import ConnectHandler
> from sys import argv
> import getpass
> import time
> 
> script, first, second=argv
> 
> p = getpass.getpass(prompt="Enter Password: ")
> 
> for n in range (int(first) , int(second)):
> ip="10.0{0}.255.2".format(n)
> 
> #connect to device
> device = ConnectHandler(device_type='cisco_ios', ip=ip, username='(username)', password=p)
> print(ip)
> 
> ```
>     output = device.send_command('sh access-list | i Tele')
>     print(output)
> 
> 
>     device.disconnect()
> ```

**Comment by ktbyers** [comment]
Adding the extra zero here:

`10.09.255.2:22` is causing socket.getaddrinfo to fail. Just convert it to `10.9.255.2` for the IP.

**Comment by wright-james** [comment]
Awesome!  Thanks!
