### ISSUE TITLE
Permissions issue on Juniper devices "set cli complete-on-space off"

### ISSUE THREAD

**Issue by bgr1980** [ktbyers/netmiko#1806]
I have two Juniper SRX550 devices;

Device A = Junos 12.1X46-D35.1
Device B = Junos12.3X48-D75.4

From my device I can directly access both devices via SSH using Putty and execute the "show version" command.

I have a very simple python script to ssh to the devices as follows (changing IP details a s necessary);

--------- START OF SCRIPT ----------
#!/usr/bin/env python

import time
from netmiko import ConnectHandler
import netmiko

device = ConnectHandler(device_type="juniper_junos", ip="192.168.1.1", username="name", password="password")

output = device.send_command("show version")
print(output)

--------- END OF SCRIPT ----------

The script successfully runs for DeviceA, however I get the following errors when trying to connect to DeviceB;

Traceback (most recent call last):
  File "C:\...\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\...\Python\Python38-32\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\...\Python\Python38-32\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\Python\Python38-32\personalscripts\sshtodevice.py", line 16, in <module>
    device = ConnectHandler(device_type="juniper_junos", ip="192.168.1.1", username="name", password="password")
  File "C:\...\Python\Python38-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 266, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\...\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 327, in __init__
    self._open()
  File "C:\...\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 333, in _open
    self._try_session_preparation()
  File "C:\...\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 756, in _try_session_preparation
    self.session_preparation()
  File "C:\...\Python\Python38-32\lib\site-packages\netmiko\juniper\juniper.py", line 27, in session_preparation
    self.disable_paging(command="set cli screen-length 0")
  File "C:\...\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1027, in disable_paging
    output = self.read_until_pattern(pattern=re.escape(command.strip()))
  File "C:\...\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\...\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 560, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
>>> 

Can anyone assist? I'm at the end of my limited knowledge and ability to troubleshoot further than I have already!!

**Comment by ktbyers** [comment]
Can you include the Netmiko log file?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by bgr1980** [comment]
Thanks for putting me in that direction, I've found the culprit (see below)!

Looks like I have different permissions on different devices and cannot issue the "set cli complete-on-space off" command, this is causing the issue.

2 options I think;

- see if there is a way to issue show commands without the initial "set cli " commands
- try and get my priv's sorted out!

I'll be using the logging function a lot more now :)

DEBUG:netmiko:write_channel: b'set cli complete-on-space off\n'
DEBUG:netmiko:read_channel: set

                               ^

unknown command.


name@DeviceB> set   cli

                               ^

unknown command.


name@DeviceB> setcli   complete-on-space

                               ^

unknown command.


name@DeviceB> setclicomplete-on-space   off

                               ^

unknown command.



{primary:node0}

**Comment by ktbyers** [comment]
Yes, you are going to have all sorts of pain with Juniper devices and SSH automation if you can't disable that so I would see if you can get that allowed on your permissions.


Regards, Kirk

**Comment by viswanath-angajala** [comment]
me too got the same problem, set cli commands are not working on the device but the netmiko is by default setting these commands("set cli complete-on-space off", "set cli screen-length 0" and "set cli screen-width 511") internally. 
Please let me know if you guys found any solution for this issue.

Thanks,
Viswanath

**Comment by ktbyers** [comment]
@viswanath-angajala They are not working because you don't have permissions on the device or something else?

**Comment by viswanath-angajala** [comment]
@ktbyers Thank you so much for your quick response. 
We dont have special permissions to run the 'set cli' commands on the device, its very limited access.  Is there any way / option to bypass these commands and run the commands normally in netmiko?

**Comment by ktbyers** [comment]
You can use `generic_termserver` device_type, but a lot of things will likely not work properly (from a Netmiko-Juniper perspective).

**Comment by bgr1980** [comment]
My issue was resolved by getting privileges/access rights sorted out on the devices that didnt work.

**Comment by viswanath-angajala** [comment]
@ktbyers  Thanks you so much for your suggestion, 'generic_termserver' worked fine for me.

**Comment by andriu-ru** [comment]
Hello dear friends!
I need your help.
I don't have enough rights to use device_type: juniper.
I replaced it with (generic_termserver) but it still didn't work.

When executing the command output = device.send_command("show version").

In the log I see an entry:

----------------------------session_log.txt--------------------------

--- JUNOS 17.3R3-S5.2 built 2019-07-08 14:07:04 UTC







JUNOS tips:
In configuration mode, use the 'insert' command to insert new
configuration into existing lists.

1 alarms currently active
Alarm time Class Description
2021-03-22 10:39:00 GMT-3 Minor ge-1/1/2: ​​Link down

user@NODE-CSR-01>

user@NODE-CSR-01-01>

user@NODE-CSR-01-01>

user@NODE-CSR-01-01>

user@NODE-CSR-01-01>

user@NODE-CSR-01-01>

user@NODE-CSR-01-01>

user@NODE-CSR-01> show

------------------------------------------------------------------------------------------
The (show version) command is not fully displayed.
What is the problem?
