### ISSUE TITLE
" % Invalid input detected at '^' marker" when " net_connect.send_command("show ip device tracking all")

### ISSUE THREAD

**Issue by nsgivanj** [ktbyers/netmiko#1812]
IPDT is quite good feature of Cisco IOS to track client information. Especially a big network, in which IPDT are able to track all user's active and inactive information. 

Unfortunately, I got the upper error message when using netmiko ConnectHandler with a Cisco C2960X.

Any idea?
###config example###

**Comment by ktbyers** [comment]
The `I Invalid input` message is from the device--so for that device the command you sent is invalid:

```
cisco3#show ip device tracking all 
                ^
% Invalid input detected at '^' marker.

```

**Comment by nsgivanj** [comment]
Thanks Ktbyers, 

It's working when using "net_connect = Netmiko", but it's still an issue with "net_connect = ConnectHandler". Although I don't know the difference between Netmiko and ConnectHandler, thank you for your time and help.
