### ISSUE TITLE
set keyboard interactive login strictly for auth method

### ISSUE THREAD

**Issue by mims1979** [ktbyers/netmiko#1813]
Recently we've had a few of our servers switch to MFA system.

The login process looks similar to this in putty:

login as: **MYUSERNAME**
Pre-authentication banner message from server:
|
|                                  WARNING!
|                     MFA Protected system
End of banner message from server
Keyboard-interactive authentication prompts from server:
| Unix Login password: **MYPASSWORD**
| MFA two-factor login for username
|
| Enter a passcode or select one of the following options:
|
|  1. MFA Push to Mobile MFA Client
|  2. SMS passcodes to Cell Phone
|
| Passcode or option (1-2):
End of keyboard-interactive prompts from server
Success. Logging you in...

At the passcode or option I select 1, get the MFA push and then I'm logged in

Any attempts to access this system basically responds with to following debugs:
DEBUG:paramiko.transport:starting thread (client mode): 0x3a10bd0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.4
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.4)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for myhost: b'XXXXXXXXXXXX'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: b'\n                                 WARNING!!.....'
**DEBUG:paramiko.transport:Authentication type (password) not permitted.**
DEBUG:paramiko.transport:Allowed methods: ['gssapi-keyex', 'gssapi-with-mic']
DEBUG:paramiko.transport:EOF in transport thread

I'm fully aware that auth type password isn't permitted, but only keyboard interactive.  There's no try again, so supposed "fallback" methods of paramiko/netmiko will not work here as you aren't allowed to try multiple auth methods, if you do not set keyboard-interactive as the first auth method in putty or other ssh client it will fail.

So how to i specify to netmiko that you should use keyboard-interactive then potentially send my password and "1" for the MFA push as a part of the login process?

Even if I can find a way to just start the ssh connection and then use expect statements to respond to them that is fine, but it appears like the initial connection and authentication is all part of the connect statement when I build the conn:

this_device = {
    "host": host,
    "username": user,
    "password": pw,
    "device_type": "terminal_server",
}
conn = Netmiko(**this_device)

I've also tried changing device_type to linux, autodetect, etc and it doesn't appear to make any changes.

**Comment by ktbyers** [comment]
@mims1979 You will probably have to make your own Netmiko driver/device_type to handle this.

You should look at the pattern used by this Dell PowerConnect as it has something similar:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/dell/dell_powerconnect.py#L65

Basically you will have to specify `SSHClient_noauth()` and then you will need to have your code handle the authentication more directly.

The PowerConnect driver does that here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/dell/dell_powerconnect.py#L94


Regards, Kirk

**Comment by ktbyers** [comment]
Let me know if you are able to get that to work.

**Comment by mims1979** [comment]
Sorry, I got site tracked on some other things and haven't had the chance to get back to this, but looks like what you posted should work for me.  Thank!

**Comment by mims1979** [comment]
So i wasn't able to get it to work with no_auth as it appeared like the examples from dell_powerconnect were getting run after login, but i was able to use auth_interactive and provide a handler to that and it does work as expected now.  Thanks for pointing me in the right direction.
