### ISSUE TITLE
Error handling not being picked up by script

### ISSUE THREAD

**Issue by igeskog** [ktbyers/netmiko#1815]
Hi,

I have an issue with error handling not being picked up by my script. I keep getting the traceback regardless of my exceptions. 
 Im not sure if the issue is with netmiko/paramiko or my script. Im trying to make the below traceback errors go away from the outout. Included is the script im working on.

Im not sure if net_connect.find_prompt() should be able to handle exceptions. I tried to comment that section out

(.venv) igeskog001@itlinux:~$ python3 find.py --find-by-ip 1.2.3.4
Namespace(find_by_ip='1.2.3.4')
find.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CFG = yaml.load(ymlfile)
Traceback (most recent call last):
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 901, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/paramiko/client.py", line 751, in _auth
    self._transport.auth_password(username, password)
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/paramiko/transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "find.py", line 51, in <module>
    device_type="cisco_xr",
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 259, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 332, in _open
    self.establish_connection()
  File "/home/igeskog001/.venv/lib/python3.6/site-packages/netmiko/base_connection.py", line 914, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Authentication failure: unable to connect cisco_xr r1003pye:22
Authentication failed.

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import re
import sys





import logging

logging.basicConfig(filename='example.log',level=logging.DEBUG)

import yaml
import argparse
from netmiko import Netmiko
from paramiko.ssh_exception import SSHException
from paramiko.ssh_exception import AuthenticationException
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import AuthenticationException

parser = argparse.ArgumentParser(description='Find ip address in RR app')

parser.add_argument('--find-by-ip', required=True, help='Find if IP address is in RR')


arguments = parser.parse_args()
print(parser.parse_args())


ip = sys.argv[2]


# Open and load config file
with open("findrouters.yaml", 'r') as ymlfile:
    CFG = yaml.load(ymlfile)


routers = CFG.get('group1')
config = {}

for router in routers:
    net_connect = Netmiko(
    router,
    username="sekrit",
    password='sekrit',
    device_type="cisco_xr",
    )


    # Connect to router
    print('Connecting to router: ' + router)
    try:
        net_connect.find_prompt()
    except (AuthenticationException, NetMikoAuthenticationException):
        print ('oops')
        continue
    except Exception as unknown_error:
        print ('Some other error: ')
        continue
    # Get router config
    try:
        print('Getting config')
        config[router] = net_connect.send_command('show run router bgp 65501')
    except (AuthenticationException, NetMikoAuthenticationException):
        print ('oops')
        continue
    except Exception as unknown_error:
        print ('Some other error: ')
        continue

    # Open output file
    with open(router + '.txt', 'w') as outfile:
        outfile.writelines(config[router])

        net_connect.disconnect()


for router in routers:
    with open(router + '.txt') as infile:
        data = infile.read()

        if data.count(ip):
            print("\nJa den finns i: ",router)
        else:
            print("Nej den finns inte")

```

**Comment by ktbyers** [comment]
It looks like you are getting this exception:

`netmiko.ssh_exception.NetmikoAuthenticationException`

So you should be importing/using that from Netmiko.

```python
from netmiko import ConnectHandler
from netmiko import NetmikoAuthenticationException

device = {
    "device_type": "cisco_ios",
    "host": "cisco1.lasthop.io",
    "username": "pyclass",
    "password": "bogus",
}

try:
    net_connect = ConnectHandler(**device)
except NetmikoAuthenticationException:
    print("Exception handled")
```

```
$ python foo.py 
Exception handled
```

**Comment by igeskog** [comment]
With this configuration I am able to catch the exception. Thought i could do it with net_connect.find_prompt or net_connect.send_command but I guess that does not work?

**Comment by ktbyers** [comment]
Your exception handler (try/except statement) needs to wrap the code that fails.

If Netmiko fails on the SSH connection then trying to handle it when you execute `find_prompt` or `send_command` would be too late. In other words, Netmiko would have failed earlier (i.e. the authentication failure would happen when the SSH connection was established which happens during the ConnectHandler/Netmiko call).

Regards, Kirk
