### ISSUE TITLE
Connecting via a terminal server and handling a menu selection

### ISSUE THREAD

**Issue by MoatazHammouda** [ktbyers/netmiko#1818]
Hello everyone, I have seen similar cases in regards to other platforms, but for my cisco device, I am trying to establish a connection to it yet I face the following error:
```
ValueError: Router prompt not found: 'Selection:'
```
For this particular set of devices once I log in I need to insert an 'x' or a number to move to the enable line for that device from the Selection: prompt (there is a menu with options). This is a console server, so I was wondering if there is a way to pass ( during the connection establishment phase ) the desired 'x' or number?

My code as it stands right now is as follows:
```python
from netmiko import ConnectHandler

device = { "device_type":"cisco_ios","host":"host","password":"pw","username":"user","secret":"secret","global_delay_factor":2}
connection = ConnectHandler(**device)
#The code does not get past this point
connection.enable()
output = connection.send_command('show ip int brief')
```

---------------------------------------------------------------------------------------------------------

**Comment by ktbyers** [comment]
Use the `terminal_server` device_type and then handle the `selection`. An example demonstrating something similar to this is here:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#terminal-server-and-redispatch

**Comment by MoatazHammouda** [comment]
Thank you this has been really helpful.

**Comment by MoatazHammouda** [comment]
Tried this and it worked perfectly
