### ISSUE TITLE
Create methods for send_command_set and send_cmmand_from_file?

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#182]
Is it worth it to create something similar to this?

net_connect.send_command_set(arguments) -- Send a set of commands to remote device
net_connect.send_command_from_file(arguments) -- Send a set of commands loaded from a file

**Comment by TimothyBramlett** [comment]
@ktbyers I think these could be helpful.  Especially the loading from a file.  I may try to help out with creating these.  Do you have any code written for them yet?

**Comment by ktbyers** [comment]
I don't have anything written for this. There are somewhat similar methods (that already exist) for sending_config_set and send_config_from_file (i.e. sending config commands, but not show commands).
