### ISSUE TITLE
Arista check_config_mode fails on hostname change

### ISSUE THREAD

**Issue by ldacol** [ktbyers/netmiko#1822]
This issues seems related to https://github.com/ktbyers/netmiko/issues/1667

When ['hostname test_switch'] is issued with a switch name != to 'test_switch': 

OUTPUT: 
`test@test-VirtualBox:~/Development/Netmiko$ python3 netmiko_show_arp.py 
{'device_type': 'arista_eos', 'host': '192.168.254.50', 'username': 'admin', 'password': 'test123', 'session_log': 'output.log'}
['hostname testswitch']
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/lib/python3/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netmiko_show_arp.py", line 50, in <module>
    main()
  File "netmiko_show_arp.py", line 41, in main
    output = net_connect.send_config_set (config_commands,cmd_verify=False)
  File "/home/test/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1770, in send_config_set
    output += self.exit_config_mode()
  File "/home/test/.local/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 44, in exit_config_mode
    return super().exit_config_mode(exit_config=exit_config, pattern=pattern)
  File "/home/test/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 1642, in exit_config_mode
    if self.check_config_mode():
  File "/home/test/.local/lib/python3.7/site-packages/netmiko/arista/arista.py", line 29, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/home/test/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/test/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
`

DEBUG

`DEBUG:paramiko.transport:starting thread (client mode): 0x91a31550
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.6.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.8
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.8)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp521', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'diffie-hellman-group14-sha1'] server key:['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa', 'ecdsa-sha2-nistp521', 'ssh-ed25519'] client encrypt:['aes256-gcm@openssh.com', 'aes128-gcm@openssh.com', 'aes256-ctr', 'aes192-ctr', 'aes128-ctr'] server encrypt:['aes256-gcm@openssh.com', 'aes128-gcm@openssh.com', 'aes256-ctr', 'aes192-ctr', 'aes128-ctr'] client mac:['hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] server mac:['hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey agreed: ssh-ed25519
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-ed25519 host key for 192.168.254.50: b'57e9d1cc9f78fce9592bd22d939e5454'
DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:Authentication type (password) not permitted.
DEBUG:paramiko.transport:Allowed methods: ['publickey', 'keyboard-interactive']
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (keyboard-interactive) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: Last login: Thu Jul  2 15:25:03 2020 from 192.168.254.35
qweasdzxc>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
qweasdzxc>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is qweasdzxc>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: terminal\ length\ 0
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: erminal length 0
Pagination disabled.
qweasdzxc>
DEBUG:netmiko:Pattern found: terminal\ length\ 0 terminal length 0
Pagination disabled.
qweasdzxc>
DEBUG:netmiko:terminal length 0
Pagination disabled.
qweasdzxc>
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:Pattern is: terminal\ width\ 511
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: erminal width 511
Width set to 511 columns.
qweasdzxc>
DEBUG:netmiko:Pattern found: terminal\ width\ 511 terminal width 511
Width set to 511 columns.
qweasdzxc>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: qweasdzxc
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: qweasdzxc>
DEBUG:netmiko:Pattern found: qweasdzxc 
qweasdzxc>
DEBUG:netmiko:write_channel: b'enable\n'
DEBUG:netmiko:Pattern is: (qweasdzxc|ssword)
DEBUG:netmiko:_read_channel_expect read_data: e
DEBUG:netmiko:_read_channel_expect read_data: nable
qweasdzxc#
DEBUG:netmiko:Pattern found: (qweasdzxc|ssword) enable
qweasdzxc#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: qweasdzxc
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: qweasdzxc#
DEBUG:netmiko:Pattern found: qweasdzxc 
qweasdzxc#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: qweasdzxc
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: qweasdzxc#
DEBUG:netmiko:Pattern found: qweasdzxc 
qweasdzxc#
DEBUG:netmiko:pattern: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: qweasdzxc
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: qweasdzxc#
DEBUG:netmiko:Pattern found: qweasdzxc 
qweasdzxc#
DEBUG:netmiko:check_config_mode: '\r\nqweasdzxc#'
DEBUG:netmiko:check_config_mode: '\r\nqweasdzxc#'
DEBUG:netmiko:write_channel: b'config term\n'
DEBUG:netmiko:Pattern is: config\ term
DEBUG:netmiko:_read_channel_expect read_data: config term

DEBUG:netmiko:Pattern found: config\ term config term

DEBUG:netmiko:Pattern is: qweasdzxc
DEBUG:netmiko:_read_channel_expect read_data: qweasdzxc(config)#
DEBUG:netmiko:Pattern found: qweasdzxc qweasdzxc(config)#
DEBUG:netmiko:pattern: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: qweasdzxc
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: qweasdzxc(config)#
DEBUG:netmiko:Pattern found: qweasdzxc 
qweasdzxc(config)#
DEBUG:netmiko:check_config_mode: '\r\nqweasdzxc(config)#'
DEBUG:netmiko:check_config_mode: '\r\nqweasdzxc(config)#'
DEBUG:netmiko:write_channel: b'hostname testswitch\n'
DEBUG:netmiko:read_channel: hostname testswitch
testswitch(config)#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:pattern: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: qweasdzxc
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: testswitch(config)#
`

With hostname matching the current one the code executes correctly. Is there any workaround for this issue or bug fix? 

Thank you

**Comment by ktbyers** [comment]
That is a bug...I will fix this.

In the interim, you can probably do:

```python
# Add the exit_config_mode=False argument
net_connect.send_config_set(config_commands, exit_config_mode=False)
net_connect.write_channel("end\n")
net_connect.set_base_prompt()
```

Let me know if that works.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/1826
