### ISSUE TITLE
command "show authentication sessions method dot1x | count Auth" prompt

### ISSUE THREAD

**Issue by wangzengyi-jet** [ktbyers/netmiko#1823]
hello ，I have a question about netmiko，please help me solve，very thankful.

the log:
DEBUG:netmiko:[find_prompt()]: prompt is ACCSW-xx-xx>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show authentication sessions method dot1x | count Auth\n'
DEBUG:netmiko:Pattern is: show\ authentication\ sessions\ method\ dot1x\ \|\ count\ Auth
DEBUG:netmiko:_read_channel_expect read_data: s
DEBUG:netmiko:_read_channel_expect read_data: how authentication sessions method dot1x | count Auth
                      ^
% Invalid input detected at '^' marker.

ACCSW-xx-xx>
DEBUG:netmiko:Pattern found: show\ authentication\ sessions\ method\ dot1x\ \|\ count\ Auth show authentication sessions method dot1x | count Auth
                      ^
% Invalid input detected at '^' marker.

ACCSW-xx-xx>

**Comment by ktbyers** [comment]
This is from your network device:

```
^
% Invalid input detected at '^' marker.
```

So that is an invalid command in that connect. My first guess would be that you need to elevate your privileges to execute that command (i.e. call the enable() method).

**Comment by wangzengyi-jet** [comment]
Problem solved, You are right, Thank you so much.

**Comment by wangzengyi-jet** [comment]
net_connect.enable()
Enter enable mode through above, it is ok.
