### ISSUE TITLE
New device_type 'at_8000s' - error sending copy configuration

### ISSUE THREAD

**Issue by vjuagar** [ktbyers/netmiko#1824]
Hello, I am trying to make a copy of the configuration and I continuously get the following error: error Timed-out reading channel

Mi code is:

```
from netmiko import ConnectHandler
import logging
import paramiko
import sys
import time

logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)

paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)

logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")


net_connect = ConnectHandler(device_type='at_8000s', host='192.168.0.254', username='user', password='password', global_delay_factor = 1)
output = net_connect.send_command_timing('copy run start')
output += net_connect.send_command_timing('Yes')
print(output)
net_connect.disconnect() 

```

And in console the following appears to me:

DEBUG:netmiko:repr = '02-Oct-2006 04:23:58 %COPY-I-FILECPY: Files Copy - source URL running-config destination URL flash://startup-config\r\r\n'
DEBUG:netmiko:_read_channel_expect read_data: 02-Oct-2006 04:23:58 %COPY-I-FILECPY: Files Copy - source URL running-config destination URL flash://startup-config

DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '02-Oct-2006 04:24:02 %COPY-N-TRAP: The copy operation was completed successfully\r\r\n'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 02-Oct-2006 04:24:02 %COPY-N-TRAP: The copy operation was completed successfully

DEBUG:netmiko:repr = '02-Oct-2006 04:24:02 %COPY-N-TRAP: The copy operation was completed successfully\r\r\n'
DEBUG:netmiko:_read_channel_expect read_data: 02-Oct-2006 04:24:02 %COPY-N-TRAP: The copy operation was completed successfully

DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'Copy succeeded\r\nconsole# '
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = Copy succeeded
console# 
DEBUG:netmiko:repr = 'Copy succeeded\r\nconsole# '
DEBUG:netmiko:_read_channel_expect read_data: Copy succeeded
console# 
Traceback (most recent call last):

  File "C:\Users\victorjuarezgarcia\anaconda3\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)

  File "C:\Users\victorjuarezgarcia\anaconda3\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()

PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\victorjuarezgarcia\anaconda3\lib\site-packages\netmiko\base_connection.py", line 535, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)

  File "C:\Users\victorjuarezgarcia\anaconda3\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()

timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Abrir-Nueva-Ventana-PyQt5-master pidiendo pass con popup corregido erro de comprobacion conexion 20200626 ultimo\prueba conexion para copia.py", line 39, in <module>
    output += net_connect.send_command_timing('Yes')

  File "C:\Users\victorjuarezgarcia\anaconda3\lib\site-packages\netmiko\base_connection.py", line 1181, in send_command_timing
    new_data = self.read_until_pattern(pattern=re.escape(cmd))

  File "C:\Users\victorjuarezgarcia\anaconda3\lib\site-packages\netmiko\base_connection.py", line 612, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)

  File "C:\Users\victorjuarezgarcia\anaconda3\lib\site-packages\netmiko\base_connection.py", line 546, in _read_channel_expect
    "Timed-out reading channel, data not available."

NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
What is this?

```
device_type='at_8000s'
```

`at_8000s` Netmiko doesn't have a device type for that?


What does the CLI look like when you do it manually?

**Comment by vjuagar** [comment]
Hi, This is a switch that I am testing, everything works correctly for me except when executing the copy of the configuration to and internal memory, if I make it to a tftp, there is no problem.

**Comment by ktbyers** [comment]
There is a second question there:

```
What does the CLI look like when you do it manually?
```

**Comment by vjuagar** [comment]
Hi, the answer by entering it manually is :

console# copy run start
Overwrite file [startup-config] ?[Yes/press any key for no]....01-Oct-2006 03:50                                                                                                 :36 %COPY-I-FILECPY: Files Copy - source URL running-config destination URL flas                                                                                                 h://startup-config
01-Oct-2006 03:50:40 %COPY-N-TRAP: The copy operation was completed successfully
Copy succeeded
console#

**Comment by ktbyers** [comment]
Is this operation slow? How long does it take to complete when you do it manually.

Maybe try adding delay_factor=2 or 4 to your send_command() call.

You should also get rid of that logging to the terminal (if that is happening when Netmiko is executing that could also cause issues).


Kirk

**Comment by vjuagar** [comment]
The operation first asks for confirmation and once confirmed it takes 4 seconds manually. I have tried putting global_delay and in the command itself and it gives me the same error.
