### ISSUE TITLE
Netmiko requires SSHv2: SSHException: Incompatible version (1.5 instead of 2.0)

### ISSUE THREAD

**Issue by abnassiri** [ktbyers/netmiko#1834]
Dear
plase if you can help me to solve this issu
BR

**Comment by ktbyers** [comment]
The underlying Paramiko requires SSHv2 and SSHv1 is not supported.

**Comment by yoonghm** [comment]
You may turn on SSH v 2 in your network switch. For example, in Cisco, you could do this and regenerate ssh keys

R1(config)#ip ssh version 2
R1(config)#crypto key generate rsa

**Comment by abnassiri** [comment]
Dear
I m working on an opérationnel network; more then 500 NE  so I can't configure Router by router 
Thank you

**Comment by ktbyers** [comment]
SSHv2 is on the order of 15 years old.

If you have terminal server access or telnet access you could possibly use Netmiko to configure SSHv2 using one of these two.
