### ISSUE TITLE
SSH WITH PROXY SERVER ISSUE

### ISSUE THREAD

**Issue by doug1as** [ktbyers/netmiko#1839]
Hello,

I'am having issue to conect in a hosts behind a proxy server.
I tried to search in another issues, but no found some help !
https://github.com/ktbyers/netmiko/issues/1204
https://github.com/ktbyers/netmiko/issues/1507
https://github.com/ktbyers/netmiko/issues/338

My script is:

#!/usr/bin/env python
from netmiko import ConnectHandler
import getpass
import sys

username = str(input("Inform your user: "))
password = getpass.getpass("Inform your password: ")

for hostname_param in sys.argv[1:]:
    print(hostname_param)
    device = {
        'device_type': 'cisco_xr',
        'host': hostname_param,
        'username': username,
        'password': password,
        'ssh_config_file': '~/.ssh/config-test'
    } 
    try:
        net_connect = ConnectHandler(**device)
        output = net_connect.send_command("show users")
        print(output)  
    except:
        print("Oops!", sys.exc_info()[0], "occurred.")
        continue

When i try to use i have this stack trace:

DEBUG:paramiko.transport:starting thread (client mode): 0x3baca00
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2212, in _check_banner
ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 622, in _read_timeout
ERROR:paramiko.transport:    raise socket.timeout()
ERROR:paramiko.transport:socket.timeout
ERROR:paramiko.transport:
ERROR:paramiko.transport:During handling of the above exception, another exception occurred:
ERROR:paramiko.transport:
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2216, in _check_banner
ERROR:paramiko.transport:    raise SSHException(
ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:

I be able to log in jumphost (proxy server) with ssh config archive write:
[user@localhost aleatory_tests]$ ssh -F ~/.ssh/config-test jumpv2
Last login: Thu Jul  9 22:04:27 2020 from 10.8.253.139

[user@hostname ~]$ 

Thanks a lot !
Regards !

**Comment by ktbyers** [comment]
@doug1as You need to include the contents of this file:

```
 ~/.ssh/config-test
```

**Comment by doug1as** [comment]
Sorry @ktbyers ,

This is the content of my archive.

[douglas.rodrigues@localhost ~]$ cat ~/.ssh/config-test
# The intermediate server
host jumpv2
 # The SSH key to use to the intermediate server
 IdentityFile ~/.ssh/id_rsa
 # Use only the key specified in IdentityFile
 IdentitiesOnly yes
 #
 user USUARIO
 hostname 10.200.1.29
#
# Use the SSH proxy for all endpoints
host * !jumpv2
 ProxyCommand ssh jumpv2 nc %h %p

**Comment by ktbyers** [comment]
This ProxyCommand section needs the `-F` argument also otherwise it will use the standard ~/.ssh/config file.

```
#Use the SSH proxy for all endpoints
host * !jumpv2
   ProxyCommand ssh -F ~/.ssh/config-test jumpv2 nc %h %p
```

**Comment by ktbyers** [comment]
Reference here:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#contents-of-ssh_config-file

**Comment by doug1as** [comment]
Thanks a lot for your help @ktbyers, it's working fine now ...

One doubt, these way works fine in another script machine, why ?

USER@HOSTNAME:~/scripts/aleatory_tests$ python3 testa_proxy.py HOSTNAME
Inform your user: USER
Inform your password: 
HOSTNAME
Sat Jul 11 04:14:33.704 BRGMT
   Line            User                 Service  Conns   Idle        Location
*  vty0            USER             ssh          0  00:00:00     10.200.1.29
USER@HOSTNAME:~/scripts/aleatory_tests$ cat  ~/.ssh/config-test              
#The intermediate server
host jumpv2
 #The SSH key to use to the intermediate server
 IdentityFile ~/.ssh/id_rsa
 #Use only the key specified in IdentityFile
 IdentitiesOnly yes
 user USER
 hostname 10.200.1.29
#Use the SSH proxy for all endpoints
host * !jumpv2
 ProxyCommand ssh jumpv2 nc %h %p

USER@HOSTNAME:~/scripts/aleatory_tests$ cat testa_proxy.py 
#!/usr/bin/env python
from netmiko import ConnectHandler
import getpass
import sys
import logging

#Generating log file for analysis when needed
logging.basicConfig(filename='testa_proxy.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

username = str(input("Inform your user: "))
password = getpass.getpass("Inform your password: ")

for hostname_param in sys.argv[1:]:
    print(hostname_param)


    device = {
        'device_type': 'cisco_xr',
        'host': hostname_param,
        'username': username,
        'password': password,
        'ssh_config_file': '~/.ssh/config-test'
    } 
    try:
        net_connect = ConnectHandler(**device)
        output = net_connect.send_command("show users")
        print(output)  
    except:
        print("Oops!", sys.exc_info()[0], "occurred.")
        continue

USER@HOSTNAME:~/scripts/aleatory_tests$ pip3 show netmiko
Name: netmiko
Version: 3.0.0
Summary: Multi-vendor library to simplify Paramiko SSH connections to network devices
Home-page: https://github.com/ktbyers/netmiko
Author: Kirk Byers
Author-email: ktbyers@twb-tech.com
License: MIT
Location: /usr/local/lib/python3.7/dist-packages
Requires: setuptools, textfsm, scp, paramiko, pyserial
Required-by: 

Python version is 3.7
