### ISSUE TITLE
Need to use SCP for transfer file in Netmiko which uses RSA soft tokens and password keep changing after everyuse.

### ISSUE THREAD

**Issue by ritesh0313** [ktbyers/netmiko#1841]
Need to use SCP for transfer file in Netmiko which uses RSA soft tokens and password keep changing after everyuse. Please suggest. 

Getting Authentication Failed error while using SCP netmiko as we need to manually enter password while establishing the connection. Do we have any additional argument to pass along with scp connection for new password.

Plz suggest.

import netmiko
from netmiko import SCPConn

 def transfer_file(net_connect,file):
 	net_connect.config_mode()
 	#Assumes SCP server isn't already enabled
 	net_connect.send_command('ip scp server enable')
 	scp_conn = SCPConn(net_connect)
 	#Source file
 	s_file = file
 	#Destination file
 	d_file = file
 	scp_conn.scp_transfer_file(s_file, d_file)
 	#Takes SCP server back off the device
 	net_connect.send_command('no ip scp server enable')
 	net_connect.exit_config_mode()
 
 net_connect = netmiko.ConnectHandler(device_type='cisco_ios', ip=ip, 
                              username=username, password=password) #once this password used in establishing connection cannot be reused for scp conn
 
 transfer_file(net_connect,"file_name")

**Comment by ktbyers** [comment]
Yeah, I don't have a good solution on that...you would probably need to hack-around on the Netmiko code to come up with a solution.
