### ISSUE TITLE
handling  copy scp://   bootflash  command on a better way (Cisco_ios)

### ISSUE THREAD

**Issue by PterC-F** [ktbyers/netmiko#1843]
Hello

I'm trying to automate upload new binaries into some devices by using copy SCP command.

The file uploads fine, most of the times (sometimes netmiko die because it takes so long to receive the "#" in the prompt, basically, a timeout, because uploading a file takes me around 3 hours)

Also, I'm trying to add some message, just to know if things are going OK... using a while loop, that is supposed to be looking for the "#" in the channel/prompt. But  its never print anything

Is there a good way to handle this?
Also, I've played with the "send_command_timing" function, with similar results.

An example of what I'mt trying to do

**------------------------------------------------------------------------------------------------------------------**

```python
scp_command="copy scp://A:USERNAME:MYPASSWORD@192.168.0.1//path/to/file.bin  bootflash:file.bin vrf VRF_NAME \n"

scp_transfer = net_connect.send_command(command_string=scp_command, strip_prompt=False,
                                       expect_string=r"Destination filename",delay_factor=30)
scp_transfer += net_connect.send_command(command_string="\n", strip_prompt=False,
                                        strip_command=False,delay_factor=30,expect_string=r"#") 



**This part never works**

animation = "|/-\\"
idx = 0
while True:                        
          print("Copying file please wait ..." end="\r")
           idx = +1
           sleep(0.5)          
           if "#" in  net_connect.find_prompt() or net_connect.readchannel() :
           break                   

 
print(scp_transfer)
```

**------------------------------------------------------------------------------------------------------------------** 
(I know this is not the best way to upload files into devices but is the only way permitted, I can not enable FTP/SCP server on the router)

**Comment by ktbyers** [comment]
`send_command()` defaults to about 100 seconds to complete a command.

So setting delay_factor to 30 would give you about 3000 seconds to complete a command, but if your operation takes 3+ hours than that is insufficient.

I would try something like:

```python
send_command(cmd, max_loops=14400, delay_factor=5)
```

With a delay_factor of five then the loop delay will be 1 second. So max_loops=14400 will allow for 4 hours.

Basically the math is:

```
.2 * max_loops * delay_factor
```

And these default to max_loops=500 and delay_factor=1

So the default is `.2 * 500 * 1` = 100 seconds

Sorry for the complexity here...I need to simplify this.

**Comment by PterC-F** [comment]
Thanks  ktbyers, that's math helps me to move on.

Just one last question, it is possible to use the "read_channel" while awaiting for longs commands to end?
to implement a "what for"  message, so I kind of know if the file still being uploaded?
I know I can use the logging function, but it's to noisy. 

I was trying to do something like:
`send_comand` (expect_string=r"#", )
while True:                        
          print("Copying file please wait ..." end="\r")
           idx = +1
           sleep(0.5)          
           if "#" in  net_connect.find_prompt() or net_connect.readchannel() :
           break     `

But it doesn't work.

**Comment by ktbyers** [comment]
Yeah, sure you can build your own loop using `read_channel`. I might not help you debug it if it doesn't work, however :-)

I don't think that will work properly trying to do `find_prompt()` in that way. You probably would need to do `read_channel()` and then do a regex pattern search on what is returned. Of course, then you are starting to re-create things that already exist in Netmiko.

**Comment by PterC-F** [comment]
Thanks  ktbyers  👍
