### ISSUE TITLE
Netmiko Juniper - Not issuing commands sent.

### ISSUE THREAD

**Issue by ghost** [ktbyers/netmiko#1848]
Juniper doesn't save using save_config command. So I was trying to enter config mode and issue a manual save, but the enter config_mode command doesn't get processed. After the exit configuration-mode the next command in script is to go back to config mode, which never happens.

`        # Goto enable mode, Execute Changes, then save configuration
        #
        print("\t\t\tGoing into Configuration mode...")
        if DEVICE_TYPE == "juniper_junos":
            ssh_session.config_mode()
        else:
            ssh_session.enable()
        print("\t\t\t\tSending Changes from file " + change_file + "...")
        Execute_Changes = ssh_session.send_config_from_file(change_file)
        print("\t\t\t\tSaving Configuration...")
        if DEVICE_TYPE == "juniper_junos":
            ssh_session.send_command('commit comment "' + CHANGE_TICKET + '"')
        else:
            ssh_session.save_config()
        print("\t\t\tExiting Configuration mode...")
        if DEVICE_TYPE == "juniper_junos":
            ssh_session.exit_config_mode()
        else:
            ssh_session.exit_enable_mode()`

`user@device# exit configuration-mode 
Exiting configuration mode

user@device> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

user@device> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is user@device>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'commit comment "U-TEST"\n'
DEBUG:netmiko:Pattern is: commit\ comment\ "U\-TEST"
DEBUG:netmiko:_read_channel_expect read_data: commit

                        ^

unknown command.

user@device> commit   com
DEBUG:netmiko:_read_channel_expect read_data: ment`

**Comment by ktbyers** [comment]
@jg555 Have you tried the `commit` method that is available for Juniper?

**Comment by jg555** [comment]
That worked, but we need to use -U comment, this aids in doing a rollback of the change back to the previous version.

**Comment by ktbyers** [comment]
There is a `comment` field on the `commit` method:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/juniper/juniper.py#L114

Is that what you are looking for?


Kirk
