### ISSUE TITLE
paramiko.transport:Authentication (keyboard-interactive) failed

### ISSUE THREAD

**Issue by Hemantkapi** [ktbyers/netmiko#1855]
Hi ,

I am trying to login a SRAS server but getting below mentioned error.

My Code - SRAS2.py

import paramiko
import socket

def handler(title, instructions, fields):
    if len(fields) > 1:
        raise SSHException("Expecting one field only.")
   return ['password']

Host = 'my server'

if __name__=="__main__":
  paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
  s=socket.socket()
  s.connect((Host,48152))
  t=paramiko.Transport(s)
  t.set_log_channel("paramiko.transport")
  t.start_client()
  t.auth_interactive ('user',handler)

but I am getting below mentioned error: Please help

DEBUG:paramiko.transport:starting thread (client mode): 0xa754b520
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Nakina_SSH_1.0
INFO:paramiko.transport:Connected (version 2.0, client Nakina_SSH_1.0)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', '3des-cbc', '3des-ctr', 'blowfish-cbc', 'blowfish-ctr'] server encrypt:['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', '3des-cbc', '3des-ctr', 'blowfish-cbc', 'blowfish-ctr'] client mac:['hmac-sha1', 'hmac-md5', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-sha1', 'hmac-md5', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group14-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:EOF in transport thread
Traceback (most recent call last):
  File "SRAS2.py", line 22, in <module>
    t.auth_interactive ('User',handler)
  File "C:\Python38\lib\site-packages\paramiko\transport.py", line 1633, in auth_interactive
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Python38\lib\site-packages\paramiko\auth_handler.py", line 236, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

**Comment by Hemantkapi** [comment]
This server is using Keyboard interactive Authentication and not taking password whereas Login is possible using SSH using putty

**Comment by OzNetNerd** [comment]
As you're not using Netmiko, perhaps you'd be better off posting this issue in the [Paramiko repo](https://github.com/paramiko/paramiko).

**Comment by Hemantkapi** [comment]
I am new in python, Can I use Netmiko to achieve the same as our server is using Keyboard Interactive Authentication.  I am able to ssh with below method which is interactive but not able to send command further as I need to login devices connected via this jump server. 

trasnport.auth_interactive_dumb(Username, handler=None, submethods='')

**Comment by ktbyers** [comment]
Closing as not a Netmiko issue.
