### ISSUE TITLE
Search pattern never detected in send_command_expect due to dynamic prompt

### ISSUE THREAD

**Issue by allan-silverstein** [ktbyers/netmiko#1856]
Hello Kirk,
I have vendor that where the prompt seems to dynamically change.  It happens due to the equivalent of a "set cli timestamp" type feature.  The timestamp get's embedded in the prompt.  Thus, the exact searching string before entering the command may be different than the prompt after the command is completed... Depending on the amount of time that has elapsed.

Exception ERROR: Search pattern never detected in send_command_expect: ^[\[FHUSTX21CWP\(22\-Jul\-2020\-21:35:05\)\#

Any suggestions for handling this?
Thx
Al Silverstein

**Comment by ktbyers** [comment]
Which Netmiko platform is this on?

Can you include the Netmiko log file for this:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by allan-silverstein** [comment]
Ok, I'll try and catch it... Very intermittent.

**Comment by ktbyers** [comment]
I am going to close this. Please re-open if you have the log-file.


Regards,

Kirk

**Comment by allan-silverstein** [comment]
Will do thx.On Aug 20, 2020 1:51 PM, Kirk Byers <notifications@github.com> wrote:
I am going to close this. Please re-open if you have the log-file.
Regards,
Kirk

**Comment by dcsaki** [comment]
Hi Kirk,
I have same problem as reported by Al.
Is always reproducible if command takes longer than 1 second - example in test.log is with "sleep 2"
[test.log](https://github.com/ktbyers/netmiko/files/10085954/test.log)
Have tried with both auto_find_prompt = True & False
Any other suggestions?
Thanks,
David

**Comment by ktbyers** [comment]
@dcsaki Can you open a new issue.

Put the exception message, the relevant section of your code, and your log file.


Thanks.
