### ISSUE TITLE
Cisco XR commit comment should not be quoted

### ISSUE THREAD

**Issue by tdorssers** [ktbyers/netmiko#1858]
The cisco_xr driver is currently quoting a commit comment, which is redundant. This is a day 0 issue since #89. Please have a look at commitId 1000003264, which is configured by netmiko:

```
RP/0/RSP0/CPU0:XR1(config-if)#commit comment ?
  LINE  Comment for this commit (Max 60 characters)
RP/0/RSP0/CPU0:XR1(config-if)#commit comment no quotes required
Wed Jul 29 17:52:59.910 CEST
RP/0/RSP0/CPU0:XR1(config-if)#
RP/0/RSP0/CPU0:XR1#show configuration commit list detail 
Wed Jul 29 17:53:09.703 CEST

   1) CommitId: 1000003265                 Label: NONE
      UserId:   admin                      Line:  vty0:node0_RSP0_CPU0
      Client:   CLI                        Time:  Wed Jul 29 17:52:59 2020
      Comment:   no quotes required 

   2) CommitId: 1000003264                 Label: NONE
      UserId:   admin                      Line:  vty1:node0_RSP0_CPU0
      Client:   CLI                        Time:  Wed Jul 29 10:18:12 2020
      Comment:   "bulk provision" 

```

For your reference, I manually configured the router to demonstrate that quotes are not needed.
I propose to remove the quoting and add a check to limit the comment length to 60 chars.
If the length exceeds 60, the commit will fail:

```
RP/0/RSP0/CPU0:XR1(config)#commit comment 0123456789012345678901234567890123456789012345678901234567890123456789
                                                                                                      ^
% Invalid input detected at '^' marker.

```

Thanks.

**Comment by OzNetNerd** [comment]
@tdorssers, I've raised a PR to fix the quoting - https://github.com/ktbyers/netmiko/pull/1878. If it's integrated into the code base, you'll be able to disable quotes by passing `quote_comment=False` to `commit()`.

As per the PR comment, I didn't implement a comment length restriction. The reason being that it may create issues in the future.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/1880
