### ISSUE TITLE
Unable to import netmiko module in Python 3.5

### ISSUE THREAD

**Issue by kousikbangalore** [ktbyers/netmiko#1859]
Hello,

I am new in python programming. I am not able to import netmiko & paramiko module in Python 3.5. I am using docker container. Getting the below error. 

Python 3.5.2 (default, Jul 17 2020, 14:04:10)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'netmiko'
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'netmiko'

Thanks,
Kousik

**Comment by ktbyers** [comment]
Netmiko requires Python 3.6 or greater. You would need to use Netmiko 2.4.2 if you wanted to use it on Python 3.5.

It also looks like you have a Netmiko installation error. You would need to `pip install netmiko==2.4.2`

**Comment by kousikbangalore** [comment]
First of all thank you for your quick responses.
Could you please share me the process, how can i configure python  3.6 in ubunru docker. Every time i can able to install puthon 3.5 not 3.6.

Thanks,
Kousik

**Comment by ktbyers** [comment]
I would think you would just use a newer Ubuntu distribution/docker image that came with a newer version of Python. Python 3.5 is getting pretty old at this point.

**Comment by kousikbangalore** [comment]
Thank you for suggestion. It will be extremely helpful for me if you can share the link where i can get/download the docker container.

**Comment by ktbyers** [comment]
How about Google Search: "Docker Ubuntu"
