### ISSUE TITLE
Going into enable mode fails

### ISSUE THREAD

**Issue by tars01** [ktbyers/netmiko#1861]
Kirk

I have an issue where on some Cisco devices (routers) where it fails to go into enable mode. They are quite slow going into enable mode because they are on remote connections on slow lines but I have tried setting global_delay to as high as 30 and it still fails so it's some other issue going on here.

If I log on to the device it goes into enable mode fine (takes about 10 seconds) 

When you go into enable mode the devices go straight to level 15 (no enable password required) It works fine like this on hundreds of routers but on about 5 or 10% of them it just fails and I can't see any reason why. 

**My connection parameters (no enable secret)**

```
    ios_device = {
        'device_type': 'cisco_ios',
        'ip': ip_address_of_device,
        'username': username,
        'password': password,
        'session_log': 'session_output',
    }
```

**Debug log**

```
Test-BA-sr1-lab-ce>
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel:

DEBUG:netmiko:Pattern is: Test\-BA\-sr1\-lab\-ce
DEBUG:netmiko:_read_channel_expect read_data:
Test-BA-sr1-lab-ce>
DEBUG:netmiko:Pattern found: Test\-BA\-sr1\-lab\-ce
Test-BA-sr1-lab-ce>
DEBUG:netmiko:write_channel: enable

DEBUG:netmiko:Pattern is: (Test\-BA\-sr1\-lab\-ce|ssword)
DEBUG:netmiko:_read_channel_expect read_data: enable

DEBUG:paramiko.transport:EOF in transport thread
```

**Session log**
```
Test-BA-sr1-lab-ce>
Test-BA-sr1-lab-ce>terminal length 0
Test-BA-sr1-lab-ce>terminal width 511
Test-BA-sr1-lab-ce>
Test-BA-sr1-lab-ce>
Test-BA-sr1-lab-ce>
Test-BA-sr1-lab-ce>enable
```

**Comment by ktbyers** [comment]
It takes 10 seconds to go into `enable` mode with no password when you do it manually?

Can you post the exception stack trace that you receive?

**Comment by tars01** [comment]
Yes that's correct, they are in some very remote parts of the world. I think the delay is the communication back to tacacs. Sorry, I should have mentioned I am using an older version of netmiko (netmiko==2.4.2) I normally use the latest version but in this scenario I only have access to a server with Python2.7 on which I can't upgrade.

```

Traceback (most recent call last):
  File "temp.py", line 104, in <module>
    net_connect.enable()
  File "/home/test/.local/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 22, in enable
    cmd=cmd, pattern=pattern, re_flags=re_flags
  File "/home/test/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 1468, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.
```

**Comment by nullbitzero** [comment]
Hi,
In reference to the python version and as a test you can use the send_command ('enable', expect_string = '#') function. Ideally, you can update the python version to take advantage of the code improvements developed in netmiko.

**Comment by tars01** [comment]
This gets me working, thank you. Normally I use the latest versions but I'm stuck for this instance. 

Thanks, closing the issue.
