### ISSUE TITLE
Accedian driver should not raise AttributeError for enable() call

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1864]
https://github.com/ktbyers/netmiko/blob/develop/netmiko/accedian/accedian_ssh.py#L17

This breaks things with other libraries/frameworks like Nornir/NAPALM/Ansible which might auto-call enable()

**Comment by veprimk** [comment]
Hi Kirk,

I appended this code to the nornir.plugins.tasks.networking.netmiko_send_config.py

`def netmiko_send_config_noenable(
    task: Task,
    config_commands: Optional[List[str]] = None,
    config_file: Optional[str] = None,
    **kwargs: Any
) -> Result:
    """
    Execute Netmiko send_config_set method (or send_config_from_file)

    Arguments:
        config_commands: Commands to configure on the remote network device.
        config_file: File to read configuration commands from.
        kwargs: Additional arguments to pass to method.

    Returns:
        Result object with the following attributes set:
          * result (``str``): string showing the CLI from the configuration changes.
    """
    net_connect = task.host.get_connection("netmiko", task.nornir.config)
    # if enable_mode != True:
    #     net_connect.enable()
    if config_commands:
        result = net_connect.send_config_set(config_commands=config_commands, **kwargs)
    elif config_file:
        result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
    else:
        raise ValueError("Must specify either config_commands or config_file")

    return Result(host=task.host, result=result, changed=True)
`

Then on nornir.plugins.tasks.networking.__init__.py  I added following:

`
from .netmiko_send_config import netmiko_send_config_noenable

__all__ = (
    "napalm_cli",
    "napalm_configure",
    "napalm_get",
    "napalm_validate",
    "netconf_capabilities",
    "netconf_edit_config",
    "netconf_get",
    "netconf_get_config",
    "netmiko_commit",
    "netmiko_file_transfer",
    "netmiko_send_command",
    "netmiko_send_config",
    **"netmiko_send_config_noenable",**
    "netmiko_save_config",
    "tcp_ping",
    "napalm_ping",
)
`
Solved my problem and I could also use it for Cisco IOS to send multiple commands as a list without having to re-run the task as iteration which basically would mean another SSH into the device and doesn't work for cases like running TCLSH scripts.

Thanks,
Veprim

**Comment by ktbyers** [comment]
Yes, you shouldn't be using `send_config_set` for these tclsh operations.

In other words, send_config_set is not the proper solution to achieve a for-loop of commands. For that you should use `send_command` and and a custom Nornir task (which would avoid the loss of state problem mentioned above).

So something like:

```python
def netmiko_direct(task):

    # Manually create Netmiko connection
    net_connect = task.host.get_connection("netmiko", task.nornir.config)

    # Use the connection
    command_list = ["show arp", "show ip int brief", "show interface"]
    output = ""
    for cmd in command_list:
        output += net_connect.send_command(cmd)

    # Close the connection
    task.host.close_connection("netmiko")

    return output
```

Regards, Kirk

**Comment by ktbyers** [comment]
Purging old issues...
