### ISSUE TITLE
auto_connect not working when passed in ConnectHandler/CiscoBaseConnection

### ISSUE THREAD

**Issue by rubengm13** [ktbyers/netmiko#1865]
Going through the API  documentation I noticed that auto_connect was a feature I wanted to utilize. I didn't want the connection to be established as soon as I created the SSH Class.
https://ktbyers.github.io/netmiko/docs/netmiko/cisco_base_connection.html

I tried it in both ConnectHandler and CiscoBaseConnection, got:
`TypeError: __init__() got an unexpected keyword argument 'auto_connect'`

I checked the library and found no 'auto_connect' in it.

Running netmiko 3.1.1

Is auto_connect, something that will be added later and somehow made it to the documentation?

Is there a workaround to prevent the Start of the connection? (similar to what auto_connect =False would do)?

**Comment by ktbyers** [comment]
@rubengm13 I think it is only in the develop branch (so you would need to use that branch)...until the next Netmiko release.

Regards, Kirk

**Comment by ktbyers** [comment]
Closing as no additional actions to do on this issue.
