### ISSUE TITLE
Breaks when enabling on specific HP procurve line

### ISSUE THREAD

**Issue by ctomkow** [ktbyers/netmiko#187]
Trying to enable on a HP with TACACS+ prompts for username and password again...not the enable password.  Netmiko is expecting to see 'Please Enter Password:' instead.

```
SSH connection established to 172.30.28.254:22
Interactive SSH session established
Traceback (most recent call last):
  File "/home/ctomkow/bin/swITch.py", line 182, in <module>
    swITch()
  File "/home/ctomkow/bin/swITch.py", line 40, in __init__
    args.portlist)
  File "/home/ctomkow/bin/swITch.py", line 125, in main
    dev.enable()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/hp/hp_procurve_ssh.py", line 41, in enable
    self.set_base_prompt()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 284, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: Please Enter Password:`
```

**Comment by ctomkow** [comment]
To expand on this a bit, it looks like your code does handle the re-prompt for username.  On my HP I have, it prompts for 'Please Enter Login Name:' not username.  This may be the issue?  I haven't dug into your code too closely to see how it handles expecting on the prompt though.

**Comment by ctomkow** [comment]
So I dug into RANCID and how it deals with this login type (in hlogin).  It seems they expect on a couple different things `Username|login|user name`.  I haven't suggested any code to fix the issue yet, I have just explored the issue as i'm not yet familiar with your code.  Maybe this weekend I will come up with a reasonable solution.

**Comment by ktbyers** [comment]
@ctomkow Can you send over to me what the SSH session looks like on this HP box. Just the login part where it is asking for Login Name: and Password. Obviously, strip out anything that is confidential to your environment.

**Comment by ctomkow** [comment]
Here is the output for the enable login and password part.  As a side note, I noticed I tested on some other HP boxes and it defaults to providing 'manager' as default username (which breaks enable on a bunch of HPs).  Not sure why that is when I have provided username and password.  Anyway, here is the trace regarding the original issue.

```
mySwitch2> 
repr = u'\x1b[2J\x1b[?7l\x1b[?6l\x1b[?6l\x1b[?7l\x1b[2J\x1b[2J\x1b[?7l\x1b[?6lmySwitch2> \nmySwitch2> no page\nInvalid input: no\n\rmySwitch2> '
In set_base_prompt
In strip_ansi_escape_codes
repr = u'\x1b[24;0H\x1bE\x1b[24;1H\x1b[24;16H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[24;1HmySwitch2> \x1b[24;1H\x1b[24;16H\x1b[24;1H\x1b[?25h\x1b[24;16H'
new_output = 
mySwitch2> 
repr = u'\nmySwitch2> '
prompt: mySwitch2
In send_command
Command is: enable

In strip_ansi_escape_codes
repr = u'\x1b[24;16Henable\x1b[24;16H\x1b[?25h\x1b[24;22H\x1b[24;0H\x1bE\x1b[24;1H\x1b[24;22H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[24;1HPlease Enter Login Name: \x1b[?25h\x1b[24;1H\x1b[?25h\x1b[24;26H\x1b[24;26H\x1b[?25h\x1b[24;26H'
new_output = enable
Please Enter Login Name: 
repr = u'enable\nPlease Enter Login Name: '
Please Enter Login Name: 
In set_base_prompt
In strip_ansi_escape_codes
repr = u'\x1b[1;1H\x1b[?25l\x1b[24;26H\x1b[24;1H\r\n\r\x1b[?25h\x1b[24;26H\x1b[24;1HPlease Enter Password: \x1b[?25h\x1b[24;1H\x1b[?25h\x1b[24;24H'
new_output = [?25l

Please Enter Password: 
repr = u'\x1b[?25l\r\n\rPlease Enter Password: '
Router prompt not found: Please Enter Password:

./swITch.py -e -i 172.30.28.254,hp_procurve -a ../auth.txt > output2.txt
Traceback (most recent call last):
  File "./swITch.py", line 185, in <module>
    swITch()
  File "./swITch.py", line 40, in __init__
    args.portlist)
  File "./swITch.py", line 127, in main
    dev.enable()
  File "/usr/lib/python2.7/site-packages/netmiko/hp/hp_procurve_ssh.py", line 41, in enable
    self.set_base_prompt()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 284, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: Please Enter Password:
```

**Comment by ktbyers** [comment]
@ctomkow Okay, it looks like we need to add a special handler for this. 

I was able to decipher it with the ANSI codes.

**Comment by aniketprajapati** [comment]
Hi ktbyers, can you share how you decipher the ANSI codes in a generic way

**Comment by ktbyers** [comment]
Use Python's `repr` built-in to see them. For example,

```
print repr(my_str)
```

Then use google to look them up.

**Comment by aniketprajapati** [comment]
Thanks @ktbyers

**Comment by ktbyers** [comment]
I put a fix for the different prompts here...it only took about 18 months :-)

https://github.com/ktbyers/netmiko/commit/471e0b2f4a82d9b72e16353cf24e3b85201724cb

I didn't make any modifications to the ANSI escape codes.

**Comment by napstercc** [comment]
I have a similar issue with an Aruba switch:
```
raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: '\x1b[1;0H\x1b[1M\x1b[24;1H\x1b[1L\x1b[24;10H\x
```
What is the fix for this?
