### ISSUE TITLE
Cisco XR suppressing error message on XR device when SSH connected

### ISSUE THREAD

**Issue by taisasak** [ktbyers/netmiko#1875]
netmiko: 3.2.0
Cisco XR: 7.0.2

__[Problem Description]__

I can see the below error message on a Cisco XR device every time netmiko is SSH connected to a Cisco XR device.
```
RP/0/RP0/CPU0:Aug  6 13:49:13.303 JST: SSHD_[68767]: %SECURITY-SSHD-3-ERR_ERRNO : Failed to set window size: %s 'tty-infra' detected the 'fatal' condition 'An invalid operation has been requested'
```
```python
from netmiko import ConnectHandler

NCS5504_A = {
    'device_type': 'cisco_xr',
    'host':   '<A.B.C.D>',
    'username': '<username>',
    'password': '<password>',
}

netconn = ConnectHandler(**NCS5504_A)
```

Even though I don't see any functional problems, I'd like to suppress the above error message from Cisco XR device's point of view.

__[Troubleshoot]__

As far as I debugged from Cisco XR device side, Cisco XR device emits the above error message when SSH terminal width/height is out of the below supported ranges.

- terminal width: <0-512>
- terminal height: <0-512>

The current netmiko always sets terminal width=511 and terminal height=1000 by default, and they're not configurable.
```python
class BaseConnection(object):
    """
    Defines vendor independent methods.
    Otherwise method left as a stub method.
    """

    -- snip --

    def establish_connection(self, width=511, height=1000):
        """Establish SSH connection to the network device
        -- snip --
```

__[Fix]__

I think there are a couple of ways to fix this issue.

1. Modify BaseConnection class so that both terminal width/height could be configurable by a netmiko user
1. Modify CiscoXrBase class so that it would overwrite establish_connection() method with allowed terminal width/height by the below patch. (I tried the below patch and confirmed the error message would not be seen anymore on a Cisco XR device)

```python
diff --git a/netmiko/cisco/cisco_xr.py b/netmiko/cisco/cisco_xr.py
index e698609..7559188 100644
--- a/netmiko/cisco/cisco_xr.py
+++ b/netmiko/cisco/cisco_xr.py
@@ -4,6 +4,9 @@ from netmiko.cisco_base_connection import CiscoBaseConnection, CiscoFileTransfer


 class CiscoXrBase(CiscoBaseConnection):
+    def establish_connection(self):
+        super().establish_connection(width=511, height=511)
+
     def session_preparation(self):
         """Prepare the session after the connection has been established."""
         self._test_channel_read()
```

Would you look at this issue and let me know which you think better?

Thanks,
Taisuke

**Comment by ktbyers** [comment]
Yes, do the second one where you create an establish_connection method in the CiscoXrBase class and then invoke super on the parent class.

Thanks, Kirk

**Comment by taisasak** [comment]
@ktbyers 

Thank you for your comment!
I've just submitted a pull request https://github.com/ktbyers/netmiko/pull/1876

Thanks, Taisuke
