### ISSUE TITLE
prompt user/pass

### ISSUE THREAD

**Issue by calvinchristopher** [ktbyers/netmiko#188]
Hello Kirk, looking forward to Thursday's class.

I'm looking for a way to prompt for a user/pass to be passed within each device in a list.

For instance:
device_creds.py:
------
`username = ''`
`password = ''`

`SW1 = {`
`  'device_type': 'cisco_ios',`
`  'ip': '172.16.1.189',`
`  'username': username,`
`  'password': password,`
`  'verbose': False,`
`  }``

`SW2 = {`
`  'device_type': 'cisco_ios',`
`  'ip': '172.16.1.190',`
`  'username': username,`
`  'password': password,`
`  'verbose': False,`
`  }``

`all_devices = [SW1, SW2]`

------
main script:
------

`from  device_creds import all_devices`

`username = raw_input('Please enter your username: \n')`
`password = raw_input('Please enter your password: \n')`

`def main():`
`    for a_device in all_devices:`
`        ssh_session = ConnectHandler(**a_device)  `

------

what sort of strategy would you invoke to insert a username/password prompt into the dictionary containing username/password? Can you insert variables into the kwargs?

**Comment by calvinchristopher** [comment]
Think I've got a working solution, I'll update after validation

**Comment by ktbyers** [comment]
Okay, sounds good.


Kirk

On Tue, Apr 5, 2016 at 12:42 PM, Calvin <notifications@github.com> wrote:

> Think I've got a working solution, I'll update after validation
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/188#issuecomment-205962973>
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by calvinchristopher** [comment]
Kirk, please close this out.

I got around this limitation, but it was quite a different approach. I'd be interested in hearing if you have a different approach.

End goal was to parse through a securecrt configuration file containing hostname and username for hundreds of devices, but no password (security reasons). here's how I got this to work:

csv file example
------

`session_name,hostname,protocol=SSH2,username,description`
`HOSTNAME-SW1,172.16.1.193,,cisco,HARDWARE`
`HOSTNAME-SW2,172.16.1.194,,cisco,HARDWARE`
`HOSTNAME-SW2,172.16.1.195,,cisco,HARDWARE`
`HOSTNAME-SW2,172.16.1.198,,cisco,HARDWARE`

------

script
------

`import csv, os.path`
`with open('device_info.csv', mode='r') as csvfile:`
`    reader = csv.DictReader(csvfile)`
`    username = raw_input('Please enter your username: \n')`
`    password = raw_input('Please enter your password: \n')`
`    for row in reader:`
`        start_time = datetime.now()  # grab a timestamps for additional information`
`        hostname = row['hostname']`
`        switch = {'device_type': 'cisco_ios', 'ip': hostname, 'username': username, 'password': password, 'verbose': False, }`
`        print switch`
`        ssh_session = ConnectHandler(**switch)`
`        hostname = ssh_session.find_prompt() `
...etc etc

**Comment by ktbyers** [comment]
@calvinchristopher Here is an example of how I would have probably done it.

https://github.com/ktbyers/pynet/blob/master/pyth_ans_ecourse/class4/ex5_netmiko.py

Note, you probably want to use 'getpass' to handle the password (so it is not echoed to the screen). See my link for an example of this.


Kirk
