### ISSUE TITLE
CiscoXrBase: Reduce the time duration for session preparation

### ISSUE THREAD

**Issue by taisasak** [ktbyers/netmiko#1882]
netmiko: 3.2.0
Cisco XR: 7.0.1

__[Problem Description]__

It takes long time (approx. 4.7 secs) until a new session preparation is completed by ConnectHandler().
I think this issue is not specific to CiscoXrBase but also applicable to other platforms calling BaseConnection::_test_channel_read() method.

I'd like to reduce this time duration and I could improve the behavior by my local patch, but I have a question before submitting a pull request.

```python
netconn = ConnectHandler(**device)
```
Please see the below CiscoXr syslog and netmiko logger for details.

- CiscoXr (syslog)

The below CiscoXr syslog says SSH connection itself is established at `19:12:15.922`.
```
RP/0/RP0/CPU0:2020 Aug 14 19:12:15.922 JST: SSHD_[68443]: %SECURITY-SSHD-6-INFO_SUCCESS : Successfully authenticated user 'cisco' from '10.71.38.195' on 'vty3'(cipher 'aes128-ctr', mac 'hmac-sha2-256')
```

- netmiko (logger)

The below netmiko logger says session_preparation() is completed at around `19:12:20.676`, which means it took about `4.754 secs` after a SSH connection is established.
```
2020-08-14 19:12:17.171 [   DEBUG] read_channel: 

RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-14 19:12:17.273 [   DEBUG] read_channel: 
2020-08-14 19:12:19.276 [   DEBUG] read_channel: 
2020-08-14 19:12:19.381 [   DEBUG] read_channel: 
2020-08-14 19:12:19.382 [   DEBUG] write_channel: b'\n'
2020-08-14 19:12:19.488 [   DEBUG] read_channel: 
RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-14 19:12:19.696 [   DEBUG] read_channel: 
2020-08-14 19:12:19.697 [   DEBUG] [find_prompt()]: prompt is RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-14 19:12:19.902 [   DEBUG] read_channel: 
2020-08-14 19:12:19.903 [   DEBUG] In disable_paging
2020-08-14 19:12:19.904 [   DEBUG] Command: terminal length 0

2020-08-14 19:12:19.905 [   DEBUG] write_channel: b'terminal length 0\n'
2020-08-14 19:12:19.906 [   DEBUG] Pattern is: RP/0/RP0/CPU0:NCS\-5501c\-ME04
2020-08-14 19:12:19.931 [   DEBUG] _read_channel_expect read_data: terminal length 0

2020-08-14 19:12:20.033 [   DEBUG] _read_channel_expect read_data: Fri Aug 14 19:12:19.798 JST

2020-08-14 19:12:20.138 [   DEBUG] _read_channel_expect read_data: RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-14 19:12:20.138 [   DEBUG] Pattern found: RP/0/RP0/CPU0:NCS\-5501c\-ME04 terminal length 0
Fri Aug 14 19:12:19.798 JST
RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-14 19:12:20.139 [   DEBUG] terminal length 0
Fri Aug 14 19:12:19.798 JST
RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-14 19:12:20.140 [   DEBUG] Exiting disable_paging
2020-08-14 19:12:20.141 [   DEBUG] write_channel: b'terminal width 511\n'
2020-08-14 19:12:20.142 [   DEBUG] Pattern is: RP/0/RP0/CPU0:NCS\-5501c\-ME04
2020-08-14 19:12:20.160 [   DEBUG] _read_channel_expect read_data: terminal width 511

2020-08-14 19:12:20.265 [   DEBUG] _read_channel_expect read_data: Fri Aug 14 19:12:20.025 JST
RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-14 19:12:20.266 [   DEBUG] Pattern found: RP/0/RP0/CPU0:NCS\-5501c\-ME04 terminal width 511
Fri Aug 14 19:12:20.025 JST
RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-14 19:12:20.676 [   DEBUG] read_channel: 
```

__[Troubleshoot]__

```python
class CiscoXrBase(CiscoBaseConnection):
    def establish_connection(self):
        """Establish SSH connection to the network device"""
        super().establish_connection(width=511, height=511)

    def session_preparation(self):
        """Prepare the session after the connection has been established."""
        self._test_channel_read()
        self.set_base_prompt()
        self.disable_paging()
        self.set_terminal_width(command="terminal width 511")
        # Clear the read buffer
        time.sleep(0.3 * self.global_delay_factor)
        self.clear_buffer()
```
After some code trace and experiment, I found the time duration could be reduced by the following enhancement.

- disable_paging() and set_terminal_width() can be removed when we calls establish_connection(width=511, height=0)
- _test_channel_read() always takes about 2 secs+ due to extra sleep(final_delay * delay_factor) in _read_channel_timing().
- _test_channel_read() can be replaced by read_until_pattern() with regular expression for CiscoXr prompt.
- set_base_prompt() can be removed if we set a prompt string directly to self.base_prompt.

__[Question]__

Would you think if it's ok for now to improve the behavior in CiscoXrBase only, even though this might be a common issue?

If yes, I'm going to submit a pull request only for CiscoXrBase changes.

**Comment by ktbyers** [comment]
Yes, I agree with this in general (i.e. that session_preparation needs to be sped-up in general to a very great extent in Netmiko--by a factor of 5).

I started doing a lot of work on this here:

https://github.com/ktbyers/netmiko/pull/1854/files

On your specific proposals for IOS-XR:

```
disable_paging() and set_terminal_width() can be removed when we calls establish_connection(width=511, height=0)
```

Does this work on a broad-range of IOS-XR platforms? What OS version did you test this on? I am not sure this fix is worth doing since newer session_preparation (in my PR) would be much more rapid (i.e. not sure the overhead time would be significant enough to justify the risk). 

Also we would need to put some command-in that we verify gets echoed/executed to ensure the state doesn't get out of sync. In other words, one problem that I have ran into a lot of times if Netmiko goes to fast is that it gets meaningfully ahead of the device (so verifying the command-echo of a command in session_preparation is a good way to ensure that doesn't happen).

```
_test_channel_read() always takes about 2 secs+ due to extra sleep(final_delay * delay_factor) in _read_channel_timing().
```

Maybe this just gets replaced by the command echo verification that we due for disable_paging() and/or set_terminal_width(). In other words, if we verify command echo on disable_paging(), then we are already ensuring a read is happening properly so the `_test_channel_read()` can be eliminated.


```
set_base_prompt() can be removed if we set a prompt string directly to self.base_prompt.
```

This I wouldn't do. It is too inconsistent with Netmiko's expected behavior and patterns and there are too many ways it can go wrong.

**Comment by taisasak** [comment]
@ktbyers 

> Does this work on a broad-range of IOS-XR platforms? What OS version did you test this on? I am not sure this fix is worth doing since newer session_preparation (in my PR) would be much more rapid (i.e. not sure the overhead time would be significant enough to justify the risk).

Yes, I tested on the below IOS-XR platforms and versions and it was all working. However, I haven't yet tested it on XR7 (which is a new IOS-XR software architecture running on Cisco 8000 and some NCS 540 platforms)

- NCS-5501 (7.0.1)
- ASR-9006 (6.5.1/64bit)
- ASR-9001 (5.3.3/32bit)

> Maybe this just gets replaced by the command echo verification that we due for disable_paging() and/or set_terminal_width(). In other words, if we verify command echo on disable_paging(), then we are already ensuring a read is happening properly so the _test_channel_read() can be eliminated.

I'm more concerned about removing _test_channel_read() method because it always takes more than 2 seconds. If the command echo verification is important, it means we have to issue at least one command during session preparation phase? I'm ok with leaving either of disable_paging() or set_terminal_width(). What I want to do is reducing the number of issued commands as many as possible.

FYI: By the way, the below is my trial path. This could reduce the time duration to less than 2 seconds when I tested it on my local testbed. (I'm not saying I want to commit the below patch. It's just for testing purpose only)

```python
diff --git a/netmiko/cisco/cisco_xr.py b/netmiko/cisco/cisco_xr.py
index ad945f5..843b251 100644
--- a/netmiko/cisco/cisco_xr.py
+++ b/netmiko/cisco/cisco_xr.py
@@ -6,14 +6,18 @@ from netmiko.cisco_base_connection import CiscoBaseConnection, CiscoFileTransfer
 class CiscoXrBase(CiscoBaseConnection):
     def establish_connection(self):
         """Establish SSH connection to the network device"""
-        super().establish_connection(width=511, height=511)
+        super().establish_connection(width=511, height=0)

     def session_preparation(self):
         """Prepare the session after the connection has been established."""
-        self._test_channel_read()
-        self.set_base_prompt()
-        self.disable_paging()
-        self.set_terminal_width(command="terminal width 511")
+        prompt_pattern = r"(?P<prompt>RP/[A-Z]*\d+/[A-Z]*\d+(?:/CPU0)?:[^(\s]+(?:\([^\s]+\))?)#"
+        output = self.read_until_pattern(pattern=prompt_pattern)
+        prompt_match = re.search(prompt_pattern, output.strip())
+        if prompt_match:
+            prompt = prompt_match.group('prompt')
+            self.base_prompt = prompt
+        else:
+            self.set_base_prompt()
         # Clear the read buffer
         time.sleep(0.3 * self.global_delay_factor)
         self.clear_buffer()
```

- CiscoXr (syslog)
```
RP/0/RP0/CPU0:2020 Aug 17 11:27:09.490 JST: SSHD_[66572]: %SECURITY-SSHD-6-INFO_SUCCESS : Successfully authenticated user 'cisco' from '10.71.38.195' on 'vty2'(cipher 'aes128-ctr', mac 'hmac-sha2-256')
```

- netmiko (logger)
```
2020-08-17 11:27:10.461 [   DEBUG] Pattern is: (?P<prompt>RP/[A-Z]*\d+/[A-Z]*\d+(?:/CPU0)?:[^(\s]+(?:\([^\s]+\))?)#
2020-08-17 11:27:10.729 [   DEBUG] _read_channel_expect read_data: 


2020-08-17 11:27:10.833 [   DEBUG] _read_channel_expect read_data: RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-17 11:27:10.834 [   DEBUG] Pattern found: (?P<prompt>RP/[A-Z]*\d+/[A-Z]*\d+(?:/CPU0)?:[^(\s]+(?:\([^\s]+\))?)# 

RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-17 11:27:11.241 [   DEBUG] read_channel:
```

**Comment by ktbyers** [comment]
I think we can get rid of the _test_channel_read().

I think both of the below will be required, I don't expect the overhead time is that much (but I don't know what is "much" in your context). I.E. I need both of these commands for the driver to execute sufficiently reliably.

```
disable_paging() or set_terminal_width(). 
```


Regards, Kirk

**Comment by ktbyers** [comment]
Sorry forgot about this part i.e. that these might be entirely controllable via terminal settings for IOS-XR:

```
super().establish_connection(width=511, height=0)
```

If that is the case, then we probably only need one command to verify the command echo is working (instead of doing the `_test_channel_read()`. The disable_paging() one is probably the simpler one to choose.

**Comment by ktbyers** [comment]
I probably wouldn't accept any of this as it is too complicated for long-term maintenance (remember Netmiko has ~75 different drivers) and I think the performance gains would be pretty small:

```
prompt_pattern = r"(?P<prompt>RP/[A-Z]*\d+/[A-Z]*\d+(?:/CPU0)?:[^(\s]+(?:\([^\s]+\))?)#"
+        output = self.read_until_pattern(pattern=prompt_pattern)
+        prompt_match = re.search(prompt_pattern, output.strip())
+        if prompt_match:
+            prompt = prompt_match.group('prompt')
+            self.base_prompt = prompt
```

This might be able to be removed or reduced:

```
         time.sleep(0.3 * self.global_delay_factor)
         self.clear_buffer()
```

The extra sleep might be redundant now with the `clear_buffer()` especially if we are doing command echo verification before this (on the disable paging).

**Comment by taisasak** [comment]
@ktbyers 

Thank you for your comments.  That would be great if both `_test_channel_read()` and extra sleep before `clear_buffer()` could be removed.

```python
diff --git a/netmiko/cisco/cisco_xr.py b/netmiko/cisco/cisco_xr.py
index ad945f5..493c821 100644
--- a/netmiko/cisco/cisco_xr.py
+++ b/netmiko/cisco/cisco_xr.py
@@ -10,12 +10,9 @@ class CiscoXrBase(CiscoBaseConnection):

     def session_preparation(self):
         """Prepare the session after the connection has been established."""
-        self._test_channel_read()
         self.set_base_prompt()
         self.disable_paging()
-        self.set_terminal_width(command="terminal width 511")
         # Clear the read buffer
-        time.sleep(0.3 * self.global_delay_factor)
         self.clear_buffer()

     def send_config_set(self, config_commands=None, exit_config_mode=False, **kwargs):
```
I modified the patch like above and verified it could also reduce the time duration a lot. Please see the below logs for details.


-  CiscoXr (syslog)
```
RP/0/RP0/CPU0:2020 Aug 18 15:25:53.038 JST: SSHD_[66111]: %SECURITY-SSHD-6-INFO_SUCCESS : Successfully authenticated user 'cisco' from '10.71.38.195' on 'vty1'(cipher 'aes128-ctr', mac 'hmac-sha2-256')
```

- netmiko (logger)
```
2020-08-18 15:25:53.112 [   DEBUG] read_channel: 
2020-08-18 15:25:53.113 [   DEBUG] write_channel: b'\n'
2020-08-18 15:25:53.217 [   DEBUG] read_channel: 

2020-08-18 15:25:53.218 [   DEBUG] read_channel: 
2020-08-18 15:25:53.218 [   DEBUG] write_channel: b'\n'
2020-08-18 15:25:53.323 [   DEBUG] read_channel: 


RP/0/RP0/CPU0:NCS-5501c-ME04#
RP/0/RP0/CPU0:NCS-5501c-ME04#
RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-18 15:25:53.525 [   DEBUG] read_channel: 
2020-08-18 15:25:53.526 [   DEBUG] [find_prompt()]: prompt is RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-18 15:25:53.728 [   DEBUG] read_channel: 
2020-08-18 15:25:53.729 [   DEBUG] In disable_paging
2020-08-18 15:25:53.730 [   DEBUG] Command: terminal length 0

2020-08-18 15:25:53.730 [   DEBUG] write_channel: b'terminal length 0\n'
2020-08-18 15:25:53.731 [   DEBUG] Pattern is: RP/0/RP0/CPU0:NCS\-5501c\-ME04
2020-08-18 15:25:53.756 [   DEBUG] _read_channel_expect read_data: terminal length 0

2020-08-18 15:25:53.860 [   DEBUG] _read_channel_expect read_data: Tue Aug 18 15:25:53.791 JST
RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-18 15:25:53.861 [   DEBUG] Pattern found: RP/0/RP0/CPU0:NCS\-5501c\-ME04 terminal length 0
Tue Aug 18 15:25:53.791 JST
RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-18 15:25:53.861 [   DEBUG] terminal length 0
Tue Aug 18 15:25:53.791 JST
RP/0/RP0/CPU0:NCS-5501c-ME04#
2020-08-18 15:25:53.862 [   DEBUG] Exiting disable_paging
2020-08-18 15:25:53.967 [   DEBUG] read_channel: 
```

> Yes, I tested on the below IOS-XR platforms and versions and it was all working. However, I haven't yet tested it on XR7 (which is a new IOS-XR software architecture running on Cisco 8000 and some NCS 540 platforms)

Regarding the above XR7 (new IOS-XR software  architecture), I checked with the XR code base and SSH server implementation seems to be same as other XR architectures (Evolved XR 64bit and Classic XR 32bit). I also verified the below control was also working well with Cisco 8000 in my local lab. It's not required anymore in this discussion, though.

```
super().establish_connection(width=511, height=0)
```

Thanks, Taisuke

**Comment by ktbyers** [comment]
This comment of mine:

```
I probably wouldn't accept any of this as it is too complicated for long-term 
maintenance (remember Netmiko has ~75 different drivers) and I think the performance gains
 would be pretty small:
```

was directed only at this one section of code pertaining to set_base_prompt()

```
prompt_pattern = r"(?P<prompt>RP/[A-Z]*\d+/[A-Z]*\d+(?:/CPU0)?:[^(\s]+(?:\([^\s]+\))?)#"
+        output = self.read_until_pattern(pattern=prompt_pattern)
+        prompt_match = re.search(prompt_pattern, output.strip())
+        if prompt_match:
+            prompt = prompt_match.group('prompt')
+            self.base_prompt = prompt
```

I am totally open to a PR/changes on the other items that we discussed.

I realized after the fact that my comment above was unclear as to what it applied to.


Regards,

Kirk

**Comment by taisasak** [comment]
@ktbyers 

FYI: I've just submitted a new PR  https://github.com/ktbyers/netmiko/pull/1889.

Thanks, Taksuke

**Comment by ktbyers** [comment]
Develop branch should have new performance improvements for IOS-XR.
