### ISSUE TITLE
Commit method should allow a regex terminating pattern

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1883]
In cases where you change the hostname, the standard terminating pattern might not work. Netmiko should allow as a method argument to commit() a way to specify a regex terminating pattern.

**Comment by veprimk** [comment]
For those who need this until the issue's been resolved use this workaround:

`from netmiko import ConnectHandler
junos_vmx = {
    'device_type': 'juniper_junos',
    'host': 'junos.ip',
    'username': 'youruser',
    'password': 'yourpass',
    'port': 22
}
hostname_input = input("Please enter the hostname you want to assign to device:")
netconn = ConnectHandler(**junos_vmx)
output = netconn.send_command('show configuration system host-name')
print(output)
print("Configuring something...")
netconn.send_config_set("set system location country-code GB", exit_config_mode=False)
print("Configuring hostname... and commiting at the same time")
netconn.send_config_set(["set system host-name " +  hostname_input, "commit"])
print("Causing a prompt reset...")
netconn.set_base_prompt()
print("Executing a show command to prove that it's working...")
output = netconn.send_command('show configuration system host-name')
print(output)
netconn.disconnect()`

Which when executed looks like:

`✦3 ❯ python junos_hostname.py
Please enter the hostname you want to assign to device:Router000001
host-name MyJunos0001;
Configuring something...
Configuring hostname... and commiting at the same time
Causing a prompt reset...
Executing a show command to prove that it's working...
host-name Router000001;`

**Comment by ktbyers** [comment]
Purging old issues...
