### ISSUE TITLE
Issue when configuring Juniper EX2300

### ISSUE THREAD

**Issue by kshymkiw** [ktbyers/netmiko#1884]
Hello,

I have an issue when I am trying to commit to a Juniper EX2300.  Not sure if this is because of the slow nature of the EX2300 Routing Engine, or if there is something else.

Here is the Script, which is very simple:

> from netmiko import ConnectHandler

> #### Define the Paramaeters for connecting to your device
> switch2 = {
	'device_type':	'juniper',
	'host':	'192.168.1.13',
	'username':	'user',
	'password':	'pass',
	'port':	'22',
}
> device = ConnectHandler(**switch2)

> ##### Define the config that you want to push
> config_commands = [ 'set interfaces ge-0/0/3 descriptiopn "Test Config"',
					'set interfaces ge-0/0/3 unit 0 family inet address 100.100.100.100/24']
output = device.send_config_set(config_commands, exit_config_mode=False)
print (output)

> output = device.commit()
print (output)

And here is the error:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 564, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "configchange.py", line 16, in <module>
    output = device.send_config_set(config_commands, exit_config_mode=False)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1782, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 641, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 574, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

I have tried global and non-global delay factors, which didn't make any difference.

**Comment by kshymkiw** [comment]
Just to add some more context - it seems once it gets into config mode, it stops and times out:

Aug 15 03:38:02  vSRX1 mgd[7708]: UI_AUTH_EVENT: Authenticated user 'user' assigned to class 'j-super-user'
Aug 15 03:38:02  vSRX1 mgd[7708]: UI_LOGIN_EVENT: User 'user' login, class 'j-super-user' [7708], ssh-connection '172.16.175.1 59327 172.16.175.131 22', client-mode 'cli'
Aug 15 03:38:06  vSRX1 mgd[7708]: UI_CMDLINE_READ_LINE: User 'user', command 'set cli complete-on-space off '
Aug 15 03:38:06  vSRX1 mgd[7708]: UI_CMDLINE_READ_LINE: User 'user', command 'set cli screen-length 0 '
Aug 15 03:38:06  vSRX1 mgd[7708]: UI_CMDLINE_READ_LINE: User 'user', command 'set cli screen-width 511 '
Aug 15 03:38:09  vSRX1 mgd[7708]: UI_CMDLINE_READ_LINE: User 'user', command 'configure '
Aug 15 03:38:09  vSRX1 mgd[7708]: UI_DBASE_LOGIN_EVENT: User 'user' entering configuration mode
Aug 15 03:38:31  vSRX1 mgd[7708]: UI_DBASE_LOGOUT_EVENT: User 'user' exiting configuration mode
Aug 15 03:38:31  vSRX1 mgd[7708]: UI_LOGOUT_EVENT: User 'user' logout

**Comment by ktbyers** [comment]
Can you include the Netmiko log for when it fails?

I assume you are using Netmiko 3.2.0?


Regards,

Kirk

**Comment by veprimk** [comment]
@kshymkiw  can you please try fixing the syntax for your first command in the list ```
config_commands = [ 'set interfaces ge-0/0/3 **descriptiopn** "Test Config"',
'set interfaces ge-0/0/3 unit 0 family inet address 100.100.100.100/24']
```
change it to : 
```
config_commands = [ 'set interfaces ge-0/0/3 **description** "Test Config"',
'set interfaces ge-0/0/3 unit 0 family inet address 100.100.100.100/24']
```

As that's not accepted by the juniper node. See below:

```
root@Router000001# set interfaces ge-0/0/3 descriptiopn"Test Config"
                                           ^
syntax error.
root@Router000001# set interfaces ge-0/0/3 descriptiopn"Test Config"
```
