### ISSUE TITLE
Accedian device SSH timeout from Jenkins but the same code works from bash.

### ISSUE THREAD

**Issue by dipankarshaw** [ktbyers/netmiko#1885]
hi @ktbyers ,

I am trying to sort out a problem at accedian SSH.
i have a python code, where i Connect 2 Cisco NCS device and 1 Accedian Device.
the flow of the code is like below
- code uses the log in details and creates the netmiko connection object for each of the 3 devices.
- using the Accdian object i log in to the Accedian node and get a Output and parse that output.
- Code create all the Config files via jinja templating.
- now code try to log in all 3 devices one by one and push the config( using the old connection objects)
- Cisco 1 and cisco 2 commit success.
- Accedian commit fails, below is the error message. 

to my surprize, i face this problem only when running the code from jenkins. 
Can you guide me how to sort out the problem.

if i run the exact same code from Linux Shell,"python3 CCA.py", the code works without any problem.

______________________________________________________________________________________________

+ who -u
colt123  tty1         2020-08-14 12:28  old         2157
+ python3 CCA.py

OS: Linux, 4.15.0-112-generic, unix; Tcl version: 8.5.19

SpirentTestCenter Automation Version: 4.70.9706.0000
Hlt Api (Ver. 4.67) was successfully loaded and initialized
Internal Version: 4.67GA.0116

Current OS: Linux,4.15.0-112-generic,#113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020; python version: 3.6.9
Connecting Tcl server via port 39409
Loading SpirentHltApi...
Loaded SpirentHltApi: STCSERVER_RET_SUCCESS:4.67

!
!!
************** Test FF type EP ************* 
!!!!!!
**** connection established with node AR15
**** connection established with node AR11
**** connection established with node LTS_144
****  Logged in node : LTS_144
****  persing completed on LTS_144
{'del_meg': 1, 'meg': 4, 'mep': 1, 'dmm': 1, 'slm': 1}
****  Logged in node : AR15
****  Configration completed on AR15
****  Logged in node : AR11
****  Configration completed on AR11
****  Logged in node : LTS_144
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CCA.py", line 80, in <module>
    result['FF'] = onnet_CCM_Y1564_CCA('F','F')
  File "CCA.py", line 38, in onnet_CCM_Y1564_CCA
    my_config.push_config()
  File "/var/lib/jenkins/workspace/CCA/csit/libraries/service.py", line 179, in push_config
    output = node['connect_obj'].send_config_set(f2)             
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1750, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Build step 'Execute shell' marked build as failure
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any

**Comment by ktbyers** [comment]
Can you include the Netmiko log in the failing case?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by dipankarshaw** [comment]
hi @ktbyers ,
 i used the cmd_verify = false and this solved my issue. wanted to Update you.
Many thanks for your response.
