### ISSUE TITLE
Read until prompt for send_command

### ISSUE THREAD

**Issue by asmaps** [ktbyers/netmiko#189]
I'm having issues with incomplete command outputs:
e.g. sometimes `sh run` takes very long to build, so I only have `Building configuration...` in my output. I'm using the send_command function on Cisco, Juniper and Arista. Now I saw, that you added a `read_until_prompt` function in 4343c98d993a94dddfcd1978f8f282a2ba6a3bfa. Is it possible to use this one somehow for send_command? I already set a higher `delay_factor` but sometimes it's still too slow. Reading until prompt would solve things I hope.

Regards

**Comment by ktbyers** [comment]
@asmaps Use send_command_expect() method. This will read until trailing prompt is detected.

output = net_connect.send_command_expect('show run')


It is better method for long-running commands.

**Comment by asmaps** [comment]
thx, will try

**Comment by ktbyers** [comment]
@asmaps Sounds good, let me know if you are still having issues. I recommend that you use Netmiko 0.4.2 (github master branch) as I have been working a lot on improving the timing/reliability of Netmiko.

**Comment by jamesbond-github** [comment]
> @asmaps Use send_command_expect() method. This will read until trailing prompt is detected.
> 
> output = net_connect.send_command_expect('show run')
> 
> It is better method for long-running commands.

Thank you very much ..... This Helps a LOT !!!
