### ISSUE TITLE
banner motd change failing on Juniper device

### ISSUE THREAD

**Issue by ibolt1** [ktbyers/netmiko#1890]
Good afternoon, I am new to programming and am very excited to learn about Netmiko.
I am trying to change the Banner Motd on more than 100 Juniper devices (RT and SWITCH) but it is giving me the following error.

File "02_Banner.py", line 38, in <module>
    output = net_connect.send_config_set(banner, exit_config_mode=False)   
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1782, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 641, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 575, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

The script is quite simple which I share. (change banner text)

```python
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import NetMikoAuthenticationException
from paramiko.ssh_exception import SSHException

IP_LIST_JUNIPER = open('eqjuniper')
for IP in IP_LIST_JUNIPER:
    dis = {
	'device_type': 'juniper',
    	'ip':   IP,
    	'username': 'juniper',
    	'password': 'juniper', 	
    }
    print ('\n### CONNECTING TO THE DEVICE' +'_'+ IP.strip() + '###\n')
    try:
        net_connect = ConnectHandler(**dis)
    except NetMikoTimeoutException:
        print ('\n###DISPOSITIVO INALCANZABLE .###\n')
        continue

    except NetMikoAuthenticationException:
        print ('\n### AUTHENTICATION FAILURE.###\n')
        continue
    except SSHException:
        print ('\n### Make sure SSH is enabled on the device.###\n')
        continue

    banner = ["set system login message '################################################################################\n#This system should be used business or for purposes       			#\n# It is mandatory to comply with all the           				#\n#requirements listed in the applicable security policy and only process         #\n#or store the data classes approved for this asset type. Use is subject         #\n.	 #################################################################################'"]

    output = net_connect.send_config_set(banner, exit_config_mode=False)   
    print(output)
```

I will be very grateful for your help

**Comment by veprimk** [comment]
Hi @ibolt1,

Try using host as key instrad of ip for the device definition dictionary:

```
dis = {
             'device_type': 'juniper',
             'host': IP,
             'username': 'juniper',
             'password': 'password',
         }
```
Kind regards,
Veprim

**Comment by ibolt1** [comment]
Thank you for your comment, but I don't think that's the problem since the connection on the computer was well established. The problem lies when you try to place the command to place the banner

**Comment by codekuu** [comment]
Hi @ibolt1!

Could you please provide logs from of the Juniper?
I would also like to ask why you use "exit_config_mode=False"?

**Comment by ktbyers** [comment]
It looks like it is probably failing on `cmd_verify` for some reason:

```
new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
```

You could probably do `cmd_verify=False` as an argument to send_config_set().

It might be interesting to dig into why it is failing in which case I need the Netmiko logs:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by ktbyers** [comment]
Have you tried to turn off `cmd_verify` for this banner command so you should be able to add the `cmd_verify=False` argument to `send_config_set()`

**Comment by ibolt1** [comment]
Hello @ktbyers  thank you very much for your comment and help, I have tried what you indicate but the problem continues.
When you enter the command on the computer, it works without problem that indicates that the command is correct.
Now when it appears to be presented with \ n in the Scrip, the argument is not recognized or not supported.

Regards

Thank you very much.

**Comment by ktbyers** [comment]
@ibolt1 You would need to post your updated code and updated exception message.

You also need to make sure you are using Netmiko 3.2.0

**Comment by ibolt1** [comment]
Hi @ktbyers 
I have the latest version of netmiko installed v3.2.0

CODIGO:
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import NetMikoAuthenticationException
from paramiko.ssh_exception import SSHException

IP_LIST_JUNIPER = open('juniper')
for IP in IP_LIST_JUNIPER:
    dis = {
	'device_type': 'juniper',
    	'ip':   IP,
    	'username': 'test',
    	'password': 'test1', 	
    }


    print ('\n### CONNECTING TO THE DEVICE' +'_'+ IP.strip() + '###\n')
    try:
        net_connect = ConnectHandler(**dis)
    except NetMikoTimeoutException:
        print ('\n### UNREACHABLE DEVICE.###\n')
        continue

    except NetMikoAuthenticationException:
        print ('\n### AUTHENTICATION FAILURE.###\n')
        continue
    except SSHException:
        print ('\n### Make sure SSH is enabled on the device.###\n')
        continue

    print ('\n##### INITIATING BANNER CONFIGURATION #####\n')

    banner = ['set system login message "######################################################################################################\n#This system should be used for conducting business or for purposes authorized by management.#\n#It is mandatory to comply with all the requirements listed in the applicable security policy and     #\n#only process or store the data classes approved for this asset type. Use is subject                  #\n#to audit at any time by management.				                              #\n#######################################################################################################"']

    output = net_connect.send_config_set(banner, cmd_verify=False, delay_factor=2)   
    print(output)

Juniper team result:
test@test1# show | compare 
[edit system login]
-   message " ";
+   message "###################################################################################################### ";

{master:0}[edit]


when it is presented with the argument \ n the message is cut and it does not continue with what else
thank you

**Comment by ibolt1** [comment]
Hi @ktbyers 
I have the latest version of netmiko installed v3.2.0

CODIGO:
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import NetMikoAuthenticationException
from paramiko.ssh_exception import SSHException

IP_LIST_JUNIPER = open('juniper')
for IP in IP_LIST_JUNIPER:
    dis = {
	'device_type': 'juniper',
    	'ip':   IP,
    	'username': 'test',
    	'password': 'test1', 	
    }


    print ('\n### CONNECTING TO THE DEVICE' +'_'+ IP.strip() + '###\n')
    try:
        net_connect = ConnectHandler(**dis)
    except NetMikoTimeoutException:
        print ('\n### UNREACHABLE DEVICE.###\n')
        continue

    except NetMikoAuthenticationException:
        print ('\n### AUTHENTICATION FAILURE.###\n')
        continue
    except SSHException:
        print ('\n### Make sure SSH is enabled on the device.###\n')
        continue

    print ('\n##### INITIATING BANNER CONFIGURATION #####\n')

    banner = ['set system login message "######################################################################################################\n#This system should be used for conducting business or for purposes authorized by management.#\n#It is mandatory to comply with all the requirements listed in the applicable security policy and     #\n#only process or store the data classes approved for this asset type. Use is subject                  #\n#to audit at any time by management.				                              #\n#######################################################################################################"']

    output = net_connect.send_config_set(banner, cmd_verify=False, delay_factor=2)   
    print(output)

Juniper team result:
test@test1# show | compare 
[edit system login]
-   message " ";
+   message "###################################################################################################### ";

{master:0}[edit]


when it is presented with the argument \ n the message is cut and it does not continue with what else
thank you

**Comment by ktbyers** [comment]
Purging old issues...
