### ISSUE TITLE
Add Netmiko integration to TTP

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#1894]

**Comment by tbotnz** [comment]
@ktbyers do you have any views on the solution for this already?
I am keen to contribute back but would be keen to hear your thoughts on below

- Would you be open to having another "index" file to match commands against templates (similar to that of ntc-templates) within netmiko ?
Couple of solution idea here:
 1. have some ```ttp/``` folder where filenames are $netmiko_driver_prefix_$command.ttp (the filename is then used to map to driver and command dynamically, though would only work for exact matches)
 2. some python lookup list or dict similar to  [{"driver":"cisco_ios","template":"/ttp/show_ver.tp","command_match":r"[sS][hH][oO][wW] [vV][eE][rR].*"}]
 3. use a similar format to the one used in ntc-templates

- With no "ntc-templates" equivalent template repo for ttp templates yet, would you just provide an empty place to load templates OR try and build a template repo within the netmiko project?

**Comment by ktbyers** [comment]
I have only looked at TTP a minimal amount.

With TTP is there any existing repository of templates (similar to ntc-templates or Genie)? From your above statements, it sounds like no. 

I would be interested in there being a template repository, but I don't want to maintain it. 

Maybe we can circle in the TTP maintainers and people that are active there and see if there is any interest in making a repository like this?

Yeah, my first thought (for how to build a template repository) would just be to copy the index idea from TextFSM/CLItable and reuse that (maybe even can use the same code or very similar code). Though probably consider writing the index in YAML.

If there is no template repository for TTP, then I would try to make it easy for Netmiko to bind to TTP for show command output, so something like:

```python
output = net_connect.send_command(command, use_ttp=True, ttp_template="my_template.ttp")
```

**Comment by tbotnz** [comment]
Have started working on #1962 which is almost complete, to implement basic functionality for this option

```output = net_connect.send_command(command, use_ttp=True, ttp_template="my_template.ttp")```

Do you want to vendor ttp or just have it as an optional extra similar to genie?

**Comment by ktbyers** [comment]
Yeah, I wouldn't want to vendor it so either a separate requirements-ttp.txt like I did for Genie. I only did that for TextFSM as TextFSM library broke (and still breaks Windows).

It looks your PR vendorred it which freaked me out at first :-)


Regards, Kirk

**Comment by tbotnz** [comment]
Np, yeah i actually did it both ways heh, will remove the vendored stuff tonight

**Comment by ktbyers** [comment]
Sounds good.

**Comment by tbotnz** [comment]
plz close meh
