### ISSUE TITLE
Brocade Fabric OS support

### ISSUE THREAD

**Issue by Rocking80** [ktbyers/netmiko#1901]
Just a quick question, Brocade FC switch is so popular and the most widely used platform on Brocade switches is Fabric OS (FOS).
Anybody can tell me why it is not in the support list (https://ktbyers.github.io/netmiko/PLATFORMS.html)?  Thanks.

```
Brocade_core_0101:tide> version
Kernel:     2.6.14.2
Fabric OS:  v8.1.2j
Made on:    Mon Nov 4 21:21:18 2019
Flash:      Thu Mar 5 22:15:20 2020
BootProm:   1.0.16
```

If I am going to use netmiko for FOS, is there any workaround for this? Thanks.

**Comment by ktbyers** [comment]
Drivers are generally created by the community...so if you want the driver, then you might need to build it.

The process for building a driver is detailed here:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md


Regards,

Kirk

**Comment by DanielWeeber** [comment]
I just created a PR for that.

https://github.com/ktbyers/netmiko/pull/2116

I need the function myself and wrote the code for it.
