### ISSUE TITLE
FortiOS Downgrade confirm Issue

### ISSUE THREAD

**Issue by Aeskithan** [ktbyers/netmiko#1903]
Hello,

I'm trying to downgrade a FWF-60E and i got an issue

I try to downgrade from 6.2.3 to 6.0.3
For upgrade from 6.0.3 to 6.2.3 no problem at all

You can find attach the process by [hand]
(url
[HandDowngradeProcess.txt](https://github.com/ktbyers/netmiko/files/5145228/HandDowngradeProcess.txt)
)
I use this 
[code.txt](https://github.com/ktbyers/netmiko/files/5145588/code.txt)

it go for this log
[log1.txt](https://github.com/ktbyers/netmiko/files/5145257/log1.txt)

This script and everything i tried at the moment never pass the second Y/N question
This operation will downgrade the current firmware version.
Do you want to continue? (y/n)

i also try to wait for "server" as pattern then burst the channel every second with "y" still not working (There's something like 7s between download confirmed as finished and the last question "Do you want to continue? (y/n)" )
On this program log i saw y coming before the Y/N question and after with 'Unknown action 0'

Terminal output
DL STARTED
##################################
Checking new firmware integrity ... pass
This operation will downgrade the current firmware version.
Do you want to continue? (y/n)

FWF60E-1115-M (global) #
#ENDING READ
y
Unknown action 0

FWF60E-1115-M (global) #

Any idea ?

**Comment by Aeskithan** [comment]
[code.txt](https://github.com/ktbyers/netmiko/files/5145586/code.txt)

**Comment by ktbyers** [comment]
This driver has changed a lot since this date so I am going to close this issue.
