### ISSUE TITLE
Huawei IndexError: string index out of range

### ISSUE THREAD

**Issue by m1009d** [ktbyers/netmiko#1905]
Hello @ktbyers ,
from time to time (seems like when my Huawei router is little bit slower than usual) I got this error:

```py
 Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir/plugins/tasks/networking/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection("netmiko", task.nornir.config)
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 294, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/inventory.py", line 345, in open_connection
    self.connections[connection].open(
  File "/usr/local/lib/python3.8/dist-packages/nornir/plugins/connections/netmiko.py", line 58, in open
    self.connection = ConnectHandler(**parameters)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/ssh_dispatcher.py", line 266, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 333, in _open
    self._try_session_preparation()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 756, in _try_session_preparation
    self.session_preparation()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/huawei/huawei.py", line 13, in session_preparation
    self.set_base_prompt()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/huawei/huawei.py", line 95, in set_base_prompt
    if not prompt[-1] in (pri_prompt_terminator, alt_prompt_terminator):
IndexError: string index out of range
```

I was trying to debug this and I added few print statement lines into the `netmiko/huawei/huawei.py`:

```py
        # log.debug("In set_base_prompt")
        delay_factor = self.select_delay_factor(delay_factor)
        print(f'delay_factor: {delay_factor}')
        print(f'Buffer before clear: {self.read_channel()}')
        self.clear_buffer()
        self.write_channel(self.RETURN)
        time.sleep(0.5 * delay_factor)

        prompt = self.read_channel()
        print(f'prompt: "{prompt}"')
```

When there is a failure indeed the `prompt` variable is empty ( `None` ):

```
delay_factor: 2
Buffer before clear: 
prompt: ""
```

Because I suspect a delay issue I added a little check and hard coded a 5s wait: 

```py
        if not prompt:
            print('No prompt, waiting another 5s')
            time.sleep(5)
            prompt = self.read_channel()
            print(f'prompt after 5s: {prompt}')
            if not prompt:
                raise ValueError('Empty prompt')
```

And it works, prompt was found:

```
delay_factor: 3
Buffer before clear: 
prompt: ""
No prompt, waiting another 5s
prompt after 5s: "<my_router>"
```

#### More info about my setup:
- netmiko==3.2.0

- I am using Nornir and it's plugin `netmiko_send_command`

- my Nornir timers are configured as followed:
```yml
  connection_options:
        netmiko:
            extras:
                use_keys: True
                ssh_strict: False
                timeout: 60
                session_timeout: 60
                auth_timeout: 60
                blocking_timeout: 60
                banner_timeout: 60
                global_delay_factor: 2
```

#### Proposed solution
- check if variable `prompt` is not empty before going further in the code (so `if not prompt[-1] ...` won't fail with `IndexError`).

- adjust `time.sleep(0.5 * delay_factor)` -  sometimes it is not the best way to configure the `delay_factor` to some high value, e.g. if there are multiple connections done at the same time (like via Nornir) - it can delay other operations when a router is really not reachable (and the connection should fait/timeout) -> this would cause long delay before proceeding to other tasks or even failures in other time depended tasks.

**Comment by ktbyers** [comment]
@dorko20 Thanks for all the good debugging info. So this is a "Huawei" device?

Can you include the debugging information on a failing case?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel


Kirk

**Comment by dorko20** [comment]
Hi @ktbyers ,
yes our Huawei routers are `Huawei NE40-X16` , pretty big ones, similar to Cisco 9922.

Unfortunately I can't do the debug because of privacy issues as the script is running on production routers.

**Comment by ktbyers** [comment]
```
check if variable prompt is not empty before going further in the code (so if not prompt[-1] ... won't fail with IndexError).
```

Yes, we could raise a different exception here that is clearer as far as what the error is.


I didn't really understand this as a proposed solution:

```
sometimes it is not the best way to configure the delay_factor to some high value, e.g. if there are multiple connections done at the same time (like via Nornir) - it can delay other operations when a router is really not reachable (and the connection should fait/timeout)
```

In general, that is the opposite of what you need to do i.e. the fix is very likely to slow things down even more.``

So it looks like the fix from your above details is to use a global_delay_factor of 3 or greater.


Can't really tell what is really going on without the aforementioned log file.


Kirk

**Comment by stvnkem** [comment]
Hello,

I work for Huawei and I often develop/run scripts on (mostly) CE devices, but there are some NE40E-X8A nodes too.
When do you encounter this issue: When there is a failure indeed the prompt variable is empty ( None ): ?

I hit this error often upon connection. I implemented a simple retry mechanism. You can do it upon sending a command too. Just retry when there is an expected output and it is not the correct: type, length, pattern.

Let me know if you need help.

**Comment by dorko20** [comment]
Hi @stvnkem ,  
thank you for your reply, I am using this workaround directly in the `Huawei.py` for now:  

```py
...
prompt = self.read_channel()

        if not prompt:
            time.sleep(5)
            prompt = self.read_channel()
            if not prompt:
                raise ValueError('Empty prompt')
...

```

This is working so far without any problem.

**Comment by ktbyers** [comment]
@stvnkem Any possibility you could the Netmiko log file for the failure case you mentioned:

```
I hit this error often upon connection.
```

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel


Regards, Kirk

**Comment by ktbyers** [comment]
I am going to close this as it doesn't look like there is any additional action to be taken.

If there is still something to do here, just re-open this issue.
