### ISSUE TITLE
Extra line is getting generated in output from netmiko

### ISSUE THREAD

**Issue by syamala-lasya** [ktbyers/netmiko#1913]
Hi,

I am facing one strange issue with netmiko , commands are being run but it is showing one extra line between each line.

I can see that in text editors like compare it /  Notepad++  while comparing logs.  That extra line is not generated via manual logs taken from putty.  

[OUTPUT_LINE ISSUE.txt](https://github.com/ktbyers/netmiko/files/5155198/OUTPUT_LINE.ISSUE.txt)

What could be the reason and how to solve this problem.?  Please suggest.

Thanks,
Shyam

**Comment by ktbyers** [comment]
I need your Netmiko code also.

Which Netmiko device_type are you using?

**Comment by syamala-lasya** [comment]
I am using different device types like :   cisco_ios,  'cisco_xe,  'cisco_xr,  'cisco_asa,  ,  juniper_junos,  cisco_wlc

using netmiko version :  3.2.0

below is the code :

from netmiko import ConnectHandler

Cisco_RS= { 'device_type': 'cisco_ios' , 'ip' : "192.168.1.10", 'username' : 'admin' ,'password' : "xxxx", 'secret' :  "xxxx",'banner_timeout':6, 'fast_cli' : True}

dev_session = ConnectHandler(**Cisco_RS)
time.sleep(0.6)
pmpt= Temp_session.find_prompt(delay_factor=3 )

result = dev_session.send_command_timing("show run",delay_factor= 2,strip_prompt=False,strip_command=False)


Thanks,
Syam
