### ISSUE TITLE
session_log only save first session log

### ISSUE THREAD

**Issue by jacquen** [ktbyers/netmiko#1923]
Hi, Kirk

When tried connect to multi device in a loop and define session_log in device, seems it only save first session into log file, is this normal?

Part of my code like this

```
 for host in host_root["host_list"]:
        platform = platform_map[host["platform"]]
        print(f"Connect to {host['name']}")

        devices = {
            'device_type': platform,
            'host': host["name"],
            'username': 'test',
            'password': password,
            'session_log': 'log.txt'
        }
```

**Comment by ktbyers** [comment]
Yes, you would typically have a per-device session_log i.e. use something like the hostname as part of the filename. Alternatively, if you want a single file, you can change the session log mode to append:

```
session_log_file_mode="append"
```
