### ISSUE TITLE
Netmiko Error "netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed."

### ISSUE THREAD

**Issue by waqas-iqbal** [ktbyers/netmiko#1937]
G'Day Champions,

I've started learning Network Automation using Python and need some assistance. I've checked out existing issues here, but couldn't find a solution to my problem. Please help me out. I'd appreciate if can explain in details as I'm beginner:
[Devices_Config_Script.txt](https://github.com/ktbyers/netmiko/files/5213461/Devices_Config_Script.txt)
[Devices_IP_List.txt](https://github.com/ktbyers/netmiko/files/5213462/Devices_IP_List.txt)

**When I run below code:**

`from netmiko import ConnectHandler
from getpass import getpass

with open('Devices_IP_List.txt') as IP_List:
    for IP in IP_List:
        SW = {
			'ip': 'IP',
			'username': 'admin',
			'password': 'cisco',
			'device_type': 'cisco_ios',
            }

        print ('Connecting to the Device ' + IP)
        net_connect = ConnectHandler(**SW)
		
        with open('Devices_Config_Script.txt') as Config_Script:  
            config_commands = Config_Script.read()
        
        output = net_connect.send_config_set(config_commands)
        print(output)

        output = net_connect.send_command('show ip int brief')
        print(output)`

**I got following Error:**

Traceback (most recent call last):
  File "C:\Users\waqas\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 915, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\waqas\AppData\Roaming\Python\Python38\site-packages\paramiko\client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "C:\Users\waqas\AppData\Roaming\Python\Python38\site-packages\paramiko\client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "C:\Program Files (x86)\Python38-32\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\08_SSH of Multiple devices using Text File_Netmiko.py", line 14, in <module>
    net_connect = ConnectHandler(**SW)
  File "C:\Users\waqas\AppData\Roaming\Python\Python38\site-packages\netmiko\ssh_dispatcher.py", line 298, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\waqas\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 341, in __init__
    self._open()
  File "C:\Users\waqas\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 346, in _open
    self.establish_connection()
  File "C:\Users\waqas\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 937, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios IP:22

Can you please advise what's required to ammend the code.

Look forward to hear soon.

Thanks

**Comment by ktbyers** [comment]
@waqas-iqbal In this code:

```python
SW = {
    'ip': 'IP',
    'username': 'admin',
    'password': 'cisco',
    'device_type': 'cisco_ios',
}
```

You passed in a string named "IP" and not the IP variable.


Regards, Kirk

**Comment by jogindergur** [comment]
Hello @waqas-iqbal 

try 'ip': IP.strip()

in your file there are blank spaces

**Comment by kumaresansp** [comment]
Hello @jogindergur 

i am also facing the same issue , Even we add the IP.strip() also same issue Please help us this issue 

from netmiko import ConnectHandler
IP_LIST = open('devices.txt')
for IP in IP_LIST:
    RTR = {
        'ip':IP.strip(),
        'username': 'kumar',
        'password': 'kumar@25',
        'device_type': 'cisco_ios',
        }
    print ("Connecting to the devieces " + IP) 
    net_connect = ConnectHandler(**RTR)

    with open('config.txt') as CONFIG_LINES:
        CON = CONFIG_LINES.read()
    output = net_connect.send_config_set(CON)
    print(output)

    output = net_connect.send_command('show ip int brief')
    print(output)


Traceback (most recent call last):
  File "C:\Users\Kumar\Desktop\Paramiko\Netmiko\Open_list.py", line 11, in <module>
    net_connect = ConnectHandler(**RTR)
  File "C:\Users\Kumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 312, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\Kumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\cisco\cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "C:\Users\Kumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 346, in __init__
    self._open()
  File "C:\Users\Kumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 351, in _open
    self.establish_connection()
  File "C:\Users\Kumar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\netmiko\base_connection.py", line 942, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 192.168.0.11:22

**Comment by jogindergur** [comment]
@kumaresansp sometimes library do connect with your device. To resolve that issue you should try to change your virtual environment. Many times I have changed my virtual environment because of timeout exception. Let me know if you still face same issue.

**Comment by kumaresansp** [comment]
@jogindergur The only problem is when i open the file using document getting the error and i'm not see the issue when i give Hardcode Like IP address and configuration part

**Comment by jogindergur** [comment]
@kumaresansp share your file as it is. - Let check what will be the issue.

**Comment by kumaresansp** [comment]
Here you go 👍 

i have two file one file devices IP address and another file creating config loop interface

**devices.txt** - 192.168.0.11
**config.txt** -
int lo99
ip add 99.99.99.99 255.255.255.255
no shut
end

**Comment by kumaresansp** [comment]
@jogindergur  Here i have attached the file logs

**Comment by kumaresansp** [comment]
@jogindergur  Did you finding anything ?

**Comment by jogindergur** [comment]
@kumaresansp attach your files as it is. not content.

**Comment by kumaresansp** [comment]
@jogindergur Here you go Files and pgm 

from netmiko import ConnectHandler
IP_LIST = open('devices.txt')
for IP in IP_LIST:
RTR = {
'ip':IP.strip(),
'username': 'kumar',
'password': 'kumar@25',
'device_type': 'cisco_ios',
}
print ("Connecting to the devieces " + IP)
net_connect = ConnectHandler(**RTR)

with open('config.txt') as CONFIG_LINES:
    config= CONFIG_LINES.read()
output = net_connect.send_config_set('config.txt')
print(output)

output = net_connect.send_command('show ip int brief')
print(output)

[config.txt](https://github.com/ktbyers/netmiko/files/5707058/config.txt)
[devices.txt](https://github.com/ktbyers/netmiko/files/5707059/devices.txt)

**Comment by ktbyers** [comment]
@sarvjeetbhardwaj You should open a new issue. This issue is old now.
