### ISSUE TITLE
Netmiko 3.3.0 breaking IOS command to 2 commands.

### ISSUE THREAD

**Issue by besdollma** [ktbyers/netmiko#1939]
Upgraded today to 3.3.0 for the Cisco IOS, IOS-XE performance improvement and I noted my script broke.
The part that breaks is doing the following:

```
dg_add = self.ssh.send_command("show ip default-gateway")
cmd = f"show ip arp {dg_add}"
result = self.ssh.send_command(cmd, use_textfsm=True)
```

The traceback goes like this:
```
Traceback (most recent call last):
File "..\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
File "...\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "...\netmiko\base_connection.py", line 567, in _read_channel_expect
   new_data = self.remote_conn.recv(MAX_BUFFER)
File "...\paramiko\channel.py", line 701, in recv
   raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

# Hiding some irrelevant details here
   result = self.ssh.send_command(cmd, use_textfsm=True)
File "...\netmiko\utilities.py", line 363, in wrapper_decorator
    return func(self, *args, **kwargs)
File "...\netmiko\base_connection.py", line 1447, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
File "...\netmiko\base_connection.py", line 644, in read_until_pattern
     return self._read_channel_expect(*args, **kwargs)
File "...\netmiko\base_connection.py", line 577, in _read_channel_expect
   raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```

Looking at the log I see the following (sorry for hiding the addresses)
```
Switch#show ip default-gateway
x.x.x.x
Switch#show ip arp
Protocol  Address    Age (min).    Hardware Addr   Type   Interface
Internet    z.z.z.z       -       yyyy.yyyy.yyyy   ARPA   VlanVVV
Internet    x.x.x.x       0       wwww.wwww.wwww   ARPA   VlanVVV
Switch#x.x.x.x
Trying x.x.x.x ...
```
The script runs on a few hundred devices on parallel, precisely with `apply_async` and uses 64 threads. I went down to 32 threads cause I though i was stressing it, but still having the same problem.

The command I send to the switch is `show ip arp x.x.x.x` and the switch is executing two different commands, `show ip arp` and then the address as a command. 
Before this I was running 3.1.1 with 64 threads and it was working fine. 
Part of the devices work fine (no exception) and part of them have this exception. In two different runs, different devices crash.
Any help would be appreciated. 
Thanks

**Comment by besdollma** [comment]
Performing `dg_add.strip()` solved this.
I don't know what changed through out the versions that now `show ip default-gateway` returns a newline before the default gateway.

**Comment by ktbyers** [comment]
@besdollma I think you were probably getting a bit lucky that there wasn't a newline in the original output (in earlier Netmiko). From looking at what your output is, I would expect there probably should be a newline there.

I.E. it was probably a minor Netmiko bug that was causing there not to be a newline.

This is definitely an area I have been making a lot of changes so it doesn't surprise me that this changed.


Regards, Kirk

**Comment by bdollma** [comment]
Hi Kirk, 
Thanks for the response. 
Striping the whitespaces was not my first approach at debugging since it happens to only a part of the devices. 
I strongly doubt that the IOS returns a newline at the beginning to part of the devices so I suppose it is because of Netmiko? 
Thanks
