### ISSUE TITLE
Handling of multiple SSH Connections

### ISSUE THREAD

**Issue by jogindergur** [ktbyers/netmiko#1941]
Hello,

I'm using Netmiko for Huawei_SmartAX. With Netmiko I'm continuously fetching every ONT status in a loop. I'm running two threads to do my tasks. Everything is fine, but when I try to add a worker thread I need to create a new SSH connection for that, I want to know how can I handle multiple SSH connections in efficient way for a single Huawei_SmartAX or can I perform multiple tasks in parallel using single SSH connection. All suggestions are welcomed.

**Comment by ktbyers** [comment]
So you want multiple simultaneous SSH connections to a single Huawei device?

Does the Huawei device even allow concurrency on it (i.e. if you execute two separate long-running commands in separate SSH windows does it allow them to execute concurrently or does one block until the other one is done).

I generally wouldn't try to do that (multiple concurrent connections to the same device), but it is just a standard threading solution (if Huawei supports it). Alternatively you could look to use Nornir + Netmiko.

Here is an example using a ProcessorPool, but you could just swap that out with a thread pool:

https://github.com/ktbyers/pyplus_course/blob/master/class10/collateral/CF_PROCESSES/ssh_procs_simple.py

**Comment by jogindergur** [comment]
Thanks for reply.

I go through the link you have shared. In this link only one connection is used in every pool. In my case when I use one SSH connection for multiple tasks it raise error but when I use separate SSH connection for each thread then program runs smoothly. 

The main issue I'm facing is that how can I handle multiple connection with messing up. Currently I have created a SSHHandler class to do that: 


```
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException, NetMikoAuthenticationException


class SSHHandler:

    def __init__(self):
        self.ready = False
        self.use = False
        self.ssh = None

    def get_ssh(self, address):
        try:
            ssh = ConnectHandler(**address)
            self.ready = True
            ssh.enable()
            ssh.config_mode()
        except NetMikoTimeoutException:
            print('Time Out.')
        except NetMikoAuthenticationException:
            print('Unable to authenticate')

        return ssh

    def is_ready(self):
        return self.ready

```

Is it enough?
