### ISSUE TITLE
Generating crypto key leads to timeout or value error

### ISSUE THREAD

**Issue by pjamerson** [ktbyers/netmiko#1942]
Hello, pulling my hair out trying to find out how to have netmiko configure the crypto key during a device build. Every time I send "crypto key generate rsa modulus 4096" there is going to be some form of delay in response depending on the device it could be 10 sec to over 2 minutes. Every iteration I have tried has failed.

`self.configApply = net_connect.send_config_set("crypto key generate rsa modulus 4096", delay_factor=4, cmd_verify=False)`
**^This pushes the config commands as desired but ultimately leads to "Timed-out reading channel, data not available."**

`self.configApply = net_connect.send_config_set("crypto key generate rsa modulus 4096", cmd_verify=False)`
**^This pushes the config commands as desired but ultimately leads to "Timed-out reading channel, data not available."**

`self.configApply = net_connect.send_command("conf t")
                    self.configApply = net_connect.send_command_timing(
                        command_string="crypto key generate rsa modulus 4096",
                        strip_prompt=False,
                        strip_command=False
                    )`
**^Leads to a timeout "Search pattern never detected in send_command_expect:"**

`self.configApply = net_connect.send_command("conf t")
                    self.configApply += net_connect.send_command(
                        command_string="crypto key generate rsa modulus 4096",
                        strip_prompt=False,
                        strip_command=False,
                        delay_factor=2
                    )`
**^Leads to a timeout "Search pattern never detected in send_command_expect:"**

`self.configApply = net_connect.send_command("conf t")
                    self.configApply += net_connect.send_command( 
                        command_string="crypto key generate rsa modulus 4096",
                        expect_string=r"#",
                        strip_prompt=False,
                        strip_command=False
                    )`
^Leads to a timeout "Search pattern never detected in send_command_expect:"

`self.configApply = net_connect.config_mode("crypto key generate rsa modulus 4096", pattern="#")`
**^Leads to "Failed to enter configuration mode."**

Help? I cannot seem to find any other support issues with this and everything relating to delay or waiting for a response only has to do with enable mode level commands not global config level commands.

**Comment by haneyf** [comment]
hi, did you find the solution for this? thanks

**Comment by ktbyers** [comment]
@haneyf I don't think there is really any issue here, you just have to handle the multiline prompting correctly. See:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-expect_string

Or alternatively:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-timing

Let me know if you are still having issues.
