### ISSUE TITLE
Commit on Palo Alto does not support commit messages

### ISSUE THREAD

**Issue by hkam40k** [ktbyers/netmiko#1943]
Hello,

The ``PaloAltoPanosBase.commit()`` method does not currently accept a message as a parameter, even though the vendor should support it. Has this been dropped for a particular reason? Would a PR that adds message as a new keyword-arg be appreciated?

Regards.

**Comment by ktbyers** [comment]
Sure go for it...try to follow the  pattern used in either IOS-XR or Junos drivers.

Regards,

Kirk
