### ISSUE TITLE
Socket is closed - pattern never detected

### ISSUE THREAD

**Issue by yanover** [ktbyers/netmiko#1948]
Hey guys, 

I'm working with Cisco devices to retrieve thousands of device's information. My script worked perfectly from my environement development but, now in production I've a few error messages in my logs that I don't know how to fix.

Here's a part of my log file

```
nell-ce1#
21-09-2020 22:55:42 [netmiko] DEBUG read_channel: 
21-09-2020 22:55:42 [netmiko] DEBUG write_channel: b'\n'
21-09-2020 22:55:42 [netmiko] DEBUG read_channel: 
nell-ce1#
21-09-2020 22:55:42 [netmiko] DEBUG read_channel: 
21-09-2020 22:55:42 [netmiko] DEBUG [find_prompt()]: prompt is nell-ce1#
21-09-2020 22:55:42 [netmiko] DEBUG read_channel: 
21-09-2020 22:55:42 [netmiko] DEBUG write_channel: b'sh run | inc snmp-server location\n'
21-09-2020 22:55:42 [netmiko] DEBUG Pattern is: sh\ run\ \|\ inc\ snmp\-server\ location
21-09-2020 22:55:42 [netmiko] DEBUG _read_channel_expect read_data: s
21-09-2020 22:55:42 [netmiko] DEBUG _read_channel_expect read_data: h run | inc
21-09-2020 22:55:42 [netmiko] DEBUG _read_channel_expect read_data:  snmp-serv
21-09-2020 22:55:42 [netmiko] DEBUG _read_channel_expect read_data: er locati
21-09-2020 22:55:42 [netmiko] DEBUG _read_channel_expect read_data: o
21-09-2020 22:55:42 [netmiko] DEBUG _read_channel_expect read_data: n

21-09-2020 22:55:42 [netmiko] DEBUG Pattern found: sh\ run\ \|\ inc\ snmp\-server\ location sh run | inc snmp-server location

21-09-2020 22:55:42 [netmiko] DEBUG read_channel: 
21-09-2020 22:55:42 [netmiko] DEBUG read_channel: 
21-09-2020 22:55:42 [netmiko] DEBUG read_channel: 
21-09-2020 22:55:42 [netmiko] DEBUG read_channel: 
===> It sends break line 600 times ...
21-09-2020 22:55:52 [netmiko] DEBUG read_channel: 
21-09-2020 22:55:52 [netmiko] DEBUG read_channel: 
21-09-2020 22:55:52 [netmiko] DEBUG read_channel: 
21-09-2020 22:55:52 [root] ERROR An unknown error occured while processing callstack : socket is closed
```

My development environment is running under Windows and all the connections are made throw VPN. The production server is running Ubuntu 18.04 and is located inside the target network, I was thinking that maybe, cisco devices are responding too quickly ..

Is there a way to fix this ? 

That's my send_command function, I do nothing special on it :
```
def send_command(self, cmd):
    return self.handler.send_command(cmd)    
```

[EDIT]

I've new information :
I changed my exception handling to display the right error message, and there it is :
```
22-09-2020 13:51:19 [root] ERROR An error occurred while sending command to : xxx.xxx.xxx.xxx: Search pattern never detected in send_command_expect: nell\-ce1\#
```

Maybe I should make use of the send_command_expect() or delay_factor ? 

The error type is still raised by the socket.error except

[EDIT]

I'm facing this issue in two nodes, I've fixed this situation on one of them by changing the delay_factor to 2. Still, one of my device return this message "Search pattern never detected", even with a delay_factor with 100 as value.

I scan over 600 devices, I cannot figure out why only this device has this problem. I've tried to run the command directly from the prompt and it takes approximately 11 second to respond, but it responds.

The command is "show run | inc snmp-server location", this device is not yet configured and is supposed to return an empty result.

Please any help would be very appreciated !

**Comment by ktbyers** [comment]
Can you post the exception you get on the failing device (full exception stack which might require you to remove any try/except i.e. make sure you aren't hiding the original error)?

Also which version of Netmiko are you using?

**Comment by yanover** [comment]
Hey ktbyers, thank you very much for your time.

After reading a little more of the documentation, I found the parameter max_loops, yesterday evening I changed it in my ssh class.

The information that failed before was successfully retrieved with this new version. Here is my function : 
```
def send_command(self, cmd):
    return self.handler.send_command(cmd, delay_factor=3, max_loops=1000)
```

Just to be sure that I understand it correctly, this new implementation will not affect the global running time, right ? It will just wait longer when the prompt is not answering under a specific amount of time, right ?

Thank you so much !

**Comment by ktbyers** [comment]
The above arguments `delay_factor=3` and max_loops=1000 should wait 600 seconds (roughly) before it gives up and generates an error.

It should not affect devices that finish normally i.e. Netmiko will recognize they completed and move on; it should really only affect devices that are taking longer of failing for some reason.
