### ISSUE TITLE
ValueError: Router prompt not found: on netmiko 3.3.0.

### ISSUE THREAD

**Issue by Yathirajkrs** [ktbyers/netmiko#1949]
Hi,

I have two devices one is MAC and another RHEL.

I am trying to execute simple test script to get the 'sh clock' output.

Script - 
device = {
        'device_type': 'cisco_ios',
        'ip': ip,
        'username': username,
        'password': password,
        'secret': password,
    }
    net_connect = ConnectHandler(**device)
    net_connect.enable()
    cmd = "sh clock"
    output = net_connect.send_command(cmd)
   print(output)

I am facing below issue :

Above script works fine on my MAC which has following versions:
python - Python 3.7.4
netmiko - 3.1.0

I am getting ValueError while running same script on RHEL which has following versions:
python - Python 3.6.8
netmiko - 3.3.0.

Below is the error i am getting:

 net_connect = ConnectHandler(**device)
  File "/usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 302, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 344, in __init__
    self._open()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 350, in _open
    self._try_session_preparation()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 775, in _try_session_preparation
    self.session_preparation()
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco/cisco_ios.py", line 24, in session_preparation
    self.set_base_prompt()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1141, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: 'Tue Sep 22 03:38:42.923 CDT'

**Comment by Yathirajkrs** [comment]
I have tested on another RHEL server which have same python version and it worked there.
python - Python 3.6.8
netmiko - 3.1.1

But i am facing issue with the newer netmiko 3.3.0 version. 

Request to help me.

**Comment by ktbyers** [comment]
Can you include the Netmiko log file:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

This is for the failing Netmiko 3.3.0 case.


Also are you connecting to a real-physical device or a virtual device?


Kirk

**Comment by Yathirajkrs** [comment]
[test.log](https://github.com/ktbyers/netmiko/files/5273844/test.log)
Uploaded the log file.

Connecting source Servers are VM's.
Connecting destinations device is router.

**Comment by Yathirajkrs** [comment]
@ktbyers,
Do we have any update on above issue.

**Comment by ktbyers** [comment]
Log file has the following:

```
DEBUG:paramiko.transport:starting thread (client mode): 0xc31686a0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
```

I would try increasing the `banner_timeout` argument to Netmiko and see if that helps.

The log error is not consistent with the original exception stack trace posted, however.
