### ISSUE TITLE
version 0.4.3 send_config_set exception

### ISSUE THREAD

**Issue by vinkp** [ktbyers/netmiko#195]
Hi, 
The latest version gives exception while using send_config_set function when i used with a Cisco 4948 switch. Exception output is "netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available." from the function "read_until_pattern" in module "base_connection.py"

Working on to identify the reason behind the exception. If anyone knows better please update/resolve the issue..

PS: The older version 0.3.4 doesn't give any problem.

Thanks 
Vinod

**Comment by ktbyers** [comment]
@vinkp What were you changing in your send_config_set?

The above is failing looking for the trailing router prompt (i.e. it didn't find the router prompt before the timeout which is set to 8 seconds)

One situation where this would happen is if your config change modified the router hostname (since that changes the router trailing prompt).

**Comment by ktbyers** [comment]
@vinkp Can you send over what you were changing in your send_config_set? Strip out anything that is confidential. It will be hard for me to resolve this issue without that information.

**Comment by vinkp** [comment]
Hi Kirk, 
Sorry for the delay.. I was trying to send some basic standard access list change into the IOS switches. The script is working fine with Netmiko 0.3.4 version though, So I've completed the task with older version. 

I had used Python 2.7 in Debian importing netmiko 0.4.3
Only this "send_config_set" function failed. Didn't get a chance to re create the issue again. I'll try to test it again and update you.. 
Thank you

**Comment by ktbyers** [comment]
@vinkp Yes, please post your code if you can (minus passwords anything else that is confidential). What type of IOS switches were they?

Also I would be interested in seeing the error.

This will help me improve the quality of the newer release.

**Comment by ktbyers** [comment]
Need additional information on why this failed.
