### ISSUE TITLE
OSError: Search pattern never detected in send_command_expect: labrouter#

### ISSUE THREAD

**Issue by navnshar** [ktbyers/netmiko#1950]
Hi,

**Context:**
I am getting "Search pattern never detected in send_command_expect: labrouter#" error while copying the file on the Cisco IOS router using TFTP(the file copy operation does succeed, however wth the error as mentioned in the subject line). When I use the shortcode it works perfectly fine, however, with bigger code, it doesn't work and always gives the error mentioned in the subject line.  I have already tried adjusting the delay factor but no luck. Could you please help me to identify the issue?

**Setup:**
Full script(non-working)
==========
import netmiko
import re
import time
import xlrd
from getpass import getpass
from datetime import datetime
from netmiko import ConnectHandler

# file location
loc = "C:\VG_list\List.xlsx"

# open file
xfile = xlrd.open_workbook(loc)
sheet = xfile.sheet_by_index(0)

username = input("Enter the username: ")
password = getpass("Enter the password: ")
delay_value = input("Enter the delay value: ")

for x in range(sheet.nrows):

    host = sheet.cell_value(x, 1)
    ip = sheet.cell_value(x, 0)
    
    try:
        my_device_ssh = { 
        "device_type" : "cisco_ios", 
        "ip": ip,
        "username": username,
        "password": password,
        "session_log": 'C:\LAB_HC\log.txt'
        }
        connection = ConnectHandler(**my_device_ssh)

    except:
        #Here we are saying "if ssh failed, TRY telnet"

        try:
            my_device_telnet = { 
            "device_type" : "cisco_ios_telnet", 
            "ip": ip,
            "username": username,
            "password": password,
            "port": '23',
            "global_delay_factor": 5,
            "session_log": 'C:\LAB_HC\log.txt'
            }

            connection = ConnectHandler(**my_device_telnet)
        except:
            print("Unable to connect!")
            connection.disconnect()
        
    flash = connection.send_command('show flash:')
    print(flash)
    result = re.findall("(\d\d+\sbytes)", flash)
    size1 = result[0]
    final = re.findall("(\d\d+)", size1)
    size = final[0]

    print('The current available flash size is ' + size + ' bytes')
    print('Comparing it with the required flash size')

    required_space = '125000000'

    if int(size) < int(required_space):
        print("Flash size not sufficient for upgrade, PLease free up the space and try again")
        connection.disconnect()
    else:
        print("Size is sufficient for an upgrade")

    try:
        version = connection.send_command('show version')
        print(version)
    except:
        result = re.findall("(\wISCO\w+)", version)
        value = result[0]
        print('The router model is ' + value)

    #For router model 2900 & 3900:
        
        if value == 'CISCO2951':
            print("Proceed with the copy of file into flash")
            start_time = datetime.now()
            cmd = 'copy tftp://10.10.10.10/c2951-universalk9-mz.SPA.157-3.M6.bin flash:'
            output = connection.send_command(
                cmd,
                expect_string=r'Destination filename [c2951-universalk9-mz.SPA.157-3.M6.bin]?'
            )
            output += connection.send_command(
                '\n',
                expect_string=r'labrouter#',
                delay_factor=int(delay_value)
            )
            end_time = datetime.now()
            print()
            print(output)
            print()
            print("File copied succesfully on " + host)
        

        elif value == 'CISCO2921':
            print("Proceed with the copy of file into flash")
            start_time = datetime.now()
            cmd = 'copy tftp://10.10.10.10/c2900-universalk9-mz.SPA.157-3.M6.bin flash:'
            output = connection.send_command(
                cmd,
                expect_string=r'Destination filename [c2900-universalk9-mz.SPA.157-3.M6.bin]?'
            )
            output += connection.send_command(
                '\n',
                expect_string=r'labrouter#',
                delay_factor=int(delay_value)
            )
            end_time = datetime.now()
            print()
            print(output)
            print()
            print("File copied succesfully on " + host)

        elif value == 'CISCO2901':
            print("Proceed with the copy of file into flash")
            start_time = datetime.now()
            cmd = 'copy tftp://10.10.10.10/c2900-universalk9-mz.SPA.157-3.M6.bin flash:'
            output = connection.send_command(
                cmd,
                expect_string=r'Destination filename [c2900-universalk9-mz.SPA.157-3.M6.bin]?'
            )
            output += connection.send_command(
                '\n',
                expect_string=r'labrouter#',
                delay_factor=int(delay_value)
            )
            end_time = datetime.now()
            print()
            print(output)
            print()
            print("File copied succesfully on " + host)

        elif value == 'CISCO2911':
            print("Proceed with the copy of file into flash")
            start_time = datetime.now()
            cmd = 'copy tftp://10.10.10.10/c2900-universalk9-mz.SPA.157-3.M6.bin flash:'
            output = connection.send_command(
                cmd,
                expect_string=r'Destination filename [c2900-universalk9-mz.SPA.157-3.M6.bin]?'
            )
            output += connection.send_command(
                '\n',
                expect_string=r'labrouter#',
                delay_factor=int(delay_value)
            )
            end_time = datetime.now()
            print()
            print(output)
            print()
            print("File copied succesfully on " + host)

        elif value == 'CISCO3925':
            print("Proceed with the copy of file into flash")
            start_time = datetime.now()
            cmd = 'copy tftp://10.10.10.10/c3900-universalk9-mz.SPA.157-3.M6.bin flash:'
            output = connection.send_command(
                cmd,
                expect_string=r'Destination filename [c3900-universalk9-mz.SPA.157-3.M6.bin]?'
            )
            output += connection.send_command(
                '\n',
                expect_string=r'labrouter#',
                delay_factor=int(delay_value)
            )
            end_time = datetime.now()
            print()
            print(output)
            print()
            print("File copied succesfully on " + host)
        
        else:
            print("Router model didn't match with the available models in the pool")
            connection.disconnect()

    #For router model ISR4K:
            
    result1 = re.findall("(ISR\d\d+)", version)
    value1 = result1[0]
    print('The router model is ' + value1)

    if value1 == 'ISR4331':
        print("Proceed with the copy of file into flash")
        start_time = datetime.now()
        cmd = 'copy tftp://10.10.10.10/ITLFile.tlv flash:'
        output = connection.send_command(
            cmd,
            expect_string=r'Destination filename [ITLFile.tlv]?'
        )
        output += connection.send_command(
            '\n',
            expect_string=r'labrouter#',
            delay_factor=int(delay_value)
        )
        end_time = datetime.now()
        print()
        print(output)
        print()
        print("File copied succesfully on " + host)
    else:
        print("Router model didn't match with the available models in the pool")
        connection.disconnect()
      
connection.disconnect()

Short script (working):
======================== 

import netmiko
from netmiko import ConnectHandler

my_device_telnet = { 
"device_type" : "cisco_ios_telnet", 
"ip": 'XXXXXXX',
"username": 'XXXXX',
"password": 'XXXXXX@123',
"port": '23',
"global_delay_factor": 3
}

connection = ConnectHandler(**my_device_telnet)

cmd = 'copy tftp://10.10.10.10/ITLFile.tlv flash:'
output = connection.send_command(
    cmd,
    expect_string=r'Destination filename [ITLFile.tlv]?'
)
output += connection.send_command(
    '\n',
    expect_string=r'labrouter#',
    delay_factor=3
)
print()
print(output)
print()

Expected Output:
================ 
labrouter#copy tftp://10.10.10.10/ITLFile.tlv flash:
Destination filename [ITLFile.tlv]? 
Accessing tftp://10.10.10.10/ITLFile.tlv...
Loading ITLFile.tlv from 10.10.10.10 (via BD): !
[OK - 12191 bytes]

12191 bytes copied in 7.485 secs (1629 bytes/sec)
labrouter#

Session Log output from full script(non-working):
====================================

labrouter#copy tftp://10.10.10.10/ITLFile.tlv flash:
Destination filename [ITLFile.tlv]? 
Accessing tftp://10.10.10.10/ITLFile.tlv...
Loading ITLFile.tlv from 10.10.10.10 (via BD): !

Session logs of the short script does return the expected string.

It never returns expected string which is "labrouter#' and therefore throws error while script execution.

How can I fix this?

Thank you.

**Comment by ktbyers** [comment]
Which version of Netmiko are you using?

**Comment by navnshar** [comment]
Netmiko version: 3.3.0
Python version: 3.8.3

**Comment by ktbyers** [comment]
I need the full exception stack trace of the failing case.

Make sure you are not hiding the exception (i.e. remove any try/except exception handlers that would block/hide the exception you are receiving).

Regards, Kirk

**Comment by navnshar** [comment]
I removed try/expect exception handlers and it worked. Just wondering why would that cause an issue with the script execution.
Just last thing, I am trying to copy file with name "cmterm_7985.4-1-7-0.bin", however, it gives below error.

Traceback (most recent call last):
  File "C:\Users\XXXXXX\Desktop\final_code_v1.1.py", line 173, in <module>
    output = connection.send_command(
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\utilities.py", line 363, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1474, in send_command
    if re.search(search_pattern, output):
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python38-32\lib\re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python38-32\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python38-32\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python38-32\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python38-32\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python38-32\lib\sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range 4-1 at position 34

snippet from session log:

labrouter#terminal width 511
labrouter#terminal length 0
labrouter#copy tftp://10.68.250.75/cmterm_7985.4-1-7-0.bin flash:

Is anything wrong with the file format? or it's something to do with regex ...

**Comment by ktbyers** [comment]
So the above is a different exception/issue? I think we should focus on one issue--do you want to focus on this issue or the original one?


Kirk

**Comment by navnshar** [comment]
Since the original issue related to search patten is fixed after removing try/expect exception handler, you can proceed with closer of this thread. Thanks a lot!!! 

Would appreciate if you can suggest anything for the exception that I listed in my previous comment...

**Comment by ktbyers** [comment]
How long roughly does that TFTP copy take if you do it manually?

**Comment by navnshar** [comment]
It takes around 30-40 mins when done locally and close to 2-3 hours over WAN. If i provide a delay factor value of 2-3 hrs, will send command wait that long?

**Comment by ktbyers** [comment]
You need to set the combination of max_loops * delay_factor such that send_command will execute for long enough. Each loop will sleep (.2 seconds IIRC).

So delay_factor=5 will cause a 1 second sleep per loop.

So then max_loops=10800 should cause send_command to wait up to 3 hours to complete (obviously, you would need a bigger value if it went over 3 hours).

# This would wait roughly 4 hours
send_command(command, delay_factor=5, max_loops=15000)

**Comment by navnshar** [comment]
Thanks Kirk, I will adjust the delay accordingly and will test tonight.
So with delay_factor = 5, I can adjust the max_loops according to my need? or is there any calculation required to adjust delay value based on max_loop value? As per your article, a delay value of 1 is close to 90 seconds and double the delay value doubles the wait.

**Comment by ktbyers** [comment]
Easiest solution is to set delay_factor=5 and then set max_loops=<number_of_seconds_you_require>

**Comment by navnshar** [comment]
Thanks kirk for the help 👍😊
You can close this thread...
