### ISSUE TITLE
check_config_mode in aruba_ssh

### ISSUE THREAD

**Issue by juha2020** [ktbyers/netmiko#1952]
check_config_mode() returns always False for me (HPE Aruba 2530). 
I think the reason is in 

`aruba_ssh.check_config_mode(self, check_string="(config) #", pattern="") `

due to extra " " (space) in check_string. My switch prompts in CLI "HP-2530-24G(config)#" (no space between "(config)" and "#". netmiko logger supports this idea:

```
config_command='configure term'
pattern=re.escape(config_command.strip())
output = net_connect.read_until_pattern(pattern)
```
> DEBUG:netmiko:Pattern is: configure\ term
> HP-2530-24G(config)# 
> HP-2530-24G(config)# 

Br. Juha.

**Comment by ktbyers** [comment]
Should be fixed here:

https://github.com/ktbyers/netmiko/pull/1973

Use `aruba_procurve` for the device_type.

Let me know if that doesn't work.

**Comment by juha2020** [comment]
Thanks. `hp_procurve ` did work

**Comment by pr3adus** [comment]
> Should be fixed here:
> 
> #1973
> 
> Use `aruba_procurve` for the device_type.
> 
> Let me know if that doesn't work.

Hi, i just had the same issue. I was using 'aruba_os' instead of 'aruba_procurve' thank you so much!
This just costed me a whole day :D
