### ISSUE TITLE
Can I point my script to a text file with a list of IPs?

### ISSUE THREAD

**Issue by hhha7x** [ktbyers/netmiko#1954]
Here is my script....

https://imgur.com/a/PFJsN0r

Instead of having the list of IPs in the ip_list section, is there a way I can point it to text file that is a list of all the IPs I want to hit?

**Comment by ktbyers** [comment]
Just open the file and read it in and then loop over the IP addresses (and establish the SSH connection appropriately).

**Comment by hhhax7** [comment]
Any way you could show me an example of how to do that?

**Comment by aliturunc** [comment]
hi , my friend you can use sth like this .
        f1 = open('hostfile.txt', 'r')
        devices = f1.readlines()
            for device in devices:
            column = device.split()
            host = str(column[0])
            
           your_function_name (host)
