### ISSUE TITLE
mikrotik_routeros incomplete output

### ISSUE THREAD

**Issue by tverhoef** [ktbyers/netmiko#1956]
Hi, I'm working on automating a mixture of devices and ran into issues. Using a minimal testscript I found the mikrotik to behave differently. I tried:

```
def testcmd(ipaddr, devicetype, MyCmd):
   DeviceInfo = {
            'device_type': devicetype,
            'host':       ipaddr,
            'username':   "admin",
            'password':   "admin",
            'global_cmd_verify':False
    }         
    net_connect = ConnectHandler(**DeviceInfo)
    output = net_connect.send_command(MyCmd)
    net_connect.disconnect()
    print("{" + output + "}\n")


testcmd("192.168.73.20", "mikrotik_routeros", "export")
testcmd("192.168.37.30", "hp_procurve",       "sh run")

```
which gave an incomplete result for routeros (yes, tried against multiple devices)

> {port
> 
> \# sep/23/2020 15:12:36 by RouterOS 6.46.7
> \#
> \# model = RB750Gr3
> /interface wireless security-profiles
> set [ find default=yes ] supplicant-identity=MikroTik
> /ip hotspot profile
> set [ find default=yes ] html-directory=flash/hotspot
> }
> 
> {
> Running configuration:
> 
> ; J9019B Configuration Editor; Created on release #Q.11.74
> 
> hostname "ProCurve Switch 2510B-24" 
> snmp-server contact "helpdesk" 
> snmp-server location "Lab" 
> trunk 23-24 Trk1 LACP 
> vlan 1 
>    name "DEFAULT_VLAN" 
>    untagged 1-22,25-26,Trk1 
>    ip address dhcp-bootp 
>    exit 
> ip authorized-managers 192.168.1.0 255.255.255.0 
> aaa authentication login privilege-mode 
> aaa authentication console login radius local 
> aaa authentication telnet login radius local 
> aaa authentication telnet enable radius local 
> aaa authentication web login radius local 
> aaa authentication ssh login radius local 
> aaa authentication ssh enable radius local 
> radius-server timeout 2
> spanning-tree
> spanning-tree Trk1 priority 4
> ip ssh
> password manager
> password operator
> }
> 

Next step I tried:

```
def testcmd(ipaddr, devicetype, MyCmd):
   DeviceInfo = {
            'device_type': devicetype,
            'host':       ipaddr,
            'username':   "admin",
            'password':   "admin",
            'global_cmd_verify':False
    }         
    net_connect = ConnectHandler(**DeviceInfo)
    if devicetype == "mikrotik_routeros":    
        output = net_connect.send_command_timing(MyCmd)
    else:
        output = net_connect.send_command(MyCmd)
    net_connect.disconnect()
    print("{" + output + "}\n")


testcmd("192.168.73.20", "mikrotik_routeros", "export")
testcmd("192.168.37.30", "hp_procurve",       "sh run")
```
which gave the result I expected in the first place

> {\# sep/23/2020 15:13:33 by RouterOS 6.46.7
> \#
> \# model = RB750Gr3
> /interface wireless security-profiles
> set [ find default=yes ] supplicant-identity=MikroTik
> /ip hotspot profile
> set [ find default=yes ] html-directory=flash/hotspot
> /ip neighbor discovery-settings
> set discover-interface-list=!dynamic
> /ip dhcp-client
> add disabled=no interface=ether5
> /ip service
> set telnet disabled=yes
> set ftp disabled=yes
> set api disabled=yes
> set api-ssl disabled=yes
> /ip ssh
> set forwarding-enabled=remote strong-crypto=yes
> /snmp
> set enabled=yes
> /system clock
> set time-zone-name=Europe/Stockholm
> /system logging
> add action=remote topics=critical
> add action=remote topics=error
> add action=remote topics=info
> add action=remote topics=warning
> /system routerboard settings
> set silent-boot=yes
> /tool graphing interface
> add
> /tool graphing queue
> add
> /tool graphing resource
> add
> /tool romon
> set enabled=yes
> /user aaa
> set use-radius=yes
> 
> 
> 
> }
> 
> {
> Running configuration:
> 
> ; J9019B Configuration Editor; Created on release #Q.11.74
> 
> hostname "ProCurve Switch 2510B-24" 
> snmp-server contact "helpdesk" 
> snmp-server location "Lab" 
> trunk 23-24 Trk1 LACP 
> vlan 1 
>    name "DEFAULT_VLAN" 
>    untagged 1-22,25-26,Trk1 
>    ip address dhcp-bootp 
>    exit 
> ip authorized-managers 192.168.1.0 255.255.255.0 
> aaa authentication login privilege-mode 
> aaa authentication console login radius local 
> aaa authentication telnet login radius local 
> aaa authentication telnet enable radius local 
> aaa authentication web login radius local 
> aaa authentication ssh login radius local 
> aaa authentication ssh enable radius local 
> radius-server timeout 2
> spanning-tree
> spanning-tree Trk1 priority 4
> ip ssh
> password manager
> password operator
> }

Is this expected? a bug? programmer error? 
Any suggestions or ideas?

//Tonny

**Comment by ktbyers** [comment]
Which version of Netmiko?

**Comment by tverhoef** [comment]
netmiko              3.1.1

**Comment by ktbyers** [comment]
Okay, need to upgrade to Netmiko 3.3.0 (can't really debug/troubleshoot the old code). Very likely will see the same issue on 3.3.0, however.

Also, is the `export` command slow or is there anything odd about it.

Finally, what happens with global_cmd_verify=True?

**Comment by tverhoef** [comment]
Did the upgrade and ran the tests you asked.
1) netmiko 3.3.0 -> no difference
2) there is no difference in behavior between export and other commands
3) with global_cmd_verify=True I get no routeros output at all

**Comment by ktbyers** [comment]
Can you capture the Netmiko log when it fails on Netmiko 3.3.0:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by tverhoef** [comment]
There you go. Only adressed the mikrotik, not the procurve in the log.
[issue1956-20200924.log](https://github.com/ktbyers/netmiko/files/5277904/issue1956-20200924.log)

**Comment by checktheroads** [comment]
Chiming in, I also see this issue with Mikrotik devices. After a cursory glance, it seems to be related to the way `find_prompt()` is "re-finding" the prompt on each line. The output @tverhoef shared is similar to what I see:

```
DEBUG:netmiko:[find_prompt()]: prompt is [admin@hostname] >
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'ping count=5 1.0.0.1\r\n'
DEBUG:netmiko:read_channel: ping count=5 1.0.0.1
[admin@hostname] > ping count=5 1.0.0.1

  SEQ HOST                                     SIZE TTL TIME  STATUS                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    0 1.0.0.1                                    56  60 23ms 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:     1 1.0.0.1                                    56  60 21ms 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is 1 1.0.0.1                                    56  60 21ms
```

The prompt is correctly detected initially (line 1), but seems to be rediscovered as the output on line 20. I've run a couple of different commands and this seems consistent with pings and traceroutes, which tend to repeat some of the same output.

For now, I ended up implementing a workaround of adding `expect_string=r"\S+\s\>\s$"` to the `send_command()` arguments, e.g. `send_command("<command>", expect_string=r"\S+\s\>\s$")`. Looking at the logic ending [here](https://github.com/ktbyers/netmiko/blob/29a89ea70f88dc2fa5d89eebf9f829b81321c162/netmiko/base_connection.py#L1476), that seems to simply hard code the prompt pattern which causes it not to be "re-found".  Hope this helps!

**Comment by tverhoef** [comment]
nice catch! tried your workaround, that does seems to do the trick.Thnx

**Comment by ktbyers** [comment]
I will see if I can fix this. It might be a week or two. If someone wants to take a first pass at a pull request to fix the underlying issue that would be helpful.


Regards, Kirk

**Comment by tverhoef** [comment]
> If someone wants to take a first pass at a pull request to fix the underlying issue that would be helpful.
I will have a look tomorrow (CET)

**Comment by tverhoef** [comment]
Been debugging today, looks like it is 'caused' by using "'global_cmd_verify': False". [here](https://github.com/ktbyers/netmiko/blob/29a89ea70f88dc2fa5d89eebf9f829b81321c162/netmiko/base_connection.py#L1517) at line 1516/1517 the variable 'output' begins with:

```
export
[admin@R2B] > export

\# oct/08/2020 11:28:14 by RouterOS 6.46.7
\# software id = 4CJB-AX6Q
(few more lines follow)

```
which looks like the command send and the echo. In any case it contains the prompt and aborts further reading of the stream.


Simplest would be using "'global_cmd_verify': True" but that brning me back to an earlier issue:

```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    testcmd("192.168.88.62", 22 , "mikrotik_routeros", "export")
  File "test.py", line 22, in testcmd
    output = net_connect.send_command(MyCmd)
  File "/usr/local/lib/python3.7/dist-packages/netmiko/utilities.py", line 363, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/netmiko/base_connection.py", line 1505, in send_command
    strip_prompt=strip_prompt,
  File "/usr/local/lib/python3.7/dist-packages/netmiko/base_connection.py", line 889, in _sanitize_output
    output = self.strip_prompt(output)
  File "/usr/local/lib/python3.7/dist-packages/netmiko/mikrotik/mikrotik_ssh.py", line 76, in strip_prompt
    last_line = response_list[-2]
IndexError: list index out of range

```

**Comment by Fleegle61** [comment]
Keeping an eye out for the next update.  Still cant get a good output from my MT router with the changes above and in other threads.  Getting partial output from commands.

**Comment by ktbyers** [comment]
Proposed fix for Mikrotik:

https://github.com/ktbyers/netmiko/pull/2362

If anyone is willing to test this, it would be appreciated.

**Comment by ktbyers** [comment]
should be fixed in this PR:

https://github.com/ktbyers/netmiko/pull/2362
