### ISSUE TITLE
Unable to enter the context and run command

### ISSUE THREAD

**Issue by vbg93** [ktbyers/netmiko#1957]
@ktbyers I was trying to enter the ACE context and run some commands - But i see it get stuck after running 'changeto XXX' command.

Below is the debug logs. It stucks here 'DEBUG:netmiko:read_channel: ' after entering the context

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
test-ace-device/Admin# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is test-ace-device/Admin#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
test-ace-device/Admin# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is test-ace-device/Admin#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'changeto context1\n'
DEBUG:netmiko:Pattern is: changeto\ context1
DEBUG:netmiko:_read_channel_expect read_data: c
DEBUG:netmiko:_read_channel_expect read_data: hangeto context1

DEBUG:netmiko:Pattern found: changeto\ context1 changeto context1

test-ace-device/context1# nnel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel:

**Comment by ktbyers** [comment]
@vbg93 You probably need to add the `expect_string` argument to get `changeto` to work (since the prompt changes). So something like:

```python
net_connect.send_command("changeto context1", expect_string=r"#")
```

**Comment by vbg93** [comment]
Thanks @ktbyers . I see its working now 👍
