### ISSUE TITLE
How do I hide my password

### ISSUE THREAD

**Issue by hhhax7** [ktbyers/netmiko#1965]
Here is my script....

    from netmiko import ConnectHandler
    import os
    import inspect
    root = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

    ip_list = open(root+ "/host.txt")

    devices = []

    for ip in ip_list:
        cisco = {
          'device_type' : 'cisco_ios',
          'ip' : ip,
          'username' : 'user',
          'password' : 'password'
        }

        net_connect = ConnectHandler(**cisco)

        output = net_connect.send_command('show interface status err-disabled')
        for entry in output.split('\n'):
            print(f'{ip}: {entry}')
        print()

Currently my script shows a plaintext password for my login to the switches. How can I hide this?

**Comment by ktbyers** [comment]
@hhhax7 getpass() or use environment variables are two common solution.

This isn't really a Netmiko issue and is probably better asked in a different forum/venue (or searched online).

Regards, Kirk
