### ISSUE TITLE
failed to use "autodetect" to find a "centec_os" switch

### ISSUE THREAD

**Issue by rhymecc** [ktbyers/netmiko#1966]
i have a trouble in detecting the switch brand by using "autodetect". 

$ cat centec_test.py

####try to use 'autodetect' to get the brand, the result shows none,it fail.####

from netmiko import SSHDetect, Netmiko
device = {
        'device_type': 'autodetect',
        'host': ip,
        'username': user,
        'password': passwd,
    }
guesser = SSHDetect(**device)
best_match = guesser.autodetect()

####Try to use 'centec_os' to access switch, it`s done.####

device['device_type'] = 'centec_os'
connection = Netmiko(**device)
a=connection.find_prompt()
print('name:%s\nbrand:%s\n'%(a,best_match))
connection.disconnect()%      

####result####

$ python centec_test.py 
name:CN-SHA5-OFS-5#
brand:None

**Comment by ktbyers** [comment]
There is no centec support for autodetect. Someone would have to add it.

https://github.com/ktbyers/netmiko/blob/develop/netmiko/ssh_autodetect.py
