### ISSUE TITLE
Telnet login failed

### ISSUE THREAD

**Issue by Eve320** [ktbyers/netmiko#1970]
I'm having an ssue establishing a telnet connection to a cisco ios xr device. Any ideas what I might be missing?
-----------------------------------------------------------------------------------------------------

from netmiko import ConnectHandler
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

ciscoxr = {
'device_type': 'cisco_xr_telnet',
'ip': '10.10.20.173',
'username': 'cisco',
'password': 'cisco',
}

net_connect = ConnectHandler(**ciscoxr)
----------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
File "myfile.py", line 14, in
net_connect = ConnectHandler(**ciscoxr)
File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 302, in ConnectHandler
return ConnectionClass(*args, **kwargs)
File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/base_connection.py", line 344, in init
self._open()
File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/base_connection.py", line 349, in _open
self.establish_connection()
File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/cisco/cisco_xr.py", line 9, in establish_connection
super().establish_connection(width=511, height=511)
File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/base_connection.py", line 908, in establish_connection
self.telnet_login()
File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 169, in telnet_login
raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: 10.10.20.173
---------------------------------------------------------------------------------------------
Here's the log file

-----------------------------------------------------------------------------------------
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:

IMPORTANT: READ CAREFULLY
Welcome to the Demo Version of Cisco IOS XRv (the "Software").
The Software is subject to and governed by the terms and conditions
of the End User License Agreement and the Supplemental End User
License Agreement accompanying the product, made available at the
time of your order, or posted on the Cisco website at
www.cisco.com/go/terms (collectively, the "Agreement").
As set forth more fully in the Agreement, use of the Software is
strictly limited to internal use in a non-production environment
solely for demonstration and evaluation purposes. Downloading,
installing, or using the Software constitutes acceptance of the
Agreement, and you are binding yourself and the business entity
that you represent to the Agreement. If you do not agree to all
of the terms of the Agreement, then Cisco is unwilling to license
the Software to you and (a) you may not download, install or use the
Software, and (b) you may return the Software as more fully set forth
in the Agreement.

Please login with any configured user/password, or cisco/cisco

User Access Verification

Username:

Username:

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:

**Comment by maximcoder** [comment]
Same issue I have with cisco_ios_telnet



DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:

**Comment by maximcoder** [comment]
Telnet works in Version: 3.1.0 of netmiko

**Comment by ktbyers** [comment]
Try setting `fast_cli=False` as an argument to ConnectHandler and see if that fixes the underlying issue?


Regards, Kirk

**Comment by maximcoder** [comment]
fast_cli=False argument fixed it, thank you Kirk!

**Comment by maximcoder** [comment]
I guess the issue can be closed. #
