### ISSUE TITLE
Send list of commands using netmiko_send_command

### ISSUE THREAD

**Issue by jbl241987** [ktbyers/netmiko#1975]
I have list of commands in the txt file, and trying to send one by one cli and collect the output.
Is there something wrong with my simple program

```python
from nornir import InitNornir
from nornir_utils.plugins.functions import print_title, print_result
from nornir_netmiko.tasks import netmiko_send_config, netmiko_commit, netmiko_send_command
from nornir_utils.plugins.processors import PrintResult
from nornir_utils.plugins.tasks.data import load_json, load_yaml
from nornir_jinja2.plugins.tasks import template_file, template_string
from nornir_napalm.plugins.tasks import napalm_get

nr = InitNornir(config_file="config.yaml", dry_run=False)
cisco = nr.filter(role="cisco")

def show(task):
    with open('command.txt') as f:
        command = f.read().splitlines()
    for cmd in command:
        task = task.run(
            task=netmiko_send_command, 
            command_string=cmd,
            delay_factor=2, 
            enable = True,
            use_timing = True,
            max_loops=5
        )

def main():
    print_title("Playbook to show NO of services on each host")
    # show output
    task = cisco.run(task=show)
    print_result(task)

if __name__ == "__main__":
    main()
```

**Comment by jbl241987** [comment]
I get this error and from the list of CLI only first cli output is shown.

^^^^ END show ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* rtr2 ** changed : False ******************************************************
vvvv show ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "C:\Users\jblokesh\Python37\lib\site-packages\nornir\core\task.py", line 98, in start
    r = self.task(self, **self.params)
  File "c:/COLT/Project Nornir/CC copy 2.py", line 16, in show
    task = task.run(
  File "C:\Users\jblokesh\Python37\lib\site-packages\nornir\core\task.py", line 249, in __getattr__
    return getattr(self[0], name)
AttributeError: 'Result' object has no attribute 'run'

**Comment by ktbyers** [comment]
Yes, your program has a bug.

You are re-assigning the `task` variable and trying to use it again.

```python
    for cmd in command:
        task = task.run(
            task=netmiko_send_command, 
            command_string=cmd,
            delay_factor=2, 
            enable = True,
            use_timing = True,
            max_loops=5
        )
```

You probably should change that to something like:

```python
    for cmd in command:
        task.run(
            task=netmiko_send_command, 
            command_string=cmd,
            delay_factor=2, 
            enable = True,
            use_timing = True,
            max_loops=5
        )
```

**Comment by jbl241987** [comment]
Thank you, it worked.
