### ISSUE TITLE
Netmiko timing out during SNMPv3 configuration on Aruba 2530 switch

### ISSUE THREAD

**Issue by rrdemay** [ktbyers/netmiko#1976]
Text file with error output:

[2020-9-30_14-40_SNMP_Error.log](https://github.com/ktbyers/netmiko/files/5307944/2020-9-30_14-40_SNMP_Error.log)

I found an earlier thread regarding this exact same issue (https://github.com/ktbyers/netmiko/issues/895) 

To reiterate:

**From the cli it looks like this**
aruba_sw(config)# snmpv3 enable
SNMPv3 Initialization process.
Creating user 'initial'
Authentication Protocol: MD5
Enter authentication password: **prompted here for string**
Privacy protocol is DES
Enter privacy password: **prompted here for string**
User 'initial' has been created
Would you like to create a user that uses SHA? [y/n] **prompted here for string**
User creation is done. SNMPv3 is now functional.
Would you like to restrict SNMPv1 and SNMPv2c messages to have read only
access (you can set this later by the command 'snmpv3 restricted-access')? [y/n] **prompted here for string**

Thread was closed with recommendation to use expect_string, but that is what I'm already doing.

Here is my code relevant to this section of configuration:

s = ConnectHandler(device_type='hp_procurve', ip=device, username=username, password=password)
s.send_command(
'config',
expect_string=r'#'
)
s.send_command(
'snmpv3 enable',
expect_string=r'password:'
)
s.send_command(
snmppassword,
expect_string=r'password:'
)
s.send_command(
snmppassword,
expect_string=r"y/n]"
)
s.send_command(
'n',
expect_string=r"y/n]"
)
s.send_command(
'n',
expect_string=r'#'
)
s.send_command(
'end',
expect_string=r'#'
)
print('Enabled SNMPv3.\n')

I'm never getting the "Enabled SNMPv3" text output, and if I check the switch config after timeout, snmpv3 enable is still missing. Really wracking my brain on this one. Any help or recommendation would be appreciated.

**Comment by ktbyers** [comment]
I am just going to close this as it is old and not being worked on. If someone is still working on this, just re-open the issue.

**Comment by NINJAX3X** [comment]
Instead of using device type of hp_procurve, use aruba_osswitch as device type for the same.....

**Comment by NINJAX3X** [comment]
import netmiko
from netmiko import ConnectHandler
import sys
import time

aruba_osswitch = {
                    "device_type": "aruba_osswitch",
                    "ip": "10.15.40.14",
                    "username": "username",
                    "password": "password",
                    "global_delay_factor" : 2,
                                                        }

net_connect = ConnectHandler(**aruba_osswitch)


commands = [
            'configure terminal',
            'snmpv3 enable',
            'initial',
            'initial',
            'n',
            'y',
                                                            ]

output = net_connect.send_multiline_timing(commands, multiline = True)

print(output)

print("\n""Done")

net_connect.disconnect()


This code above will work fine with Aruba OS switches and will handle the prompts of SNMPv3 enable command.
