### ISSUE TITLE
Palo Alto Driver Extra Delays Required

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#198]
@GGabriele FYI, I removed the extra delay_factor in the unit tests and the extra sleep times. The send_command_expect shouldn't need this.

This makes me believe there is a different issue (i.e. something is not working correctly with send_command_expect on the PA device).

What issue do you see when you run the unit tests without these extra delays?

```python
show_version = net_connect.send_command_expect(commands["version"], delay_factor=2)
```

**Comment by GGabriele** [comment]
Uhmm that's right, it's odd. This is the complete output from send_command_expect

    gabriele@gabriele:~/netmiko/tests$ py.test -v test_netmiko_show.py --test_device paloalto_panos
    ============================================================= test session starts =============================================================
    platform linux2 -- Python 2.7.6 -- pytest-2.5.1 -- /usr/bin/python
    collected 11 items 
    
    test_netmiko_show.py:22: test_disable_paging FAILED
    test_netmiko_show.py:29: test_ssh_connect FAILED
    test_netmiko_show.py:37: test_send_command PASSED
    test_netmiko_show.py:46: test_send_command_expect FAILED
    test_netmiko_show.py:53: test_base_prompt PASSED
    test_netmiko_show.py:57: test_strip_prompt PASSED
    test_netmiko_show.py:64: test_strip_command PASSED
    test_netmiko_show.py:71: test_normalize_linefeeds PASSED
    test_netmiko_show.py:78: test_clear_buffer PASSED
    test_netmiko_show.py:89: test_enable_mode PASSED
    test_netmiko_show.py:101: test_disconnect PASSED
    
    ================================================================== FAILURES ===================================================================
    _____________________________________________________________ test_disable_paging _____________________________________________________________
    
    net_connect = <netmiko.paloalto.paloalto_panos_ssh.PaloAltoPanosSSH object at 0x7f439b42fa50>
    commands = {'basic': 'show system info', 'config': ['set network vlan new_test', 'set network vlan another_test'], 'config_verification': 'run show vlan all', 'extended_output': 'show system info', ...}
    expected_responses = {'base_prompt': 'ntc@pa1', 'cmd_response_final': 'another_test', 'cmd_response_init': 'new_test', 'enable_prompt': 'ntc@pa1>', ...}
    
        def test_disable_paging(net_connect, commands, expected_responses):
            '''
            Verify paging is disabled by looking for string after when paging would normally occur
            '''
            multiple_line_output = net_connect.send_command_expect(commands["extended_output"])
    >       assert expected_responses["multiple_line_output"] in multiple_line_output
    E       assert 'logdb-version: 7.0.9' in '\n'
    
    test_netmiko_show.py:27: AssertionError
    ______________________________________________________________ test_ssh_connect _______________________________________________________________
    
    net_connect = <netmiko.paloalto.paloalto_panos_ssh.PaloAltoPanosSSH object at 0x7f439b42fa50>
    commands = {'basic': 'show system info', 'config': ['set network vlan new_test', 'set network vlan another_test'], 'config_verification': 'run show vlan all', 'extended_output': 'show system info', ...}
    expected_responses = {'base_prompt': 'ntc@pa1', 'cmd_response_final': 'another_test', 'cmd_response_init': 'new_test', 'enable_prompt': 'ntc@pa1>', ...}
    
        def test_ssh_connect(net_connect, commands, expected_responses):
            '''
            Verify the connection was established successfully
            '''
            show_version = net_connect.send_command_expect(commands["version"])
            time.sleep(1)
    >       assert expected_responses["version_banner"] in show_version
    E       assert 'sw-version: 7.0.1' in ''
    
    test_netmiko_show.py:35: AssertionError
    __________________________________________________________ test_send_command_expect ___________________________________________________________

    net_connect = <netmiko.paloalto.paloalto_panos_ssh.PaloAltoPanosSSH object at 0x7f439b42fa50>
    commands = {'basic': 'show system info', 'config': ['set network vlan new_test', 'set network vlan another_test'], 'config_verification': 'run show vlan all', 'extended_output': 'show system info', ...}
    expected_responses = {'base_prompt': 'ntc@pa1', 'cmd_response_final': 'another_test', 'cmd_response_init': 'new_test', 'enable_prompt': 'ntc@pa1>', ...}
    
        def test_send_command_expect(net_connect, commands, expected_responses):
            """Verify a command can be sent down the channel successfully using _expect method."""
            time.sleep(1)
            net_connect.clear_buffer()
            show_ip_alt = net_connect.send_command_expect(commands["basic"])
    >       assert expected_responses['interface_ip'] in show_ip_alt
    E       assert '10.0.0.90' in '\n'
    
    test_netmiko_show.py:51: AssertionError
    ===================================================== 3 failed, 8 passed in 30.09 seconds ====================================================

**Comment by ktbyers** [comment]
@GGabriele So from the above I think what we need to do is write a small Netmiko script that does the following:

```python
from netmiko import ConnectHandler
from getpass import getpass

device = {
    'device_type': 'cisco_ios',
    'ip': '50.76.53.27',
    'username': 'admin',
    'password': getpass(),
    'port': 22,
}

start = datetime.now()
net_connect = ConnectHandler(**device)
output = net_connect.send_command_expect("show system info")
print output
```

Change 'device' values to match your device?

What does the above output show? 


Kirk

**Comment by GGabriele** [comment]
Nothing!

I start receiving the output if I include `delay_factor=2`

**Comment by ktbyers** [comment]
@GGabriele 

What if you change it to do the following:

```python
net_connect = ConnectHandler(**device)
output = net_connect.find_prompt()
print output
output = net_connect.find_prompt()
print output
output = net_connect.find_prompt()
print output
```

**Comment by GGabriele** [comment]
Here it is:
    
    >>> output = net_connect.find_prompt()
    >>> print output
    ntc@pa1>
    >>> output = net_connect.find_prompt()
    >>> print output
    ntc@pa1>
    >>> output = net_connect.find_prompt()
    >>> print output
    ntc@pa1>
    >>> 

But if I add the previous send:

    >>> output = device.send_command_expect("show system info")
    >>> print output
    >>> 
    >>> output = device.find_prompt()
    >>> print output
    operational-mode: normal         # this is the last expected line from the output
    >>> output = device.find_prompt()
    >>> print output
    ntc@pa1>
    >>> output = device.find_prompt()
    >>> print output
    ntc@pa1>
    >>>

**Comment by ktbyers** [comment]
@GGabriele Okay, in send_command_expect code can you toggle the

```python
debug = True           # toggle this to True 
```

and then re-run the original test.

```
net_connect = ConnectHandler(**device)
output = net_connect.send_command_expect("show system info")
print output
```

**Comment by GGabriele** [comment]
That's what I see coming:

    >>> output = net_connect.send_command_expect("show system info")
    Command is: show system info
    
    Search to stop receiving data is: 'ntc\@pa1\>'
    >>> print output
    
    
    >>>

**Comment by ktbyers** [comment]
@GGabriele So there is this loop in send_command_expect in base_connection.py

```python
        while i <= max_loops:
            if self.remote_conn.recv_ready():
                output += self.remote_conn.recv(MAX_BUFFER).decode('utf-8', 'ignore')
                try:
                    lines = output.split("\n")
                    first_line = lines[0]
                    # First line is the echo line containing the command. In certain situations
                    # it gets repainted and needs filtered
                    if BACKSPACE_CHAR in first_line:
                        pattern = search_pattern + r'.*$'
                        first_line = re.sub(pattern, repl='', string=first_line)
                        lines[0] = first_line
                        output = "\n".join(lines)
                except IndexError:
                    pass
                if re.search(search_pattern, output):
                    break
            else:
                time.sleep(delay_factor * 1)
            i += 1
```

Line 432 - 451.

Can you add a print statement write after the output is received back:

```python
            if self.remote_conn.recv_ready():
                output += self.remote_conn.recv(MAX_BUFFER).decode('utf-8', 'ignore')
                print(output)
```

Also can you print something out if the pattern is detected:

```python
                if re.search(search_pattern, output):
                    print("Found search pattern: {0}".format(output))
                    break
```

Let me know what you see.

**Comment by GGabriele** [comment]
Hey @ktbyers, this is what is printed out:
    
    >>> output = net_connect.send_command_expect("show system info")
    Command is: show system info
    
    Search to stop receiving data is: 'ntc\@pa1\>'
    ntc@pa1> 
    Found search pattern: ntc@pa1> 
    >>> print output
    
    >>>

**Comment by ktbyers** [comment]
@GGabriele Okay, well that is progress anyways...so for some reason the router prompt is already there.

**Comment by ktbyers** [comment]
@GGabriele Line 424-426 of the code has the following (in send_command_expect method).

```python
        time.sleep(delay_factor * 1)
        self.clear_buffer()
        self.remote_conn.sendall(command_string)
```

What if you change that time.sleep to time.sleep(2)? Does that fix the problem?

**Comment by GGabriele** [comment]
@ktbyers that additional sleep doesn't fix the problem, but changing another one does (line 450).

    while i <= max_loops:
                if self.remote_conn.recv_ready():
                    output += self.remote_conn.recv(MAX_BUFFER).decode('utf-8', 'ignore')
                    try:
                        lines = output.split("\n")
                        first_line = lines[0]
                        # First line is the echo line containing the command. In certain situations
                        # it gets repainted and needs filtered
                        if BACKSPACE_CHAR in first_line:
                            pattern = search_pattern + r'.*$'
                            first_line = re.sub(pattern, repl='', string=first_line)
                            lines[0] = first_line
                            output = "\n".join(lines)
                    except IndexError:
                        pass
                    if re.search(search_pattern, output):
                        break
                else:
                    time.sleep(delay_factor * 2)     # from delay_factor * 1 to delay_factor * 2
                i += 1
            else:   # nobreak
                raise IOError("Search pattern never detected in send_command_expect: {0}".format(
                search_pattern))

This is the output:

    >>> output = net_connect.send_command_expect("show system info")
    Command is: show system info

    Search to stop receiving data is: 'ntc\@pa1\>'
    >>> 
    >>> print output
    
    hostname: pa1
    ip-address: 10.0.0.90
    netmask: 255.255.255.0
    default-gateway: 10.0.0.2
    ipv6-address: unknown
    ipv6-link-local-address: fe80::20c:29ff:fe6d:c67e/64
    ipv6-default-gateway: 
    mac-address: 00:0c:29:6d:c6:7e
    time: Fri May  6 00:07:53 2016
    uptime: 9 days, 20:13:31
    family: vm
    model: PA-VM
    serial: unknown
    vm-mac-base: BA:DB:EE:FB:AD:00
    vm-mac-count: 255
    vm-uuid: 564D8B6D-7BDB-75AF-400F-B062016DC67E
    vm-cpuid: FB060000FDFB8B07
    vm-license: none
    vm-mode: VMWare ESXi
    sw-version: 7.0.1
    global-protect-client-package-version: 0.0.0
    app-version: 497-2688
    app-release-date: unknown
    av-version: 0
    av-release-date: unknown
    threat-version: 0
    threat-release-date: unknown
    wf-private-version: 0
    wf-private-release-date: unknown
    url-db: paloaltonetworks
    wildfire-version: 0
    wildfire-release-date: unknown
    url-filtering-version: 0000.00.00.000
    global-protect-datafile-version: 0
    global-protect-datafile-release-date: unknown
    logdb-version: 7.0.9
    platform-family: vm
    vpn-disable-mode: off
    multi-vsys: off
    operational-mode: normal
    
    >>>

**Comment by ktbyers** [comment]
@GGabriele Okay, I pushed the above fix to master. 

Can you test it out and see if that fixes the issue and all of PA unit tests now pass without modification (i.e. extra delays)?

Is this a virtual device?

**Comment by GGabriele** [comment]
Theeeere we go :) 

    gabriele@gabriele:~/netmiko/tests$ py.test -v test_netmiko_show.py --test_device paloalto_panos
    ============================================================= test session starts =============================================================
    platform linux2 -- Python 2.7.6 -- pytest-2.5.1 -- /usr/bin/python
    collected 11 items 

    test_netmiko_show.py:25: test_disable_paging PASSED
    test_netmiko_show.py:32: test_ssh_connect PASSED
    test_netmiko_show.py:40: test_send_command PASSED
    test_netmiko_show.py:49: test_send_command_expect PASSED
    test_netmiko_show.py:56: test_base_prompt PASSED
    test_netmiko_show.py:60: test_strip_prompt PASSED
    test_netmiko_show.py:67: test_strip_command PASSED
    test_netmiko_show.py:74: test_normalize_linefeeds PASSED
    test_netmiko_show.py:81: test_clear_buffer PASSED
    test_netmiko_show.py:92: test_enable_mode PASSED
    test_netmiko_show.py:105: test_disconnect PASSED

    ========================================================= 11 passed in 32.94 seconds ==========================================================
    

    gabriele@gabriele:~/netmiko/tests$ py.test -v test_netmiko_config.py --test_device paloalto_panos
    ============================================================= test session starts =============================================================
    platform linux2 -- Python 2.7.6 -- pytest-2.5.1 -- /usr/bin/python
    collected 7 items 
    
    test_netmiko_config.py:21: test_ssh_connect PASSED
    test_netmiko_config.py:29: test_enable_mode PASSED
    test_netmiko_config.py:43: test_config_mode PASSED
    test_netmiko_config.py:51: test_exit_config_mode PASSED
    test_netmiko_config.py:58: test_command_set PASSED
    test_netmiko_config.py:95: test_commands_from_file PASSED
    test_netmiko_config.py:109: test_disconnect PASSED
    
    ========================================================= 7 passed in 103.02 seconds ==========================================================

Yes, that's virtual.

**Comment by ktbyers** [comment]
Yes, virtual devices are frequently meaningfully slower...

Nice!

**Comment by GGabriele** [comment]
Thanks for finding the time to go through this :)
