### ISSUE TITLE
Nokia ISAM platform

### ISSUE THREAD

**Issue by dejantep** [ktbyers/netmiko#1988]
Not really an issue but I don't know where to ask. Is there a support for this platform? Its a Nokia sros actually but somehow it doesn't work. Maybe minor differences.

Does anybody use this successfully?

**Comment by ktbyers** [comment]
@hellt Roman any idea on this?

**Comment by balkandude** [comment]
This is the error i get
`AttributeError: 'list' object has no attribute 'rstrip'`

And as far as i can see in ISAM log there was a successfull login

**Comment by hellt** [comment]
Its an optics product it seems which I have no experience with, but what would help is a full debug log

**Comment by balkandude** [comment]
This is Nokia OLT platform with CLI based on SROS. I would like to help but i need guidance. Is it debug log of Netmiko?

**Comment by hellt** [comment]
@balkandude 

try to add this:

```python
import logging
logging.basicConfig(filename='netmiko.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
```

before you proceed with connection setup

**Comment by balkandude** [comment]
[netmiko.log](https://github.com/ktbyers/netmiko/files/5324159/netmiko.log)

As far as i can see there's an issue with call for "environment" command. There's no paging on this platform but there's a command "environment inhibit-alarms" to disable the alarm reporting in the current  session.

**Comment by hellt** [comment]
I think failing to disable paging shouldn't stop you from running commands.
Did this execution stop with the same `AttributeError: 'list' object has no attribute 'rstrip'` error? I do not see it in the log...

**Comment by ktbyers** [comment]
Also please post the full exception stack trace where you get the `rstrip` error

**Comment by balkandude** [comment]
[traceback.txt](https://github.com/ktbyers/netmiko/files/5324190/traceback.txt)

I hope this is what you're asking for

**Comment by ktbyers** [comment]
@balkandude You are passing in a list:

`['show equipment slot']`

You need to pass in a string.

**Comment by balkandude** [comment]
That's it. So simple. Many thanks guys. One follow up question...Is it possible to adapt "environment no more" before it is sent or should i just send it as a command_string or lets say first line in config_commands/config_file?

**Comment by groy1** [comment]
In my testing of netmiko with Nokia ISAM products, I was able to get some limited functionality to work when the device_type = autodetect.  Currently there is no vendor support for it with netmiko.

The Nokia 7360 OLT, actually runs two different operating systems.  The main os is the isam.  
The 2nd operating, which does the switching, is similar to SROS.

For these Nokia product lines you probably want use the following disable paging command 
"environment print no-more inhibit-alarms mode batch"

There are multiple types of ISAM products, and they all operate a little bit differently etc.
Hope that helps.

G
