### ISSUE TITLE
Netmiko - Huawei switches 5700 - Save to device - Issue 

### ISSUE THREAD

**Issue by stijnvbb** [ktbyers/netmiko#1990]
Hi All,

I would like to open a new issue in reference to #1163. At this moment, the function save_config() is not working / not implemented yet. Therefore I'm trying to create a workaroud.

From cli part on the S5700 huawei device, the following is happening:

From operational mode:
<test-device>save
The current configuration will be written to flash:/vrpcfg.zip.
Are you sure to continue?[Y/N]

OR

Configuration mode:
<test-device>save
The current configuration will be written to flash:/vrpcfg.zip.
Are you sure to continue?[Y/N]

Some explanation: within huawei you have two options to work in: operational mode or configuration mode. Afterwards you enter the "save" command and huawei device is asking for input Y/N in order to save the file. 

At this moment, the save_config( ) function is not yet implemented, I'm looking for a workaround. I think the issue is that huawei device is asking to confirm the save but netmiko is not able to handle such behavior ?

I have tried the following without success in operational mode or configuration mode with netmiko:

Basis template:
    device = {
        'device_type': 'huawei_vrpv8',
        'ip': ipaddress,
        'username': username,
        'password': pwd,
        'verbose': False,
    }

    net_connect = netmiko.ConnectHandler(**item)
    net_connect.set_base_prompt()

During operational mode:
      net_connect.send_command("save")    <==== 
      net_connect.send_command("Y")    <==== 

OR 

During configuration mode:
      net_connect.send_config_set("run save", "y")     <==== 

Please advise me to fix this issue!
Thanks

Stijn vbb

**Comment by stijnvbb** [comment]
Nobody able to assist me how to save on huawei s5700 device?

**Comment by ktbyers** [comment]
```
From operational mode:

save
The current configuration will be written to flash:/vrpcfg.zip.
Are you sure to continue?[Y/N]
```

**Comment by ktbyers** [comment]
Handling multiline prompting is pretty well documented in Netmiko--did you search around for it?

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-timing

**Comment by stijnvbb** [comment]
Thanks man ! We did not found this page before. Very much appreciated to provide me with this information.
Appreciate your work!!
