### ISSUE TITLE
Netmiko fails to connect to switch, but run it again and it connects successfully, then fails the next switch on

### ISSUE THREAD

**Issue by hhha7x** [ktbyers/netmiko#1991]
from netmiko import ConnectHandler
    import os
    import inspect
    root = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

    ip_list = open(root+ "/host.txt")

    devices = []

    for ip in ip_list:
        cisco = {
          'device_type' : 'cisco_ios',
          'ip' : ip,
          'username' : 'user,
          'password' : 'password'
        }

    net_connect = ConnectHandler(**cisco)

    output = net_connect.send_command('show interface status err-disabled')
    for entry in output.split('\n'):
        print(f'{ip}: {entry}')
    print()

As the title states, this script points to a text file that contains roughly 50-60 switches. When I first run it, I get an error for the first IP on the list, stating

    `"netmiko.ssh_exception.NetmikoTimeoutException:` TCP connection to device failed.

    Common causes of this problem are:

    Incorrect hostname or IP address.
    Wrong TCP port.
    Intermediate firewall blocking access.
    Device settings: cisco_ios 192.168.12.97:22"`

When I run the script again, this switch will succeed, but the next switch on the list will get the same error. Run it again, the first and second switch succeed, and the third switch gets the error. And it just keeps going from there. Anyone have any idea how to fix this? SSH connectivity to all devices is fine.

**Comment by ktbyers** [comment]
I probably would try to increase the `conn_timeout` of all of the devices to like 20 or 30 seconds.

Are these virtual devices or physical devices?

**Comment by hhhax7** [comment]
> I probably would try to increase the `conn_timeout` of all of the devices to like 20 or 30 seconds.
> 
> Are these virtual devices or physical devices?

They are physical devices, cisco 3750x. I am new to this, so where exactly am I going to increase the conn_timeout? Or is this something I will need to add to the script?

**Comment by aliturunc** [comment]
hi fırst write a function  to connect the equipment  and sen the command ,  than use a loop for this function .

but ı think main issue is  net.coneect  and other lines are outside the for loop .

**Comment by ktbyers** [comment]
So what @aliturunc was saying was to modify your code to something like:

```python
from netmiko import ConnectHandler
import os
import inspect
root = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

ip_list = open(root+ "/host.txt")

devices = []

for ip in ip_list:
    cisco = {
      'device_type' : 'cisco_ios',
      'ip' : ip,
      'username' : 'user,
      'password' : 'password'
    }

    net_connect = ConnectHandler(**cisco)

    output = net_connect.send_command('show interface status err-disabled')
    for entry in output.split('\n'):
        print(f'{ip}: {entry}')
    print()
```
