### ISSUE TITLE
WLC Throwing OSError Since 3.3

### ISSUE THREAD

**Issue by KSBolton** [ktbyers/netmiko#1992]
Hello all. 

I've had this Netmiko implementation running since 2018 but recently, I've seen where my WLC throws an OSError stating 'Search pattern never detected in send_command: >'. From what I can tell, it seems to fail right at the end after the config has been properly copied and the prompt is supposed to return to normal.
`
```
def CAT_con(ip2):

    strtoday, strtime1 = grab_time()

    cat_sw1 = {
        'device_type': 'cisco_ios',
        'ip': ip2,
        'username': username,
        'password': password,
        'secret': secret,
    }

    try:
        net_connect2 = ConnectHandler(**cat_sw1)
        devname2 = net_connect2.base_prompt

        if "DMZ" in devname2:
            net_connect2.enable()

        if "Controller" in devname2:
            output2 = net_connect2.send_command("transfer upload mode sftp", expect_string=r">")
            output2 += net_connect2.send_command("transfer upload username secure_user", expect_string=r">")
            output2 += net_connect2.send_command("transfer upload password secure_pw", expect_string=r">")
            output2 += net_connect2.send_command("transfer upload datatype config", expect_string=r">")
            output2 += net_connect2.send_command("transfer upload filename wlc-backup-"
                                                 f"{strtoday}-{strtime1}", expect_string=r">")
            output2 += net_connect2.send_command("transfer upload path /wireless/my-WLC01/", expect_string=r">")
            output2 += net_connect2.send_command("transfer upload serverip 100.100.0.1", expect_string=r">")
            output2 += net_connect2.send_command("transfer upload start", delay_factor=2, expect_string=r"Are you sure")
            output2 += net_connect2.send_command("y", delay_factor=10, expect_string=r">")
        else:
            output2 = net_connect2.send_command(copy_dir_switch + "Site1/" + devname2 + "/" + devname2 + "_" + strtime1 + ".cfg",
                                                expect_string=r"Address or name")
            output2 += net_connect2.send_command("\n", expect_string=r"Destination filename")
            output2 += net_connect2.send_command("\n", expect_string=r"#")
        net_connect2.disconnect()
        # print(output2)

        lg.write("\n" + devname2 + " - " + output2 + "\n")
        return f"{devname2} {output2}"
    except (NetMikoTimeoutException, NetMikoAuthenticationException, IOError, OSError) as err2:
        # print(err2)
        print(output2)
        lg.write("\n" + ip2 + " - " + str(err2) + "\n")
        return f"{ip2} <=> {err2}"`
```

It results in this

```
`Mode............................................. TFTP  
TFTP Server IP................................... 100.100.0.1
TFTP Path........................................ /wireless/my-WLC01/
TFTP Filename.................................... wlc-backup-2020-10-05-14-07
Data Type........................................ Config File 
Encryption....................................... Disabled

**************************************************
***  WARNING: Config File Encryption Disabled  ***
**************************************************


Are you sure you want to start? (y/N) 
10.0.70.2 <=> Search pattern never detected in send_command: >`

```
Instead of 

```
`(Cisco Controller)  - Mode............................................. TFTP  
TFTP Server IP................................... 100.100.0.1
TFTP Path........................................ /wireless/my-WLC01/
TFTP Filename.................................... wlc-backup-14-42
Data Type........................................ Config File 
Encryption....................................... Disabled

**************************************************
***  WARNING: Config File Encryption Disabled  ***
**************************************************


Are you sure you want to start? (y/N) 

TFTP Config transfer starting.

File transfer operation completed successfully.`
```

**Comment by ktbyers** [comment]
Can you get rid of your try/except as it is hiding the full stacktrace and where the exception is occurring?

Can you then post the full exception stack trace?

**Comment by KSBolton** [comment]
> Can you get rid of your try/except as it is hiding the full stacktrace and where the exception is occurring?
> 
> Can you then post the full exception stack trace?

I had reverted back to 3.0.0 to get it working. Just upgraded back to 3.3.2 and recreated the issue. Here you go:

C:\Users\admin\AppData\Local\Programs\Python\Python38-32\python.exe C:/Users/admin/Python_Workspace/test/LP_Bckup_v3.py
Traceback (most recent call last):
  File "C:/Users/admin/Python_Workspace/test/LP_Bckup_v3.py", line 136, in <module>
    for result in results:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:/Users/admin/Python_Workspace/test/LP_Bckup_v3.py", line 116, in CAT_con
    output2 += net_connect2.send_command("transfer upload start", delay_factor=2, expect_string=r"Are you sure")
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\utilities.py", line 429, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1523, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command: Are you sure

Process finished with exit code 1

**Comment by KSBolton** [comment]
> Can you get rid of your try/except as it is hiding the full stacktrace and where the exception is occurring?
> 
> Can you then post the full exception stack trace?

I found the issue. It just happened to coincide with my upgrade to 3.3.0 and the change wasn't communicated to me. My apologies. 

For anyone who's curious, the timestamps appended to the file name included a ':' and the WLC doesn't like that so it broke there and went on my exception and so didn't print the rest of the output (which should have included the WLC error  message).
