### ISSUE TITLE
netmiko.ssh_exception.NetmikoAuthenticationException: Authentication failure

### ISSUE THREAD

**Issue by superloopnetworks** [ktbyers/netmiko#1995]
Hi @ktbyers ,

I'm facing an issue where the authentication fails because the device is unable to reach the TACACS before it timesout. 

```netmiko.ssh_exception.NetmikoAuthenticationException: Authentication failure: unable to connect cisco_ios {ipaddress:port}```

The device then falls back to local authentication. But because the credentials given to netmiko initially are TACACS credentials and not local, it fails. I understand that is not netmiko's issue at all. However, what's happening is whenever I get these authentication failures, the threading process gets stuck and the app never completes it's task. It's thinking "work" is still going on in the background and haven't completed. Is there a way to "kill" off the inactive threads that faces these authentication error?

**Comment by ktbyers** [comment]
You might want to just increase the `auth_timeout` that you pass to ConnectHandler. This potentially is an easier solution/workaround to the original problem.

Alternatively, you can do a try/except and pass a second set of credentials for the local credentials.

I am not sure what you mean by the the threading process gets stuck...that just sounds like an implementation error in your code.

**Comment by superloopnetworks** [comment]
The current value for auth_timeout is set to None. I like the idea of the try/except.

I'm using your multithread engine code with some modifications to suite my environment.. What I'm seeing is upon a Authentication Failure in the tracebacks, the multithread get stuck in a stale state (app never finishes it's task. ex. config back up)... I'm assuming it's waiting for some kill signal to know the thread is "complete" before the multithread process finishes or timesout. But because of the Authentication Failure, is that thread being stuck? I could be totally off... When I have a successful run (without Authentication Failures), every thread finishes and the app completes it's task as per normal (ex. config backups).

```        for i in ntw_object:
                if(redirect[zero] == 'exec_cmd' or redirect[zero] == 'pull_cfgs' ):
                        arguments = commands
                        element = 0
                elif(redirect[index] == 'push_cfgs' or redirect[index] == 'get_config' or redirect[index] == 'get_diff'):
                        arguments = commands[index]
                        element = index
                my_thread = threading.Thread(target=getattr(ntw_object[index],redirect[element]) , args=(arguments,))
                my_thread.start()

                index = index + 1

        main_thread = threading.currentThread()
        for some_thread in threading.enumerate():
                if some_thread != main_thread:
#                       print(some_thread)
                        some_thread.join()```

**Comment by ktbyers** [comment]
Make sure you are using a Netmiko Context Manager...in other words, make sure you are always gracefully cleaning up your SSH connections including when they fail auth.

I would also look to use concurrent futures and not legacy thread code (and some form of a thread pool with concurrent futures).

It would be pretty similar to the code shown here except ThreadPoolExecutor and not ProcessPoolExecutor:

https://github.com/ktbyers/pyplus_course/blob/master/class10/collateral/CF_PROCESSES/ssh_procs_wait.py


Regards, Kirk

**Comment by superloopnetworks** [comment]
Thanks @ktbyers ! Appreciate your help. In your opinion, do you recommend multithreading or asyncio? What would work best?

**Comment by superloopnetworks** [comment]
I tried the below code and it works. However I think there is some issues to this logic of code. This is saying, it will try and connect. Should it receive an Authentication Failure, Try RECONNECTING again using a local credential. The issue I find is this - if it tries to reconnect the second time, it may or may NOT face a TACACs timeout. So rather than reconnecting again, is there a way I can just send the "password" down the SSH pipe? Or have the SSH channel have not been formed at this point? and hence, I cannot use a "net_connect.send_command('new_password')"

```
        try:
            self.net_connect = ConnectHandler(self.ip,self.hostname,self.username,self.password,self.password,device_type=self.get_device_type())
        except (NetMikoAuthenticationException) as error:
            self.net_connect = ConnectHandler(self.ip,self.hostname,self.username,'new_password','new_password',device_type=self.get_device_type())
```

**Comment by ktbyers** [comment]
Yes, you don't have an SSH session until you authenticate.

Realistic options:
1. Make sure TACACS+ solution work more reliably.
2. Stagger the threads so the TACACS+ solution doesn't get overloaded (i.e. introduce very slight delays between each thread running so that TACACS+ doesn't get overloaded).
3. Put in enough logic and connection handling to overcome the lack of TACACS+ reliability.

Regards, Kirk

**Comment by superloopnetworks** [comment]
Thanks Kirk. Will try some of your suggestions. Cheers!
