### ISSUE TITLE
Cisco IOS show vrf is not being processed by textfsm

### ISSUE THREAD

**Issue by ilia2344** [ktbyers/netmiko#1998]
Hi!
Trying like so:
```
import netmiko
c4500_connect = netmiko.ConnectHandler(device_type='cisco_ios', ip = core_sw_ip, username=user, password=pwd)
c4500_vrf_raw = c4500_connect.send_command_expect('show vrf', use_textfsm=True)
c4500_int_raw = c4500_connect.send_command_expect('show int', use_textfsm=True)

type(c4500_vrf_raw)
Out[190]: str

type(c4500_int_raw)
Out[191]: list
```
Connection is successful, output is valid for both commands, but as you can see, sh vrf is returned as a string, it is exactly as if textfsm was disabled. Works ok for a whole bunch of other commands. Checked definition in index file - should work without issue:
`cisco_ios_show_vrf.textfsm, .*, cisco_ios, sh[[ow]] vrf`
  
Thank you in advance

**Comment by ktbyers** [comment]
Looks like your output is failing parsing via TextFSM (likely meaning that the TextFSM template is failing on your particular output). I would run it manually with the given raw output and TextFSM template and see if it works.

Or alternatively open an issue with ntc-templates (I am assuming you are using ntc-templates for your textfsm template).

It doesn't really look like a Netmiko issue.
