### ISSUE TITLE
netmiko error while running.

### ISSUE THREAD

**Issue by muhammednikhilmm** [ktbyers/netmiko#1999]
Getting below error while running netmiko program 

----------error below---------------
**osboxes@osboxes:~/netmiko$ python3 New-Pro.py
Connecting to device"
Traceback (most recent call last):
  File "New-Pro.py", line 20, in <module>
    net_connect = ConnectHandler(**ios_device)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/ssh_dispatcher.py", line 312, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 240, in __init__
    raise ValueError("Either ip or host must be set")
ValueError: Either ip or host must be set**

-----------program below----------

```python
from netmiko import ConnectHandler

with open('aaa-snmp-config') as f:
    commands_list = f.read().splitlines()

with open('switches-H17') as f:
    devices_list = f.read().splitlines()

for devices in devices_list:
    print ('Connecting to device" ' + devices)
    #ip_address_of_device = devices_list

    ios_device = {
        'device_type': 'cisco_ios',
        'ip': devices,
        'username': 'mddnetadmin',
        'password': 'C1sc0@123'
    }

    net_connect = ConnectHandler(**ios_device)
    # net_connect.enable('C1sc0@123')
    output = net_connect.send_config_set(commands_list)
    print (output)**
```
-----------------------

please let me know the fix for the same.

**Comment by ktbyers** [comment]
Error message is pretty self explanatory. You are not passing in a DNS hostname or IP address properly into Netmiko with your `devices` variable.
