### ISSUE TITLE
Cisco privilege level support

### ISSUE THREAD

**Issue by tdorssers** [ktbyers/netmiko#2000]
The mechanism to detect if a device is in enable mode is based on string matching of the device prompt. In case of a Cisco device, Netmiko checks for `#`. This is however not accurate. The prompt of a Cisco device ends with `>` when the privilege level is 1. If it is greater then 1, then the prompt ends with `#`.
If you have a privilege level between 1 and 15, then Netmiko cannot `enable()` to privilege level 15, because `check_enable_mode()` returns `True`. On a Cisco device, it is not needed to check the device prompt, because the `enable` command will simply return the prompt, when you are already in privilege level 15. If you are in level 3 for instance,  then the device will prompt you for the password.
By simply adding a test to check if pattern is in output and removing the initial enable mode check, you can workaround this:

```python
    def enable(self, cmd="", pattern="ssword", re_flags=re.IGNORECASE):
        output = ""
        msg = (
            "Failed to enter enable mode. Please ensure you pass "
            "the 'secret' argument to ConnectHandler."
        )
        self.write_channel(self.normalize_cmd(cmd))
        try:
            output += self.read_until_prompt_or_pattern(
                pattern=pattern, re_flags=re_flags
            )
            if pattern in output:
                self.write_channel(self.normalize_cmd(self.secret))
                output += self.read_until_prompt()
        except NetmikoTimeoutException:
            raise ValueError(msg)
        if not self.check_enable_mode():
            raise ValueError(msg)
        return output
```

Privilege level 3 is assigned by a TACACS server in my case and I have to implement this workaround to use Netmiko to configure the network. I believe that it is a valid use case to have a privilege level other then 1 or 15, but Netmiko has issues with this. Can you please look into this?

**Comment by ktbyers** [comment]
So you are in `privilege level 3` and your prompt ends in `#` and you need to elevate your privileges to privilege level 15 (so you can make configuration changes). Is that correct?

**Comment by tdorssers** [comment]
Yes precisely.

**Comment by ktbyers** [comment]
Can you downgrade your privilege level via `disable 1` (in your script) and then invoke `enable()`?

Alternate solution is to just use `write_channel()` and `read_channel()` and write a special handler. 

I am pretty reluctant to make the change you proposed above (I probably wouldn't do it).


Regards, Kirk

**Comment by tdorssers** [comment]
Downgrading to privilege level 1 and then upgrade to 15 is prohibited by security regulations, so that only worked in my lab and not in production.
My current solution is indeed as you suggest to write my own special handler.
I believe it should be documented at the very least that only privilege levels 1 and 15 are supported by Netmiko.
To understand your reluctance, the IOS XR driver implements interactive CLI as well to prohibit concurrent commits (although that implementation is currently broken, see #1860). So you could integrate this into the IOS driver only. Or maybe it is such a big change that it's something for Netmiko 4.x
Another solution is to just send 'show privilege' and capture the value. If show privilege isn't supported or didn't work, then fallback to current prompt check.
Regards,
Tim

**Comment by ktbyers** [comment]
I guess we could possible do something like:

`enable(no_state_check=True)`

Where Netmiko bypasses the initial `check_enable_mode` call.

Would that work from your perspective?

**Comment by tdorssers** [comment]
Yes that would work, except when you are already at privilege level 15, then the Cisco device interprets the password as a hostname to telnet to, because there will be no `Password:` prompt.

```
Switch#show privilege 
Current privilege level is 3
Switch#enable
Password: 
Switch#show privilege 
Current privilege level is 15
Switch#enable       <-- no prompt here
Switch#
```

That's why I added a check to see if the `Password:` prompt appears or not.

**Comment by gusyee** [comment]
Please help, I create backup config with netmiko. But some device user only privilege 7.  And I try to use net_connect.enable() but enable secret password not input to device. How to I can login to exec mode?

this log on netmiko if i try to show run on switch  "% Invalid input detected at '^' marker."

show privilege
Current privilege level is 7
switch#en
Password:

**Comment by meldean** [comment]
> The mechanism to detect if a device is in enable mode is based on string matching of the device prompt. In case of a Cisco device, Netmiko checks for `#`. This is however not accurate. The prompt of a Cisco device ends with `>` when the privilege level is 1. If it is greater then 1, then the prompt ends with `#`.
> If you have a privilege level between 1 and 15, then Netmiko cannot `enable()` to privilege level 15, because `check_enable_mode()` returns `True`. On a Cisco device, it is not needed to check the device prompt, because the `enable` command will simply return the prompt, when you are already in privilege level 15. If you are in level 3 for instance, then the device will prompt you for the password.
> By simply adding a test to check if pattern is in output and removing the initial enable mode check, you can workaround this:
> 
> ```python
>     def enable(self, cmd="", pattern="ssword", re_flags=re.IGNORECASE):
>         output = ""
>         msg = (
>             "Failed to enter enable mode. Please ensure you pass "
>             "the 'secret' argument to ConnectHandler."
>         )
>         self.write_channel(self.normalize_cmd(cmd))
>         try:
>             output += self.read_until_prompt_or_pattern(
>                 pattern=pattern, re_flags=re_flags
>             )
>             if pattern in output:
>                 self.write_channel(self.normalize_cmd(self.secret))
>                 output += self.read_until_prompt()
>         except NetmikoTimeoutException:
>             raise ValueError(msg)
>         if not self.check_enable_mode():
>             raise ValueError(msg)
>         return output
> ```
> 
> Privilege level 3 is assigned by a TACACS server in my case and I have to implement this workaround to use Netmiko to configure the network. I believe that it is a valid use case to have a privilege level other then 1 or 15, but Netmiko has issues with this. Can you please look into this?

Where you able to come up with a workaround for this issue? I have the same problem. If yes would you be willing to share the python script. I am new to python. Thanks!

**Comment by tdorssers** [comment]
> > The mechanism to detect if a device is in enable mode is based on string matching of the device prompt. In case of a Cisco device, Netmiko checks for `#`. This is however not accurate. The prompt of a Cisco device ends with `>` when the privilege level is 1. If it is greater then 1, then the prompt ends with `#`.
> > If you have a privilege level between 1 and 15, then Netmiko cannot `enable()` to privilege level 15, because `check_enable_mode()` returns `True`. On a Cisco device, it is not needed to check the device prompt, because the `enable` command will simply return the prompt, when you are already in privilege level 15. If you are in level 3 for instance, then the device will prompt you for the password.
> > By simply adding a test to check if pattern is in output and removing the initial enable mode check, you can workaround this:
> > ```python
> >     def enable(self, cmd="", pattern="ssword", re_flags=re.IGNORECASE):
> >         output = ""
> >         msg = (
> >             "Failed to enter enable mode. Please ensure you pass "
> >             "the 'secret' argument to ConnectHandler."
> >         )
> >         self.write_channel(self.normalize_cmd(cmd))
> >         try:
> >             output += self.read_until_prompt_or_pattern(
> >                 pattern=pattern, re_flags=re_flags
> >             )
> >             if pattern in output:
> >                 self.write_channel(self.normalize_cmd(self.secret))
> >                 output += self.read_until_prompt()
> >         except NetmikoTimeoutException:
> >             raise ValueError(msg)
> >         if not self.check_enable_mode():
> >             raise ValueError(msg)
> >         return output
> > ```
> > 
> > 
> > Privilege level 3 is assigned by a TACACS server in my case and I have to implement this workaround to use Netmiko to configure the network. I believe that it is a valid use case to have a privilege level other then 1 or 15, but Netmiko has issues with this. Can you please look into this?
> 
> Where you able to come up with a workaround for this issue? I have the same problem. If yes would you be willing to share the python script. I am new to python. Thanks!

Yes, you can use this function:
```python
    def _enable(session, cmd='enable', pattern='ssword', re_flags=re.IGNORECASE):
        """ Enter enable mode properly, see Netmiko issue #2000 """
        output = ''
        msg = 'Failed to enter enable mode.'
        session.write_channel(session.normalize_cmd(cmd))
        try:
            output += session.read_until_prompt_or_pattern(pattern, re_flags)
            if pattern in output:
                session.write_channel(session.normalize_cmd(session.secret))
                output += session.read_until_prompt()
        except:
            raise ValueError(msg)
        if not session.check_enable_mode():
            raise ValueError(msg)
        return output
```
Example usage:
```python
with ConnectHandler(**device) as session:
    _enable(session)
```

**Comment by meldean** [comment]
> > > The mechanism to detect if a device is in enable mode is based on string matching of the device prompt. In case of a Cisco device, Netmiko checks for `#`. This is however not accurate. The prompt of a Cisco device ends with `>` when the privilege level is 1. If it is greater then 1, then the prompt ends with `#`.
> > > If you have a privilege level between 1 and 15, then Netmiko cannot `enable()` to privilege level 15, because `check_enable_mode()` returns `True`. On a Cisco device, it is not needed to check the device prompt, because the `enable` command will simply return the prompt, when you are already in privilege level 15. If you are in level 3 for instance, then the device will prompt you for the password.
> > > By simply adding a test to check if pattern is in output and removing the initial enable mode check, you can workaround this:
> > > ```python
> > >     def enable(self, cmd="", pattern="ssword", re_flags=re.IGNORECASE):
> > >         output = ""
> > >         msg = (
> > >             "Failed to enter enable mode. Please ensure you pass "
> > >             "the 'secret' argument to ConnectHandler."
> > >         )
> > >         self.write_channel(self.normalize_cmd(cmd))
> > >         try:
> > >             output += self.read_until_prompt_or_pattern(
> > >                 pattern=pattern, re_flags=re_flags
> > >             )
> > >             if pattern in output:
> > >                 self.write_channel(self.normalize_cmd(self.secret))
> > >                 output += self.read_until_prompt()
> > >         except NetmikoTimeoutException:
> > >             raise ValueError(msg)
> > >         if not self.check_enable_mode():
> > >             raise ValueError(msg)
> > >         return output
> > > ```
> > > 
> > > 
> > > Privilege level 3 is assigned by a TACACS server in my case and I have to implement this workaround to use Netmiko to configure the network. I believe that it is a valid use case to have a privilege level other then 1 or 15, but Netmiko has issues with this. Can you please look into this?
> > 
> > 
> > Where you able to come up with a workaround for this issue? I have the same problem. If yes would you be willing to share the python script. I am new to python. Thanks!
> 
> Yes, you can use this function:
> 
> ```python
>     def _enable(session, cmd='enable', pattern='ssword', re_flags=re.IGNORECASE):
>         """ Enter enable mode properly, see Netmiko issue #2000 """
>         output = ''
>         msg = 'Failed to enter enable mode.'
>         session.write_channel(session.normalize_cmd(cmd))
>         try:
>             output += session.read_until_prompt_or_pattern(pattern, re_flags)
>             if pattern in output:
>                 session.write_channel(session.normalize_cmd(session.secret))
>                 output += session.read_until_prompt()
>         except:
>             raise ValueError(msg)
>         if not session.check_enable_mode():
>             raise ValueError(msg)
>         return output
> ```
> 
> Example usage:
> 
> ```python
> with ConnectHandler(**device) as session:
>     _enable(session)
> ```

Thank you so much!! I have been trying various things for the past 2 weeks. I found if I changed my tacac servers to bogus ips and created a user account with privilege 15 that worked - which is fine in my test lab but not a solution for production.  Then I stumbled upon this. Thanks again!

**Comment by ktbyers** [comment]
Probably need to do two things here:

1. For cisco_ios/ios_xe have the enable call be `enable 15`.
2. Add some sort of an argument like `no_state_check` such that the `check_enable_mode` call can be bypassed (so for those set of people that use priv2 through priv14, having a `prompt` that ends in `#` won't cause the enable invocation to get skipped (due to check_enable_mode thinking we are already at privilege 15).

**Comment by tdorssers** [comment]
Regarding 1.: that doesn't make sense, since 15 is the default: https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/security/d1/sec-d1-cr-book/sec-cr-e1.html#wp3307186499
Regarding 2.: that could work, except when you are at privilege level 15 already, then the method will timeout while not receiving the expected `assword` pattern. To prevent that you should skip waiting for the pattern if the prompt returns immediately after sending `enable`.
```
Switch#show privilege 
Current privilege level is 3
Switch#enable
Password:         <- here is the pattern
Switch#show privilege 
Current privilege level is 15
Switch#enable     <-- no prompt here, which will cause timeout
Switch#
```

**Comment by ktbyers** [comment]
People really should not be using `no_state_check=False` if you are privilege 15 or privilege 1.

But we should probably regex on `(ssword|{base_prompt})` anyways (as there is no good reason to fail if the password prompt never shows up on the `enable` cmd execution.

**Comment by ktbyers** [comment]
Should be fixed here:

https://github.com/ktbyers/netmiko/pull/3194

Added a new `check_state` argument. 

You should now be able to do the following:

```python
netmiko_obj.enable(check_state=False)
```

And Netmiko will not check the current prompt (for determining if you are already in enable mode).

Previous changes to Netmiko should cause it to already work if you send `enable` and the device never prompts you for a password (i.e. Netmiko will generally search for the password or for the trailing prompt and only send the password if prompted by the device).

**Comment by fernal9301** [comment]
Seems, not working 

I have a user with privilege 6 

```
#!/usr/bin/python3

from netmiko import ConnectHandler

R1 = {
    'device_type': 'cisco_ios',
    'host':   'x.x.x.x',
    'username': 'admin',
    'password': 'admin',
    'secret': 'cisco',     # optional, defaults to ''
}

net_connect = ConnectHandler(**R1)

output = net_connect.send_command('show privilege')
print(output)

net_connect.enable(check_state=False)
output2 = net_connect.send_command('show privilege')
print(output2)

net_connect.disconnect()```

Output: 

Current privilege level is 6


netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'R1' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

So, it's trying to find pattern  R1#  but  get R1 because check_state=False

**Comment by ktbyers** [comment]
@fernal9301 Please open a new issue and link to this issue (otherwise, your issue will get lost) as this is a closed issue.

Also, you need to include the full exception stack trace in the output.
