### ISSUE TITLE
scp.SCPException: ser **** (100) may not copy files 

### ISSUE THREAD

**Issue by superloopnetworks** [ktbyers/netmiko#2002]
Hi @ktbyers , 

Using your SCP module in netmiko... SCP'ing config.ucs files from F5 LTMs to local and I'm faced with these exception messages. I can't find much info on this issue. Any idea what that means? I'm able to do a normal scp from bash without problems.

```File "/usr/local/lib/python3.6/dist-packages/netmiko/scp_handler.py", line 45, in scp_get_file
    self.scp_client.get(source_file, dest_file)
  File "/usr/local/lib/python3.6/dist-packages/scp.py", line 238, in get
    self._recv_all()
  File "/usr/local/lib/python3.6/dist-packages/scp.py", line 388, in _recv_all
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: ser **** (100) may not copy files (scp -f /var/local/ucs/config.ucs)```

**Comment by ktbyers** [comment]
Can you post the entire stack trace? Also is that last line correct? Was the **** by you or is that the literal string?

**Comment by superloopnetworks** [comment]
Hi @ktbyers , 

Sure thing... Here is the entire traceback:

```Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jenkins/workspace/team-infra-networking/superloop_pull_cfgs_prod/lib/objects/basenode.py", line 129, in pull_cfgs
    self.scp_connect.scp_get_file('/var/local/ucs/config.ucs', '{}/superloop/data/{}/{}{}/{}.ucs'.format(self.get_home_directory(),self.get_subdir(),self.get_region(),self.get_environment(),self.hostname))
  File "/usr/local/lib/python3.6/dist-packages/netmiko/scp_handler.py", line 45, in scp_get_file
    self.scp_client.get(source_file, dest_file)
  File "/usr/local/lib/python3.6/dist-packages/scp.py", line 238, in get
    self._recv_all()
  File "/usr/local/lib/python3.6/dist-packages/scp.py", line 388, in _recv_all
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: ser **** (100) may not copy files (scp -f /var/local/ucs/config.ucs)```

I did not put the ****... The output is like that.

**Comment by ktbyers** [comment]
Looks like the F5 sent back an invalid SCP command (at least from the scp.py perspective).

I would guess maybe an F5 permissions issue. Have you been able to get the SCP to work completely outside of Python.

Anyways doesn't look like a Netmiko issue.

**Comment by superloopnetworks** [comment]
Yes, a regular scp from bash works just fine outside of Python.

**Comment by superloopnetworks** [comment]
I seem to have "fixed" it... I removed the flag '-f', in 'scp -f /var/local/ucs/config.ucs'... I tried searching to see what the "-f" does but couldn't find any info.. The linux man page doesn't have -f...

**Comment by superloopnetworks** [comment]
Hey @ktbyers , does the scp_handler.py module have a delay factor by any chance? I do see a "socket_timeout=10.0". What does this do?

**Comment by ktbyers** [comment]
@superloopnetworks So you are trying to write your own SCP code correct? Using the Python SCP module?


Regards, Kirk

**Comment by superloopnetworks** [comment]
@ktbyers I am not.. I'm still trying to get the file to scp across. Wasn't sure if delay factor plays an issue in this case. If the F5s are too slow to respond (Two F5s throwing this scp issues and they are the only F5s overseas. The ones that are working fine are situated in US), would it affect the scp process. Hence I wanted to try "slowing" it down..

**Comment by ktbyers** [comment]
Where is this code from?

```python
        elif(self.platform == 'f5'):
            command = 'list ltm one-line'
            self.scpconnect()
            self.write_to_file(command)
            self.scp_connect.scp_get_file('/var/local/ucs/config.ucs', '{}/superloop/data/{}/{}{}/{}.ucs'.format(self.get_home_directory(),self.get_subdir(),self.get_region(),self.get_environment(),self.hostname))
            self.scp_connect.close()
            self.net_connect.disconnect()
```

Or the `scp -f /var/local/ucs/config.ucs`

**Comment by ktbyers** [comment]
You can set the global_delay_factor for Netmiko's standard file_transfer process which is detailed here:

https://pynet.twb-tech.com/blog/automation/netmiko-scp.html

This is in the SSH control channel that is used with file transfer, but there is no support for F5 here (except for the Linux file_transfer device type).

scp_timeout is a timeout that is passed into the the SCP library that originated due to failures on large file transfers. See this issue:

https://github.com/ktbyers/netmiko/issues/1254


Regards, Kirk

**Comment by superloopnetworks** [comment]
@ktbyers

The below is my own code but it's using your scp module, SCPConn.. ```from netmiko import ConnectHandler, SCPConn```
 
```
elif(self.platform == 'f5'):
            command = 'list ltm one-line'
            self.scpconnect()
            self.write_to_file(command)
            self.scp_connect.scp_get_file('/var/local/ucs/config.ucs', '{}/superloop/data/{}/{}{}/{}.ucs'.format(self.get_home_directory(),self.get_subdir(),self.get_region(),self.get_environment(),self.hostname))
            self.scp_connect.close()
            self.net_connect.disconnect()
```

```scp -f ``` comes from the scp.py module imported within scp_handler.py - lines 233 - 238.

Do you no longer recommend using ```SCPConn``` but rather ```file_transfer```.?

I don't see any of the arguments from file_transfer that allows me to adjust the global_delay_factor from the document you pasted. Am I looking at the wrong place?

```
def file_transfer(ssh_conn, source_file, dest_file, 
                  file_system=None, direction='put',
                  disable_md5=False, overwrite_file=False):
```

**Comment by ktbyers** [comment]
Yeah we probably should focus on creating an F5 FileTransfer driver. `SCPConn` is generally only intended to be used with the FileTransfer class and associated file_transfer function (i.e. it is a pretty thin wrapper to the `scp` library).

The first argument of the `file_transfer` function is a Netmiko SSH connection object: `ssh_conn`

You would create this using `ConnectHandler` and can pass in all the standard arguments including `global_delay_factor`.

Here is an example of creating a FileTransfer class that can be used with the file_transfer function:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/linux/linux_ssh.py#L114


Regards, Kirk

**Comment by superloopnetworks** [comment]
Thanks for your help @ktbyers . I'll have a look!

**Comment by ktbyers** [comment]
Sounds good.
