### ISSUE TITLE
Problem handling large output

### ISSUE THREAD

**Issue by abigailzeke** [ktbyers/netmiko#2003]
Hi, not sure if this is the right place to post this but I'm using below code to run show commands on my routers but my web app (using Flask) crashes everytime I get large amounts of output (100mb+)

I have multi-line input (html form) for several commands at a time, and if the output returned is large (usually log files), I get timed out on Chrome with this error: "Error code: SBOX_FATAL_MEMORY_EXCEEDED"

Is there any limitation to the string output that I can pass from netmiko to my web app?

```
net_connect = ConnectHandler(**connect_params)
            net_connect.enable()

            output = hostname + '\n-------------\n'

            for command in commands:
                output += command + '\n'
                output += net_connect.send_command(command,delay_factor=5) + '\n'

net_connect.disconnect()
```

**Comment by ktbyers** [comment]
It doesn't really look like a Netmiko issue.

Netmiko itself doesn't have restrictions on the size of your `output` variable. Python and your system will. 


Regards, Kirk

**Comment by Gopiprashanthraju** [comment]
Same issue I don't think issue is with python

**Comment by ktbyers** [comment]
@Gopiprashanthraju The referenced issue is ~5 years old and was closed a long time ago--you should probably open a new issue and provide code, exception message.
