### ISSUE TITLE
Expcet function in send_config_set

### ISSUE THREAD

**Issue by smolit** [ktbyers/netmiko#2004]
Hi netmiko-team,

I have to remove a user on a Cisco IOS device.
As you surely know IOS asks for confirmation after you entered the "no username xyz" command.
If I send commands outside configuration mode which also needs confirmation like "format flash:" this works fine with the "expect_string" option of the send_command function.
Maybe there still exists a method to handle confirmations during send_config_set.
I would be happy if I can get a hint from you.
If there doesn't exist an option at the moment, this is a feature request. ;-)

Thanks
Sebastian

**Comment by ktbyers** [comment]
General solution for this is to handle it separately from your other config changes:

```python
out = net_connect.config_mode()
out += net_connect.send_command("no username foo", expect_string=r"confirm")
out += net_connect.send_command("y")
out += net_connect.exit_config_mode()
```


Regards, Kirk

**Comment by smolit** [comment]
Hi Kirk,

thank you very much for your hint.
I am working with netmiko for about a half year and had never read about config_mode.
Obviously I was blind. ;-))
I tried your solution successfully.

Thanks,
Sebastian

**Comment by ktbyers** [comment]
No worries.


Kirk
