### ISSUE TITLE
Questions related to my fork

### ISSUE THREAD

**Issue by johnneerdael** [ktbyers/netmiko#2010]
Hi ktbyers, 

I've forked the netmiko release to add support for Infoblox NIOS (enterprise DNS, DHCP and IPAM solution). I would love to add some more features but I get stuck a little...

For instance the juniper code for JunOS contains the following:
```py
    def _enter_shell(self):
        """Enter the Bourne Shell."""
        return self.send_command("start shell sh", expect_string=r"[\$#]")

    def _return_cli(self):
        """Return to the Juniper CLI."""
        return self.send_command("exit", expect_string=r"[#>]")
```

Infoblox CLI also has a expertmode and maintencemode that i want to incorporate which changes the prompt drastiscally which leads the module to stall and I was wondering how to handle it. I got it working from my script itself (using expect_string) but I would like to able to handle this logic from the module so it's more user friendly for yours and our users.

```py
with ConnectHandler(**nios) as connection:
    configmode = connection.find_prompt()
    output = connection.send_command('set maintenancemode', expect_string='Maintenance Mode >')
    maintenancemode = connection.find_prompt()
    connectivitycheck = connection.send_command('show network_connectivity type 4 proto tcp src_addr 10.61.9.2 10.61.5.7 22', expect_string=maintenancemode)
    print(connectivitycheck)
    exitmaintenancenode = connection.send_command('set maintenancemode off', expect_string=configmode)
    interfaces = connection.send_command('show interface')
    print(interfaces)
    connection.disconnect()
```

Any tips/pointers are greatly appreciated and I would be happy if you could add our NIOS (Infoblox) support in the main release :)

**Comment by ktbyers** [comment]
I am going to close this as it doesn't look like anyone is actively working on it. If anyone is still working on it, just re-open the issue and comment on it.
