### ISSUE TITLE
Dell os10 switch fails ssh autodetect

### ISSUE THREAD

**Issue by sregister** [ktbyers/netmiko#2014]
Hi--I'm seeing an issue with SSHDetect.autodetect() on a few dell os10 switches.

Example code: 
```#!/usr/bin/env python
from netmiko import SSHDetect, ConnectHandler
from getpass import getpass

device = {
    "device_type": "autodetect",
    "host": "switch_ip",
    "username": "admin",
    "password": getpass(),
}

guesser = SSHDetect(**device)
best_match = guesser.autodetect()
print(best_match)  # Name of the best device_type to use further
```

If switch_ip is an os9 switch best_match is `dell_os9`; if its an os10 switch I get `None`. Here is a the full `show version` output I see when I manually ssh into the os10 switch:
```switch1# show version
Dell EMC Networking OS10 Enterprise
Copyright (c) 1999-2019 by Dell Inc. All Rights Reserved.
OS Version: 10.5.0.0P1
Build Version: 10.5.0.0P1.342
Build Time: 2019-08-12T22:06:43+0000
System Type: Z9332F-ON
Architecture: x86_64
Up Time: 5 weeks 5 days 20:55:31
```

I'm not sure exactly at which level this is breaking; I'll update if I find out anything more.

**Comment by sregister** [comment]
After working with @penguin359, this might be caused by the switch being stuck in a pager when `show version` is executed causing an impartial read.  When `autodetect()` starts walking through the elements in `SSH_MAPPER_BASE` it runs alacatel_aos's command "show system" which is a valid command on os10 (but not the one we're looking for) which opens a pager. The next switch it tries is alcatel_sros's "show version" which is the correct command for dell_os10 but the output is incomplete and doesn't contain the string we are looking for. When it comes around to checking for dell_os10's search patterns the cache is incomplete and it fails. 

I'm trying to lookup the command to globally disable paging (for all ttys forever) but this might not exist.

**Comment by ktbyers** [comment]
@sregister Netmiko's autodetect mechanism requires there to be no disabling of paging. In other words, since we don't know the platform, there is no way we can disable the paging of output. Though maybe you were looking to disable paging in your devices as a one-off operation (and not as part of Netmiko's autodetect mechanism).

I guess we could potentially re-order such that `show version` comes first...and `show system` comes after that.

**Comment by sregister** [comment]
> I guess we could potentially re-order such that `show version` comes first...and `show system` comes after that.

Yes I was thinking that too; I've confirmed that moving a `show version` to the top does prevent this from happening. Unfortunately means that with each reordering of that dictionary we risk introducing bugs on some other switch OS. With that said--since this hasn't been reported before, so dell_os10 could be the only switch that has this issue and a simple reordering (while a less-than ideal solution) might be an appropriate fix.

**Comment by ktbyers** [comment]
Yes, I agree with your statement regarding ordering problems and ...but `show version` should probably be the first command always executed as it is by far the most common command we use to determine the platform.

**Comment by rasanentimo** [comment]
The same issue is with Dell OS9 as well (dell_force10 or dell_os9). Would it be possible to order the dict based on the frequency of commands as @ktbyers proposed?

'show version': 13,
'show system': 4,
'display version': 2,
'show sys version': 1,
'cat /etc/issue': 1,
'uname -a': 1,
'show copyright': 1

One other option would be to add grep to the command but it would generate more commands to be sent to the devices and therefore it's not optimal, i.e 
'show version | i ASA'
'show version | i Networking OS Version'

**Comment by sregister** [comment]
@rasanentimo I was not able to reproduce this issue using a dell_os9 switch. Per the first post--when I entered a dell_os9 ip the `switch_ip` did correctly detect it was dell_os9. As for grepping, I didn't think of that but I agree it would add some complexity to the commands sent to devices and some poor soul would have to confirm the grep syntax for each vendor.

**Comment by ktbyers** [comment]
Proposed fix is here:

https://github.com/ktbyers/netmiko/pull/2032

In the PR, the commands are executed based on their frequency (so "show version" is first).
