### ISSUE TITLE
Login on Device(Kind a Linux Version) with 4 steps of login

### ISSUE THREAD

**Issue by martydream** [ktbyers/netmiko#2017]
Hi guys,

I'm having issues to figure out how to login on device where I need to run some periodically commands:

I was trying to use linux type but unsuccessfully, well let me explain the regular loging from cli:

***********************************************************************************
**FIRST:**
$ ssh cli@10.3.30.120

**SECOND**:
Username: admin

**THIRD**:
Password: *****

**FOURTH:**
Do you acknowledge? (Y/N)?Y

VER_RNA01# 

***************************************************************************
Basically all this is what I need to put to login from CLI.

Please your help, how can I login using netmiko.

This is my code:
               linux = {
                    'device_type': 'linux',
                    'ip':   '10.3.30.120',
                    'username': 'cli',
                    'password': '',
                    'port' : 22,          # optional, defaults to 22
                    'verbose': True,       # optional, defaults to Fals
                }                  
                try:
                    net_connect = ConnectHandler(**linux)

                #except SSHException:
                except (BadHostKeyException, AuthenticationException, SSHException, socket.error) as e:
                    print ("4 - Error! The file was not uploaded: ", e)
                    #print('SSH is not enabled for this device.')
                net_connect.find_prompt()
                server = net_connect.read_channel()
                print(server)

This is the OUTPUT ERROR:
VER_RNA01_10.3.30.120
SSH connection established to 10.3.30.120:22
Interactive SSH session established
Traceback (most recent call last):
  File "/home/jgomezg/dwdm_show_int_detail.py", line 56, in <module>
    net_connect = ConnectHandler(**linux)
  File "/home/jgomezg/.local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 259, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/jgomezg/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 327, in __init__
    self._open()
  File "/home/jgomezg/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 333, in _open
    self._try_session_preparation()
  File "/home/jgomezg/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 756, in _try_session_preparation
    self.session_preparation()
  File "/home/jgomezg/.local/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 19, in session_preparation
    return super().session_preparation()
  File "/home/jgomezg/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 776, in session_preparation
    self.set_base_prompt()
  File "/home/jgomezg/.local/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 43, in set_base_prompt
    delay_factor=delay_factor,
  File "/home/jgomezg/.local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1081, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: 'Password:'
Process finished with exit code 1

 

Regards.

**Comment by martydream** [comment]
This the output of a complete LOGIN from CLI:

xxxxx@mrtdrm:~$ ssh cli@10.3.30.120
Last login: Thu Oct 22 17:37:59 2020 from 10.0.70.249

Username: admin
Password: 
Last Login: Thu Oct 22 17:32:26 2020 from ssh_10.0.70.249-45822

Security compliance warning - Please check password status! 

Nokia 1830 PSS, WAVELENGTH TRACKER
(c) 2019 Nokia.  All rights reserved.

   Legal Notices  applicable to  any  software   distributed  alone or in
   connection with the product to which this text pertains, are available
   at  NOS (Nokia Online Services)  with "1830  Photonic  Service  Switch
   (PSS) Software Legal Notice Details".

   This  system   is  restricted  solely to  Nokia  authorized  users for
   legitimate    business  purposes   only.    The actual   or  attempted
   unauthorized  access, use, or modification of this system  is strictly
   prohibited  by  Nokia.  Unauthorized  users  are  subject  to  Company
   disciplinary   proceedings and/or  criminal and  civil penalties under
   state, federal, or other applicable domestic and foreign laws.  Use of
   this  system may  be monitored  and  recorded for  administrative  and
   security reasons.  Anyone accessing this system expressly  consents to
   such  monitoring and is advised  that if  monitoring  reveals possible
   evidence of criminal activity, Nokia may provide  the evidence of such
   activity to law  enforcement  officials.   All  users must comply with
   Nokia   Corporate  Instructions  regarding  the  protection  of  Nokia
   information assets.

Do you acknowledge? (Y/N)?Y

Alarm Status:  Critical-0   Major-1   Minor-0 Warning-10

VER_RNA01# help

**Comment by martydream** [comment]
I was making an example in expect just for an example what Im need to do but with NETMIKO:

#!/usr/bin/expect -f


spawn ssh cli@10.3.30.120
expect "name: "
send "admin\r"
expect "ssword: "
send "pass\r"
expect "*(Y/N)?"
send "Y\r"
expect "*#"
send -- "show interface 1/3 detail\r"
expect "*#"


Please your help.

Regards.

**Comment by ktbyers** [comment]
You probably need to make a Netmiko driver for this device. The below is very non-standard from an SSH perspective and consequently, you need special handlers to handle it. I can point you at other platforms where we have solved similar things in the past (if you are interested in creating the driver).

```
FIRST:
$ ssh cli@10.3.30.120

SECOND:
Username: admin

THIRD:
Password: *****

FOURTH:
Do you acknowledge? (Y/N)?Y

VER_RNA01#

```

**Comment by martydream** [comment]
Yes of course, please.

Let me know how and what I need.

Regards

**Comment by ktbyers** [comment]
You need something like this:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/calix/calix_b6.py#L79-L96

And:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/calix/calix_b6.py#L37-L60

i.e. you need to handle the prompts and the special `Do you acknowledge`
