### ISSUE TITLE
cisco_ios not properly disabling paging

### ISSUE THREAD

**Issue by spijen** [ktbyers/netmiko#2020]
hi everybody
i have one ACL with 2000 line of rules
i use this command to show the ACL's Rule and in result i find only 999 line and --more-- 
![aaaaa](https://user-images.githubusercontent.com/42704183/97414568-5ff99100-1919-11eb-9c84-506f17f6cb67.PNG)
(net_connect.send_command(command ,expect_string=r'\s+\d',delay_factor=5))
is there any limit in number of results  ?

**Comment by ktbyers** [comment]
@spijen Which Netmiko device_type are you using?

Netmiko should automatically disable the paging of output.

**Comment by spijen** [comment]
'device_type': 'cisco_ios' ,
'global_delay_factor': 4,
'fast_cli': False,

**Comment by ktbyers** [comment]
What is the actual model of the device you are connecting to?

Also what does the `session_log` show? You can add this as an argument to ConnectHandler `session_log="output.txt"` and then look at what is in that file.

**Comment by spijen** [comment]
actual devise model is cisco 2960 switch
session_log is all of things than i want :D 
the full result of sho ip access-list is there 
tank you man

**Comment by ktbyers** [comment]
So it works now?


Kirk

**Comment by spijen** [comment]
yes i found my (show access-list) full result in session_log file .
