### ISSUE TITLE
Cisco Nexus 9000 failing on slow command

### ISSUE THREAD

**Issue by babilat** [ktbyers/netmiko#2021]
Netmiko is quitting on slow running commands "show run" on Cisco Nexus 9000. I have tried using "expect_string={hostname}#, delay factor of 4 and neither works. Netmiko documentation says it should take atleast 100 seconds, but it seems to be failing around 20 seconds into the run. 
#####My code############
device = {
    "device_type": "cisco_nxos",
    "host": "xx.xx.xx.xx",
    "username": "username",
    "password": "passwd",
    "session_log": "session.out",
}

command = "show run | xml | no-more"
with ConnectHandler(**device) as net_connect:
    print(net_connect.find_prompt())
    output = net_connect.send_command(command, delay_factor=4)

#############error#########################
Traceback (most recent call last):
  File "netmiko_detect.py", line 30, in <module>
    response = connection.send_command(command, delay_factor=4)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/utilities.py", line 429, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1525, in send_command
    search_pattern
OSError: Search pattern never detected in send_command: #2020

**Comment by ktbyers** [comment]
Is that the full exception stack trace?

You probably need to include the Netmiko log file from the failure case.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Also which version of Netmiko are you using. You need to be using the latest released Netmiko version.


Regards, Kirk

**Comment by babilat** [comment]
I am using netmiko==3.3.2. I don't get much when trying to get full exception stack trace with traceback.

**Comment by babilat** [comment]
[test.log](https://github.com/ktbyers/netmiko/files/5466424/test.log)

**Comment by babilat** [comment]
Attached the log file.

**Comment by ktbyers** [comment]
If you do this manually, how long (roughly) does it take to output data:

```
!Command: show running-config
!Running configuration last done at: Tue Oct 13 13:50:54 2020
!Time: Fri Oct 30 16:38:49 2020

version 7.0(3)I7(6) Bios:version 07.65 

DEBUG:netmiko:read_channel: ******************************************
This may take time. Please be patient.
******************************************

```

**Comment by ktbyers** [comment]
By this, I mean the following command:

`show run | xml | no-more`

**Comment by babilat** [comment]
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2019, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

nep6delag102# terminal width 511

nep6delag102# terminal length 0

nep6delag102#

nep6delag102#

nep6delag102#

nep6delag102# show run | xml | no-more

!Command: show running-config
!Running configuration last done at: Tue Oct 13 13:50:54 2020
!Time: Fri Oct 30 16:38:49 2020

version 7.0(3)I7(6) Bios:version 07.65
******************************************
This may take time. Please be patient.
******************************************

exit

**Comment by babilat** [comment]
It takes about 30-35 seconds to run this command. I found some limited success using delay_factor=4, max_loops=5000

**Comment by ktbyers** [comment]
Probably will work if you set, fast_cli=False as an argument to ConnectHandler.

**Comment by babilat** [comment]
Thanks for the help. Using fast_cli=False didn't make a difference.

**Comment by ktbyers** [comment]
Okay, so with the following code:

```python
#####My code############
device = {
    "device_type": "cisco_nxos",
    "host": "xx.xx.xx.xx",
    "username": "username",
    "password": "passwd",
    "session_log": "session.out",
    "fast_cli": False,
}

command = "show run | xml | no-more"
with ConnectHandler(**device) as net_connect:
    print(net_connect.find_prompt())
    output = net_connect.send_command(command, delay_factor=4)

#############error#########################
```

What error/exception do you get?

Also, can you post the Netmiko log file associated with the above code.

**Comment by ktbyers** [comment]
The following code worked for me on my NX-OS 9K:

```python
from getpass import getpass
from netmiko import ConnectHandler

device = {
    "device_type": "cisco_nxos",
    "host": "nxos1.domain.com",
    "username": "pyclass",
    "password": getpass(),
    "fast_cli": False,
    "session_log": "session.out",
}

command = "show run | xml | no-more"
with ConnectHandler(**device) as net_connect:
    print(net_connect.find_prompt())
    output = net_connect.send_command(command, delay_factor=4)

print(output)
```

**Comment by ktbyers** [comment]
No response to additional questions.
