### ISSUE TITLE
send_command_timing "copy tftp flash" to download sw from tftp server

### ISSUE THREAD

**Issue by umutyasar19** [ktbyers/netmiko#2022]
Hi,
I want to do tftp with the below commands, to download sw from the server.
What can I do to click the enter command after question?

From CLI, Manual config:

R#copy tftp:WANold.pcap bootflash:
Address or name of remote host   ->I need to type ip address for the first command run
Source filename [WANold.pcap]? ->I need to click enter
Destination filename [WANold.pcap]?  -> i need to click enter
Accessing tftp://10.10.12.145/WANold.pcap...
Loading WANold.pcap from 10.10.12.145 (via GigabitEthernet0/0/0): !
[OK - 43655 bytes]

Python Script:

```python
net_connect = Netmiko(**host1)
command1 = ("copy tftp:WANold.pcap bootflash:")  # Enter set of commands

print("Connected to:", net_connect.find_prompt())             # Display hostname
output = net_connect.enable()
print(net_connect.find_prompt())

Tftp_server = "10.10.12.145"

output = net_connect.send_command_timing(command1)
if 'Address or name of remote host' in output:
    output += net_connect.send_command_timing(Tftp_server)
if 'Source filename' in output:
    # switch back to send_command() here as this might be slow
    output += net_connect.send_command()
if 'Destination filename' in output:
    # switch back to send_command() here as this might be slow
    output += net_connect.send_command()
net_connect.disconnect()                                        # Disconnect from Session
print(output)
```

Error:

Traceback (most recent call last):
  File "C:\Users\tftp-2.py", line 29, in <module>
    output += net_connect.send_command()
  File "C:\Users\venv\lib\site-packages\netmiko\utilities.py", line 429, in wrapper_decorator
    return func(self, *args, **kwargs)
TypeError: send_command() missing 1 required positional argument: 'command_string'

------------
def select_cmd_verify(func):
    """Override function cmd_verify argument with global setting."""

    @functools.wraps(func)
    def wrapper_decorator(self, *args, **kwargs):
        if self.global_cmd_verify is not None:
            kwargs["cmd_verify"] = self.global_cmd_verify
        return func(self, *args, **kwargs)

**Comment by ktbyers** [comment]
This section probably should be:

```python
if 'Source filename' in output:
    # switch back to send_command() here as this might be slow
    output += net_connect.send_command_timing("\n")
if 'Destination filename' in output:
    # switch back to send_command() here as this might be slow
    output += net_connect.send_command_timing("\n")
```

You will run into an issue just using `send_command` so you should either use `send_command_timing` for this or you should use `send_command` with an `expect_string` argument.

**Comment by ktbyers** [comment]
Here are a couple of similar examples:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-timing

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-expect_string

**Comment by umutyasar19** [comment]
Thanks for that, the examples are very useful.
But I couldn't make it run for me still giving errors. Can you make any assumption by looking at the below codes?

from netmiko import Netmiko
import logging


logging.basicConfig(filename="test.log", level=logging.DEBUG)   # It will log all reads and writes on the SSH channel
logger = logging.getLogger("netmiko")

host1 = {                                                       # Enter Device information
    "host": "192.168.x.x",
    "username": "a",
    "password": "b",
    "device_type": "cisco_xe",
    "global_delay_factor": 0.1,                                   # Increase all sleeps by a factor of 1
}

net_connect = Netmiko(**host1)
command = "copy tftp:WANold.pcap bootflash:"  # Enter set of commands

print("Connected to:", net_connect.find_prompt())             # Display hostname
output = net_connect.enable()
print(net_connect.find_prompt())


output = net_connect.send_command_timing(
    command_string=command,
    strip_prompt=False,
    strip_command=False,
    delay_factor=4
)
if "Address or name of remote host" in output:
    output += net_connect.send_command_timing(
        command_string="192.168.y.y",
        strip_prompt=False,
        strip_command=False
    )
if "Source filename" in output:
    output += net_connect.send_command_timing(
        command_string="/n",
        strip_prompt=False,
        strip_command=False
    )
if "Destination filename" in output:
    output += net_connect.send_command_timing(
        command_string="/n",
        delay_factor = 4
    )
net_connect.disconnect()                                        # Disconnect from Session
print()
print(output)
print()

**Comment by umutyasar19** [comment]
The output is like below, seems a timing problem but I put the delay factor.

copy tftp:WANold.pcap bootflash:
Address or name of remote host []? 192.168.y.y
Destination filename [WANold.pcap]? Accessing tftp://192.168.y.y/WANold.pcap...


Process finished with exit code 0

**Comment by umutyasar19** [comment]
Hi Kirk,

I used a different command format and worked this time, thank you for the examples, they're helping me a lot.
Do you know somewhere that I can find paramiko examples as well?
