### ISSUE TITLE
Show commands text template

### ISSUE THREAD

**Issue by maazjaved882** [ktbyers/netmiko#2024]
is there any way to use a text template with more then 1 cli show commands in netmiko? i saw the example in config_change_file.py but I wanna try this specifically using a text file with cli chow commands.

**Comment by ktbyers** [comment]
@maazjaved882 Can you provide more context on what you are trying to do? Text template--meaning TTP or something else?

**Comment by maazjaved882** [comment]
so basically i have a script that i can use to loop through a csv and output a show command. I want to basically use a text file with more then one show command that can be out put using this script below. In the line command = "show ip int breif" 
I want to use a text file file with more then one command to be output by the script.

import os
import sys
from getpass import getpass
from netmiko import ConnectHandler
from csv import reader

password = getpass()

#modify the path of the csv file 
with open('C:/Users/u28057/Desktop/nxos.csv', 'r') as read_obj:
    # pass the file object to reader() to get the reader object
    csv_reader = reader(read_obj)
    # Iterate over each row in the csv using reader object
    counter = 0
    for row in csv_reader:
        # row variable is a list that represents a row in csv
        if (counter !=0 ) :
            cisco = {
                'device_type': 'cisco_nxos',
                'ip': row[0],
                'username': 'u28057',
                'password': password,
            }

            print(cisco)

            command = "show ip int brief"

            with ConnectHandler(**cisco) as net_connect:
                output = net_connect.send_command(command)

            print()
            print(output)
            print()


        counter = counter + 1

**Comment by ktbyers** [comment]
Sure just read the file of commands and then send the commands down the channel. Probably make a dictionary where the key is the command name and the response is the corresponding value.

Note, you will want to establish the SSH connection first (or worded differently, you do NOT want to establish a new SSH connection for each command).


Regards, Kirk
