### ISSUE TITLE
 in _read_channel_expect     "Timed-out reading channel, data not available

### ISSUE THREAD

**Issue by jj-jj-j** [ktbyers/netmiko#2025]
Hello Team,

I getting this error while try to remove ip with subnet from object group of ASA firewall, using python script.
I adjusted delay factor 2,4 and 8, no luck, and tried keeping the cmd_verify to false but still , no luck.
    firewall_list = {
        'device_type': 'cisco_asa',
        'ip': asa_ip,
        'username': username,
        'password': password,
        'secret': password,
        'global_cmd_verify':False,
        'session_log':'output.txt'
        }

**Comment by vivekj1922** [comment]
Error,



22:14:16 | Traceback (most recent call last):
-- | --
22:14:16 | File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
22:14:16 | out = self.in_buffer.read(nbytes, self.timeout)
22:14:16 | File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
22:14:16 | raise PipeTimeout()
22:14:16 | paramiko.buffered_pipe.PipeTimeout
22:14:16 |  
22:14:16 | During handling of the above exception, another exception occurred:
22:14:16 |  
22:14:16 | Traceback (most recent call last):
22:14:16 | File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 569, in _read_channel_expect
22:14:16 | new_data = self.remote_conn.recv(MAX_BUFFER)
22:14:16 | File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
22:14:16 | raise socket.timeout()
22:14:16 | socket.timeout
22:14:16 |  
22:14:16 | During handling of the above exception, another exception occurred:
22:14:16 |  
22:14:16 | Traceback (most recent call last):
22:14:16 | File "/tmp/879-8927821-DNE-Worker-Node-dev-dispatch-script.tmp.sh", line 116, in <module>
22:14:16 | ftp_add_or_remove(ip,"csg-ftp1_customers_sftp",add_or_remove_frm_grp)
22:14:16 | File "/tmp/879-8927821-DNE-Worker-Node-dev-dispatch-script.tmp.sh", line 44, in ftp_add_or_remove
22:14:16 | remove_ip = net_connect.send_config_set(config_ftp)
22:14:16 | File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1859, in send_config_set
22:14:16 | new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
22:14:16 | File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 646, in read_until_pattern
22:14:16 | return self._read_channel_expect(*args, **kwargs)
22:14:16 | File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 580, in _read_channel_expect
22:14:16 | "Timed-out reading channel, data not available."
22:14:16 | netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
Which version of Netmiko are you using?

Also you need to include your full code including the configuration commands you are sending.


Kirk

**Comment by jj-jj-j** [comment]
@ktbyers 
[git_ftp.txt](https://github.com/ktbyers/netmiko/files/5491894/git_ftp.txt)-----code
[output.txt](https://github.com/ktbyers/netmiko/files/5491897/output.txt)------output

Adding into the object group happening fine , but when I remove the same, host is removing fine but while removing subnet, its throwing error, but the subnet got removed, its not going for next ip

Adding ip/subnet happening fine,
object-group network test1-ftp1_customers_sftp
  network-object host 1.1.1.2
 end

object-group network test1-ftp1_customers_sftp
 network-object 3.2.0.0 255.255.240.0
 end

object-group network test1-ftp1_customers_sftp
  network-object host 3.3.3.4
 end

While removing host removal happening fine but, removing subnet creating problem

object-group network test1-ftp1_customers_sftp
  no network-object host 1.1.1.2
 end

object-group network test1-ftp1_customers_sftp
 no network-object 3.2.0.0 255.255.240.0---------------stops here and throws error--------------------not going next line-----
 end

object-group network test1-ftp1_customers_sftp
  no network-object host 3.3.3.4
 end

**Comment by jj-jj-j** [comment]
>>> print(paramiko.__version__)
2.7.2
>>> print(netmiko.__version__)                                                                                                                                                                                          
3.3.2
>>>

**Comment by ktbyers** [comment]
Try setting this argument:
 
allow_auto_change=True

```python
firewall_list = {
    "device_type": "cisco_asa",
    "ip": asa_ip,
    "username": username,
    "password": password,
    "secret": password,
    "allow_auto_change": True,
    "session_log": "output.txt",
}
```

Or alternatively in your send_config_set() call add the following argument `cmd_verify=False`

**Comment by jj-jj-j** [comment]
Hi ktbyers,
Thank you So much, both worked perfect.
Could you tell me, What is this "allow_auto_change", what it will do? is it same as "cmd_verify", but globally applied ?
Also do you have any suggestion for me to use in timeout setting or any other setting like ""allow_auto_change": True" , need it for long term stable running, because we are integrating this code with automation engines like jenkins to execute whenever the request comes in.

**Comment by jj-jj-j** [comment]
@ktbyers 
Hi ktbyers,
Thank you So much, both worked perfect.
Could you tell me, What is this "allow_auto_change", what it will do? is it same as "cmd_verify" ?
Also do you have any suggestion for me to use in timeout setting or any other setting like ""allow_auto_change": True" , need it for long term stable running, because we are integrating this code with automation engines like jenkins to execute whenever the request comes in.

**Comment by ktbyers** [comment]
ASAs have this bad idea where setting the terminal width is a configuration change. And Netmiko needs to set the terminal width to work properly.

But some people do not like Netmiko automatically changing the config (for the terminal width). So I defaulted it to not change the config.

`allow_auto_change=True` allows Netmiko to automatically change the terminal width setting on the ASA.

There is a good chance I will change this back to being the default (as I value Netmiko `just working` more).

**Comment by ktbyers** [comment]
I did change the ASA back to default to allow_auto_change = True. This is the case in Netmiko 4.0.0 and later. Would have to dig more to see when exactly it changed, but it is set in the 4.0.0 code.

**Comment by jj-jj-j** [comment]
Hi ktbyers,
Hope you are doing good!
Thank you for the update, so new 4.0.0 will not automatically adjust width, because it is making change in standby unit of ASA, that is kind of flaw and also show commands should not change any configuration,  so where I have to set this parameter to false?

regards,
Vivek J

**Comment by ktbyers** [comment]
Yeah, I disagree with you on this: `show commands should not change any configuration`. Netmiko by design will change the terminal width and disable output paging.

But at least for the ASA case, you can disable this behavior as per the above.
