### ISSUE TITLE
Netmiko dropping output lines on HP Comware switch

### ISSUE THREAD

**Issue by ludesdeveloper** [ktbyers/netmiko#2026]
Hi Kirk and Friends,

I have issue with output hp switch,

i used device_type hp_procurve & hp_comware

If I do manual capture with putty it has 531703 lines.

If I do with netmiko, with both device type, it has around 73 thousands lines.

There are no error happen, connection just closed and go to the next device.

If there is log for me to share i would likely share it for you.

Is there any limitation lines for netmiko or something like that?

Thanks a lot

**Comment by ktbyers** [comment]
You didn't really provide what I asked for yesterday in Slack which was a much more limited use case where you are having lines that are dropped. There is not really anything I can do with the above problem description.

You need to start with a use case where the output is less than 50 lines and whether any lines are being dropped.

OR you need to provide one or two lines that are being dropped in your above situation i.e. what the lines actually are in the CLI and what Netmiko is showing you in the output.

You stated above that you used `device_type` of ProCurve and Comware--what type of device do you actually have?

**Comment by ludesdeveloper** [comment]
Hi Kirk,

This is information form putty, so i choose hp_comware to capture:
HPE Comware Software, Version 7.1.045

This is my code:
`                                output = net_connect.send_command("display diagnostic-information", expect_string="[Y/N]")
                                print("display diagnostic-information")
                                print(output)
                                write.write("display diagnostic-information"+"\n")
                                write.write(output+'\n')
                                output = net_connect.send_command("N\n", expect_string="<")
                                write.write(output+'\n')
                                print(output)`

These are last line i capture with netmiko:

1st
<4>[    0.000000]     0:        0 ->    15360
<4>[    0.000000]     0:    32768 ->   278528
<7>[    0.000000] 0:On node 0 totalpages: 2

2nd
1   0    199      8/620  <-    8/20203  0        ffffff81 ffffff81 ffffff81 0   
1   0    307      8/20203->    8/620    8        ffffff80 ffffff80 ffffff80 0   
1   0    194      8/10523<-    8/20200  0        23c      23c

3rd
1   0    321      8/20917->    8/3173   0        ffffff80 ffffff80 ffffff80 0   
1   0    194      8/10523<-    8/20909  0        ffffff81 ffffff81 ffffff81 0   
1   0    325      8/20909->    8/1052

4th
1   0    305      8/3173 <-    8/61346  0        4        ffffff81 0   810000
1   0    101225     8/61346->    8/3173   0        4        ffffff92 0    10000
1   0    194

5th
1   0    102635     8/53261->    8/10523  0        4        ffffff82 0    10000
1   0    305      8/3173 <-    8/53259  0        4        ffffff81 0   810000
1   0    102636     8/53259->    8/3173   0        4        ffffff92 0

**Comment by ktbyers** [comment]
What does this look like normally? What should it look like?
