### ISSUE TITLE
No module name netmiko on Centos

### ISSUE THREAD

**Issue by william48110651** [ktbyers/netmiko#2031]
### I kept get below message when I was using Python(2.7.5).
![image](https://user-images.githubusercontent.com/70486965/98424374-30543280-2057-11eb-958b-9149f03f18ee.png)

###  If I used Python(3.6.8), it will be this.
![image](https://user-images.githubusercontent.com/70486965/98424488-74dfce00-2057-11eb-96c0-442a76233b0f.png)

### I have verified that I did install netmiko.
![image](https://user-images.githubusercontent.com/70486965/98424597-bec8b400-2057-11eb-8187-36e490e31452.png)

### I kindly appreciate your answer!!!!

**Comment by ktbyers** [comment]
It looks like you have Netmiko installed for Python 2.7, but Netmiko requires Python 3.6 or greater.

Your Python 3.6 does not have it installed.

The PIP you are using is the Python 2.7 PIP and not the Python 3.6 PIP.


Regards, Kirk

**Comment by william48110651** [comment]
Hi Kirk

I tried update both  Python 2.7 PIP and Python 3.6 PIP.
![image](https://user-images.githubusercontent.com/70486965/98427024-030c8200-2061-11eb-9962-e6616d9419da.png)
![image](https://user-images.githubusercontent.com/70486965/98427032-0d2e8080-2061-11eb-8c40-85c7aa29bbd4.png)

But the issue is still there. (same error code)
Did I do something wrong?

Best, Chien

**Comment by ktbyers** [comment]
You upgraded PIP, but you didn't actually install Netmiko for your Python3 environment. You probably need to do:

```
python3 -m pip install netmiko
```

**Comment by william48110651** [comment]
Hi Kirk

Thank you so much. It works this time.

By the way, since I have Python 3 installed on Centos, do you think is it a good idea to remove Python 2?

**Comment by ktbyers** [comment]
No, I wouldn't remove Python2. I would instead use Python virtual environments and decouple from the system Python.
