### ISSUE TITLE
Unable to import ConnectHandler or Netmiko from netmiko

### ISSUE THREAD

**Issue by garrettwilliamson11** [ktbyers/netmiko#2034]
Kinda crazy getting shot in the foot on line 1! 

Just simply trying a:

from netmiko import ConnectHandler

OR

from netmiko import Netmiko

Neither of these work. Very puzzling, as I've used Netmiko in the past and have never seen this issue. I also checked that I didn't create a file named 'netmiko.py'. No such file exists. This is the error I'm seeing:
``
![image](https://user-images.githubusercontent.com/74317706/98842556-c0a7c400-2417-11eb-8d99-1c2fab6a4ba7.png)

Any advice would be greatly appreciated.

**Comment by garrettwilliamson11** [comment]
I should also mention, I did look through issue #321, and followed the steps suggested there, with no luck.

![image](https://user-images.githubusercontent.com/74317706/98844186-fbaaf700-2419-11eb-85a2-9d5cc94cdbff.png)

After uninstalling and reinstalling netmiko, I'm now unable to even import netmiko at all! Getting the same error as above.

**Comment by garrettwilliamson11** [comment]
Alright, I went ahead and downgraded my netmiko version to 2.4.2 (pip3 install netmiko==2.4.2)

That seems to have cleared the issue. I'm curious to hear if anyone knows the reason? Is there a compatability issue btwn Python3.8.2 and Netmiko 3.3.2?

**Comment by ktbyers** [comment]
Your original issue looks like you didn't have the "tenacity" library installed. This library should have been automatically installed when you installed Netmiko.

So I would try to `pip3 install netmiko==3.3.2` and see if you see the same issue or not.

```
$ ipython
Python 3.8.5 (default, Sep 14 2020, 19:19:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from tenacity import retry, stop_after_attempt, wait_exponential
```

**Comment by garrettwilliamson11** [comment]
No luck! Back to 3.3.2, still getting the same error as above when importing netmiko. I should mention this is on the same machine we were discussing on Slack. Rolling back to 2.4.2 had solved this 'tenacity' problem, but introduced the 'EIGHTBITS' problem:

![image](https://user-images.githubusercontent.com/74317706/98889612-43586f80-2468-11eb-829a-588e39b4b087.png)

I'm going to spin up a new vm, start from 0 and see if it crops up again. I'll post results.

**Comment by ktbyers** [comment]
That looks like you have some issue with pyserial:

```
$ pip list | grep pyserial
pyserial                     3.4

$ ipython
Python 3.8.5 (default, Sep 14 2020, 19:19:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import serial

In [2]: serial.EIGHTBITS
Out[2]: 8
```

**Comment by garrettwilliamson11** [comment]
Started with a fresh vm, couldn't replicate the issue. I musta had something hosed. *shrugs* Thanks for the help!
