### ISSUE TITLE
Several Timeout on Netmiko

### ISSUE THREAD

**Issue by Nadir-Urbina** [ktbyers/netmiko#2035]
Hi There!

I hope all is well and safe,

So I have this code:

```python
from time import sleep
from getpass import getpass
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException

username = input("Enter your SSH username: ")
password = getpass()
with open("commands_file") as f:
    commands_list = f.read().splitlines()
with open("devices_file") as f:
    devices_list = f.read().splitlines()
for devices in devices_list:
    print('Connecting to device" ' + devices)
    ip_address_of_device = devices
    ios_device = {
        "device_type": "cisco_ios",
        "ip": ip_address_of_device,
        "username": username,
        "password": password,
    }
    try:
        net_connect = ConnectHandler(**ios_device)
    except (AuthenticationException):
        print("Authentication failure: " + ip_address_of_device)
        continue
    except (NetMikoTimeoutException):
        print("Timeout to device: " + ip_address_of_device)
        continue
    except (EOFError):
        print("End of file while attempting device " + ip_address_of_device)
        continue
    except (SSHException):
        print("SSH Issue. Are you sure SSH is enabled? " + ip_address_of_device)
        continue
    except Exception as unknown_error:
        print("Some other error: " + str(unknown_error))
        continue
    # Add the DNS Device name to the list in "commands_list"
    commands_list.insert(
        2, "crypto key generate rsa general-keys modulus 2048 label " + devices
    )
    for command in commands_list:
        if devices:
            print("================================")
            print("Applying command: " + command)
            sleep(2)
            print("================================")
            print("Waiting for command to be applied")
            print("================================")
            print("Commands applied", command)
    output = net_connect.send_config_set(command_file)
    commands_list.pop(2)  # Remove the DNS Device name from the list in "commands_list"
    print("================================")
    print(output)

```

All works well on the first device from my list, once I reach the second device it fails with the following erros:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "custom_config_push.py", line 50, in <module>
    output = net_connect.send_config_set(commands_list)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1868, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 646, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 579, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Once I even the command again, it fails from the very first device until I manually edit the list of commands to send.

Thank you for your help in advance!

**Comment by ktbyers** [comment]
Your code above looks wrong:

```
    output = net_connect.send_config_set(command_file)
```

The variable command_file doesn't exist in your send_config_set line.

**Comment by Nadir-Urbina** [comment]
Hi Kirk, yes I am sorry I did send a wrong version of my code, I did corrected that using:

output = net_connect.send_config_set(commands_list)

Which is defined at the beginning of the code, what I find really odd is that it works the first time on the first device, second device on the list "devices_list" it fails, if I try to run it again it fails from the first device on the list with the same error I shared.

**Comment by Nadir-Urbina** [comment]
Update: I modified my code and leave it like this:

from getpass import getpass
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException

username = input('Enter your SSH username: ')
password = getpass()

with open('commands_file') as f:
    commands_list = f.read().splitlines()

with open('devices_file') as f:
    devices_list = f.read().splitlines()

for devices in devices_list:
    print ('Connecting to device" ' + devices)
    ip_address_of_device = devices
    ios_device = {
        'device_type': 'cisco_ios',
        'ip': ip_address_of_device,
        'username': username,
        'password': password
    }

    try:
        net_connect = ConnectHandler(**ios_device)
    except (AuthenticationException):
        print ('Authentication failure: ' + ip_address_of_device)
        continue
    except (NetMikoTimeoutException):
        print ('Timeout to device: ' + ip_address_of_device)
        continue
    except (EOFError):
        print ('End of file while attempting device ' + ip_address_of_device)
        continue
    except (SSHException):
        print ('SSH Issue. Are you sure SSH is enabled? ' + ip_address_of_device)
        continue
    except Exception as unknown_error:
        print ('Some other error: ' + str(unknown_error))
        continue
    except Exception as unknown_error:
        print ('Some other error: ' + str(unknown_error))
        continue
    # Add the DNS Device name to the list in "commands_list"
    commands_list.insert(2, "crypto key generate rsa general-keys modulus 2048 label " + devices)
    output = net_connect.send_config_set(commands_list)
    commands_list.pop(2) # Remove the DNS Device name from the list in "commands_list"
    print (output)



on this one once I reach the 5th device on my list I get the following:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/lib/python3/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nurbinabr/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "config_push-1.py", line 48, in <module>
    output = net_connect.send_config_set(commands_list)
  File "/home/nurbinabr/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1868, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/home/nurbinabr/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 646, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/nurbinabr/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 579, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
You probably need to include the Netmiko log file so I can see more details about what is going on:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by ktbyers** [comment]
Additional information is missing.
