### ISSUE TITLE
send_config_set fails on long commands for Cisco ASA

### ISSUE THREAD

**Issue by ganeshprashanthar** [ktbyers/netmiko#2039]
Here is the config set that I am tying to send it to ASA firewall. 
!
object-group network COMMVAULT_CUSTOMERS
no network-object object 20.20.20.20_SCTASK0012345
exit
no object network 20.20.20.20_SCTASK0012345
end
!
It is Cisco ASAv10 with Software Version 9.12(4)

Command execution fails because of this reason.

PYTHON(config)# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'object-group network COMMVAULT_CUSTOMERS\n'
DEBUG:netmiko:Pattern is: object\-group\ network\ COMMVAULT_CUSTOMERS
DEBUG:netmiko:_read_channel_expect read_data: object-group network COMMVAULT_CUSTOMERS

PYTHON(config-network-object-group)# 
DEBUG:netmiko:Pattern found: object\-group\ network\ COMMVAULT_CUSTOMERS object-group network COMMVAULT_CUSTOMERS

PYTHON(config-network-object-group)# 
DEBUG:netmiko:write_channel: b'no network-object object 20.20.20.20_SCTASK0012345\n'
DEBUG:netmiko:Pattern is: no\ network\-object\ object\ 20\.20\.20\.20_SCTASK0012345
DEBUG:netmiko:_read_channel_expect read_data: no network-object object 20.20.20.20_SCTAS$.20.20.20_SCTASK                         0012345no network-object object 20.20.20.20_SCTA$

Usually Cisco also truncate the lengthy line with $. I am also referring #1058 but could not resolve. 
![ASA](https://user-images.githubusercontent.com/66072831/99185257-9daa4680-276e-11eb-84fe-0b41fe4379c4.PNG)

Here is my code snippet and catching some general exceptions. 

delobject = object 20.20.20.20_SCTASK0012345

cmds = ['object-group network COMMVAULT_CUSTOMERS',
                'no network-object object %s'%(delobject),
                'exit',
                'no object network %s'%(delobject),
                'end']

_loginFunction(cmds)

def _loginFunction (cmdset):
    cisco_asa = {
        'device_type': 'cisco_asa_ssh',
        'ip':   '192.168.11.132',
        'username': 'cisco',
        'password': 'cisco',
        'port' : 22,          # optional, defaults to 22
        'secret': 'cisco',     # optional, defaults to ''
        'verbose': False,       # optional, defaults to False
        #'global_delay_factor': 2
    }
    try:
        net_connect = ConnectHandler(**cisco_asa)
    except Exception:
            sys.exit("Could not connect to devices. Check device status and your credential")
    try:
        output = net_connect.send_config_set(cmdset)
        net_connect.disconnect()
    except Exception:
            sys.exit("Could not execute the command")
    return output

**Comment by ktbyers** [comment]
Can you try setting:

`allow_auto_change=True` as an argument ConnectHandler?

This will set the terminal width.

**Comment by ganeshprashanthar** [comment]
> Can you try setting:
> 
> `allow_auto_change=True` as an argument ConnectHandler?
> 
> This will set the terminal width.

Thank You. It worked.
