### ISSUE TITLE
one command cli output is mixing with another command cli output on cisco network device using netmiko

### ISSUE THREAD

**Issue by viswanath-angajala** [ktbyers/netmiko#2040]
Hi All, 

I am using netmiko library to connect to the cisco network devices and executing the cli commands ( output = self.remote.**send_command_timing**(command, strip_command=True, strip_prompt=True, delay_factor=cisco_command_timeout)) sequentially one after the other using same netmiko session for all the list of commands. I am getting the output of one command to another command cli output. Is there any solution to fix this issue and also the command time out issue?

Thanks in Advance,
Viswanath Angajala

**Comment by ktbyers** [comment]
You need to include an actual example of this happening including the relevant log file. 

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Note, keep the example simple that demonstrates the underlying problem.


Regards, Kirk
