### ISSUE TITLE
Unable to send config commands to Cisco ASR5500

### ISSUE THREAD

**Issue by dougchristensen** [ktbyers/netmiko#2041]
Hello Kirk,

I am trying to use Netmiko 3.2.0 to send config commands to a Cisco ASR5500 running StarOS 21.14.b19.  I am able to connect to the node, and I can run standard show commands, but I keep getting an error "ValueError: Failed to enter configuration mode" when trying to run the command in using the following code.  I've taken out any proprietary information using ######, but I know the context is correct.

 config_commands = ['context ######',
                                    'apn #######']
 gw.send_config_set(config_commands)

I'm not sure why this code is failing, any insight you could provide would be appreciated.  Thank you.

**Comment by ktbyers** [comment]
Switching `context` changes the prompt, which breaks the pattern that Netmiko is expecting to see.

You probably would need to do something more like:

```python
net_connect.send_command("context foo", expect_string=r"pattern")   # where 'pattern' is something in the new prompt
net_connect.set_base_prompt()
net_connect.send_config_set(config_commands)
```
