### ISSUE TITLE
Dell OS10 devices are not detected by ssh_autodetect.py

### ISSUE THREAD

**Issue by rasanentimo** [ktbyers/netmiko#2044]
### Steps to Reproduce
Run ssh_autodetect against switch with Dell OS10.

### Expected and Actual Results
ssh_autodetect should return dell_os10 as OS but it's not detected.

The current search pattern in ssh_autodetect is 

"Dell EMC Networking OS10-Enterprise"

However, the corresponding line in the [documentation](https://www.dell.com/support/manuals/fi-fi/networking-z9100/os10-enterprise-user-guide-10.4.0e-r3-pub/show-version?guid=guid-932e4f82-8ac1-4dd1-b782-00254ad8e9f6&lang=en-us) is:

"Dell EMC Networking OS10 Enterprise" 

i.e. without the '-'
```
Dell EMC Networking OS10 Enterprise
Copyright (c) 1999-2018 by Dell Inc. All Rights Reserved.
OS Version: 10.4.0E(R3)
Build Version: 10.4.0E(R3.221)
Build Time: 2018-03-25T22:20:52-0700
System Type: Z9100-ON
Architecture: x86_64
Up Time: 02:22:09
```

I also verified the same on the all Dell OS10 versions which I have access. 

### Proposed solution

Change "Dell EMC Networking OS10-Enterprise" to "Dell EMC Networking OS10 Enterprise"  on search pattern. 

if there are some OS10 devices/SW version which has '-' on the output, then the search pattern should be changed from 
 "Dell EMC Networking OS10-Enterprise" to "Dell EMC Networking OS10"

@skg-net could you comment?

**Comment by ktbyers** [comment]
FIXED here:

https://github.com/ktbyers/netmiko/pull/2047
