### ISSUE TITLE
Nornir/Netmiko Cisco ASA in Multicontext Mode File Transfer

### ISSUE THREAD

**Issue by paff-9299** [ktbyers/netmiko#2049]
Hello,

Im running into a bit of trouble using both Nornir as a framework and Netmiko as the task to transfer an ASA image to my multicontext ASA. Every time I attempt to upload code in this way, I get an error stating the following:

'ValueError: Unexpected output from check_file_exists'

I believe this to an issue with the device attempting to check the management context for available space but since those commands are typically ran in system instead of the management context in Multicontext mode, I believe the scp_handler.py scrip is failing in netmiko. Is it possible to bypass the check_file_exists task?

**Comment by ktbyers** [comment]
@paff-9299 Can you include the code, full exception stack, and the session_log file?


Regards, Kirk
