### ISSUE TITLE
How to send commands faster?

### ISSUE THREAD

**Issue by stvnkem** [ktbyers/netmiko#2051]
Hi,

I am trying to catch an issue which is only visible for a very short time, therefore I need to repeatedly send a command at the highest rate.

There are some commands which can be sent every 0.7 seconds, but there are much faster/slower commands too.

How can I instruct Netmiko to send commands as fast as possible?

Thanks!

**Comment by ktbyers** [comment]
Make a for-loop and use `write_channel()`
