### ISSUE TITLE
Traceroute timeout

### ISSUE THREAD

**Issue by tars01** [ktbyers/netmiko#2055]
Hi Kirk

I am running traces to multiple devices. Some work, some time out for ages. I want to be able to ctrl+shift+6_x when it fails more than 4 or 5 hops. 

I found a few bits of info about it that you also commented on here:
https://www.reddit.com/r/networking/comments/c73odu/netmiko_question_how_to_send_ctrlc_to_cisco/

One example given is:
```
command = device.send_command('traceroute 10.1.1.2 source-interface vlan 100', expect_string='[0-9]{1,3}  \* \* \*')
device.send_command_timing('\x036')
```

You have given this example:

```
net_connect = ConnectHandler(**device)
pattern = re.escape('*')
output = net_connect.send_command("traceroute 80.80.80.80", expect_string=pattern)
net_connect.write_channel(CNTL_SHIFT_6)
```

Could you elaborate a bit on how that would work? The expect string is * but the majority of time the script won't time out so there won't be a * or multiple stars in the output. Won't that cause netmiko to think the command has not finished executing?

Also, for both examples it sends ctrl+shift+6x regardless of it it failed or not? Unless I'm missing something.

Thank you

**Comment by ktbyers** [comment]
Purging old issues...
