### ISSUE TITLE
write mem, save_config and delay_factor issues

### ISSUE THREAD

**Issue by unifiedjd** [ktbyers/netmiko#2058]
Long read, I apologize up front.

Here is a snippet of the WORKING code I am using (commented sections are in there for testing):

        # The rest of the device config was omitted
        device['session_log'] = 'netmiko.log'
        device['global_delay_factor'] = 5
        connection = netmiko.ConnectHandler(**device)
        response = ''
        response += connection.send_config_set(lines)
        # response += connection.save_config()
        response += connection.send_command('write memory', strip_prompt=False, strip_command=False, delay_factor=5)
        print(response)

        # Disconnect while you run through logic
        connection.disconnect()

This code works when the global_delay_factor is present, but fails when it relies on the delay_factor as a parameter of the send_command.  Here are the details:

I'm having issues with handling a save_config or write memory command on an IOS router when the router takes the additional action of copying the config to an FTP server.  The output of the router looks like this during a normal SSH session:

        Router#write memory
        Building configuration...
        Compressed configuration from 29669 bytes to 8120 bytes[OK]
        Writing RouterNov-27-09-53-22.289-12
        Router#

(total operation takes about 15 seconds)

The error is: OSError: Search pattern never detected in send_command

If I DO NOT have the global_delay_factor property set, the error is present. It is present if I use save_config or send_command with delays SET, using expect_string or no expect_string.  Here is the session log during those tests:

        Router#write memory
        Building configuration...

However, if I set the global_delay_factor >=5, all commands work EXCEPT send_command_timing, which produces the following session_log (this log looks the same either way):

        Router#write memory
        Building configuration...
        exit

The two issues I see, and I am not sure if they are directly related, are:
- The delay_factor in the send_command is not being honored for this write memory operation. Essentially the "delay_factor=5" argument is ignored.
- It appears as though the library sees the end of the output after the "Building configuration..." line and expects to return the base prompt. It isn't waiting for the next operation which is the FTP copy.

I recognize that setting the global_delay_factor solves the issue, but I am trying to keep everything as clean as possible and optimize performance.

**Comment by ktbyers** [comment]
Try setting the following (this is an argument to ConnectHandler):

```
fast_cli = False
```

And then do:

```
response += connection.send_command('write memory', strip_prompt=False, strip_command=False, delay_factor=5)
```

You shouldn't need to set global_delay_factor after you set fast_cli=False. Note, setting fast_cli=False will slow things down quite a bit however.

Probably for better performance, you could toggle fast_cli off/on before and after `send_command` call.

The reasons for all of the above are long and contorted. I will try and get that all fixed in Netmiko 4.x.

**Comment by ktbyers** [comment]
Let me know if what I posted above...works.

**Comment by unifiedjd** [comment]
Can I set that as a property just prior? connection.fast_cli = False?

**Comment by ktbyers** [comment]
Yep...should be able to do that.

```
netmiko_object.fast_cli = False
... your send_command
netmiko_object.fast_cli = True
```

Basically for some convoluted reasons, `fast_cli` affects the behavior of the global_delay_factor and delay_factor. And fast_cli now defaults to True for IOS.

**Comment by unifiedjd** [comment]
Both commands work without requiring a delay_factor (disregard the comment, there for testing):

        connection.fast_cli = False
        # response += connection.send_command('write memory', strip_prompt=False, strip_command=False)
        response += connection.save_config()
        connection.fast_cli = True

This is a great workaround and the performance is still good, especially with the ability to remove that delay_factor. Can you modify the fast_cli behavior in the save_config() function for IOS?

I'll be running the same script against a set of NXOS switches shortly with the same FTP process for config changes and will respond if I face a similar issue.

Thank you for the prompt help!

**Comment by ktbyers** [comment]
Yeah, I wouldn't modify the underlying the `save_config()` as it should be fixed in Netmiko 4.x (and the TFTP transfer on wr mem is unusual i.e. that is just not that common). So you would need to use the above workaround until Netmiko 4.X.

Yeah, you might run into similar issues with NX-OS since it now also defaults to fast_cli=True.
