### ISSUE TITLE
TextFSM template for HPE/Aruba show port-access config command

### ISSUE THREAD

**Issue by pfillips** [ktbyers/netmiko#2060]
Hello all,

We have a requirement to identify if dot1x is enabled on Aruba 2930 series switches. Normally it is straightforward for any command if FSM template is available. But the command that we plan to use to identify the dot1x "show port-access config" doesn't have a template. I tried to create one but don't have understanding on the subject and it is failing with blank output. Attached is the output of the command. Appreciate if anyone can assist with providing a TextFSM template to generate an output with port number and Dot1x auth status. Thank you

![CMD](https://user-images.githubusercontent.com/75084901/100518529-5a9a9b00-3192-11eb-8c33-f0001be05a42.png)

**Comment by ktbyers** [comment]
Yeah, we can't really do the parsing for you. I cover this to a certain extent in one of my courses: https://pynet.twb-tech.com/class-pyauto.html

But it is pretty hard and there is a pretty big ramp up to it.

You might want to look at Text Template Parsing for the above, it is probably easier than TextFSM for that output. I have some videos on TTP here:

https://pynet.twb-tech.com/videos/ttp/ttp.html
