### ISSUE TITLE
Q: Ansible anounces libssh to replace paramiko in netcommon collection.

### ISSUE THREAD

**Issue by pszulczewski** [ktbyers/netmiko#2061]
Source: https://www.ansible.com/blog/new-libssh-connection-plugin-for-ansible-network

Dear Kirk, can you plese share your perspective how it may impact netmiko in the long run?

**Comment by ktbyers** [comment]
It should impact Netmiko i.e. Netmiko will continue to use Paramiko for the foreseeable future.


Regards, Kirk
