### ISSUE TITLE
Huawei S5700 - Crash string index out of range

### ISSUE THREAD

**Issue by stijnvbb** [ktbyers/netmiko#2064]
Hi All,

I'm getting the following error "string index out of range" once I'm running my script on Huawei devices (switches: S5700 series):

```
import pandas as pd
from netmiko import ConnectHandler
from termcolor import colored


location = TEST

devices_huawei = pd.read_excel(r'path\to\file\huawei-devices.xlsx', sheet_name=location)
info_huawei = pd.DataFrame(devices_huawei, columns=['HOSTNAME', 'IP', 'CONNECTED'])

username = XXX
pwd = XXX

for index, row in info_huawei.iterrows():

    device = {
        'device_type': 'huawei_vrpv8',
        'ip': row["IP"],
        'username': username,
        'password': pwd,
        'verbose': False,
    }
    net_connect = ConnectHandler(**device)
    net_connect.set_base_prompt()

    output = net_connect.send_command("dis curr | include 1209600")
    text = colored("success", 'green')
    text2 = colored("error", 'red')
    text3 = colored("bigger", 'blue')

    if output.count("1209600") == 2:
        print(row["HOSTNAME"] + " " + row["IP"] + ": " + text)
    elif output.count("1209600") > 2:
        print(row["HOSTNAME"] + " " + row["IP"] + ": " + text3)
    else:
        print(row["HOSTNAME"] + " " + row["IP"] + ": " + text2)
```

It's a very basic script, taking all the IP addresses from an excel file and run some show commands.
But there is a chance of 5 - 10% that the script is failing for unknown reasons. If I re-run the script I don't have any issues anymore.

It fails when it runs the command "net_connect = ConnectHandler(**device)".

Can someone assist me why I'm getting this error ?

```
Traceback (most recent call last):
  File "C:/Users/Stijn/PycharmProjects/KSJ/INFO/CHECK.py", line 24, in <module>
    net_connect = ConnectHandler(**device)
  File "C:\Users\Stijn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\ssh_dispatcher.py", line 312, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\Stijn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 346, in __init__
    self._open()
  File "C:\Users\Stijn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 352, in _open
    self._try_session_preparation()
  File "C:\Users\Stijn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 777, in _try_session_preparation
    self.session_preparation()
  File "C:\Users\Stijn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\huawei\huawei.py", line 13, in session_preparation
    self.set_base_prompt()
  File "C:\Users\Stijn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\huawei\huawei.py", line 84, in set_base_prompt
    if not prompt[-1] in (pri_prompt_terminator, alt_prompt_terminator):
IndexError: string index out of range
```

Furthermore I checked #1905, does a sleep timer of 5 seconds fixed the issue?
Therefore would the [global_delay_factor ](https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html)help us to prevent such problems ?

Thanks in advance for the support!

BR
Stijn

**Comment by ktbyers** [comment]
What does your prompt look like? The above error probably means your prompt came back as a completely empty string (in some context...likely due to a timing issue between Netmiko and the device).

Yes, I would probably try a global delay factor of either 2 or 4.


Regards,

Kirk

**Comment by stijnvbb** [comment]
Hi Kirk,

See image below:

[image: image.png]

I will update the timer and let you know the results.

Thanks, appreciate your work!

KR
Stijn

Op wo 2 dec. 2020 om 16:47 schreef Kirk Byers <notifications@github.com>:

**Comment by ktbyers** [comment]
I am going to close this issue. If you are still running into a problem here, please go ahead and re-open it.
