### ISSUE TITLE
netmiko.ssh_autodetect shows IOSXE as cisco_ios and IOSXR show None 

### ISSUE THREAD

**Issue by muhammad-rafi** [ktbyers/netmiko#2067]
I was writing a program where I can get the os detected and perform the operations as per the platform os type but I found the 'netmiko.ssh_autodetect' detecting the ios-xe as ios though it wont make much different but wonder why and apparently ios-xr showing 'None' 
Here is my simple script snippet 

`from netmiko.ssh_autodetect import SSHDetect`
`from netmiko.ssh_dispatcher import ConnectHandler`
`from getpass import getpass`
`import netmiko`
`import logging`

`logging.basicConfig(filename='test.log', level=logging.DEBUG)`
`logger = logging.getLogger("netmiko")`

`username = input("Pleae enter your username: ")`
`password = getpass("password: ")`

`hosts = ['R1', 'R2']`

`def osdetect():`
	`try:` 
		`for host in hosts:`
			`device = {`
					`'device_type': 'autodetect',`
			        `'host': host,`
			        `'username': username,`
			        `'password': password,`
			        `"secret": password`
			        `}`
			`os_detect = SSHDetect(**device)`
			`best_os_match = os_detect.autodetect()`
			`return f"The device_type of the {host} is {best_os_match}"`
	`except netmiko.ssh_exception.NetMikoTimeoutException:`
	       `exit( '[ERROR:] Connection to ' + host + ' has been timed out.')`

`if __name__ == "__main__":`
	`print(osdetect())`

I have attached the log files for both routers. 
Please advise and let me know if you need more information
[iosxr_logs.log](https://github.com/ktbyers/netmiko/files/5645861/iosxr_logs.log)
[iosxe_logs.log](https://github.com/ktbyers/netmiko/files/5645862/iosxe_logs.log)

**Comment by ktbyers** [comment]
`ios` and `ios_xe` are identical in Netmiko...so autodetect will use the more general `ios` selection.

I think  the IOS-XR issue is likely fixed in the Netmiko `develop` branch (if you want to test that).


Just re-open if there is still an issue here.


Regards, Kirk

**Comment by muhammad-rafi** [comment]
`C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
cisco_ios

C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
cisco_nxos

C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
dell_os10

C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
cisco_asa

C:\Users\rafim1\Downloads>python netmiko_autodetect_2.py
Traceback (most recent call last):
  File "netmiko_autodetect_2.py", line 35, in <module>
    main()
  File "netmiko_autodetect_2.py", line 30, in main
    osdetect(host)
  File "netmiko_autodetect_2.py", line 22, in osdetect
    best_match = os_detect.autodetect()
  File "C:\Users\rafim1\Downloads\netmiko\ssh_autodetect.py", line 286, in autodetect
    accuracy = autodetect_method(**tmp_dict)
TypeError: _autodetect_remote_version() got an unexpected keyword argument 'cmd'`
