### ISSUE TITLE
netmiko paloalto_panos disable_paging

### ISSUE THREAD

**Issue by rapowell** [ktbyers/netmiko#2071]
I thought I read on one of the blogs that disable_paging() would issue the appropriate command for the device specified in the device_type argument that is passed to the ConnectHandler.  When trying this with a PANOS device, the wrong command is being sent:

```
>>> device.disable_paging()
'terminal \r\x1b[Kadmin@LabPanorama1(primary-active)> terminal length \r\x1b[Kadmin@LabPanorama1(primary-active)> terminal length 0\r\nUnknown command: terminal\r\n'
```
It should be sending the command _set cli pager off_

If I misunderstood or if what I read was wrong, is there a way to implement the proper command for PANOS?

Thanks.

**Comment by ktbyers** [comment]
@rapowell This should work:

```
device.disable_paging(command="set cli pager off")
```
