### ISSUE TITLE
Get ouput from Cisco WLC

### ISSUE THREAD

**Issue by pponte81** [ktbyers/netmiko#2077]
I know that this has been analyzed in some other posts, but I was wondering if someone has been able to solve this.
Get some outputs from a Cisco WLC is really disgusting.
I am posting my code, maybe someone can help.
I am trying to get a config from every AP but I am dealing with "Press Enter to continue..."

This code works, but it is really slow. It took me almost three minutes to chek 10 APs, and I have more than 4500 devices.
Yes, I want to improve this if posssible.

Thanks in advance.

`
def chequeo():

    # Chequeo de logg
    print("Chequeando equipos")
    output = "Press Enter"
    max_loops = 10
    contador = 1
    while "Press Enter" in output and contador < max_loops:
        print(f"Chequeando antena {contador}")
        output = connection.send_command_w_enter\
            ('grep include "FlexConnect Vlan mode|Cisco AP Name|IP Address|AP Model" "show access-point-config"')
        if "Disabled" in output:
            lineas = output.splitlines()
            for linea in lineas:
                if linea.startswith("Cisco AP Name"):
                    antena = linea.split()[-1]
                elif linea.startswith("AP Model"):
                    modelo = linea.split()[-1]
                elif linea.startswith("IP Address....."):
                    ip = linea.split()[-1]
            diccionario = {"antena": antena, "modelo": modelo, "ip": ip}
            fallos.append(diccionario)
            print(f"Añadiendo {antena} en la lista")
        contador += 1

`

This is the output from WLC:
`
(Cisco Controller) >

(Cisco Controller) >grep include "FlexConnect Vlan mode|Cisco AP Name|AP Model|IP Address..." "show access-point-config"
Press any key to continue.. 
Cisco AP Name.................................... Hiper_Lucena_Flex_AP13
IP Address Configuration......................... Static IP assigned
IP Address....................................... 10.84.199.33
NAT External IP Address.......................... None
Primary Cisco Switch IP Address.................. 10.71.204.254
Secondary Cisco Switch IP Address................ Not Configured
Tertiary Cisco Switch IP Address................. Not Configured
AP Model......................................... AIR-CAP1702I-E-K9
FlexConnect Vlan mode :.......................... Enabled
Press Enter to continue or <ctrl-z> to abort
 
Cisco AP Name.................................... Market_Ramblas_Flex_AP05
IP Address Configuration......................... Static IP assigned
IP Address....................................... 10.200.51.235
NAT External IP Address.......................... None
Primary Cisco Switch IP Address.................. 10.71.204.254
Secondary Cisco Switch IP Address................ Not Configured
Tertiary Cisco Switch IP Address................. Not Configured
AP Model......................................... AIR-CAP1702I-E-K9
FlexConnect Vlan mode :.......................... Enabled
Press Enter to continue or <ctrl-z> to abort
`

Then I send all to a dataframe and create an excel file to keep all that information.
I am getting an output file (I added all the APs just for testing purposes, the goal is getting just FlexConnect Disabled) like this:

Fecha | antena | ip | modelo
2020-12-19 | Hiper_Lucena_Flex_AP13 | 10.84.199.33 | AIR-CAP1702I-E-K9
2020-12-19 | Market_Alcala396_Flex_AP02 | 10.200.210.232 | AIR-CAP1702I-E-K9

Everything works, just need to know if there is a chance to make it faster.

**Comment by pwiddicombe** [comment]
Sometimes it's better to view from an alternative point.  You might find it's actually faster to:
- config paging disable
- show ap summary; parse that list and create a dictionary for reference
- show ap config general <apname>   for each of them, and parse as you are doing; but picking up flexconnect from "AP mode"

This way, you can use the standard display commands and avoid the paging issue, and should be able to do them a lot faster.  
DO make sure you only connect to (each?) controller once, though, and not in the loop, as that will really drag down your speed.

**Comment by pponte81** [comment]
Hello,
This is how I did it because this has been the fastest way I could find.
I have tried to get this output by using some different commands and I am posting my results.

This was my first try. It works and can get the goal, but it takes more than 5 hours to read 4500 APs. This is not the full program, I write that output to an excel file and send a message to our Microsoft Teams group, but that's not relevant.

`
def conexion_wlc():
    netmiko_exceptions = (netmiko.ssh_exception.NetMikoTimeoutException,
                          netmiko.ssh_exception.NetMikoAuthenticationException,
                          netmiko.ssh_exception.SSHException)
    # Conexión con equipos
    try:
        print("Conectando a WLC", wlc)
        connection = netmiko.ConnectHandler(ip=wlc, username=****, password=*****,
                                            device_type="cisco_wlc_ssh")
        return connection #Devuelve posición en memoria

    except netmiko_exceptions as e:
        print('No se ha podido conectar con la WLC ')
        return False

def obtener_ap():
    #Chequeo de antenas registradas
    print("Chequeando antenas registradas")
    output = connection.send_command_w_enter('grep include 10.. "show ap summary"')
    lineas = output.splitlines()
    df = pd.DataFrame({"antena": [], "ip": [], "modelo": []})
    for l in lineas:
        if "10." in l:
            if l.split()[-6].startswith("10."):
                ip = l.split()[-6]
                antena = l.split()[0]
                modelo = l.split()[2]
                df = df.append(dict(ip=ip, antena=antena, modelo=modelo), ignore_index=True)

    return df

def chequeo(idx, ap):
    # Chequeo de logg
    print(f"Chequeando equipo {idx} {ap}")
    output = connection.send_command_w_enter(f'show ap config general {ap}')
    #print(output)
    lineas = output.splitlines()
    for linea in lineas:
        if linea.startswith("FlexConnect Vlan mode"):
            #print(linea)
            if "Disabled" in linea:
                fallos.append(ap)
                print(f"Añadiendo {ap} en la lista")
            break


wlc = "10.71.204.254"
hoy = datetime.today().date()
connection = conexion_wlc()
fichero = "\\\\ESSVPM902017\\Doc_Comunicaciones\\Problemas, Incidencias y Seguimientos\\Wifi\\Seguimiento_APs_vlan_support.xlsx"

if __name__ == '__main__':
    # Establecemos la conexión con la WLC
    if connection:
        df_global = obtener_ap()
        print("Obtenido total de antenas ", df_global.shape[0])
        devices = list(df_global["antena"])
        fallos = []
        for idx, ap in enumerate(devices, start=1):
            chequeo(idx, ap)
        connection.disconnect()
        if fallos:
            df_fallos = pd.DataFrame(fallos, columns=["antena"])
            print(df_fallos)
            df_combinada = pd.merge(df_global, df_fallos, how="inner")  #Unimos las df con los elementos comunes
            df_combinada["Fecha"] = str(hoy)
            df_combinada = df_combinada[["Fecha", "antena", "ip", "modelo"]]
            print(df_combinada)
            mensaje(df_combinada)  #Enviamos las antenas a revisar el teams

            guardar_excel(df_combinada)

        print("Fin de programa")
`

By using a "while" loop (the one in my first post), I couldn't get all the ouput, always stops at 2256th AP. Can't understand why.
That's why I used your suggestion and read all APs and created a "for" loop but using "show access-point-config".
So, this has been the fastest way to get the goal. It takes about 70 min to end.
`
def conexion_wlc():
    netmiko_exceptions = (netmiko.ssh_exception.NetMikoTimeoutException,
                          netmiko.ssh_exception.NetMikoAuthenticationException,
                          netmiko.ssh_exception.SSHException)
    # Conexión con equipos
    try:
        print("Conectando a WLC", wlc)
        connection = netmiko.ConnectHandler(ip=wlc, username=++++, password=+++++,
                                            device_type="cisco_wlc_ssh")
        return connection  # Devuelve posición en memoria

    except netmiko_exceptions as e:
        print('No se ha podido conectar con la WLC ')
        return False

def obtener_aps():
    print("Obteniendo número de antenas")
    output = connection.send_command_w_enter('grep include Number "show ap summary"')
    lineas = output.splitlines()
    total_aps = int(lineas[1].split()[-1])
    print("Total de antenas", total_aps)
    return total_aps

def chequeo(contador):
    # Chequeo de logg
    print(f"Chequeando equipos")
    output = connection.send_command_w_enter('grep include "FlexConnect Vlan mode|Cisco AP Name|'
                                                     'IP Address......|AP Model" "show access-point-config"')
    if "Disabled" in output:
        print(output)
        add_diccionario(output)
    salida_completa.append(output)
    for i in range(2, contador+1):
        try:
            print(f"Chequeando antena {i}")
            output = connection.send_command("\n")
            salida_completa.append(output)
            if "Disabled" in output:
                print(output)
                add_diccionario(output)
        except OSError:
            print(output)
            print("No se ha detectado el prompt")

def add_diccionario(output):
    lineas = output.splitlines()
    for linea in lineas:
        if linea.startswith("Cisco AP Name"):
            antena = linea.split()[-1]
        elif linea.startswith("AP Model"):
            modelo = linea.split()[-1]
        elif linea.startswith("IP Address....."):
            ip = linea.split()[-1]
    diccionario = {"antena": antena, "modelo": modelo, "ip": ip}
    fallos.append(diccionario)
    print(f"Añadiendo {antena} en la lista")

wlc = "10.71.204.254"
hoy = datetime.today().date()
connection = conexion_wlc()
fichero = "\\\\ESSVPM902017\\Doc_Comunicaciones\\Problemas, Incidencias y Seguimientos\\Wifi\\Seguimiento_APs_vlan_support.xlsx"
fallos = []
salida_completa = []


if __name__ == '__main__':
    # Establecemos la conexión con la WLC
    if connection:
        chequeo(obtener_aps())
        connection.disconnect()
        if fallos:
            df_fallos = pd.DataFrame(fallos)
            df_fallos["Fecha"] = str(hoy)
            df_fallos = df_fallos[["Fecha", "antena", "ip", "modelo"]]
            print(df_fallos)
            mensaje(df_fallos)
            guardar_excel(df_fallos)

    print("Fin de programa")

`

If somebody has any suggestion, will be welcomed.
Feel free to improve this code and share with me.

**Comment by applericky** [comment]
From doing a quick scan, it does not appear you are doing any type of threading/multiprocessing. I would recommend using the following: 
-concurrent.futures
-multiprocessing
-asyncio

These will allow to speed up your script. If you are not comfortable with the above mentioned, I would use Nornir. It has threading built it. Kirk has worked on that project. It requires to learn a new technology, but its worth it. 

As to make your output cleaner, you can try:
https://github.com/willmcgugan/rich

**Comment by pponte81** [comment]
Hello applericky,
Thanks for your suggestion.
I have never used concurrent futures to make multiples commands through a connection.
I have just used It to make multiples connections and get multiples outputs.
Could you share an example to know how to do that?
Please, advice that I just have to press "enter" to get new output and parse It.
I am not sure if I could apply concurrent futures on this case, but maybe could be usefull for futures projects.

**Comment by ktbyers** [comment]
@pponte81 The Cisco WLC Netmiko Driver has a method named: `send_command_w_enter()` have you  tried using that?

**Comment by applericky** [comment]
I would try the `send_command_w_enter() ` that was recommended. As for the concurrent.futures, this will allow more SSH logins at once to speed up the process.

**Comment by ktbyers** [comment]
Yes, and you might want to look at Nornir + Netmiko for built-in concurrency so you don't have to re-implement concurrency yourself.

**Comment by pwiddicombe** [comment]
Hard to read Python when it's non-indented like that...

Some questions/comments:
1.  It looks like all the AP's are on one controller.  Concurrency is "trickier" in this environment.  You have to maintain multiple connections to the same controller; and split the workload.
2.  Have you tried just connection.send_command( <command> ) ?  I never have used the _w_enter with wlc's.  Not sure if it
3. What version of Python are you using, and how fast a computer?  Python 3.6 gets bogged down quickly with complicated/nested tables.  3.7 and 3.8 work much better, if you aren't already using them.
4. Did you "config paging disable"?  This way there may be less handshaking necessary with output that exceeds 24 lines.
5. Quick calculation - you're now getting about 1 AP/sec where you have to send a command for each AP - other than the threading, you may not be able to exceed that rate by much.

**Comment by ktbyers** [comment]
Closing as the issue looks like it is no longer active.
