### ISSUE TITLE
AttributeError: 'super' object has no attribute 'config_mode'

### ISSUE THREAD

**Issue by jjuu** [ktbyers/netmiko#208]
**My codes:**
```
device = dict(device_type='cisco_ios', ip=host_ip_address, username=username,
                      password=password, secret=enable_password, port=port)

try:
    self.net_connect = ConnectHandler(**device)
    sys.stdout.write("SSH Connection Established. Proceed to Device Configuration")
except SSHException as e:
    sys.stderr.write("Error occurred: %s" % e)
    time.sleep(10)
    self.net_connect = ConnectHandler(**device)

self.net_connect.config_mode()
```

**Error**
File "C:\Python27\lib\site-packages\netmiko\ssh_connection.py", line 27, in config_mode     return super(SSHConnection, self).config_mode(config_command=config_command) AttributeError: 'super' object has no attribute 'config_mode'

Python 2.7.6
The netmiko version is 0.4.3

It's very strange.

**Comment by ktbyers** [comment]
@jjuu Can you repost your code and use \`\`\` so that the markdown doesn't mess up the code:

```
some python code
```

**Comment by jjuu** [comment]
Sorry, I re-edit my code. Please take a look.

**Comment by ktbyers** [comment]
@jjuu Your references to 'self' above are an error:

Try the following:
```
device = dict(device_type='cisco_ios', ip=host_ip_address, username=username,
                      password=password, secret=enable_password, port=port)
net_connect = ConnectHandler(**device)
sys.stdout.write("SSH Connection Established. Proceed to Device Configuration")
net_connect.config_mode()
```

**Comment by jjuu** [comment]
Well, sorry. These are three pieces of code. I have the code, but I cannot debug.

**Comment by ktbyers** [comment]
@jjuu I didn't under stand your statement above?
