### ISSUE TITLE
Netmiko 4

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#2082]
Rationalize delay_factor/global_delay_factor behavior when fast_cli=True is used.

Probably should make it always slow things down.

**Comment by dmulyalin** [comment]
Not sure if was proposed before, at least have not found anything exactly like that in previous issues, so, would it make sense to introduce plugins in Netmiko 4 and make overall system more pluggable, IMHO, good candidates for plugins are:
- parser or text output post processing plugins, e.g. TextFSM, Genie, TTP etc.
- reader plugins - modules to read output from devices, e.g. read till pattern, read till timeout, or something exotic like described in https://github.com/ktbyers/netmiko/issues/1153 issue  i.e. make functions like send_command_timing, send_command, send_command_expect and their counterparts - _read_channel_expect, _read_channel, _read_channel_timing pluggable
- transport plugins e.g. Paramiko, Telnetlib etc.
- connection plugins, responsible for initiating connections to devices and handling requests, e.g. single connection plugin, multi-connection plugin, plugin to connect to devices behind proxies/jumphosts etc.
- device drivers plugins, pluggability are already in place I think but might be good to consider adding capability to use entry points to load more drivers

Its similar to Nornir, various people can create their own plugins to fulfil their own needs and use cases without bothering to merge in main Netmiko codebase. 

Normally, pluggable system more scalable and flexible compared to solid architectures, however, even though it helps to ease maintenance burden on core developers, it might increase requirements in the area of creating well defined architecture and documenting processes and tests procedures to follow. 

IMHO, good example of that architecture are SALTSTACK and Nornir

**Comment by ktbyers** [comment]
Purging old issues...
