### ISSUE TITLE
I am trying to connect to remote machine to change password without connecting to prompt

### ISSUE THREAD

**Issue by Vaishu2211** [ktbyers/netmiko#2083]
Hi,
I using netmiko to configure user at the remote machine. I have created a password for a user using netmiko now I want to login to the same machine with a new user and password that I have set. But in my case, while connecting to a machine with a new user and password, I get a prompt that the password expired, change the password. 

bash-4.4# ssh <username>@<ip_address>
Password: 
Password expired. Change your password now.
Current Password: 
Enter new password: 

This is what I get when I connect manually, how can I achieve this using netmiko?
is there any way that I can pass the current password and new password while connecting to device?

**Comment by applericky** [comment]
Hi,

From what I'm reading, this is more of a how to question is that right?
I think the following will help. It assists with handling expected strings


https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-expect_string

```

from netmiko import ConnectHandler
from getpass import getpass

cisco1 = {
    "device_type": "cisco_ios",
    "host": "cisco1.lasthop.io",
    "username": "pyclass",
    "password": getpass(),
}

command = "del flash:/test4.txt"
net_connect = ConnectHandler(**cisco1)

# CLI Interaction is as follows:
# cisco1#delete flash:/testb.txt
# Delete filename [testb.txt]? 
# Delete flash:/testb.txt? [confirm]y

# Use 'send_command' and the 'expect_string' argument (note, expect_string uses 
# RegEx patterns). Netmiko will move-on to the next command when the
# 'expect_string' is detected.

# strip_prompt=False and strip_command=False make the output
# easier to read in this context.
output = net_connect.send_command(
    command_string=command,
    expect_string=r"Delete filename",
    strip_prompt=False,
    strip_command=False
)
output += net_connect.send_command(
    command_string="\n",
    expect_string=r"confirm",
    strip_prompt=False,
    strip_command=False
)
output += net_connect.send_command(
    command_string="y",
    expect_string=r"#",
    strip_prompt=False,
    strip_command=False
)
net_connect.disconnect()

print()
print(output)
print()

```

**Comment by reddyarun474** [comment]
I am also having same issue i.e, want to change password without expecting prompt.

Manual steps:
=========
Using username "root".
Keyboard-interactive authentication prompts from server:
End of keyboard-interactive prompts from server
Access denied
Keyboard-interactive authentication prompts from server:
| Password:
| You are required to change your password immediately (root enforced)
| Changing password for root.
| (current) UNIX password:
| Enter new UNIX password:
| Retype new UNIX password:

I am trying to automate above manual steps using netmiko. Can anyone suggest me some pointers here ?

**Comment by ktbyers** [comment]
For the password change, you are better off using send_command_timing:


The pattern shown here should probably work:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-timing

If you are using Netmiko4 (currently the develop branch), you could also use send_multiline_timing()
