### ISSUE TITLE
Cisco WLC driver is leaving stale Paramiko threads in Netmiko >3.0.0

### ISSUE THREAD

**Issue by pwiddicombe** [ktbyers/netmiko#2084]
Not sure exactly which version this cropped up.  At version 3.0.0 and lower, using cisco_wlc model, when the .disconnect() method is called (directly, or indirectly via the "with" method), the underlying Paramiko thread is correctly closed.

3.3.0 and 3.3.2 fail to close the Paramiko thread when cisco_wlc is used (directly via disconnect() or implicitly by a completed "with" block); although works as expected with model cisco_ios.
(This may be related to issue #2080).  If connecting to multiple WLC's, you will get one stranded underlying Paramiko thread for each WLC you have connected to.

**Comment by pwiddicombe** [comment]
Tested with Netmiko 3.3.3.  The issue still persists with device type cisco_wlc - Paramiko thread left open after connection closure.

**Comment by ktbyers** [comment]
@pwiddicombe You need to post your code particularly how you are ending your SSH session.

**Comment by pwiddicombe** [comment]
from netmiko import Netmiko
import threading
import getpass
import time

userid = getpass.getuser()
userpwd = getpass.getpass(f"Enter password for {userid}: ")

conn = Netmiko(
    device_type="cisco_wlc",
    ip="172.22.122.247",
    username=userid,
    password=userpwd,
    secret="cisco",
)
resp = conn.send_command("show certificate summary")
print("Before disconnect")
print(threading.enumerate())
print(resp)
print("After disconnect")
conn.disconnect()
print(threading.enumerate())
time.sleep(5)
print(threading.enumerate())

=========================== Output
Enter password for pw32115: 
Before disconnect
[<_MainThread(MainThread, started 267572)>, <Thread(SockThread, started daemon 261988)>, <paramiko.Transport at 0x32de3f0 (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>]
Web Administration Certificate................... 3rd Party
Web Authentication Certificate................... Locally Generated
Certificate compatibility mode:.................. off
Lifetime Check Ignore for MIC ................... Disable
Lifetime Check Ignore for SSC ................... Disable

After disconnect
[<_MainThread(MainThread, started 267572)>, <Thread(SockThread, started daemon 261988)>, <paramiko.Transport at 0x32de3f0 (cipher aes128-ctr, 128 bits) (active; 0 open channel(s))>]
[<_MainThread(MainThread, started 267572)>, <Thread(SockThread, started daemon 261988)>, <paramiko.Transport at 0x32de3f0 (cipher aes128-ctr, 128 bits) (active; 0 open channel(s))>]

--------------------------------------
If the same code is run under Netmiko 3.0.0 or earlier, the Paramiko thread is gone after the conn.disconnect()

**Comment by ktbyers** [comment]
How about adding:

`delete conn`

right after the disconnect?

**Comment by pwiddicombe** [comment]
" del conn" doesn't have any impact.
send_command_timing('logout') just before the disconnect seems to have no impact.

Is there a way to send a "close" request to paramiko directly?   (although I would have presumed the conn.disconnect() would have implicitly done that).

**Comment by ktbyers** [comment]
I suspect it in someway pertains to the SSH connection not being terminated/completely closed (in other words, if you look at the connection level I suspect the SSH connection still exists from a TCP state...anyways that would be my guess). It seems like there is a Python3 behavior change with respect to TCP connections that still exist.

So you probably would need to do more debugging and look at the session_log or the debug log on Netmiko and see if the Cisco WLC SSH connections are properly terminating. That is where I would look for the issue.

The following code should be executed (disconnect() which then calls paramiko_cleanup() ).

```python
    def paramiko_cleanup(self):
        """Cleanup Paramiko to try to gracefully handle SSH session ending."""
        self.remote_conn_pre.close()
        del self.remote_conn_pre

    def disconnect(self):
        """Try to gracefully close the session."""
        try: 
            self.cleanup()
            if self.protocol == "ssh":
                self.paramiko_cleanup()
            elif self.protocol == "telnet":
                self.remote_conn.close()
            elif self.protocol == "serial":
                self.remote_conn.close()
        except Exception:
            # There have been race conditions observed on disconnect.
            pass 
        finally:
            self.remote_conn_pre = None 
            self.remote_conn = None 
            self.close_session_log()
```

The Cisco WLC is a weird duck, however, so there could be issues in trying to gracefully logout from the device.

**Comment by ktbyers** [comment]
What issue does this actually cause you?

**Comment by pwiddicombe** [comment]
1.  I typically run reports on 300-400 controllers, and am concerned about the impact of having several hundred "partly active" threads on the system.  Paramiko session still an active thread, but with 0 open channels.
2.   Many of these reports are threaded, and  "completion" is when all the threads complete.

This works under Python 3.6, 7, 8 as long as I don't run the newer versions of netmiko - up to 3.0.0 appears to work perfectly.  I originally thought it was an issue with a Python upgrade, because at that time I had installed the current version of netmiko in  that venv, but realized it was working properly in Python 3.7 on an "older" installation on another laptop.

**Comment by ktbyers** [comment]
Have you checked whether you still have active/stale TCP connections on your system when this happens i.e. what does `netstat -an` show when you observe the extra Paramiko threads?

Can you expand on this statement--I didn't understand it?

`Many of these reports are threaded, and "completion" is when all the threads complete.`

**Comment by ktbyers** [comment]
This doesn't happen on Cisco IOS:

```python
from netmiko import Netmiko
import threading
import time

device = {
    "device_type": "cisco_ios",
    "host": "device.domain.com",
    "username": "admin",
    "password": "password",
}

conn = Netmiko(**device)
resp = conn.send_command("show ip int brief")
print("Before disconnect")
print(threading.enumerate())
print(resp)
print("After disconnect")
conn.disconnect()
print(threading.enumerate())
time.sleep(5)
print(threading.enumerate())
```

```
$ python foo.py 
Before disconnect
[<_MainThread(MainThread, started 140523863906112)>, <paramiko.Transport at 0x254367f0 (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>]
Interface                  IP-Address      OK? Method Status                Protocol
FastEthernet0              unassigned      YES unset  down                  down    
FastEthernet1              unassigned      YES unset  down                  down    
FastEthernet2              unassigned      YES unset  down                  down    
FastEthernet3              unassigned      YES unset  down                  down    
FastEthernet4              10.220.88.20    YES NVRAM  up                    up      
Vlan1                      unassigned      YES unset  down                  down    
After disconnect
[<_MainThread(MainThread, started 140523863906112)>, <paramiko.Transport at 0x254367f0 (unconnected)>]
[<_MainThread(MainThread, started 140523863906112)>]
```


This makes me think it is probably something specific to the WLC driver and not gracefully closing the SSH sessions.

**Comment by pwiddicombe** [comment]
I ran a "smaller batch" of 28 connections; of which threading had me run 7 at a time.

Immediately on completion, netstat -an showed 28 connections using port 22; 3 in a TIM_WAIT state (coindentally 3 unavailable reported as "no connection"), and the others all ESTABLISHED.  After 5 minutes, the TIM_WAIT ones disappeared from the netstat-an, and 18 remain still ESTABLISHED.  Upon completion, I had 18 threads in that "stale thread" state.  The other 7 appeared to have shut down normally.  Shutting down the Python shell, and they all went away.

Running the same job on netmiko 3.0.0 shows all threads shutting down properly - still 3 unreachable, but all threads properly closed; and any connections of netstat -an at the end all in a TIM_WAIT state.  At all times, the number of ESTABLISHED sessions matched the number of expected active Paramiko threads, and never exceeded the 7 active threads.

**Comment by ktbyers** [comment]
Have you used the Netmiko session_log on a single WLC connection to see why the SSH connection is not being closed on the device?

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#session-log


Regards, Kirk

**Comment by pwiddicombe** [comment]
It does seem to be a change in behavior with WLC's between releases.
In older versions, it seems the connection was simply closed, and the SSH connection was dropped (and never seemed to leave any live sessions on the WLC).

=====================
Netmiko 3.0.0 and earlier, closedown

(misndwc042lab) >
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'config paging enable\n'
DEBUG:netmiko:send_command_timing current output: 
DEBUG:netmiko:read_channel: config paging enable

(misndwc042lab) >
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:send_command_timing final output: 

DEBUG:paramiko.transport:EOF in transport thread

=================
Now with 3.3.2, 3.3.3  wlc closedown

(misndwc042lab) >
DEBUG:netmiko:write_channel: b'config paging enable\n'
DEBUG:netmiko:send_command_timing current output: 
DEBUG:netmiko:read_channel: config paging enable

(misndwc042lab) >
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:send_command_timing final output: 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: \(misndwc042lab\)\ 
DEBUG:netmiko:_read_channel_expect read_data: 

(misndwc042lab) >
DEBUG:netmiko:Pattern found: \(misndwc042lab\)\  

(misndwc042lab) >
DEBUG:netmiko:write_channel: b'logout\n'
DEBUG:netmiko:read_channel: logout

The system has unsaved changes.

Would you like to save them now? (y/N) 
DEBUG:netmiko:write_channel: b'n\n'
DEBUG:netmiko:write_channel: b'\n'
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:netmiko:read_channel: n

<  I presume the former versions didn't actually sent the LOGOUT  >
<  It almost looks like Cisco drops the session, and Paramiko "agrees", but then
    Netmiko tries to read the echo, so Paramiko either doesn't close or re-opens ?   >

DEBUG:paramiko.transport:Received global request "keepalive@openssh.com"
DEBUG:paramiko.transport:Rejecting "keepalive@openssh.com" global request from server.
DEBUG:paramiko.transport:Received global request "keepalive@openssh.com"
DEBUG:paramiko.transport:Rejecting "keepalive@openssh.com" global request from server.
DEBUG:paramiko.transport:Received global request "keepalive@openssh.com"
DEBUG:paramiko.transport:Rejecting "keepalive@openssh.com" global request from server.
DEBUG:paramiko.transport:Received global request "keepalive@openssh.com"
DEBUG:paramiko.transport:Rejecting "keepalive@openssh.com" global request from server.
DEBUG:paramiko.transport:Received global request "keepalive@openssh.com"
DEBUG:paramiko.transport:Rejecting "keepalive@openssh.com" global request from server.
DEBUG:paramiko.transport:Received global request "keepalive@openssh.com"
DEBUG:paramiko.transport:Rejecting "keepalive@openssh.com" global request from server.

**Comment by mfr-6** [comment]
Alright, i did some investigation to this, since i have similar issue right now with Netmiko 3.4.0 (Paramiko 2.7.2). Tried upgrade Netmiko and Paramiko to latest version but this doesn't resolve the problem, so i started debugging this.

I have two WLC controllers:
WLC1 - software version: 8.3.150.0 -> connection to this results with generating paramiko.transport DEBUG messages forever
WLC2 - software version: 8.10.151.0 - no issues spotted

I use Netmiko with Context Manager, so every time when it's moment to close connecthandler - "disconnect" method is invoked.

Here we have self.cleanup() with invokes "cleanup" from CiscoWlcSSH. That method raises OSError: Socket is closed exception and because of that - "paramiko_cleanup()" is not invoked and that's why thread is not deleted and hangs forever.

"OSError: Socket is closed" exception is raised in cisco_wlc_ssh.py in "while" loop, because at first iteration - line 195  is not raising socket.error exception, because - in my opinion - write_channel is send immediately, which is way too fast for old WLC, so at line 195 socket is still alive (propably WLC needs more time to close session after logout and sending "n" than newer software versions), so it iterates again in while loop (first time.sleep(0.5) still not enough) and write_channel at line 192 fails with exception "OSError: Socket is closed" raised.

I have to solutions for that:
1.  Add additional time.sleep(0,5) between if loop at 190 and "try" at 194 - resolves the problem
2. Clear "output" at the end of while block to prevent entering inside the if loop (line 190), because there is no need to send "n" again since it's already done at first iteration.
