### ISSUE TITLE
Sending multiple show commands to single device and sending different show commands to different devices

### ISSUE THREAD

**Issue by amitbeniwal48** [ktbyers/netmiko#2087]
Hi Kirk,

Is it possible to do these tasks using Nornir:

1. Sending multiple show commands to single device.
2. Sending different show commands to different devices (at the same time).

**Comment by ktbyers** [comment]
@amitbeniwal48 Sure...

1. Just use a for-loop and a list/file some iterable with the show commands and then call send_command for each command and create a data structure to store the results in.

2. Use concurrency...Nornir + Netmiko is one of the easier ways to do this.
