### ISSUE TITLE
SGOS device connection

### ISSUE THREAD

**Issue by HoxinhLuo** [ktbyers/netmiko#2089]
My device info is "Version: SGOS 6.5.8.3 Proxy Edition", when I try to use Netmiko to connect it, raising the following error(s)
```
172.16.56.28 login successfully.
Timed-out reading channel, data not available.
```
Is Netmiko supporting SGOS device's connection ?

**Comment by ktbyers** [comment]
Netmiko doesn't support Broadcom SGOS. Someone would need to create a driver for it:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md


Regards, Kirk
