### ISSUE TITLE
ImportError: cannot import name 'netmiko_send_command' from 'nornir.plugins.tasks' (/home/michael/.local/lib/python3.9/site-packages/nornir/plugins/tasks/__init__.py)

### ISSUE THREAD

**Issue by toumichaelyang1026** [ktbyers/netmiko#2093]
Im new to coding. Im getting this error after using pip install netmiko. I think the file might of been installed else where.

**Comment by ktbyers** [comment]
Did you pip install: `nornir-netmiko`

Also you will probably need to post your code (at least the imports section).
