### ISSUE TITLE
ValueError：Failed to exit configuration mode

### ISSUE THREAD

**Issue by Mic0623** [ktbyers/netmiko#2094]
HI dear ktbyers:
I have an issue about the netmiko,
my code is:

```python
from netmiko import ConnectHandler
import netmiko
import getpass
import socket


username = input('Enter your SSH/Telnet username: ')
password_now = getpass.getpass('Enter your SSH/Telnet password now: ') 
password = getpass.getpass('Enter your new password: ')

cisco_3560_18 = {
                    'device_type':'cisco_ios',
                    'ip':'XXXXXXX',
                    'username':username,
                    'password':password_now
                    }

cisco_3560_19 = {
                    'device_type':'cisco_ios',
                    'ip':'1XXXXXXX9',
                    'username':username,
                    'password':password_now
                    }
devices_cisco = [cisco_3560_18,cisco_3560_19]
for device in devices_cisco:
    try:
        connect = ConnectHandler(**device)
        print('Successfully connected to ' + device['ip'])
        
        config_commands ='username admin secret 12345'
        #connect.send_command('conf t')
        output = connect.send_config_set(config_commands)
        print(output)
    except netmiko.ssh_exception.NetMikoTimeoutException:
        print(device['ip' + 'is not reachable.'])
    except netmiko.ssh_exception.NetmikoAuthenticationException:
        print('username or password incorrect')
```

and there is an error is :ValueError：Failed to exit configuration mode     (output = connect.send_config_set(config_commands))

and i follow your reply for other issue add the 'exit_config_mode=False' and 'delay_factor=4'
there will be another error:
username admin secret 12345
                                ^
%invalid input detected at '^' marker.
XXXXX#

this two swtiches is cisco WS-C3560-24TS, and ios is :C3560-IPSERVICESK9-M

and i use netmiko.send_command to show information can works.

**Comment by pwiddicombe** [comment]
You might want to replace 
 config_commands ='username admin secret 12345'
with
config_commands =['username admin secret 12345']
...  it's expecting a list.

**Comment by ktbyers** [comment]
That shouldn't matter--Netmiko will automatically wrap a single command (string) in a list...so the single command as a string should be fine.

For the first error, you would need to post the full exception stack trace.

For the second error: `%invalid input detected at '^' marker.`. That error is from the device i.e. the device is stating the command is not valid. My guess would be that you don't have privileges to enter config mode with the user you are logging in as (or haven't elevated privileges). This could potentially be accomplished by using the Netmiko `enable()` method and adding the secret argument.

You should enable the session_log which is an argument to ConnectHandler so you can see more about what is going on:

```python
cisco_3560_18 = {
                    'device_type':'cisco_ios',
                    'ip':'10.119.1.18',
                    'username':username,
                    'password':password_now,
                    'session_log': 'device-18.out',
                    }
```

Regards,  Kirk

**Comment by Mic0623** [comment]
![901609720162_ pic_hd](https://user-images.githubusercontent.com/65208349/103492672-63ece680-4e67-11eb-8465-de729803a98f.jpg)
hi dear ktbyers:
this is the original errors,
i have configured the privileges 15 level for the admin user, so the second error i guess is not about the privileges.
when i got the first error, and follow ur reply of other people's issue, i add the parameters(delay factor and exit config mode)
. Then the second error happened.

**Comment by Mic0623** [comment]
![911609720782_ pic_hd](https://user-images.githubusercontent.com/65208349/103492804-7ae00880-4e68-11eb-9aaa-0414a4cd1d7d.jpg)
and this is the device-18.out

**Comment by ktbyers** [comment]
What is the vendor/model of this device? Is this Cisco IOS or something else?

If this is Cisco IOS, then why do you have `QDSW11(zhanduan)#` (is that your device hostname)?

 If so, you can't do that and have netmiko work (as Netmiko will think you are always in `config` mode due to the presence of the `)#` in the output.


Regards, Kirk

**Comment by Mic0623** [comment]
> What is the vendor/model of this device? Is this Cisco IOS or something else?
> 
> If this is Cisco IOS, then why do you have `QDSW11(zhanduan)#` (is that your device hostname)?
> 
> If so, you can't do that and have netmiko work (as Netmiko will think you are always in `config` mode due to the presence of the `)#` in the output.
> 
> Regards, Kirk

this is the cisco ios and this two swtiches is cisco WS-C3560-24TS, and ios is :C3560-IPSERVICESK9-M
and QDSW11 is device hostname.

**Comment by Mic0623** [comment]
> What is the vendor/model of this device? Is this Cisco IOS or something else?
> 
> If this is Cisco IOS, then why do you have `QDSW11(zhanduan)#` (is that your device hostname)?
> 
> If so, you can't do that and have netmiko work (as Netmiko will think you are always in `config` mode due to the presence of the `)#` in the output.
> 
> Regards, Kirk

Dear Kirk
how can i do to solve this issue. everything is ok  and the code can work at other cisco devices.
plz point the problem about it  
thank you 
Regards. Michael

**Comment by ktbyers** [comment]
Why does it say this?

```
(zhanduan)
```

What is the meaning/significance of that?

**Comment by Mic0623** [comment]
> Why does it say this?
> 
> ```
> (zhanduan)
> ```
> 
> What is the meaning/significance of that?

sorry, its a part of hostname, the hostname of 10.119.1.18 is QDSW(zhanduan).

**Comment by ktbyers** [comment]
@Mic0623 Yeah, you can't do that AND have Netmiko work...that is breaking things.

**Comment by ktbyers** [comment]
Adding the parenthesis breaks how Netmiko checks for whether we are in config-mode or not:

https://github.com/ktbyers/netmiko/blob/netmiko4_exp/netmiko/cisco/cisco_ios.py#L26

**Comment by Mic0623** [comment]
> Adding the parenthesis breaks how Netmiko checks for whether we are in config-mode or not:
> 
> https://github.com/ktbyers/netmiko/blob/netmiko4_exp/netmiko/cisco/cisco_ios.py#L26
> 
> You can see this argument:
> 
> `check_string=")#"`
> 
> So trailing parenthesis and a pound sign is the indicator we are using for determining configuration mode.
> 
> Unfortunately, in this case you would have to change the hostname to get Netmiko to work properly...
> 
> Regards, Kirk

Thank you！Kirk，when i change the hostname of the device, the problem is solved.
Thank you very much!

**Comment by ktbyers** [comment]
@Mic0623 Yeah, sorry you ran into this...unfortunately, certain string patterns for determining device state (config mode, enable mode, et cetera) are necessary.
