### ISSUE TITLE
CLI session limit reached

### ISSUE THREAD

**Issue by agcasey** [ktbyers/netmiko#2098]
When the CLI login session limit is reached, the connection is closed immediately after the login banner is displayed.  It would be nice if this condition could be detected.  This would save a significant amount of time waiting for the connection attempt to timeout.

In base_connection.py, the function "_test_channel_read" loops around looking for the login prompt in "new_data".  The CLI error message can be found in the last line of "new_data" after each call to self._read_channel_timing().

If "CLI session limit \d+ reached" is found in new_data, a suitable exception could be raised and no further action taken.  Further calls to self._read_channel_timing() are superfluous in this situation.

**Comment by agcasey** [comment]
The device in question is Cisco, running NX-OS.

**Comment by ktbyers** [comment]
Are you gracefully closing the connecting i.e. making sure `disconnect()` is always called? I would probably look more to why I am running out of VTY ports.

Regards, Kirk

**Comment by pwiddicombe** [comment]
What version of NetMiko are you using?  Are you possibly reconnecting to the device multiple times?

#2084 is open, and may be related.  .disconnect() on the cisco_wlc model doesn't actually close ssh sessions properly - this could possibly also affect other model types as well, potentially leaving live .SSH sessions on hosts? 

I had added this to the control portion of a script that scans wlc's:
            for anythread in threading.enumerate():
                if anythread != main_thread:
                    nm=anythread.getName()
                    if (nm != 'SockThread'):
                        cnt=cnt+1
            print (f'Thread count is now  {cnt}')
...  and discovered the .disconnect() doesn't disconnect the Paramiko SSH thread for cisco_wlc but does work properly on cisco_ios.  Not sure about nx-os or other model types.

**Comment by agcasey** [comment]
NetMiko is not the  culprit exhausting the VTY sessions.  The VTY sessions are being consumed by another script not under my control.  All I know is that when I try to connect and the CLI session limit is reached, my NetMiko session spins its wheels because it does not act on the error message displayed after each call to self._read_channel_timing() which is telling it that no more CLI sessions are available.

I'm running version 2.4.2 on RHEL7, python2.7.

**Comment by ktbyers** [comment]
@agcasey Can you capture a Netmiko logging session of the failure case?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel


Regards, Kirk

**Comment by agcasey** [comment]
Kirk,
My host is not connected to the Internet :-(  I ran the debug and have transcribed what I believe are the "interesting bits" to clarify the issue.

DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel:
Cisco Nexus Operating System (NX-OS) Software
...
... (Standard Cisco banner text)
...
http://www.gnu.org/licenses/old-licenses/library.txt.   <--- normal last line of Cisco banner
CLI session limit 32 reached. Exiting.                  <--- appears immediately after last line of Cisco banner

DEBUG:netmiko:read_channel:
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF send (0)
DEBUG:netmiko:read_channel:
...
(line repeated 80 times)
DEBUG:netmiko:read_channel:
ERROR:root:Socket is closed
DEBUG:root:netmiko resultDict: {usual stuff - valid details from the device}

It looks like paramiko is detecting the EOF but netmiko continues looking for output until it times out.
I hope this sheds some light on the issue.

Regards,
Adrian.

**Comment by ktbyers** [comment]
Can you show me the full exception stack trace of this failure? I need to see where in the SSH-connect/Netmiko code the exception actually happens.

Thanks.

Kirk

**Comment by agcasey** [comment]
Kirk,

There is no unhandled exception raised and no stack trace.  It's not a failure per se; just an opportunity to save cpu cycles.   The function _read_channel_timing() in base_connection.py is repeatedly calling read_channel() and missing the fact that the connection has been dropped due to the CLI session limit being reached.

By adding the following 2 lines to base_connection.py, I can detect the error instead of having to wait for the timeout.  

base_connection.py -:
def _read_channel_timing(self, delay_factor=1, max_loops=150):
...
...
    while i <= max_loops:
        time.sleep(loop_delay * delay_factor)
        new_data = self.read_channel()
        if 'CLI session limit' in new_data:                         # detect CLI session limit message
            raise socket.error('CLI session limit reached.')  # raise appropriate exception
        if new_data:
...
...

You should be able to reproduce this for yourself by setting the CLI session limit to 1 on a Cisco / NX-OS device -:
# config t
# session-limit 1
Keep your terminal session active and try to connect via netmiko in another session.

Adrian.

**Comment by ktbyers** [comment]
There are no exceptions?

Or your code is handling the exception?

**Comment by agcasey** [comment]
Correct, no exceptions.  The root logger logs the message "ERROR:root:Socket is closed" after a minute or so.  My code simply detects that the socket is closed due to the CLI limit being reached.  Without this, netmiko will keep looking for the login prompt which is never going to be seen because the connection has been closed.

This issue becomes noticeable when accessing multiple devices concurrently.  For example, run a command on 20 devices.  I'm using multiprocessing and netmiko to access the devices concurrently.  I get my results in around 5 seconds.  However, if any of the 20 devices has reached the "CLI session limit", I get absolutely no output for well over 60 seconds while waiting for the connection timeout to be detected on the offending device.

By detecting the "CLI session limit" message, the login attempt can be abandoned with a second or two of connecting thereby saving a lot of time.

Are you able to test the session-limit feature yourself?

**Comment by ktbyers** [comment]
Seems like you either have a try/except in your code or are using some sort of concurrency? Otherwise, you should get an exception.

I am probably not going to fix this--it is not in my top-100 things to fix on Netmiko and I have reservations about putting Cisco specific handlers in this code (since it would likely be in code that is shared across platforms or alternatively I would have to break out Cisco_platform specific handlers).

You are welcome to do a PR on it.

If you are able to obtain the exception stack trace, I would probably look at it a bit more.


Regards, Kirk

**Comment by agcasey** [comment]
Ah, yes, I did have a try/except!  I commented it out and managed to get the full traceback (manually transposed) -:

`File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 246, in ConnectHandler
   return ConnectionClass(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 317, in __init__
   self._open()
File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 323, in _open
   self._try_session_preparation()
File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 740, in _try_session_preparation
   self.session_preparation()
File "/usr/lib/python2.7/site-packages/netmiko/cisco/cisco_nxos_ssh.py", line 15, in session_preparation
   self.set_base_prompt()
File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 1070, in set_base_prompt
   prompt = self.find_prompt(delay_factor=delay_factor)
File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 1085, in find_prompt
   self.write_channel(self.RETURN)
File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 422, in write_channel
   self._write_channel(out_data)
File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 384, in _write_channel
   self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
File "/usr/lib/python2.7/site-packages/paramiko/channel.py', line 846, in sendall
   sent = self.send(s)
File "/usr/lib/python2.7/site-packages/paramiko/channel.py', line 801, in send
   return self._send(s, m)
File "/usr/lib/python2.7/site-packages/paramiko/channel.py', line 1198, in _send
   raise socket.error("Socket is closed")
socket.error: Socket is closed
2021-02-05 04:10:17,969 DEBUG: EOF in transport thread`

**Comment by ktbyers** [comment]
Purging old issues...
