### ISSUE TITLE
Nokia SR-OS changes

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#2104]
1. Split out MD-CLI and Classical CLI into separate drivers.
2. For classical CLI make it such that `enable()` call will work regardless of whether `configure enable-admin` has been configured. In other words, you should `always` be able to call `enable()` and have it work.
    a. If `configure enable-admin` is not configured, then `enable()` call is a  do nothing
    b. If `configure enable-admin` is configured, then `enable()` call  will execute `enable-admin`

**Comment by hellt** [comment]
Hi Kirk,
why do you scope these long term changes to Classic mode only? I think that should also apply to MD mode SR OS as well, as both can be configured with `enable` privileges escalation

**Comment by ktbyers** [comment]
They are two separate items: 
1) I want to fix the enable issue.
2) I want to split out the driver into two separate drivers as this current overloading of single driver to two separate platforms is fundamentally against how Netmiko operates (i.e. Netmiko device_type is intended to always be a single OS with one set of behavior patterns and this is two).

**Comment by ktbyers** [comment]
Purging old issues...
