### ISSUE TITLE
show interface brief textfsm error on nxos

### ISSUE THREAD

**Issue by bkt0031** [ktbyers/netmiko#2108]
I run a show interface brief command on a Cisco Nexus switch and I get the following message on various switches on the network:

```
venv\lib\site-packages\textfsm\parser.py:375: FutureWarning: Possible set difference at position 39
  self.regex = re.compile(pattern)
```

I noticed that one of the interfaces is missing in the dictionary returned by 
`int_brief = c.send_command('show int brief', use_textfsm=True)`

Looking at the output of the show interface brief command on the switch with the error I see the missing interface showing up as:

`Eth4/16       monitor eth  access up      none                        10G(D) --`

Where the word 'monitor' shows up in the VLAN column. This port is configured as a span port on the switch.

If I remove the use_textfsm the output shows the port in question:

`Eth4/16       monitor eth  access up      none                        10G(D) --`

Sorry I forgot - running Python 3.8.1 on Windows 10 and netmiko version 3.3.2

**Comment by ktbyers** [comment]
It sounds like an ntc-templates or textfsm issue so you should report the issue there.


Regards, Kirk
