### ISSUE TITLE
Can netmiko used to ZTE equipment？

### ISSUE THREAD

**Issue by Mic0623** [ktbyers/netmiko#2110]
Dear ktbyers:
I have two ZTE router， can i use netmiko?
how to define the value of the device_type?
king regards.

**Comment by ktbyers** [comment]
There is a `zte_zxros` device_type:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/ssh_dispatcher.py#L209

**Comment by Mic0623** [comment]
> There is a `zte_zxros` device_type:
> 
> https://github.com/ktbyers/netmiko/blob/develop/netmiko/ssh_dispatcher.py#L209

ok thank you very much！
