### ISSUE TITLE
Cisco ios: do not send enable password if not required

### ISSUE THREAD

**Issue by icovada** [ktbyers/netmiko#2113]
Netmiko sends the enable password right after sending the "enable" command without verifying if the password is actually needed. Without `no ip domain-lookup` the timeout expires and the command fails

Debug logs:

```
worker_1  | DEBUG:netmiko:Pattern found: Switch 
worker_1  | Switch>
worker_1  | DEBUG:netmiko:write_channel: b'enable\r\n'
worker_1  | DEBUG:netmiko:Pattern is: (Switch|ssword)
worker_1  | DEBUG:netmiko:read_channel: 
worker_1  | DEBUG:netmiko:read_channel: enable
worker_1  | Switch#
worker_1  | DEBUG:netmiko:Pattern found: (Switch|ssword) enable
worker_1  | Switch#
worker_1  | DEBUG:netmiko:write_channel: b'cisco\r\n'
worker_1  | DEBUG:netmiko:Pattern is: Switch
worker_1  | DEBUG:netmiko:read_channel: 
worker_1  | DEBUG:netmiko:read_channel: cisco
worker_1  | Translating "cisco"...domain server (255.255.255.255)
worker_1  | DEBUG:netmiko:read_channel: 
```

**Comment by ktbyers** [comment]
If no enable secret is required, wouldn't you set the `secret` to be a null-string? In other words, you don't need a secret, but you are setting one in your Netmiko definition.

Do you want to try that and see if it works?

**Comment by icovada** [comment]
I will test this, however I still think this is not the correct behaviour

I am writing a tool to help us stage network devices and with the millions of different releases and code trains Cisco has it's very hard to foresee how a specific machine will behave

I remember years ago when routers started booting with a one-time account "cisco/cisco", some come with access lists on line vty and some don't.

Passing "cisco" as enable password should be a safe option that only gets used if actually necessary, just like it is not used if after login the shell drops you in privileged exec mode

**Comment by ktbyers** [comment]
What is unsafe about the current behavior? You just don't like that the `secret` could be logged or you don't like the `ip domain-lookup` delay? I am just trying to understand your concern here?

Regards, Kirk

**Comment by icovada** [comment]
My issue is that the name resolution timeout causes netmiko to fail the authentication with a generic "authentication failed" error

Sure, increasing the timeout could fix this, but it would be easier t just check if we get a `Password:` prompt or not instead of forcing the user to figure out why the authentication might have failed and try again with other credentials

I'll look into it myself this weekend and send a PR, I just haven't had time yet these two days

**Comment by ktbyers** [comment]
Okay, that is probably okay (as far as a PR). We just need to add a conditional here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1682

**Comment by icovada** [comment]
It's not that easy, because read_until_pattern() actually reads beyond pattern and it causes a race condition:

How it should be:
- send "enable"
- `read_until_pattern(pattern='enable')` returns "R1>enable"
- `read_until_prompt_or_pattern('ssword')` returns either "Password:" or "R1#"

How it is:
- send "enable"
- `read_until_pattern(pattern='enable')` returns "R1>enable\r\nR1#" ([read_until_pattern actually reads beyond pattern](https://github.com/ktbyers/netmiko/blob/8c976ce411f0ad17eea93af7d0f981239c1afad1/netmiko/base_connection.py#L535))
- Check whether "ssword" is in the output of previous command. It's not.
- Try again, but `read_until_prompt_or_pattern(prompt='ssword')` times out because there is no subsequent output

Problem is, there should be a way to check if we are in enable mode just after [line 1677](https://github.com/ktbyers/netmiko/blob/8c976ce411f0ad17eea93af7d0f981239c1afad1/netmiko/base_connection.py#L1677) otherwise we risk causing a race condition

**Comment by AJ-Acevedo** [comment]
What if instead of checking if enable mode is active, you check the privilege level of the user signing in?

If the user has a privilege 15 then there is no need to pass the enable password.

**Comment by ktbyers** [comment]
@AJ-Acevedo No, I wouldn't want state check on the user and that would be veryCisco specific (and this is a general method that applies to 60+ networking platforms).

@icovada Okay, add a second if-conditional. The read beyond pattern is a harder bug to fix, I will probably see if I can fix that in Netmiko4.


Regards, Kirk

**Comment by icovada** [comment]
I've been thinking about it and I think it's wrong, cli scraping is hard enough as it is, a delicate brittle balance between machines talking to machines as if they were two humans

I do not want to introduce a race condition in this important piece of code that might break too many people's workflow when the fix is just not passing the secret argument to the function. The greater good is more important than my little hack

Just keep it in mind for netmiko4
