### ISSUE TITLE
send_command strips the trailing blank from the end of the command

### ISSUE THREAD

**Issue by sysjm00** [ktbyers/netmiko#2121]
I am sending a command to a  Cisco router using send_command and I am using the | include feature at the end of the command.  In my search, I need a blank at the end of the include parameter to get a unique response but the send_command appears to be stripping the blank from the end and my results are incorrect.  Thanks,

**Comment by sysjm00** [comment]
After looking at the Netmiko code and seeing that the rstrip coudl be avoided by using the normalize=False option, I set that parameter and appended a \n (RETURN) and that seemed to correct the issue.  Sorry for posting the issue before looking into this further.

**Comment by ktbyers** [comment]
No worries at all...
