### ISSUE TITLE
The Slack Invitation Link is inactive

### ISSUE THREAD

**Issue by whitehacker** [ktbyers/netmiko#2122]
How can I join the Slack channel?

**Comment by schautwb** [comment]
Here an updated invite link: https://join.slack.com/t/pynet/shared_invite/zt-km2k3upf-AkWHY4YEx3sI1R5irMmc7Q

**Comment by AJ-Acevedo** [comment]
I submitted a pull request using the above Slack invite link.

**Comment by alkisg** [comment]
Hi @ktbyers, the link is inactive once more.

**Comment by schautwb** [comment]
@alkisg here is a invite link [https://join.slack.com/t/pynet/shared_invite/zt-1uoyeufkw-CKZ6iW9Pag3MW4RS0DytVg](url)
