### ISSUE TITLE
/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv     out = self.in_buffer.read(nbytes, self.timeout)

### ISSUE THREAD

**Issue by juliansw** [ktbyers/netmiko#2123]
I am running a script with 2 actions, that are run depending on the action variable.  The "ban" part of the script that connects to the ASA and creates a new network object works perfectly.  The unban part that connects and removes the object does not work. It does get upto the first "no" command.   'no network-object object ' + param_3 + param_1, . The script then fails. This command is completed on the ASA, but it dos not run the remaining 3 commands, or save and exit. 

I have attached the script, log and original error. 
[script.txt](https://github.com/ktbyers/netmiko/files/5860574/script.txt)
[error.txt](https://github.com/ktbyers/netmiko/files/5860578/error.txt)
[log.txt](https://github.com/ktbyers/netmiko/files/5860579/log.txt)

**Comment by ktbyers** [comment]
@juliansw Try setting `allow_auto_change=True` as an argument to ConnectHandler (this will change the terminal width of the device). The output of the commands are getting distorted as the ASA wants to make the output more human readable for long commands.

https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_asa_ssh.py#L40

**Comment by juliansw** [comment]
@ktbyers thanks, that worked perfectly. Thanks for the help.
