### ISSUE TITLE
Need to add IPv6 support for connections.

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#213]

**Comment by davama** [comment]
Looks like there hasn't been much movement here. Whats the latest?

We are testing ntc-ansible which depends on netmiko and found that it works only on ipv4 but not ipv6

netmiko (1.4.2)
ntc-ansible (0.1.0)

We are willing to test.

Thank you,
Dave

**Comment by ktbyers** [comment]
Yes, I haven't done anything on this. 

It would be interesting to see what happens if you just tried to feed it a `host=dns_name` where dns_name resolved to an IPv6 address or an `ip=ipv6_addr` argument.

In other words, I am passing these to Paramiko so it would be interesting to see what Paramiko does (if we passed in an IPv6 address.

@davama

**Comment by netengdj** [comment]
I can already tell you it does not work.  I have this exact setup and am using netmiko.  Someone just turned off IPv4 on a lab device and made it so DNS resolved to ipv6 address.  Netmiko just times out eventually with no attempt to connect.

**Comment by ktbyers** [comment]
@netengdj Can you post the exception you get when this happens?

**Comment by ktbyers** [comment]
Also what arguments are you using to ConnectHandler (you can obscure anything that is confidential).

**Comment by lazhao123** [comment]
I also found ipv6 addr doesn't work when connect. Both paramiko and netmiko timeout.
The arguments are:
cisco = {
    'device_type':'cisco_nxos',
    'ip':'fe80::be26:c7ff:fexxxx%ens33',
    'username':'admin',
    'password': 'admin',
}

   ...: connect=ConnectHandler(**cisco)
   ...: 
Traceback (most recent call last):
  File "/root/learn_lab/netmiko-exp/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 858, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/root/learn_lab/netmiko-exp/venv/lib64/python3.6/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/root/learn_lab/netmiko-exp/venv/lib64/python3.6/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/root/learn_lab/netmiko-exp/venv/lib64/python3.6/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/learn_lab/netmiko-exp/venv/lib64/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-7681cad37737>", line 9, in <module>
    connect=ConnectHandler(**cisco)
  File "/root/learn_lab/netmiko-exp/venv/lib64/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 228, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/root/learn_lab/netmiko-exp/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 312, in __init__
    self.establish_connection()
  File "/root/learn_lab/netmiko-exp/venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 864, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_nxos fe80::be26:c7ff:xxxxxxxxx%ens33:22

**Comment by ktbyers** [comment]
Yes, when I looked into this--it wasn't as easy as I hoped. I hoped it would just work, but alas no.

I think we might also have to specify the source interface i.e. that it was a combination of the IPv6 address and the source interface. I don't know if this was particular to the Paramiko implementation or how sockets in IPv6 are implemented (I suspect more the latter).

If anyone wants to work on this, create a PR--that would be great.

**Comment by lazhao123** [comment]
Hi Kirk,

Thank you for reply. I used ens33 in the argument.
==============================
The arguments are:
cisco = {
'device_type':'cisco_nxos',
'ip':'fe80::be26:c7ff:fexxxx%ens33',     <-- source interface
'username':'admin',
'password': 'admin',
}

**Comment by lazhao123** [comment]
Hi Kirk,

Thank you for reply. I used ens33 in the argument.
==============================
The arguments are:
cisco = {
'device_type':'cisco_nxos',
'ip':'fe80::be26:c7ff:fexxxx%*ens33*',     <-- source interface
'username':'admin',
'password': 'admin',
}

**Comment by ktbyers** [comment]
This looks to work using Paramiko 2.6.0:

```python
from netmiko import ConnectHandler
from getpass import getpass

ip = "fe80::439:dcff:fea1:999a%eth0"
username = "pyclass"
password = ""

net_connect = ConnectHandler(ip=ip, username=username, password=password, device_type='linux')
print("-------")
print(net_connect.find_prompt())
print("-------")
```

This was too a Linux machine. Though I had someone online using the same format:

```
link_local%source_interface
```

To connect to an HP_ProCurve/Aruba device.

It would be interesting to the behavior with an IPv6 global unicast addresses

**Comment by ktbyers** [comment]
Jeff just did some additional testing and verified it worked for IPv6 global unicast address (connecting to an "hp_procurve" device type).
