### ISSUE TITLE
Cisco ASA connect failure when device is already in enable mode after login

### ISSUE THREAD

**Issue by mrkcmo** [ktbyers/netmiko#2139]
Works in version 3.1.0 and breaks in version 3.3.0.

If the device is not in enable mode at login then it works correctly and goes into enable mode allowing the script to continue.

If the device drops to enable mode at login (aaa authorization exec LOCAL auto-enable) then we get the below traceback at login using 3.3.0 but not with 3.1.0.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1680, in enable
    pattern=pattern, re_flags=re_flags
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 669, in read_until_prompt_or_pattern
    return self._read_channel_expect(combined_pattern, re_flags=re_flags)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 580, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vpn_stats.py", line 313, in <module>
    vpnstats()
  File "vpn_stats.py", line 308, in vpnstats
    vpn_sess_obj.updateVpnSessionStats()
  File "vpn_stats.py", line 235, in updateVpnSessionStats
    cmd_out = self.__ciscoSessions(fw[X].strip())
  File "vpn_stats.py", line 138, in __ciscoSessions
    secret=self.password)
  File "/usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 315, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco/cisco_asa_ssh.py", line 15, in __init__
    return super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 346, in __init__
    self._open()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 352, in _open
    self._try_session_preparation()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 788, in _try_session_preparation
    self.session_preparation()
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco/cisco_asa_ssh.py", line 35, in session_preparation
    self.enable()
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco/cisco_asa_ssh.py", line 28, in enable
    cmd=cmd, pattern=pattern, enable_pattern=enable_pattern, re_flags=re_flags
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 25, in enable
    cmd=cmd, pattern=pattern, enable_pattern=enable_pattern, re_flags=re_flags
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1690, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.
```

**Comment by ghmj2417** [comment]
I was just going to create the same issue.  I am experiencing the exact same thing.  Thank you for opening this issue @mrkcmo.

**Comment by ktbyers** [comment]
Are you using Netmiko 3.3.0 or Netmiko 3.3.3?


Kirk

**Comment by ghmj2417** [comment]
I experienced it with 3.3.3.  I'm downgrading to 3.3.2 to see if encounter the same thing.  I'm pretty sure I saw the same issue in 3.3.2 but not as often.  I'll post more after I test the downgrade.

**Comment by ktbyers** [comment]
Second question does the problem go away if you set fast_cli=False?


Kirk

**Comment by mrkcmo** [comment]
> 
> 
> Are you using Netmiko 3.3.0 or Netmiko 3.3.3?
> 
> Kirk

It was 3.3.3 that I tested.

**Comment by mrkcmo** [comment]
> 
> 
> Second question does the problem go away if you set fast_cli=False?
> 
> Kirk

I will need to test this today. Anything else you want me to test as well?

**Comment by ktbyers** [comment]
@mrkcmo Grabbing the log output of the failing case would also be helpful:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

So we can see better what is going on.

**Comment by mrkcmo** [comment]
> 
> 
> Second question does the problem go away if you set fast_cli=False?
> 
> Kirk

I will need to test this today. Anything else you want me to test as well?

> 
> 
> > Second question does the problem go away if you set fast_cli=False?
> > Kirk
> 
> I will need to test this today. Anything else you want me to test as well?

I tried the fast_cli=False and got the same traceback.
`    def __ciscoSessions(self, host):
        try:
            dut = ConnectHandler(device_type='cisco_asa',
                                 host=host,
                                 username=self.username,
                                 password=self.password,
                                 secret=self.password,
                                 fast_cli=False)`

**Comment by mrkcmo** [comment]
> 
> 
> @mrkcmo Grabbing the log output of the failing case would also be helpful:
> 
> https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel
> 
> So we can see better what is going on.

Here is the log data:
`[root@usricsms006 Scripts]# more test.log 
INFO:netmiko:Processing Row: 31, TestDevice, Cisco, ASA 5525-X, 1.1.1.1
INFO:netmiko:Device Previous Current Sessions: 1
INFO:netmiko:Device Peak Sessions: 1
DEBUG:paramiko.transport:starting thread (client mode): 0x9b2a2be0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group14-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'aes128-ctr', 'aes192-ctr', 'a
es256-ctr'] server encrypt:['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-sha1', 'hmac-sha1-96'] server mac:['hmac-sha1', 
'hmac-sha1-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group14-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 1.1.1.1: b'513bfa643b989d8e9d52ce832dff82e2'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: 
DEBUG:netmiko:_read_channel_expect read_data:  
 
**********************************************************

DEBUG:netmiko:Pattern found:   
 
**********************************************************

DEBUG:netmiko:write_channel: b'enable\n'
DEBUG:netmiko:Pattern is: enable
DEBUG:netmiko:_read_channel_expect read_data: *                                                        *
*               TESTS Global Networks TEST               *
*                                                        *

DEBUG:netmiko:_read_channel_expect read_data: **********************************************************
*                                                        *
*               !AUTHORISED PERSONNEL ONLY!              *
* YOU ARE LOGGING ON TO PRIVATE COMMUNCIATIONS EQUIPMENT *
*  IF YOU DO NOT HAVE PERMISSION TO DO SO, LOG OFF NOW   *
*           AND NO FURTHER ACTION WILL BE TAKEN.         *
*       !INTRUSION DETECTION SYSTEMS MONITOR 24 X 7!     *
*       REPEATED LOGON FAILURES WILL BE INVESTIGATED     *
*                                                        *
**********************************************************
*                                                        *
*      Contact Test@test.com for help.                   *
*                                                        *
**********************************************************
 
 
User Testuser logged in to TestDevice

DEBUG:netmiko:_read_channel_expect read_data: Logins over the last 91 days: 6057.  Last login: 00:30:22 UTC Feb 9 2021 from 10.238.13.97

DEBUG:netmiko:_read_channel_expect read_data: Failed logins since the last login: 0.  Last failed login: 08:30:22 UTC Jan 30 2021 from 10.238.13.4
Type help or '?' for a list of available commands.
TestDevice/pri/act# 
TestDevice/pri/act# 
DEBUG:netmiko:_read_channel_expect read_data: e
DEBUG:netmiko:_read_channel_expect read_data: nable
                      ^
ERROR: % Invalid input detected at '^' marker.
TestDevice/pri/act# 
DEBUG:netmiko:Pattern found: enable *                                                        *
*               SYKES Global Networks EMEA               *
*                                                        *
**********************************************************
*                                                        *
*               !AUTHORISED PERSONNEL ONLY!              *
* YOU ARE LOGGING ON TO PRIVATE COMMUNCIATIONS EQUIPMENT *
*  IF YOU DO NOT HAVE PERMISSION TO DO SO, LOG OFF NOW   *
*           AND NO FURTHER ACTION WILL BE TAKEN.         *
*       !INTRUSION DETECTION SYSTEMS MONITOR 24 X 7!     *
*       REPEATED LOGON FAILURES WILL BE INVESTIGATED     *
*                                                        *
**********************************************************
*                                                        *
*      Contact Test@test.com for help.                   *
*                                                        *
**********************************************************
 
 
User Testuser logged in to TestDevice
Logins over the last 91 days: 6057.  Last login: 00:30:22 UTC Feb 9 2021 from 1.1.1.2
Failed logins since the last login: 0.  Last failed login: 08:30:22 UTC Jan 30 2021 from 1.1.1.3
Type help or '?' for a list of available commands.
TestDevice/pri/act# 
TestDevice/pri/act# enable
                      ^
ERROR: % Invalid input detected at '^' marker.
TestDevice/pri/act# 
DEBUG:netmiko:Pattern is: (|ssword)
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
TestDevice/pri/act# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'exit\n'`

**Comment by mrkcmo** [comment]
@ktbyers here is the connect code snippet from the script:
```   
   def __ciscoSessions(self, host):
        try:
            dut = ConnectHandler(device_type='cisco_asa',
                                 host=host,
                                 username=self.username,
                                 password=self.password,
                                 secret=self.password)
            enable_check = dut.check_enable_mode(check_string='#')
            if enable_check:
                logger.info('Device is in enable mode')
            else:
                dut.enable()
                logger.info('Device has been put into enable mode')
```

**Comment by ghmj2417** [comment]
> I experienced it with 3.3.3. I'm downgrading to 3.3.2 to see if encounter the same thing. I'm pretty sure I saw the same issue in 3.3.2 but not as often. I'll post more after I test the downgrade.

I went back to 3.3.2 and no longer encounter this issue.

**Comment by tbiens** [comment]
I had similar problem. Except I do enable()

Then a send-command.

Search pattern never detected in send_command: asa\#

Reverting to 3.3.2 fixed the problem.

**Comment by ktbyers** [comment]
@mrkcmo @ghmj2417 Could one of you regression test the fix I linked to and see if it fixes your issue?

**Comment by mrkcmo** [comment]
> 
> 
> @mrkcmo @ghmj2417 Could one of you regression test the fix I linked to and see if it fixes your issue?
> 
> Hmmm, hold off on the testing...there are probably more things I need to do in that PR.

Just let me know when.

**Comment by ktbyers** [comment]
Sounds good...let me do a few more things and I will post an update here when it is ready to be tested.

**Comment by ktbyers** [comment]
@mrkcmo Okay, do you want to test that fix referenced in #2182 ?

**Comment by mrkcmo** [comment]
@ktbyers that appears to have fix it. @ghmj2417 and @tbiens  can you guys confirm as well?

**Comment by ktbyers** [comment]
I am going to merge that PR and then we can adjust/fix it, if there are still issues outstanding.
