### ISSUE TITLE
Embedded AP support

### ISSUE THREAD

**Issue by wellspokenman** [ktbyers/netmiko#214]
EDIT: better error handling EDIT2: disconnect syntax wasn't quite right
Would be nice to have an extension to the ssh Connection Object that added 'enterAP' and 'exitAP' methods. The commands included below work as imperative functions, but I haven't made a proper class extension. Important to clear any existing sessions to get a predictable prompt. Also important to have an extra carriage return after entering password. 

There are two quirks here that I can't explain: initial (as in first time after a full reload) login requires double entry of the user/password (hence my len(n) check) and commands seem to need a leading space. 

```
from netmiko import ConnectHandler
router_ssh = {
        'device_type': 'cisco_ios',
        'ip': "10.5.2.1",
        'username': "admin",
        'password': "password",
        'port' : 22, 
        'secret': 'ENABLE', 
        'verbose': True, 
        }

ssh_connect = ConnectHandler(**router_ssh)
user = router_ssh.get('username')
pwd = router_ssh.get('password')

def enterAP():
    ssh_connect.remote_conn.sendall('service-module wlan-ap 0 session clear\n')
    ssh_connect.remote_conn.sendall('\n')
    ssh_connect.read_until_pattern('#')
    ssh_connect.remote_conn.sendall('service-module wlan-ap 0 session\n')
    ssh_connect.read_until_pattern('sername')
    ssh_connect.remote_conn.sendall(user+'\n')
    ssh_connect.read_until_pattern('ssword')
    ssh_connect.remote_conn.sendall(pwd+'\n')
    ssh_connect.remote_conn.sendall('\n')
    ssh_connect.remote_conn.sendall('\n')
    output = ssh_connect.send_command(' show int dot11radio0')
    #output should be about 1100 in length. If not, we are not inside the AP. 
    if (len(output) < 500):
        #On initial login it seems I have to enter user/password twice
        ssh_connect.remote_conn.sendall('service-module wlan-ap 0 session clear\n')
        ssh_connect.remote_conn.sendall('service-module wlan-ap 0 session\n')
        ssh_connect.read_until_pattern('sername')
        ssh_connect.remote_conn.sendall(user+'\n')
        ssh_connect.read_until_pattern('ssword')
        ssh_connect.remote_conn.sendall(pwd+'\n')
        ssh_connect.remote_conn.sendall('\n')
        ssh_connect.remote_conn.sendall('\n')

def exitAP():
    ssh_connect.remote_conn.sendall(chr(30))
    ssh_connect.remote_conn.sendall('x')
    ssh_connect.remote_conn.sendall('disconnect\n')
    ssh_connect.read_until_pattern('confirm')
    ssh_connect.remote_conn.sendall('\n') 

enterAP()
ssh_connect.send_command(' terminal length 0') #note the leading spaces 
output = ssh_connect.send_command(' show int dot11radio0')
print "length: " + str(len(output)) #expected length
print output #expected output
exitAP() #back in host router
print ssh_connect.find_prompt()
```

**Comment by abaldan** [comment]
Hello,

I'm working on something similar, hence posting here.

I'd like to connect to a service-module installed on a router with the command "service-module gigabitEthernet 1/0 session" from the router console. I'm using something like this:


    user_nl = 'username\n' 
    pw_nl = 'password\n' 
    
    ssh_connect = ConnectHandler(**host_obj)
    sm_session_clr = 'service-module gigabitEthernet 1/0 session clear\n'
    ssh_connect.remote_conn.sendall(sm_session_clr)
    ssh_connect.remote_conn.sendall('\n')
    ssh_connect.read_until_pattern('#')

    sm_session_conn = 'service-module gigabitEthernet 1/0 session\n'
    ssh_connect.remote_conn.sendall(sm_session_conn)
    ssh_connect.read_until_pattern('sername')
    ssh_connect.remote_conn.sendall(user_nl)
    ssh_connect.read_until_pattern('ssword')
    ssh_connect.remote_conn.sendall(pw_nl)
    ssh_connect.remote_conn.sendall('\n')
    ssh_connect.remote_conn.sendall('\n')
    ssh_connect.read_until_pattern('>')

    print ssh_connect.find_prompt()
    output = ssh_connect.send_command('show ver | i Software')
    print output
    print ssh_connect.find_prompt()

    ssh_connect.remote_conn.sendall(chr(30))
    ssh_connect.remote_conn.sendall('x')
    ssh_connect.remote_conn.sendall('disconnect')
    ssh_connect.remote_conn.sendall('\n')
    print ssh_connect.find_prompt()

    ssh_connect.disconnect()


This works well as long as logging into the service-module does _not_ display a banner, i.e. when the session is something like this:

    router-cs1#service-module gigabitEthernet 1/0 session
    ...
    username: username
    password: 
    
        All configuration information on this router is confidential
    
    router-sw1a>

However it doesn't work when there's a banner between the password and the prompt:

    router-cs1#service-module gigabitEthernet 1/0 session 
    ...
    username: username
    password: 
    
           All configuration information on this router is confidential
    
    [Some logo banner here / ascii code] 
    
    US, Asia & Americas support:    +1 xxx xxx xxxx
    EMEA support:                   +xx xxx xxx xxxx
    
    **Unauthorized access to this network device is prohibited.**
    You must have explicit permission to access or configure this
    device.  All activities performed on this device are logged and
    violations of this policy may result in disciplinary action.
    
    router-sw1a line 0 
    
                           IT administered router.
            Mail "xxx@domain.com" with any proposed configuration changes,
                or call the Technical Resource Center at xx-xxxx.
    
    router-sw1a>

The error I get is the following (I turned on debugging in "read_until_pattern" of base_connection.py)

    Pattern found: sername service-module gigabitEthernet 1/0 session
    Trying 192.168.1.1, 2067 ... Open
     
    [Some logo banner here / ascii code]
    
    US, Asia & Americas support:    + 1 xxx xxx xxxx
    EMEA support:                   +xx xxx xxx xxxx
    
    **Unauthorized access to this network device is prohibited.**
    You must have explicit permission to access or configure this
    device.  All activities performed on this device are logged and
    violations of this policy may result in disciplinary action.   
    
    router-cs1 line 67 backplane_to_switchmodule
    
    username: 
    Pattern is: ssword 
    Pattern found: ssword username
    password: 
    Pattern is: \>
    Traceback (most recent call last):

      File "./access_class_add_cs_line.py", line 171, in <module>
        Verify(host, eth_port)
      File "./access_class_add_cs_line.py", line 136, in Verify
         ssh_connect.read_until_pattern('>')
      File "/usr/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 393, in    read_until_pattern
        raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
    netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
@abaldan On the face of it, I am not seeing why that is failing. Let me get back to you on some additional debugging to do.


Kirk

**Comment by ktbyers** [comment]
@abaldan Are you still having this issue?

**Comment by ktbyers** [comment]
I think we should probably add a special method into cisco ios to handle this service module login process.

**Comment by ktbyers** [comment]
Not fixed. You could solve this with redispatch and handling the username/password in your code.
