### ISSUE TITLE
write output on a file without sending command to device

### ISSUE THREAD

**Issue by hamzou** [ktbyers/netmiko#2141]
Hello,

I would like to know if it is possible to get output from "?" command without sending the command to the device. For example, I have a Fortigate in a test environment, in fortigate CLI, we can use "?" to show different possibilities of commands that we can enter. I would like to have the result of the command below written in a file.

_**FortiGate-VM64-KVM # show router policy "?"
seq-num    Sequence number(1-65535).
1
2
1200
3
4**_
 
Do you know if it is possible thanks to netmiko ? 

Best regards.

**Comment by mrkcmo** [comment]
@hamzou I would think you could just send the command as normal if the output includes the device prompt in the return.

**Comment by ktbyers** [comment]
Yes, you should be able to reproduce whatever you do via the CLI? Note, just like via the CLI you would have to delete your command if you wanted to do something else after this).

Regards, Kirk

**Comment by hamzou** [comment]
Hello,

Thank you for your response, the command that @mrkcmo adviced me is correct. I will be able to do something good with it, thank you very much ! :)
