### ISSUE TITLE
Add enterasys telnet

### ISSUE THREAD

**Issue by narcotico-g** [ktbyers/netmiko#2151]
Hello,

I have added telnet for enterasys with same code than enterasys SSH (I have old devices with SSH problems). Each update I have to modify again, could you add for next version? I guess this it would be a pull request, however after trying it I have not very clear how to do it.

Thanks.

`"""Enterasys support."""
import time
from netmiko.cisco_base_connection import CiscoSSHConnection

class EnterasysTelnet(CiscoSSHConnection):
    """Enterasys support."""

    def session_preparation(self):
        """Enterasys requires enable mode to disable paging."""
        self._test_channel_read()
        self.set_base_prompt()
        self.disable_paging(command="set length 0")
        # Clear the read buffer
        time.sleep(0.3 * self.global_delay_factor)
        self.clear_buffer()

    def save_config(self, *args, **kwargs):
        """Not Implemented"""
        raise NotImplementedError
`

**Comment by ktbyers** [comment]
@narcotico-g You would need to do a pull request on it and run the Netmiko test suite against the telnet driver.

The testing process is here:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

**Comment by narcotico-g** [comment]
Hello,

I read testing.md, however there is no "enterasys" device_type in *.yml files for running test.

**Comment by ktbyers** [comment]
Yeah, you have to edit the YAML files and add the relevant entries.


Regards, Kirk
