### ISSUE TITLE
Speed up responses

### ISSUE THREAD

**Issue by JoshNetDiag** [ktbyers/netmiko#2161]
Hey guys,

Is there any way to 'speed up' netmiko's responses; I am writing some software that polls the switch for all the interfaces, and then does a number of status lookups for each interface. For a 48 port switch with a few port-channels, it takes about 5 minutes.

I have tried to do this all within the same SSH session to make it quicker, but its still taking longer than I would have hoped!

General gist of my code below (using cisco_ios as device_type)

```
    def poll_interface(self):
        """Pull interface configuration"""
        net_connect = ConnectHandler(**self.net_switch)
        config_commands = "show interface description"
        net_connect.enable()
        dirty_interface_out = net_connect.send_command(config_commands)
        interface_dict = cisco_list_interface_sanitizer(dirty_interface_out)
        net_connect.disconnect()
        interface_dict_detailed = {}
        interface_dict_detailed = self.poll_interface_details(interface_dict)
        return interface_dict_detailed

    def poll_interface_details(self, interface_dict):
        """return the interface configuration"""
        i = 0
        net_connect = ConnectHandler(**self.net_switch)
        net_connect.enable()
        output = {}
        for i in interface_dict:
            if "cisco" in self.net_switch["device_type"]:
                int_config = net_connect.send_command("show run interface " + interface_dict[i]['ID'])
                if "switchport mode trunk" in int_config:
                    interface_type = "trunk"
                elif "switchport mode access" in int_config:
                    interface_type = "access"
                else:
                    interface_type = "access"
                mac_list = self.poll_interface_mac(interface_dict[i]['ID'])
                if interface_type == "trunk":
                    interface_vlans = cisco_trunk_vlans_sanitizer(int_config)
                if interface_type == "access":
                    interface_vlans = cisco_access_vlans_sanitizer(int_config)
                dty_int_status = net_connect.send_command("show interface " + interface_dict[i]['ID'])
                interface_status = cisco_interface_status_sanitizer(dty_int_status)
                output[interface_dict[i]['ID']] = {
                    "macs": mac_list,
                    "interface_type": interface_type,
                    "vlan": interface_vlans,
                    "status": interface_status
                }
                i += 1
            elif "arista" in self.net_switch["device_type"]:
                return("Operating system not supported for this feature")
            else:
                return("Operating system not supported for this feature")
        net_connect.disconnect()
        return output
```

**Comment by ktbyers** [comment]
@JoshNetDiag Execute a single `show run` command and parse the config entirely locally on the box. This would be pretty easy with TTP (template text parser).

**Comment by JoshNetDiag** [comment]
@ktbyers thanks Kirk, actually a very creative and intelligent idea! - that being said, not everything I want will be encapsulated in the running config. For example the MAC addresses per interface & the status (up/down) for each interface. Having run some tests, it appears that the lag is coming entirely from netmiko's `.send_command()` function, do you know if there is anyway (either via environment, or parameters) to reduce the lag?

**Comment by ktbyers** [comment]
A few things:

1. Make sure you are using the latest released Netmiko version as there have been relatively recent performance improvements.
2. Make sure fast_cli=True (it probably will be).
3. Once fast_cli=True, you can try to adjust downward the global_delay_factor (I think it defaults to .1 when fast_cli=True, but don't quote me on that so you could try .05 or .02 et cetera).

At some point for low value of global_delay_factor, your code will stop working reliably.

4. If that doesn't work, then you could write your own custom solution using write_channel() and read_channel()


But that all being said my solution to the problem would be to convert all or as many of the commands to a single command and then parse on the automation machine (so commands like `show interfaces`, `show run`, `show ip int brief`). 

You will probably have a difficult time getting the response time below a second per command so if you are running 150+ commands it will take a while (using your pattern where you are sending lots of commands).


Regards, Kirk

**Comment by ktbyers** [comment]
I am going to close this. Just ping me if there are more questions here.
