### ISSUE TITLE
Juniper send_config_from_file doesnt commit

### ISSUE THREAD

**Issue by czkoudy** [ktbyers/netmiko#2165]
Hi,

`#!/usr/bin/env python3
from __future__ import print_function, unicode_literals
# Netmiko is the same as ConnectHandler
from netmiko import Netmiko

cfg_file = pathtofile

net_connect = Netmiko(device_type='juniper_junos', host = ipaddress, username='username', password='password')

output = net_connect.send_config_from_file(cfg_file)

output = net_connect.commit(and_quit=True)

print()
print(output)
print()
`

with the above code i can see correct output as far as commit goes but the i see this:
`exit configuration-mode
The configuration has been changed but not committed
Exiting configuration mode
`

and after that it will print commited. But when exiting config mode it wont save the changes si it will commit nothing. ANyone can help. I have update to python 3.6 and netmiko 3.3.3. Before with python 2.7.5 and netmiko 2.x it worked just fine

Iam not quite sure what am i doing wrong here

**Comment by czkoudy** [comment]
Apologies, you can close this. I have to start reading docs with both eyes open :-)

`net_connect.send_config_from_file(cfg_file, exit_config_mode=False)`

**Comment by czkoudy** [comment]
ok maybe not :-D

This is my out from .py
`[root@whm /]# python3 /home/portal/public_html/admin/client/python/firewallConfig.py client_name ip_address root_dir site_id
Traceback (most recent call last):
  File "/home/oregaportal/public_html/admin/client/python/firewallConfig.py", line 24, in <module>
    net_connect.commit()
  File "/usr/local/lib/python3.6/site-packages/netmiko/juniper/juniper.py", line 192, in commit
    delay_factor=delay_factor,
  File "/usr/local/lib/python3.6/site-packages/netmiko/utilities.py", line 430, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1531, in send_command
    search_pattern
OSError: Search pattern never detected in send_command: root\@SRXA\#
`
and this is .py file:
`#!/usr/bin/env python3
from __future__ import print_function, unicode_literals
# Netmiko is the same as ConnectHandler
from netmiko import Netmiko

import sys

args = sys.argv[1:]

# Creating a dictionary
switch = {}
switch['clientName'] = args[0]
switch['ipAddress'] = args[1]
switch['rootDir'] = args[2]
switch['siteID'] = args[3]


cfg_file = switch['rootDir'] + "admin/client/configuration/" + switch['siteID'] + "/" + switch['clientName'] + "/firewallConfiguration.txt"

net_connect = Netmiko(device_type='juniper_junos', host = switch['ipAddress'], username='username', password='password')

output = net_connect.send_config_from_file(cfg_file, exit_config_mode=False)

net_connect.commit()


print()
print(output)
print()`

I have similar script for core switch from HP and this works just fine. Ive tried everything but still its not working properly. Losing my mind now :-)

**Comment by czkoudy** [comment]
And its me again. Fixed it using
`fast_cli= False, global_delay_factor = 5` 

Thank you

**Comment by ktbyers** [comment]
No worries, that last part is sort of hard (i.e. the commit operation takes a long time on Juniper so it might fail due to Netmiko not allocating enough time for it). Hopefully, will be improved in Netmiko4.
