### ISSUE TITLE
Cisco ASA waiting for ENTER in configuration mode

### ISSUE THREAD

**Issue by tbankdev** [ktbyers/netmiko#2171]
Hello, I am trying to confirm that yes I do want to remove that by virtually pressing ENTER. I was trying multiple ways but nothing worked in configuration mode. Please help if you can.

`FW-IOT-ASA/act/pri(config)# no context client-janedoe
WARNING: Removing context 'client-janedoe'
Proceed with removing the context? [confirm] 
`
This is where i would need to press enter to confirm the deletion.

**Comment by ktbyers** [comment]
You probably would need to go into config mode using the config_mode() method and then handle the prompting. An example for handling prompting is here:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-timing

So the code would be something like:

```python
net_connect.config_mode()
output = net_connect.send_command_timing("no context client-janedoe")
if 'confirm' in output:
    # Here I am assuming it requires a "y", but if it just required an enter you would do "\n")
    output += net_connect.send_command_timing("y")
net_connect.exit_config_mode()
```
