### ISSUE TITLE
How to see "show cli command" that I entered on the fetched terminal

### ISSUE THREAD

**Issue by networkjourney** [ktbyers/netmiko#2172]
Hi Kirk
Is there a way to also see the entered command on terminal.
Bcaz by default in netmiko fetched output the "cli" is not visible.
We need to enter Print for doing that but anyway to turn on this feature using a special tag/filter

**Comment by ktbyers** [comment]
You probably should look into the Netmiko session_log. You can `tail -f` this file to get more information on what is happening, close to real-time.


Kirk
