### ISSUE TITLE
Bind address

### ISSUE THREAD

**Issue by bojika** [ktbyers/netmiko#2173]
Hi, 

Is it possible to point out the bind address for ssh connection?
Could somebody show me an example how to do it?

Thanks,
Alexey

**Comment by ktbyers** [comment]
You mean the source IP the SSH connection is coming from?

**Comment by ktbyers** [comment]
```
ipdb> conn.remote_conn.transport.sock.getsockname()
('172.30.0.171', 43152)
```

Where `conn` is the Netmiko object.

**Comment by bojika** [comment]
For example I have two interfaces/two IPv4 addresses.
How can I chose which IPv4 address to use as a source for the ssh connection?

**Comment by ktbyers** [comment]
For IPv4, I believe it uses your routing table...so most specific route wins.
