### ISSUE TITLE
Can't enter enable mode where host name contains '#'

### ISSUE THREAD

**Issue by ddchristian** [ktbyers/netmiko#2179]
Hello,

I'm using the 'cisco_ios' driver to ssh a bunch of Cisco Access Points. My script works fine except for when I have an AP with a host name that contains the character '#' e.g. hostname = AP158-#10.

It looks like the enable process scans for '#' in the output to determine if the device is in enable mode. Since I have '#' in the hostname it assumes it's already in enable mode and doesn't do anything.

net_connect.check_enable_mode() returns True.
If I modify it by setting the check_string it correctly returns False:
net_connect.check_enable_mode(check_string='AP158-#10#')

I'm looking for a way to modify the net_connect.enable() process in a similar way.

Here is a code snippet:

`
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

device_ssh = {
    'device_type': 'cisco_ios',
    'ip': ap_ip,
    'username': ssh_userId,
    'password': ssh_passwd,
    'secret': ap_enable,
    'port' : 22,
}

net_connect = ConnectHandler(**device_ssh)
output = net_connect.find_prompt()
print(output)
net_connect.enable()
output = net_connect.find_prompt()
print(output)
print(net_connect.check_enable_mode())
print(net_connect.check_enable_mode(check_string='AP158-#10#'))
`

This is the output it presents:

`AP158-#10>

AP158-#10>

True

False
`

Here is the partial logging output:

`
DEBUG:netmiko:terminal length 0

DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

AP158-#10>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is AP158-#10>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

AP158-#10>
AP158-#10>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is AP158-#10>
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: AP158\-\#10
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: 
AP158-#10>
AP158-#10>
DEBUG:netmiko:Pattern found: AP158\-\#10 

AP158-#10>
AP158-#10>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

AP158-#10>
AP158-#10>

AP158-#10>
AP158-#10>

AP158-#10>
AP158-#10>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is AP158-#10>
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: AP158\-\#10
DEBUG:netmiko:_read_channel_expect read_data: 

AP158-#10>
AP158-#10>
DEBUG:netmiko:Pattern found: AP158\-\#10 

AP158-#10>
AP158-#10>
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: AP158\-\#10
DEBUG:netmiko:_read_channel_expect read_data: 

AP158-#10>
AP158-#10>
DEBUG:netmiko:Pattern found: AP158\-\#10 

AP158-#10>
AP158-#10>
`

**Comment by ktbyers** [comment]
Yeah, you would probably need to change your hostname to not use that pattern. Using a `#` as part of the hostname itself will break all sorts of things.

I guess you could write a special function using write_channel() and read_channel() to handle the enable call and password, but the best long-term solution is to probably not use that format for your hostname (given that it conflicts with the standard terminating character that indicates enable mode).
