### ISSUE TITLE
Unifi switch returns "failed to enter enable mode" upon connect

### ISSUE THREAD

**Issue by RobBie1221** [ktbyers/netmiko#2183]
When trying out the `UbiquitiUnifiSwitchSSH` class, I keep running in "failed to enter enable mode".

I used a debugger to see where it goes wrong. 
It successfully sends out the command here:
https://github.com/ktbyers/netmiko/blob/d0dc0c0dc8d2a52c0c5b92d60cd1427e71878d4c/netmiko/base_connection.py#L1677
Then with this line:
https://github.com/ktbyers/netmiko/blob/d0dc0c0dc8d2a52c0c5b92d60cd1427e71878d4c/netmiko/base_connection.py#L1679
The output becomes `enable\r\n\r\n(UBNT) #`
That is the correct response, the session is in "enable" now. Nothing more is needed. It however does not see the pattern `ssword` in the output, so here:
https://github.com/ktbyers/netmiko/blob/d0dc0c0dc8d2a52c0c5b92d60cd1427e71878d4c/netmiko/base_connection.py#L1681-L1683
It's going to read until prompt or pattern. This function times out because no more output is coming.

I can see, at the time this code was merged, the function looked differently:

https://github.com/ktbyers/netmiko/blob/16f735751fb39021bab235de1625f18a7367e604/netmiko/base_connection.py#L1546-L1575

I suppose that code will work, given that it will only do one read.

I think the existing logic does not work with Unifi Switch because no password should be entered. I'm willing to push some code, but would need some guidance then what would be an appropriate solution.

**Comment by RobBie1221** [comment]
Maybe a fix would be to add `enable` to `UbiquitiUnifiSwitchSSH` and call `super().enable` with a different pattern?

**Comment by ktbyers** [comment]
@RobBie1221 Can you show me what the UnifiSwitch `enable` command looks like when you do it manually from the CLI?

So above you are saying, "you just `enter "enable"` and it goes straight into `enable` mode without a password? Is that a function of how you have the device configured? I assume different configurations would prompt you for a password?

**Comment by RobBie1221** [comment]
![Screenshot_20210324-184724_Termius~2](https://user-images.githubusercontent.com/31007358/112359378-7f7ec500-8cd1-11eb-82a6-e5e95919be51.jpg)

This is the default config, that it prompts without password. I'm not sure if you can enable one and how.

**Comment by ktbyers** [comment]
@RobBie1221 Which version of Netmiko are you using?


Kirk

**Comment by RobBie1221** [comment]
3.3.3

**Comment by ktbyers** [comment]
Can you post the full exception stack trace?

**Comment by RobBie1221** [comment]
I can, not sure though what you are looking for. I debugged the code, on line 1679 it is waiting for the switch to prompt for password, which never happens. I then get a NetmikoTimeoutException.

**Comment by RobBie1221** [comment]
If I comment out lines below, it works perfectly, for Unifi (at least default config), it should not search for a prompt for password.

https://github.com/ktbyers/netmiko/blob/d0dc0c0dc8d2a52c0c5b92d60cd1427e71878d4c/netmiko/base_connection.py#L1680-L1684

**Comment by RobBie1221** [comment]
Here's the stack trace

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/lib/python3/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/lib/python3/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1679, in enable
    output += self.read_until_prompt_or_pattern(
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 669, in read_until_prompt_or_pattern
    return self._read_channel_expect(combined_pattern, re_flags=re_flags)
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 579, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/dev/netmiko/test_unifi.py", line 3, in <module>
    test = UbiquitiUnifiSwitchSSH(ip='192.168.123.123',username='user',password='blablabla',session_log='/home/test/test.log')
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 346, in __init__
    self._open()
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 352, in _open
    self._try_session_preparation()
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 788, in _try_session_preparation
    self.session_preparation()
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/ubiquiti/unifiswitch_ssh.py", line 21, in session_preparation
    self.enable()
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 24, in enable
    return super().enable(
  File "/home/test/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1690, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.
```

**Comment by ktbyers** [comment]
Is this standard Unifi switch behavior to go straight into enable mode without a password or does it depend on how the device is configured.

In other words, if you add a password/secret does it then prompt you?

**Comment by RobBie1221** [comment]
It is standard behavior not to prompt, I didn't set any config for that.
I don't know if and how a password/secret could be set and what it's behavior would be.

**Comment by ktbyers** [comment]
Should be fixed here:

https://github.com/ktbyers/netmiko/pull/2220

**Comment by RobBie1221** [comment]
Thanks!
