### ISSUE TITLE
ruckus_fastiron devices constantly throw NetMikoTimeoutException

### ISSUE THREAD

**Issue by QuasarKid** [ktbyers/netmiko#2186]
ruckus_fastiron devices seem to be randomly throwing NetMikoTimeoutExceptions. Here's my code:

```
def loginRuckus(ipAddress):
    #attempt to login
    try:
        return ConnectHandler(device_type='ruckus_fastiron', host=ipAddress, username=user, password=pw)
    except (AuthenticationException):
        print ('Authentication Failure: ' + ipAddress)
    except (NetMikoTimeoutException):
        print ('\n' + 'Timeout to device: ' + ipAddress)
    except (SSHException):
        print ('SSH might not be enabled: ' + ipAddress)
    except (EOFError):
        print ('\n' + 'End of attempting device: ' +  ipAddress)
    except Exception as e:
        print ('Some other error: %s' % e))
    return -1
```

If I call that function as seen below, the second call seems to always work, and if not the third usually does.
```
rk = -1
while rk == -1:
    time.sleep(.1)
    rk = loginRuckus(ip_add)
```

Enabling the netmiko logger for the devices that return that exception doesn't seem to generate any logging info.

The timeouts are adding quite a bit of time to the execution of my scripts, as the timeout takes quite long. This does not happen in my same code for my Cisco devices.

**Comment by QuasarKid** [comment]
The timeouts seems to take ~166 seconds. Changing the `global_delay_factor` to .2 results in it failing in ~122 seconds.

**Comment by ktbyers** [comment]
If you remove all of your try/except statements, which error/exception message do you receive? Can you post the full stack trace here?


Kirk

**Comment by QuasarKid** [comment]
Well, I went to go do that and even though I didn't change my code at all outside of the try/except it worked. I added the try/except back and it works. No idea what happened. Thanks!
