### ISSUE TITLE
Verifying every command in config_set for failure

### ISSUE THREAD

**Issue by manjitlazada** [ktbyers/netmiko#2192]
Hi,

I want to verify every command in config_set to be verified for failure before going for the next command in list.
Use Case is:
For below command sets to shut  the bgp neighbor may shut the whole BGP if the previous command is not verified
router bgp 65000, neighbor 1.1.1.1, shutdown 
If the neighbor command has failed it will shut the whole BGP.

So the idea is to have every command checked for successful execution and If failed the script should exit without executing further commands in set.

**Comment by network-shark** [comment]
It's just a for loop with an if 'unexpected input' -> sys.exit()

**Comment by ktbyers** [comment]
I plan on creating this, but it doesn't exist at this time.

Basically ad an argument like:

```
config_fail_pattern=""
```

Where you specify a regex string to search for that would indicate the configuration failed. If that pattern was ever encountered immediately stop executing the config changes and raise an exception.

Right now you would have to build your own function.
