### ISSUE TITLE
Pushing "show running formal" to a XRv

### ISSUE THREAD

**Issue by chrislrobson** [ktbyers/netmiko#220]
Test command string is: "rd-set 1111:22222\n"
netmike method used is: 
received_data = \
              ssh_handle.send_command_expect( cmd_data.split( '\n' )[0],
                                              delay_factor=delaycnt,
                                              max_loops=240,
                                              strip_prompt=True,
                                              strip_command=True )
Problem:  The system will hang when the above method is called.
None reason for problem:  The cisco command rd-set is a sub-system.  Unfortunately and unlike other commands subsystems where its possible to string the entire subsystem command into one string the issuing of the following command string will not work:  "rd-set 1111:222222 end-set\n", the system will complain.  It appears the XRv requires separated input streams.  While using a "cut/paste" into the console will work, building a stream such as "rd-set 1111:22222 \n end-set \n" (note the linefeeds) will not work.
Any suggestions?
Easy way to observe the problem is to use a typical "show running-config" output file which has the indented format as a pushed file through the netmiko method "send_command_expect"

thanks...Chris

**Comment by ktbyers** [comment]
Chris,

What do you get for an error message when you try to do this?



Kirk

On Fri, May 27, 2016 at 10:59 AM, chrislrobson <notifications@github.com>
wrote:

> Test command string is: "rd-set 1111:22222\n"
> netmike method used is:
> received_data = \
> ssh_handle.send_command_expect( cmd_data.split( '\n' )[0],
> delay_factor=delaycnt,
> max_loops=240,
> strip_prompt=True,
> strip_command=True )
> Problem: The system will hang when the above method is called.
> None reason for problem: The cisco command rd-set is a sub-system.
> Unfortunately and unlike other commands subsystems where its possible to
> string the entire subsystem command into one string the issuing of the
> following command string will not work: "rd-set 1111:222222 end-set\n", the
> system will complain. It appears the XRv requires separated input streams.
> While using a "cut/paste" into the console will work, building a stream
> such as "rd-set 1111:22222 \n end-set \n" (note the linefeeds) will not
> work.
> Any suggestions?
> Easy way to observe the problem is to use a typical "show running-config"
> output file which has the indented format as a pushed file through the
> netmiko method "send_command_expect"
>
> thanks...Chris
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/220>, or mute the thread
> <https://github.com/notifications/unsubscribe/AA26hMdLL4cbF-v0VRoDnoxLUBVUHmt_ks5qFzEbgaJpZM4Iou49>
> .
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by chrislrobson** [comment]
The problem is with the return prompt pattern.

There are at least two times the pattern is not what is expected when 
uploading line-by-line configurations into a Cisco box.

One fix, well not really a fix but configuration, but the other return 
pattern is a bit more challenging.

First when a command places the system into a subsystem, for example 
issuing "mpls oam", this puts the system in the MPLS subsystem where the 
prompt string "(config-aom)#" is returned and not the expected 
"(config)#".  This is easily overcome by including the 
"expect_string='#'" parameter in the send method call.

Another time the expected prompt string is not returned is issuing the 
"banner" with carrot and string with more than one input line.  For example:

banner login ^

   now is the time

  for all good men

^

What is returned is an empty unicode string.

The work around for this is to drop the loop counter to something small 
and simply continue on the exception.  Example code is:

            try:
               received_data = \
                 ssh_handle.send_command_expect( cmd_data.split( '\n' )[0],
                                                 expect_string = '#',
                                                 delay_factor = .5,
                                                 max_loops = 2, #240,
                                                 strip_prompt = True,
                                                 strip_command = True )
             except Exception as e:
               print( e.message )
               pass


The question is, is there a better way to handle unexpected prompt 
strings, aka, something without such a tight dependency?

Chris

**Comment by ktbyers** [comment]
@chrislrobson If you are sending config commands you should be using the send_config_set() or send_config_from_file() methods. The subcontext issue, for example '(config-if)#' should not be an issue. 

The banner command is probably a bit tricky, but can probably do this with send_config_set().

send_command_expect() could also possibly be made to work, but you might have to feed in an alternate terminating pattern using the expect_string argument.

**Comment by chrislrobson** [comment]
I'll give the send_config_set a try.

As you indicate, I did get the send_command_expect to work by simply 
setting the max-loop count down very low so delay was minimized and pass 
through the prompt string exception.  By doing this neither the changed 
prompt or banner upload cause problems. In fact, using a normal "show 
running-config" reports file is usable as a config upload file.  This 
has turned out to be critical because Cisco doesnt reformat the "show 
configuration running-config formal" reports file correctly, aka the 
class/policy sections dont get reformatted.  Anyway, at least there's a 
way for netmiko to process it which is the key.

Thanks....Chris

**Comment by ktbyers** [comment]
@chrislrobson Did send_config_set() work for this?

**Comment by chrislrobson** [comment]
Well not really, since the banner would still be an issue, opted to keep 
my workaround of setting the repeat and delay counters low.  This is 
acceptable and seems to work consistently.

If I can get some time, I'll give config_set a try just to test it out.

Thanks

Chris
