### ISSUE TITLE
Cisco IOS device fails to enter config mode properly

### ISSUE THREAD

**Issue by Eng20** [ktbyers/netmiko#2204]
I've error when using send_config_set method in Netmiko with cisco_ios and but other methods are working normally, Thanks for your kind support . [Noted that : this is virtual LAB ]

`from netmiko import ConnectHandler
from getpass import getpass

password = getpass()

cisco = {
    'device_type': 'cisco_ios',
    'host':'192.168.100.10',
    'username':'R1',
    'password':password,

}

net_connect = ConnectHandler(**cisco)

output = net_connect.send_command('show ip int brief')
print(output)

config_commands = ['config t', 'int loop 1', 'ip address 1.1.1.1 255.255.255.255']
output = net_connect.send_config_set(config_commands=cisco)
print (output)

cisco.disconnect()

===================================================================================================

C:\Users\engmo>python C:/Users/engmo/PycharmProjects/Netmiko/Netmiko.py
Password:

Interface                  IP-Address      OK? Method Status                Protocol
Ethernet0/0                unassigned      YES NVRAM  administratively down down
Ethernet0/1                192.168.100.10  YES NVRAM  up                    up
Ethernet0/2                unassigned      YES NVRAM  administratively down down
Ethernet0/3                unassigned      YES NVRAM  administratively down down
Ethernet1/0                unassigned      YES NVRAM  administratively down down
Ethernet1/1                unassigned      YES NVRAM  administratively down down
Ethernet1/2                unassigned      YES NVRAM  administratively down down
Ethernet1/3                unassigned      YES NVRAM  administratively down down
Serial2/0                  unassigned      YES NVRAM  administratively down down
Serial2/1                  unassigned      YES NVRAM  administratively down down
Serial2/2                  unassigned      YES NVRAM  administratively down down
Serial2/3                  unassigned      YES NVRAM  administratively down down
Serial3/0                  unassigned      YES NVRAM  administratively down down
Serial3/1                  unassigned      YES NVRAM  administratively down down
Serial3/2                  unassigned      YES NVRAM  administratively down down
Serial3/3                  unassigned      YES NVRAM  administratively down down
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\engmo\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/engmo/PycharmProjects/Netmiko/Netmiko.py", line 22, in <module>
    output = net_connect.send_config_set(config_commands=cisco)
  File "C:\Users\engmo\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 1853, in send_config_set
    output += self.config_mode(*cfg_mode_args)
  File "C:\Users\engmo\AppData\Roaming\Python\Python38\site-packages\netmiko\cisco_base_connection.py", line 48, in config_mode
    return super().config_mode(
  File "C:\Users\engmo\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 1737, in config_mode
    if not self.check_config_mode():
  File "C:\Users\engmo\AppData\Roaming\Python\Python38\site-packages\netmiko\cisco\cisco_ios.py", line 32, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "C:\Users\engmo\AppData\Roaming\Python\Python38\site-packages\netmiko\cisco_base_connection.py", line 38, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
  File "C:\Users\engmo\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 1721, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\engmo\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\engmo\AppData\Roaming\Python\Python38\site-packages\netmiko\base_connection.py", line 579, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
`

**Comment by applericky** [comment]
Hi,

Are you able to turn on logging and post your outputs here? I think I it's failing to get the details when trying to get into configuration mode. If you are also able to provide the steps when you ssh directly so see how your IOS device responds it would be helpful. 

One thing I can think of for testing is to separate all your commands and send them one by one to isolate it from there. 

Let me know of your findings.

**Comment by gviabcua** [comment]
same problem cisco_ios(ssh & telnet)
Username: 
DEBUG:netmiko:write_channel: b'XXXXXXXXXX\r'
Password: 
DEBUG:netmiko:write_channel: b'XXXXXXXXXXXXX\r'
--------------------
DEBUG:netmiko:Pattern found: QQQQQQQQQQQQQQ 
QQQQQQQQQQQQQQ>
DEBUG:netmiko:write_channel: b'enable\r\n'
DEBUG:netmiko:Pattern is: enable
QQQQQQQQQQQQQQ#
DEBUG:netmiko:Pattern found: enable enable
QQQQQQQQQQQQQQ#
DEBUG:netmiko:Pattern is: (QQQQQQQQQQQQQQ)
DEBUG:netmiko:write_channel: b'\r\n'
QQQQQQQQQQQQQQ#
DEBUG:netmiko:[find_prompt()]: prompt is QQQQQQQQQQQQQQ#
DEBUG:netmiko:write_channel: b'show version\r\n'
-----------------
OUTPUT Error enable. Skipping


/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: netmiko in /usr/local/lib/python3.8/dist-packages (3.3.3)
Requirement already satisfied: ntc-templates in /usr/local/lib/python3.8/dist-packages (from netmiko) (2.0.0)
Requirement already satisfied: pyserial in /usr/local/lib/python3.8/dist-packages (from netmiko) (3.5)
Requirement already satisfied: scp>=0.13.2 in /usr/local/lib/python3.8/dist-packages (from netmiko) (0.13.3)
Requirement already satisfied: paramiko>=2.6.0 in /usr/local/lib/python3.8/dist-packages (from netmiko) (2.7.2)
Requirement already satisfied: setuptools>=38.4.0 in /usr/local/lib/python3.8/dist-packages (from netmiko) (54.2.0)
Requirement already satisfied: tenacity in /usr/local/lib/python3.8/dist-packages (from netmiko) (7.0.0)
Requirement already satisfied: textfsm<2.0.0,>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from ntc-templates->netmiko) (1.1.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from paramiko>=2.6.0->netmiko) (1.4.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python3.8/dist-packages (from paramiko>=2.6.0->netmiko) (3.4.7)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.8/dist-packages (from paramiko>=2.6.0->netmiko) (3.2.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from tenacity->netmiko) (1.15.0)
Requirement already satisfied: future in /usr/local/lib/python3.8/dist-packages (from textfsm<2.0.0,>=1.1.0->ntc-templates->netmiko) (0.18.2)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from pynacl>=1.0.1->paramiko>=2.6.0->netmiko) (1.14.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=2.6.0->netmiko) (2.20)

**Comment by applericky** [comment]
Your debugging shows success. It looks like you are going all the way up to "show version".

The code you posted when you opened the issue does not report a "show version". Are you running this with the latest version of Netmiko?

**Comment by ktbyers** [comment]
Yeah, the debugging output above is not consistent with the code you posted earlier? Also as @applericky mentioned there is no error/issue in the debugging output (everything worked properly there).

**Comment by ktbyers** [comment]
Closing as there was no additional response on this. Just re-open if you have more info on the problem.
