### ISSUE TITLE
Lack of searching pattern with base prompt

### ISSUE THREAD

**Issue by selfuryon** [ktbyers/netmiko#221]
In this code pattern is not good for searching
```
    def read_until_pattern(self, pattern='', re_flags=0):
        """Read channel until pattern detected. Return ALL data available."""
        debug = False
        output = ''
        if not pattern:
            pattern = self.base_prompt
            ...
```
It's bad because we have only base prompt without prompt terminator in output of some commands like ```show version``` and ```show run```. Maybe use as example for cisco pattern like ```"{0}\(?[\w-]*\)?[{1}|{2}]".format(self.base_prompt,self.pri_prompt_terminator,self.alt_prompt_terminator)```

**Comment by ktbyers** [comment]
@selfuryon Use send_command_expect() method for 'show version' and 'show run'. 

Either send_command() or send_command_expect() are the general way to execute 'show commands' for Netmiko. read_until_pattern and read_until_prompt are usually used internally and are lower-level.

You can provide a pattern by adding the pattern argument so if you have a case that is not working for you then provide the pattern argument.

It needs to work for broader than Cisco devices. I also don't want to be frequently updating the base_prompt when the prompt changes (for example, config mode, sub-config mode, etc).

If you know of a case where send_command_expect() doesn't work, let me know.

**Comment by ktbyers** [comment]
@selfuryon Note, you can also obtain the current prompt using the find_prompt() method so you can use the current prompt if you want by passing this as the 'pattern'. It will just be slower.
