### ISSUE TITLE
SSH to remote router from Jump router

### ISSUE THREAD

**Issue by v2dev7** [ktbyers/netmiko#2214]
Topology :

Laptop======jump router (Nokia SR-OS Hostname=Router A)==========Target Router (Nokia SR-OS Hostname Router B)

NOTE: 

No privilege issue 

I am able to enter into Router B. I am not able to get the output. When I send ".txt" file 

Code:
====

```python
from netmiko import ConnectHandler
from netmiko import redispatch
import time
import socket

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

Nokia = {
        'device_type': 'nokia_sros',
        'ip': 'x.x.x.x',
        'username': 'admin',
        'password': 'admin',
        'port': 22,
        'global_delay_factor': 4,
}
net_connect = ConnectHandler(**Nokia)

net_connect.write_channel("ssh admin@x.x.x.x\n")
time.sleep(10)
output = net_connect.read_channel()
if 'password' in output:
    net_connect.write_channel(net_connect.password+'\n')
    time.sleep(10)

output += net_connect.read_channel()


print("logging into second device")
print("ssh prompt : {}".format(net_connect.find_prompt()))

new_output = net_connect.send_config_from_file('osaka.txt')

print (output)
print(new_output)
```

LOG
====

*A:Router B# 
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is *A:Router B#
DEBUG:netmiko:write_channel: b' environment no more\n'
DEBUG:netmiko:Pattern is: environment\ no\ more
DEBUG:netmiko:_read_channel_expect read_data:  
DEBUG:netmiko:_read_channel_expect read_data: environment no more 

*A:Router B# 
DEBUG:netmiko:Pattern found: environment\ no\ more  environment no more 

*A:Router B# 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: A:Router A
DEBUG:netmiko:_read_channel_expect read_data: 

*A:Router B
DEBUG:netmiko:_read_channel_expect read_data: # 
DEBUG:paramiko.transport:EOF in transport thread

ERROR:
======

logging into second device
ssh prompt : *A:Router B#-------------------------->>Successfully logged in Router B
Traceback (most recent call last):
  File "C:\venv\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\venv\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\venv\lib\site-packages\netmiko\base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\venv\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/vdeshpan/PycharmProjects/Nokia/Osaka.py", line 33, in <module>
    new_output = net_connect.send_config_from_file('osaka.txt',delay_factor=4, exit_config_mode=False)
  File "C:\venv\lib\site-packages\netmiko\base_connection.py", line 1790, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "C:\venv\lib\site-packages\netmiko\nokia\nokia_sros_ssh.py", line 152, in send_config_set
    return super().send_config_set(
  File "C:\venv\lib\site-packages\netmiko\base_connection.py", line 1875, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "C:\venv\lib\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\venv\lib\site-packages\netmiko\base_connection.py", line 579, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Process finished with exit code 1

Osaka.txt: (Contains, below text)

environment no more

########TC-3########
show time
show router bfd interface
show router bfd session
show router 403 bfd interface
show router 403 bfd session
show router 500 bfd interface
show router 500 bfd session
show router 503 bfd interface
show router 503 bfd session
show router 600 bfd interface
show router 600 bfd session

**Comment by ktbyers** [comment]
You probably need to execute `redispatch` after you have logged into the end-device. Even though the Netmiko class of the two devices is the same, there are some things that probably are not setup correctly on the end device (Netmiko's base_prompt, output paging, and terminal width).


Regards, Kirk

**Comment by ktbyers** [comment]
@v2dev7 Any update on whether this is working using redispatch?

**Comment by ktbyers** [comment]
Going to close since there wasn't any earlier response.
