### ISSUE TITLE
Nokia SR-OS output behaviour

### ISSUE THREAD

**Issue by ynysmeudwy** [ktbyers/netmiko#2215]
Hi all,

Sending some basic show commands and for some odd reason the output contains a **e"** from the show command syntax:

```python
for i in al:
    nokia = {
        'host': i,
        'device_type': 'alcatel_sros',
        'username': ur,
        'password': pw,
    }
    try: #Will try this block if there is a successful SSH connection
        net_conn = ConnectHandler(**nokia)
        chassis = net_conn.send_command("show chassis  detail | match ass")
        version = net_conn.send_command('show version | match Timos ignore-case')
        sfm = net_conn.send_command('admin display-config | match sfm-type ignore-case')
        card = net_conn.send_command('admin display-config | match express "card-type|mda-type"')

        if 'Error' in chassis: #Older versions of Timos dont need the detail syntax and generate an error if used
            if '82' not in chassis:
                print('#' * 17)
                print('# ' + i + ' #')
                print('#' * 17)
                print()
                print("Chassis Build - Pre 2008")
                print()
                print(version, sfm, card)
                print()
            else:
                print('#' * 17)
                print('# ' + i + ' #')
                print('#' * 17)
                print()
                print("Chassis Build - Post 2008")
                print()
                print(version, sfm, card)
                print()
        else:
            if '82' not in chassis:
                print('#' * 17)
                print('# ' + i + ' #')
                print('#' * 17)
                print()
                print("Chassis Build - Pre 2008")
                print()
                print(version, sfm, card)
                print()
            else:
                print('#' * 17)
                print('# ' + i + ' #')
                print('#' * 17)
                print()
                print("Chassis Build - Post 2008")
                print()
                print(version, sfm, card)
                print()
    except (NetMikoTimeoutException): #If SSH timesout with this exception next block of code
        print('#' * 15)
        print(i, ' - SSH connection timed out Investigate cause')
```

The output appears like this:

Chassis Build - Post 2008

TiMOS-C-19.10.R9 cpm/hops64 Nokia 7750 SR Copyright (c) 2000-2020 Nokia.
        sfm-type m-sfm5-7
        sfm-type m-sfm5-7 **e"** **<<<<< This is my reference**
        card-type iom3-xp-c
            mda-type m20-1gb-xp-sfp
            mda-type m2-10gb-xp-xfp
        card-type imm-2pac-fp3
            mda-type p10-10g-sfp
            mda-type p10-10g-sfp

Apologies if this has already been answered.

**Comment by ktbyers** [comment]
@ynysmeudwy I would probably look at the Netmiko session_log or possibly Netmiko logging and see if you can get more details as to what is causing the issues.

You might also want to see if you can simplify your code, what you are doing, so you can better isolate the issue.


Regards, Kirk

**Comment by ynysmeudwy** [comment]
Hi Kirk, thanks for the response.

I turned on logging but there's nothing I can see that indicates the output printing part of the cli syntax.

**Comment by ktbyers** [comment]
I can't really help much (at all) without being able to see the logging output. 


Regards, Kirk

**Comment by basharalfatly** [comment]
@ynysmeudwy 

Would you  execute `admin display-config | match sfm-type ignore-case` on the router and observe the output? 

Just to verify that the output is correct in the Nokia router without that **e"**.

**Comment by ktbyers** [comment]
@ynysmeudwy Any update on providing the output logging?

**Comment by ktbyers** [comment]
Closing this as it is no longer being actively worked on.
