### ISSUE TITLE
Potential TextFSM Integration issue with Netmiko on certain platforms

### ISSUE THREAD

**Issue by AdamMason1877** [ktbyers/netmiko#2217]
Hello Kirk, 

It's a pleasure speaking again after our twitter exchange, I wanted to submit the github issue here and provide you as much information as possible to help determine why I am unable to receive formatted data structures back when using the TextFSM integration. It is possible that this could be a platform related issue due to environmental variables on Mac OS and being on a corporate machine, I can never rule out corporate endpoint policies... I don't have a lab environment as of yet.

Apologies in advance but due to this being run off of prod gear, the output of some commands and certain RFC1918 addressing I need to change/omit for reasons relating security concerns... This is the internet after all, call me overly cautious.

Also keep in mind I am not the best programmer, so while I can understand and write in most topics, some may be foreign to me.

```
import netmiko
from getpass import getpass
#import json   
import textfsm
import os

os.environ["NTC_TEMPLATES_DIR"] = "/Users/myusername/Desktop/PythonScripts/ntc-templates/ntc_templates/templates"

class credential_lock:
    def __init__(self):
        self.username = getpass('what is your username?: ')
        self.password = getpass('what is your password?: ')
    
creds = credential_lock()


location = {
    'forest': 246,
    'mountain': 235
}


hosts = []

for x in location.values():
    hosts.extend([f"10.{x}.99.2", f"10.{x}.99.3"])


all_devices = []

for address in hosts:
    all_devices.append(
        {
        'device_type': 'nxos',
        'host': address, 
        'username': creds.username,
        'password': creds.password
        }
    )


for device in all_devices:
        print(type(device))  
        print('connecting....')
        net_connect = netmiko.BaseConnection(**device)
        print(net_connect.find_prompt())
        net_connect.enable()
        output = net_connect.send_command('show vrf interface', use_textfsm='/Users/myusername/ntc-templates/ntc_templates/templates/cisco_nxos_show_vrf_interface.textfsm') <--- per your last twitter  suggestion
        print(output)

```

and the relevant environmental variables

```
PATH=/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
SHLVL=1
PWD=/Users/myusername
OLDPWD=/Users
NET_TEXTFSM=/Users/myusername/ntc-templates/ntc_templates/templates
NTC_TEMPLATES_DIR=/Users/myusername/ntc-templates/ntc_templates/templates
_=/usr/bin/printenv
myusername@machinename ~ % 
```

What I get is the typical netmiko show command output, formatted strings that look nice, but I have checked via print(type(output)) and they are indeed strings not dictionaries or lists... :(

**Comment by ktbyers** [comment]
Let's get a simplified base case. Pick a single NX-OS device and execute code similar to the following on it (i.e. update device to match your device):

```python
from netmiko import ConnectHandler

device = {
    "device_type": "cisco_nxos",
    "host": "nxos1.domain.com",
    "username": "admin",
    "password": "admn",
}

net_connect = ConnectHandler(**device)
net_connect.enable()
output = net_connect.send_command("show interface", use_textfsm=True)
print(output)

```

Note, it is not valid to use `BaseConnection` directly in Netmiko, you need to use ConnectHandler to pick the proper class. Also, your device_type of "nxos" is wrong; it needs to be `cisco_nxos`.

**Comment by ktbyers** [comment]
You should make sure you have `ntc-templates` installed via PIP and `NO environment variable` for NTC templates.

You should also ensure you are using Netmiko 3.3.3

```
$ pip list | grep netmiko
netmiko                      3.3.3

$ pip list | grep ntc-templates
ntc-templates                1.4.1
```

**Comment by AdamMason1877** [comment]
> Let's get a simplified base case. Pick a single NX-OS device and execute code similar to the following on it (i.e. update device to match your device):
> 
> ```python
> from netmiko import ConnectHandler
> 
> device = {
>     "device_type": "cisco_nxos",
>     "host": "nxos1.domain.com",
>     "username": "admin",
>     "password": "admn",
> }
> 
> net_connect = ConnectHandler(**device)
> net_connect.enable()
> output = net_connect.send_command("show interface", use_textfsm=True)
> print(output)
> ```
> 
> Note, it is not valid to use `BaseConnection` directly in Netmiko, you need to use ConnectHandler to pick the proper class. Also, your device_type of "nxos" is wrong; it needs to be `cisco_nxos`.

Literally solved it, I was misinterpreting the usage of the API.  I am so sorry for wasting your time.

Out of curiosity, what is the proper use of BaseConnection? I am trying to figure out where I went wrong so to speak with understanding the API documentation.

**Comment by ktbyers** [comment]
BaseConnection is the class that all the other driver classes are built upon, but it is not intended to be directly used. I probably would look at some of the reference examples here:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md


Regards, Kirk
