### ISSUE TITLE
Huawei router throwing an error "Router prompt not found: ---- More ---- Router prompt not found: ---- More ----" while trying to configure with Netmiko

### ISSUE THREAD

**Issue by arunkumark81** [ktbyers/netmiko#2219]
Hi All
Huawei router throwing an error "Router prompt not found: ---- More ---- " while trying to configure with Netmiko

Sample Code as below

 huawei_device = {
                'device_type': 'huawei',
                'ip': '1.1.1.1',
                'username': 'admin',
                'password': passwd,
                'verbose': True
            }
connection = ConnectHandler(**huawei_device)
connection.enable()
time.sleep(2)

command1 = ["acl name snmp 2001", "rule permit source 1.1.1.1 0"]  # Enter set of commands
print("Connected to:", connection.find_prompt())  # Display hostname
hostname = connection.find_prompt()[:-1]
connection.send_config_set(command1, delay_factor=.5)  # Run set of commands in order

out = connection.send_command_timing("save")
if 'Are you sure to continue?[Y/N]:' in out:
out += connection.send_command_timing('Y'+'\n')
print("Config Saved")
***************

Error as below
![error](https://user-images.githubusercontent.com/82443555/114531512-04b82280-9c5d-11eb-907c-620b213dab41.PNG)

Please help to resolve

//Arun

**Comment by ktbyers** [comment]
What is the model / network OS of the device that is failing?

Can you show what a full SSH CLI login looks like if you login manually?


Kirk

**Comment by ktbyers** [comment]
Output paging should be disabled.

This is the command we are using in that Huawei driver.

I am going to close since there was no response here.
