### ISSUE TITLE
Exception has occurred: NetmikoTimeoutException Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by jorgebanegas** [ktbyers/netmiko#2228]
<img width="975" alt="Screen Shot 2021-04-16 at 11 43 03 AM" src="https://user-images.githubusercontent.com/22305451/115049602-e8a8c100-9ea8-11eb-976a-5cf35351c805.png">

unable to configure simple vlan. tried all the remedies with issue under the same error. 

using a Cisco catalyst 9200L

netmiko logs 
----------------------------------------------------------------------------------------------------------------------------
DEBUG:paramiko.transport:starting thread (client mode): 0x765f310
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-sha1-96'] server mac:['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-sha1-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 172.28.104.67: b'379e57bb916db06a454a6b976bd7065a'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:write_channel: b'terminal width 511\r\n'
DEBUG:netmiko:Pattern is: terminal width 511
DEBUG:netmiko:_read_channel_expect read_data: 

sidious>
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: e
DEBUG:netmiko:_read_channel_expect read_data: r
DEBUG:netmiko:_read_channel_expect read_data: minal 
DEBUG:netmiko:_read_channel_expect read_data: w
DEBUG:netmiko:_read_channel_expect read_data: idth 
DEBUG:netmiko:_read_channel_expect read_data: 511
DEBUG:netmiko:Pattern found: terminal width 511 

sidious>terminal width 511
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\r\n'
DEBUG:netmiko:Pattern is: terminal\ length\ 0
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: sidious>
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: sidious>
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: e
DEBUG:netmiko:_read_channel_expect read_data: rmin
DEBUG:netmiko:_read_channel_expect read_data: a
DEBUG:netmiko:_read_channel_expect read_data: l
DEBUG:netmiko:_read_channel_expect read_data:  le
DEBUG:netmiko:_read_channel_expect read_data: n
DEBUG:netmiko:_read_channel_expect read_data: gth 0
DEBUG:netmiko:Pattern found: terminal\ length\ 0 
sidious>
sidious>terminal length 0
DEBUG:netmiko:
sidious>
sidious>terminal length 0
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: 
sidious>

DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: sidious>
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
sidious>
sidious>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is sidious>
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:Pattern is: #
DEBUG:netmiko:_read_channel_expect read_data: 
sidious>
sidious>
sidious>
sidious>
sidious>
sidious>
sidious>
sidious>
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:netmiko:_read_channel_expect read_data: sidious>
sidious>

**Comment by jorgebanegas** [comment]
show commands work fine

**Comment by applericky** [comment]
See if trying the following works:

vlan_number = "200"

net_connect = Netmiko(**device )

vlan_response = net_connect.send_command("vlan " + vlan_number)

I'm keeping it simple on my end to see if it still errors out this way.

**Comment by ktbyers** [comment]
It looks like you need to call `enable()` before calling `send_config_set()`:

You will also need to add `'secret'` argument to your `device` dictionary.
