### ISSUE TITLE
send_command returns incomplete output

### ISSUE THREAD

**Issue by lundybernard** [ktbyers/netmiko#223]
ex: 
```python
device = {'device_type':'cisco_ios'...
shell = ConnectHandler(**device)
shell.enable()
out = shell.send_command("write memory")
print(out)
```
returns:
>Building configuration...

but the full output should be:
>Building configuration...
>Compressed configuration from 543610 bytes to 149342 bytes[OK]

I tried a bit of a hack-around like so:
```python
out = shell.send_command(self.args.cmd, max_loops=500)
out += shell.read_until_prompt()
```
which returns:
>Building configuration...
>Compressed configuration from 543610 bytes to 149342 bytes[OK]
>my_host#

with the prompt at the end.

Is there a better way to collect all of the output from send_command before it returns, or is using a read_until method the correct solution?
I guess i'm also a bit confused because "show version" returned a big multi-line block of output without any trouble.

**Comment by ktbyers** [comment]
Use

```
out = send_command_expect("write mem")
```

This is the preferred solution. I will probably convert send_command to be send_command_expect() in a future release (and retain send_command_expect so as not to break code that uses it). I will probably rename the current send_command, send_command_timing (or something similar).

**Comment by ktbyers** [comment]
@lundybernard The problem is with commands that are slow to respond or give some data and then delay. For these type of commands send_command_expect is a better method.

**Comment by lundybernard** [comment]
@ktbyers thanks! send_command_expect() took care of the problem, and its now working as expected.

Mind if I add that to the examples in README.md?

**Comment by ktbyers** [comment]
Sure.



Kirk

On Wed, Jun 15, 2016 at 10:20 AM, Lundy Bernard <notifications@github.com>
wrote:

> @ktbyers <https://github.com/ktbyers> thanks! send_command_expect() took
> care of the problem, and its now working as expected.
>
> Mind if I add that to the examples in README.md?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/223#issuecomment-226257268>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA26hFDi8ZEwBpqodlgvaMk1n_tAole5ks5qMDRigaJpZM4I1yHv>
> .
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by lundybernard** [comment]
[README.md](https://github.com/ktbyers/netmiko/blob/master/README.md) has been updated to show this solution.
closing issue.
