### ISSUE TITLE
send_command shows only the output of the command and not the command itself

### ISSUE THREAD

**Issue by besjanvata** [ktbyers/netmiko#2237]
Hi,

I have a problem with send_command which i do not see the command in the output, but only the output of the command.
With send_command i can send 3 times faster the list of commands so it improves performance.

def monitor(repeat,periotime):
 for i in range(repeat):
     output = net_connect.send_config_set(commands)
     print(output, file = sourceFile)
     import time
     time.sleep(periodtime)

  'device_type': 'fortinet',
    'host':   '10.109.52.56',
    'username': 'admin',
    'password': '',
    "fast_cli": False ---> The is faster if you set to True
}
the problem is that with that if you change to true the net_connect.send_config_set will not be able to respond so fast

If we change the function to send the commands one by one with the send_command, then the command itself executed will not be prompted on the output, file = sourceFil

def monitor(repeat,periotime):
 for i in range(repeat):
     for comm in commands:
       output = net_connect.send_command(comm, auto_find_prompt=True, expect_string='#')
       print(output, file = sourceFile)
       import time
       time.sleep(periodtime)

How can i make send_command to save also the command executed in the output?

Regards

**Comment by ktbyers** [comment]
You will need to format your code properly in GitHub markdown.


Regards, Kirk

**Comment by besjanvata** [comment]
Hello Kirk,

#When i use send_config_set 

def monitor(repeat,periotime):
   for i in range(repeat):
      output = net_connect.send_config_set(commands)
      print(output, file = sourceFile)
      import time
      time.sleep(periodtime)

The output is : 
PRH-HLM-FW5 (global) # get hardware status ---> the command executed
Model name: FortiGate-1500D
ASIC version: CP8

#When i use send_command

def monitor(repeat,periotime):
 for i in range(repeat):
     for comm in commands:
       output = net_connect.send_command(comm, auto_find_prompt=True, expect_string='#')
       print(output, file = sourceFile)
       import time
       time.sleep(periodtime)

Output:
Model name: FortiGate-1500D 
ASIC version: CP8

I am not very informed with GitHub markdown, I tried to format it in a more readable way.
Thanks in advance Kirk
Regards,
Besjan

**Comment by ktbyers** [comment]
I am not sure I understand your issue, but Netmiko intentionally strips the command from the output, you can set the `strip_command=False` argument if you do not want the command stripped.

Github markdown is well documented online.


Regards, Kirk

**Comment by besjanvata** [comment]
Thanks Kirk,

This was the option I was looking for.
Have a nice day.

Regards
