### ISSUE TITLE
netmiko - getting "Failed to enter configuration mode." error on arista device that responds slower than other devices of similar pedigree.

### ISSUE THREAD

**Issue by jasonhaominglo** [ktbyers/netmiko#2239]
Hi guys,

Seeing the below error on a particular device that is responding slower than other similar devices:
"File "/opt/venvs/nornir/lib/python3.6/site-packages/netmiko/base_connection.py", line 1731, in config_mode
    raise ValueError("Failed to enter configuration mode.")
ValueError: Failed to enter configuration mode."

It does report the below which looks like config term mode is hit:
"
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'configure terminal\n'
DEBUG:netmiko:Pattern is: configure\ terminal
DEBUG:netmiko:_read_channel_expect read_data:

DEBUG:netmiko:_read_channel_expect read_data: baqtwndevs01(config)#
DEBUG:netmiko:_read_channel_expect read_data: configure terminal

DEBUG:netmiko:Pattern found: configure\ terminal
baqtwndevs01(config)#configure terminal
"

calling from a nornir script:
r = task.run(task=netmiko_custom_send_config, config_commands=all_command_changes, delay_factor=1, max_loops=5000, cmd_verify=True)

Any tips?

**Comment by ktbyers** [comment]
Have you tried setting fast_cli=False and then setting global_delay_factor=2 (or 4)?

**Comment by jasonhaominglo** [comment]
Hi Keith, is there a way to specify fast_cli=False as an argument to netmiko send_config command directive? at the moment, its giving me this error:
"send_config_set() got an unexpected keyword argument 'fast_cli'"

**Comment by ktbyers** [comment]
Both `fast_cli` and `global_delay_factor` are arguments to ConnectHandler.

You would typically specific both of these inside Nornir inventory. See link here (assuming you are using YAML-based inventory):

https://nornir.discourse.group/t/passing-options-to-napalm-netmiko/22/2

Look at the `connection_options > netmiko > extras` example. Both `fast_cli` and `global_delay_factor` would be set inside of `extras`.
