### ISSUE TITLE
can't login on jumpserver with 2FA through netmiko

### ISSUE THREAD

**Issue by chenmianye** [ktbyers/netmiko#2240]
jumpserver need mfa auth when I try to login on it. It login process below:
ssh user@172.21.34.100 -p 2222
The authenticity of host '[172.21.34.100]:2222 ([172.21.34.100]:2222)' can't be established.
cctv@172.21.34.100's password:
Please enter 6 digits.
[MFA auth]: 123456

I don't know how to use netmiko to do it,could you help me ?

**Comment by applericky** [comment]
Hi,

Netmiko has a feature where you can send a command when expecting a prompt. Essentially you would scrape for "[MFA auth]:". Hope this helps. 


send_command_prompting_expect.py

https://github.com/ktbyers/netmiko/blob/develop/examples/send_command_prompting_expect.py

**Comment by ktbyers** [comment]
Yeah, I don't know how you solve that (without a meaningful amount of work), that is probably going to be somewhat hard to solve/fix.

Generally, Netmiko doesn't do any interaction with SSH proxy server i.e. you just embed the parameters in the SSH config file and Netmiko reads/uses this SSH config.

I would probably see if you can convince your security organization to allow that to be bypassed for automation work.
