### ISSUE TITLE
Cisco-variable IP in config file

### ISSUE THREAD

**Issue by sandeepkhera** [ktbyers/netmiko#2242]
Hi All,

I am trying to push set of static routes in multiple devices using a config file. SInce the next hop is different for each device, I want to add it as variable in config file and needs that to be updated itself for each device.
I've found a way to find the next hop but needs to know how to code so it writes it to file before pushing.

Below is the code:-

from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException
import time
import re

RTR1 = open('Rtrs')
for IP in RTR1
	RTR = {
    'ip':   IP,
    'username': 'xxx',
    'password': 'xxx',
	'secret': 'xxx',
    'device_type': 'cisco_ios',
    }
	try:
        device = ConnectHandler(**RTR)
		time.sleep(3)
		print('connecting to device' + IP)
    except NetMikoTimeoutException:
        print ('Device not reachable.')
        continue
    except AuthenticationException:
        print ('Authentication Failure.')
        continue
    except SSHException:
        print ('Make sure SSH is enabled in device.')
        continue
	output = device.send_command("show ip route 1.1.1.1")
	p = re.findall(r'\d+\.\d+\.\d+\.\d+', output)
print(p[1])              ---------------------- "this prints the next hop which I want to use as variable in config file"
device.enable()
device.send_config_from_file(config_file = 'config')
device.save_config()
device.disconnect

config file - 

ip route 4.2.2.2 255.255.255.255 [variable] name xyxy
ip route 4.3.3.3 255.255.255.255 [variable] name xyxy

**Comment by applericky** [comment]
Hi,

Your question appears to be more of a knowledge question. There is a lot of information here missing like the type of OS you are running, proper use of opening files, missing certain import statements, and use of functions/classes. 

I know there are a few sites like Stackoverflow or Network automation groups in Discord that can be more help in a live chat. Do let me know if I misunderstood your question but opening an issue is to report a bug in the Netmiko code.

**Comment by sandeepkhera** [comment]
I am sorry. I am new to Python and this one going to be my first code.
I am using Linux Ubuntu and Python 3.8.
you're right it is actually a query where I need assistance with this code. 
I will check on the suggested forums too. Can we keep this open here in case someone willing to help. 
Thankyou.

**Comment by applericky** [comment]
Hi,

No worries. I just wanted to make sure this was more of a educational question. On my page I have a way that I used to do what you are looking for with Python. Take a look and see if it helps you out. The examples will show you reading from a file, which is similar if you want to write. 

https://github.com/applericky/runbooks/blob/master/nonthreadded.py

**Comment by ktbyers** [comment]
@sandeepkhera Did @applericky response answer your question?

**Comment by ktbyers** [comment]
@sandeepkhera I would typically use some form of Jinja2 templating to solve this type of problem. There should be quite a few examples available online (in a network automation context).

**Comment by ktbyers** [comment]
I am going to close this as it is not really a Netmiko issue.
