### ISSUE TITLE
After  connecting to router through another router using netmiko, I can't run commands to the destination router

### ISSUE THREAD

**Issue by hackmoonlight** [ktbyers/netmiko#2251]
hello,
I connected to the router R2 throught another router using netmiko and redispatch function , but after dooing the redispatch when I run  commands it still be running under the jump router.

![image](https://user-images.githubusercontent.com/11053381/116883286-bc6d9e00-ac25-11eb-9bdb-8fac79adb219.png)

`from napalm import get_network_driver
from robot.api.deco import keyword
#import tools
from netmiko import ConnectHandler
import os
import sys
import re
import robot
import time
import subprocess
#import IP
import traceback
from netmiko import redispatch
import textfsm`

`def sh_route(IP):
        
        device_info = {
                    'device_type': 'cisco_ios',
                    'host': 'hostname',
                    'username': 'username',
                    'password': 'pwd',}
        #connect to device1 from linux
        net_connect = ConnectHandler(**device_info)
        # Use raw read/write to SSH into device2
        net_connect.write_channel('ssh 192.168.247.2\n')
        time.sleep(1)
        output = net_connect.read_channel()
        if 'Username' in output:
            net_connect.write_channel('username' + '\r\n')
            time.sleep(1)
            output = net_connect.read_channel()
        if 'password' in output:
            net_connect.write_channel('pwd'+ '\n')
            time.sleep(1)
        ### Logged into Second device
        print ("SSH prompt: {}".format(net_connect.find_prompt()))
        redispatch(net_connect, device_type='cisco_ios')
        net_connect.enable()
        new_output = net_connect.send_command('show version', use_textfsm=True)
        #print(output)
        version= new_output[0]['rommon']
        if  version == 'IOS-XE':
            new_output = net_connect.send_command('show ip route connected')
            return new_output
        if  version == 'IOS-XR':
            new_output = net_connect.send_command('show route local')
            return new_output
`

**Comment by ktbyers** [comment]
Have you looked at the Netmiko session_log() to see where you are failing at? It sounds like you are not properly logging into the end-device (R2 in your diagram).

You will probably need some loop structure here:

```
    output = net_connect.read_channel()
    if 'Username' in output:
        net_connect.write_channel('username' + '\r\n')
        time.sleep(1)
        output = net_connect.read_channel()
    if 'password' in output:
        net_connect.write_channel('pwd'+ '\n')
        time.sleep(1)
```

That is probably very prone to being unreliable (i.e. I could easily see how this might fail.

**Comment by hackmoonlight** [comment]
This is the full code, :

`def sh_route(self,alias):
        global verif
        self.device = self._cache.switch(alias)
        device_info = {
                    'device_type': 'cisco_ios',
                    'ip': self.device.hostname,
                    'username': self.device.username,
                    'password': self.device.password,}
        
        #connect to device1 from linux
        net_connect = ConnectHandler(**device_info)
        ldp= self.get_ldp_neighbors(alias)
        for  x in ldp.keys():
            addr_list = ldp[x]['addresses'] #List of ldp ip adresses  
            
            src_ip_addr= ldp[x]['SrcIPaddr'] #source ip addr
                
            # Use raw read/write to SSH into device2
            net_connect.write_channel('ssh'+src_ip_addr+'\n')
            time.sleep(1)
            output = net_connect.read_channel()
            if 'Username' in output:
                net_connect.write_channel(net_connect.username + '\r\n')
                time.sleep(1)
                output = net_connect.read_channel()
            if 'password' in output:
                net_connect.write_channel(net_connect.password + '\n')
                time.sleep(1)
            ### Logged into Second device
            print ("SSH prompt: {}".format(net_connect.find_prompt()))
            redispatch(net_connect, device_type='cisco_ios')
            net_connect.enable()
            new_output = net_connect.send_command('show version', use_textfsm=True)
           
            version= new_output[0]['rommon']  #check ios version
            # check if addr_list exist in addr(list of ip addr got with cisco cmd)
            if  version == 'IOS-XE':
                new_output = net_connect.send_command('show ip route connected')
                addr= re.findall( r'[0-9]+(?:\.[0-9]+){3}', new_output) # list of @ip got from new_output
                #return addr
                # #return addr_list
                # #return addr
            if  version == 'IOS-XR':
                new_output = net_connect.send_command('sh route local')                
                addr= re.findall( r'[0-9]+(?:\.[0-9]+){3}', new_output)
            return addr`

**Comment by ktbyers** [comment]
Are you checking the Netmiko session_log? I would definitely check there.

**Comment by hackmoonlight** [comment]
you think that i should make split ? and then check the Username and password patterns if they exist ?

**Comment by hackmoonlight** [comment]
> Are you checking the Netmiko session_log? I would definitely check there.

You mean  that I should import logging  and  putting logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

**Comment by hackmoonlight** [comment]
> Have you looked at the Netmiko session_log() to see where you are failing at? It sounds like you are not properly logging into the end-device (R2 in your diagram).
> 
> You will probably need some loop structure here:
> 
> ```
>     output = net_connect.read_channel()
>     if 'Username' in output:
>         net_connect.write_channel('username' + '\r\n')
>         time.sleep(1)
>         output = net_connect.read_channel()
>     if 'password' in output:
>         net_connect.write_channel('pwd'+ '\n')
>         time.sleep(1)
> ```
> 
> That is probably very prone to being unreliable (i.e. I could easily see how this might fail.

I did the same instructions : https://github.com/ktbyers/netmiko/issues/470#issuecomment-302160186

**Comment by hackmoonlight** [comment]
@ktbyers

**Comment by ktbyers** [comment]
Is there some reason, you don't want to look at the Netmiko session_log? Otherwise you are just guessing as to why it is not working.

Yeah, sure the above worked for me and doesn't work for you. Okay, so what do we do now? I think you should look at the Netmiko session_log and probably use a loop for the above username and password handling.

**Comment by hackmoonlight** [comment]
Hello ktbyers,  now I cannot run the script and show you the output because there is a problem with proxy of our client( so I cannot make the virtual env to run the script) .  

for the loop , what do you mean by looping over username and password?  

tomorrow when the problem of proxy is resolved I will show you the session login.

**Comment by ktbyers** [comment]
Okay, makes sense on the session_log.

Yeah, usually while trying to handle the username/password you want some form of loop to keep trying more than once if the login fails (i.e. if things get slightly out of sync timing wise).

Here is an example:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L731

This is from a telnet login process, but it is basically the same idea i.e. you are trying to handle that username/password login in your code.

Regards, Kirk

**Comment by hackmoonlight** [comment]
Thank you Krik, 

I will try it tomorrow  and I will give you feedback.
Regards, Younes

**Comment by hackmoonlight** [comment]
`DEBUG:paramiko.transport:starting thread (client mode): 0xc69c9470
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group14-sha1'] server key:['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa'] client encrypt:['aes128-gcm', 'aes256-gcm', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-gcm', 'aes256-gcm', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512'] server mac:['hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for Bnet-A101: b'a51ea5a576822573a37ce25441bd0241'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:Pattern is: terminal width 511
DEBUG:netmiko:_read_channel_expect read_data: CCCCCCCC
CCCCCCCCCC
CC
C
 _____________________________________________________________________________
|                                                                             |
|                    BNET-A101 at BRATISLAVA vLAB                             |
|                                                                             |
|         THIS IS A PRIVATE SYSTEM MANAGED BY ORANGE BUSINESS SERVICES        |
|                                                                             |
|        ACCESS TO THIS DEVICE REQUIRES AUTHENTICATION AGAINST THE            |
|                                                                             |
|                  >> LAB INFRASTRUCTURE TACACS SERVICE <<                    |
|                                                                             |
|                 Your "saturne" login should be used here                    |
|                                                                             |
|                                                                             |
|_____________________________________________________________________________|

DEBUG:netmiko:_read_channel_expect read_data: CCCCCCCC
CCCCCCCCCC
CC
C
       ________________________________________________________________
      |                                                                |
      |  Activity on this device is recorded and possibly monitored    |
      |________________________________________________________________|

Bnet-A101#terminal wid
DEBUG:netmiko:_read_channel_expect read_data: th 511

DEBUG:netmiko:Pattern found: terminal width 511 CCCCCCCC
CCCCCCCCCC
CC
C
 _____________________________________________________________________________
|                                                                             |
|                    BNET-A101 at BRATISLAVA vLAB                             |
|                                                                             |
|         THIS IS A PRIVATE SYSTEM MANAGED BY ORANGE BUSINESS SERVICES        |
|                                                                             |
|        ACCESS TO THIS DEVICE REQUIRES AUTHENTICATION AGAINST THE            |
|                                                                             |
|                  >> LAB INFRASTRUCTURE TACACS SERVICE <<                    |
|                                                                             |
|                 Your "saturne" login should be used here                    |
|                                                                             |
|                                                                             |
|_____________________________________________________________________________|
CCCCCCCC
CCCCCCCCCC
CC
C
       ________________________________________________________________
      |                                                                |
      |  Activity on this device is recorded and possibly monitored    |
      |________________________________________________________________|

Bnet-A101#terminal width 511

DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: terminal\ length\ 0
DEBUG:netmiko:_read_channel_expect read_data: Bnet-A101#
DEBUG:netmiko:_read_channel_expect read_data: terminal le
DEBUG:netmiko:_read_channel_expect read_data: ngth 0

DEBUG:netmiko:Pattern found: terminal\ length\ 0 Bnet-A101#terminal length 0

DEBUG:netmiko:Bnet-A101#terminal length 0

DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is Bnet-A101#
DEBUG:netmiko:write_channel: b'ssh 192.168.247.2\n'
DEBUG:netmiko:read_channel: ssh 192.168.247.2
Password: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: CCCCAuthentication failed, please try again!
Password: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is Password:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: Bnet\-A101
DEBUG:netmiko:_read_channel_expect read_data: CCCCAuthentication failed, please try again!
Password: 

DEBUG:netmiko:_read_channel_expect read_data: CCCCAuthentication failed, please try again!
Password: 

DEBUG:netmiko:_read_channel_expect read_data: 
[Connection to 192.168.247.2 closed by foreign host]
Bnet-A101#
Bnet-A101#
DEBUG:netmiko:Pattern found: Bnet\-A101 CCCCAuthentication failed, please try again!
Password: 
CCCCAuthentication failed, please try again!
Password: 

[Connection to 192.168.247.2 closed by foreign host]
Bnet-A101#
Bnet-A101#
DEBUG:netmiko:read_channel: 
Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
Bnet-A101#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is Bnet-A101#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'show version\n'
DEBUG:netmiko:Pattern is: show\ version
DEBUG:netmiko:_read_channel_expect read_data: s
DEBUG:netmiko:_read_channel_expect read_data: how version

DEBUG:netmiko:Pattern found: show\ version show version

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: Cisco IOS XE Software, Version 17.04.01a
Cisco IOS Software [Bengaluru], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 17.4.1a, RELEASE SOFTWARE (fc4)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2020 by Cisco Systems, Inc.
Compiled Fri 18-Dec-20 05:01 by mcpre


Cisco IOS-XE software, Copyright (c) 2005-2020 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.  For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.


ROM: IOS-XE ROMMON

Bnet-A101 uptime is 3 weeks, 5 days, 23 hours, 40 minutes
Uptime for this control processor is 3 weeks, 5 days, 23 hours, 41 minutes
System returned to ROM by reload at 10:48:46 UTC Wed Mar 24 2021
System restarted at 10:14:59 UTC Wed Apr 7 2021
System image file is "bootflash:packages.conf"
Last reload reason: reload



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

License Level: network-advantage
License Type: Perpetual
Next reload license Level: network-advantage

Addon License Level: dna-advantage
Addon License Type: Subscription
Next reload addon license Level: dna-advantage

The current throughput level is 250000 kbps 


Smart Licensing Status: Registration Not Applicable/Not Applicable

cisco C8000V (VXE) processor (revision VXE) with 2035358K/3075K bytes of memory.
Processor board ID 95CAJW7JUHV
Router operating mode: Autonomous
8 Gigabit Ethernet interfaces
32768K bytes of non-volatile configuration memory.
3965748K bytes of physical memory.
5234688K bytes of virtual hard disk at bootflash:.

Configuration register is 0x2102

Bnet-A101#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
Bnet-A101#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is Bnet-A101#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'show ip route connected\n'
DEBUG:netmiko:Pattern is: show\ ip\ route\ connected
DEBUG:netmiko:_read_channel_expect read_data: sh
DEBUG:netmiko:_read_channel_expect read_data: ow ip route connected

DEBUG:netmiko:Pattern found: show\ ip\ route\ connected show ip route connected

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: Codes: L - local, C - connected, S - static, R - RIP, M - mobile, B - BGP
       D - EIGRP, EX - EIGRP external, O - OSPF, IA - OSPF inter area 
       N1 - OSPF NSSA external type 1, N2 - OSPF NSSA external type 2
       E1 - OSPF external type 1, E2 - OSPF external type 2, m - OMP
       n - NAT, Ni - NAT inside, No - NAT outside, Nd - NAT DIA
       i - IS-IS, su - IS-IS summary, L1 - IS-IS level-1, L2 - IS-IS level-2
       ia - IS-IS inter area, * - candidate default, U - per-user static route
       H - NHRP, G - NHRP registered, g - NHRP registration summary
       o - ODR, P - periodic downloaded static route, l - LISP
       a - application route
       + - replicated route, % - next hop override, p - overrides from PfR
       & - replicated local route overrides by connected

Gateway of last resort is not set

      172.17.0.0/16 is variably subnetted, 2 subnets, 2 masks
C        172.17.1.0/24 is directly connected, GigabitEthernet7
L        172.17.1.2/32 is directly connected, GigabitEthernet7
      192.168.242.0/24 is variably subnetted, 59 subnets, 2 masks
C        192.168.242.55/32 is directly connected, Loopback2
C        192.168.242.70/32 is directly connected, Loopback1
      192.168.243.0/24 is variably subnetted, 2 subnets, 2 masks
C        192.168.243.0/24 is directly connected, GigabitEthernet1
L        192.168.243.60/32 is directly connected, GigabitEthernet1
      192.168.246.0/24 is variably subnetted, 6 subnets, 2 masks
C        192.168.246.156/32 is directly connected, Loopback99
      192.168.247.0/24 is variably subnetted, 20 subnets, 2 masks
C        192.168.247.0/30 is directly connected, GigabitEthernet4
L        192.168.247.1/32 is directly connected, GigabitEthernet4
C        192.168.247.4/30 is directly connected, GigabitEthernet2
L        192.168.247.5/32 is directly connected, GigabitEthernet2
C        192.168.247.48/30 is directly connected, GigabitEthernet5.911
L        192.168.247.49/32 is directly connected, GigabitEthernet5.911
Bnet-A101#
`

**Comment by hackmoonlight** [comment]
I added loop for the username and passord, 
`        i = 1
        while i <= 20:
            try:   
                if 'Username' in output:
                    net_connect.write_channel('yhajhassine' + '\r\n')
                    time.sleep(1)
                    output = net_connect.read_channel()
                if 'password' in output:
                    net_connect.write_channel('Welcome24'+ '\n')
                    time.sleep(1)
                    output = net_connect.read_channel()
                i += 1
            except EOFError:
                pass
            print(output)`

**Comment by hackmoonlight** [comment]
THIS is the log

> DEBUG:paramiko.transport:starting thread (client mode): 0x31b464e0
> DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
> DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
> INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
> DEBUG:paramiko.transport:kex algos:['ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group14-sha1'] server key:['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa'] client encrypt:['aes128-gcm', 'aes256-gcm', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-gcm', 'aes256-gcm', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512'] server mac:['hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
> DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
> DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
> DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
> DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
> DEBUG:paramiko.transport:Compression agreed: none
> DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
> DEBUG:paramiko.transport:Switch to new keys ...
> DEBUG:paramiko.transport:Adding ssh-rsa host key for Bnet-A101: b'a51ea5a576822573a37ce25441bd0241'
> DEBUG:paramiko.transport:userauth is OK
> INFO:paramiko.transport:Authentication (password) successful!
> DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
> DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
> DEBUG:paramiko.transport:Secsh channel 0 opened.
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:netmiko:write_channel: b'terminal width 511\n'
> DEBUG:netmiko:Pattern is: terminal width 511
> DEBUG:netmiko:_read_channel_expect read_data: CCCCCCCC

CC
C
 _____________________________________________________________________________
|                                                                             |
|                    BNET-A101 at BRATISLAVA vLAB                             |
|                                                                             |
|         THIS IS A PRIVATE SYSTEM MANAGED BY ORANGE BUSINESS SERVICES        |
|                                                                             |
|        ACCESS TO THIS DEVICE REQUIRES AUTHENTICATION AGAINST THE            |
|                                                                             |
|                  >> LAB INFRASTRUCTURE TACACS SERVICE <<                    |
|                                                                             |
|                 Your "saturne" login should be used here                    |
|                                                                             |
|                                                                             |
|_____________________________________________________________________________|


> DEBUG:netmiko:_read_channel_expect read_data: CCCCCCCC

CCCCCCCCCC
CC
C
       ________________________________________________________________
      |                                                                |
      |  Activity on this device is recorded and possibly monitored    |
      |________________________________________________________________|

Bnet-A101#terminal width 5

> DEBUG:netmiko:_read_channel_expect read_data: 11
> 
> DEBUG:netmiko:Pattern found: terminal width 511 CCCCCCCC

CC
C
 _____________________________________________________________________________
|                                                                             |
|                    BNET-A101 at BRATISLAVA vLAB                             |
|                                                                             |
|         THIS IS A PRIVATE SYSTEM MANAGED BY ORANGE BUSINESS SERVICES        |
|                                                                             |
|        ACCESS TO THIS DEVICE REQUIRES AUTHENTICATION AGAINST THE            |
|                                                                             |
|                  >> LAB INFRASTRUCTURE TACACS SERVICE <<                    |
|                                                                             |
|                 Your "saturne" login should be used here                    |
|                                                                             |
|                                                                             |
|_____________________________________________________________________________|
CCCCCCCC
CCCCCCCCCC
CC
C
       ________________________________________________________________
      |                                                                |
      |  Activity on this device is recorded and possibly monitored    |
      |________________________________________________________________|

Bnet-A101#terminal width 511

> DEBUG:netmiko:In disable_paging
> DEBUG:netmiko:Command: terminal length 0
> 
> DEBUG:netmiko:write_channel: b'terminal length 0\n'
> DEBUG:netmiko:Pattern is: terminal\ length\ 0
> DEBUG:netmiko:_read_channel_expect read_data: Bnet-A101#
> DEBUG:netmiko:_read_channel_expect read_data: terminal len
> DEBUG:netmiko:_read_channel_expect read_data: gth 0
> 
> DEBUG:netmiko:Pattern found: terminal\ length\ 0 Bnet-A101#terminal length 0
> 
> DEBUG:netmiko:Bnet-A101#terminal length 0
> 
> DEBUG:netmiko:Exiting disable_paging
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: Bnet-A101#

Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#


> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:[find_prompt()]: prompt is Bnet-A101#
> DEBUG:netmiko:write_channel: b'ssh 192.168.247.2\n'
> DEBUG:netmiko:read_channel: ssh 192.168.247.2

Password: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: CCCCAuthentication failed, please try again!
Password: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is Password:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: Bnet\-A101
DEBUG:netmiko:_read_channel_expect read_data: CCCCAuthentication failed, please try again!
Password: 

DEBUG:netmiko:_read_channel_expect read_data: CCCCAuthentication failed, please try again!
Password: 

> DEBUG:netmiko:_read_channel_expect read_data: 
> 
> DEBUG:netmiko:_read_channel_expect read_data: 

[Connection to 192.168.247.2 closed by foreign host]
Bnet-A101#
Bnet-A101#

> DEBUG:netmiko:Pattern found: Bnet\-A101 CCCCAuthentication failed, please try again!

Password: 
CCCCAuthentication failed, please try again!
Password: 

[Connection to 192.168.247.2 closed by foreign host]
Bnet-A101#
Bnet-A101#

> DEBUG:netmiko:read_channel: 

Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#
Bnet-A101#

> DEBUG:netmiko:Clear buffer detects data in the channel
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 

Bnet-A101#

> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:[find_prompt()]: prompt is Bnet-A101#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'show version\n'
> DEBUG:netmiko:Pattern is: show\ version
> DEBUG:netmiko:_read_channel_expect read_data: s
> DEBUG:netmiko:_read_channel_expect read_data: how version
> 
> DEBUG:netmiko:Pattern found: show\ version show version
> 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel:

**Comment by hackmoonlight** [comment]
Terminal output:


```
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
ssh 192.168.247.2
Password: 
SSH prompt: Password:
```

**Comment by hackmoonlight** [comment]
@ktbyers

**Comment by hackmoonlight** [comment]
@ktbyers

**Comment by hackmoonlight** [comment]
@ktbyers

**Comment by hackmoonlight** [comment]
The log shows that the password is not written?

**Comment by hackmoonlight** [comment]
Hello @ktbyers  ,
I made some change in the code and it connects to the remote device.  but after using the redispatch function , I still not able to execute commands on the remote device. 

Untill here I connected to the second router 

`ldp= self.get_ldp_neighbors(alias)
        msg = ''
        for  x in ldp.keys():
            addr_list = ldp[x]['addresses'] #List of ldp ip adresses  
            print(addr_list)
            src_ip_addr= ldp[x]['SrcIPaddr'] #source ip addr
            print(src_ip_addr)  
            # Use raw read/write to SSH into device2
            print(device_info)
            net_connect = ConnectHandler(**device_info)
            
            net_connect.write_channel('ssh'+' '+src_ip_addr+'\n')
            time.sleep(1)
            net_connect.write_channel(net_connect.password + '\n')
            time.sleep(1)
            output = net_connect.read_channel()
            print(output)
            ### Logged into Second device
            print ("SSH prompt: {}".format(net_connect.find_prompt()))`

but After runing the dispatch command I cannot run commands on the router.

`            redispatch(net_connect, device_type='cisco_ios', session_prep=True)
            
            net_connect.enable()
            new_output = net_connect.send_command('show version', use_textfsm=True)
           
            version= new_output[0]['rommon']  #check ios version
            # check if addr_list exist in addr(list of ip addr got with cisco cmd)
            
            if  version == 'IOS-XE':
                new_output = net_connect.send_command('show ip route connected')
                addr= re.findall( r'[0-9]+(?:\.[0-9]+){3}', new_output) # list of @ip got from new_output
                verif = set(addr) & set(addr_list)
                #return src_ip_addr
                if verif == addr_list:
                    msg= 'ip in the list'
                               
            else:
                new_output1 = net_connect.send_command('sh route local')      self.cli   
                # cmd= "sh route local"
                # new_output1= self.device.cli([cmd])[cmd]
                addr= re.findall( r'[0-9]+(?:\.[0-9]+){3}', new_output1)
                if addr_list == addr:
                    msg= 'ip in the list'
        return msg    `


This is the log from robot framework showing that I am connectd to the second router:

<html><body>

Start / End / Elapsed: | 20210506 02:09:23.813 / 20210506 02:09:40.985 / 00:00:17.172
-- | --


</body></html>

**Comment by ktbyers** [comment]
@hackmoonlight Did you work this out?
