### ISSUE TITLE
flexvnf custom password login fail

### ISSUE THREAD

**Issue by dinzpy** [ktbyers/netmiko#2258]
HI @ktbyers, if we are using a custom password for login, flex_vnf ssh is failing, due to "re" condition in enter_cli_mode on flexvnf_ssh.py.
Manually changed the "re" condition in local installation, it's working fine.

        if re.search(r"admin@", cur_prompt) or re.search(
            r"^\$$", cur_prompt.strip()

        if re.search(r"admin@", cur_prompt) or re.search(
            r"\$$", cur_prompt.strip()

**Comment by ktbyers** [comment]
@dinzpy Both the above are identical and identical to the existing code so I am not understanding what you changed to fix it.

Also can you post me what the CLI looks like in this case so I can understand what is failing?

**Comment by ktbyers** [comment]
Okay, I see the difference now with the dropped `^` character.

Can you still show me what the CLI looks like so I can understand why it is failing.

Thanks, Kirk

**Comment by dinzpy** [comment]
Hi @ktbyers, CLI for your reference

Working CLI:
admin@ABCDEFGH-01:~$

Not working CLI:
[Administrator@ABCDEFGH-01: ~] $

**Comment by ktbyers** [comment]
And this is because the prompt has been customized? Why are the prompts different in the two cases?

**Comment by dinzpy** [comment]
username "admin" is only for CLI, But "Administrator" username is used for both CLI and GUI, depends on users role prompt has been customized. also, both user credentials, have write access.

**Comment by dinzpy** [comment]
Any update !

**Comment by ktbyers** [comment]
Is your CLI prompt customized i.e. why does Administrator have the square brackets around it (as compared to the Admin user)?

**Comment by ktbyers** [comment]
@dinzpy FYI, I put your fix here:

https://github.com/ktbyers/netmiko/pull/2268

**Comment by ktbyers** [comment]
Should be fixed in #2268

**Comment by dinzpy** [comment]
Thanks
