### ISSUE TITLE
Log the session output from device to a file

### ISSUE THREAD

**Issue by sandeepkhera** [ktbyers/netmiko#2259]
Hello All,

I am new to Netmiko and Python. I am working on a script to push set of commands to number of Cisco IOS devices. The script is tested fine but I am looking for a way where the whole session details from each device will be recorded in separate file.
The purpose is so these files can be checked to see if there was some issue to execute any command on any device..

**Comment by ktbyers** [comment]
Yes, just look up Netmiko's session_log this should provide you what you are looking for.


Kirk
