### ISSUE TITLE
issue with using Nornir netmiko_file_transfer

### ISSUE THREAD

**Issue by ryanmerrell92** [ktbyers/netmiko#2266]
Hi,

When I try and use the netmiko file transfer function in my script I get the following issue:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\Temp\\\Test\\\image.txt'

I use a variable for the source file destination as follows:
source_file = "C:\Temp\Test\image.txt"
dest_file= "bootflash:image.txt"
task.run(task=netmiko_file_transfer, source_file=source_file, dest_file=dest_file)

I don't get why it adding an extra backslash to the directory path when it runs the task?

**Comment by ktbyers** [comment]
That is probably just due to Python backslash escaping the backslashes.

```
In [8]: source_file = "C:\Temp\Test\image.txt"

In [9]: source_file
Out[9]: 'C:\\Temp\\Test\\image.txt'
```

Can you show me the full exception stack trace from your program (you probably will need to get this from Nornir's log file).
