### ISSUE TITLE
[ERROR] UnboundLocalError: local variable 'net_connect' referenced before assignment

### ISSUE THREAD

**Issue by roshanraj30** [ktbyers/netmiko#2270]
I'm testing netmiko on an AWS Lambda function. The script runs successfully if the Palo Alto instance is up and running, although when the Palo Alto instance is in down state I get "UnboundLocalError: local variable 'net_connect' referenced before assignment" .

Below is the code:

```
import os
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException

username = os.environ['username']
password = os.environ['password']

IP = '172.31.41.51'

def lambda_handler(event, context):
    login = {
        'ip': IP,
        'username': username,
        'password': password,
        'device_type': 'paloalto_panos'
    }
    try:
        net_connect = ConnectHandler(**login)
    except NetMikoTimeoutException:
        print(' Device not reachable.')
    except AuthenticationException:
        print(' Authentication Failure.')
    except SSHException:
        print(' Unable to SSH into the device.')

    version = net_connect.send_command('show system info')
    net_connect.disconnect()
    print(version)
```

**Comment by mrkcmo** [comment]
@roshanraj30 did this fix your issue?

**Comment by ktbyers** [comment]
Or more generally if a failure happened (i.e. an exception, you can't just keep executing your function i.e. expect Netmiko to do subsequent things). So you should decide what you want to have happen at that point (i.e. return from your function, raise an exception, log a.message and return from function, et cetera).
