### ISSUE TITLE
Netmiko OSError: Search pattern never detected in send_command_expect: Destination

### ISSUE THREAD

**Issue by searching12** [ktbyers/netmiko#2272]
Hi Ktbyers, I'm stuck here for more than an hour but seem like not able to find the solution for my issue. Issue is that I'm not able to completely match the string output. Please let me know if I'm missing something here ?

**Manual Process:**
```
hostname#$192.168.1.1/out/c2960x-universalk9-mz.152-7.E3.bin flash:c2960x-universalk9-mz.152-7.E3.bin
Destination filename [c2960x-universalk9-mz.152-7.E3.bin]? 
```

my code not working:
```
commandsend = "copy ftp://206.112.194.143/out/c2960x-universalk9-mz.152-7.E3.bin flash:c2960x-universalk9-mz.152-7.E3.bin"
output = connection.send_command(commandsend,expect_string=r'Destination filename')
output += connection.send_command('\n',expect_string=r'#')
```

I tried using the following but it still not working.
```
output = connection.send_command(commandsend,expect_string=r'Destination.*')
output = connection.send_command(commandsend,expect_string='Destination.*')
output = connection.send_command(commandsend,expect_string=r'Destination filename.+')

```
I even tried adjusting the delay factor, encoding and fast_cli=False but still the same.

When I tried using the exact output. I'm seeing the below error.
`output = connection.send_command(commandsend,expect_string=r'Destination filename [c2960x-universalk9-mz.152-7.E3.bin]? ')`
bad character range x-u at position 27

Is this a Bug or something? BTW during the issue im still seeing that the script still connected to the device.

**Comment by ktbyers** [comment]
You state here that your code isn't working:

```
commandsend = "copy ftp://206.112.194.143/out/c2960x-universalk9-mz.152-7.E3.bin flash:c2960x-universalk9-mz.152-7.E3.bin"
output = connection.send_command(commandsend,expect_string=r'Destination filename')
output += connection.send_command('\n',expect_string=r'#')
```

What happens? Do you get an exception or something else?

If you get an exception can you post your full exception stack trace.

**Comment by searching12** [comment]
Hi @ktbyers , Here's the traceback.

copy ftp://206.112.194.143/out/c2960x-universalk9-mz.152-7.E3.bin flash:c2960x-universalk9-mz.152-7.E3.bin
21:11:27.067 GMT Wed May 12 2021
Traceback (most recent call last):
  File "./svu.py", line 292, in <module>
    output = uploading_update(models,ver[0],ver[1],ver[2],ver[3])                            # Send to func {'CSR1000V': ['12.2.55',
  File "./svu.py", line 119, in uploading_update
    output = connection.send_command(commandsend,expect_string=r'Destination filename')
  File "/home/repos/public/Python/lib/python3.6/site-packages/netmiko/base_connection.py", line 1112, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: Destination filename

**Comment by searching12** [comment]
Does the length of the copy command affects the functionality? 

I not if the script actually sends the "copy" command since I noticed that users is idle. So not sure that why script cast see or march the "Destination filename"
   **2 vty 1     script  idle                 00:01:30 206.112.194.139 <--**

**Comment by searching12** [comment]
I found the issue and this is due to the script not actual entering the enable mode :(.

Learned another method in debugging this kind of issue and this is using the logs. 
https://github.com/ktbyers/netmiko/issues/1950

Cheers :).
