### ISSUE TITLE
Netmiko Beginner  : connecting to a router, Invalid parameter ^

### ISSUE THREAD

**Issue by ENLAYERBUI** [ktbyers/netmiko#2276]
Hello, 
I was trying to connect to a router and to just get the result of a one command the code is below :

from netmiko import ConnectHandler 

router = { 
"device_type": "xxxx", 
"host": "xxxx", 
"username": "xxxx", 
"password": "xxxx", 

} 

command = "show arp all" 

net_connect= ConnectHandler(**router)
output = net_connect.send_command(command) 

print(output)

and i get this error ' Error: Invalid parameter ^ ' i don't undrestand where is the problem !

would really appreciate help. Many thanks

**Comment by icrow78** [comment]
Hi @ENLAYERBUI:
Have Look at the following link :

https://pynet.twb-tech.com/blog/automation/netmiko.html


BR




Enviado desde mi iPhone

**Comment by ENLAYERBUI** [comment]
Hello @icrow78 

this is what i did, the same code! That’s why i am amazed ! I can’t figure out the error !

**Comment by icrow78** [comment]
But based on your script you are missing something . I had the same issue on Thursday and I solved it after I read the link. 
Can you share the log?

**Comment by ENLAYERBUI** [comment]
I don’t undrestand which log ?

**Comment by icrow78** [comment]
I recommend before starts to play with netmiko go through the documentation.
And before run the script , perform a testing of what you want to achieve using the cli.

Cheers

Enviado desde mi iPhone

**Comment by ktbyers** [comment]
@ENLAYERBUI Please post the full exception stack trace not just one line.

Also which Netmiko device_type are you using?

**Comment by Tes3awy** [comment]
I think the error is in the Cisco command itself. There is no `all` in the command. Please consider sending `show arp` only. You can add `"session_log": "router.log"` to the router dictionary and find the invalid parameter in the log file.

Something like:

```python
router = {
    "device_type": "xxxx",
    "host": "xxxx",
    "username": "xxxx",
    "password": "xxxx",
    "session_log": "router.log"
}

cmd = "show arp all"

net_connect = ConnectHandler(**router)
arp_output = net_connect.send_command(cmd)
net_connect.disconnect() # to clear the vty line

print(arp_output)
```

**Comment by ktbyers** [comment]
Yes, I agree with @Tes3awy. This probably indicates that the command you sent was invalid and Netmiko returned to you the output indicating your command was invalid.
