### ISSUE TITLE
Using netmiko to get the wrong file size of cisco device running-config file.

### ISSUE THREAD

**Issue by igbh** [ktbyers/netmiko#2278]
hi all,I met a strange thing....
My code
`
import netmiko

def logintodevice():
	r001={
		'device_type':'cisco_ios_telnet',
		'ip':'192.20.0.3',
		'port':23,
		'username':'admin',
		'password':'passwd',
		'secret':'passwd'
	}

	
	conn1=netmiko.ConnectHandler(**r001)
	hostname=conn1.find_prompt().replace('>','')
	filename="1"
	expectstring="Destination filename ["+ filename + "]?"
	print(expectstring)
	comm='copy running-config tftp://192.20.1.36/' + filename
	conn1.enable()
	output=conn1.send_command(comm,expect_string=r"Address or name of remote host [192.20.1.36]?",delay_factor=20)
	output+=conn1.send_command('\n',expect_string=expectstring)
	output+=conn1.send_command('\n',expect_string=r"!!")
	print(output)

if __name__ == '__main__':
	logintodevice()
'
The code works,but get a wrong size of the running-config,maybe 4K or 8K or 12K,and the correct size is 17Kb,
what's problem with my code??
plz help me,thanks a lot!

**Comment by igbh** [comment]
the output
------------------------------------------------------
D:\py>mycode.py
Destination filename [1]?
Address or name of remote host [143.20.1.36]? Destination filename [1]? !!
------------------------------------------------------

**Comment by vivekvashist** [comment]
Looks like you are using a `r001` dictionary inside a function `logintodevice` which returns `None` - and passing it to `netmiko.ConnectHandler(**r001)` 

I suggest you try/test with some official examples under https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#simple-example

**Comment by igbh** [comment]
it works!
thank you,vivekvashist !!
i should not use “ __main__” function.....
