### ISSUE TITLE
netmiko - weird issue - unable to derive context sensitve help without execution of the command string

### ISSUE THREAD

**Issue by jasonhaominglo** [ktbyers/netmiko#2281]
Hi guys,

Trying to invoke the printing of context sensitive help for a particular use case that i have but hitting an issue where i can get the return result for context sensitive help that i require but however, netmiko still goes ahead and still executes the command line string as per below:

```
ipdb> net_connect.find_prompt()
'mpkauswans02(config)#'
ipdb> net_connect.write_channel('int eth 1 ?')
ipdb> pp net_connect.read_channel()
('int eth 1 ?\r\n'
 '  inactive     Inactive subordinate lanes in multi-lane mode\r\n'
 '  unconnected  Unconnected/Internal ethernet ports\r\n'
 '  ,            extend list\r\n'
 '  -            specify range\r\n'
 '  .            subinterface\r\n'
 '  <cr>         \r\n'
 '\r\n'
 **'mpkauswans02(config)#int eth 1 ')**
ipdb> net_connect.find_prompt()
'mpkauswans02(config-if-Et1)#'
```

How does one prevent netmiko from eg. in the example above - eventually executing int eth1 to enter into the sub-structure of config-if-eth1?

Cheers,

Jason

**Comment by ktbyers** [comment]
Don't execute the find_prompt() after your `int eth 1`

find_prompt() sends an <enter> down the channel and your `int eth 1` command is still sitting there after you are done with the context sensitive help.

So you would need to delete the command `int eth 1` before executing find_prompt(). Realistically, you should delete the command sitting there before doing anything else using the SSH channel.

**Comment by jasonhaominglo** [comment]
Thanks Kirk - is there a neat way to remove the command string?

**Comment by ktbyers** [comment]
You can just splitlines() on the first line and then retrieve what is left...should be close to:

```python
out_list = output.splitlines()
# drop the first line
out_list = out_list[1:]
# convert back to a string
output = "\n".join(out_list)
```
