### ISSUE TITLE
ZTE zte_zxros screen-length 0 Issue

### ISSUE THREAD

**Issue by nontha** [ktbyers/netmiko#2287]
I'm importing `ZteZxrosSSH` and `zte_zxros` when connecting to **ZTE 5250-28TC-H** and **ZTE 5250-28TM-H** devices. However, when the screen-length is longer (than one screen), it doesn't automatically load the full output of a command (eg:` show run`). 

```
MOBXXX>show running-config 
  Software version: V2.05.12B21
  Switch's Mac Address: 0c.xx.xx.xx.xx.cd

!
  syslocation No.123, XYZ
  syscontact Contact__info@mail.XYZ.com.cn__for_more_information.
  hostname MOBXXX
  promptlen 32
  create user admin admin
  set user local admin login-password B612AD6F2259089Axxxxxxxx5A38BF
  set user local admin admin-password 4DBxxxxxxx5AFB1AE
  line-vty timeout 10
  terminal monitor module AAA off 
  terminal monitor module radius off 
  set loginauth local+radius
  set user multi-user enable
!
!
!
  set port statistics mode ingress 
  set port 1/1 description ### X11111_MOBXXX_ETHERNET_VPN ###
  set jumbo port 1/1 enable
  set port 1/1 pvid 101
  set port 1/2 disable
----- more ----- Press Q or Ctrl+C to break -----
```

I couldn't find any `screen-length 0` command in the device in both normal or privileged modes. 

Appreciate if you could find me a workaround method for this issue.

**Comment by ktbyers** [comment]
Does `terminal length 0` work / not work?

That looks like what we are trying to execute for the ZTE device_type.

**Comment by nontha** [comment]
@ktbyers `terminal length 0` is applied by the  (`zte_zxros`?) however, the log says 

```
MOBXXX>
2021-05-31 15:56:40,731 DEBUG Pattern found: terminal\ length\ 0 terminal length 0

  %  Command not found (0x40000034)
```

Also the command `terminal length 0` not found in cli (not in both user exec/ privilege modes).

**Comment by ktbyers** [comment]
Are there different ZTE ZXROS devices or is there a different OS version where this command works?

Is there any command in ZTE ZXROS where you can disable the paging of output?

**Comment by nontha** [comment]
I couldn't find any ZTE device in my network which include the command `terminal-length`.

And couldn't find any alternative command to disable paging.

**Comment by ktbyers** [comment]
You could probably write a for loop and use write_channel() to page through the output (sending a space character each time `more` appears). 

I would assume that some set of ZTE ZXROS have this capability since it was included in the original implementation, but would have to dig into these devices more to know.
