### ISSUE TITLE
Netmiko/ How can I make my current code use Multithreading/concurrent.futures?

### ISSUE THREAD

**Issue by sanketh89** [ktbyers/netmiko#2300]
I am new to netmiko/Python scripting , Using online examples was able to make a script to take configuration backup. The backup is copied to the text file and output is saved.

Currently this backup is done sequentially and it does not connect to all device at once and take the backup. I want to connect to all the devices concurrently.

I understand multithreading or concurrent.futures can solve this issue  but I was not able to do it so far.

Can anyone please suggest, how my existing code can be modified to achieve it. Below is the code.

    from netmiko import ConnectHandler
    from netmiko.ssh_exception import NetMikoTimeoutException
    from paramiko.ssh_exception import SSHException
    from netmiko.ssh_exception import AuthenticationException
    import getpass
    import sys
    import time
    import os
    from datetime import datetime

    ##getting system date 
    day=time.strftime('%d')
     month=time.strftime('%m')
     year=time.strftime('%Y')
     today=day+"-"+month+"-"+year

     ##initialising device
     device = {
    'device_type': 'cisco_ios',
    'ip': '192.168.100.21',
    'username': 'Cisco',
    'password': 'Cisco',
    'secret':'Cisco',
    'session_log': 'log.txt'
     }
    ##opening IP file
    ipfile=open("iplist.txt")
    print ("Script to take backup of devices, Please enter your credential")
    device['username']=input("username ")
    device['password']=getpass.getpass()
    print("Enter enable password: ")
    device['secret']=getpass.getpass()

    ##taking backup
    for line in ipfile:
     try:
     device['ip']=line.strip("\n")
     print("\n\nConnecting Device ",line)
     net_connect = ConnectHandler(**device)
     net_connect.enable()
     time.sleep(1)

    with open('config.txt') as f:
    cmd = f.read().splitlines()
    print ("Reading the running config ")
    output = net_connect.send_config_set(cmd)
    output4 = "Failed"
    time.sleep(7)    
    filename=device['ip']+'-'+today+".txt"
    folder = os.path.join(today)
    file = os.path.join(folder,filename)
     os.makedirs(folder,exist_ok=True)
     saveconfig=open(file,'w+')
     print("Writing Configuration to file")
     saveconfig.write(output)
      saveconfig.close()
      time.sleep(10)
      net_connect.disconnect()
      
      print ("Configuration saved to file",filename)   
      except:
      print ("Access to       ######"+device['ip']+" failed,backup did not taken")
      output4 = "Failed"
      file= device['ip']+'-'+today+"Error"+".txt"
      config=open(file,'w+')
      config.write(output4)
      config.close()
      
     ipfile.close()
     print ("\nAll device backup completed")

**Comment by ktbyers** [comment]
Here are some examples using threads and processes:

https://github.com/twin-bridges/netmiko_course/tree/master/class8/collateral


You might also want to check out Nornir which has Netmiko plugins available.
