### ISSUE TITLE
Netmiko not properly detecting enable mode on some Cisco ASA logins

### ISSUE THREAD

**Issue by bookydedreamer** [ktbyers/netmiko#2305]
I'm adapting a script I inherited in order to add additional devices to be queried.
 
The devices I'm adding are Cisco ASAs - the same types of ASAs that already exist in the script. I duplicated the configuration that exists to connect to them, and the commands that run on them to match the settings for the previously configured ASAs. However, whenever I try to connect to them using NetMiko, I receive the following error:
_Some Other Exception with Device. Failed to enter enable mode.  Please ensure you pass the 'secret' argument to Connect Handler._
 
I logged the output of what happens on the ASA when the connection is attempted, and receive the following output:
 
_* * * * * * * * * * * * * * * * * * * * * * * *
******************WARNING!*********************
* This computer system and network is PRIVATE *
* AND PROPRIETARY and may only be accessed    *
* by authorized users.                        *
*                                             *
* Unauthorized use of this computer system or *
* network is strictly prohibited and may be   *
* subject to criminal prosecution, employee   *
* discipline up to and including discharge, or*
* the termination of vendor/service contracts.*
*                                             *
* The owner, or its agents, may monitor any   *
* activity or communication on the computer   *
* system or network. The owner of its agents, *
* may retrieve any information stored within  *
* the computer system or network.             *
*                                             *
* There is no privacy on this system. By      *
* accessing and using this computer system    *
* or network, you are consenting to such      *
* monitoring.                                 *
* * * * * * * * * * * * * * * * * * * * * * * *
User *** logged in to dc1-fvdmz07
Logins over the last 1 days: 4.  Last login: 13:22:45 UTC Jun 10 2021 from ***
<--- More --->              Failed logins since the last login: 0. 
<--- More --->              Type help or '?' for a list of available commands.
dc1-fvdmz07#
dc1-fvdmz07# exit_
 
It's clearly hitting the ASA in enable mode. The configured connections for the previously set up ASAs continue to work fine. I tried adding a sleep command for 10 seconds and sending a command to just send 'newline' and check for the router prompt. Neither helped with this issue.  What can I do to ensure these new ASAs are properly detected as being in enable mode on login?

**Comment by ktbyers** [comment]
Can you post the following:

1. Simplified version of your test code (i.e. simplified down to the base case).
2. The exception stack trace that you receive.


Why is your device doing this i.e. what is this about?

```
<--- More ---> Failed logins since the last login: 0.
<--- More ---> Type help or '?' for a list of available commands.
```

**Comment by bookydedreamer** [comment]
While setting up to do a simplified test to show you the output you requested, I also logged the results for one of the successful connections. I found the successful ASA connection was not logging into enable mode at base, where the failing ASAs were. I removed the 'enable' prompt for the problem ASAs and the connection worked.
