### ISSUE TITLE
cant send multiple commands

### ISSUE THREAD

**Issue by saadi381** [ktbyers/netmiko#231]
hi ;
first i would like to thank you for great work you have done with netmiko . 2ndly i am a bit newbie for python and i am having dofficulties sending multiple commands
Below is the snippet

So the idea is to grab host names from
Hostfile.txt
router 1
router 2
router 3
commands.txt
sh run
sh ip int bri
sh invent

the problem is the below codes for each router runs

router 1
sh run
router 1
sh run
sh ip int bri
router 1
sh run
sh ip int bri
sh invent

router 2
sh run
router 2
sh run
sh ip int bri
router 2
sh run
sh ip int bri
sh invent
 
and so on

what i need is

router 1
sh run
sh ip int bri
sh inventory
router 2
sh run
sh ip int bri
sh inventory
and so on

from __future__ import print_function
from netmiko import ConnectHandler ##For SSH
import re
import getpass
while True: #create loop for whole program
    username = input ("Enter Username")
    jumphostpassword = getpass.getpass("Enter Jumphost Password")
    elif (op == 2):
            TACACSpassword = getpass.getpass ("Enter TACACS Password")
            elif(in1=="c"):
                    commandsfile = input ("Please Enter CommandsFile path as c:/example/ \n :")
                    hostsfile = input ("Please Enter Hosts path as c:/example/ \n :")
                   # hosts = open((hostsfile) , "r")
                    hosts = [hosts for hosts  in (hosts.strip() for hosts in open(hostsfile)) if hosts]
                    for host1  in hosts:
                                    with open ( host1+".txt","w") as file:
                                            commands1 = open( (commandsfile), "r+")
                                            jumphost = {'device_type': 'linux','ip': '172.27.200.26', 'username': (username),'password': (jumphostpassword)}
                                            net_connect = ConnectHandler(**jumphost)
                                            output = net_connect.send_command("ssh " +str(host1))
                                            print (output)
                                            else:
                                                    output = net_connect.send_command(TACACSpassword)
                                                    print (output)
                                                    output = net_connect.send_command("term leng 0")
                                                    print (output)                                                        

                                                    cmd1 = [cmd1 for cmd1  in (cmd1.strip() for cmd1 in open(commandsfile)) if cmd1]
                                                    for cmd1 in commands1:                                                       
                                                        print ("File saved in c:\saad\saad.txt ")
                                                        output += net_connect.send_config_set(cmd1)
                                                        print (output)

                                                        net_connect.disconnect
                                                    print ("File saved in c:\saad\saad.txt ")       
                                            file.write(output)

                                    file.close()
                    continue

**Comment by saadi381** [comment]
I found the issue ..thanks

**Comment by marktongarcia** [comment]
hi Saadi,

How did you fix the issue?  Also, can you please share your code?  I'm trying to achieve the same thing using netmiko but it wont work.  I am able to send a single command to several devices  but not able to send multiple commands.  send.config.set doesn't seem to work. 

thanks in advance.

**Comment by saadi381** [comment]
Hi ; I actually ended up using "for loop" ; here is a snippet to what i did.. I am just a starter in python so its not very clean code

>  jumphost = {'device_type': 'linux','ip': 'x.x.x.x', 'username': (username),'password': (jumphostpassword)} 
                                    net_connect = ConnectHandler(**jumphost)
                                    output = net_connect.send_command("ssh " +str(host))
                                    print (output)
                                    file = open('c:\saad\saad.txt', 'w')
                                    if "No route to host"  in output:
                                        print ("Device Not Found")
                                    else:
                                        if "continue" in output:
                                            output = net_connect.send_command("yes")
                                            print (output)
                                            output = net_connect.send_command(TACACSpassword)
                                            print (output)
                                            output = net_connect.send_command("term leng 0")
                                            print (output)
                                            output = ''
                                            
                                            for cmd in commands:
                                                out2 = net_connect.send_command(cmd, delay_factor=2)
                                                print(cmd)
                                                print (out2)
                                                net_connect.disconnect
                                                print (out2)
                                                file.write(cmd)
                                                file.write(out2)                                         
                                                print ("File saved in c:\saad\saad.txt ")
                                                net_connect.disconnect
                                                
                                        else:
                                            output = net_connect.send_command(TACACSpassword)
                                            print (output)
                                            output = net_connect.send_command("term leng 0")
                                            print (output)
                                            for cmd in commands:
                                                out3 = net_connect.send_command(cmd, delay_factor=2)
                                                print (cmd)
                                                print (out3)
                                                file.write(cmd)
                                                file.write(out3)
                                                net_connect.disconnect
                                                print (out3)
                                                print ("File saved in c:\saad\saad.txt ")
                                    
                    file.close()



let me know incase of any thing more i can help with

**Comment by marktongarcia** [comment]
Hi Saadi,

Thanks for sharing your code.  I will take time though to analyze this as I'm a complete noob.  Not really a programmer but since I'm handling hundreds of access switch and distribution switches, network automation would really help me a lot.

I'll update you and share my work once I get it fully functional.  It will be coded to run on windows python btw.

Kind regards,
Mark

**Comment by kooljonn6858** [comment]
Try this solution, https://github.com/kooljonn6858/Netmiko_Multiple_Show_Commands

**Comment by ktbyers** [comment]
```python
for cmd in list_of_commands:
    output = net_connect.send_command(cmd)
    print(output)
    # You could do other things with the results, but that might require a more complex data structure like a dictionary.
    # results_dict[cmd] = output (for example)
```
