### ISSUE TITLE
Variable with multiple-lines

### ISSUE THREAD

**Issue by mewpeh** [ktbyers/netmiko#2312]
Hi!
I'm completely new to both python and netmiko.
So I'm sorry if this question is stupid.
However, I would like to paste a variable that contains multiple lines after I've first targeted the interface that's going to get the configuration.

The variable is reading from a txt-file. I'll give examples.

So the _file.txt_ looks like this
_sw mo ac
sw ac vlan 301
span bpduguard en
sw port violation protect
sw port maximum 30
sw port aging time 3
span portfast
st m l 20
st b l 10
st a shut
sw none
desc IPTV_

Here's the code: (jumping right into the middle, the command given by the user is "Port 14 iptv" that we split into vars)

```
try:
     command, portNumber, itemName = line.split()
     item_is = (data[ch]['items'][itemName])
     file = open(item_is)
     item_to_config = file.read()
     item_thread = Thread(target=config_item, args=(host, InterFace, portNumber, item_to_config))
     item_thread.start()
```
                
Function:
```
def config_item(host, InterFace, portNumber, item_to_config):
    nethost = connect_to_switch(host)
    ssh = ConnectHandler(**nethost)
    ssh.commands = ['int range '+InterFace+portNumber, item_to_config]
    output1 = ssh.send_config_set(ssh.commands)
    print(output1)
```
    
This ofc doesn't work, it's just one of many ways I've tried.
I've tried to just send the path to the file and use "send_config_from_file"
That works to send the config from the file, but I don't know how to specify the interface first. If I use "send_command" first followed by interface, the lines ends with "end" and the config followed by the "send_config_from_file" is not pasted into the interface.

So to make my long questions shorter.
Is it possible to first specify an interface and then paste configuration from a file with netmiko?
This should ofc be done without specifying the interface within the file.txt.

Thanks in advance, and sorry if it's unclear, I've started coding 4 weeks ago, so this is all new to me.

**Comment by ktbyers** [comment]
You need to post a simplify base case without threading. In other words, just simplify the problem to a single device and no threading.

Are you still seeing an issue then?

Also I would pretty strongly recommend not using `int range` with automation. In other words, with `int range` you are counting on a macro that expands range construct internal to the device. With automation you are almost invariably better off doing that expansion of the configuration in your code. For example, in a for-loop or some other way of generating the configs. 

In other words, you want all of the config you are sending available to your program ideally with the same exact syntax that it shows in the remote device (including no abbreviations).

These things will make it more likely that your program works properly and make it easier in the long run for you to compare what you sent to what is configured.

Typically the type of thing you are trying to do would be accomplished by Jinja2 templating. There should be a bunch of examples for generating network configs using Jinja2 template online.

Regards, Kirk

**Comment by mewpeh** [comment]
> You need to post a simplify base case without threading. In other words, just simplify the problem to a single device and no threading.
> 
> Are you still seeing an issue then?
> 
> Also I would pretty strongly recommend not using `int range` with automation. In other words, with `int range` you are counting on a macro that expands range construct internal to the device. With automation you are almost invariably better off doing that expansion of the configuration in your code. For example, in a for-loop or some other way of generating the configs.
> 
> In other words, you want all of the config you are sending available to your program ideally with the same exact syntax that it shows in the remote device (including no abbreviations).
> 
> These things will make it more likely that your program works properly and make it easier in the long run for you to compare what you sent to what is configured.
> 
> Typically the type of thing you are trying to do would be accomplished by Jinja2 templating. There should be a bunch of examples for generating network configs using Jinja2 template online.
> 
> Regards, Kirk

Thanks for your feedback mate!
About the int range I see your point, and I will definitely think of this for future projects.
For this particular project I'm however not that worried.  This is a slackbot for accessswitches so that people can send "@confbot <host> Port 1-14 <item>" etc. Since 'int range' will work for one port and more ports with the "-" it's an easy way to get it done.
But probably not the best, *tihi*...

Will look into Jina2 templating, never heard of it before.

For the issue I had, I got it solved with yet another awful way...

```
int_gig = ('int gig1/0/')
port = ('14')
the_user_input = ('iptv')
port2 = ('15')



iptv = ['sw mo ac',
        'sw ac vlan 10',
        'desc IPTV']

AP = ['sw mo ac',
      'sw ac vlan 105',
      'sw none',
      'span portfast',
      'desc AP']

not_found = ('item not found in list')

def the_list(the_input):
    if the_input == "iptv":
        return(iptv)
    if the_input == "ap":
        return(AP)
    else:
        return(not_found)
```
```
def the_function(host, the_user_input, int_gig, port):
    item_from_list = the_list(the_user_input)
    the_configuration = list.copy(item_from_list)
    the_configuration.insert(0, int_gig+port)
    ssh = ConnectHandler(**host)
    send_commands = (the_configuration)
    output = ssh.send_config_set(send_commands)
    return(output)

test1 = the_function(nethost, the_user_input, int_gig, port)
print(test1)

```
inserting the port to a copy of the list, i don't like it, but it works...
