### ISSUE TITLE
Netmiko check prompt before pushing the configuration

### ISSUE THREAD

**Issue by kbSean1** [ktbyers/netmiko#2326]
I use Netmiko to ssh to a cisco router and  I was trying to apply the BGP configuration using ssh_conn.send_config_set(). Below is a sample configuration to be applied. Expected behavior:
bgp router-id x.x.x.x should be configured under the vrf address family. For some reason, when I tested manually, router didn't change the prompt and hence applied all the configuration to the global mode instead of address family mode and resulted in a BGP flap. Is there any way to check the prompt before applying the configuration?
router bgp as_no
  address-family ipv4 vrf {vrf_name}
      bgp router-id x.x.x.x

**Comment by ktbyers** [comment]
Closing and using discussion instead:

https://github.com/ktbyers/netmiko/discussions/2325
