### ISSUE TITLE
SSH Connection to Cisco ISE - ADE-OS 2.6

### ISSUE THREAD

**Issue by mika-mika-mika** [ktbyers/netmiko#2327]
Hello, I have been trying to create an SSH connection to Cisco ISE in order to automate periodic config changes. 
![image](https://user-images.githubusercontent.com/86295227/122908709-bad27380-d354-11eb-93d5-b0289671eb4b.png)

The issue I have noticed, however, is that at the start of the session, it will show currently open sessions and ask whether the user wants to start a new one (by pressing Enter) or keep using an existing session (by pressing the corresponding number):
![image](https://user-images.githubusercontent.com/86295227/122906929-f1a78a00-d352-11eb-93cb-7611ed9922bd.png)

Using the following parameters:
```py
dev = {
    "host": ise1,
    "username": user,
    "password": pwd,
    "device_type": "cisco_ios",
    "session_log": f"{script_path}\session.out",
}
conn = ConnectHandler(**dev)
```
... I keep getting an AttributeError exception. I tried sending "1" or "\n" but to no avail.

Here is also a part of the session_log:
```
Enter session number to resume or press <Enter> to start a new one:% Error: Invalid session, enter the number of the session
Enter session number to resume or press <Enter> to start a new one:terminal length 0
% Error: Invalid session, enter the number of the session
Enter session number to resume or press <Enter> to start a new one:
[r[m[2J[H[?7h[?1;3;4;6l[4l[4l=[0m(B[1;1000r[H[2J[H[2J
```

The other situation is when there aren't any existing sessions running, then I am able to get into the CLI right away without any problem since there aren't any prompts like the one above.

Ideally, I would like to still be able to reach the CLI even when there are existing sessions. How can I get around this?

Thanks in advance!

**Comment by datisnetwork** [comment]
i have this problem too

**Comment by ktbyers** [comment]
It looks like someone needs to build a Netmiko driver for this platform. The cisco_ios driver looks like it will not handle the special things this ISE ADE-OS platform is doing.

The general process for adding a driver is here.

Just let me know if you have questions.


Regards, Kirk
