### ISSUE TITLE
SSH-Proxy through windows jump server is not working properly

### ISSUE THREAD

**Issue by alwaysdoubts** [ktbyers/netmiko#2330]
I am connecting to a network device through a windows jumpserver in middle.I am able to perform tasks and eveything.But i am getting the junk data in the output.I have observerd in middle when there is a windows jumpserver the junk data is coming.If it is linux the junk data is not coming.Please help me to eliminate the junk data.

**Comment by ktbyers** [comment]
@alwaysdoubts That is really insufficient information to assist in anyway.

You would need to include your code, and the example output of what you are seeing, and also your SSH proxy config file that Netmiko is using for the Jump Server.

Also how are you even making the windows jump server work i.e. does it have Windows Subsystem for Linux on it?


Regards, Kirk
