### ISSUE TITLE
Telnet over SSH Proxy not possible?

### ISSUE THREAD

**Issue by Toxic-Waste-** [ktbyers/netmiko#2365]
Hi all,

Apologies if this is the wrong place, but I have searched for a solution an entire day. Either my searchskills are way off, or it's not possible what I am trying to achieve, but the following is not working: 

We have multiple cisco ios devices we connect to via Telnet. However these are only reachable from a jumphost (linux machine). I have an ssh config that does the SSH proxy. Whenever I use pure SSH, this works, but only certain routers have SSH enabled.

Is it possible to use the ProxyCommand for Telnet aswell? Whenever I run the script I get:

Traceback (most recent call last):
  File "/home/user/netmiko/lcr-ntp-update.py", line 17, in <module>
    net_connect = ConnectHandler(**device)
  File "/home/user/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/user/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/home/user/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 922, in establish_connection
    self.remote_conn = telnetlib.Telnet(
  File "/usr/lib/python3.8/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.8/telnetlib.py", line 235, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

Any suggestions?

**Comment by Toxic-Waste-** [comment]
Anyone that could at least confirm it is possible to do? 

I am happy to put more details of what I am trying to do, but for now I am very much stuck..

**Comment by ktbyers** [comment]
You can definitely do this straight in Netmiko i.e. connect to Jump host, then SSH from there to the end device. Then do a redispatch to switch the Netmiko class. You should be able to see if this if you search on redispatch in Github issues.

I don't know if you can do this with ProxyCommand...I doubt it.


Kirk

**Comment by Toxic-Waste-** [comment]
@ktbyers thanks for the reply!

However it seems I didn't explain it properly, the usecase is basically the following:
WSL instance on a Windows machine => SSH to jumphost => telnet to cisco IOS routers.

The reason I am asking is because I get a connection refused when I try to run it, so I feel like netmiko is trying to telnet to the jumphost instead of redirecting the command via SSH to the jumphost and THEN telnetting.

So my setup should be to connect to a linux device (the jumphost) and then redispatch it to the telnet class to do the connection to all my routers?

**Comment by ktbyers** [comment]
No worries...yeah I understood your original question, just wrote it wrong above.

```
You can definitely do this straight in Netmiko i.e. connect to Jump host, then telnet from there to the end device. Then do a redispatch to switch the Netmiko class. 
```

Yeah, that is how I would try to do it...use Netmiko to SSH to linux device using device_type of `linux` and then use Netmiko to execute `telnet x.x.x.x` where x.x.x.x is your end Cisco IOS router. Note, you will need to handle the telnet login yourself (though you might be able to reuse the existing telnet_login() method in Netmiko). After you have handled the telnet login, then use `redispatch` to change the Netmiko class (so the Cisco IOS operations work properly).

This example should be similar to what you are doing:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#terminal-server-and-redispatch

**Comment by Toxic-Waste-** [comment]
Alright, I wanted to make sure I was not missing anything, I took another route and got it to work this way (basically everything pure SSH I run from my personal station, while the telnet I run from the jumphost itself)

Thanks for the amazing work on this!
