### ISSUE TITLE
Remove max_loops from send_config_set and convert to read_timeout()

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#2370]

**Comment by adrian549092** [comment]
Hey Kurt, does it make sense to do this for send_command as well? I am having an issue with ASA regarding "max_loops" on the send_command (#2378)

**Comment by ktbyers** [comment]
@adrian549092 That is done on send_command in the `develop` branch (Netmiko 4.x).

New format will be:

```
net_connect.send_command(command, read_timeout=30)
```

Where read_timeout is an absolute timer in seconds for the number of seconds Netmiko will wait looking for terminating pattern (defaults to being based on prompt). If read_timeout expires a ReadTimeout exception will be raised.

Just let me now if you have questions.

**Comment by ktbyers** [comment]
This was implemented in the Netmiko develop branch.

**Comment by adrian549092** [comment]
Hey @ktbyers , thanks for letting me know. Does the read_timeout take into account if there is new data in the channel? I.e. Only timeout after 30 seconds of no new data

Also, I am debugging and I just realised that in 3.3.2 the ASA default for fast_cli is false and in 3.40 it is true which is causing netmiko to ignore the delay factor I pass in as an argument if it is larger than the default global_delat_factor

```Python
def select_delay_factor(self, delay_factor):
    """
    Choose the greater of delay_factor or self.global_delay_factor (default).
    In fast_cli choose the lesser of delay_factor of self.global_delay_factor.
    :param delay_factor: See __init__: global_delay_factor
    :type delay_factor: int
    """
    if self.fast_cli:
        if delay_factor and delay_factor <= self.global_delay_factor:
            return delay_factor
        else:
            return self.global_delay_factor
    else:
        if delay_factor >= self.global_delay_factor:
            return delay_factor
        else:
            return self.global_delay_factor
```

**Comment by ktbyers** [comment]
No read_timeout is an absolute timer so it starts at the beginning and waits that amount of time independent of data.

For send_command_timing() which is entirely delay based there is a timer based on the last successful read. This timeout is named `last_read` (i.e. how long to wait on the last read when it thinks there is no new data). There is also an absolute timer named `read_timeout`. You can set this to zero if you never want it to timeout.

Yeah, the complexity of fast_cli and delay_factor/global_delay_factor is one of the major things I want to move away from in Netmiko 4.x.

Just let me know if you have other questions.

**Comment by adrian549092** [comment]
Got it, the approach makes sense now. Thanks again for taking the time to respond to my questions, and thanks for the work you've done on Netmiko, this library is the backbone for most of what I do today!

**Comment by ktbyers** [comment]
Yeah, I am hoping some of these Netmiko 4.x timeouts greatly simplify this...

**Comment by adrian549092** [comment]
Oh one more thing, I saw that Netmiko has a slack channel. I clicked on the "invitation link" but got a message that it is no longer active and that I should reach out directly to the owner.

**Comment by ktbyers** [comment]
Do you know my email? Probably easier to send it that way.

**Comment by adrian549092** [comment]
I do not, but I found you on linked-in and sent you a request to connect. I can share you my email there privately if that works for you.
