### ISSUE TITLE
Secure Copy with Progressbar

### ISSUE THREAD

**Issue by Tes3awy** [ktbyers/netmiko#2373]
Hello @ktbyers,

I am trying to improve my code and add the progressbar to the `file_transfer` function. I was wondering how can I calculate the `sent` argument? I found this [answer ](https://stackoverflow.com/questions/49657776/python-scpclient-copy-progress-check/#answer-49657868) on SOF and this demo on [GitHub](https://github.com/jbardin/scp.py), but I can't figure out how to use it with my provided code.

```python
from os.path import getsize

from netmiko import ConnectHandler, file_transfer, progress_bar

router = {
    "device_type": "cisco_ios",
    "host": "sandbox-iosxe-latest-1.cisco.com",
    "username": "developer",
    "password": "C1sco12345",
    "port": 22,
    "verbose": True,
    "conn_timeout": 12,
    "fast_cli": False,
    "session_log": "sandbox-iosxe-latest-1.cisco.com.log",
}

src_file = dest_file = input("Name of file to copy: ")

with ConnectHandler(**router) as net_connect:
    scp = net_connect.send_config_set(config_commands=["ip scp server enable"])
    transfer = file_transfer(
        net_connect,
        source_file=src_file,
        dest_file=dest_file,
        file_system="flash:",
        direction="put",
        overwrite_file=True,
        socket_timeout=100.0,
        progress=progress_bar(
            filename=src_file,
            size=getsize(src_file),
            sent=sent,  # How to calculate? What should be placed here?
        ),
    )
```

Thanks a lot.

**Comment by ktbyers** [comment]
Should just be:

`progress=progress_bar`

or

`progress4=progress_bar`

You don't provide any arguments, just a callable.

**Comment by ktbyers** [comment]
Here is an example `file_transfer` on it:

```python
ssh_conn = ConnectHandler(**cisco)
transfer_dict = file_transfer(
    ssh_conn,
    source_file=source_file,
    dest_file=dest_file,
    file_system=file_system,
    direction=direction,
    # Force an overwrite of the file if it already exists
    overwrite_file=True,
    progress4=progress_bar,
)
```

**Comment by Tes3awy** [comment]
I am using this code on Windows 10 with GitBash installed. I can normally print statments in colors using `termcolor` and `colorama`. But I see some weird characters that appear in standard output every time I run the script:

```bash
←[2J <--- These characters
Transferring file to (ip_address, port): file.txt
``` 

I can find these chars in [`scp_functions.py`](https://github.com/ktbyers/netmiko/blob/62f9ff683b6329e729a55c8ab5510ccfd74f8fd3/netmiko/scp_functions.py#L26) file.

I actually have no idea why these characters appears in the terminal as is?

**Comment by ktbyers** [comment]
Netmiko's progress bar uses Ansi escape codes to accomplish what it needs to do. The [2J is the clear screen ANSI code:

     clear_screen = chr(27) + "[2J"

It looks like your terminal setup and what Netmiko is doing are probably interfering in some way.

A couple of options:
1. See if you can simplify your terminal setup to get what Netmiko is doing to work.
2. Write your own progress bar function to work with your terminal.

Here is Netmiko's progress bar function.

https://github.com/ktbyers/netmiko/blob/v3.4.0/netmiko/scp_functions.py#L11


Regards, Kirk

**Comment by ktbyers** [comment]
@Tes3awy Did you work out a solution?

**Comment by Tes3awy** [comment]
> 
> 
> @Tes3awy Did you work out a solution?

Not yet really. I am planning to simplify the terminal setup but later as it's not an issue preventing anything from working.

Thanks for caring <3

**Comment by Tes3awy** [comment]
> @Tes3awy Did you work out a solution?

Finally, I had the time to find a pretty method of printing the progress in terminal.

```python
from rich import print

def progress_bar(filename, size, sent, peername):
    print(
        f"({peername[0]}:{peername[1]}) {filename.decode('ascii')}'s progress: {float(sent) / float(size) * 100:.1f}%",
        end=" \r",
        flush=True,
    )
```

This is actually the same as in the [scp.py README](https://github.com/jbardin/scp.py#tracking-progress-of-your-file-uploadsdownloads) but using `print()` from `rich` instead of `sys.stdout.write()` to have a colored output in the terminal.

_The only drawback of using `end=" \r"` is that the print statement after the `progress_bar` print statement overwrites it._

**Comment by ktbyers** [comment]
Okay, nice...yeah, we should update Netmiko's default progress bar to use "rich".

**Comment by Tes3awy** [comment]
> Okay, nice...yeah, we should update Netmiko's default progress bar to use "rich".

Couldn't agree more 👍🏼
