### ISSUE TITLE
ASA IOError Search pattern never detected in send_command for long output commands

### ISSUE THREAD

**Issue by adrian549092** [ktbyers/netmiko#2378]
On ASAs, for commands that produce a large amount of output, such as show running-config, max_loops is reached in the send_command function before the ASA has finished producing the output of the command.  This was working in 3.3.2 and earlier but is not working in 3.3.3 and 3.4.0

A workaround would be to specify a delay factor to the send_command function, but I'm not sure if that should be the solution

**Comment by ktbyers** [comment]
@adrian549092 So is this issue fixed then...it looks like it from our discussion in #2370?

**Comment by adrian-martin11** [comment]
@ktbyers, unfortunately I don't have a way to test this anymore, I've moved on to another role and don't have access to the ASAs anymore.

**Comment by ktbyers** [comment]
@adrian-martin11 No worries :-)
