### ISSUE TITLE
how to give delay after executing the following command in NETMIKO

### ISSUE THREAD

**Issue by adarshagowda** [ktbyers/netmiko#238]
from netmiko import ConnectHandler
import time
cisco_881 = {
    'device_type': 'cisco_ios',
    'ip':   '10.10.10.1',
    'username': 'user',
    'password': 'pwd',
}
net_connect = ConnectHandler(**cisco_881)

output = net_connect.send_command('show ip int brief')
output = net_connect.send_command('copy bootflash:my_config running-config\n')
print(output)

# AT THIS PLACE IT SHOWING Timed-out reading channel, data not available.
#TO LOAD THE CONFIG IT TAKES TIME

config_commands = [ 'hostname OBSsite1CSR1000v',
                    'ip name-server 192.168.5.68',
                    'ip name-server 172.17.28.101',
                    'interface Loopback0',
                    'ip address 77.77.77.7 255.255.255.255',
                    'ntp server 172.17.28.5'
                  ]
output = net_connect.send_config_set(config_commands)
# AT THIS PLACE IT SHOWING Timed-out reading channel, data not available.
print(output)

**Comment by ktbyers** [comment]
For your first one do this:

```
output = net_connect.send_command_expect('copy bootflash:my_config running-config\n')
```

For the second one...that is probably failing because you are changing the 'hostname' which causes it to break (as it is looking for the trailing prompt).

Try, something like this:

```
net_connect.config_mode()
net_connect.remote_conn.sendall('hostname OBSsite1CSR1000v' + '\n')
net_connect.exit_config_mode()
```

Then remove the hostname from your config_commands and re-execute that as normal:

```
config_commands = [
'ip name-server 192.168.5.68',
'ip name-server 172.17.28.101',
'interface Loopback0',
'ip address 77.77.77.7 255.255.255.255',
'ntp server 172.17.28.5'
]
output = net_connect.send_config_set(config_commands)
```

**Comment by ktbyers** [comment]
Note, the above assumes that bootflash:my_config is not changing the hostname.

**Comment by adarshagowda** [comment]
The bootflash:my_config has default config, and i need to load a new config with different host name.

**Comment by ktbyers** [comment]
Okay, then

```
output = net_connect.send_command('copy bootflash:my_config running-config', delay_factor=1)
```

You might need to experiment with the delay_factor.

Note, NAPALM-ios which uses Netmiko might be a better solution for you. See https://pynet.twb-tech.com/blog/automation/napalm-ios.html
