### ISSUE TITLE
Unable to become root: ANSI code Shift-in (\x0f) after prompt: #

### ISSUE THREAD

**Issue by drod0991** [ktbyers/netmiko#2398]
Hi,

Having some issues when trying to adquire sudo priviledges on a Linux host. 
Issue: *: Router prompt not found: \'\x1b[XXXXXXXXX:/home/xxxxxxxx#\x0f\'*

From the session log file:
```
XXXXXXXX$ sudo -s

ESC[1mXXXXXXXX:/home/xxxxxx#SI
ESC[1mXXXXXXXX:/home/xxxxxx#SI
...
```

The config I am using:
```
        server = {
            "device_type": "linux",
            "host": ip_address,
            "username": username,
            "password": password,
            "secret": password,
            "session_log": netmiko_session_log,
        }
        try:
            conn = ConnectHandler(**server)
            is_sudo = conn.check_enable_mode(check_string="#")
            if not is_sudo:
                conn.enable()
            ...
```
Target host: Linux: SUSE Linux Enterprise Server 15 SP2 x86_64 (64-bit) (VM)
netmiko             3.4.0

Let me know if further info is required.
Any help on this is really aprpreciated.

Thanks

**Comment by ktbyers** [comment]
Okay, fix is here:

https://github.com/ktbyers/netmiko/pull/2420

Note, the `develop` branch is Netmiko 4.x code which has backwards incompatible changes so make sure you test properly in your environment before using it.
