### ISSUE TITLE
Aruba OS issues with "/"

### ISSUE THREAD

**Issue by DonKawamura66** [ktbyers/netmiko#2414]
### Discussed in https://github.com/ktbyers/netmiko/discussions/2413

<div type='discussions-op-text'>

<sup>Originally posted by **DonKawamura66** July 22, 2021</sup>
Hi All,

I hope this is the good place for this, otherwise my apologies
 
all of a sudden I am getting issues when I'm using the "/" in my send_config_set() for netmiko

Below the code I'm using:

```PYTHON
from netmiko import ConnectHandler # netmiko is the framework we use to connect to devices

aruba_mm = {
    "device_type": "aruba_os",
    "host": "Branches_MM.local",
    "username": f'{userVar}',
    "password": f'{passVar}',
}

with ConnectHandler(**aruba_mm) as net_connect:
 config_commands = [f'CD "\u2215md\u2215Branches"', f'no ap-group ag-{sitecode}', 'write memory']
 output = net_connect.send_config_set(config_commands)
 print(output)
 ```

The command is successful when you don't use the "/", as you can see I tried using unicode, to no avail.

I keep getting "Timed-out reading channel, data not available."

Anyone some idea what this might be?
</div>

**Comment by DonKawamura66** [comment]
I have found the issue here. It had nothing to do with "/".
It had to do something with changing the folder on the mobility master.
The vendor module netmiko/aruba/aruba_ssh.py checks if the node is still in config mode by the following code:

` def check_config_mode(self, check_string="(config) #", pattern=""):
"""
Checks if the device is in configuration mode or not.

    Aruba uses "(<controller name>) (config) #" as config prompt
    """
    if not pattern:
        pattern = re.escape(self.base_prompt[:16])
    return super().check_config_mode(check_string=check_string, pattern=pattern)
`

The problem I had is solved in two ways:

changing the directory back to mynode as the snipped below
changing the Aruba vendor module to use less characters for the pattern (I have changed it to 14: pattern = re.escape(self.base_prompt[:14]))
Below a small snipped of the session logging:

(Branches_MM.local) [mynode] #no paging
(Branches_MM.local) [mynode] #configure term
Enter Configuration commands, one per line. End with CNTL/Z
(Branches_MM.local) [mynode] (config) #
(Branches_MM.local) [mynode] (config) #CD /md/Branches

(Branches_MM.local) [branches] (config) #write memory
Saving Configuration...
(Branches_MM.local) [branches] (config) #CD mynode
(Branches_MM.local) [mynode] #

**Comment by DonKawamura66** [comment]
Suggestion to change the vendor module pattern, can the developer check into this?

**Comment by ktbyers** [comment]
So why does Aruba keep the `(config)` prompt when you change-node to "/md/Branches", but not when you change-node to "mynode"?

At the end (when on mynode) what would you need to do make configuration changes (on mynode). What would this look like on the CLI.

Also the code you posted doesn't match your session_log can you make sure to post the code corresponding to the session_log.


Kirk

**Comment by DonKawamura66** [comment]
Hi Kirk,

The session_log has been edited since I’m not allowed posting anything related to our organization.

Aruba keeps the (config) part in both nodes. The problem with us was in the check that is done. “self.base_prompt[:16]” to see if the node is ready processing the commands that when changing the node to Branches the first 16 characters are different from when we entered config mode.

in our situation (name replaced byX)

(XXXXXXXXXXX) [m (when logging in, in mynode)
(XXXXXXXXXXX) [b (when changing to branches)

Therefor changing back to mynode solves the issue.

I do believe that it’s more of a workaround and maybe improving the check would be better.

Hope it’s more clear now.

**Comment by ktbyers** [comment]
Have you tried the Netmiko `develop` branch?

These two lines have already been removed from the `develop` branch (previously removed):

```python
# removed
if not pattern:
    pattern = re.escape(self.base_prompt[:16])
```

https://github.com/ktbyers/netmiko/blob/develop/netmiko/aruba/aruba_ssh.py#L39

Note, the `develop` branch is Netmiko 4.x so there are quite a few other changes including backwards incompatible changes (so make sure you test things in a test environment as there might be other changes that break your existing code).

**Comment by DonKawamura66** [comment]
Thanks Kirk,

we usually don’t use the develop branch, but it’s worth looking into that one. I am confident that we don’t see our specific issue anymore when seeing the new code.

We are moving from ‘own written code’ with Paramiko to Netmiko and this was one of our first experiences. 

I can mark this issue as closed, since the issue is clearly taken care of already.

**Comment by ktbyers** [comment]
Yeah, you could edit those two lines out in your copy of Netmiko. They will be gone any ways in the next version of Netmiko and that way your delta is only that one specific change you need (and none of the other Netmiko 4.x changes).


Regards Kirk
