### ISSUE TITLE
Timeout using ssh config ProxyCommand

### ISSUE THREAD

**Issue by lundybernard** [ktbyers/netmiko#242]
There is, what I would consider, a bug in the way ssh config files are used to proxy.

Normally your ssh config allows you to do this:

```
Host *
    ServerAliveInterval 5

Host *.domain
    ProxyCommand ssh -W %h:%p domain_proxy

Host my_host.domain
    HostName 10.10.10.10
```

when you ssh to my_host.domain, it will apply the ServerAliveInterval from Host *, the ProxyCommand from *.domain, and the IP address from my_Host.domain.
like so:

``` bash
> ssh -vvvv my_host.domain
OpenSSH_7.2p2 Ubuntu-4ubuntu1, OpenSSL 1.0.2g-fips  1 Mar 2016
debug1: Reading configuration data ssh_config
debug1: ssh_config line 1: Applying options for *
debug1: ssh_config line 17: Applying options for *.domain
debug1: ssh_config line 45: Applying options for my_host.domain*
debug1: Executing proxy command: exec ssh -W 10.10.10.10:22 domain_proxy
...
```

Netmiko, on the other hand, will not find the ProxyCommand under *.domain, you must set all of the options under the Host its self like so:

```
Host my_host.domain
    HostName 10.10.10.10
    ProxyCommand ssh -W %h:%p domain_proxy
    ServerAliveInterval 5
```

If you must use a proxy to connect, the first ssh config, without ProxyCommand specified under the host, will give this error:

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lbernard/miniconda3/envs/netmiko/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 84, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/lbernard/miniconda3/envs/netmiko/lib/python2.7/site-packages/netmiko/base_connection.py", line 68, in __init__
    self.establish_connection(verbose=verbose, use_keys=use_keys, key_file=key_file)
  File "/home/lbernard/miniconda3/envs/netmiko/lib/python2.7/site-packages/netmiko/base_connection.py", line 169, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios my_host.domain:22
```

**Comment by lundybernard** [comment]
Additionally, I found that I must add the host key to authorized hosts, or it fails with the same error as above.

after I connect via ssh, and add the host keys like so:
```
debug3: hostkeys_foreach: reading file "/home/lbernard/.ssh/known_hosts"
The authenticity of host '10.10.10.10 (<no hostip for proxy command>)' can't be established.
RSA key fingerprint is SHA256:#####.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.10.10.10' (RSA) to the list of known hosts.
```
I am able to connect with netmiko.ConnectHandler.

I thought that netmiko explicitly disabled host key checking, so, this may be specific to using a proxy (or two proxies in my case)

**Comment by lundybernard** [comment]
Ok, I have an explanation for the ssh config usage now.

Looking at [base_connection.py line 97](https://github.com/ktbyers/netmiko/blob/master/netmiko/base_connection.py#L97):
```python
with open(<ssh config file>) as f:
    ssh_config_instance.parse(f)
    host_specifier = "{0}:{1}".format(self.host, self.port)
    source = ssh_config_instance.lookup(host_specifier)
```
It is the port that is wrecking everything.  Using my standard SSH config:
```
Host *
    ServerAliveInterval 5

Host *.domain
    ProxyCommand ssh -W %h:%p domain_proxy

Host my_host.domain
    HostName 10.10.10.10
```
ssh_config_instance.lookup("my_host.domain:22"), only matches the Host * patern, and i only get the ServerAliveInterval property in source.
```python
>>> host_spec = "{0}:{1}".format("my_host.domain", 22)
>>> source = ssh_config_instance.lookup(host_spec)
>>> source
{'hostname': 'my_host.domain:22', 'serveraliveinterval': '5'}
```
Note, it did not get the proper IP address from HostName.

One solution is to add an inadvisable number of wildcards to my ssh config:
```
Host *
    ServerAliveInterval 5

Host *.domain*
    ProxyCommand ssh -W %h:%p domain_proxy

Host my_host.domain*
    HostName 10.10.10.10
```
This matches, and I am able to establish a connection to my_host.domain successfully!
```python
>>> source = ssh_config_instance.lookup(host_spec)
>>> source
{'hostname': '10.10.10.10', 'proxycommand': 'ssh -W 10.10.10.104:22 domain_proxy'}
```


The other, safer solution, still requires a wild-card at the end of the host name, like so:
```
Host my_host.domain*
    HostName 10.10.10.10
    ServerAliveInterval 5
    ProxyCommand ssh -W %h:%p domain_proxy
```
    
I am curious as to the reason for adding the port number to the host string, and if it is something that we could safely remove.  It came as quite a surprise to me, as I have never seen an ssh config (or guide to ssh config files that suggests) declare 'Host my_host.domain:22'

**Comment by ktbyers** [comment]
The reason the port is there is to support SSH to non-standard SSH ports using SSH proxy. Basically the problem was that the port has to be in the host entry otherwise you cannot differentiate between overlapping IP addresses that use different ports. 

We could probably do the following--put a conditional in and if the 'host' comes in as an IP address, then use the ip:port search. If it comes in as a name, then don't include the port in the SSH config search.

**Comment by lundybernard** [comment]
I think I can come up with a way to match the most specific Host record in the ssh config file.
If the port is specified look for the specific host record, otherwise fallback to the non-specific host.
Am I correct in guessing that some Hosts require different Proxies/credentials for different ports?

Can you provide a few examples of the kind of ssh config records that you are using to differentiate overlapping ports, so that I can build some test cases?

**Comment by ktbyers** [comment]
I want to be able to support overloaded IP addresses and SSH proxy. In other words, I want to be able to support the same public IP address and a port address translation to different network devices. 

For example
66.66.66.10:22          # rtr1
66.66.66.10:8022      # rtr2
66.66.66.10:8122      # rtr3

If a hostname is used and not an IP address, then the above does not need to apply. As in that case, you could differentiate on 'rtr1', 'rtr2', 'rtr3' by hostname in the SSH proxy config file.

I think this should probably provide an example (if not, just let me know):

https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

Let me know if the above all makes sense (or not).

**Comment by lundybernard** [comment]
Thanks @ktbyers
that example will work perfectly.

The only thing that's not making a lot of sense to me, is the setting the host record to <ip>:<port>, since the record already contains the IP under 'HostName', and the 'Port'.

as in your example:
```
host 10.10.10.27:9822           # Juniper SRX
  user pyclass
  hostname 10.10.10.27
  Port 9822
  ProxyCommand ssh jumphost nc %h %p
```
It feels redundant, and I have always seen ssh config files set the host record to the FQDN, or a convenient alias.  I would expect this config to look like:
```
host Juniper.SRX
  user pyclass
  hostname 10.10.10.27
  Port 9822
  ProxyCommand ssh jumphost nc %h %p
```
or some similar naming scheme.

One thing I have not explored is how ssh config interacts with records in /etc/hosts, so i'm unsure if setting host=<ip>:<port> is due to that consideration.  Is there some other commonly used application that is driving the ip:port naming scheme?

Regardless, I will try to get a pull request together to satisfy both scenarios.  I am not terribly familiar with pytest (I use unittest on my projects).  Could you direct me to an existing test file that I should add tests to, or an appropriate new file name for the tests, that will be inline with your schema?

**Comment by ktbyers** [comment]
Network engineers frequently use IP address (probably majority of the time). 

A lot of the time (most of the time) is there no corresponding DNS name nor DNS alias. You could make a strong argument it would be better to use names, but we usually don't do this.

So how do we differentiate between these two entries?

host 10.10.10.27:9822           # Juniper SRX
  user pyclass
  hostname 10.10.10.27
  Port 9822
  ProxyCommand ssh jumphost nc %h %p

host 10.10.10.27:8022           # Cisco rtr2
  user pyclass
  hostname 10.10.10.27
  Port 8022
  ProxyCommand ssh jumphost nc %h %p

Also Netmiko would then have to know the "name" of the entry in the SSH config (when there is a very good chance it doesn't have this information i.e. only has an ip address and port).

I think this is probably a case where common system practices conflict with common network engineering practices.

Will make separate comment on testing.

**Comment by ktbyers** [comment]
Here is a link to testing:

https://github.com/ktbyers/netmiko/blob/master/TESTING.md

This is pretty close to the normal tests I run (it is actually a slightly expanded version of this):

https://github.com/ktbyers/netmiko/blob/master/tests/test_suite.sh


I need to add both a Linux server driver into this and an SSH proxy specific test into this. I have a quick linux test script which I sometimes run which is as follows (not using py.test but just running some Netmiko actions):

```
#!/usr/bin/env python
from __future__ import print_function
from __future__ import unicode_literals

from netmiko import ConnectHandler
from datetime import datetime

device = {
    'device_type': 'linux',
    'host': 'some_machine.compute.amazonaws.com',
    'username': 'admin',
    'use_keys': True,
    'key_file': '/home/admin/.ssh/test_rsa',
} 

start = datetime.now()
net_connect = ConnectHandler(**device)
print()
print("Test find_prompt: ")
print(net_connect.find_prompt())

print()
print("Test enable: ")
net_connect.enable()
if not net_connect.check_enable_mode():
    raise ValueError("Not in enable mode")
print(net_connect.find_prompt())

print()
print("Exit enable: ")
net_connect.exit_enable_mode()
if net_connect.check_enable_mode():
    raise ValueError("Still in enable mode")
print(net_connect.find_prompt())

print()
print("Test config mode: ")
net_connect.config_mode()
if not net_connect.check_config_mode():
    raise ValueError("Not in config mode")
print(net_connect.find_prompt())

print()
print("Exit config mode: ")
net_connect.exit_config_mode()
if net_connect.check_config_mode():
    raise ValueError("Still in config mode")
print(net_connect.find_prompt())

print()
print("Test send_command")
print(net_connect.send_command('ls'))

print()
print("Test send_command_expect")
print(net_connect.send_command_expect('ls'))

print()
```

I am definitely happy to work through how to create the test code for this.

**Comment by ktbyers** [comment]
This was updated to the more canonical SSH config format. So it should look like this now:

```
host 10.10.10.70
  user pyclass
  hostname 10.10.10.70
  Port 22
  ProxyCommand ssh jumphost nc %h %p

host pynet-rtr1.twb-tech.com
  user pyclass
  hostname 10.10.10.70
  Port 22
  ProxyCommand ssh jumphost nc %h %p
```

**Comment by ktbyers** [comment]
https://github.com/ktbyers/netmiko/commit/24d39ce28484af0b4465f53c55e1ed0342f92c30
