### ISSUE TITLE
Copy configuration using SCP

### ISSUE THREAD

**Issue by kensaut** [ktbyers/netmiko#2421]
This isn't really an issue, but I am having a touch time copying the running configuration from Cisco IOS switch to a Windows SCP server.  I believe the password is what is giving me problems.  I tried including the password in the copy command, but when I try it on the switch, Authentication failed.  Without the password in the command, it works.  

I left out the password field in the Python script, but the Password: prompt doesn't let the script enter the password.  I am running Netmiko 3.3.3 and I am wondering if I need to use another module or library.  

Any help would be appreciated.

**Comment by ktbyers** [comment]
You would have to post your code and the CLI command you are trying to use. You can obfuscate your username/password and any other confidential information.

**Comment by kensaut** [comment]
Code one of my attempts: `# Switch information
switch = input("IP: ")
kenswitch = {
    "host": switch,
    "username": input("Username: "),
    "password": getpass(),
    "device_type": "cisco_ios",
    "secret": getpass("Secret: ")
}

# Get SCP server information
server_name = socket.gethostname()
server_ip = socket.gethostbyname(server_name)

# Make connection to switch
connection = Netmiko(**kenswitch)

print(f"Connection to {switch}.\n")

connection.enable()

scp_process = True
result = connection.send_command_timing(
    command_string=f"copy running-config scp://{kenswitch['username']}@{server_ip}/desktop/kenswitch1.txt",
    delay_factor=4,
)

print(f"Copying running-config to SCP server\nName: {server_name}\nIP: {server_ip}")

while scp_process:
    print(connection.find_prompt())
    if "Password:" in connection.find_prompt():
        connection.send_command(kenswitch["password"])
        scp_process = False`

CLI command: `copy running-config scp://user:password@x.x.x.x/file.txt`

**Comment by kensaut** [comment]
> 

> 

>

**Comment by kensaut** [comment]
My apologies for closing and reopening.

**Comment by kensaut** [comment]
I am verifying, if I capture the running-config in a variable and write it to a file with open(), that should be transferred via SSH from the router.  This is all depending if I am using "cisco-ios" as the "device_type" and making a connection with netmiko.Netmiko.

**Comment by ktbyers** [comment]
Can you show me what doing this process manually from the CLI looks like?

Also have you looked at the Netmiko session_log?



Kirk

**Comment by kensaut** [comment]
Kirk, I can't recreate SCP working on the Cisco switch, but could you confirm this?  

> I am verifying, if I capture the running-config in a variable and write it to a file with open(), that should be transferred via SSH from the router. This is all depending if I am using "cisco-ios" as the "device_type" and making a connection with netmiko.Netmiko.

**Comment by ktbyers** [comment]
Yeah, that is a lot easier than trying to transfer it via SCP i.e. just execute `show run` and save the contents to a file.

Yes, that will use SSH as long as your device_type is `cisco_ios` (i.e. Netmiko will use SSH unless you explicitly tell it to use telnet).


Regards, Kirk

**Comment by kensaut** [comment]
Thank you Kirk!
