### ISSUE TITLE
Timed-out reading channel, data not available, when using `cmd_verify=True` with `send_config_set()`

### ISSUE THREAD

**Issue by laimaretto** [ktbyers/netmiko#2429]

**Comment by ktbyers** [comment]
You are using abbreviated commands:

```
/configure port 1/1/7 descr newDescCron1236-12
```

And the network device is echoing the full canonical command (i.e. not abbreviated):

```
DEBUG:netmiko:_read_channel_expect read_data: /configure port 1/1/7 description 
DEBUG:netmiko:_read_channel_expect read_data: newDescCron1236-12 
```

You pretty much shouldn't use abbreviated commands with network automation. Use the full canonical command.

**Comment by ktbyers** [comment]
Let me know if that fix works and you are now able to use cmd_verify=True.

**Comment by laimaretto** [comment]
Hi @ktbyers , yes, indeed, using a full canonical command name solved the issue. Thank you.

If I use the complete name, Netmiko understands the pattern:

```
DEBUG:netmiko:write_channel: b'/configure port 1/1/7 description newDescCron1236-12\n'
DEBUG:netmiko:Pattern is: /configure\ port\ 1/1/7\ description\ newDescCron1236\-12
DEBUG:netmiko:_read_channel_expect read_data: # 
DEBUG:netmiko:_read_channel_expect read_data: /configure port 1/1/7 description newDescCron1236-12 

DEBUG:netmiko:Pattern found: /configure\ port\ 1/1/7\ description\ newDescCron1236\-12 # /configure port 1/1/7 description newDescCron1236-12 
```
On one hand, this is good, since we've solved the problem. On the other, me and my team are very used to work with abbreviated commands, which we still can use by using `cmd_verify=False`.
 
What's then the benefit of using `cmd_verify=True` if I still can accomplish the execution with `cmd_verify=False` (and yet it still allows me to use abbreviated commands?).

**Comment by ktbyers** [comment]
You are going to have a lot of ongoing pain if you try to use abbreviated commands with automation (especially with a platform like Nokia SR-OS that auto changes them to the canonical form when it echoes them).

You could possibly see if you can disable this behavior in SR-OS (i.e. see if SR-OS can be configured so it doesn't normalize the command when it echoes it).

Without cmd_verify=True, you will run into a lot of timing/state issues with Netmiko applying configuration changes too fast and the network device potentially unable to keep up. This will cause you to get into the pain point of trying to adjust timers (which is what we were discussing on LinkedIn).

There are other issues, you run into i.e. you won't be able to make idempotency work (as what you sent is not what shows up in the configuration--so you won't be able to check whether your configurations already exist and consequently the change is unnecessary). 

Personally, I would never use abbreviated commands for automation and I would strive to have cmd_verify=True unless I ran into problems I just couldn't work around in other ways.

**Comment by laimaretto** [comment]
Thank you very much!
