### ISSUE TITLE
Timing comparison for show commands

### ISSUE THREAD

**Issue by laimaretto** [ktbyers/netmiko#2430]
During this last time I've been doing some testing, making different kind of executions, in terms of `delay_factor`, `max_loops`, mixed together with `send_config_set()` and `send_command()`.

My conclusion is three fold:
1) `delay_factor` should be tuned to improve interaction with the network;
2) if using `config` like commands, `send_config_set()` is better; if show-like commands, `send_command()` is better;
3) if `send_config_set()`, better off use it with `cmd_verify=True`.

I've performed some tests and it is true that when dealing with only config-like commands, `send_config_set(cmd_verify=True)` is an absolute winner.

But, when dealing with show-like commands, the picture is somehow different, at least for me.

Let me show you some results:

```
26 routers;
delayFactor=1;
maxLoops=5000;
device=nokia_sros;
commands=60 different show commands;
netmiko=3.4.0
```

And these are the code I'm using:
```
inText = [showCmd1, showCmd2, .... , shwCmd60]
if runType == 'config':
	output = conn2rtr.send_config_set(config_commands=inText, 
                                            enter_config_mode=False, 
                                            cmd_verify=cmdVerify, 
                                            delay_factor=delayFactor, 
                                            max_loops=maxLoops)
elif runType == 'show':
	output = ''
	for cmd in inText:
		output = output + '\n' + cmd + '\n' + conn2rtr.send_command(cmd, 
                                                                             delay_factor=delayFactor, 
                                                                             max_loops=maxLoops)
```
The results:

   | send_config_set() | | send_command() 
-- | -- | --|--
Data | verify=no | verify=yes | verify=n/a
Count - Router | 26 | 26 | 26
 showCommands | 60 | 60 | 60
Min - rxLines | 440 | 440 | 444
Average - rxLines | 5,211.77 | 5,212.73 | 5,216.85
Max - rxLines | 14282 | 14283 | 14287
Min - time(s) | 6.74 | 12.37 | 56.71
Average - time(s) | 13.31 | 17.81 | 60.81
Max - time(s) | 23.16 | 28.74 | 71.29

so, as you can see, the better performance in my case is not obtained with `send_command()` but with `send_config_set()`.

It's just a test that I wanted to share with you. I've repeated the tests several times, and the numbers are consistent.

Is it may be because I'm concatenating the results when using `send_command()` while `send_config_set()` gives me the result directly in the `output` variable? What is it that I'm doing wrong? Because show comands should better off treated with `send_command()`, isn't it?

Regards!

Lucas

**Comment by ktbyers** [comment]
You really should be testing everything on the Netmiko `develop` branch. A lot of this code has changed substantially since Netmiko 3.4.0 and any subsequent changes will all be based on the `develop` branch.

Also, note there are performance enhancements/improvements that I still need to make to the SR-OS driver as part of the Netmiko4 (`develop`) work.

Also note, it is not surprising at all the send_config_set is faster at retrieving output as it just sends all the commands rapidly one after the other and gathers the output and doesn't care nearly as much about properly gathering the output (compared to send_command).

Also note, I won't support using send_config_set() for executing show commands...so if/when you run into issues doing this, I am just going to say "don't do that". send_config_set() is not intended for use with show commands so if it works, it is just luck.

**Comment by ktbyers** [comment]
One other thing that should greatly improve your test results for the `send_command` case, set the expect_string argument in your send_command() call. In other words, set this to some string that would be common to the prompt at the end of every show command (for example, expect_string="#" assuming SR-OS classical CLI).

By default, Netmiko will try to automatically find the prompt for every show command you execute via send_command (if you don't set expect_string). This will slow things down a lot (given what you are doing).

Let me know if you do this test, I would be interested in seeing your results.

**Comment by laimaretto** [comment]
@ktbyers , thanks for the reply. Just to make it clear, I fully understand that show commands should be used with `send_command()` while config commands with `send_config_set()`. This was just a test that called my attention because of the apparent delay when using `shows + send_command()` compared to `shows + send_config_set()`.

So, bottom line, II'll do as you suggest: 1) try the `expect_string` in the `send_command()` call; 2) Try the develop branch. I'll let you know about the results. thanks!

**Comment by laimaretto** [comment]
Hi @ktbyers. So I've repeated the test, taking into consideration your idea of using an `expect_string` inside the `send_command()` function. I've used the same scenario, in terms of routers and show commands.

```
26 routers;
delayFactor=1;
maxLoops=5000;
device=nokia_sros;
commands=60 different show commands;
netmiko=3.4.0
```
These are the results.

sendType | config | config | show | show | show | show
-- | -- | -- | -- | -- | -- | --
cmdVerify | no | yes | no | no | yes | yes
expectString | None | None | # | None | # | None
Count - Router | 26 | 26 | 26 | 26 | 26 | 26
Count - txLines | 60 | 60 | 60 | 60 | 60 | 60
Min - time | 7.72 | 14.86 | 33.98 | 57.09 | 33.06 | 56.72
Average - time | 13.91 | 21.12 | 39.16 | 62.77 | 38.08 | 62.06
Max - time | 23.29 | 30.92 | 50.38 | 75.05 | 48.71 | 74.20
Min - rxLines | 439.00 | 440.00 | 444.00 | 444.00 | 444.00 | 444.00
Average - rxLines | 5,211.73 | 5,212.69 | 5,213.96 | 5,216.85 | 5,213.81 | 5,216.85
Max - rxLines | 14,282.00 | 14,283.00 | 14,287.00 | 14,287.00 | 14,287.00 | 14,287.00

So yes, the use of the `expect_string=#` does improve the timing for `show_command()` by a factor of 2/3 with respect to not using `expect_string`. But it is still somehow slower than using `send_config_set()` for the same purpose. Nevertheless nothing that we cannot live with ... :-) 

If you want, I'm open to do some more testing ...

Regards!

Lucas

**Comment by ktbyers** [comment]
Okay, your numbers seem reasonably (i.e. make sense to me given how Netmiko works).

With the obvious caveat that I expect send_config_set() to generally not work and to not behave correctly for most show command operations (i.e. most people would run into issues using it).
