### ISSUE TITLE
What platform should be used for asking questions, etc. about Netmiko

### ISSUE THREAD

**Issue by TimothyBramlett** [ktbyers/netmiko#244]
I didn't see it in the documentation, specifically `README.md`, so I thought I would ask what forum should be used for asking questions and discussing Netmiko?

**Comment by ktbyers** [comment]
@TimothyBramlett Not sure I understood your question? 

From the readme, here are the supported platforms (and their status):

Supports:

Regularly tested

Arista vEOS
Cisco ASA
Cisco IOS
Cisco IOS-XE
Cisco IOS-XR
HP Comware7
HP ProCurve
Juniper Junos

Limited testing

Avaya ERS
Avaya VSP
Brocade VDX
Brocade ICX/FastIron
Brocade MLX/NetIron
Cisco NX-OS
Cisco WLC
Dell-Force10 DNOS9
Huawei
Linux
Palo Alto PAN-OS

Experimental

A10
F5 LTM
Enterasys
Extreme
Fortinet
Alcatel-Lucent SR-OS

**Comment by ktbyers** [comment]
There is a Netmiko channel inside of there.

**Comment by TimothyBramlett** [comment]
Got!  That is what I was asking.  Let me know if you would like to me to add that info to the README.  I am trying to find more opensource projects to contribute to.
