### ISSUE TITLE
Lack of support for multi-hop proxyCommand

### ISSUE THREAD

**Issue by mohsen1565** [ktbyers/netmiko#2444]
Hi
We are running a network which consists of different parts and each part has got a dedicated jump host for accessing devices. One section of the network, specifically, is only accessible via two nested jumhosts (jhostA, jHostB).
I am using netmiko with the following ssh command file for that part of the network but it doesn't  seem to be able to establish the connection:

```
Host * !jhostA !jHostB
    StrictHostKeyChecking no
    KexAlgorithms +diffie-hellman-group1-sha1
    KexAlgorithms +diffie-hellman-group-exchange-sha1
    Ciphers 3des-cbc,aes128-ctr
    HostKeyAlgorithms +ssh-dss
    ControlMaster auto
    ControlPath ~/.ssh/sock-%r@%h:%p
    ControlPersist 30m
    ProxyCommand ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q -i ~/.ssh/id_rsa %r@jHostB
Host jHostB
    StrictHostKeyChecking no
    KexAlgorithms +diffie-hellman-group1-sha1
    KexAlgorithms +diffie-hellman-group-exchange-sha1
    Ciphers 3des-cbc,aes128-ctr
    IdentityFile ~/.ssh/id_rsa
    HostKeyAlgorithms +ssh-dss
    ControlMaster auto
    ControlPath ~/.ssh/sock-%r@%h:%p
    ControlPersist 30m
    ProxyCommand ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q -i ~/.ssh/id_rsa %r@jhostA
Host jhostA
    StrictHostKeyChecking no
    KexAlgorithms +diffie-hellman-group1-sha1
    KexAlgorithms +diffie-hellman-group-exchange-sha1
    Ciphers 3des-cbc,aes128-ctr
    IdentityFile ~/.ssh/id_rsa
    HostKeyAlgorithms +ssh-dss
    ControlMaster auto
    ControlPath ~/.ssh/sock-%r@%h:%p
    ControlPersist 30m
```

however when I find the following code, it just hangs:

```
from netmiko import ConnectHandler
device = {
    'device_type': 'cisco_xr',
    'host': 'hostC',
    'username': 'my_user',
    'password': 'my_password',
    'ssh_config_file': '/home/my_user/.ssh/config',
} 

net_connect = ConnectHandler(**device)
output = net_connect.send_command('show version')
```

what's the best way to handle this.
also if we try to cover more networks in the same ssh config file, it will fail again because each network has it's own jumphost **which is not even a part of the host's FQDN** (i.e. "networkA_device.networkA_jumphost" cannot be resolved via DNS) so we have to make entries like this in the config file to establish the connection (This setting works in linux ssh but fails with Netmiko):

```
Host networkA_jumphost
    StrictHostKeyChecking no
    KexAlgorithms +diffie-hellman-group1-sha1
    KexAlgorithms +diffie-hellman-group-exchange-sha1
    Ciphers 3des-cbc,aes128-ctr
    IdentityFile ~/.ssh/id_rsa
    HostKeyAlgorithms +ssh-dss
Host *,networkA_jumphost
    StrictHostKeyChecking no
    KexAlgorithms +diffie-hellman-group1-sha1
    KexAlgorithms +diffie-hellman-group-exchange-sha1
    Ciphers 3des-cbc,aes128-ctr
    ProxyCommand ssh -W $(echo %h | cut -d , -f1):%p %r@networkA_jumphost
    HostKeyAlgorithms +ssh-dss
```
The above config file enables the ssh connection when we run the following in Linux command line but fails if we attempt to connect to the device via Netmiko:
ssh my_username@networkA_device,networkA_jumphost

Could you please advise what the best solution is to tackle such problems?

**Comment by ktbyers** [comment]
@mohsen1565 Have you tried `ProxyJump` (IIRC, we support bouncing via two jumphosts using ProxyJump).

Note, Netmiko only processes a very small amount of information in the `ssh_config` file i.e. Netmiko itself will ignore all of these items:

```
   StrictHostKeyChecking no
    KexAlgorithms +diffie-hellman-group1-sha1
    KexAlgorithms +diffie-hellman-group-exchange-sha1
    Ciphers 3des-cbc,aes128-ctr
    HostKeyAlgorithms +ssh-dss
```

**Comment by ktbyers** [comment]
Ooops, I just checked the source code:

```
       "ProxyJump with more than one proxy server is not supported."
```

So multiple SSH proxy servers is not supported.

The only way I know how to do it would be to use a Netmiko connection and then bounce step-by-step through each one of them to the end device (i.e. start out with the `linux` device_type and bounce through devices).

Once you reached the end device you would need to execute `redispatch`

**Comment by mohsen1565** [comment]
@ktbyers 
Thanks Kirk. Im actually enriching your package so that it accepts jumpHost="host1,host2,host3,..." and then builds a tempprary file with the necessary ProxyCommands to acheive that connection and attach that config file to the device dictionary. It's looking promissing. Would you be open to add that to your package as a contribution, once ive finished it?

**Comment by ktbyers** [comment]
@mohsen1565 Can you explain at a high-level how your are thinking of solving this problem? 

Note, Paramiko upon which Netmiko is based does not support multiple ProxyJump hosts (though there was a link to the main developer implementing it in Fabric in some way.

**Comment by mohsen1565** [comment]
@ktbyers 
Sure. Consider the following setup:

localHost-->host1.mycompany.com-->host2.mycompany.com-->host3.mycompany.com-->myHost

 Now, assume that we add two more arguments to your device dict to account for the jumpHosts along the way:

`
device = {
    'device_type': 'cisco_xr',
    'host': 'myHost',
    'username': 'myUser',
    'password': 'myPassword',
    'jHost' : 'host1.mycompany.com,host2.mycompany.com,host3.mycompany.com',
    'jHostKeyFile' : '/path/to/jumphost/SSH/key'
} 
`
then we pass this new dictionary to a new function which is basically a wrapper around your "ConnectHandler":

`
ssh = ConnectHandlerWrapper(**device)
`
What this does is it creates a NamedTemporaryFile objects with the SSH configuration for the connection based on the specified  "jHost" and "jHostKeyFile" values written to it ("jHostKeyFile" is in case the user wants to specify a custom SSH key for the jumphosts along the way).
The generated file will have a format like below:

`
    Host *  !host3.mycompany.com !host2.mycompany.com !host1.mycompany.com
        StrictHostKeyChecking no
        KexAlgorithms +diffie-hellman-group1-sha1
        KexAlgorithms +diffie-hellman-group-exchange-sha1
        Ciphers 3des-cbc,aes128-ctr
        IdentityFile /path/to/jumphost/SSH/key
        HostKeyAlgorithms +ssh-dss
        ProxyCommand ssh -F /tmp/tmpmadsq9v5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q myUser@host3.mycompany.com
    

    Host host3.mycompany.com
        StrictHostKeyChecking no
        KexAlgorithms +diffie-hellman-group1-sha1
        KexAlgorithms +diffie-hellman-group-exchange-sha1
        Ciphers 3des-cbc,aes128-ctr
        IdentityFile /path/to/jumphost/SSH/key
        HostKeyAlgorithms +ssh-dss
        ProxyCommand ssh -F /tmp/tmpmadsq9v5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q myUser@host2.mycompany.com
    

    Host host2.mycompany.com
        StrictHostKeyChecking no
        KexAlgorithms +diffie-hellman-group1-sha1
        KexAlgorithms +diffie-hellman-group-exchange-sha1
        Ciphers 3des-cbc,aes128-ctr
        IdentityFile /path/to/jumphost/SSH/key
        HostKeyAlgorithms +ssh-dss
        ProxyCommand ssh -F /tmp/tmpmadsq9v5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q myUser@host1.mycompany.com
    

    Host host1.mycompany.com
        StrictHostKeyChecking no
        KexAlgorithms +diffie-hellman-group1-sha1
        KexAlgorithms +diffie-hellman-group-exchange-sha1
        Ciphers 3des-cbc,aes128-ctr
        IdentityFile /path/to/jumphost/SSH/key
        HostKeyAlgorithms +ssh-dss
`
Here, "/tmp/tmpmadsq9v5" is the path to the NamedTemporaryFile , created in the memory, on the fly . Then the wrapper will remove  "jHost" and "jHostKeyFile" keys off the device dict and append a "ssh_config_file" key to it instead, pointing to the temporary file:

`
device = {
    'device_type': 'cisco_xr',
    'host': 'myHost',
    'username': 'myUser',
    'password': 'myPassword',
    'ssh_config_file' : '/tmp/tmpmadsq9v5'
} 
`
The rest of the wrapper function works basically like native Netmiko. It will create a connection object out of the new device dict and return it:

`
def ConnectHandlerWrapper(**kargs):
    #create new device dict
    ...
    ssh = ConnectHandler(**device)  
    return ssh
`

The key point here is the function which generate the dynamic config file. It follows an algorithm enabling it to handle however many hosts along the way. I have coded and tested this design and it works error-free for up to 2 jumphosts so far.
Please let me know what your thoughts are.

**Comment by mohsen1565** [comment]
So would you be open to this solution as a contribution? I've finished coding all the necessary functions. Happy to share.

**Comment by ktbyers** [comment]
@mohsen1565 I am going to pass on adding this to Netmiko.

Needing to bounce through multiple SSH proxy servers is really a rare edge case and their is an existing solution (albeit a bit unpleasant).

I think the above would be very hard to maintain and support across time.

Thanks for the proposal, however.

Regards, Kirk
