### ISSUE TITLE
cmd_verify failing on send_command on very long command in f5_linux

### ISSUE THREAD

**Issue by reddyarun474** [ktbyers/netmiko#2445]
```
import logging
import netmiko

logging.basicConfig(filename='bigip.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

def log_msg(lvl, msg):
    """
    :param lvl:
    :param msg:
    :return:
    """
    global LOGGER
    if LOGGER:
        LOGGER.log(lvl, msg)
    else:
        print(msg)

def device_connection(**kwargs):
    """
    Connect to device using netmiko
    :type kwargs: dict
    """
    if 'key_file' in kwargs:
        device_password = {
            'use_keys': True,
            'key_file': kwargs['key_file']
        }
    else:
        device_password = {
            'password': kwargs['password']
        }
    device = {
        'device_type': kwargs['device_type'],
        'host': kwargs['ip'],
        'username': kwargs['username'],
        'port': kwargs['port'],
        'blocking_timeout': kwargs.get('blocking_timeout', 20),
        'keepalive': kwargs.get('keepalive', 1),
        'session_log': 'bigip.log'
    }
    device.update(device_password)
    try:
        handl = netmiko.ConnectHandler(**device)
        return handl
    except netmiko.ssh_exception.NetMikoTimeoutException as err1:
        log_msg(logging.WARNING, "Timeout({}): {}".format(kwargs['ip'], err1))
        raise DeviceConnectionTimeout(err1)
    except netmiko.ssh_exception.NetMikoAuthenticationException as err2:
        raise DeviceAuthenticationFailure(err2)
    except Exception as err3:
        log_msg(logging.WARNING,
                "Exception({}): {}".format(kwargs['ip'], err3))
        raise err3

if __name__ == "__main__":
    device_data = {
            'device_type': 'f5_linux',
            'ip': 'xxxxxxxx',
            'username': 'xxxx',
            'password': 'xxxxxxx',
            'port': 22
            }
    handle = device_connection(**device_data)
    cmd = 'tmsh create net ipsec ike-peer dgtbptxhnfvt app-service none ca-cert-file none crl-file none description none dpd-delay 30 generate-policy off lifetime 1440 mode main my-cert-file none my-cert-key-file none my-cert-key-passphrase none my-id-type address my-id-value 15.1.1.1 nat-traversal off passive false peers-cert-file none peers-cert-type none peers-id-type address peers-id-value 15.1.1.10 phase1-auth-method pre-shared-key phase1-encrypt-algorithm aes256 phase1-hash-algorithm sha256 phase1-perfect-forward-secrecy modp1024 preshared-key-encrypted test@123 prf sha256 proxy-support enabled remote-address 15.1.1.10 replay-window-size 64 state enabled traffic-selector replace-all-with { /Common/xhgynrlwyzvk} verify-cert true version replace-all-with { v2 }'
    expect_prompt = r"(root@.*#|\s*|[#|\$]\s*$)"
    handle.send_command_expect(cmd, expect_string=expect_prompt)

```
Trace:
=====
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "access.py", line 144, in <module>
    handle.send_command_expect(cmd, expect_string=expect_prompt)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1582, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1496, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Debug log:**
Netmiko Version: 3.4.0
[root@localhost:Active:Standalone] config #
[root@localhost:Active:Standalone] config #
[root@localhost:Active:Standalone] config #
[root@localhost:Active:Standalone] config # tmsh create net ipsec ike-peer dgtbptxhnfvt app-service none ca-cert-file none crl-file none description none dpd-delay 30 generate-policy off lifetime 1440 mode main my-cert-file none my-cert-key-file none my-cert-key-passphrase none my-id-type address my-id-value 15.1.1.1 nat-traversal off passive false peers-cert-file none peers-cert-type none peers-id-type address peers-id-value 15.1.1.10 phase1-auth-method pre-shared-key phase1-encrypt-algorithm aes256 phase
1-hash-algorithm sha256 phase1-perfect-forward-secrecy modp1024 preshared-key-encrypted ipsec@123 prf sha256 proxy-support enabled remote-address 15.1.1.10 replay-window-size 64 state enabled traffic-selector replace-all-with { /Common/xhgynrlwyzvk} verify-cert true version replace-all-with { v2 }
01070734:3: Configuration error: Traffic Selector /Common/xhgynrlwyzvk does not exist.
[root@localhost:Active:Standalone] config # amiko.transport:Cipher agreed: aes128-ctr
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
[root@localhost:Active:Standalone] config #
DEBUG:netmiko:read_channel:
[root@localhost:Active:Standalone] config #

DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: [root@localhost:Active:Standalone] config #
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is [root@localhost:Active:Standalone] config #
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'tmsh create net ipsec ike-peer dgtbptxhnfvt app-service none ca-cert-file none crl-file none description none dpd-delay 30 generate-policy off lifetime 1440 mode main my-cert-file none my-cert-key-file none my-cert-key-passphrase none my-id-type address my-id-value 15.1.1.1 nat-traversal off passive false peers-cert-file none peers-cert-type none peers-id-type address peers-id-value 15.1.1.10 phase1-auth-method pre-shared-key phase1-encrypt-algorithm aes256 phase1-hash-algorithm sha256 phase1-perfect-forward-secrecy modp1024 preshared-key-encrypted ipsec@123 prf sha256 proxy-support enabled remote-address 15.1.1.10 replay-window-size 64 state enabled traffic-selector replace-all-with { /Common/xhgynrlwyzvk} verify-cert true version replace-all-with { v2 }\n'
DEBUG:netmiko:Pattern is: tmsh\ create\ net\ ipsec\ ike\-peer\ dgtbptxhnfvt\ app\-service\ none\ ca\-cert\-file\ none\ crl\-file\ none\ description\ none\ dpd\-delay\ 30\ generate\-policy\ off\ lifetime\ 1440\ mode\ main\ my\-cert\-file\ none\ my\-cert\-key\-file\ none\ my\-cert\-key\-passphrase\ none\ my\-id\-type\ address\ my\-id\-value\ 15\.1\.1\.1\ nat\-traversal\ off\ passive\ false\ peers\-cert\-file\ none\ peers\-cert\-type\ none\ peers\-id\-type\ address\ peers\-id\-value\ 15\.1\.1\.10\ phase1\-auth\-method\ pre\-shared\-key\ phase1\-encrypt\-algorithm\ aes256\ phase1\-hash\-algorithm\ sha256\ phase1\-perfect\-forward\-secrecy\ modp1024\ preshared\-key\-encrypted\ ipsec@123\ prf\ sha256\ proxy\-support\ enabled\ remote\-address\ 15\.1\.1\.10\ replay\-window\-size\ 64\ state\ enabled\ traffic\-selector\ replace\-all\-with\ \{\ /Common/xhgynrlwyzvk\}\ verify\-cert\ true\ version\ replace\-all\-with\ \{\ v2\ \}
DEBUG:netmiko:_read_channel_expect read_data: tmsh create net ipsec ike-peer dgtbptxhnfvt app-service none ca-cert-file none crl-file none description none dpd-delay 30 generate-policy off lifetime 1440 mode main my-cert-file none my-cert-key-file
DEBUG:netmiko:_read_channel_expect read_data: none my-cert-key-passphrase none my-id-type address my-id-value 15.1.1.1 nat-traversal off passive false peers-cert-file none peers-cert-type none peers-id-type address peers-id-value 15.1.1.10 phase1-aut
DEBUG:netmiko:_read_channel_expect read_data: h
1-hash-algorithm sha256 phase1-perfect-forward-secrecy modp1024 preshared-key-encrypted ipsec@123 prf sha256 proxy-support enabled remote-address 15.1.1.10 replay-window-size 64 state enabled traffic-selector replace-all-with { /Common/xhgynrlwyzvk} verify-cert true version replace-all-with { v2 }

DEBUG:netmiko:_read_channel_expect read_data: 01070734:3: Configuration error: Traffic Selector /Common/xhgynrlwyzvk does not exist.

DEBUG:netmiko:_read_channel_expect read_data: [root@localhost:Active:Standalone] config #
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"

**Comment by ktbyers** [comment]
Please format your Python code so that it displays properly in Github markdown.

**Comment by ktbyers** [comment]
I would try setting cmd_verify=False as an argument to send_command_expect

```
 handle.send_command_expect(cmd, expect_string=expect_prompt, cmd_verify=False)
```

**Comment by reddyarun474** [comment]
It is working fine. Thanks for your support
