### ISSUE TITLE
Netmiko 1.0 Release

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#245]
I have made a new branch on github called dev_1_0 and I would like to implement some of the following:

1. implement telnet driver and potentially serial driver by abstracting the underlying protocol from the higher level methods that interface with the protocol.
2. Make send_command_expect be send_command (and rename current send_command to send_command_timing) and work out issues associated with this.
3. Improve current timing problems with Netmiko. Still run into recurring issues with timing based Netmiko failures.
     a. Rationalize the use of delay_factor so that it defaults to one and is more consistently used.
4. Improve automated testing. Add tests that are missing. See if we can get more vendor devices to test against somehow.
5. Possibly other things depending on what people are interested in.

**Comment by ktbyers** [comment]
If anyone wants to help on this, let me know.

**Comment by LindsayHill** [comment]
Sounds good. Happy to help with running tests against as many Brocade devices as I can get my hands on. Interested in item 3 in particular.

**Comment by ktbyers** [comment]
@LindsayHill I think it would be good for item3 to figure out a way to introduce latency (somehow) into the automated testing (too hopefully make Netmiko less fragile to high-latency/slow response situations).

**Comment by samulord** [comment]
Happy to help @ktbyers , specifically on item number #4, I can get a hand on some SMB/Cellular devices if the idea is to grow the list of supported devices.

Anyways, let me know how I can help further.

**Comment by ktbyers** [comment]
@samulord Always open to more drivers, but I need other people to contribute them. You can see this doc for how to contribute new vendor support.

https://github.com/ktbyers/netmiko/blob/master/VENDOR.md

**Comment by ktbyers** [comment]
I have done the following on Netmiko_1_0:

1. Implemented telnet driver for Cisco IOS. Including abstracting the Netmiko general read/write methods to support both telnet and SSH.
2. Standardized delay_factor such that it almost always defaults to 1.0 so it is a true multiplier. Made sure that all sleeps depend on global_delay_factor (generally the greater of delay_factor or global_delay_factor if the specific method implements a delay_factor). Ensured send_command_expect used delay_factor.
3. Renamed send_command to be send_command_expect; renamed old send_command to be send_command_timing.
4. Implemented an SCP get method for scp_handler.
5. Added a driver for Cisco S300 series devices.
6. Improved unit tests (added unit tests for Linux, SCP operations, S300 devices).

I am probably going to release Netmiko 1_0 next week as I want to release it prior to NAPALM hackathon. Please test the dev_1_0 branch if you have time. Let me know if you see issues.

**Comment by normalboy09** [comment]
At first, thank you for your telnet driver. But iam new to github.com. Would you mind telling me how to use it please ?
Iam using SSH by the command 
>>> device = ConnectHandler(device_type='cisco_ios', ip="192.168.100.100", usern
ame="admin", password="admin")
 
What have i to do now ? Thank you very much again

**Comment by ktbyers** [comment]
@normalboy09 How to use the telnet driver?

Make the 
```
device_type = 'cisco_ios_telnet'
```

**Comment by ktbyers** [comment]
This release is done.
