### ISSUE TITLE
send_config_set() should cmd_verify auto disable if there is a newline embedded in the commands

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#2451]

**Comment by luweijun1992** [comment]
> _No description provided._

I feel that I have encountered the same problem. When there are 2 or more commands executed from a send_config_set, there will be a timeout error .

I want to know what "cmd_verify" does .

![image](https://user-images.githubusercontent.com/58923704/132537374-a85b0c99-b1d7-4e46-9d3a-66ebca8d36de.png)
```
commands = '''
display version
display device
'''
with ConnectHandler(**s57) as connect:
    print('Login Success: ' + s57['host'])
    connect.send_config_set(commands)
```

**Comment by ktbyers** [comment]
Yeah, I would say don't do this:

```python
commands = '''
display version
display device
'''
with ConnectHandler(**s57) as connect:
    print('Login Success: ' + s57['host'])
    connect.send_config_set(commands)
```

You are basically trying to cram show commands into a method designed for configuration and are running into side effects of it not working. And you have a second anti-pattern here which is instead of making a list of commands, you make a string of multiple commands with embedded newlines.

But to directly answer your question--cmd_verify verfies that the command you sent is properly echoed back before moving on. So if you were sending a single command like `display version`, then Netmiko would make sure that `display version` was echoed before moving on (with send_command() moving on would be reading the actual output; with send_config_set() moving on would be executing the next configuration command).

**Comment by luweijun1992** [comment]
> display

I only use the show command for testing. It is actually a configuration command. I want to test why two or more commands cause timeout.
![image](https://user-images.githubusercontent.com/58923704/132541765-fe7ade6e-0838-40e7-b17c-b546963c68c5.png)
![image](https://user-images.githubusercontent.com/58923704/132541845-55463fe4-d954-49f4-af11-877ce1fdb605.png)

When I add `cmd_verify=False`, it will be normal.
![image](https://user-images.githubusercontent.com/58923704/132542093-e2195e4a-0593-4ce4-9ca1-780165ef5fb6.png)
![image](https://user-images.githubusercontent.com/58923704/132542127-80f8f9b3-af23-441d-b9e9-752d1b2715dd.png)

**Comment by ktbyers** [comment]
Can you show me what `interface_configs` is defined as in your Python code?

**Comment by ktbyers** [comment]
FYI, when you see that `re.escape(cmd.strip())` in the exception stack trace that means it is failing cmd_verify.

**Comment by luweijun1992** [comment]
> Can you show me what `interface_configs` is defined as in your Python code?

as follows:
[interface_configs.txt](https://github.com/ktbyers/netmiko/files/7130290/interface_configs.txt)
![image](https://user-images.githubusercontent.com/58923704/132545330-b696748b-9341-4bdb-9a9f-3e0fd2c2fd01.png)

**Comment by ktbyers** [comment]
Try converting it into a list so do a `splitlines()` on it before sending it to send_config_set().

Let me know if that works or not.

**Comment by luweijun1992** [comment]
> Try converting it into a list so do a `splitlines()` on it before sending it to send_config_set().
> 
> Let me know if that works or not.

![image](https://user-images.githubusercontent.com/58923704/132546872-39d9d61f-db00-428d-b63d-0616e43ebc80.png)

When confirmation is required, it cannot be executed.
![image](https://user-images.githubusercontent.com/58923704/132547036-fe5761ed-97e7-485e-9065-5797a8b694ef.png)

**Comment by luweijun1992** [comment]
> Try converting it into a list so do a `splitlines()` on it before sending it to send_config_set().
> 
> Let me know if that works or not.

I delete the operation that needs to be confirmed in the command, and it can be executed normally.
![image](https://user-images.githubusercontent.com/58923704/132548141-296295d2-0b56-4835-975f-03e38cfef0e6.png)

**Comment by ktbyers** [comment]
So it works as long as you get rid of the configuration commands that need to be confirmed?

Yeah, configuration commands with confirmation are a real pain...vendors should not do this (or at least give you a way to disable this behavior via the CLI).

What happens when you leave the `clear configuration this` and `y` in the send_config_set?

Probably would need to look at the Netmiko logging to see why it is failing:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by luweijun1992** [comment]
> So it works as long as you get rid of the configuration commands that need to be confirmed?
> 
> Yeah, configuration commands with confirmation are a real pain...vendors should not do this (or at least give you a way to disable this behavior via the CLI).
> 
> What happens when you leave the `clear configuration this` and `y` in the send_config_set?
> 
> Probably would need to look at the Netmiko logging to see why it is failing:
> 
> https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Yes, if there is no need to confirm in the command, adding splitlines can work normally.

The command contains commands that need to be confirmed, as I replied earlier, it cannot be executed.
![image](https://user-images.githubusercontent.com/58923704/132551098-c317510d-bf06-4eea-b1b2-0594e4c5a606.png)

**Comment by ktbyers** [comment]
Yes, so the question is why doesn't sending the "Y" in send_config_set not work? It looks to me like it should work?

But there is a good chance that the fix will be to disable cmd_verify i.e. we are back to what we started with.


Regards,

Kirk

**Comment by luweijun1992** [comment]
> Yes, so the question is why doesn't sending the "Y" in send_config_set not work? It looks to me like it should work?
> 
> But there is a good chance that the fix will be to disable cmd_verify i.e. we are back to what we started with.
> 
> Regards,
> 
> Kirk

I modified the pattern in'base_connection.py', and the test result is that the'y' can be brought into the command that needs to be confirmed and executed successfully.
But not sure if this method is the perfect solution.
![Uploading image.png…]()

**Comment by ktbyers** [comment]
I would read this as you never send the last "Y"? 

```
[HUAWEI-GigabitEthernet0/0/2]
DEBUG:netmiko:Pattern found: interface\ G0/0/2 interface G0/0/2

[HUAWEI-GigabitEthernet0/0/2]
DEBUG:netmiko:write_channel: b' clear configuration this\n'
DEBUG:netmiko:Pattern is: clear\ configuration\ this
DEBUG:netmiko:_read_channel_expect read_data:  clear 
DEBUG:netmiko:_read_channel_expect read_data: configuration this

Warning: All configurations of the interface will be cleared, and its state will be shutdown. Continue? [Y/N] :
DEBUG:netmiko:Pattern found: clear\ configuration\ this  clear configuration this

Warning: All configurations of the interface will be cleared, and its state will be shutdown. Continue? [Y/N] :
DEBUG:netmiko:Pattern is: (?:HUAWEI|#)
```

Netmiko finds the last clear configuration this, but there is no "Y" that is sent.

Please post your code (as text only not as screenshots). Also please include in this the entire configuration that you are sending.

Also please include your configuration of your `s57` device (i.e. what does this Netmiko dictionary look like). You can obscure any confidential information (but let me know which fields you modify).


We would have to look at the full log to see where the N is coming from (once again as text-only, not as a screenshot). I don't see anything in the `huawei` driver that would explain that.

Which version of Netmiko are you using?

**Comment by ktbyers** [comment]
Does cmd_verify=False fix your issue or are you still running into issues even with this?

**Comment by ktbyers** [comment]
Yeah, I wouldn't accept that fix. It is particular to your situation and to the Huawei driver (so that wouldn't be a fix that would be viable to put into the Base code).

**Comment by luweijun1992** [comment]
> I would read this as you never send the last "Y"?
> 
> ```
> [HUAWEI-GigabitEthernet0/0/2]
> DEBUG:netmiko:Pattern found: interface\ G0/0/2 interface G0/0/2
> 
> [HUAWEI-GigabitEthernet0/0/2]
> DEBUG:netmiko:write_channel: b' clear configuration this\n'
> DEBUG:netmiko:Pattern is: clear\ configuration\ this
> DEBUG:netmiko:_read_channel_expect read_data:  clear 
> DEBUG:netmiko:_read_channel_expect read_data: configuration this
> 
> Warning: All configurations of the interface will be cleared, and its state will be shutdown. Continue? [Y/N] :
> DEBUG:netmiko:Pattern found: clear\ configuration\ this  clear configuration this
> 
> Warning: All configurations of the interface will be cleared, and its state will be shutdown. Continue? [Y/N] :
> DEBUG:netmiko:Pattern is: (?:HUAWEI|#)
> ```
> 
> Netmiko finds the last clear configuration this, but there is no "Y" that is sent.
> 
> Please post your code (as text only not as screenshots). Also please include in this the entire configuration that you are sending.
> 
> Also please include your configuration of your `s57` device (i.e. what does this Netmiko dictionary look like). You can obscure any confidential information (but let me know which fields you modify).
> 
> We would have to look at the full log to see where the N is coming from (once again as text-only, not as a screenshot). I don't see anything in the `huawei` driver that would explain that.
> 
> Which version of Netmiko are you using?

The attachment is all the content involved, I will send it in a package.
[config.zip](https://github.com/ktbyers/netmiko/files/7131136/config.zip)

**Comment by luweijun1992** [comment]
> Does cmd_verify=False fix your issue or are you still running into issues even with this?

Add `cmd_verify=False`; it can be resolved and run normally.
But I still don’t quite understand the difference brought by `cmd_verify=True/False`, can I explain it in detail or have a case?

**Comment by ktbyers** [comment]
Okay, can you show me what the value of this is:

`interface_configs.splitlines()`

I.E. what is the value of that at run-time?

**Comment by ktbyers** [comment]
Okay, the code you referenced is the issue (that plus the prompting that the Huawei device is doing):

https://github.com/ktbyers/netmiko/issues/2476

Issue is above.

I will probably add a way to override/disable this behavior in send_config_set.


The general need for cmd_verify=True is that Python is a lot faster than your network device so it can easily get way ahead of the networking device and this can lead to a series of problems. For example, devices might have an input buffer for how many commands they can receive and can start dropping commands.

cmd_verify=True works around the problem of Python being too fast by not allowing the next command to be executed until the echo of the previous command has been read in.

**Comment by luweijun1992** [comment]
> `interface_configs.splitlines()`

Do you still need me to provide a valid value of `interface_configs.splitlines()`
The code I provided can run directly and output.

**Comment by luweijun1992** [comment]
> Okay, the code you referenced is the issue (that plus the prompting that the Huawei device is doing):
> 
> #2476
> 
> Issue is above.
> 
> I will probably add a way to override/disable this behavior in send_config_set.
> 
> The general need for cmd_verify=True is that Python is a lot faster than your network device so it can easily get way ahead of the networking device and this can lead to a series of problems. For example, devices might have an input buffer for how many commands they can receive and can start dropping commands.
> 
> cmd_verify=True works around the problem of Python being too fast by not allowing the next command to be executed until the echo of the previous command has been read in.

@ktbyers 
`cmd_verify=True` is to wait for the completion of the execution of the command to continue the operation.
So if I only have one `send_config_set` in the whole script but it contains multiple commands.
Does `cmd_verify=True` take effect in multiple `send_config_set` or does it take effect if there are multiple commands.
Please see the following two ways:
---
```
vlans = """
vlan 10
vlan 20
vlan 30
"""
connect.send_config_set(vlans)
```
---
```
connect.send_config_set('vlan 10')
connect.send_config_set('vlan 20')
connect.send_config_set('vlan 30')
```
---

**Comment by ktbyers** [comment]
You should never do this and I will tell you it is not valid and not to do it.

```python
vlans = """
vlan 10
vlan 20
vlan 30
"""
connect.send_config_set(vlans)
```

You should either send a single configuration command or a list of configuration commands:

```python
vlans = ["vlan 10", "vlan 20", "vlan30"]
connect.send_config_set(vlans)
```

cmd_verify = True verifies the echo of each and every configuration command.

**Comment by luweijun1992** [comment]
> You should never do this and I will tell you it is not valid (i.e. overloading multiple configuration commands as a single string with newlines).
> 
> ```python
> vlans = """
> vlan 10
> vlan 20
> vlan 30
> """
> connect.send_config_set(vlans)
> ```
> 
> You should either send a single configuration command or a list of configuration commands:
> 
> ```python
> vlans = ["vlan 10", "vlan 20", "vlan30"]
> connect.send_config_set(vlans)
> ```
> 
> cmd_verify = True verifies the echo of each and every configuration command.

@ktbyers 
Thank you for your reminder. After I format the command into a list, `splitlines()` . It can execute normal and end python.
But there is a problem that the configuration that needs to be confirmed operation cannot be executed.
---
The aforementioned Huawei device has an `N` operation. Could you please confirm what that function is?

**Comment by luweijun1992** [comment]
@ktbyers 
Can you tell me why the `N` of Huawei equipment is used.

**Comment by ktbyers** [comment]
I need the full log output for where the N shows up. Can you include that. The earlier debug log you sent me doesn't have this "N" (as far as I can tell).

I will also need the corresponding Python code that goes with the debug capture.

Please simplify your code to the smallest base case where you can demonstrate/show the problem.


Kirk

**Comment by luweijun1992** [comment]
> I need the full log output for where the N shows up. Can you include that. The earlier debug log you sent me doesn't have this "N" (as far as I can tell).
> 
> I will also need the corresponding Python code that goes with the debug capture.
> 
> Please simplify your code to the smallest base case where you can demonstrate/show the problem.
> 
> Kirk

@ktbyers 
It looks like it should be line 53,54 in the debug file.
[huawei.zip](https://github.com/ktbyers/netmiko/files/7146828/huawei.zip)

**Comment by ktbyers** [comment]
@luweijun1992 Okay, there is a bug here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/huawei/huawei.py#L114

Basically Netmiko is sending the "N" regardless of whether the change password prompt is present or not.

I will try to fix this in the develop branch shortly.

**Comment by luweijun1992** [comment]
> @luweijun1992 Okay, there is a bug here:
> 
> https://github.com/ktbyers/netmiko/blob/develop/netmiko/huawei/huawei.py#L114
> 
> Basically Netmiko is sending the "N" regardless of whether the change password prompt is present or not.
> 
> I will try to fix this in the develop branch shortly.

@ktbyers 
okay, thank you.
I want to know what you said in your #2476 post about `send_multiline` does the current version support it.

**Comment by ktbyers** [comment]
`send_multiline` and `send_multiline_timing` are in the `develop` branch (Netmiko 4 code).

Examples are here:

https://github.com/twin-bridges/netmiko_course/tree/master/bonus/collateral

**Comment by luweijun1992** [comment]
> Examples are here:

Ok, thank you. Looking forward to the new version release.

**Comment by ktbyers** [comment]
The `N` issue should be fixed in the Huawei driver. 

A separate issue was created to track the send_config_set() prompting issue.

So I am going to go ahead and close this issue.
