### ISSUE TITLE
scp_handler.py - Intermittent issue when verifying md5 checksum

### ISSUE THREAD

**Issue by johngriegerjr** [ktbyers/netmiko#2452]
Hello,

When calling verify_file() to compare the md5 checksum of an image on a Cisco router I am intermittently getting the error below. When changing line 356 of scp_handler.py from `dest_md5 = self.ssh_ctl_chan.send_command(remote_md5_cmd, max_loops=1500)` to `dest_md5 = self.ssh_ctl_chan.send_command_timing(remote_md5_cmd, max_loops=1500)` the issue goes away. Is there any chance this change can be made to the repository or do you know of another way to fix this? Seems like the verify command is taking too long sometimes causing netmiko to not find the prompt when using the send_command and send_command_timing fixes it.

`  File "C:\Users\john\PycharmProjects\ios_upgrade\venv\lib\site-packages\netmiko\scp_handler.py", line 382, in verify_file
    return self.compare_md5()`

`  File "C:\Users\john\PycharmProjects\ios_upgrade\venv\lib\site-packages\netmiko\scp_handler.py", line 339, in compare_md5
    remote_md5 = self.remote_md5()`

`  File "C:\Users\john\PycharmProjects\ios_upgrade\venv\lib\site-packages\netmiko\scp_handler.py", line 356, in remote_md5
    dest_md5 = self.ssh_ctl_chan.send_command(remote_md5_cmd, max_loops=1500)`

`  File "C:\Users\john\PycharmProjects\ios_upgrade\venv\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)`

`  File "C:\Users\john\PycharmProjects\ios_upgrade\venv\lib\site-packages\netmiko\base_connection.py", line 1535, in send_command`

`    raise IOError(
OSError: Search pattern never detected in send_command: JKGHO\-MDF001\-RTR001\#`

Thank you,
John

**Comment by ktbyers** [comment]
@johngriegerjr So this has changed a lot in the Netmiko `develop` branch already.

Could you test it out and see if it works using that?

```
        remote_md5_cmd = f"{base_cmd} {self.file_system}/{remote_file}"
        dest_md5 = self.ssh_ctl_chan._send_command_str(remote_md5_cmd, read_timeout=300)
        dest_md5 = self.process_md5(dest_md5)
```

So this will allow it 300 seconds for the remote_md5 to complete.

We should probably figure out a way that this could be adjusted via arguments...I will create an issue in Netmiko on that.

**Comment by johngriegerjr** [comment]
@ktbyers I installed the `develop` branch and tested transferring & validating the image. It worked 5 times in a row which is much better than when it was failing intermittently. I'd say the issue it is fixed for now but agree it would be nice to be pass an argument to change the timeout. Thanks for your help.

**Comment by skabdullatief** [comment]
@johngriegerjr Will you be able to share the script, I am able to scp but for MD5 I am getting error.

**Comment by skabdullatief** [comment]
Yes, I have installed Netmiko develop branch. Here is my script not sure where I am missing. 

Script #
from netmiko import  ConnectHandler,file_transfer,progress_bar
from os.path import  getsize
import getpass

credentials = {
    "device_type" : "cisco_ios",
    "username" : "cisco",
    "password" : "cisco",
    "ip" : "192.168.2.12",
    "port" : 22,
    "session_log": "session_log.log",
}
net_connect = ConnectHandler(**credentials)
base_cmd = 'verify /md5'
remote_file = "c2960-lanbasek9-mz.150-2.SE11.bin"
flash = "flash:"
remote_md5_cmd = f"{ base_cmd } {net_connect.flash}/{remote_file}"
dest_md5 = net_connect.ssh_ctl_chan._send_command_str(remote_md5_cmd, read_timeout=300,conn_timeout = 180)
dest_md5 = net_connect.process_md5(dest_md5)
net_connect.disconnect()

Traceback#
Traceback (most recent call last):
  File "c:\Users\pwfmpe\Desktop\Python Directory\Scripts\Md5 Checksum.py", line 19, in <module>
    remote_md5_cmd = f"{ base_cmd } {net_connect.flash}/{remote_file}"
AttributeError: 'CiscoIosSSH' object has no attribute 'flash'
