### ISSUE TITLE
send_command OSError: Search pattern never detected in send_command

### ISSUE THREAD

**Issue by Sederfo** [ktbyers/netmiko#2462]
Hello,
I am trying to push a set of config commands to a Cisco switch in a sequential manner, with an ideal time between them around 0.5 seconds, such that I can follow the script output and if any errors are spotted, I can manually close it.
The solution I have come to is using send_command_timing
```
print(connection.send_command_timing("conf t"))
for command in file_content:
    print(command)
    print(connection.send_command_timing(command))
```
This is not ideal since it takes around 1 and 1.5 seconds for each command to send its output. Adding delay_factor=0.5 does not seem to alter the time either. 
I would like to try using send_command and time.sleep(0.5) to get the results I need, BUT when using send_command with any command that is not a show command (for example, send_command('conf t')), it gives me this error:

> Traceback (most recent call last):
>   File "C:\Users\uie53785\Desktop\vlan105\vlan105test.py", line 41, in <module>
>     print(connection.send_command("conf t"))
>   File "C:\Users\uie53785\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
>     return func(self, *args, **kwargs)
>   File "C:\Users\uie53785\AppData\Local\Programs\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 1535, in send_command
>     raise IOError(
> OSError: Search pattern never detected in send_command: tm\-ise\-test\#

I'm sorry if this a newbie question, but I've run out of ideas and issues to browse.

**Comment by ktbyers** [comment]
@Sederfo I would try to use the `send_config_set()` method instead. This method is Netmiko's solution for sending configuration commands. It will automatically enter and exit configuration mode.

```python
command_list = [some, list, of commands]
output = connection.send_config_set(command_list)
```

**Comment by Sederfo** [comment]
Thanks for the response. 
The send_config_set() method does indeed work but it does not produce the behaviour I need. I got around this issue by using paramiko like this:
```
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname=ip,username=username,password=password)

ssh = client.invoke_shell()
ssh.send(b"conf t \n")  
time.sleep(1)

for command in file_content:
    ssh.send(command + "\n")   
    time.sleep(1) 
    output = ssh.recv(65535)
    print(output.decode())
```
