### ISSUE TITLE
Configuring banner requires cmd_verify=False

### ISSUE THREAD

**Issue by seyedfazil900** [ktbyers/netmiko#2472]
I am trying to send the below comman for banner not working. Could someone help plz.

from netmiko import ConnectHandler

with open('devices_file') as f:
    devices_list = f.read().splitlines()

ios_devices = {
    'device_type': 'cisco_ios',
    'ip': '172.16.253.48',
    'username': 'admin',
    'password': 'ciao123',
}
config_commands = [

 'conf t', 

 'no banner login', 

 'banner login ^c',

 '*********************************************************************',

'  COMPANY LOGON SECURITY WARNING NOTICE!  ',

 ' This is the first line of the banner ',

 ' This is the second line of the banner ',   

 ' This is the third line of the banner ',

 ' *This is the fourth line of your banner ',

 ' *This is the last line of your banner ',

 ' ********************************************************************',

 ' ^C'

 ]

all_devices = [ios_devices]

for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    output = net_connect.send_config_set(commands_to_send)
    print (output)

**Comment by ktbyers** [comment]
Add cmd_verify=False (the banner does not behave like a normal configuration command).

```python
output = net_connect.send_config_set(commands_to_send, cmd_verify=False)
```

**Comment by seyedfazil900** [comment]
Thank you so much, It is working tkbyers
