### ISSUE TITLE
Change send_config_set and look ahead behavior on cmd_verify

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#2476]
https://github.com/ktbyers/netmiko/blob/v3.4.0/netmiko/base_connection.py#L1916-L1917

This should be a configurable option as whenever you have a command that prompts you in a configuration command this will break.

Should probably default disable this for the Huawei driver.

**Comment by luweijun1992** [comment]
> https://github.com/ktbyers/netmiko/blob/v3.4.0/netmiko/base_connection.py#L1916-L1917
> 
> This should be a configurable option as whenever you have a command that prompts you in a configuration command this will break.
> 
> Should probably default disable this for the Huawei driver.

@ktbyers 
When I checked the Cisco documentation, the Cisco command line also confirmed the operation.
![image](https://user-images.githubusercontent.com/58923704/132608173-4154cce7-45ed-4697-8dce-4bfc76a252dd.png)
Including the device `reboot`, there is also a confirmation prompt, what needs to be done.

**Comment by ktbyers** [comment]
S300 is not that common of a Cisco platform (you are looking at a Cisco S300 series above).

 Yes there are some Cisco IOS/IOS-XE config operations that confirm (and really shouldn't) in particular the removal of a user.

Yes, I probably wouldn't make this the default for Cisco IOS/IOS-XE or Cisco S300 as it not that common in Cisco-land, but it looks like it might be more common in Huawei (given what you were showing).

There are other workarounds for this including the disabling of cmd_verify=False as referenced earlier.

`reboot` is not a config command so you would typically handle the prompting in the standard Netmiko way using either send_command() or send_command_timing()

**Comment by luweijun1992** [comment]
> S300 is not that common of a Cisco platform (you are looking at a Cisco S300 series above).
> 
> Yes there are some Cisco IOS/IOS-XE config operations that confirm (and really shouldn't) in particular the removal of a user.
> 
> Yes, I probably wouldn't make this the default for Cisco IOS/IOS-XE or Cisco S300 as it not that common in Cisco-land, but it looks like it might be more common in Huawei (given what you were showing).
> 
> There are other workarounds for this including the disabling of cmd_verify=False as referenced earlier.
> 
> `reboot` is not a config command so you would typically handle the prompting in the standard Netmiko way using either send_command() or send_command_timing()

Yes, I am worried that other problems will be introduced after configuring `cmd_verify=False`
Is there any other way to solve the operation that needs to be confirmed?

**Comment by ktbyers** [comment]
For non-configuration commands, there are various ways you can solve the confirmation including send_multiline, send_multiline_timing, and the solutions listed here:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-timing

And:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-expect_string

So the only issue is configuration commands that prompt, the main options are:

1. What you were doing with cmd_verify=False (i.e. add in the confirmations as part of the list of commands sent to send_config_set.
2. Do a pattern where you handle the confirmations using send_multiline or send_command/send_command_timing but where you first invoke the .config_mode() method and then employ one of the solutions referenced at the top here (i.e. send_multiline/send_command/send_command_timing).

**Comment by luweijun1992** [comment]
> For non-configuration commands, there are various ways you can solve the confirmation including send_multiline, send_multiline_timing, and the solutions listed here:
> 
> https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-timing
> 
> And:
> 
> https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-expect_string
> 
> So the only issue is configuration commands that prompt, the main options are:
> 
> 1. What you were doing with cmd_verify=False (i.e. add in the confirmations as part of the list of commands sent to send_config_set.
> 2. Do a pattern where you handle the confirmations using send_multiline or send_command/send_command_timing but where you first invoke the .config_mode() method and then employ one of the solutions referenced at the top here (i.e. send_multiline/send_command/send_command_timing).

@ktbyers 
Viewed the examples, they are all used for a single command.
My current is multiple commands in one `send_config_set`
Is there any relevant introduction example for `send_multiline`

**Comment by ktbyers** [comment]
Purging old issues...
