### ISSUE TITLE
Cisco SG Series Switches handling login directly for their non-standard SSH

### ISSUE THREAD

**Issue by routeallthings** [ktbyers/netmiko#2477]
Reading through some previous bugs.. I did see where you call out need to make changes to the config on the SG switches. One of the network mapping programs I am developing does blind logins (after matching device types). These are in environments where I cannot make changes to configurations in order to login to pull down data. Looking through how the auth is handled.. it looks like Cisco WLC and Cisco SG share a lot of the same characteristics when they go to login (requiring a username first which can really be anything, and then rolling into the actual user/password prompts). I see you have a function called "special_login_handler". As a test I did some minor modification to it.. but later realized it wasnt getting far enough in netmiko due to failures it looks like in paramiko.

Is there some way to handle this type of login without making those SSH changes?

This is the function  I added to the cisco_s300.py file.
`def special_login_handler(self, delay_factor=1):
		"""SG Switches presents with the following on login with SSH and specific configurations on the device

		login as: user

		User: user

		Password:****
		"""
		delay_factor = self.select_delay_factor(delay_factor)
		i = 0
		time.sleep(delay_factor * 0.5)
		output = ""
		while i <= 12:
			output = self.read_channel()
			if output:
				if "login as" in output or "User" in output:
					self.write_channel(self.username + self.RETURN)
				elif "Password" in output:
					self.write_channel(self.password + self.RETURN)
					break
				time.sleep(delay_factor * 1)
			else:
				self.write_channel(self.RETURN)
				time.sleep(delay_factor * 1.5)
			i += 1`

Error I am getting from netmiko/paramiko

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Python38\lib\site-packages\paramiko\client.py", line 435, in connect
    self._auth(
  File "C:\Python38\lib\site-packages\paramiko\client.py", line 764, in _auth
    raise saved_exception
  File "C:\Python38\lib\site-packages\paramiko\client.py", line 751, in _auth
    self._transport.auth_password(username, password)
  File "C:\Python38\lib\site-packages\paramiko\transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Python38\lib\site-packages\paramiko\auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['']

**Comment by ktbyers** [comment]
Did you do the no_auth part like we have here for the Calix B6 driver?

https://github.com/ktbyers/netmiko/blob/v3.4.0/netmiko/calix/calix_b6.py#L79

I suspect you might need to do more of a pattern like that.

You might also need to look at the more detailed logging to see what is going on.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by routeallthings** [comment]
You nailed it.. in copying part of the code from calix_b6 I was able to get it working (see below). Now because these switches have the options to do EITHER depending on configuration.. I also had to add a "use_login" to BaseConnection.. so the logic will work out that if the BaseConnection fails.. I can set use_login to false to force the s300 driver to use noauth.

Changes to BaseConnection
`def __init__(
        self,
        ip="",
        host="",
        username="",
        password=None,
        secret="",
        port=None,
        device_type="",
        verbose=False,
        global_delay_factor=1,
        global_cmd_verify=None,
        use_keys=False,
        **use_login=True,**
        key_file=None,
        pkey=None,
        passphrase=None,
        allow_agent=False,
        ssh_strict=False,
        system_host_keys=False,
        alt_host_keys=False,
        alt_key_file="",
        ssh_config_file=None,`

`
            # Options for SSH Login
            **self.use_login = use_login**

            # Options for SSH host_keys
            self.use_keys = use_keys`

Changes to S300
`import time
from os import path

from paramiko import SSHClient

from netmiko.cisco_base_connection import CiscoSSHConnection

class SSHClient_noauth(SSHClient):
    """Set noauth when manually handling SSH authentication."""

    def _auth(self, username, *args):
        self._transport.auth_none(username)
        return

class CiscoS300SSH(CiscoSSHConnection):
	"""
	Support for Cisco SG300 series of devices.

	Note, must configure the following to disable SG300 from prompting for username twice:

	configure terminal
	ip ssh password-auth
	"""

	def special_login_handler(self, delay_factor=1):
		"""SG Switches presents with the following on login with SSH and specific configurations on the device

		login as: user

		User: user

		Password:****
		"""
		delay_factor = self.select_delay_factor(delay_factor)
		i = 0
		time.sleep(delay_factor * 0.5)
		output = ""
		while i <= 12:
			output = self.read_channel()
			if output:
				if "login as" in output or "User" in output:
					self.write_channel(self.username + self.RETURN)
				elif "Password" in output:
					self.write_channel(self.password + self.RETURN)
					break
				time.sleep(delay_factor * 1)
			else:
				self.write_channel(self.RETURN)
				time.sleep(delay_factor * 1.5)
			i += 1

	def session_preparation(self):
		"""Prepare the session after the connection has been established."""
		self.ansi_escape_codes = True
		self._test_channel_read()
		self.set_base_prompt()
		self.set_terminal_width(command="terminal width 511", pattern="terminal")
		self.disable_paging(command="terminal datadump")
		# Clear the read buffer
		time.sleep(0.3 * self.global_delay_factor)

	def save_config(self, cmd="write memory", confirm=True, confirm_response="Y"):
		return super().save_config(
			cmd=cmd, confirm=confirm, confirm_response=confirm_response
		)

	def _build_ssh_client(self):
		"""Prepare for Paramiko SSH connection."""
		# Create instance of SSHClient object
		# If not using SSH keys, we use noauth
		# If login is required, use SSHClient do to "ip ssh password-auth" change
		if not self.use_keys and self.use_login:
			remote_conn_pre = SSHClient_noauth()
		else:
			remote_conn_pre = SSHClient()

		# Load host_keys for better SSH security
		if self.system_host_keys:
			remote_conn_pre.load_system_host_keys()
		if self.alt_host_keys and path.isfile(self.alt_key_file):
			remote_conn_pre.load_host_keys(self.alt_key_file)

		# Default is to automatically add untrusted hosts (make sure appropriate for your env)
		remote_conn_pre.set_missing_host_key_policy(self.key_policy)
		return remote_conn_pre`

**Comment by kazegls** [comment]
Can you please post your whole code of cisco_s300.py? Thx in advance!

**Comment by ktbyers** [comment]
Standard process is to configure the SG300 for a more standard SSH login.

An alternate workaround is here for cases where you can't make these configuration changes.

**Comment by ktbyers** [comment]
Updated version of this fix (should be the same as above, unless I made an error). In `diff` format.

```diff
$ git diff
diff --git a/netmiko/cisco/cisco_s300.py b/netmiko/cisco/cisco_s300.py
index 1058c4a3..38c328eb 100644
--- a/netmiko/cisco/cisco_s300.py
+++ b/netmiko/cisco/cisco_s300.py
@@ -1,3 +1,7 @@
+import time
+from os import path
+from paramiko import SSHClient
+from netmiko.ssh_auth import SSHClient_noauth
 from netmiko.cisco_base_connection import CiscoSSHConnection
 
 
@@ -11,6 +15,37 @@ class CiscoS300Base(CiscoSSHConnection):
     ip ssh password-auth
     """
 
+    def special_login_handler(self, delay_factor: float = 1.0) -> None:
+        """
+        SG Switches presents with the following on login with SSH and specific
+        configurations on the device
+
+        login as: user
+
+        User: user
+
+        Password:****
+        """
+        delay_factor = self.select_delay_factor(delay_factor)
+        i = 0
+        time.sleep(delay_factor * 0.5)
+        output = ""
+        while i <= 12:
+            output = self.read_channel()
+            if output:
+                if "login as" in output or "User" in output:
+                    assert isinstance(self.username, str)
+                    self.write_channel(self.username + self.RETURN)
+                elif "Password" in output:
+                    assert isinstance(self.password, str)
+                    self.write_channel(self.password + self.RETURN)
+                    break
+                time.sleep(delay_factor * 1)
+            else:
+                self.write_channel(self.RETURN)
+                time.sleep(delay_factor * 1.5)
+            i += 1
+
     def session_preparation(self) -> None:
         """Prepare the session after the connection has been established."""
         self.ansi_escape_codes = True
@@ -31,7 +66,24 @@ class CiscoS300Base(CiscoSSHConnection):
 
 
 class CiscoS300SSH(CiscoS300Base):
-    pass
+    def _build_ssh_client(self) -> SSHClient:
+        """Prepare for Paramiko SSH connection."""
+        # Create instance of SSHClient object
+        # If not using SSH keys, we use noauth
+        if not self.use_keys:
+            remote_conn_pre: SSHClient = SSHClient_noauth()
+        else:
+            remote_conn_pre = SSHClient()
+
+        # Load host_keys for better SSH security
+        if self.system_host_keys:
+            remote_conn_pre.load_system_host_keys()
+        if self.alt_host_keys and path.isfile(self.alt_key_file):
+            remote_conn_pre.load_host_keys(self.alt_key_file)
+
+        # Default is to automatically add untrusted hosts (make sure appropriate for your env)
+        remote_conn_pre.set_missing_host_key_policy(self.key_policy)
+        return remote_conn_pre
 
 
 class CiscoS300Telnet(CiscoS300Base):
```

**Comment by ktbyers** [comment]
The Netmiko `cisco_s200` device_type will probably just work for "SG Series" devices that have the non-standard SSH behavior.

I say this as the `cisco_s200` device_type does the special login handling for the non-standard SSH (as at least some set of the S200 devices do not support the `ip ssh password-auth` command).
