### ISSUE TITLE
lrzsz not support?

### ISSUE THREAD

**Issue by songtianyi** [ktbyers/netmiko#2480]
Like i'm running `sz` in remote host which connected with ssh, how to receive the payload in netmiko?
> Generally, a wizard in localhost will prompt to choose a file to save to, but what i want is save this file in netmiko silently 

```python3
from netmiko import ConnectHandler
from getpass import getpass

cisco1 = {
    "device_type": "autodetect",
    "host": "10.88.88.240",
    "username": "administrator",
    "password": getpass(),
}

# Show command that we execute.
command = "new  export config.log encrypt  off"

with ConnectHandler(**cisco1) as net_connect:
    output = net_connect.send_command(command)

# Automatically cleans-up the output so that only the show output is returned
print()
print(output)
print()
```
The command `new  export config.log encrypt  off` is mostly like `sz`, because i saw the zmodem start flag bytes in output.
```
rz^M**^XB00000000000000^M<8a>^Q
```

**Comment by ktbyers** [comment]
@songtianyi You are going to have to repeat and expand on your question here? I don't understand what you are asking.

Your code above is not valid i.e. that is not a valid way to use `autodetect`, you could try `generic` instead and see if that works (or not).
