### ISSUE TITLE
Failed to login mellanox switch using netmiko

### ISSUE THREAD

**Issue by zhangli1616** [ktbyers/netmiko#2483]
this is the device type: MSX6518-NR. The switch version as below:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Product name:      MLNX-OS
Product release:   3.6.6000
Build ID:          #1-dev
Build date:        2018-03-04 16:48:04
Target arch:       ppc
Target hw:         m460ex
Built by:          jenkins@2811f8c7d517
Version summary:   PPC_M460EX 3.6.6000 2018-03-04 16:48:04 ppc

Product model:     ppc
Host ID:           F45214D45EEC

Uptime:            1270d 18h 27m 6.880s
CPU load averages: 1.70 / 1.56 / 1.56
Number of CPUs:    1
System memory:     393 MB used / 1634 MB free / 2027 MB total
Swap:              0 MB used / 0 MB free / 0 MB total
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
this is my code:
net_connect = ConnectHandler(device_type='mellanox',host=host,username=username,password=password)
current_view = net_connect.find_prompt()
dirname = host + '_' + LogTime + "_roce"
os.mkdir(dirname)
for j in cmd.split('\n'):
    output = net_connect.send_command(j)
    time.sleep(2)

And the problem was occured using this code：
`err is Router prompt not found: 'other state: ready'
err is Router prompt not found: 'Active HA nodes: 2'
err is Router prompt not found: 'other state: ready'
err is Router prompt not found: 'other state: ready'`

Then I change the device type from mellanox to linux or mellanox_mlnxos，it's still no use. Could someone else know this statement?

**Comment by ktbyers** [comment]
I am going to close this issue as it doesn't look like it is actively being worked on.

If this is still an issue, feel free to re-open it.
