### ISSUE TITLE
SSH Connection over SSO Server

### ISSUE THREAD

**Issue by tolgak87** [ktbyers/netmiko#2488]
Hi,

With directly connection, I use Netmiko successfully. But I must use jumping server (SSO) to do that. I checked proxy server code for netmiko. But I am confused. 

My way to login device:

1- Connect SSO server with IP,SSH2 port as 2222,username and password, finally enter bottom
2- Then write the target IP address as Cisco, or other vendors than enter bottom. There is no username and password entered in this step.

With 2 steps I can login device with jump server. 
I cannot figure out to do that with netmiko.

That's why I use paramiko module there. But I prefer Netmiko, it's more efficent for me.

**Comment by ktbyers** [comment]
So how are you authenticating in step2? In other words, you say there is no username/password for step2?

Are you using an SSH Config file with Paramiko or some other solution?

**Comment by tolgak87** [comment]
Hi Kirk,

Thank you for quick response :) 

Yes you are correct. In the 1st step I already enter my account informations to SSO server. After that in 2nd step, only write the IP address of the device. No command such **ssh**, **username,** or something else. Only the **IP information** and then **enter bottom**.

Currently, I am using paramiko to login SSO server. Then write IP of device.

Code part is as below.  

**1st STEP: (Paramiko SSH connection to SSO Server)**
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect("X.X.X.X", 2222, "USERNAME", "PASSWORD")     #SSO Server Info
commands = client.invoke_shell()                                            #Now I am inside of SSO Server


**2nd STEP:**
for ip in host:
    commands.send(f"{ip} \r")				        #IP info and push enter bottom -In this step I am login to router.
	time.sleep(5)							#Login take time, so I add some delay
    commands.send("show version \n")		        #I am inside of router now. I run commands after that.


I cannot figure out that I can do these steps with netmiko :)

**Comment by ktbyers** [comment]
@tolgak87 Okay, what have you tried with Netmiko? You should be able to do a very similar thing there.

**Comment by tolgak87** [comment]
I didn't try netmiko for sso. I don't understamd to start.should I use with ssh proxy example? İf ok, i will try some and inform you. But i didnt get it clearly whether I create a proxy file or its already inside the module :)

**Comment by ktbyers** [comment]
Just login probably using the `linux` device_type and then use `send_command` probably with an `expect_string` to execute:

```python
commands.send(f"{ip} \r") #IP info and push enter bottom -In this step I am login to router.
time.sleep(5) #Login take time, so I add some delay
commands.send("show version \n") #I am inside of router now. I run commands after that.
```

You probably need to use `redispatch` to switch the class. `redispatch` should be documented in the Netmiko examples.md file.

Is the intermediate device a terminal server or something else? It is a bit odd that no credentials are required for your second login--that is very much non-standard.

**Comment by tolgak87** [comment]
Hi Kirk, I will try to login as linux server first to Server, and continue as you explained.

Thanks a lot :)
