### ISSUE TITLE
Netmiko 3.4.0 F5 TMSH session does not terminate normal but only after time-out

### ISSUE THREAD

**Issue by EnBee66** [ktbyers/netmiko#2492]
Hi,

After the update from Netmiko 3.3.3 to 3.4.0 a TMSH session to an F5 devices does not terminate as expected but after a time out (approx. 100 seconds after the last command was sent)  
I did not have that issue with versione 3.3.3 and below.

In my script I used device_type f5_ltm and f5_tmsh, both map to F5TmshSSH. For our daily tasks we only use the TMSH shell, not the normal linux shell (which F5 calls the advanced shell)
That is the reason for using f5_ltm or f5_tmsh. I assume this will make Netmiko to expect the TMSH shell only without first having to enable the TMSH shell via the command "tmsh". 
This "tmsh" command is only required when a user logs in and then connects to the linux shell first. 

The ways to connect to connect to a device and get to the TMSH shell

- User account with rights to connect to the Linux shell first 

[root@f5-device:Active:In Sync] config # tmsh
root@(f5-device)(cfg-sync In Sync)(Active)(/Common)(tmos)# quit
[root@f5-device:Active:In Sync] config # exit

- User acount with ONLY rights to use the TMSH shell ONLY

username@(f5-device)(cfg-sync In Sync)(Active)(/Common)(tmos)# quit 

In Netmiko version 3.4.0 one of the modified files for F5 devices is file f5_tmsh_ssh.py. It seems one of the modifications in that file is the way the TMSH session is terminated. After termination the TMSH shell Netmiko expects to return to the Linux shell. Which is not always what will happen, depending on the shell presented after logging in.

I have looked at the differences between 3.3.3 and 3.4.0 and modified the file f5_tmsh_ssh.py to get more info what causes this delay.

- Original file f5_tmsh_ssh.py
    def exit_tmsh(self):
        output = self.send_command("quit", **_expect_string=r"#"_**)
        <..>

    def cleanup(self, command="exit"):
        """Gracefully exit the SSH session."""
        try:
            self.exit_tmsh()
        except Exception:
            pass

I enabled logging in the script and from the result I had the impression that the quit part caused the issue. I have modified the file first in such a way I was able to see the Exception which I expected to see because of the time-out.

- Modified file f5_tmsh_ssh.py
    def exit_tmsh(self):
        output = self.send_command("quit", expect_string=r"#")
        <..>

    def cleanup(self, command="exit"):
        """Gracefully exit the SSH session."""
        try:
            self.exit_tmsh()
            except Exception as e:
            print ("~" *20) 
            print ("Exception:") 
            print (e)
            print ("~" *20)

- Result Modified file f5_tmsh_ssh.py, command send to device is "list sys ntp"

d:\>connect-f5.py
sys ntp {
    servers { 1.1.1.1 }
    timezone Europe/Amsterdam
}
**~~~~~~~~~~~~~~~~~~~~
Exception:
Search pattern never detected in send_command: #
~~~~~~~~~~~~~~~~~~~~**

This shows the reason for the time-out.  The expected character # is not seen after quit


It makes sense the # is not seen if the user account used to connect, only is allowed to use the TMSH shell. After "quit" the SSH session will be terminated. 
I would expect that at least the device type f5_tmsh should be aware that quit will terminate the SSH session.   



I found two work arounds. First one is modify the file f5_tmsh_ssh.py and change the expect_string=r"#" to something like expect_string=r"". 
The session will be terminated but still with an Exception "Socket is closed"  (which I only see because I added the print statement)

The other workaround is use f5_linux as device type.
Because my account puts me in the TMOS sheel directly, the command "list sys ntp" will be executed.  With f5_linux the exit command is used to disconnect and this will not work but the connection will still be terminated after the second try to sent exit.


I hope this issue can be addressed in the next version of Netmiko.

**Comment by ktbyers** [comment]
I need someone to assist me on working with the Netmiko F5 driver. If anyone here wants to help, let me know.

Otherwise, I probably just need to completely remove it.

**Comment by EnBee66** [comment]
Hi Mr. Byers,

The removal of the Netmiko driver would be very convenient for me and all my colleagues who use Netmiko to collect data from our F5 devices.  I'm not a Python expert but willing to help with the development of the F5 driver. 
In the test environment of the company I work for, we have F5 devices I can use to perform connectivity tests for the bash and tmsh shells.  Just let me know how and what you would like to test and how I can share the results.

**Comment by ktbyers** [comment]
@EnBee66 Great thanks. Let me try to put some things together early next week.

**Comment by ktbyers** [comment]
@EnBee66 It would be great it we could run the standard Netmiko tests against an F5 device and see if they pass. See https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

Let me know if you need any help in getting the tests to run properly.

Once again thanks for your help.

**Comment by EnBee66** [comment]
Hi,

Due to unexpected additional work I had to handle I did not have time to look into your request. I will do so next week. 
I did have a quick look at the URL you supplied but for me this did not make clear what or how I can test. 
Maybe you can give a hint on how to proceed.

**Comment by ktbyers** [comment]
@EnBee66 Can you expand on what you don't understand in the testing document? Or what part you are struggling with?

**Comment by EnBee66** [comment]
I looked at the tests again and this is what I have done without success. As in the existing examples there is not much what looks like what an F5 can produce I tried to use a minimal set of commands / results first, maybe that is where I go wrong.   

Maybe worth to share, the issue I reported does not occur in Netmiko version: 4.2.0 or the earlier 4.x version. 

To get the most correct output from an F5 device I have to use send_command_timing instead of send_command which can be used for Cisco devices.  The device type used is f5_tmsh.   send_command is not able to detect the correct prompt and the command execution will fail. 




# Created a virtual environment 

# Installed netmiko and pytest

(netmiko-test) <<omitted>>\netmiko-test\netmiko\tests>pip freeze
bcrypt==4.0.1
cffi==1.15.1
colorama==0.4.6
cryptography==41.0.1
exceptiongroup==1.1.1
future==0.18.3
iniconfig==2.0.0
netmiko==4.2.0
ntc-templates==3.3.0
packaging==23.1
paramiko==3.2.0
pluggy==1.0.0
pycparser==2.21
PyNaCl==1.5.0
pyserial==3.5
pytest==7.3.1
PyYAML==6.0
scp==0.14.5
six==1.16.0
textfsm==1.1.3
tomli==2.0.1


# Modified the suggested files 

"<<omitted>>\netmiko-test\netmiko\tests\etc\commands.yml" 

f5-tmsh:
  version: "show sys version
  basic: "list ltm interface"

f5-linux:
  version: "uname"
  basic: "ls"


"<<omitted>>\netmiko-test\netmiko\tests\etc\responses.yml" 

f5-tmsh:
  version: "BIG-IP"
  basic: "interface"
  base_prompt: tmos

f5-linux:
  version: "Linux"
  basic: "bigip"
  base_prompt: config


"<<omitted>>\netmiko-test\netmiko\tests\etc\test_devices.yml" 

f5-tmsh:
  device_type: f5_tmsh
  ip: <<device IP address
  username: <<my user id>>
  password: <<my password>>

f5-linux:
  device_type: f5_linux
  ip: <<device IP address
  username: root
  password: <<root password>>


# Then ran this:
<<omitted>>\netmiko-test\netmiko\tests>py.test -v test_netmiko_show.py --test_device f5-linux

py.test will run but the result is a list with only errors
