### ISSUE TITLE
FORTINET -  raise ValueError(f"Router prompt not found: {repr(prompt)}")

### ISSUE THREAD

**Issue by kongraphael** [ktbyers/netmiko#2493]
Hello,
Since the new version, my simple connection is broken with this error:  raise ValueError(f"Router prompt not found: {repr(prompt)}")

Same code with Netmiko 3.3.3 is OK.

Any idea ?

**Comment by ktbyers** [comment]
Can you post the full exception stack trace?

**Comment by kongraphael** [comment]
Hi Kirk, I'm really confused ... it seems i've tested the same code with netmiko 3.4.0 ... but on a different remote device (hpe instead of Fortinet)
So you code is OK (tested again with Netmiko 3.4.0)
