### ISSUE TITLE
one-liner config fails; two lines, ok

### ISSUE THREAD

**Issue by laimaretto** [ktbyers/netmiko#2495]
Hi!

I have experienced that (sometimes) the onliner config failes. If I change that to a more specific two-line config, it passes ok. Let me show:

1) This fails:
`"/configure router interface test5 address 99.99.98.8/32\n"`

This is what I see in the debug:
```
DEBUG:netmiko:Pattern is: \#\ SCRIPT_NONO_START
DEBUG:netmiko:_read_channel_expect read_data: # SCRIPT_NONO_START
*A:myRouter# 
DEBUG:netmiko:Pattern found: \#\ SCRIPT_NONO_START # SCRIPT_NONO_START
*A:myRouter# 
DEBUG:netmiko:write_channel: b'/environment no more\n'
DEBUG:netmiko:Pattern is: /environment\ no\ more
DEBUG:netmiko:_read_channel_expect read_data: /envi
DEBUG:netmiko:_read_channel_expect read_data: ronment no more 
*A:myRouter# 
DEBUG:netmiko:Pattern found: /environment\ no\ more /environment no more 
*A:myRouter# 
DEBUG:netmiko:write_channel: b'/configure router interface test5 address 99.99.98.8/32\n'
DEBUG:netmiko:Pattern is: /configure\ router\ interface\ test5\ address\ 99\.99\.98\.8/32
DEBUG:netmiko:_read_channel_expect read_data: /configure router interface test5[5D
DEBUG:netmiko:_read_channel_expect read_data: "test5[5D[5C" address 99.99.98.8/32 

DEBUG:netmiko:_read_channel_expect read_data: *A:
DEBUG:netmiko:_read_channel_expect read_data: myRouter# 
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:netmiko:write_channel: b'logout\n'
```

2) This works:
`"/configure router interface test5\naddress 99.99.98.8/32\n"` (notice the `\n` in the middle to make it a two-line config).
This is what I see in the debug:
```
DEBUG:netmiko:Pattern found: \#\ SCRIPT_NONO_START # SCRIPT_NONO_START
*A:myRouter# 
DEBUG:netmiko:write_channel: b'/environment no more\n'
DEBUG:netmiko:Pattern is: /environment\ no\ more
DEBUG:netmiko:_read_channel_expect read_data: /enviro
DEBUG:netmiko:_read_channel_expect read_data: nment no more 

DEBUG:netmiko:Pattern found: /environment\ no\ more /environment no more 

DEBUG:netmiko:Pattern is: (?:\*A:myRouter|#)
DEBUG:netmiko:_read_channel_expect read_data: *A:
DEBUG:netmiko:_read_channel_expect read_data: myRouter# 
DEBUG:netmiko:Pattern found: (?:\*A:myRouter|#) *A:myRouter# 
DEBUG:netmiko:write_channel: b'/configure router interface test5\n'
DEBUG:netmiko:Pattern is: /configure\ router\ interface\ test5
DEBUG:netmiko:_read_channel_expect read_data: /co
DEBUG:netmiko:_read_channel_expect read_data: nfigure router interface test5[5D"test5[5D[5C" 
*A:myRouter>config>router>if# 
DEBUG:netmiko:Pattern found: /configure\ router\ interface\ test5 /configure router interface test5[5D"test5[5D[5C" 
*A:myRouter>config>router>if# 
DEBUG:netmiko:write_channel: b'address 99.99.98.8/32\n'
DEBUG:netmiko:Pattern is: address\ 99\.99\.98\.8/32
DEBUG:netmiko:_read_channel_expect read_data: address 99.99.98
DEBUG:netmiko:_read_channel_expect read_data: .8/32 
*A:myRouter>config>router>if# 
DEBUG:netmiko:Pattern found: address\ 99\.99\.98\.8/32 address 99.99.98.8/32 
```
---
For some reason, if I send the command as two lines, it works.

I'm using:
- netmiko 3.4.0
- send_config_set()
- cmd_verify= True.
- device_type = nokia_sros

Thanks!
Lucas

**Comment by ktbyers** [comment]
@laimaretto Which Netmiko device_type are you using?

**Comment by laimaretto** [comment]
@ktbyers , sorry I missed that part. It is a nokia_sros. Let me update the original question ...

**Comment by ktbyers** [comment]
For your `send_config_set()` call can you try adding the argument cmd_verify=False and see if that fixes the issue?

It looks like some ANSI escape codes in the output are causing certain things to break (namely cmd_verify). It probably arises in the one case and not the other due to the line length.

**Comment by laimaretto** [comment]
Yes, indeed, setting `cmd_verify=False` solves it. Look at the debug now for the one-liner ...

```
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is A:myRouter#
DEBUG:netmiko:write_channel: b'# SCRIPT_NONO_START\n'
DEBUG:netmiko:write_channel: b'/environment no more\n'
DEBUG:netmiko:write_channel: b'/configure router interface test5 address 99.99.98.8/32\n'
DEBUG:netmiko:write_channel: b'/configure port 1/1/1 description newDescCron1236-12\n'
DEBUG:netmiko:write_channel: b'/configure port 1/1/2 description newDescCron3456-12\n'
DEBUG:netmiko:write_channel: b'exit all\n'
DEBUG:netmiko:write_channel: b'# SCRIPT_NONO_FIN\n'
DEBUG:netmiko:read_channel: # SCRIPT_NONO_START
A:myRouter# /environment no more 
A:myRouter# /configure router interface test5[5D"test5[5D[5C" address 99.99.98.8/32 
A:myRouter# /configure port 1/1/1 description newDescCron1236-12 
A:myRouter# /configure port 1/1/2 description newDescCron3456-12 
A:myRouter# exit all 
A:myRouter# # SCRIPT_NONO_FIN
A:myRouter# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'exit all\n'
DEBUG:netmiko:Pattern is: A:myRouter
DEBUG:netmiko:_read_channel_expect read_data: exit all 

DEBUG:netmiko:_read_channel_expect read_data: A:myRouter# 
DEBUG:netmiko:Pattern found: A:myRouter exit all 
A:myRouter# 
DEBUG:netmiko:# SCRIPT_NONO_START
A:myRouter# /environment no more 
A:myRouter# /configure router interface test5[5D"test5[5D[5C" address 99.99.98.8/32 
A:myRouter# /configure port 1/1/1 description newDescCron1236-12 
A:myRouter# /configure port 1/1/2 description newDescCron3456-12 
A:myRouter# exit all 
A:myRouter# # SCRIPT_NONO_FIN
A:myRouter# exit all 
A:myRouter# 
DEBUG:netmiko:write_channel: b'logout\n'
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:paramiko.transport:EOF in transport thread
```
---
So, nothing that we can do about it, isn't it? Either disabling `cmd_verify` or issuing the config commands as multiple lines ...

Thanks!

**Comment by ktbyers** [comment]
It is basically caused by two factors:

1. SR-OS classical CLI doesn't allow the terminal width to be set (as far as I am aware). Model driven CLI does allow this.
2. Netmiko has this bug:

https://github.com/ktbyers/netmiko/issues/2473

So I told Netmiko to disable cmd_verify for SR-OS classical CLI, but Netmiko is not honoring it for send_config_set (until I fix that bug).

**Comment by laimaretto** [comment]
Good, no worries then. Having that in mind at least gives us a chance to modify the scripts, or disabling `cmd_verify` in order to make it work.
Thanks!

**Comment by laimaretto** [comment]
@ktbyers , I did a fourth test, with a one-liner config + `cmd_verify=True` and it did work. Let me review the whole thing.

1) one-line `"/configure router interface test5 address 99.99.98.8/32\n"` + `cmd_verify=True`, falis.
2) two-lines `"/configure router interface test5\naddress 99.99.98.8/32\n"` + `cmd_verify=True`, ok.
3) one-line `"/configure router interface test5 address 99.99.98.8/32\n"` + `cmd_verify=False`, ok.

So here I did a fourth test which is:

4) one-line `'/configure router interface "test5" address 99.99.98.8/32\n'` + `cmd_verify=True`, ok.

If you see, I added the quotes around the name of the interface `"test5"` because, looking at the debug, the expected pattern `_read_channel_expect` is waiting for `"test5"`. Look at the debug.

```
DEBUG:netmiko:_read_channel_expect read_data: # SCRIPT_NONO_START
A:CF129_LABORATORIO_SARM# 
DEBUG:netmiko:Pattern found: \#\ SCRIPT_NONO_START # SCRIPT_NONO_START
A:CF129_LABORATORIO_SARM# 
DEBUG:netmiko:write_channel: b'/environment no more\n'
DEBUG:netmiko:Pattern is: /environment\ no\ more
DEBUG:netmiko:_read_channel_expect read_data: /environment no mor
DEBUG:netmiko:_read_channel_expect read_data: e 
A:CF129_LABORATORIO_SARM
DEBUG:netmiko:Pattern found: /environment\ no\ more /environment no more 
A:CF129_LABORATORIO_SARM
DEBUG:netmiko:write_channel: b'/configure router interface "test5" address 99.99.98.8/32\n'
DEBUG:netmiko:Pattern is: /configure\ router\ interface\ "test5"\ address\ 99\.99\.98\.8/32
DEBUG:netmiko:_read_channel_expect read_data: # 
DEBUG:netmiko:_read_channel_expect read_data: /configure router interface "test5" address 99.99.98.8/32 

DEBUG:netmiko:Pattern found: /configure\ router\ interface\ "test5"\ address\ 99\.99\.98\.8/32 # /configure router interface "test5" address 99.99.98.8/32 
```
In case (1), netmiko wrote to the channel something, expected something, but received something different. The difference is the `"` around the interface name.

```
DEBUG:netmiko:write_channel: b'/configure router interface test5 address 99.99.98.8/32\n'
DEBUG:netmiko:Pattern is: /configure\ router\ interface\ test5\ address\ 99\.99\.98\.8/32
DEBUG:netmiko:_read_channel_expect read_data: /configure router interface test5�[5D
DEBUG:netmiko:_read_channel_expect read_data: "test5�[5D�[5C" address 99.99.98.8/32 
```

So it seems to me that `cmd_verify` on nokia_sros is tricky, because the echoed string is different from what you wrote into the channel. I mean, the difference between case (1) and (4) is the quotes `"` around the name of the interface.

Hope this helps, because it seems it is not related to the terminal width. Could it be?

thanks!

**Comment by ktbyers** [comment]
Yeah, I think that is...that you should always use the canonical form of the configuration command or else Nokia SR-OS will re-write it to the canonical form.

So in the case without the quotes, Nokia SR-OS is re-writing the echoed command to be the canonical form (which is not what Netmiko is expecting since Netmiko is expecting an exact echo).
