### ISSUE TITLE
Error telnetting to console on dynamips for Cisco IOS

### ISSUE THREAD

**Issue by vinayakuh** [ktbyers/netmiko#2497]
Hi Team,

we are getting below error when we try to get the handler for CISCO device using telnet.
Issue is seen only on Python3 and it works fine on Python2

2021-09-16 06:54:28,817  - INFO - Timed-out reading channel, pattern not found in output: terminal width 511
2021-09-16 06:54:28,824 -  - INFO - Traceback (most recent call last):
  
 handler = netmiko.ConnectHandler(ip=self.ip, device_type='cisco_ios_telnet',
                                                 port=self.port, username=self.username,
                                                 password=self.password, global_delay_factor=4)
  File "/export/home/svcacct/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/export/home/svcacct/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/export/home/svcacct/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/export/home/svcacct/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 356, in _open
    self._try_session_preparation()
  File "/export/home/svcacct/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 792, in _try_session_preparation
    self.session_preparation()
  File "/export/home/svcacct/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 22, in session_preparation
    self.set_terminal_width(command=cmd, pattern=cmd)
  File "/export/home/svcacct/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1131, in set_terminal_width
    output = self.read_until_pattern(pattern=pattern)
  File "/export/home/svcacct/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/export/home/svcacct/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 595, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, pattern not found in output: terminal width 511

Please help to resolve the issue

**Comment by ktbyers** [comment]
You should look at either the Netmiko debug log or the Netmiko session_log and see why the `terminal width` command is not being properly echoed back.

**Comment by vinayakuh** [comment]
> You should look at either the Netmiko debug log or the Netmiko session_log and see why the `terminal width` command is not being properly echoed back.

Hi Ktbyers,

Thanks very much for responding.

I tried to check the session log and it fails to execute the terminal width 511 command suspect is mostly because of prompt is not coming up.

I just added 'self.write_channel('\r\n')' before sending the command  and that seems helping in resolving the issue but not sure about the consistency still I am doing the testing.

Do you suspect anything that is missing when I use Python3 for netmiko?

Thanks,
Vinayak

**Comment by ktbyers** [comment]
@vinayakuh Can you show me your Netmiko log file for this session?

https://github.com/ktbyers/netmiko/blob/v3.4.0/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

How slow is this device? Is this device very, very slow?

**Comment by vinayakuh** [comment]
Hi @ktbyers

PFA, of session log when the issue occured.

Due to some reason debug logs are not getting reported and will try to resolve the issue. After that I will attach the debug logs.

Regarding the slowness of the device, device is not slow and it works fine with Python2.

Thanks,
Vinayak
[common_netmiko_session.log](https://github.com/ktbyers/netmiko/files/7229404/common_netmiko_session.log)

**Comment by ktbyers** [comment]
How are you connecting in? It looks like you are connected to the console and are not connecting via SSH?

```
Connected to Dynamips VM "R1" (ID 0, type c7200) - Console port
Press ENTER to get the prompt.
```

**Comment by vinayakuh** [comment]
Hi @ktbyers ,

Thanks for responding!!

We are connecting through telnet console and  there is no SSH. Please find the below line.

**handler = netmiko.ConnectHandler(
                ip=self.ip, device_type='cisco_ios_telnet', port=self.port, username=self.username, password=self.password)**

Thanks,
Vinayak

**Comment by ktbyers** [comment]
Redispatch code should be:

```python
from netmiko import redispatch

# Use redispatch to re-initialize the right class.
redispatch(net_connect, device_type="cisco_ios_telnet")
```

Broader redispatch example:

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#terminal-server-and-redispatch

**Comment by vinayakuh** [comment]
Hi @ktbyers 

That fix seems working fine now. I wrote couple of lines initially with **write_channel()** and **read_channel()** with **device_type** set to **generic_termserver_telnet**. Later I switched the class to  **cisco_ios_telnet** using **redispatch**.

Thanks very much for all the information and suggestions.

Note: Any thought on why it was working totally fine with Python2 with device_type set to **cisco_ios_telnet**  initially? Issue started showing with Python3 with same piece of code.

**Comment by ktbyers** [comment]
Recent versions of Netmiko will verify that commands like setting the output paging and setting the terminal width are properly echoed.

Also Netmiko hasn't supported Python2.X for 8 releases so there have been a lot of changes since then.
