### ISSUE TITLE
[FATAL] CiscoConfParse could not open 'xxx.xx.xx.xx_2020_12_22.txt'

### ISSUE THREAD

**Issue by langcblt** [ktbyers/netmiko#2500]
I have a data folder where I stored the cisco config files.  I have three configs named as xxx.xxx.xxx.xxx.txt and the rest as xxx.xxx.xxx.xxx_2020_12_22.txt. I tested the python code using ciscoconfparse mode for the three configs that named without the year_month_date and it rans successfully.  when I put the rest of the config files that were named year_mo_date after the IP and ran it, it gave me [FATAL] error above.  I don't see anything wrong with those config files and don't know why.  Can you help please? Thanks

**Comment by ktbyers** [comment]
At a minimum you would would need to post your code and the full except stack trace.
