### ISSUE TITLE
SCP not working with cisco ios device

### ISSUE THREAD

**Issue by seyedfazil900** [ktbyers/netmiko#2501]
Dear Kt, 

I am tring to upload the file to cisco swicth. But it is not happeing. Below is the debug.

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is PLA#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'dir flash:/test.text\n'
DEBUG:netmiko:Pattern is: dir\ flash:/test\.text
DEBUG:netmiko:_read_channel_expect read_data: d
DEBUG:netmiko:_read_channel_expect read_data: ir flash:/test.
DEBUG:netmiko:_read_channel_expect read_data: text

DEBUG:netmiko:Pattern found: dir\ flash:/test\.text dir flash:/test.text

DEBUG:netmiko:read_channel: %Error opening flash:/test.text (No such file or directory)

PLA#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

PLA#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is PLA#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'dir flash:\n'
DEBUG:netmiko:Pattern is: dir\ flash:
DEBUG:netmiko:_read_channel_expect read_data: d
DEBUG:netmiko:_read_channel_expect read_data: ir flash:

DEBUG:netmiko:Pattern found: dir\ flash: dir flash:

DEBUG:netmiko:read_channel: Directory of flash:/

    2  -rwx        2072   Mar 8 1993 15:35:58 +04:00  multiple-fs

    3  -rwx         796   Mar 1 1993 04:00:52 +04:00  vlan.dat

  451  -rwx        3584   Mar 8 1993 15:35:58 +04:00  private-config.text

    4  -rwx        2454   Mar 8 1993 15:35:58 +04:00  config.text

    6  drwx         512   Mar 1 1993 04:22:30 +04:00  c3560c405-universalk9-mz.122-55.EX3

59996160 bytes total (42951168 bytes free)

PLA#
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

PLA#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel:

**Comment by ktbyers** [comment]
I need your code and the full exception stack trace. Please simplify your code to the simplest form that illustrates the problem.

**Comment by seyedfazil900** [comment]
from netmiko import ConnectHandler
from netmiko import file_transfer
from netmiko.ssh_exception import NetmikoTimeoutException, AuthenticationException

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

CISCO_IOS = {
    "device_type": "cisco_ios",
    "ip": "172.16.253.48",
    "username": "ckari",
    "password": "ckari99!",
    "verbose": "True",
    "session_log": "session_output"
    }

try:

    ssh_connect = ConnectHandler(**CISCO_IOS)
    image_upload = file_transfer(ssh_connect, source_file="test.text", dest_file="test.text", file_system="flash:", direction="put", overwrite_file=True, disable_md5=True)
    ssh_connect.disconnect()

except NetmikoTimeoutException:
    print("test")
except AuthenticationException:
    print("Authentication error")
except Exception as Unknown_error:
    print("Unknown error")

**Comment by ktbyers** [comment]
And what is the full exception stack trace? You will need to remove your try/except code (i.e. your above code will actually hide the error).

Is this a real physical device or a virtual device?


Regards.

**Comment by seyedfazil900** [comment]
This is real device. I have removed the try and excep code and captured the session as well. below is the out put.


EMR-BWD-Plaza1#terminal width 511
EMR-BWD-Plaza1#terminal length 0
EMR-BWD-Plaza1#
EMR-BWD-Plaza1#
EMR-BWD-Plaza1#dir flash:/CIS.text
%Error opening flash:/CIS.text (No such file or directory)
EMR-BWD-Plaza1#
EMR-BWD-Plaza1#dir flash:
Directory of flash:/

    2  -rwx        3096  Mar 16 1993 11:49:47 +04:00  multiple-fs
    3  -rwx         796   Mar 1 1993 04:00:52 +04:00  vlan.dat
    6  drwx         512   Mar 1 1993 04:22:30 +04:00  c3560c405-universalk9-mz.122-55.EX3

59996160 bytes total (42957312 bytes free)
EMR-BWD-Plaza1#
EMR-BWD-Plaza1#exit

**Comment by seyedfazil900** [comment]
Still the file is not getting copied.

**Comment by seyedfazil900** [comment]
SCRIPT
-------


from netmiko import ConnectHandler
from netmiko import file_transfer

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")


CISCO_IOS = {
    "device_type": "cisco_ios",
    "ip": "172.99.253.48",
    "username": "the46",
    "password": "the46!",
    "verbose": "True",
    "session_log": "session_output"
    }

ssh_connect = ConnectHandler(**CISCO_IOS)
image_upload = file_transfer(ssh_connect, source_file="CIS.text", dest_file="CIS.text", file_system="flash:", direction="put", overwrite_file=True, disable_md5=True)
ssh_connect.disconnect()

**Comment by Tes3awy** [comment]
I am suspecting that it's because of `fast_cli`. Please add `fast_cli: False` to the `CISCO_IOS` dictionary. I am also assuming you have the following configuration on the remote Cisco device (`switch/router`):

```cisco
ip ssh version 2
ip ssh time-out 120 ! optional
ip ssh authentication-retries 3 ! optional
ip scp server enable
ip tcp window-size 65536 ! max recommended window size
ip ssh window-size 65536 ! max recommended window size
```

It's recommended by Cisco to have these lines in your running configuration to be able to run the SCP smoothly and can be found [here](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/sec_usr_ssh/configuration/xe-16-6/sec-usr-ssh-xe-16-6-book/sec-usr-ssh-xe-16-book_chapter_0110.pdf)

Please try the below code demo

```python
from netmiko import ConnectHandler, file_transfer

device = {
    "device_type": "cisco_ios",
    "host": "",
    "username": "",
    "password": "",
    "fast_cli": False, # disable fast cli
    "conn_timeout": 20,
    "auth_timeout": 20,
    "session_log": "scp-session.log",
}

src_file = ""  # file on local machine
dest_file = ""  # file to put on remote device (usually identical to src_file)

with ConnectHandler(**device) as ssh_conn:
    print(f"Connected to {ssh_conn.host}:{ssh_conn.port}")

    window_size = 65_536  # Max recommended window size by Cisco
    commands = [
        "ip ssh version 2",  # Recommended by Cisco
        "ip ssh time-out 120",  # Recommended by Cisco
        "ip ssh authentication-retries 3",  # Recommended by Cisco
        "ip scp server enable",
        f"ip tcp window-size {window_size}",
        f"ip ssh window-size {window_size}",
    ]
    cfg = ssh_conn.send_config_set(config_commands=commands, enter_config_mode=True)

    print(
        f"Transferring {src_file} to flash:{dest_file} for {ssh_conn.host}, please wait..."
    )
    scp_transfer = file_transfer(
        ssh_conn,
        source_file=src_file,
        dest_file=dest_file,
        file_system="flash:",
        overwrite_file=True,
        verify_file=True,
    )

    cfg += ssh_conn.save_config()
    print(f"Config changes saved to {ssh_conn.host}")

print(scp_transfer)
```

After you run the demo, please provide the content of `scp-session.log` file and the printed value of `scp_transfer` variable.
