### ISSUE TITLE
Aruba OS fails to make configuration changes (fixed in Netmiko >= 3.4.0)

### ISSUE THREAD

**Issue by EarlRamirez** [ktbyers/netmiko#2502]
Good day,

First of all, thank you for providing the community with this module. Recently when I try to use the following methods/functions from ConnectHandler `send_config_set` and `send_config_from_file` I get the following traceback

Interactive SSH session established
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 541, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prov_ap.py", line 30, in <module>
    results = ssh_connect.send_config_from_file(base_config_cmd, cmd_verify=False)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1642, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1704, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 40, in config_mode
    return super().config_mode(config_command=config_command, pattern=pattern)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1598, in config_mode
    output += self.read_until_pattern(pattern=re.escape(config_command.strip()))
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 618, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 552, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

It's important to mention that when I use `send_config_set` to send one command it is processed successfully and the change is reflected on the network device. However, if I am looping through data and sending it to the device only the first command is processed and soon after the above error is displayed.

Session logging was enabled in the connection handler and it appears that the data is not being sent to the device as shown below.

cat output.txt
(MM-03) *[mynode] #
(MM-03) *[mynode] #
(MM-03) *[mynode] #no paging
(MM-03) *[mynode] #
(MM-03) *[mynode] #configure term
Enter Configuration commands, one per line. End with CNTL/Z

Therefore, I suffix each line in the config set with a newline; however, that did not resolve the issue, I have also sent `cmd_verify=False` but did not resolve the issue.

Any recommendation will be highly appreciated

**Comment by ktbyers** [comment]
@EarlRamirez Which Netmiko `device_type` are you using?

Also please show what your configuration commands are i.e. what are you sending into send_config_from_file or send_config_set?


Regards, Kirk

**Comment by EarlRamirez** [comment]
@ktbyers, the device type is aruba_os
Below is the content of the file
```
!
clear provisioning-ap-list
provision-ap 
read-bootinfo ap-name 48:4a:e9:c3:46:6e
ap-name D00Z3F248P
ap-group WN-Crew-Cabin-Corridors
reprovision ap-name 48:4a:e9:c3:46:6e
clear provisioning-ap-list
clear provisioning-params
!
clear provisioning-ap-list
provision-ap 
read-bootinfo ap-name 48:4a:e9:c3:2e:da
ap-name D00Z3F259P
ap-group WN-Crew-Cabin-Corridors
reprovision ap-name 48:4a:e9:c3:2e:da
clear provisioning-ap-list
clear provisioning-params
!
```
and for the send_config_set, it is

```python
#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass


aruba_mm = {
    'device_type': 'aruba_os',
    'host': '192.168.122.100',
    'username': 'admin',
    'password': getpass(),
    'session_log': 'output.txt',
    'verbose': True
}

#Establish SSH session
ssh_connect = ConnectHandler(**aruba_mm) 

# Parse CSV file
with open('lab_ap_list.csv') as lab_aps:
    for line in lab_aps:
        line = line.rstrip()
        line = line.split(',')
        ap_name = line[0]
        ap_mac = line[1]
        ap_installed = line[4]
        ap_ctrl_status = line[6]
        ap_deck = line[9]
        ap_fz = line[10]
        ap_side = line[12]
        ap_group = line[17]
        ap_model = line[18]

        # Add condition to limit the APs being provisioned
        if ap_deck == 3 and ap_model == 'AP-303H':

            base_config_cmd = [
                'clear provisioning-ap-list\n',
                'provision-ap\n',
                f'read-bootinfo wired-mac {ap_mac}\n',
                f'ap-name {ap_name}\n',
                f'ap-group {ap_group}\n',
                f'reprovision wired-mac {ap_mac}\n',
                'clear provisioning-ap-list\n',
                'clear provisioning-params\n'
            ]

            results = ssh_connect.send_config_set(base_config_cmd, cmd_verify=False)
            print(results)
```
The new line was included after checking the session log but it still does not send the command to the device

**Comment by ktbyers** [comment]
What does this config look like like if you send it manually from the CLI? Can you post that here? 

I just want to see what the CLI behavior normally looks like for this set of confirmation commands.

**Comment by EarlRamirez** [comment]
Here is the config that I send via CLI
```
(MM-03) *[mynode] #clear provisioning-ap-list
(MM-03) *[mynode] #provision-ap
(MM-03) *[mynode] #read-bootinfo wired-mac 00:11:22:33:44:55
(MM-03) *[mynode] #ap-name lab-ap-001
(MM-03) *[mynode] #ap-group Guest
(MM-03) *[mynode] #reprovision wired-mac 00:11:22:33:44:55
(MM-03) *[mynode] #clear provisioning-ap-list
(MM-03) *[mynode] #clear provisioning-params
```

**Comment by ktbyers** [comment]
Hmmmm, can you show me in the logging file:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Also which version of Netmiko are you using?

**Comment by ktbyers** [comment]
@EarlRamirez Where is this `config term` coming from? Is that in your Python script?

**Comment by EarlRamirez** [comment]
Here is the complete code, I was under the impression that this is coming from Netmiko when the `send_config_set`

```python
#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass
import logging

logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")


aruba_mm = {
    'device_type': 'aruba_os',
    'host': '192.168.122.100',
    'username': 'admin',
    'password': getpass(),
    'session_log': 'output.txt',
    'verbose': True
}

#Establish SSH session
ssh_connect = ConnectHandler(**aruba_mm) 

# Parse CSV file
with open('lab_ap_list.csv') as lab_aps:
    for line in lab_aps:
        line = line.rstrip()
        line = line.split(',')
        ap_name = line[0]
        ap_mac = line[1]
        ap_installed = line[4]
        ap_ctrl_status = line[6]
        ap_deck = line[9]
        ap_fz = line[10]
        ap_side = line[12]
        ap_group = line[17]
        ap_model = line[18]

        # Add condition to limit the APs being provisioned
        if ap_deck == 10 and ap_group == 'lab-public-space' and  ap_side == 'S':
            
            print(f'Deck: {ap_deck} group: {ap_group} position: {ap_side}')

            base_config_cmd = [
                'clear provisioning-ap-list',
                'provision-ap',
                f'read-bootinfo wired-mac {ap_mac}',
                f'ap-name {ap_name}',
                f'ap-group {ap_group}',
                f'reprovision wired-mac {ap_mac}',
                'clear provisioning-ap-list',
                'clear provisioning-params'
            ]

            results = ssh_connect.send_config_set(base_config_cmd, cmd_verify=False)
            print(results)
```

**Comment by ktbyers** [comment]
Hmmm, weird. I checked in Netmiko 3.3.3 and it properly sends `configure term`:

https://github.com/ktbyers/netmiko/blob/v3.3.3/netmiko/aruba/aruba_ssh.py#L48

I would try upgrading to Netmiko 3.4.0 and see if you see the same behavior.

Basically, the issue in the log file that you sent is that `config term` is being sent, but the Aruba device echos back `configure term` (and thus cmd_verify fails).

This part of the exception stack is cmd verify failing:

output += self.read_until_pattern(pattern=re.escape(config_command.strip()))

**Comment by EarlRamirez** [comment]
Thank you, I will upgrade to 3.4.0 and try again and keep you posted.
thnaks again.

**Comment by EarlRamirez** [comment]
@ktbyers after upgrading to the Netmiko v3.4.0 we no longer experience the error as shown in the [test.log](https://github.com/ktbyers/netmiko/files/7229915/test.log).

**Comment by EarlRamirez** [comment]
@ktbyers, thank you very much for your support.
