### ISSUE TITLE
Checkpoint - CLISH Mode Support Request

### ISSUE THREAD

**Issue by giffordj** [ktbyers/netmiko#2506]
I've been working on a script to pull configurations from various devices. I was wondering if it was possible to create a clish_mode for the checkpoint gaia. Simliar to the f5_tmsh

The reason behind it is by default checkpoint is using /bin/bash in our environment, and to pull a config via bash is impossible, we have to issue a /bin/clish which changes the prompt to look more like a router. I have an example below. 

`[Expert@CHKP0011:0]# /bin/clish
UCHKP0011> show configuration
#
# Configuration of CHKP0011
# Language version: 12.3v1
#
# Exported by giffordj on Wed Sep 22 19:28:08 2021
CONFIG DATA
CHKP0011> exit
[Expert@CHKP0011:0]#`

I will give a shot to create my own patch. Will upload if I have success.

**Comment by ktbyers** [comment]
It looks like the existing Checkpoint driver should already work for your case (if you structure your code properly). What is the actual issue/failure that you run into?
