### ISSUE TITLE
Configuration mode Juniper

### ISSUE THREAD

**Issue by Demmad1983** [ktbyers/netmiko#2521]
Hi team

I want to launch the command bellow from configure exclusive mode on juniper devices , the output show me that it was executed from normal configure mode.
Did I miss something?

        commande ="set system ntp source-address "+host
        net_connect.send_config_set(commande,enter_config_mode="configure exclusive")

Thank you in advance

**Comment by nullbitzero** [comment]
Hi,
Please show log output when execute your code

**Comment by Demmad1983** [comment]
Here it is :

configure 

Entering configuration mode

The configuration has been changed but not committed



{master}[edit]

W_Wallix@MX104_SAF008# commit
 
re0: 
configuration check succeeds
re1: 
commit complete
re0: 
commit complete
