### ISSUE TITLE
Unable to connect to Nexus 5020 device

### ISSUE THREAD

**Issue by pmakovec** [ktbyers/netmiko#253]
I'm experiencing problem with netmiko connection to the Nexus 5020 switch while Nexus 5596 is working well.
Tested with Netmiko
Version: 0.4.3
Version: 0.5.6
Same result.

Code:
import netmiko
from netmiko import ConnectHandler

username = "user"
password = "pass"

print("Nexus 5596")
print(ConnectHandler(
        device_type='cisco_nxos',
        ip="prgdca-b1-sa-sw61",
        username=username,
        password=password,
    ))

print("Nexus 5020")
print(ConnectHandler(
        device_type='cisco_nxos',
        ip="prgdca-b1-sa-sw51",
        username=username,
        password=password,
    ))

Result:
$ python3 test.py
Nexus 5596
<netmiko.cisco.cisco_nxos_ssh.CiscoNxosSSH object at 0xb72eb5cc>
Nexus 5020
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    password=password,
  File "/usr/local/lib/python3.4/dist-packages/netmiko/ssh_dispatcher.py", line 88, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 69, in __init__
    self.session_preparation()
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 82, in session_preparation
    self.set_base_prompt()
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 253, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: http://www.opensource.org/licenses/lgpl-2.1.php

SSH to the Nexus 5020
$ ssh prgdca-b1-sa-sw51
Nexus 5000 Switch
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (c) 2002-2013, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under
license. Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or the GNU
Lesser General Public License (LGPL) Version 2.1. A copy of each
such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://www.opensource.org/licenses/lgpl-2.1.php
prgdca-b1-sa-sw51#

**Comment by pmakovec** [comment]
Tested with netmiko 0.3.4 from Windows - working.
Looks only newer versions are affected.

**Comment by ktbyers** [comment]
@pmakovec As a test, it would be interesting to do the following:

You will need to clone the master branch of netmiko, then cd ./netmiko/netmiko
edit base_connection.py

In this file, edit the following:

```
    def session_preparation(self):
        """
        Prepare the session after the connection has been established

        This method handles some of vagaries that occur between various devices
        early on in the session.

        In general, it should include:
        self.set_base_prompt()
        self.disable_paging()   # if applicable
        """
        time.sleep(2)     # add this line
        self.clear_buffer()    # add this line
        self.set_base_prompt()
        self.disable_paging()
```

You will make sure your code is using the new version of Netmiko 'python setup.py install' (or you can put a print("hello world") statement after the clear buffer so you know you are using the new code.

Let me know what happens.

**Comment by pmakovec** [comment]
@ktbyers 
Tested, it's working with the sleep(2). Looks like that Cisco 5020 is little bit slower then 5596.
But then I tried to send a command "show version" to both switches via
`net_connect.send_command("show version")`

This was working just for the Nexus 5020 platform. Nexus 5596 didn't respond.
I tried to send a command with expect method:
`net_connect.send_command_expect("show version")`
Working well on both switches.


Regarding the initial issue I tried to play with the Global Delay Factor. The code tries to connect to the switches three times and increments the global_delay_factor until gets the prompt.
```
def netmiko_open(netmiko_device):
    retries = 3
    for i in range(retries):
        try:
            net_connect = ConnectHandler(**netmiko_device)
            net_connect.enable()
            return net_connect
        except ValueError:
            print(netmiko_device["ip"]+": Router prompt not found, prolonging the delay_factor to %d seconds" % (i+1))
            netmiko_device["global_delay_factor"] = i+1 #sec
        except NetMikoTimeoutException:
            print(device_name+": Connection time-out")
            continue
    return False
```

BTW, can you please explain me a difference between the send_command and send_command_expect. I understood that is should be used for longer commands like show run, etc. But show version is not so long.

**Comment by BobbyGR** [comment]
I was having the same issue.  
        time.sleep(2)     # add this line
        self.clear_buffer()    # add this line

Placing this in fixed it for 5k's

**Comment by ktbyers** [comment]
@pmakovec 

send_command() is a timing based it tries to figure out the proper amount of time to way for the command to complete and return the output.

send_command_expect() is a pattern based method. It sends a command down the channel and looks for a pattern in the output to determine it is done. By default, the pattern output is based on the trailing router prompt. 

Note, across time I have encountered a lot of issues with send_command() i.e. just using timing is very problematic given how devices behave/response.

Because of this, in Netmiko 1.0

send_command() will be pointed to send_command_expect(). In other words, send_command() and send_command_expect() will be the same thing
The old send_command will be renamed send_command_timing()


Kirk

**Comment by ktbyers** [comment]
FYI, I incorporated a fix for this here https://github.com/ktbyers/netmiko/commit/fa1c240ef627933fb5c1e7d248a471283fa126ef

If you git pull the master branch, you should be able to test/verify this works.
