### ISSUE TITLE
Authentication failed despite correct password

### ISSUE THREAD

**Issue by ntaken** [ktbyers/netmiko#2532]
Happens to different HP switches seemingly at random. In this specific case a old 2915-8G-PoE with HP ProCurve A.15.16.0023. Always works fine with different ssh clients. Autentication uses tacacs but I think I remember having the same trouble with local accounts.

Connection settings:
>         net_connect = ConnectHandler(device_type=device_type, host=ip_address, username=username, password=password, conn_timeout=60, auth_timeout=60)

Error message:

> 172.20.100.111  =  hp_procurve 
>
> Authentication to device failed.
>
> Common causes of this problem are:
>
> 1. Invalid username and password
> 2. Incorrect SSH-key file
> 3. Connecting to the wrong device
>
> Device settings: hp_procurve 172.20.100.111:22
>
> Authentication failed.
>
> Execution time: 0:00:06.068738

Debug:
> DEBUG:paramiko.transport:starting thread (client mode): 0x76dde070
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Mocana SSH 5.8
INFO:paramiko.transport:Connected (version 2.0, client Mocana)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group14-sha1'] server key:['ssh-rsa'] client encrypt:['aes256-ctr', 'aes256-cbc', 'rijndael-cbc@lysator.liu.se', 'aes192-ctr', 'aes192-cbc', 'aes128-ctr', '>DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group14-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 172.20.100.111: b'e06d255e7b1cb191c2e09e7e23651654'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: b"We'd like to keep you up to date about:\n  * Software feature updates\n  * New product announcements\n  * Special events\nPlease register your products now at:  www.hp.c>INFO:paramiko.transport:Authentication (password) failed.

**Comment by ktbyers** [comment]
@ntaken Can you try the HP ProCurve code in Netmiko `develop` branch. I recently did a lot of work improving the ProCurve driver.


Regards, Kirk

**Comment by ntaken** [comment]
Not sure what a full stack trace is. Is it more than the traceback
immediately before? Do I use a debugger?

BTW I am using visual studio code when scripting. I will look into it and
collect what I can find before the end of the week.
Very much appreciated you taking your time looking into this.

Den ons 20 okt. 2021 kl 18:05 skrev Kirk Byers ***@***.***>:

**Comment by ntaken** [comment]
````
Traceback (most recent call last):
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/paramiko/client.py", line 751, in _auth
    self._transport.auth_password(username, password)
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/paramiko/transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netautoscripts/telnetprocurve.py", line 1437, in <module>
    net_connect = ConnectHandler(device_type=device_type, host=ip_address,
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/home/itservice/.local/share/virtualenvs/netautoscripts-Ad84lSuf/lib/python3.8/site-packages/netmiko/base_connection.py", line 972, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Authentication to device failed.
````
Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: hp_procurve 172.20.100.144:22

**Comment by ktbyers** [comment]
Can you show me what this looks like manually if you SSH into the device? You can obscure the username/password if needed...i.e. just use something fictional here.

Is there anything odd about this login--is it really slow or anything else?

Regards, Kirk

**Comment by pete-north** [comment]
Did you guys ever get to the bottom of this. I'm having a very similar issue with cisco NXOS switches. I have a list of switches to apply configuration to. I will get an authentication failure from netmiko for say switch 5, I run the script again, it works for switch 5 but fails on 6. run again and it makes it one more down the list to 7. every time it reports an authentication problem:

 line 972, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: cisco_nxos 10.50.1.9:22


Authentication failed.

very strange, feels more like an SSH key problem than authentication.

**Comment by ntaken** [comment]
The problem is not reproducible with a new ISE server set up.

**Comment by jscooksey** [comment]
I'm getting the same issue.

'''
  File "C:\Python\Python39\lib\site-packages\netmiko\ssh_dispatcher.py", line 344, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 434, in __init__
    self._open()
  File "C:\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 439, in _open
    self.establish_connection()
  File "C:\Python\Python39\lib\site-packages\netmiko\base_connection.py", line 1058, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.exceptions.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: cisco_xe 172.20.204.1:22
'''

There is no delay, the error is pretty instantaneous.

If I try gitbash and ssh I get, and Im not sure if it's related. (ugg Win10 PC)
```
$ ssh user@172.20.204.1
Unable to negotiate with 172.20.204.1 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
```

If I try Windows/Powershell command prompt with ssh it continually asks for my password

Yet I can access this fine using putty or SecureCRT.
OpenSSH (for Windows) is installed and at version 8.1.0.1

**Comment by Anirudh-Suri** [comment]
For me it was the same error. But then I saw it was due to the wrong IP given and also the reason might be that your SSH from the putty is not active.

**Comment by AasthaNarula** [comment]
I am getting the same error when I login with putty there is no error but when I login using python authentication failure occurs

**Comment by roys10** [comment]
> Did you guys ever get to the bottom of this. I'm having a very similar issue with cisco NXOS switches. I have a list of switches to apply configuration to. I will get an authentication failure from netmiko for say switch 5, I run the script again, it works for switch 5 but fails on 6. run again and it makes it one more down the list to 7. every time it reports an authentication problem:
> 
> line 972, in establish_connection raise NetmikoAuthenticationException(msg) netmiko.ssh_exception.NetmikoAuthenticationException: Authentication to device failed.
> 
> Common causes of this problem are:
> 
> 1. Invalid username and password
> 2. Incorrect SSH-key file
> 3. Connecting to the wrong device
> 
> Device settings: cisco_nxos 10.50.1.9:22
> 
> Authentication failed.
> 
> very strange, feels more like an SSH key problem than authentication.

Hey I know it was a while ago but I am currently having the same problem, did you manage to fix it?

**Comment by ktbyers** [comment]
@roys10 You should create a new issue. This issue was closed as not reproducible.

**Comment by pete-north** [comment]
> > Did you guys ever get to the bottom of this. I'm having a very similar issue with cisco NXOS switches. I have a list of switches to apply configuration to. I will get an authentication failure from netmiko for say switch 5, I run the script again, it works for switch 5 but fails on 6. run again and it makes it one more down the list to 7. every time it reports an authentication problem:
> > line 972, in establish_connection raise NetmikoAuthenticationException(msg) netmiko.ssh_exception.NetmikoAuthenticationException: Authentication to device failed.
> > Common causes of this problem are:
> > 
> > 1. Invalid username and password
> > 2. Incorrect SSH-key file
> > 3. Connecting to the wrong device
> > 
> > Device settings: cisco_nxos 10.50.1.9:22
> > Authentication failed.
> > very strange, feels more like an SSH key problem than authentication.
> 
> Hey I know it was a while ago but I am currently having the same problem, did you manage to fix it?

I put it down to some sort of issue with inconsistent TACACS+ response times from our ISE server, likely related to processing load. I implemented a workaround via a loop that just made up to 3 attempts to connect to a device before declaring it unreachable. I only encountered the issue with NXOS network devices at one specific site.

**Comment by roys10** [comment]
> > > Did you guys ever get to the bottom of this. I'm having a very similar issue with cisco NXOS switches. I have a list of switches to apply configuration to. I will get an authentication failure from netmiko for say switch 5, I run the script again, it works for switch 5 but fails on 6. run again and it makes it one more down the list to 7. every time it reports an authentication problem:
> > > line 972, in establish_connection raise NetmikoAuthenticationException(msg) netmiko.ssh_exception.NetmikoAuthenticationException: Authentication to device failed.
> > > Common causes of this problem are:
> > > 
> > > 1. Invalid username and password
> > > 2. Incorrect SSH-key file
> > > 3. Connecting to the wrong device
> > > 
> > > Device settings: cisco_nxos 10.50.1.9:22
> > > Authentication failed.
> > > very strange, feels more like an SSH key problem than authentication.
> > 
> > 
> > Hey I know it was a while ago but I am currently having the same problem, did you manage to fix it?
> 
> I put it down to some sort of issue with inconsistent TACACS+ response times from our ISE server, likely related to processing load. I implemented a workaround via a loop that just made up to 3 attempts to connect to a device before declaring it unreachable. I only encountered the issue with NXOS network devices at one specific site.

Thanks :)
For me this problem only occurs when I use threads to connect to the switches, do you remember if you used something similar?

**Comment by ktbyers** [comment]
@roys10 Yes, it is reasonably common for threads to overload the TACACS+ authentication/authorization system (i.e. the TACACS+ system becomes the bottleneck). I.E. the TACACS+ system can't handle the load and responds too slowly or with too much variation.
