### ISSUE TITLE
Telnet (cisco_ios_telnet) via SOCKS5 proxy timing out

### ISSUE THREAD

**Issue by elittleford2** [ktbyers/netmiko#2536]
Trying to Telnet to a Cisco switch via a SOCKS5 proxy, the connection always times out.

Code used to connect:
```
sock_proxy_telnet = socks.socksocket()
sock_proxy_telnet.set_proxy(
	proxy_type=socks.SOCKS5,
	addr="192.160.1.50",
	port=1080
)
sock_proxy_telnet.connect(('192.168.140.10', 23))
net_connect = ConnectHandler(
	host='192.168.140.10',
	device_type="cisco_ios_telnet",  # Use Telnet instead.
	username='my_username',
	password='my_password',
	fast_cli=False,
	sock=sock_proxy_telnet
)
show_version = net_connect.send_command('sh ver')
```
It sits on the ConnectHandler and times out, error:

> [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

I've confirmed that the socket is connecting via `sock_proxy_telnet.recv(1000)` (shows the login banner).

The above code works fine if I use port 22 on the .connect and cisco_ios on the device type.
I tried to debug it, but the global logging method doesn't generate any logs.

I can use PuTTy to connect via the SOCKS5 proxy and Telnet, so I think this is specific to how Netmiko handles the socket and Telnet.

Any help would be greatly appreciated.

**Comment by ktbyers** [comment]
What does the full exception stack trace look like?

**Comment by elittleford2** [comment]
Is there any way you're aware of to proxy and use Telnet with Netmiko? I've been loving Netmiko so far (just started using it this week)!

**Comment by krzysztoflawppl** [comment]
Hi,
I'm trying to have SSH connection to router via SOCKS5 proxy in Netmiko (Windows).
What else should be added into this script?
Where did you take socks.socksocket() from?

**Comment by ktbyers** [comment]
@krzysztoflawppl There is an example here:

https://github.com/ktbyers/netmiko/pull/1473

**Comment by krzysztoflawppl** [comment]
Hi Kirk,
It worked like a charm! Great stuff!
Best regards and Happy New Year!

Krzysztof

**Comment by IAseven** [comment]
I rewrote telnet in the standard library to make Telnet work with socks5 proxy. If necessary, I can contribute my code.

**Comment by ktbyers** [comment]
Probably not going to fix this. So I am closing this issue.
