### ISSUE TITLE
Junos - Sending Commit Confirm

### ISSUE THREAD

**Issue by ynysmeudwy** [ktbyers/netmiko#2539]
Hi, I appreciate that you can use this to commit config to a juniper device:

net_connect.commit()

Does netmiko have the ability to send the commit confirm {minutes}? I'm looking into this at the moment and my code looks like this:

net_conn.send_command_timing('commit confirm 5')

Thanks

**Comment by ktbyers** [comment]
Yeah, just send in the `confirm` and `confirm_delay` arguments see:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/juniper/juniper.py#L91
