### ISSUE TITLE
SFTP support for IOS-XR

### ISSUE THREAD

**Issue by bewing** [ktbyers/netmiko#255]
Would it be possible to expose the SFTP subsystem in the CiscoXrSSH object?  I can't seem to get SCP to work via netmiko or paramiko, but am able to transfer files directly to a router using paramiko's SFTP subsystem -- would be good to have it available in netmiko as well, instead of opening separate SSH connections for file transfers.

**Comment by ktbyers** [comment]
@bewing Can you post some reference code for this or submit a PR on it.

**Comment by bewing** [comment]
So I dug into both sets of sources a little bit more. 

It looks like in Netmiko, the SCP "channel" is really just a new paramiko object/SSH connection that we copy a bunch of connection settings from the netmiko object.

In paramiko, you can open the SFTP subsystem on a new or existing connection via the transport object, which I don't think currently has a clear analog in the netmiko code.

Best approach might be similar to how SCP is handled -- create a wrapper class that calls SFTP object and exposes get/put methods.

I'll try to put together a pull request if I have time in the next few weeks, but in the meantime, using paramiko does appear to work for small files, but I'm running into issues pushing around binaries due to https://github.com/paramiko/paramiko/issues/151

**Comment by ktbyers** [comment]
Okay, sounds good.

**Comment by nkaliape** [comment]
@bewing @ktbyers Did we bring sftp enhancement into netmiko?

**Comment by ktbyers** [comment]
@nkaliape Nope.
