### ISSUE TITLE
Exception: Incompatible ssh peer (no acceptable host key)

### ISSUE THREAD

**Issue by luweijun1992** [ktbyers/netmiko#2556]
netmiko            3.4.0

@ktbyers Please help me see why I can't connect to the device
---
Exception: Incompatible ssh peer (no acceptable host key)
Traceback (most recent call last):
  File "C:\Users\Master\AppData\Roaming\Python\Python39\site-packages\paramiko\transport.py", line 2083, in run
    self._handler_table[ptype](self, m)
  File "C:\Users\Master\AppData\Roaming\Python\Python39\site-packages\paramiko\transport.py", line 2198, in _negotiate_keys
    self._parse_kex_init(m)
  File "C:\Users\Master\AppData\Roaming\Python\Python39\site-packages\paramiko\transport.py", line 2377, in _parse_kex_init
    raise SSHException(
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable host key)

**Comment by ktbyers** [comment]
You need to post your code and the device type you are connecting to.

Also you probably need the Netmiko log file so know what requirements the network device is asserting.



Kirk

**Comment by luweijun1992** [comment]
> You need to post your code and the device type you are connecting to.
> 
> Also you probably need the Netmiko log file so know what requirements the network device is asserting.
> 
> Kirk

It has been sorted out to be an algorithm problem. Just turn it on.
By default, when a device starts with factory settings, the RSA_SHA2_256, and RSA_SHA2_512 public key algorithm is enabled, and the RSA, ECC, and DSA algorithms are disabled.

![image](https://user-images.githubusercontent.com/58923704/139759453-252fce01-5265-4118-9559-0d5753766ca7.png)

**Comment by stvnkem** [comment]
> > You need to post your code and the device type you are connecting to.
> > Also you probably need the Netmiko log file so know what requirements the network device is asserting.
> > Kirk
> 
> It has been sorted out to be an algorithm problem. Just turn it on. By default, when a device starts with factory settings, the RSA_SHA2_256, and RSA_SHA2_512 public key algorithm is enabled, and the RSA, ECC, and DSA algorithms are disabled.
> 
> ![image](https://user-images.githubusercontent.com/58923704/139759453-252fce01-5265-4118-9559-0d5753766ca7.png)

Looks like a Huawei VRP device :) You can always troubleshoot such an issue by checking the logs or running the "display ssh server error" from diag view.

**Comment by ktbyers** [comment]
I will possibly try to implement a fix on the Netmiko side also so that factory default devices will work (i.e. we can change the allowed encryption/hashing algorithms).

**Comment by ktbyers** [comment]
@luweijun1992 Which vendor-platform is this?

**Comment by luweijun1992** [comment]
> @luweijun1992 Which vendor-platform is this?

Huawei CE Switch
https://support.huawei.com/enterprise/en/switches/cloudengine-58-68-78-88-98-pid-252837181

**Comment by Laurel-rao** [comment]
login huawei device with manager role
```
system-view
ssh server publickey rsa ecc dsa
save
```
problem resolved
