### ISSUE TITLE
 CLI Command Empty Output

### ISSUE THREAD

**Issue by soheer** [ktbyers/netmiko#2561]
Hello,

I'm using show interfaces counters cli command to get traffic on SF300 and SG300 28 port cisco switch interfaces. (using netmiko python library based on SSH connection)

It returns the data for the first few ports and then for the rest ones it returns an empty output knowing that there is actual data for those ports.At this point the connection with the switch is still alive, and after passing multiple ports with no results it breaks the connection.(sometimes the result returned for the missing ports is the command of the first port raising this missing data sequence)

 

Ex:

![image](https://user-images.githubusercontent.com/15982135/140072992-b9784b57-c1bd-4436-9be2-09c6a1ec5558.png)

in this example the command returns data for interfaces fa1,fa2 and fa3 then for fa4 it starts returning empty result(shown as empty list) then at interface fa6 the result returned is the command "show interfaces counters fa4"

This is a sample of my code:
```

ter_data = switch_connect.send_command_timing("terminal datadump")
if "SF302-08" in switch_model:
        ports_list_to_be_used = SF300_LIST
    elif "SG300-10" in switch_model:
        ports_list_to_be_used = SG300_10_LIST
    elif "SG300-28" in switch_model:
        ports_list_to_be_used = SG300_28_LIST
    for switch_port_name in ports_list_to_be_used:
        try:
            interfaces_counters = switch_connect.send_command_timing(
                f'show interfaces counters {switch_port_name}')
            print(interfaces_counters)
```

Can anyone helps us to figure whats going on?

 
Thanks in advance.

**Comment by ktbyers** [comment]
I wouldn't use send_command_timing for this--I would use `send_command`. send_command_timing will be prone to the problem you describe depending on the device's behavior.

**Comment by soheer** [comment]
I tried using send_command but I face the same problem. Is there any other option to fix this problem?

Thanks.

**Comment by ktbyers** [comment]
Can you get rid of your try/except and post the exception that you get with `send_command`.

**Comment by soheer** [comment]
Hello,

This is the error after removing try/except:

![image](https://user-images.githubusercontent.com/15982135/140701113-5c0e2da2-a5cb-44dd-9031-8ca84fda45f7.png)

Thanks in advance.

**Comment by ktbyers** [comment]
Purging old issues...
