### ISSUE TITLE
unable to send restart command for palo alto firewall

### ISSUE THREAD

**Issue by dhanapal242** [ktbyers/netmiko#2568]
unable to send reload command to palo alto firewall. following script i used it. I may be missing which i couldn't find out. please suggest a solution

**Script** 
from netmiko import ConnectHandler  
import getpass
import time  

f = open("firewall.txt", "r")
for ip in f:
    ip_address = ip
    print("Connecting to " + ip_address)
       
   
    user = input("username: ")
    password = getpass.getpass("password: ")
    palab = {
                'device_type': "paloalto_panos",
                'ip': ip_address,
                'username':user,
                'password': password,
                
        }
    
    connect = ConnectHandler(**palab)
    output = connect.send_command("request restart system", expect_string="(y or n)")
    print(output)
    output1 = connect.send_command_timing("y\n")
    print(output1)
    print("\nCompleted")

**Comment by David00** [comment]
What _specifically_ happens that makes you say "unable to send reload command"?

Without any tracebacks or even the output from your program, there's no way to help you.

**Comment by stvnkem** [comment]
I assume the expected string does not catch the output. I suggest disabling the prompt - if the device supports it - before sending the reboot command.

**Comment by dhanapal242** [comment]
sometime it is successful and sometime not, Please find the details below

**when it is successful, I'm getting following message (that's what expected) and firewall getting rebooted**

"Executing this command will disconnect the current session. Do you want to continue? (y or n)

Broadcast Message from root (pts/0) (Tue Nov 9 12:33:14 2021):

The system is going down for reboot NOW!

Completed"

**when it is un-successful, getting following message but firewall not getting rebooted**

"Executing this command will disconnect the current session. Do you want to continue? (y or n)

Completed"

**Comment by dhanapal242** [comment]
> I assume the expected string does not catch the output. I suggest disabling the prompt - if the device supports it - before sending the reboot command.

sorry I don't understand,  I'm not sure how to disable prompt , restart command only work in user prompt and if we disable it how we can execute the command ?

**Comment by dhanapal242** [comment]
> What _specifically_ happens that makes you say "unable to send reload command"?
> 
> Without any tracebacks or even the output from your program, there's no way to help you.

sometime it is successful and sometime not, Please find the details below

when it is successful, I'm getting following message (that's what expected) and firewall getting rebooted

"Executing this command will disconnect the current session. Do you want to continue? (y or n)

Broadcast Message from root (pts/0) (Tue Nov 9 12:33:14 2021):

The system is going down for reboot NOW!

Completed"

when it is un-successful, getting following message but firewall not getting rebooted

"Executing this command will disconnect the current session. Do you want to continue? (y or n)

Completed"

**Comment by ktbyers** [comment]
@dhanapal242 The only issue I see in your code is here:

```python
output = connect.send_command("request restart system", expect_string="(y or n)")
```

The `expect_string` is a regular expression and parenthesis have special meaning in regex. I would probably change the expect_string to be `expect_string=r"y or no"`.

This might not be your issue as it doesn't really explain what you are seeing, but I would start with that.

**Comment by dhanapal242** [comment]
> @dhanapal242 The only issue I see in your code is here:
> 
> ```python
> output = connect.send_command("request restart system", expect_string="(y or n)")
> ```
> 
> The `expect_string` is a regular expression and parenthesis have special meaning in regex. I would probably change the expect_string to be `expect_string=r"y or no"`.
> 
> This might not be your issue as it doesn't really explain what you are seeing, but I would start with that.

I tried with that but it is not working. when we use regex do i need to import re ?

**Comment by ktbyers** [comment]
No, you shouldn't need to import re (as you are not using the re library in your code, re is used inside of Netmiko).

Try adding a session_log:

```
palab = {
            'device_type': "paloalto_panos",
            'ip': ip_address,
            'username':user,
            'password': password,
            'session_log': 'pa_output.txt',
    }
```

And see if that gives you any clues as to why it fails.

An alternate solution would be to just use send_command_timing() for the `request restart system` and see if that helps fix your problem.


Regards, Kirk

**Comment by ktbyers** [comment]
Purging old issues...
