### ISSUE TITLE
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by CrazyPigHead** [ktbyers/netmiko#2569]
I use `ConnectHandler.send_config_set` to set juniper config:

set interfaces ae30 unit 2943 vlan-id 2943
delete interfaces ae30 unit 2943 disable
delete interfaces ae30 unit 2943 family inet policer
delete interfaces ae30 unit 2943 family inet6 policer
set interfaces ae30 unit 2943 family inet policer input 5m
set interfaces ae30 unit 2943 family inet policer output 5m
set interfaces ae30 unit 2943 family inet6 policer input 5m
set interfaces ae30 unit 2943 family inet6 policer output 5m
set interfaces ae30 unit 2943 family inet address 111.11.11.111/30
set firewall family inet filter *************-018-c87a173b-1445-493a-bdd6-ad7a0267cb9f term 1 from source-address 111.11.11.110/30
set firewall family inet filter *************-018-c87a173b-1445-493a-bdd6-ad7a0267cb9f term 1 from destination-address 111.11.11.111/32
set firewall family inet filter *************-018-c87a173b-1445-493a-bdd6-ad7a0267cb9f term 1 then accept
set firewall family inet filter *************-018-c87a173b-1445-493a-bdd6-ad7a0267cb9f term 6 from source-address 111.11.11.110/30
set firewall family inet filter *************-018-c87a173b-1445-493a-bdd6-ad7a0267cb9f term 6 then routing-instance vrf-name
insert firewall family inet filter *************-018-c87a173b-1445-493a-bdd6-ad7a0267cb9f term 1 before term 1001
insert firewall family inet filter *************-018-c87a173b-1445-493a-bdd6-ad7a0267cb9f term 6 before term 1001

but sometimes it's error, the session_log is:
![16365305222630](https://user-images.githubusercontent.com/48537720/141071692-875e7a63-482c-4e79-81ea-915cd639e814.png)

this is my error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/service/subtask_handler/executor/juniper.py", line 66, in execute
    output = self.s.send_config_set(config_commands=commands, exit_config_mode=False, config_mode_command="configure exclusive")
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1912, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 584, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

my version is 3.4.0

**Comment by ktbyers** [comment]
On the `why double` question, it is likely because the device is `re-painting` the line when it is exceeded a certain line length. It does this to make it more readable to humans.

Or worded differently, it is essentially echoing the line more than once to the screen.

On your error, try adding the following argument to send_config_set: `cmd_verify=False`

**Comment by CrazyPigHead** [comment]
![16370275121830](https://user-images.githubusercontent.com/48537720/141881368-9739b70e-5ea3-4a41-9b71-aa863f87a0d9.png)
When I modify it from 511 to 51, it always raise the same error:
![16370277691799](https://user-images.githubusercontent.com/48537720/141881655-285e2ebe-3b77-4ebf-8d0f-41338f7c9683.png)
After i add the argument `cmd_verify=False`, it still error.

**Comment by ktbyers** [comment]
Why are you changing the screen-width to 51?

**Comment by CrazyPigHead** [comment]
I want to test if the device will re-paint the line when it is exceeded a certain line length, now it seems to be.

**Comment by ktbyers** [comment]
Yes, your changing this is breaking the `set cli complete-on-space off` that comes shortly after this.
