### ISSUE TITLE
Timing out on authentication if primary auth is unavailable

### ISSUE THREAD

**Issue by ghmj2417** [ktbyers/netmiko#257]
In certain circumstances a user may use TACACS, RADIUS, etc as their primary authentication service (with local being their backup).  In normal operation this should work fine.  In the event TACACS or RADIUS is unavailable there will be a delay in authentication.  Even though we can set a timeout for SSH being established, we cannot set a timeout for authentication success.  I have tested this a few times and I always receive an exception of NetMikoTimeoutException("Timed out waiting for recv_ready").  

base_connection.py, on establish_connection, this gets called; if self.wait_for_recv_ready_newline():
The problem is there is no way for a user to customize the wait time for initial authentication.  I would ask either use the timeout value set, or allow us to use global_delay_factor.

Using Cisco device configured for two RADIUS servers with a timeout of 2 and retransmit of 2.  I use RADIUS as the primary and local as the backup.

**Comment by ktbyers** [comment]
Good idea. Let's add this to the dev_1_0 issues and see if it can be fixed there.

**Comment by ktbyers** [comment]
@ghmj2417 Where exactly do you think a delay needs introduced to fix your above problem?

**Comment by ghmj2417** [comment]
@ktbyers Hmm.  I know the issue occurs in establish_connection at (if self.wait_for_recv_ready_newline():) so it's in that function.  I doubt modifying max_loops would do anything because your max wait time appears to be 8 seconds (I don't think it ever hits this amount with the max_loops being only 20).  Maybe we should focus on delay_factor.  This is where I thought global_delay_factor could be used.

One option; use user assigned global_delay_factor at init, at the beginning of the function (wait_for_recv_ready_newline()) add  delay_factor = self.select_delay_factor(delay_factor) and increase your if delay_factor >= 8: to 20 (or get rid of this check entirely because I don't see why you would want to cap this.)

Second option; Increase max_loops to something much larger and increase the if delay_factor >= 8 to 20, or remove this check entirely.

Third option; remove delay_factor and use the timeout set by the user.  Since this function is only called from establish_connection, it may make sense to use the timeout.

**Comment by ktbyers** [comment]
@ghmj2417 Okay, that code is pretty much all changed in the new dev_1_0 branch (the entire wait_for_recv_ready_newline() method doesn't exist).

https://github.com/ktbyers/netmiko/blob/dev_1_0/netmiko/base_connection.py

So the question is...where should extra sleep be added for devices that take excessively long times to log in. Probably in the session_preparation() method.

**Comment by ghmj2417** [comment]
*face palm* sorry I didn't even stop to think this is for 1.0.  I'll take a look soon.

**Comment by ktbyers** [comment]
@ghmj2417 It is all good. I have just changed a lot that pertains to this so we need to make sure we put the sleep at the proper location (in the new code).

**Comment by ghmj2417** [comment]
I believe this part would need to be modified.  You need to give more time to make sure authentication succeeds.  It can take awhile (sometimes 30 seconds) if TACAS, RADIUS, etc aren't available.

###  In establish_connection()
        i = 0
        delay_factor = self.select_delay_factor(delay_factor=0)
        main_delay = delay_factor * .1
        time.sleep(main_delay)
        while i <= 20:
            new_data = self._read_channel()
            if new_data:
                break
            else:
                self.write_channel('\n')
                main_delay = main_delay * 1.1
                if main_delay >= 8:
                    main_delay = 8
                time.sleep(main_delay)
                i += 1

**Comment by ghmj2417** [comment]
What is weird is I would expect the exception to be raised here....but it never was.  Which means somewhere netmiko thought I was authenticated or I actually was authenticated.  It wasn't till after this section on the wait_for_recv_ready_newline() function where I received an exception.

### initiate SSH connection
            try:
                self.remote_conn_pre.connect(**ssh_connect_params)
            except socket.error:
                msg = "Connection to device timed-out: {device_type} {ip}:{port}".format(
                    device_type=self.device_type, ip=self.host, port=self.port)
                raise NetMikoTimeoutException(msg)
            except paramiko.ssh_exception.AuthenticationException as auth_err:
                msg = "Authentication failure: unable to connect {device_type} {ip}:{port}".format(
                    device_type=self.device_type, ip=self.host, port=self.port)
                msg += '\n' + str(auth_err)
                raise NetMikoAuthenticationException(msg)

**Comment by ktbyers** [comment]
@ghmj2417 Yes, your later comment means that SSH thinks it is authenticated (the underlying Paramiko driver). I would guess this is a function of how the underlying RADIUS/TACACS+ works so probably not something we can change.
