### ISSUE TITLE
Timeouts after exactly 60 different logins via Python

### ISSUE THREAD

**Issue by purplepacketpusher** [ktbyers/netmiko#2570]
I have a script that clears ARP entries in Cisco IOS routers. Four routers, each one gets logged into via netmiko in each pass. I issue a show arp, clear arp, ping, and show arp command for an IP address (doing website migrations to a new set of firewalls). After exactly fifteen logins to each router in sequence every time I run the script (for a total of exactly 60 successful connections), every connection attempt fails with a connection timeout error.

**Comment by ktbyers** [comment]
That is a bit strange...Netmiko shouldn't care and doesn't even track it--so the question would be what cares about the previous connections. Common things that this might be:
1. Your TACACS+ server
2. Maybe ulimit settings on your automation server.

Those are the two things I would probably look into.

**Comment by purplepacketpusher** [comment]
> 
> 
> That is a bit strange...Netmiko shouldn't care and doesn't even track it--so the question would be what cares about the previous connections. Common things that this might be:
> 
>     1. Your TACACS+ server
> 
>     2. Maybe ulimit settings on your automation server.
> 
> 
> Those are the two things I would probably look into.

To answer your numbered questions...

1. The TACACS server is not at issue. It checks out entirely. I am the admin on it, so I know it's not having issues. 
2. There is no automation server. I run this manually on my Windows 10 laptop when we are migrating websites from one set of firewalls to another. Not run during from an automated process.

I can stop the script when it starts timing out and re-run it from that point in the data file, and it has no problem for another sixty logins. At that point, it will start timing out again.

I suspect it is a memory overflow or out of memory issue of some kind.

**Comment by ktbyers** [comment]
What exception do you get when it fails?

**Comment by purplepacketpusher** [comment]
> 
> 
> What exception do you get when it fails?

It throws the NetMikoTimeoutException, but it does it instantly, as soon as it tries to connect.

**Comment by ktbyers** [comment]
I need the full exception stack trace to see where it is failing at (this provides evidence as to what is causing the problem).

**Comment by purplepacketpusher** [comment]
Not sure how to get that. Its a Python script. Suggestions?-PeteSent from my mobile.
-------- Original message --------From: Kirk Byers ***@***.***> Date: 11/16/21  6:13 PM  (GMT-06:00) To: ktbyers/netmiko ***@***.***> Cc: purplepacketpusher ***@***.***>, Author ***@***.***> Subject: Re: [ktbyers/netmiko] Timeouts after exactly 60 different logins via Python (Issue #2570) 
I need the full exception stack trace to see where it is failing at (this provides evidence as to what is causing the problem).

**Comment by Tes3awy** [comment]
Hello @purplepacketpusher,

I am quoting your question as you said after exactly15 logins every connection attempt fails with a connection timeout error.

> After exactly fifteen logins to each router in sequence every time I run the script (for a total of exactly 60 successful connections), every connection attempt fails with a connection timeout error.

Most probably line(s) vty are not cleared because you don't disconnect.

You have two options to clear the line vty _(close the session)_

1. use `.disconnect()`
2. use context manager (`with statement`) (Recommended)

**Option 1**

```python
from netmiko import ConnectHandler

devices = [
    {
        "device_type": "cisco_ios",
        "ip": "192.168.1.1",
        "username": "cisco",
        "password": "cisco",
        "secret": "cisco",
        "fast_cli": False,
    },
    {
        "device_type": "cisco_ios",
        "ip": "192.168.1.2",
        "username": "cisco",
        "password": "cisco",
        "secret": "cisco",
        "fast_cli": False,
    },
]

for device in devices:
    net_connect = ConnectHandler(**device)
    net_connect.send_command("show ip arp")
    net_connect.send_command("clear arp")
    net_connect.send_command("ping 172.16.1.1")
    net_connect.send_command("show ip arp 172.16.1.1")
    net_connect.disconnect()
    # print after net_connect.disconnect() closes the connection
    print(f"{device['ip']}: Session closed")
```

**Option 2 (Recommended)**

```python
from netmiko import ConnectHandler

devices = [
    {
        "device_type": "cisco_ios",
        "ip": "192.168.1.1",
        "username": "cisco",
        "password": "cisco",
        "secret": "cisco",
        "fast_cli": False,
    },
    {
        "device_type": "cisco_ios",
        "ip": "192.168.1.2",
        "username": "cisco",
        "password": "cisco",
        "secret": "cisco",
        "fast_cli": False,
    },
]

for device in devices:
    # context manager will automatically close the connection
    with ConnectHandler(**device) as net_connect:
        net_connect.send_command("show ip arp")
        net_connect.send_command("clear arp")
        net_connect.send_command("ping 172.16.1.1")
        net_connect.send_command("show ip arp 172.16.1.1")
    # print after the context manager closes the connection
    # notice the print statement is de-dented and therefore is not part of the with/as block
    print(f"{device['ip']}: Session closed")
```

**Comment by purplepacketpusher** [comment]
This makes sense. Kind of a newbie to all this, and when I looked at my code, I am not closing the connection. Live and learn, eh?Most likely I have saturated/consumed all available outbound sessions by not closing the connections properly. Oopsie!I will implement one of these methods when I get back online after my holiday vacation next Monday and report back on what happened.Thanks for all your help!-PeteSent from my mobile.
-------- Original message --------From: Osama Abbas ***@***.***> Date: 12/25/21  8:24 AM  (GMT-06:00) To: ktbyers/netmiko ***@***.***> Cc: purplepacketpusher ***@***.***>, Mention ***@***.***> Subject: Re: [ktbyers/netmiko] Timeouts after exactly 60 different logins via Python (Issue #2570) 
Hello @purplepacketpusher,
I am quoting your question as you said after exactly15 logins every connection attempt fails with a connection timeout error.

After exactly fifteen logins to each router in sequence every time I run the script (for a total of exactly 60 successful connections), every connection attempt fails with a connection timeout error.

Most probably line(s) vty are not cleared because you don't disconnect.
You have two options to clear the line vty (close the session)

use .disconnect()
use context manager (with statement) (Recommended)

Option 1
from netmiko import ConnectHandler

devices = [
    {
        "device_type": "cisco_ios",
        "ip": "192.168.1.1",
        "username": "cisco",
        "password": "cisco",
        "secret": "cisco",
        "fast_cli": False,
    },
    {
        "device_type": "cisco_ios",
        "ip": "192.168.1.2",
        "username": "cisco",
        "password": "cisco",
        "secret": "cisco",
        "fast_cli": False,
    },
]

for device in devices:
    net_connect = ConnectHandler(**device)
    net_connect.send_command("show ip arp")
    net_connect.send_command("clear arp")
    net_connect.send_command("ping 172.16.1.1")
    net_connect.send_command("show ip arp 172.16.1.1")
    net_connect.disconnect()
    # print after net_connect.disconnect() closes the connection
    print(f"{device['ip']}: Session closed")
Option 2 (Recommended)
from netmiko import ConnectHandler

devices = [
    {
        "device_type": "cisco_ios",
        "ip": "192.168.1.1",
        "username": "cisco",
        "password": "cisco",
        "secret": "cisco",
        "fast_cli": False,
    },
    {
        "device_type": "cisco_ios",
        "ip": "192.168.1.2",
        "username": "cisco",
        "password": "cisco",
        "secret": "cisco",
        "fast_cli": False,
    },
]

for device in devices:
    # context manager will automatically close the connection
    with ConnectHandler(**device) as net_connect:
        net_connect.send_command("show ip arp")
        net_connect.send_command("clear arp")
        net_connect.send_command("ping 172.16.1.1")
        net_connect.send_command("show ip arp 172.16.1.1")
    # print after the context manager closes the connection
    # notice the print statement is de-dented and therefore is not part of the with/as block
    print(f"{device['ip']}: Session closed")

**Comment by ktbyers** [comment]
I am going to close this as it looks resolved. Just re-open it if there is still an outstanding issue.
