### ISSUE TITLE
Adtran ValueError: Failed to enter enable mode. 

### ISSUE THREAD

**Issue by jhodie** [ktbyers/netmiko#2573]
I am running into an issue when trying to get into an Adtran TA5004.

It comes up with the error
 `ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.`

Here is the code I am using to try and send the commands
```
from netmiko import ConnectHandler

olt = {
        'device_type': 'adtran_os',
        'ip': '10.0.0.10',
        'username': 'ADMIN',
        'password': 'PASSWORD',
        'secret': '',
        'session_log': 'adtran_output.txt'
}

config_commands = ['do show system parameters']
print(config_commands)

all_devices = [olt]
for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    net_connect.enable()
    output = net_connect.send_config_set(config_commands)
    print(output)
```

Have also got a session log if that helps
```
Last Login Date      : Jan  1 2000 00:46:17 
Last Login Type      : IP Session(CLI) 
Login Failures       : 0 (Since Last Login)
                     : 4 (Total for Account)
>
>terminal length 0
>
>
```

The OLT doesn't have a secret enabled, and just seems like there is an issue with using `net_connect.enable()` on the device, it doesn't seem to be grabbing the `secret` value
Thinking it might be down to the OLT having a different command dictionary compared to regular AOS, but I'm not 100% on that

Sorry if this has been answered before and I missed it

**Comment by ktbyers** [comment]
Can you post the full exception stack trace?

Why are you going into config-mode, to execute a show command?

**Comment by ktbyers** [comment]
@jhodie 

It looks like it is failing here:

https://github.com/ktbyers/netmiko/blob/v3.4.0/netmiko/base_connection.py#L1704

On your device that is failing, what does the CLI look like when you type `enable` and hit enter?

Related pull request where the adtran behavior changed:

https://github.com/ktbyers/netmiko/pull/2019

**Comment by ktbyers** [comment]
The Netmiko driver is definitely intended to be for `Adtran OS`.

**Comment by jhodie** [comment]
It looks slightly different to that pull request as it doesn't ask for a password, it goes straight into enable mode
```
>enable
#
```
