### ISSUE TITLE
Double SSH proxy support

### ISSUE THREAD

**Issue by RenanHingel** [ktbyers/netmiko#2574]
Hello,

I'm trying to solve a puzzle to achieve the following scenario:

Script Server -> Intermediate Server 1 ->  Intermediate Server 2 -> Device Under Management

After reading Kirk's article https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html I understood it is possible to achieve the above, but with only one intermediate server.

Any ideas on how to successfully manage the device behind two intermediate servers?

**Comment by ktbyers** [comment]
@RenanHingel I don't have a good solution to this.

Ultimately, using Netmiko you could SSH bounce through every server and then connect to the end device (you should use `redispatch()` to change the Netmiko class when you get to the end device).

You would have to write a bunch of glue-code to make this work, however.
