### ISSUE TITLE
Issues with newer Dell OS. OS10.5.2.7

### ISSUE THREAD

**Issue by parkerschoenig** [ktbyers/netmiko#2578]
I've been experiencing issues with Dell OS10.5.2.7

I have a script to autodetect Dell OS, send_config_set to change config parameters of the switch. This worked on a list of switches running Dell OS 10.4.3, and Dell OS 9.

Now, on some new switches running Dell OS10.5.2.7, autodetect still works and detects Dell OS10 and logs in successfully. However, I cannot send a command with send_config_set anymore, or send_command - it just times out with "Timed-out reading channel, data not available." I have tried setting cmd_verify=False as well. 

Also, if I change the password and user priv on the switch for the admin account, netmiko can no longer autodetect.
ex: 
# config() username admin password fakepassword userrole sysadmin priv-lvl 15

once this command is issued via console netmiko will no longer autodetect the OS. but if I blow away the config and reload netmiko will autodetect the OS. 

This is not an issue on 10.4.3

I have been looking thru cisco_base_connection.py as I noticed DellOS10SSH.py calls it, but I cannot see anything that would cause this issue. 

also for autodetect, I do have OS10 listed at the top of the list with show version as the cmd. I found this fix a while ago, so we can rule that out. + it works with 10.4.3

all these commands work normally via console, not sure what has changed with OS10.5.2.7

**Comment by ktbyers** [comment]
Probably need to work on these issues one at a time--so which one is most important from your perspective?

**Comment by parkerschoenig** [comment]
> Probably need to work on these issues one at a time--so which one is most important from your perspective?

Thanks for the quick reply. Right now I would say just the send_config_set / trying to send commands. I could always issue a config command to change the admin password / privileges at the end of the script as a last resort.

**Comment by ktbyers** [comment]
What is the exception you receive when using `send_config_set`?

On this failing 10.5.2.7 OS, can you show what the CLI looks like for entering/exiting configuration mode and for sending configuration commands. In other words, just show an example screen output here.

**Comment by parkerschoenig** [comment]
The exception I am getting is: **Timed out reading channel, data not available** when trying to issue send_config_set('hostname test')

Screen output: logging in, going into config mode, changing the hostname, exiting config mode, issuing show version.

This product is protected by U.S. and international copyright and
intellectual property laws. Dell EMC and the Dell EMC logo are
trademarks of Dell Inc. in the United States and/or other
jurisdictions. All other marks and names mentioned herein may be
trademarks of their respective companies.

%Warning : Default password for admin account should be changed to secure the system
%Warning : Default password for linuxadmin account should be changed to secure the system.
OS10# configure terminal
OS10(config)# hostname test
test(config)# exit
test# show version
Dell EMC Networking OS10 Enterprise
Copyright (c) 1999-2021 by Dell Inc. All Rights Reserved.
OS Version: 10.5.2.7
Build Version: 10.5.2.7.374
Build Time: 2021-07-28T04:48:16+0000
System Type: S3048-ON
Architecture: x86_64
Up Time: 01:08:35
test#

**Comment by ktbyers** [comment]
I need the full exception stack trace so I can see where it is failing at.

**Comment by ramonbrugman** [comment]
-

**Comment by ktbyers** [comment]
Is your `send_config_set()` change in your code actually changing the hostname?

Changing the hostname can be a bit of a special case since it changes the device prompt.

**Comment by parkerschoenig** [comment]
My apologies - this turned out to be user error. After some troubleshooting I am able to run the script with no problems from my IDE, I receive the errors when running from python on my CMD prompt. I am assuming this is a path issue on my end. I overlooked this.

**Comment by ktbyers** [comment]
Okay, so is there any issue here or can we close this?

**Comment by parkerschoenig** [comment]
No this can be closed
