### ISSUE TITLE
Mellanox and breaking out of a continuous ping

### ISSUE THREAD

**Issue by shreyaspandey** [ktbyers/netmiko#2583]
So I am using netmiko to SSH into mellanox switch. I am then pinging a server from inside the switch using

`net_connect.send_command('ping '+ilo_ip)`

But the problem is the ping is not stopping and the code is just stuck and is not moving forward.

I tried using write_channel instead of send_command but I get the output 'None' and then code just stuck there.

`net_connect.write_channel('ping '+ilo_ip)`
 
I also tried

`"fast_cli": False`

using it inside ConnectHandler inputs, but I didnt see any change.

Let me know how to use ping and get success or fail message using netmiko. Thanks!

**Comment by ktbyers** [comment]
What is the behavior of the Mellanox Switch CLI when you execute:

```
ping $IP
```

i.e. does it stop on its own after a certain number of pings or do you have to break out of it.

**Comment by shreyaspandey** [comment]
Yes when I am doing ping $IP using CLI the ping doesn't stop.

**Comment by shreyaspandey** [comment]
j3norpr01imasw01 [standalone: master] > ping 10.41.217.102
PING 10.41.217.102 (10.41.217.102) 56(84) bytes of data.
64 bytes from 10.41.217.102: icmp_seq=1 ttl=255 time=0.334 ms
64 bytes from 10.41.217.102: icmp_seq=2 ttl=255 time=0.374 ms
64 bytes from 10.41.217.102: icmp_seq=3 ttl=255 time=0.448 ms
64 bytes from 10.41.217.102: icmp_seq=4 ttl=255 time=0.431 ms
64 bytes from 10.41.217.102: icmp_seq=5 ttl=255 time=0.425 ms
64 bytes from 10.41.217.102: icmp_seq=6 ttl=255 time=0.367 ms
64 bytes from 10.41.217.102: icmp_seq=7 ttl=255 time=0.395 ms
64 bytes from 10.41.217.102: icmp_seq=8 ttl=255 time=0.407 ms
64 bytes from 10.41.217.102: icmp_seq=9 ttl=255 time=0.331 ms
64 bytes from 10.41.217.102: icmp_seq=10 ttl=255 time=0.370 ms
64 bytes from 10.41.217.102: icmp_seq=11 ttl=255 time=0.399 ms
64 bytes from 10.41.217.102: icmp_seq=12 ttl=255 time=0.401 ms
64 bytes from 10.41.217.102: icmp_seq=13 ttl=255 time=0.409 ms
64 bytes from 10.41.217.102: icmp_seq=14 ttl=255 time=0.376 ms
64 bytes from 10.41.217.102: icmp_seq=15 ttl=255 time=0.418 ms
64 bytes from 10.41.217.102: icmp_seq=16 ttl=255 time=0.440 ms
64 bytes from 10.41.217.102: icmp_seq=17 ttl=255 time=0.400 ms
64 bytes from 10.41.217.102: icmp_seq=18 ttl=255 time=0.368 ms
64 bytes from 10.41.217.102: icmp_seq=19 ttl=255 time=0.426 ms
64 bytes from 10.41.217.102: icmp_seq=20 ttl=255 time=0.362 ms
64 bytes from 10.41.217.102: icmp_seq=21 ttl=255 time=0.405 ms
64 bytes from 10.41.217.102: icmp_seq=22 ttl=255 time=0.517 ms
64 bytes from 10.41.217.102: icmp_seq=23 ttl=255 time=0.423 ms
64 bytes from 10.41.217.102: icmp_seq=24 ttl=255 time=0.400 ms
64 bytes from 10.41.217.102: icmp_seq=25 ttl=255 time=0.376 ms
64 bytes from 10.41.217.102: icmp_seq=26 ttl=255 time=0.312 ms
64 bytes from 10.41.217.102: icmp_seq=27 ttl=255 time=0.346 ms
64 bytes from 10.41.217.102: icmp_seq=28 ttl=255 time=0.382 ms
64 bytes from 10.41.217.102: icmp_seq=29 ttl=255 time=0.373 ms
64 bytes from 10.41.217.102: icmp_seq=30 ttl=255 time=0.385 ms
64 bytes from 10.41.217.102: icmp_seq=31 ttl=255 time=0.395 ms
64 bytes from 10.41.217.102: icmp_seq=32 ttl=255 time=0.393 ms
64 bytes from 10.41.217.102: icmp_seq=33 ttl=255 time=0.411 ms
64 bytes from 10.41.217.102: icmp_seq=34 ttl=255 time=0.401 ms
64 bytes from 10.41.217.102: icmp_seq=35 ttl=255 time=0.381 ms
64 bytes from 10.41.217.102: icmp_seq=36 ttl=255 time=0.426 ms
64 bytes from 10.41.217.102: icmp_seq=37 ttl=255 time=0.395 ms
64 bytes from 10.41.217.102: icmp_seq=38 ttl=255 time=0.354 ms
64 bytes from 10.41.217.102: icmp_seq=39 ttl=255 time=0.345 ms
64 bytes from 10.41.217.102: icmp_seq=40 ttl=255 time=0.346 ms
64 bytes from 10.41.217.102: icmp_seq=41 ttl=255 time=0.437 ms

**Comment by ktbyers** [comment]
@shreyaspandey So you probably would need to do one of the following:

1. Send a ping command that completes after a certain number of pings.
2. Use netmiko write_channel() to send the ping command and then use Netmiko write_channel again (after a sleep) to break out of the ping. In other words, replicate what you do when you manually ping. Use read_channel() after you have broken out of the ping to read the data.

send_command() won't work in this case as it is expecting the device's prompt to be returned which doesn't happen here.

**Comment by shreyaspandey** [comment]
Thanks @ktbyers!

1) I am not sure what is the command to send ping with specific number.

2) I tried write_channel() and it gave me output as 'None' and then the code stuck.
I do a Ctrl+C to get out of the ping.
But say if I get out of the ping how will I get the output of the ping as I have already came out of the command?

Is there any example you can post here or guide me through to see how it works?

Thanks again!

**Comment by ktbyers** [comment]
@shreyaspandey Can you post your code from the above?

**Comment by shreyaspandey** [comment]
I am doing this now.

   ```
 net_connect.write_channel('ping 10.41.217.102')   
    time.sleep(0.5)
   # net_connect.write_channel(CNTL_SHIFT_6)
    output = net_connect.read_channel()
    print(output)
    net_connect.write_channel("\n")
    time.sleep(0.1)
    net_connect.clear_buffer()
    print("Hi")
    print(output)
```

And the output below is 

```
ping 10.41.217.102
Hi
ping 10.41.217.102
```

So I am getting the output as the command I ran not the result of the command.

Also code just gets stuck after 2nd 'ping 10.41.217.102' output.

**Comment by shreyaspandey** [comment]
@ktbyers , I made some more adjustment in the code.
I am seeing ping message now.
But the code stuck and got below error.

Below is my sample code.

```
    net_connect.write_channel('ping 10.41.217.102')   #write code to ping just once when using that ilo for the first time
    time.sleep(0.5)
   # net_connect.write_channel(CNTL_SHIFT_6)
    output = net_connect.read_channel()
    print(output)
    net_connect.write_channel("\r\n")
    time.sleep(0.1)
    output = net_connect.read_channel()
    print(output)
    net_connect.clear_buffer()
    print("Hi")
   # output = net_connect.read_channel()
   # print(output)
    output=net_connect.send_command('show lldp remote | inc '+mac_address)

```

```
ping 10.41.217.102

PING 10.41.217.102 (10.41.217.102) 56(84) bytes of data.
64 bytes from 10.41.217.102: icmp_seq=1 ttl=255 time=0.333 ms

Hi
Traceback (most recent call last):
  File "./verify_switch_server.py", line 236, in <module>
    main()
  File "./verify_switch_server.py", line 192, in main
    interface,speed=get_switch_interface_and_speed(asw_ip,interface_mac_address,ipv4_ilo) #get asw dict here from another module
  File "./verify_switch_server.py", line 101, in get_switch_interface_and_speed
    output=net_connect.send_command('show lldp remote | inc '+mac_address)
  File "/usr/local/lib/python3.6/site-packages/netmiko/utilities.py", line 429, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1525, in send_command
    search_pattern
OSError: Search pattern never detected in send_command: 64\ bytes\ from\ 10\.41\.217\.102\:\ icmp_seq\=2\ ttl\=255\ time\=0\.389\ ms
```

**Comment by ktbyers** [comment]
Yeah, cntl_shift_6 probably isn't the character you need. Typically this is more cntl-c (which you will have to look up what it is in ascii).

So you. need to replicate what you do with keyboard and then code it into Netmiko.

You can just read_channel after you have sent cntl-c, all the data will be sitting there (provided you have done a time sleep to allocate enough time).

**Comment by shreyaspandey** [comment]
hi @ktbyers ,
I am not even using cntl_shift_6. As you can see the line is commented out in the code.
 The problem is I am getting below error which instead it should run the command (`output=net_connect.send_command('show lldp remote | inc '+mac_address)

```
Traceback (most recent call last):
  File "./verify_switch_server.py", line 236, in <module>
    main()
  File "./verify_switch_server.py", line 192, in main
    interface,speed=get_switch_interface_and_speed(asw_ip,interface_mac_address,ipv4_ilo) #get asw dict here from another module
  File "./verify_switch_server.py", line 101, in get_switch_interface_and_speed
    output=net_connect.send_command('show lldp remote | inc '+mac_address)
  File "/usr/local/lib/python3.6/site-packages/netmiko/utilities.py", line 429, in wrapper_decorator
    return func(self, *args, **kwargs)
  **File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1525, in send_command
    search_pattern
OSError: Search pattern never detected in send_command: 64\ bytes\ from\ 10\.41\.217\.102\:\ icmp_seq\=2\ ttl\=255\ time\=0\.389\ ms**
```


As you can see in my earlier message I am getting the output of the ping but then it is throwing up above error.

```
ping 10.41.217.102

PING 10.41.217.102 (10.41.217.102) 56(84) bytes of data.
64 bytes from 10.41.217.102: icmp_seq=1 ttl=255 time=0.333 ms

Hi
```

I am not sure why that error is coming up? What is the issue there?

**Comment by ktbyers** [comment]
Yes, you need to send some sequence to break out of the ping (or else the ping will just continue indefinitely as per your previous statements).

You cannot send the subsequent send_command() as your ping is still going on.
