### ISSUE TITLE
Guess device type

### ISSUE THREAD

**Issue by bbkane** [ktbyers/netmiko#259]
Thank you for netmiko. I really like it. 

One thing that would be very useful is a 'guess_device_type' argument for the [ssh_dispatcher](https://github.com/ktbyers/netmiko/blob/master/netmiko/ssh_dispatcher.py#L91) function. If this is passed, it would try to guess the device type (perhaps by sending 'show version' and parsing the output) then return the appropriate Connection class. Then I could use code like:

```python
net_connect = ConnectHandler(device_type='guess_device_type', **other_options)
if net_connect.device_type == 'cisco_ios':
    print('This device is an IOS device')
    do_ios_stuff(net_connect)
elif net_connect.device_type == 'cisco_nxos':
    print('This device is an NXOS device!')
    do_nxos_stuff(net_connect)
else:
    print('I only care about IOS or NXOS')
```

Would you be open to a pull request implementing such functionality?

**Comment by ktbyers** [comment]
@bbkane Sorry for slow response...forgot to respond to this earlier.

Yes, I don't think I want to try to support this. Basically the issue is that without knowing the device type, you basically run into problems before a 'show version' (or equivalent) can even be run.

Kirk

**Comment by bbkane** [comment]
Maybe netmiko could use some kind of exception to handle that:

```
try:
    net_connect = ...
except AmbiguousDeviceType:
    ...
except UnknownDeviceType:
    ...
else: # no exception
    ....
```

This would let folks like me, ignorant of many device types in my internal network, get some information to deal with them effectively and it wouldn't limit the people who do know their networks better. They get the same API they've always had. I haven't looked super carefully, but I don't really think it would bloat the code much either.

Anyway, thanks for the response. If you change your mind, please let me know and I'll try to start work on it. Otherwise, I'll probably just code a wrapper :)

**Comment by ktbyers** [comment]
@bbkane A failed device_type would cause the following exception to be generated:

        raise ValueError('Unsupported device_type: '
                         'currently supported platforms are: {0}'.format(platforms_str))

It does this prior to connect, however.

You could write separate code that tries to automatically determine the device type. For example, you could just use 'cisco_ios' as the device_type and then try to execute 'show version' on it and parse the output.

You could also probably work out the device_type using SNMP MIB-2.

Regards, Kirk
