### ISSUE TITLE
Netmiko disconnect is somewhat slow.

### ISSUE THREAD

**Issue by Maxime2006** [ktbyers/netmiko#2592]
Hi ! 
When I use the function disconnect() I wait 3 secondes before he close the connection ? 

May be it's normaly ? 

Cordialy

**Comment by Maxime2006** [comment]
I don't know how I can reduce this time ?

**Comment by ktbyers** [comment]
Which Netmiko platform/device_type is this?

Have you tested it with the develop branch?
