### ISSUE TITLE
Executing long commands on TP-Link switch

### ISSUE THREAD

**Issue by mnehrebecki** [ktbyers/netmiko#2608]
Hello, 
I'm using Netmiko to configure ACL on TP-Link switch (T2600G-28TS). Here is my code:

from netmiko import ConnectHandler
tplink_switch = {
    'device_type': 'tplink_jetstream',
    'host': '192.168.2.40',
    'username': 'admin',
    'password': 'admin',
    'secret': 'admin'
}

print("Connect to host")
connect_tplink_switch = ConnectHandler(**tplink_switch)
print("Connected.")
print("Switch: ", connect_tplink_switch.find_prompt())

config_commands = ['access-list create 1501',
                   'access-list extended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 pre 5'
                   'end']
tplink_output = connect_tplink_switch.send_config_set(config_commands)
print(tplink_output)

I'm getting error:

Traceback (most recent call last):
  File "/home/lab/PycharmProjects/rest_api_test/venv/lib/python3.8/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/home/lab/PycharmProjects/rest_api_test/venv/lib/python3.8/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lab/PycharmProjects/rest_api_test/venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/home/lab/PycharmProjects/rest_api_test/venv/lib/python3.8/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lab/PycharmProjects/rest_api_test/netmiko_send_command_tplink.py", line 21, in <module>
    tplink_output = connect_tplink_switch.send_config_set(config_commands)
  File "/home/lab/PycharmProjects/rest_api_test/venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 1912, in send_config_set
    new_output = self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/home/lab/PycharmProjects/rest_api_test/venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/lab/PycharmProjects/rest_api_test/venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

Process finished with exit code 1

I'm using logging and that's what I've got:

T2600G-28TS>

T2600G-28TS>

T2600G-28TS>

T2600G-28TS>enable

T2600G-28TS#

T2600G-28TS#

T2600G-28TS#enable-********
Already in ******** level.

T2600G-28TS#

T2600G-28TS#

T2600G-28TS#terminal length 0

T2600G-28TS#

T2600G-28TS#

T2600G-28TS#configure

T2600G-28TS(config)#

T2600G-28TS(config)#access-list extended 1501 rule 1 permit sip 192.168.5.1 sm[58D$ccess-list extended 1501 rule 1 permit sip 192.168.5.1 sma[59D$cess-list extended 1501 rule 1 permit sip 192.168.5.1 smas[59D$ess-list extended 1501 rule 1 permit sip 192.168.5.1 smask[59D$ss-list extended 1501 rule 1 permit sip 192.168.5.1 smask [59D$s-list extended 1501 rule 1 permit sip 192.168.5.1 smask 2[59D$-list extended 1501 rule 1 permit sip 192.168.5.1 smask 25[59D$list extended 1501 rule 1 permit sip 192.168.5.1 smask 255[59D$ist extended 1501 rule 1 permit sip 192.168.5.1 smask 255.[59D$st extended 1501 rule 1 permit sip 192.168.5.1 smask 255.2[59D$t extended 1501 rule 1 permit sip 192.168.5.1 smask 255.25[59D$ extended 1501 rule 1 permit sip 192.168.5.1 smask 255.255[59D$extended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.[59D$xtended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.2[59D$tended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.25[59D$ended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255[59D$nded 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.[59D$ded 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.2[59D$ed 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.25[59D$d 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255[59D$ 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 [59D$1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 t[59D$501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 to[59D$01 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos[59D$1 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos [59D$ rule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5[59D$rule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 [59D$ule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 p[59D$le 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 pr[59D$e 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 pre[59D$ 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 pre [59D$1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 pre 5

T2600G-28TS(config)#

As you can see, problem exists when I want to send command longer than 57 characters. 

Sorry if this has been answered before and I missed it

**Comment by applericky** [comment]
Hi,

I took your code from config_commands to debug it a little and I think there is a problem in this part. 

Here is what you posted:
```
config_commands = ['access-list create 1501',
'access-list extended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 pre 5'
'end']

```
I threw your code in the REPL printed the config_commands to see how it would post. 

```
In [1]: config_commands = ['access-list create 1501',
   ...: 'access-list extended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 to
   ...: s 5 pre 5'
   ...: 'end']
   ...:

In [2]: print(config_commands)
['access-list create 1501', 'access-list extended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 pre 5end']
```


So I see that you have a number 5 and a end together like this: "5end".

I would try the following to see if the code works 

config_command1 = 'access-list create 1501'
config_command2 = 'access-list extended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 pre 5'
config_command3 = 'end'


tplink_output1 = connect_tplink_switch.send_config_set(config_command1)
tplink_output2 = connect_tplink_switch.send_config_set(config_command2)
tplink_output3 = connect_tplink_switch.send_config_set(config_command3)


This should have Netmiko enter the commands one by one. This will tell us if the syntax of the device was wrong or of there was a character limit that was hit. 

If this works then I would try to do a while loop with the commands to see if you can clean up the code a little more.

**Comment by mnehrebecki** [comment]
Hi, sorry for late response.
I tried your solution but still got the same problem. When I log to switch with Putty or Linux terminal and type command, I see that characters are "moving" from right to left, not going to new line. I think that's the problem.

**Comment by ktbyers** [comment]
Expanding on @applericky earlier response, I would try this:

```python
config_commands = [
    'access-list create 1501',
    'access-list extended 1501 rule 1 permit sip 192.168.5.1 smask 255.255.255.255 tos 5 pre 5',
]
connect_tplink_switch.send_config_set(config_commands)
```

You should not include `end` in your config_commands, Netmiko will do this automatically.
