### ISSUE TITLE
Error when trying to import netmiko ModuleNotFoundError: No module named 'netmiko.citrix'

### ISSUE THREAD

**Issue by ak1066** [ktbyers/netmiko#2609]
Hi,

I'm very new to apple, python & any sort of scripting. I've installed Python & netmiko & following a tutorial (https://www.youtube.com/watch?v=NSnrvVhbuy8) . When I get to the following to import the netmiko into python I get the following error...any ideas where I'm going wrong, what I need to amend change etc etc? Thanks

MacBook-Air Network % pip3 freeze
bcrypt==3.2.0
cffi==1.15.0
cryptography==35.0.0
future==0.18.2
netmiko==3.4.0
ntc-templates==3.0.0
paramiko==2.8.0
pycparser==2.21
PyNaCl==1.4.0
pyserial==3.5
scp==0.14.1
six==1.16.0
tenacity==8.0.1
textfsm==1.1.2

MacBook-Air Network % pwd
/Users/*****/Documents/pythonfiles/programs/Network
*****@MacBook-Air Network % 

MacBook-Air Network % python3
Python 3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> import netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/ssh_dispatcher.py", line 31, in <module>
    from netmiko.citrix import NetscalerSSH
**ModuleNotFoundError: No module named 'netmiko.citrix' <<<<<<<<????????????????
>>>

**Comment by applericky** [comment]
Hi, 

I did what you did and I didn't get the problem.


```
➜  ~  python3
Python 3.9.9 (main, Nov 21 2021, 03:16:13)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> from netmiko.ssh_dispatcher import ConnectHandler
>>> from netmiko.citrix import NetscalerSSH
>>>
>>>
>>>
```

Can you show me your code where the imports are failing?
Also have you tried to just do:
`from netmiko import Netmiko`

See if just importing it this way moves beyond the import.
