### ISSUE TITLE
telnet to Cisco IOS router fails with netmiko.ssh_exception.NetMikoAuthenticationException

### ISSUE THREAD

**Issue by sockduct** [ktbyers/netmiko#261]
I have a Cisco 1811W router running 15.1(4)M8 setup for both telnet and ssh.  When I connect with telnet, it fails:
dev = dict(device_type='cisco_ios_telnet', ip='192.168.1.1', username='testuser', password='testpass', secret='testpass', port=23, verbose=True)

dev_conn = netmiko.ConnectHandler(**dev)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netmiko\ssh_dispatcher.py", line 90, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "netmiko\base_connection.py", line 68, in __init__
    self.establish_connection()
  File "netmiko\base_connection.py", line 329, in establish_connection
    self.telnet_login()
  File "netmiko\base_connection.py", line 243, in telnet_login
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Telnet login failed: 192.168.1.1

sys.version
'2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]'

I used Wireshark, and it appears that netmiko successfully authenticates to the router but upon login it keeps sending newlines.  Maybe it's stuck trying to figure out the prompt?  Not sure what it doesn't like.  Any suggestions on debugging?

**Comment by ktbyers** [comment]
@sockduct So looking at this telnet_login() code:

```python
                elif re.search("assword", output):
                    self.write_channel(self.password + "\n")
                    output += self.remote_conn.read_very_eager().decode('utf-8', 'ignore')
                    if debug:
                        print("Z2")
                        print(output)
                    time.sleep(.5 * delay_factor)
                    output = self.remote_conn.read_very_eager().decode('utf-8', 'ignore')
                    if '>' in output or '#' in output:
                        if debug:
                            print("Z3")
                        return output
```

It looks like it never finds '>' or '#'. 

It would be interesting to see what happens if you set the debug flag to true in this telnet_login() function. It could just be a timing issue. I only have a sleep of .5 seconds there (after sending the password).

**Comment by ktbyers** [comment]
@sockduct Are you still seeing this issue on the current dev_1_0 code?

**Comment by sockduct** [comment]
@ktbyers - yes.  Here's my procedure (just want to make sure I'm not missing something):

From my Windows PC running Python v2.7.11 win32:
* # Enter virtualenv for testing
* git pull origin dev_1_0
* git branch -vv
* git status
* python setup.py clean
* Edit base_connection.py and in telnet_login() change debug to True
* python setup.py build
* python setup.py install
* python
>>> import netmiko
>>> from getpass import getpass
>>> r2t = dict(device_type='cisco_ios_telnet', ip='192.168.234.130', username='jim', password='', secret='', port=23
rbose=True)
>>>
>>> mypass = getpass()
Password:
>>> r2t['password'] = mypass
>>> r2t['secret'] = mypass
>>> dev_conn = netmiko.ConnectHandler(**r2t)
In telnet_login():
<type 'unicode'>

Authorized use only.  This system is monitored.  Usage of this system implies
consent to such monitoring.  Unauthorized usage will result in system logs
being handed over to the appropriate authorities.


User Access Verification

Username:
Z1
jim
Password:
<type 'unicode'>

Z2
jim
Password:
<type 'unicode'>

<type 'unicode'>

<type 'unicode'>


twofish#
twofish#
twofish#
<type 'unicode'>

twofish#
<type 'unicode'>

(This sequence repeats 25 times and then it bombs out):
twofish#
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netmiko\ssh_dispatcher.py", line 90, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "netmiko\base_connection.py", line 68, in __init__
    self.establish_connection()
  File "netmiko\base_connection.py", line 340, in establish_connection
    self.telnet_login()
  File "netmiko\base_connection.py", line 252, in telnet_login
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Telnet login failed: 192.168.234.130
>>>


Does this help?  Let me know if you need more info or want me to try something else.

**Comment by ktbyers** [comment]
@sockduct Here is the current code as of today (slightly different than what you have based on line numbers):

```
                elif re.search(r"assword", output):
                    self.write_channel(self.password + "\n")
                    output += self.read_channel()
                    if debug:
                        print("Z2")
                        print(output)
                    time.sleep(.5 * delay_factor)
                    output += self.read_channel()
                    if pri_prompt_terminator in output or alt_prompt_terminator in output:
                        if debug:
                            print("Z3")
                        return output
```

So we never hit the 'Z3' marker, I wonder if increasing the time.sleep fixes it?

Are you using your own fork, or is your 'git remote' my repo?

**Comment by ktbyers** [comment]
Note pri_prompt_terminator and alt_prompt_terminator are '#' and '>' respectively.

**Comment by sockduct** [comment]
@ktbyers - just upgraded to 1.0 version from PyPI and it works, so marking this as closed.
