### ISSUE TITLE
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by Birajan2019** [ktbyers/netmiko#2610]
Hello Folks,

I'm stuck with this error:

Traceback (most recent call last):
  File "C:\Users\tonyfal\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\tonyfal\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tonyfal\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\tonyfal\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\cogen-change-config-1.py", line 45, in <module>
    output1 = net_connect.send_config_from_file(config_file = 'cogen-set-config.txt')
  File "C:\Users\tonyfal\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 1665, in send_config_from_file
    return self.send_config_set(cfg_file, **kwargs)
  File "C:\Users\tonyfal\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 1759, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "C:\Users\tonyfal\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\tonyfal\AppData\Local\Programs\Python\Python38\lib\site-packages\netmiko\base_connection.py", line 560, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Here is the script, I'm using:**

from netmiko import ConnectHandler
from netmiko.ssh_exception import NetmikoAuthenticationException
from netmiko.ssh_exception import NetmikoTimeoutException
from paramiko.ssh_exception import SSHException
from getpass import getpass
from datetime import datetime

password = getpass()
start_time = datetime.now()

IP_LIST = open ('gold-list.txt')

for IP in IP_LIST:
  RTR = {
		"device_type": "juniper_junos",
        "ip": IP,
        "username": "Trishul",
		"password": password,
		"global_cmd_verify": False,
        
}
                            
		
  print ('Connecting to the device' + IP)
  try:
   net_connect = ConnectHandler(**RTR)
  except NetmikoAuthenticationException:
   print('Authentication error')
   continue
  except NetmikoTimeoutException:
   print('Device is not reachable')
   continue 
  except SSHException:
   print('Make sure SSH is enabled')
  except ValueError:
   print ('Router prompt not found')
   continue  
  except EOFError:
   print('Unable to connect at all')
   continue   
    
  output1 = net_connect.send_config_from_file(config_file = 'cogen-set-config.txt')
  print(net_connect.find_prompt())
  print (output1)
  end_time = datetime.now()
  total_time = end_time - start_time
  print (total_time) 

###

**Here is how the gold-list.txt file looks like:**

10.10.10.1
10.10.10.2
10.10.10.3

**Here is how the cogen-set-config.txt file looks like:**
rollback 0
delete system login user cogen
set system services netconf ssh
set system login user cogen uid 500
set system login user cogen class read-only
set system login user cogen authentication encrypted-password "####"
commit

Would really appreciate some assistance on this.

Thank You,
B

**Comment by Birajan2019** [comment]
I'm starting to see where the problem lies. Surprisingly, I have no issues pushing out just the set commands. Its only when I try to push the "set commands" and "commit command" at the same time, I get timeout. After using a different line for commit. and passing the following arguement for commit, I'm golden:
net_connect.commit(and_quit=True)

But if someone could help explain, why we cannot use both the set and commit statements at the same time, that would be great.

Thanks,
B

**Comment by Tes3awy** [comment]
Try to set `fast_cli: False` in the RTR dictionary.

```
RTR = {
    "device_type": "juniper_junos",
    "ip": IP,
    "username": "Trishul",
    "password": password,
    "global_cmd_verify": False,
    "fast_cli": False, # this item
}
```

By default `fast_cli` is set to `True` for `juniper_junos` https://github.com/ktbyers/netmiko/blob/a82ae784f4f1ef75e864ac972c088b8c963f77ff/netmiko/juniper/juniper.py#L18

Basically, `fast_cli` multiplies the `global_delay_factor` by 0.1 to scrape the CLI fatser; hence its name `fast_cli`. The default value of the `global_delay_factor` is 1 which is 100 seconds. Then, `100*0.1 = 10` seconds only which is not enough in some cases. Faster is not always better, so always set `fast_cli` to `False`.

**Comment by ktbyers** [comment]
You shouldn't perform the `commit` as part of the commands in your configuration file. This operation is (way) too slow to be done that way.

Netmiko expects send_config_from_file commands to be done relatively rapidly and `commit` is very slow. Consequently, it should be invoked separately using the `commit()` method (as you indicated with what you discovered during your testing).

Even with fast_cli=False, I wouldn't necessarily expect commit() to work (i.e. it might, but I wouldn't count on it).

**Comment by Birajan2019** [comment]
Thanks @ktbyers and @Tes3awy for your explaination. Marking this as closed.
