### ISSUE TITLE
DEll os6 not supported in AutoDetect

### ISSUE THREAD

**Issue by Dev01024** [ktbyers/netmiko#2611]
The return value is none. Is this something that can be corrected?

**Comment by applericky** [comment]
Hi,

I'm not seeing OS6 in the` SSH_MAPPER_DICT`

Here is what I found:
```
dell_os9": {
        "cmd": "show system",
        "search_patterns": [
            r"Dell Application Software Version:  9",
            r"Dell Networking OS Version : 9",
        ],
        "priority": 99,
        "dispatch": "_autodetect_std",
    },
    "dell_os10": {
        "cmd": "show version",
        "search_patterns": [r"Dell EMC Networking OS10.Enterprise"],
        "priority": 99,
        "dispatch": "_autodetect_std",
    },
    "dell_powerconnect": {
        "cmd": "show system",
        "search_patterns": [r"PowerConnect"],
        "priority": 99,
        "dispatch": "_autodetect_std",
```

The dell driver looks like it has os6 but not auto detect. Were you trying to stick with it? Wasn't os6 similar to powerconnect?
If @ktbyers can confirm auto detect does not have os6, you can submit a pull request for it.

**Comment by ktbyers** [comment]
Yes, no one has added this support, someone would need to do a pull request on it.
