### ISSUE TITLE
netmiko with proxyjump can't connect device(Paramiko.ssh_exception.ProxyCommandFailure: ProxyCommand)

### ISSUE THREAD

**Issue by x84net** [ktbyers/netmiko#2612]
Hi,

this is a replication of issue #2415. I'm having the same problem but sadly no english error messages for you.
It's also on Windows 10 and I don't have WSL. Netmiko is v3.4.0 paramiko says SSH-2.0-paramiko_2.7.1

The problem lies in the path evaluation of  _'ssh_config_file': './ssh_config',_ in the dict that gets passed to the ConnectHandler().
As with in issue #2415 the path is missing all the '\\' from the path.
In my case it's :
_ERROR:paramiko.transport:Exception: ProxyCommand("ssh -F C:UsersUsernameDocumentsCodessh_config_
and not like:
_ERROR:paramiko.transport:Exception: ProxyCommand("ssh -F C:\Users\Username\Documents\Code\ssh_config_

I tried using _'ssh_config_file': str(Path(__file__).resolve().parent.joinpath('ssh_config')),_ in the dictionary with no luck, the '\\' are still missing. 

regards

**Comment by ktbyers** [comment]
@x84net If you don't have WSL, what is the local SSH that you will be executing?

**Comment by x84net** [comment]
@ktbyers that is a good question, any clues how to check what/which binary python is using?
Judging from the output I'd have guessed sth. from paramiko but... I don't know.
It's like "I installed netmiko with pip and it just worked"
When using ssh without python I'm using [ZOC](https://www.emtec.com/zoc/index.html) but I've also used putty in the past.
I haven't (actively) used any ssh_config config file before trying to use the proxy command in netmiko.
I'd love to have WSL but it's a company PC.

**Comment by ktbyers** [comment]
You need to have a local working SSH for the SSH Proxy to properly work.

If you don't have a local, system SSH, then you would probably need to use straight Netmiko (i.e. no SSH proxy config) and bounce through each device and then use Netmiko "redirect" to change the Netmiko class. Search on "redirect" and Netmiko and you should find some examples.
