### ISSUE TITLE
Aruba OSCX Textfsm fail and the device is not listed in the support devices

### ISSUE THREAD

**Issue by NetDevOpsNewbie** [ktbyers/netmiko#2613]
Hi 
Currently using Netmiko trying to automate [ Aruba OSCX ] when using devicetype as Aruba_OS it does work but the textfsm doesn't. the command is listed in the ntc-templates and I have followed the same method with Cisco_IOS and it worked without any issue. 

Is [ Aruba OSCX ] not supported in Netmiko? We cannot see it as device type:
ntc-templates show the following avaiable: 
aruba_aoscx_show_aaa_authentication_port-access_interface_all_client-status.textfsm
aruba_aoscx_show_arp_all-vrfs.textfsm
aruba_aoscx_show_bfd_all-vrfs.textfsm
aruba_aoscx_show_bgp_all_all-vrfs_summary.textfsm
aruba_aoscx_show_bgp_all-vrfs_all_summary.textfsm
aruba_aoscx_show_interface_dom_detail.textfsm
aruba_aoscx_show_interface.textfsm
aruba_aoscx_show_ip_route_all-vrfs.textfsm
aruba_aoscx_show_lldp_neighbors-info_detail.textfsm
aruba_aoscx_show_mac-address-table.textfsm
aruba_aoscx_show_ntp_associations.textfsm
aruba_aoscx_show_vsf_detail.textfsm

However, in netmiko I cannot find Aruba_AOSCX - used Aruba_OS isntead and it returned string output.

**Comment by Tes3awy** [comment]
I haven't tried Netmiko with Aruba before, but you have three options to connect to Aruba switch: `aruba_os`, `aruba_osswitch`, or `aruba_procurve`.

If neither of these three options work, stick to `aruba_os` and **explicitly** specify the template you want to use

```python
arp_table = conn.send_command("show arp all", use_textfsm=True, textfsm_template="/path/to/textfsm/template/file")
```

**Comment by ktbyers** [comment]
Yeah, it looks like ntc-templates has an OS that Netmiko doesn't have a driver for (Aruba OS CX) so someone probably needs to make a specific Aruba OS CX driver.
