### ISSUE TITLE
SSHException handled but traceback is still displayed in stderr

### ISSUE THREAD

**Issue by Tes3awy** [ktbyers/netmiko#2615]
I am trying to handle the `SSHException` using the `try/except` block. It's handled but the traceback is still printed out! Even if I try `Exception` or `BaseException` instead of  `SSHException`, it's handled but I still get the traceback displayed in the `stderr`.

I also tried removing `Paramiko`'s exception and to use the one in `Netmiko` _(I know it's the same as the one in `paramiko`)_

```python
import sys

from netmiko import ConnectHandler
from netmiko.ssh_exception import (
    NetmikoAuthenticationException,
    NetmikoTimeoutException,
    # SSHException
)
from paramiko.ssh_exception import SSHException

device = {
    "device_type": "cisco_ios",
    "ip": "192.168.1.1",
    "username": "cisco",
    "password": "cisco",
    "secret": "",
    "fast_cli": False,
}

try:
    print(f"Connecting to {device['ip']}...")
    with ConnectHandler(**device) as conn:
        print(f"Connected to {conn.host}:{conn.port}")
        facts = conn.send_command(command_string="show version", use_textfsm=True)
except (
    SSHException,
    NetmikoAuthenticationException,
    NetmikoTimeoutException,
    ConnectionResetError,
    TimeoutError,
) as e:
    print(f"Connection to {device['ip']} failed: {e}", file=sys.stderr)
else:
    print(facts)
```

```
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\paramiko\transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\paramiko\packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\paramiko\packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\paramiko\transport.py", line 2039, in run
    self._check_banner()
  File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\paramiko\transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

I want to prevent the traceback being printed out to the `stderr`. 

Thank you!

**Comment by applericky** [comment]
Hey,

Based from what I can see, I would try to modify it a little. See if this helps.


```
except (SSHException, NetmikoAuthenticationException, NetmikoTimeoutException, ConnectionResetError, TimeoutError) as e:
    print(f"Connection to {device['ip']} failed: {}".format(e))
```

You can also do:

```
except (SSHException, NetmikoAuthenticationException, NetmikoTimeoutException, ConnectionResetError, TimeoutError) as e:
    print(f"Connection to {device['ip']} failed: ", e)
```


Also you can create your own custom messages in a class. It's a little more complicated but you can catch the major Netmiko exceptions.


```
 class MyCustomSSHException(Exception):
    ...:     def __init__(self, value)
    ...:        message = f"Somethings wrong: {value}"
    ...:        super ().__init__(message)
```


```
if my_ssh > 3:
    ...:     print("SSH is good!")
    ...: else:
    ...:     raise MyCustomSSHException(my_ssh)
    ...:
SSH is good!
```

```
In [23]: if my_ssh < 3:
    ...:     print("SSH is good!")
    ...: else:
    ...:     raise MyCustomSSHException(my_ssh)
    ...:
    ...:
---------------------------------------------------------------------------
MyCustomSSHException                      Traceback (most recent call last)
<ipython-input-23-df3f0add8c4a> in <module>
      2     print("SSH is good!")
      3 else:
----> 4     raise MyCustomSSHException(my_ssh)
      5
      6

MyCustomSSHException: Somethings wrong: 5
```


Hopefully the first two can get you on the right track.

**Comment by Tes3awy** [comment]
@applericky Unfortunately, the first two didn't solve the issue. However, I wonder why you removed the `file=sys.stderr` and used `.format()` instead of the `f-string`? 

I'll try the custom exception.

**Comment by applericky** [comment]
Oh you're right. I always miss those f strings!

**Comment by ktbyers** [comment]
I think this is probably due to Paramiko using threading in a certain context. In other words, you are handling the exception in your code, but this exception in Paramiko is in a different thread so it still appears.

I would probably try to setup logging to get that stderr message to go to the log file (instead of stderr). Definitely not sure this will work, but that is probably where I would look.

**Comment by ktbyers** [comment]
@Tes3awy Let me know if the logging fix works or not. 

I am pretty confident about the underlying cause of the issue being Paramiko using threading in a certain context (as I have seen this issue before).

**Comment by Tes3awy** [comment]
> @Tes3awy Let me know if the logging fix works or not.
> 
> I am pretty confident about the underlying cause of the issue being Paramiko using threading in a certain context (as I have seen this issue before).

Yes, using `logging` does fix the issue. What I actually did is that I added the following lines to my script

```python
import logging

logging.basicConfig(filename="netmiko.log", level=logging.WARNING)
logger = logging.getLogger("netmiko")
```

However, if you don't need a log file to be created in the cwd

```python
import logging

logger = logging.getLogger("paramiko")  # paramiko not netmiko
logger.addHandler(logging.NullHandler())
```

You can also refer to this [official Python documentation link](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) for the second method.

Thanks a lot @ktbyers. Have a great day ahead!
