### ISSUE TITLE
command length time out.

### ISSUE THREAD

**Issue by Bizzo1990** [ktbyers/netmiko#2622]
Hello everyone. I am running into an issue where netmiko is sending a command, but when in CLI if the command is too long it shortens to show half of the command, and I believe this is throwing off my code. i have tried to use a expect string "$" since when the command gets shorten it shows that, but it does work. from what i see in the session output. i get a weird character. 

![image](https://user-images.githubusercontent.com/59747561/148123097-f794e246-9040-4b0c-9fea-9dce39ffdf59.png)
![image](https://user-images.githubusercontent.com/59747561/148123265-e1047cff-51ac-42a1-93b8-e1c5a946dcc5.png)

    `from netmiko import ConnectHandler
    import re
    import paramiko
    
    
    def conn():
        CSR = {
            'device_type': 'cisco_ios',
            'ip': '192.168.1.1',
            'username': 'uname',
            'password': 'pwrock',
            'secret': 'pwsecrest',
            'session_log': "output.txt"
        }
        net_connect = ConnectHandler(**CSR)
        net_connect.enable()
        #below command gets the host name
        hostname = net_connect.find_prompt()[:-1]
        #below code gets the onu profiles then passes it to another var and replaces the begining
        #with empty string.
        onu_prof_raw = net_connect.send_command('show startup-config | i onu-profile')
        onu_prof_clean = onu_prof_raw.replace("onu-profile gpon ", "")
        onu_prof_clean = onu_prof_clean.split(sep='\n')
        print(f'>>>>{hostname}<<<<')
    
        for i in onu_prof_clean:
             cmd = (f'show pon onu-profile gpon {i} cfg')
             onu_prof_cfg = net_connect.send_command(cmd, expect_string=r"#")
             onu_prof_cfg += net_connect.send_command('\n', expect_string=r"#",delay_factor=2)
             net_connect.send_command('!')
             print('-' * 20)
             print(f'#{i}')
             pattern = re.compile(r'service\s[A-Z]\w*\stype\s[a-z]\w*\sgemport\s[0-9]\svlan\s[0-9]\w*')
             matches = pattern.findall(onu_prof_cfg)
             for b, x in enumerate(matches):
                 print(x)
    
    conn()`

**Comment by ktbyers** [comment]
Try sending your command as is i.e. do not modify the command that you send and then add the `cmd_verify=False` to Netmiko's send_command method. This will disable cmd echo verification for that command in Netmiko (i.e. Netmiko will not check whether the command is properly echoed or not).

**Comment by Bizzo1990** [comment]
this is resolved. Thank you @ktbyers  

fix, was: 
  `cmd = (f'show pon onu-profile gpon {i} cfg')
           onu_prof_cfg = net_connect.send_command(cmd, cmd_verify=False)`
