### ISSUE TITLE
Netmiko fails when using proxy to a cisco device for a port different than 22 

### ISSUE THREAD

**Issue by AmineHBAR** [ktbyers/netmiko#2624]
Hello,

I use netmiko with proxy under ssh/config to connect to cisco devices. 
one of the devices is accessible through port 22 and the other one through a different port 3005
The connection works with the proxy for the cisco device  with port 22 and fails for the ohter one with 3005. 

when i use the cli command to connect to devices, they both work through proxy ( i.e proxy file is configured correctly ) 

I'm having an issue when i use Netmiko to connect to the device with 3005. 

This the device dict i use:

        **device = {
            'device_type'     : d_type,
            'host'            : self.ip,
            'username'        : self.user,
            'password'        : self.pwd,
            'port'            : port,            # optional, defaults to 22
            'secret'          : enable_pass,     # optional, defaults to ''
            'ssh_config_file' : '~/.ssh/config',
            'conn_timeout'    : 100,
            'auth_timeout'    : 100,
            'fast_cli'        : False,
            'global_delay_factor'  : 4,
            'timeout'              : 200,
            'banner_timeout'       : 200,
            'allow_agent': False,
        }**

i keep getting this error: 

      **Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 10 seconds or larger.**

I have changed the value of conn_timeout to different values, 20,30,50,..,100 but it still does not work. 

Do you have any ideas what could cause the issue ? 

Thanks a lot

Amine

**Comment by ktbyers** [comment]
What does your ~/.ssh/config file look like? Netmiko does not process all of the SSH config file only parts of it.
