### ISSUE TITLE
loading ntc templates installed via pip fails with "IsADirectoryError"

### ISSUE THREAD

**Issue by jasons2** [ktbyers/netmiko#2633]
Trying to use TextFSM with Netmiko on Python 3.9.10 on  ubuntu 20.x

Fails with following traceback.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jasons/TSCIF_Audit/venv/lib/python3.9/site-packages/netmiko/utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/jasons/TSCIF_Audit/venv/lib/python3.9/site-packages/netmiko/base_connection.py", line 1550, in send_command
    structured_output = get_structured_data(
  File "/home/jasons/TSCIF_Audit/venv/lib/python3.9/site-packages/netmiko/utilities.py", line 344, in get_structured_data
    template_dir = get_template_dir()
  File "/home/jasons/TSCIF_Audit/venv/lib/python3.9/site-packages/netmiko/utilities.py", line 281, in get_template_dir
    with importresources_path(
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/home/jasons/TSCIF_Audit/venv/lib/python3.9/site-packages/ntc_templates/templates'`

To trigger above traceback
`Python 3.9.10 (main, Jan 27 2022, 17:47:55)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from netmiko import Netmiko
>>> router = Netmiko(host= "somehostname",username= "someUid",password= "somePass", device_type= "cisco_ios")
>>> print(router.send_command("show cdp neighbors", use_textfsm=True))`

Current Environment
`(venv) jasons@godzilla:~/TSCIF_Audit$ pip list
Package       Version
------------- -------
bcrypt        3.2.0
cffi          1.15.0
cryptography  36.0.1
future        0.18.2
netmiko       3.4.0
ntc-templates 3.0.0
paramiko      2.9.2
pip           21.2.4
pycparser     2.21
PyNaCl        1.5.0
pyserial      3.5
scp           0.14.2
setuptools    58.1.0
six           1.16.0
tenacity      8.0.1
textfsm       1.1.2`

The templates and the index file are in /home/jasons/TSCIF_Audit/venv/lib/python3.9/site-packages/ntc_templates/templates as expected. Setting the NET_TEXTFSM environment variable to this path works as expected.

**Comment by ktbyers** [comment]
@jasons2 Can you test and see if the Netmiko `develop` branch works?

I think this is probably fixed in the `develop` branch already.

**Comment by vvevans** [comment]
> @jasons2 Can you test and see if the Netmiko `develop` branch works?
> 
> I think this is probably fixed in the `develop` branch already.

If I may weigh in on this - I spent a terrible amount of time last week trying to sort this issue as well and discovered something that I don't think should be.

I upgraded my netmiko (3.4.0) and ntc-templates (3.0.0) packages (via pip) after I was receiving the same error @jasons2 shows above. I had seen the commit by @jgsawyers in which he changed two lines in the utilities.py file of netmiko.

However, following my upgrade, I did not have these entries in my utilities.py file and had to add them manually  in order to get ntc-templates to work correctly, looking in the "templates" directory , as expected.

I haven't checked the dev branch of Netmiko (not even sure I know how to), but currently I'm working with a modified version of the utilities.py file to have my scripts work.

**Comment by jasons2** [comment]
I can confirm that I am experiencing the exact same issue @vvevans references.   I made the following changes to my utilities.py and was able to execute without Environment Variables Set.

```
            with importresources_path(
                #package="ntc_templates", resource="templates" <== Original in 3.4
                package="ntc_templates", resource="parse.py" # <== Replaced
            ) as posix_path:
                # Example: /opt/venv/netmiko/lib/python3.8/site-packages/ntc_templates/templates
                #template_dir = str(posix_path)  <== Original in 3.4
                template_dir = str(posix_path.parent.joinpath("templates")) # <== Replaced
```

**Comment by ktbyers** [comment]
Okay, going to close as fixed as this should be in the next Netmiko release.
