### ISSUE TITLE
send_command times out because space+backspace from the device.

### ISSUE THREAD

**Issue by sirikothe** [ktbyers/netmiko#2643]
When executing a send_command() on one junos device with a long command, netmiko is eventually timingout even though it receives an output from the device.

Further debugging shows that the device is echoing 3 spaces followed by 3 backspace characters in the middle of the command.
This makes netmiko not to be able to find the command in the output and eventually timeout.

PS: I dont want to disable cmd_verify=False because the code has been written to verify the commands everywhere else. Enabling for only in this case is not possible for various reasons.

Thanks for your help.

**Comment by sirikothe** [comment]
![Untitled 2](https://user-images.githubusercontent.com/20236316/153156380-f19c7987-e1a0-46f4-add4-ff8964b1ab38.png)

**Comment by sirikothe** [comment]
Adding this piece of code to sanitise the new_data in base_connection.py -> read_channel() function solves the issue.
Before line 556
https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L556

```
                iter = 0
                while f"{BACKSPACE_CHAR}" in new_data and iter < 100:
                    # replace any char (other than back_space) followed by backspace with empty string.
                    new_data = re.sub(f"[^{BACKSPACE_CHAR}]{BACKSPACE_CHAR}", "", new_data)
                    new_data = re.sub(f"^{BACKSPACE_CHAR}", "", new_data)
                    iter += 1
                    # iter is added to make sure we dont go into infinite loop for whatever reason.
```

**Comment by ktbyers** [comment]
Did you try just calling/using this method on the `new_data`?

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1752-L1760

I would not be willing to put it into the base code as it is a Junos specific odd behavior (and there already is a workaround for cmd_verify=False).

We could maybe talk about putting something in that is Junos specific, but even that might be hard and not really viable.

**Comment by sirikothe** [comment]
Thanks a lot for the quick response @ktbyers 
> Did you try just calling/using this method on the `new_data`?
> 
> https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1752-L1760
> 

I think this would not work. Because this junos output contains "three spaces" followed by "three backspaces". This function just removes the backspaces, which will leave the 3 spaces, causing the match to fail anyway.

Ideally, strip_backspaces() should remove backspace and its preceding character (to emulate what a terminal would do) and not just remove the backspace.

> I would not be willing to put it into the base code as it is a Junos specific odd behavior (and there already is a workaround for cmd_verify=False).
> 
> We could maybe talk about putting something in that is Junos specific, but even that might be hard and not really viable.

I agree putting this in base_connection may be too generic, but I think putting in junos specific plugin may be worth a thought. It is safe enough that if there are no backspaces, the original behaviour continues.
The problem with cmd_verify=False is that I dont want to generically disable this for all/junos devices just because of this odd behaviour of one command. (And I can not disable per command because I dont know which command user is going to execute).

Thanks once again for your quick response.

**Comment by ktbyers** [comment]
Can you show me the Netmiko session_log output for a Junos device that is exhibiting this behavior?

Basically, why is Juniper doing this? It shouldn't be.

Early on in the session Netmiko sets the terminal screen width to 511 so it shouldn't be doing that weird backspace/space behavior.

**Comment by sirikothe** [comment]
> Can you show me the Netmiko session_log output for a Junos device that is exhibiting this behavior?
> 
I could not figure out how to get the session_log from netmiko. ( I am using nornir-> nornir_netmiko -> netmiko).
Anyway, I verified from the logs that it is in fact sending proper initialisation sequence. i see the following in the log.
```
2022-02-28 04:26:38,191 -      netmiko -    DEBUG - _write_channel() - write_channel: b'set cli screen-width 511\n'
2022-02-28 04:26:38,269 -      netmiko -    DEBUG - _write_channel() - write_channel: b'set cli complete-on-space off\n'
2022-02-28 04:26:38,315 -      netmiko -    DEBUG - _write_channel() - write_channel: b'set cli screen-length 0\n'
```

> Basically, why is Juniper doing this? It shouldn't be.
> 
It should not be. But it is :)

> Early on in the session Netmiko 

>sets the terminal screen width to 511 so it shouldn't be doing that weird backspace/space behavior.

I manually executed the initialization commands from a manual ssh and captured the log from ssh and attached is the screenshot. So, the backspaces are not because something wrong from netmiko. It is just that junos behaves like that just for this command.

![Untitled 2](https://user-images.githubusercontent.com/20236316/155925206-c2f25fde-03d7-49f1-ba71-a76da20d57b5.png)

**Comment by ktbyers** [comment]
So what is the full Junos command you are sending via send_command()?

**Comment by ktbyers** [comment]
You mentioned above the behavior of a partial command, but why is it a partial command i.e. why is there a carriage-return + newline after the DL-0004?

**Comment by sirikothe** [comment]
The full command I sending to junos (used in manual ssh as well as in send_command())  is `show route table DL-0048 community-name VRF-TARGET-DL-0048-1234-123456789`
I was not sending partial command. What I meant was, when I enter the full command and press enter, the device is supposed to echo the command as is (which netmiko tries to match in the output from device). But it echos part of the command + newline + prompt + full command (along with space and backspace). Not sure why device does that, but it does that.

**Comment by ktbyers** [comment]
Okay, I really don't have a fix for this besides cmd_verify=False. It is starting to sound like a Juniper bug.

You are welcome to put in a custom function/method to do this stripping, but given where it happens you would probably have to override the default Junos class and replace it with your own class.

Definitely weird behavior on Juniper's part.

I would definitely check that you don't have any embedded characters (that are hidden) in the given `show route` command. Especially the ^M above is typically something you would see if you had a carriage return + newline in your command.

**Comment by sirikothe** [comment]
Ok. We put a fix in our code to override the _read_channel_expect() to detect these special characters and remove them. I am definitely absolutely sure that we dont have any ^M etc characters in the command sent to the device.
Closing this issue for now. Thanks for looking into it.

**Comment by ktbyers** [comment]
Okay, weird behavior. I can't reproduce it, but I also probably don't have a close enough match to what you are doing. 

Does it only happen on that one route command or is it more general?
