### ISSUE TITLE
connect() got an unexpected keyword argument 'passphrase'

### ISSUE THREAD

**Issue by AcousticPanic** [ktbyers/netmiko#2649]
Getting the above error when trying to connect to a cisco device. Looking around the interwebs, it looks like there was an issue with versioning between the netmiko and paramiko installs. However, I have what seems to be, acceptable versions of each.  Netmiko is at 3.3.0 and Paramiko is 2.7.2. I can ssh to the switch from the same linux host w/o issue and the same error occurs when running in an idle shell so I know it isn't something odd with the script. Should I just upgrade all? This is a group, multipurposed production box so I'm hesitant to suggest that until I know that is the proper solution (although somewhat obvious...) .

**Comment by ktbyers** [comment]
Have you tried Netmiko 3.4.0?

**Comment by AcousticPanic** [comment]
Hi Kirk - No, haven't upgraded yet. There are a lot of people on this box and before that is the path I suggest, I wanted to get opinions here. I will  create my own virtual environment and install there, but we're having home drive mapping issues at the moment so until next week I'm pretty much stuck with the system pip packages. Just seems odd to have such a basic issue with versions of netmiko and paramiko that aren't, comparatively, that old.

**Comment by ktbyers** [comment]
Can you post a full exception stack trace?

Are you sure that the version of Paramiko is 2.7.2? I.E. that 2.7.2 is the Paramiko version that is being used. Historically, the above message/error is associated with using old versions of Paramiko. See:

https://stackoverflow.com/questions/52146312/netmiko-connection-error-typeerror-connect-got-an-unexpected-keyword-argume

**Comment by AcousticPanic** [comment]
I just read the link you posted and looks like the OP had the same thought for getting the version. He/she also makes mention of the failure being related to paramiko version < 2.0.0, which I'm not. Do you think that is that still accurate?

**Comment by ktbyers** [comment]
I think your Python and PIP3 are not the same Python i.e. I think the very old Paramiko is being used when you execute your script.

I would expect that is very likely the cause of this issue.

**Comment by AcousticPanic** [comment]
Well, I talked a guy into upgrading netmiko and paramiko. This landed another error, but was related to the cryptography package. Upgraded that one too and I'm in business now. Thanks for the help, much appreciated!
