### ISSUE TITLE
Netmiko 3.4.0 - Invalid ssh key issue

### ISSUE THREAD

**Issue by Shev84** [ktbyers/netmiko#2651]
I've got openssh private key file that starts and end with:
```
-----BEGIN OPENSSH PRIVATE KEY-----

-----END OPENSSH PRIVATE KEY-----
```

I can connect to device with that key by command:

`ssh -i test_key -l test_user -p port some_ip`

But when I setup such connection with Netmiko it throws me an error:
```
Traceback (most recent call last):
  File "bras-check-queue-list.py", line 28, in <module>
    with ConnectHandler(**bras) as net_connect:
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/netmiko/mikrotik/mikrotik_ssh.py", line 13, in __init__
    return super().__init__(**kwargs)
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/paramiko/client.py", line 766, in _auth
    raise saved_exception
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/paramiko/client.py", line 679, in _auth
    key_filename, pkey_class, passphrase
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/paramiko/client.py", line 588, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/paramiko/ed25519key.py", line 63, in __init__
    signing_key = self._parse_signing_key_data(data, password)
  File "/opt/virtualenv/netmiko_test/lib/python3.7/site-packages/paramiko/ed25519key.py", line 112, in _parse_signing_key_data
    raise SSHException("Invalid key")
```

Code is simple:

```
#!/opt/virtualenv/netmiko_test/bin/python3

### MODULES

from netmiko import ConnectHandler

### VARIABLES

bras_ip = '192.168.1.254'
bras_user = 'test_user'
bras_user_key = '/opt/scripts/test_user'
bras_ssh_port = '12345'

bras = {
        'device_type': 'mikrotik_routeros',
        'host': bras_ip,
        'username': bras_user,
        'port': bras_ssh_port,
        'use_keys': True,
        'key_file': bras_user_key,
}

####    CODE

with ConnectHandler(**bras) as net_connect:
    output = net_connect.send_command("interface print")

print(f"\n{output}\n")
```

Key was made with command:

`ssh-keygen -C test_user -t rsa -b 2048 -f test_user`

Key doesn't have passphrase.

These are python modules installed in this virtual enviroment:
```
Package       Version
------------- -------
bcrypt        3.2.0
cffi          1.15.0
cryptography  36.0.1
future        0.18.2
netmiko       3.4.0
ntc-templates 3.0.0
paramiko      2.9.2
pip           22.0.3
pkg_resources 0.0.0
pycparser     2.21
PyNaCl        1.5.0
pyserial      3.5
scp           0.14.2
setuptools    40.8.0
six           1.16.0
tenacity      8.0.1
textfsm       1.1.2
```

OS:
`Linux test 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`

Device is Mikrotik with RouterOS 6.x, but I don't think it is important, code doesn't get to attempt to login to device.

**Comment by ktbyers** [comment]
Can you try it with Paramiko 2.8.1?

**Comment by Shev84** [comment]
Downgrade of paramiko to version 2.8.1 solved that behaviour.

Now code with key is working fine.

`Package       Version
------------- -------
bcrypt        3.2.0
cffi          1.15.0
cryptography  36.0.1
future        0.18.2
netmiko       3.4.0
ntc-templates 3.0.0
paramiko      2.8.1
pip           22.0.3
pkg_resources 0.0.0
pycparser     2.21
PyNaCl        1.5.0
pyserial      3.5
scp           0.14.2
setuptools    40.8.0
six           1.16.0
tenacity      8.0.1
textfsm       1.1.2`

I suppose I should report it on Paramiko's github site, right?

Now problem is with Mikrotik output in Netmiko, it's full of white lines. But it's different case, probably mention somewhere else and I need to seek for solution to it.

**Comment by ktbyers** [comment]
It is this issue in Paramiko:

https://github.com/paramiko/paramiko/issues/1961

Netmiko develop branch has added the `disabled_algorithms` support in a recent PR so you should be able to workaround it using the `develop` branch (or just stay on Paramiko 2.8.1 for a while).

**Comment by megakarl** [comment]
Hey! Just started testing netmiko and I am running in to some issues with the ssh_key too. As long as I use username and password and can connect to my switch and run commands. But if I use ssh_key (which works fine if I just ssh to the device without paramiko) my script will not execute:

Unknown exception: q must be exactly 160, 224, or 256 bits long
Traceback (most recent call last):
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2109, in run
    handler(self.auth_handler, m)
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
    sig = self.private_key.sign_ssh_data(blob)
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/dsskey.py", line 109, in sign_ssh_data
    key = dsa.DSAPrivateNumbers(
  File "/home/ansible/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 244, in private_key
    return backend.load_dsa_private_numbers(self)
  File "/home/ansible/.local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 826, in load_dsa_private_numbers
    dsa._check_dsa_private_numbers(numbers)
  File "/home/ansible/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 282, in _check_dsa_private_numbers
    _check_dsa_parameters(parameters)
  File "/home/ansible/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 274, in _check_dsa_parameters
    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ValueError: q must be exactly 160, 224, or 256 bits long

Traceback (most recent call last):
  File "./sshkey_backup_comware_config.py", line 19, in <module>
    with ConnectHandler(**sw_wai_01) as net_connect:
  File "/home/ansible/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/ansible/.local/lib/python3.8/site-packages/netmiko/hp/hp_comware.py", line 11, in __init__
    return super().__init__(**kwargs)
  File "/home/ansible/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 350, in __init__
    self._open()
  File "/home/ansible/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 355, in _open
    self.establish_connection()
  File "/home/ansible/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/client.py", line 682, in _auth
    self._transport.auth_publickey(username, key)
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/transport.py", line 1580, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/auth_handler.py", line 236, in wait_for_response
    raise e
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2109, in run
    handler(self.auth_handler, m)
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
    sig = self.private_key.sign_ssh_data(blob)
  File "/home/ansible/.local/lib/python3.8/site-packages/paramiko/dsskey.py", line 109, in sign_ssh_data
    key = dsa.DSAPrivateNumbers(
  File "/home/ansible/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 244, in private_key
    return backend.load_dsa_private_numbers(self)
  File "/home/ansible/.local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 826, in load_dsa_private_numbers
    dsa._check_dsa_private_numbers(numbers)
  File "/home/ansible/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 282, in _check_dsa_private_numbers
    _check_dsa_parameters(parameters)
  File "/home/ansible/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 274, in _check_dsa_parameters
    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ValueError: q must be exactly 160, 224, or 256 bits long

My pip packets are as follows:

/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Package                      Version             
---------------------------- --------------------
ansible                      2.9.6               
apache-libcloud              2.8.0               
apturl                       0.5.2               
argcomplete                  1.8.1               
bcrypt                       3.2.0               
blinker                      1.4                 
catfish                      1.4.13              
certifi                      2019.11.28          
cffi                         1.15.0              
chardet                      3.0.4               
Click                        7.0                 
colorama                     0.4.3               
cryptography                 3.4.7               
cupshelpers                  1.0                 
dbus-python                  1.2.16              
defer                        1.0.6               
distro                       1.4.0               
distro-info                  0.23ubuntu1         
dnspython                    1.16.0              
entrypoints                  0.3                 
future                       0.18.2              
httplib2                     0.14.0              
idna                         2.8                 
iotop                        0.6                 
Jinja2                       2.10.1              
jmespath                     0.9.4               
keyring                      18.0.1              
language-selector            0.1                 
launchpadlib                 1.10.13             
lazr.restfulclient           0.14.2              
lazr.uri                     1.0.3               
lightdm-gtk-greeter-settings 1.2.2               
lockfile                     0.12.2              
macaroonbakery               1.3.1               
MarkupSafe                   1.1.0               
menulibre                    2.2.1               
mugshot                      0.4.2               
netaddr                      0.7.19              
netifaces                    0.10.4              
netmiko                      3.4.0               
ntc-templates                3.0.0               
ntlm-auth                    1.1.0               
oauthlib                     3.1.0               
olefile                      0.46                
onboard                      1.4.1               
packaging                    21.3                
paramiko                     2.8.1               
pbr                          5.8.1               
pexpect                      4.6.0               
Pillow                       7.0.0               
pip                          20.0.2              
pip-licenses                 3.5.3               
pip-review                   1.1.1               
protobuf                     3.6.1               
psutil                       5.5.1               
PTable                       0.9.2               
pycairo                      1.16.2              
pycparser                    2.21                
pycrypto                     2.6.1               
pycups                       1.9.73              
PyGObject                    3.36.0              
PyJWT                        1.7.1               
pykerberos                   1.1.14              
pymacaroons                  0.13.0              
PyNaCl                       1.4.0               
pyparsing                    3.0.7               
pyRFC3339                    1.1                 
pyserial                     3.5                 
python-apt                   2.0.0+ubuntu0.20.4.6
python-dateutil              2.7.3               
python-debian                0.1.36ubuntu1       
pytz                         2019.3              
pywinrm                      0.3.0               
pyxdg                        0.26                
PyYAML                       5.3.1               
reportlab                    3.5.34              
requests                     2.22.0              
requests-kerberos            0.12.0              
requests-ntlm                1.1.0               
requests-unixsocket          0.2.0               
scp                          0.14.4              
SecretStorage                2.3.1               
selinux                      3.0                 
setuptools                   45.2.0              
sgt-launcher                 0.2.5               
simplejson                   3.16.0              
six                          1.16.0              
ssh-import-id                5.10                
systemd-python               234                 
tenacity                     8.0.1               
testresources                2.0.1               
textfsm                      1.1.0               
ubuntu-advantage-tools       27.3                
ubuntu-drivers-common        0.0.0               
unattended-upgrades          0.1                 
urllib3                      1.25.8              
wadllib                      1.3.3               
wheel                        0.34.2              
xcffib                       0.8.1               
xkit                         0.0.0               
xmltodict                    0.12.0   


Sorry if this is an obvious issues, new to both netmiko and python!

Also new to github and can't find the develop version to test with, could I get a link to that from someone?

Thanks for any help!

**Comment by megakarl** [comment]
I am also running in to some issues with the ssh_key. Everything works fine either when using a username and password and I have verified that the ssh_key works from the client otherwise.

I saw you mention testing the develop branch. What do I do to install or activate that?

**Comment by ktbyers** [comment]
You can also use the following with the `develop` branch, but the easy fix is to downgrade to Paramiko 2.8.1.

https://github.com/ktbyers/netmiko/issues/2652

**Comment by megakarl** [comment]
Hey ktbeyers, thansk for replying.

I was already in version 2.8.1 of paramiko.

This is my pip list :

Package                      Version             
---------------------------- --------------------
ansible                      2.9.6               
apache-libcloud              2.8.0               
apturl                       0.5.2               
argcomplete                  1.8.1               
bcrypt                       3.1.7               
blinker                      1.4                 
catfish                      1.4.13              
certifi                      2019.11.28          
chardet                      3.0.4               
Click                        7.0                 
colorama                     0.4.3               
cryptography                 2.8                 
cupshelpers                  1.0                 
dbus-python                  1.2.16              
defer                        1.0.6               
distro                       1.4.0               
distro-info                  0.23ubuntu1         
dnspython                    1.16.0              
entrypoints                  0.3                 
future                       0.18.2              
httplib2                     0.14.0              
idna                         2.8                 
iotop                        0.6                 
Jinja2                       2.10.1              
jmespath                     0.9.4               
keyring                      18.0.1              
language-selector            0.1                 
launchpadlib                 1.10.13             
lazr.restfulclient           0.14.2              
lazr.uri                     1.0.3               
lightdm-gtk-greeter-settings 1.2.2               
lockfile                     0.12.2              
macaroonbakery               1.3.1               
MarkupSafe                   1.1.0               
menulibre                    2.2.1               
mugshot                      0.4.2               
netaddr                      0.7.19              
netifaces                    0.10.4              
netmiko                      2.4.2               
ntlm-auth                    1.1.0               
oauthlib                     3.1.0               
olefile                      0.46                
onboard                      1.4.1               
paramiko                     2.8.1               
pexpect                      4.6.0               
Pillow                       7.0.0               
pip                          20.0.2              
protobuf                     3.6.1               
psutil                       5.5.1               
pycairo                      1.16.2              
pycrypto                     2.6.1               
pycups                       1.9.73              
PyGObject                    3.36.0              
PyJWT                        1.7.1               
pykerberos                   1.1.14              
pymacaroons                  0.13.0              
PyNaCl                       1.3.0               
pyRFC3339                    1.1                 
pyserial                     3.4                 
python-apt                   2.0.0+ubuntu0.20.4.6
python-dateutil              2.7.3               
python-debian                0.1.36ubuntu1       
pytz                         2019.3              
pywinrm                      0.3.0               
pyxdg                        0.26                
PyYAML                       5.3.1               
reportlab                    3.5.34              
requests                     2.22.0              
requests-kerberos            0.12.0              
requests-ntlm                1.1.0               
requests-unixsocket          0.2.0               
scp                          0.13.0              
SecretStorage                2.3.1               
selinux                      3.0                 
setuptools                   45.2.0              
sgt-launcher                 0.2.5               
simplejson                   3.16.0              
six                          1.14.0              
ssh-import-id                5.10                
systemd-python               234                 
textfsm                      1.1.0               
ubuntu-advantage-tools       27.3                
ubuntu-drivers-common        0.0.0               
unattended-upgrades          0.1                 
urllib3                      1.25.8              
wadllib                      1.3.3               
wheel                        0.34.2              
xcffib                       0.8.1               
xkit                         0.0.0               
xmltodict                    0.12.0  

Let me know if there is anything else I can try or how I can go about to get the netmiko develop branch if that could solve the issue.

**Comment by ktbyers** [comment]
@megakarl Okay, you should open a new issue in GitHub and include your full exception stack trace (also include in that post that you are using Paramiko 2.8.1 so I don't forget and ask you again).

Also please include your Python / Netmiko code.

**Comment by sydasif** [comment]
I have the same issue but solved with paramiko 2.8.1 thanks 🙏

**Comment by ktbyers** [comment]
@sydasif You can also specify the `disabled_algorithms:

```
disabled_algorithms = {'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']}
```

Netmiko should support this now.

**Comment by ktbyers** [comment]
This would be an argument to ConnectHandler.

**Comment by sydasif** [comment]
Thanks for replying.
