### ISSUE TITLE
Spaces in commands fail to trigger TextFSM template

### ISSUE THREAD

**Issue by wardy3** [ktbyers/netmiko#2656]
Hi. Thanks for the great work!

I have a statement in my script to send a command and retrieve structured output
```python
        structured_output: list[dict] = ssh.send_command(
            command, use_textfsm=True, max_loops=MAX_LOOPS
        )
```
This works fine when there is a match in the `index` file for the command. For example `sh port-sec database` has this entry
```
cisco_nxos_show_port_security_database.textfsm, .*, cisco_nxos, sh[[ow]] port-s[[ecurity]] da[[tabase]]
```

However, if my user enters the command with more than one space between the words, it doesn't match.

Is this an easy fix to ignore duplicate spaces? Or will i need to clean up the command string in my script?

thanks!

**Comment by ktbyers** [comment]
@wardy3 You probably should just cleanup the command string in your script i.e. normalize it there.

The above is really not a Netmiko issue i.e. this would be an ntc-template issue and potentially a textfsm library issue itself.
