### ISSUE TITLE
Square brackets are being removed from SROS MDCLI 

### ISSUE THREAD

**Issue by svautour** [ktbyers/netmiko#2659]
Nokia SROS MDCLI contains square brackets in the config. These are being stripped by netmiko. Example:

A:admin@rr# admin show configuration |match area pre-lines 5 post-lines 5
            ipv6-routing native
            level-capability 2
            router-id 10.1.0.15
            system-id 0100.0100.0015
            traffic-engineering true
            area-address [49.0000]
            segment-routing {
                admin-state enable
                prefix-sid-range {
                    global
                }

(config-env) root@hyper10:/containerlab/config-env# python3 -V
Python 3.8.10

(config-env) root@hyper10:/containerlab/config-env# pip3 list|egrep netmiko
netmiko       3.4.0  

Simple script to get the config:

from netmiko import ConnectHandler

dev = {
    'device_type' : 'nokia_sros',
    'host' : "clab-c1-rr",
    'username' : "xxx",
    'password' : "xxx"
}
router_conn = ConnectHandler(**dev)
NokiaCMDOutput = router_conn.send_command('''admin show configuration''')
print (repr(NokiaCMDOutput))
print (NokiaCMDOutput)
router_conn.disconnect()

The output:

(config-env) root@hyper10:/containerlab/config-env# python3 test.py 
---snip---
  isis 0 {\n            admin-state enable\n            advertise-passive-only true\n            advertise-router-capability as\n            ldp-sync false\n            ignore-attached-bit true\n            ipv6-routing native\n            level-capability 2\n            router-id 10.1.0.15\n            system-id 0100.0100.0015\n            traffic-engineering true\n            area-address             segment-routing {\n                admin-state enable\n                prefix-sid-range {\n                    global\n                }\n            }\n            interface "TO_TS11" {\n                interface-type point-to-point\n                level-capability 2\n            }\n            interface "TO_TS12" {\n                interface-type point-to-point\n                level-capability 2\n            }\n            interface "system" {\n                passive true\n  
---snip---
       isis 0 {
            admin-state enable
            advertise-passive-only true
            advertise-router-capability as
            ldp-sync false
            ignore-attached-bit true
            ipv6-routing native
            level-capability 2
            router-id 10.1.0.15
            system-id 0100.0100.0015
            traffic-engineering true
            area-address             segment-routing {
                admin-state enable
                prefix-sid-range {
                    global
                }
            }

Thanks,
Serge

**Comment by ktbyers** [comment]
Okay, yeah that looks like a bug.

**Comment by ktbyers** [comment]
Should be fixed here:

https://github.com/ktbyers/netmiko/pull/2732

@svautour Any possibility you can test that fix?
