### ISSUE TITLE
A10: Initial prompt read fails with default delay factors

### ISSUE THREAD

**Issue by saparikh** [ktbyers/netmiko#2672]
In my testing the A10 device connection often fails because netmiko is not able to find the prompt. I was able to alleviate that by implementing this quick fix:

```
diff --git a/netmiko/a10/a10_ssh.py b/netmiko/a10/a10_ssh.py
index 5ca269d7..7ba5286c 100644
--- a/netmiko/a10/a10_ssh.py
+++ b/netmiko/a10/a10_ssh.py
@@ -8,10 +8,10 @@ class A10SSH(CiscoSSHConnection):
     def session_preparation(self) -> None:
         """A10 requires to be enable mode to disable paging."""
         self._test_channel_read(pattern=r"[>#]")
-        self.set_base_prompt()
+        self.set_base_prompt(delay_factor=8)
```

In my testing, I tried setting `delay_factor` to 2 and 4, but neither option worked across all of the devices in my inventory.

**Comment by ktbyers** [comment]
Proposed fix is here:

https://github.com/ktbyers/netmiko/pull/2673
