### ISSUE TITLE
Key Based Auth - Cisco IOS

### ISSUE THREAD

**Issue by AuthenticAMD** [ktbyers/netmiko#2675]
JSON connection file parameters:

"device_type": "autodetect",
"ip": "1.1.1.1",
"username": "username",
"password": "password",
"secret": "enable",
"port": "22",
"fast_cli": false,
"allow_agent": true

This is enough to allow successful key based authentication with Cisco Nexus devices. However it does not work with Cisco IOS / IOSXE devices. Cisco IOSXE devices (ASR1009x, ISR4431) are running modern versions of code.

I've tried the solution in https://github.com/ktbyers/netmiko/issues/322, but it doesn't seem to help.

I'm using Putty, and the private key is password protected. If I try to SSH without using netmiko, I can get into the devices. Any ideas on why? I know this is likely a Paramiko issue, but there has to be someone successfully using key based authentication through netmiko, with putty / agent forwarding.

Paramiko 2.9.2
Netmiko 3.4.0

**Comment by AuthenticAMD** [comment]
Investigating possibility this is related.

https://stackoverflow.com/questions/70565357/paramiko-authentication-fails-with-agreed-upon-rsa-sha2-512-pubkey-algorithm

**Comment by AuthenticAMD** [comment]
Lastly, leads me to
https://github.com/ktbyers/netmiko/pull/2646

Looks like I'll need to run the development branch and then disable the sha2 algorithms.

**Comment by ktbyers** [comment]
@AuthenticAMD As a quick test you can verify that `paramiko==2.8.1` fixes the issue (i.e. if you temporarily downgrade your Paramiko does it work).

**Comment by AuthenticAMD** [comment]
@ktbyers I'm sure that will work too, but wanted to run the newer version if possible. I've confirmed that connection to current version NXOS, IOSXE, and IOSXR works now if the rsa-sha2-512, and rsa-sha2-256 is disabled when previously IOSXE and IOSXR wouldn't connect at all **with key based authentication**.

"disabled_algorithms": {"disabled_algorithms": "rsa-sha2-512, rsa-sha2-256"}

**Comment by AuthenticAMD** [comment]
I thought the format I provided worked, but that is not the case. Maybe it changed from 4.0.0a4 to final release 4.0.0.

Must be formatted as follows:

```
"disabled_algorithms": { "pubkeys": ["rsa-sha2-256","rsa-sha2-512"]}
```
