### ISSUE TITLE
Unit testing improvements

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#268]
Test line wrapping behavior / terminal width

**Comment by johnarnold** [comment]
Do you have a decent way to mock the SSH session?  Either at the channel / paramiko level, or by mocking a ssh device?  I'm writing unit tests on top of netmiko, could be really useful.

**Comment by ktbyers** [comment]
@johnarnold I haven't been doing any mock testing with Netmiko as so many of the problems issues are timing or other CLI idiosyncrasies that I have questioned whether it is worth doing.

I am totally open to discussion on this, however.

We are doing mocking in NAPALM (which has several drivers that are based on Netmiko) and their I think it totally makes sense (at least for all of the get operations).
