### ISSUE TITLE
Cisco NXOS: read timeout when command is invalid

### ISSUE THREAD

**Issue by saparikh** [ktbyers/netmiko#2682]
When trying to collect show command output from a large set of NXOS devices, I ran into a situation in which some commands are not valid on all of the devices. An example:

```
NXOS1# show ip ospf neighbor
                ^
% Invalid command at '^' marker.
NXOS1# 
```

This is resulted in the following exception in Netmiko:
```
ERROR:03/14/2022 04:02:36 PM Command show ip ospf neighbor to NXOS1 failed
Traceback (most recent call last):
  File "/tmp/pycharm_project_924/collection_helper.py", line 81, in run_command
    expect_string=pattern)
  File "/storage/samir/git/netmiko/netmiko/utilities.py", line 600, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/storage/samir/git/netmiko/netmiko/base_connection.py", line 1644, in send_command
    new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
  File "/storage/samir/git/netmiko/netmiko/base_connection.py", line 1370, in command_echo_read
    pattern=re.escape(cmd), read_timeout=read_timeout
  File "/storage/samir/git/netmiko/netmiko/base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'show\\ ip\\ ospf\\ neighbor' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

**Comment by saparikh** [comment]
After digging into the code, I tried this patch locally:
```
(datacollection) samir@bfeu1804:~/git/netmiko$ git diff
diff --git a/netmiko/base_connection.py b/netmiko/base_connection.py
index dca85992..0965b2d1 100644
--- a/netmiko/base_connection.py
+++ b/netmiko/base_connection.py
@@ -1366,7 +1366,7 @@ A paramiko SSHException occurred during connection creation:
     def command_echo_read(self, cmd: str, read_timeout: float) -> str:
 
         # Make sure you read until you detect the command echo (avoid getting out of sync)
-        new_data = self.read_until_pattern(
+        new_data = self.read_until_prompt_or_pattern(
             pattern=re.escape(cmd), read_timeout=read_timeout
         )
```

which has resolved the issue for me. However, I am not sure if this is the correct long-term fix or not, so opening this issue so it can be tracked and discussed.

**Comment by saparikh** [comment]
I am running latest develop:

```
commit a6d5103670d63016075db2f225a1d0ef395fc5a3 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Kirk Byers <ktbyers@twb-tech.com>
Date:   Mon Mar 14 11:50:17 2022 -0700

    Fixing exception message issue (#2681)
```

**Comment by ktbyers** [comment]
Why isn't this echoed?

`show ip ospf neighbor`

It looks like it should be given what you posted above. Even when it is an invalid command it should still be echoed?

**Comment by ktbyers** [comment]
It works fine/properly for me using the `develop` branch?

```python
import os
from netmiko import ConnectHandler

password = os.environ["NETMIKO_PASSWORD"]

nxos1 = {
    "name": "nxos1",
    "device_type": "cisco_nxos",
    "host": "nxos1.lasthop.io",
    "username": "pyclass",
    "password": password,
}

for device in (nxos1,):
    device_name = device.pop("name")
    conn = ConnectHandler(**device)
    output = conn.send_command("show ip ospf neighbor")
    print()
    print("-" * 80)
    print(output)
    print("-" * 80)
    print()
```

**Comment by ktbyers** [comment]
```
$ python nxos_test1.py 
--------------------------------------------------------------------------------
             ^
% Invalid command at '^' marker.

--------------------------------------------------------------------------------


```

**Comment by saparikh** [comment]
what output do you see?  and what version of NXOS are you running?

before I made my change, I was getting that error. after I made my change the error went away

**Comment by ktbyers** [comment]
@saparikh The above isn't an error. That is the expected behavior i.e. that is the actual output of that command (since it is an intentionally invalid command).

So above Netmiko is doing exactly what it is supposed to do.

**Comment by saparikh** [comment]
i added this debug code to help debug the error, in case it resurfaced.

```
index a3a19ded..6df73ad6 100644
--- a/netmiko/base_connection.py
+++ b/netmiko/base_connection.py
@@ -611,6 +611,19 @@ where x is the total number of seconds to wait before timing out.\n"""
         # if read_timeout == 0 or 0.0 keep reading indefinitely
         while (time.time() - start_time < read_timeout) or (not read_timeout):
             output += self.read_channel()
+
+### samir debug code
+            debug_msg = f"""
+B-------------------------------------------------------------------------
+{time.time()}
+{self.host}
+{output}
+E-------------------------------------------------------------------------
+"""
+            if self.session_log:
+                self.session_log.write(debug_msg)
+###
+
             if re.search(pattern, output, flags=re_flags):
                 results = re.split(pattern, output, maxsplit=1, flags=re_flags)
```

but, so far i have been unable to reproduce this error. 

When I first filed this issue, it happened consistently when I was polling a large inventory of devices, but not when polling devices individually.

I am going to close this issue for now. If it happens again and I have new information, I will reopen it.

**Comment by ktbyers** [comment]
Sounds good.

Kirk

**Comment by JuukoHenry12** [comment]
hi how can sort the issue above on my end,am facing the same issue on both Huawei and Cisco_iso devices,
def get_expect_string(connection):
    prompt = connection.find_prompt().strip()
    return re.escape(prompt)

@bp.route('/api/connect', methods=['POST'])
def send_command():
    data = request.get_json()
    device = data.get('device')
    commands = data.get('commands', [])

    if not device or not commands:
        return jsonify({"error": "Device and commands are required"}), 400

    try:
        connection = get_session(device)
        expect_str = get_expect_string(connection)
        result = {}
        for command in commands:
            output = connection.send_command(command,expect_string=expect_str,read_timeout=60)
            result[command] = output
            print(output)
        return jsonify(result), 200
    except NetmikoTimeoutException:
        return jsonify({"error": "Connection timed out"}), 500
    except NetmikoAuthenticationException:
        return jsonify({"error": "Authentication failed"}), 401
    except Exception as e:
        logger.error(f"Error executing commands: {e}")
        return jsonify({"error": str(e)}), 500

**Comment by JuukoHenry12** [comment]
ERROR:app.routes:Error executing commands: 

Pattern not detected: 'show\\ running\\-config\\ interface\\ Gi0/3' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by JuukoHenry12** [comment]
ERROR:app.routes:Error executing commands: 

Pattern not detected: 'show\\ running\\-config\\ interface\\ Gi0/3' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
