### ISSUE TITLE
Queries to handle some scenarios 

### ISSUE THREAD

**Issue by bhaskar219** [ktbyers/netmiko#2684]
hi , 

need environment similar to popen subprocess in python
 Scenario : 
                - execute command , no need to wait , go for next steps 
                - if status of command is completed may be with in 30 mins or after 5 days , then get status  and proceed for next steps

but in netmiko:
   - - after executing command  ,  need to wait for the command to complete 
   - if the expected output is not there  then it will hang till timeout  or time out happens then it will comeout without completing the command 

so looking for simillar steps subprocess with netmiko or any alternative module.

If it is possible through netmiko , please share the steps .

Could you please suggest the same.

currently i am using subprocess , its working fine , but everything happening in one terminal , so want to distribute to multiple terminals and multiple machines also.

**Comment by ktbyers** [comment]
You can just use Python multiple processes or Python threads (or see Nornir for a specific implementation of threads that supports Netmiko).

But all of that should be doable.

**Comment by ktbyers** [comment]
Closing as not really a Netmiko issue here, but we can reopen and discuss (if needed).
