### ISSUE TITLE
Delay needed in check_enable_mode() for Aruba Wireless

### ISSUE THREAD

**Issue by mww012** [ktbyers/netmiko#269]
I've been working on adding support for Aruba controllers.  I had an issue getting into enable mode.  All would work fine while debugging and stepping through the process by hand, however, when just running the code, it always threw a "Failed to enter enable mode." exception.  After a little digging, it looks as though the check_enable_mode() in base_connection.py would send '\n' and check for the prompt before the Aruba controller has time to actually return to the prompt.  The end result is that the previously mentioned exception is thrown.

Adding a sleep between sending the command and checking for the prompt(shown below) fixes everything but I don't know if this is the preferred way to solve this issue.  I've also attached a screenshot of the logon process for reference.  I'm more than happy to give any other info that may be helpful.  Any thoughts?

```
def check_enable_mode(self, check_string=''):
    """Check if in enable mode. Return boolean."""
    self.remote_conn.sendall('\n')
    time.sleep(self.global_delay_factor) 
    output = self.read_until_prompt()
    return check_string in output
```

![arubacontroller_login](https://cloud.githubusercontent.com/assets/4991000/18397832/8641c07a-768f-11e6-8e62-8bf46dd41428.png)

**Comment by kadecole** [comment]
I would love to see aruba controller access added to the code.

**Comment by ktbyers** [comment]
@mww012 You should test this with the dev_1_0 branch code. This is probably going to be pushed live next week and some of the above has changed.

check_enable_mode() uses read_until_prompt()

```
    def check_enable_mode(self, check_string=''):
        """Check if in enable mode. Return boolean."""
        debug = False
        self.write_channel('\n')
        output = self.read_until_prompt()
        if debug:
            print(output)
        return check_string in output
```

This in turn will call _read_channel_expect() method which should wait for up to 8 seconds to read data or find the trailing prompt.

Anyways, let me know if it is still failing on the dev_1_0 branch. Also you should probably add an Aruba driver see https://github.com/ktbyers/netmiko/blob/master/VENDOR.md

**Comment by mww012** [comment]
I'm not a python dev, more of a hobbyist.  That said, I enjoy working on stuff like this because it's always a learning experience.  Think I hit one of those learning experiences now.  I checked out the dev_1_0 and the one thing that's missing is a ssh_connection.py file.  Should I just bring that over from master or should I use something else in its place?  Or did I just do something wrong?

**Comment by ktbyers** [comment]
Yes, let me update that document (this is a pretty recent change):

Here is an example:

```
from netmiko.cisco_base_connection import CiscoSSHConnection


class HuaweiSSH(CiscoSSHConnection):
```

**Comment by ktbyers** [comment]
Basically, if Aruba is pretty similar to Cisco from a CLI interaction perspective, then you should base it off CiscoSSHConnection which is now in netmiko.cisco_base_connection

If Aruba is not similar to Cisco, then base it off of BaseConnection, for example:

For example:
```
from netmiko.base_connection import BaseConnection


class JuniperSSH(BaseConnection):

```

**Comment by mww012** [comment]
So after beating my head against a wall for a bit trying to figure out why I couldn't get things to work properly, I realized that today I can't spell session_preparation properly.  After fixing that things went as expect but, unfortunately, it still looks like I need the delay in the check_enable_mode function. 

Having to change a base_connection function seems like something I should avoid but I'm not sure what else to do to make this work.  Thoughts?

**Comment by ktbyers** [comment]
Can you link to your current code and post the exception you are getting? 

On the face of it, I don't see why you would need to add an extra sleep.

**Comment by mww012** [comment]
Thanks for all the help btw.

Here's my code...
https://github.com/mww012/netmiko/tree/dev_1_0

You'll see that I've got the sleep command in the base_connection.py/check_enable_mode function and it works as is.  If you take that sleep line out it gets the following error.  Below that is the actual code I'm using to test.
```
Traceback (most recent call last):
  File "c:\Users\mw6000975\playground\git\netmiko\test_aruba_os.py", line 16, in <module>
    net_connect = ConnectHandler(**aruba_os)
  File "c:\Users\mw6000975\playground\git\netmiko\netmiko\ssh_dispatcher.py", line 92, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "c:\Users\mw6000975\playground\git\netmiko\netmiko\base_connection.py", line 89, in __init__
    self.session_preparation()
  File "c:\Users\mw6000975\playground\git\netmiko\netmiko\aruba\aruba_ssh.py", line 9, in session_preparation
    self.enable()
  File "c:\Users\mw6000975\playground\git\netmiko\netmiko\cisco_base_connection.py", line 15, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "c:\Users\mw6000975\playground\git\netmiko\netmiko\base_connection.py", line 715, in enable
    raise ValueError("Failed to enter enable mode.")
ValueError: Failed to enter enable mode.
```

```
from netmiko import ConnectHandler


aruba_os = {
    'device_type': 'aruba_os',
    'ip': '10.1.200.242',
    'username': 'user',
    'password': 'pass',
    'secret': 'enable_secret'
}

net_connect = ConnectHandler(**aruba_os)
output = net_connect.send_command('show version')
print output
```

**Comment by ktbyers** [comment]
@mww012 Try it with set_base_prompt() first:

```
class ArubaSSH(CiscoSSHConnection):
    """Aruba OS support"""
    def session_preparation(self):
        """Aruba OS requires enable mode to disable paging."""
        self.set_base_prompt()
        self.enable()
        self.disable_paging(command="no paging")
```

Let me know if this works?

**Comment by mww012** [comment]
That seems to fix it. :)  Any idea why it worked at all prior to switching those lines?  Now working on getting config mode right.  Thanks again for the help.

Also, any chance I could get access to the slack channel?

**Comment by ktbyers** [comment]
@mww012 The base_prompt is used to determine when a command is done in many contexts (including for .enable() ). 

You can sign-up for the slack channel here:

http://slack.networktocode.com/

There is a Netmiko sub-channel.


Kirk
