### ISSUE TITLE
Enhancement request for IOS device missing password setup

### ISSUE THREAD

**Issue by sockduct** [ktbyers/netmiko#271]
Kirk - would be nice to differentiate between a failed authentication and an IOS device not being setup.

Failed authentication = bad username/password

Password not setup:
R1#telnet 172.31.255.1
Trying 172.31.255.1 ... Open

Password required, but none set

[Connection to 172.31.255.1 closed by foreign host]

Agree?  If yes, I can take a stab at a patch...  I find this type of problem more often then you'd expect, especially in controls/embedded system type environments.

**Comment by ktbyers** [comment]
Hmmmm...how about still failed authentication, but catch the 'Password required, but none set' and return that as part of the NetMikoAuthentication message?

**Comment by sockduct** [comment]
That works - interested in taking a patch for this?

**Comment by ktbyers** [comment]
@sockduct Yes, sounds good.

**Comment by sockduct** [comment]
@ktbyers Is this too simple?

In base_connection.py, in telnet_login(), after if re.search(r"sername", output): but before elif re.search(r"assword", output):, insert the following conditional:
```
                elif re.search(r"assword required, but none set", read_data):
                    if debug:
                        print("Z-Fail-Noauthsetup")
                    self.host += " reports: password required, but none set"
                    # Exit while loop
                    i = max_loops
```

**Comment by ktbyers** [comment]
@sockduct Why the self.host += " reports..."?

As opposed to i = max_loops I would just raise the NetMikoAuthentication exception and pass in the 'password required, but none set' as the message to it.

**Comment by sockduct** [comment]
OK - did it like you said and added immediate support for no authentication and starting at a prompt.  Looks like you added that as a fallback after max_loops - any reason not to test for prompt immediately?  I submitted a PR with my minor changes - let me know what you think.

**Comment by sockduct** [comment]
Closing since you're accepting the PR into dev 1.1 branch
