### ISSUE TITLE
Textfsm using the wrong device_type fails

### ISSUE THREAD

**Issue by migmorales22** [ktbyers/netmiko#2712]
I'm trying to work with textfsm to make reporting of a bunch of devices.

But first I wanna know how it work.

This is the script
`from netmiko import ConnectHandler
from getpass import getpass
from pprint import pprint

cisco1 = {
    "device_type": "cisco_ios",
    "host": "10.192.33.115",
    "username": "jmimorales",
    "password": getpass(),
}

command = "show ip int brief"
with ConnectHandler(**cisco1) as net_connect:
    # Use TextFSM to retrieve structured data
    output = net_connect.send_command(command, use_textfsm=True)

print(output)
`
But the output isn't parse, it just normal

`
Mon Mar 28 16:14:33.294 GMT

Interface                      IP-Address      Status          Protocol Vrf-Name
Loopback0                      10.192.33.115   Up              Up       default 
Loopback1                      190.56.112.237  Up              Up       default 
Loopback10                     216.230.136.196 Up              Up       default 
PW-Ether1                      216.230.137.177 Up              Up       default 
PW-Ether11                     10.87.54.89     Up              Up       default 
PW-Ether12                     10.31.109.217   Up              Up       default 
PW-Ether28                     10.31.73.137    Down            Down     default 
PW-Ether39                     10.174.181.157  Shutdown        Down     default 
PW-Ether41                     10.174.196.145  Down            Down     default 
MgmtEth0/RSP0/CPU0/0           unassigned      Shutdown        Down     default 
MgmtEth0/RSP0/CPU0/1           unassigned      Shutdown        Down     default 
TenGigE0/0/2/0                 10.192.41.74    Up              Up       default 
TenGigE0/0/2/1                 10.192.41.78    Up              Up       default 
TenGigE0/0/2/2                 unassigned      Shutdown        Down     default 
TenGigE0/0/2/3                 unassigned      Shutdown        Down     default 
`

I don't know if netmiko is not finding textfsm.

`
Package       Version
------------- -------
bcrypt        3.2.0
cffi          1.15.0
cryptography  36.0.2
distlib       0.3.4
filelock      3.6.0
future        0.18.2
Jinja2        3.1.1
MarkupSafe    2.1.1
netmiko       4.0.0
ntc-templates 3.0.0
packaging     21.3
paramiko      2.10.3
pip           22.0.4
pip-review    1.1.1
platformdirs  2.5.1
pycparser     2.21
PyNaCl        1.5.0
pyparsing     3.0.7
pyserial      3.5
scp           0.14.4
setuptools    61.2.0
six           1.16.0
tenacity      8.0.1
textfsm       1.1.2
virtualenv    20.14.0
wheel         0.37.1
XlsxWriter    3.0.3
`

`
josem@MIG ssh-multiple-sessions-textfsm % python3
Python 3.9.7 (default, Sep  3 2021, 04:31:11) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ntc_templates
>>> ntc_templates.__file__
'/opt/homebrew/lib/python3.9/site-packages/ntc_templates/__init__.py'
>>> exit()
`

It would be nice, if someone can help me. Thanks so much in advance.

**Comment by applericky** [comment]
Hi @migmorales22,


I do believe you might be missing the following on your print.

```

pprint(output)

```

You have a regular print.
Double p that line.

There could be another reason but I think that should be it.

Have you seen this Article?

[Netmiko and TextFSM
Author: Kirk Byers
Date: 2022-01-13](https://pynet.twb-tech.com/blog/netmiko-and-textfsm.html)

**Comment by migmorales22** [comment]
Thank u @applericky 

I figure it out, I need to be sure that the template and the device match with the exact command

**
from netmiko import ConnectHandler
from getpass import getpass
from pprint import pprint

cisco1 = {
    "device_type": "cisco_xr",
    "host": "10.192.33.115",
    "username": "jmimorales",
    "password": getpass(),
}

command = "show ip int brief"
with ConnectHandler(**cisco1) as net_connect:
    # Use TextFSM to retrieve structured data
    output = net_connect.send_command(command, use_textfsm=True)


print(output)
**

Now it works as expected.

**[{'intf': 'Loopback0', 'ipaddr': '10.192.33.115', 'status': 'Up', 'proto': 'Up', 'vrf': 'default'}, {'intf': 'Loopback1', 'ipaddr': '190.56.112.237', 'status': 'Up', 'proto': 'Up', 'vrf': 'default'}, {'intf': 'Loopback10', 'ipaddr': '216.230.136.196', 'status': 'Up', 'proto': 'Up', 'vrf': 'default'}, {'intf': 'PW-Ether1', 'ipaddr': '216.230.137.177', 'status': 'Up', 'proto': 'Up', 'vrf': 'default'}, {'intf': 'PW-Ether11', 'ipaddr': '10.87.54.89', 'status': 'Up', 'proto': 'Up', 'vrf': 'default'}, {'intf': 'PW-Ether12', 'ipaddr': '10.31.109.217', 'status': 'Up', 'proto': 'Up', 'vrf': 'default'}, {'intf': 'PW-Ether28', 'ipaddr': '10.31.73.137', 'status': 'Down', 'proto': 'Down', 'vrf': 'default'}, {'intf': 'PW-Ether39', 'ipaddr': '10.174.181.157', 'status': 'Shutdown', 'proto': 'Down', 'vrf': 'default'}, {'intf': 'PW-Ether41', 'ipaddr': '10.174.196.145', 'status': 'Down', 'proto': 'Down', 'vrf': 'default'}, {'intf': 'MgmtEth0/RSP0/CPU0/0', 'ipaddr': 'unassigned', 'status': 'Shutdown', 'proto': 'Down', 'vrf': 'default'}, {'intf': 'MgmtEth0/RSP0/CPU0/1', 'ipaddr': 'unassigned', 'status': 'Shutdown', 'proto': 'Down', 'vrf': 'default'}, {'intf': 'TenGigE0/0/2/0', 'ipaddr': '10.192.41.74', 'status': 'Up', 'proto': 'Up', 'vrf': 'default'}, {'intf': 'TenGigE0/0/2/1', 'ipaddr': '10.192.41.78', 'status': 'Up', 'proto': 'Up', 'vrf': 'default'}, {'intf': 'TenGigE0/0/2/2', 'ipaddr': 'unassigned', 'status': 'Shutdown', 'proto': 'Down', 'vrf': 'default'}, {'intf': 'TenGigE0/0/2/3', 'ipaddr': 'unassigned', 'status': 'Shutdown', 'proto': 'Down', 'vrf': 'default'}]**

Either way thank you men

**Comment by applericky** [comment]
Ahh! I'm glad you were able to get it up and running. Those device types with Cisco get me too!

@ktbyers I would say this one is good to close out.

**Comment by ktbyers** [comment]
I changed the title, just for people that might search on this later.

So the issue was you had an IOS-XR device, but initially tried to use the `cisco_ios` device_type--correct?

**Comment by migmorales22** [comment]
> I changed the title, just for people that might search on this later.
> 
> So the issue was you had an IOS-XR device, but initially tried to use the `cisco_ios` device_type--correct?

Yes, that was the issue. At first, I thought that Netmiko doesn't know where the TextFSM templates are, but that was not the problem.

Thanks.
