### ISSUE TITLE
Backslash added in hostname leading to 'pattern not detected'

### ISSUE THREAD

**Issue by JulienSSH** [ktbyers/netmiko#2713]
I'm trying to execute a list of commands on devices from a specific inventory by using Nornir. It seems I'm facing an issue at Netmiko level. For some reasons backslash are added to the hostname of some IOS devices (not all) leading to below error:

```
Traceback (most recent call last):
  File "/home/administrator/venv_nornir/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/administrator/venv_nornir/lib/python3.8/site-packages/nornir_napalm/plugins/tasks/napalm_cli.py", line 20, in napalm_cli
    result = device.cli(commands)
  File "/home/administrator/venv_nornir/lib/python3.8/site-packages/napalm/ios/ios.py", line 2372, in cli
    output = self._send_command(command)
  File "/home/administrator/venv_nornir/lib/python3.8/site-packages/napalm/ios/ios.py", line 205, in _send_command
    output = self.device.send_command(command)
  File "/home/administrator/venv_nornir/lib/python3.8/site-packages/netmiko/utilities.py", line 600, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/administrator/venv_nornir/lib/python3.8/site-packages/netmiko/base_connection.py", line 1694, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:
Pattern not detected: 'CPE\\-XXX\\-YYYYYY\\-ZZZZZZZZ>' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.
```

For exemple, device hostname 'CPE-XXX-YYYYYY-ZZZZZZZZ>' is converted according ReadTimeout error to: 'CPE\\-XXX\\-YYYYYY\\-ZZZZZZZZ>'.

To share more details you can find below inventory connection_options settings:
```
    "provider": {
      "name": "provider",
      "connection_options": {
        "napalm": {
          "extras": {
            "optional_args": {
              "force_no_enable": true,
              "ssh_config_file": "~/.ssh/config"
            }
          },
          "hostname": null,
          "port": null,
          "username": null,
          "password": null,
          "platform": null
        },
        "netmiko": {
          "extras": {
            "fast_cli": false,
            "global_delay_factor": 2
          },
          "hostname": null,
          "port": null,
          "username": null,
          "password": null,
          "platform": null
        }
      }
```

The tricky point is the issue doesn't appear for all devices even if they are using the same plateform (ios) and same OS version. Moreover, I'm not 100% sure the issue is coming from the hostname.

I'm reaching devices through IP and I can not set the pattern cause I don't know before to connect to devices the configured hostname.

Could you please help me to solve this issue?

**Comment by ktbyers** [comment]
The backslash is fine (that is just normal/standard regular expression escaping). In other words, hyphen is a special character so it needs escaped.

```
>>> import re
>>> re.escape("CPE-XXX-YYYYYY-ZZZZZZZZ>")
'CPE\\-XXX\\-YYYYYY\\-ZZZZZZZZ>'
```

**Comment by ktbyers** [comment]
Can you post your Nornir code?

Which `command` are you sending to the device?

Also, you might want to set both global_delay_factor=2 and fast_cli=False:

```yaml
        "napalm": {
          "extras": {
            "optional_args": {
              "fast_cli": false,
              "global_delay_factor": 2
              "force_no_enable": true,
              "ssh_config_file": "~/.ssh/config"
            }
          },
```

In other words, I see you have these defined when you directly use the Netmiko driver, but you are not setting them for NAPALM (and NAPALM IOS calls Netmiko under-the-hood so it likely needs them also).

**Comment by JulienSSH** [comment]
Thanks for your help ktbyers! I'm using really basic command on nornir:
```
  results = task.run(
    name="Execute commands",
    task=napalm_cli,
    commands=['show interfaces']
  )
```

I updated napalm optional_args as you advised but unfortunately it didn't help.

I still don't understand why this is issue is appearing only for specific devices beacause I'm able to connect to all devices using SSH.

**Comment by JulienSSH** [comment]
Ok I don't have any idea of the reason of the issue but for some reason we rebooted the devices and my script is working as expected now.

**Comment by ktbyers** [comment]
Okay, FWIW I pretty much never use napalm_cli. 

In this case, I would probably say you should just straight Netmiko (i.e. you are just adding a layer of indirection to get at the Netmiko driver). So if it comes up again, I will probably ask if you can reproduce the issue directly using Netmiko.

**Comment by ktbyers** [comment]
@kambata-bg Not really enough information to help you there. It is probably unrelated to the backslashes however.

You should probably open a separate ticket and provide more details about your code and the full exception stack.

**Comment by kambata-bg** [comment]
@ktbyers thanks for the reply, will do :)
