### ISSUE TITLE
FortiGate sending back line feed in 'Do you want to continue'

### ISSUE THREAD

**Issue by ultimattt** [ktbyers/netmiko#2716]
I am running on macOS with Python3.8. Trying to use send_command_timing to execute a task and provide a 'y' in the process.
It's failing because I don't think it's passing a carriage return, but instead adding a ^J to the command. I know fortinet support is experimental, however whatever I can do to help improve support, I'd be happy to assist.

Script looks like this:

```#!/usr/bin/env python
from netmiko import ConnectHandler
from getpass import getpass

fortigate = {
    "device_type": "fortinet",
    "host": "fortigate.fqdn",
    "username": "admin",
    "password": getpass(),
}

command = "execute wireless-controller delete-wtp-image all"
net_connect = ConnectHandler(**fortigate)
#
# CLI Interaction is as follows:
#  fortigate# execute wireless-controller delete-wtp-image all
#  This operation will remove all specified WTP images!
#    Do you want to continue? (y/n)
#
output = net_connect.send_command_timing(
    command_string=command,
    strip_prompt=False,
    strip_command=False
)
# If we're prompted if were're sure
if "Do you want to continue?" in output:
    output += net_connect.send_command_timing(
        command_string="n",
        strip_prompt=True,
        strip_command=False
    )

net_connect.disconnect()

print()
print(output)
print()
```

Output looks like this:

matt@Matts-Mac-mini ~ % /usr/local/bin/python3 /Users/matt/Downloads/test-this.py
Password: 

execute wireless-controller delete-wtp-image all
This operation will remove all specified WTP images!
Do you want to continue? (y/n)y**^J**

asm-gate # 

My question is if I am even referencing the example provided by Kirk correctly, 2 how i fix that added "^j".
Thoughts?

**Comment by ktbyers** [comment]
Can you separate the two parts i.e. make an output1 and an output2 for the two separate send_command_timing() calls.

Probably should set strip_prompt=False and strip_command=False in both cases.


Also can you post what this looks like when you do it manually via the CLI (i.e. just capture it and paste it here)?

**Comment by ultimattt** [comment]
Hey ktbyers, thanks for responding. Sorry for my delay in responseSo I changed the script a bit to look like this:

```
#!/usr/bin/env python
from netmiko import ConnectHandler
from getpass import getpass

fortigate = {
    "device_type": "fortinet",
    "host": "asm-gate.ultraviolet.network",
    "username": "admin",
    "password": getpass(),
}

command = "execute wireless-controller delete-wtp-image all"
net_connect = ConnectHandler(**fortigate)
#
# CLI Interaction is as follows:
#  fortigate# execute wireless-controller delete-wtp-image all
#  This operation will remove all specified WTP images!
#    Do you want to continue? (y/n)
#
output = net_connect.send_command_timing(
    command_string=command,
    strip_prompt=False,
    strip_command=False
)
print("Print value of output")
print(output)
# If we're prompted if we're sure
if "Do you want to continue?" in output:
    output2 = net_connect.send_command_timing(
        command_string="y",
        strip_prompt=False,
        strip_command=False
    )
    print("")
    print("")
    print("Printing output2")
    print(output2)
```

And got the following output:

```
matt@Matts-Mac-mini ~ % /usr/local/bin/python3 /Users/matt/Downloads/test-this.py
Password: 
Print value of output
execute wireless-controller delete-wtp-image all
This operation will remove all specified WTP images!
Do you want to continue? (y/n)


Printing output2
y^J

Command cancelled by user.

asm-gate #
```

Also, it should look like this in real life:

```
asm-gate # exec wireless-controller delete-wtp-image all
This operation will remove all specified WTP images!
Do you want to continue? (y/n)y


asm-gate#
```

**Comment by ktbyers** [comment]
Looking it up online "^J" (control-J) is a line feed. I am guessing it is from the device. I guess your terminal emulator ignores it when you login manually (but printing it out doesn't).

I don't really see any reason that it would be from Netmiko.

Do you actually fail to hand the `Do you want to continue`? Does that actually get stuck and not work?

**Comment by ktbyers** [comment]
If you aren't seeing any issue and the only problem is the `^J` in the output, then just strip that from the output (i.e. remove that character from the output in your code so that it doesn't show up).

**Comment by ultimattt** [comment]
Well... I think you're right. I just ran a test and it's working. I think the added `^j` was confusing me - noob at best with Python here, super green with Netmiko, in fact this is the first thing I used it for - so thanks for the double check.

I do have access to FortiOS, if there's any way I can help improve the support from Experimental to something more mainstream please let me know.

**Comment by ktbyers** [comment]
Yeah, I couldn't see any reason that Netmiko would send that (and it seems plausible to me that the Fortigate would automatically send a line-feed after that). But definitely assumptions on my part.

If you want to run the Netmiko test suite on the fortios, that would be helpful.

The process is here.

Make sure you are using Netmiko 4.0.0 or alternatively the Netmiko `develop` branch.
