### ISSUE TITLE
Slack link is inactive

### ISSUE THREAD

**Issue by DarkPhily** [ktbyers/netmiko#2722]
I know, that is not an issue directly connected to development of netmiko. But I have some questions and wanted to join you on slack to geht them answered. Unfortunately the link is inactive.

I would appreciate it if you could renew the link.

**Comment by ktbyers** [comment]
Yeah, Slack doesn't keep their invite links active indefinitely (even though they indicate they should stay active).

Can you ping me or contact me via LinkedIn or Twitter and we can get you the invite.

@DarkPhily 

My linkedin is here:

https://www.linkedin.com/in/ktbyers/
