### ISSUE TITLE
Unable to login into zte router

### ISSUE THREAD

**Issue by panda2799** [ktbyers/netmiko#2724]
Hi Ktbyers.

I have just started learning netmiko module. I am following your documentation. Tried to login into zte router but its throwing me some errors.

netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Could you please guide me how to resolve this issue. And also is there any link to follow to perform some commands like ping a device or traceroute. Don't know where to start all these things. 

Thanks!

**Comment by luweijun1992** [comment]
> Hi Ktbyers.
> 
> I have just started learning netmiko module. I am following your documentation. Tried to login into zte router but its throwing me some errors.
> 
> netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.
> 
> Common causes of this problem are:
> 
> 1. Incorrect hostname or IP address.
> 2. Wrong TCP port.
> 3. Intermediate firewall blocking access.
> 
> Could you please guide me how to resolve this issue. And also is there any link to follow to perform some commands like ping a device or traceroute. Don't know where to start all these things.
> 
> Thanks!

The connection should have timed out, add a timeout.
```
huawei = {
    "device_type": "huawei",
    "host": "192.168.255.57",
    "username": "admin",
    "password": 'Admin@huawei.com',
    "conn_timeout": 30,
    'session_log': "logs/192.168.255.57.log"
}
```

**Comment by panda2799** [comment]
Hi,

Putting the connection time out statement it didn't worked. I believe if the router has port 22 open. Would that must be the case

**Comment by ktbyers** [comment]
Are you able to manually SSH into the router from the server you are running your script on? Can you show me what that login process looks like (i.e. post the SSH login output here).

**Comment by panda2799** [comment]
Hi kt

I tried via putty but it says network timed out popup. The thing is i don't have any other router like cisco to practice on. Can i practice this work through gns3 lab excercise? To login into a simulator cisco router.

**Comment by panda2799** [comment]
It looks like i m messing up in assigning the ips. For sure the wifi router part is not working.

**Comment by panda2799** [comment]
After trying all the things from cloud to a cisco router

I confugured loopback interface and assigned a ip to my router belonging to same submet as of loopback address but when i am trying to ping its showing me destination not reachable or requested time out

**Comment by ktbyers** [comment]
Okay, this all sounds like not Netmiko issues so I am just going to close this.
