### ISSUE TITLE
read_timeout not working with send_config_set

### ISSUE THREAD

**Issue by itzzmeshashi** [ktbyers/netmiko#2725]
Hi,

I'm using send_config_set with read_timeout set to 40sec. I'm sending a few set commands and a commit to a palo alto firewall.
The commit is actually taking 36 sec to complete, but netmiko is sending '\n' to get the read the prompt after around 10sec which is raising a read timeout exception.

I did test individually with read_timeout_override and passing read_timeout in send_command, both are working fine. I noticed this only with send_config_set command.

netmiko version : 4.0

**Comment by nivaldoinacios** [comment]
same issue here

**Comment by ktbyers** [comment]
@itzzmeshashi @nivaldoinacios Can you both post the failing code and the exception message that you are receiving.

**Comment by ktbyers** [comment]
I am pretty sure this issue was subsequently fixed...so closing.
