### ISSUE TITLE
Netmiko failed to fetch large output approx 104KB and has empty string as output.

### ISSUE THREAD

**Issue by govindrathod1987** [ktbyers/netmiko#2726]
Netmiko failed to fetch large output approx 104KB and has empty string as output.

**sample code:**
linux = {
        'device_type': 'linux',
        "session_log": 'netmiko_session.log',
        'ip': '',
        'username': '',
        'password': '',
        'port': 22,
        'verbose': True
    }
cmd0 = "docker exec -ti hpe_nfc /bin/sh"
cmd2 = nnsadm_loc + '/nnsadm -a ' + primary_vlan_ip + " -q portal -f json"

net_connect = ConnectHandler(**linux)
output1 = net_connect.send_command_timing(cmd0, delay_factor=5)
time.sleep(1)
prompt = net_connect.find_prompt(delay_factor=2)
print(prompt)
output = net_connect.send_command_timing(cmd2, delay_factor=30)
print(output)
 print(type(output))

the output of this code is:

<class 'str'>

tried capturing the session logs and below is the content of the same:

Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-100-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon 11 Apr 2022 11:30:19 AM UTC

  System load:     0.0                IPv4 address for docker0: 172.18.0.1
  Usage of /:      59.0% of 32.35GB   IPv4 address for ens160:  172.17.17.66
  Memory usage:    57%                IPv4 address for ens161:  100.100.5.254
  Swap usage:      0%                 IPv4 address for ens192:  100.100.2.254
  Processes:       535                IPv4 address for ens224:  100.100.3.254
  Users logged in: 1                  IPv4 address for ens256:  100.100.4.254

57 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Mon Apr 11 11:29:54 2022 from 172.17.17.240
sfm_admin@ubuntuonprem:~$ 
sfm_admin@ubuntuonprem:~$ docker exec -ti hpe_nfc /bin/sh
# 

Note: When manually entered the command (cmd2) in code above, I see valid Json output of 104KB in ssh terminal.

**Comment by ktbyers** [comment]
You shouldn't use `send_command_timing` for very large output, you should use `send_command` with a known terminating pattern i.e. expect_string argument (or alternatively use the trailing prompt which is the default).

It is unlikely that send_command_timing will successfully capture large outputs (given the way it works).
