### ISSUE TITLE
IOS_XR cmd send failure | newlines being pre/appended 

### ISSUE THREAD

**Issue by code-dave** [ktbyers/netmiko#2730]
Basic import and parameters set:
>_from netmiko import ConnectHandler
parms = {
"device_type": "cisco_xr",
"host": ip,
"username": username,
"password": password
}_

Create reference
>_c = ConnectHandler(**parms)_ 

Find prompt
>_c.find_prompt()_
**'RP/0/RP0/CPU0:Hostname#'**

Attempt  send cmd
>_c.send_command('show route vrf all 1.1.1.1')_
**_'\n% This command is not authorized'_**

I thought maybe the terminal width had something to do with the issue, so I tried setting it, and got this output:

> c.set_terminal_width('500')
"500\r\n\r                              ^\r\n% Invalid input detected at '^' marker.\r\nRP/0/RP0/CPU0:Hostname#"

> c.set_terminal_width('show clock')
'show clock\r\n\r% This command is not authorized\r\nRP/0/RP0/CPU0:Hostname#'

**#Manual Testing**
Output of show route command works without issue.

>RP/0/RP0/CPU0:Hostname#show route vrf all 1.1.1.1
Wed Apr 13 19:17:11.038 UTC

>VRF: MGMT

>Routing entry for 0.0.0.0/0

<output omitted>

**Comment by code-dave** [comment]
_>>> c.send_command('\nshow clock')
'\n\nRP/0/RP0/CPU0:CSSneMUScghdc01#show clock\n\n% This command is not authorized'
>>>_

**Comment by ktbyers** [comment]
What does your IOS-XR device do if you just send an `enter` by itself?

**Comment by ktbyers** [comment]
Are you sure you are logging in with Netmiko using the same user that you are logging in manually with?

The above just looks like standard `AAA` rejecting the command.

**Comment by ktbyers** [comment]
This all works fine for me:

```
In [5]: c = ConnectHandler("iosxr.domain.io", username="admin", password=getpass(), device_type="cisco_xr")
Password: 

In [6]: c.find_prompt()
Out[6]: 'RP/0/RP0/CPU0:iosxr3-with-very-long-hostname-plus#'

In [7]: c.send_command("show clock")
Out[7]: '\nWed Apr 13 21:57:33.298 UTC\n21:57:33.371 UTC Wed Apr 13 2022'

In [8]: c.send_command("\nshow clock")
Out[8]: '\nWed Apr 13 21:57:39.342 UTC\n21:57:39.405 UTC Wed Apr 13 2022'

In [9]: c.send_command("\nshow clock\n")
Out[9]: '\nWed Apr 13 21:57:47.983 UTC\n21:57:48.053 UTC Wed Apr 13 2022'
```

**Comment by code-dave** [comment]
Apologizes @ktbyers . It appears different permissions were being assigned to the sessions, based on source IP. With that, the sessions permissions were being limited for the netmiko sessions.

Sorry again for the misunderstanding. I did not at all mean to waste your time.

**Comment by ktbyers** [comment]
@code-dave No worries at all.
