### ISSUE TITLE
Aruba AOS-CX - Timed-out reading channel, data not available

### ISSUE THREAD

**Issue by EarlRamirez** [ktbyers/netmiko#2738]
I am getting "Timed-out reading channel, data not available" each time I try to send changes to an Aruba AOS-CX device

I am trying to send the banner to the switch and each time I get the error, I tried delay_factor, cmd_verify=False and I have not received the expected behaviour 

I use a class in a separate file and the class that I use is
class NetworkDevice(object):
    '''
    Connect to networking devices and execute show commands or make changes to the 
    device using netmiko's send_config_set or send config from file. In the simplest form
    the  class can be used as follows.
    from myclass import NetworkDevice
    net_dev = NetworkDevice('192.168.122.100', 'aruba_os', 'user1', getpass()) # if the device username is not admin, it must be specified
    net_dev.establish_conn()
    net_dev.show_cmd('show version')
    '''
    
    def __init__(self, username, address, password, device_type, session=60):
        self.address = address
        self.device_type = device_type
        self.username = username
        self.password = password
        self.session = session

    # Establish a connection with the remote device    
    def establish_conn(self):
        #self.password = getpass()
        device = {
            'username': self.username,
            'host': self.address,
            'password': self.password,
            'device_type': self.device_type,
            'session_timeout': self.session,
            'verbose': True,
            'global_delay_factor': 2,
            'fast_cli': False,
            'session_log': 'output.log'
        }
        
        print(f'connecting to {self.address}....')
        ssh_conn = ConnectHandler(**device)
        self.remote_conn = ssh_conn
        
    # define show commands function
    def send_cmd(self, send_cmd):
        show_results = self.remote_conn.send_command(send_cmd)
        return show_results

    # define configuration function 
    def config_cmd(self, send_cfg):
        config_results = self.remote_conn.send_config_set(send_cfg, delay_factor=4)
        print(config_results)
     
    # define function to send configuration as a file   
    def config_file_cmd(self, send_file):
        file_results = self.remote_conn.send_config_from_file(send_file)
        print(file_results)

    # define function to save the configuration
    def save_config(self):
        wr_mem = self.remote_conn.send_command('write memory')
        print(wr_mem)

The script  is 
my_dev = { 'host1' : '192.168.100.20'}

try:
    for host,ip_addr in net_devs.items():
        base_cmd = '''banner motd !
############################## My Sample Banner ##################################
    This 
    is 
    a 
    long 
    multiline
    banner
    for the network devices
############################# My Sample Banner ##################################!'''
        
        if 'host1' == host:
        # Call NetworkDevice class and specify the netmiko parameters
            net = NetworkDevice('admin', ip_addr, ssh_password, 'aruba_procurve')
            
            # Establish connection
            net.establish_conn()
            
            # Send command to the switch
            output = net.config_cmd(f'{base_cmd}')
            print(output)
            net.save_config()
except Exception as e:
    print(e)

From logging
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: Last login: 2022-04-17 12:45:56 from 10.109.216.37
User "user1" has logged in 294 times in the past 30 days
host1# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:paramiko.transport:[chan 0] Unhandled channel request "keepalive@openssh.com"
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
host1# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
host1# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is host1#
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:Pattern is: terminal
DEBUG:netmiko:_read_channel_expect read_data: terminal width 511

DEBUG:netmiko:Pattern found: terminal terminal width 511

DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: 
no page

DEBUG:netmiko:write_channel: b'\nno page\n'
DEBUG:netmiko:Pattern is: no\ page
DEBUG:netmiko:_read_channel_expect read_data: Invalid input: width

DEBUG:netmiko:_read_channel_expect read_data: host1# 
host1# no page
host1# 
DEBUG:netmiko:Pattern found: no\ page Invalid input: width
host1# 
host1# no page
host1# 
DEBUG:netmiko:Invalid input: width
host1# 
host1# no page
host1# 
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
host1# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'configure terminal\n'
DEBUG:netmiko:Pattern is: configure\ terminal
DEBUG:netmiko:_read_channel_expect read_data: configure terminal

DEBUG:netmiko:Pattern found: configure\ terminal configure terminal

DEBUG:netmiko:Pattern is: host1
DEBUG:netmiko:_read_channel_expect read_data: host1(config)# 
DEBUG:netmiko:Pattern found: host1(config)# 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
host1(config)# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'banner motd !\############################## My Sample Banner ##################################
This
is
a
long
multiline
banner
for the network devices
############################# My Sample Banner ##################################!\n'
DEBUG:netmiko:Pattern is: banner\ motd\ !\
############################## My Sample Banner ##################################
This
is
a
long
multiline
banner
for the network devices
############################# My Sample Banner ##################################!!
DEBUG:netmiko:_read_channel_expect read_data: banner motd !

DEBUG:netmiko:_read_channel_expect read_data: Enter a new banner. Terminate the banner with the delimiter you have chosen.
host1(config-banner-motd)# ############################# My Sample Banner ##################################
host1(config-banner-motd)#     This 
host1(config-banner-motd)#     use 
host1(config-banner-motd)#     provisions 
host1(config-banner-motd)#     Laws 
host1(config-banner-motd)#     indi
host1(config-banner-motd)#     you
host1(config-banner-motd)#     d
host1(config-banner-motd)# ############################# My Sample Banner ##################################!
host1(config)# 
DEBUG:paramiko.transport:[chan 0] Unhandled channel request "keepalive@openssh.com"

From the session log

Last login: 2022-04-17 12:45:56 from 10.109.216.37
User "admin" has logged in 294 times in the past 30 days
host1# 
host1# 
host1# terminal width 511
Invalid input: width
host1# 
host1# no page
host1# 
host1# configure terminal
host1(config)# 
host1(config)# banner motd !
Enter a new banner. Terminate the banner with the delimiter you have chosen.
host1(config-banner-motd)# ############################# My Sample Banner ##################################
host1(config-banner-motd)#     This 
host1(config-banner-motd)#     use 
host1(config-banner-motd)#     provisions 
host1(config-banner-motd)#     Laws 
host1(config-banner-motd)#     indi
host1(config-banner-motd)#     you
host1(config-banner-motd)#     d
host1(config-banner-motd)# ############################# My Sample Banner ##################################!
host1(config)#

**Comment by ktbyers** [comment]
@EarlRamirez `aruba_os` device_type is for the Aruba Wireless Controllers.

Can you try to use `aruba_osswitch` device_type instead and let me know if that works (or not).


Regards, Kirk

**Comment by EarlRamirez** [comment]
> 
Thanks @ktbyers I tried with aruba_osswitch and I am seeing the same behaviour, also I an see the same thing in the session and debug log. The command executes on the device but seems to sit waiting for something before it timeout. This is the same behaviour I see when I use aruba_os, aruba_procurve, and now aruba_osswitch. On a more positive note I get the expected results when I use send_config_from_file.

**Comment by ktbyers** [comment]
Banner commands are a bit of a special case due to them not echoing in a way that Netmiko matches.

I would try the following:

```python
# define configuration function 
def config_cmd(self, send_cfg, cmd_verify=True):
    config_results = self.remote_conn.send_config_set(send_cfg, cmd_verify=cmd_verify, delay_factor=4)
    print(config_results)
```

Then for `banner` commands send in `cmd_verify=False`

Note, this assumes that you are using Netmiko 4.0.0

**Comment by ktbyers** [comment]
I would still use the `aruba_osswitch` device_type.

Let me know if this works or not.

**Comment by EarlRamirez** [comment]
Thanks, @ktbyers using Netmiko 4.0.0 together with cmd_verify=False worked.
