### ISSUE TITLE
Extreme ERS Netmiko 4 -  Pattern not detected: '[>#]' in output. 

### ISSUE THREAD

**Issue by mrkslm** [ktbyers/netmiko#2739]
Hello,
I am using a simple script to configure SNMPv3 username and password. With Netmiko 3 it works perfectly but with Netmiko 4 I get an error:

Pattern not detected: '[>#]' in output.

```
def connect_to_switch(ip, comms):
    print(f"Connecting to {ip}")
    switch = {
        'device_type': 'extreme_ers',
        'host': ip,
        'username': 'USERNAME',
        'password': 'PASSWORD',
        "global_delay_factor": 2
    }
    net_connect = ConnectHandler(**switch)    
    net_connect.special_login_handler()        
     
    for command in comms:
        v = net_connect.send_command(command, expect_string=r'#')
        print(v)
    net_connect.disconnect()
 
 
if __name__ == "__main__":
    # Commands to sent
    commands = ['configure terminal',
                "snmp-server user SNMPUSERNAME sha SECURE_PASS aes SECURE_PASS read-view snmpv1Objs",
                "wr mem",
                ]
 
     
    connect_to_switch('10.10.10.10', commands)
  
```

Here is the DEBUG log file. The "host1#" is there  and it should match the but somehow it does not understand the pattern.

> 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> [2J[0m[0;0f[1;1H[2;1H[3;1H[4;1H[5;1H[6;1H[7;1H[8;1H[9;1H[10;1H[11;1H[12;1H[13;1H[14;1H[15;1H[14;1HEnter Ctrl-Y to begin.[16;3H****************************************************************************[17;3H*** Ethernet Routing Switch 4926GTS-PWR+    [17;76H***[18;3H*** Copyright (C) 1996-2021 Extreme Networks.  All rights reserved.      ***[19;3H*** This product is protected by one or more US patents listed           ***[20;3H*** at http://www.extremenetworks.com/patents along with                 ***[21;3H*** their foreign counterparts.                                          ***[22;3H***                                                                      ***[23;3H*** HW:01       FW:7.5.0.4   SW:v7.8.4.013[23;76H***[24;3H****************************************************************************[?25l
> DEBUG:netmiko:write_channel: b'\x19'
> DEBUG:netmiko:read_channel: [2J[18;1H[2K[19;1H[2K[20;1H[2K[2J[4;14HLast login: --
> [5;14HFailed retries since last login:  0
> [10;0HPress ENTER to continue
> [24;1H
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: [2J[?25h[2J[23;1H
> host1#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> host1#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> host1#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> host1#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> host1#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
>  
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> 
> DEBUG:netmiko:read_channel: host1#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'exit\n'
> DEBUG:paramiko.transport:EOF in transport thread

**Comment by ktbyers** [comment]
Can you try the following code instead (using Netmiko version 4):

```python
switch = {
    "device_type": "extreme_ers",
    "host": ip,
    "username": "USERNAME",
    "password": "PASSWORD",
    "global_delay_factor": 2,
}

with ConnectHandler(**switch) as net_connect:
    cmd = "snmp-server user SNMPUSERNAME sha SECURE_PASS aes SECURE_PASS read-view snmpv1Objs"
    v = net_connect.send_config_set(cmd)
    print(v)
    net_connect.save_config()
```

Netmiko will automatically enter/exit config mode for send_config_set. The `save_config()` method should handle the saving of running configuration to startup configuration.

Let me know what you see when you do this?

**Comment by mrkslm** [comment]
Hello,
Tried with the send_config_set but unfortunately got the same result. I will paste here the traceback I got:

```
Traceback (most recent call last):
  File "C:\Users\someuser\PycharmProjects\SNMPv3_test\snmpv3_test.py", line 16, in <module>
    with ConnectHandler(**switch) as net_connect:
  File "C:\Users\someuser\PycharmProjects\SNMPv3_test\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 344, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\someuser\PycharmProjects\SNMPv3_test\venv\lib\site-packages\netmiko\base_connection.py", line 434, in __init__
    self._open()
  File "C:\Users\someuser\PycharmProjects\SNMPv3_test\venv\lib\site-packages\netmiko\base_connection.py", line 440, in _open
    self._try_session_preparation()
  File "C:\Users\someuser\PycharmProjects\SNMPv3_test\venv\lib\site-packages\netmiko\base_connection.py", line 879, in _try_session_preparation
    self.session_preparation()
  File "C:\Users\someuser\PycharmProjects\SNMPv3_test\venv\lib\site-packages\netmiko\extreme\extreme_ers_ssh.py", line 13, in session_preparation
    self._test_channel_read(pattern=r"[>#]")
  File "C:\Users\someuser\PycharmProjects\SNMPv3_test\venv\lib\site-packages\netmiko\base_connection.py", line 1119, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "C:\Users\someuser\PycharmProjects\SNMPv3_test\venv\lib\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

**Comment by ktbyers** [comment]
The exception above looks like it is failing to properly login. I saw this in your original post:

```
Press ENTER to continue
```

Does it force you to do that as part of the login process?

**Comment by mrkslm** [comment]
I tried to log in directly to switch via ssh and yes it waits for Enter command:

At first it is username password, the comes the extreme special banner

```
Enter Ctrl-Y to begin.

  ****************************************************************************
  *** Ethernet Routing Switch 4950GTS-PWR+                                 ***
  *** Copyright (C) 1996-2019 Extreme Networks.  All rights reserved.      ***
  *** This product is protected by one or more US patents listed           ***
  *** at http://www.extremenetworks.com/patents along with                 ***
  *** their foreign counterparts.                                          ***
  ***                                                                      ***
  *** HW:02       FW:7.5.0.2   SW:v7.6.2.019                               ***
  ******
**********************************************************************
```

and then it is waiting for Enter:

```
   Last login: MON 2022-04-18 22:10:34 from IP address 10.10.10.10
             Failed retries since last login:  0




Press ENTER to continue
```

After that it is like normal prompt 
hostname01#

**Comment by ktbyers** [comment]
Okay, this looks like a Netmiko bug?

Netmiko looks like it was expecting `cnrl-y` and then username + password.

I am not sure if something changed here on the ERS or if it never really worked.

**Comment by ktbyers** [comment]
Here is the relevant Netmiko code:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/extreme/extreme_ers_ssh.py#L32-L40

**Comment by ReK42** [comment]
> Okay, this looks like a Netmiko bug?
> 
> Netmiko looks like it was expecting `cnrl-y` and then username + password.
> 
> I am not sure if something changed here on the ERS or if it never really worked.

On all current models the behaviour over SSH is username/password first, then Ctrl+Y, then Enter. This may differ over console connections and some older, end-of-life models but I believe it is true for all ERS models that are still supported by Extreme.

**Comment by ktbyers** [comment]
@ReK42 @mrkslm 

Can either of you test this fix and see if it works properly:

https://github.com/ktbyers/netmiko/pull/2814

**Comment by mrkslm** [comment]
@ktbyers  
Hey Kirk,
Tested with my device and it works now!

**Comment by ktbyers** [comment]
Okay, I merged that fix in. I am going to go ahead and close this issue.

If there is still an issue, just let me know.

**Comment by jross2828** [comment]
@ktbyers would you be able to explain how to implement the above fix? I'm new to Python, but am running into the issue where the enter prompt isn't allowing our scripts to run properly on the latest ERS code. Previous code was not requiring ENTER upon logging in.

**Comment by ktbyers** [comment]
@jross2828 You should be able to just update your Netmiko version using pip:

```
pip install netmiko==4.3.0
```
