### ISSUE TITLE
Cisco NXOS long send_command no commands work after

### ISSUE THREAD

**Issue by AuthenticAMD** [ktbyers/netmiko#2740]
Netmiko 3.4.0, 4.0.0b4

Cisco NXOS 9.3.x

When doing a long "conn.send_command", in this case, with 746 characters (adding big ssh key to user), it will successfully send the command, but any further send_command statements after will not process. There is no error message as the script completes successfully. The debug shows the same thing where the command is sent, but any further commands do not show up.

**Comment by AuthenticAMD** [comment]
Just tested it against current release 4.0.0 and observed the same thing.

**Comment by ktbyers** [comment]
Can you include the debug log and your code?

**Comment by AuthenticAMD** [comment]
Unfortunately I'm running this on a closed network and can't transfer stuff off easily. Here is a snippet of code I am transposing from the other network.


if device['device_type'] == 'cisco_nxos':
  conn.send_command('conf t', expect=r'#')
  conn.send_command('username john sshkey ssh-rsa Here_Is_Long_Key_That_Is_717_Characters_Long', expect=r'#')
  conn.send_command('end', expect=r'#')
  conn.send_command('copy run start', expect=r'#')


In the above, the "conf t" and "username john" statement will work fine. But the "end" and "copy run start" will not execute and does not show up in the log. Script does not stack trace. Just doesn't run the commands after "username john".

**Comment by ktbyers** [comment]
Have you tried the standard Netmiko way of doing the above? I.E. all configuration changes should really use `send_config_set()` (unless they do the odd behavior of prompting for something additional).

```python
cmd = "username john sshkey ssh-rsa Here_Is_Long_Key_That_Is_717_Characters_Long"
conn.send_config_set(cmd)
conn.save_config()
```

Netmiko will automatically enter/exit configuration mode.

Also is there anything else in your code that would hide errors i.e. are you wrapping the above code in a try/except.

Last question, when you say the debug log shows the same thing i.e. the command is sent, but nothing further shows up. What is the text in the last few lines of the debug log (you can remove your key or anything else that is confidential)?

**Comment by AuthenticAMD** [comment]
@ktbyers 

I tried your method with the send_config_set, and the same thing happened where the "long key" command ran, but a command after didn't run. There was also no config save attempted according to the output log. I do not have any try / except in this part of the code.

```
cmd = ["username john sshkey ssh-rsa Here_Is_Long_Key_That_Is_717_Characters_Long", "username alice role network-admin"]
conn.send_config_set(cmd)
conn.save_config()
```

I can try to reproduce the section of the log that I found interesting, which appeared in the "long key" part of the command. Here is a subset of it until I can type more of it tomorrow. In the log, in the middle of the ssh key string, there is a space then ^H. I've attempted to show it in bold below. The space appears at chacter 461 into the ssh key string part.

switch(config)# username john sshkey ssh-rsa AAAAB..... 3Slt **^H**/ck.......

**Comment by ktbyers** [comment]
@AuthenticAMD Oh, you should disable cmd_verify and try it again.

So: 

```python
cmd = "username john sshkey ssh-rsa Here_Is_Long_Key_That_Is_717_Characters_Long"
conn.send_config_set(cmd, cmd_verify=False)
conn.save_config()
```

I am assuming Netmiko 4.0.0 on all of this.

**Comment by AuthenticAMD** [comment]
@ktbyers I can confirm that works.

I have cmd_verify for other scripts. I just forgot about this option as a troubleshooting method. Is there a "simple" rule when to use cmd_verify and when not to?

**Comment by ktbyers** [comment]
`cmd_verify` will verify that the command you sent is properly echoed to the screen before moving on to the next command. It does this to help ensure that Netmiko's state does not get in front of the state of the networking device (i.e. Python is a lot faster than the Networking device so you don't want Netmiko to think it should be doing X when the device is still doing something from a step or two earlier).

The reason I knew it was likely cmd_verify is when you said the output wasn't what you actually sent i.e. the ^H and space in the output.

So one case you run into issues with cmd_verify is long commands as if you get beyond the terminal width the network device tries to make the output more human readable.

Another case you run into cmd_verify issues is if the device changes the command automatically from format one to format two (for example, you put in abbreviated commands and the device automatically echoes them in the canonical form).

**Comment by AuthenticAMD** [comment]
@ktbyers Thanks for the detailed response. I really appreciate it.
