### ISSUE TITLE
config_file_set fails to enter commands

### ISSUE THREAD

**Issue by jdoyl28** [ktbyers/netmiko#2746]
Hello all!

I am attempting to simply create and rename a VLAN on a cisco switch using config_file_set(). Unfortunately I have yet to see success. It appears it ultimately reach config mode, but fails to deliver the expected commands.

### **Returned Error**

PS C:\WINDOWS\system32> python.exe "C:\Users\user1\Desktop\Scripts\Netmiko manage device.py"
Traceback (most recent call last):
  File "C:\Users\user1\Desktop\Scripts\Netmiko manage device.py", line 38, in <module>
    output = net_connect.send_command("conf t")
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\utilities.py", line 600, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1694, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:
Pattern not detected: 'HOST\\-SWITCH1\\#' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

---------------------

### **Debugging Log**

HOST-SWITCH1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
HOST-SWITCH1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is HOST-SWITCH1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
HOST-SWITCH1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is HOST-SWITCH1#
DEBUG:netmiko:write_channel: b'conf t\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: conf
DEBUG:netmiko:read_channel:  t
DEBUG:netmiko:Pattern found: (conf\ t) conf t
DEBUG:netmiko:read_channel: Enter configuration commands, one per line.  End with CNTL/Z.
HOST-SWITCH1(config)#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
HOST-SWITCH1(config)#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
HOST-SWITCH1(config)#
DEBUG:netmiko:Pattern found: (#) 
HOST-SWITCH1(config)#
DEBUG:netmiko:write_channel: b'end\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: end
DEBUG:netmiko:Pattern found: (end) end
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: HOST-SWITCH1#
DEBUG:netmiko:Pattern found: (#.*) 
HOST-SWITCH1#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
HOST-SWITCH1#
DEBUG:netmiko:Pattern found: (#) 
HOST-SWITCH1#
DEBUG:netmiko:exit_config_mode: end
HOST-SWITCH1#
DEBUG:netmiko:write_channel: b'exit\n'
DEBUG:paramiko.transport:EOF in transport thread

-------------------------
### **Code**
```
import netmiko
from netmiko import ConnectHandler
from datetime import datetime
import logging

logging.basicConfig(filename='netmiko_global.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")


device = {
        "host":"192.168.2.5",
        "device_type":"cisco_ios",
        "port":"22",
        "username":"user_admin",
        "password":"123456",
        }

start_time = datetime.now()


config_commands = ["vlan 999","name EUD_VLAN999"]
                 
with ConnectHandler(**device) as net_connect:
    output = net_connect.send_config_set(config_commands,delay_factor=5,cmd_verify=False)
    output += net_connect.save_config()

end_time = datetime.now()

print(output)
print("total time: {}".format(end_time -start_time))


net_connect.disconnect()
```

**Comment by zohassadar** [comment]
`output = net_connect.send_command("conf t")` <- this line, which appears in your error but not in your code, is the issue.  The config mode prompt doesn't match the prompt being searched for.  The code accounts for the command necessary to get into config mode as well as accounting for the changed prompt when using `send_config_set`, so sending `conf t` is unnecessary.

**Comment by jdoyl28** [comment]
> `output = net_connect.send_command("conf t")` <- this line, which appears in your error but not in your code, is the issue. The config mode prompt doesn't match the prompt being searched for. The code accounts for the command necessary to get into config mode as well as accounting for the changed prompt when using `send_config_set`, so sending `conf t` is unnecessary.

Apologies, as I believe that line was accidentally included. I re-ran and re-captured the error as follows:

### **Error**
PS C:\WINDOWS\system32> python.exe "C:\Users\user1\Desktop\Scripts\Netmiko manage device.py"
Traceback (most recent call last):
  File "C:\Users\user1\Desktop\Scripts\Netmiko manage device.py", line 24, in <module>
    output = net_connect.send_config_set(config_commands,delay_factor=5,cmd_verify=False)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 2137, in send_config_set
    output += self.config_mode()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\cisco_base_connection.py", line 47, in config_mode
    return super().config_mode(
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1976, in config_mode
    output += self.read_until_prompt(read_entire_line=True)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 734, in read_until_prompt
    return self.read_until_pattern(
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'HOST\\-SWITCH1.*' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
Can you try using the Netmiko `develop` branch?

I think you might be running into this issue here which has previously been fixed:

```
https://github.com/ktbyers/netmiko/pull/2720
```

**Comment by jdoyl28** [comment]
> Can you try using the Netmiko `develop` branch?
> 
> I think you might be running into this issue here which has previously been fixed:
> 
> ```
> https://github.com/ktbyers/netmiko/pull/2720
> ```

Good Morning ktbyers,

I redirected to the develop branch and looks like everything functions as expected now. Thank you!
