### ISSUE TITLE
have netmiko installed but cant run the scripts

### ISSUE THREAD

**Issue by srooprai** [ktbyers/netmiko#275]
Hello
Im running netmiko on python 2.7 on a linux debian device. 
I have installed netmike via pip. 
>>> import netmiko
>>> dir (netmiko)
['ConnectHandler', 'FileTransfer', 'NetMikoAuthenticationException', 'NetMikoTimeoutException', 'NetmikoAuthError', 'NetmikoTimeoutError', 'SCPConn', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'a10', 'alcatel', 'arista', 'avaya', 'base_connection', 'brocade', 'cisco', 'cisco_base_connection', 'dell', 'enterasys', 'extreme', 'f5', 'fortinet', 'hp', 'huawei', 'juniper', 'linux', 'netmiko_globals', 'ovs', 'paloalto', 'platforms', 'quanta', 'scp_handler', 'ssh_dispatcher', 'ssh_exception', 'utilities', 'vyos']

i have netmiko installed as shown obove from the python shell. But a script on the same device show this

The script: junos.py
from netmiko import ConnectHandler
Juniper_mx5 ={
'device_type':'juniper_junos',
 'ip':'10.10.0.151',
 'username':'test',
'password':'nsadmin123',
}

def my_connectons():
        return ConnectHandler(**juniper_mx5)

 ./junos.py
from: can't read /var/mail/netmiko
./junos.py: rad 2: Juniper_mx5: kommandot finns inte
./junos.py: rad 3: device_type:juniper_junos,: kommandot finns inte
./junos.py: rad 4: ip:10.10.0.151,: kommandot finns inte
./junos.py: rad 5: username:test,: kommandot finns inte
./junos.py: rad 6: password:nsadmin123,: kommandot finns inte
./junos.py: rad 7: syntaxfel nära den oväntade symbolen "}"
./junos.py: rad 7: `}'

**Comment by ktbyers** [comment]
@srooprai You don't have the following at the top of your file:

```
#!/usr/bin/env python
```

So when you execute your script it is not being executed as a python script.

You either need to add the above or do

```
python myscript.py
```
