### ISSUE TITLE
Huawei and potentially HPE-Comware need a disconnect() method created

### ISSUE THREAD

**Issue by luweijun1992** [ktbyers/netmiko#2771]
Check log information and see that the last exit is "exit"
But Huawei "quit"

![image](https://user-images.githubusercontent.com/58923704/165908275-e50630d4-97e1-41b9-98a5-18e2ba9415a4.png)

![image](https://user-images.githubusercontent.com/58923704/165908488-5df5c7a2-22e7-4ed2-95c4-07d1f8568693.png)

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/2780
