### ISSUE TITLE
hp_comware H3C device will give 'Timed-out reading channel, data not available.'; only for RBM devices, others are normal

### ISSUE THREAD

**Issue by leojianli** [ktbyers/netmiko#2776]
DEBUG:paramiko.transport:starting thread (client mode): 0xabb24688
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.9.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Comware-7.1.064
INFO:paramiko.transport:Connected (version 2.0, client Comware-7.1.064)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: ecdh-sha2-nistp256, ecdh-sha2-nistp384, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1
DEBUG:paramiko.transport:server key: ssh-rsa
DEBUG:paramiko.transport:client encrypt: aes128-ctr, aes192-ctr, aes256-ctr, AEAD_AES_128_GCM, AEAD_AES_256_GCM, aes128-cbc, 3des-cbc, aes256-cbc, des-cbc
DEBUG:paramiko.transport:server encrypt: aes128-ctr, aes192-ctr, aes256-ctr, AEAD_AES_128_GCM, AEAD_AES_256_GCM, aes128-cbc, 3des-cbc, aes256-cbc, des-cbc
DEBUG:paramiko.transport:client mac: hmac-sha2-256, hmac-sha2-512, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
DEBUG:paramiko.transport:server mac: hmac-sha2-256, hmac-sha2-512, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
DEBUG:paramiko.transport:client compress: none, zlib, zlib@openssh.com
DEBUG:paramiko.transport:server compress: none, zlib, zlib@openssh.com
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Kex: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey: ssh-rsa
DEBUG:paramiko.transport:Cipher: aes128-ctr
DEBUG:paramiko.transport:MAC: hmac-sha2-256
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.165.240.19: b'89c8e9d5af94fb93607a0878de0b3362'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 

RBM_S<HZ_rndlabFW_J01-17u_M9K_backup>
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'

RBM_S<HZ_rndlabFW_J01-17u_M9K_backup>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'

RBM_S<HZ_rndlabFW_J01-17u_M9K_backup>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is RBM_S<HZ_rndlabFW_J01-17u_M9K_backup>
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: 
screen-length disable

DEBUG:netmiko:write_channel: b'\nscreen-length disable\n'
DEBUG:netmiko:Pattern is: BM_S<HZ_rndlabFW_J01\-17u_M9K_backup
RBM_S<HZ_rndlabFW_J01-17u_M9K_backup>
RBM_S<HZ_rndlabFW_J01-17u_M9K_backup>

RBM_S<HZ_rndlabFW_J01-17u_M9K_backup>
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
RBM_S<HZ_rndlabFW_J01-17u_M9K_backup>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'system-view\n'
DEBUG:netmiko:Pattern is: BM_S<HZ_rndlabFW
DEBUG:netmiko:_read_channel_expect read_data: s
RBM_S[HZ_rndlabFW_J01-17u_M9K_backup]

**Comment by ktbyers** [comment]
@andrewXiaoyu Can you post a larger section of your code. Please include `commands` with this.

I assume you are using Netmiko 4.1.0 and a device_type of `huawei`?
