### ISSUE TITLE
huawei failing on save_config() call

### ISSUE THREAD

**Issue by luweijun1992** [ktbyers/netmiko#2783]
May I ask what parameter time should be set for the error
```
  File "C:\Soft\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 2160, in send_config_set
    output += self.read_channel_timing(read_timeout=read_timeout)
  File "C:\Soft\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 720, in read_channel_timing
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

read_channel_timing's absolute timer expired.

The network device was continually outputting data for longer than 15
seconds.

If this is expected i.e. the command you are executing is continually emitting
data for a long period of time, then you can set 'read_timeout=x' seconds. If
you want Netmiko to keep reading indefinitely (i.e. to only stop when there is
no new data), then you can set 'read_timeout=0'.

You can look at the Netmiko session_log or debug log for more information.
```

**Comment by ktbyers** [comment]
Okay, can you show me the session_log and the exception stack trace. The original error you included above is not from `save_config`.

**Comment by luweijun1992** [comment]
> @luweijun1992 The log is not consistent with the code you showed above? What is sending the `exit` and why is there no `save_config()` execution?
> 
> Which version of Netmiko are you using?
> 
> You might have to look at Python debugger to see what is happening i.e. particularly on the save_config() call.
> 
> Can you also include the full exception stack trace?

netmiko            4.1.0
Exit is not saved
How do I get an exception stack trace ?

**Comment by ktbyers** [comment]
`Exit is not saved`???

I didn't understand what you meant here?

**Comment by luweijun1992** [comment]
> `Exit is not saved`???
> 
> I didn't understand what you meant here?



> `Exit is not saved`???
> 
> I didn't understand what you meant here?

Session_log: Exit is not saved after return.
![image](https://user-images.githubusercontent.com/58923704/169177680-24541185-f731-4ff0-b886-c0323f23eabf.png)

**Comment by ktbyers** [comment]
Okay, let's start over (as I don't see where else to go on this issue):

Can you create a simplified test case that illustrates the problem. Please include all of your code (for this simplified test case) and the full exception stack trace.

Regards, Kirk

**Comment by luweijun1992** [comment]
> Okay, let's start over (as I don't see where else to go on this issue):
> 
> Can you create a simplified test case that illustrates the problem. Please include all of your code (for this simplified test case) and the full exception stack trace.
> 
> Regards, Kirk

The error was caused by too much information being returned.

```
# -*- coding: utf-8 -*-
from netmiko import ConnectHandler

device = {
    "device_type": "huawei",
    "host": "10.x.x.251",
    "username": "main",
    "password": "xxx",
    'session_log': 'logs/10.x.x.251.log'
}

# Show command that we execute.
commands = '''
display current-configuration
display version
display device
display lldp neighbor brief
display ap all
'''
with ConnectHandler(**device) as net_connect:
    output = net_connect.send_command(commands)
    net_connect.send_config_set(commands, cmd_verify=False)
    net_connect.save_config()
```
![image](https://user-images.githubusercontent.com/58923704/169468258-3d6f8b8d-7bab-43e9-8f7a-717a150bd3b2.png)

**Comment by luweijun1992** [comment]
> Okay, let's start over (as I don't see where else to go on this issue):
> 
> Can you create a simplified test case that illustrates the problem. Please include all of your code (for this simplified test case) and the full exception stack trace.
> 
> Regards, Kirk

It's probably too much output.
I can execute normally with the following code.
`read_timeout=0`
```
# -*- coding: utf-8 -*-
from netmiko import ConnectHandler

device = {
    "device_type": "huawei",
    "host": "10.x.x.251",
    "username": "admin",
    "password": "xxx",
    'session_log': 'logs/10.x.x.251.log'
}

# Show command that we execute.
commands = '''
display current-configuration
display version
display device
display lldp neighbor brief
display ap all
'''
with ConnectHandler(**device) as net_connect:
    net_connect.send_config_set(commands.splitlines(), read_timeout=0, cmd_verify=False)
    net_connect.save_config()
```
![image](https://user-images.githubusercontent.com/58923704/169547129-d2644b7e-893c-4f68-9d87-dfdefb354d1f.png)

**Comment by ktbyers** [comment]
Okay, I am going to close this.

Using `show commands` with `send_config_set` is invalid (i.e. you are doing an invalid operation and Netmiko is not liking it).

If you see an issue with `save_config()` let me know, but the above just looks like `trying to send 'show' commands using a method only intended for configuration commands`.

**Comment by luweijun1992** [comment]
> Okay, I am going to close this.
> 
> Using `show commands` with `send_config_set` is invalid (i.e. you are doing an invalid operation and Netmiko is not liking it).
> 
> If you see an issue with `save_config()` let me know, but the above just looks like `trying to send 'show' commands using a method only intended for configuration commands`.

Because the commands that need to be operated on vary, it can be viewed now and configured next time, all using `send_config_set`
Or do you have any suggestions.

**Comment by ktbyers** [comment]
Because `send_config_set` is intended for configuration commands and one aspect of configuration commands is that they very frequently execute very quickly (i.e. within one or two seconds) and you are not particularly concerned about gathering the data from them (it is nice to have, but it is not the reason you are sending the command).

So you are sending long-running show commands using a method that is not intended for long-running show commands and it is failing.

I would look into either `send_multiline()` or use a for-loop and use `send_command()`.

Details on send_multiline are here:

https://pynet.twb-tech.com/blog/netmiko4-send-multiline.html

IIRC, by default `send_multiline` will look for the trailing prompt so you don't need to specify any additional terminating pattern. I.E. you can just send your list of commands.


Regards, Kirk
