### ISSUE TITLE
Enhancement Request - Provide option to log all read/writes from device to file equivalent to putty session log

### ISSUE THREAD

**Issue by halfmetaljacket** [ktbyers/netmiko#279]
Kirk - First thanks for Netmiko, I've gotten a lot mileage out of it already- I was looking through the code and didn't find a way to capture all output and commands applied to the device by Netmiko, beyond just the responses from explicit send_command/config calls. The idea here being equivalent to a putty or securecrt session log that saves everything the device sees and responds with.

I think the use case here would be not only debugging (both netmiko as well as user scripts that make use of netmiko), but would also provide a sort of audit trail if that were desired by the user.

Now that most all I/O is consolidated down to the read/write_channel methods I think this might be feasible, perhaps selecting on the existing `verbose` option or maybe a new `session_log` option. If you think this is worth looking into I can try my hand at a patch.

Thoughts?

**Comment by ktbyers** [comment]
@halfmetaljacket Yes, I like this idea. It would probably be good to have a way to have it write to a log file and/or standard output.

**Comment by ktbyers** [comment]
This is done, here and some other commits:

https://github.com/ktbyers/netmiko/commit/a1c1c7a6c62aa3af937d591e0285e0b2c23e3a3a

Still might be improvmeents to be made.
