### ISSUE TITLE
API documentation still shows legacy sub-module `ssh_exception`

### ISSUE THREAD

**Issue by matthias-colt** [ktbyers/netmiko#2791]
In the current [netmiko API documentation](https://ktbyers.github.io/netmiko/docs/netmiko/ssh_exception.html) the exceptions are still listed under the sub-module `ssh_exception` although since release 4.0.0 this has been moved to `exceptions`.

I found that the exceptions are also directly accessible under the main module, e.g. `netmico.NetMikoTimeoutException`.
Not sure if it is good practice to use them or better stick with `netmico.exceptions.NetMikoTimeoutException`, any recommendations?

**Comment by ktbyers** [comment]
It should be fine either way (as far as how to import them).

Docs need fixed/updated. I will need to look at that (as far as why it is still referring to the old/stale information).

**Comment by matthias-colt** [comment]
@ktbyers thanks for your prompt response and clarification!
