### ISSUE TITLE
Is it possible to use ssh proxy to connect to an IPv6 device behind an IPv4 jumphost?

### ISSUE THREAD

**Issue by aoterbear** [ktbyers/netmiko#2801]
Hi all,
First, thanks in advance for any help from anybody. I have an issue about netmiko when using SSH proxy.

Below is my topology:
```
laptop<---ipv4--->jumphost<---ipv6--->target_router
```
On the target router, a loopbak interface with IPv6 global unicast address configured as the management interface. So the jumphost and the target router are not directly connected, actually there is a backbone network between the jumphost and the target router.

Below is my code:
```
from netmiko import ConnectHandler

DEVICE_TYPE = 'cisco_xr'
SSH = "./ssh_config"
USERNAME = 'username'
PASSWORD = 'password'
HOST = 'IPv6_FAKE_ADDR'

net_connect = ConnectHandler(device_type=DEVICE_TYPE, ip=HOST, username=USERNAME, password=PASSWORD, ssh_config_file=SSH)
prompt = net_connect.find_prompt()
print(prompt)
```

Below is the error message raised from IDE:
```
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_xr <IPv6_FAKE_ADDR>:22
```

I tried to use the command  below in terminal, which can work:
```
ssh -F ./ssh_config <IPv6_FAKE_ADDR> 
```
More or less I think that means my ssh_config file is correct.

It also works if I replace the "IPv6_FAKE_ADDR" with an IPv4 address (in that case, I use my lab environment, because the production network is a pure IPv6 network), that means my topology changes to below:
```
laptop<---ipv4--->jumphost<---ipv4--->target_router
```

So my question is, in my use case, is it possible to use ssh proxy to connect to an IPv6 device behind an IPv4 jumphost?
Thanks again for any help~

**Comment by aoterbear** [comment]
Solved this by modifying my ssh_config file a little bit, very strange to me.

**Comment by ktbyers** [comment]
@aoterbear Okay, might be helpful if you post your solution (sanitized of anything confidential to you).

Glad you got it working.
