### ISSUE TITLE
Dealing with commands that do not return a prompt

### ISSUE THREAD

**Issue by Chuck-Thornton** [ktbyers/netmiko#2806]
I have looked all over and can't seem to find an answer that works consistently.

I have a script that will run iperf tests from router to router and I am having issues getting it to be consistent. I am running at the enable prompt with "guestshell run sudo iperf3 -s". It either says it is running and does not return a prompt or gives an error and returns a prompt. 

My issue comes into play when the script issues the above command but it doesn't return the output I am looking for to continue or not before it moves to the next command. I have tried different variations on send_commands_timing with delay_factor and max_loops set but it isn't consistent.

Below are snips from both the debug log and my code. Let me know if I need to submit more detail.

----------------------Relevant Code--------------------
```python
            iperf_status = att_connection.send_command_timing('guestshell run sudo iperf3 -s',
                                                              delay_factor=8, max_loops=600) # initial run of iperf
            if 'Server listening' in iperf_status: # check if it's running
                return (iperf_status, iperf_server, att_connection, a_host_name)
            else:
                # server wasn't listening, stop and then restart guest shell and try again
                print(f'Restarting guestshell on {a_host_name}, please wait.')
                att_connection.send_command_timing('guestshell disable', delay_factor=2) #force close guestshell
                time.sleep(5)
                att_connection.send_command_timing('guestshell enable', delay_factor=2) # restart guestshell
                time.sleep(5)
                iperf_status = att_connection.send_command_timing('guestshell run sudo iperf3 -s', delay_factor=2) # try again
                if 'Server listening' in iperf_status: # see if it's running and exit function if it isn't
                    print(f'Successfull restart of guestshell on {a_host_name} and iperf successfully started')
                    return (iperf_status, iperf_server, att_connection, a_host_name)
                else:
                    return(f'Error encountered after attempted restart of guestshell on: {iperf_status}',iperf_server, a_host_name)
```
-----------------------Debug log ----------------------
DEBUG:netmiko:write_channel: b'guestshell run sudo iperf3 -s\n'
DEBUG:netmiko:read_channel: guestshell run sudo iperf3 -s # initial run sets variable to null

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'guestshell disable\n' # fails iperf_status check - null
DEBUG:netmiko:read_channel: ^@----------------------------------------------------------- # output from initial run
Server listening on 5201
-----------------------------------------------------------
guestshell disable # script thinks it didn't run

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

# repeat of initial run  where it fails check and thinks it didn't run a second time so it exits script

As you can see, the command did run as expected initially but output was returned after issuing the command to forcefully exit the guestshell because the value of iperf_status is nothing (debug shows iperf_status = '').

I have also tried send_command with expect_string='[expected output]' but since I could get one of three outputs (null, running, unable to run) if it gets anything but what I specify it raises an exception, which is expected I would think.

Is there a way to make the send_command_timing wait just a bit longer aside from delay_factor and/or max_loops to actually capture the output I am looking for? Running manually, the command takes 2-5 seconds to complete so I think a delay of 8 would be sufficient.

What am I missing?

**Comment by ktbyers** [comment]
@Chuck-Thornton So when you run this command:

`guestshell run sudo iperf3 -s`


You mentioned there three cases:
1. null  -- what is the 'null' case can you expand on this?
2. running --  "Server listening" case.
3. unable to run -- what is the output in this case? "Error, guestshell is in disabled state" or something else?

Trying to make sure I understand the various situations.

In the running case i.e. after `Server listening` happens, you just want your function/method to `return` at that point--correct?

**Comment by Chuck-Thornton** [comment]
Thanks for responding.

From the routers perspective it will only return two things:
- -----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------

Or:
iperf3: error - unable to start listener for connections: Address already in use
iperf3: exiting

The null comes from the script. I assigned a variable to the "iperf_status = cl_connection.send_command_timing('guestshell run sudo iperf3 -s',read_timeout=240)" (currently testing options) command so I can look at what it does return to decide what to do next. The script assigns it to null and then runs the guestshell kill command because the iperf_status doesn't say it's running. And on the debug log, after it sends the write_channel there are a few blank lines for read_channel an then it does another write_channel sending the "guestshell disable" command. Immediately after that write_channel the debug log shows a "read_channel" returning the output from it running the iperf command successfully. (see snip from debug log file)

Since it doesn't return a prompt (iperf command) on a successful run I have been using the "send_command_timing" command to give it time to run and return something, usually around 2 - 5 seconds.

It is driving me bonkers since sometimes it works, and then it doesn't. More back story, I am trying to run it on 2 routers as iperf servers based on our circuit providers since our AT&T circuits don't talk to our Lumen circuits and test remote routers to their respective circuit servers. Both routers are the same model, same firmware, configured the same save for required IP address differences.

If you need the full debug log and/or function or full code, let me know.

Thanks again, in spite of this scenario, I do love this module.

**Comment by ktbyers** [comment]
How about:

```python
pattern = r"(?:Server listening|error)"
iperf_status = att_connection.send_command('guestshell run sudo iperf3 -s', expect_string=pattern, read_timeout=10.0)
```

Note, I switched it to `send_command` above which I think is probably better for your use-case.

I also set read_timeout to 10 seconds, this is how long Netmiko will wait (searching for the pattern) before giving up and generating an exception. You can adjust that as needed (depending on how long that commands takes in the various cases).

Let me know if that works or not.

**Comment by Chuck-Thornton** [comment]
Thank you for the response, I will try it and let you know.

**Comment by ktbyers** [comment]
FYI, this is just a regular expression, logical-or:

```
pattern = r"(?:Server listening|error)"
```

The funky `?:` just indicates not to save what it matches from a regular expression pattern perspective (as there is no need to save that in this case).

**Comment by Chuck-Thornton** [comment]
That was the answer. I kinda figured I was missing something somewhere. 

Regular expressions are not my forte.

Thanks again for the assistance
