### ISSUE TITLE
Netmiko and textfsm not working

### ISSUE THREAD

**Issue by pperesbr** [ktbyers/netmiko#2811]
Hi everyone....

I am trying to create a class to get Huawei equipment informations with operating system VRP, I am do not gettting  Netmiko works correctly with textfsm.

My application has a directory called: textfsm, inside this directory two files: index and huawei_vrp_display_ip_vpn_instance_verbose.textfsm.

index file:

```
Template, Hostname, Platform, Command

huawei_vrp_display_ip_vpn_instance_verbose.textfsm, .* , huawei_vrp, dis[[play]] ip vp[[n-instance]] ver[[bose]]
```
huawei_vrp_display_ip_vpn_instance_verbose.textfsm file:

```
Value VPN_NAME (\S+)
Value DESC (.*)
Value RD (\d+:\d+)
Value FAMILY (ipv4|ipv6)
Value List INTERFACES (Eth-Trunk.*|Giga.*)
Value STATUS (UP|DOWN)
Value List RTS_IN (\d+:\d+)
Value List RTS_OUT (\d+:\d+)
Value FRR (Enable|Disable)
Value TUNNEL_POLICY (\S+)
Value IMPORT_RP (\S+)
Value EXPORT_RP (\S+)

Start
  ^\sVPN-Instance Name and ID : ${VPN_NAME},.* -> Record
  ^\s+Description : ${DESC}
  ^\s+${INTERFACES} 
  ^\sAddress family ${FAMILY}
  ^\s+Vrf Status : ${STATUS}
  ^\s+Route Distinguisher : ${RD}  
  ^\s+Export VPN Targets : ${RTS_OUT}
  ^\s+Import VPN Targets : ${RTS_IN}
  ^\s+Import Route Policy : ${IMPORT_RP}
  ^\s+Export Route Policy : ${EXPORT_RP}
  ^\s+VPN FRR ${FRR} 
  ^\s+Tunnel Policy : ${TUNNEL_POLICY} 
```

In my main.py file I am settting NET_TEXTFSM enviroment variable like this:

`os.environ["NET_TEXTFSM"] = "/home/g0004830/dev/python/bln3-shikoku/textfsm"  `

Follow code that sends command to equipment:
```
    def get_vpns(self) -> None:
        command = "display ip vpn-instance verbose"
        output = self.conn.send_command(command, use_textfsm=True)
        pprint(output)
```

Output text comes with no structured data.

I did this test and than works:

```
  def get_vpns(self) -> None:
        command: str = "display ip vpn-instance verbose"
        index_file: str = "index"
        template_dir: str = "/home/g0004830/dev/python/bln3-shikoku/textfsm"

        rawtxt = self.conn.send_command(command)
        cli_table = clitable.CliTable(index_file, template_dir)
        attrs = {'Command': command, 'platform': "huawei_vrp"}

        cli_table.ParseCmd(rawtxt, attrs)
            
        structured_data = clitable_to_dict(cli_table)
        
        pprint(structured_data)
```
        
So, I am do not understanding why netmiko not works with option use_textfsm.

My python version is 3.10.4 and below lib versions.

```
asttokens==2.0.5
backcall==0.2.0
bcrypt==3.2.2
cffi==1.15.0
coloredlogs==15.0.1
cryptography==37.0.2
decorator==5.1.1
executing==0.8.3
flake8==4.0.1
funcy==1.17
future==0.18.2
humanfriendly==10.0
ipython==8.4.0
jedi==0.18.1
matplotlib-inline==0.1.3
mccabe==0.6.1
netmiko==4.1.0
ntc-templates==3.0.0
paramiko==2.11.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
populate==0.0.9
prompt-toolkit==3.0.29
ptyprocess==0.7.0
pure-eval==0.2.2
pycodestyle==2.8.0
pycparser==2.21
pyflakes==2.4.0
Pygments==2.12.0
PyNaCl==1.5.0
pyserial==3.5
PyYAML==6.0
scp==0.14.4
six==1.16.0
stack-data==0.2.0
tabulate==0.8.9
tenacity==8.0.1
textfsm==1.1.2
traitlets==5.2.1.post0
wcwidth==0.2.5
```

Thanks.

**Comment by pperesbr** [comment]
Hi,

I managed to solve it, I changed the platform type in the textfsm file, from huawei_vrrp to huawei, as a netmiko log is supported only huawei or huawei_vrrp8.

I believe that for the case of Huawei in ntc-templates it is also wrong, I tested it with the commands there and it didn't work.

**Comment by ktbyers** [comment]
@pperesbr You might want to bring that up with ntc-templates as we generally share the same device type (alternatively if Netmiko should add another name of `huawei_vrrp` that could be an option). I don't know enough about the Huawei platforms to say what naming makes the most sense.
