### ISSUE TITLE
Windows support for netmiko-tools

### ISSUE THREAD

**Issue by ReK42** [ktbyers/netmiko#2813]
The tools included in the cli_tools folder depend on the external program grep. As far as I can tell, this is the only thing preventing them from working on Windows. I was able to get them working quickly by substituting the [`findstr`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr) utility and removing the lone default grep-specific argument that is passed (see patch below). A more permanent solution would be to generalize the argument code and use Powershell's [`Select-String`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-7.2), or use Python-native code instead of an external dependency.

#### **`netmiko_grep.py.patch`**
```diff
26,28c26,29
< GREP = "/bin/grep"
< if not os.path.exists(GREP):
<     GREP = "/usr/bin/grep"
---
> GREP = "findstr"
> #GREP = "/bin/grep"
> #if not os.path.exists(GREP):
> #    GREP = "/usr/bin/grep"
38,39c39,40
<     if use_colors:
<         grep_options += ["--color=auto"]
---
>     #if use_colors:
>     #    grep_options += ["--color=auto"]
```

**Comment by ktbyers** [comment]
@ReK42 IIRC correctly, I liked the output coloring that `grep` provided automatically on Linux so it a nice solution for *nix-based platforms.

I am fine with a fix for Windows if you want to do a PR on it, we could just detect that it is Windows and then swap the pattern-searching solution (using findstr or whatever the best option was).
