### ISSUE TITLE
Rebooting device throws search pattern exception

### ISSUE THREAD

**Issue by ghmj2417** [ktbyers/netmiko#282]
Before 1.0, rebooting a device, example a Cisco router, by using ssh_conn.send_command() would not throw an exception.  Now when I reboot my device, I receive the following:

Exception: Search pattern never detected in send_command_expect:

With 1.0, how do you want us to tell netmiko to not expect a prompt or output?  Should we use send_command_timing?

**Comment by ktbyers** [comment]
send_command() is now the same as send_command_expect()

Yes, use send_command_timing() now (it is what send_command used to be).


Basically, I changed this as I kept running into too many issues with using a 'timing' based mechanism to execute commands (except in special cases).
