### ISSUE TITLE
Netmiko PaloAlto | OSError: Search pattern never detected

### ISSUE THREAD

**Issue by peejaydeejay** [ktbyers/netmiko#2823]
I'm trying to automate the backup configuration of a palo alto firewall. SCP backup is working fine when entered manually on the firewall's command line. But when I try to use it on my code below, I get the error "OSError: Search pattern never detected in send_command: admin26@PA\-500>"

```python
from netmiko import ConnectHandler
from netmiko import ssh_exception
from netmiko.ssh_exception import NetmikoAuthenticationException, NetmikoTimeoutException
import time
from datetime import date
import os
from paramiko import SSHException
from platformdirs import user_state_dir
from getpass import getpass
import pandas as pd

print('\nPlease enter your device login credentials')
username = input("Enter Username: ")
password = getpass(prompt="Enter Password: ")

DEVICE = {
    'ip':   '172.30.195.111',
    'username': username,
    'password': password,
    'device_type': 'paloalto_panos',
    }

try:
        net_connect = ConnectHandler(**DEVICE)
        print ('[INFO] - Saving current configuration for SBX-PA')
        saveconfig = ['configure','save config to SBX-PA-FW.xml','exit']
        palosave = net_connect.send_config_set(saveconfig)
        print ('[INFO] - Initiating cofiguration backup for SBX-PA')
        output = net_connect.send_command('scp export configuration from SBX-PA-FW.xml to backupadmin@172.30.169.98:/')
        output2 = net_connect.send_command(
            command_string="pass.123",
            expect_string=r"password:",
        )
        net_connect.disconnect
        print(output)
        print(output2)
        print ('[INFO] - Finished configuration backup for SBX-PA')

#Exceptions for authentication failure, device unreachable or unable to SSH
except (NetmikoTimeoutException):
    print('[ERROR] - Device with management IP is not reachable')
except (NetmikoAuthenticationException): #1 failed authentication
    print('[ERROR] - Authentication failed for device with management IP ')   
except (SSHException):
    print ('[ERROR] - Make sure SSH is enabled on device with management IP ')

print ('\n[INFO] - Finished configuration backup for devices on ')
exit=input("\n Press enter to exit") 
```

**Comment by ktbyers** [comment]
@peejaydeejay Can you get rid of the exception handling in your code (the try/except lines) and then post the full exception stack trace into this issue?

**Comment by peejaydeejay** [comment]
@ktbyers update, I found out some mistakes on my code. Specially on the expect_string part. Here's the updated code, with a different error.

```
#!C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe

from netmiko import ConnectHandler
from netmiko import ssh_exception
from netmiko.ssh_exception import NetmikoAuthenticationException, NetmikoTimeoutException
import time
from datetime import date
import os
from paramiko import SSHException
from platformdirs import user_state_dir
from getpass import getpass
import pandas as pd
import logging

logging.basicConfig(filename='pabackuplog2', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
# Input Admin Credentials
print('\nPlease enter your device login credentials')
username = input("Enter Username: ")
password = getpass(prompt="Enter Password: ")

DEVICE = {
    'ip':   '172.30.195.111',
    'username': username,
    'password': password,
    'device_type': 'paloalto_panos',
    }

#try:
net_connect = ConnectHandler(**DEVICE)

print ('[INFO] - Saving current configuration for SBX-PA')
saveconfig = ['configure','save config to SBX-PA-FW.xml','exit']
palosave = net_connect.send_config_set(saveconfig)
print ('[INFO] - Initiating cofiguration backup for SBX-PA')
#backup = net_connect.send_command('tftp export configuration from SBX-PA-FW-06-21-2022.xml to 172.30.169.98')
output = net_connect.send_command("scp export configuration from SBX-PA-FW.xml to backupadmin@172.30.169.98:/",expect_string=r"password")
time.sleep(2)
output2 = net_connect.send_command('pass.123',expect_string=r'.xml')
net_connect.disconnect
print(output)
print(output2)

print ('[INFO] - Finished configuration backup for SBX-PA')

# Exceptions for authentication failure, device unreachable or unable to SSH
#except (NetmikoTimeoutException):
#    print('[ERROR] - Device with management IP is not reachable')
#except (NetmikoAuthenticationException): #1 failed authentication
#    print('[ERROR] - Authentication failed for device with management IP ')   
#except (SSHException):
#    print ('[ERROR] - Make sure SSH is enabled on device with management IP ')

print ('\n[INFO] - Finished configuration backup for devices on ')
exit=input("\n Press enter to exit") 
```

Here are the exception tracebacks

Traceback (most recent call last):
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\netadmin\Documents\BackupCopy-v3\basicpaloalto.py", line 39, in <module>
    output2 = net_connect.send_command('pass.123',expect_string=r'.xml')
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 165, in send_command
    return super().send_command(*args, **kwargs)
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1496, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 655, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
Try setting `cmd_verify=False` on your send_command() calls.

**Comment by peejaydeejay** [comment]
@ktbyers that one worked!

 I have an additional question. Is it possible to put an "OR" boolean on the expect_string command?
 Reason for this is my output may change when the SCP server timed out.

Possible output1:
backupadmin@172.30.169.98's password:
scp: Failed to open file /.
lost connection

Possible output2:
backupadmin@172.30.169.98's password:
SBX-PA-FW.xml                                 100%   13KB  12.8KB/s   00:00

I tried to just remove the expect_string and just create an if-else based on the output.
```
print ('[INFO] - Saving current configuration for SBX-PA')
saveconfig = ['save config to SBX-PA-FW-06-26-2022.xml']
palosave = net_connect.send_config_set(saveconfig)
print ('[INFO] - Initiating cofiguration backup for SBX-PA')
output = net_connect.send_command("scp export configuration from SBX-PA-FW-06-26-2022.xml to backupadmin@172.30.169.98:/",expect_string=r"password",cmd_verify=False)
output2 = net_connect.send_command('pass.123',cmd_verify=False)
net_connect.disconnect
print(output)
print(output2)

if 'Failed' in output2:
    print('[ERROR] - Failed configuration backup for SBX-PA ')
else:
    print ('[SUCCESS] - Finished configuration backup for SBX-PA')

```
With the script above, I'm getting the following errors:

Traceback (most recent call last):
  File "c:\Users\netadmin\Documents\BackupCopy-v3\basicpaloalto.py", line 37, in <module>
    output2 = net_connect.send_command('pass.123',cmd_verify=False)
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 165, in send_command
    return super().send_command(*args, **kwargs)
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "C:\Users\netadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1535, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command: backupadmin@172\.30\.169\.98's\ password:

**Comment by ktbyers** [comment]
@peejaydeejay expect_string is used as a Python regular expression so you can do a logical or there:

```python
my_pattern = (string1|string2)
```

On this second command, you probably would still need to do an `expect_string`:

```python
output2 = net_connect.send_command('pass.123',cmd_verify=False)
```

For example, use `expect_string=r">"` or whatever the trailing prompt character is.

Alternatively, you could just do:

```python
output2 = net_connect.send_command_timing('pass.123',cmd_verify=False)
```

Note, I switched the second command to send_command_timing so it is not looking for any pattern.

**Comment by ktbyers** [comment]
@peejaydeejay expect_string is used as a Python regular expression so you can do a logical or there:

```python
my_pattern = (string1|string2)
```

On this second command, you probably would still need to do an `expect_string`:

```python
output2 = net_connect.send_command('pass.123',cmd_verify=False)
```

For example, use `expect_string=r"#"` or whatever the trailing prompt character is.

**Comment by rahulnangare007** [comment]
I am getting similar error in ConnectHandler part. it is giving me exception before going to send_command section.
