### ISSUE TITLE
Juniper login as root user fails to login properly

### ISSUE THREAD

**Issue by achhabr1** [ktbyers/netmiko#2824]
#Netmiko Version 4.1.0

Trying to login in to Juniper Porter 3 OS

```
Authentication failed.
>>> net_connect = ConnectHandler(
...         device_type="juniper_junos",
...         host="ptr76-jdm",
...         username="root",
...         password="xxxxxxx",
...         ssh_config_file= "~/.ssh/ssh_config_netmiko",
...         conn_timeout = 15
...     )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ac043s/python38-venv/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 344, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/ac043s/python38-venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 434, in __init__
    self._open()
  File "/Users/ac043s/python38-venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 440, in _open
    self._try_session_preparation()
  File "/Users/ac043s/python38-venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 879, in _try_session_preparation
    self.session_preparation()
  File "/Users/ac043s/python38-venv/lib/python3.8/site-packages/netmiko/juniper/juniper.py", line 24, in session_preparation
    self.set_terminal_width(command=cmd, pattern=r"Screen width set to")
  File "/Users/ac043s/python38-venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 1235, in set_terminal_width
    output = self.read_until_pattern(pattern=pattern)
  File "/Users/ac043s/python38-venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'Screen width set to' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.


>>> 
```

Error 

```
root@ga-u410-p3-prt75:~ # 
DEBUG:netmiko:Pattern found: ((?m:[>#] $)) 
root@ga-u410-p3-prt75:~ # 
DEBUG:netmiko:write_channel: b'exit\n'

```

**Comment by achhabr1** [comment]
***@***.***> set cli screen-width 511
Screen width set to 511

***@***.***>


Hope this helps

Thanks
Ankit

**Comment by achhabr1** [comment]
Any update on this one ?

**Comment by ktbyers** [comment]
@achhabr1 What does the Netmiko session_log show?

You can enable the Netmiko session_log by adding the following argument:

```
>>> net_connect = ConnectHandler(
...         device_type="juniper_junos",
...         host="ptr76-jdm",
...         username="root",
...         password="xxxxxxx",
...         ssh_config_file= "~/.ssh/ssh_config_netmiko",
...         conn_timeout = 15,
            session_log="output.txt",
...     )
```

This will create a file named `output.txt`. Can you post what this shows? 

You can obscure anything that is confidential.

**Comment by achhabr1** [comment]
`(python38-venv) ac043s@NJML01AC043S juniper % cat output.txt
Last login: Fri Jul  1 04:48:20 2022 from fd:192:168:53::4
--- JUNOS 21.1X3.2 Kernel 64-bit  JNPR-11.0-20220419.9889e6f_buil
root@ptr76-ucp:~ # 
root@ptr76-ucp:~ # set cli screen-width 511
set: Variable name must contain alphanumeric characters.
root@ptr76-ucp:~ # 
root@ptr76-ucp:~ # %                                                                                                                                                                                                          (python38-venv) ac043s@NJML01AC043S juniper % `

Hope this helps 

set cli screen-width 511 - this should run in operational mode

**Comment by ktbyers** [comment]
@achhabr1 I think this fix here probably fixed this issue:

https://github.com/ktbyers/netmiko/pull/2867/files

Can you re-test this using the Netmiko `develop` branch.

**Comment by tevfikyildiz** [comment]
I have that same problem. But there is something I don't understand. I am able to send commands to another device on the same device model.

---------------------------------------------------------------------------
ReadTimeout                               Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_15724\364941018.py in <module>
    152                 commands_device.append("commit")
    153                 commands_device.append("quit")
--> 154                 vt1 = connection.send_config_set(commands_device,read_timeout=200)
    155                 print(vt1)
    156 

~\Anaconda3\lib\site-packages\netmiko\base_connection.py in send_config_set(self, config_commands, exit_config_mode, read_timeout, delay_factor, max_loops, strip_prompt, strip_command, config_mode_command, cmd_verify, enter_config_mode, error_pattern, terminator, bypass_commands)
   2172                 # Read until next prompt or terminator (#); the .*$ forces read of entire line
   2173                 pattern = f"(?:{re.escape(self.base_prompt)}.*$|{terminator}.*$)"
-> 2174                 output += self.read_until_pattern(pattern=pattern, re_flags=re.M)
   2175 
   2176                 if error_pattern:

~\Anaconda3\lib\site-packages\netmiko\base_connection.py in read_until_pattern(self, pattern, read_timeout, re_flags, max_loops)
    649 
    650 You can also look at the Netmiko session_log or debug log for more information.\n\n"""
--> 651         raise ReadTimeout(msg)
    652 
    653     def read_channel_timing(

ReadTimeout: 

Pattern not detected: '(?:tevfik\\.yildiz@06ostim_yapasw01.*$|#.*$)' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
@tevfikyildiz This looks like a different issue, you should open it separately and provide both your code and the above exception stack.

**Comment by tevfikyildiz** [comment]
> @tevfikyildizBu farklı bir sorun gibi görünüyor, ayrı olarak açmalı ve hem kodunuzu hem de yukarıdaki istisna yığınını sağlamalısınız.



> @tevfikyildiz This looks like a different issue, you should open it separately and provide both your code and the above exception stack.

Thanks for your quick response :) @ktbyers
