### ISSUE TITLE
Palo Alto FW Netmiko 4 - Pattern not detected: '[>#]' in output. 

### ISSUE THREAD

**Issue by sasukebinbin** [ktbyers/netmiko#2828]
Hello,
I am geting an error when connecting to palo alto firewall device:

Pattern not detected: '[>#]' in output.

try:
    net_connect = ConnectHandler(
    device_type = "paloalto_panos",
    host = "x.x.x.x",
    username = auth["staticuser"],
    password = auth["staticpw"],
    )
    output = net_connect.send_command("show clock")

I have no issue with other OS like cisco_ios. 

I believe this is same as this bug. 
https://github.com/ktbyers/netmiko/issues/2739

Please kindly help look into it. Appereciated

**Comment by ktbyers** [comment]
@sasukebinbin Can you post the full exception stack trace that you are receiving?

**Comment by sasukebinbin** [comment]
> @sasukebinbin Can you post the full exception stack trace that you are receiving?
Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
@sasukebinbin I didn't understand your response here?

But anyways I still need the full exception stack trace to be able to provide much assistance here.

**Comment by sasukebinbin** [comment]
> @sasukebinbin I didn't understand your response here?
> 
> But anyways I still need the full exception stack trace to be able to provide much assistance here.

Please close this as issue identified as account problem.
