### ISSUE TITLE
logs get mixed when using `expect_string` inside `send_command()`

### ISSUE THREAD

**Issue by laimaretto** [ktbyers/netmiko#2835]
Hi! I'm trying out the new version of netmiko 4.1.0. I'm upgrading a set of tools that I was using with netmiko 3.4.0. I'm using device type `nokia_sros` with a range of timos versions (7.x, 9.x, 16.x, 21.x).

When using send_command() with show-like commands, I used to store the received outputs both in a json file and a plain text file.

These are a snippet of the commands I'm sending to the router:

```
# SCRIPT_NONO_START
/environment no more
/show router bgp summary
/show router interface
/show service sdp
/show service sdp detail
```
This is how I store the recevied output:
```
try:
    for cmd in cmdList:
        rx        = conn2rtr.send_command(cmd, expect_string=r"#", cmd_verify=True, read_timeout=10)
        outputTxt = outputTxt + '\n' + cmd + '\n' + rx
        outputJson[cmd] = rx
    outputReason = ""
    runStatus    = 1
except Exception as e:
    outputTxt    = ''
    outputReason = str(e)
    runStatus    = -1
```
But here is a problem. If I enable the `expect_string` inside the send_command(), then my ouput both in the json or the text file, gets scrambled. The output on the left corresponds to the case where `exptect_string` is enabled; on the right, I'm not using it. You can see on the left how the sent commands are being repeated, like echoed.

![image](https://user-images.githubusercontent.com/8891825/175794302-557a1f98-02db-48aa-81c2-5f264d9b4d00.png)

This is a snippet of the json file. Look how the values for each key, are mixed.

![image](https://user-images.githubusercontent.com/8891825/175794314-dd9fcf81-fe92-4a98-ab8c-24bdf50e5cb8.png)

I was using the expect_string before, to speed up things, but the output gets corrupted. 

However, everything seems to be allright if I do not use the `expect_string`. 

Any hint?

thanks!

Lucas

**Comment by ktbyers** [comment]
@laimaretto One possible issue I can see is that your very first command:

`# SCRIPT NONO START`

contains a `#` so Netmiko will conclude it is done reading when it encounters that in the output (and this likely starts to mess things up for future commands).

I would start by fixing that and then see what you get for output.

**Comment by laimaretto** [comment]
Mmmm, ok, I see your point. Thing is some times we can use comments in the sent commands with `#`, just like I'm doing. In nokia, many sections of the config files include comments starting with `#`.

On the other hand, this was not an issue with netmiko 3.4.0. With 3.4.0 I would sent this without problems 

But ok, let me try removing the first command and test again ... I'll let you know.

thank you

**Comment by ktbyers** [comment]
Netmiko 3.4.0 had a bug where you might have gotten away with this...

Nonetheless there is a `#` in the output so Netmiko should stop reading once it encounters this character (that is the proper behavior).

**Comment by laimaretto** [comment]
Ok, got you.

Now, before I find a way to remove the command with `#`, I tried to enhance the regex, but its not working. For example:

    conn2rtr.send_command(cmd, expect_string=r"#$", cmd_verify=True, read_timeout=10)

Note the `#$` meaning that only an `#` at the end of the line should be considered. I'm asking, because in nokia, the CLI prompt ends in `#` such as: `A:name>show#`. But this is not working either. If I use `#$` I get the following exception:
```
Pattern not detected: '#$' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```
Is there a specific syntax to be considered with `expect_string` or a regular regex should work? 

But everything goes smooth if I do not set the `expect_string` inside the `send_command()`. But slower ...

Lucas

**Comment by laimaretto** [comment]
Well, yes, I confirm it. I have replaced the initial commando `# START_NONO_SCRIPT` with `echo START_NONO_SCRIPT` and logs are now ok. The `#` in my command was confusing netmiko ...

Note: if I do use as expect_string `#` it does work; if I use `r'#'` it does work; however if I use `r'#$` it does not work and returns the next error.
```
Pattern not detected: '#$' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```
Thanks for the support ...

Lucas

**Comment by laimaretto** [comment]
Yes, that was it ... thank you ...
