### ISSUE TITLE
Netmiko  file transfer not working with source address binding (sock param)

### ISSUE THREAD

**Issue by senthilkumar594** [ktbyers/netmiko#2838]
Netmiko  file transfer not working with source address binding (sock param)

**Example code:-**
from netmiko import ConnectHandler

from netmiko import FileTransfer

import socket

from netmiko import Netmiko

sok = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

sok.bind(("192.168.204.114", 0))

sok.connect(("10.50.10.2", 22))

ssh_conns = Netmiko(

    "10.50.10.2",

    username="admin",

    password="Samsung!1",

    device_type="cisco_ios",

    sock=sok

)

def transfer_file():

        kwargs = dict(

                ssh_conn=ssh_conns,

                source_file="test1.txt",

                dest_file="test1.txt",

                direction="put",

                file_system="/flash/config",

        )

        with FileTransfer(**kwargs) as transfer:

            # Transfer file

            transfer.transfer_file()

transfer_file()

**Comment by ktbyers** [comment]
@senthilkumar594 Secure Copy has never been implemented to work directly with a socket. I would expect that it would probably not work.

Someone would need to implement and test this new feature.
