### ISSUE TITLE
Netmiko not auto accept fingerprint

### ISSUE THREAD

**Issue by rafaelpmagalhaes** [ktbyers/netmiko#2844]
When I try to SSH to a device not previously accessed, the script stops with the question:
The authenticity of host 'x.x.x.x (x.x.x.x)' can't be established.
ECDSA key fingerprint is SHA256:wFPJNevlK4hWQaYGxYBiy+QezX*****************.
Are you sure you want to continue connecting (yes/no/[fingerprint])?

Is it possible to configure an auto accept?

**Comment by ktbyers** [comment]
Can you show more of your code and the full exception stack trace.

By default, Netmiko will auto-accept this...so there must be something else going on.

**Comment by rafaelpmagalhaes** [comment]
device = {
            'device_type': 'linux',
            'host': args.ip,
            'username': 'ubuntu',
            'use_keys': True,
            'key_file': '~/.ssh/involves-ec2-eua.pem',
            }
        try:
            with ConnectHandler(**device) as net_connect:

The authenticity of host '10.10.0.225 (10.10.0.225)' can't be established.
ECDSA key fingerprint is SHA256:tSODkXOCXVG7cUH6ngYp0ZQHFPJj3LLyDIQ21Pbdsd0.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.10.0.225' (ECDSA) to the list of known hosts.
agilepromoter.com.crt                                                                                                                                        100% 5950    17.2KB/s   00:00    
agilepromoter.com.key                                                                                                                                        100% 3247     7.3KB/s   00:00    
The authenticity of host '10.10.0.126 (10.10.0.126)' can't be established.
ECDSA key fingerprint is SHA256:q6ch7BlB7CKB9V74tAkDq4FIueSLYPBmQ68WPH1QvNA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.10.0.126' (ECDSA) to the list of known hosts.
agilepromoter.com.crt                                                                                                                                        100% 5950    17.5KB/s   00:00    
agilepromoter.com.key                                                                                                                                        100% 3247    10.9KB/s   00:00    
The authenticity of host '10.10.0.166 (10.10.0.166)' can't be established.
ECDSA key fingerprint is SHA256:BzyomD7CfeQ8hA2c08JbzlLe/XrfixjW+WZHW0EkUT4.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.10.0.166' (ECDSA) to the list of known hosts.
agilepromoter.com.crt                                                                                                                                        100% 5950    17.5KB/s   00:00    
agilepromoter.com.key                                                                                                                                        100% 3247    10.9KB/s   00:00    
The authenticity of host '10.10.0.213 (10.10.0.213)' can't be established.
ECDSA key fingerprint is SHA256:IsSJ80KJZD4/qU6lyy456bRj9rrvClOwe2qCBVccYUM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.10.0.213' (ECDSA) to the list of known hosts.
agilepromoter.com.crt                                                                                                                                        100% 5950    17.0KB/s   00:00    
agilepromoter.com.key                                                                                                                                        100% 3247    10.8KB/s   00:00    
agilepromoter.com.crt                                                                                                                                        100% 5950    17.3KB/s   00:00

**Comment by ktbyers** [comment]
@rafaelpmagalhaes I need the full exception stack trace (which likely implies that you need to get rid of your try/except statement and the Context Manager).

Also above looks like system SSH and not Paramiko/Netmiko? Can you provide your full Python code (a simplified version that is failing)?

**Comment by rafaelpmagalhaes** [comment]
>>>I need the full exception stack trace (which likely implies that you need to get rid of your try/except statement and the Context Manager).
Where can I see this?

>>>Also above looks like system SSH and not Paramiko/Netmiko? Can you provide your full Python code (a simplified version that is failing)?

import argparse
import os
import boto3
from netmiko import ConnectHandler
from datetime import datetime

def parse_arguments():
    parser = argparse.ArgumentParser(
        description='Please which server do you want install Zabbix Agent. If do you want to install in all servers, type "all" in --ip'
    )
    parser.add_argument("--cert", dest="cert",
                        help="Insert the certificate do you wish to renovate",
                        required=True, type=str)
    parser.add_argument("--ip", dest="ip",
                        help="Insert server IP address or type all for all servers",
                        required=True, type=str)
    args = parser.parse_args()
    
    return args
    
def list_servers():
    args = parse_arguments()
    if args.ip == "all":
        servers = []
        ec2 = boto3.resource('ec2', region_name='us-east-1')
        running_instances = ec2.instances.filter(Filters=[{
            'Name': 'instance-state-name',
            'Values': ['running']
        }])
        for instance in running_instances:
            ip = instance.private_ip_address
            device = {
                'device_type': 'linux',
                'host': ip,
                'username': 'ubuntu',
                'use_keys': True,
                'key_file': '~/.ssh/**********.pem',
                }
            try:
                with ConnectHandler(**device) as net_connect:
                    check_proxy_exists = "sudo docker ps | grep proxy | wc -l"
                    output = net_connect.send_command(check_proxy_exists)
                    if int(output) > 0:
                        servers.append(ip)
            except:
                pass

    return servers

def renov_certs():
    args = parse_arguments()
    if args.ip == "all":
        servers = list_servers()
        for ip in servers:
            os.system(f"scp -q ../certs/{args.cert}.com.* {ip}:/tmp")
        for ip in servers:
            print(f"Conectando no servidor {ip}...")
            device = {
                'device_type': 'linux',
                'host': ip,
                'username': 'ubuntu',
                'use_keys': True,
                'key_file': '~/.ssh/**********.pem',
                }
            try:
                with ConnectHandler(**device) as net_connect:
                    data_e_hora_atuais = datetime.now()
                    data_e_hora_em_texto = data_e_hora_atuais.strftime('%d-%m-%Y')
                    bkp_certs_crt_old = f"sudo mv /data/nginx/certs/{args.cert}.com.crt /data/nginx/certs/{args.cert}.com.crt.{data_e_hora_em_texto}.bkp"
                    bkp_certs_key_old = f"sudo mv /data/nginx/certs/{args.cert}.com.key /data/nginx/certs/{args.cert}.com.key.{data_e_hora_em_texto}.bkp"
                    copy_cert = f"sudo cp /tmp/{args.cert}.com.* /data/nginx/certs/"
                    nginx_reload = "sudo docker exec -ti proxy bash -c '/etc/init.d/nginx reload'"
                    net_connect.send_command(bkp_certs_crt_old)
                    net_connect.send_command(bkp_certs_key_old)
                    net_connect.send_command(copy_cert)
                    net_connect.send_command(nginx_reload)
            except:
                pass
    else:
        os.system(f"scp -q ../certs/{args.cert}.com.* {args.ip}:/tmp")
        device = {
            'device_type': 'linux',
            'host': args.ip,
            'username': 'ubuntu',
            'use_keys': True,
            'key_file': '~/.ssh/**************.pem',
            }
        try:
            with ConnectHandler(**device) as net_connect:
                data_e_hora_atuais = datetime.now()
                data_e_hora_em_texto = data_e_hora_atuais.strftime('%d-%m-%Y')
                bkp_certs_crt_old = f"sudo mv /data/nginx/certs/{args.cert}.com.crt /data/nginx/certs/{args.cert}.com.crt.{data_e_hora_em_texto}.bkp"
                bkp_certs_key_old = f"sudo mv /data/nginx/certs/{args.cert}.com.key /data/nginx/certs/{args.cert}.com.key.{data_e_hora_em_texto}.bkp"
                copy_cert = f"sudo cp /tmp/{args.cert}.com.* /data/nginx/certs/"
                nginx_reload = "sudo docker exec -ti proxy bash -c '/etc/init.d/nginx reload'"
                net_connect.send_command(bkp_certs_crt_old)
                net_connect.send_command(bkp_certs_key_old)
                net_connect.send_command(copy_cert)
                net_connect.send_command(nginx_reload)
        except:
            pass

def main():
    renov_certs()

if __name__ == '__main__':
    main()

**Comment by ktbyers** [comment]
What is this?

```
    else:
        os.system(f"scp -q ../certs/{args.cert}.com.* {args.ip}:/tmp")
```

That is probably what is generating your SSH known host issues.

**Comment by rafaelpmagalhaes** [comment]
You're right! Thanks!
