### ISSUE TITLE
Netmiko Jump Server + TACAC's Error reading SSH protocol banner [WinError 10054]

### ISSUE THREAD

**Issue by joand3512004** [ktbyers/netmiko#2853]
Friends,
I need help with a script, and it should perform 2 actions:
1 - Connect to a gateway machine (Jump Server)
2 - Connect via ssh and execute show's commands to obtain switch outputs.
In this case, the model is Nortel which has the same syntax as Cisco but is not working.
I already increased the sefl.banner_timeout = 60
Authentication timeout = 30 and self.handshake = 15
And I still can't access the devices.
We have tacacs to access the client's environment, but I don't see what to do differently. When there is no tacacs, I access the equipment normally, however, when there is, the connection is through the Jumper, and it gives an error. I've been trying to figure this out for weeks, and I can't. Help me!

**Comment by ktbyers** [comment]
@joand3512004 Did you work this out?

**Comment by ktbyers** [comment]
Can you provide some more details on what issue you are running into (i.e. the full error you are receiving). You probably will also need to post your code corresponding to the error that you are receiving.

**Comment by ktbyers** [comment]
If you are still running into this issue, just re-open this.
