### ISSUE TITLE
revert / rollback a configuration

### ISSUE THREAD

**Issue by omryshay** [ktbyers/netmiko#2857]
hey i am trying to set a config revert on every config commands i send to netmiko. cant manage to find any solution for doing that task.
i want to set a time which if the configuration isnt complete then it will revert to before the configuration

**Comment by ktbyers** [comment]
Not enough information for me to help you with this...

At a high-level, just re-create what you do with the CLI, but using Netmiko.

If you have more specifics on what is failing, let me know.

**Comment by omryshay** [comment]
> Not enough information for me to help you with this...
> 
> At a high-level, just re-create what you do with the CLI, but using Netmiko.
> 
> If you have more specifics on what is failing, let me know.

thank you and sorry for not responding.
i am trying to revert config commands like the command "configure revert {now | timer {minutes | idle minutes}}" to prevent performance interruptions

**Comment by ktbyers** [comment]
@omryshay Okay, yes shouldn't be a problem doing this with Netmiko.

You probably need to post what you have tried and what issue you are running into.

**Comment by omryshay** [comment]
i am using config commands and there isnt any parameters that can handle that. also the prompt for send config and send commands are different.

function send configs sends a list of configs commands

**Comment by ktbyers** [comment]
@omryshay Can you include your Python code and the exception message you are receiving.

You might want to look into napalm and Cisco IOS (I am assuming IOS/IOS-XE here from your posted command above). Rollback and commit confirm capabilities are a part of NAPALM for IOS/IOS-XE.
