### ISSUE TITLE
Multi context ASA

### ISSUE THREAD

**Issue by nvitaly** [ktbyers/netmiko#286]
I probably doing something wrong. It used to be working (couple month ago):

I connect to device with 'device_type': 'cisco_asa',
do send_command("sh ver")
getting what expected
do send_command("changeto context dev")

And here it stuck, i debugged a bit and found that it stuck in loop in BaseConnection
in send_command waiting for prompt that changed because we changed context.

**Comment by ktbyers** [comment]
I would try to do the 'changeto' command using send_command_timing:

```
send_command_timing("changeto context dev")
...
```

This is a timing based method and should update the prompt after changeto is done.

Let me know if this works.

**Comment by ktbyers** [comment]
Related to this I think there is a bug in the ASA Netmiko code where send_command() with changeto action won't work.

**Comment by nvitaly** [comment]
Excellent, thank you! send_command_timing works.

I could probably use send_command with crafted expect_string for new prompt, but _timing works great for me.

**Comment by ktbyers** [comment]
I think this issue is fixed here:

https://github.com/ktbyers/netmiko/commit/ebde3fd486e00bf8b11e0c95bba64177a796d4a5
