### ISSUE TITLE
Redispatch failing due to no data being present

### ISSUE THREAD

**Issue by assadniang** [ktbyers/netmiko#2861]
Hello,

This used to work before I upgrade from version 3.4.0 to version 4.1.1

Not sure why it is failing on the juniper device:

````
#Use the redispatch method (to switch the Netmiko class to a Juniper)
    redispatch(net_connect, device_type='juniper_junos')
    
    net_connect.send_command('cli', expect_string=r'>')
    
    output = net_connect.send_command('show configuration | display set')
    
    if f'vcsr-{domain}' in output:
        print(f'Found vcsr-{domain}')
        print(f'>>> Deleting vcsr-{domain} instance')
        net_connect.send_config_set(f'delete virtual-machines instance vcsr-{domain}',\
             exit_config_mode = False)
        output = net_connect.commit(and_quit=True)
        
        if 'commit complete' in output:
            print(output)
            print(Fore.LIGHTGREEN_EX + 'Success!')
        else:
            print(Fore.RED + f'Could not delete vcsr-{domain} instance')
            net_connect.disconnect()
            quit()
    else:
        print(f'No vcsr-{domain} instance running')
    
    net_connect.send_command('exit', expect_string=r'#')
````

**Output:**

> >>> Checking if any vnf are running: vcsr-a
> Traceback (most recent call last):
>   File "./CSR1000V_License_Stage.py", line 1467, in <module>
>     check_vnf_running()
>   File "./CSR1000V_License_Stage.py", line 275, in check_vnf_running
>     redispatch(net_connect, device_type='juniper_junos')
>   File "/usr/local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 449, in redispatch
>     obj._try_session_preparation()
>   File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 879, in _try_session_preparation
>     self.session_preparation()
>   File "/usr/local/lib/python3.8/site-packages/netmiko/juniper/juniper.py", line 20, in session_preparation
>     self._test_channel_read(pattern=pattern)
>   File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1119, in _test_channel_read
>     return self.read_until_pattern(pattern=pattern, read_timeout=20)
>   File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 651, in read_until_pattern
>     raise ReadTimeout(msg)
> netmiko.exceptions.ReadTimeout: 
> 
> Pattern not detected: '[%>$#]' in output.
> 
> Things you might try to fix this:
> 1. Adjust the regex pattern to better identify the terminating string. Note, in
> many situations the pattern is automatically based on the network device's prompt.
> 2. Increase the read_timeout to a larger value.
> 
> You can also look at the Netmiko session_log or debug log for more information.

**Log file shows this:**

> DEBUG:netmiko:read_channel: root@ptr53-jdm:~# 
> DEBUG:netmiko:Pattern found: ([\$\#]) Last login: Tue Jul 19 00:36:24 2022 from fd:192:168:53::250
> root@ptr53-jdm:~#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:Clear buffer detects data in the channel
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> root@ptr53-jdm:~# 
> DEBUG:netmiko:Pattern found: ([\$\#]) 
> root@ptr53-jdm:~#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:Clear buffer detects data in the channel
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:[find_prompt()]: prompt is root@ptr53-jdm:~#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: b'\n'
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> root@ptr53-jdm:~# 
> DEBUG:netmiko:Pattern found: ([\$\#]) 
> root@ptr53-jdm:~#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:Clear buffer detects data in the channel
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:[find_prompt()]: prompt is root@ptr53-jdm:~#
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> ...
> .....
> .......
> ..........

I also tried commenting this line, but same issue:
`#net_connect.send_command('cli', expect_string=r'>')`

**Comment by ktbyers** [comment]
Your error and the log file don't really match up?

The exception says it tried to read and was looking for '[%>$#]'  but never found it, but then the log has `#` in the output (and doesn't really match the exception stack trace)?

Maybe add a log entry that you generate in your code before and after the `redispatch` call so we can make sure we are looking at the right location in the log file?

**Comment by assadniang** [comment]
Hi,
It does does not login to the CSR1000V directly, but to the Juniper device first, where the CSR1000V is running as a vnf:

This is the code where it connects to the device:

````
############# MTLAB-AUTO SSH Parameters
ssh_juniper_ucpe = {
    'device_type': 'linux',
    'host': target_host,
    'username': 'root',
    'password': 'juniper123',
}


def ssh_connect_ucpe():

    global net_connect

    # SSH Connection to first Device
    print()
    print(f'{Fore.LIGHTYELLOW_EX}>>> Connecting to uCPE: {target_host}')
    net_connect = ConnectHandler(**ssh_juniper_ucpe)

    #####################################################################
    # Make sure SSH connection is working at this point
    output = (net_connect.find_prompt())

    # Verify you logged in successfully
    if f'{target_host}' in output:
        print(output)
        print(Fore.LIGHTGREEN_EX + 'Successfully connected to uCPE')
    else:
        print(Fore.RED + 'Failed to connect to uCPE')
        print(output)
        quit()
    
def check_vnf_running():
    print()
    print(Fore.LIGHTYELLOW_EX + f'>>> Checking if any vnf are running: {Fore.RESET}vcsr-{domain}')

    #Use the redispatch method (to switch the Netmiko class to a Juniper)
    redispatch(net_connect, device_type='juniper_junos')
    
    net_connect.send_command('cli', expect_string=r'>')
    
    output = net_connect.send_command('show configuration | display set')
    
    if f'vcsr-{domain}' in output:
        print(f'Found vcsr-{domain}')
        print(f'>>> Deleting vcsr-{domain} instance')
        net_connect.send_config_set(f'delete virtual-machines instance vcsr-{domain}',\
             exit_config_mode = False)
        output = net_connect.commit(and_quit=True)
        
        if 'commit complete' in output:
            print(output)
            print(Fore.LIGHTGREEN_EX + 'Success!')
        else:
            print(Fore.RED + f'Could not delete vcsr-{domain} instance')
            net_connect.disconnect()
            quit()
    else:
        print(f'No vcsr-{domain} instance running')



############################# Start Main ##############################     

ssh_connect_ucpe()
check_vnf_running()
create_xml()
````


Output:
```

********************************
*** CSR1000V License Staging ***
*** AT&T NJ - Middletown Lab ***
********************************
Date: Tuesday 19 July 2022
Start time: 15:07

*** CSR1000V Parameters ***
>> Host: ptr53
>> Domain: vcsr-a
>> Speed: 1G
>> Feature: app
>> Version: 16.9.6
>> Serial Number: TBD
>> License Term: 1Y
>> UUID: 37435E1D-AAC9-4F86-9D22-62DDB9E27AE6
>> Licensed: True
>> Procure: False
>> SKU: L-CSR-1G-APP-1Y

>>> Connecting to uCPE: ptr53-jdm
root@ptr53-jdm:~#
Successfully connected to uCPE

>>> Checking if any vnf are running: vcsr-a
Traceback (most recent call last):
  File "./CSR1000V_License_Stage.py", line 1467, in <module>
    check_vnf_running()
  File "./CSR1000V_License_Stage.py", line 275, in check_vnf_running
    redispatch(net_connect, device_type='juniper_junos')
  File "/usr/local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 449, in redispatch
    obj._try_session_preparation()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 879, in _try_session_preparation
    self.session_preparation()
  File "/usr/local/lib/python3.8/site-packages/netmiko/juniper/juniper.py", line 20, in session_preparation
    self._test_channel_read(pattern=pattern)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1119, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '[%>$#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

```

[an144a@mtlab-auto uCPE]$

**Comment by assadniang** [comment]
I had to downgrade to 3.4.0, as the same code was working great.
The issue started after I upgraded:

The pattern is found, but netmiko fails to send any commands.

DEBUG:netmiko:Pattern found: (cli) cli
DEBUG:netmiko:read_channel: {master:0}
**root@ptr53-jdm>** 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
..
...
....
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

{master:0}
root@ptr53-jdm> 
**DEBUG:netmiko:Pattern found: ((?m:[>#] $))** 

{master:0}
root@ptr53-jdm> 
DEBUG:netmiko:write_channel: b'exit\n'
DEBUG:paramiko.transport:EOF in transport thread

**Comment by utkuozsan** [comment]
I had the same issue. Based on the log file, there shouldn't be a problem but I can't run any commands.
Script:
---
from netmiko import ConnectHandler
from netmiko import redispatch
import time
import logging
import sys 
logging.basicConfig(filename = 'test.log', level = logging.DEBUG)
logger = logging.getLogger("netmiko")


device = {
    'device_type':'terminal_server',
    'ip':'X.X.X.X',
    'username': 'username',
    'password':'password',
    'port': 22,
    "delay_factor_compat": True,
    "fast_cli": False,
    
    }

net_connect = ConnectHandler(**device)
print (f"Jump Server Prompt:{net_connect.find_prompt()}")
print("\n\n")
time.sleep(2)

net_connect.write_channel("ssh username@1.2.3.4\n")
time.sleep(5)

output = net_connect.write_channel('password\n')
time.sleep(5)


print(f"Router Prompt: {net_connect.find_prompt()}")

redispatch(net_connect, device_type = 'cisco_xr')

new_output = net_connect.send_command("show bgp summary")

print(new_output)
---

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

RP/0/RSP1/CPU0:Node_XXX#
DEBUG:netmiko:Pattern found: ([#\$]) 

RP/0/RSP1/CPU0:node_XXX#
DEBUG:netmiko:write_channel: b'exit\n'
DEBUG:paramiko.transport:EOF in transport thread

**Comment by ktbyers** [comment]
@utkuozsan Can you post your full exception stack trace?

**Comment by ktbyers** [comment]
@utkuozsan @assadniang Can you try this fix here and let me know if it works:

https://github.com/ktbyers/netmiko/pull/2867

**Comment by assadniang** [comment]
``> @utkuozsan @assadniang Can you try this fix here and let me know if it works:
> 
> #2867

Hi Kirk,

That did not fix it...
I don't know how to do update the package with the fix, so I just downloaded the new file base_connection.py, and replace it under /nemiko/base_connection.py on my server

I have attached the log

**output:**
```
>>> Connecting to uCPE: ptr53-jdm
root@ptr53-jdm:~#
Successfully connected to uCPE

>>> Checking if any vnf are running: vcsr-a
Traceback (most recent call last):
  File "./CSR1000V_License_Stage.py", line 1470, in <module>
    check_vnf_running()
  File "./CSR1000V_License_Stage.py", line 277, in check_vnf_running
    redispatch(net_connect, device_type='juniper_junos')
  File "/usr/local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 449, in redispatch
    obj._try_session_preparation()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 817, in _try_session_preparation
    self.session_preparation()
  File "/usr/local/lib/python3.8/site-packages/netmiko/juniper/juniper.py", line 24, in session_preparation
    self.set_terminal_width(command=cmd, pattern=r"Screen width set to")
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1151, in set_terminal_width
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 599, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'Screen width set to' in output.
Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.
You can also look at the Netmiko session_log or debug log for more information.


[an144a@mtlab-auto uCPE]$ cd logs/
```

**Code:**

```
############# MTLAB-AUTO SSH Parameters
ssh_juniper_ucpe = {
    'device_type': 'linux',
    'host': target_host,
    'username': 'root',
    'password': 'juniper123',
}

############## SSH into MTLAB-AUTO and ptr53
def ssh_connect_ucpe():

    global net_connect

    # SSH Connection to first Device
    print()
    print(f'{Fore.LIGHTYELLOW_EX}>>> Connecting to uCPE: {target_host}')
    net_connect = ConnectHandler(**ssh_juniper_ucpe)

    #####################################################################
    # Make sure SSH connection is working at this point
    output = (net_connect.find_prompt())

    # Verify you logged in successfully
    if f'{target_host}' in output:
        print(output)
        print(Fore.LIGHTGREEN_EX + 'Successfully connected to uCPE')
    else:
        print(Fore.RED + 'Failed to connect to uCPE')
        print(output)
        quit()
    
def check_vnf_running():
    print()
    print(Fore.LIGHTYELLOW_EX + f'>>> Checking if any vnf are running: {Fore.RESET}vcsr-{domain}')

    #Use the redispatch method (to switch the Netmiko class to a Juniper)
    redispatch(net_connect, device_type='juniper_junos')
    
    net_connect.send_command('cli', expect_string=r'>')    
    
    output = net_connect.send_command('show configuration | display set | match vcsr')
    print(output)

    if f'vcsr-{domain}' in output:
        print(f'Found vcsr-{domain}')
        print(f'>>> Deleting vcsr-{domain} instance')
        net_connect.send_config_set(f'delete virtual-machines instance vcsr-{domain}',\
             exit_config_mode = False)
        output = net_connect.commit(and_quit=True)
        
        if 'commit complete' in output:
            print(output)
            print(Fore.LIGHTGREEN_EX + 'Success!')
        else:
            print(Fore.RED + f'Could not delete vcsr-{domain} instance')
            net_connect.disconnect()
            quit()
    else:
        print(f'No vcsr-{domain} instance running')
    
    net_connect.send_command('exit', expect_string=r'#')
    
    print()
    print(f'>>> Deleting QCOW2 files in /images_{domain} folder')
```
[csr1000v_staging_100m_app_0022-07272022_debug_test.log](https://github.com/ktbyers/netmiko/files/9195047/csr1000v_staging_100m_app_0022-07272022_debug_test.log)

**Comment by ktbyers** [comment]
@assadniang Okay, I made a second change to that pull-request. You will need to get both of these changes.

https://github.com/ktbyers/netmiko/pull/2867

Also, you need to change your code (as what you are doing is not really correct...if I am reading it properly. Yes, I understand you got away with it in 3.4.x.

```python
ssh_juniper_ucpe = {
    'device_type': 'juniper_junos',         # This should be juniper_junos and not linux
    'host': target_host,
    'username': 'root',
    'password': 'juniper123',
}
```

These two lines should be removed or commented out:

```python
    #Use the redispatch method (to switch the Netmiko class to a Juniper)
    # redispatch(net_connect, device_type='juniper_junos')
    
    # net_connect.send_command('cli', expect_string=r'>')
```

Netmiko will automatically detect you are logged into the Unix shell and automatically execute "cli" to switch you over to the shell.

Let me know if that works.

**Comment by assadniang** [comment]
@ktbyers 

Finally got it working....

Thank you!!!

The reason I had it set to linux initially, is I wanted to run some linux command at the shell when I am doing junos config changes 

**Output:**

```
>>> Connecting to uCPE: ptr53-jdm
root@ptr53-jdm>
Successfully connected to uCPE

>>> Checking if any vnf are running: vcsr-a
set virtual-machines instance vcsr-a descriptor-file-name /var/third-party/vcsr_a.xml

Found vcsr-a
>>> Deleting vcsr-a instance
commit and-quit 
commit complete
Exiting configuration mode

{master:0}
root@ptr53-jdm> 
Success!


>>> Deleting QCOW2 files in /images_a folder
cd /var/third-party/images_a
root@ptr53-jdm:/var/third-party/images_a# rm csr1000v*
root@ptr53-jdm:/var/third-party/images_a# 

>>> Creating xml file: vcsr_a.xml
Verifying vcsr_a.xml file is created
Success!
root@ptr53-jdm:/var/third-party# 
Successfully created vcsr_a.xml
```


**Code:**

```
############# MTLAB-AUTO SSH Parameters
ssh_juniper_ucpe = {
    'device_type': 'juniper_junos',
    'host': target_host,
    'username': 'root',
    'password': 'juniper123',
}

#Use the redispatch method (to switch the Netmiko class to a Juniper)
    #redispatch(net_connect, device_type='juniper_junos')
    
    #net_connect.send_command('cli', expect_string=r'>')    
    
    output = net_connect.send_command('show configuration | display set | match vcsr')
    print(output)

    if f'vcsr-{domain}' in output:
        print(f'Found vcsr-{domain}')
        print(f'>>> Deleting vcsr-{domain} instance')
        net_connect.send_config_set(f'delete virtual-machines instance vcsr-{domain}',\
             exit_config_mode = False)
        output = net_connect.commit(and_quit=True)
        
        if 'commit complete' in output:
            print(output)
            print(Fore.LIGHTGREEN_EX + 'Success!')
        else:
            print(Fore.RED + f'Could not delete vcsr-{domain} instance')
            net_connect.disconnect()
            quit()
    else:
        print(f'No vcsr-{domain} instance running')
```

**Comment by ktbyers** [comment]
@assadniang Yes, you can still drop to `Unix Shell`, but if you want to do that still use `juniper_junos` driver and drop into the shell from Junos (otherwise you will run into issues with the Netmiko Juniper driver).

**Comment by ktbyers** [comment]
@assadniang Okay, I merged that pull-request into the Netmiko `develop` branch.
