### ISSUE TITLE
`send_config_set` no longer works with generators

### ISSUE THREAD

**Issue by cbay** [ktbyers/netmiko#2874]
Starting with bc8fc448bb76a57cb18f61c663c4d7aeb8c037ef, `send_config_set` no longer works when `config_commands` is a generator as `bypass_commands` (which is automatically set by default) will consume the generator, and the rest of the method will have an "empty" `config_commands`.

That breaks [Napalm](https://github.com/napalm-automation/napalm/blob/develop/napalm/nxos_ssh/nxos_ssh.py#L473), for instance.

**Comment by ktbyers** [comment]
I am not understanding your reasoning here? How would bypass_commands affect this?

But I will test it.

**Comment by ktbyers** [comment]
Nevermind...I see more what you were referring to. Let me look into it some more.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/2890
