### ISSUE TITLE
Restoring Configuration file

### ISSUE THREAD

**Issue by Anirudh-Suri** [ktbyers/netmiko#2877]
Input- my own changed config file for switch to restore a device.

Hello,
I want to store a changed config file into flash so that every time system boots up, my input config file will be restored.

I am using netmiko. But not able to find the command to copy the file from my editor into switch in flash as config-file.

**Comment by ktbyers** [comment]
Is this the same issue as #2879?

**Comment by Anirudh-Suri** [comment]
> Is this the same issue as #2879?

Yes.
