### ISSUE TITLE
Restoring the Config file on Network Devices using Python

### ISSUE THREAD

**Issue by Anirudh-Suri** [ktbyers/netmiko#2879]
I have a config file in my code editor. I did for loop on that with  .readline() e.g for items in my_config_file .readlines() and when I print the items, I am getting the desired output. But now I want to replace this config file in the flash e.g in the switch. So, that each time when I boot up my system, I have my config file in the flash.

Even I am using "copy my_config_file flash:/config.text"
and trying to send the output through .send_command(). Some errors so I used the global_delay_time with expect_string :( But ya, it was very complex to do the pattern matching thing.

I even tried the .send_config_from_file("----") instead of .send_command()
But it is not helping me either.

Do you have some better way to solve this problem? Or the command to do this task.

Thanks.

**Comment by Anirudh-Suri** [comment]
Hello 
Cisco Switch  and Debian is the OS.

I think I am using the command copy my-file name startup-config for restoring the file. But since that file is not in the Cisco switch or in flash. So I am using file_transfer from netmiko to transfer the file so that my command will be able to copy that file as startup- config. But in file_transfer errors are coming like check_my_file is not found

**Comment by ktbyers** [comment]
Can you clarify what you are trying to do?

You have a configuration file in your Python code that you want to get to the device's flash or something else?

**Comment by Anirudh-Suri** [comment]
> Can you clarify what you are trying to do?
> 
> You have a configuration file in your Python code that you want to get to the device's flash or something else?

Yes right. This is what I am doing. A config file which I want to put in flash to make the file as start-up config

**Comment by ktbyers** [comment]
The general process would be:

1. Using Python save your configuration to the unix file-system.
2. Make sure your configuration is proper and can be loaded.
3. Use the Netmiko file_transfer to transfer the config into flash
4. Send the command to copy the file from flash into the startup config using Netmiko.

**Comment by Anirudh-Suri** [comment]
Okay. Thanks a lot for this answer. I will try that.

But I also find another way to do that. Instead of using file_transfer netmiko. Now, I am using tftp. 

But soon, I will try the other way too.

Thanks:)
