### ISSUE TITLE
strange prompt (not matched) in 'terminal_server'

### ISSUE THREAD

**Issue by adampav** [ktbyers/netmiko#2882]
Hi Kirk,

First things first, huge fan of all the work you and like-minded people are doing! 

I was wondering if I could pick your brain about something.
Trying to experiment with the "terminal_server" device type in order to create some initial provisioning scripts, or on-board devices that need some 1-2 basic commands before i can incorporate them to the automation tools.

What i am doing is something like this:

Linux box 
  -> SG300 (device_type=terminal_server)
    -> write_channel('\r')
      -> redispatch(net_connect, device_type='cisco_ios')
  	-> cisco_command 
  
The strange thing is that if send a command, e.g. 'show clock'. I get a ReadTimeout exception and i notice that the prompt seems a bit weird.

if the switch is "foo#", the find_prompt() -> to a file is ^]]Kfoo#.

So i get something like this.

netmiko.exceptions.ReadTimeout: 
Pattern not detected: '\x1b\\[foo\\#' in output.

This does not happen if i select 'cisco_ios' from the start, without redispatch-ing.

code snippet

```python 
   cisco1 = {
        "device_type": h[1],
        "host": h[0],
        "username": crd[0],
        "password": crd[1],
        "secret": crd[2]
    }

    cisco1.update(
        {
            'device_type': 'terminal_server'
        }
    )

    nc = ConnectHandler(**cisco1)

    nc.write_channel('\r')
    time.sleep(1)

    prompt = nc.find_prompt()
    with open('prompt1.txt', 'w') as f:
        f.write(prompt)

    redispatch(nc, device_type='cisco_ios')

    outp = nc.send_command('show clock')
    # this is stuck into read-channel and throws the error. 
```

I understood from reading similar issues that the way to go when you want to manipulate the initial connection, was to use the "terminal_server" device type as interrim and then redispatch to the appropriate device.

I could use the cisco_ios from the start but i was wondering what is the issue since i want to use it for other purposes (e.g. provisioning etc)

Thanks in advance,
Adam

**Comment by adampav** [comment]
Follow up:
Though i have been tinkering at it for the entire day, and using the correct device_type='cisco_s300' for other purposes, i put on my blinders here...

It just hit me after i logged out

leaving the comment  editing the issue so as to potentially help others.

```python
redispatch(nc, device_type='cisco_s300')
``` 
the above worked without issue, however i noticed the prompt change prior and after redispatch.
Just out of curiosity for the 'under the hood magic'?

If i understand correctly the special characters are expected in 'cisco_ios' and 'terminal_server' but not on the s300 prompt ?

Thanks again!

**Comment by ktbyers** [comment]
The Cisco S300 has ANSI escape codes in the output, this is what is here:

Pattern not detected: '\x1b\[foo\#' in output.

The `\x1b` is part of an ANSI escape code. This does special things like coloring your terminal.

Netmiko auto-strips these ANSI escape codes automatically for the S300

(https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_s300.py#L16)

I am probably going to change Netmiko to always enable this regardless of platform, but I haven't done that yet.

**Comment by adampav** [comment]
Thank you very much for the info. Will keep this in mind.
