### ISSUE TITLE
Cisco ASA failing on send_command as allow_auto_change is disabled

### ISSUE THREAD

**Issue by jj-jj-j** [ktbyers/netmiko#2886]
Hi team,

Getting below error for running show command in ASA, please provide solution for it, i tried all the solutions available online.
2022-08-05 20:28:28PM : ERROR - Search pattern never detected in send_command: test\-lab/pri/act\#

code
```python
asa_list = [f"2.2.2.2", f"1.1.1.1"]
#Existing object group output 
csg_ftp_exis_grp=[]
den_ftp_exis_grp=[]

try:
    #connect to ASA and take the existing object group input
    for asa_ip in asa_list:
        firewall_list = {
                'device_type': 'cisco_asa',
                'ip': asa_ip,
                'username': username,
                'password': password,
                'secret': password,
                'fast_cli': False,
                'allow_auto_change' : False


            }
        # Establish connection to ASA
        net_connect = ConnectHandler(**firewall_list)
        #check for existing object group configuration
        csg_ftp_exis_grp.append(net_connect.send_command(f"show object-group id test-ftp1_customers_sftp",cmd_verify=False).split("\n"))
        den_ftp_exis_grp.append(net_connect.send_command(f"show object-group id test1-ftp1_customers_sftp",cmd_verify=False).split("\n"))




except Exception as occured_exception:
    retcode = 1
    CSGLogger.error(occured_exception)
  

#Exit with global return code
exit(retcode) 
```

**Comment by ktbyers** [comment]
Can you eliminate the exception handling (try/except statement) and post the full exception stack trace?

Note, this argument:

```
                'allow_auto_change' : False
```

is generally required for the ASA to work properly so I would change that to True (or else, you will need to manually do the things Netmiko does automatically i.e. set the terminal width: "terminal width 511").

**Comment by jj-jj-j** [comment]
hi @ktbyers , Thank you , actually it will accidently make changes on standby unit, I dont want to do that, so I used "send_command_timing", I saw one issue you mentioned it wont expect any pattern, that fixed my issues, thank you so much for the response.
