### ISSUE TITLE
Netmiko should generate an exception if you specify a key-file and it doesn't exist

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#2887]

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/2892

**Comment by markonen** [comment]
@ktbyers Hi! I fully realize that this particular ship sailed three months ago... however, specifying `use_keys=True` without a `key_file` worked great before this change as it fell back to finding a key from my `.ssh` folder on its own.

Explicitly specifying the key file is a bit awkward in a multi-user setting; I think I have to add a config facility for this where previously it just did the right thing automatically.

Am I missing something?
