### ISSUE TITLE
send_command_timing requires last_read argument for slow show commands

### ISSUE THREAD

**Issue by Typovy** [ktbyers/netmiko#2888]
Hey,
im using send_command_timing() to collect data from devices. In this example command was 'show run' in cisco_ios device.
Code below:
`for command in commands:
                    output = connection.send_command_timing(command)`
Then i save output in .txt file. Output looks like this:
`Building configuration..`
And there is no more than this. I tried with adding 'term len 0' befor 'sh run' and nothing changed. When i will add additional command after 'sh run' command it works as it supposed to.
Any ideas? Should i use other "send_command" function?

**Comment by ktbyers** [comment]
Try adjusting the `last_read` argument to send_command_timing.

Try:

```python
for command in commands: 
    output = connection.send_command_timing(command, last_read=8)
    ...
```

The cause of your issue is likely that the device is responding too slowly.

Another alternative is to switch to `send_command`.
