### ISSUE TITLE
timing issue with find_prompt on Palo Alto - netmiko 1.0.0

### ISSUE THREAD

**Issue by mcfone** [ktbyers/netmiko#289]
_[**Summary**: in netmiko v1.0.0 need to set delay_factor in paloalto_panos_ssh.py to 7 from the current value of 3 to get it to work with Palo Altos as it did with netmiko v0.5.6]_

All was fine connecting to my Palo Alto 5060 with 0.5.6, but with 1.0.0 I get:

```
Traceback (most recent call last):
  File "/home/fav/get_arp_tables.py", line 241, in <module>
    net_connect = ConnectHandler(**dev)
  File "/home/fav/anaconda3/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 94, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/fav/anaconda3/lib/python3.5/site-packages/netmiko/base_connection.py", line 89, in __init__
    self.session_preparation()
  File "/home/fav/anaconda3/lib/python3.5/site-packages/netmiko/paloalto/paloalto_panos_ssh.py", line 21, in session_preparation
    self.set_base_prompt(delay_factor=3)
  File "/home/fav/anaconda3/lib/python3.5/site-packages/netmiko/base_connection.py", line 478, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: Welcome root.
```

The Palo Alto returns the following on login:

```
Last login: Thu Oct  6 11:58:08 2016 from x.y.z
Welcome root.

root@fw(active)> 
```

Turning on debugging in find_prompt() in base_connection.py (extra debugging prompt4 and "end of prompt" added by me - prompt4 is the result after processing multi-line response) I get:

```
prompt1: 
^^^^^ end of prompt1 ^^^^^
prompt2a: 'Welcome root.'
^^^^^ end of prompt2a ^^^^^
prompt2b: Welcome root.
^^^^^ end of prompt2b ^^^^^
prompt3: Welcome root.
^^^^^ end of prompt3 ^^^^^
prompt4: Welcome root. 
^^^^^ end of prompt4 ^^^^^
Traceback (most recent call last):
  File "test_netmiko.py", line 7, in <module>
    net_connect = ConnectHandler(**dev)
  File "/home/fav/anaconda3/lib/python3.5/site-packages/netmiko/ssh_dispatcher.py", line 94, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/fav/anaconda3/lib/python3.5/site-packages/netmiko/base_connection.py", line 89, in __init__
    self.session_preparation()
  File "/home/fav/anaconda3/lib/python3.5/site-packages/netmiko/paloalto/paloalto_panos_ssh.py", line 23, in session_preparation
    self.set_base_prompt(delay_factor=3)
  File "/home/fav/anaconda3/lib/python3.5/site-packages/netmiko/base_connection.py", line 478, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: Welcome root.
```

So despite sending a newline in find_prompt(), it doesn't get past seeing "Welcome root" as the response.

If I change the value of delay_factor in paloalto_panos_ssh.py from 3 to 4 it works, but only by sending multiple newlines in find_prompt:

```
prompt1: 
^^^^^ end of prompt1 ^^^^^
prompt2a: 'Welcome root.\r\n\r\nroot@fw(active)> \r\nroot@fw(active)> \r\nroot@fw(active)>'
^^^^^ end of prompt2a ^^^^^
prompt2b: Welcome root.

root@fw(active)> 
root@fw(active)> 
root@fw(active)>
^^^^^ end of prompt2b ^^^^^
prompt3: Welcome root.

root@fw(active)> 
root@fw(active)> 
root@fw(active)>
^^^^^ end of prompt3 ^^^^^
prompt4: root@fw(active)>
^^^^^ end of prompt4 ^^^^^
```

If I increase delay_factor to 7, then it works as expected (and as similar debugging shows it does with netmiko v0.5.6), getting all of the initial prompt lines without having to send more than one newline in find_prompt():

```
prompt1: Welcome root.

root@fw(active)> 
root@fw(active)>
^^^^^ end of prompt1 ^^^^^
prompt3: Welcome root.

root@fw(active)> 
root@fw(active)>
^^^^^ end of prompt3 ^^^^^
prompt4: root@fw(active)>
^^^^^ end of prompt4 ^^^^^
```

Hope this helps, and many thanks for the module,

Mark

**Comment by ktbyers** [comment]
@mcfone @GGabriele 

I assume that you are modifying the delay_factor here?

```
    def session_preparation(self):
        """
        Prepare the session after the connection has been established.

        Disable paging (the '--more--' prompts).
        Set the base prompt for interaction ('>').
        """
        self.set_base_prompt(delay_factor=3)
```

**Comment by mcfone** [comment]
Yes, that's correct.

**Comment by mcfone** [comment]
The other curious thing I've just noticed is that v1.0.0 seems to double up with prompt lines. If, after establishing a connection to the Palo Alto via:

`net_connect = ConnectHandler(**dev)`

I then call

`prompt = net_connect.find_prompt()`

with debugging turned on in find_prompt() in base_connection.py, I get (with the initial connection find_prompt() debug output removed, leaving just the net_connect.find_prompt() debug output):

```
prompt1: root@fw(active)> 
root@fw(active)>
^^^^^ end of prompt1 ^^^^^
prompt3: root@fw(active)> 
root@fw(active)>
^^^^^ end of prompt3 ^^^^^
prompt4: root@fw(active)>
^^^^^ end of prompt4 ^^^^^
```

so the prompt processed by find_prompt() is initially two lines. With v0.5.6, the prompt is initially just a single line:

```
prompt1: root@fw(active)>
prompt3: root@fw(active)>
prompt4: root@fw(active)>
```

Maybe not a problem, but it is a different behaviour.

**Comment by mcfone** [comment]
My script logins in to the Palo Alto once every 10 minutes; even with increasing the delay_factor from 3 to 7, it still fails to get the prompt every now and again (1-2 times per day). I've now increased the delay_factor to 8 and will see how that goes.

**Comment by mcfone** [comment]
Meant to add that with whatever delay Netmiko 0.5.6 was using it was rock solid as far as this script was concerned.

**Comment by ktbyers** [comment]
Let me know how the delay factor of 8 works.

Unfortunately, reverse engineering what it used to be is probably not straight-forward. We had issues with this earlier as well.

**Comment by GGabriele** [comment]
Unfortunately it seems it can vary from device to device. I've just tested on a virtual one and the first good value was 13 :\

**Comment by ktbyers** [comment]
Okay, made this change in dev_1_1 branch:

https://github.com/ktbyers/netmiko/commit/891fc42f1d7f1ca51d8790a617bdd80dd71b0a56

That results in a 2 second delay which isn't that long.

Can either of you test the dev_1_1 branch and see if this fixes it? @mcfone @GGabriele

**Comment by GGabriele** [comment]
It worked for me.

**Comment by mcfone** [comment]
I've made the delay_factor change (to 20) in my copy of v1.0, and it's been working so far for most of the day, running every 10 minutes. I haven't tried using the full dev_1_1 branch yet...

**Comment by ktbyers** [comment]
Okay, I am going to close this issue.

If you see problems in the future, just open a new issue.
