### ISSUE TITLE
Netmiko unable to connect via GIT pipeline

### ISSUE THREAD

**Issue by anurudhdubey** [ktbyers/netmiko#2909]
Geeting NetmikoTimeOutException  Error .
Gets this error while running the code via GIT pipeline .
Host.yaml file
---
iosv-1:
    hostname: '10.10.10.2'
    port: 22
    username: 'dubey'
    password: 'dubey'
    platform: 'cisco_ios'

show_version.py file
--------------------

#!/usr/bin/env python
from nornir import InitNornir
from nornir_netmiko import netmiko_send_command
from nornir_utils.plugins.functions import print_result

# Initialize Nornir, by default it will look for the 
# hosts.yaml file in the same directory. 
nr = InitNornir()

# Run the show version command for each of the devices. 
# store the value in the results variable. 
result = nr.run(
    task=netmiko_send_command,
    command_string="show version"
)

# print the results in 
print_result(result)

**Comment by ktbyers** [comment]
```
Netmiko Error :netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed. Common causes of this problem are: 1. Incorrect hostname or IP address. 2. Wrong TCP port. 3. Intermediate firewall blocking access. Device settings: cisco_ios 10.10.10.2:22
```

**Comment by ktbyers** [comment]
@anurudhdubey Are you sure that your GIT pipeline can connect to `10.10.10.2` for SSH? How have you verified this?
