### ISSUE TITLE
Should create a get_config() method to Netmiko

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#291]
Probably pattern after NAPALM:

running-config
startup-config
candidate-config.

**Comment by pathcl** [comment]
@ktbyers what is NAPALM?

**Comment by pathcl** [comment]
@ktbyers wouln't be enough if just we use send_command(running_config)

**Comment by ktbyers** [comment]
See here for info on NAPALM  http://napalm.readthedocs.io/en/latest/

Netmiko supports some 25 different networking platforms...not as easy as just doing 'show run' (as many don't support `show run`; they might have candidate config, etc).
