### ISSUE TITLE
Netmiko: Cisco ASA send_config_set "Pattern not detected"

### ISSUE THREAD

**Issue by edgarpalamarchuk** [ktbyers/netmiko#2910]
Greetings! Please advise.

1. With multiple IP's in _asa.txt_, Netmiko pushes the config to the first device on the list and then throws this _Pattern not detected_ error.
2. With one IP in _asa.txt_, Netmiko pushes the config to the device and then throws the same _Pattern not detected_ error.
3. With multiple IP's in _asa.txt_ and only one config line in _CONFIG.txt_ (i.e., "no object network EDC_PAT"), Netmiko pushes the config to the devices with no errors.

------------------------------------
ERROR:
Traceback (most recent call last):
  File "send-config-from-file.py", line 38, in <module>
    net_connect.send_config_set(CONFIG)
  File "/home/user1/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 2170, in send_config_set
    output += self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/home/user1/.local/lib/python3.7/site-packages/netmiko/base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'object\\ network\\ EDC_PAT\\\n\\ host\\ 172\\.81\\.85\\.1' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

------------------------------------
PYTHON SCRIPT:
#!/usr/bin/python3 -tt
from netmiko import Netmiko
from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='debug.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

IP_LIST = open("asa.txt", "r")
for IP in IP_LIST:
	ASA = {
		'ip': IP,
		'username': 'user1',
		'password': 'password',
		'secret': 'password',
		'device_type': 'cisco_ios',
		'fast_cli': False,
		'session_log': 'CONFIG.log',
	}

	print('CONNECTING TO ' + IP)		
	net_connect = ConnectHandler(**ASA)
	net_connect.enable()
	with open('CONFIG.txt') as CONFIG_LINES:
		CONFIG = CONFIG_LINES.read()
	print(CONFIG)
    net_connect.send_config_set(CONFIG)
	net_connect.disconnect()

------------------------------------
CONFIG.txt:
object network EDC_PAT
 host 172.16.5.1

**Comment by ktbyers** [comment]
@edgarpalamarchuk 

```
'device_type': 'cisco_ios',
```

Try using `cisco_asa` for the `device_type` and see if that works.

**Comment by edgarpalamarchuk** [comment]
@ktbyers 
Kirk, thanks so much for the pointer! Works great now. Sorry I couldn’t update you earlier.
