### ISSUE TITLE
Brocade FOS not detecting in SSH Auto detect

### ISSUE THREAD

**Issue by laxusdreyar123** [ktbyers/netmiko#2916]
So I am trying to back up Brocade switches ( 6620 ) and I usually do backups with netmiko on Ethernet and thought would try it here. I have a simple logic where it detects the vendor type and then applies the appropriate command. However I get " None " when SSHDetect tries to detect the brocade switch vendor when it hits the IP.

So I am pasting the vendor detection bit here. I changed the IP, variable names, username and password for obvious reasons. Those shouldn't matter because my script is successfully logging into the SAN switch and then it throws out " device type: None ".

```
logininfo = {'device_type':'autodetect', 'host':'192.168.1.1', 'username':'username', 'password':'password'}
ssh_session = ConnectHandler(**logininfo)
guesser = SSHDetect(**logininfo)
print("Trying to determine the vendor")
best_match = guesser.autodetect()
print(" device_type: " + str(best_match))
```

So what do you think is going on here?

Netmiko version says 3.4.0

**Comment by laxusdreyar123** [comment]
I had to urgently get this done so I did a workaround where I equated "None" with Brocade FOS and did the backup.

However, I would really appreciate it if there's a fix or if I am doing something wrong.

**Comment by ktbyers** [comment]
There is currently no support for Brocade/Extreme in Netmiko's autodetect (though there is a broken open PR on it). Someone would need to add this into Netmiko's autodetect support.
