### ISSUE TITLE
IOError: Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by zeepi222** [ktbyers/netmiko#292]
Hi,

I am using netmiko and python to collect CPU information from Cisco IOS based access points. In most instances the script works fine, but on other occasions it fails and I cannot determine why.

python version = 2.7.8
netmiko version = 1.0.0
paramiko version = 2.0.2

Code sample:
```
            if icmp_response == 0:
                try:
                    device = ConnectHandler(device_type='cisco_ios', ip=APIPAddr, username=Aplogin, password=ApPassword)
                    sleep(0.5)
                    output = (device.send_command('show proc cpu | include LWAPP CLIENT')).encode("utf-8").split()
                    sleep(0.5)
                    device.disconnect()
                    logging.info('CPU usage for %s (%s) @ %s' % (DeviceName, DeviceIP, output[5].strip('%')))
                except NetMikoTimeoutException:
                    logging.info('SSH connection failed to %s (%s)' % (DeviceName, DeviceIP))
                except NetMikoAuthenticationException:
                    logging.info('AP Authentication Failure for %s (%s)' % (DeviceName, DeviceIP))
                except Exception:
                    logging.exception('Exception for %s (%s)' % (DeviceName, DeviceIP))
                    logging.info('Exception ...', output)
            else:
                logging.info('Device not pingable for %s, %s' % (DeviceName, DeviceIP))
```
Log Message:
```
Sat, 08 Oct 2016 12:36:01 CPU usage for ap2602 (10.36.14.152) @ ['81', '51008', '1355556', '37', '0.00%', '0.00%', '0.00%', '0', 'LWAPP', 'CLIENT']
Sat, 08 Oct 2016 12:36:01 CPU usage for ap2602 (10.36.14.152) @ 0.00
Sat, 08 Oct 2016 12:36:09 CPU usage for ap2602 (10.36.190.159) @ ['81', '26408', '915727', '28', '0.00%', '0.00%', '0.00%', '0', 'LWAPP', 'CLIENT']
Sat, 08 Oct 2016 12:36:09 CPU usage for ap2602 (10.36.190.159) @ 0.00
```
Error Message:
```
Sat, 08 Oct 2016 12:38:00 Exception for ap2602 (10.x.x.x)
Traceback (most recent call last):
  File "/home/user1/CheckCPU.py", line 430, in CPUQuery
    output = (device.send_command('show proc cpu sort | inc LWAPP CLIENT')).encode("utf-8").split()
  File "/home/user1/venv/lib/python2.7/site-packages/netmiko/base_connection.py", line 645, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: 51

Sat, 08 Oct 2016 12:38:00 *** CPUQuery() Error ***
Traceback (most recent call last):
  File "/home/user1/CheckCPU.py", line 443, in CPUQuery
    logging.info('Exception ...', output)
UnboundLocalError: local variable 'output' referenced before assignment
```

Manual Test:
```
[user1@hj1 ~]$ ssh -l admin 10.x.x.x
The authenticity of host '10.x.x.x (10.x.x.x)' can't be established.
RSA key fingerprint is 6b:c5:79:6e:13:f5:00:00:00:00:bb:08:99:5a:0d:b4.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.x.x.x' (RSA) to the list of known hosts.
Password: 
ap2602>show proc cpu | include LWAPP CLIENT
  81       35028      870017         40  0.00%  0.00%  0.00%   0 LWAPP CLIENT     
ap2602>quit
Connection to 10.x.x.x closed.
```

**Comment by ktbyers** [comment]
It looks like the failing command is:

```
output = (device.send_command('show proc cpu sort | inc LWAPP CLIENT')).encode("utf-8").split()
```

What happens on the AP when you execute the following manually:

```
show proc cpu sort | inc LWAPP CLIENT
```

Also note, you shouldn't need the 'encode', this is already done in the library (unrelated to this problem, however).

Anything funny about the timing of the command when executed manually (i.e. is it really slow)?

**Comment by zeepi222** [comment]
@ktbyers thank you for your prompt response.


I included the output of the manual check in the OP and the manual check seems to work without any noticeable issues. When I tested the manually it didn't seem slow or unresponsive.

I added the "encode" statement so that I could format the output into an integer and compare the result against a CPU threshold value (integer). Without the "encode" statement, the output looks as follows:
Sat, 08 Oct 2016 22:17:11 CPU usage for ap2602 (10.x.x.x) @ [u'81', u'35088', u'871616', u'40', u'0.00%', u'0.00%', u'0.00%', u'0', u'LWAPP', u'CLIENT']

Is there any benefit to having those "sleep" statements or can I remove them?

This is what the script log collected over night ...

IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 511
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 511
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: dt
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 511
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 511
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: id
IOError: Search pattern never detected in send_command_expect: 511
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: h\ 5
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 511
IOError: Search pattern never detected in send_command_expect: h\ 51
IOError: Search pattern never detected in send_command_expect: 51
IOError: Search pattern never detected in send_command_expect: 51
 
Does an IOError suggests that the TCP / SSH connection ended unexpectedly?

One other abnormality is that the script occasionally returns a blank output e.g. ...

Sat, 08 Oct 2016 18:11:15 CPU usage for ap2602 (10.x.x.x) @ []
Traceback (most recent call last):
  File "/home/user1/CPUCheck.py", line 435, in CPUQuery
    if ((float(output[5].strip('%'))) > CpuThreshold):
IndexError: list index out of range

**Comment by ktbyers** [comment]
I don't think you should need time.sleep, Netmiko should have the needed sleeps already.

The error indicates that it was expecting the trailing router prompt and it never found it in the output for some reason.

It would be interesting to turn on the debug flag in the send_command (line 602 in base_connection.py). You will have to:

https://github.com/ktbyers/netmiko
cd netmiko/netmiko
edit base_connection.py file

It would be interesting to see:

print self.base_prompt             (in case this is getting set wrong)

**Comment by zeepi222** [comment]
At which line number of base_connection.py should I insert the "print self.base_prompt"?

**Comment by ktbyers** [comment]
@zeepi222 Ooops my bad...in your program before it crashes you can just do:

```
device.base_prompt()
```

Assuming 'device' is the name of Netmiko object.

**Comment by zeepi222** [comment]
Yes, you are correct ... 'device' is my object name.
When I tried that inserting that print statement, I got the following error;

Traceback (most recent call last):
  File "./CPUCheck.py", line 437, in CPUQuery
    print(device.base_prompt())
TypeError: 'unicode' object is not callable

**Comment by zeepi222** [comment]
Hi Kirk,

Is there a way to enable "full debugging" so that I can see exactly what info is being sent and received during the SSH session?  For some reason, I have one particular device that continues to fail with an "IOError" but  I have no issues collecting the output manually. I notice a small delay when I login manually, the hostname prompt is presented to me approximately 4 seconds after sending the password. With that said, I know the device is running at 95% CPU utilization (which is the issue I am trying to identify using netmiko)

Here are the errors I see when I run the script;

Tue, 11 Oct 2016 01:49:10 SSH session ended unexpectedly for ap2602 (10.x.x.x)
Traceback (most recent call last):
  File "./CheckCPU.py", line 433, in CPUQuery
    output = (device.send_command('show processes cpu | include CPU')).encode("utf-8").split()
  File "/home/user1/venv/lib/python2.7/site-packages/netmiko/base_connection.py", line 645, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: rmi

Tue, 11 Oct 2016 01:53:09 SSH session ended unexpectedly for ap2602 (10.x.x.x)
Traceback (most recent call last):
  File "/home/user1/CheckCPU.py", line 433, in CPUQuery
    output = (device.send_command('show processes cpu | include CPU')).encode("utf-8").split()
  File "/home/user1/venv/lib/python2.7/site-packages/netmiko/base_connection.py", line 645, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: erm


Here is the output when I attempt a manual SSH connection;

(venv)[user1@jh1 ~]$ ssh -l admin 10.x.x.x
Password: 
ap2602>terminal len 0
ap2602>show processes cpu | include CPU
CPU utilization for five seconds: 100%/0%; one minute: 86%; five minutes: 88%
ap2602>exit
Connection to 10.x.x.x closed.
(venv)[user1@jh1 ~]$

**Comment by ktbyers** [comment]
@zeepi222 Okay, wrong format. It is an attribute (not a method) so no parenthesis.

```
print(device.base_prompt)
```

Try the following and let me know if it works:

```
time.sleep(3)
device.clear_buffer()
output = (device.send_command('show processes cpu | include CPU', expect_string='ap2602>')).encode("utf-8").split()
```

The send_command_expect() method tries to determine the routers prompt and use this as a trailing pattern for determining command completion. This looks like it is failing (possibly due to the router being slow).

**Comment by zeepi222** [comment]
Hi @ktbyers 

Below are the results. I did 6 runs with the sleep statement and 6 runs without the sleep statement;

Code:

device = ConnectHandler(device_type='cisco_ios', ip=APIPAddr, username=Aplogin, password=ApPassword)
sleep(3)
device.clear_buffer()
print(device.base_prompt)
output = (device.send_command('show processes cpu | include CPU', expect_string='ap2602>')).encode("utf-8").split()
CpuUsage = float(output[11].strip('%'))
print('CPU usage for %s (%s) @ %s' % (APName, APIPAddr, str(CpuUsage)))
device.disconnect()

Result with sleep(3) statement ...
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
CPU usage for ap2602 (10.68.138.156) @ 88.0
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
CPU usage for ap2602 (10.68.138.156) @ 88.0
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
CPU usage for ap2602 (10.68.138.156) @ 85.0
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
CPU usage for ap2602 (10.68.138.156) @ 86.0
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
CPU usage for ap2602 (10.68.138.156) @ 86.0
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
CPU usage for ap2602 (10.68.138.156) @ 87.0

Result without sleep(3) statement ...
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
CPU usage for ap2602 (10.68.138.156) @ 88.0
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
CPU usage for ap2602 (10.68.138.156) @ 88.0
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
('Exception .... ', IndexError('list index out of range',))
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
('Exception .... ', IndexError('list index out of range',))
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
('Exception .... ', IndexError('list index out of range',))
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
CPU usage for ap2602 (10.68.138.156) @ 90.0
(venv)[user1@jh1 ~]$ ./ssh_test.py 
ap2602
('Exception .... ', IndexError('list index out of range',))
(venv)[user1@jh1 ~]$

**Comment by zeepi222** [comment]
With the code below, I have had 100% success in 20 test runs;

device = ConnectHandler(device_type='cisco_ios', ip=APIPAddr, username=Aplogin, password=ApPassword)
sleep(1)
device.clear_buffer()
print(device.base_prompt)
output = (device.send_command('show processes cpu | include CPU')).encode("utf-8").split()
CpuUsage = float(output[11].strip('%'))
print('CPU usage for %s (%s) @ %s' % (APName, APIPAddr, str(CpuUsage)))
device.disconnect()

**Comment by ktbyers** [comment]
Yes, I suspect the device is slow due to being overloaded so not all the characters have been written to the screen (from the SSH login).

Adding the sleep allows these characters to get output (and not mess up your later command).

**Comment by zeepi222** [comment]
@ktbyers 
Thank you for your time and assistance.

**Comment by carrascodc** [comment]
I wrote a script that worked with Cisco NXOS and IOS, and then I tried to apply it to the F5 LTM and hit this error. The solution mentioned by zeepi222 fixed this problem. 
Thank you !!!

net_connect = ConnectHandler(**Node)
time.sleep(2)                                                       <<< Resolved this error message
print(net_connect.find_prompt())
