### ISSUE TITLE
Cisco IOS/IOS-XE prompts while removing usernames

### ISSUE THREAD

**Issue by nikunj436** [ktbyers/netmiko#2921]
```
from netmiko import ConnectHandler
from cred import username, password
ios_device = {
        'device_type': 'cisco_ios',
        'ip': '',  #deleted  ip for privacy issue
        'username': username,
        'password': password
    }
output = net_connect.send_command('show run | i username')   #i here get username which i want removed
change = 'no' +' ' + output
device = ConnectHandler(**ios_device)
device.send_config_set([change]) 
---
some more logic

----
device.disconnect()


```

---------------------------------------------------

here is the thing;-
2 things happening above code( it's chuck of code i used in differnet file)

1. When I put above block in try and except send_config_set([change)] till it work and also user deleted from devices. But after that some error occured and it got out and except blog is excuting everytime.
2.  So i went and cut that block and want to see what is going wrong. So now I'm receiving below error

 File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: '(?:)' in output.      #hostname removed for privacy purpose

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by nikunj436** [comment]
I tried ssh.net_timinng() but it was only for the non-config command.

when add additional line \n or another command then user is removed from the config but still getting error for the promot confirm.
promte with config commnad not able to get work. .strangely  able to remove username but why it's stuck.

how can i handle promote for config set?
f```
rom netmiko import ConnectHandler
from cred import username, password
change ='no username test'
ios_device = {
        'device_type': 'cisco_ios',
        'ip': 'x.x.x.x',
        'username': username,
        'password': password,
        "session_log": 'netmiko_session.log'
    }

device = ConnectHandler(**ios_device)


change = 'no username test \ny'
print(change)
device.send_config_set(change)
device.disconnect()
```

```
session log
R1#terminal width 511
R1#terminal length 0
R1#
R1#
R1#configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
R1(config)#
R1(config)#no username test
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]y
R1(config)#
(config)#

```

PS C:\Users\> python .\test_network.py
no username test
y
Traceback (most recent call last):
  File "C:\Users", line 18, in <module>
    device.send_config_set(change)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 2167, in send_config_set
    output += self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'no\\ username\\ test\\ \\\ny' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
Try:

```python
net_connect.config_mode()
net_connect.send_command("no username test", expect_string=r"#"))
net_connect.exit_config_mode())
```

I would argue this is a Cisco misdesign i.e. they shouldn't do what they did here (or at least should let you disable it so you are never prompted).

**Comment by ktbyers** [comment]
Probably a slightly better solution (or at least simpler):

```python
net_connect.config_mode()
net_connect.send_multline_timing("no username test", "y")
net_connect.exit_config_mode()
```

**Comment by nikunj436** [comment]
Thanks for response, first method works but still doubt why my 1st comment or 2nd post in thread "\n" didn't work.

simpler one give below error:
simpler one session log 


R1#terminal width 511
R1#terminal length 0
R1#
R1#
R1#configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
R1(config)#
R1(config)#n
% Incomplete command.

R1(config)#o
% Ambiguous command:  "o"
R1(config)#
R1(config)#u
% Ambiguous command:  "u"
R1(config)#s
% Incomplete command.

R1(config)#e
% Ambiguous command:  "e"
R1(config)#r
% Ambiguous command:  "r"
R1(config)#n
% Incomplete command.

R1(config)#a
% Ambiguous command:  "a"
R1(config)#m
% Incomplete command.

R1(config)#e
% Ambiguous command:  "e"
R1(config)#
R1(config)#m
% Incomplete command.

R1(config)#a
% Ambiguous command:  "a"
R1(config)#n
% Incomplete command.

R1(config)#o
% Ambiguous command:  "o"
R1(config)#j
                    ^
% Invalid input detected at '^' marker.

R1(config)#k
% Incomplete command.

R1(config)#
R1(config)#end
R1#
R1#
R1#exit

**Comment by ktbyers** [comment]
I don't really understand your post above (as that is a different behavior than your first comment on this thread...and from that I am inferring different code).

Your first comment solution doesn't work as embedding a newline into a command breaks Netmiko's cmd_verify and consequently you would have to disable cmd_verify to do that (but it is also a bit of an anti-pattern in Netmiko so I would recommend to not use that type of solution).
