### ISSUE TITLE
extreme mlx/netiron not going into enable mode

### ISSUE THREAD

**Issue by py-noob-01** [ktbyers/netmiko#2924]
Hello, I'm a novice developer.

Please understand that it is not smooth because I am not good at English.

While implementing netmiko, I confirmed that net_connect.enable() became normal for all other equipment.

In the meantime, only the extream mlx device does not enter enable even though there is an enable command.

Currently, show running-config is not running because it is not enabled.

I've changed several types of devices, but they're the same

Which part did I do wrong?

brocade_ip: 192.168.1.21, 192.168.1.21
brocade_command: show ip interface brief

```python
from netmiko import ConnectHandler

brocade_ip = open('brocade_ip.list', 'r')
brocade_command = open('brocade_command.list', 'r')

brocade_ip.list = brocade_ip.readlines()
brocade_command.list = brocade_command.readlines()

for brocade_devices in brocade_ip.list:
    brocade = {
            'device_type': 'brocade_netiron',
            'ip': brocade_devices,
            'username': 'admin',
            'password': 'qwe123!@#',
            'secret': 'qwe123!@#'
            }
    net_connect = ConnectHandler(**brocade)
    net_connect.enable()

    net_connect.find_prompt()
    print(net_connect.find_prompt())

    output_01 = net_connect.send_command('show running-config')

    config_backup = open(brocade_devices.strip(), 'w')
    print(brocade_devices.strip('\n') + ' Config Backup.....')
    print(config_backup.write(output_01))
    print(config_backup.write('\n\n############################################\n\n\n\n'))

    for brocade_commands in brocade_command.list:
        print(config_backup.write('!Command: ' + brocade_commands.strip() + '\n'))
        output_02 = net_connect.send_command(brocade_commands)
        print(config_backup.write(output_02))
        print(config_backup.write('\n\n\n\n############################################\n\n\n\n'))

    print(brocade_devices.strip('\n') + ' Config Backup..... Success!\n')
    config_backup.close()

    net_connect.disconnect()

brocade_ip.close()
brocade_command.close()`
```

**result>
SSH@MLX#1>
Invalid input -> show running-config**

**Comment by ktbyers** [comment]
I would look at the Netmiko session_log to see what is going on:

```python
brocade = {
'device_type': 'brocade_netiron',
'ip': brocade_devices,
'username': 'admin',
'password': 'qwe123!@#',
'secret': 'qwe123!@#',
'session_log': 'output.txt',
}
```

This will create a file named output.txt. I would see what that shows.

**Comment by py-noob-01** [comment]
thanks @ktbyers 

When I saw the session log you told me, I checked the phenomenon that it was not enabled.
It is confirmed that it is enabled normally when other equipment is used with the same script

--------------------
$ cat output.txt 
SSH@MLX#1>
SSH@MLX#1>
SSH@MLX#1>
SSH@MLX#1>skip-page-display
Invalid input -> skip-page-display
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>
SSH@MLX#1>
SSH@MLX#1>show running-config
Invalid input -> show running-config
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>show ip interface
Invalid input -> show ip interface
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>show ip route
Invalid input -> show ip route
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>show cluster
Invalid input -> show cluster
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>show lag
Invalid input -> show lag
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>show version
Invalid input -> show version
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>show chassis
Invalid input -> show chassis
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>show clock
Invalid input -> show clock
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>show ntp associations
Invalid input -> show ntp associations
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>show logging
Invalid input -> show logging
Type ? for a list
SSH@MLX#1>
SSH@MLX#1>exit

**Comment by ktbyers** [comment]
@py-noob-01 Which version of Netmiko are you using?

```
pip list | grep netmiko
```

Does the `skip-page-display` command work if you are in enable() mode (i.e. if you do this manually from the CLI)?

**Comment by py-noob-01** [comment]
> @py-noob-01 Which version of Netmiko are you using?
> 
> ```
> pip list | grep netmiko
> ```
> 
> Does the `skip-page-display` command work if you are in enable() mode (i.e. if you do this manually from the CLI)?

The netmiko version is 3.4.0.
If you enable it manually, the skip-page-display command works normally.

**Comment by ktbyers** [comment]
@py-noob-01 On the Extreme MLX/Netiron, what does `enable` look like. In other words, can you show elevating privileges using the CLI?

**Comment by py-noob-01** [comment]
@ktbyers 
I checked if I had the right to access it directly with enable, but there was no separate one.
However, the command send_command_timing('enable\n\admin\qwe123!@#') was not perfect, but it could be solved Thank you.

**Comment by py-noob-01** [comment]
@ktbyers Hello, Kirk
Hello, Kirk
I don't know if this is the prompt you want, but I'll upload it Let me know if you need anything. 
Thank you.

$ ssh -l admin 192.168.2.22
##################################################
WARNING !!!
All your Activities are monitored and recorded
Unauthorized access to this device is prohibited!
##################################################

Password:
SSH@MLX#2>
SSH@MLX#2>en
  enable            Enter Privileged mode
SSH@MLX#2>enable 
Password:
SSH@MLX#2#
SSH@MLX#2#

**Comment by ktbyers** [comment]
Okay, strange...it looks like the Netmiko code should have worked for the `enable()` call...so I don't see why it failed.

I am going to close this as it sounds like you have a workaround.
