### ISSUE TITLE
Timeout options

### ISSUE THREAD

**Issue by zeepi222** [ktbyers/netmiko#293]
Hi,

For SSH sessions which have not completed or terminated cleanly, are there any methods available for passing an absolute timeout or keep alive parameter to the SSH instance?

In some instances I have found that an SSH session has not terminated and remained connected for several hours, most likely due to a network failure. The result is that the python script never completes.

Below is an example of where a script appears to have hung and I can see an SSH session is still in an established state;

[user1@jh1]$ ps -ef | grep 51185
user1 51185 51179  0 19:50 ?        00:00:44 /home/user1/venv/bin/python /home/user1/CheckCPU.py
user1 51749 51185  0 19:50 ?        00:00:00 [sh] <defunct>
user1 51754 51185  0 19:50 ?        00:00:00 [sh] <defunct>
user1 51758 51185  0 19:50 ?        00:00:00 [sh] <defunct>
user1 51762 51185  0 19:50 ?        00:00:00 [sh] <defunct>
[user1@jh1]$ lsof -p 51185
python  51185 user1   30u  IPv4 4135001126      0t0        TCP 10.x.x.x:49320->10.x.x.x:ssh (ESTABLISHED)

**Comment by ktbyers** [comment]
@zeepi222 You will need to post your code--why didn't your script complete (or at least have an exception). The SSH sessions should terminate when your script completes.

**Comment by zeepi222** [comment]
```
ICMPQ = Queue()
WorkerThreads = 20

def CPUQuery():
    while True:
        try:
            DeviceInfo = ICMPQ.get()
            DeviceName = DeviceInfo[0]
            DeviceLocation = DeviceInfo[1]
            DeviceIPAddr = DeviceInfo[2]
            icmp_response = os.system(ICMPBin + DeviceIPAddr + ' > /dev/null 2>&1')
            if icmp_response == 0 and CheckCPU == 'Y':
                try:
                    device = ConnectHandler(device_type='devicesco_ios', ip=DeviceIPAddr, username=Devicelogin, password=DevicePassword, secret=DevicePassword)
                    sleep(4)
                    output = (device.send_command('show processes cpu | include CPU')).encode("utf-8").split()
                    CpuUsage = float(output[11].strip('%'))
                    print('CPU usage for %s (%s) @ %s' % (DeviceName, DeviceIPAddr, str(CpuUsage)))
                    logging.info('CPU usage for %s (%s) @ %s' % (DeviceName, DeviceIPAddr, str(CpuUsage)))
                    device.disconnect()

                except NetMikoTimeoutException:
                    Msg = 'SSH connection failed'
                    logging.info('SSH connection failed for %s (%s)' % (DeviceName, DeviceIPAddr))

                except NetMikoAuthenticationException:
                    Msg = 'SSH authentication failed'
                    logging.info('SSH authentication failure for %s (%s)' % (DeviceName, DeviceIPAddr))

                except IndexError:
                    Msg = 'Script could not collect CPU output'
                    logging.info('No CPU output received for %s (%s)' % (DeviceName, DeviceIPAddr))

                except IOError:
                    Msg = "SSH session terminated unexpectedly or timed out"
                    logging.info('SSH session ended unexpectedly for %s (%s)' % (DeviceName, DeviceIPAddr))

                except Exception:
                    logging.exception('Unspecified exception for %s (%s)' % (DeviceName, DeviceIPAddr))

            else:
                logging.info('Device not pingable for %s, %s, %s' % (DeviceName, DeviceLocation, DeviceIPAddr))

            ICMPQ.task_done()

        except Exception:
            logging.exception('*** CPUQuery() Error ***')
            sys.exit(1)

  def CheckCPU(failures):
    try:
        for i in range(WorkerThreads):
            t = Thread(target=CPUQuery)
            t.daemon = True
            t.start()
        for k, v in device_alert_detail.iteritems():
            for i in v:
                device_name = i[0]
                device_location = i[3]
                device_ipaddr = i[6]
                if device_ipaddr == 'unspecified IP' or device_ipaddr == '0.0.0.0':
                    pass
                else:
                    ICMPQ.put([device_name, device_location, device_ipaddr])
                    ICMPQ.join()

    except Exception:
        logging.exception('*** CheckCPU() Error ***')
```

**Comment by zeepi222** [comment]
@ktbyers 
I understand you are still working the documentation. If I understood the default timeouts and how to pass them, then I should be able to adjust the script to cater for various failure scenarios.

I'm looking for;
The connect timeout (how long netmiko will wait for the SSH connection to establish)
The expect timeout (how long netmiko will wait for a prompt or output to be returned)
The absolute timeout (how long netmiko will wait for the entire operation to complete)

Thanks

**Comment by ktbyers** [comment]
@zeepi222 I only had a chance to glance at your code. I suspect your issue is not a Netmiko timeout issue, but an issue with your 'while True' loop inside of CPUQuery.

Netmiko would have given up long before this.  Connect timeout defaults to 8 seconds.

send_command_expect looks like it will wait 100 seconds by default (trying to find the terminating pattern).

Netmiko will end the SSH session when you disconnect() or when your script exits so there is no absolute timeout.

**Comment by ktbyers** [comment]
I think this is really an issue with your script. 

I don't see a fix or a feature that should be added to Netmiko here...I am open to discussion about it, however.
