### ISSUE TITLE
[SG350] Trouble to consistently use send command.

### ISSUE THREAD

**Issue by ntaken** [ktbyers/netmiko#2933]
Using 
netmiko 4.1.2

Tried different SG350 switches same trouble. firmware 2.5.8.15 and 2.5.9.13 tested.
Perhaps every second or third time the script successfully retrieved the show command asked for.
Sometimes but more seldom, it failed to find prompt after collecting the output of show command (failed and suggested longer read_timeout; Have no example of that happening)

It worked consistently for 70+ different SG300 switches (When using Nornir runner: serial, Similar problem with retrieving send command happened with SG300 when using threaded runner and more than one worker).

Script used for testing:
```
import logging
import netmiko
logging.basicConfig(level=logging.DEBUG)
session = netmiko.ConnectHandler(
    host='10.86.252.106',
    username='USER',
    password='PASSWORD',
    device_type='cisco_s300')
results = session.send_command('show running-config')
```

Debug output.
[success.txt](https://github.com/ktbyers/netmiko/files/9488972/success.txt)
[fault_one.txt](https://github.com/ktbyers/netmiko/files/9488975/fault_one.txt)
[fault_three.txt](https://github.com/ktbyers/netmiko/files/9488976/fault_three.txt)
[fault_two.txt](https://github.com/ktbyers/netmiko/files/9488977/fault_two.txt)

**Comment by ktbyers** [comment]
It looks like your device is really slow.

Maybe, try setting fast_cli=False and increasing global_delay_factor.

```python
session = netmiko.ConnectHandler(
    host='10.86.252.106',
    username='USER',
    password='PASSWORD',
    global_delay_factor=2,
    fast_cli=False,
    device_type='cisco_s300')
```

Let me know if that helps or not.

**Comment by ntaken** [comment]
You were spot on.

The changes fixed it. Now i have not had a single fault in over 30 runs.
