### ISSUE TITLE
session_timeout and ConnectHandler(**router).disconnect() not working

### ISSUE THREAD

**Issue by arezazadeh** [ktbyers/netmiko#2942]
Hi, 

once i login to the device and retrive the interested output, i use `disconnect()` but it doesnt really terminate the session. then i tried to set the `session_timeout` but still doesnt reflect on my sessions. 

my netmiko version: `3.4.0`
my python version: `3.9.5`

# my config below: 

```
router = {
   'device_type': "cisco_ios",
    'username': "username",
    'password': "password",
    'host': "host_A",
    'fast_cli': False,
    'session_timeout': 20,
    'conn_timeout': 20,
     'timeout': 20
   }

ssh_obj = ConnectHandler(**router)

ssh_result = ssh_obj.send_command(f"show ip cef ", cmd_verify=True)

ssh_obj.disconnect()

```

**Comment by ktbyers** [comment]
You probably need to upgrade to the newest version of Netmiko: 4.1.2

Do you see the same issue using the newer version?

**Comment by arezazadeh** [comment]
hey thanks for the advise, i havent tried using the latest update and i was afraid there might be compatibility issue. but if you think there wont any problem then i can go ahead and update it to the latest

**Comment by arezazadeh** [comment]
ok i just updated to the latest version 4.1.2 and still seeing the same issue.

**Comment by ktbyers** [comment]
And what do you see in the Netmiko session_log on the disconnect() call?

```
router = {
   'device_type': "cisco_ios",
    'username': "username",
    'password': "password",
    'host': "host_A",
    'session_log': 'output.txt',         # This will create a file name "output.txt" in your current directory
    'fast_cli': False,
    'session_timeout': 20,
    'conn_timeout': 20,
     'timeout': 20
   }
```

**Comment by arezazadeh** [comment]
thanks so much. after logging it i found out i am not calling the disconnect() function properly. i fixed it and now its working fine. 
thanks so much again for your help. i will close this issue now.
