### ISSUE TITLE
Add support for Python context management (with statement)

### ISSUE THREAD

**Issue by jrschneider** [ktbyers/netmiko#295]
I think it would be neat to incorporate the ability to use the 'with' statement to manage connections to other devices. This would involve adding the __exit__ method to automatically close out any open connections (or maybe some other action is appropriate). 

This alleviates the need for direct connection management (having to remember to close connections), and would be especially useful for connecting to multiple devices within the same script. It can also come in handy in error handling so that we don't need to provide extraneous "close connection" code in the event of exceptions within the context, or wrap everything in massive try/except blocks.

For example:
```
with ConnectHandler(device_type='cisco_ios', ip=host, username=username, password=password) as cmd:

    config_output = cmd.send_command('show running')
    print(config_output)

# now that we've left the context, the cmd object is automatically disconnected and 
# closed out properly, if possible
sys.exit()
```

As of now, running the above code results in the following:

```
Traceback (most recent call last):
  File "/tmp/tmp.ZNdhTJ7Zva/lb-grab.py", line 24, in <module>
    with ConnectHandler(device_type='cisco_ios', ip=host, username=username, password=password) as cmd:

AttributeError: __exit__
```

**Comment by ebeahan** [comment]
I see value in this as well and created a PR with a proposed implementation: https://github.com/ktbyers/netmiko/pull/299

Open to changes or alternative approaches. Here's an example of the current proposed implementation:

```
>>> from netmiko import ConnectHandler
>>> with ConnectHandler(**linux_device) as conn:
...     print("Testing netmiko context manager functionality")
...     print(conn.send_command('uname -a'))
...
Testing netmiko context manager functionality
Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux
```

**Comment by ktbyers** [comment]
This was completed in the above PR. It is in the dev_1_2 branch.
