### ISSUE TITLE
Disabling output paging is not allowed.

### ISSUE THREAD

**Issue by cbarbudo** [ktbyers/netmiko#2960]
I´m connecting to a Cisco device using netmiko 4.1.2 to parse information with TEXTFSM. I've checked TEXTFSM is not involved on this problem.
I Use send_command_timing and get the answer for "show interfaces switchport", BUT seems I do not get all data. If I print data received last line finish with '--More--'.
I can't use the "terminal length 0" to solve this. In fact I have a lot of information parsed (I mean, i don't thing problem is related to that '--More--'. 
Seems like netmiko worked fine for others '--More--' but Maybe by the answer length? stoped removing it.

I tried even those additional lines (Not needed?)

datos_swp = connection.send_command_timing('show interfaces switchport', use_textfsm=True)
if '--More--' in datos_swp:
      datos_swp += connection.send_command_timing('\n')

Anyone can help?

**Comment by ktbyers** [comment]
Why can't you use `terminal length 0`?

`I can't use the "terminal length 0" to solve this.`

**Comment by cbarbudo** [comment]
End user do not want to modify it's configs (networking devices are not
mine). I know has no sense but...

**Comment by ktbyers** [comment]
@cbarbudo You would probably need to construct some sort of a custom method/function to use read_channel() and write_channel() to loop through all of the output and send the `space-bar` (or whatever the character-key that is needed to get another page of data).

You would then have to use some sort of a regex to filter all of the `--More--` lines from the output.

It is going to be pretty hard to manage the pagination manually. You could look at the Cisco WLC driver and see the pattern that we used there (as we did something similar in that driver).

**Comment by cbarbudo** [comment]
Thanks for the tip, Kirk. I'll take a look to that driver.
And of course, thanks for this wonderful tool.

Regards.
