### ISSUE TITLE
Can anyone help?

### ISSUE THREAD

**Issue by Sadanand75** [ktbyers/netmiko#2961]
Can anyone help? not been able to find out the issue

SCRIPT:

```python
from netmiko import ConnectHandler #from getpass import getpass

with open('commands.txt') as f: commands = f.read().rstrip()

with open('config.txt') as f: config_file = f.read().splitlines()

with open('ip_list.txt') as f: device_list = f.read().splitlines()

for device in device_list: 

    print("connecting " + device) 
    iosv = { 'device_type': 'cisco_ios', 'ip': device, 'username': 'anand', 'password': 'cisco', }

    net_connect = ConnectHandler(**iosv)
    output = net_connect.send_command(commands)
    full = 'Full-duplex'
    half = 'Half-duplex'
    if 'Half-duplex' in output:
            print("its " + half)
            print("Configuring it to Full-duplex")
            net_connect.enable()
            output = net_connect.send_config_set(config_file)
    else:
            print("its " + full)
```

ERROR:

root@NetworkAutomation-1:~# python3 test.py
connecting 192.168.122.100 
its Half-duplex 
Configuring it to Full-duplex

 Traceback (most recent call last): File "test.py", line 29, in net_connect.enable() File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 25, in enable return super().enable( File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1935, in enable output += self.read_until_prompt() File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 755, in read_until_prompt return self.read_until_pattern( File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 672, in read_until_pattern raise ReadTimeout(msg) netmiko.exceptions.ReadTimeout:

Pattern not detected: 'R1' in output.

Things you might try to fix this:

Adjust the regex pattern to better identify the terminating string. Note, in many situations the pattern is automatically based on the network device's prompt.
Increase the read_timeout to a larger value.
You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
Can you show what `commands` contains?

You might want to add the Netmiko `session_log` to your device definition so you can see what is going on during the session.

```python
iosv = { 
    'device_type': 'cisco_ios', 
    'ip': device, 
    'username': 'anand', 
    'password': 'cisco', 
    'secret': '',          # Add your enable secret here. I put a blank string as a placeholder.
    'session_log': 'output.txt',
```

This will create a file named 'output.txt' in your local directory. That will provide more details about what is occurring.

**Comment by Sadanand75** [comment]
Thank you adding secret worked like a charm.... session_log was very useful too..
