### ISSUE TITLE
Dell PowerConnect 8024F version 5 unable to authenticate

### ISSUE THREAD

**Issue by iHaagcom** [ktbyers/netmiko#2964]
Hi all,

I get Failed Authentication when trying to backup our powerconnect 8024F

```python
##Dell PowerConnect
TNOW = datetime.datetime.now().replace(microsecond=0)
IP_LIST = open('DellPowerConnect_devices')
TNOW=TNOW.strftime("%d%b%Y")
for IP in IP_LIST:
    print ('\n #### Connecting to the Switch '+ IP.strip() + ' #### \n' )
    RTR = {
    'ip':   IP,
    'username': 'admin',
    'password': 'admin',
    'device_type': 'dell_powerconnect',
    }

    try:
        net_connect = ConnectHandler(**RTR)
    except NetmikoTimeoutException:
        print ('Device not reachable')
        continue
    except AuthenticationException:
        print ('Failed to Authenticate')
        continue
    except SSHException:
        print ("Make sure SSH is enabled in device.")
        continue

    print ('Initiating backup')
    net_connect.enable()
    output = net_connect.send_command('show startup-config')
    IP=IP.strip()
    SAVE_FILE = open(IP +'_'+TNOW,'w')
    SAVE_FILE.write(output)
    SAVE_FILE.close
    print ('Finished config backup')`
```

Is it because it required en before the admin password is sent?

**Comment by ktbyers** [comment]
Can you post the full exception stack trace? You will need to get rid of your try/except statement(s) as that will hide the error.

**Comment by iHaagcom** [comment]
Device settings: dell_powerconnect 192.168.0.99:22


Bad authentication type; allowed types: ['publickey', 'password', 'keyboard-interactive']
initating backup
Dell_PowerConnect.py", line 45, in <module>
    net_connect.enable()
NameError: name 'net_connect' is not defined

**Comment by iHaagcom** [comment]
Managed to get in with sending a write_channel('en\n')

But sending commands and capturing them is the next challenge.

**Comment by iHaagcom** [comment]
Anyone know how to display the whole output???

`guesser = SSHDetect(**device)
best_match = guesser.autodetect()
print(best_match)  # Name of the best device_type to use further
#Find the current view 
net_connect = ConnectHandler(**device)
SAVE_FILE = open('Dell_Churchill_PowerConnect','w')
net_connect.write_channel("en\n")
time.sleep(1)
output = net_connect.read_channel()
output = net_connect.send_command_timing("terminal datadump")
print(output)
print(net_connect.find_prompt())
print ('Initiating backup')
#net_connect.send_command("show run\n", expect_string=r"More", strip_prompt=False, strip_command=False)
#output = net_connect.send_command(command_string="terminal length 1\n", expect_string=r"#")
#print(output)
print(net_connect.find_prompt())
output = net_connect.send_command(command_string="show running\n", expect_string=r"--More--")
output = net_connect.send_command("show running")
print(output)
output = net_connect.read_channel()
print(net_connect.find_prompt())
SAVE_FILE.write(output)
SAVE_FILE.close
net_connect.disconnect()`

**Comment by iHaagcom** [comment]
Anyone know how to display the whole output???

`guesser = SSHDetect(**device)
best_match = guesser.autodetect()
print(best_match)  # Name of the best device_type to use further
#Find the current view 
net_connect = ConnectHandler(**device)
SAVE_FILE = open('Dell_PowerConnect','w')
net_connect.write_channel("en\n")
time.sleep(1)
output = net_connect.read_channel()
output = net_connect.send_command_timing("terminal datadump")
print(output)
print(net_connect.find_prompt())
print ('Initiating backup')
#net_connect.send_command("show run\n", expect_string=r"More", strip_prompt=False, strip_command=False)
#output = net_connect.send_command(command_string="terminal length 1\n", expect_string=r"#")
#print(output)
print(net_connect.find_prompt())
output = net_connect.send_command(command_string="show running\n", expect_string=r"--More--")
output = net_connect.send_command("show running")
print(output)
output = net_connect.read_channel()
print(net_connect.find_prompt())
SAVE_FILE.write(output)
SAVE_FILE.close
net_connect.disconnect()`
