### ISSUE TITLE
get terminal width from somtimes when collecting configuration for the device

### ISSUE THREAD

**Issue by caibitim** [ktbyers/netmiko#297]
Hi,

I'm using 1.00 to do some configuration backup for cisco devices. it runs everyday to collect the configuration for cisco switch. However, I just found there is a chance that these lines will be included in the configuration. Not too sure what caused it.

gth 0
hostname#terminal width 511
hostname#
hostname#
hostname#show config

Here is the code I used, it should be pretty striaghtforward.
```python
con = ConnectHandler(**dev_config)
host_name = con.find_prompt()[:-1]'
curr_config = con.send_command_expect('show config')
```

any clue for this?

**Comment by ktbyers** [comment]
What device_type are you using--is it 'cisco_ios'?

Yes, the following two commands get executed post login:

# terminal length 0
# terminal width 511

There is a delay post login to clear these out, but it looks like this device is slower so they don't get cleared out of the buffer.

You could add the following:

```
import time
time.sleep(3)
con.clear_buffer()
```

That should clear out the extra characters.

**Comment by caibitim** [comment]
So I need to sleep for 3 seconds and clear the buffer.
after I call con = ConnectHandler(**dev_config)?

**Comment by ktbyers** [comment]
Yes, you might be able to sleep for a shorter time.

Do you see this on only a small number of devices or do you see this regularly (the extra commands in the output)?

**Comment by caibitim** [comment]
I would say it has around 10% chance to happen (cisco switch fortinet firewall) in LAN network, and I think it is a lot, becasure it's in the LAN, not WAN or Internet. 

I'm doing the configuration backup if the configuration changes for around 15 devices. If my script runs every minutes, I will get some invalid configuraion in one hour for some devices. If I run the script everyday, I will start to get the invalid configuration in a week. it's not limited to the specific device.

I still don't undestand why the "width 511 and hostname#show config" can be included in the configuration. I thought the library should clear the buffer before I send the command and terminal length 0 and width 511 should be the way you disable the paging. why are they still in the buffer after I send "show configuration" to the device?

**Comment by ktbyers** [comment]
@caibitim I do the following after you complete your SSH session:

```
        self.set_base_prompt()
        self.disable_paging()
        self.set_terminal_width()
```

I suspect there is an issue with the set_base_prompt() not getting set right (do to not sleeping long enough). This is causing both disable_paging and set_terminal width to not have their output cleared. They normally should clear that output.

I also should probably add a clear_buffer() after the set_terminal_width.

I will probably try to improve this sometime this week.

**Comment by caibitim** [comment]
I just read the source code in your libary. I think it should be caused by self.set_terminal_width(). Since in disable page and set_base_prompt, there are buffer_clear method to clear the buffer, but there isn't any buffer clear in set_terminal_width. From my result, what I usually saw for invalid configuration is starting with terminal width 511 and a few prompt like(cisco_switch#). I'm not that familiar with paramiko and your libary, Hope it can help you to narrow down the issue.

**Comment by caibitim** [comment]
I just think it again. I think it could bre resolved by setting a larger global_delay_factor. Please let me if what I think is wrong

**Comment by ktbyers** [comment]
Here is what I see in your output (from above):

```
gth 0
hostname#terminal width 511
hostname#
hostname#
hostname#show config
```

I see part of the remnants of 'terminal length 0'. That really shouldn't be there. I think this should have read it off the channel.

```
       # In disable_paging method()
        self.write_channel(command)
        output = self.read_until_prompt()
```

Then we see the entirety of 'terminal width 511' i.e. the command that is sent in the set_terminal_width which I would have expected to be read here (i.e. I would have expected it not to be there):

```
        # in set_terminal_width() method
        self.write_channel(command)
        output = self.read_until_prompt()
```

Yes, you might be able to fix it with setting a larger global_delay_factor() maybe try a value of 2 or 4 and see if it fixes it.

Notwithstanding that there might be changes I need to make in the library so that this is less likely to happen.

**Comment by ktbyers** [comment]
Okay, I am adding a minor sleep after completing session_preparation and then a clear_buffer(). This might help clear the buffer. I still think the fundamental problem above is that base_prompt didn't get set right.

This possibly is due to given device just being really slow (or something else).

Let me know if setting global_delay_factor() to a larger doesn't fix this issue.

**Comment by hungtdao** [comment]
ktbyers, 
      Somehow I got this error when trying to send_command "show run" on arista_eos device.  Any idea?  Thanks.

  strConfig = net.send_command("show run")
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 1051, in send_command
IOError: Search pattern never detected in send_command_expect:

**Comment by ktbyers** [comment]
@hungtdao You need to open a new issue in GitHub for Netmiko. Please post your code (you can obfuscate any confidential information). Also please post your full stack trace and the version of Netmiko that you are using.
