### ISSUE TITLE
viptela profile missing from ssh_autodetect.py

### ISSUE THREAD

**Issue by tramontano** [ktbyers/netmiko#2972]
Hello,

I noticed that during a massive check on the network several Viptela devices failed with `ValueError: Unsupported 'device_type'`

When I went to ssh_autodetect.py I noticed that we don't have the cisco_viptela profile, even though having the cisco_viptela.py inside netmiko.cisco

I have added the below to the ssh_autodetect.py and seems to be working now:
```
    "cisco_viptela": {
        "cmd": "show system status",
        "search_patterns": [r"Viptela, Inc"],
        "priority": 99,
        "dispatch": "_autodetect_std",
    },
```
Hope it helps !

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/2975
