### ISSUE TITLE
Newer Cisco Wireless Controllers failing to get detected with ssh_autodetect

### ISSUE THREAD

**Issue by tramontano** [ktbyers/netmiko#2973]
Hello ktbyers,

I would like to help improve netmiko by making a change in the ssh_autodetect. I noticed that newer Cisco Wireless Controllers have a different output on the `show inventory` (Cisco 5500 Wireless Controller, instead of Cisco Wireless Controller, for example) that makes newer WLCs not be auto-detected by netmiko. By leaving only "Wireless Controller" it worked for me! Not sure if anyone thought of a better way of doing this, but this is what my lazy brain was able to come out as a workaround.

```
"cisco_wlc_85": {
        "cmd": "show inventory",
        "dispatch": "_autodetect_std",
        "search_patterns": [r" Wireless Controller",],
        "priority": 99,
    }
```

Cheers!

**Comment by ktbyers** [comment]
Should be fixed in that linked Pull Request. Thanks for letting me know.
