### ISSUE TITLE
unable to enter CLI mode on Juniper device 

### ISSUE THREAD

**Issue by pkrrules** [ktbyers/netmiko#298]
Tried this code on a juniper device 

https://raw.githubusercontent.com/wdennis/Netmiko-Testing/master/junos-test.py

I see that "show" command is not recognized. It doesn;t seem to enter CLI mode. 
-sh: show: command not found
-sh: display: command not found

I was also unable to enter config mode:

> > > device.config_mode()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/netmiko/juniper/juniper_ssh.py", line 64, in config_mode
> > >     return super(JuniperSSH, self).config_mode(config_command=config_command)
> > >   File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 742, in config_mode
> > >     raise ValueError("Failed to enter configuration mode.")
> > > ValueError: Failed to enter configuration mode.
> > > device.enter_cli_mode()
> > > device.send_command('show version')
> > > u'show: Command not found.'
> > > output = device.send_command('show version')
> > > print output

When I login to a chassis, I log in to a shell. How do I enter CLI mode to attempt the above commands. Please let me know if there are known issues. I am new to netmiko. I am just poking around. I would love to help resolve issues.

**Comment by ktbyers** [comment]
@pkrrules What version of netmiko are you using?

```
>>> import netmiko
>>> netmiko.__version__
```

**Comment by pkrrules** [comment]
I am using 1.0.0

>>> import netmiko
>>> netmiko.__version__
'1.0.0'

**Comment by ktbyers** [comment]
@pkrrules Can you print out what happens when you try to run the script in the file that you linked to?

FYI, is @pkrrules Will Dennis?

**Comment by ktbyers** [comment]
FYI, here is what should happen (this is from dev_1_1 branch), but 1.0.0 should be the same as this:

```
    def session_preparation(self):
        """
        Prepare the session after the connection has been established.

        Disable paging (the '--more--' prompts).
        Set the base prompt for interaction ('>').
        """
        self.enter_cli_mode()
        self.set_base_prompt()
        self.disable_paging(command="set cli screen-length 0\n")
        self.set_terminal_width(command='set cli screen-width 511')

    def enter_cli_mode(self):
        """Check if at shell prompt root@.*% shell prompt and go into CLI."""
        delay_factor = self.select_delay_factor(delay_factor=0)
        count = 0
        cur_prompt = ''
        while count < 50:
            self.write_channel("\n")
            time.sleep(.1 * delay_factor)
            cur_prompt = self.read_channel()
            if re.search(r'root@.*%', cur_prompt):
                self.write_channel("cli\n")
                time.sleep(.3 * delay_factor)
                self.clear_buffer()
                break
            elif '>' in cur_prompt or '#' in cur_prompt:
                break
            count += 1
```

**Comment by ktbyers** [comment]
A couple of interesting things to see would be:

1. Instead of executing the send_command() method, execute find_prompt() so you can see whether the 'cli' worked.

2. Show me what you manually see in the CLI when you login (i.e. repeat the process of SSH login and executing):

show chassis hardware | display xml

So I can see if I see anything that Netmiko will break on.

**Comment by pkrrules** [comment]
Hi Kirk

No. My name is Pradeep. I was just trying to poke around with netmiko and
came across a script written by Will Dennis. Here is the original article
by Will Dennis

http://packetpushers.net/parsing-junos-xml-python/


I tried to run the script by modifying just the login credentials:

-sh: show: command not found
-sh: display: command not found

That is all I see.

When I execute find_prompt()

I see the shell

>>> output = device_conn.find_prompt()
>>> print output
root@vMX1_RE:~ #


Here is the output when I ssh to vmx:

--- JUNOS 15.1R1.9 Kernel 32-bit
 JNPR-10.1-20150617.306001_builder_stable_10
root@vMX1_RE:~ #

I manually launch cli to enter show/configure commands.

Thanks
Pradeep

**Comment by ktbyers** [comment]
@pkrrules Can you capture the entire manual CLI session, including SSH login, execute 'cli' command, execute 'show' command in Juniper shell.

Also, please make sure you properly format GitHub markdown.

**Comment by pkrrules** [comment]
Here is the CLI session with SSH login:

pradeeps@svl-evodev-pradeeps:~$ ssh root@10.102.225.114
Last login: Wed Oct 19 17:37:28 2016 from 10.160.3.2
--- JUNOS 15.1R1.9 Kernel 32-bit
 JNPR-10.1-20150617.306001_builder_stable_10
root@vMX1_RE:~ # cli
root@vMX1_RE> show chassis hardware | no-more
Hardware inventory:
Item             Version  Part number  Serial number     Description
Chassis                                VMX9b74           MX960
Midplane
Routing Engine 0                       2799c6ec-96       RE-VMX
CB 0                                                     VMX SCB
CB 1                                                     VMX SCB
FPC 0                                                    Virtual 20x1G +
4x10G FPC
  CPU            Rev. 1.0 RIOT         123XYZ987
  MIC 0                                                  Virtual 20x
1GE(LAN) SFP
    PIC 0                 BUILTIN      BUILTIN           Virtual 10x
1GE(LAN) SFP
    PIC 1                 BUILTIN      BUILTIN           Virtual 10x
1GE(LAN) SFP
  MIC 1                                                  Virtual 4x
10GE(LAN) XFP
    PIC 2                 BUILTIN      BUILTIN           Virtual 2x
10GE(LAN) XFP
    PIC 3                 BUILTIN      BUILTIN           Virtual 2x
10GE(LAN) XFP

root@vMX1_RE>

**Comment by ktbyers** [comment]
@pkrrules Did you change your default root shell (in the VMX)? I am expecting the following prompt:

```
if re.search(r'root@.*%', cur_prompt):
```

i.e. something that ends with '%'

**Comment by ktbyers** [comment]
@pkrrules Any update on this (on the question that I asked above)?

**Comment by pkrrules** [comment]
No. I didn't change the prompt. Probably there is difference machine
developer image and publicly deployed images on this chassis. In any case,
I would like to modify it to check and accept the prompt as is. Can you
suggest some tweaks?

Thanks
Pradeep

**Comment by ktbyers** [comment]
@pkrrules Okay, I will have to think about this...unfortunately Juniper is making it hard to differentiate between the Unix shell and the router prompt.

**Comment by pkrrules** [comment]
I got around this for now by not checking the trailing character. I am just
looking for "root" prompt.

Here is my change to "enter_cli_mode" method. Can you please update the
code ? I didn't clone the sandbox.

    def enter_cli_mode(self):
        """Check if at shell prompt root@.*% shell prompt and go into
CLI."""
        delay_factor = self.select_delay_factor(delay_factor=0)
        count = 0
        cur_prompt = ''
        while count < 50:
            self.write_channel("\n")
            time.sleep(.1 * delay_factor)
            cur_prompt = self.read_channel()
            if re.search(r'root@.*', cur_prompt):
<<<<<<<<<<<<<<<<<<<<<<<<<<<
                self.write_channel("cli\n")
                time.sleep(.3 * delay_factor)
                self.clear_buffer()
                break
            elif '>' in cur_prompt or '#' in cur_prompt:
                break
            count += 1

**Comment by ktbyers** [comment]
@pkrrules Okay, implemented this fix. It is in the dev_1_2 branch. I think it should fix your issue.

https://github.com/ktbyers/netmiko/commit/e9800fac569a05f546e8f1bf1a4b9a8c2b6ab0e1
