### ISSUE TITLE
DEBUG:netmiko:_read_channel_expect read_data:

### ISSUE THREAD

**Issue by krishnashk** [ktbyers/netmiko#2989]
There is a difference is the way the "DEBUG:netmiko:_read_channel_expect read_data:" the data handled, I am supposed to enter "yes" at the prompt , but at the prompt I see only "y" is entered.  it works fine for a similar platform , was trying to understand why it is occurring.

netmiko                   3.4.0

**Comment by krishnashk** [comment]
DEBUG:paramiko.transport:starting thread (client mode): 0x6920e160
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.5 PKIX[10.1]
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.5)
DEBUG:paramiko.transport:kex algos:['ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group16-sha512', 'diffie-hellman-group14-sha256'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] server mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for modcr1sub1.lowes.com: b'77696a15391e10010214f13394ea4a03'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: Command Line Interface is starting up, please wait ...



   Welcome to the Platform Command Line Interface



VMware Installation:

	4 vCPU: Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz

	Disk 1: 110GB, Partitions aligned

	8192 Mbytes RAM



admin:
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'utils system shutdown\n'
DEBUG:netmiko:Pattern is: utils\ system\ shutdown
DEBUG:netmiko:_read_channel_expect read_data: ut
DEBUG:netmiko:_read_channel_expect read_data: ils syst
DEBUG:netmiko:_read_channel_expect read_data: e
DEBUG:netmiko:_read_channel_expect read_data: m shutdown



Do you really want to shutdown ?



Enter (yes/no)? 
DEBUG:netmiko:Pattern found: utils\ system\ shutdown utils system shutdown



Do you really want to shutdown ?



Enter (yes/no)? 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'yes\n'
DEBUG:netmiko:Pattern is: yes
DEBUG:netmiko:_read_channel_expect read_data: y
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:paramiko.transport:starting thread (client mode): 0x691ebf10
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.5 PKIX[10.1]
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.5)
DEBUG:paramiko.transport:kex algos:['ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group16-sha512', 'diffie-hellman-group14-sha256'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] server mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for modcr1sub2.lowes.com: b'de7b332bb9da6bb40f701462674c264b'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: Command Line Interface is starting up, please wait ...



   Welcome to the Platform Command Line Interface



VMware Installation:

	4 vCPU: Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz

	Disk 1: 110GB, Partitions aligned

	8192 Mbytes RAM



admin:
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'utils system shutdown\n'
DEBUG:netmiko:Pattern is: utils\ system\ shutdown
DEBUG:netmiko:_read_channel_expect read_data: u
DEBUG:netmiko:_read_channel_expect read_data: tils system shutdown


DEBUG:netmiko:Pattern found: utils\ system\ shutdown utils system shutdown


DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

Do you really want to shutdown ?



Enter (yes/no)? 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'yes\n'
DEBUG:netmiko:Pattern is: yes
DEBUG:netmiko:_read_channel_expect read_data: yes





 Appliance is being Powered - Off ...


DEBUG:netmiko:Pattern found: yes yes





 Appliance is being Powered - Off ...


DEBUG:paramiko.transport:EOF in transport thread

**Comment by ktbyers** [comment]
Can you include the relevant section of your code and the Netmiko device_type you are using?

**Comment by krishnashk** [comment]
with ConnectHandler (**cucm_node) as net_connect:
            time.sleep(40)

            net_connect.send_command("utils system shutdown",expect_string=r"Enter (yes/no)?")
            
            net_connect.send_command(sendyes,expect_string="Appliance")
        
            
            net_connect.disconnect()

-------------

fname=ip+".log"
    cucm_node = {
            'device_type': 'autodetect',
            "host": ip,
            "username": username,
            "password":password,
            "fast_cli":False,
            "session_log": fname
            }

**Comment by ktbyers** [comment]
@krishnashk 

I would try this:

```python
with ConnectHandler (**cucm_node) as net_connect:
    net_connect.send_command("utils system shutdown",expect_string=r"Enter (yes/no)?")
    net_connect.write_channel("yes\n")
```

In your logs above, Netmiko sent the "yes", see here:

```
DEBUG:netmiko:write_channel: b'yes\n'
DEBUG:netmiko:Pattern is: yes
DEBUG:netmiko:_read_channel_expect read_data: y
DEBUG:paramiko.transport:EOF in transport thread
```

So I expect the issue is that device actually reloaded/shutdown before the rest of the data could be read. So with my above proposed fix, you don't try to do any reading after the 'yes' is sent (i.e. you send it and then assume the device is down).

You can obviously test that it is down also, but at that point you would expect any SSH connection is no longer functioning.

**Comment by krishnashk** [comment]
looks like it is working , I will do more testing on it. thank you @ktbyers
