### ISSUE TITLE
Question with using textfsm with Netmiko

### ISSUE THREAD

**Issue by hhha7x** [ktbyers/netmiko#2993]
Trying to do a check against Cisco IOSXE to see if any ports are still configured in the default VLAN.

    Output = net_connect.send_command ('show int status', use_textfsm=true)
    for i in output:
      if i["vlan"] == "1":
        print ('Not compliant')
      else:
        print ('Compliant')

This does work, but for a 48 port switch, I get 48 lines saying Compliant or Not Compliant. How can I change this so that if all ports are in a different vlan, lets say vlan 2, I get one line saying Complaint. And if ANY number of ports are in VLAN 1 , whether is be 1 port or 10 ports, I get one line saying "Not complaint", instead of 48 lines.

**Comment by hhha7x** [comment]
Sorry was out for the weekend and just getting back to this. The output of this is just 48 lines saying "Compliant". 

`This is not compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant
This is compliant`

Like I said, I would just like one line saying "this is compliant" if all 48 ports are not in VLAN 1. If any number of ports are in vlan 1 (whether it be 1 port or 17 ports), I would like 1 line saying "This is not complaint."

**Comment by ktbyers** [comment]
Can I see the contents of the `Output` variable here:

```
Output = net_connect.send_command ('show int status', use_textfsm=true)
```

In other words, I want to see the `show int status` result.

**Comment by hhha7x** [comment]
Oh yeah of course.....

`[{'port': 'Gi1/0/1', 'name': '', 'status': 'notconnect', 'vlan': '1', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/2', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/3', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/4', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/5', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/6', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/7', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/8', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/9', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/10', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/11', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/12', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/13', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/14', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/15', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/16', 'name': '', 'status': 'notconatus': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/19', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/20', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/21', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/22', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/23', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode':X', 'fc_mode': ''}, {'port': 'Gi1/0/26', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/27', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/28', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/29', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/30', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/31', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 
lex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/34', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/35', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/36', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/37', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/38', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/39', 'name': '', ' 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/42', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/43', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/44', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/45', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/46', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/47', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Gi1/0/48', 'name': '', 'status': 'notconnect', 'vlan': '999', 'duplex': 'auto', 'speed': 'auto', 'type': '10/100/1000BaseTX', 'fc_mode': ''}, {'port': 'Te1/1/1', 'name': '', 'status': 'connected', 'vlan': 'trunk', 'duplex': 'full', 'speed': '10G', 'type': 'SFP-10GBase-LR', 'fc_mode': ''}, {'port': 'Te1/1/2', 'name': '', 'status': 'disabled', 'vlan': 'trunk', 'duplex': 'auto', 'speed': 'auto', 
'type': 'unknown', 'fc_mode': ''}, {'port': 'Te1/1/3', 'name': '', 'status': 'disabled', 'vlan': 'trunk', 'duplex': 'auto', 'speed': 'auto', 'type': 'unknown', 'fc_mode': ''}, {'port': 'Te1/1/4', 'name': '', 'status': 'disabled', 'vlan': 'trunk', 'duplex': 'auto', 'speed': 'auto', 'type': 
'unknown', 'fc_mode': ''}]`

**Comment by ktbyers** [comment]
Maybe print it out with Python rich and then post it here? The above has a Python syntax error in it and since it is all on one line I can't find the error.

```python
from rich import print

# Other lines to create the Netmiko connection
output = net_connect.send_command ('show int status', use_textfsm=True)

print(output))
```

Then re-paste the output here.
