### ISSUE TITLE
Hi! I have a small question.

### ISSUE THREAD

**Issue by MrAntonS** [ktbyers/netmiko#2997]
Is there any way to make this library behave like telnetlib function read_eager, which allows you to read some bytes in a buffer but not blocking the I/O. I am trying to make a console for ssh with python and was thinking if i can add ssh to my little GUI program. But I'm not sure if i can constantly check for bytes in a buffer without sending any commands like in telnet lib

**Comment by ktbyers** [comment]
@MrAntonS Is the general issue that you are trying to create an `async program` and consequently need it to be non-blocking?

**Comment by MrAntonS** [comment]
The program will be ran in different thread(I'm not sure if it's async or not) but it needs to get information from device as soon as possible. My gui itself is very similar to SuperPutty. So i just need to update console as fast as possible and send keys I'm pressing. Sorry for my bad English. If there is no information ready it should just return blank byte-string(b'')

**Comment by ktbyers** [comment]
You could try creating your own function/method using read_channel() and write_channel() or you can try to access the underlying Paramiko constructs and see if there is something that is sufficiently fast for your use case.
