### ISSUE TITLE
What is the purpose of the find_prompt string

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#30]
What does it do, when does it get updated, is it named properly.

Placeholder as I am concerned how I am currently using this is going to cause problems/confusion.

**Comment by ravenblue12** [comment]
find_prompt is an important function to distinguish the different modes at the cli. It should be updated after login and after the enable or config command.

**Comment by ktbyers** [comment]
Here is the main issue...some platforms (Juniper, Alcatel, Cisco to a certain extent in config mode) have prompts that very frequently change.

When you call find_prompt(), it updates the self.router_prompt attribute (and self.router_prompt is used as part of the send_command() method to strip off the trailing prompt at the end of show commands).  If self.router_prompt doesn't match the current real prompt, then this stripping the trailing prompt from show output would fail.

IMO there should be two things:
1. set_base_prompt() which updates self.router_prompt (maybe rename this self.base_prompt) which should be called as little as possible.  It would be called on initial login and maybe on enter/exit enable mode, maybe on enter/exit config mode (if necessary--i.e. the prompt changes sufficiently to require this).

2. find_prompt() which just returns the current router prompt (i.e. sends a blank '\n' down the channel and returns whatever comes back i.e. the current prompt).  Nothing is saved in the object because of this call.
