### ISSUE TITLE
send_command may return before the command output gets responsed

### ISSUE THREAD

**Issue by spengjie** [ktbyers/netmiko#3012]
Hi all,

Please find the brief session log and my analysis below.
```# send '\n'

******************************************************************************
* Copyright (c) 2004-2021 New H3C Technologies Co., Ltd. All rights reserved.*
* Without the owner's prior written consent,                                 *
* no decompiling or reverse-engineering shall be allowed.                    *
******************************************************************************

<switch>
<switch>
# send '\n'

<switch>
# send '\nscreen-length disable\n'

<switch>screen-length disable
<switch>
# send_command starts here
# send '\n'
# send '\n'

# send '\n'
<switch>
<switch>
# send 'display version\n'

<switch>  # a prompt received before getting the response of 'display version', so send_command returns here. If the response of 'display version' is received before the prompt, send_command will work fine.
# send '\n'
display version
# send '\n'
# send 'quit\n'
```
H3C Comware version: 7.1.070, Release 6555P01
Set global_cmd_verify to True can work around this issue. This issue is related to #1763.

**Comment by ktbyers** [comment]
Comware puts you in a bad position as they have no way to set the terminal width. This will cause cmd verify to fail for long commands.

Consequently, `global_cmd_verify` is disabled by default in Comware.

But then with cmd_verify disabled you can run into the above problems (i.e. slow devices that don't respond fast enough can lead Netmiko to match on the wrong prompt).

So we have two options:
1. Enable global_cmd_verify and live with the long command problem/errors (which users could potentially work around).
2. Disable global_cmd_verify and live with the slow device / match on wrong prompt problem (which users could potentially work around).

Fundamental issue is Comware should behave better with wide terminals.

**Comment by ktbyers** [comment]
I am going to close this as I don't see a solution for Comware.

The workaround is to set `global_cmd_verify=True`, but then there are problems with long commands if you do this (due to lack of terminal width on Comware).

If you see a solution or better solution, let me know.
