### ISSUE TITLE
not sure this is issue or not : timed out only 10 seconds.

### ISSUE THREAD

**Issue by pengembaratemporer** [ktbyers/netmiko#3014]
Dear all,

our script is always timed out only after 10 seconds, even if we change delay factor to 5. It should be 500 seconds right ? dont know what is missed.

also add conn_timeout just in case takes longer time to make ssh to host.

our script is very simple :

from netmiko import Netmiko
from netmiko import ConnectHandler 
import datetime
net_connect = ConnectHandler(device_type='cisco_ios', host="xxx", username='xxx', password='xxx', conn_timeout= 20)
cmd = "show running-config"
try:
    now = datetime.datetime.now()
    print(cmd, now)
    net_connect.send_command(cmd, delay_factor= 5)
except:
    now = datetime.datetime.now()
    print ('Device not reachable: ', now)
===

show running-config 2022-11-02 x:48:50.678980
Device not reachable:  2022-11-02 x:49:00.767195

we got around 15xxx lines of result. But it is not yet completed.

Thanks.

**Comment by ktbyers** [comment]
Try:

```python
# Set read_timeout to be the value you require plus some additional margin
net_connect.send_command(cmd, read_timeout=20)
```

**Comment by pengembaratemporer** [comment]
thanks, it works.

and sorry for huge font at script. I typed normally, including during copy paste the script. But i dont know the result is huge.
