### ISSUE TITLE
ssh_dispatcher.py ConnLogOnly() throwing exception

### ISSUE THREAD

**Issue by windmite** [ktbyers/netmiko#3017]
ssh_dispatcher.py lines 414-421

```
except NetmikoTimeoutException as e:
        if "DNS failure" in str(e):
            msg = f"Device failed due to a DNS failure, hostname {hostname}"
        elif "TCP connection to device failed" in str(e):
            msg = f"Netmiko was unable to reach the provided host and port: {hostname}:{port}"
            msg += f"\n\n{str(e)}"
        logger.error(msg)
        return None
```

Unfortunately I wasn't able to capture the string that brought me to this bug (and it was a timeout error I've only gotten a couple times so difficult to reproduce, I've added some code to grab it if it every happens again) but I'm assuming this needs to be something like:

```
except NetmikoTimeoutException as e:
        if "DNS failure" in str(e):
            msg = f"Device failed due to a DNS failure, hostname {hostname}"
        elif "TCP connection to device failed" in str(e):
            msg = f"Netmiko was unable to reach the provided host and port: {hostname}:{port}"
            msg += f"\n\n{str(e)}"
        else:
            msg = f"Unknown Timeout Error device timed-out: {hostname}:{port}"
            msg += f"\n\n{str(e)}"
        logger.error(msg)
```

I was getting 'msg' referenced before assignment because presumably neither of those strings was in str(e)  Big fan of ConnLogOnly() by the way.

**Comment by windmite** [comment]
Captured the exception string:
Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 15 seconds or larger.

**Comment by ktbyers** [comment]
@windmite Yeah, that msg referenced before assignment is a bug and needs fixed like you described.

Do you want to submit a PR on this?

**Comment by windmite** [comment]
I'm up for it if you'll excuse any mistakes I make in the process. I'll get some tutorials in tonight.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/3055
