### ISSUE TITLE
IPV6 support for SNMPDetect

### ISSUE THREAD

**Issue by kacem-expereo** [ktbyers/netmiko#3027]
Hi Team!
The snmp_autodetect.py providing netmiko's SNMPDetect do not seem to support ipv6 addresses passed to the hostname parameter.

snmp_autodetect uses UdpTransportTarget by default , which works for ipv4 only.
We can use Udp6TransportTarget for ipv6 instead of UdpTransportTarget.
I propose to identify the host ip version using ipaddress.ip_address().version from ipaddress library and to switch between UdpTransportTarget and Udp6TransportTarget accordingly.
I tested it successfully.
If the idea looks ok for you let me know and I will submit a PR.

Kindly,

**Comment by ktbyers** [comment]
@kacem-expereo Yeah, that sounds fine to me.

**Comment by kacem-expereo** [comment]
Thanks a lot :)
