### ISSUE TITLE
Last example - Terminal server and redispatch but with SSH

### ISSUE THREAD

**Issue by joaoneves10** [ktbyers/netmiko#3029]
Hi I'd love to see the last example but with SSH.

It uses the net_connect.telnet_login() method to handle the login process for the second and third connections but what if it used SSH?

Thanks!

**Comment by ktbyers** [comment]
@joaoneves10 You would basically use `write_channel()` and `read_channel()` to keep reading and writing the channel (and you would need to handle the authentication process).

Note, you might need to add `time.sleep(1)` (or some small sleep) after `write_channel()` operations, but before you read (as your program will be much faster than the remote device).

**Comment by joaoneves10** [comment]
Thanks! It is all working pretty well until now.
