### ISSUE TITLE
No Module Named 'netmiko.ssh_exception"

### ISSUE THREAD

**Issue by CootieCooter** [ktbyers/netmiko#3032]
Hi all, I am trying to run this automated script of python and netmiko to grab information from our switches. I'm pretty new to all this so bear with me. I am doing all my coding in Microsoft Visual Studio Code, and I have the Python extension installed as well as have Netmiko 4.1.2 installed. 

I try to run my code in visual studio code and I am error'd with "from netmiko.ssh_exception import NetMikoTimeoutException
ModuleNotFoundError: No module named 'netmiko.ssh_exception'"

I have 2 more lines following that imports SSHException and AuthenticationException from netmiko.ssh_exception. Where do I find or get this module???

![image](https://user-images.githubusercontent.com/61844397/202277657-6a5f2b28-181a-4124-952b-03d3eb647c62.png)

**Comment by ktbyers** [comment]
Change it to:

```python
from netmiko.exceptions import NetMikoTimeoutException
from netmiko.exceptions import AuthenticationException
from netmiko.exceptions import SSHException
```
