### ISSUE TITLE
extreme_ers / problem Press ENTER to continue

### ISSUE THREAD

**Issue by Microbe7777** [ktbyers/netmiko#3036]
Hello,

I have a problem with the device_type **extreme_ers** on an Extreme ERS 4950GTS-PWR+

I copied the return from debug mode

If I understand correctly he waits Press ENTER to continue

How to solve the problem ?

Thank for your help

----
### My script

`from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='netmiko_global.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

connection = ConnectHandler(host='xxx', username="xxx", password="xxx", device_type='extreme_ers')
connection.enable()

which_prompt = connection.find_prompt()
print(which_prompt)

connection.disconnect()`

----
### debug mode

INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
[2J[0m[0;0f[1;1H[2;1H[3;1H[4;1H[5;1H[6;1H[7;1H[8;1H[9;1H[10;1H[11;1H[12;1H[13;1H[14;1H[15;1H[14;1HEnter Ctrl-Y to begin.[16;3H****************************************************************************[17;3H*** Ethernet Routing Switch 4950GTS-PWR+    [17;76H***[18;3H*** Copyright (C) 1996-2021 Extreme Networks.  All rights reserved.      ***[19;3H*** This product is protected by one or more US patents listed           ***[20;3H*** at http://www.extremenetworks.com/patents along with                 ***[21;3H*** their foreign counterparts.                                          ***[22;3H***                                                                      ***[23;3H*** HW:13       FW:7.5.0.4   SW:v7.8.3.015[23;76H***[24;3H****************************************************************************[?25l
DEBUG:netmiko:Pattern found: ((?:sername|ssword|Ctrl-Y|(?m:[>#]\s*$))) 
[2J[0m[0;0f[1;1H[2;1H[3;1H[4;1H[5;1H[6;1H[7;1H[8;1H[9;1H[10;1H[11;1H[12;1H[13;1H[14;1H[15;1H[14;1HEnter Ctrl-Y
DEBUG:netmiko:write_channel: b'\x19'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: [2J[18;1H[2K[19;1H[2K[20;1H[2K
DEBUG:netmiko:read_channel: [2J[4;14HLast login: TUE 2022-11-22 16:41:26
[4;50Hfrom IP address x.x.x.x
[5;14HFailed retries since last login:  0
[10;0HPress ENTER to continue
[24;1H
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 

----
### login banner

  ****************************************************************************
  *** Ethernet Routing Switch 4950GTS-PWR+                                 ***
  *** Copyright (C) 1996-2021 Extreme Networks.  All rights reserved.      ***
  *** This product is protected by one or more US patents listed           ***
  *** at http://www.extremenetworks.com/patents along with                 ***
  *** their foreign counterparts.                                          ***
  ***                                                                      ***
  *** HW:13       FW:7.5.0.4   SW:v7.8.3.015                               ***
  ****************************************************************************

            Last login: TUE 2022-11-22 17:03:00 from IP address x.x.x.x
             Failed retries since last login:  0

Press ENTER to continue

**Comment by ktbyers** [comment]
Is this configurable? Can you disable this behavior on the device?

**Comment by Microbe7777** [comment]
I can disable the first part with command line  "banner disable" but not the one with Press Enter to continue.

**Comment by Microbe7777** [comment]
I'm new to Python, so this is going to be difficult for me. On an old Extreme model without **ENTER to continue**  Netmiko works very well...

Thank you

----

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 439, in __init__
    self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 444, in _open
    self.establish_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 1117, in establish_connection
    self.special_login_handler()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/extreme/extreme_ers_ssh.py", line 38, in special_login_handler
    new_data = self.read_until_pattern(pattern=pattern, read_timeout=25.0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '(?:sername|ssword|Ctrl-Y|(?m:[>#]\\s*$))' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
@Microbe7777 Can you test this proposed fix here:

https://github.com/ktbyers/netmiko/pull/3100

**Comment by ktbyers** [comment]
Should be fixed in the above referenced PR. That PR was merged into the Netmiko `develop` branch.
