### ISSUE TITLE
Issue with autodetect in Netmiko not working

### ISSUE THREAD

**Issue by kalium19** [ktbyers/netmiko#3037]
New to Python and Netmiko, so plz forgive me. 
I have an issue when I try to autodetect a cisco OS I am getting an abundance of error messages following and after reading the internet (all of it) and trying to resolve I still have issues. Here is what I am working with and I have tried different variations of the code but no luck all the way around. If i change the code from autodetect to cisco_ios or cisco_nxos the code runs fine and without an issue. I have many devices in my network that I want to set this up with and not have to have separate code builds or have to manually change the data each time. I am using 2fa to login. It has no impact on single device lookup only on autodetect Any thoughts are appreciated, i am sure i am missing something very obvious!!

Thank you in advance for any assistance.

```python
from netmiko import SSHDetect, ConnectHandler

device = {
         "device_type": "autodetect",
         "host": "10.1.1.1",
         "username": "name,
         "password": "password",
         "ssh_config_file": "~/.ssh/config",
}

guesser = SSHDetect(**device) # works
best_match = guesser.autodetect() # works
print(best_match)  # Name of the best device_type to use further - works
print(guesser.potential_matches)  # Dictionary of the whole matching result - works
# - Update the 'device' dictionary with the device_type
device["device_type"] = best_match 

print('Starting ConnectHandler')  #This is the last feedback I get prior to all the reference back to the backend scripts

connection = ConnectHandler(**device) # issue is stemming from here as I have put print commands in prior to this
# - used the "with ConnectHandler(**device) as connection:" command as well, without quotes!
# - once I get to this point i get that onslaught of error messages.  
print('Start Send Command lookup')
bob = connection.send_command('show interface status')
print(bob)
```

# (output)
cisco_ios
{'cisco_ios': 99}
Traceback (most recent call last):
netmiko/base_connection.py", line 1046, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
paramiko/client.py", line 450, in connect
    self._auth(
paramiko/client.py", line 781, in _auth
    raise saved_exception
paramiko/client.py", line 768, in _auth
    self._transport.auth_password(username, password)
paramiko/transport.py", line 1564, in auth_password
    return self.auth_handler.wait_for_response(my_event)
paramiko/auth_handler.py", line 259, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-ac.py", line 19, in <module>
    with ConnectHandler(**device) as connection:
netmiko/ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
netmiko/base_connection.py", line 439, in __init__
    self._open()
netmiko/base_connection.py", line 444, in _open
    self.establish_connection()
netmiko/base_connection.py", line 1083, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.exceptions.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: cisco_ios 10.1.1.1

Authentication failed.

**Comment by ktbyers** [comment]
So you are saying it works--if you don't use autodetect (i.e. hard-code in the device_type), but fails if you use autodetect?

Is your authentication system/two-factor locking things out due to the rapid connections (i.e. you are making two connections rapidly here)? The initial connection is likely still open when you try to connect again.

**Comment by kalium19** [comment]
Yes it works fine when I define the device_type. You are also correct on the issue being with 2fa. I hard coded a username and password and it worked out fine. I then created a second login to the device (having to put in two RSA codes) I get past the authentication issue. Debug says it even sees that my code returns that it is cisco_ios so that is good. Now I have to look at the code below to determine how to send command x if device_type == cisco_ios and same for cisco_nxos or other cisco device i will run into. Thank you for any suggestions and taking the time look at this code.
```python
from netmiko.ssh_autodetect import SSHDetect
from netmiko import (
    ConnectHandler,
    NetmikoTimeoutException,
    NetmikoAuthenticationException
)

device1 = {
    "device_type": "autodetect",
    "host": "10.200.110.221",
    "username": "b17088",
    "password": input('Enter Password: '),
    # "username": "cpautomation",
    # "password": "Ew39%891",
    "ssh_config_file": "~/.ssh/config",
}

guesser = SSHDetect(**device1)
best_match = guesser.autodetect()
print(best_match)  # Name of the best device_type to use further
print(guesser.potential_matches)  # Dictionary of the whole matching result
# Update the 'device' dictionary with the device_type
device1["device_type"] = best_match

device2 = {
    "device_type": best_match,
    "host": "10.200.110.221",
    "username": "b17088",
    "password": input('Enter Password: '),
    # "username": "cpautomation",
    # "password": "Ew39%891",
    "ssh_config_file": "~/.ssh/config",
}

net_connect = ConnectHandler(**device2)
# remaing code for correct IOS to be written below!!!
```
