### ISSUE TITLE
net_connect.commit() exception on IOS-XR 6.0.1

### ISSUE THREAD

**Issue by cameronff** [ktbyers/netmiko#304]
net_connect.commit() is expecting the prompt as

hostname#, 

while on ios-xr 6.0.1 (and other versions) a successful commit will return you to

Sat May 28 22:33:46.054 UTC
RP/0/RP0/CPU0:test(config)#

-- will attempt to submit a pull request to fix.

raises the following exception:

`In [16]: net_connect.commit()

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-16-2dd74e8a97fe> in <module>()
----> 1 net_connect.commit()

/usr/local/lib/python2.7/site-packages/netmiko/cisco/cisco_xr_ssh.pyc in commit(self, confirm, confirm_delay, comment, label, delay_factor)
     90         output = self.config_mode()
     91         output += self.send_command_expect(command_string, strip_prompt=False, strip_command=False,
---> 92                                            delay_factor=delay_factor)
     93         if error_marker in output:
     94             raise ValueError("Commit failed with the following errors:\n\n{0}".format(output))

/usr/local/lib/python2.7/site-packages/netmiko/base_connection.pyc in send_command_expect(self, *args, **kwargs)
    679     def send_command_expect(self, *args, **kwargs):
    680         """Support previous name of send_command method."""
--> 681         return self.send_command(*args, **kwargs)
    682
    683     @staticmethod

/usr/local/lib/python2.7/site-packages/netmiko/base_connection.pyc in send_command(self, command_string, expect_string, delay_factor, max_loops, auto_find_prompt, strip_prompt, strip_command)
    671         else:   # nobreak
    672             raise IOError("Search pattern never detected in send_command_expect: {0}".format(
--> 673                 search_pattern))
    674
    675         output = self._sanitize_output(output, strip_command=strip_command,

IOError: Search pattern never detected in send_command_expect: RP\/0\/RP0\/CPU0\:re\-me\-ved\-d\(config\)\#`

**Comment by ktbyers** [comment]
@cameronff 

On quick glance, I didn't see what was causing the issue here? It looks like Netmiko was expecting:

```
IOError: Search pattern never detected in send_command_expect: RP/0/RP0/CPU0:re-me-ved-d(config)#`
```

Are your config changes modifying the hostname?

**Comment by ktbyers** [comment]
@cameronff Also maybe try

```
.commit(delay_factor=2)
```

or

```
.commit(delay_factor=4)
```
