### ISSUE TITLE
cisco_ios_show_mac_address-table.textfsm template issue with only 1/10 Cisco C2960L

### ISSUE THREAD

**Issue by hiendinh114** [ktbyers/netmiko#3040]
**Hi Guys,
I got problem when was running my test script. It only worked in 9/10 devices which had the same model and firmware version.
This is my code:**
##########################
import pandas as pd
from netmiko import Netmiko
from openpyxl import load_workbook

net_connect = Netmiko(host= '10.0.9.191', username= 'admin', password= 'Cisco_test123', device_type='cisco_ios')
mac_table = net_connect.send_command("show mac address-table", use_textfsm=True)
#print(mac_table)
mac_data = {'mac':  [entry['destination_address'] for entry in mac_table],
            'interface': [entry['destination_port'] for entry in mac_table],
            'type': [entry['type'] for entry in mac_table],
            'vlan': [entry['vlan'] for entry in mac_table]
            }
df = pd.DataFrame(mac_data, columns=list(mac_data.keys()))
writer = pd.ExcelWriter('mac_table_v1.xlsx', engine='xlsxwriter')
df.to_excel(writer, '10.0.9.191')
writer.save()
print ('OK')

#############################
**When I run this script to got MAC Table of 10.0.9.191, it returned this Error:**
![image](https://user-images.githubusercontent.com/95537534/203734424-f8692fe0-86f3-4e82-b7b9-13216f7e9d2e.png)

Traceback (most recent call last):
  File "F:\Practice\Khao sat thiet bi mang\show_mac_v1.py", line 15, in <module>
    mac_table = net_connect.send_command("show mac address-table", use_textfsm=True)
  File "P:\Python\lib\site-packages\netmiko\utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "P:\Python\lib\site-packages\netmiko\base_connection.py", line 1729, in send_command
    return_val = structured_data_converter(
  File "P:\Python\lib\site-packages\netmiko\utilities.py", line 556, in structured_data_converter
    structured_output_tfsm = get_structured_data_textfsm(
  File "P:\Python\lib\site-packages\netmiko\utilities.py", line 379, in get_structured_data_textfsm
    output = _textfsm_parse(textfsm_obj, raw_output, attrs)
  File "P:\Python\lib\site-packages\netmiko\utilities.py", line 343, in _textfsm_parse
    tfsm_parse(raw_output, attrs)
  File "P:\Python\lib\site-packages\textfsm\clitable.py", line 282, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "P:\Python\lib\site-packages\textfsm\clitable.py", line 315, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "P:\Python\lib\site-packages\textfsm\parser.py", line 897, in ParseText
    self._CheckLine(line)
  File "P:\Python\lib\site-packages\textfsm\parser.py", line 946, in _CheckLine
    if self._Operations(rule, line):
  File "P:\Python\lib\site-packages\textfsm\parser.py", line 1026, in _Operations
    raise TextFSMError('State Error raised. Rule Line: %s. Input Line: %s'
textfsm.parser.TextFSMError: State Error raised. Rule Line: 77. Input Line:   12    1c69.7a0d.f4e4    STATIC      Gi0/36 
[Finished in 4.0s]

############################
**I have checked for several days and don't know what happened with the line "12    1c69.7a0d.f4e4    STATIC      Gi0/36"
I tried editing cisco_ios_show_mac_address-table.textfsm by removing the line "^. -> Error" and it worked.**
**I feel very confused.  The line "12    1c69.7a0d.f4e4    STATIC      Gi0/36" must match the "^\s*${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+${DESTINATION_PORT}$$" pattern.**

TYPE4
  ^\s*${VLAN}\s+${DESTINATION_ADDRESS}\s+${TYPE}\s+${DESTINATION_PORT}$$ -> Record
  ^-+\s+-+
  ^Displaying\s+entries
  ^Vlan\s+Mac Address\s+Type\s+Ports
  ^\s*$$
  ^Total\s+Mac\s+Addresses
  ^MultiCast\s+Entries -> End
  #^. -> Error

**Can someone explain it to me? Thank a lot :(**

**Comment by ktbyers** [comment]
@hiendinh114 Are you writing your own TextFSM template or are you using ntc-templates? If you are using ntc-templates, then you should create an issue there.

If it is your own textfsm template, then it is not really a Netmiko issue (output parsing is hard and TextFSM is hard as well).

**Comment by hiendinh114** [comment]
**mac_table = net_connect.send_command("show mac address-table", use_textfsm=True)**
@ktbyers I am using ntc-templates. Anyway I handled it by leaving out the "^ line. -> Error". I think it might not matter. @@
