### ISSUE TITLE
Nornir netmiko fails to  do pagination or if we send terminal length 0 with command does not understand the end of output

### ISSUE THREAD

**Issue by sktg84** [ktbyers/netmiko#3042]
team,
   I am encountering a use case where the show cdp neighbor detail is spaning across pages and if we use :

`results = nr.run(task=netmiko_send_command, command_string="show cdp neighbors detail", use_genie=True)`

It fails to paginate and gives error as below:

> DEBUG:netmiko:read_channel: 
> -------------------------
> Device ID: bgl16-cxlab-asw-oo16.cisco.com
> Entry address(es): 
>   IPv4 address: 10.105.8.175
> Platform: cisco WS-C3750X-48P,  Capabilities: Router Switch IGMP 
> Interface: MgmtEth0/RSP0/CPU0/0
> Port ID (outgoing port): GigabitEthernet1/0/47
> Holdtime : 127 sec
> 
> Version :
> Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.2(4.0.15)E, TEST ENGINEERING ESTG_WEEKLY BUILD, synced to  END_OF_FLO_ISP
> Technical Support: http://www.cisco.com/techsupport
> Copyright (c) 1986-2015 by Cisco Systems, Inc.
> Compiled Wed 17-Jun-15 12:36 by sasyamal
> 
> advertisement version: 1
> 
> -------------------------
> Device ID: NOD-MPL-RTR-157-76
> Entry address(es): 
>   IPv4 address: 192.168.12.0
> Platform: cisco ASR9K Series,  Capabilities: Router 
>  --More-- 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> ...
> DEBUG:netmiko:read_channel: 
> 
> 
> netmiko_send_command************************************************************
> * h1 ** changed : False ********************************************************
> vvvv netmiko_send_command ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
>     r = self.task(self, **self.params)
>   File "/usr/local/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
>     result = net_connect.send_command(command_string, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
>     return func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/netmiko/base_connection.py", line 1721, in send_command
>     raise ReadTimeout(msg)
> netmiko.exceptions.ReadTimeout: 
> Pattern not detected: '#' in output.
> 
> Things you might try to fix this:
> 1. Explicitly set your pattern using the expect_string argument.
> 2. Increase the read_timeout to a larger value.
> 
> You can also look at the Netmiko session_log or debug log for more information.
> 
> 
> 
> ^^^^ END netmiko_send_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Instead, if we use as : 
`results = nr.run(task=netmiko_send_command, command_string="terminal length 0\nshow cdp neighbors detail\n", use_genie=True)`
It fails to detect the prompt after correct full output:

> -------------------------
> Device ID: NCS55A2-1.cisco.com
> Entry address(es): 
>   IPv4 address: 192.168.21.3
> Platform: cisco NCS-5500,  Capabilities: Router 
> Interface: TenGigE0/1/0/8
> Port ID (outgoing port): TenGigE0/0/0/8
> Holdtime : 179 sec
> 
> Version :
>  6.6.3
> 
> advertisement version: 1
> 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: RP/0/RSP0/CPU0:NDL-MPL-PE-RTR-195#

**Error stack**

> 2022-11-29 09:52:01,412 - nornir.core.task -    ERROR -      start() - Host 'h1': task 'netmiko_send_command' failed with traceback:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
>     r = self.task(self, **self.params)
>   File "/usr/local/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
>     result = net_connect.send_command(command_string, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
>     return func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/netmiko/base_connection.py", line 1671, in send_command
>     new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
>   File "/usr/local/lib/python3.9/site-packages/netmiko/base_connection.py", line 1396, in command_echo_read
>     new_data = self.read_until_pattern(
>   File "/usr/local/lib/python3.9/site-packages/netmiko/base_connection.py", line 672, in read_until_pattern
>     raise ReadTimeout(msg)
> netmiko.exceptions.ReadTimeout: 
> 
> Pattern not detected: 'terminal\\ length\\ 0\\\nshow\\ cdp\\ neighbors\\ detail' in output.
> 
> Things you might try to fix this:
> 1. Adjust the regex pattern to better identify the terminating string. Note, in
> many situations the pattern is automatically based on the network device's prompt.
> 2. Increase the read_timeout to a larger value.
> 
> You can also look at the Netmiko session_log or debug log for more information.
> 
> 
> 
> netmiko_send_command************************************************************
> * h1 ** changed : False ********************************************************
> vvvv netmiko_send_command ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
>     r = self.task(self, **self.params)
>   File "/usr/local/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
>     result = net_connect.send_command(command_string, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
>     return func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/netmiko/base_connection.py", line 1671, in send_command
>     new_data = self.command_echo_read(cmd=cmd, read_timeout=10)
>   File "/usr/local/lib/python3.9/site-packages/netmiko/base_connection.py", line 1396, in command_echo_read
>     new_data = self.read_until_pattern(
>   File "/usr/local/lib/python3.9/site-packages/netmiko/base_connection.py", line 672, in read_until_pattern
>     raise ReadTimeout(msg)
> netmiko.exceptions.ReadTimeout: 
> 
> Pattern not detected: 'terminal\\ length\\ 0\\\nshow\\ cdp\\ neighbors\\ detail' in output.
> 
> Things you might try to fix this:
> 1. Adjust the regex pattern to better identify the terminating string. Note, in
> many situations the pattern is automatically based on the network device's prompt.
> 2. Increase the read_timeout to a larger value.
> 
> You can also look at the Netmiko session_log or debug log for more information.
> 
> 
> 
> ^^^^ END netmiko_send_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by sktg84** [comment]
For now i am by passing by using the send multi line : 

`results = nr.run(task=netmiko_multiline, commands=["terminal length 0","show cdp neighbors detail"])`

**Comment by sktg84** [comment]
Core issue of show cdp neighbors not paginating is still there.

**Comment by ktbyers** [comment]
I assume your Nornir platform is either `ios` or `cisco_ios`?

**Comment by ktbyers** [comment]
Here is the disable paging call:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_ios.py#L20

This happens just after login.

**Comment by ktbyers** [comment]
I am going to go ahead and close this. There is tot enough information to provide any other assistance on why the output paging is not properly being disabled on this device. On its face it doesn't look like a Netmiko issue (i.e. Netmiko for IOS driver disables the output paging as per above code reference).
