### ISSUE TITLE
Autodetect Issue - Cisco 9348 (NXOS)

### ISSUE THREAD

**Issue by AuthenticAMD** [ktbyers/netmiko#3043]
This is the only Cisco 9348 that I've ever seen so far that has an issue. Other Cisco 9348s autodetect correctly. Looking for troubleshooting tips on what is going on.

This is being run on an air gapped system, so I have to re-dictate the results.

When I look at the logs form a detailed output from netmiko on what is going on, it apparently runs the following commands in the order stated. For some reason the "show version" output doesn't match for "Cisco Nexus Operating System" or "NX-OS".  It is currently running 10.2.3.F, and trying to upgrade to 10.2.4.M. This worked for other 9348s, but this specific one is not autodetecting.

show version
show system
show system info
display version
show system package-info
get system status
show copyright
show inventory
uname -a
cat /etc/issue
show sys verison
software show

**Comment by AuthenticAMD** [comment]
Note, I wonder if it's a timing issue. This device response a little bit slower than the others for whatever reason (same building / network). This device takes around 3 seconds to respond to a "show version". While others take closer to 1.5 seconds.

**Comment by AuthenticAMD** [comment]
I think it is a timing thing and the expect part of the interaction is confused. The output below shows that a "show version" is executed, but it doesn't come back until after a "show system" is executed. Is there timers that can be tweaked to help with this?

The interesting section of the debug log is as follows:

*Paramiko SSH section*
*NX-OS login copyright*

im13-maz1db34-clf1#

im13-maz1db34-clf1#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show version\n'
DEBUG:netmiko:read_channel: show version

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'show system\n'
DEBUG:netmiko:read_channel: Cisco Nexus Operating System (NX-OS) Software...

**Comment by AuthenticAMD** [comment]
I rebooted the device and symptom still exists. Manually upgraded to 10.2.4 and same thing.

**Comment by AuthenticAMD** [comment]
It's worth noting that this only happens during autodetect. If I force the device type to 
cisco_nxos", I do not have problems with commands coming back correctly for send/expect.

**Comment by ktbyers** [comment]
@AuthenticAMD 

Can you try this fix and see if it works?

https://github.com/ktbyers/netmiko/pull/3056

**Comment by AuthenticAMD** [comment]
Unfortunately no change in behavior. Output of debug log is the same.

**Comment by AuthenticAMD** [comment]
@ktbyers Confirmed your recent commit #3074 fixed my issue!
