### ISSUE TITLE
Access with Netmiko in OLT MA5800 (Huawei Integrated Access Software)

### ISSUE THREAD

**Issue by RecsC** [ktbyers/netmiko#3044]
@ktbyers @tbotnz @MrPaulAR 
Any idea how I can access an OLT MA5800 (Huawei)!!??

I'm trying to access a huawei device (OLT MA5800) but I have the timeout error according to the logg below.
![image](https://user-images.githubusercontent.com/68303383/205048826-50d43b35-7655-4842-bd81-9bbb1779672e.png)

Note that for Huawei ATN 910C-G routers, I can access and execute commands with the Login below(in the same way that I try to access the OLT).
                huawei_ios = {
                                'device_type': 'huawei', 
                                'host': IP, 
                                'username': Username, 
                                'password': Password, 
                                'global_delay_factor': 0.1
                                }
net_connect = ConnectHandler(**huawei_ios)  
                

**Normal access via ssh:**
![image](https://user-images.githubusercontent.com/68303383/205048381-2a64ff35-795b-43aa-a7bf-f6b16c0eae39.png)

**Comment by ktbyers** [comment]
Did you try the `huawei_olt` device type?

**Comment by RecsC** [comment]
Hi @ktbyers , 
Thank you for your availability and help.

I changed it to "Huawei_OLT" and I see that I can now access it. In the image below marked in green I see the question that the OLT asks when accessing the element. But now I have an exception error there marked in red.

Summary: when accessing the equipment, we must accept the "YES" or "Y" statement, otherwise we cannot execute/send any command.(You can also see it in the image above)
How can I send the "Y" when sending the ConnectHandler.

I need to send a yes and have full access


![image](https://user-images.githubusercontent.com/68303383/210170418-131cd9ed-9562-4d57-a263-5ddfd9b8ee85.png)

**Comment by ktbyers** [comment]
Does it do this every time or only the first time you login?

Can you disable this behavior via configuration?

Someone would need to write a special handler to handle this. This device has something similar:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/calix/calix_b6.py#L29

Ping me in a week or so and I might see if I can do it.

**Comment by RecsC** [comment]
Does it do this every time or only the first time you log in?
**Answer:** Yes.

Can you disable this behavior via configuration?
**Answer:** It can be removed, but as good practice it should remain. It is hereby accepted the statements and terms above the above law.

Ping me in a week or so and I might see if I can do it.
**Answer:** In a week and a half to two weeks I'll give you a signal again.

I reiterate: I really appreciate your dedication and help, with that many, many more processes will be automated, similar to those made with CISCO equipment.

**Comment by RecsC** [comment]
hi @ktbyers any news for me!?

**Comment by ktbyers** [comment]
I didn't do anything on this yet. Probably won't get to it for two more weeks.

**Comment by ktbyers** [comment]
Reminder to myself to work on this.

**Comment by ktbyers** [comment]
@RecsC Can you test this proposed fix?

https://github.com/ktbyers/netmiko/pull/3099

**Comment by ktbyers** [comment]
Should be fixed in the referenced PR which I merged into the `develop` branch.

**Comment by RecsC** [comment]
Hi @ktbyers,
thank you very much for your help and availability.

I saw your proposed solution #3099, but I'm still very lost. Please help me better with the shared code.
- Is the class to be used?
         * If yes, is it just import?
         * What is the parameter to be passed?

Or do I just need to upgrade Netmiko?


Let's imagine for the login code below how to incorporate the created solution(https://github.com/ktbyers/netmiko/pull/3099):

from netmiko import ConnectHandler

net_connect = ConnectHandler(
    device_type="huawei_olt",
    host="10.10.10.10",
    username="admin",
    password="password",
)
output = net_connect.send_command("display interface description")
print(output) 



I look forward to feedback,
Thanks.
