### ISSUE TITLE
I want to log in to the network device for batch pings

### ISSUE THREAD

**Issue by love01211** [ktbyers/netmiko#3045]
I want to log in to the network device for batch ping. I found the send file in the reference document_ Multiline function, but it only pings one by one. I want to ping in batches at the same time. Can you help me？

**Comment by ktbyers** [comment]
@love01211 You can log in multiple times to the same device using threads or multiple proceses and then send your separate ping commands.

If you only have a single connection, then you likely would have to do them one after the other.
