### ISSUE TITLE
net_connect.send_config_set()

### ISSUE THREAD

**Issue by BENBUNOR** [ktbyers/netmiko#3051]
TypeError: BaseConnection.send_config_set() takes from 1 to 2 positional arguments but 3 were given

**Comment by BENBUNOR** [comment]
keep getting this error

**Comment by BENBUNOR** [comment]
> @BENBUNOR Can you show a larger section of your code and the full exception stack trace?

from netmiko import ConnectHandler
from getpass import getpass
import time
import os
 
 
cisco1 = {
    "device_type": "cisco_ios",
    "host": "10..0.0.0",
    "username": "admin",
    "password": getpass(),
    "ssh_config_file": "~/.ssh/ssh_config",
}
 

 

with ConnectHandler(**cisco1) as net_connect:
    output = net_connect.send_command('sh ntp ass', use_textfsm=True)
    print(output)
    net_connect.enable()
    net_connect.config_mode()
    #print("Connected Successfully")
 
P = '192.168.1.1'
S = '192.168.1.2'
 

if output == P and output [1] == S: #with P as primary NTP and S as Secondary NTP
    print ('Both Primary and Secondary NTP are present') # if both are present in the config, print it  int the output
elif output == None and output == S: #if primary is not present and secondary is present, print it out.
    output1 = net_connect.send_config_set('ntp server 192.168.1.1', 'ntp peer 192.168.1.2') # where this is absent, implement the config.
    print(output, output1)
elif output [1] == P and output [1] == None: # where secondary server is not present, implement the config
    output2 = net_connect.send_config_set('conf t', 'ntp server 192.168.1.2')
    print(output, output2)
elif output  == None and output  == None: # if none of them is present, implement both
   output3 = net_connect.send_config_set('conf t', 'ntp server 192.168.1.1', 'ntp peer192.168.1.2')
   print(output, output3)
#else:
    #print('None of the condition exist')

**Comment by ktbyers** [comment]
Your `send_config_set()` statements are invalid.

If you are passing in more than one command, you should pass it in as a list of commands.

So this:

```
output1 = net_connect.send_config_set('ntp server 192.168.1.1', 'ntp peer 192.168.1.2')
```

Should instead be:

```
# Configuration commands enclosed in a list.
output1 = net_connect.send_config_set(['ntp server 192.168.1.1', 'ntp peer 192.168.1.2'])
```


Also, you shouldn't need to do the `conf t`, Netmiko should do that automatically as part of `send_config_set()`

**Comment by BENBUNOR** [comment]
> Your `send_config_set()` statements are invalid.
> 
> If you are passing in more than one command, you should pass it in as a list of commands.
> 
> So this:
> 
> ```python
> output1 = net_connect.send_config_set('ntp server 192.168.1.1', 'ntp peer 192.168.1.2')
> ```
> 
> Should instead be:
> 
> ```python
> # Configuration commands enclosed in a list.
> output1 = net_connect.send_config_set(['ntp server 192.168.1.1', 'ntp peer 192.168.1.2'])
> ```
> 
> Also, you shouldn't need to do the `conf t`, Netmiko should do that automatically as part of `send_config_set()`

now i am getting this result:

 output1 = net_connect.send_config_set(['ntp server 192.168.1.1', 'ntp peer 192.168.1.2']) # where this is absent, implement the config.
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 2172, in send_config_set
    output += self.config_mode()
              ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/cisco_base_connection.py", line 49, in config_mode
    return super().config_mode(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 1999, in config_mode
    if not self.check_config_mode():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/cisco/cisco_ios.py", line 55, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/cisco_base_connection.py", line 41, in check_config_mode
    return super().check_config_mode(check_string=check_string, pattern=pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 1972, in check_config_mode
    self.write_channel(self.RETURN)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 97, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    func(self, out_data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/base_connection.py", line 537, in write_channel
    self.channel.write_channel(out_data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/netmiko/channel.py", line 74, in write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed

**Comment by ktbyers** [comment]
@BENBUNOR It looks like your code (at least as shown above) is not indented properly. You are ending the `with` block. Once you end the `with` block, your SSH-connection to the device will be closed.

**Comment by BENBUNOR** [comment]
So you want me to remove the with? or?

**Comment by ktbyers** [comment]
All of this code should be indented inside your `with` statement:

```python
P = '192.168.1.1'
S = '192.168.1.2'
 
if output == P and output [1] == S: #with P as primary NTP and S as Secondary NTP
    print ('Both Primary and Secondary NTP are present') # if both are present in the config, print it  int the output
elif output == None and output == S: #if primary is not present and secondary is present, print it out.
    output1 = net_connect.send_config_set('ntp server 192.168.1.1', 'ntp peer 192.168.1.2') # where this is absent, implement the config.
    print(output, output1)
elif output [1] == P and output [1] == None: # where secondary server is not present, implement the config
    output2 = net_connect.send_config_set('conf t', 'ntp server 192.168.1.2')
    print(output, output2)
elif output  == None and output  == None: # if none of them is present, implement both
   output3 = net_connect.send_config_set('conf t', 'ntp server 192.168.1.1', 'ntp peer192.168.1.2')
   print(output, output3)
#else:
    #print('None of the condition exist')
```

**Comment by BENBUNOR** [comment]
with: 
      P = '192.168.1.1'
     S = '192.168.1.2'
 
    if output == P and output [1] == S: #with P as primary NTP and S as Secondary NTP
    print ('Both Primary and Secondary NTP are present') # if both are present in the config, print it  int the output
    elif output == None and output == S: #if primary is not present and secondary is present, print it out.
    output1 = net_connect.send_config_set('ntp server 192.168.1.1', 'ntp peer 192.168.1.2') # where this is absent, implement 
    the config.
    print(output, output1)
    elif output [1] == P and output [1] == None: # where secondary server is not present, implement the config
    output2 = net_connect.send_config_set('conf t', 'ntp server 192.168.1.2')
    print(output, output2)
    elif output  == None and output  == None: # if none of them is present, implement both
   output3 = net_connect.send_config_set('conf t', 'ntp server 192.168.1.1', 'ntp peer192.168.1.2')
   print(output, output3)
     #else:
         #print('None of the condition exist')

like this?

**Comment by ktbyers** [comment]
```python
from netmiko import ConnectHandler
from getpass import getpass
import time
import os
 
cisco1 = {
    "device_type": "cisco_ios",
    "host": "10..0.0.0",
    "username": "admin",
    "password": getpass(),
    "ssh_config_file": "~/.ssh/ssh_config",
}
 
with ConnectHandler(**cisco1) as net_connect:
    output = net_connect.send_command('sh ntp ass', use_textfsm=True)
    print(output)
    net_connect.enable()
    net_connect.config_mode()
    #print("Connected Successfully")
 
    P = '192.168.1.1'
    S = '192.168.1.2'
     
    if output == P and output [1] == S: #with P as primary NTP and S as Secondary NTP
        print ('Both Primary and Secondary NTP are present') # if both are present in the config, print it  int the output
    elif output == None and output == S: #if primary is not present and secondary is present, print it out.
        output1 = net_connect.send_config_set('ntp server 192.168.1.1', 'ntp peer 192.168.1.2') # where this is absent, implement the config.
        print(output, output1)
    elif output [1] == P and output [1] == None: # where secondary server is not present, implement the config
        output2 = net_connect.send_config_set('conf t', 'ntp server 192.168.1.2')
        print(output, output2)
    elif output  == None and output  == None: # if none of them is present, implement both
       output3 = net_connect.send_config_set('conf t', 'ntp server 192.168.1.1', 'ntp peer192.168.1.2')
       print(output, output3)
    #else:
        #print('None of the condition exist')
```

**Comment by BENBUNOR** [comment]
it worked kirk, it configured the ntp for me. then i ran the script again after the first config was successful, this time it didnt configure it cos of the conditionals. 
say i want to do a multiline show like:
    output = net_connect.send_multiline('sh ntp ass', 'sh clock det'), how do i do it? cos i want to. modify the script to check for timezone too, if not, the script should configure it.

**Comment by ktbyers** [comment]
Just run `send_command()` multiple time and capture the output from the two separate commands.

**Comment by ktbyers** [comment]
Okay, did you test your code to see if your logic is correct--i.e. are you even trying to configure the timezone (is send_config_set()) being executed?

**Comment by BENBUNOR** [comment]
here is what i have done:

from netmiko import ConnectHandler
from getpass import getpass
import time
import os


 
cisco1 = {
    "device_type": "cisco_ios",
    "host": "10.0.0.0",
    "username": "adm",
    "password": getpass(),
    "ssh_config_file": "~/.ssh/ssh_config",
}
 
with ConnectHandler(**cisco1) as net_connect:
    output = net_connect.send_command('sh ntp ass')
    outputd = net_connect.send_command('sh clock det')
    print(output)
    print(outputd)
    net_connect.enable()
    net_connect.config_mode()
    #print("Connected Successfully")

    P = '134.174.17.6'
    S = '134.174.141.2'
    EST = 'clock timezone est -5'
    EDT = 'clock summer-time edt recurring'
     
    if output == P: 
        print ('Primary NTP is present')
    elif output != P: 
        output1 = net_connect.send_config_set('ntp server 192.168.1.1') # where ntp server  is absent, implement the config.
        print(output, output1)
    if output == S:
        print('Secondary NTP is present')
    elif output != S:
        output2 = net_connect.send_config_set('ntp peer 192.168.1.2')
        print(output, output2)
    if outputd == EST:
        print('EST time correct')
    elif outputd != EST:
        output3 = net_connect.send_config_set('clock timezone est -5')
        print(outputd, output3).


when i ran this, the script did the confg is, but when i ran it the second time, it, reconfigured it again. and my aim of the script is to check if the config is there, if it is not there, it should implement it. but when the configs are there, the script should do nothing.

**Comment by ktbyers** [comment]
Have you looked at your output and tested your logic to see why it is failing?

**Comment by BENBUNOR** [comment]
here is the output:

address         ref clock     st  when  poll reach  delay  offset    disp
+~192.168.1.1    206.82.16.3       3    48    64  377    -0.1    6.32     0.5
*~192.168.1.2     216.197.228.230   2    28    64  377    -0.1    8.05     0.6
 * master (synced), # master (unsynced), + selected, - candidate, ~ configured
13:09:03.944 est Tue Dec 13 2022
Time source is NTP

+~192.168.1.1    206.82.16.3       3    48    64  377    -0.1    6.32     0.5
*~192.168.1.2     216.197.228.230   2    28    64  377    -0.1    8.05     0.6
 * master (synced), # master (unsynced), + selected, - candidate, ~ configured ntp server 192.168.1.1
Test-Lab(config)#end
Test-Lab#

      address         ref clock     st  when  poll reach  delay  offset    disp
+~192.168.1.1    206.82.16.3       3    48    64  377    -0.1    6.32     0.5
*~192.168.1.2     216.197.228.230   2    28    64  377    -0.1    8.05     0.6
 * master (synced), # master (unsynced), + selected, - candidate, ~ configured configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
Test-Lab(config)#ntp peer 192.168.1.2

Test-Lab#
13:09:03.944 est Tue Dec 13 2022
Time source is NTP configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
Test-Lab(config)#clock timezone est -5
Test-Lab(config)#end

if i run it again, i will get the same output. it will reconfigure both the peer and the timeszone again
