### ISSUE TITLE
Arista EOS terminal length issue

### ISSUE THREAD

**Issue by HeikkiLavaste** [ktbyers/netmiko#3054]
Hi, 

I've the following issue. I have a limited read-only account to our Arista boxes. 
When I try SSH to the devices with netmiko, the connection fails as I have no authorization to run "terminal length" command. 
Is there a way to change when command is sent to the the device? 

devname-1#terminal width 511

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: % Authorization denied for command 'terminal width 511'

Br,
Heikki

**Comment by ktbyers** [comment]
You can use the `generic` driver:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/ssh_dispatcher.py#L208

This should get you an SSH connection, but then you will run into issues trying to execute any command that pages the output (and possibly wide commands will cause issues as well).

**Comment by HeikkiLavaste** [comment]
Cool. Thanks. I'll give that a  go.
