### ISSUE TITLE
Slack Invite Link is Broken

### ISSUE THREAD

**Issue by alphabet5** [ktbyers/netmiko#3057]
The link in the [README](https://github.com/ktbyers/netmiko/blob/develop/README.md) is currently broken.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/1178293/208755761-6932e27f-1576-4cdb-a589-c4d31f93e723.png">

**Comment by ktbyers** [comment]
@schautwb can you help @alphabet5  on this.

Yes, Slack's permanent invite is not so permanent.

**Comment by schautwb** [comment]
@alphabet5 here is the Slack invite link: [https://join.slack.com/t/pynet/shared_invite/zt-1mc0vzrcg-MBPkEm8XmAFIzCsNlZGdig](url)
