### ISSUE TITLE
HP procurve switch prep session

### ISSUE THREAD

**Issue by caibitim** [ktbyers/netmiko#306]
Hi,

I'm working on getting the configuration from HP procurve switch. However, what I just found is if the HP procruve switches are in the stack, there will be another screen that we need to skip. Here is an example:

 Stack Members

  SN MAC Address   System Name      Device Type           Status
  -- ------------- ---------------- --------------------- ----------------------
  0  xxxxxxxxxxxxxxxxxxxxxxx       ProCurve Switch      Commander Up
  1  yyyyyyyyyyyyyyyyyyyyyy       ProCurve Switch      Member Up
Enter switch number to connect to or <CR>:

Basically, we need to send another '\n'. I've added it to hp_procurve_ssh.py to resolve the issue. An extra enter will not cause any other issue for normal switch but would help the stack.

Here is the code that I use, and it works fine for hp standalone switch and the stack.

    def session_preparation(self):
        """
        Prepare the session after the connection has been established.
        Procurve uses - 'Press any key to continue'
        """
        delay_factor = self.select_delay_factor(delay_factor=0)
        time.sleep(1 * delay_factor)
        self.write_channel("\n")
        time.sleep(1 * delay_factor)
        self.write_channel("\n")
        time.sleep(1 * delay_factor)

**Comment by ktbyers** [comment]
@caibitim Okay, let me regression test it...sounds reasonable.

**Comment by ktbyers** [comment]
@caibitim Okay, here is a fix for it. It is in the dev_1_2 branch. 

https://github.com/ktbyers/netmiko/commit/a818427216f71272ae8410f63927db4891dbe39e
