### ISSUE TITLE
check_config_mode is very slow by default

### ISSUE THREAD

**Issue by jonglezb** [ktbyers/netmiko#3062]
I have been chasing a severe performance regression between Netmiko 3.X and 4.X: on a Dell Force10 device, a basic `send_config_set` with several commands was taking 4 seconds with Netmiko 3.X. Now, with Netmiko 4.1.1, it takes as much as 14 seconds.

I tracked it down to mostly `check_config_mode`: by default, no pattern is specified, so it ends up calling `read_channel_timing`, which has a fixed `sleep` of 2 seconds at the end. Since `check_config_mode` is called multiple times, these 2 seconds of delay add up.

I see several ways to fix it:

1) **straightforward fix:** add a pattern to `check_config_mode` for the devices I'm interested in
2) **generic fix:** add a default pattern for all devices, `[>#]` should be a reasonable default. Device-specific code can override the pattern if needed (and in fact, many devices already do)
3) **more complex fix:** rework `check_config_mode` so that it uses the existing prompt pattern. Not sure this is really worth it, it'll probably be more fragile

I would like to send a patch with solution 2), does that sound good? Otherwise I'll go with solution 1) for the few device models I have access to.

**Comment by jonglezb** [comment]
Here is a patch with solution 1 (device-specific) as a first step: #3069

**Comment by ktbyers** [comment]
This was fixed with PR #3069

**Comment by ktbyers** [comment]
@jonglezb Thanks for the contribution.
