### ISSUE TITLE
Paramiko   Errno 11001 getaddrinfo failed

### ISSUE THREAD

**Issue by DOTTRAM** [ktbyers/netmiko#3064]
Hello! I have some proble when i try use this code. So I get error like : "Errno 11001 getaddrinfo failed"
I have  acess for all my devices by SSH and ICMP(ping).  How  i can fix this?

```
> import time
> from datetime import datetime
> import paramiko
> 
> login = 'ciscogtkz'
> passw = 'Jkbvgbflf80'
> 
> client = paramiko.SSHClient()
> client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
> file = open('device.txt', 'r')
> 
> for line in file:
>     timestamps = str(datetime.now())
>     print('Timestamp:', timestamps)
> 
>     def connector():
>         print('Connecting to IP:' + line)
>         client.connect(line, username=login, password=passw, look_for_keys=False, allow_agent=False)
> 
>     try:
>         connector()
>         with client.invoke_shell() as ssh:
>              ssh.send('enable\n')
>              ssh.send('terminal length 0\n')
>              ssh.send('show running-config\n')
>              time.sleep(10)
>              result = ssh.recv(10000).decode("utf-8")
>              fo = open(line.strip() + '.txt', 'w')
>              fo.writelines(result)
>              fo.close()
> 
>     except Exception as e:
>         error_log = str(e)
>         print(error_log + '\n')
> 
> file.close()
```

**Comment by ktbyers** [comment]
@DOTTRAM Why are you posting this here i.e. it doesn't have anything to do with Netmiko?

**Comment by DOTTRAM** [comment]
OK. Where can I run this question?

**Comment by kacem-expereo** [comment]
@DOTTRAM  it seems you use paramiko , but your problem is more related to your python code than the library. You can try forums or IT slacks/discords channels next time.

replace this 
`client.connect(line, username=login, password=passw, look_for_keys=False, allow_agent=False)`
with
`client.connect(line.strip(), username=login, password=passw, look_for_keys=False, allow_agent=False)`

that should do the trick

**Comment by DOTTRAM** [comment]
> 

Its working. Thank you so much
