### ISSUE TITLE
Newly added users on Cisco FTD require password change on login

### ISSUE THREAD

**Issue by TwoFace24** [ktbyers/netmiko#3065]
Hello. I'm trying to add users to Cisco FTD automatically using paramiko. Adding Users by "configure user add" works fine but if a newly added user logs in to the device he needs to enter a new password instantly and the pattern of the base prompt does not appear. Any suggestions how to fix this?

**Output from FTD:**
Cisco Firepower Extensible Operating System (FX-OS) v2.10.1 (build 175)
Cisco Firepower 1140 Threat Defense v7.0.1 (build 84)

Hello testuser. You must change your password.
Enter new password: 
Confirm new password:  exit

**Error**
`netmiko.exceptions.ReadTimeout:

Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.`

**Comment by ktbyers** [comment]
@TwoFace24 You would probably need to modify the Cisco FTD driver to handle that case.

The pattern of the code would probably be similar to this:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/fortinet/fortinet_ssh.py#L29-L34

i.e. you would read and 'new password' would be in the output (or the prompt would be in the output). In the case of "password" in the output, you would need to set the new password (basically use a conditional to detect this and then send the new password).

**Comment by ktbyers** [comment]
Another solution would be to use the `generic` device_type and `write_channel` and `read_channel` to handle the setting of the new password on the first login.

After you do this, disconnect and then login normally (with Netmiko)
