### ISSUE TITLE
Issues with ConnectHandler on netmiko 4.1.2  to Huawei platforms.

### ISSUE THREAD

**Issue by Higgigs** [ktbyers/netmiko#3071]
Python 3.9.7
Python 3.8.2 
Netmiko 4.1.2 

There is an intermittent issue when trying to connect via netmiko to the following huawei platforms: 

S5320  
S6320  

Some times it works fine and I face no issues (20% of the times) and other times I am getting back one of the following exceptions: 

Please see picture attached. 
<img width="868" alt="image" src="https://user-images.githubusercontent.com/121892742/210419212-edb840ce-35ce-4cd1-84d1-ddf3ef0f3b0c.png">

Please note that the same piece of code works fine for other paltforms and huawei devices such as: 

ATN 
CE6855

**Comment by aztec102** [comment]
@Higgigs I don't know what happened in the source code, but I also experienced certain problems. Therefore, I still advise you to use version == 3.4.0

**Comment by ktbyers** [comment]
@Higgigs Can you provide the full stack trace for one of the errors that you are running into. I need to see the actual lines of code in the stack trace where the error is happening.

I would just pick one of the above cases and then I can look at that.

**Comment by Higgigs** [comment]
The issue was caused due to huge delay on the device. Using "except_string" parameter it fixed the issue.
