### ISSUE TITLE
Send multiple operations commands to Palo Alto firewall

### ISSUE THREAD

**Issue by rahulnangare007** [ktbyers/netmiko#3076]
Hello,

I am using Netmiko to send "test vpn" command to PA firewalls using send_command module. I want to send multiple commands at a time. I am trying to find way to do that. Is there any way I can do that?

**Comment by namiles** [comment]
Hi @rahulnangare007.

You can use send_command_set() is send multiple commands

https://pyneng.readthedocs.io/en/latest/book/18_ssh_telnet/netmiko.html#send-config-set

**Comment by namiles** [comment]
Hey @rahulnangare007,

If they are configuration commands, you can use send_command_set() to send multiple commands in configuration mode. Otherwise you will likely need to use send_command() in a loop

**Comment by ktbyers** [comment]
@rahulnangare007 Can you show from the Palo Alto CLI what you are trying to do?

That will probably show us the patterns that you could use to accomplish this via Netmiko.
