### ISSUE TITLE
Syntax Error: unexpected argument (set and tmsh)

### ISSUE THREAD

**Issue by michaelc0n** [ktbyers/netmiko#308]
I am using netmiko with device_type 'f5_ltm' and noticed in the logs the below when pushing config. changes.  I am connecting via "net_connect = ConnectHandler(**f5ssh)" and using "net_connect.send_command" to send commands.  Not sure if this is an issue or user error, but it appears the commands "tmsh" and "set" are throwing the error.  My user "adminx" is automatically dropped into "tmsh" not "bash", could this be the issue?  Thanks!

Error in log:
pid=4005 user=adminx folder=/Common module=(tmos)# status=[Syntax Error: unexpected argument "tmsh"] cmd_data=tmsh:
pid=4005 user=adminx folder=/Common module=(tmos)# status=[Syntax Error: unexpected argument "set"] cmd_data=set:
 sshd(pam_audit): user=adminx(adminx) partition=[All] level=Administrator tty=ssh:

**Comment by ktbyers** [comment]
@michaelc0n The F5 code does the following on login:

```
 13         delay_factor = self.select_delay_factor(delay_factor=0)
 14         self.set_base_prompt()
 15         self.disable_paging(command="\nset length 0\n")
 16         time.sleep(1 * delay_factor)
 17         self.tmsh_mode()
 18         self.set_base_prompt()
```

It is expecting to be at the shell prompt and then to enter tmsh.

Note, the F5 Netmiko driver hasn't had much testing so let me know what you find. 

Also I am open to better ways of handling the login (i.e. we could probably detect if we are at the shell or in tmsh).

**Comment by ktbyers** [comment]
@michaelc0n Did you resolve this issue from your side?

**Comment by ktbyers** [comment]
No response on issue...so closing.
