### ISSUE TITLE
Cannot login to some Cisco XR (version 6.5.3) devices via telnet 

### ISSUE THREAD

**Issue by gifino75** [ktbyers/netmiko#3083]
Hello,

I am experiencing an odd issue with Netmiko 4.1.2 . This is the configuration I am using, which works with other XR devices without issues, and it does not seems to be version related (i.e., it works on other 6.5.3 devices)

```
def create_conn(host) :
	# define host connection properties for Netmiko consumption
		defhost = {                 
		"device_type": "cisco_xr_telnet", 
		"host": host,
		"username": "lala",
		"password": "lala",     
		"conn_timeout": 10,
		}
		conn = ConnLogOnly(**defhost)       # try establishing connection, if ok return conn obj
		if conn is None:
			print("Cannot extablish connection to " + host)
			sys.exit('exiting. Error logged in netmiko.log')
		else:
			return conn
```

I turned on the debugger/logging and obtained the following

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: Username: 

Username: 

Username: 

Username: 

ERROR:netmiko.ssh_dispatcher:Authentication failure to: 10.255.254.253:23 (cisco_xr_telnet)

Apparently it's not matching Username. I tried "default_enter": "\r" in hope it would change the behavior by sending only \r, but I must have misunderstood that parameter because it still sends \r\n. 

As it seems similar to issue #1970, I also tried fast_cli=False argument by adding it to the dictionary config above ( 'fast_cli':False), but it didn't help.

Anybody else got this issue or found a workaround for similar issues? 
Thanks!

**Comment by gifino75** [comment]
Tried to modify and use ConnectHandler vs ConnLogOnly and adding fast_cli, this time I get a traceback

	defhost = {                 # we define the properties of jumphost for Netmiko consumption
		"device_type": "cisco_xr_telnet",  # we must always pass the device type to netmiko, read netmiko docs
		"host": host,
		"username": "sptac",
		"password": "T0rn4Do",      # note that session logging has a unicode bug
		"conn_timeout": 10,
		"fast_cli": False
		}
		conn = ConnectHandler(**defhost) 
		#conn = ConnLogOnly(**defhost)       # try establishing connection, if ok return conn obj
		if conn is None:
			print("Cannot extablish connection to " + host)
			sys.exit('exiting. Error logged in netmiko.log')
		else:
			return conn

######

Traceback (most recent call last):
  File "xr_get_shows.py", line 95, in <module>
    mainflow()
  File "xr_get_shows.py", line 84, in mainflow
    get_shows(myip, host, shows_2_do)
  File "xr_get_shows.py", line 51, in get_shows
    myconn = create_conn(host)
  File "xr_get_shows.py", line 23, in create_conn
    conn = ConnectHandler(**defhost) 
  File "/home/ciscouser/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/ciscouser/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 439, in __init__
    self._open()
  File "/home/ciscouser/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 444, in _open
    self.establish_connection()
  File "/home/ciscouser/.local/lib/python3.8/site-packages/netmiko/cisco/cisco_xr.py", line 11, in establish_connection
    super().establish_connection(width=width, height=height)
  File "/home/ciscouser/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1034, in establish_connection
    self.telnet_login()
  File "/home/ciscouser/.local/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 191, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.exceptions.NetmikoAuthenticationException: Login failed: 10.255.254.253

**Comment by ktbyers** [comment]
Maybe try setting `global_delay_factor: 2` (or 4)?

**Comment by gifino75** [comment]
Hello,
yes I tried with a global delay factor of 6 and it didn't help, even for that particular case in which Username is matched, but then Password isn't

```
defhost = {                 # we define the properties of jumphost for Netmiko consumption
		"device_type": "cisco_xr_telnet",  # we must always pass the device type to netmiko, read netmiko docs
		"host": host,
		"username": "sptac",
		"password": "T0rn4Do",  
		"global_delay_factor": 6,    
		"conn_timeout": 10,
		}
```

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

Username: 


DEBUG:netmiko:write_channel: b'lala\r'
DEBUG:netmiko:read_channel: Username: 


DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
Username: lala

Password: 
Request Denied


ERROR:netmiko.ssh_dispatcher:Authentication failure to: 10.3.3.182:23 (cisco_xr_telnet)

**Comment by gifino75** [comment]
If it is any help, I just tried on a NCS540 running eXR 6.5.3 and it works well :-( I am at a loss. The others were asr9010.
It seem to work with cXR 5.3.3, but on not on 9910 eXR 6.5.3 and 9010 eXR 7.1.2.

**Comment by gifino75** [comment]
If it is of any help, I just threw together a script using Telnetlib, which if I am not mistaked is used in Netmiko to do telnet

```
def telnetter_xr(hostname):
		hostn = hostname + '.log'
		hostdump = os.path.join(dump_dir, hostn)
		telnet = telnetlib.Telnet(hostname)
		telnet.read_until(b'Username: ', 5)
		telnet.write(myuser)
		telnet.read_until(b'Password: ', 5)
		telnet.write(mypass)
		telnet.write(b"term leng 0\r")
		time.sleep(1)
		telnet.write(b"show ver\r\n")
		time.sleep(3)
		telnet.write(b"exit\r")
		dump = telnet.read_until(b'#exit')
		with open(hostdump, 'w', encoding='utf-8') as f:
			f.write(dump.decode('utf-8'))
		telnet.close() 
```
this is very crude and no way comparable to Netmiko, but it logged in and out happily.

**Comment by ktbyers** [comment]
Try setting `fast_cli=False` as an Argument to ConnectHandler.

If that still fails, then set global_delay_factor=2 or 4 (once again with fast_cli=False).

**Comment by gifino75** [comment]
Hello Kirk,

fast_cli=False alone was not sufficient, but used in combination with global_delay_factor = 2, it now works on the nodes on which auth was failing. 

I read that fast_cli

> Provide a way to optimize for performance. Converts select_delay_factor
>             to select smallest of global and specific. Sets default global_delay_factor to .1
>             (default: True)

So I guess to actually set a global_delay of 2, I first need to set fast_cli as False, as it would otherwise set it to 0.1, correct? 
Also, I wonder if global_delay could be more fine tuned to address cases such as mine. Is it an int or a float i could set, for instance, to 1.5?

Thank you for your quick support!

**Comment by ktbyers** [comment]
@gifino75 Yes, I think the timing was just off i.e. the `username` would not come fast enough (or when the username was sent, the password would not follow with the right timing). So the above basically slowed things down a lot.

Yeah, you need to set fast_cli=False to get global_delay_factor to work normally (basically goes from .1 to 1 as a multiplier). Then the setting global_delay_factor=2 increases it to 2 (so 20 times the original value). Yeah global_delay_factor should support a float.
