### ISSUE TITLE
Getting exception at ConnectHandler while trying to connect to Palo Alto firewall

### ISSUE THREAD

**Issue by rahulnangare007** [ktbyers/netmiko#3085]
Hello Kirk,

I am running a code get information from Palo Alto firewall. While trying to connect I am getting an error at ConnectHandler. How do I work around this?

below is the code:

from netmiko import ConnectHandler
import getpass
import time

begin = time.time()

device = "paloalto_panos"

hostname = input("Enter IP addres: ")
user = input("Enter username: ")
passw = getpass.getpass(prompt='Password: ', stream=None)
device_info = {
	'device_type': device,
	'host':   hostname,
	'username': user,
	'password': passw,
	'port' : 22,
    'fast_cli': False
  }

try:
    device_connect = ConnectHandler(**device_info)
except Exception as err:
    print("ERR_Device_Connect")
    sys.exit(f"Message: {err}")

output = device_connect.send_command("show system info")
print(output)

time.sleep(1)
# store end time
end = time.time()
# total time taken
#print("Total tunnels proccesed:", x)
print(f"Total runtime of the program is {end - begin}")
#f.close()

==============================
Exception:

raceback (most recent call last):
  File "c:\Users\rahul.nangare\Documents\my python codes\new_pa_written.py", line 18, in <module>
    net_connect = ConnectHandler(**device_info)
  File "C:\Program Files\Python39\lib\site-packages\netmiko\ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\netmiko\base_connection.py", line 439, in __init__
    self._open()
  File "C:\Program Files\Python39\lib\site-packages\netmiko\base_connection.py", line 445, in _open
    self._try_session_preparation()
  File "C:\Program Files\Python39\lib\site-packages\netmiko\base_connection.py", line 904, in _try_session_preparation
    self.session_preparation()
  File "C:\Program Files\Python39\lib\site-packages\netmiko\paloalto\paloalto_panos.py", line 72, in session_preparation
    self.set_terminal_width(
  File "C:\Program Files\Python39\lib\site-packages\netmiko\base_connection.py", line 1260, in set_terminal_width
    output = self.read_until_pattern(pattern=pattern)
  File "C:\Program Files\Python39\lib\site-packages\netmiko\base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'set cli terminal width 500' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
If you manually do this from the CLI of the failing device, what do you see (make sure you use the same account as your script uses):

```
set cli terminal width 500
```

**Comment by rahulnangare007** [comment]
I ran this command on device directly, i got no response.

FW-PRI(active)> set cli terminal width 500
FW-PRI(active)>

**Comment by ktbyers** [comment]
Okay, your error above indicates that the palo alto device didn't echo `set cli terminal width 500` to the screen for some reason.

Can you enable the Netmiko `session_log` and upload that information here?

```python
device_info = {
'device_type': device,
'host': hostname,
'username': user,
'password': passw,
'port' : 22,
'fast_cli': False,
'session_log': 'output.txt',
}
```

**Comment by rahulnangare007** [comment]
Hello,

I was able to work around the issue by downgrading Netmiko to 4.0.0

It does not show me same exception now.

**Comment by ktbyers** [comment]
@rahulnangare007 Okay, just let me know if you want to try to resolve the underlying issue (otherwise you will be a bit stuck on the old version of Netmiko indefinitely).
