### ISSUE TITLE
Juniper commit issue

### ISSUE THREAD

**Issue by HeikkiLavaste** [ktbyers/netmiko#3086]
Hi, 

I'm trying to send commands with "send_config_set". 
The commands are send, but nothing comes back on the read channel. 
I'm sending a commit after the list of commands: 

    def Set(self, command):
        
        output = self.connection.send_config_set(command)
        if self.device.driver in ['juniper_junos', 'vyos']:
            self.connection.commit()
        return output

On a Vyos box I use for lab testing, I have no issues. 
With a Juniper box. debug just gets stuck on:

DEBUG:netmiko:write_channel: b'set system  name-server 192.168.192.2\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: set system name-server
DEBUG:netmiko:read_channel:  192.168.192.2
DEBUG:netmiko:read_channel:

Then, when I login to the router, I see following:

hlavaste-a@lab_box2> configure
Entering configuration mode
The configuration has been changed but not committed

{master:0}[edit]
hlavaste-a@lab_box2# show | compare
[edit system]
+  name-server {
+      192.168.192.2;
+      192.168.192.3;
+  }

I'm pretty sure I'm missing something very simple, just don't know what it is. 

Br, 
Heikki

**Comment by ktbyers** [comment]
@HeikkiLavaste Do you receive an exception back from Netmiko. Can you post that here?

**Comment by HeikkiLavaste** [comment]
Hi,
No exception, in the debug, the read channel just keeps waiting for something.

**Comment by ktbyers** [comment]
No exception?

Can you show your ConnectHandler arguments for the device and your broader code where you call this method?

**Comment by HeikkiLavaste** [comment]
I did some tests today. 
When a list of commands is short, adding one or two lines, it works. 
If the list is longer, say, 8 lines of commands, I get readtimeout:

['delete system name-server 8.8.8.8', 'delete system name-server 4.4.4.4', 'set system  name-server 10.116.224.5 ', 'set system  name-server 10.224.60.194 ', 'set system  name-server 10.116.224.6 ', 'set system  name-server 10.224.60.195 ', 'set system ntp server 10.116.224.5 prefer', 'set system ntp server 10.116.224.6']
Traceback (most recent call last):
  File "/Users/heikki.lavaste/Documents/code/projects/Configurator/main.py", line 291, in <module>
    Main()
  File "/Users/heikki.lavaste/Documents/code/projects/Configurator/main.py", line 270, in Main
    print(TestOrRun(dry_run,config, connection))
  File "/Users/heikki.lavaste/Documents/code/projects/Configurator/main.py", line 165, in TestOrRun
    message = connection.Set(output)
  File "/Users/heikki.lavaste/Documents/code/globalModules/connector/ssh_connect.py", line 24, in Set
    output = self.connection.send_config_set(command, exit_config_mode=False)
  File "/Users/heikki.lavaste/Documents/code/lib/python3.9/site-packages/netmiko/base_connection.py", line 2202, in send_config_set
    output += self.read_until_pattern(pattern=re.escape(cmd.strip()))
  File "/Users/heikki.lavaste/Documents/code/lib/python3.9/site-packages/netmiko/base_connection.py", line 672, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'set\\ system\\ \\ name\\-server\\ 10\\.116\\.224\\.5' in output.

Below is the module I use for sending the config commands: 

from netmiko import ConnectHandler, NetmikoAuthenticationException, NetmikoTimeoutException
import paramiko
import logging
import os

class Connect:

    def __init__(self,user,device, timeout=10, parse=True, debug=False, dir=None):
        self.user = user
        self.device = device
        self.timeout = timeout
        self.parse = parse
        self.debug = debug
        self.connection = None
        self.status_code, self.status = self.connect(self)
        
    def Show(self, command):
     
        output = self.connection.send_command(command,use_textfsm=self.parse)
        return output

    def Set(self, command):
        
        output = self.connection.send_config_set(command, exit_config_mode=False)
        if self.device.driver in ['juniper_junos', 'vyos']:
            print("Commit time")
            self.connection.commit(and_quit=True)
            
        elif self.device.driver in ['arista_eos', 'cisco_ios']:
            self.connection.save_config()
        return output

    def Quit(self):
        self.connection.disconnect()


    @staticmethod
    def connect(self):
        if self.debug: 
            logging.basicConfig(filename='debug.log', level=logging.DEBUG)
            logger = logging.getLogger(f"netmiko")
        try: 
            Conn = {'device_type': self.device.driver,
                    'ip': self.device.MgmtIp,
                    'username' :self.user.username,
                    'password': self.user.password,
                    'conn_timeout': self.timeout, 
                    } 

            self.connection = ConnectHandler(**Conn)
            if not self.connection.check_enable_mode():  ### Check for EXEC-mode
                self.connection.enable()

            return 100, True

        except NetmikoAuthenticationException as e:
            exception_type = type(e).__name__ ### Authentication error
            return 400, False
    
    
        except NetmikoTimeoutException as e:
            exception_type = type(e).__name__ ### Timeout
            return 401, False
    
        except Exception as e:
            exception_type = type(e).__name__ ### 
            return 402, False

**Comment by ktbyers** [comment]
Try setting cmd_verify=False.

```python
output = self.connection.send_config_set(command, cmd_verify=False)
```

**Comment by HeikkiLavaste** [comment]
That fixed it. Huge thanks, sir.
