### ISSUE TITLE
Palo alto, script, execute set commands and commit, hostname dash issue

### ISSUE THREAD

**Issue by kambata-bg** [ktbyers/netmiko#3089]
Hello, 

I'm trying to create a simple script to execute set configuration commands on multiple Palo Alto firewalls. 
It works sporadically and from time to time I get the error(my firewalls have "-"(dashes) in their hostname):
_"
Pattern not detected: 'PA\\-Test\\-DNS\\>' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.
"_

Python 3.8.12 (on CentOS 7) and/or 3.11.1 (Windows server 2019), netmiko - 4.8.5

+++CODE:
from __future__ import absolute_import, division, print_function

import netmiko
import time
import sys

devices = '''
10.42.169.138
10.42.169.130
10.42.169.162
'''.strip().splitlines()

device_type='paloalto_panos'
username='admin'
password='asdsada'

netmiko_exceptions = (netmiko.NetMikoTimeoutException, netmiko.NetMikoAuthenticationException)

for device in devices:
  try:
    print ('~'*78)
    print ('Connecting to device', device)
    connection = netmiko.ConnectHandler(ip=device, device_type=device_type, username=username, password=password)
    print(connection.send_command('show system info | match hostname'))
    print(connection.send_command('show clock'))
    connection.send_command('set cli scripting-mode on')
    connection.config_mode()
    connection.send_command('set shared log-settings syslog prg1-soclog-1 server prg1-soclog-1 port 514')
    connection.send_command('set shared log-settings syslog prg1-soclog-1 server prg1-soclog-1 server 5.5.5.5')
    connection.send_command('set shared log-settings syslog prg1-soclog-1 server prg1-soclog-1 format BSD')
    connection.send_command('set shared log-settings syslog prg1-soclog-1 server prg1-soclog-1 facility LOG_USER')
    connection.send_command('set shared log-settings syslog prg1-soclog-1 server prg1-soclog-1 transport UDP')

    connection.send_command('set shared log-settings syslog gva4-soclog-1 server gva4-soclog-1 port 514')
    connection.send_command('set shared log-settings syslog gva4-soclog-1 server gva4-soclog-1 format BSD')
    connection.send_command('set shared log-settings syslog gva4-soclog-1 server gva4-soclog-1 server 5.5.5.4')
    connection.send_command('set shared log-settings syslog gva4-soclog-1 server gva4-soclog-1 facility LOG_USER')
    connection.send_command('set shared log-settings syslog gva4-soclog-1 server gva4-soclog-1 transport UDP')

    connection.send_command('set shared log-settings config match-list Configuration send-syslog gva4-soclog-1')
    connection.send_command('set shared log-settings config match-list Configuration send-syslog prg1-soclog-1')
    connection.send_command('set shared log-settings config match-list Configuration filter "All Logs"')

    connection.send_command('set shared log-settings system match-list System send-syslog gva4-soclog-1')
    connection.send_command('set shared log-settings system match-list System send-syslog prg1-soclog-1')
    connection.send_command('set shared log-settings system match-list System filter "All Logs"')
    print(connection.commit())
    print(connection.send_command('show clock'))
    connection.disconnect()
  except netmiko_exceptions as e:
    print ('Login failed to ', device, e)

exit()

**Comment by ktbyers** [comment]
@kambata-bg You need to include the full exception stack trace i.e. all the items before `Pattern not detected: 'PA\-Test\-DNS\>' in output.` (so I can see where in the code the error happened).

**Comment by ktbyers** [comment]
The dashes in your hostnames shouldn't matter.

Any chance on providing the full exception stack trace?

You might need to eliminate your try/except block if that is hiding/masking the underlying error.

**Comment by kambata-bg** [comment]
Sorry, I moved to using pexpect , as I really need to finish this project.
