### ISSUE TITLE
Command line filtering, need to enable session logging

### ISSUE THREAD

**Issue by zeepi222** [ktbyers/netmiko#309]
Hi Kirk,

I have a strange issue ... when I send a command to a Cisco switch and use the "include" command to grep specific output. The include command appears to work, however I am also receiving output which is unfiltered. I have installed netmiko dev 1_2 in an attempt to enable session logging, so I can see what is being sent to the CLI, but I am unsure of the syntax to enable session logging.

Code Snippet:
```
DeviceList = {'SW01': {'10.1.1.1': {'Gi1/0/40': {'vlan ID': '97', 'nmac': '588d.096c.a9ea'}, 'Gi1/0/2': {'vlan ID': '111', 'nmac': '0022.909d.fe46'}

for ifname in DeviceList[swname][swip].keys():
    cmd = 'show interface status | include ' + ifname
    print cmd
    StatusType = ssh_session.send_command(cmd, delay_factor=2)
    print StatusType
```

Output:
```
show interface status | include Gi1/0/40
Gi1/0/40  ASA MGMT0/0        connected    97         a-full  a-100 10/100/1000BaseTX
show interface status | include Gi1/0/2
Gi1/0/2   ASA Ext            connected    trunk      a-full a-1000 10/100/1000BaseTX
Gi1/0/20                     notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/21                     notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/22                     notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/23                     notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/24                     notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/25                     notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/26                     notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/27                     notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/28                     notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/29                     notconnect   1            auto   auto 10/100/1000BaseTX

```

Thanks Zee

**Comment by halfmetaljacket** [comment]
If you look at the output you're getting in this specific case, you'll notice that all of the additional lines includes the "Gi1/0/2" string that you're grepping. For instance "Gi1/0/20" will match what you're including. You would have to ensure that your search string is more specific (e.g. "Gi1/0/2 " <- note the trailing space) in order to avoid receiving unwanted output. This looks like expected behavior (even if it is undesired) to me, but to be sure, try executing the same command manually from the CI and compare it with what you get from your script.

**Comment by zeepi222** [comment]
Good pickup @halfmetaljacket , I will test and report back.
As an aside, do you know how to enable session logging (like in putty)?
I am using the dev_1_2 release.

**Comment by halfmetaljacket** [comment]
Session logging is not currently available as a feature in Netmiko. I do have an open PR to add that feature, but it is still under review by @ktbyers and has not yet been merged in. If you would like to stay informed, keep an eye on PR #284 or the original issue #279.

**Comment by zeepi222** [comment]
Thank you @halfmetaljacket 
My issue was resolved by including a space at the end of the include statement.
I will follow PR#284 as I think this will be a great feature for troubleshooting.
