### ISSUE TITLE
Need tests for Comware

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#31]
Need unit tests for Comware (located in the netmiko/tests directory).

**Comment by ravenblue12** [comment]
It works also on comware 7. I tested it with a virtual HP VSR1000.

**Comment by ktbyers** [comment]
Okay, nice...here I am referring to Unit Tests.  I have unit tests for pretty much everything, but Comware.  The unit tests are located in the netmiko/tests directory and use py.test.

They are pretty easy to create.

**Comment by ravenblue12** [comment]
on the way!

**Comment by ktbyers** [comment]
Nice :-)

On Thu, Feb 12, 2015 at 1:25 PM, Rene Plattner <notifications@github.com>
wrote:

> on the way!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/31#issuecomment-74155876>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation
