### ISSUE TITLE
SSHDetect - OneAccess device not detected

### ISSUE THREAD

**Issue by bilalel** [ktbyers/netmiko#3104]
Hi Kirk,

The [SSHDetect](https://github.com/ktbyers/netmiko/blob/develop/netmiko/ssh_autodetect.py#L309) class is not able to detect OneAccess equipment.
This is due to missing entry in the SSH_MAPPER_DICT dictionnary.

The following entry should make it:
```
"oneaccess_oneos": {
        "cmd": "show version",
        "search_patterns": [r"OneOS"],
        "priority": 99,
        "dispatch": "_autodetect_std",
    },
```

Do you mind if I send a pull request for this ?

**Comment by ktbyers** [comment]
@bilalel Sounds good. Yes, send a PR on it.
