### ISSUE TITLE
Unable to find prompt error on HP ProCurve 2510, 2610, and 2810 switches

### ISSUE THREAD

**Issue by devinmcintyre** [ktbyers/netmiko#311]
I've verified login information by manually SSHing to the switch and running this exact code on other model of switches without error.  Here's the exact traceback I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 96, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 90, in __init__
    self.session_preparation()
  File "C:\Python27\lib\site-packages\netmiko\hp\hp_procurve_ssh.py", line 23, in session_preparation
    self.set_base_prompt()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 504, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 549, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt:
```

And here's my code:

```
from netmiko import ConnectHandler
net_connect = ConnectHandler(device_type='hp_procurve', ip='172.16.1.220', username='manager', password='password')
net_connect.send_command("copy run tftp 172.16.1.1 SwitchBackups\\Hershey\\HPS-LIB-HP2810A.txt")
net_connect.disconnect()
```

Login prompt looks identical to other models of switches so not sure what could be tripping up netmiko here.

**Comment by ktbyers** [comment]
@devinmcintyre What happens when you manually run this command?

```
copy run tftp 172.16.1.1 SwitchBackups\\Hershey\\HPS-LIB-HP2810A.txt
```

Does it prompt you for additional things or just execute (without any additional prompting)?

Also what does the following show you (if you insert this between the ConnectHandler line and the send_command() line.

```
print net_connect.find_prompt()
```

**Comment by devinmcintyre** [comment]
The command takes without any additional prompts:

```
HPS-LIB-HP2810A# copy run tftp 172.16.1.1 SwitchBackups\Hershey\HPS-LIB-HP2810A.txt
HPS-LIB-HP2810A#
```

Although you've probably seen it before, here's the output the switch gives after the "login as:" and "manager@172.16.1.220's password:" prompt:

```
ProCurve J9021A Switch 2810-24G
Software revision N.11.74

Copyright (C) 1991-2016 Hewlett-Packard Co.  All Rights Reserved.

                           RESTRICTED RIGHTS LEGEND

 Use, duplication, or disclosure by the Government is subject to restrictions
 as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and
 Computer Software clause at 52.227-7013.

         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303











Press any key to continue
```

Here's the output of the command you mentioned as well:

```
>>> from netmiko import ConnectHandler
>>> net_connect = ConnectHandler(device_type='hp_procurve', ip='172.16.1.220', username='manager', password='password')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 96, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 90, in __init__
    self.session_preparation()
  File "C:\Python27\lib\site-packages\netmiko\hp\hp_procurve_ssh.py", line 23, in session_preparation
    self.set_base_prompt()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 504, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 549, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt:
>>> print net_connect.find_prompt()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'net_connect' is not defined
>>>
```

Logging in manually, everything seems responsive.  It doesn't seem to me the # prompt takes longer to come up than other models we have in the field.  Updated to the latest firmware on these switches as well with no luck.

**Comment by devinmcintyre** [comment]
I just wanted to say too that I can't thank you enough for the work you've done on this Python module.  Using this, my organization is now able to automate the config backups of the close to 500 switches we have deployed in the field.  We were never able to keep current backups for these devices until I stumbled on this solution.  Anything you need from me to help resolve this minor issue I'd be more than happy to provide!

**Comment by ktbyers** [comment]
@devinmcintyre Thanks Devin. It is nice to hear people that are having success using this library.

Can you try the Netmiko dev_1_2 branch? We put a fix in recently for HP ProCurve. This fix added some extra delay that might be relevant here. The issue is referenced here.

https://github.com/ktbyers/netmiko/commit/a818427216f71272ae8410f63927db4891dbe39e

You can install this as follows.

```
git clone https://github.com/ktbyers/netmiko --branch dev_1_2
cd netmiko
python setup.py install

cd ~
>>> import netmiko
>>> netmiko.__version__
'1.2.0'
```

Just to be careful to test this in an environment where it is appropriate (i.e. use a virtual environment sandbox and don't mess up your existing production code.

**Comment by devinmcintyre** [comment]
Thanks for the reply.  I'm still noticing the issue with the dev_1_2 brand unfortunately.  On the mentioned models, I've noticed it'll complete about 25% (maybe less) of the time successfully so a timing issue is what I assumed first as well.  Like I said too, all other models have been rock solid.  Even older 2626 models I didn't expect to work have been taking the script well.

**Comment by ktbyers** [comment]
@devinmcintyre What happens if you set the global_delay_factor to either 2 or 4.

```
net_connect = ConnectHandler(device_type='hp_procurve', ip='172.16.1.220', 
                                                    username='manager', password='password',
                                                    global_delay_factor=2)
```

**Comment by devinmcintyre** [comment]
That did the trick!  One interesting thing to note is that a global_delay_factor of 2 worked in a Python script, but I had to bump it up to 6 after compiling it to an exe with PyInstaller for it to work.  Also, 2626 models were affected by this issue as well I found.

Thanks for all the help!  Everything appears to be working for me now.  Even have these configs setup to push to a git repo weekly so we can do version controlling.  Very helpful solution this module made possible.

**Comment by ktbyers** [comment]
@devinmcintyre Okay, I put this improvement in for HP ProCurve (i.e. increase the default delay):

https://github.com/ktbyers/netmiko/commit/7215e32debe227a2637be889880486e8ceaeddf9

I will possibly try to improve this by making it a while loop as I don't like that it now will take at least 6 seconds to login.

**Comment by rwwelford** [comment]
I was also experiencing this issue for HP Procurve 2600 and 2610 devices.  However, I was able to solve my problem by adding a line to the find_prompt() function of the base_connection.py file.

In that function is a section of code that handles the case where the prompt variable contains only a newline.  The change I made was to strip the newline character from the prompt variable so that it passed the while statement condition and executed the code in the while loop:

`   

    def find_prompt(self, delay_factor=1):
       debug = False
       delay_factor = self.select_delay_factor(delay_factor)
       self.clear_buffer()
        self.write_channel("\n")
       time.sleep(delay_factor * .1)

       prompt = self.read_channel().strip()
       if self.ansi_escape_codes:
       prompt = self.strip_ansi_escape_codes(prompt)

        if debug:
       print("prompt1: {}".format(prompt))

       count = 0
       prompt = prompt.strip()   # <================================== added this line
       while count <= 10 and not prompt:

`

While this allowed the code to complete successfully the real issue seems to be in the paramiko libraries buffered_pipe.py file.  Something like a race condition seems to happen when code execution gets to the  _read_ function.  If you put a debug/break on the line containing the self._lock.acquire() (line 143) then code execution works.  Putting a time.sleep(1) command immediately before the self._lock.acquire() line seems to fix things as well but introduces an unnecessary delay:

`   

    def read(self, nbytes, timeout=None):
        out = bytes()
        import time   # <============================ Added this line
        time.sleep(1) # <============================ Added this line
        self._lock.acquire()
        try:
`

**Comment by ktbyers** [comment]
@rwwelford Where did the above find_prompt() method come from? 

Current find_prompt() method in Netmiko 1.1 and dev_1_2 branch already are doing strip() at the end.

**Comment by rwwelford** [comment]
I'm using Netmiko 1.1.0.  There is indeed a strip() at the end - after the while loop as well as inside the while loop.  The problem I was having is that when the prompt that I had received only contained a newline character I was not satisfying the while loop conditional test.  That is, the test was failing on the "and not prompt" part of the test.  Striping the newline immediately before the while allowed the test to pass and process the code within.

**Comment by ktbyers** [comment]
@rwwelford What does the prompt on the failing device look like?

Here is the current find_prompt:
```
575     def find_prompt(self, delay_factor=1):
576         """Finds the current network device prompt, last line only."""
577         debug = False
578         delay_factor = self.select_delay_factor(delay_factor)
579         self.clear_buffer()
580         self.write_channel("\n")
581         time.sleep(delay_factor * .1)
582 
583         # Initial attempt to get prompt
584         prompt = self.read_channel().strip()
585         if self.ansi_escape_codes:
586             prompt = self.strip_ansi_escape_codes(prompt)
587 
588         if debug:
589             print("prompt1: {}".format(prompt))
590 
591         # Check if the only thing you received was a newline
592         count = 0
593         while count <= 10 and not prompt:
594             prompt = self.read_channel().strip()
595             if prompt:
596                 if debug:
597                     print("prompt2a: {}".format(repr(prompt)))
598                     print("prompt2b: {}".format(prompt))
599                 if self.ansi_escape_codes:
600                     prompt = self.strip_ansi_escape_codes(prompt).strip()
601             else:
602                 self.write_channel("\n")
603                 time.sleep(delay_factor * .1)
604             count += 1
605 
606         if debug:
607             print("prompt3: {}".format(prompt))
608         # If multiple lines in the output take the last line
609         prompt = self.normalize_linefeeds(prompt)
610         prompt = prompt.split('\n')[-1]
611         prompt = prompt.strip()
612         if not prompt:
613             raise ValueError("Unable to find prompt: {}".format(prompt))
614         time.sleep(delay_factor * .1)
615         self.clear_buffer()
616         return prompt
```

**Comment by ktbyers** [comment]
@rwwelford Okay, if I am understanding you correctly, you are saying that your prompt (on line 593 above) would contain only whitespace so it would never enter the while loop?

**Comment by rwwelford** [comment]
You are essentially correct.  My prompt at line 593 only contained the newline character.

Here is my modified find_prompt:
```
511     def find_prompt(self, delay_factor=1):
512         """Finds the current network device prompt, last line only."""
513         debug = False
514         delay_factor = self.select_delay_factor(delay_factor)
515         self.clear_buffer()
516         self.write_channel("\n")
517         time.sleep(delay_factor * .1)
518
519         # Initial attempt to get prompt
520         prompt = self.read_channel().strip()
521         if self.ansi_escape_codes:
522             prompt = self.strip_ansi_escape_codes(prompt)
523
524         if debug:
525             print("prompt1: {}".format(prompt))
526
527         # Check if the only thing you received was a newline
528         count = 0
529         prompt = prompt.strip()    <========================================  Added this line
530         while count <= 10 and not prompt:
531             prompt = self.read_channel().strip()
532             if prompt:
533                 if debug:
534                     print("prompt2a: {}".format(repr(prompt)))
535                     print("prompt2b: {}".format(prompt))
536                 if self.ansi_escape_codes:
537                     prompt = self.strip_ansi_escape_codes(prompt).strip()
538             else:
539                 self.write_channel("\n")
540                 time.sleep(delay_factor * .1)
541             count += 1
542
543         if debug:
544             print("prompt3: {}".format(prompt))
545         # If multiple lines in the output take the last line
546         prompt = self.normalize_linefeeds(prompt)
547         prompt = prompt.split('\n')[-1]
548         prompt = prompt.strip()
549         if not prompt:
550             raise ValueError("Unable to find prompt: {}".format(prompt))
551         time.sleep(delay_factor * .1)
552         self.clear_buffer()
553         return prompt

```

**Comment by ktbyers** [comment]
@rwwelford Okay, I will move line 520 to happen after 522.

In other words, the ANSI escape characters must be screwing this up.

**Comment by rwwelford** [comment]
I suppose that a newline character doesn't qualify as a "True" boolean.

**Comment by ktbyers** [comment]
Yes, Python will treat the following as boolean True.

```
prompt = "\n"
```

**Comment by ktbyers** [comment]
Okay, thanks for pointing this out...I have made a change and am running unit tests now.

**Comment by rwwelford** [comment]
Thanks Kirk.  This library is very useful for us and I appreciate the work you put into it.

**Comment by ktbyers** [comment]
Okay, the fix for this is in the dev_1_2 branch

https://github.com/ktbyers/netmiko/commit/71d4bab023e68d50f369553b2b8325452d270fbf
