### ISSUE TITLE
show tech collection from cisco xr

### ISSUE THREAD

**Issue by ramprasanthbe** [ktbyers/netmiko#3113]
[ktbyers](https://github.com/ktbyers) - I have learnt a lot from you and I would like to thank you for all your efforts in making network engineers successful

I was using netmiko for collecting multiple show techs from the XR devices. One by one using loop.

I am getting the following error  all the time. 

netmiko.exceptions.ReadTimeout:
Pattern not detected: 'RP/0/RP0/CPU0:NCS5508\\\\#' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

#########################################################################'
I have played with read_timeout  and expect_string argument arguments and it doesn't help. 

The command will buffer for sometime,  and we can't define for any  timeline for each commands. 

We are from TAC and we collect more show techs and I need your help to fix this 
##########################################################################

Show tech outputs will be like. 

RP/0/RP0/CPU0:NCS5508#show tech-support
Mon Feb 13 14:26:23.469 UTC
++ Show tech start time: 2023-Feb-13.142623.UTC ++
Mon Feb 13 14:26:45 UTC 2023 Waiting for gathering to complete
.............................
Mon Feb 13 14:28:52 UTC 2023 Compressing show tech output
Show tech output available at 0/RP0/CPU0 : /harddisk:/showtech/showtech-NCS5508-generic-2023-Feb-13.142623.UTC.tgz
++ Show tech end time: 2023-Feb-13.142912.UTC ++

RP/0/RP0/CPU0:#show tech bundles 
Mon Feb 13 05:50:09.282 UTC
++ Show tech start time: 2023-Feb-13.055009.UTC ++
Mon Feb 13 05:50:26 UTC 2023 Waiting for gathering to complete
.............................
Mon Feb 13 05:52:33 UTC 2023 Compressing show tech output
Show tech output available at 0/RP0/CPU0 : /harddisk:/showtech/showtech--bundle-2023-Feb-13.055009.UTC.tgz
++ Show tech end time: 2023-Feb-13.055247.UTC ++

**Comment by ramprasanthbe** [comment]
My code

from netmiko import ConnectHandler
import time


def get_routers():
    hostnames = input("Enter hostname separated by comma (or 'q' to quit): ")
    username = input("Enter username: ")
    password = input("Enter password: ")
    device_type = input("Enter device type: ")
    if hostnames == 'q':
        return []
    return [
        {
            'device_type': device_type,
            'ip': host,
            'username': username,
            'password': password
        }
        for host in hostnames.split(",")
    ]


def get_commands():
    commands = []
    commands_str = input(
        "Enter commands separated by comma (or 'q' to quit): ")
    if commands_str == "q":
        return commands
    commands = commands_str.strip().split(",")
    return commands


def run_show_tech(routers, commands):
    for router in routers:
        try:
            connection = ConnectHandler(**router)
        except Exception as e:
            print(f"Failed to connect to {router['ip']}: {e}")
            continue
        for command in commands:
            show_tech_output = ">>> " + router['ip'] + " - " + command + "\n"
            output = connection.send_command(command)
            show_tech_output += output
        connection.disconnect()


routers = get_routers()
commands = get_commands()
run_show_tech(routers, commands)

**Comment by ramprasanthbe** [comment]
I see this consistently. I tried removing "for" loop for commands and executed with single "show tech" command

PS C:\Users\rampr\Desktop\Ram's Shelf\Python\Python_Files\Ram_Code_Cisco_tra> python show_tech.py
Enter hostname separated by comma (or 'q' to quit): 10.122.19.242
Enter username: adminEnter password: cisco.123
Enter device type: cisco_xr
Traceback (most recent call last):
  File "C:\Users\rampr\Desktop\Ram's Shelf\Python\Python_Files\Ram_Code_Cisco_tra\show_tech.py", line 39, in <module>
    run_show_tech(routers, command="show tech-support")
  File "C:\Users\rampr\Desktop\Ram's Shelf\Python\Python_Files\Ram_Code_Cisco_tra\show_tech.py", line 32, in run_show_tech
    output = connection.send_command(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rampr\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rampr\AppData\Local\Programs\Python\Python311\Lib\site-packages\netmiko\base_connection.py", line 1721, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:
Pattern not detected: 'RP/0/RP0/CPU0:NCS5508\\-MSFT\\#' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.


PS C:\Users\rampr\Desktop\Ram's Shelf\Python\Python_Files\Ram_Code_Cisco_tra>

**Comment by ktbyers** [comment]
How long roughly does this command take to run if you execute the command manually?

Have you set read_timeout to that value plus some additional margin? So if the command on the CLI takes 120 seconds, then a `read_timeout=180` is pretty reasonable.

The default read_timeout is 10 seconds i.e. Netmiko will wait 10 seconds looking for the given pattern and then raise an exception.

**Comment by ramprasanthbe** [comment]
yes, I tried with 120 seconds, we run multiple show techs and we never know if that completes within 5 minutes also. It depends on various factors.  if suppose my command does complete in 6 minutes and if the read_timeout is 5 minutes, still I could see same error.  the same show tech command will not take same time if you run in different routers at same time. 

lets say, the output starts to come after 4 minutes, and it takes few more seconds for the expected strings to occur.

How I can make the command active until i find expected string after 4 minutes of buffer

**Comment by ramprasanthbe** [comment]
for example, if you can see here it took close to 300 seconds. it depends on how much we  configured and enabled the features in routers 

RP/0/RP0/CPU0:NCS5508#show tech-support
Mon Feb 13 14:26:23.469 UTC
++ Show tech start time: 2023-Feb-13.142623.UTC ++
Mon Feb 13 14:26:45 UTC 2023 Waiting for gathering to complete
.............................
Mon Feb 13 14:28:52 UTC 2023 Compressing show tech output
Show tech output available at 0/RP0/CPU0 : /harddisk:/showtech/showtech-NCS5508-generic-2023-Feb-13.142623.UTC.tgz
++ Show tech end time: 2023-Feb-13.142912.UTC +

**Comment by ktbyers** [comment]
Just set it to an overly large value, Netmiko will return when it finds the prompt.

So if 5-minutes is not long enough, then set it to 10-minutes (600 seconds). If 10-minutes is not enough, then set it to 20-minutes, etc. Netmiko will return when it sees the prompt so there isn't much downside (i.e. if Netmiko sees the trailing prompt in 330 seconds, then it will return the output in ~330 seconds).

**Comment by ramprasanthbe** [comment]
let me try with 10 minutes. should i add both  read_timeout and the expect_string argument.

**Comment by ktbyers** [comment]
I would just `read_timeout=600` (i.e. 10 minutes and see what happens). I am assuming this operation completes within 10 minutes. If it is longer, then make it even larger.

**Comment by ramprasanthbe** [comment]
It worked like a charm 

PS C:\Users\rampr\Desktop\Ram's Shelf\Python\Python_Files\Ram_Code_Cisco_tra> python show_tech.py
Enter hostname separated by comma (or 'q' to quit): 10.122.19.242
Enter username: admin
Enter password: cisco.123
Enter commands separated by comma (or 'q' to quit): show tech,show tech bundles,admin show tech os,admin show tech install
>>> 10.122.19.242 - show tech

Tue Feb 14 02:51:47.707 UTC
++ Show tech start time: 2023-Feb-14.025148.UTC ++
Tue Feb 14 02:52:09 UTC 2023 Waiting for gathering to complete
.............................
Tue Feb 14 02:54:16 UTC 2023 Compressing show tech output
Show tech output available at 0/RP0/CPU0 : /harddisk:/showtech/showtech-NCS5508-MSFT-generic-2023-Feb-14.025148.UTC.tgz
++ Show tech end time: 2023-Feb-14.025436.UTC ++
>>> 10.122.19.242 - show tech bundles

Tue Feb 14 02:54:38.469 UTC
++ Show tech start time: 2023-Feb-14.025438.UTC ++
Tue Feb 14 02:55:00 UTC 2023 Waiting for gathering to complete
.............................
Tue Feb 14 02:57:07 UTC 2023 Compressing show tech output
Show tech output available at 0/RP0/CPU0 : /harddisk:/showtech/showtech-NCS5508-MSFT-bundle-2023-Feb-14.025438.UTC.tgz
++ Show tech end time: 2023-Feb-14.025727.UTC ++
>>> 10.122.19.242 - admin show tech os

Tue Feb 14 02:57:29.202 UTC
++ Show tech start time: 2023-Feb-14.025730.UTC ++
Waiting for gathering to complete
...............
Compressing show tech output
Show tech output available at /misc/disk1//showtech/showtech-os-admin-2023-Feb-14.025730.UTC.tgz
 Please collect show tech-support ctrace in addition to any sysadmin show-tech-support  collection 
++ Show tech end time: 2023-Feb-14.025803.UTC ++
>>> 10.122.19.242 - admin show tech install

Tue Feb 14 02:58:04.528 UTC
++ Show tech start time: 2023-Feb-14.025805.UTC ++
Waiting for gathering to complete
...............
Compressing show tech output
Show tech output available at /misc/disk1//showtech/showtech-install-admin-2023-Feb-14.025805.UTC.tgz
 Please collect show tech-support ctrace in addition to any sysadmin show-tech-support  collection
++ Show tech end time: 2023-Feb-14.025940.UTC ++
PS C:\Users\rampr\Desktop\Ram's Shelf\Python\Python_Files\Ram_Code_Cisco_tra>

**Comment by ktbyers** [comment]
@ramprasanthbe Okay, so are you all good then?

**Comment by ramprasanthbe** [comment]
Yes, Thanks for the input.
