### ISSUE TITLE
Run different set of commands on different cisco routers with a script

### ISSUE THREAD

**Issue by asgr8e** [ktbyers/netmiko#3117]
### Discussed in https://github.com/ktbyers/netmiko/discussions/3116

<div type='discussions-op-text'>

<sup>Originally posted by **asgr8e** February 16, 2023</sup>
HI all , If anyone can suggest on creating a python script where I should be able to Run different set of commands on different cisco routers  at once as I need to send config commands to around 1200 routers</div>

**Comment by ktbyers** [comment]
@asgr8e The question is too general to understand what you are looking for.

If you are talking configuration commands, then just use an external file per network device and use that to configure the device. Have the file based on some unique element of the device (the device hostname for example). Netmiko has a `send_config_from_file` method.

**Comment by asgr8e** [comment]
@ktbyers Thank you so much for your response. I was thinking of using that, but the device count is around 1200 routers. so, shall I go ahead, and use `send_config_from_file` for each device and put 100 or 200 routers in one script or are there any other options?

**Comment by ktbyers** [comment]
@asgr8e You should probably look into Nornir + Netmiko or some solution that supports threading.

**Comment by asgr8e** [comment]
Alright thanks again for your support @ktbyers
