### ISSUE TITLE
Getting error while handling the prompt on aruba os switch through netmiko using expect_string method....

### ISSUE THREAD

**Issue by NINJAX3X** [ktbyers/netmiko#3121]
```python
from netmiko import ConnectHandler
import sys
import time

aruba_osswitch = {
                    "device_type": "aruba_osswitch",
                    "ip": "address _ip",
                    "username": "user",
                    "password": "password",
                                                        }

net_connect = ConnectHandler(**aruba_osswitch)

net_connect.send_command(input('press enter'))

commands = [
            ('configure terminal', r'Aruba'),
            ('snmpv3 enable', r'authentication password')
                                                            ]

output = net_connect.send_multiline(commands)

print('Done')

output = net_connect.send_command('initial', expect_string = r'privacy password')

print('Done')

output = net_connect.send_command('initial', expect_string = r'that uses SHA')

print('Done')

output = net_connect.send_command('n', expect_string = r'messages to have read only')

print('Done')

output = net_connect.send_command('y', expect_string = r'')
                         
print('terminate')

net_connect.disconnect()
```

**Up till snmpv3 enable the script is working fine and printing the output but right after that it gives and error** 

Error is pattern not detected : 'initial in output'.

**Comment by ktbyers** [comment]
Can you show what you are trying to do from the Aruba CLI. In other words, show this interaction as it looks on the Aruba CLI.

**Comment by NINJAX3X** [comment]
In Aruba CLI, in global configuration mode-- 

When I execute command "snmpv3 enable" the following multiple prompts and multiple line in  one prompt comes-

1)SNMPv3 Initialization process.
   Creating user 'initial'
   Authentication Protocol: MD5
   Enter authentication password:  **(Prompts for authencation password for 'initial' user where I put 'initial' as password)**

2)Privacy protocol is DES
   Enter privacy password: **(Prompts for privacy password for 'initial' user where i again put 'initial' as password)**

3)User 'initial' has been created
   Would you like to create a user that uses SHA? [y/n]   **(Prompts for using SHA, where i put 'n' as input)**

4)User creation is done.  SNMPv3 is now functional.
   Would you like to restrict SNMPv1 and SNMPv2c messages to have read only
   access (you can set this later by the command 'snmpv3 restricted-access')?
     [y/n]  **(Prompts here for the same, where I put 'y' as an input)**

The above is the last prompt and it comes back to global config mode again in Aruba CLI.

**Comment by NINJAX3X** [comment]
These all prompt comes when I execute a single command i.e., "snmpv3 enable".

**Comment by NINJAX3X** [comment]
import netmiko
from netmiko import ConnectHandler
import sys
import time

aruba_osswitch = {
                    "device_type": "aruba_osswitch",
                    "ip": "10.15.40.14",
                    "username": "username",
                    "password": "password",
                    "global_delay_factor" : 2,
                                                        }

net_connect = ConnectHandler(**aruba_osswitch)


commands = [
            'configure terminal',
            'snmpv3 enable',
            'initial',
            'initial',
            'n',
            'y',
                                                            ]

output = net_connect.send_multiline_timing(commands, multiline = True)

print(output)

print("\n""Done")

net_connect.disconnect()

**Comment by NINJAX3X** [comment]
Was able to resolve the above with the above code in Aruba CLI. It worked fine.
