### ISSUE TITLE
netmiko : errors when using the ssh proxy

### ISSUE THREAD

**Issue by samy92100** [ktbyers/netmiko#313]
Hi,

Do you have please an idea about this output errors :

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/paramiko-2.0.2-py3.4.egg/paramiko/transport.py", line 77, in _join_lingering_threads
  File "/usr/lib/python3.4/site-packages/paramiko-2.0.2-py3.4.egg/paramiko/transport.py", line 1552, in stop_thread
AttributeError: 'ProxyCommand' object has no attribute '_closed'

I use python 3.
my python file

#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass

cisco = {
    'device_type': 'cisco_ios',
    'ip': '10.10.10.250',
    'username': 'user1',
    'password': 'passwd',
    'port': 22,
    'ssh_config_file': '~/.ssh/config',
    'verbose': False,
}

net_connect = ConnectHandler(**cisco)
output = net_connect.send_command('show users')
print (output)
print()
print (net_connect.find_prompt())
print() 

my config file

host 10.10.10.250:22          # Cisco IOS router pynet-rtr1
  user user1
  hostname 10.10.10.250
  Port 22
  ProxyCommand ssh user1@10.20.20.20 nc %h %p

thank you for your help

**Comment by ktbyers** [comment]
@samy92100 Yeah, don't know.

Did you read this article:

https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html


Also I don't see any definition for the '10.20.20.20' connection in your SSH config file?

**Comment by samy92100** [comment]
Hi @ktbyers , thank you for your answer. Yes, I have read this article. The problem, that the code is executed with success but it shows the errors mentioned above !!!

**Comment by ktbyers** [comment]
@samy92100 Okay, it looks like it might be this issue under Python3.

https://github.com/paramiko/paramiko/issues/789
