### ISSUE TITLE
python script is pushing the code but Cisco XR is not printing the output!!!

### ISSUE THREAD

**Issue by Licky1997** [ktbyers/netmiko#3134]
New to Python and Netmiko: Was trying to view the Python output by sending a script. The Script went in fairly but the problem is that, the router is printing only one command , ignoring the rest and moving to other router.Is there anything else that i'm missing in this part of the code ?

```import os
os.chdir("/home/cisco/python")
from netmiko import ConnectHandler
commands = ("do sh int desc | i down","do sh interface | i drop","do ping vrf <VRF AND IPADDRESS> source loopback 10","do sh version","do sh run formal | i mac | i BVI","do sh run router isis | i sid")
R1=ConnectHandler(ip="<IP address>", username="<Username>", password="<Password>", device_type="cisco_xr",fast_cli="true")
R2=ConnectHandler(ip="<IP address>", username="<Username>", password="<Password>", device_type="cisco_xr",fast_cli="true")
devices=[R1,R2]
for x in devices:
    x.establish_connection()
    x.enable()
    output=x.send_config_set(commands,cmd_verify=False)
    print(output)
```

Output:
configure terminal

Sun Mar  5 06:33:14.737 UTC

RP/0/RP0/CPU0:R1(config)#do sh int desc | i down

do sh interface | i drop
do ping vrf <VRF AND IPADDRESS> source loopback 10
do sh version
do sh run formal | i mac | i BVI
do sh run router isis | i sid
Sun Mar  5 06:33:15.238 UTC
Hu0/0/0/24         down        down        Ring 1 to CSR-4
Hu0/0/0/25         down        down        Ring 2 to CSR-4
Hu0/0/0/26         down        down        Ring 3 to CSR-4
Hu0/0/0/27         down        down        Ring 4 to CSR-4
Hu0/0/0/28         down        down        Ring 5 to CSR-4
TF0/0/0/9          admin-down  admin-down  
TF0/0/0/10         down        down        CELL SITE 01
TF0/0/0/11         down        down        CELL SITE 02
TF0/0/0/12         down        down        CELL SITE 03
TF0/0/0/13         down        down        CELL SITE 04
TF0/0/0/14         down        down        CELL SITE 05
TF0/0/0/15         down        down        CELL SITE 06
TF0/0/0/16         down        down        CELL SITE 07
TF0/0/0/17         down        down        CELL SITE 08
TF0/0/0/18         down        down        CELL SITE 09
TF0/0/0/19         down        down        CELL SITE 10
Hu0/0/1/1          down        down        
Hu0/0/1/2          admin-down  admin-down  
Hu0/0/1/3          admin-down  admin-down  
FH0/0/2/2          admin-down  admin-down  
FH0/0/3/0          down        down        

RP/0/RP0/CPU0:R1(config)#do sh interface | i drop

Sun Mar  5 06:33:15.843 UTC

configure terminal

Sun Mar  5 06:33:20.859 UTC
RP/0/RP0/CPU0:R2(config)#do sh int desc | i down

do sh interface | i drop
do ping vrf <VRF AND IPADDRESS> source loopback 10
do sh version
do sh run formal | i mac | i BVI
do sh run router isis | i sid
Sun Mar  5 06:33:21.277 UTC
Hu0/0/0/24         down        down        Ring 1 to CSR-4
Hu0/0/0/25         down        down        Ring 2 to CSR-4
Hu0/0/0/26         down        down        Ring 3 to CSR-4
Hu0/0/0/27         down        down        Ring 4 to CSR-4
Hu0/0/0/28         down        down        Ring 5 to CSR-4
TF0/0/0/9          admin-down  admin-down  
TF0/0/0/10         down        down        CELL SITE 01
TF0/0/0/11         down        down        CELL SITE 02
TF0/0/0/12         down        down        CELL SITE 03
TF0/0/0/13         down        down        CELL SITE 04
TF0/0/0/14         down        down        CELL SITE 05
TF0/0/0/15         down        down        CELL SITE 06
TF0/0/0/16         down        down        CELL SITE 07
TF0/0/0/17         down        down        CELL SITE 08
TF0/0/0/18         down        down        CELL SITE 09
TF0/0/0/19         down        down        CELL SITE 10
Hu0/0/1/1          down        down        
Hu0/0/1/2          admin-down  admin-down  
Hu0/0/1/3          admin-down  admin-down  
FH0/0/2/2          admin-down  admin-down  
FH0/0/3/0          down        down        

RP/0/RP0/CPU0:R2(config)#do sh interface | i drop

Sun Mar  5 06:33:21.846 UTC

**Comment by ktbyers** [comment]
You shouldn't try to use `send_config_set()` for show commands.

I would look into using a for-loop and send_command() or send_multiline() for what you are trying to do.
