### ISSUE TITLE
Netmiko on python 3.11 timeout exception connecting to Cisco IOS

### ISSUE THREAD

**Issue by JasonTBurns** [ktbyers/netmiko#3138]
![image](https://user-images.githubusercontent.com/127548691/224413141-90bbb6cd-8bf8-4360-bd63-4a71e75d47b1.png)

Hi, I'm seeing the issue in the screenshot above.  I can SSH to this switch just fine from this PC, so there's not a firewall or anything blocking it.  The device type, IP, and port are correct.  Any help determining what I've done wrong would be greatly appreciated!  This is just my second netmiko project so I'm still learning.

Here is the main file so far (this is a work in progress).  It reads a list of switches from an XML file.

import socket
import re
import xml.etree.ElementTree as ET
from switchfunctions import *
from netmiko import ConnectHandler

# Set variables
showLldp = "show lldp"
showIpTracking = "show ip device tracking all"
xml = r"C:\CiscoSwitches\conf.xml"
tree = ET.parse(xml)
root = tree.getroot()
#userName = input("Enter your username (e.g. ): ")
userName = "TEMPORARILY HARDCODED"
password = input("Enter your password: ")

# Gather site data from conf.xml
for switch in root.findall('./switches/'):
    switchName = switch.get('name')
    switchModel = switch.find('model').text
    switchIp = switch.find('ip').text

    if switchModel == "cat2960":
        switchDeviceType = "cisco_ios"
    elif switchModel == "cat9200":
        switchDeviceType = "cisco_xe"
    elif switchModel == "nex3k":
        switchDeviceType = "cisco_nxos"
    else:
        print("\n","Something went wrong with the device detection")
        break
    runcommand(switchIp,userName,password,switchDeviceType,showLldp)

Here is the code from switchfunctions.py (where the netmiko work is done)

# runcommand() sends commands to the switches with variables passed from switchupdate.py
def runcommand(switchIp,userName,password,switchDeviceType,command):
    from netmiko import ConnectHandler
    with ConnectHandler(**con(switchIp,userName,password,switchDeviceType)) as ssh_connection:
        ssh_connection.enable()
        cmdOut = ssh_connection.send_command(command)
        print(cmdOut)
    # print("switch IP: ",switchIp," username: ",userName," password: ",password," device type: ",switchDeviceType," command: ",command)

# con() function sets switch connectivity appropriately
def con(switchIp,userName,password,switchDeviceType):
    switch = {
        "device_type": switchDeviceType,
        "ip": switchIp,
        "username": userName,
        "password": password,
        "secret": password,
        "conn_timeout": "20"
        }
    return switch

**Comment by ktbyers** [comment]
@JasonTBurns Can you enable Netmiko logging and attach the log file to the issue?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by JasonTBurns** [comment]
@ktbyers 
Hi Kirk, I believe I correctly enabled logging but the resulting logfile is empty.  I tried putting the logging setup right under the 'from netmiko...' line as well but this made no difference.

![image](https://user-images.githubusercontent.com/127548691/224704922-7245c564-b9bf-4524-b257-88db5f7e45b5.png)

**Comment by JasonTBurns** [comment]
Any advice/suggestions?

**Comment by ktbyers** [comment]
You are doing the logging after the connection is establish and after the connection is already removed.

I would put all your imports at the top of your program:

```python
# Top of your Python program
# Other Python imports
from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
```

**Comment by JasonTBurns** [comment]
Hi Kirk,

My apologies but I'm very new to this.  I tried putting the logging here and it didn't work either.  I had tried putting it at the top of the runcommand function as well but it was also empty.  Would it be possible for you to tell me exactly what lines the various bits are meant to go in?

![image](https://user-images.githubusercontent.com/127548691/226004408-531983f2-eab1-4638-8922-428c8c209f56.png)
![image](https://user-images.githubusercontent.com/127548691/226005494-80f9882c-e5d6-449f-b92e-04f005611951.png)

**Comment by JasonTBurns** [comment]
I've been messing with this more and can't figure out how to get it to work :(  It may be a fundamental lack of understanding of Python (I just started teaching myself a few weeks ago) or something actually being wrong but I'm not able to determine it on my own.

Any assistance would be greatly appreciated, if I can't get this working soon I'll just have to manually go through a whole mess of switches and make the changes by hand.

**Comment by ktbyers** [comment]
The screenshots are very hard to read...can you switch over to cutting and pasting instead of using screenshots. 

Note, please look up how to format markdown in Github which is enclose your code in `---python` and then end it with `---`.

It will look as follows:

```python
if True:
    # Example code
    print("Hello world")
```

Your original error just looks like a basic TCP connection failure. In the vast majority of the cases, the issue is what it says it is--something is blocking TCP access to the device. I know you mentioned that wasn't the case, but based on my past experience--it still usually is the case, even when people believe it isn't.

Are you still getting the same exception, do you have any host firewall or other host security restrictions on your windows system. Can you disable this (temporarily)?

Have you tried simplifying your Netmiko code to a simple base case--i.e. hard-coded IP address, username, password, simple connection and retrieve some output?

Regards, Kirk

**Comment by JasonTBurns** [comment]
It appears you're right sir.  After doing some more digging, "webroot endpoint protection" is installed and has a local firewall that's blocking it.  I guess it is set to allow Putty/Kitty but not python.

Thanks for the assist, sorry for burning your time on this.
