### ISSUE TITLE
Pattern not detected error for old switches

### ISSUE THREAD

**Issue by msyafiqramlee** [ktbyers/netmiko#3145]
i have this old switches called 3com,  and using hp_comware types to retrieve the output.

However, i notice when i send a command like display interface or display current-configuration, it will gave me the following error:

##################
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: '<switch\\-zone>' in output.   

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

##################

i am able to get the output only when i do some filter for example "display current-configuration | i sysname" but for those long output that require 'space bar' to go to another page seems fail.

How can i troubleshoot further on this error? I tried increase global delay factor, add reading timeout but none seems to be working. I feel like seems it waiting for some of the keystroke to go to the next page before it getting time out, but i just can't figure out how to achieve that. 

The only thing works is when i change from net_connect.send_command to net_connect.send_command_timing but it is only show first page.

**Comment by kacem-expereo** [comment]
Hello,
You'd need to create a function to handle pagination.
Most easy way would be to disable pagination if it's possible.
A google search says that "screen-length disable" could help.
Run it just before your "display current-configuration" and you might get your output in one shot .

**Comment by ktbyers** [comment]
@msyafiqramlee The Comware driver automatically does a `screen-length disable` command.

Does this work on your switch?  (cc @kacem-expereo )

**Comment by msyafiqramlee** [comment]
@kacem-expereo @ktbyers 
The command seems not working as i am getting error when i see the error. The error looks like below. Maybe i should find and send a command to disable the pagination?

<HOSTNAME>
<HOSTNAME>screen-length disable
                    ^
 % Unrecognized command found at '^' position.
<HOSTNAME>
<HOSTNAME>display interface
Aux1/0/0

**Comment by ktbyers** [comment]
@msyafiqramlee Yes, it sounds like your switch must be so old that it doesn't support output pagination. 

So you can do what you did and filter at the device level to make sure output paging doesn't happen. Or you can code in a way to do the output pagination in Netmiko (i.e. send a space bar whenever you hit the `more` output--or whatever is required for this particular switch).
