### ISSUE TITLE
Authentication error while running multi-threaded code 

### ISSUE THREAD

**Issue by asgr8e** [ktbyers/netmiko#3146]
HI @ktbyers I'm working on an IOS upgrade script using netmiko and multi-threading.
the issue is whenever I'm running the script, I'm getting authentication error for most of the devices, only 1 or 2 routers are able to connect and execute the rest of the code. attaching the error screenshot and code as well, need your inputs on the same.
I won't be able to use nornir or other
![1](https://user-images.githubusercontent.com/20974541/227861000-2f823aa0-1c4a-4f64-a460-8f31689ca232.png)
 modules as they are not allowed as per the security protocols, only netmiko is available.

**Comment by ktbyers** [comment]
For a device that failed with threading--does it work using Netmiko (if you do not use threads)?

**Comment by asgr8e** [comment]
Yes it is working fine without threading , I got it resolved with use of a while loop to retry the login for 3 times if failed and break when logged in and proceed forward
