### ISSUE TITLE
Capturing output not working all the time on same device

### ISSUE THREAD

**Issue by robwdwd** [ktbyers/netmiko#3155]
Netmiko version:  4.1.2
Python: 3.10.6

I'm seeing some strange behaviour, we have some devices that are quite distant (but not really that slow) from the server running our script using Netmiko. Sometimes it captures all the output but sometimes it seems to finishes prematurely. I'm not getting any timeout exceptions. The device I'm connecting to is an Cisco IOS-XR device.

Here's the log. The first connection doesn't capture the second captures correctly.

I've played with various timeouts on the connection, conn_timeout, session_timeout, banner_timeout. I've not looking into blocking_timeout yet.

read_timeout in send_command is set to 60 seconds.

This does not happen with just the 'show bop' command I'm seeing it with other commands like 'ping'.

In the working log I see this:

```
  Not advertised to any peer
  15169
    212.74.91.155 (metric 31270) from
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: 212.74.82.142 (212.74.91.155)
      Origin IGP, metric 5, localpref 100, valid, internal
      Received Path ID 0, Local Path ID 0, version 0
```

And non working it does this:

```
  Path #5: Received by speaker 0
  Not advertised to any peer
  15169
    212.74.91.155 (metric 31270) from
DEBUG:netmiko:Pattern found: ([#\$])
BGP routing table entry for 8.8.8.0/24
Versions:
  Process           bRIB/RIB  SendTblVer
  Speaker              14729       14729
Last Modified: Dec 31 05:58:56.982 for 12w6d
Paths: (7 available, best #
DEBUG:netmiko:write_channel: b'exit\n'
DEBUG:paramiko.transport:EOF in transport thread
```

For ping I'm seeing the same and what's strange is netmiko returns the following output from the router:

This on a non-working example return:

```
RP/0/RSP0/CPU0:sr1.CHI#ping 8.8.8.8 source loopback999
```

Working example return.

```
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 8.8.8.8, timeout is 2 seconds:
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 1/1/2 ms
```

Logs attached.

[ping_working.txt](https://github.com/ktbyers/netmiko/files/11122355/ping_working.txt)
[ping_not_working.txt](https://github.com/ktbyers/netmiko/files/11122356/ping_not_working.txt)
[show_bgp_working.txt](https://github.com/ktbyers/netmiko/files/11122357/show_bgp_working.txt)
[show_bgp_non_working.txt](https://github.com/ktbyers/netmiko/files/11122358/show_bgp_non_working.txt)

**Comment by ktbyers** [comment]
@robwdwd In your failing case, it looks like it is matching on a `#` that happens to be in the show-command output:

```
Paths: (7 available, best #
```

Can you try using `send_command()` and an expect_string argument that would work around this?

For example:

```
expect_string="CHI#"
```

**Comment by robwdwd** [comment]
@ktbyers It seems to fail on the ping one as well without the #. 

What I did notice though was setting it up this way seemed to resolve the issue. I did some digging in the code and saw the fast_cli option made the timeouts to short.

        "global_delay_factor": 2,
        "fast_cli": False,

**Comment by ktbyers** [comment]
Yeah, your device seemed pretty slow to respond (for some reason) i.e. Netmiko was getting ahead of your device on the ping so that was causing the problem you saw.

And your above is a reasonable fix for that.
