### ISSUE TITLE
. Increase the read_timeout to a larger value-Python

### ISSUE THREAD

**Issue by ajuarnair** [ktbyers/netmiko#3158]
from netmiko import ConnectHandler  device = {     'device_type': 'cisco_ios',     "ip": "10.154.12.11",     "username": "johor",     "password": "@ma1776",  } net_connect = ConnectHandler(**device)  ntp_config = [      'clock timezone UTC 0', ] output = net_connect.send_config_set(ntp_config, read_timeout=90.0) print(output) net_connect.disconnect()

The above code always give the error , can someone help plz

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

**Comment by ktbyers** [comment]
@ajuarnair Can you post your full exception stack trace?

Also please properly format your code / messages in markdown.

**Comment by ajuarnair** [comment]
[netmiko.txt](https://github.com/ktbyers/netmiko/files/11190488/netmiko.txt)
Attached code for your ref.
I'm running netmiko 4.1.2 latest python:3.11
From the code, if I delete the command write it works fine.

**Comment by ajuarnair** [comment]
That works.Thank you
