### ISSUE TITLE
enable() : 'NoneType' object has no attribute 'rstrip' cisco_ios.

### ISSUE THREAD

**Issue by WestconSamaDevTeam** [ktbyers/netmiko#3164]
Hi,

Recently i've found some issue with Netmiko:

AttributeError: 'NoneType' object has no attribute 'rstrip'

I'm not using rstrip in my code anywhere.

Python 3.10
netmiko 4.1.2

barebones code to reproduce:
```
device = {
            "device_type": "cisco_ios" if useASA == False else "cisco_asa",
            "ip": <ip>,
            "username": <user>,
            "password": <pass>,
            "port": 22,
            "secret": <enable>,
            "conn_timeout": 60,
            "auth_timeout": 60,
            "fast_cli": False, 
            "session_log": "scp-session.log",
}
Connection = Netmiko(**device)
Connection.enable()
```

This issue happens under the conditions device_type = cisco_ios, secret = None, assuming the rest is valid.
Of course it's stupid to set "secret" to None, but it's no help to leave the problem as is imo.

If i use device_type = cisco_asa i get this error message:
netmiko.exceptions.NetmikoAuthenticationException: Unable to enter enable mode!

This is error message would have been much more helpful.

Perhaps even expanding on this you could add a hint in case secret is None saying that this might be a probable cause.

**Comment by ktbyers** [comment]
Can you post the full exception stack trace so I can see where the error occurs at.

Thanks.

**Comment by ktbyers** [comment]
Okay, yeah if you want `secret` to be blank use a null-string i.e. `secret=""`.

Regards, Kirk

**Comment by WestconSamaDevTeam** [comment]
Hi Kirk,

Sure thing, that is a solution for the immediate problem.

First question that comes to my mind in such an answer: 
Is it documented that this value for the attribute secret can't be None?

To give you the whole picture, i didn't come to this problem because i wanted the value to be None or empty, i came to this problem because i couldn't figure out what the problem was from the error message.

I could make a guess that something probably somewhere got the value None that it probably shouldn't have.
But the problem lies in exactly that. Something somewhere is not specific enough.

First i went through our code and found that we did not use that function.
So it's not our code that is the problem you might think.

Then i had to analyze the process flow to find out what was happening and exactly when the problem was showing up.
It's good to have these problems sometimes because it teaches you things about your own system that you possibly hadn't thought of before, or perhaps you did think of them, but you ruled it out because of perhaps how you documented it or trained people on it, or how the software was designed to be used.
But, users always tend to find ways to (ab)use your software in ways that you couldn't envision before it actually happens.

But then, after this analysis i had to write a minimal viable test case to isolate the problem to its core.
And even then, at the end, the error message is still not really covering the actual problem.

The real problem is that there is an attribute named secret that was apparently assigned the wrong value.

That the consequence of that is that function x is unavailable is not really helpfull nor descriptive of the root cause nor is that error message telling me what the name of the attribute is that is having the problem.

A much better error message would have been:
AttributeError (secret): Invalid value assigned (None).

This error message does tell me exactly what the problem is.

You could argue that showing the value that is deemed invalid is a security issue.
And in this specific case it would most likely be an issue because it's a password field, but even without the value the error message is much more descriptive of the problem and that make troubleshooting a lot easier.

This is just my own opinion of course, but i hope it's logical enough to see that perhaps error messaging should not (entirely) be left to Python, as it's error messages are sometimes very high level global and vague.

Kind Regards,
Marco.

**Comment by ktbyers** [comment]
@WestconSamaDevTeam From base_connection.py `__init__` method:

```python
        secret: str = "",
```

The type hint indicates secret should be a string.

You could implement type hinting in your code and it would flagged this as an error (when running `mypy` on your code). Basically `mypy` would have told you that you were setting secret to a type that it is not allowed to be.
