### ISSUE TITLE
Huawei telnet login doesn't handle re grouping properly

### ISSUE THREAD

**Issue by hgqcs** [ktbyers/netmiko#3165]
hi ktbyers:
     I try login huawei device,netmiko  auto send username and password, device response:

```
 ':
Info: The max number of VTY users is 5, the number of current VTY users online is 1, and total number of terminal users online is 1.
      The current login time is 2023-04-14 10:53:30.
<HUWWEI-DEVICE>'
```

 but netmiko raise en error, i look for source code, found it re rule's '(>\s*$|]\s*$|(Change now|Please choose 'YES' or 'NO').+)' and the length of re.split() method is 4, not 3,so it raise error. 
     re pattern include meta code with 

```
()
```

 it should add

```
\
```
 did you think so ?

netmiko version: 4.1.2
source re rule: (>\s*$|]\s*$|(Change now|Please choose 'YES' or 'NO').+)
success login and respose: ':\nInfo: The max number of VTY users is 5, the number of current VTY users online is 1, and total number of terminal users online is 1.\n      The current login time is 2023-04-14 09:43:39.\n<HUWWEI-DEVICE>'
re.split's length: 4
test rule:     combined_pattern = r"({}|{}|{})".format(
        pri_prompt_terminator, alt_prompt_terminator, re.escape(password_change_prompt)
    )
the device list:
model                         system version
CE6865-48S8CQ-EI     Version 8.180
NetEngine 8000          Version 8.191
S12700                        Version 5.170
S9700                          Version 5.160

**Comment by ktbyers** [comment]
@hgqcs Can you post the full Netmiko stack trace to the issue that you are experiencing.

**Comment by hgqcs** [comment]
hi ktbyers:
session_log：
```

Warning: Telnet is not a secure protocol, and it is recommended to use Stelnet.

Login authentication


Username: username
Password:
Info: The max number of VTY users is 10, and the number
      of current VTY users on line is 1.
      The current login time is 2023-04-18 17:51:57+08:00.
<HUAWEI>
<HUAWEI>quit
```


Exception:
```
Unable to successfully split output based on pattern:\npattern=(]\\s*$|>\\s*$|(Change now|Please choose 'YES' or 'NO').+)\noutput=':\\nInfo: The max number of VTY users is 10, and the number\\n      of current VTY users on line is 1.\\n      The current login time is 2023-04-18 17:51:57+08:00.\\n<HUAWEI>'\nresults=[':\\nInfo: The max number of VTY users is 10, and the number\\n      of current VTY users on line is 1.\\n      The current login time is 2023-04-18 17:51:57+08:00.\\n<HUAWEI', '>', None, '']
```

**Comment by ktbyers** [comment]
Okay, this is probably fixed here:

https://github.com/ktbyers/netmiko/pull/3173

**Comment by ktbyers** [comment]
@hgqcs That PR has been merged into the `develop` branch. Can you test the develop branch and verify that it fixed your issue?

**Comment by hgqcs** [comment]
The new code has successfully login the device, thinks!
