### ISSUE TITLE
Catching Command Errors with Netmiko for Cisco Catalysts 9300/9500!

### ISSUE THREAD

**Issue by sindhujit1** [ktbyers/netmiko#3166]
I could not find any exception handling class which catches for errors running commands using netmiko. 

The output returns as a success and shows "% Invalid input detected at '^' marker." , but it does not tell me what exactly failed.

Is there any plan to return status code apart from 200 responses and return the exact error why the command failed !?

**Comment by ktbyers** [comment]
Are you sending configuration commands or something else? Please provide some more details on what your code is doing when this happens.

**Comment by sindhujit1** [comment]
Yes configuration commands. I meant in general like any command, For example if I send "ip **domainnn** lookup source-interface Loopback0", the response returns a success with a response of "% Invalid input detected at '^' marker." around the word domainnn. However if we were to use some API like pyeapi it would return a 400 status code saying what exactly is wrong with that command under the exception "pyeapi.eapilib.CommandError as e:". Wondering if any such exception class was available in netmiko.

**Comment by ktbyers** [comment]
For configuration commands, you can use the `error_pattern` argument to define a regular expression pattern that specifies the error condition.

If error_pattern is encountered Netmiko will raise an exception and stop at the configuration command that failed. I believe the exception includes the command that failed.

For send_command or send_command_timing, it is your responsibility to ensure your commands are valid. You can look at the output of the commands and detect errors from this output including determining the command that failed.

You can also use write_channel() and read_channel() to do whatever you want as far as sending commands and detecting errors.

Obviously, SSH is not an API so errors are not indicated all that well.
