### ISSUE TITLE
delay factor for getting prompt too small

### ISSUE THREAD

**Issue by caibitim** [ktbyers/netmiko#317]
I ran into some issue to get the prompt for hp switches. After I looked into the code for hp_procurve_ssh.py and base_connection.py and found out the reason. Even the code compared the global delay and default delay factor, but the delay is not passed to set_base_prompt() in hp_procurve_ssh.py. In the set_base_prompt(), it can only use the default value,which is 1 sec, as the parameter, and it only waits 0.1 seconds to get the prompt. In my case, the device takes a little longer than 0.1 to read the prompt. 

we can either change .1 to .5 or 1 to wait longer for get the prompt, or passing the delay to set_base_prompt after select_delay_factor.

Another thing I don't quite understand is why the select_delay_factor is not implemented in base_connection. it sounds like a basic feature for all kinds of devices

**Comment by ktbyers** [comment]
@caibitim There are no sleeps in set_base_prompt(). set_base_prompt() calls find_prompt() and find_prompt() does the following:

```
511     def find_prompt(self, delay_factor=1):
512         """Finds the current network device prompt, last line only."""
513         debug = False
514         delay_factor = self.select_delay_factor(delay_factor)
```

i.e. it will get the larger of global_delay_factor() and local delay_factor() so if you want to increase the sleep time, then increase the global_delay_factor to be something greater than 1.

Also find_prompt() has a while loop so it should wait up to 1 second by default (so it would be strange that you couldn't get a prompt back after a second). Though it is possible you got some partial data back which would cause it fall out of the while loop.

I don't understand what you mean by, "I don't quite understand is why the select_delay_factor is not implemented in base_connection"? select_day_factor is implemented in base_connection.py? It is both defined in base_connection.py and called numerous times in base_connection.py?

**Comment by caibitim** [comment]
sorry my bad,I didn't notice there is select_delay_factor in find_prompt. please ignore my last question

`time.sleep(delay_factor * .1)`
after I changed this to `time.sleep(delay_factor * 1)` it starts working fine. I think it only waits 0.1 second for the prompt here. For the for loop, it looks like it tries 10 times for 0.1 second, not 1 second.

I pretty sure I get nothting since I got the "unable to find prompt" not partial of the hostname, and it is judeged by 
`        if not prompt:`

**Comment by ktbyers** [comment]
@caibitim 

Here is the while loop:

```
593         while count <= 10 and not prompt:
594             prompt = self.read_channel().strip()
595             if prompt:
596                 if debug:
597                     print("prompt2a: {}".format(repr(prompt)))
598                     print("prompt2b: {}".format(prompt))
599                 if self.ansi_escape_codes:
600                     prompt = self.strip_ansi_escape_codes(prompt).strip()
601             else:
602                 self.write_channel("\n")
603                 time.sleep(delay_factor * .1)
604             count += 1
```

It will loop eleven times each time sending a newline and waiting .1 seconds. If your prompt comes back as empty (for all of this) that means you never got any data back for the eleven newlines and 1.1 seconds of waiting.

You can modify the behavior without modifying the code by setting global_delay_factor in the Netmiko ConnectHandler call. Default value of this is 1. So setting it to 2 will double the delay; 4 will quadruple the delay.

Is there anything you see when you manually login that indicates this device is slow to authenticate?

It would be interesting to know if you pass using a:

```
time.sleep(delay_factor * .2)
```

Or possibly .3 / .4 i.e. do we need just a little more delay or a lot more delay.

**Comment by caibitim** [comment]
I manually login to the device and notice every time I hit enter, it takes around 0.5 sec to get the prompt. I think that's the reason why I can not get the prompt with the for loop. From my perspective, the biggest problem for this for loop is it waits 0.1 second for 11 times. If it takes 0.5 second to get prompt, it will just fail. I think that would be better if we can increase the coefficient as the loop grows. like 1st loop 0.1 second, 2nd 0.2 second 3rd for 0.3 second.

**Comment by ktbyers** [comment]
@caibitim Given what you said here, then it should work if you commented out line 602 above. Does it work if you do this?

```
601             else:
602  ####               self.write_channel("\n")
603                 time.sleep(delay_factor * .1)
604             count += 1
```

Comment out the sending of the newline.

**Comment by ktbyers** [comment]
@caibitim Any update on my above questions?

**Comment by caibitim** [comment]
Sorry, I was tied up by something else for last few days. 

I couldn't comment line 602 to see if it works anymore, since I've finished the project for configuration backup of that client. Currently, everything is up and running after I change .1 to 1 second, the script is scheulded to login the device every 7 days. I can try your method if I run into this issue in the future.

Hope you can understand.

**Comment by ktbyers** [comment]
It is all good.
