### ISSUE TITLE
SyntaxError: name 'newname' is assigned to before global declaration

### ISSUE THREAD

**Issue by mikenugs** [ktbyers/netmiko#3178]
I am getting a SyntaxError: name is assigned to before global declaration. Oddly enough this code works fine when for some IOS devices and then fails another. Any idea why this is failing?

mike@RTMMIS60-L:~$ python3 cm1-infra-chk.py
Traceback (most recent call last):
  File "/home/mike/cm1-infra-chk.py", line 5, in <module>
    from csco_int_chk import intchk
  File "/home/mike/csco_int_chk.py", line 11
    global newname
    ^^^^^^^^^^^^^^
SyntaxError: name 'newname' is assigned to before global declaration
mike@RTMMIS60-L:~$

`mike@RTMMIS60-L:~$ cat cm1-infra-chk.py
import os
from pprint import pprint
from netmiko import ConnectHandler
from csco_cpu_chk import showcpu
from csco_int_chk import intchk
from csco_ver_chk import showver
from csco_mod_chk import showpla
from cm1_devices import devices

for device in devices:
    net_connect = ConnectHandler(**device)
    show_ver = net_connect.send_command('show version', use_textfsm=True)
    showver(show_ver)
    show_cpu = net_connect.send_command('show processes cpu', use_textfsm=True)
    showcpu(show_cpu)
    show_pla = net_connect.send_command('show platform diag', use_textfsm=True)
    showpla(show_pla)
    show_int = net_connect.send_command('show interface status', expect_string=r"#", use_textfsm=True)
    intchk(show_int)
mike@RTMMIS60-L:~$ cat csco_int_chk.py
intfc = 'Interface'
descr = 'Description'
opera = 'Status'
def intchk(showint):
    print('{:12}{:20}{}'.format(intfc, descr, opera))
    for line in showint:
         for k, v in line.items():
             if v != '':
                 if k == 'name':
                     newname = v
                 if k == 'port':
                     newport = v
                 if k == 'status':
                     newstatus = v
                     print('{:12}{:20}{}'.format(newport, newname, newstatus))
mike@RTMMIS60-L:~$`

**Comment by ktbyers** [comment]
Your error looks like it is in this file:

```
  File "/home/mike/csco_int_chk.py", line 11
    global newname
```

**Comment by mikenugs** [comment]
I tried adding the global to the variable in an attempt to resolve the issue with no luck. Even with removing that for some reason the code works perfectly fine on one of my IOS devices and fails on another. Here is that file that you referenced with the error. Any idea what could be causing this?
`intfc = 'Interface'
descr = 'Description'
opera = 'Status'
def intchk(showint):
    print('{:12}{:20}{}'.format(intfc, descr, opera))
    for line in showint:
         for k, v in line.items():
             if v != '':
                 if k == 'name':
                     newname = v
                 if k == 'port':
                     newport = v
                 if k == 'status':
                     newstatus = v
                     print('{:12}{:20}{}'.format(newport, newname, newstatus))`

**Comment by ktbyers** [comment]
Initialize:

```python
def intchk(showint):
    newname = ""
```

At the top of your code so you don't try to use it before you give it a value.
