### ISSUE TITLE
Performance improvements needed

### ISSUE THREAD

**Issue by HaiderNL** [ktbyers/netmiko#3181]
Hi Kirk,
Thanks your awesome tutorial, I've written a script that sends out the outcome of multiple show commands of cisco ios devices.
Yet I think it's a bit slow. It takes 2s to show up at every device.
Are there some magic tweaks and tunes to improve the performance ?
I've been told; No. Better moving to Nornir
I appreciate your idea

`from netmiko import Netmiko

with open('addresses.txt') as f1:
    file1 =f1.read().splitlines()

with open('commands.txt') as f2:
    file2 =f2.read().splitlines()

for device in file1:
    dict = {'device_type':'cisco_ios',
       'ip':device,
       'username':'user1',
       'password':'secret1'
    }
        ssh = Netmiko(**dict)
        for cmd in file2:
            output = ssh.send_command(cmd)
            print(output)`

**Comment by ktbyers** [comment]
2s seems pretty fast. I guess you can try tweaking global_delay_factor down to .05 or .01 (but your code might also break) and performance improvements will be very marginal.

If you have multiple devices, then you should use threading (either through Nornir) or through your own threading solution. That should let you do multiple devices concurrently in roughly the same amount of time.
