### ISSUE TITLE
Spin a release for Arista prompt issue?

### ISSUE THREAD

**Issue by tlaberge-godaddy** [ktbyers/netmiko#3185]
I see https://github.com/ktbyers/netmiko/pull/2944 was merged some time ago. We encounter this issue fairly frequently in production, is there a plan to spin a release that contains it soon?

**Comment by ktbyers** [comment]
It is on my todo list, but I also have too many things on said list.

You can always just install Netmiko directly from Github using PIP (pinned to a specific commit)...so I don't think I should be a bottleneck here (i.e. there is a pretty easy way for you to solve this).

**Comment by tlaberge-godaddy** [comment]
That will work, good luck on trimming your todo list!

**Comment by ktbyers** [comment]
@tlaberge-godaddy I managed to get this done this week. So Netmiko 4.2.0 is now up on pypi.

Regards, Kirk
