### ISSUE TITLE
Is my threading working properly?

### ISSUE THREAD

**Issue by hfakoor222** [ktbyers/netmiko#3187]
I've tried various formats from context managers, to threading.Thread and see no improvement. I have commands split across different classes. Each class holds about 20 commands or so. I run the threads against an individual class for testing, as so far there are actually only 2 command classes (and a ConnectHandler class).  I'm using 5-6 devices. So basically runing about 20 show commands on 5 devices, I see no improvement of threads vs non threading. I have a suspicion I may be doing something wrong.

Here is the latest iteration, where I call the connect_parser function under main. The inlist= sys.argv[1] is the class list I pass in the CLI, to choose which classes to run. So far I have only 2 classes, and notice no difference when using threads. One class is an OSPF show command trouble shoot, other is a Hardware class which diagnoses cabling, bfd, memory etc via show commands.

Heree is the code:
thread_pool=[]
class Connect:

    def __init__(self,):
        intake_file = open('ip_list.txt', 'r')
        self.json_data = [json.loads(line) for line in intake_file]
        pass
    def connect_parser(self, inlistx=[]):

        for data in self.json_data:
            ip = data["ip"]
            # port = data["port"]
            username = data["username"] if data["username"] else ""
            password = data["password"] if data["password"] else ""
            secret = data["secret"] if "secret" in data else False
            device_type = data["device_type"] if data["device_type"] else ""

            if data["header"] == "Netmiko":
                print("The variables being passed:  " + ip, username, password, device_type)
                ConnectHandler = netmiko.ConnectHandler(
                    device_type=device_type,
                    host=ip,
                    username=username,
                    password=password,
                    port=22,
                    secret=data["secret"] if "secret" in data else False
                )
                if ConnectHandler:
                    try:
                        ConnectHandler.enable()
                    except Exception as e:
                        print("Could not connect to {}".format(ip))
                for i in inlistx:
                    th = threading.Thread(target=i(ConnectHandler))
                    thread_pool.append(th)
                    th.start()

                for some_thread in threading.enumerate():
                    if some_thread != th:
                        print(some_thread)
                        some_thread.join()

if __name__ == "__main__":
    from Connect_Handler import Hardware, OSPF
    from Connect_Handler import Connect
    inlist = sys.argv[1]
    outlist = inlist.split(",")
    result = [i.strip("[]") for i in outlist]
    inlist = []
    for i in result:
        inlist.append(functions[i])
    Connector = Connect()
    print(time.perf_counter())
    # print(time.perf_counter())
    Connector.connect_parser(inlist)
    print(time.perf_counter())
    print(time.perf_counter())

**Comment by ktbyers** [comment]
Not really an appropriate question for here.
