### ISSUE TITLE
Cisco IOS 'send_config_from_file' error

### ISSUE THREAD

**Issue by JesusPavonCBRE** [ktbyers/netmiko#3188]
Hi there,
I'm having an issue when sending any file to push configuration to a Cisco C9800 box.
The task is completed but with no effect due to the addition of extra words as sufixes (Attached the file with the config and the relevant script lines)
Using Python==3.11 with pip==23.1.2 and netmiko==4.1.2

```
_gbrdcwlcs001#configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
gbrdcwlcs001(config)#o;?
object-group  onep  otv  overlay

gbrdcwlcs001(config)#o;
% Ambiguous command:  "o;"
gbrdcwlcs001(config)#ap 0000.1111.2222
gbrdcwlcs001(config-ap-tag)#no ap 0000.1111.2222
Removing named tag mapping will result in the AP rejoin
gbrdcwlcs001(config)#end
gbrdcwlcs001#write mem
Building configuration...
[OK]
Writing gbrdcwlcs001-May--3-2023-18-11-35.517-UTC-65 
```
[wlc_commands.txt](https://github.com/ktbyers/netmiko/files/11389633/wlc_commands.txt)
[_simple_script.txt](https://github.com/ktbyers/netmiko/files/11389650/_simple_script.txt)

**Comment by ktbyers** [comment]
Can you expand here on what your issue is?

Also what settings do you have for `device`?

The only weird thing I see above is the extra `o;`, but it also doesn't seem to be affecting anything i.e. the commands in your config file are being properly sent.

**Comment by JesusPavonCBRE** [comment]
I found the isssue was saving the TXT file with EOL in Windows style and not Unix
