### ISSUE TITLE
Cisco WLC -> cannot find prompt issue

### ISSUE THREAD

**Issue by boneworker** [ktbyers/netmiko#319]
I have the following issue when login into our Cisco WLCs:
[xxxxxx@localhost ~]$ python test.py xx.xx.xx.xx user 'password'
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    net_connect = ConnectHandler(**cisco_2504)
  File "build/bdist.linux-x86_64/egg/netmiko/ssh_dispatcher.py", line 96, in ConnectHandler
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 90, in __init__
  File "build/bdist.linux-x86_64/egg/netmiko/cisco/cisco_wlc_ssh.py", line 100, in session_preparation
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 504, in set_base_prompt
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 549, in find_prompt
ValueError: Unable to find prompt: 

For our customer we are using a login banner on the WLC. 
I believe that this banner is too larger for finding the prompt.

I believe that in the following file
/netmiko/cisco/cisco_wlc_ssh.py

the 
      while i <= 12: 
needs to be changed to a bigger value like:
      while i <=24; 

/netmiko/cisco/cisco_wlc_ssh.py
...
Password:****
        '''
        delay_factor = self.select_delay_factor(delay_factor)
        i = 0
        time.sleep(delay_factor * .5)
        output = ""
        -->while i <= 12:<--
            output = self.read_channel()
            if output:
                if 'login as' in output or 'User' in output:
                    self.write_channel(self.username + '\n')
                elif 'Password' in output:
                    self.write_channel(self.password + '\n')
                    break
                time.sleep(delay_factor * 1)
            else:
                self.write_channel('\n')
                time.sleep(delay_factor * 1.5)
            i += 1
...

Unfortunately i am new to python and have no idea on how to change this on my own.

Who can help ??
  
With regards,
Frank

**Comment by ktbyers** [comment]
@boneworker Does it work if you increase that from 12 to 24. On the face of I don't see why you would need to do this?

It is waiting at least 12 seconds and reading 12 * 64Kbytes of data.

**Comment by boneworker** [comment]
Hello ktbyers, 

i have tried to change that value in the files i can access but it has not helped. 

/usr/local/netmiko/netmiko/cisco/cisco_wlc_ssh.py
/usr/local/netmiko/build/lib/netmiko/cisco/cisco_wlc_ssh.py

Like written, i am new to Python (have used Perl at lot but now want to go deeper into Python) and have no clue if I would need to do the update/change in the egg file. No idea how to do that to be honest.

Fact is that a Cisco WLC without Banner let me in, a WLC with Banner does not let me in because the prompt can not be found.

This is my testprogram:

[xxx@localhost ~]$ cat firsttest.py
from netmiko import ConnectHandler
import sys

print(sys.argv[0])
print(sys.argv[1])
print(sys.argv[2])
print(sys.argv[3])

cisco_2504 = {
	'device_type': 'cisco_wlc',
	'ip': sys.argv[1],
	'username': sys.argv[2],
	'password': sys.argv[3],
}

net_connect = ConnectHandler(**cisco_2504)

output = net_connect.send_command('show interface summary')
print(output)

[xxx@localhost ~]$ 


Here is how the banner/SSH login looks like:
****** Template xxx  5508/2504/WISM2/7500                        *********
*Warning Notice:                                                   ***** *
*  This system is restricted solely to xxxx authorized users for legit-   *
*  imate business purposes only. The actual or attempted unauthorized     *
*  access, use, or modification of this system is strictly prohibited     *
*  by xxxx.  Unauthorized users are subject to Company disciplinary pro-  *
*  ceedings and/or criminal and civil  penalties under state, federal     *
*  or other applicable domestic and foreign laws. The use of this system  *
*  may be monitored and recorded for administrative and security reasons. *
*  Anyone  accessing this system expressly consents to such monitoring and*
*  is advised that if monitoring reveals possible evidence of criminal    *
*  activity, xxxx may provide evidence of such activity to law enforcement*
*  officials. All users must comply with xxxx company policies regarding  *
*  the protection of xxxx information assets.                             *
****** Template xxx  5508/2504/WISM2/7500                        *********

(abc-de-efg)
User:

With regards,
Frank

**Comment by ktbyers** [comment]
@boneworker Does it work if you add more delay (i.e. global_delay_factor argument)?

```
cisco_2504 = {
'device_type': 'cisco_wlc',
'ip': sys.argv[1],
'username': sys.argv[2],
'password': sys.argv[3],
'global_delay_factor': 4,
}
```


Kirk

**Comment by boneworker** [comment]
Hello Kirk,

yes, that solved it :-)
Even with a delay factor of 2 it works.

Many thanks for your help.

With regards,
Frank
