### ISSUE TITLE
check_config_mode '(config' string will fail for Cisco IOS and potentially other vendors

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#32]
Potentially use ')#' as a solution.

Look at what HP ProCurve does in config mode and wider sample of what Cisco does.

**Comment by ravenblue12** [comment]
use prompt[-2:] == ')#' or we distinguish between context switch prompt and context prompt as you suggest.

**Comment by ktbyers** [comment]
Some HP examples
twb-sf-hpsw1(config)# 
twb-sf-hpsw1(vlan-1)# 

Some Cisco examples
twb-sf-uc520(config)#
twb-sf-uc520(config-if)#
twb-sf-uc520(dhcp-config)#
twb-sf-uc520(config-ext-nacl)#
