### ISSUE TITLE
I'm trying to use fortinet_ssh.py like this, but are there any other issues?

### ISSUE THREAD

**Issue by doohyunnoh84** [ktbyers/netmiko#3204]
When using post banner, (Press 'a' to accept):, socket closed continued even when using modified distribution. It's not accurate when I checked, but we used '#' and '' (space) in the banner, so it seems that the banner's content only # entered in the data(variable), so it didn't work.
Will there be a problem when I modify the code as below?
After that, the show operation seems to be normal.

banner example >
#################
warning ~~~~.             #
~~                                 #
~~                                 #
#################

(Press 'a' to accept):

fortinet_ssh.py>
as-is
data = self._test_channel_read(pattern=f"to accept"|{self.prompt_pattern})
to-be
data = self._test_channel_read(pattern=f"to accept")

**Comment by ktbyers** [comment]
@doohyunnoh84 I am not sure I understand your question? Are you getting an exception/error in this case?

Which version of Netmiko are you using?
