### ISSUE TITLE
Regex Fix in ciena_saos.py

### ISSUE THREAD

**Issue by ajdollens** [ktbyers/netmiko#3208]
Discovered bug preventing router prompt from ever being matched if hostname is longer than one character. On line 30 of ciena_saos.py. . As of now raises error "Router prompt not found:" despite router prompt being found if you look at logs. Regex pattern should read as follows in order to match for hostname of any length

Should BE:
pattern = rf"^.*+{self.prompt_pattern}$

Existing:
pattern = rf"^.+{self.prompt_pattern}$"

**Comment by ktbyers** [comment]
@ajdollens ???

The existing pattern is: `^.+` (which is any character repeated one or more times).

I don't see any need for the `*` character.

**Comment by ktbyers** [comment]
It was probably just this issue:

https://github.com/ktbyers/netmiko/pull/3214/files

Let me know if there is some other problem...though.
