### ISSUE TITLE
Connect to device using intermediate without ssh config

### ISSUE THREAD

**Issue by Prov-RafaelSavoy** [ktbyers/netmiko#3213]
HI, im developing a system to get a device configuration to backup him.

I really like netmiko, but it dont have the easy way to connecto to device using tunnel like paramiko

**Comment by ktbyers** [comment]
@Prov-RafaelSavoy Can you show how you connect with Paramiko?

**Comment by Prov-RafaelSavoy** [comment]
> @Prov-RafaelSavoy Can you show how you connect with Paramiko?

Of course!

First, i connect to gateway device and return the channel of him

`def getGatewayChannel(self):
        gateway = paramiko.SSHClient()
        gateway.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        gatewayError = GatewayError()
        
          gateway.connect(
              self.deviceInfo.gateway.host,
              self.deviceInfo.gateway.port,
              self.deviceInfo.gateway.user,
              self.deviceInfo.gateway.password,
              look_for_keys=False, allow_agent=False
          )
          gateway_transport = gateway.get_transport()

          addr = (self.deviceInfo.host, self.deviceInfo.port)

          channel = gateway_transport.open_channel(
              "direct-tcpip", dest_addr=addr, src_addr=addr, timeout=10
          )
         return channel
         
         `
        
        After, i connect to final device passing the gateway like sock
        
        `
         device.connect(
                hostname=self.deviceInfo.host,
                port=self.deviceInfo.port,
                username=self.deviceInfo.user,
                password=self.deviceInfo.password,
                sock=gateway_channel,
                timeout=5,
                look_for_keys=False, allow_agent=False,
            )
            `

**Comment by ktbyers** [comment]
Netmiko does support a `sock` parameter, but you would have to establish/create the tunnel outside of Netmiko (i.e. using Paramiko).

The other way you could do this is just bounce through boxes i.e. `SSH using Netmiko to the intermediate device` and then execute `ssh end_system` using Netmiko.

You would need to handle the SSH authentication for this final connection.

Once you are connected to the end box, you would then execute the Netmiko `redispatch` method to switch the device_type to the proper Netmiko class for the end device.

**Comment by ktbyers** [comment]
I didn't understand your statement here?

**Comment by Prov-RafaelSavoy** [comment]
The netmiko is beautiful because already have 99% of my problem ready, i need to connect to many devices in my database, devices with different models. But some of this devices need connect in another devices before connect to him. I already make this only using paramiko and telnetlib, but this is complicated when i need transform output from some commands in "clean" texts, and this is easy with netmiko. But i have problem to make a tunnel in another device with a simple way with netmiko, i passed the sock argument to the device param, but returned me a error if i make like this:

`import netmiko

gateway = {
    "device_type": "mikrotik_switchos",
    "host": "gateway",
    "username": "gatewayusername",
    "password": "gatewaypassword",
    "session_log": "session.txt",
    "port": 22,
    "verbose": True,
}

device = {
    "device_type": "huawei",
    "host": "deviceip",
    "username": "deviceusername",
    "password": "devicepassword",
    "session_log": "session.txt",
    "port": 22,
    "verbose": True,
    "sock": gateway
}

with netmiko.ConnectHandler(**device,sock=gateway) as conn: 
    output = conn.send_command('dis cu')
        `

**Comment by ktbyers** [comment]
Yeah, I am not clear on what your question to me is?

**Comment by Prov-RafaelSavoy** [comment]
How to connect to the end device passing through an intermediary device

**Comment by Prov-RafaelSavoy** [comment]
When i use paramiko, return this error
``
Traceback (most recent call last):
  File "/home/rafael/Backups/provbkp_oldfiles/teste/netmikotest.py", line 30, in <module>
    net_connect = ConnectHandler(**device)
  File "/home/rafael/.local/lib/python3.10/site-packages/netmiko/ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/rafael/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 439, in __init__
    self._open()
  File "/home/rafael/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 444, in _open
    self.establish_connection()
  File "/home/rafael/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 1046, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/rafael/.local/lib/python3.10/site-packages/paramiko/client.py", line 430, in connect
    t.start_client(timeout=timeout)
  File "/home/rafael/.local/lib/python3.10/site-packages/paramiko/transport.py", line 704, in start_client
    raise e
  File "/home/rafael/.local/lib/python3.10/site-packages/paramiko/transport.py", line 2088, in run
    self.packetizer.write_all(b(self.local_version + "\r\n"))
  File "/home/rafael/.local/lib/python3.10/site-packages/paramiko/packet.py", line 361, in write_all
    raise EOFError()
EOFError
``

**Comment by ktbyers** [comment]
@Prov-RafaelSavoy I stated it above, but I guess you don't want to do that.

Your `gateway` is just a dictionary (i.e. is not a `sock`), you would need to use `gateway` device in Netmiko to connect and then access the paramiko object (probably `netmiko_obj.remote_conn`). Once you have the paramiko object on the intermediary device, then you would need to repeat some of the steps to create and pass back the `sock`.

But that all being said, the standard way to do this in Netmiko is:
1. SSH config file.
2. SSH to intermediary device using Netmiko and then connect to end device and `redispatch`

**Comment by Prov-RafaelSavoy** [comment]
Okay, I get the idea, I'll see what I can do. Thank you very much.

**Comment by ktbyers** [comment]
Let me know if you are able to get it working or need more assistance on it :-)
