### ISSUE TITLE
How to handle timing when there is no data in the channel

### ISSUE THREAD

**Issue by germs2611** [ktbyers/netmiko#3224]
Am writing a script to update firmware on Cisco ( IOS XE) 9300 and 9400 switches.

Am running the command "install remove inactive"  and expect_string=[y/n] to remove inactive packages and files after a new firmware is installed. The thing is, after the command is executed there is a period of about 2 minutes when there is no data in the channel.

The expect_string argument pattern will always NOT be detected hence a ReadTimeout error. If I use time.sleep(120) it will work but I want to know how to programmatically (probably using a while loop with find_prompt() ) code it so has not to use time.sleep() because the timing on different device models will be different.

command = 'install remove inactive'
        net_connect = ConnectHandler(**device)
        print(f"Removing inactive files  on {device['host']} to prevent clutter... Please wait")
        net_connect.send_command(command, read_timeout=300, expect_string='[y/n]')
        time.sleep(120)
        net_connect.send_command('y')

**Comment by ktbyers** [comment]
```
The expect_string argument pattern will always NOT be detected hence a ReadTimeout error.
```

Why will the expect_string argument NOT be detected?

Note, in regular expressions--the below is not what you think it is:

```
[y/n]
```

In regex you are making a character class consisting of `y, n, and forward-slash` (and looking for any occurrence of any of those characters).

**Comment by germs2611** [comment]
> ```
> The expect_string argument pattern will always NOT be detected hence a ReadTimeout error.
> ```
> 
> Why will the expect_string argument NOT be detected?
> 
> Note, in regular expressions--the below is not what you think it is:
> 
> ```
> [y/n]
> ```
> 
> In regex you are making a character class consisting of `y, n, and forward-slash` (and looking for any occurrence of any of those characters).


This is the prompt:

Do you want to remove the above files? [y/n]

Can you suggest and expected string format?
