### ISSUE TITLE
ModuleNotFoundError: No module named 'netmiko'

### ISSUE THREAD

**Issue by JimmyLi000** [ktbyers/netmiko#3241]
Python 3.10.1 and netmiko 4.2.0 have been installed , and the following problems are displayed after execution.

from netmiko import ConnectHandler
ModuleNotFoundError: No module named 'netmiko'

# code
from netmiko import ConnectHandler

device = {
    'device_type': 'cisco_ios',
    'ip': 'xx.xx.xx.xx',          # 交換機的IP地址
    'username': 'xxxx',  # 交換機的登錄用戶名
    'password': 'xxxx',  # 交換機的登錄密碼
    'secret': 'xxxx', # 啟用模式的密碼
}

net_connect = ConnectHandler(**device)

net_connect.enable()

vlan_commands = [
    'vlan 30',
    'name sale',
    'int vlan 30',
    'ip address 10.10.10.30 255.255.255.0',
    'no shutdown',
    'exit',
   
]

output = net_connect.send_config_set(vlan_commands)

print(output)

net_connect.disconnect()

# error

from netmiko import ConnectHandler
ModuleNotFoundError: No module named 'netmiko'

![1](https://github.com/ktbyers/netmiko/assets/102612222/46b8334e-ecfa-417d-95fb-7fa8933155e6)

**Comment by ktbyers** [comment]
The Python you are using doesn't have Netmiko installed. You should double check the Python that is being used.

**Comment by nullbitzero** [comment]
Hi,

As indicated by @ktbyers "You should double check the Python that is being used" and if you are using Windows, execute the command in cmd: "pip install netmiko" or "pip install netmiko -U"

regards.
