### ISSUE TITLE
Ericsson_mltn63XX changes prompt

### ISSUE THREAD

**Issue by nbaranov** [ktbyers/netmiko#3244]
I tried to use netmiko for send_commnad or send_multiline to ericsson_mltn63

But i got an error:
```
netmiko.exceptions.ReadTimeout:
Pattern not detected: 'ML6352\\[VVS\\ to\\ Golubi\\ Dali\\]\\#' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

It's happen because ericsson  mltn changes prompt string after input configuration commands.
For example:
```
ML6352[Golubidali to VVS]# config cos queue-profile queue_profile_new

ML6352[Golubidali to VVS](config-cos-queue-profile)#
```

I fixed it added expect_string:
```
import re
prompt = ericsson_ne.find_prompt()
fixed_prompt = re.escape(prompt[:-1]) + ".*\\#" 
output = ericsson_ne.send_multiline(commands_list, expect_string=fixed_prompt)

```

But i think it fix need to add to the library.

**Comment by ktbyers** [comment]
@nbaranov You should use `send_config_set` for any configuration changes (and not send_command nor send_multiline).

send_command and send_multiline should generally be used for show commands and not config changes.

**Comment by nbaranov** [comment]
Okay.
