### ISSUE TITLE
Guess device type using SNMP

### ISSUE THREAD

**Issue by maximumG** [ktbyers/netmiko#325]
Hello,

I just found out about your wonderful Paramiko wrapper and I am currently reading the code to understand the library. I come from the 'Exscript' project and might rather switch to Netmiko because of its support on Python3.

**What I am missing in netmiko is the ability to auto guess the device type, which Exscript is doing as best as it can**.

As mentioned in issue #259, I'd like to work on a separate module/class that will try to auto guess the device type prior to create a new *BaseConnection* object from the *ConnectHandler* function. The auto guessing will use SNMP (v1/v2/v3) to:

* Gather SysDescr object from MIB-2
* Based on defined regular expression, filter SysDescr and associate this with a netmiko device_type

Are you interested in this enhancement ?

**Comment by ktbyers** [comment]
@maximumG Which SNMP library are you planning on using? Are you open to using pysnmp?

I have some SNMP helper code for pysnmp here.

https://github.com/ktbyers/pynet/blob/master/snmp/snmp_helper.py

And here is an example getting sysDescr:

https://github.com/ktbyers/pynet/blob/master/appliedpy_ecourse/class1/ex2_simple_snmp.py


I am probably open to this.

**Comment by bbkane** [comment]
Also very interested in this.

**Comment by maximumG** [comment]
@ktbyers. I'm almost done writing this 'add-on'. Basically it is compatible with SNMPv2 and V3 (thanks to your helper function).

Unfortunately I don't have access to the *SysDescr* of all devices type that Netmiko supports (Cisco IOS, IOS-XE, ASA, NX-OS, WLC, F5). Some people will need to update my auto guessing module if they do have access to the missing device type.

**Comment by ogenstad** [comment]
If you want to you can use the hostinfo function from my nelsnmp lib:

https://networklore.com/nelsnmp-hostinfo/

`pip install nelsnmp`

``` python
>>> from nelsnmp.snmp import SnmpHandler
>>> from nelsnmp.hostinfo.device import HostInfo
>>> dev = SnmpHandler(host='172.29.52.34', version='2c', community='cisco')
>>> hostinfo = HostInfo(dev)
>>> hostinfo.get_version()
>>> print(hostinfo.vendor)
cisco
>>> print(hostinfo.os)
ios
>>> print(hostinfo.version)
15.0(2)SE4
>>>
```

**Comment by maximumG** [comment]
@ogenstad : seems to be a interesting lib. 
However I prefer not to use it for now as netmiko dependency might grow to much. 

@ktbyers : which way do you prefer to handle SNMP query for the OSGuesser ? If you prefer to use *nelsnmp* I can modify the code easily.

**Comment by ktbyers** [comment]
@maximumG Let me review what you have. I probably prefer your current solution, but I have only quickly glanced at it.

**Comment by ktbyers** [comment]
We implemented a PR on this...so closing this issue.
