### ISSUE TITLE
Huawei 6680 firewall IOError: Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by benjaminbudts** [ktbyers/netmiko#326]
>>> from netmiko import ConnectHandler
>>> net_connect = ConnectHandler(device_type='huawei', ip='10.0.89.2', username='xxx', password='xxxxxxxxxx')
>>> net_connect.find_prompt()
u'HRP_A<ACTIVE>'         ---------> we got an active standby configuration
>>> output = net_connect.send_command("display ip int brief")     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 673, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: HRP\_A\<ACTIVE\>

**Comment by ktbyers** [comment]
@benjaminbudts What does this look like when you manually do it i.e. if you manually SSH in and do:

```
display ip int brief
```

**Comment by ktbyers** [comment]
@benjaminbudts Just re-open this if you are still having an issue.
