### ISSUE TITLE
Connection to Juniper SRX with limited permissions

### ISSUE THREAD

**Issue by czkoudy** [ktbyers/netmiko#3263]
Hi,

I am trying to automate certain things for our customer. I need to print all security policies. 

I have a user login which has enough to do so.

However i dont have enough permissions to go to config mode.

This is the output from the session_log

```
{primary:node0}
user@node> 

{primary:node0}
user@node> 

{primary:node0}
user@node> set cli
                                   ^
syntax error, expecting <command>.

user@node> set cli   screen-width
                                   ^
syntax error, expecting <command>.

user@node> set cliscreen-width   511
                                   ^
syntax error, expecting <command>.

{primary:node0}
user@node> 

{primary:node0}
user@node> 
```

can i achieve this printout without asking for ```set cli``` permissions? I guess somehow bypassing ```session_preparation```?

Thank you

EDIT: netmiko==4.1.2

**Comment by ktbyers** [comment]
@czkoudy Juniper driver and Netmiko doesn't really work properly without these things.

You could try the `generic` device_type and see if you can get away with it. The `generic` driver won't do anything post login. You can see if you can make this work (well enough).

**Comment by czkoudy** [comment]
yeah i thought that might be the case :-) 

Thanks for your help. Ill try to get the permissions sorted first 👍
