### ISSUE TITLE
Modify the  file_tranfer support with huawei,Whether  can be updated into your code?

### ISSUE THREAD

**Issue by ranmaolin** [ktbyers/netmiko#3265]
Hi
im using the file_transfer of netmiko to upload files for huawei devices, i found it not support huawei platform,so i modified some codes to support this function, Whether it can be updated into your code?
pypi_url:https://pypi.org/project/huawei-file-transfer/
github_url:https://github.com/ranmaolin/huawei_file_transfer

thanks

**Comment by ktbyers** [comment]
Yes, it looks like there is no existing support for Huawei and File Transfer in Netmiko (so someone would need to implement it and submit a PR to Netmiko on this).


Regards, Kirk
