### ISSUE TITLE
unable to enter command on huawei device

### ISSUE THREAD

**Issue by MgOmbodorj** [ktbyers/netmiko#327]
after i enter commands ,below error occured.
**Commands:**
device1.config_mode
output1 =  device1.send_command('?')
print output1

**Error:**
IOError: Search pattern never detected in send_command_expect: \\<test\\-1\\>

**Comment by ktbyers** [comment]
@MgOmbodorj Do you have more context on a larger section of your script?

Also what are you trying to do?

**Comment by MgOmbodorj** [comment]
@ktbyers i am trying to connect huawei device and configure null route.

**Comment by ktbyers** [comment]
@MgOmbodorj Why are you sending a question mark down the SSH session?

```
output1 = device1.send_command('?')
```

Note, in Netmiko you execute config changes by doing the following:

```
net_connect = ConnectHandler(**kwargs)      # where kwargs is your connection information 
                                                                        # ip/username/password
config_changes = ['cfg command1', 'cfg_command2']
output = net_connect.send_config_set(config_changes)
print output
```

**Comment by ktbyers** [comment]
@MgOmbodorj Just re-open this if you are still having an issue.
