### ISSUE TITLE
Cant access SG200 and CBS switches using netmiko python scripts

### ISSUE THREAD

**Issue by Jayze611** [ktbyers/netmiko#3281]
Hi Anyone

We are trying to log in to SG250-26HP, SG200-18, SF220-24 24, SG250-26 26, CBS350-24FP Switches using Netmiko python scripts to configure switches.

Unfortunately not as routers they have Login as: and username both when SSH.
We tried few different ways but failed

Sample as follow

from netmiko import Netmiko
from getpass import getpass

cisco_sw = {
    "host": "",  # input("Host: "),
    "username": "admin",  # input("Username: "),
    "password": "",  # getpass(),
    "device_type": "cisco_s200"
}

connection = Netmiko(**cisco_sw)
prompt = connection.find_prompt()
print(prompt)

output = connection.send_command("show vlan")
print(output)

connection.disconnect()

But we are getting an error each time we try , tried this in all different models
is there a way around it to SSH in to these switches using netmiko

**Comment by ktbyers** [comment]
@Jayze611 If you manually SSH to one of these devices, can you show what the SSH login process looks like (obviously, you can hide anything that is confidential to your environment).

**Comment by Jayze611** [comment]
![image](https://github.com/ktbyers/netmiko/assets/143692159/f5de1de6-4fb3-4b84-a0a6-291a073811c4)

**Comment by Jayze611** [comment]
Before the username and the password when we SSH to the switch, it prompt 'Login as':
Which can be anything
This is where we think that it blocks us accessing.
