### ISSUE TITLE
Problem connecting to TP-Link switch

### ISSUE THREAD

**Issue by Stonito** [ktbyers/netmiko#3282]
Hello, guys,

I'm having problems with **tplink_jetstream** module in netmiko. When trying to connect with **ConnectHandler**, it exceeds the read_timeout and returns the following exception:

Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

When debugging, however, I see the pattern is present. This is the debug message:

DEBUG:paramiko.transport:starting thread (client mode): 0x2aa79d30
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_3.3.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-1.99-IPSSH-6.6.0
INFO:paramiko.transport:Connected (version 1.99, client IPSSH-6.6.0)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:server key: ssh-dss
DEBUG:paramiko.transport:client encrypt: aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, cast128-cbc, 3des-cbc
DEBUG:paramiko.transport:server encrypt: aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, cast128-cbc, 3des-cbc
DEBUG:paramiko.transport:client mac: hmac-sha1, hmac-sha1-96, hmac-md5, hmac-md5-96
DEBUG:paramiko.transport:server mac: hmac-sha1, hmac-sha1-96, hmac-md5, hmac-md5-96
DEBUG:paramiko.transport:client compress: none
DEBUG:paramiko.transport:server compress: none
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Kex: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:HostKey: ssh-dss
DEBUG:paramiko.transport:Cipher: aes128-cbc
DEBUG:paramiko.transport:MAC: hmac-sha1
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-dss host key for 10.255.16.31: b'6e3ca110ab027f73d8aa7e40d0516ef8'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

Switch1>

Switch1>
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'exit\r\n'
DEBUG:paramiko.transport:EOF in transport thread

There are atleast 500 more **DEBUG:netmiko:read_channel:** lines, which I excluded here. What might be causing this issue. I'm having it only with tplink jetstream devices.

Posting the source code also:

from netmiko import ConnectHandler
import getpass
import logging

logging.basicConfig(filename='netmiko_global.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

#usr = input("Username: ")
#passwd = getpass.getpass()
hostIp = input("Host IP: ")

currentHost =  {
            'host': hostIp,
            'username': usr,
            'password': passwd,
            'device_type': 'tplink_jetstream',
            'session_log': 'netmiko_session.log',
        }

net_connect = ConnectHandler(**currentHost)
print("Connected to: {}".format(hostIp))

Thanks in advance.

Cheers!

**Comment by ktbyers** [comment]
@Stonito Try setting `fast_cli=False` as an argument to ConnectHandler and see if that helps or not.

If that still doesn't work, try `fast_cli=False` and `global_delay_factor=4`.

**Comment by Stonito** [comment]
Hello, Mr. Byers,

Thanks for the fast reply! However, after adding both args to ConnectHandler, it still behaves the same. 
I tried on different device, also by connecting with telnet, and the results are similar. :/

**Comment by ktbyers** [comment]
Okay, which version of Netmiko are you using.

Also please post the full exception stack trace up into GitHub.

**Comment by Stonito** [comment]
I'm using Netmiko version 4.2.0.

Here is the full exception stack trace - https://pastebin.com/2884gtAD

**Comment by chemstar** [comment]
i could reproduce the problem.
it could be fixed with following change:

    def session_preparation(self) -> None:
        """
        Prepare the session after the connection has been established.
        """
        delay_factor = self.select_delay_factor(delay_factor=0)
        time.sleep(0.3 * delay_factor)
        #self.clear_buffer()

**Comment by Stonito** [comment]
@chemstar Thanks so much, man. Everything is working now, I am connecting to the switch.
Cheers!

**Comment by ktbyers** [comment]
Okay, as per the above, it looks like this issue was fixed in this PR:

https://github.com/ktbyers/netmiko/commit/47820f7a27d66831aec4ff4ac94f1074d9eb0491
