### ISSUE TITLE
Nokia SROS issue with return value in ["xx"]

### ISSUE THREAD

**Issue by scottweese** [ktbyers/netmiko#3305]
### Discussed in https://github.com/ktbyers/netmiko/discussions/2458

<div type='discussions-op-text'>

<sup>Originally posted by **theblues25** August 20, 2021</sup>
I used netmiko with nokia sros (md-cli) and when i use send_command to show something and return value has some text in a bracket like this ["xxx"] . the return value disappears. below is some example

when i show some command by myself (ssh to node)
    /configure policy-options policy-statement "vrf-import" entry 10 from protocol name [bgp-vpn]
    /configure policy-options policy-statement "vrf-import" entry 10 action action-type accept

when i got return value of send_cmd of netmiko
    /configure policy-options policy-statement "vrf-import" entry 10 from protocol name
   /configure policy-options policy-statement "vrf-import" entry 10 action action-type accept

i already try to use device_type='nokia_sros' and 'alcatel_sros" but result is same</div>

**Comment by scottweese** [comment]
Similar issue with other responses that include ["something"] in the value.  Command like:
"/admin show configuration json"

Expected resposnse:
"action": {
	"accept": [null]
}

or

"action": {
	"accept": ["some string"]
}



Netmiko response (with missing value to key):
"action": {
	"accept":
}

"action": {
	"accept":
}

**Comment by ktbyers** [comment]
@scottweese Can you show your code?

Also can you show what the prompt on the device looks like?

**Comment by scottweese** [comment]
Relevant code snippet, basic netmiko stuff.  It does auto-detect it to an alcatel/SROS device as it should, logs in, sends the commands, etc... (same code works on other network gear/etc):
    def build_template(self) -> dict:
        template = {
            'device_type': self.device_type,
            'ip': self.ip,
            'username': self.username,
            'password': self.password,
            'secret': self.secret,
            'timeout': int(env.get("DEVICE_TIMEOUT"))
        }
        return template

    def get_connection(self):
        LOGGER.info(f"Connecting to {self.username}@{self.ip}.")
        template = self.build_template()
        try:
            guesser = SSHDetect(**template)
            best_match = guesser.autodetect()
            LOGGER.info(f"Found device type of {best_match}.")
            if best_match:
                self.device_type = best_match
                template = self.build_template()
                return ConnectHandler(**template)
            else:
                raise
        except (NetMikoTimeoutException, SSHException) as error:
            LOGGER.error(f"Error connecting to device, error: {error}.")
            raise
        except (AuthenticationException) as error:
            LOGGER.error(f"Error authenticating to device, error: {error}.")
            raise

    def send_command(self, command: str) -> str:
        LOGGER.debug(f"Running command '{command}' on {self.device_name}.")
        return self.connection.send_command(command)

    def get_config(self) -> str:
        LOGGER.info(f"Getting config for {self.device_name}.")
        return json.loads(self.send_command("/admin show configuration json"))["nokia-conf:configure"]

SSH prompt on device:
A:username@LAB-FTTX-DR-1# /admin show configuration json 

Also attaching large sample of json with [null] values.
[filter.json](https://github.com/ktbyers/netmiko/files/12870318/filter.json)

**Comment by ktbyers** [comment]
@scottweese You are using Netmiko 4.2.0--correct?

Can you try to capture the log file for when it fails?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by ktbyers** [comment]
It seems like the issue is here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/nokia/nokia_sros.py#L247

```python
    def strip_prompt(self, *args: Any, **kwargs: Any) -> str:
        """Strip prompt from the output."""
        output = super().strip_prompt(*args, **kwargs)
        if "@" in self.base_prompt:
            # Remove Nokia context prompt too
            output_list = output.rstrip().splitlines()
            last_line = output_list[-1]
            other_lines = output_list[:-1]
            last_line = nokia_context_filter(last_line)
            output_list = other_lines + [last_line]
            return "\n".join(output_list).rstrip()
        else:
            return output
```

It would be interesting to know what last_line is before/after the nokia_context_filter function is called. I am still not seeing why that is causing the issue you are seeing (as last_line should just be the trailing context i.e. this: `[/]`.

**Comment by scottweese** [comment]
Follow up to this - thought we were on the most recent version of netmiko & apparently wasn't updating properly.  Forced update to 4.2.0 & only issue is very last line is "[/]", which is causing JSON serialization issue....so just got rid of last line & it works as expected.
