### ISSUE TITLE
Slack invite

### ISSUE THREAD

**Issue by ctomkow** [ktbyers/netmiko#3316]
Hello. I hate to open an issue just for getting a slack invite, but it seems the most direct way.
I checked the latest issue that showed a new slack invite, but it is also expired.

If anyone has a current slack invite that would be greatly appreciated! Thanks!

**Comment by schautwb** [comment]
@ctomkow here is a Slack invite: [https://join.slack.com/t/pynet/shared_invite/zt-25h01hscl-wY3C07a5YNrMOGfz0C0iBw](url)
