### ISSUE TITLE
Checks canceling

### ISSUE THREAD

**Issue by dasTor** [ktbyers/netmiko#3317]
I tried to send a small pull request:
https://github.com/ktbyers/netmiko/pull/3315

but checks are failing with "Error: The operation was canceled."
I'm not sure what i can about that.

**Comment by ktbyers** [comment]
One or more of the tests on the pull-request failed. Once that happens, GitHub actions will potentially cancel the others (since the tests have already failed).

See #3315 and the test results.

**Comment by dasTor** [comment]
so only the first test is broken:
"Command not found: pylama
Error: Process completed with exit code 1."
should i open a new issue about that?

**Comment by ktbyers** [comment]
@dasTor Okay, I just re-ran all the tests. There is something going on with GitHub actions where it sometimes fails that that `pylama` error (not sure what is going on there), but re-running the tests generally seems to fix it.
