### ISSUE TITLE
hp procurve telnet support

### ISSUE THREAD

**Issue by spikedrba** [ktbyers/netmiko#332]
Hi,

wonderful work, thank you so much for this lib. I have a bunch of procurve switches and I noticed support for them has been recently added + telnet support was added in 1.0, however the combination of the two is not supported. Is that correct or am I just failing at getting it to work?

If that's the case and somebody was willing to provide some pointers, I'd be happy to take a stab at providing a patch, altho I'm a complete noob at python dev.

thanks,

Spike

**Comment by ktbyers** [comment]
@spikedrba Yes, there is HP ProCurve support for SSH and their is telnet support currently only for Cisco IOS.

Basically, we would need to write a telnet driver for HP ProCurve.

If I do this, can you test it?

**Comment by spikedrba** [comment]
@ktbyers totally yeah, I have 3 diff kinds of HPs deployed (15 total) and would love to automate their setup and maintenance with netmiko (and then wrap that into ansible with ntc-ansible).

**Comment by leo8a** [comment]
Hi,

Great work with Netmiko! Is there any progress in the development of the telnet driver for HP ProCurve?

Cheers!

**Comment by ktbyers** [comment]
No, no one ever worked on this (including me). If you are interested in working on it, please submit a PR, there should be relatively recent examples of people adding telnet support for other platforms.

@leo8a

**Comment by amitsova** [comment]
Hi Kirk,

Any chance for telnet support for hp procurve? :/ I have to upgrade 800 device which support only telnet. I saw that I can use hp_procurve_telnet but the problem is that it requires carriage return twice. Any ideas?
