### ISSUE TITLE
FEATURE: optional ping before connection

### ISSUE THREAD

**Issue by i-m-d** [ktbyers/netmiko#3321]
Hello,

 I have several scripts that connect to lots of devices, some time a device is down, (upgrade, problems, so on) and then the timeout occurs, it would be very good to have a ping parameter to test the device before connection.

 I would like a new feature, a new parameters:
 ping (default = False).
 ping_count (default = 1)

Parameter ping, if True, do a 'ping device' before connect, if ping fails do not connect, so do not try to connect to a device that is down.

Parameter ping_count, number of pings to do.

Cheers

**Comment by ktbyers** [comment]
@i-m-d Should be relatively easy for you to wire into your code (i.e. I think this is better to have outside of Netmiko and not have it be a part of Netmiko).
