### ISSUE TITLE
Netmiko cannot recognize "sshpass alias" while using ProxyCommand

### ISSUE THREAD

**Issue by waleedqq** [ktbyers/netmiko#3328]
My setup is:
[WSL on Windows 10] ----> [Jump Server] -----> [Cisco Device]

I have used an alias in `.bashrc` to allow me to login to the JumpServer without a password. This was tested and confirmed in the CLI. SSH keys are not an option and this is a lab environment. 

`alias my_sshpass='sshpass -p "myPass" ssh'`

The following is an excerpt from the `~/.ssh/config`
```
Host JumpServer
		KexAlgorithms +diffie-hellman-group-exchange-sha1
		Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc
		HostKeyAlgorithms +ssh-rsa
		

Host cisco1
		Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc
		KexAlgorithms +diffie-hellman-group1-sha1
		StrictHostKeyChecking no
		ProxyCommand my_sshpass -W %h:%p JumpServer  <<<<<<<<<<<< This Alias is not recognized in my python script
		User myUser
```

**Netmiko Error**

``FileNotFoundError: [Errno 2] No such file or directory: 'my_sshpass'`

Even when running it on the CLI `ssh cisco1`
This is the error

```
/bin/bash: line 1: exec: my_sshpass: not found
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

Does anyone know how I could fix this?

**Comment by g1sm** [comment]
For me it works if I use the `ProxyCommand` like this:
```
Host switch
    HostName switch
    ProxyCommand /usr/bin/sshpass -e ssh -W %h:%p user@jumphost
    User someuser
```
You just need to export `SSHPASS` with your password.
