### ISSUE TITLE
SSH Into Cisco Device and provide input from .txt/.csv file and save the output to another file.

### ISSUE THREAD

**Issue by raunak06anand** [ktbyers/netmiko#334]
Hi Experts,

I am using below code to login to multiple devices and perform the show commands and saving the output in another file. Some how these codes are running into terminal but not into the launch pad. Its throwing below mention error. Now I am totally lost what need to be done to finalize this code for multiple devices.

Need expert advice to resolve this issue.

ERROR::::

++++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "./asa-ssh-from-file.py", line 20, in <module>
    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 96, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 90, in __init__
    self.session_preparation()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco/cisco_asa_ssh.py", line 13, in session_preparation
    self.enable()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 15, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 737, in enable
    output += self.read_until_prompt()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 192, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 149, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available

++++++++++++++++++++++++++++++++++++++++++++++++++++

================CODE=====================
#! /usr/bin/python
from __future__ import print_function
from netmiko import ConnectHandler
import sys
import time
import select
import paramiko
import re
fd = open(r'C:\NewdayTest.txt','w') # Where you want the file to save to.
old_stdout = sys.stdout   
sys.stdout = fd 
platform = 'cisco_ios'
username = 'username' # edit to reflect
password = 'password' # edit to reflect

ip_add_file = open(r'C:\IPAddressList.txt','r') # a simple list of IP addresses you want to connect to each one on a new line

for host in ip_add_file:
    host = host.strip()
    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
    output = device.send_command('terminal length 0')
    output = device.send_command('enable') #Editable to be what ever is needed
    print('##############################################################\n')
    print('...................CISCO COMMAND SHOW RUN OUTPUT......................\n')
    output = device.send_command('sh run')
    print(output)
    print('##############################################################\n')
    print('...................CISCO COMMAND SHOW IP INT BR OUTPUT......................\n')
    output = device.send_command('sh ip int br')
    print(output) 
    print('##############################################################\n')

fd.close()

**Comment by ktbyers** [comment]
@raunak06anand Yes, it looks like you are trying to SSH to something that isn't available via SSH.

I would print out the following before your SSH connection and make sure they are correct:

```
platform
host
username
password
```

You should also use a try/except statement so that the above exception is gracefully handled and it moves on to the next device.

**Comment by raunak06anand** [comment]
Hi Ktbytes,

I am trying to ssh to a list (rather a .txt file) which contains list of Cisco ASA firewall IP address. I am trying to execute the script so that it reads the IP of ASA from the .txt file and perform the steps define in the script and save the output in another file. Below is the script which I am trying to execute.

where IP_LIST.txt this is the file which contains the IP address of ASA and IP_LIST1.txt this is the file in which output needs to be stored.
==========SCRIPT============

from __future__ import print_function
from netmiko import ConnectHandler
import sys
import time
import select
import paramiko
import re
fd = open(r'C:\Users\anandr\Desktop\python\IP_LIST1.txt','w') # Path where I have saved the file.
old_stdout = sys.stdout   
sys.stdout = fd 
platform = 'cisco_asa'
username = 'anandr' 
password = 'mk@2045'

ip_add_file = open(r'C:\Users\anandr\Desktop\python\IP_LIST.txt','r') # File contains IP of ASA 

for host in ip_add_file:
    host = host.strip()
    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
    output = device.send_command('terminal length 0')
    output = device.send_command('enable') #Editable to be what ever is needed
    print('##############################################################\n')
    print('...................CISCO COMMAND SHOW RUN OUTPUT......................\n')
    output = device.send_command('sh run')
    print(output)
    print('##############################################################\n')
    print('...................CISCO COMMAND SHOW IP INT BR OUTPUT......................\n')
    output = device.send_command('sh ip int br')
    print(output) 
    print('##############################################################\n')

fd.close() 

ERROR:

Below is the output which i am receiving in the output file IP_LIST1.txt

##############################################################

...................CISCO COMMAND SHOW RUN OUTPUT......................

                          ^
ERROR: % Invalid input detected at '^' marker.
##############################################################

As per my understanding the script is not able to read the IP address from the .txt file. Please suggest on this how the script can  read the IP address mentioned in the script.

I have tried the suggestion which you have mentioned its working for single IP address but not for multiple IP which the script is using from the .txt file.

Please suggest what modification needs to be done in the script.
