### ISSUE TITLE
Python SSH network devices

### ISSUE THREAD

**Issue by AhmedMS1** [ktbyers/netmiko#3354]
Hello Team,
I am trying to run a code that could SSH list of devices and come back with data in an external file from these devices.

But, at the beginning I am facing some issues regarding netmiko and other features however I have already installed these functions. Could you please give a support hand?

**Code:**

from __future__ import print_function
from netmiko import ConnectHandler
import sys
import time
import select
import paramiko
import re
fd = open(r'C:\Test.txt','w') 
old_stdout = sys.stdout
sys.stdout = fd
platform = 'cisco_ios'
username = 'admin' 
password = 'cisco'
ip_add_file = open(r'C:\IPAddressList.txt','r')

for host in ip_add_file:
    host = host.strip()
    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
    output = device.send_command('terminal length 0')
    output = device.send_command('enable') 
    print('##############################################################\n')
    print('...................CISCO COMMAND SHOW RUN OUTPUT......................\n')
    output = device.send_command('sh run')
    print(output)
    print('##############################################################\n')
    print('...................CISCO COMMAND SHOW IP INT BR OUTPUT......................\n')
    output = device.send_command('sh ip int br')
    print(output)
    print('##############################################################\n')

fd.close()

**![Uploading Code support.PNG…]()**

Traceback (most recent call last):
File "C:\Users\adam\PycharmProjects\test\testt.py", line 2, in <module>
from netmiko import ConnectHandler
ModuleNotFoundError: No module named 'netmiko'

Process finished with exit code 1

**Comment by AhmedMS1** [comment]
![Code support](https://github.com/ktbyers/netmiko/assets/153702751/9f0476ab-4429-475b-9d55-bd1373a1911a)

**Comment by ktbyers** [comment]
It looks like your environment doesn't have Netmiko installed (which if you think you have Netmiko installed probably implies that you are not using the right Python and/or the right Python virtual environment).
