### ISSUE TITLE
"send_config_from_file" method send commands but errors "Pattern not detected" 

### ISSUE THREAD

**Issue by justrob1980** [ktbyers/netmiko#3364]
### Description of Issue/Question
All the relevant python code and inputs and error messages are in the pastebin, link below. 

Basically I want to feed a txt file of IP addresses and then have a set of text files named with those IP addresses. I want the script to parse the IP addresses then apply the config in the corresponding text file to the device (e.g. it would parse 10.1.1.1 from routerips.txt and then read the configuration from the file 10.1.1.1.txt and apply that configuration to the device @ 10.1.1.1). However, for some reason it seems to be expecting the hostname of the device in the output for some reason. I saw similar issue related to the "send_config_set" method, but I am using "send_config_from_file" so not sure if this is different. 

It seems that the configuration is applied, but like the other issue, it seems like the for loop does not execute, so only the first instance of this process happens for this error terminates the script. 

### Netmiko Version
username@HOSTNAME:~/netmiko_rtr$ pip freeze | grep netmiko
netmiko==4.1.2
nornir-netmiko==1.0.0

### Everything Else
https://pastebin.com/rHrL4Wb1

**Comment by ktbyers** [comment]
@justrob1980 You need to pick one failing device and show the full exception stack trace and the configuration commands that you are sending from the text file.

Can you simplify your test case and post that information here?

**Comment by justrob1980** [comment]
This output is from only one device. And the full output I received is included in the pastebin link, if additional debugging or logging is requested let me know how to enable it. By simplifying the test case do you mean simplifying the configuration file I am trying to apply or simplify the process in general?

**Comment by justrob1980** [comment]
So I narrowed down that what it doesn't like is that some of the applied configuration is "interactive" e.g. it asks for a yes/no confirmation which the file includes as the next line, but it looks like it is validating the prompt at every line and since the next line doesn't go back to the same config prompt it errors out. So can "send_config_from_file" and "send_config_set" not be used with configuration that require answers?

**Comment by ktbyers** [comment]
If configuration is interactive, then the standard `send_config_set` or `send_config_from_file` will not work (as both of these are not expecting this unusual interaction behavior.

Typically, in these cases you would call the `config_mode()` and `exit_config_mode()` methods and then handle all of the interactive prompting using either send_command() or send_multiline()

```python
net_connect.config_mode()
net_connect.send_multiline(cmd_list)
net_connect.exit_config_mode()
```

Additional details on send_multiline() are here:

https://pynet.twb-tech.com/blog/netmiko4-send-multiline.html
