### ISSUE TITLE
Cannot get whole running config from maipu switch using netmiko script

### ISSUE THREAD

**Issue by brancott** [ktbyers/netmiko#3388]
I'm new to netmiko, just wanted a simple script to backup a maipu switch config and the script runs "sh run" and gets output but only before ---MORE--- it doesn't go beyond it:

![shrun](https://github.com/ktbyers/netmiko/assets/51475705/87d5c46d-4247-424c-aceb-bc0689b8eed5)

I use cisco_ios as device_type because as far as I know there is no device_type for maipu. Here is the script:
```

from getpass import getpass
from netmiko import ConnectHandler

from datetime import date

today = date.today()

username = input('Enter your SSH username: ')
password = getpass()

with open('myswitches') as f:
    ip_lines = f.read().splitlines()
print (ip_lines)

for device in ip_lines:
    ip_address_of_device = device
    CE = {
        'device_type': 'cisco_ios',
        'ip':   ip_address_of_device,
        'username': username,
        'password': password
    }

    net_connect = ConnectHandler(**CE)
    running_config = net_connect.send_command("show running-config", read_timeout=500)
    with open(
       f'/root/networklab/maipu/maipu-running-config-{today}.txt', "w"
    ) as outfile:
       outfile.write(running_config.lstrip())
    print(f'Backup completed')
    net_connect.disconnect()

```
The same script gets config from cisco nexus switch fine. How to fix it?

**Comment by ktbyers** [comment]
Try using `device_type="maipu"` and let me know if you are still seeing this issue.

**Comment by brancott** [comment]
Works great, I believed netmiko doesn't have device type for maipy for some reason, silly mistake :) 
Thanks for help!

**Comment by ktbyers** [comment]
@brancott The `maipu` driver is pretty new...so, no worries.
