### ISSUE TITLE
Cisco IOS Command "ip host $hostname $ipaddress" is not properly detected as config mode command

### ISSUE THREAD

**Issue by admiralspark** [ktbyers/netmiko#339]
The command used in Cisco IOS for setting a hostname within the configuration, example:
```
ip host tftp 192.168.1.1
```
Is not properly being detected as a command to be run in configuration mode. This is likely due to the 'ip' command being available in 'enable' mode (Privileged EXEC Mode). 

Need confirmation before moving forward, I only have two Cisco IOS-based devices available for testing.

**Comment by ktbyers** [comment]
@admiralspark There is no detection of the mode a command is in. You need to send it as a configuration change i.e.

```
output = net_connect.send_config_set(['ip host tftp 192.168.1.1'])
print output
```

**Comment by admiralspark** [comment]
Oh man, I'm an idiot, very sorry for that--just looked and the rest of my working code is sending config sets...

Thanks @ktbyers

**Comment by ktbyers** [comment]
@admiralspark It is all good :-)
