### ISSUE TITLE
Unable to capture full output of a lengthy output

### ISSUE THREAD

**Issue by lasithadks** [ktbyers/netmiko#3399]
Unable to capture full length output from a lengthy output like show run or show ip route.

I have using Netmiko to ssh network devices and collect pre and post checks using CLI commands. Previously my script work nicely and as expected. Recently, I have found that script is not collecting lengthy outputs like 'show run', 'show ip route'. Collecting only a half of the output.
In addition to that I'm using that 'autodetect' as the device type.

Python version is 3.10.10

output = net_connect.send_command(f'{command}\n', read_timeout=300, expect_string=r'.*[$#>]')

### Netmiko version
netmiko==4.2.0

use autodetect
found this issue on few device types like cisco (many flavors like XE, nxos, ios), juniper

**Comment by ktbyers** [comment]
@lasithadks Probably need to look at the log and see what it is matching on (or if it is not matching see why it is timing out and you should have an exception).

Netmiko logging is here.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by lasithadks** [comment]
@ktbyers thank you. 
By enabling a debug on netmiko, I have found that next command passes to the device while reading the previous command output. But in debug, I can see rest of the output which not printed in the screen and file.
I don't why that strange thing happened suddenly.  

Issue is sorted after replacing send_command() with send_command_timing() with below options. 

previous function:
output = net_connect.send_command(f'{command}\n', read_timeout=300, expect_string=r'.*[$#>]')

new function:
output = net_connect.send_command_timing(f'{command}\n', last_read=1, read_timeout=300)

**Comment by ktbyers** [comment]
@lasithadks Okay, it sounds like you got it working so I am going to close this issue.
