### ISSUE TITLE
Python 2.6 - WLC connection returns ValueError: zero length field name in format

### ISSUE THREAD

**Issue by xdkreij** [ktbyers/netmiko#341]
Hello all, 

Hope you're doing well. Running into a .format() issue with python 2.6 when connecting to a WLC.
This results into the following:

```
Traceback (most recent call last):
  File "get_InfoFromHosts.py", line 178, in <module>
    l_vConnectResult    = ssh.prompt(l_iCMDsendDelay) + "\n"
  File "/home/xkreij/pyScripts/mod_sshConnect.py", line 34, in prompt
    self.ssh()
  File "/home/xkreij/pyScripts/mod_sshConnect.py", line 29, in ssh
    password=self.password
  File "/usr/lib/python2.6/site-packages/netmiko-1.1.0-py2.6.egg/netmiko/ssh_dispatcher.py", line 96, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/netmiko-1.1.0-py2.6.egg/netmiko/base_connection.py", line 90, in __init__
    self.session_preparation()
  File "/usr/lib/python2.6/site-packages/netmiko-1.1.0-py2.6.egg/netmiko/cisco/cisco_wlc_ssh.py", line 100, in session_preparation
    self.set_base_prompt()
  File "/usr/lib/python2.6/site-packages/netmiko-1.1.0-py2.6.egg/netmiko/base_connection.py", line 504, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/usr/lib/python2.6/site-packages/netmiko-1.1.0-py2.6.egg/netmiko/base_connection.py", line 549, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: zero length field name in format
```

Unfornatately i'm unable to test the "raise ValueError("Unable to find prompt: {}".format(prompt))"
in base_connection.py since i'm not root at the specific server its running on, and its the only way to connect to the WLC via that server. (Asked the admin to upgrade to 3.5.2 but i thought lets post it anyway since netmiko is supposed to support 2.6 as well according to the readme on github)

Any thoughts?

Regards,

Xander

**Comment by rwwelford** [comment]
This issue sounds very similar to the one raised on November 11 for  [some HP Procurvedevices:](https://github.com/ktbyers/netmiko/issues/311)

You might want to try the suggestions offered there to see if they resolve your issue as well.

**Comment by ktbyers** [comment]
@xdkreij Yes, that is a Python2.6 bug...but you also have a second issue which is you failed to complete the connection. 

In other words, you would only get to this location if the connection failed to complete.

I would probably try setting the

```
 'global_delay_factor': 2
```

This is an argument to ConnectHandler (you might also want to try 4)

**Comment by ktbyers** [comment]
@rwwelford That "Unable to find prompt" is the generic message you are going to get on pretty much all platforms if the connection fails to complete.

**Comment by xdkreij** [comment]
Ok, thanks for the feedback. Tested it with python 2.7 and 3.5, which works :)

**Comment by ktbyers** [comment]
@xdkreij I am going to keep this issue open as there is an error here on Python2.6 (i.e. this a bug in Python2.6).

```
raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: zero length field name in format
```

**Comment by ktbyers** [comment]
FYI, I am removing support for Py2.6 in Netmiko 1.2. You should use Python27 (in a virtualenv to maintain support).
