### ISSUE TITLE
problem with send_command_timing()

### ISSUE THREAD

**Issue by Stiwar0098** [ktbyers/netmiko#3412]
Hi,I am using a **huawei olt**.
I have the same problem with **net_connect.send_command_timing('display current-configuration ont 0/2/4 17')** Applying this **net_connect.send_command_expect('display current-configuration ont 0/2/4 17')** I got the following :
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'display\ current-configuration\ ont\ 0/2/4\ 17' in output.

Things you might try to fix this:

Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
Increase the read_timeout to a larger value.
You can also look at the Netmiko session_log or debug log for more information.

**on console it comes out like this**
olt_hk(config)#display current-configuration0/2/417
^
% Unknown command, the error locates at '^'

**Comment by ktbyers** [comment]
Why are you executing this from configuration mode?

What happens in the CLI if you execute this same command from configuration mode:

```
display current-configuration ont 0/2/4 17
```

I also would not abbreviate any commands, I would use the full canonical version of the command.

**Comment by Stiwar0098** [comment]
Thank you very much for the prompt response, the problem had been due to my user's permissions
