### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by devinmcintyre** [ktbyers/netmiko#342]
Have you thought of adding a "reload" method to the Netmiko library?  For example, "net_connect.reload()", which would send a "reload" command down the channel, expecting this prompt:
 
![capture](https://cloud.githubusercontent.com/assets/23405619/21285500/e2bfa8fe-c3ff-11e6-9c41-85d0bf7a905e.PNG)

And then sending "y" down the channel to initiate the reboot.  I've been playing around with automating switch firmware upgrades and have run into a little snag with this prompt after issuing the "reload" command.  

Interestingly, this does work if the code is ran in the Python interpreter and if a keyboard interrupt is issued after each "reload" and "y" command is sent using the send_command method.  For example, my code:
```
from netmiko import ConnectHandler
net_connect = ConnectHandler(device_type='hp_procurve', ip='10.1.2.20', username='manager', password='$tars2016')
net_connect.send_command("reload")
net_connect.send_command("y")
```

And what the output looks like in the Python interpreter:
![capture](https://cloud.githubusercontent.com/assets/23405619/21285571/e3070e18-c401-11e6-9c42-5162d04f4d61.PNG)

I appreciate any thoughts you have on this!

**Comment by ktbyers** [comment]
@devinmcintyre 

You can just do:

```
output = net_connect.send_command_timing("reload")
if 'do you want to continue' in output:
    output += net_connect.send_command_timing("y")
```

**Comment by devinmcintyre** [comment]
This solves my issue, thanks Kirk!
