### ISSUE TITLE
IOError: Search pattern never detected in send_command_expect: \(Cisco\ Controller\)\ \> when getting to prompt "Are you sure you want to start? (y/N)"

### ISSUE THREAD

**Issue by atabb** [ktbyers/netmiko#343]
Hello,

Getting the following error,

Traceback (most recent call last):
  File "/Users/atabbakh/PycharmProjects/training/netMiko.py", line 21, in <module>
    device.send_command('transfer download start\n')
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 673, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: \(Cisco\ Controller\)\ \>

Process finished with exit code 1

Here is my code,
mport netmiko
from netmiko import ConnectHandler
import time

platform = 'cisco_wlc'
host = '10.89.20.6'
username = 'cisco'
password = 'Cisco123'
device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)

#sending needed commands to update the code
device.send_command('transfer download mode ftp\n') #downloading from an FTP server
device.send_command('transfer download datatype code\n') #data type is code since we are upgrading/downgrading the code
device.send_command('transfer download serverip 192.64.62.6\n') #ip of the FTP server
device.send_command('transfer download filename AIR-CT5500-K9-8-3-102-0.aes\n') #file name .aes to upgrade code
device.send_command('transfer download path FTP/code/83/\n') #the file path
device.send_command('transfer download username ftpuser\n') #ftp username
device.send_command('transfer download password ftp123\n') #ftp password
device.send_command('transfer download start\n')
print(device.base_prompt)
device.remote_conn.sendall('y\n')
device.send_command('save config\n')
device.remote_conn.sendall('y\n')
device.send_command('reset system\n')
device.remote_conn.sendall('y\n')

Looks like its failing when trying to send a the 'y' response after i run the transfer download start command but since the prompt is "Are you sure you want to start? (y/N)" instead of (Cisco controller) it throws the error, how do you get around that issue? 

Thank you!

**Comment by atabb** [comment]
Wanted to mention that the device i am connecting to is a CISCO 5508 WLC, i'm trying to write a script that upgrades the code, right now i'm writing the basic script for it.

**Comment by ktbyers** [comment]
@atabb

Try changing the end of your script to:

```
device.send_command_timing('transfer download start')
print(device.base_prompt)
device.send_command_timing('y')
device.send_command_timing('save config')
device.send_command_timing('y')
device.send_command_timing('reset system')
device.send_command_timing('y')
```

Let me know if that works or not.

**Comment by atabb** [comment]
thank you, that worked!
