### ISSUE TITLE
Aruba CX naming update is wrong

### ISSUE THREAD

**Issue by pietos** [ktbyers/netmiko#3443]
### Description of Issue/Question

We submitted the new Aruba vendor as how it's called in the market & community Aruba AOS-CX
I see now that in a recent commit you changed it to Aruba-CX, which is incorrect. Therefor I would like to request to undo the naming change back to aruba_aoscx

This will also conflict with the exiting NTC template:
https://github.com/networktocode/ntc-templates/tree/master/ntc_templates/templates

Aruba tech:
https://www.arubanetworks.com/techdocs/AOS-CX/help_portal/Content/home.htm

**Comment by ktbyers** [comment]
Fix is to just add a second entry and map "aruba_aoscx" to the existing driver. Obviously, I was not aware that ntc-templates had an existing name for this platform.

    "aruba_aoscx": ArubaCxSSH,

**Comment by Trailingslashes** [comment]
This is was worked for me in my environment, but I don't know if renaming the platform is the best path forward - https://github.com/Trailingslashes/netmiko/commit/927e02b06a0b825be47e1402e2f42fac3d83152c

**Comment by ktbyers** [comment]
@Trailingslashes Not sure I follow you? Was there a question or concern here?

**Comment by Trailingslashes** [comment]
@ktbyers, no concern, I just wasn't sure if I should submit a PR to update the platform name.

**Comment by ktbyers** [comment]
@Trailingslashes Either way is fine (you can submit it or I can submit it). I will try to do it this week otherwise.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/pull/3448

**Comment by ktbyers** [comment]
@pietos @Trailingslashes FYI, Netmiko 4.4.0 was released today that includes this fix and Aruba CX support.
