### ISSUE TITLE
HP Procurve Logout Process Incomplete

### ISSUE THREAD

**Issue by tyler-8** [ktbyers/netmiko#346]
The HP Procurve logout process looks like

    switch# exit
    switch> exit
    Do you want to log out (y/n)? y
However netmiko currently only does one `exit` before closing SSH connection. This results in the following syslog message:
`ssh: AM1: read error Connection reset by peer, session aborted`

**Comment by wmann** [comment]
Maybe the logout command is better.

**Comment by tyler-8** [comment]
logout still has a prompt for logout, as well as an additional prompt asking if you want to save the current configuration.

```
# logout
Do you want to log out (y/n)? y
Do you want to save the current configuration (y/n)? n
```
