### ISSUE TITLE
Linux - error when changing directory

### ISSUE THREAD

**Issue by bulyhome** [ktbyers/netmiko#347]
I am using Windows 7 (64 bit) and Python 3.5 (64 bit) with Paramiko 2.1.1 and Netmiko 1.1.0
I need to connect to multiple Linux hosts using ssh, run several commands there and then disconnect.
When trying to change the current directory, I get error:

Traceback (most recent call last):
  File "script_v5.py", line 13, in <module>
    output = device.send_command(command)
  File "C:\Program Files\Python35\lib\site-packages\netmiko\base_connection.py", line 673, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: \[root\@host\ \~\]\#

Here is my code:

from netmiko import ConnectHandler

platform = 'linux'
host='***'
username='root'
password='***'

device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
command = "pwd"
output = device.send_command(command)
print(output)
command = "cd /etc"
output = device.send_command(command)

**Comment by ktbyers** [comment]
I recommend that you try using:

```
send_command_timing(command)
```

Basically your prompt is changing on the 'cd' operation and that is causing the send_command() method to fail.

**Comment by bulyhome** [comment]
I tried that and it worked, thanks a lot.

**Comment by rbouali34** [comment]
thanks a lot for me too
