### ISSUE TITLE
cisco telnet login username_pattern

### ISSUE THREAD

**Issue by yearcode** [ktbyers/netmiko#3478]
hi  ktbyers

cisco c2960's username prompt is 'Login Name'

**Comment by ktbyers** [comment]
@yearcode Should work:

```python
    def telnet_login( 
        self,
        pri_prompt_terminator: str = r"\#\s*$",
        alt_prompt_terminator: str = r">\s*$",
        username_pattern: str = r"(?:user:|username|login|user name)",
        pwd_pattern: str = r"assword",
        delay_factor: float = 1.0,
        max_loops: int = 20,
    ) -> str:
```

It should match on `login`.

**Comment by yearcode** [comment]
> @yearcode Should work:
> 
> ```python
>     def telnet_login( 
>         self,
>         pri_prompt_terminator: str = r"\#\s*$",
>         alt_prompt_terminator: str = r">\s*$",
>         username_pattern: str = r"(?:user:|username|login|user name)",
>         pwd_pattern: str = r"assword",
>         delay_factor: float = 1.0,
>         max_loops: int = 20,
>     ) -> str:
> ```
> 
> It should match on `login`.

yeah, the rule match it , please close it . thanks!
