### ISSUE TITLE
ReadTimeout with large Cisco Configurations

### ISSUE THREAD

**Issue by AndreasFranzSchweizer** [ktbyers/netmiko#3484]
### Description of Issue/Question

Probably not an netmiko issue, but possibly someone already has seen his issue. I have a Cisco 9300 Access switch configuration to deploy and as soon I exceed a certain amount of configuration operations im getting ReadTimeout. So actually 300 of 1000 commands run without any issue. But after exactly the same number of config commands, IOS stops answering.

### Netmiko version

netmiko==4.4.0
paramiko==3.4.1

### Netmiko device_type (if relevant to the issue)
device_type: cisco_ios

### Steps to Reproduce the Issue

You can simply reproduce the issue, entering and exiting the config mode in a loop.

### Error Traceback
Traceback (most recent call last):
  File "/etc/wara_network_configuration/setup.py", line 37, in <module>
    config_ports(net_connect)
  File "/etc/wara_network_configuration/ports.py", line 51, in config_ports
    connection.send_config_set(commands, enter_config_mode=False, exit_config_mode=False, delay_factor=5)
  File "/etc/wara_network_configuration/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/wara_network_configuration/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 2319, in send_config_set
    output += self.read_until_pattern(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/wara_network_configuration/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 748, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'switchport\\ mode\\ access' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

### Relevant Python code

```python
from netmiko import ConnectHandler

cisco1 = {
    "device_type": "cisco_ios",
    "host": "10.16.3.27",
    "username": "user",
    "password": password,
    "secret": secret,
    "session_log": "output.txt"
}

print(f"Connect to {cisco1['host']}")
net_connect = ConnectHandler(**cisco1)

print("Enable")
net_connect.enable()

for trial in range(1000):
    print(trial)
    net_connect.config_mode()
    net_connect.exit_config_mode()

net_connect.disconnect()
```

**Comment by joshniec** [comment]
Have you tried increasing the read_timeout (I think you have to override it at the object level for it to work on send_config_set, so try "read_timeout_override": 30 in your connection details dictionary)?

What does the session.log show as the last response from the device?

I don't have a Cisco device to rest with, I did use your provided reproduction case against an Arista device and didn't observe any ReadTimeout exception.

**Comment by yearcode** [comment]
device config with 3A? if true, try to add time.sleep(seconds)

**Comment by AndreasFranzSchweizer** [comment]
Thank you for your prompt support, and I apologize in advance for leading you in the wrong direction. 

The issue was neither related to Netmiko nor Cisco IOS. It turned out to be an SSH problem caused by asymmetric routing. Due to the access control lists in place, I could only reach the switches from a specific network. Today, I had the opportunity to test everything locally within the same VLAN, and it worked immediately.

The tricky thing about asymmetric routing with SSH is that the connection appears to be terminated only after a certain amount of time. I didn't notice this in the logs. When making a manual SSH connection, the problem didn’t occur.
Hopefully, this will help someone who encounters a similar issue. 

**If the SSH connection is unexpectedly terminated after about 60 seconds, asymmetric routing could be the cause.**

Thanks again for your support.
