### ISSUE TITLE
Send Command failing for Panorama

### ISSUE THREAD

**Issue by bdugg21** [ktbyers/netmiko#349]
device = ConnectHandler(device_type='paloalto_panos', ip=panorama, username = username, password = password)
>>> device.config_mode()
u''
>>> device.send_command("set device-group datacenters address tf_sandbox ip-netmask 192.168.116.0/28")               
**u'set \r\x1b[K\n'**

**Comment by ktbyers** [comment]
@bdugg21 Yes, Panorama isn't supported.

Why not use the Panorama API?

**Comment by bdugg21** [comment]
@ktbyers thanks. I can use the api, however I'm migrating objects to a shared device group so there are over 3000 commands that I already had scripted. I just now have to modify the script make api calls instead.

**Comment by ktbyers** [comment]
...there might be some workaround. Someone would have to update Netmiko to support Panorama (I have not idea what the Panorama interface looks like).
