### ISSUE TITLE
The slack invitation link in Readme is expired

### ISSUE THREAD

**Issue by Yukissss** [ktbyers/netmiko#3495]
The link is no longer active, could you update a new one?

**Comment by thamuppet** [comment]
Would also appreciate an invite.

**Comment by schautwb** [comment]
@Yukissss & @thamuppet 

Slack invite: [https://join.slack.com/t/pynet/shared_invite/zt-2qkogju51-ImCWG~SKEy6y7BiikWL6fg](url)
