### ISSUE TITLE
Router prompt not found for Cisco ACE

### ISSUE THREAD

**Issue by ogenstad** [ktbyers/netmiko#351]
Trying Netmiko with some Cisco ACE devices. Don't know if it's supposed to be supported. I just assumed that I would be able to set `device_type='cisco_ios'`.

The installation I was using Netmiko 0.5.1 and basically it worked, however it was inconsistent as in:

``` Python
>>> device = ConnectHandler(**args)

SSH connection established to ch-int-admin-lb-2:22
Interactive SSH session established
>>>
>>> device.disconnect()
>>> device = ConnectHandler(**args)
SSH connection established to ch-int-admin-lb-2:22
Interactive SSH session established
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/svc_netscript/.virtualenvs/ansible/lib/python2.6/site-packages/netmiko/ssh_dispatcher.py", line 84, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/svc_netscript/.virtualenvs/ansible/lib/python2.6/site-packages/netmiko/base_connection.py", line 69, in __init__
    self.session_preparation()
  File "/home/svc_netscript/.virtualenvs/ansible/lib/python2.6/site-packages/netmiko/base_connection.py", line 82, in session_preparation
    self.set_base_prompt()
  File "/home/svc_netscript/.virtualenvs/ansible/lib/python2.6/site-packages/netmiko/base_connection.py", line 263, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: http://www.gnu.org/licenses/gpl.html.
>>>
```

There are a number of devices I'm trying to connect to and some of them seem to work better. 

Logging on with an ssh client looks like this:

```
paog01@ch-int-admin-lb-1's password:
Bad terminal type: "xterm-256color". Will assume vt100.
Cisco Application Control Software (ACSW)
TAC support: http://www.cisco.com/tac
Copyright (c) 1985-2015 by Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.
User 'www' is disabled.Please change the password to enable the user.
ch-int-admin-lb-1/Admin#
```

Using a later version of Netmiko:
``` Python
>>> import netmiko
>>> print netmiko.__version__
1.1.0
>>> device = ConnectHandler(**args)
SSH connection established to ch-int-admin-lb-2:22
Interactive SSH session established
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paog01/.virtualenvs/netmiko/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 96, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/paog01/.virtualenvs/netmiko/lib/python2.7/site-packages/netmiko/base_connection.py", line 90, in __init__
    self.session_preparation()
  File "/home/paog01/.virtualenvs/netmiko/lib/python2.7/site-packages/netmiko/cisco/cisco_ios.py", line 11, in session_preparation
    self.set_base_prompt()
  File "/home/paog01/.virtualenvs/netmiko/lib/python2.7/site-packages/netmiko/base_connection.py", line 506, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: http://www.gnu.org/licenses/gpl.html.
>>>
```

Setting a different `global_delay_factor` and `timeout` seems to work. Would that be the best solution or should this be fixed in the code? (Haven't done any real troubleshooting or looked in the code yet)

**Comment by ktbyers** [comment]
@ogenstad If I generate an ACE driver, can you test it?

**Comment by ogenstad** [comment]
Since Cisco ACE is end of life it would perhaps be cleaner to be able to solve it within the Cisco IOS driver. Seems to be just a small timing issue. But perhaps you don't want to add the code to the ios driver?

I can take a look too, reported it here mostly not to forget the details. But if you know what's going on, sure I can test new code.

**Comment by ktbyers** [comment]
Yes, from the above, it looks like there is just not enough delay at login (which is why setting the global_delay_factor fixes it). We could possibly add an additional slight delay to the cisco_ios driver in the session_preparation() method.

**Comment by ogenstad** [comment]
Well since it works when I change the timing settings I would say that it is a timing issue.

Actually I'm running this against six devices. Two of them are ACE4710 and four are ACE30 modules (sitting in 6500 chassis). I don't think I've seen the issue against the ACE4710 devices but against the ACE30 devices it becomes unreliable. Sometimes it works and other times it doesn't.

Haven't had time to dive deeper into this yet but will try to do so "soon".

**Comment by ktbyers** [comment]
@ogenstad I added a fix here:

https://github.com/ktbyers/netmiko/commit/a03638c1a2447204841bbd62af2d9c8d7b8ff60c

Can you test it? You can still use a device_type of 'cisco_ios'.

This is a general issue that people are running into with Netmiko (i.e. it is not robust enough on reading all the banner/header information post login). So I am trying to fix/improve that issue.

**Comment by ogenstad** [comment]
This seems to have solved the issue. Thanks!
