### ISSUE TITLE
ANSI Escape codes in output of Cisco APIC

### ISSUE THREAD

**Issue by sindhujit** [ktbyers/netmiko#352]
Hi,
   I am using Django/Python for network automation in our Cisco ACI infrastructure. However, I always get this error:- **Router prompt not found** when I am using netmiko. I have done the basic required modifications needed, like changing the delays in base_connection.py and also adding global delay variable, but nothing seems to work. Does netmiko support Nexus 9k devices, or is it missing i'm doing wrong?

**Comment by ktbyers** [comment]
@sindhujit Can you post the part of your code that is failing and the error message (strip out anything that is confidential).

**Comment by sindhujit** [comment]
cisco_881 = {
	'device_type': 'cisco_nxos',
	'ip': 'not essential(x.x.x.x)',
	'username': 'admin',
	'password': 'Can't disclose this',
	'port' : 22, # optional, defaults to 22
	'secret': 'secret', # optional, defaults to ''
	'verbose': False, # optional, defaults to False
	# 'global_delay_factor' : 3,
	}
	device = ConnectHandler(**cisco_881)
	# print(device.find_prompt())
	print(device)
	output = device.send_command('show version')
	print(output)


This gives me an error on the front end :- 
Exception Value:	
Router prompt not found: [1m[7m%[m[1m                                                                                [0m[m[m[Japic1# [K

**Comment by ktbyers** [comment]
What happens if you set the global_delay_factor to 3?



Kirk

**Comment by sindhujit** [comment]
same thing..

**Comment by ktbyers** [comment]
What does an SSH login to the switch look like (if you do it manually)?

**Comment by sindhujit** [comment]
it asks for the login and pwd, and after logging in gives me a prompt like apic1#..
i was successful in setting up paramiko though.

**Comment by ktbyers** [comment]
Yes, you need to post it here (I need to see it)...wrap in triple backticks so it doesn't get munched by the markdown.

**Comment by sindhujit** [comment]
its like:-
```
login: admin
password:
last login: ................................(date and time)
apic1#
```

**Comment by ktbyers** [comment]
@sindhujit Some reason you can't post the real output? I can't really fix the issue without the real output.

**Comment by sindhujit** [comment]
this is all:-

login: admin
password:
last login: Mon Jan 9 18:51:45 from 10.68.14.119 
apic1#

**Comment by ktbyers** [comment]
In your above code, can you do the following:

```
cisco_881 = {
'device_type': 'cisco_nxos',
'ip': 'not essential(x.x.x.x)',
'username': 'admin',
'password': 'Can't disclose this',
'port' : 22, # optional, defaults to 22
'secret': 'secret', # optional, defaults to ''
'verbose': False, # optional, defaults to False
# 'global_delay_factor' : 3,
}
device = ConnectHandler(**cisco_881)
import time           # new
time.sleep(2)         # new
print(repr(device.find_prompt()))               # new line
```

and show me the output?

**Comment by sindhujit** [comment]
it's the same..
Exception Value:	
Router prompt not found: [1m[7m%[m[1m[0m                                                                                [0m[m[m[Japic1# [K

also where the server is listening, i get a 500 http error.. and it prints nothing..
think its failing at the connecthandler.. if i put it in a try except block, it catches the exception..

**Comment by ktbyers** [comment]
Okay, let me look into it.

**Comment by vtocco** [comment]
Hi Kirk, 
I tried this on a switch inside the ACI environment and that works fine, its just the ACI controller sends out that prompt garbage. It does't look like strip_ansi_escape_codes removes all of it (when it's set to True in base_connection.py).  
This is the output from find_prompt() with self.ansi_escape_codes = True:
"[1m[7m%[m[1m[0m                                                                                [0m[m[m[Japic1#"

Not quite sure what those characters are.. 

Thanks for your help!

**Comment by vtocco** [comment]
Try again with code view: 
`'[1m[7m%[m[1m[0m                                                                                [0m[m[m[Japic1#'`

**Comment by ktbyers** [comment]
@vtocco Okay, that helps...yes, that was what I thought might be going on (i.e. that there were ANSI codes in the output).

You can see the prompt is there.

**Comment by sindhujit** [comment]
@ktbyers thanks for the insight.. is there a way to remove these codes?  the code fails at device = ConnectHandler(**cisco_881), so i have no scope of removing the ANSI codes , since thats the 1st line of connection. it stops there and exits.. is there a way u could update the library file?

**Comment by sindhujit** [comment]
@ktbyers any update on this, sir?

**Comment by ktbyers** [comment]
@sindhujit Do you have 'terminal color' configured on your device?

It might be the same issue as this:

https://github.com/ktbyers/netmiko/issues/164

**Comment by ktbyers** [comment]
Okay, those look like this:

off = '\x1b[0m' # off
bd = '\x1b[1m' # bold
rv = '\x1b[7m' # reverse

**Comment by ferjaninasraoui** [comment]
@ktbyers 
i have been able to fix this : 
i did the following under my local netmiko repo : 
1 - Create a new file named 'cisco_apic_ssh.py' under netmiko>cisco
2- copied the cisco_nxos_ssh.py int it and changed the method 'normalize_linefeeds' to reflect the following

```
    def normalize_linefeeds(self, a_string):
        """Convert '1m' or '\x1b[0m' or '\x1b[m' or '\x1b[' or '\x1b[K'to '\n, and remove extra '\r's in the text."""
        newline = re.compile(r'(1m|7m\%|\x1b|\[0m|\[J|\[m)|\[K|\[')
        return newline.sub(self.RESPONSE_RETURN, a_string).replace('\r', '')
```

3- changed the file cisco.__inti__.py and ssh_dispatcher to reflect the new changes

this may not be optimal , but it's working for know , please let me know if you have any thoughts

**Comment by jcrotts** [comment]
I tried out @ferjaninasraoui 's suggestion and it works on a few apics I tested.

Would this be worth creating a subclass of CiscoNxosSSH for, I can submit a PR for it if so.

**Comment by ktbyers** [comment]
The missing ANSI escape codes should be added into the `strip_ansi_escape_codes` method in:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1572

If we do that, then we shouldn't need to subclass the CiscoNxosSSH (i.e. this class should then work).

You should be able to see the pattern in that method (for defining new ANSI escape codes to strip).

I think this is better as it is more consistent with the other netmiko code and it will cover other situations (in addition to the newline stripping).

Let me know if that makes sense.

**Comment by jcrotts** [comment]
Makes sense to me, I'll work on it this week.

**Comment by jcrotts** [comment]
I am having trouble getting this to work by adding codes to the escape_codes list. Most of the codes in the regex posted above are actually already in the list, but aren't getting stripped from the prompt.

I am getting the following with the ios_dispatcher:
```
Traceback (most recent call last):
  File "apic_test.py", line 15, in <module>
    conn = ssh_client(**device_dict)
  File "/Users/jacrotts/Devel/netmiko/netmiko/base_connection.py", line 313, in __init__
    self._try_session_preparation()
  File "/Users/jacrotts/Devel/netmiko/netmiko/base_connection.py", line 723, in _try_session_preparation
    self.session_preparation()
  File "/Users/jacrotts/Devel/netmiko/netmiko/cisco/cisco_ios.py", line 18, in session_preparation
    self.set_base_prompt()
  File "/Users/jacrotts/Devel/netmiko/netmiko/base_connection.py", line 1042, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: '\x1b[0m\x1b[m\x1b[m\x1b[Jtest-apic1# \x1b[K'
```
This is with the nxos_dispatcher:
```
Traceback (most recent call last):
  File "apic_test.py", line 15, in <module>
    conn = ssh_client(**device_dict)
  File "/Users/jacrotts/Devel/netmiko/netmiko/base_connection.py", line 313, in __init__
    self._try_session_preparation()
  File "/Users/jacrotts/Devel/netmiko/netmiko/base_connection.py", line 723, in _try_session_preparation
    self.session_preparation()
  File "/Users/jacrotts/Devel/netmiko/netmiko/cisco/cisco_ios.py", line 18, in session_preparation
    self.set_base_prompt()
  File "/Users/jacrotts/Devel/netmiko/netmiko/base_connection.py", line 1040, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/Users/jacrotts/Devel/netmiko/netmiko/base_connection.py", line 1081, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt:
```

However if I replace the normalize_linefeeds function in cisco_nxos_ssh.py with the one posted above I am able to get a show version command to print out successfully.
