### ISSUE TITLE
Requesting new PIP package with fix for Arista Shell handling

### ISSUE THREAD

**Issue by jniec-js** [ktbyers/netmiko#3534]
### Description of Issue/Question

Could a new release published for Netmiko that includes the changes merged here: https://github.com/ktbyers/netmiko/pull/3483?

Thank you

### Netmiko version
(Paste verbatim output from `pip freeze | grep netmiko` between quotes below)

```
n/a
```

### Netmiko device_type (if relevant to the issue)
(Paste `device_type` between quotes below)

```
n/a
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
n/a
```

### Relevant Python code
(Please try to essentialize your Python code to the minimum code needed to reproduce the issue)
(Paste the code between the quotes below)

```python
n/a
```

**Comment by ktbyers** [comment]
@jniec-js Should be able to just `pip install` the `develop` branch or `pip install` from GitHub and reference a specific commit?

i.e. I shouldn't be blocking your use?

But yes was planning on doing a new Netmiko release in the next few weeks.

Let me know if I am blocking your work for some reason though...

**Comment by jniec-js** [comment]
I see, unfortunately with our infrastructure we can't pull in specific commits/branches and just what is published to pypi, it would be greatly appreciated if you could mint a new package but I understand if you would prefer to stick to your original planned release schedule. 

Thank you,

**Comment by ktbyers** [comment]
@jniec-js 

```
I see, unfortunately with our infrastructure we can't pull in specific commits/branches and just what is published to pypi, 
```

Can you explain why? You are obviously creating me as a bottleneck here and I don't really see why your organization would want to do that?

**Comment by jniec-js** [comment]
We have a rather large, opinionated internal python infrastructure that is not very flexible to this sort of method of important python packages unfortunately. I am working with our team to see if there is a way to import a package that isn't published to pypi. 

I agree that this is not ideal. I can close this issue in the interim, I am sure I will be able to figure something out. Thank you!

**Comment by ktbyers** [comment]
@jniec-js I will try to get this released to pypi either Thanksgiving week or the week after Thanksgiving. I need to do some more thorough testing before I release it. Additionally, there are potentially some things I want to improve in the "cli_tools" code before release (which you probably aren't using).

Regards, Kirk
