### ISSUE TITLE
Configuring a switch

### ISSUE THREAD

**Issue by bambam82** [ktbyers/netmiko#364]
Hi,

I've written a piece of code to configure cisco switches. I've tried to load it from a file and now also using a generator to split it into multiple pieces since I was running into a ValueError "Failed to exit configuration mode". 

I've tried it on 2960X/S and 3560V2 switches. Please let me know if you need anything else.

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dorlab01/devel/scripts/sw_config_execute_dir.py", line 25, in threader
    execute(worker)
  File "/home/dorlab01/devel/scripts/sw_config_execute_dir.py", line 84, in execute
    exit_config_mode=True)
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 912, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/lib/python3.4/dist-packages/netmiko/cisco_base_connection.py", line 48, in exit_config_mode
    pattern=pattern)
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 869, in exit_config_mode
    raise ValueError("Failed to exit configuration mode")
ValueError: Failed to exit configuration mode
```

the specific piece of code:
```
result.append(net_connect.send_config_set(
    config_commands=lists,
    max_loops=max_loops,
    delay_factor=delay_factor,
    exit_config_mode=False))
```

**Comment by ktbyers** [comment]
@bambam82 Which 'config_commands' is it failing on (i.e. what is the value of 'lists' when it fails)?

**Comment by bambam82** [comment]
Hi Kirk,

This is the first group of commands. 
```
lists: ['macro name ise\n', ' no macro description\n', ' description 802.1x\n', ' switch
port mode access\n', ' no switchport access vlan\n', ' switchport voice vlan 200\n', ' authentication control-direction in\n', ' authentication event server alive action reinitialize\n', ' authentication host-mode multi-domain\n', ' authentication order mab dot1x\n', ' authentication priority dot1x mab\n', ' authentication port-control auto\n', ' authentication periodic\n', ' authentication timer reauthenticate 36000\n', ' mab\n', ' no snmp trap link-status\n', ' dot1x pae authenticator\n', ' dot1x timeout held-period 300\n', ' dot1x timeout quiet-period 300\n', ' dot1x timeout ratelimit-period 300\n', ' storm-control broadcast level 2.00\n', ' storm-control multicast level 2.00\n', ' spanning-tree portfast\n', ' spanning-tree guard root\n', ' no spanning-tree bpduguard\n', ' service-policy input Input-Policy\n', '@\n', '!\n', 'default interface FastEthernet0/2\n', 'interface FastEthernet0/2\n', ' shut\n', ' macro apply ise\n', ' no shut\n', '!\n', 'default interface FastEthernet0/3\n', 'interface FastEthernet0/3\n', ' shut\n', ' macro apply ise\n', ' no shut\n', '!\n', 'default interface FastEthernet0/4\n', 'interface FastEthernet0/4\n', ' shut\n', ' macro apply ise\n', ' no shut\n', '!\n', 'default interface FastEthernet0/5\n', 'interface FastEthernet0/5\n', ' shut\n', ' macro apply ise\n', ' no shut\n', '!\n']
```

I turned on debug in 'def send_config_set'. Below is the output when applying the same 'lists'.

```
CAT3560(config-if)#default interface FastEthernet0/3
%Unidirectional control for authentication has no effect when portfast is disabled.
Interface FastEthernet0/3 set to default configuration
CAT3560(config)#interface FastEthernet0/3
CAT3560(config-if)# shut
CAT3560(config-if)# macro apply ise

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dorlab01/devel/scripts/sw_config_execute_dir.py", line 25, in threader
    execute(worker)
  File "/home/dorlab01/devel/scripts/sw_config_execute_dir.py", line 84, in execute
    exit_config_mode=True)
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 912, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/lib/python3.4/dist-packages/netmiko/cisco_base_connection.py", line 48, in exit_config_mode
    pattern=pattern)
  File "/usr/local/lib/python3.4/dist-packages/netmiko/base_connection.py", line 869, in exit_config_mode
    raise ValueError("Failed to exit configuration mode")
ValueError: Failed to exit configuration mode

```

The delay_factor has been increased also to 1.0.

**Comment by ktbyers** [comment]
@bambam82 What does the CLI output of "macro apply ise" look like when you do it manually via SSH.

How long does 'macro apply ise' take to complete when you do it manually?

**Comment by bambam82** [comment]
@ktbyers the output "macro apply ise" doesn't show anything. It will continue as any other command. It will take a few seconds, depending on the latency between the device and the ACS server, since each subcommand of the macro is verified. 

fa0/2 was already processed correctly, before Fa0/3 failed and also the commands to create the actual macro. It isn't consistent when the program crashes. 
I've also seen it doing around 30 interfaces, including other configurations making up for around 330 lines. (including a few "!"). 

That is why i tried the generator to limit the amount of code gonig into the function as a list, but since that didn't work either I found my way to your issuelist.

**Comment by bambam82** [comment]
@ktbyers , were you able to have a look at this issue? If i can do anything to assist, please let me know.

**Comment by ktbyers** [comment]
@bambam82 Let me see if I can reproduce the issue.

**Comment by ktbyers** [comment]
@bambam82 I don't see any issue when I test this:

```
from netmiko import ConnectHandler
from getpass import getpass

cmds = [ 
 'macro name ise\n',
 ' no macro description\n',
 ' description 802.1x\n',
 ' switchport mode access\n',
 ' no switchport access vlan\n',
 ' switchport voice vlan 200\n',
 ' authentication control-direction in\n',
 ' authentication event server alive action reinitialize\n',
 ' authentication host-mode multi-domain\n',
 ' authentication order mab dot1x\n',
 ' authentication priority dot1x mab\n',
 ' authentication port-control auto\n',
 ' authentication periodic\n',
 ' authentication timer reauthenticate 36000\n',
 ' mab\n',
 ' no snmp trap link-status\n',
 ' dot1x pae authenticator\n',
 ' dot1x timeout quiet-period 300\n',
 ' dot1x timeout ratelimit-period 300\n',
 ' storm-control broadcast level 2.00\n',
 ' storm-control multicast level 2.00\n',
 ' spanning-tree portfast\n',
 '@\n',
 '!\n',
 'default interface FastEthernet0\n',
 'interface FastEthernet0\n',
 ' shut\n',
 ' macro apply ise\n',
 ' no shut\n',
 '!\n']

ip = raw_input("Enter IP: ")
username = raw_input("Enter username: ")
password = getpass()

net_connect = ConnectHandler(ip=ip, username=username, password=password, device_type='cisco_ios')
print net_connect.find_prompt()

output = net_connect.send_config_set(cmds, exit_config_mode=False)
print output

**Comment by ktbyers** [comment]
@bambam82 Also, can you post the 10 lines before and after this:

```
  File "/home/dorlab01/devel/scripts/sw_config_execute_dir.py", line 84, in execute
    exit_config_mode=True)
```

**Comment by ktbyers** [comment]
@bambam82 You might also want to try to completely get rid of the macro and do the same thing at the Python level (i.e. just make a list with all your config commands directly in it and apply that list to whatever interfaces that are relevant).

**Comment by snowden404** [comment]
Your net_connect.find_prompt() line helped me realize that some commands weren't properly executed coz netmiko expects something like (conf t)# or just # but ends up finding "--More--" for other commands sent. This helped me debug a week long issue. Thank you. 

Is there a better way to output the errors from netmiko coz this "Pattern not detected" thing doesn't really help much.

**Comment by ktbyers** [comment]
@snowden404 Not really enough information to help you much here. You shouldn't really be seeing `--More--` in the output (Netmiko should automatically disable that).

You might want to create a separate issue and provide more details.

**Comment by snowden404** [comment]
@ktbyers Oh, sorry, my English is not all that good so maybe the point i tried to make was not delivered well. I meant to say thank you for the code you pasted as it contained crucial functions like `net_connect.find_prompt()` that helped me debug mine. And this new reply has helped me realize how `terminal length 0` could have helped me all along. Thank you again

**Comment by ktbyers** [comment]
No worries at @snowden404 . Netmiko should automatically disable output paging shortly after it connects (i.e. execute `terminal length 0` or equivalent for a given platform).
