### ISSUE TITLE
Huawei search pattern issues

### ISSUE THREAD

**Issue by benjaminbudts** [ktbyers/netmiko#366]
Hi Kirk,

Have more time to debug, would love to see your script working on Huawei and can provide you as much feedback as needed as im on a fulltime huawei firewalling/switch project at the moment.

through your example I get :

>>> huawei_6680 = {
...         'device_type': 'huawei',
...         'ip': '192.168.1110.110',
...         'username': 'xxxxx',
...         'password': 'xxxxx',
... }
>>> net_connect = ConnectHandler(**huawei_6680)
>>> net_connect.find_prompt()
u'HRP_A<hostname>'
>>> output = net_connect.send_command("display date")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 761, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: \-\-\-\-\ More\ \-\-\-\-

Huawei does a | more automatically ... Will contact their TAC to see if there is a " | something" to print it fully without the --- MORE --- . 

here the output from the firewall itself :

HRP_A<hostname>display ip int brief
15:40:06  2017/02/01
*down: administratively down
(s): spoofing
Interface                   IP Address      Physical Protocol Description
Eth-Trunk2                  unassigned      up       down     Huawei, USG660..
Eth-Trunk2.80               192.168.110.110 up       up       "GIAL manageme..
Eth-Trunk63                 172.16.3.1      up       up       "HA firewall"
GigabitEthernet0/0/0        192.168.110.210 up       up       Huawei, USG660..
GigabitEthernet1/0/0        unassigned      down     down     Huawei, USG660..
GigabitEthernet1/0/1        unassigned      down     down     Huawei, USG660..
GigabitEthernet1/0/2        unassigned      down     down     Huawei, USG660..
GigabitEthernet1/0/3        unassigned      down     down     Huawei, USG660..
GigabitEthernet1/0/4        unassigned      down     down     Huawei, USG660..
GigabitEthernet1/0/5        unassigned      down     down     Huawei, USG660..
GigabitEthernet1/0/6        unassigned      down     down     Huawei, USG660..
GigabitEthernet1/0/7        unassigned      down     down     Huawei, USG660..
GigabitEthernet1/0/9(XGE)   unassigned      down     down     Huawei, USG660..
GigabitEthernet2/0/0        unassigned      down     down     Huawei, USG660..
GigabitEthernet2/0/1        unassigned      down     down     Huawei, USG660..
GigabitEthernet2/0/2        unassigned      down     down     Huawei, USG660..
GigabitEthernet2/0/3        unassigned      down     down     Huawei, USG660..
GigabitEthernet2/0/4        unassigned      down     down     Huawei, USG660..
GigabitEthernet2/0/5        unassigned      down     down     Huawei, USG660..
GigabitEthernet2/0/6        unassigned      down     down     Huawei, USG660..
GigabitEthernet2/0/7        unassigned      down     down     Huawei, USG660..
GigabitEthernet3/0/0        unassigned      down     down     Huawei, USG660..
GigabitEthernet3/0/1        unassigned      down     down     Huawei, USG660..
  ---- More ----

**Comment by ktbyers** [comment]
@benjaminbudts Here is what Netmiko is currently trying to do (to disable paging on Huawei)

screen-length 0 temporary



Does this work if you do it manually i.e. does this correctly disable paging on the above device?

**Comment by benjaminbudts** [comment]
screen-length 0 temporary   <-- I do not have this command on the huawei firewalls or switches I'm using. 

I have to go under the vty 0 4 interface to configure "screen-length 0"  permanently to overcome this.

Another option I discovered is to use "| no-more"   This is actually something that could replace your screen-length 0 temporary.

Problem with huawei is that command lines slightly differ from product to product...

**Comment by benjaminbudts** [comment]
When I add "| no-more" it works on the huawei commandline. the " --- MORE ---" is gone and he prints everything in one go. But with netmiko it gives an error :

>>> net_connect.find_prompt()
u'HRP_A<hostname>'

>>> output = net_connect.send_command("display current-configuration")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 761, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: HRP\_A\<hostname\>
>>> output = net_connect.send_command("display current-configuration | no-more")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 712, in send_command
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/usr/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 603, in find_prompt
    self.write_channel("\n")
  File "/usr/local/lib/python2.7/site-packages/netmiko/base_connection.py", line 164, in write_channel
    self.remote_conn.sendall(write_bytes(out_data))
  File "/usr/local/lib/python2.7/site-packages/paramiko/channel.py", line 813, in sendall
    sent = self.send(s)
  File "/usr/local/lib/python2.7/site-packages/paramiko/channel.py", line 767, in send
    return self._send(s, m)
  File "/usr/local/lib/python2.7/site-packages/paramiko/channel.py", line 1133, in _send
    raise socket.error('Socket is closed')
socket.error: Socket is closed

my netmiko version :
# pip search netmiko
netmiko (1.2.7)  - Multi-vendor library to simplify Paramiko SSH connections to network devices
  **INSTALLED: 1.2.7 (latest)**

**Comment by ktbyers** [comment]
Okay, what type of Huawei is this? In other words, we need to categorize the different huawei products (as far as software behavior).

**Comment by benjaminbudts** [comment]
Hello Kurt,

USG firewall series, all have same cmdline. in my case the USG6680
and cloudengine switches CE5800 series  both share the same « | no-more »  commandline to get rid of the paging issues

Regards,
Benjamin

**Comment by ktbyers** [comment]
@benjaminbudts Okay, we need to make a new Netmiko platform huawei_usg.

Here is the general process:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md
