### ISSUE TITLE
Juniper - how am I handling [edit] string in output

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#37]

**Comment by supertylerc** [comment]
A description here could help me out with resolving this issue (if necessary).  :)

**Comment by ktbyers** [comment]
Basically, I wanted to make sure I was handling "show" command properly in configuration mode. For example, if the following is executed using netmiko:

pyclass@pynet-jnpr-srx# show routing-options    
static {
    route 0.0.0.0/0 next-hop 10.220.88.1;
    route 1.1.1.0/24 next-hop 10.220.88.1;
    route 1.1.2.0/24 next-hop 10.220.88.1;
    route 1.1.3.0/24 next-hop 10.220.88.1;
    route 1.1.4.0/24 next-hop 10.220.88.1;
    route 1.1.5.0/24 next-hop 10.220.88.1;
    route 1.1.6.0/24 next-hop 10.220.88.1;
}

[edit]
pyclass@pynet-jnpr-srx# 


Then the output should only include:

static {
    route 0.0.0.0/0 next-hop 10.220.88.1;
    route 1.1.1.0/24 next-hop 10.220.88.1;
    route 1.1.2.0/24 next-hop 10.220.88.1;
    route 1.1.3.0/24 next-hop 10.220.88.1;
    route 1.1.4.0/24 next-hop 10.220.88.1;
    route 1.1.5.0/24 next-hop 10.220.88.1;
    route 1.1.6.0/24 next-hop 10.220.88.1;
}

i.e. the command itself should be stripped off, the trailing prompt should be stripped off, and the [edit] (plus other variants of it should be stripped off). You should only get back the show output itself.

**Comment by ktbyers** [comment]
I think this has been handled in the Juniper support.
