### ISSUE TITLE
Dell Force10 EOFError

### ISSUE THREAD

**Issue by pelijaro** [ktbyers/netmiko#373]
Hi friend i'm using netmiko module for DELL FORCE F10 switch. I only need to do "show interfaces status" and this doesn't work, this is the error:

No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "connect.py", line 13, in <module>
    net_connect = ConnectHandler(**dell_f10)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 100, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 144, in __init__
    self.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 498, in establish_connection
    self.remote_conn = self.remote_conn_pre.invoke_shell()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 465, in invoke_shell
    chan = self._transport.open_session()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 711, in open_session
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 832, in open_channel
    raise e
EOFError

And this is my code, it is simple:

#!/usr/bin/env python
#-*- coding: utf-8 -*-

from netmiko import ConnectHandler

dell_f10 = {
    'device_type': 'dell_force10',
    'ip':   'x.x.x.x',
    'username': 'user',
    'password': 'pass'
}

net_connect = ConnectHandler(**dell_f10)

output = net_connect.send_command('show interfaces status')
print(output)

net_connect.disconnect()

What is the problem? I've tried to connect in cisco switch and it works! but with Dell Force no and i need that it works! Could you help me?

Thanks!

[connect.txt](https://github.com/ktbyers/netmiko/files/783022/connect.txt)

[error.txt](https://github.com/ktbyers/netmiko/files/783019/error.txt)

**Comment by ktbyers** [comment]
Yes, that looks like this issue with Dell Force10 and Paramiko:

https://github.com/ktbyers/netmiko/issues/128

We never found a solution for it.

**Comment by networkpadawan** [comment]
any logs|debug|tests that could help? I have a lot of these devices that could use netmiko|ansible:)

**Comment by pathcl** [comment]
You might need enable mode and also have 'secret' for this. Try:
``
#!/usr/bin/env python3
from netmiko import ConnectHandler
''''
hostname DELL - 1

In[6]: %run connect - s4048.py
SSH connection established to 1.1.1.1: 22
Interactive SSH session established
hostname DELL - 1

In[7]: device.send_command('show run|grep vlan')
Out[7]: 'default vlan-id 5\ndefault-vlan disable'

In[8]: print(device.send_command('show run|grep vlan'))
default vlan - id 5
default - vlan disable

In[9]: print(device.send_command('show ip route'))

Codes: C - connected, S - static, R - RIP,
       B - BGP, IN - internal BGP, EX - external BGP, LO - Locally Originated,
       O - OSPF, IA - OSPF inter area, N1 - OSPF NSSA external type 1,

       N2 - OSPF NSSA external type 2, E1 - OSPF external type 1,
       E2 - OSPF external type 2, i - IS - IS, L1 - IS - IS level - 1,
       L2 - IS - IS level - 2, IA - IS - IS inter area, * - candidate default,
       > - non - active route, + - summary route

Gateway of last resort is 172.16.49.1 to network 0.0.0.0

       Destination        Gateway                                                 Dist / Metric Last Change
       ----------- ------- ----------- -----------
 *S    0.0.0.0/0          via 1.1.1.1, Vl 64                                          1/0        6d2h
  C    172.16.49.0/26     Direct, Vl 64                                                   0/0        6d2h

In [10]: device.is_alive()
Out[10]: True

In [11]: device.is_alive??

In [12]: device.is_alive()
Out[12]: True

In [13]: device.disconnect()

In [14]: device.is_alive()
Out[14]: False
'''
dev = {
    'device_type': 'dell_force10',
    'ip': '1.1.1.1',
    'username': 'test',
    'secret': 'test',
    'password': 'test',
    'verbose': 'True',
    'global_delay_factor': 0,
}

device = ConnectHandler(**dev)
device.enable()
interfaces = device.send_command('show interfaces status')
print(interfaces)

**Comment by networkpadawan** [comment]
S4048 are working here fine, S50 are not, they are FTOS8 so it seems to be a switch issue, but we have quite a lot of them:/ im testing with ntc-ansible with paramiko 2.4.0 and netmiko 2.0.1

**Comment by networkpadawan** [comment]
'''
print(interfaces)SSH connection established to 10.118.14.1:22
No handlers could be found for logger "paramiko.transport"







Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 168, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 187, in __init__
    self.establish_connection()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 669, in establish_connection
    self.remote_conn = self.remote_conn_pre.invoke_shell()
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 510, in invoke_shell
    chan = self._transport.open_session()
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 767, in open_session
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 891, in open_channel
    raise e
EOFError
'''

**Comment by networkpadawan** [comment]
with the S4048:
```
SSH connection established to 10.189.15.2:22
Interactive SSH session established
```

**Comment by networkpadawan** [comment]
the only thing I have so far is that it seems that they are different ssh daemons running on the F10s
s4048 uses openssh6.9 and ths S50 seems to be some custom version "ssh_v2.0@force10networks.com\r" according to a pcap

**Comment by networkpadawan** [comment]
an the window sizes for tcp also differ, parmiko starts with 29200 on both sessions, but on s4048 it replies with 32768 but the s50 decreases to 16384

**Comment by ktbyers** [comment]
@networkpadawan You can turn on Netmiko/Paramiko debugging here:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Ultimately, we might have to get someone involved from Dell on the developer side...I dug into it a lot once and I could never resolve the issue.

Please post here what you see on the debugging (if possible).

**Comment by networkpadawan** [comment]
this is what I got
```
DEBUG:paramiko.transport:starting thread (client mode): 0x1f0aa10L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-SSH_v2.0@force10networks.com
INFO:paramiko.transport:Connected (version 2.0, client SSH_v2.0@force10networks.com)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'3des-cbc'] server encrypt:[u'3des-cbc'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: 3des-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.118.14.1: 615b82a1ef969e1f97cb9db9f9cc3a13
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication continues...
DEBUG:paramiko.transport:Methods: [u'password']
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
WARNING:paramiko.transport:Oops, unhandled type 3
DEBUG:paramiko.transport:EOF in transport thread
```

**Comment by networkpadawan** [comment]
`WARNING:paramiko.transport:Oops, unhandled type 3`
this one seems to be worth investigating because:
https://github.com/ansible/ansible/issues/24367
something on the pty session

**Comment by networkpadawan** [comment]
with paramiko.startshell it works, but not with paramiko.exec_command
it seems that it is something with the netmiko connectHandler. I notice that dell_force reuses ciscossh code. is it possible to do a barebones dell handler? what code is needed to "duplicate"? I can test but don´t want to bork the ciscossh that is working.

**Comment by networkpadawan** [comment]
```
    self.remote_conn = self.remote_conn_pre.invoke_shell()
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 510, in invoke_shell
    chan = self._transport.open_session()
```
calls https://github.com/paramiko/paramiko/blob/f1562d76511890c648c657c45debe57b5112872f/paramiko/client.py#L486
that acll exec command that seems to create the same issue with paramiko exec command

**Comment by networkpadawan** [comment]
any help please?

**Comment by ktbyers** [comment]
Can you post the working code with Paramiko start_shell?

**Comment by ktbyers** [comment]
Yes, I agree that unhandled type 3 message is interesting.

I would just focus on a working Paramiko solution i.e. something we can connect and execute multiple commands on the channel and get the data back.

We can then figure out how to integrate it into Netmiko.

**Comment by networkpadawan** [comment]
not working:
```
import paramiko, os
paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
paramiko.util.log_to_file('/paramiko.log')
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('10.118.14.1',username='USERNAME', password='PASSWORD')
commmand = ssh.exec_command('show interfaces status',get_pty=False)
print command.read()
```
working:
```
import paramiko, os
paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
paramiko.util.log_to_file('/paramiko.log')
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('10.118.14.1',username='USERNAME', password='PASSWORD')
channel = ssh.invoke_shell()
channel.send('show interface status| no-more\n')
output=channel.recv(2024)
print(output)
````

**Comment by networkpadawan** [comment]
if I use invoke_shell with paramiko it works fine, as soon as I use exec_command it crashes with EOF error

**Comment by ktbyers** [comment]
@networkpadawan Netmiko uses `invoke_shell` and not `exec_command`.

**Comment by ktbyers** [comment]
And what happens in your working situation if you execute multiple commands on the SSH channel, does it continue to work?

**Comment by networkpadawan** [comment]
I can keep executing: 
```
channel.send('show interface status| no-more\n')
output=channel.recv(2024)
print(output)
 ```
```
channel.send('show version\n')
output=channel.recv(2024)
print(output)
```
the session does not close.

I understand that netmiko uses invoke_shell, but can it be something on the set up of the connection?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 168, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 187, in __init__
    self.establish_connection()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 669, in establish_connection
    self.remote_conn = self.remote_conn_pre.invoke_shell()
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 510, in invoke_shell
    chan = self._transport.open_session()
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 767, in open_session
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 891, in open_channel
    raise e
EOFError
```
base_connection is calling remote_conn_pre.invoke_shell that calls `open_channel`, is it possible to do a "barebones" call? without reusing the cisco code?

**Comment by ktbyers** [comment]
We need to figure out what is different (between what you posted) and why the two are behaving differently.

 I say this because if we re-implemented Paramiko straight in Dell driver, we would end up needing to re-implement what we have in base (as the items there are needed)...which would probably imply we will re-create the bug.

But this gives us a big clue that it works with what you have above.

Does this Dell device support SSH keys?

**Comment by networkpadawan** [comment]
but maybe there is some item that is causing the issue? I would like to go from scratch and start adding on top of it to see which one breaks, (until feature complete with the current base) and maybe get one ```legacy_connection``` ...I can do the tests and start adding but don´t know where to start:)

I think it does based on:
```
BAS-S1-OOB01(conf)#ip ssh pub-key-file ?
WORD                    File name for hostbased authentication
```
but have never implemented it

**Comment by ktbyers** [comment]
You will probably need to copy over the entire __init__ method (about 100 lines of code), establish_connection (about 40 lines of code), _connect_params_dict, and _build_ssh_client method. 

You might want to just test if the connection still works, when you add all of the needed Netmiko arguments to the connect() method.

You can print out what each one of these is getting set to in the failing case. Here are the default arguments, you can see what these default to in `__init__` method definition.

```
 593         conn_dict = {
 594             'hostname': self.host,
 595             'port': self.port,
 596             'username': self.username,
 597             'password': self.password,
 598             'look_for_keys': self.use_keys,        # Should default to False
 599             'allow_agent': self.allow_agent,      # Should default to False
 600             'key_filename': self.key_file,           # I think this defaults to null string
 601             'timeout': self.timeout,
 602         }
```

**Comment by networkpadawan** [comment]
well, I´m trowing in the towell, I can´t seem to get this to work.

It seems that the issue is that the force10 is authenticating both password and certificate because with netmiko i get `self <paramiko.Transport at 0x1c33490L (cipher 3des-cbc, 192 bits) (connected; awaiting auth)>`
but with paramiko ` <paramiko.Transport at 0x1a8c110L (cipher 3des-cbc, 192 bits) (active; 0 open channel(s))>`
but can´t understand why, and it´s the same with ansible, it gives the exact same error. only plain paramiko works

**Comment by ktbyers** [comment]
@networkpadawan Did you try unsetting the `key_filename` argument in Netmiko and see if it works then?

Eliminate line 600 below:

```
 593         conn_dict = {
 594             'hostname': self.host,
 595             'port': self.port,
 596             'username': self.username,
 597             'password': self.password,
 598             'look_for_keys': self.use_keys,        # Should default to False
 599             'allow_agent': self.allow_agent,      # Should default to False
 600    #             'key_filename': self.key_file,           # I think this defaults to null string
 601             'timeout': self.timeout,
 602         }
```

It would also be interesting to see if your Paramiko solution works if you add these arguments look_for_keys=False, allow_agent=False.

Note, I think Paramiko defaults both of those to True.

**Comment by networkpadawan** [comment]
commenting didn´t help:/
it works with the 2 arguments:
```
>>> import paramiko, os
>>> paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
>>> paramiko.util.log_to_file('/paramiko.log')
>>> ssh = paramiko.SSHClient()
>>> ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> ssh.connect('10.118.14.1',username='user', password='passwprd',look_for_keys='False', allow_agent='False')
DEBUG:paramiko.transport:starting thread (client mode): 0x16f4450L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-SSH_v2.0@force10networks.com
INFO:paramiko.transport:Connected (version 2.0, client SSH_v2.0@force10networks.com)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'3des-cbc'] server encrypt:[u'3des-cbc'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: 3des-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.118.14.1: 615b82a1ef969e1f97cb9db9f9cc3a13
DEBUG:paramiko.transport:Trying discovered key 8d0801ef1a44be59ff745dcc18481e55 in /root/.ssh/id_rsa
DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:Authentication type (publickey) not permitted.
DEBUG:paramiko.transport:Allowed methods: [u'password']
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
>>> channel = ssh.invoke_shell()
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
```

what does not make sense to me is that it seems to try pubkey first and then password:
```
DEBUG:paramiko.transport:Authentication type (publickey) not permitted.
DEBUG:paramiko.transport:Allowed methods: [u'password']
``` 
but it with netmiko it goes directly to password
```
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication continues...
DEBUG:paramiko.transport:Methods: [u'password']
````
and then I think it tries to use the certificate, but  I´m not sure...

**Comment by ktbyers** [comment]
This needs to be Booleans not strings:

```
ssh.connect('10.118.14.1',username='user', password='passwprd',
        look_for_keys=False, allow_agent=False)
```

Note, there are no quotes around the False keyword (False in quotes is a string that would probably behave not how you wanted...).

**Comment by networkpadawan** [comment]
That´s it!! with  ` look_for_keys=False` I get the same error. Ill try to reproduce that on netmiko

**Comment by networkpadawan** [comment]
:) manually setting ` 'look_for_keys': True,`
works on netmiko!!!

**Comment by ktbyers** [comment]
@networkpadawan So your settings are to provide `username`, `password` and `look_for_keys=True` and it works? 

Can you post the working code in Netmiko i.e. what is the change required for it to work with Dell?

Do you have any key files in ~/.ssh? Paramiko will automatically use one of these keys if it exists (id_rsa, id_dsa, id_ecdsa).

**Comment by ktbyers** [comment]
@networkpadawan Can you post your working code so that we can incorporate this fix into Netmiko.

**Comment by crazychengmm** [comment]
Hi @ktbyers @networkpadawan guys, I have same problem here.
as you say,I set look_for_keys=False, allow_agent=False on conect method,but not work.
Here is debug log:
DEB [20180620-16:32:58.301] thr=5   paramiko.transport: starting thread (client mode): 0x9d804cd0L
DEB [20180620-16:32:58.301] thr=5   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.1
DEB [20180620-16:32:58.318] thr=5   paramiko.transport: Remote version/idstring: SSH-1.99-SSH_v2.0@force10networks.com
INF [20180620-16:32:58.318] thr=5   paramiko.transport: Connected (version 1.99, client SSH_v2.0@force10networks.com)
DEB [20180620-16:32:58.322] thr=5   paramiko.transport: kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'3des-cbc'] server encrypt:[u'3des-cbc'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20180620-16:32:58.322] thr=5   paramiko.transport: Kex agreed: diffie-hellman-group-exchange-sha1
DEB [20180620-16:32:58.322] thr=5   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20180620-16:32:58.322] thr=5   paramiko.transport: Cipher agreed: 3des-cbc
DEB [20180620-16:32:58.322] thr=5   paramiko.transport: MAC agreed: hmac-sha1
DEB [20180620-16:32:58.322] thr=5   paramiko.transport: Compression agreed: none
DEB [20180620-16:32:58.326] thr=5   paramiko.transport: Got server p (2048 bits)
DEB [20180620-16:32:58.793] thr=5   paramiko.transport: kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEB [20180620-16:32:58.794] thr=5   paramiko.transport: Switch to new keys ...
DEB [20180620-16:32:58.803] thr=2   paramiko.transport: Adding ssh-rsa host key for 192.168.2.25: 0d9ff24df2ec62020f29f11533357218
DEB [20180620-16:32:58.992] thr=5   paramiko.transport: userauth is OK
INF [20180620-16:32:58.997] thr=5   paramiko.transport: Authentication continues...
DEB [20180620-16:32:58.997] thr=5   paramiko.transport: Methods: [u'password']
DEB [20180620-16:32:59.004] thr=2   paramiko.transport: [chan 0] Max packet in: 32768 bytes
WAR [20180620-16:32:59.007] thr=5   paramiko.transport: Oops, unhandled type 3
DEB [20180620-16:33:28.102] thr=5   paramiko.transport: EOF in transport thread

ERROR:
![image](https://user-images.githubusercontent.com/23517542/41647171-371e8d0c-74a8-11e8-9f75-f8421f4d17ee.png)

Thanks

**Comment by ktbyers** [comment]
@crazychengmm What happens if you do:

```
ssh.connect('10.10.10.10',username='user', password='password',
        look_for_keys=True, allow_agent=True)
```

i.e. when you send a password and look_for_keys=True and allow_agent=True.

**Comment by carlniger** [comment]
inactive. closing.
