### ISSUE TITLE
How do I use netmiko with a jump box (SunOs)

### ISSUE THREAD

**Issue by 1001QAdotNET** [ktbyers/netmiko#374]
Hi guys

Our access to network devices is controlled via a jump box. Any session must be initiated from this box only.  I have tried ssh tunneling via putty but that does not work
What type of driver should I use for SunOS?
How do I go around the jump box issue ? 

Edit: for my last question I think that this article is the answer: https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

client(Windows-Eclipse-netmiko)---->Bastion(SuntOS)----->cisco/F5

**Comment by ktbyers** [comment]
@1001QAdotNET Yes, that article is how to use a Jump Box with Netmiko. I have no idea whether it will work with SunOS, however.
