### ISSUE TITLE
Parenthesis at the end of hostname - check_config_mode always returns True

### ISSUE THREAD

**Issue by shamanu4** [ktbyers/netmiko#375]
Example scenario: IP address added to hostname and in result prompt looks like this:
`Switch(127.0.0.1)#` and in config mode like this `Switch(127.0.0.1)(config)#`
Checking for string `)#` returns `True` in both cases.

**Comment by ktbyers** [comment]
EdgeCore is not supported. You should make any necessary adjustments in the EdgeCore driver PR.

**Comment by shamanu4** [comment]
@ktbyers 
It is not function of EdgeCore. I have hundreds of Cisco switches in network configured in this way and I need to manage them. Hostname contains physical address and 2 last bytes of IP e.g. `European.76(3.11)`.

**Comment by ktbyers** [comment]
@shamanu4 Yes, I don't see myself changing this. 

It is very hard to meet all the requirements and changing nature of the router prompt as it is. There are certain requirements the hostname will have to meet i.e. no '#' in it and no parenthesis in it.
