### ISSUE TITLE
`#` symbol in hostname - check_enable_mode always returns True

### ISSUE THREAD

**Issue by shamanu4** [ktbyers/netmiko#376]

**Comment by ktbyers** [comment]
Why does the hostname have a '#' in it?

Is this a function of the EdgeCore device or the hostname you chose?

**Comment by shamanu4** [comment]
It is possible to set such hostname even in Cisco ios. And fix is pretty simple - change string check from `in` to `endswith`

**Comment by ktbyers** [comment]
If you do this (i.e. use a hostname with # in it), you are setting yourself up for automation failure...

**Comment by shamanu4** [comment]
Ok. Not an issue then.
