### ISSUE TITLE
Check if device is ready to accept next command

### ISSUE THREAD

**Issue by Wyko** [ktbyers/netmiko#378]
Hey Kirk, 

Several times now I've experienced that running a command will fail in one of two ways. Either it will 

1. Return the prompt (alone or multiple copes of the prompt separated by newlines), or; 
2. It will return some segment of the result from the last command. 

For example, on a Cisco IOS device (my primary use case) I might execute "show run" and then "show CDP neigh det". 95% of the time it works, but when it fails it returns some version of the prompt or it will return the config. I suspect this may have something to do with my VPN connection falling out, since my internet is really spotty sometimes.

What can be done to check if a device is actually done finishing the task and is ready to continue?

**Comment by ktbyers** [comment]
@Wyko Can you post an example (code + output). This will help me understand.

Also what version of Netmiko are you using?

**Comment by Wyko** [comment]
My apologies for not responding. I have been unable to reproduce this issue since I mentioned it. It was likely just a bug in my own code.
