### ISSUE TITLE
Nokia SROS v14 Prompt is broken.

### ISSUE THREAD

**Issue by compyy** [ktbyers/netmiko#379]
Hello,

it seems script is broken if there is a long msg after login, could be buffer issue ?

>>> net_connect = ConnectHandler(**ALU)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 100, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 145, in __init__
    self.session_preparation()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/alcatel/alcatel_sros_ssh.py", line 11, in session_preparation
    self.set_base_prompt()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/alcatel/alcatel_sros_ssh.py", line 16, in set_base_prompt
    cur_base_prompt = super(AlcatelSrosSSH, self).set_base_prompt(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 593, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: the EULA, then Nokia is unwilling to lic

Actually what happens :

Login: admin
Password: 

 SR OS Software
 Copyright (c) Nokia 2016.  All Rights Reserved.
 
 Trademarks
 
 Nokia and the Nokia logo are registered trademarks of Nokia. All other
 trademarks are the property of their respective owners.
 
 IMPORTANT:  READ CAREFULLY
 
 The SR OS Software (the "Software") is proprietary to Nokia and is subject
 to and governed by the terms and conditions of the End User License
 Agreement accompanying the product, made available at the time of your order,
 or posted on the Nokia website (collectively, the "EULA").  As set forth
 more fully in the EULA, use of the Software is strictly limited to your 
 internal use.  Downloading, installing, or using the Software constitutes
 acceptance of the EULA and you are binding yourself and the business entity
 that you represent to the EULA.  If you do not agree to all of the terms of
 the EULA, then Nokia is unwilling to license the Software to you and (a) you
 may not download, install or use the Software, and (b) you may return the
 Software as more fully set forth in the EULA.
 
 This product contains cryptographic features and is subject to United States 
 and local country laws governing import, export, transfer and use. Delivery 
 of Nokia cryptographic products does not imply third-party authority to 
 import, export, distribute or use encryption.
 
 If you require further assistance please contact us by sending an email
 to support@nokia.com.

A:VSR-I#

**Comment by ktbyers** [comment]
What version of Netmiko are you using?

**Comment by compyy** [comment]
Name: netmiko
Version: 1.2.7

How can i debug the session, is there any guide ?

**Comment by compyy** [comment]
Ok, i fixed it with >> global_delay_factor=2 >> how can we make it as default ?

**Comment by ktbyers** [comment]
@compyy Try Netmiko 1.2.8 which I just released and see if you have the same issue.

**Comment by ktbyers** [comment]
@compyy Did you try this with Netmiko 1.2.8?
