### ISSUE TITLE
Enterasys SecureStack doesn't need enable() and disable_paging()

### ISSUE THREAD

**Issue by tevaum** [ktbyers/netmiko#380]
I'm testing netmiko with my Enterasys SecureStack switches/routers and, at first it didn't work:

ValueError: Failed to enter enable mode.

So I looked at the code and it seems that it was only testes and I'm supposing that it was only testes on enterasys routers. I commented out the self.enable() and self.disable_paging() and it worked correctly with my devices.

So I thought: should we create another class, say EnterasysSecurestackSSH or something like that so that we don't break backward compatibility and add support to other devices?

If this should be the solution, I can make a pull request.

Thanks for the time.

**Comment by ktbyers** [comment]
So Enterasys SecureStack is different than other Enterasys devices?

The Enterasys driver currently does this:

```
"""Enterasys support."""
from __future__ import unicode_literals
from netmiko.cisco_base_connection import CiscoSSHConnection


class EnterasysSSH(CiscoSSHConnection):
    """Enterasys support."""
    def session_preparation(self):
        """Enterasys requires enable mode to disable paging."""
        self.enable()
        self.set_base_prompt()
        self.disable_paging(command="set length 0\n")

**Comment by ktbyers** [comment]
So it disables paging using:

```
set length 0
```

and would default to a Cisco enable mode.

**Comment by tevaum** [comment]
What I did was comment out the self.enable() and self.disable_paging(command="set length 0\n").
After that, I was able to run commands sucessfully.

**Comment by ktbyers** [comment]
Yes, is the SecureStack different than other Enterasys switches?

When you manually execute commands on the SecureStack do you observe output paging and what do you do to disable it?

**Comment by tevaum** [comment]
Just checked and set length  0 works on my device, so it doesn't need to be commented.
By default, SecureStack doesn't do paging (it's length is 0 by default)
It only have enable in router mode, which isn't the default.
I tryed the following to check:

conn = netmiko.ConnectHandler(**dist_dti);


conn.send_command('router');
conn.enable()
o = conn.send_command('show ip route');

but it still gives me the **Failed to enter enable mode.** error.

**Comment by ktbyers** [comment]
What CLI commands do you do manually to enter `enable` in router mode?

**Comment by tevaum** [comment]
you log in the switch and enter
**router**
then you enter
**enable**

That's it

**Comment by ktbyers** [comment]
Yes, can you post what the actual CLI session looks like including the prompt.

**Comment by tevaum** [comment]
tevaum@alpha:~/Projetos/enterasys$ ssh -l estevao 10.20.1.1
estevao@10.20.1.1's password: 


Enterasys C3 
Command Line Interface 

Enterasys Networks, Inc. 
9 Northeastern Boulevard
Salem, NH 03079 U.S.A. 

Phone: +1 603 952 5000 
E-mail: support@enterasys.com 
WWW: http://www.enterasys.com 

(c) Copyright Enterasys Networks, Inc. 2013

Chassis Serial Number:      09080919895A
Chassis Firmware Revision:  06.61.11.0006


Dist-DTI-1.1(su)->router
Dist-DTI-1.1(su)->router>enable
Dist-DTI-1.1(su)->router#configure terminal 
Enter configuration commands:
Dist-DTI-1.1(su)->router(Config)#

**Comment by ktbyers** [comment]
And what happens with `enable` if not in in `router` mode?

**Comment by tevaum** [comment]
There's no `enable` if not in `router` mode here.

**Comment by ktbyers** [comment]
Yes, can you post what happens in the CLI when you type `enable` this will help me write an error handler (if that is the best way to do it).

**Comment by tevaum** [comment]
I think that's cool handling the error... I realised that it's an exception... I can handle it in my code also, if necessary...

```
tevaum@alpha:~/Projetos/enterasys$ ssh -l estevao 10.20.1.1
estevao@10.20.1.1's password: 


Enterasys C3 
Command Line Interface 

Enterasys Networks, Inc. 
9 Northeastern Boulevard
Salem, NH 03079 U.S.A. 

Phone: +1 603 952 5000 
E-mail: support@enterasys.com 
WWW: http://www.enterasys.com 

(c) Copyright Enterasys Networks, Inc. 2013

Chassis Serial Number:      09080919895A
Chassis Firmware Revision:  06.61.11.0006


Dist-DTI-1.1(su)->enable
                   ^
% Invalid input detected at '^' marker.

Dist-DTI-1.1(su)->

```

**Comment by ktbyers** [comment]
Okay, I think I have enough to write a proposed fix...I will update here once I have a proposed fix for this.

**Comment by tevaum** [comment]
Thanks! I'll be waiting :]

**Comment by ktbyers** [comment]
@tevaum Okay, I put in this fix in the Netmiko `develop` branch on GitHub. Can you test it?

**Comment by ktbyers** [comment]
@tevaum Did you test this fix that is in the `develop` branch?

**Comment by tevaum** [comment]
@ktbyers sorry. Wasn't able to test before. It still didn't work...

I'm trying to take a look at the code to find anything that can help with this...

One thing is that enable doesn't ask for a password on my switches and you're using "password" as the stop pattern for `read_until_prompt_or_pattern`.

I also found out that read_until_prompt_or_pattern is not returning the error message. It's just an empty string (`""`). Does the underlying part of the library that connects and executes commands threat stderr and stdout differently?

Thanks for working on this.

**Comment by ktbyers** [comment]
@tevaum Can you post what the CLI looks like for going into `enable`?

Also can you post the exception you are now seeing?

**Comment by tevaum** [comment]
It's the same: `ValueError: Failed to enter enable mode.`.

What I'm not understanding is why the `read_until_prompt_or_pattern` called after the `enable` command is returning `""`. I know this because I put a `print('"%s"' % output)` right after the `read_until_prompt_or_pattern` and it doesn't return the `% Invalid input detected at` that usually happens when I'm connected to the switch.

Also, FYI, there's no password prompt. No password is asked when you run `enable` in router mode. The switch knows that I can enter enable mode because my RADIUS server informed it on login.

**Comment by ktbyers** [comment]
@tevaum Can you turn on logging and send me output log file that is generated:

Put this near the top of your file.

```
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
```

Just edit the log to remove anything that is confidential...like replace "your_real_password" with "password".



Kirk

**Comment by tevaum** [comment]
File attached.
[test.txt](https://github.com/ktbyers/netmiko/files/828522/test.txt)

**Comment by ktbyers** [comment]
And when you do it manually it looks like this?

```
Dist-DTI-1.1(su)->enable
                   ^
% Invalid input detected at '^' marker.

Dist-DTI-1.1(su)->
```

**Comment by tevaum** [comment]
Yes. That's really strange :/

**Comment by ktbyers** [comment]
What happens if you change this line:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/enterasys/enterasys_ssh.py#L23

From:

```
            self.write_channel(self.normalize_cmd(cmd))
```

To:

```
            self.write_channel(cmd + "\r")
```

**Comment by tevaum** [comment]
Same error. Log attached.

[test-02.txt](https://github.com/ktbyers/netmiko/files/828789/test-02.txt)

**Comment by ktbyers** [comment]
Okay, I don't understand why there is never any data from the Enterasys device?

We send `enable`, but never get anything back.

**Comment by tevaum** [comment]
Documentation of paramiko says something interesting in Channel.set_combine_stderr [1]:

> Set whether stderr should be combined into stdout on this channel. The default is False, but in some cases it may be convenient to have both streams combined.
>
> If this is False, and exec_command is called (or invoke_shell with no pty), output to stderr will not show up through the recv and recv_ready calls. You will have to use recv_stderr and recv_stderr_ready to get stderr output.
> 
> If this is True, data will never show up via recv_stderr or recv_stderr_ready

So we really can have different APIs to read from stdout and stderr... I tried to call set_combine_stderr on base_connection.py [2] without success... I checked and invoke_shell was being called without arguments. I forced it to use vt100 with 80x24 but also no success.

I also tried changing base_connection read_channel to call `recv_stderr` first and then `recv` and print both in the log file, but no success... I'm really lost here :/

[1] http://docs.paramiko.org/en/2.1/api/channel.html#paramiko.channel.Channel.set_combine_stderr
[2] https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L487

**Comment by ktbyers** [comment]
@tevaum What happens if you run this code:

```

from getpass import getpass
from netmiko import ConnectHandler

if True:
    password = getpass("Enter router password: ")
    device = {
        'device_type': 'terminal_server',
        'ip':   '10.10.10.70',      # Update with your IP address
        'username': 'admin',     # Update with your username
        'password': password
    }

    net_connect = ConnectHandler(**device)
    print net_connect.find_prompt()
```

**Comment by tevaum** [comment]
Same problem, as it tryes to enter enable mode before running the `find_prompt`. BTW, I'm using python3, is that a problem?

> tevaum@alpha:~/Projetos/enterasys$ ./ktbyers.py 
> Enter router password: 
> ""
> Traceback (most recent call last):
>   File "./ktbyers.py", line 14, in <module>
>     net_connect = ConnectHandler(**device)
>   File "/usr/lib/python3/dist-packages/netmiko/ssh_dispatcher.py", line 112, in ConnectHandler
>     return ConnectionClass(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 144, in __init__
>     self.session_preparation()
>   File "/usr/lib/python3/dist-packages/netmiko/enterasys/enterasys_ssh.py", line 11, in session_preparation
>     self.enable()
>   File "/usr/lib/python3/dist-packages/netmiko/enterasys/enterasys_ssh.py", line 33, in enable
>     raise ValueError("Failed to enter enable mode.")
> ValueError: Failed to enter enable mode.
>

**Comment by tevaum** [comment]
Ahh, ignore the "", I was printing some stuff... clean up my modifications. Here's the output:

> tevaum@alpha:~/Projetos/enterasys$ ./ktbyers.py 
> Enter router password: 
> Traceback (most recent call last):
>   File "./ktbyers.py", line 14, in <module>
>     net_connect = ConnectHandler(**device)
>   File "/usr/lib/python3/dist-packages/netmiko/ssh_dispatcher.py", line 112, in ConnectHandler
>     return ConnectionClass(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/netmiko/base_connection.py", line 144, in __init__
>     self.session_preparation()
>   File "/usr/lib/python3/dist-packages/netmiko/enterasys/enterasys_ssh.py", line 11, in session_preparation
>     self.enable()
>   File "/usr/lib/python3/dist-packages/netmiko/enterasys/enterasys_ssh.py", line 31, in enable
>     raise ValueError("Failed to enter enable mode.")
> ValueError: Failed to enter enable mode.
>

**Comment by tevaum** [comment]
I commented the `self.enable()` line in EnterasysSSH `session_preparation` and ran your script again. Here's the result:

> tevaum@alpha:~/Projetos/enterasys$ ./ktbyers.py 
> Enter router password: 
> Dist-DTI-1.1(su)->

That is really the prompt of the switch. :]

**Comment by ktbyers** [comment]
@tevaum It looks like you didn't run the code that I posted above?

It should be `device_type = 'terminal_server'`

Also, I am not calling the `enable()` method. I am manually putting in `enable` directly using write_channel.

**Comment by tevaum** [comment]
Oh, sorry. I pasted your code and changed the `device_type` to enterasys :/

Here's how it looks now
> tevaum@alpha:~/Projetos/enterasys$ cat ktbyers.py 
> #!/usr/bin/python3
> 
> from getpass import getpass
> from netmiko import ConnectHandler
> 
> password = getpass("Enter router password: ")
> device = {
>     'device_type': 'terminal_server',
>     'ip':   '10.20.1.1',      # Update with your IP address
>     'username': 'estevao',     # Update with your username
>     'password': password
> }
> 
> net_connect = ConnectHandler(**device)
> print(net_connect.find_prompt())
>
>
> tevaum@alpha:~/Projetos/enterasys$ ./ktbyers.py 
> Enter router password: 
> Dist-DTI-1.1(su)->
>

**Comment by ktbyers** [comment]
@tevaum Okay and what about this part of it:

```
Run this code using:

python -i kbyers.py
This will drop you into the Python shell after it runs.

In the Python shell try the following:

net_connect.write_channel("enable\r\n")
net_connect.read_channel()
You might have to experiment with using '\r' or '\n' at the end of 'enable'. Let's see if this gives us any clues as to what is happening.
```

**Comment by ktbyers** [comment]
Run the code using `python -i kbyers.py`

Then go into the Python shell and manually try to use read_channel() and write_channel()

**Comment by tevaum** [comment]
> tevaum@alpha:~/Projetos/enterasys$ python3 -i ./ktbyers.py 
> Enter router password: 
> Dist-DTI-1.1(su)->
> >>> net_connect.write_channel("enable\n")
> >>> net_connect.read_channel()
> "enable\r\n                   ^\r\n% Invalid input detected at '^' marker.\r\n\r\nDist-DTI-1.1(su)->"
> >>>

**Comment by tevaum** [comment]
Hi, @ktbyers. Any news about this issue?

**Comment by apepelis** [comment]
1.4.2 still has this issue.

**Comment by ktbyers** [comment]
@apepelis @tevaum I just read through the issue again, I don't think we understand why it is failing. I should have some more time to work on it in the next few weeks.

**Comment by apepelis** [comment]
I haven't looked at this since I posted that. Going from memory. 
My gear are switches (or switch/routers). There is no "enable". When you call enable on the switch prompt, you get an error. I think it then changes to the router prompt. Then it looks for # and doesn't see that.

S4(su)->enable
Error: Unknown: "enable"
S4(su)->router
S4(su-router)->enable
Error: Unknown: "enable"

**Comment by ktbyers** [comment]
Yes, but some Enterasys devices require enable() to disable paging (at least that is my understanding, correct me if I am wrong). 

Also the troubleshooting above didn't show the enable happening (this is from my quick read of the above message, I need to review).

So I need to differentiate somehow between the Enterasys that require enable() and those that don't support it.

Once again...correct me if I am wrong as I am going on information provided to me by others and don't have direct access to Enterasys devices.

**Comment by apepelis** [comment]
I have never heard of that. Granted, I have only worked at Enterasys/Cabletron/Extreme Networks for 18 years. If you can give me a device type that you have seen enable on, I can find one and test it, but none of my devices have the need for enable.

**Comment by ktbyers** [comment]
Okay, should be fixed here:

https://github.com/ktbyers/netmiko/commit/93849158eb4f1c3cc7756ff5614b9ff0efe1c17f

I removed enable() call from `session_preparation`. This also corrected a similar issue on Extreme.

It would be good if someone could check if this fixes the issue and that both `send_command()` and `send_config_set` methods work properly on Enterasys and Extreme.
