### ISSUE TITLE
Cisco telepresence might still have an issue

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#381]
See bottom of PR here:

https://github.com/ktbyers/netmiko/pull/356

**Comment by ahmadbarrin** [comment]
@ktbyers 
Thanks for adding my last Telepresence PR on master release 1.3.0 !
Also on my [personal website](http://ahmadbarrin-software.com/index.html), I've added a link to your Netmiko project. I hope you're fine with it. I've not, just tell me and I can remove or change it.

Regards,
Ahmad

**Comment by ktbyers** [comment]
Sure, looks good.
