### ISSUE TITLE
Generic Terminal Server Device Type

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#383]
FYI, I have created a 'terminal_server' device_type. The general idea is that it won't do anything post SSH connection (or won't do much anyways).

Consequently, post SSH connection, you can then do:

```
>>> net_connect.write_channel("\r")
>>> net_connect.read_channel()
'\r\npynet-rtr1#'
```

In other words, you can directly interact with the terminal server to get logged-in to the end network device.

Once you have done this, you can then `redispatch` the connect (i.e. reset the device_type and class to the proper netmiko class.

```
>>> from netmiko import redispatch

# Dynamically reset the class back to CiscoIosSSH
>>> redispatch(net_connect, device_type='cisco_ios')
>>> 
>>> net_connect.device_type
'cisco_ios'
>>> net_connect.__class__
<class 'netmiko.cisco.cisco_ios.CiscoIosSSH'>

>>> net_connect.base_prompt
'pynet-rtr1'
```

I am looking for people that are able to test this?

**Comment by ktbyers** [comment]
Here is the connection code, I used above (before switching the class):

```
#!/usr/bin/env python
from netmiko import ConnectHandler
from getpass import getpass

try:
    ip_addr = raw_input("Enter IP Address: ")
except NameError:
    ip_addr = input("Enter IP Address: ")

device = {
    'device_type': 'terminal_server',
    'ip': ip_addr,
    'username': 'pyclass',
    'password': getpass()
} 

net_connect = ConnectHandler(**device)
```

**Comment by ktbyers** [comment]
Use cases I see:

1. SSH through a terminal server where you need to send a key like '\r' to get the session started (and maybe even require a second login on the console port).
2. Manual terminal server interaction to connect to the console port; login; and then redispatch() Netmiko.

**Comment by briantsaunders** [comment]
@ktbyers I have some use cases for this and could help test if you need some assistance.

**Comment by ktbyers** [comment]
@briantsaunders Yes, would be great if you could help test.

**Comment by jeffdeham** [comment]
I am having problem with connecting to my console server. SSH seems to work fine but I can't get to the enable prompt. Wouldn't mind being a guinea pig and help out in some way.

**Comment by ktbyers** [comment]
@jeffdeham Can you show what your SSH session via your console server looks like when you do it manually?

**Comment by jeffdeham** [comment]
ssh sjc12-41a-sw1-con
password: 
                    <=== I have to hit return here to get to enable
sjc12-41a-sw1>en
Password: 
sjc12-41a-sw1#

**Comment by jeffdeham** [comment]
I turned on verbose and I got this before it hangs,

SSH connection established to sjc12-41a-sw1-con:22
Interactive SSH session established

**Comment by ktbyers** [comment]
@jeffdeham And what exception do you see in your Netmiko script?

**Comment by jeffdeham** [comment]
I don't see any exception.  It just stops and sits there

**Comment by ktbyers** [comment]
@jeffdeham And what does your Python code look like?

And what version of Netmiko are you using?

**Comment by jeffdeham** [comment]
I am using a NetMiko engine. How would I find out the version?

================================

from netmiko import ConnectHandler
import getpass

password_name = ''
router_ip = raw_input('Enter route ip: ')

name = raw_input('Enter user name: ')

password_name = getpass.getpass('Password:')

password_enable = raw_input('Enter enable password:')

net_connect = ConnectHandler(device_type='cisco_ios', ip= router_ip, username= name, password= password_name, secret= password_enable)

net_connect.enable()

output = net_connect.send_command('show ip int brief')
print(output)

net_connect.find_prompt()
~

**Comment by jeffdeham** [comment]
Engine Manager:
KickàExecutionàCreateàengine
Title: netmiko
Create / Edit Engine:
FROM pyats-2.1-py2                                                     #we are using Python 2.7.x
RUN /kick/pyATS2/bin/pip install netmiko
 
FROM pyats-2.1-py2                                                    
RUN /kick/pyATS2/bin/pip install netmiko

**Comment by ktbyers** [comment]
Usually just go into python:

```
import netmiko
netmiko.__version__
```

**Comment by jeffdeham** [comment]
NetMiko version 1.1.0

**Comment by ktbyers** [comment]
@jeffdeham And you are going via a terminal server here--correct (i.e. you are SSHing through a terminal server)?

**Comment by jeffdeham** [comment]
I am SSHing to a console server that is connected to a router.

The script works fine to non console servers for a data point.

**Comment by ktbyers** [comment]
Okay, you need to do the following:

1. Use the `develop` branch of Netmiko from GitHub:

This is how I would do it on Linux (not sure in your environment).

```
git clone https://github.com/ktbyers/netmiko
cd netmiko
python setup.py install
```

Change your Python program to:

```
from netmiko import ConnectHandler
import getpass
import time

password_name = ''

router_ip = raw_input('Enter route ip: ')
name = raw_input('Enter user name: ')
password_name = getpass.getpass('Password:')
password_enable = raw_input('Enter enable password:')

net_connect = ConnectHandler(
    device_type='terminal_server',        # Note change here
    ip= router_ip, 
    username= name, 
    password= password_name, 
    secret= password_enable)

net_connect.enable()

net_connect.write_channel("\r")
time.sleep(1)
net_connect.read_channel()

output = net_connect.send_command('show ip int brief')
print(output)

net_connect.find_prompt()

**Comment by ktbyers** [comment]
And let me know what you get for `output` at the end there.

**Comment by jeffdeham** [comment]
I ran that script and it failed with the following,

 File "/kick/pyATS2/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 94, in ConnectHandler
    'currently supported platforms are: {0}'.format(platforms_str))
ValueError: Unsupported device_type: currently supported platforms are:
a10
alcatel_sros
arista_eos
etc...

**Comment by jeffdeham** [comment]
Thanks by the way for taking the time to help me.

**Comment by ktbyers** [comment]
@jeffdeham That looks like you didn't upgrade your Netmiko (i.e. you are still using the old Netmiko not the `develop` Netmiko).?

**Comment by ktbyers** [comment]
@jeffdeham Okay, I made an update to the `develop` branch.

You will need to cd into your copy of this branch and then:

```
git pull origin develop
```

And then install the new version (which for me is):

```
python setup.py install
```

**Comment by ktbyers** [comment]
Here is the change I made:

https://github.com/ktbyers/netmiko/commit/ba57f9361b68ae607d98bcfeec0cff3986fc5aac

**Comment by jeffdeham** [comment]
"You will need to cd into your copy of this branch and then"  Sorry, is there a folder that this branch resides in? I am not a linux guy so kinda hazy where this branch resides,
---
I tried doing a "git pull origin develop" from my prompt with doing any changing of folders and got this,

Warning: Permanently added 'gitlab.cisco.com,173.36.21.126' (RSA) to the list of known hosts.
fatal: Couldn't find remote ref develop
(pyATS2)[root@f07a84291cdd workspace]# fatal: The remote end hung up unexpectedly

**Comment by ktbyers** [comment]
@jeffdeham Yes, there should be a 'netmiko' folder (this was created earlier when you did a `git clone`).

What does `ls` show you (from your home directory)?

**Comment by jeffdeham** [comment]
I ran it after doing the update and it doesn't hang but it failed with this error codes,

Traceback (most recent call last):
  File "netmiko_new_way.py", line 20, in <module>
    net_connect.enable()
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 829, in enable
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 821, in check_enable_mode
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 261, in read_until_prompt
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 218, in _read_channel_expect
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
@jeffdeham Okay, can you post your code ("netmiko_new_way.py").

**Comment by briantsaunders** [comment]
@ktbyers initial testing of the terminal_server works with an Opengear terminal server.  Was able to connect to the Opengear and authenticate.  From there entered my credentials to log into the NXOS device and then use redispatch to change device type to cisco_nxos and issue a few commands.

**Comment by jeffdeham** [comment]
Sorry for the delay working on this in a development system at work. No access on weekend.
Here is the code and errors,

Errors
-----------------------------------------------------
 File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 829, in enable
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 821, in check_enable_mode
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 261, in read_until_prompt
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 218, in _read_channel_expect
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

Code
---------------------------------------
from netmiko import ConnectHandler
import getpass

password_name = ''
router_ip = raw_input('Enter route ip: ')

name = raw_input('Enter user name: ')

password_name = getpass.getpass('Password:')

password_enable = raw_input('Enter enable password:')

net_connect = ConnectHandler(device_type='terminal_server', ip= router_ip, username= name, password= password_name, secret= password_enable)

net_connect.enable()

output = net_connect.send_command('show ip int brief')
print(output)

net_connect.find_prompt()
~

**Comment by jeffdeham** [comment]
I tried again the way that you suggested earlier and it worked! 

from netmiko import ConnectHandler
import getpass
import time

password_name = ''

router_ip = raw_input('Enter route ip: ')
name = raw_input('Enter user name: ')
password_name = getpass.getpass('Password:')
password_enable = raw_input('Enter enable password:')

net_connect = ConnectHandler(
    device_type='terminal_server',        # Note change here
    ip= router_ip, 
    username= name, 
    password= password_name, 
    secret= password_enable)

net_connect.write_channel("\r")
time.sleep(1)
net_connect.write_channel("\r")
time.sleep(1)
output = net_connect.read_channel()

print(output)

**Comment by jeffdeham** [comment]
Thank you very much for your help!

**Comment by jeffdeham** [comment]
Hello again, I am having problem with my configuration commands not working. It is just sits there and times out with,

Traceback (most recent call last):
  File "netmiko-jeff-creese-console.py", line 50, in <module>
    output = net_connect.send_config_set(config_commands)
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 920, in send_config_set
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 875, in exit_config_mode
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 265, in read_until_pattern
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 218, in _read_channel_expect
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

I tried this,

config_commands = ['vlan 200']
net_connect.config_mode()
output = net_connect.send_config_set(config_commands)
net_connect.exit_config_mode()
print '++++++++++++++++++++++++++++++++++'
print output

tried this
config_commands = ['vlan 200']
output = net_connect.send_config_set(config_commands)
print '++++++++++++++++++++++++++++++++++'
print output

Tried this
output = net_connect.send_command('vlan 200')

Nothing has worked. Thanks for any help!

**Comment by ktbyers** [comment]
@jeffdeham 

After you are fully logged into the end network device:

```
net_connect.write_channel("\r")
time.sleep(1)
net_connect.write_channel("\r")
time.sleep(1)
output = net_connect.read_channel()

print(output)
```

then, you need to use this `redispatch` method:

```
from netmiko import redispatch

# Dynamically reset the class back to CiscoIosSSH
redispatch(net_connect, device_type='cisco_ios')
```

Then try your other commands:

```
config_commands = ['vlan 200']
net_connect.config_mode()
output = net_connect.send_config_set(config_commands)
```

**Comment by jeffdeham** [comment]
That worked! Thanks again for your help!

**Comment by Swandip** [comment]
Hi KTbyers

I have similar issue I need to pull some show commands output from Cisco devices connected through only the console server. The cosole server uses my LDAP username and password to connect in 1st place and then it connects to  Cisco Device which again ask for second username and password.

I can pull the details from the devices in which I am able to   directly ssh with help of below script

rom __future__ import print_function
from netmiko import ConnectHandler
import sys
import time
import select
import paramiko
import re
fd = open(r'C:\NewdayTest.txt','w') # Where you want the file to save to.
old_stdout = sys.stdout   
sys.stdout = fd 
platform = 'cisco_ios'
username = 'username' # edit to reflect
password = 'password' # edit to reflect

ip_add_file = open(r'C:\IPAddressList.txt','r') # a simple list of IP addresses you want to connect to each one on a new line

for host in ip_add_file:
    host = host.strip()
    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
    output = device.send_command('terminal length 0')
    output = device.send_command('enable') #Editable to be what ever is needed
    print('##############################################################\n')
    print('...................CISCO COMMAND SHOW RUN OUTPUT......................\n')
    output = device.send_command('sh run')
    print(output)
    print('##############################################################\n')
    print('...................CISCO COMMAND SHOW IP INT BR OUTPUT......................\n')
    output = device.send_command('sh ip int br')
    print(output) 
    print('##############################################################\n')

fd.close()


Please help I am a new bee in automation.

**Comment by ktbyers** [comment]
@Swandip You could possibly try using a `terminal_server` device type and then writing all of the glue code to get fully logged in.

After you are fully logged in then you would do the redispatch from #470

**Comment by juanpb12** [comment]
Hi @ktbyers. I'm trying to use as you say, but i think python goes faster than ssh connection.
I need to send to the terminal the following commands:
login as: "cli"
Username: "my_username"
Password: "my_pass"
Agreement Terms (Y/N)? :  "y"
(no quotes, obviously)

and my code is:

console_username = 'cli'
console_server = {
    'host': my_ip_add,
    'username': console_username,
    'password': 'admin',
    'device_type': 'terminal_server',
}

net_connect = ConnectHandler(**console_server)
net_connect.enable()
net_connect.write_channel("admin"+ '\n')
time.sleep(3)
password_prompt = net_connect.read_channel()
net_connect.write_channel("admin" + '\n')
time.sleep(3)
net_connect.write_channel('y\n')
time.sleep(3)
redispatch(net_connect, device_type='nokia_sros')

but I receive Authentication Failed.
