### ISSUE TITLE
netmiko-show fails to consistently obtain output when ran in loop

### ISSUE THREAD

**Issue by dirkvdplas** [ktbyers/netmiko#386]
This error appears intermittent (10% of connection attempts) when running netmiko-show against a group of 4 routers. The errors are not seen when I use Ansible (with ios_command) to query the routers.

versions used:
Python 2.7.5 
netmiko (1.2.8)
paramiko (2.1.2)
RHEL 7.3

**Comment by ktbyers** [comment]
@dirkvdplas that is just a Paramiko warning. It shouldn't will have any consequence.

If you want it to go away...you can configure a logger.

Probably can just do this:

```
import logging
logger = logging.getLogger("netmiko")
```

**Comment by dirkvdplas** [comment]
Hello Kirk

Thanks for the quick reply.
I am sure it's not a warning, and has real consequences. When the messages
appears, I am missing output (so only ouput of 3 out of 4 devices is shown)

Dirk

**Comment by ktbyers** [comment]
@dirkvdplas Then you must have a different issue...that warning has no significance (in itself).

Can you post your script and what you are getting for output? Remove any sensitive information.

**Comment by dirkvdplas** [comment]
Here the script. It's nothing special, just endless loop performing netmiko-show command to a group of 4 asa's (note i have tested against other cisco hardware as well, c7600, nexus5k, with similar results)

```
[user-x@server:0 netmiko_tools]_OT $ more test-asa.py
#/usr/bin/python
import os
import time
while True:
  os.system('./netmiko-show --cmd "show version" asa >> log-netmiko-asa ')
  time.sleep(5)
[user-x@server:0 netmiko_tools]_OT $ ./test-asa.py
No handlers could be found for logger "paramiko.transport"

Here the output from netmiko

<output omitted, this is output from asa's that do respond>
--------------------
Failed devices:
  asa002

**Comment by ktbyers** [comment]
@dirkvdplas If you manually run this from the command line:

```
./netmiko-show --cmd "show version" asa
```


Does it consistently work?

**Comment by dirkvdplas** [comment]
@ktbyers  problem also occurs (intermittent in 30% of cases) when running
directly from commandline.  please note that I started running it in
endless loop in order to get more insight in the failure rate

Op 28 feb. 2017 6:17 p.m. schreef "Kirk Byers" <notifications@github.com>:

**Comment by dirkvdplas** [comment]
both. which means when the error appears  I see Failed device of which
output is missing

Op 28 feb. 2017 7:05 p.m. schreef "Kirk Byers" <notifications@github.com>:

**Comment by ktbyers** [comment]
@dirkvdplas Can you try experimenting with increasing the global_delay_factor for the device(s) in the .netmiko.yml file.

Should be like this:

```
asa1:
  device_type: cisco_asa
  ip: 10.10.10.10
  username: pyclass
  password: invalid
  secret: invalid
  global_delay_factor:  2     # try 2 and then 4 (if 2 doesn't work)
```

**Comment by dirkvdplas** [comment]
@ktbyers  global_delay_factor: 4 has improved it quite a bit. But I still
have issues now and then (quality of network if fine, low latency and no
errors), also manually login to devices goes fast.  Any further suggestions?

**Comment by ktbyers** [comment]
@dirkvdplas I think we need to get this out of Netmiko-tools and straight into Netmiko so we can get better error information, it should be something like this:


```
#!/usr/bin/env python
from netmiko import ConnectHandler
from getpass import getpass

ip_addr = raw_input("Enter IP Address: ")

device = {
    'device_type': 'cisco_asa',
    'ip': ip_addr,
    'username': 'admin',       # replace with your username
    'password': getpass()
    'global_delay_factor': 2,
} 

net_connect = ConnectHandler(**device)
output = net_connect.send_command_expect("show version")
print(output)
```

You will need to run this directly with Python.

**Comment by dirkvdplas** [comment]
when running code above, it goes fine. But when wrapping it in endless while loop it throws timeout error after a couple of runs

Traceback (most recent call last):
  File "./test-single.py", line 18, in <module>
    net_connect = ConnectHandler(**device)
  File "/opt/gbitools/automation/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 105, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/opt/gbitools/automation/lib/python2.7/site-packages/netmiko/base_connection.py", line 144, in __init__
    self.establish_connection()
  File "/opt/gbitools/automation/lib/python2.7/site-packages/netmiko/base_connection.py", line 472, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_asa <ip-adres>:22

**Comment by ktbyers** [comment]
@dirkvdplas That indicates that the device didn't respond on port 22 (i.e. accept the SSH connection) which makes me think that we possibly filled up all the available SSH sessions.

What happens if you add the following to the end of the above Python code:

```python
net_connect.disconnect()
```

**Comment by dirkvdplas** [comment]
You're right. All sessions were filling up. I added the net_connect.disconnect and now endless loop for single device (just netmiko, not netmiko tools) runs fine.  I have the feeling netmiko-tools multithreading is the cause of the error: "No handlers could be found for logger “paramiko.transport”, which I still have when using netmiko-show. 

Why have you changed the subject of this thread BTW? Would be better to put the "no handlers could be found... error in the subject

**Comment by ktbyers** [comment]
Yes, as I said earlier the "No handlers could be found for logger" is a Paramiko warning that is not relevant to your ASA connections failing. It has to do with Paramiko library logging configuration.

So back to the original issue, are you still having an issue with netmiko_tools?

I would try to modify your .netmiko.yml and add a `global_delay_factor: 2`  (or 4) argument to your ASA devices.

Let me know if that helps or not.

**Comment by dirkvdplas** [comment]
I am still having issues with netmiko-show. increasing global_delay_factor
does not help. below a brief overview of the symptoms:

-when error "no handlers could be found is thrown" the show results from at
least one or multiple devices is not returned
-issue occurs against all type of devices (c7600,nexus, asa)
-the number of devices in the group seems to increase the chances for error
-issue is reproducable on rhel7.3 and centos 6.8 server
-ansible ntc_show_command on same devices works fine





Op 16 mrt. 2017 06:25 schreef "Kirk Byers" <notifications@github.com>:

Yes, as I said earlier the "No handlers could be found for logger" is a
Paramiko warning that is not relevant to your ASA connections failing. It
has to do with Paramiko library logging configuration.

So back to the original issue, are you still having an issue with
netmiko_tools?

I would try to modify your .netmiko.yml and add a global_delay_factor: 2
(or 4) argument to your ASA devices.

Let me know if that helps or not.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ktbyers/netmiko/issues/386#issuecomment-286961355>, or mute
the thread

**Comment by ktbyers** [comment]
@dirkvdplas Are you using AAA for login? Do you see any messages in the network device logs when the login fails?

You stated earlier:

```
global_delay_factor: 4 has improved it quite a bit. 
```

So it improved things quite a bit, but you still see some errors (just a fewer number of errors). Is this correct?

**Comment by dirkvdplas** [comment]
@ktbyers  yep, we are using AAA for login. I ran "debug aaa authentication" meanwhile and saw that following message appear at same time when "No handlers could be found for logger" is seen:

Mar 20 19:30:06.619 CET: SSH2 1: Unexpected mesg type received

The problem is seen when targetting a device-group with multiple devices (4) with netmiko-show. 4  netmiko-show commands in parallel against a single device works fine without any error.

I therefore have the feeling that this multiprocess / threading is the cause of the problem. Do you have any tips for debugging this?

**Comment by ktbyers** [comment]
@dirkvdplas Are you using AAA for authorization or only authentication?

Yes, I doubt threading is the cause (at least as a primary cause).

Also, did `global_delay_factor` improve things?

**Comment by rwwelford** [comment]
I also am having this issue when running commands for multiple devices.  I tried several different global_delay_factors (1,2 and 3) without success.  

I finally "resolved" the issue by adding a time.sleep(1) after the " my_thread.start()" line in each of the netmiko_tools utilities but I would be very interested in a real solution.

**Comment by ktbyers** [comment]
@rwwelford Can you create an issue into netmiko tools and show what your solution ended up being?


Kirk

**Comment by superloopnetwork** [comment]
@rwwelford I tried your suggestion, putting the time.sleep(1) and it worked... But of course, slowing the processing down by a lot versus without the sleep... Which leads me to suspect the mutithread may be the issue? Is it processing it so fast that it's not able to keep up? Were you able to find a solution for this? 

@ktbyers Do you have any insights on this?

**Comment by ktbyers** [comment]
@superloopnetwork I suspect his AAA is getting progressively slower. A bunch of device logins at close to the same time. He then overcame this by just putting a 1 second delay between each device.

He probably needs to fix his AAA server performance issue.

**Comment by amangoel6** [comment]
Hi All,

I am facing a similar issue, when I run below code, I get IOError: Search pattern never detected in send_command_expect:

#!/usr/bin/env python
from netmiko import ConnectHandler
from getpass import getpass

ip_addr = raw_input("Enter IP Address: ")

device = {
    'device_type': 'cisco_asa',
    'ip': ip_addr,
    'username': 'admin',       # replace with your username
    'password': getpass()
    'global_delay_factor': 2,
} 

net_connect = ConnectHandler(**device)
print(net_connect.send_command_expect("show version"))

**Comment by amangoel6** [comment]
I ran find_prompt to find my prompt and then i figured out it was stuck at -------more--------
So when i set my terminal pager to 0 it started working.

Is there any other solution to this?
