### ISSUE TITLE
Enhancement: Add Some more switches

### ISSUE THREAD

**Issue by broncofan** [ktbyers/netmiko#389]
What is the process for getting some additional switches added?  I have a few switches I would like to add and the commands that would allow that. 
I would also like to see fibre (brocade) and ib (mellanox) switches added.  Any opposition to that?  some of the eexisting switch types work for these, but it would be nice to officially list them and have a type dedicated.
I can look at doing a pull request, but that would probably take we a while to implement. 

![image](https://cloud.githubusercontent.com/assets/1126787/23485082/8243c232-fe9f-11e6-8164-001a3c9b13bd.png)

EDIT: Sorry.  Just noticed the VENDOR.md file.  Will take a look at that and see if I can contribute.

**Comment by ktbyers** [comment]
@broncofan General process is here:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md

The devices should also pass probably both the `show` and `config` unit tests.

The testing process is here:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md


Definitely open to additional vendor support, but someone will have to do the work/submit the PR on them.
