### ISSUE TITLE
PALOALTO OS - search pattern never detected

### ISSUE THREAD

**Issue by adieball** [ktbyers/netmiko#392]
I have the following using netmiko

```
def main():

    timestamp = datetime.now().strftime("%Y-%m-%d_%H:%M:%S")
    print(timestamp)

    net_connect = ConnectHandler(device_type='paloalto_panos', ip='nodeip', username='admin', password='password')
    net_connect.find_prompt()
    net_connect.send_config_set('save config to config' + timestamp + '.xml')
#    output = net_connect.send_command('configure')
#    print(output)
#    output = net_connect.send_command('save config to config' + timestamp + '.xml')
#    print(output)
#    output = net_connect.send_command('exit')
#    print(output)
    output = net_connect.send_command('tftp export configuration from config' + timestamp + '.xml' + 'to 10.1.1.1')
    print(output)

main()
```
the script connects fine, but "hangs" during the net_connect.send_config_set command.

I also tried sending "configure" the the command and then "exit" with the same result. Then I remembered that in config mode it's expecting a different prompt so I used the "send_config_set" method. After a timeout, the script comes back with:

> traceback (most recent call last): File "", line 1, in net_connect.send_config_set('save config to config' + timestamp + '.xml') File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 921, in send_config_set output += self.exit_config_mode() File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/paloalto/paloalto_panos_ssh.py", line 48, in exit_config_mode output = self.send_command(exit_config, strip_prompt=False, strip_command=False) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/paloalto/paloalto_panos_ssh.py", line 154, in send_command return super(PaloAltoPanosSSH, self).send_command(*args, **kwargs) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 770, in send_command search_pattern)) OSError: Search pattern never detected in send_command_expect: admin\@PA-200#

Am I missing something?

**Comment by ktbyers** [comment]
What does this look like in the CLI when you do it manually?

```
'save config to config' + timestamp + '.xml'
```

**Comment by adieball** [comment]
Hi

I obviously can't use the string above (using the timestamp variable), but manually it shows:

--cut--
admin@PA-200> configure 
Entering configuration mode
[edit]                                                                          
admin@PA-200# save config to config20170304164300.xml

Config saved to config20170304164300.xml
[edit]                                                                          
admin@PA-200# exit
Exiting configuration mode
admin@PA-200> 
--cut--

**Comment by adieball** [comment]
Hi Kirk

any idea why the script seems to have problems with the configure mode?

**Comment by ktbyers** [comment]
@adieball How long does that `save config to config2017.xml` command take it? Is it very slow?

Also is that required to be a config command or can you do it from outside of `config` mode?

**Comment by adieball** [comment]
@ktbyers it takes a second or so.
Yes, this command requires the config mode

**Comment by ktbyers** [comment]
@adieball You might need to add delay_factor as an argument:

```
net_connect.send_config_set('save config to filename', delay_factor=2)
```

Keep increasing delay_factor until it works (try 2, then 4, then 8).
