### ISSUE TITLE
Failed to enter configuration mode

### ISSUE THREAD

**Issue by mdsalman049** [ktbyers/netmiko#396]
Hi All,

I am kinda new to programming and just started learning python. 
whenever I use config_mode() method I get the error attached. Also, when I try to go to enable mode I get time out error(also attached)

![image](https://cloud.githubusercontent.com/assets/26249237/23654803/6e9ea108-0358-11e7-80ef-385ed4147f04.png)

![image](https://cloud.githubusercontent.com/assets/26249237/23654892/cfc6eab2-0358-11e7-9d8f-cc13b5cfe8d4.png)

The netmiko version is 1.2.8 and paramiko version is 2.1.2 and python is 2.7.10

Please let me know how can I resolve this

**Comment by ktbyers** [comment]
@mdsalman049 What kind of device are you connecting to?

What is your device_type set to in your script?

What does it look like when you manually go into config mode (i.e. post the screen capture of manually going into config mode on this device).

**Comment by mdsalman049** [comment]
Thank you very much for the prompt response.

I have an ubuntu running on a VM and connected to cisco ios in gns3. The device type is 'cisco_ios' just the way its configured in http://networktocode.com/labs/tutorials/netmiko-quickstart/

output = device.send_command('show version') works perfectly ok.

Everything is fine when I directly configure the router.


![image](https://cloud.githubusercontent.com/assets/26249237/23685319/6cdd18c4-03c9-11e7-992a-c371aa468805.png)

**Comment by ktbyers** [comment]
@mdsalman049 

Can you turn on logging and see what it shows you? This should create a file test.log in your current directory:

Add this up near the top of your script.

```
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
```

**Comment by ktbyers** [comment]
Reopen if you are still having an issue (and tell me what you see with logging enabled).
