### ISSUE TITLE
Add ability to specify an alternate inventory file.

### ISSUE THREAD

**Issue by rwwelford** [ktbyers/netmiko#397]
Most of the ability to specify an alternate inventory file already exists.  Simply modifying **utilities.py** line 53 to accept a "file_name" as a parameter completes the functionality.

**old line 53:**  
`def load_devices():`

**new line 53:** 
`def load_devices(file_name=None):`

The code to forward the parameter _file_name_ to the _find_cfg_file_ function already exists in the body of the _load_devices_ function.

I've found that adding the parm to **utilities.py** line 53 does not affect backward compatibility (_i.e. running without specifying a file_) and also degrades gracefully if the file is not found - defaulting back to using the standard .netmiko.yml file.  The file can be specified via full path or relative addressing.

Adding this ability allows us to manage a large inventory among numerous team members working on existing and new (not yet deployed) equipment without mangling a large master inventory file.  We can also maintain inventory files by device type, location, etc.

**Comment by ktbyers** [comment]
@rwwelford Submit a PR on it. Also make sure you submit a PR on netmiko-tools to support this.

**Comment by rwwelford** [comment]
Addressed by pull request #398
