### ISSUE TITLE
Mellanox Driver

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#400]
How about this for check_config_mode.

Basically uses the `self.base_prompt` to determine a command is done. self.base_prompt doesn't have the trailing prompt character (i.e. the '>' and the '#')

```
    def check_config_mode(self, check_string='(config)', pattern=''):
        if not pattern:
            pattern = self.base_prompt
        return super(MellanoxSSH, self).check_config_mode(check_string=check_string,
                                                                  pattern=pattern)
```

**Comment by broncofan** [comment]
That seems to cause the same race condition.  Sometimes this passes and sometimes it doesn't.  The bad part is the (config) information comes after the base prompt.  So, it won't always catch the end bit of info, which is needed to verify config mode.
Passing data:
ictm-dw-mlnx [standalone: master] (config) #
Failing data:
ictm-dw-mlnx [standalone: master] (confi

**Comment by ktbyers** [comment]
Okay, how about this?

```
    def check_config_mode(self, check_string='(config)', pattern=r'[>#]'):
        return super(MellanoxSSH, self).check_config_mode(check_string=check_string,
                                                                  pattern=pattern)
```

i.e. the regex character set of [>#]

**Comment by broncofan** [comment]
That causes a timeout in the  _read_channel_expect.  Seems like it is not matching.
```
                except socket.timeout:
>                   raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
E                   netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

../netmiko/base_connection.py:221: NetMikoTimeoutException
----------------------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------------------
base_connection.py - 204 - Pattern is: \[\>\|\#\]
NEW_DATA:
ictm-dw-mlnx [standalone: master] #
END_NEW_DATA:
```

**Comment by ktbyers** [comment]
@broncofan Can you commit this change to your repository so I can look at the code you are using.

**Comment by broncofan** [comment]
@ktbyers latest changes committed.

**Comment by ktbyers** [comment]
@broncofan Strange. I think that should have worked. Let me look into it some more.

**Comment by ktbyers** [comment]
@broncofan Okay, I had a bug in some of my regex code that was causing the earlier pattern not to work. Can you try it again with this fix included (the fix is in the Netmiko `develop` branch).

https://github.com/ktbyers/netmiko/commit/ae10233e716b6593d90352f8bac64f4e7fc2554b

**Comment by ktbyers** [comment]
Mellanox driver was submitted on a previous PR.
