### ISSUE TITLE
failed to connect

### ISSUE THREAD

**Issue by tyson87** [ktbyers/netmiko#404]
Hello All, 

First time playing with netmiko, I cant seem to connect to my device when I attempt to. I am wondering if it is due to confirming the authenticity of the host when SSH'ing. Do I need to add something to type 'yes' within the script? I am following the http://networktocode.com/labs/tutorials/netmiko-quickstart/ guide. Thanks in advance for the help!! 

i.e is this causing my script to hang?

The authenticity of host '10.5.99.6 (10.5.99.6)' can't be established.
RSA key fingerprint is SHA256:axem93G31LAUQptbDvGuoeBbnGv7ouOJ4+Yms27CnQ4.
Are you sure you want to continue connecting (yes/no)? yes

vagrant@precise64:~$ python
Python 2.7.3 (default, Oct 26 2016, 21:01:49)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from netmiko import ConnectHandler
>>> import logging
>>> logging.basicConfig(filename='test.log', level=logging.DEBUG)
>>> logger = logging.getLogger("netmiko")
>>> from netmiko import ConnectHandler
>>> platform = 'cisco_ios'
>>> host = '10.5.99.6'
>>> username = 'user'
>>> password = 'password'
>>> device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
>>>     ### this is where it just hangs for a few seconds then goes the default '>>>" prompt.

**Comment by tyson87** [comment]
so, I checked the log and I see the output of show version in there. I guess was just expecting it to print to the screen.

**Comment by ktbyers** [comment]
Yes, when you do this. It will establish an SSH connection to the device.

```
device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
```

You can then do things like:

```
output = device.send_command("show version")
print(output)
```
