### ISSUE TITLE
Router prompt not found: {0}".format(prompt)

### ISSUE THREAD

**Issue by saadi381** [ktbyers/netmiko#406]
Hi ;

I am having issues detecting my Jumphost prompt with below exception

Router prompt not found: {0}".format(prompt)

the jumphost prompt looks like 
-mgmt:~>

any help

**Comment by ktbyers** [comment]
@saadi381 That is not enough information to help you...you will need to post a lot of your code. Also post the full exception you are getting.

**Comment by ktbyers** [comment]
Re-open if you are still having an issue.

**Comment by fariezs** [comment]
hi, perhaps u could help me.

how to handle declaration prompt as below : -

associated sub-systems are
PROPRIETARY INFORMATION and remain the sole and exclusive property of me and may be
---- More ( Press 'Q' to break ) ----


  Do you accept the declaration? YES to continue(YES/NO):Y



//script as below.
from netmiko import ConnectHandler
from datetime import datetime
import paramiko
import pexpect

start_time = datetime.now()
huawei = {
    'device_type': 'huawei',
    'ip': '192.168.1.1',
    'username': 'abc',
    'password': '123',
	'global_delay_factor': 2,
	'port': 22,
	'verbose': True,
}

p = p.expect('*break*')
p.expect('*break*')
p.sendline('Q')
p.expect('YES/NO')
p.sendline('YES')
p.expect('*HW*')

   
net_connect = ConnectHandler(**huawei)
output = net_connect.send_command('display board 0')
print output

end_time = datetime.now()
