### ISSUE TITLE
Not able to trap exception when router or asa doesn't respond.

### ISSUE THREAD

**Issue by durwoodmi** [ktbyers/netmiko#409]
Script stops when exception occurs due to a down

Python version: 3.6
Netmiko version: 1.2.8
Paramiko version: 2.1.2

Have tried trapping "netmiko.ssh_exception.NetMikoAuthenticationException,
                  netmiko.ssh_exception.NetMikoTimeoutException, netmiko.NetMikoTimeoutException,
                  netmiko.NetMikoAuthenticationException, netmiko.NetmikoTimeoutError, netmiko.NetmikoAuthError,
                  netmiko.ssh_exception.SSHException, netmiko.ssh_exception.AuthenticationException,
                  paramiko.OPEN_FAILED_CONNECT_FAILED, socket.timeout, paramiko.SSHException"

Have even tried the default "except Exception:", but still can't get the code to continue once the exception occurs.

Traceback (most recent call last):
  File "/Users/radded/Library/Python/3.6/lib/python/site-packages/netmiko/base_connection.py", line 468, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/Users/radded/Library/Python/3.6/lib/python/site-packages/paramiko/client.py", line 305, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/Users/radded/Library/Python/3.6/lib/python/site-packages/paramiko/util.py", line 269, in retry_on_signal
    return function()
  File "/Users/radded/Library/Python/3.6/lib/python/site-packages/paramiko/client.py", line 305, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/radded/PycharmProjects/GRE Audit/RAWDataGather.py", line 73, in <module>
    ssh = netmiko.ConnectHandler(ip=line, device_type='cisco_asa', username=username, password=password, secret=secret)
  File "/Users/radded/Library/Python/3.6/lib/python/site-packages/netmiko/ssh_dispatcher.py", line 105, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/radded/Library/Python/3.6/lib/python/site-packages/netmiko/base_connection.py", line 144, in __init__
    self.establish_connection()
  File "/Users/radded/Library/Python/3.6/lib/python/site-packages/netmiko/base_connection.py", line 472, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_asa 139.126.0.26:22

**Comment by ktbyers** [comment]
Can you post your relevant code (around line 73 of yoru RAWDataGather.py).

**Comment by durwoodmi** [comment]
Line 73 is in bold bellow.

with open('firewalls.txt', 'r') as firewalls:
    for line in firewalls:
        try:
            line = line.rstrip('\n')
            print(line)
            **ssh = netmiko.ConnectHandler(ip=line, device_type='cisco_asa', username=username, password=password, secret=secret)**
            ssh.enable()

**Comment by ktbyers** [comment]
Need more of your code (add like 50 lines surrounding this). Also are you using threads or processes at all?

**Comment by durwoodmi** [comment]
import netmiko
import paramiko
import socket

ssh_exceptions = (netmiko.ssh_exception.NetMikoAuthenticationException,
                  netmiko.ssh_exception.NetMikoTimeoutException, netmiko.NetMikoTimeoutException,
                  netmiko.NetMikoAuthenticationException, netmiko.NetmikoTimeoutError, netmiko.NetmikoAuthError,
                  netmiko.ssh_exception.SSHException, netmiko.ssh_exception.AuthenticationException,
                  paramiko.OPEN_FAILED_CONNECT_FAILED, socket.timeout, paramiko.SSHException)

with open('routers.txt', 'r') as accessrouters:
    for line in accessrouters:
        try:
            line = line.rstrip('\n')
            print(line)
            ssh = netmiko.ConnectHandler(ip=line, device_type='cisco_ios', username=username, password=password, secret=secret)
            ssh.enable()
            ssh.send_command("term len 0")
            data = ssh.send_command("sho run", delay_factor=2)
            out_file = open('%s.config' % line, 'w')
            out_file.writelines(data)
            out_file.flush()
            out_file.close()
            data = ssh.send_command("sho ip access-list", delay_factor=2)
            out_file = open('%s_ACLs.config' % line, 'w')
            out_file.writelines(data)
            out_file.flush()
            out_file.close()
            data = ssh.send_command("sho ip prefix-list", delay_factor=2)
            out_file = open('%s_prefix-lists.config' % line, 'w')
            out_file.writelines(data)
            out_file.flush()
            out_file.close()
            data = ssh.send_command("sho ip int brie", delay_factor=2)
            out_file = open('%s_tun_state.config' % line, 'w')
            out_file.writelines(data)
            out_file.flush()
            out_file.close()
            ssh.disconnect
        except ssh_exceptions as error:
            out_file = open('%s.config' % line, 'w')
            out_file.writelines(error)
            out_file.flush()
            out_file.close()
            out_file = open('%s_ACLs.config' % line, 'w')
            out_file.writelines(error)
            out_file.flush()
            out_file.close()
            out_file = open('%s_prefix-lists.config' % line, 'w')
            out_file.writelines(error)
            out_file.flush()
            out_file.close()
            out_file = open('%s_tun_state.config' % line, 'w')
            out_file.writelines(error)
            out_file.flush()
            out_file.close()
            continue
accessrouters.closed
with open('firewalls.txt', 'r') as firewalls:
    for line in firewalls:
        try:
            line = line.rstrip('\n')
            print(line)
            ssh = netmiko.ConnectHandler(ip=line, device_type='cisco_asa', username=username, password=password, secret=secret)
            ssh.enable()
            ssh.send_command("term pager 0")
            data = ssh.send_command("sho run", delay_factor=2)
            out_file = open('%s.config' % line, 'w')
            out_file.writelines(data)
            out_file.flush()
            out_file.close()
            ssh.disconnect
        except ssh_exceptions as error:
            print('Error to ', line, ' ', error)
            out_file = open('%s.config' % line, 'w')
            out_file.writelines(error)
            out_file.flush()
            out_file.close()
            continue
firewalls.closed

**Comment by ktbyers** [comment]
@durwoodmi You need to simplify your try/exception block. Try to just wrap this part of your code in the exception handler and see if you still have the same issue:

with open('routers.txt') as accessrouters:
    routers = accessrouters.readlines()

for ip_addr in routers:
    ip_addr = ip_addr.strip()
    try:
        ssh = netmiko.ConnectHandler(ip=line, device_type='cisco_ios', 
                                        username=username, password=password, secret=secret)
        print(ssh.find_prompt())
    except Exception:
        print("There was an error")


See if that works or not (you might need to make slight modifications to this, but that should be pretty close).
