### ISSUE TITLE
Adding 'arista_eos' to snmp_autodetect

### ISSUE THREAD

**Issue by liorfranko** [ktbyers/netmiko#412]
Can you please add Arista:
    'arista_eos': {"oid": ".1.3.6.1.2.1.1.1.0",
                  "expr": re.compile(r".*Arista Networks EOS.*", re.IGNORECASE),
                  "priority": 60},

I'm checked it and it works, I'm not sure about the priority value.

**Comment by ktbyers** [comment]
Okay, done. It is in `develop` branch. Made priority be 99.

**Comment by liorfranko** [comment]
10x

2017-03-14 20:00 GMT+02:00 Kirk Byers <notifications@github.com>:
