### ISSUE TITLE
NetMikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by kaage** [ktbyers/netmiko#415]
I'm having troubles to use NAPALM to get some information out of devices. It raises netmiko error. At the same time manual SSH to the device works well. See Below:

jaakko@ubuntu:~/Desktop/Ansible-shared/ansible-playbooks$ cat napalm-test.py 
```
from netmiko import ConnectHandler
from napalm import get_network_driver
get_network_driver('ios')
driver = get_network_driver('ios')
device = driver('192.168.61.121', 'cisco', 'cisco')
device.open()
device.get_mac_address_table()
```

```
jaakko@ubuntu:~/Desktop/Ansible-shared/ansible-playbooks$ python napalm-test.py 
Traceback (most recent call last):
  File "napalm-test.py", line 6, in <module>
    device.open()
  File "/usr/local/lib/python2.7/dist-packages/napalm_ios/ios.py", line 118, in open
    self.device.enable()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 15, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 834, in enable
    output += self.read_until_prompt()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 262, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 219, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```

jaakko@ubuntu:~/Desktop/Ansible-shared/ansible-playbooks$ python --version
Python 2.7.12
jaakko@ubuntu:~/Desktop/Ansible-shared/ansible-playbooks$ pip freeze | grep netmiko
netmiko==1.2.8
jaakko@ubuntu:~/Desktop/Ansible-shared/ansible-playbooks$ pip freeze | grep paramiko
paramiko==2.1.2
jaakko@ubuntu:~/Desktop/Ansible-shared/ansible-playbooks$ pip freeze | grep napalm
napalm==1.2.0
napalm-base==0.23.0
napalm-eos==0.5.5
napalm-fortios==0.3.1
napalm-ios==0.6.1
napalm-iosxr==0.4.8
napalm-junos==0.6.4
napalm-nxos==0.5.1
napalm-panos==0.4.0
napalm-pluribus==0.5.1
napalm-ros==0.2.1
napalm-vyos==0.1.3

**Comment by ktbyers** [comment]
@kaage It looks like you are not passing in an enable secret:

```
    optional_args = {}
    optional_args['secret'] = 'your_secret'

    driver = get_network_driver('ios')
    device = driver(ip_addr, username, password, optional_args=optional_args)
```

Just re-open if this doesn't fix the issue.
