### ISSUE TITLE
IOError(u'Search pattern never detected in send_command_expect: TEST\\(config\\)\\#',))

### ISSUE THREAD

**Issue by WhatGO** [ktbyers/netmiko#421]
Hello,

I have this error and I think it's because of the prompt with "applet" string,

Is there any way to add an expected string as an option (because I'm also getting this problem with reload when getting the output : "System configuration has been modified. Save? [yes/no]:")

IOError(u'Search pattern never detected in send_command_expect: TEST\\(config\\)\\#',))

Here is output directly on the device 
TEST(config)#
TEST(config)#event manager applet TEST authorization bypass
TEST(config-applet)#

Thanks

**Comment by ktbyers** [comment]
@WhatGO You shouldn't use `send_command` for configuration changes.

Use either `send_config_set` or `send_config_from_file` methods.

For your reload question:

`System configuration has been modified. Save? [yes/no]:`

Use `send_config_timing` method

```
output = net_connect.send_config_timing('reload')
if 'System configuration has been modified' in output:
    output = net_connect.send_config_timing('no')             # Or whatever you want to do in this case
```

**Comment by WhatGO** [comment]
Many thanks , you probably mean "send_command_timing"
```
                   reload_count = '10'
                   print('Reloading in : ' + reload_count)
                   output = ssh_connect.send_command_timing('do reload in ' + reload_count)
                   print(output)
                   if 'System configuration has been modified' in output:
                       output = ssh_connect.send_command_timing('no')
                   elif 'Proceed with reload? [confirm]' in output:
                       output = ssh_connect.send_command_timing('')
```

**Comment by ktbyers** [comment]
@WhatGO Yes, my bad `send_command_timing`

**Comment by h0th3d3d** [comment]
Whats the reload_count for?
