### ISSUE TITLE
Issue with password prompt on Aruba OS

### ISSUE THREAD

**Issue by sjtarik** [ktbyers/netmiko#426]
Using netmiko, I am trying to update existing user passwords and receiving invalid input error.

Flow:
command: mgmt-user dummyuser read-only
Password:************
Re-Type password:************
 
First send_command_expect is successful but second call fails since device gives invalid input error. 
Password passed as u'cleartextpwd\n' to the device.

```
net_connect = ConnectHandler(**dev_profile)
net_connect.config_mode()
if net_connect.check_config_mode():
    print("Successfully in connect mode")
    net_connect.send_command_expect('mgmt-user dummyuser read-only', expect_string='.*Password:.*')
    net_connect.send_command_expect(new_pwd, expect_string='.*password:.*')
    net_connect.send_command(new_pwd)
    net_connect.exit_config_mode()
    print("Successfully committed")
    net_connect.send_command('write mem')
    net_connect.disconnect()
```

**Comment by ktbyers** [comment]
@sjtarik What error do you get?

Where is the `new_pwd` variable set?

**Comment by sjtarik** [comment]
html markdown removed the value. Let say for value cleartext, we write channel u'cleartext\n' and the Aruba gives error generic Invalid input.

**Comment by ktbyers** [comment]
@sjtarik Please post your Python stack trace.

**Comment by ktbyers** [comment]
I think this is fixed here (basically the issue is that Aruba requires a different <enter> character in this context i.e. a '\r'

https://github.com/ktbyers/netmiko/pull/903
