### ISSUE TITLE
send_command search efficiency

### ISSUE THREAD

**Issue by johnarnold** [ktbyers/netmiko#427]
I'm looking at the send_command function.   

Imagine I log into an internet/backbone router and issue 'show ip route', and it returns a few million lines.  I see some issues with the way send_command searches the output.

    lines = output.split("\n")
    first_line = lines[0]
    .... code block around parsing first line

If you hit the loop / delay factor at all reading the channel, this first line parsing logic gets applied over and over to the same first line of the output.  Shouldn't this only happen once / on the first channel read?   Given known term lengths, would it be more efficient to use string.partition() rather than splitting (searching) the whole output?  Or otherwise, just search the first n bytes?
    
    if re.search(search_pattern, output):
        break

This searches the whole output (which could be terrifically long, like 'show ip route') to find the prompt / search pattern.  Would it make more sense to just search the end of the output (last n bytes)?

For reference, ExScript searches for prompt by using io.StringIO  for the output buffer, instead of just string, and then partitioning it with helper functions.  See:
https://github.com/knipknap/exscript/blob/master/Exscript/protocols/ssh2.py

   def _domatch(self, prompt, flush):

and 
https://github.com/knipknap/exscript/blob/bf05568ab9a75571502fe7d3537972605d331bd6/Exscript/util/buffer.py

**Comment by ktbyers** [comment]
@johnarnold Yes, it will certainly choke on very large output.

Let me review your points here.

**Comment by johnarnold** [comment]
@ktbyers ping :)

**Comment by ktbyers** [comment]
Yeah, haven't got to it :-)

A workaround for large output is to just write your own custom function. You can use the underlying `read_channel` and `write_channel` methods to directly control the channel.

...that doesn't answer the question of whether send_command should be modified, however.

**Comment by ktbyers** [comment]
@johnarnold Your fix sounds reasonable. Do you want to submit a PR on it?


Kirk

**Comment by ktbyers** [comment]
@johnarnold Okay, I worked on this in PR #910. Feel free to test and comment there.
