### ISSUE TITLE
Extreme Networks issue connecting (prompt)

### ISSUE THREAD

**Issue by apepelis** [ktbyers/netmiko#428]
extreme puts a command number at the end of the base prompt line.

class ExtremeSSH(CiscoSSHConnection):
    """Extreme support."""
    def session_preparation(self):
        """Extreme requires enable mode to disable paging."""
        self._test_channel_read()
        self.enable()
        self.set_base_prompt() << sets the base prompt to something ending in ".1"
        self.disable_paging(command="disable clipaging\n") << waits for a line ending in ".1" from above, but the next line ends in a ".2"

ExtremeSSH needs that removed.

    def set_base_prompt(self, pri_prompt_terminator='#',
                        alt_prompt_terminator='>', delay_factor=1):
        super(ExtremeSSH, self).set_base_prompt(pri_prompt_terminator,alt_prompt_terminator, delay_factor)        
        self.base_prompt = self.base_prompt.strip().rstrip(string.digits)
        return self.base_prompt

**Comment by apepelis** [comment]
ok, I jumped back to 0.3.0 and it looks like it was doing this:

class ExtremeSSH(SSHConnection):
    '''
    Extreme support
    '''
    def session_preparation(self):
        '''
        Extreme requires enable mode to disable paging
        '''
        self.enable()
        self.disable_paging(command="disable clipaging\n")
        self.set_base_prompt()

so it never did the wait for prompt. since the base prompt is wrong, that is the deal.

**Comment by ktbyers** [comment]
We are working on this here:

https://github.com/ktbyers/netmiko/pull/425

You might want to jump onto the comments on that pull request (as we have questions about how Extreme operates across platforms).
