### ISSUE TITLE
Multiple logins Failing

### ISSUE THREAD

**Issue by jacrotts** [ktbyers/netmiko#429]
I'm having an issue with certain Cisco IOS-XE / Nexus devices that require multiple logins.

This is my desired process:
log into console server (using terminal_server device type) -- > enable secret is requested for regular access --> connection.enable() is sent for privileged access --> send.commands()

 I've tried sending the secret as a send.command after recasting the connection, but the device hangs waiting for output.

I have netmiko working with devices that do not request the additional enable secret for regular access.

Thanks for any assistance

Great library by the way!

**Comment by ktbyers** [comment]
@jacrotts Can you post your code and the stack trace that you get.

**Comment by jacrotts** [comment]
Here is the traceback.

Traceback (most recent call last):
  File "C:/Users/jacrotts/PycharmProjects/cert_library/main.py", line 7, in <module>
    connection.connect()
  File "C:\Users\jacrotts\PycharmProjects\cert_library\SshConnection.py", line 59, in connect
    redispatch(ssh_connection, device_type='cisco_ios')
  File "C:\Python36\lib\site-packages\netmiko-1.2.8-py3.6.egg\netmiko\ssh_dispatcher.py", line 136, in redispatch
  File "C:\Python36\lib\site-packages\netmiko-1.2.8-py3.6.egg\netmiko\cisco\cisco_ios.py", line 10, in session_preparation
  File "C:\Python36\lib\site-packages\netmiko-1.2.8-py3.6.egg\netmiko\base_connection.py", line 633, in set_base_prompt
  File "C:\Python36\lib\site-packages\netmiko-1.2.8-py3.6.egg\netmiko\base_connection.py", line 679, in find_prompt
ValueError: Unable to find prompt: 


[netmiko_issue.txt](https://github.com/ktbyers/netmiko/files/903276/netmiko_issue.txt)

**Comment by ktbyers** [comment]
Try it with latest version of Netmiko (1.3.0).

Also you probably need to try it with Python3.5 and not Python 3.6. Python 3.6 is very new and I have been receiving reports of issues with it on Windows.

**Comment by ktbyers** [comment]
You also, should enable logging to give us more details on what is happening:

```
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
```

**Comment by jacrotts** [comment]
Would I handle the password with write_channel('password')  before re-dispatching the connection?

I will upgrade then import the logger.

**Comment by ktbyers** [comment]
Yes, you would need to use write_channel() and read_channel() to handle the session login. I don't know how your terminal server environment is setup (i.e. some have no password to the end network device, some have username/passwords, etc).

You can probably re-use parts of what I have for this telnet login code:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco_base_connection.py#L64-125


Note, write_channel requires a return at the end...so it would be write_channel('password\n')

**Comment by jacrotts** [comment]
After adding the '\n' to write_channel and increasing the delay after the first login the issue was fixed.

Thanks for the help, I appreciate it.
