### ISSUE TITLE
Error installing netmiko under Python 3.4

### ISSUE THREAD

**Issue by ravenblue12** [ktbyers/netmiko#43]
# python3.4 setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import netmiko
  File "/home/c102/c1021058/devel/netmiko/netmiko/__init__.py", line 1, in <module>
    from ssh_dispatcher import ssh_dispatcher
ImportError: No module named 'ssh_dispatcher'

**Comment by ravenblue12** [comment]
PEP420 (https://www.python.org/dev/peps/pep-0420/)?

**Comment by ktbyers** [comment]
Python3 is currently not supported only Python2.6 and Python2.7.

**Comment by ravenblue12** [comment]
Thanks!

Am Samstag, 7. März 2015 schrieb Kirk Byers :
