### ISSUE TITLE
Line break modifications needed for some Brocade gear

### ISSUE THREAD

**Issue by davesill** [ktbyers/netmiko#437]
I needed to replace multiple instances of \n with \r\n in base_connection.py to make some Brocade models work properly.  Doing so didn't seem to cause any issues with devices which worked with the stock version.  As discussed on Slack, I think an 'enter' variable specifying the format of line breaks which can be overridden per platform would be great.

**Comment by ktbyers** [comment]
This has been implemented in Netmiko 1.5.0 (not released yet) see branch `netmiko_dev_1_5`. Implemented:

```
         self.RETURN = '\n'
         self.TELNET_RETURN = '\r\n'
         # Line Separator in response lines
         self.RESPONSE_RETURN = '\n'
```

Which all get set in `__init__.py` method and can be set in the child class. I implemented this in the Brocade child class.

**Comment by davesill** [comment]
Brilliant.  I’m using my hacked up version in production and this is way easier to deal with when updating.

Thanks,
Dave

**Comment by ktbyers** [comment]
Here for example is the new Brocade module with telnet:

https://github.com/ktbyers/netmiko/blob/netmiko_dev_1_5/netmiko/brocade/brocade_netiron.py

I think this should work (it will use the telnet_login method that it inherits from a parent class).

Let me know if you test the new version and whether you see any issues.

**Comment by davesill** [comment]
Got it.  I ended up building out Brocade Fastiron and Netiron telnet as well, although there’s not much code there.  I could get you a PR on those if you’re interested, but I assume you want to lean everything toward SSH.

Thanks,
Dave

**Comment by davesill** [comment]
Looks like you’ve got that in there already.  Sorry.

Thanks,
Dave

**Comment by ktbyers** [comment]
I think this issue is fixed. Let me know if it is not.
