### ISSUE TITLE
Implement save_config() method for all devices.

### ISSUE THREAD

**Issue by jumpojoy** [ktbyers/netmiko#441]
However there is commit() which already implemented but supports only limited hardware. It should be good to have common method for example save_config() which allow to save configuration for devices that doesn't support commit()

**Comment by ktbyers** [comment]
And this method just saves running-config to start-config for platforms that use this model?

**Comment by jumpojoy** [comment]
Exactly, or is a generic method that calls commit() if it is supported and if not do "copy running-config startup-config"

**Comment by ktbyers** [comment]
@jumpojoy It is a lot of work to properly implement this on 25 or so drivers including unit tests. Are you signing up for doing that?

**Comment by jacrotts** [comment]
I could help with this if needed, at least on cisco platforms.

**Comment by jumpojoy** [comment]
@ktbyers I have only Cisco switches, but can try it with virtualized appliances for Juniper/Arista.

**Comment by ktbyers** [comment]
I still think we need someone to sign-up for implementing on the other 20-25 platforms (i.e. working out the commands for performing a save_config for that platform). Or at least > half of them.

Even if we don't have a device to test on.

If we can get closer to 50-75% coverage on the platforms, then I would be more interested in doing this.

**Comment by jacrotts** [comment]
I would be open to implementing it on the other platforms as well, but I just wouldn't have gear to test it on.

**Comment by ktbyers** [comment]
Yes, if you want to take a go at implementing it that would be great. It is okay to not have the gear to test it on.

You just need to determine for each platform what the commands are to do this.

**Comment by jacrotts** [comment]
I will start compiling a list of the commands for each platform.

**Comment by jacrotts** [comment]
Here is my first pass at the supported/and somewhat tested platforms. 
I can go into more detail as needed!

[netmiko_save_config_commands.txt](https://github.com/ktbyers/netmiko/files/1037370/netmiko_save_config_commands.txt)

**Comment by gmcms** [comment]
You can add (no enable nor config mode):

Alcatel AOS
write memory flash-synchro

Thanks

**Comment by jacrotts** [comment]
added 
[netmiko_save_config_commands.txt](https://github.com/ktbyers/netmiko/files/1056381/netmiko_save_config_commands.txt)

**Comment by jcrotts** [comment]
I am going to start working on this. I plan to do Cisco devices first, then I'll move on to the others.
