### ISSUE TITLE
Resolve differences between powerconnect SSH and telnet.

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#444]

**Comment by rverchere** [comment]
Do you need some help about this issue, as I have poweconnect 5524 device?

**Comment by ktbyers** [comment]
IIRC, some of the behavior was different in the powerconnect telnet code versus powerconnect SSH code...I suspect this was due to different platforms of PowerConnect, but someone should probably look into this.

If you want to look into it, that would be great.

**Comment by rverchere** [comment]
See #800.
