### ISSUE TITLE
Authentication failure: unable to connect cisco_ios [ip] ('Bad authentication type', ['']) (allowed_types=[''])

### ISSUE THREAD

**Issue by NedySuprianto** [ktbyers/netmiko#448]
hi, i used netmiko python to connect to cisco switch SF300 to runs some command and get the output from the device, but i got a problem when i try to connect with ssh netmiko.
i already use putty to connect to the device, but there's have 3 variables that's should i input : 
login as : 
Username : 
Password : 
and but with netmiko i just have 'username' and 'password' variables, i actually confused what variabel should i add,

**this is my code : ** 
def get_cisco(device_type, ip, username, password, enable_secret, command):
    Cisco = {
        'device_type': 'device_type',
        'ip': 'ip',
        'username': 'username',
        'password': 'password',
        'secret': 'enable_secret',  
    }
    SSHClass = netmiko.ssh_dispatcher(device_type=Cisco['device_type'])
    net_connect = SSHClass(**Cisco)

**this is the error :** 

Traceback (most recent call last):
  File "C:/Users/Nedy Suprianto/PycharmProjects/project/Network.py", line 39, in <module>
    send = get_cisco(Device_type, Ip, Username, Password, Enable_secret, Command)
  File "C:/Users/Nedy Suprianto/PycharmProjects/project/Network.py", line 16, in get_cisco
    net_connect = SSHClass(**Cisco)
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\netmiko\base_connection.py", line 151, in __init__
    self.establish_connection()
  File "C:\Users\Nedy Suprianto\python\lib\site-packages\netmiko\base_connection.py", line 510, in establish_connection
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Authentication failure: unable to connect cisco_ios [IP]
('Bad authentication type', ['']) (allowed_types=[''])

Thanks :)

**Comment by ktbyers** [comment]
@NedySuprianto I think you probably need to configure this on your switch.

```
ip ssh password-auth
```

Here is example code for connecting to sg300 (which should also work for sf300).

```
#!/usr/bin/env python
from netmiko import ConnectHandler
from getpass import getpass

# Change IP to your IP and username also
device = {
    'device_type': 'cisco_s300',
    'ip': '10.10.10.10',
    'username': 'admin',
    'password': getpass(),
} 

net_connect = ConnectHandler(**device)
output = net_connect.send_command_expect("show run")

print output
```

**Comment by ktbyers** [comment]
I am going to close this issue. Re-open if you are still having problems.

**Comment by NedySuprianto** [comment]
ok, ill try it.

thanks for your help kirk

**Comment by aimman** [comment]
Hi,

Can I use netmiko for my cisco SG500 switch? I tested netmiko on my SG300 and it work, but sad to say it didn't work on SG500. I check the list of cisco devices, only SG300 are listed. I have lots of SG500 on our network w/c I am trying to configure/monitor.

Thank you.

**Comment by ktbyers** [comment]
@aimman Did you try using the `device_type = cisco_s300`?

**Comment by aimman** [comment]
yes, I did try cisco_s300, it won't work, i'm new to python and i'm still trying to read the codes used
at cisco_s300. as of now no luck.

**Comment by ktbyers** [comment]
@aimman Can you post the exception that you get using the `cisco_s300` device_type. Also can you post a manual CLI session with the SG500 (i.e. what it looks like to login).

Also, I assume you have the following configured on the SG500:

```
ip ssh password-auth
```

The above is required as otherwise the SG device prompts for the username twice which breaks the Netmiko SSH session (at least this is the behavior on the SG300).
