### ISSUE TITLE
send_config_set usage

### ISSUE THREAD

**Issue by h0th3d3d** [ktbyers/netmiko#451]
hi may i ask for your assistance on how to use the send_config_set command. check the help but having problem output is being considered  per character

config_commands = ('boot system flash')                                      
output = tftp_connection.send_config_set(config_commands)
print (output)

----------------

config term
Enter configuration commands, one per line.  End with CNTL/Z.
R1(config)#b
% Ambiguous command:  "b"
R1(config)#o
% Incomplete command.

R1(config)#o
% Incomplete command.

R1(config)#t
% Ambiguous command:  "t"
R1(config)# 
R1(config)#s
% Ambiguous command:  "s"
R1(config)#y
           ^
% Invalid input detected at '^' marker.

R1(config)#s
% Ambiguous command:  "s"
R1(config)#t
% Ambiguous command:  "t"
R1(config)#e
% Ambiguous command:  "e"
R1(config)#m
% Ambiguous command:  "m"
R1(config)# 
R1(config)#f
% Incomplete command.

R1(config)#l
% Incomplete command.

R1(config)#a
% Ambiguous command:  "a"
R1(config)#s
% Ambiguous command:  "s"
R1(config)#h
% Ambiguous command:  "h"
R1(config)#end

should i increase the delay

**Comment by ktbyers** [comment]
@h0th3d3d 

send_config_set requires a list of commands or a tuple of commands. What you had previously is not a tuple but just a string enclosed in parenthesis (you would need to add a comma to make it a tuple

```
config_commands = ('boot system flash',)     # add comma
output = tftp_connection.send_config_set(config_commands)
print (output)
```
