### ISSUE TITLE
Unexpected error: <class 'sre_constants.error'>

### ISSUE THREAD

**Issue by hoyeunglee** [ktbyers/netmiko#453]
using python 2.7 and pip install paramiko and pip install netmiko

using python command to run , there is no error

but after compile to executable file with "python setupcloudchangepassword.py py2exe"

There is error after run changepassword.exe
Unexpected error: <class 'sre_constants.error'>

```
 try:
        print("ssh connecting to " + ssubstring(ip).replace("hello.com",""))
        net_connect = ConnectHandler(device_type='ovs_linux', ip=ssubstring(ip).replace("hello.com",""), port="7000", username=username1, password=password1) 
        print("ssh succeed to connect to " + ssubstring(ip).replace("hello.com",""))
    except:
        print "Unexpected error:", sys.exc_info()[0]
        return 1
```

**Comment by ktbyers** [comment]
@hoyeunglee Don't know. 

Doesn't sound like a Netmiko error though. Sounds like a creating an executable issue.
