### ISSUE TITLE
Not able to login to Extreme switch

### ISSUE THREAD

**Issue by Bharath910** [ktbyers/netmiko#456]
Hi All,

I am not able to login to Extreme switch, below is the code. 

>>> from netmiko import ConnectHandler
>>> extnet = {
	'device_type': 'extreme',
	'ip': '192.168.211.8',
	'username': 'bharath',
	'password': '******',
	}
>>> net_connect = ConnectHandler(**extnet )
>>> output = net_connect.send_command("show vlan")

 I am getting below error, can any one explain why i am getting this error.
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    output = net_connect.send_command("show vlan")
  File "C:\Python27\lib\site-packages\netmiko\extreme\extreme_ssh.py", line 48, in send_command
    kwargs.setdefault({'auto_find_prompt': False})
TypeError: unhashable type: 'dict'

**Comment by ktbyers** [comment]
See the fix above that I just implemented in the `develop` branch.

Please test it if you can.

**Comment by sanuma02** [comment]
Hello @ktbyers I tested the fix you shared, however I got no luck 

kwargs.setdefault({'auto_find_prompt', False})
TypeError: unhashable type: 'set'

send_config_set for Extreme devices works fine is the send one that is giving me issues.

**Comment by ktbyers** [comment]
@sanuma02 What version of Netmiko are you using?
