### ISSUE TITLE
Checkpoint GAIA expert mode access

### ISSUE THREAD

**Issue by rgk013** [ktbyers/netmiko#457]
How we can go into checkpoint gaia expert mode from cli.sh mode 

Checkpoint if we change shell to bash mode for user it can be connected to expert mode .
if we are in cli.sh mode then need to enter "expert" command and password to get into expert mode 
how we can automate using   ConnectHandler  .like cisco we have "secret" in dictionary  for enable mode .

**Comment by ktbyers** [comment]
@rgk013 Can you show me what the session looks like from the CheckPoint CLI when you do it manually?

**Comment by rgk013** [comment]
when login via cli prompt is as below..
GW>

on expert mode prompt is as below 
[Expert@GW]

**Comment by ktbyers** [comment]
@rgk013 You are going to have to show me in the CLI what you are looking to do in Netmiko.

Note, I have never used Checkpoint Gaia and it has been ~10+ years since I have used Checkpoint at all.

**Comment by tribs26** [comment]
@ktbyers Please check below:
MGMT>                          <-----------clish mode
MGMT> expert
Enter expert password:                <------- We enter expert password here


Warning! All configurations should be done through clish
You are in expert mode now.
 
[Expert@MGMT:0]# 
[Expert@MGMT:0]#  <------------------------ Expert mode

Problem here is how we login into expert mode by using let's say Paramiko
Or, how can we use pexpect library to achieve this.

Please help.
