### ISSUE TITLE
Issue with HP Comware with banners that require Enter to accept

### ISSUE THREAD

**Issue by bobwinners** [ktbyers/netmiko#459]
Hello,

I noticed an issue with version 1.3 and 1.4 of Netmiko that was not a problem with version 1.2.8 of the package.

My HP comware switches have a disclaimer that requires the user to press the enter or y key to accept.  When setting up a ConnectHandler object, the process hangs.  This does not happen on my HP switches that do not have a disclaimer.   I have traced the hanging to the session_preparation() function in the hp_comware_ssh.py file.  Between versions 1.2.8 and 1.3 the function was changed from:

def session_preparation(self):
        """
        Prepare the session after the connection has been established.
        Extra time to read HP banners.
        """
        delay_factor = self.select_delay_factor(delay_factor=0)
        time.sleep(2 * delay_factor)
        self.clear_buffer()
        self.set_base_prompt()
        self.disable_paging(command="\nscreen-length disable\n")

to

def session_preparation(self):
        """
        Prepare the session after the connection has been established.
        Extra time to read HP banners.
        """
        self._test_channel_read(pattern=r'[>\]]')
        self.set_base_prompt()
        self.disable_paging(command="\nscreen-length disable\n")

Thanks,
Bob

**Comment by ktbyers** [comment]
@bobwinners Can you show me the banner messages you receive when you manually SSH to one of those switches.

Also can post the Netmiko error you receive when trying to connect to one of the switches that fails.

**Comment by bobwinners** [comment]
I do not receive an error, it still just hangs.

Below is the banner that comes up after login
login as: admin
admin@10.1.5.15's password:

******************************************************************************
* Copyright (c) 2010-2013 Hewlett-Packard Development Company, L.P.          *
* Without the owner's prior written consent,                                 *
* no decompiling or reverse-engineering shall be allowed.                    *
******************************************************************************


                 ----------------------------------
                 |               |
                 |                                |
                 ----------------------------------
                         ***SECURITY WARNING***
Access to this device is restricted to authorized employees or
affiliates of the xxxxxxxx.  If you are
not an authorized party, you must disconnect now.  Any unlawful or
unauthorized access will be prosecuted to the fullest extent of the
law. All information contained within this device is proprietary to
the xxxxs network.  By accessing
this device, you acknowledge that you have read and agree to the
security statement above.Using keyboard-interactive authentication.

 Press Y or ENTER to continue, N to exit.

**Comment by ktbyers** [comment]
Can you do `show version` from that device after you login (or the equivalent). I want to see the software and model.

**Comment by ktbyers** [comment]
Is that your banner or an HP banner?

It looks like your banner...is this something you have configured?

**Comment by bobwinners** [comment]
The wording of the banner is something that was configured as a "header legal" in the config.

Version Info:

dis version
HP Comware Platform Software
Comware Software, Version 5.20.105, Release 6708-US
Copyright (c) 2010-2013 Hewlett-Packard Development Company, L.P.
HP 7510 uptime is 82 weeks, 4 days, 8 hours, 52 minutes

**Comment by bobwinners** [comment]
It freezes on the self._test_channel_read(pattern=r'[>]]') statement.

**Comment by etem** [comment]
Same issue here.

**Comment by ktbyers** [comment]
@bobwinners  I put this fix in:

https://github.com/ktbyers/netmiko/commit/ce50e3ab7afac805d97e11fc04d1753e034bc59a

Let me know if it fixes the problem.
