### ISSUE TITLE
Credential Hash verification

### ISSUE THREAD

**Issue by networkguy22** [ktbyers/netmiko#460]
In my application If I wanted to do client side credential authentication for Cisco routers and switches as away of providing redundant security measure, is that possible? I believe Cisco devices have their secret passwords hashed in md5, so couldn't you theoretically create a hash table to accomplish this?

Also I wouldn't consider this an issue as much as a question, but I couldn't find an appropriate section. In the future would prefer me to email you at a particular address or post in a different section?

As always thank you, Adam

**Comment by ktbyers** [comment]
@networkguy22 Meaning you want to properly identify their SSH host key using ~/.ssh/known_hosts (or something else)?

**Comment by networkguy22** [comment]
correct

**Comment by ktbyers** [comment]
See this article:

https://pynet.twb-tech.com/blog/python/paramiko-known-hosts.html

You should be able to pass in the arguments into Netmiko. 

http://netmiko.readthedocs.io/en/latest/classes/base_connection.html
