### ISSUE TITLE
Juniper SRX exit the configuration mode before committing

### ISSUE THREAD

**Issue by sjtarik** [ktbyers/netmiko#463]
Is below code correct for Juniper SRX? This works for MX's but with SRX, what I see is in debug mode, code exists the configuration mode without committing the changes. Workaround is to send a commit CLI as part of configuration commands sent along configuration items.

```
net_connect.config_mode()
if net_connect.check_config_mode():
    print("Successfully in config mode")
    net_connect.send_config_set(config_cmds)
    net_connect.commit()
    net_connect.exit_config_mode()
```

**Comment by ktbyers** [comment]
Should be able to just do the following (shouldn't need to enter/exit config mode manually).

```
    net_connect.send_config_set(config_cmds)
    net_connect.commit(and_quit=True)
```

Let me know if that doesn't work.

**Comment by tee-lake** [comment]
Hi ktbyers,

Below is what happens after sending commands to juniper devices if net_connect.commit(and_quit=True) is used. As mentioned by sjtarik, netmiko exits config mode thus changes made got discarded. It then logs in again to commit discarded changes thus not changes are made. Please view below.

DEBUG:netmiko:_read_channel_expect read_data: {primary:node0}[edit]

root@xxx-01# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'exit configuration-mode\n'
DEBUG:netmiko:read_channel: exit configuration-mode 

The configuration has been changed but not committed

Exiting configuration mode



{primary:node0}

root@xxx-01> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:_read_channel_expect read_data: 




DEBUG:netmiko:_read_channel_expect read_data: {primary:node0}

root@xxx-01> 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:_read_channel_expect read_data: 




DEBUG:netmiko:_read_channel_expect read_data: {primary:node0}

root@xxx-01> 
DEBUG:netmiko:write_channel: b'configure\n'
DEBUG:netmiko:_read_channel_expect read_data: configure
DEBUG:netmiko:_read_channel_expect read_data:  

warning: Clustering enabled; using private edit

warning: uncommitted changes will be discarded on exit

Entering configuration mode



{primary:node0}[edit]

root@xxx-01# 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:_read_channel_expect read_data: 




DEBUG:netmiko:_read_channel_expect read_data: {primary:node0}[edit]

root@xxx-01#  
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'commit and-quit\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: commit and-quit 

node0: 

commit complete


DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: Exiting configuration mode



{primary:node0}

root@xxx-01> 
DEBUG:paramiko.transport:EOF in transport thread

**Comment by ktbyers** [comment]
@tee-lake No the changes shouldn't get discarded. They are still there. You make a change, exit config mode (the changes are still in candidate config), you then go back into config mode and commit them.

That is what I see in your above trace.

Here is what it looks like if I do it manually on an SRX:

```
pyclass@pynet-jnpr-srx1# edit system         

[edit system]
pyclass@pynet-jnpr-srx1# set host-name test123 

[edit system]
pyclass@pynet-jnpr-srx1# exit configuration-mode 
The configuration has been changed but not committed
Exiting configuration mode

pyclass@pynet-jnpr-srx1> configure 
Entering configuration mode
The configuration has been changed but not committed

[edit]
pyclass@pynet-jnpr-srx1# show | compare 
[edit system]
-  host-name pynet-jnpr-srx1;
+  host-name test123;

[edit]
pyclass@pynet-jnpr-srx1# commit and-quit 
commit complete
Exiting configuration mode

pyclass@test123> 

```

Let me know if I am missing something, but I am not seeing the issue.

**Comment by ktbyers** [comment]
If you don't like that pattern, you can add this argument to `send_config_set()`:

```
net_connect.send_config_set(config_commands, exit_config_mode=False)
```

So it won't exit config mode.

**Comment by tee-lake** [comment]
I'll have to test if the above provides the desired result. However a quick look into "exit configuration-mode".
I do not think this works as demonstrated above for high-end srx device. Please see below

{primary:node0}[edit]
srx-5800-01# set security zones security-zone zoneA address-book address 10.10.10.10/32 10.10.10.10/32 

{primary:node0}[edit]
srx-5800-01# **sh|compare** 
[edit security zones security-zone zoneA address-book]
       address 10.12.19.0/18 { ... }
**+**      address 10.10.10.10/32 10.10.10.10/32;

{primary:node0}[edit]
srx-5800-01# exit configuration-mode 
The configuration has been changed but not committed
Exiting configuration mode

{primary:node0}
srx-5800-01> configure 
warning: Clustering enabled; using private edit
warning: uncommitted changes will be discarded on exit
Entering configuration mode

{primary:node0}[edit]
srx-5800-01# **sh|compare** 

{primary:node0}[edit]
srx-5800-01#

Thus I believe the config pasted is discarded once you leave config mode.

**Comment by ktbyers** [comment]
@tee-lake You should be able to do the following then:

```
net_connect.send_config_set(config_commands, exit_config_mode=False)
net_connect.commit(and_quit=True)
```

Basically, don't exit config mode on the changes. Then use the commit() method to commit the changes (and_quit just causes it to exit config mode after the commit).

**Comment by tee-lake** [comment]
@ktbyers 

Yes. that worked!

**Comment by assadniang** [comment]
This is still an issue Juniper Junos.

When you apply the config with:
`net_connect.send_config_set('delete virtual-machines instance vcsr-b')`
It would send the command and exit before giving you the chance to commit.

This is my code:
```
    net_connect.send_config_set('delete virtual-machines instance vcsr-a')
    net_connect.commit()
```
And here is the log:

```
{master:0}[edit]

root@ptr546-jdm# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'delete virtual-machines instance vcsr-b\n'
DEBUG:netmiko:read_channel: delete virtual-machines instance vcsr-b 



{master:0}[edit]

root@ptr546-jdm# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 



{master:0}[edit]

root@ptr546-jdm# 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'exit configuration-mode\n'
DEBUG:netmiko:read_channel: exit configuration-mode 

The configuration has been changed but not committed

Exiting configuration mode



{master:0}

root@ptr546-jdm> 
```

It should not exit the configuration mode after sending the command.

This is done right in Vyatta OS, in Vyatta, it sends the config command, but does not exit, and you can then send the Commit and Exit Config Mode.
