### ISSUE TITLE
Nested SSH using netmiko

### ISSUE THREAD

**Issue by alex2548** [ktbyers/netmiko#465]
Hi,
I'm new into netmiko, and i am trying to SSH into a CPE router via a PE router
i can SSH to the PE router with no problems.However, when trying to connect to CPE (in a VRF) i get a timeout exception: netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 33.33.33.33:22
is it because connectHandler is not VRF-aware ??
PE = {
    'device_type': 'cisco_ios',
    'ip': '3.3.3.3',
    'username': 'alex',
    'password': '12345',
    'port' : 22,
}
CPE = {
    'device_type': 'cisco_ios',
    'ip': '192.168.20.38',
    'username': 'alex',
    'password': '12345',
    'port' : 22,          
}
PE_connect = ConnectHandler(**PE)
CPE_connect = ConnectHandler(**CPE)

output = CPE_connect.send_command('show ip int brief')
print(output)

CPE_connect.disconnect()
PE_connect.disconnect()

**Comment by ktbyers** [comment]
@alex2548 Netmiko is going to try to SSH to the IP address you specify...so it will try connect to 192.168.20.38 for the CPE device.

If this IP is not directly reachable from the Netmiko server, then the SSH will fail.

If you want to SSH to PE and then SSH to CPE, you will need to connect to PE and then manually control the SSH session to login to the second device (i.e. execute ssh -l username <ip_addr> and handle the username/password login of the remote device).

You will probably need to use the `write_channel` and `read_channel` methods to accomplish this.

**Comment by ktbyers** [comment]
Here is an issue where someone did something similar to this:

https://github.com/ktbyers/netmiko/issues/470

**Comment by alex2548** [comment]
That's what I was trying to do. Thanks a lot

**Comment by amitbeniwal48** [comment]
@ktbyers Thanks for support in advance. But I have a followup question: What would be the best approach if I wanted to return to Jump-Server/Router after my job on the actual device was completed and wanted to login a second or a third device and complete more jobs on them.

**Comment by ktbyers** [comment]
@amitbeniwal48 If you don't have Netmiko actually installed on the intermediate server, then the best solution is to use an SSH config file from your automation server and just use the Jump Server as a hopping off point.

See:  https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html
