### ISSUE TITLE
Set default connection method to Telnet when port 23 is specified 

### ISSUE THREAD

**Issue by 2001-g-1001** [ktbyers/netmiko#466]
Hello Kirk,

I think that this should be the default behavior when port 23 is specified and there is no '_telnet' addition specified at the device_type.

Best Regards!

diff --git a/netmiko/base_connection.py b/netmiko/base_connection.py
index 4f1409d..5bcf2dc 100644
--- a/netmiko/base_connection.py
+++ b/netmiko/base_connection.py
@@ -117,7 +117,7 @@ class BaseConnection(object):

         self._session_locker = Lock()
         # determine if telnet or SSH
-        if '_telnet' in device_type:
+        if '_telnet' in device_type or self.port == '23':
             self.protocol = 'telnet'
             self._modify_connection_params()
             self.establish_connection()

**Comment by ktbyers** [comment]
Netmiko Telnet support is too narrow to make this worthwhile.
