### ISSUE TITLE
parse cli output to csv file from network device using TextFSM

### ISSUE THREAD

**Issue by NedySuprianto** [ktbyers/netmiko#468]
- Template Creation Help

hi guys, sorry for the inconvenience, i want to ask how to create new template TextFSM for '**_show memory statistics_**', i already looked at https://github.com/networktocode/ntc-templates/tree/master/templates but there's no '**_show memory statistics template_**'. 

thanks :)

**Comment by cldeluna** [comment]
Hi @NedySuprianto,

Try something like this:
I have two options for MEMTYPE, one for explicit matching and one for more general (commented out) but it may pick up more than you wanted.

I've attached the sample text I used and the CSV (saved as XLSX for upload here)  file of the results.
I tend to process lots of files at once so I always start with the hostname but you can do that other ways and simplify this a bit more.
[MEM_cisco_ios_show_memory_stat-results.xlsx](https://github.com/ktbyers/netmiko/files/996923/MEM_cisco_ios_show_memory_stat-results.xlsx)

This may not be exactly what you want but hopefully will serve as an example that you can edit for your own needs.

I'm fairly new at this myself so this may not be the best approach (so If anyone has any suggestions I'd love to hear them!) but at least in my small sample set it seems to be working.

I hope this helps!

cisco_ios_show_memory_stat.template
<>
Value Filldown HOSTNAME (\S+)
#Value MEMTYPE ([^0-9]+)
Value MEMTYPE ((Processor|\s+I/O|Driver te))
Value HEAD ([0-9A-f]+)
Value TOTAL (\d+)
Value USED (\d+)
Value FREE (\d+)
Value LOW (\d+)
Value LARGE (\d+)


Start
  ^\s+Head\s+
  ^(hostname|switchname) ${HOSTNAME}
  ^${MEMTYPE}\s+${HEAD}\s+${TOTAL}\s+${USED}\s+${FREE}\s+${LOW}\s+${LARGE} -> Record
  ^${MEMTYPE}\s+${HEAD}\s+${TOTAL}\s+${USED}\s+${FREE}\s+${LOW}\s+${LARGE} -> Record
  ^${MEMTYPE}\s+${HEAD}\s+${TOTAL}\s+${USED}\s+${FREE}\s+${LOW}\s+${LARGE} -> Record

<>

Sample Config
[cisco_ios_show_mem_stat_example.txt](https://github.com/ktbyers/netmiko/files/996895/cisco_ios_show_mem_stat_example.txt)

**Comment by NedySuprianto** [comment]
hi @ktbyers  

this is like what i want,i tried it and its worked. 
thanks for your help @ktbyers  this is so helpful :)

**Comment by NedySuprianto** [comment]
i solved this problem, should we close this issue?
