### ISSUE TITLE
parse cli output 'show proc cpu history' to file csv (Using TextFSM,etc)

### ISSUE THREAD

**Issue by NedySuprianto** [ktbyers/netmiko#471]
is anyone have idea how to read this table and parse out to csv file or something, i need to convert it into graph(if possible).
i really confused how to read this table, not like 'show inventory' or 'show version' there's have a TextFSM Template to parse out the data, how about 'show proc cpu history' there's have TextFSM Template or anything?

**_show proc cpu history(from show tech.txt)_** 
![show-proc-cpu](https://cloud.githubusercontent.com/assets/27726673/26151432/13bfeffa-3b2d-11e7-9f5b-dc15fdc81a71.jpg)

**Comment by ktbyers** [comment]
Just use SNMP and grab the CPU usage from this (and then for historical data store into some time-series system).

**Comment by NedySuprianto** [comment]
i actually build app to grab data from router/switch (build my own SNMP) for my internship project with python using netmiko, matplotlib, TextFSM which can convert the data into a graph, and my boss told me to grab 'show proc cpu history' too, i confused how can i grab if the data like that.
hhmmm... should i use SNMP Tools to grab it? i think i will working twice here, have another way??

**Comment by ktbyers** [comment]
IMO, it is a bad idea to try to do a complex TextFSM parsing against a poor ASCII screen-graph when you just have the data directly and can easily just grab the data and make a very nice graph.

If you don't want to use SNMP, then you could use SSH and grab this:

```
$ netmiko-show --cmd "show proc cpu | inc CPU util" pynet_rtr1
CPU utilization for five seconds: 10%/0%; one minute: 2%; five minutes: 1%
```

And then parse it to get the number you want (i.e. 5-second; one-minute average, etc)

**Comment by NedySuprianto** [comment]
i already grabed
`CPU utilization for five seconds: 10%/0%; one minute: 2%; five minutes: 1%`
parse it to text and makeit to graph, that's why i really confused when my PM tell me to grab 'show proc cpu history'.hmmmm... maybe i'll find another way to parse it and make it to graph.

**Comment by riddhi2910** [comment]
Hey,I am doing similar project in my internship. I need to find vulnerabilities of network devices and make one file with asked network device. Need some help.
