### ISSUE TITLE
IOError: Search pattern never detected in send_command_expect:

### ISSUE THREAD

**Issue by Goldish21** [ktbyers/netmiko#474]
Hi,

I am trying to fetch network logs from a repository, HP server, for a particular IP and trying to display it but getting the following errors:

---------------------------------------
[Fri May 19 09:49:13.636747 2017] [cgi:error] [pid 7672:tid 2552] [client ::1:64776] AH01215: Traceback (most recent call last):\r: C:/xampp/cgi-bin/login.py, referer: http://localhost/wp/login/?preview_id=224&preview_nonce=a936551700&_thumbnail_id=-1&preview=true
[Fri May 19 09:49:13.636747 2017] [cgi:error] [pid 7672:tid 2552] [client ::1:64776] AH01215:   File "C:/xampp/cgi-bin/login.py", line 30, in <module>\r: C:/xampp/cgi-bin/login.py, referer: http://localhost/wp/login/?preview_id=224&preview_nonce=a936551700&_thumbnail_id=-1&preview=true

[Fri May 19 09:49:13.636747 2017] [cgi:error] [pid 7672:tid 2552] [client ::1:64776] AH01215:     output = net_connect.send_command('fw log | grep ' + 'addr' + "\\n")\r: C:/xampp/cgi-bin/login.py, referer: http://localhost/wp/login/?preview_id=224&preview_nonce=a936551700&_thumbnail_id=-1&preview=true

[Fri May 19 09:49:13.637750 2017] [cgi:error] [pid 7672:tid 2552] [client ::1:64776] AH01215:   File "C:\\Python27\\lib\\site-packages\\netmiko\\base_connection.py", line 802, in send_command\r: C:/xampp/cgi-bin/login.py, referer: http://localhost/wp/login/?preview_id=224&preview_nonce=a936551700&_thumbnail_id=-1&preview=true
[Fri May 19 09:49:13.637750 2017] [cgi:error] [pid 7672:tid 2552] [client ::1:64776] AH01215:     search_pattern))\r: C:/xampp/cgi-bin/login.py, referer: http://localhost/wp/login/?preview_id=224&preview_nonce=a936551700&_thumbnail_id=-1&preview=true

[Fri May 19 09:49:13.637750 2017] [cgi:error] [pid 7672:tid 2552] [client ::1:64776] AH01215: IOError: Search pattern never detected in send_command_expect: \\[Expert\\@logserver\\:0\\]\\#\r: C:/xampp/cgi-bin/login.py, referer: http://localhost/wp/login/?preview_id=224&preview_nonce=a936551700&_thumbnail_id=-1&preview=true
-------------------------

Here is the code:
=============

_crp_mds = {
    'device_type': 'hp_procurve',
    'ip': 'x.x.x.x',
    'username': 'admin',
    'password': 'x.x.x.x',
}_

_net_connect = ConnectHandler(**crp_mds)
net_connect.send_command("mdsenv x.x.x.x")
print "Connected to mdsenv" + "\n"
output = net_connect.send_command('fw log | grep ' + 'addr' + "\n")
print (output)__

**Comment by ktbyers** [comment]
@Goldish21 What kind of device are you connecting to?

It is running Linux?

**Comment by Goldish21** [comment]
Yes, it's an MDS server. Running GAIA OS but i am pulling logs from Expert mode.

**Comment by ktbyers** [comment]
If you are just interfacing to it at the Linux level, then something like Ansible will be much easier to accomplish this.

There is a `checkpoint_gaia` device type and a 'linux' device type...but I would look at Ansible (if possible).

You probably won't be able to use the hp_procurve device type.

**Comment by Goldish21** [comment]
Thanks! for your time. I used paramiko and it's working.

**Comment by ktbyers** [comment]
FYI, you still might want to check out Ansible...it makes this kind of thing very easy.

**Comment by Goldish21** [comment]
Sure, I will. I am following your articles :)
