### ISSUE TITLE
Loading a configuration from txt file takes a lot of time

### ISSUE THREAD

**Issue by piyushshewkani** [ktbyers/netmiko#475]
Hi,

I am practicing network automation using netmiko library and have been able to do so only because of the great content provided by Kirk Byers. Thank you so much sir!

I created a code which loads the configuration from a text file in a certain directory on to the cisco device. I have created the whole lab on GNS3. The code is running perfectly fine it's just that it takes a lot of time to push the configuration on the device. Using the datetime library, I came to know that the code is taking 1 minute and 30 seconds to push the configuration. I am just curious to know if there is any faster way of doing it or does netmiko takes this much amount of time.

Here is the part of the code:

`AUTOLAB = {
	'device_type': 'cisco_ios',
	'ip': IP_ADD, #these variables have been taken as raw_input
	'username': USER_NAME,
	'password': PASSWORD,
	'secret' : SECRET_PASS,
	} 

net_connect = ConnectHandler(**AUTOLAB)
net_connect.enable()
net_connect.config_mode()

with open(user_path, 'r') as f:		#user_path is the variable i defined which takes the path of file(configuration file) as raw input from the user.
	config_commands = f.readlines()

Tstart = datetime.now()
net_connect.send_config_set(config_commands)
Tend = datetime.now()
Tdiff = Tend - Tstart
print ("\n ***Configuration loaded***")
print ("Time taken to push the configuration = " + str(Tdiff))
print ("\n\n Aborting Connection with " + IP_ADD)
net_connect.disconnect()`

![image](https://cloud.githubusercontent.com/assets/28910562/26381182/7bcec7a0-3fe8-11e7-84bc-9a71c83f9d45.png)

As you can in above screen shot, it took 1:30 secs to push the configuration. Can you please let me know if this is normal?

**Comment by ktbyers** [comment]
@piyushshewkani How many configuration commands are in `config_commands`?

**Comment by piyushshewkani** [comment]
Hi,

It's the whole configuration taken from txt file. I am attaching the file so that you can look for yourself.
[R2_backup2.txt](https://github.com/ktbyers/netmiko/files/1026798/R2_backup2.txt)

When we normally ssh connect to a device via putty or any other terminal and copy paste the configurations from a text file, it happens in 5-10 seconds. The script is taking way too much time to accomplish the same task. I have just tried it on one device at a time. I was planning on to run the script such that it will push the configurations in all the devices in my lab (around 6 routers, 4 switches and two ASAs)

**Comment by ktbyers** [comment]
@piyushshewkani Yes, you should probably use NAPALM (napalm-ios) replace operation for this. It uses Netmiko under-the-hood for this, but should be faster.

90 seconds sounds a bit slow (meaning it is longer than I would have expected), but it also isn't going to happen in 5-10 seconds using straight Netmiko.

You can parallelize, if you use napalm-ansible, it will automatically parallelize to 5 devices (you can add the --forks arguments to parallelize to more devices).

**Comment by mabslkoirala** [comment]
Hi Kirk,
I feel lucky today as I came to read this comment thread today. I believe you will help me how to speed up to load the config in the router. I spend around a week to find the information how do we make faster pushing config in ASR9K router. it is taking around 40 min to push around 300 lines of config. I found default global delay is 3 sec in python. I made it 1 sec setting global_delay_factor =1 in connecthandler. my config line is below. could you please help to resolve this issue? your earliest response is highly appreciated.

 net_connect = netmiko.ConnectHandler(device_type='cisco_xr', ip=Ip , username=Username, password=Password, global_delay_factor=1)

    for i in range(len(dictnew_PM)):
        print net_connect.send_config_set(dictnew_PM[i])

**Comment by ktbyers** [comment]
@mabslkoirala Make sure you are using Netmiko 2.3.0 then try setting fast_cli=True

```
net_connect = netmiko.ConnectHandler(device_type='cisco_xr', ip=Ip , username=Username, password=Password, fast_cli=True)
```

Also, you shouldn't be doing a for loop in that way for Netmiko and send_config_set (you will be making things a lot slower that way).

Netmiko send_config_set() takes a list of commands, so you should just do:

```
net_connect.send_config_set(list_of_commands)
```

i.e. no separate for-loop. If you need to create a list of commands from some other data-structure, then you should do that as a preprocessing step before calling send_config_set.

**Comment by mabslkoirala** [comment]
> @mabslkoirala Make sure you are using Netmiko 2.3.0 then try setting fast_cli=True
> 
> ```
> net_connect = netmiko.ConnectHandler(device_type='cisco_xr', ip=Ip , username=Username, password=Password, fast_cli=True)
> ```
> Also, you shouldn't be doing a for loop in that way for Netmiko and send_config_set (you will be making things a lot slower that way).
> 
> Netmiko send_config_set() takes a list of commands, so you should just do:
> 
> ```
> net_connect.send_config_set(list_of_commands)
> ```
> i.e. no separate for-loop. If you need to create a list of commands from some other data-structure, then you should do that as a preprocessing step before calling send_config_set.



Thank you very much Krik, your comment is highly appreciated.
I created text file and load config removed for loop so less than a minute of job completed.
(however I tried but could not able to install netmiko version 2.3.0, but not a big deal for me now)
Now time to go through your lecture videos and to learn more :).
