### ISSUE TITLE
Help to access network device via ssh over jump server from windows script server

### ISSUE THREAD

**Issue by toaster09** [ktbyers/netmiko#479]
Hi below is the code I've used, im very new to programming 

from netmiko import ConnectHandler
import time
from netmiko import redispatch

jumpserver = {
        'device_type':'linux', <<<<<<<<<<<<<<< tried using terminal server as well
        'ip': '192.168.5.2',
        'username':'xxx',
        'password':'xxxx',
}

net_connect = ConnectHandler(**jumpserver)
print net_connect.find_prompt()
net_connect.write_channel("ssh xx@10.30.1.11") >>>> or a ssh 10.30.1.11
net_connect.read_channel()
redispatch(net_connect, device_type='cisco_ios')
net_connect.send_command('show version')
net_connect.disconnect()

I can see that i do get a hit on the end network device for the terminal server ip address without a login id shown on the sh users output but after sometime it times out but this is only if i use the net_connect.send_command("ssh 10.30.1.11") instead of net_connect.write_channel.

the network device ip address; the username and password to access both the jumpserver and network device are the same.

If i use the above code below is the output i get

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\KRS\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "C:\Users\KRS\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/KRS/testshiiproute.py", line 22, in <module>
    redispatch(net_connect, device_type='cisco_ios')
  File "build\bdist.win32\egg\netmiko\ssh_dispatcher.py", line 142, in redispatch
ValueError: Router prompt not found: [xx@xx-terminal ~]$
>>>   File "build\bdist.win32\egg\netmiko\cisco\cisco_ios.py", line 11, in session_preparation
  File "build\bdist.win32\egg\netmiko\base_connection.py", line 634, in set_base_prompt

**Comment by ktbyers** [comment]
I recommend you look at this article:

https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

Note, the format of the SSH config host identifier changed in Netmiko 1.4.0, see:

https://github.com/ktbyers/netmiko/releases/tag/v1.4.0

**Comment by toaster09** [comment]
Thanks I've managed to resolve the issue using data from the below link, thanks for the awesome module as well

https://github.com/ktbyers/netmiko/issues/470

**Comment by milind1234567** [comment]
Hello,

I have below code for SSH to Cisco device and getting error as below

I am using Python 2.7.10 version.

#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass

ip_addr = raw_input("Enter IP Address: ").strip()
password = getpass()

cisco = {
    'device_type': 'cisco_ios',
    'ip': ip_addr,
    'username': 'mphulmal',
    'password': password,
    'port': 22,
	'global_delay_factor': 3,
    'ssh_config_file': '~/.ssh/config',
    'verbose': False,
}

net_connect = ConnectHandler(**cisco)
output= net_connect.enable()
output = net_connect.send_command('show users')
print output
print
print net_connect.find_prompt()
print 



=================
Error I get is as below
=================

C:\Milind\Python>telnet.py
Enter IP Address: 57.215.88.151
Password:

Traceback (most recent call last):
  File "C:\Milind\Python\telnet.py", line 20, in <module>
    net_connect = ConnectHandler(**cisco)
  File "C:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 168, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 187, in __init__
    self.establish_connection()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 654, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 57.7.44.97:22

C:\Milind\Python>



Intermediate server IP : 57.7.44.97


pvce124#sh users
    Line       User       Host(s)              Idle       Location
*  2 vty 0     mphulmal   idle                 00:00:00 57.7.44.97

  Interface    User               Mode         Idle     Peer Address

pvce124#
