### ISSUE TITLE
Search pattern never detected 

### ISSUE THREAD

**Issue by soaliou** [ktbyers/netmiko#484]
Hi guys,

I am writing a code and It stops at "int loopback3" level no ip address assigned  Not sure exactly what I am missing in my code. I am new to netmiko and python.
Thank you in advance.

```
Traceback (most recent call last):
  File "C:\Users\212606476\Documents\Python\shcdpneighbors.py", line 26, in <module>
    connection.send_command('int loopback3')
  File "C:\Users\212606476\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko-1.4.0-py3.6.egg\netmiko\base_connection.py", line 802, in send_command
OSError: Search pattern never detected in send_command_expect: ESW1\(config\)\#
>>> connection.find_prompt()
'ESW1(config-if)#'


===================below is the script===================================
import netmiko
import time
Sw1 = {'device_type' : 'cisco_ios' , 'ip' : '172.23.1.72' , 'username' : 'admin' , 'password' : 'cisco' , 'secret' : 'cisco'}

connection = netmiko.ConnectHandler(**Sw1)

connection.enable()
connection.find_prompt()
connection.config_mode()
connection.find_prompt()


connection.send_command('int loopback3')
time.sleep(2)
connection.send_command('ip address 39.39.39.39 255.255.255.255')
time.sleep(2)
connection.send_command('end')
time.sleep(2)
connection.send_command('wr')
time.sleep(2)
output = connection.send_command('show ip int brief | ex una')
print(output)
```

**Comment by Demacr** [comment]
Maybe do you need call connection.find_prompt() after 'int loop3' command because your prompt changed from 'ESW1(config)#' to 'ESW1(config-if)#'?

**Comment by soaliou** [comment]
still the same. stuck 'ESW1(config-if)

**Comment by Demacr** [comment]
Print your new code and traceback.

**Comment by Demacr** [comment]
So, now I understand one thing. You call find_prompt(). Delete all find_prompt()'s in your code and try again.

**Comment by soaliou** [comment]
delete " connection.find_prompt() " ?

**Comment by Demacr** [comment]
Yep )

**Comment by soaliou** [comment]
All the show commands work fine. but not enable.  Still stops at interface loopback3

**Comment by soaliou** [comment]
I am using a text editor Notepad++ to run my script

**Comment by soaliou** [comment]
But should not affect the output. Even from the python shell it stops at "interface "loopback3" level

**Comment by ktbyers** [comment]
@soaliou For configuration changes, always use `send_config_set()` or `send_config_from_file()` methods.

So it should be pretty close to this:

```
import netmiko
import time

Sw1 = {'device_type' : 'cisco_ios' , 'ip' : '172.23.1.72' , 
             'username' : 'admin' , 'password' : 'cisco' , 'secret' : 'cisco'}

connection = netmiko.ConnectHandler(**Sw1)

connection.enable()
connection.find_prompt()

config_cmds = ['int loopback3', 'ip address 39.39.39.39 255.255.255.255']
connection.send_config_set(config_cmds)
connection.send_command('wr mem')

output = connection.send_command('show ip int brief | ex una')
print(output)
```

Netmiko will automatically handle entering/exiting config mode.

Trying to do this manually with `send_command` is challenging as the prompt is changing.

**Comment by ktbyers** [comment]
Just re-open if this doesn't work.
