### ISSUE TITLE
How can I connect to host use pem file with ssh？

### ISSUE THREAD

**Issue by kingcmy** [ktbyers/netmiko#488]
How can I connect to host use pem file with ssh？please display a example, thanks!

**Comment by ktbyers** [comment]
Can you give some more details on what you are trying to do?

A host...you mean a Linux box? or a network device (which type)?

Also post your current code.

**Comment by kingcmy** [comment]
@ktbyers 
We use Jumpserver(http://www.jumpserver.org/) to connect servers and network devices,it deploys on CentOS6.0 and use pem files has encrypted to login, I want to connect the Jumpserver than connect the network devices through it.I use paramiko to connect jumpserver below,sorry my English is very poor,hope you can understand it :

import paramiko
hostname = '1.1.1.1'
username = 'mianye.chen'
 
key_file = '/data/DeviceConfiguration/mianye.chen.pem' #私钥文件
key_file_pwd = '*****'  #私钥密码
 
 
paramiko.util.log_to_file('ssh_key-login.log')
privatekey = os.path.expanduser(key_file) #私钥文件
key = paramiko.RSAKey.from_private_key_file(privatekey,key_file_pwd)
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
a = ssh.connect(hostname=hostname,username=username,pkey=key)

**Comment by ktbyers** [comment]
...you aren't using Netmiko? 

Here is how you would do an SSH proxy setup with Netmiko. Note, the host identifier changed in Netmiko 1.4.0 so see this for reference to that change:

https://github.com/ktbyers/netmiko/releases/tag/v1.4.0

**Comment by kingcmy** [comment]
@ktbyers 
I just ask how to using netmiko to connect device through pem file that encrypted...
I post the example just means I know use paramiko to do it...
Thanks for your answer,I'll try it.

**Comment by ktbyers** [comment]
@kingcmy Okay...I understand what you are trying to do now.

Unfortunately, I don't have support for encrypted keys. I need to add in support for the `pkey` argument.

**Comment by ktbyers** [comment]
The fix for this is in Netmiko to use the `password` field which will be used to decrypt the key.
