### ISSUE TITLE
Add a way to read commands from a file for send_command_set()

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#49]

**Comment by supertylerc** [comment]
I asked about this a few days ago.  However, I think that there may be some things to consider.  Creating an array of the files lines may be bad from a performance perspective.  Chunking may be better, creating a smaller array, pushing the lines, and then going through the next X chunks.  This is particularly true when the file contains entire configurations with comments.

This suggestion may fall under "[premature optimization is the root of all evil](http://en.wikipedia.org/wiki/Program_optimization#Quotes)", though.  Take it with a grain of salt.  :)

Also, as I require this feature for an upcoming project, I may implement it (crudely) and submit a PR with the change.

**Comment by ktbyers** [comment]
I think we should probably keep it simple...just read in the whole file and parse it into a list. 

I don't see the performance of chunking as mattering.

The performance that possibly matter is how long it takes to send a whole bunch of configuration commands since send_config_set() calls send_command() which will by default delay 1 second per command.

**Comment by supertylerc** [comment]
I've written the code for this.  I'll be submitting a PR later today or tomorrow.

**Comment by supertylerc** [comment]
This is in #58.
