### ISSUE TITLE
SCP transfer change window-size to reasonable value.

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#491]
An update to the group regarding code uploads with netmiko on cisco devices (edited)
by default most cisco devices have this setting only shown when performing: sh run all | in tcp

ip tcp window-size 4128

this will drastically slow down file transfers. for example a 178 mb file took over 3 hours due to this horrible window size after changing to

ip tcp window-size 65535

the file transfer was around 20 minutes with verify at 30 minutes total.

**Comment by rwill-at-ncgov** [comment]
Just an FYI... 

cisco ASR-920-24TZ-M
Cisco IOS XE Software, Version 16.06.04
Cisco IOS Software [Everest], ASR920 Software (PPC_LINUX_IOSD-UNIVERSALK9_NPE-M), Version 16.6.4, RELEASE SOFTWARE (fc3)

with:

ip tcp window-size 65536
ip ssh window-size 65536
ip ssh rsa keypair-name myrsakey
ip ssh version 2
ip ssh server peruser session limit 4
ip ssh server algorithm authentication password
ip scp server enable

And no change whatsoever in scp file transfer time.

Regards,

Rick

**Comment by ktbyers** [comment]
Closing as I don't think there is any action for to do here.
