### ISSUE TITLE
root login for linux/ovs

### ISSUE THREAD

**Issue by plasmixs** [ktbyers/netmiko#492]
Should the username 'root' be allowed for the linux and ovs devices ?
Rather the initial ssh login should be non-root and when changing to enable/config mode
the sudo su does change to the root user. This keeps it consistent with Cisco and other devices,
where you need to change to enable/config to perform privileged operations.

**Comment by plasmixs** [comment]
With root username when logging to linux issue #348 is encountered.

**Comment by ktbyers** [comment]
I don't think this is Netmiko's job to enforce this. Note, on Cisco and other platforms you can potentially log directly into privileged mode depending on AAA configuration so the Linux behavior is consistent with these platforms.
