### ISSUE TITLE
Testing web connectivity after connection established  

### ISSUE THREAD

**Issue by clatcho** [ktbyers/netmiko#493]
i am trying to test web connectivity from a Cisco router after i am connected. 

I want to be able to do something like this :

telnet 212.58.244.57 80 /source-interface Eth0
GET /index.htm HTTP/1.1
host: news.bbc.co.uk

So, lets say the above is in a list, and then 

	print 'send > ' + commands[0]
	print net_connect.send_command(commands[0],expect_string='Open') < This is working 

	print 'send > ' + commands[1]
	net_connect.write_channel(commands[1]) < This is not working 

	print 'send > ' + commands[2]
	print net_connect.send_command(commands[2] + '\n') < This is not working
	print 'end'

After the first command. there is no router prompt, thats why i was trying to use write_channel() < although i don't know if this is the right thing to do ?

**Comment by ktbyers** [comment]
Can you post the contents of `commands` so I can see what the contents of command[0], [1], [2] are exactly?

**Comment by clatcho** [comment]
The commands 

telnet 212.58.244.57 80 /source-interface Eth0
GET /index.htm HTTP/1.1
host: news.bbc.co.uk

**Comment by ktbyers** [comment]
Yes, I want to see the code...as it matters if the code has an enter in it or not. 

For example, `write_channel` you must add a newline to it (as write_channel is pretty low-level). Whereas `send_command` will automatically send an enter, by default.

**Comment by clatcho** [comment]
three 	= 'telnet 212.58.244.57 80 source-interface Eth0'

	four	= 'GET /index.htm HTTP/1.1\n'

	five	= 'host: news.bbc.co.uk\n'

	command_list.extend((three,four,five))

I have played around with the carriage returns, but no joy so far. 

For the last command, i thought i could wait for the closing html, but 

  `print net_connect.send_command(commands[2],expect_string='</html>') `

however, i eventually get 

`IOError: Search pattern never detected in send_command_expect: </html>`

i thought maybe its something to do with the terminal length ? So i added this

```
def prepareTheTerminal(net_connect):
	net_connect.send_command('terminal width 0')
	net_connect.send_command('terminal length 0')
```

Again, no luck so far

**Comment by clatcho** [comment]
I got it working, should have had more patience, sometimes its better to walk away from the screen and think about it . . .

```
def getHTML(net_connect,commands):

	print net_connect.send_command(commands[0],expect_string='Open')

	net_connect.write_channel(commands[1] + '\n')
	net_connect.write_channel(commands[2] + '\n\n')
	print net_connect.read_until_pattern('</html>')
```

Not sure if this is the best approach, but it works, thanks for all your hard work with netmiko, i use it nearly every day at work
