### ISSUE TITLE
Huawei switches have no enable mode.

### ISSUE THREAD

**Issue by fumeng2005** [ktbyers/netmiko#494]
Huawei switches have no enable mode that causes an exception to be raised when a network is added.
The exception msg is as follows:"Failed to enter enable mode"

**Comment by fumeng2005** [comment]
https://bugs.launchpad.net/networking-generic-switch/+bug/1697440

**Comment by fumeng2005** [comment]
edit /usr/lib/python2.7/site-packages/netmiko/huawei/huawei_ssh.py
and rewrite the methos for HuaweiSSH class:
class HuaweiSSH(CiscoSSHConnection):
    。。。。。。
    def enable(self, cmd='enable', pattern='password', re_flags=None):
        return “”

**Comment by ktbyers** [comment]
@fumeng2005 This was fixed and added to the `develop` branch.

Can you update the issue here and let them know it will be in the next Netmiko release:

https://bugs.launchpad.net/networking-generic-switch/+bug/1697440

**Comment by fumeng2005** [comment]
thx, I will do it.
