### ISSUE TITLE
Unable to log into Brocade ICX (fastiron) when RADIUS authentication for Enable is configured

### ISSUE THREAD

**Issue by nsnoonan** [ktbyers/netmiko#495]
I'm testing using a Brocade ICX7250.  If enable authentication is disabled with the following command, everything works:
`aaa authentication enable default none`

If enable authentication is configured to use RADIUS:
`aaa authentication enable default radius local`

I get the following when connecting:
```
net_connect = netmiko.ConnectHandler(**icx)
SSH connection established to 10.0.0.2:22
Interactive SSH session established
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "C:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 124, in ConnectHandler
   return ConnectionClass(*args, **kwargs)
 File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 151, in __init__
   self.session_preparation()
 File "C:\Python27\lib\site-packages\netmiko\brocade\brocade_fastiron_ssh.py", line 12, in session_preparation
   self.enable()
 File "C:\Python27\lib\site-packages\netmiko\cisco_base_connection.py", line 17, in enable
   return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
 File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 877, in enable
   output += self.read_until_prompt_or_pattern(pattern=pattern, re_flags=re_flags)
 File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 345, in read_until_prompt_or_pattern
   return self._read_channel_expect(combined_pattern, re_flags=re_flags)
 File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 289, in _read_channel_expect
   raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```

Here is what a login looks like with enable radius configured:
```
Using username "service_netmiko".
Using keyboard-interactive authentication.
Password:
SSH@Lab-ICX7250>en
User Name:service_netmiko
Password:
SSH@Lab-ICX7250#
```

**Comment by aaglenn** [comment]
I have numerous ICX7250s with RADIUS configured that do not exhibit this behavior. They're running SW: Version 08.0.61T211.

**Comment by ktbyers** [comment]
@aaglenn I made a fix for this in the `develop` branch. See https://github.com/ktbyers/netmiko/commit/ec9ce93c20b005931d8c6dbeae75556871f9a0b3

Can you test if this fixes the issue?

**Comment by ktbyers** [comment]
Closing this should be fixed. If you test this, please update the issue or re-open if still not working.

**Comment by nhandh09** [comment]
Hi Ktbyers,

I'm sorry if here is duplicate question. May I ask if netmiko support Brocade devices (specifically is ADX1000 and ICX(6k, 7k series), could you link me to topic mentioned brocades devices (device_type)?

Many thanks again KT, your library help me much on work!

**Comment by ktbyers** [comment]
@nhandh09 Check this file here:

https://github.com/ktbyers/netmiko/blob/develop/PLATFORMS.md

**Comment by yemisie** [comment]
from typing import 
from netmiko import ConnectHandler
from getpass import getpass


password = getpass()
secret = getpass()


# creating a dictionary for the device to connect to
brocade = {
       "device_type": "brocade",     
       "host": "172.16.1.1",
       "username": "admin",
       "password": password,
       "port": 22,             # optional, default 22
       "secret": secret,      # this is the enable password
       "verbose": True         # optional, default False
       }

# connecting to the device and returning an ssh connection object
connection = ConnectHandler(**brocade)

connection.enable 

I made up this for my Brocade MLxe and its working for me.
