### ISSUE TITLE
SHOW_RUN_MAPPER for Alcatel AOS

### ISSUE THREAD

**Issue by rbthomp** [ktbyers/netmiko#498]
Hello, I was looking at the SHOW_RUN_MAPPER and noticed that command 'show configuration snapshot' is the command used for returning the running config. Do you plan to use the send_command() to execute this? If so, note that the session prompt is a line item in the config and will result in a partial config being returned by send_command().

To address this in my code I had to use send_command_expect() with the last line of 'show configuration snapshot' so the prompt was not detected prematurely. 

Ryan

**Comment by ktbyers** [comment]
Okay, thanks for that information. Netmiko doesn't actually implement this command directly it is for use by other applications that use Netmiko (so they would need to handle that case properly for Alcatel AOS).
