### ISSUE TITLE
set_base_prompt for ubiquiti_edge

### ISSUE THREAD

**Issue by jftuga** [ktbyers/netmiko#499]
I am using device_type=ubiquiti_edge but my edge router has a different default prompt. I just installed the latest firmware on my EgdeRouter Lite 3 (v1.9.1.1).

    obj = {'username': 'ubnt', 'ip': '192.16.1.1', 'verbose': True, 'port': 22, 'password': b'whatever', 'device_type': 'ubiquiti_edge'}

When I ssh in, my shell prompt look like this:

    ubnt@ubnt:~$
    
I can then type 'configure' which will change the prompt:

    ubnt@ubnt:~$ configure
    [edit]
    ubnt@ubnt# run terminal length 9999
    [edit]
    ubnt@ubnt#

I am initiating a connection like this:

    net_connect = ConnectHandler(**obj)

I get this error:

    ValueError: Router prompt not found: ubnt@ubnt:~$

How can I call something like the code below before the ConnectHandler actually makes the SSH connection so that the prompt is set correctly beforehand?

    net_connect.base_prompt = "$"
    # or:
    net_connect.set_base_prompt("$")

Ideally, the full set of commands I want to run are:

    configure
    run terminal length 9999
    run show configuration all
    exit

Notice that after the 'configure' command, the prompt changes and then it will change back after the 'exit' command is issued.  The 'exit' command does not log off, it just exits the configure mode.

**Comment by ktbyers** [comment]
Okay, looking into this...

**Comment by lykinsbd** [comment]
After looking at this in conversation with @ktbyers on Slack, I can confirm that EdgeOS is behaviorally similar to VyOS, and we'd need to have similar behavior as [listed in the VyOS class](https://github.com/ktbyers/netmiko/blob/98d0961adf1aefae45f1d83d84d63ef584b62b82/netmiko/vyos/vyos_ssh.py) where we don't attempt to Enable, etc.  The `#` prompt only appears in Configure mode (`configure`) and when sudo'ed to root (`sudo su`).

The [existing Ubiquiti child class](https://github.com/ktbyers/netmiko/blob/b04fcae4368ef9dea3ab5255507766cb2512b413/netmiko/ubiquiti/edge_ssh.py#L11) doesn't override the default actions around entering Enable mode as shown in the [parent Cisco Base Connection class](https://github.com/ktbyers/netmiko/blob/0ff5b22dc8227b57c471177de559ee5e2cd6d2c6/netmiko/cisco_base_connection.py#L11).

**Comment by jftuga** [comment]
I can confirm the prompt issue is now fixed. Thank you.

The next issue is that my script will hang after this:

    cmd = "configure"
    net_connect.send_command(cmd)

I believe this is because the prompt changes from '$' to '#' and netmiko is waiting for a '$' but will never get it.  How can I fix this?

      File "C:\Python35\lib\site-packages\netmiko\base_connection.py", line 815, in send_command
    search_pattern))
    OSError: Search pattern never detected in send_command_expect: ubnt\@ubnt\:\~\$

**Comment by lykinsbd** [comment]
@jftuga You don't want to send `configure` as a command, you need to use the other method on net_connect, `send_config_set`, to get into configuration mode, Example:

```
config_list = ['set interface ethernet eth1 blah']
net_connect.send_config_set(config_list)
```

If you just want to view config that's when you'd use `net_connect.send_command()`:

```
command_list = ['terminal length 9999','show configuration all']
net_connect.send_config_set(command_list)
```

If you use `send_config_set` it has handling for `$` vs `#` built in.

**Comment by jftuga** [comment]
Using `send_config_set ` work for me.  I am now able to output the config.

Thank you!

**Comment by sconrod-tester** [comment]
How can I drop into vshell with netmiko on viptela?
