### ISSUE TITLE
ValueError: Failed to enter enable mode

### ISSUE THREAD

**Issue by blbrown06** [ktbyers/netmiko#502]
I receive error "ValueError: Failed to enter enable mode" when "AAA new-model" is configured on the switch. When I remove AAA new-model from the config,  the script works great. Any ideas?

from netmiko import ConnectHandler

test = {
	'device_type' : 'cisco_ios',
	'ip' : '172.16.1.140',
	'username' : 'cisco',
	'password' : 'cisco'}

connect = ConnectHandler(**test)
config_cmds = ['interface g0/1','desc Python madnesss','speed auto']
connect.send_config_set(config_cmds)

connect.disconnect()

**Comment by ktbyers** [comment]
Can you enable logging for more information as to what happens:

```
    import logging
    logging.basicConfig(filename='test.log', level=logging.DEBUG)
    logger = logging.getLogger("netmiko")
```

This will create a file named test.log in you the current working directory.

**Comment by ktbyers** [comment]
No response on issue...closing.
