### ISSUE TITLE
Discussing about new huawei device.

### ISSUE THREAD

**Issue by fumeng2005** [ktbyers/netmiko#503]
I find the new huawei fiber switch: CE6850EI . The command is not completely similar with the existed huawei device in netmiko. 
You need to execute 'commit' to make your configuration effective. For example:
#
interface 10GE1/0/10
 port default vlan 14
 device transceiver 10GBASE-FIBER
#
return
[~HUAWEI-10GE1/0/10]
[~HUAWEI-10GE1/0/10]port default vlan 50
[*HUAWEI-10GE1/0/10]d th
#
interface 10GE1/0/10
 port default vlan 14
 device transceiver 10GBASE-FIBER
#
return
[*HUAWEI-10GE1/0/10]commit
[~HUAWEI-10GE1/0/10]d th
#
interface 10GE1/0/10
 port default vlan 50
 device transceiver 10GBASE-FIBER
#
return
[~HUAWEI-10GE1/0/10]
I am not sure whether it is suitable to add a new type of device named huawei_fiber in CLASS_MAPPER_BASE in ssh_dispatcher.py like 'huawei_fiber' : HuaweiSSH.

**Comment by fumeng2005** [comment]
https://review.openstack.org/#/c/473800/4/setup.cfg

**Comment by ktbyers** [comment]
@fumeng2005 Okay, someone will need to submit a PR to support this device.

**Comment by fumeng2005** [comment]
modify ssh_dispatcher.py:
CLASS_MAPPER_BASE = {
......
    'huawei': HuaweiSSH, # Huawei Network Operating System VRP V3 and V5
    'huawei_VRPV8': HuaweiSSH, # Huawei Network Operating System VRP V8.

**Comment by fumeng2005** [comment]
please help me to push it.

**Comment by fumeng2005** [comment]
I have no idea how to contribute to this project, I have no authority to git push my code. Is there any guidance to help me?Thank you.

**Comment by fumeng2005** [comment]
https://review.openstack.org/#/c/473800/5
Does someone help me to fix this problem?

**Comment by fumeng2005** [comment]
new device huawei_VRPV8 is necessary

**Comment by 191801737** [comment]
@fumeng2005  i recommend use ansible to configuration the huawei ce switch , ansible has power modules (cloudengine).
https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/network/cloudengine

**Comment by ktbyers** [comment]
@fumeng2005 Sorry for slow response. I have been slammed with work for the last month or so.

Here is an outline of the process:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md

Then you would create a pull request and submit it the project. If you have questions about contributing, you might want to ask them in the netmiko slack channel here 

https://networktocode.slack.com


You can sign-up for this slack here:

http://slack.networktocode.com/

**Comment by ktbyers** [comment]
Okay it sounds like this issue was fixed on the openstack side.
