### ISSUE TITLE
netmiko with VPN

### ISSUE THREAD

**Issue by elcolie** [ktbyers/netmiko#504]
Hi.<br>
I am now debugging the script. The environment is VPN therefore my ordinary `ssh` will be changed from `ssh root@202.111.xxx.yyy` to `ssh -b 10.134.5.5 root@202.111.xxx.yyy`

**Problem:**
The outgoing IP in my computer is not a VPN-IP. Then the target network device will not response to me and at my terminal receives an `ConnectionError` exception

**Question:**
How to set the source IP and make call to target network device?

**Comment by ktbyers** [comment]
@elcolie This doesn't sound like a Netmiko issue.

You can't set the source IP in Netmiko (although maybe you can in Paramiko).

You can do SSH Proxy in Netmiko.

It is possible I am not understanding your issue though?
