### ISSUE TITLE
Please include unit tests in the release tarballs

### ISSUE THREAD

**Issue by dtantsur** [ktbyers/netmiko#508]
When packaging a Python library, it's handy to run unit tests to make sure you've done everything right. However, the "tests" directory is not included in the tarball.

I'd recommend to move "tests" under the main package, by the way.

**Comment by ktbyers** [comment]
Can you expand on why `tests` should be under the main package? Looking online about 1/2 of people put them in main package; about half put them at base directory (outside main package).

Unit tests require real devices to test against and also require some amount of customization (i.e. defining real devices). Not seeing the value of including in the tar ball--can you expand on this?

**Comment by dtantsur** [comment]
> Can you expand on why tests should be under the main package?

It's not a requirements, just feels a bit more natural to me personally. Feel free to ignore.

> Unit tests require real devices to test against and also require some amount of customization (i.e. defining real devices).

Oh, I see. I assumed there is a test suite that can run by mocking hardware access. If it's not the case, then shipping them might not be useful indeed.

I'll leave it up to you whether to fix or close this request. Thanks!

**Comment by ktbyers** [comment]
@dtantsur Yes, no mock at the current time...some very high percentage of issues relate to timing/behavior of screen-scraping of real devices so haven't implemented mock.

It would probably be worthwhile to create some amount of mock (to make sure something basic didn't get broken by a change/PR) and also so I could integrate better in Travis-CI tooling (i.e. automatically do at least a sanity check on all changes).

I am going to close this...but the main item is I probably need to build a basic mock test (which I will open a separate issue on).

**Comment by ktbyers** [comment]
New issue for creating Mock tests:   https://github.com/ktbyers/netmiko/issues/509
