### ISSUE TITLE
Allow Key-Based Authentication

### ISSUE THREAD

**Issue by supertylerc** [ktbyers/netmiko#51]
Key-based SSH authentication can be highly desirable, particularly for automation.  In #1, though, it was explicitly and statically disabled.

I propose that this be parameterized with a sane default of disabling SSH keys.  I will be working on an implementation as I require this functionality for an upcoming project.  It will probably be poorly considered as it is strictly for demonstrative purposes, but I may submit a PR with that change within the next week.

**Comment by ktbyers** [comment]
I didn't test this, but I am pretty confident this change will work given the behavior I saw earlier with Paramiko and it attempting to use SSH keys. 

Let me know when you use it.

**Comment by ktbyers** [comment]
There is more that needs done to tie this into the establish_connection() calls

**Comment by ktbyers** [comment]
This should be done now. There is a use_keys parameter when you instantiate the class. It is False by default.
