### ISSUE TITLE
cisco ios-xr ValueError in Paramiko : p must be exactly 1024, 2048, or 3072 bits long

### ISSUE THREAD

**Issue by tee-lake** [ktbyers/netmiko#514]
Hi Ktbyers,

Looking forward to the best way to solve this error while connecting cisco ios-xr.  "ValueError: p must be exactly 1024, 2048, or 3072 bits long" from dsa.py. 

Code snippets shown below:

from netmiko import ConnectHandler
cisco_ios_xrv = {
    'device_type': 'cisco_xr',
    'ip':   '192.168.179.154',
    'username': 'cisco',
    'password': 'cisco'
}
net_connect = ConnectHandler(**cisco_ios_xrv)
output = net_connect.send_command('show ip int brief')
print(output) 

Debug output is shown below.

DEBUG:paramiko.transport:starting thread (client mode): 0x2eb5df0L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.1.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-2.0
INFO:paramiko.transport:Connected (version 2.0, client Cisco-2.0)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group1-sha1'] server key:[u'ssh-dss'] client encrypt:[u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'3des-cbc'] server encrypt:[u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'3des-cbc'] client mac:[u'hmac-md5', u'hmac-sha1'] server mac:[u'hmac-md5', u'hmac-sha1'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-md5
DEBUG:paramiko.transport:Compression agreed: none
ERROR:paramiko.transport:Unknown exception: p must be exactly 1024, 2048, or 3072 bits long
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\paramiko\transport.py", line 1778, in run
ERROR:paramiko.transport:    self.kex_engine.parse_next(ptype, m)
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\paramiko\kex_group1.py", line 75, in parse_next
ERROR:paramiko.transport:    return self._parse_kexdh_reply(m)
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\paramiko\kex_group1.py", line 111, in _parse_kexdh_reply
ERROR:paramiko.transport:    self.transport._verify_key(host_key, sig)
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\paramiko\transport.py", line 1626, in _verify_key
ERROR:paramiko.transport:    if not key.verify_ssh_sig(self.H, Message(sig)):
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\paramiko\dsskey.py", line 153, in verify_ssh_sig
ERROR:paramiko.transport:    ).public_key(backend=default_backend())
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 206, in public_key
ERROR:paramiko.transport:    return backend.load_dsa_public_numbers(self)
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\multibackend.py", line 201, in load_dsa_public_numbers
ERROR:paramiko.transport:    return b.load_dsa_public_numbers(numbers)
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 683, in load_dsa_public_numbers
ERROR:paramiko.transport:    dsa._check_dsa_parameters(numbers.parameter_numbers)
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 132, in _check_dsa_parameters
ERROR:paramiko.transport:    raise ValueError("p must be exactly 1024, 2048, or 3072 bits long")
ERROR:paramiko.transport:ValueError: p must be exactly 1024, 2048, or 3072 bits long
ERROR:paramiko.transport:

**Comment by ktbyers** [comment]
@tee-lake Can you re-generate your SSH key on the device and select one of the allowed values (1024, 2048, or 3072)?

**Comment by tee-lake** [comment]
Hi ktbyers,

Thanks. It worked.

**Comment by maycon-r** [comment]
Hi guys,

I have the same issue, but i cant  re-generate the my ssh-key because i have other things use this

I need use 

#crypto key generate dsa
How many bits in the modulus [1024]: 768

my router is a asr-9k.
Please any one help me.

**Comment by ktbyers** [comment]
Yes, I don't think there is any fix in the `Paramiko` (actually Python cryptography library). Consequently, are only solution is for you to generate a new key.

@maycon-r

**Comment by ktbyers** [comment]
Adding reference to TPLink fix that we implemented:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/tplink/tplink_jetstream.py#L146-L168
