### ISSUE TITLE
read_until_pattern & read_until_prompt

### ISSUE THREAD

**Issue by clatcho** [ktbyers/netmiko#515]
mission :: log into cisco devices, test connectivity using ping and trace

problem :: command after trace is causing timeout

i am sending a simple traceroute 

`trace vrf ABC 8.8.8.8 source vlan 10`

During the trace i hit a firewall, and then * * * , * * * * all the way to 30 hops, its this extra time that causing me issues.
 
I have tried lots, my current solution, which does not work is 

```
    def readUntilPrompt(self,command,max_loops=500):
        return self.connection.read_until_prompt(command)
```

thinking that i can simply read until prompt appears

```
Traceback (most recent call last):
  File "go.py", line 287, in <module>
    main()
  File "go.py", line 19, in main
    AAA_XXX_YYY_PRI()
  File "go.py", line 259, in AAA_XXX_YYY_PRI
    if '100.96.8.' in str(AAA_XXX_YYY_PRI.readUntilPrompt(AAA_XXX_YYY_PRI_traceroute[0])):
  File "/home/blah/core_checks/mods/core_c.py", line 59, in readUntilPrompt
    return self.connection.read_until_prompt(command)
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 262, in read_until_prompt
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 219, in _read_channel_expect
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```

but no, this just times out

if i dont include the MAX_LOOPS it lasts a bit longer. 

So i went on to use 

`read_until_pattern`

but from reading comments in base connection, it actually reads beyond the pattern 

?

**Comment by ktbyers** [comment]
@clatcho I would probably just use the `send_command_timing` method which basically will default to waiting a certain amount of time and then give up.

You can use `delay_factor` and `max_loops` to influence how long it waits. In general, the pattern is it waits a certain amount of time for the first data and then some amount of time after that.

```
net_connect.send_command_timing("traceroute 8.8.8.8")
```

If that doesn't work, I would probably try:

```
try:
    net_connect.send_command("traceroute 8.8.8.8")
except IOError:
    # catch error
    pass
```

And then use `max_loops` to influence how long I will wait. I think it will default to waiting about 90 seconds.

**Comment by clatcho** [comment]
ok, i can see by changing  delay_factor and/or max_loops i am getting different results.

i was hoping to accomplish something like this 

`read_until_pattern(*args, **kwargs)`

then call upon, for a Ctrl+Shift+6 then X)
```
    def escape(self):
        self.connection.send_command('\036')
        self.connection.send_command('x')
```

but, i was not able to get this to work.

**Comment by clatcho** [comment]
I got this working with below

```
    def command_sender_delayed(self,command,):
    	# send a command
    	the_command = self.connection.send_command_timing(command,delay_factor=3,max_loops=1000)
    	return str(the_command)
```

would have been good to use 

```
    def escape(self):
        self.connection.send_command('\036')
        self.connection.send_command('x')
```

so i dont have to wait for the command to finish.

**Comment by ktbyers** [comment]
Yes, you can send a break. You just have to do it manually in your code.
