### ISSUE TITLE
issue with saving running config to flash cisco ios

### ISSUE THREAD

**Issue by legionofdogg** [ktbyers/netmiko#519]
Hello,

I would like your assistance with helping me to save my running-config to flash. When I run this bit of code I continue to run into a road block where it looks like its looking for a new line to be entered. I have tried concatenating a carriage return in the "copy running config" command. What do you think the best method of saving my running config to flash is?

Cisco Switch Output:

rtr008mains01(config)#do copy running-configuration flash:170707_running
Destination filename [170707_running]? end
rtr008mains01#

Python Code:

import netmiko

title = str(170707)

connection = netmiko.ConnectHandler(ip = '10.11.12.1',
  device_type = 'cisco_ios', username = 'jordan', password = 'cisco')

print(connection.send_config_set('do copy running-configuration flash:' + title + '_running'))

**Comment by ktbyers** [comment]
Don't try to send this from config mode:

I would do something like this:

```
cmd = 'copy running-configuration flash:' + title + '_running'
output = connection.send_command_timing(cmd)
if 'Destination filename' in output:
    output += connection.send_command_timing('\n')
print(output)
```

**Comment by legionofdogg** [comment]
Thank you very much! I really appreciate your help with this. Hope you have a good weekend

**Comment by ktbyers** [comment]
@legionofdogg Can you post your program? Please use triple backticks \`\`\` to enclose your code (so that it doesn't get distorted by the markdown).

**Comment by legionofdogg** [comment]
'''
#!/usr/bin/env python

from __future__ import absolute_import, division, print_function

from getpass import getpass
import netmiko
import os
import sys


def get_input(prompt=''):
	try:
		line = raw_input(prompt)
	except NameError:
		line = input(prompt)
	return line


title = get_input('Name the file we are creating using YYMMDD: ')


devices = '''
10.11.12.1
10.11.12.2
'''.strip().splitlines()


def get_credentials():
	'''Prompts for and returns a username and password'''
	username = get_input('Enter username: ')
	password = None
	while not password:
		password = getpass()
		password_verify = getpass('Retype your password: ')
		if password != password_verify:
			print('Passwords do not match. Try again.')
			password = None
	return username, password

netmiko_exceptions = (netmiko.ssh_exception.NetMikoTimeoutException,
						netmiko.ssh_exception.NetMikoAuthenticationException)

username, password = get_credentials()


cmd = 'copy running-configuration flash:' + title + '_running'


for device in devices:
	try:
		print('~' * 79)
		print('Connecting to ', device)
		connection = netmiko.ConnectHandler(ip = device,
			device_type = 'cisco_ios', username = username, password = password)


		print(connection.send_command('show clock'))
		output = connection.send_command_timing(cmd)
		if 'Destination filename' in output:
    		output += connection.send_command_timing('\n')
		print(output)


	except netmiko_exceptions as e:
		print('Failed to', base, e)


		connection.disconnect()
'''

**Comment by ktbyers** [comment]
@legionofdogg Your indentation has an error here:

```
 59                 if 'Destination filename' in output:
 60                 output += connection.send_command_timing('\n')
 61                 print(output)
```

At least with what is posted above.

**Comment by 191801737** [comment]
@legionofdogg please try this code 

```
        cisco_ios = {
            'device_type': 'cisco_ios',
            'ip': ip,
            'username': username,
            'password': password,
        }
        net_connect = ConnectHandler(**cisco_ios)
        config_commands = ['end',
                           'write memory']
        output = net_connect.send_config_set(config_commands)
        net_connect.disconnect()
```

**Comment by ktbyers** [comment]
@191801737 Why? 

You shouldn't have either `end` or `write mem` in `send_config_set`. Netmiko will automatically exit config mode (so no need for end).

For `write mem`, use send_command() method for that.
