### ISSUE TITLE
Explain what delay_factor is for?

### ISSUE THREAD

**Issue by lamiskin** [ktbyers/netmiko#52]
Just wondering what the delay_factor in send_command() is for?

It seems to me it is a delay to wait for output from the device, before receiving it.

My issue lays with grabbing running configuration from Cisco gear - as it seems with a small delay factor all that is received is "Building configuration...\n". Some of the older Sup 720's etc with large configurations can take 40 seconds + to display the running configuration. 

Is there no way to wait till a command is processed, instead of a delay factor?

**Comment by supertylerc** [comment]
I think this was discussed during a recent meetup.  @ktbyers can probably speak more to it, but I believe the solution was to essentially balance out the timings yourself.  I think they can be overwritten (or that ability is on the roadmap).

**Comment by ktbyers** [comment]
delay_factor is used as a multiplication factor for timing delays. The send_command() method has some things where the delays are multiplied times this delay_factor. 

I know that there will be some devices that won't support the delays that I have used as the default so I wanted to give people the option of overriding them. So if it takes 40 seconds for the entire config to show, then I would probably try a delay_factor of 20 when doing 'show run'. This will delay 20 seconds before it enters a while loop and 20 seconds each time through the while loop. You will obviously have to experiment with this. 

I am thinking about adding a send_command_expect() method which would keep reading data until it gets the router prompt back. There would be some fail-safe timeout as well. If this would be helpful, let me know.

**Comment by ktbyers** [comment]
Let me know if this doesn't work for you (or this doesn't sufficiently clarify how this works).

**Comment by lamiskin** [comment]
Submitted a PR for proposed new method send_command_expect().

**Comment by rishabh5j** [comment]
> Submitted a PR for proposed new method send_command_expect().

Does it work for all supported hardware? Also can you confirm, send_command_expect() will wait for the router prompt back and till that is received, buffer would keep receiving the output?

**Comment by ktbyers** [comment]
@rishabh5j This is a really old thread closed 3+ years ago.

Here are some details on how send_command and delay_factor work:

https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html


Note, send_command and send_command_expect are the same thing.

Yes send_command should wait for the either the router prompt to be returned or for the timeout. The timeout (by default) is very long i.e. it is on the order of 100 seconds.
