### ISSUE TITLE
NetMikoAuthenticationException: Telnet login failed: 10.X.X.17

### ISSUE THREAD

**Issue by bboylord** [ktbyers/netmiko#520]
Hi, How are you, if you can give a view to this error that is presented to me with some devices, I would appreciate it.

It happens when I internally connect by Telnet to some devices in my network.

Code:

```
def telnet(IP_Switch,user,pa):
    os.system('cls')
    print "Wait try to connect"
    cisco_ios ={'device_type':'cisco_ios_telnet','ip':IP_Switch,'username': user,'password': pa,'verbose': False,'global_delay_factor': 2}
    net_connect = ConnectHandler(**cisco_ios)
    print ("Connect " +  IP_Switch + " by  Telnet " )
    #print net_connect.find_prompt()
    output = net_connect.send_command("Show users")

def main():
    IP_Switch = "192.168.7.17"
    user = "usersss"
    pa = "Pass123"
    telnet(IP_Switch,user,pa)
main()
```

Wait try to connect

---------------------------------------------------------------------------
NetMikoAuthenticationException            Traceback (most recent call last)<ipython-input-12-1643641f63b5> in <module>()
     13     pa = "Pass123"
     14     telnet(IP_Switch,user,pa)
---> 15 main()
     16 

<ipython-input-12-1643641f63b5> in main()
     12     user = "usersss"
     13     pa = "Pass123"
---> 14     telnet(IP_Switch,user,pa)
     15 main()
     16 

<ipython-input-12-1643641f63b5> in telnet(IP_Switch, user, pa)
      3     print "Wait try to connect"
      4     cisco_ios ={'device_type':'cisco_ios_telnet','ip':IP_Switch,'username': user,'password': pa,'verbose': False,'global_delay_factor': 2}
----> 5     net_connect = ConnectHandler(**cisco_ios)
      6     print ("Connect " +  IP_Switch + " by  Telnet " )
      7     #print net_connect.find_prompt()

C:\Program Files\Anaconda2\lib\site-packages\netmiko\ssh_dispatcher.pyc in ConnectHandler(*args, **kwargs)
     98                          'currently supported platforms are: {0}'.format(platforms_str))
     99     ConnectionClass = ssh_dispatcher(kwargs['device_type'])
--> 100     return ConnectionClass(*args, **kwargs)
    101 
    102 

C:\Program Files\Anaconda2\lib\site-packages\netmiko\base_connection.pyc in __init__(self, ip, host, username, password, secret, port, device_type, verbose, global_delay_factor, use_keys, key_file, allow_agent, ssh_strict, system_host_keys, alt_host_keys, alt_key_file, ssh_config_file, timeout)
    121         if '_telnet' in device_type:
    122             self.protocol = 'telnet'
--> 123             self.establish_connection()
    124             self.session_preparation()
    125         else:

C:\Program Files\Anaconda2\lib\site-packages\netmiko\base_connection.pyc in establish_connection(self, width, height)
    453         if self.protocol == 'telnet':
    454             self.remote_conn = telnetlib.Telnet(self.host, port=self.port, timeout=self.timeout)
--> 455             self.telnet_login()
    456         elif self.protocol == 'ssh':
    457 

C:\Program Files\Anaconda2\lib\site-packages\netmiko\base_connection.pyc in telnet_login(self, pri_prompt_terminator, alt_prompt_terminator, delay_factor, max_loops)
    352             except EOFError:
    353                 msg = "Telnet login failed: {0}".format(self.host)
--> 354                 raise NetMikoAuthenticationException(msg)
    355 
    356         # Last try to see if we already logged in

NetMikoAuthenticationException: Telnet login failed: 192.168.7.17

can you help me with give me some idea about the issue.?

**Comment by ktbyers** [comment]
@bboylord Try enabling logging and see if that gives you more information:

```
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
```

**Comment by grockin50** [comment]
I'm having similar issues with Telnet. Doesn't appear to be detecting the prompt after successful login.

[netmiko telnet issue.txt](https://github.com/ktbyers/netmiko/files/1194473/netmiko.telnet.issue.txt)

**Comment by ktbyers** [comment]
@grockin2500 Is that a single switch or two switches.

This switch was connected and command executed.
```
someswitch-distribution#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: show ip arp 3440.b5ab.18d8 | exclude ^Protocol

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: show ip arp 3440.b5ab.18d8 | exclude ^Protocol


DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: Internet  10.170.186.88           0   3440.b5ab.18d8  ARPA   Vlan186

```

What issue are you seeing (i.e. what exception do you get)?

**Comment by grockin2500** [comment]
Thanks for the quick reply.  I should have been more detailed in my initial comment.

My script attempts to login with tacacs+ creds first before falling back to local credentials with message "Telnet login failed: 10.x.x.x". From the debug, it was able to login successfully with the tacacs and issue commands before disconnecting and trying local creds, which worked.

`Username:
DEBUG:netmiko:write_channel: aaa_username


DEBUG:netmiko:read_channel: aaa_username

Password:
DEBUG:netmiko:write_channel: aaa_password


DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 


DEBUG:netmiko:read_channel: 



someswitch-distribution#

someswitch-distribution#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 

someswitch-distribution#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 

someswitch-distribution#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: terminal length 0

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: terminal length 0


DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: someswitch-distribution#
DEBUG:netmiko:write_channel: terminal width 511

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: terminal width 511


DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: someswitch-distribution#
`
I get the message:
Telnet login failed: 10.x.x.x

**Comment by ktbyers** [comment]
@grockin2500 Can you post your script and the error you get running it.
