### ISSUE TITLE
extreme switch no enable mode

### ISSUE THREAD

**Issue by lidewu** [ktbyers/netmiko#521]
@extreme_ssh.py

> 
> `def session_preparation(self):`
>         `"""Extreme requires enable mode to disable paging."""`
>         `self._test_channel_read()`
>         `#self.enable()`
>         `self.set_base_prompt()`
>         `self.disable_paging(command="disable clipaging\n")`

I modified it and connect to extreme switch as well.

**Comment by ktbyers** [comment]
@lidewu Does the `enable()` call cause an issue? 

I would have expected it to think it was already in enable mode and not cause any negative effects (although probably not needed)?

**Comment by lidewu** [comment]
@ktbyers  My Switch is summit series. X430 OS version is 16.2.3.5.
Here was got  an error which was enable self.enable().

<img width="1564" alt="2017-08-15 00 44 05" src="https://user-images.githubusercontent.com/6071871/29282059-f2f50536-8153-11e7-888f-a0c112591d42.png">

So, command out of self.enable() than connect well.

**Comment by ktbyers** [comment]
@lidewu Okay, I will fix and remove that. I think it was not needed (so if it also breaking something then I will eliminate).

**Comment by ktbyers** [comment]
Okay, should be fixed here:

https://github.com/ktbyers/netmiko/commit/93849158eb4f1c3cc7756ff5614b9ff0efe1c17f

I removed enable() call from `session_preparation`. This also corrected a similar issue on Extreme.

It would be good if someone could check if this fixes the issue and that both `send_command()` and `send_config_set` methods work properly on Enterasys and Extreme.
