### ISSUE TITLE
bug: Cisco ASA terminal width

### ISSUE THREAD

**Issue by Rosiak** [ktbyers/netmiko#522]
Hi there,

Netmiko tries to set the terminal width, but fails, as "terminal width" can only be set in Global configuration, whereas "terminal pager" can be set in Privileged EXEC.

This results in the following error for the "terminal width" command:
ERROR: % Invalid input detected at '^' marker

Ref:
http://www.cisco.com/c/en/us/td/docs/security/asa/asa-command-reference/T-Z/cmdref4/t1.html#pgfId-1640149

**Comment by ktbyers** [comment]
@Rosiak Yes, we need to fix that.

Closing this issue as it is a duplicate of this one:

https://github.com/ktbyers/netmiko/issues/281
