### ISSUE TITLE
support for (multiple) jump hosts argument without config file

### ISSUE THREAD

**Issue by 1-61803** [ktbyers/netmiko#525]
Could you add such a feature? Possibly defining an argument locally for single devices and globally for all connections opened by a script.

`'jumphost' : 'ssh -q -J user1@jumphost1,user2@jumphost2,user3@jumphost3 user@server'`

NB [This tutorial](https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html) doesn't mention it, but for multiple jump hosts `OpenSSH` supports `-J` or `ProxyJump` since version `7.3`.

**Comment by ktbyers** [comment]
You can see if there is a way to do it via Paramiko. 

If there is a way to do it via Paramiko, I might be open to it.

Netmiko uses Paramiko for its underlying SSH library.

**Comment by 1-61803** [comment]
I couldn't find a way following the documentation, so I opened [#1018](https://github.com/paramiko/paramiko/issues/1018). I don't think you can circumvent 1 or 2 jump hosts in most organizations, and as soon as you move away from the office network it just adds up.

**Comment by ktbyers** [comment]
Depends on your environment, I would say VPNs are probably more common than Jump hosts, but it really depends.

Why not just SSH config and embed them in there? That is the standard solution to this problem.

**Comment by 1-61803** [comment]
I know there are [other methods](https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts#Old_Methods_of_Passing_Through_Jump_Hosts), but I rather have this config inline with the node definition, or globally in the script, instead of tied to a host file.

**Comment by ktbyers** [comment]
Yes, this is just something I won't implement in Netmiko (it is too much of an edge case) and it probably is not supported by Paramiko.

**Comment by 1-61803** [comment]
I don't think it's an edge case and such parameters shouldn't depend on a host's config file.

`Paramiko` does support it, please see [this comment](https://github.com/paramiko/paramiko/issues/1018#issuecomment-316483867) from its developer for a reference.

**Comment by ktbyers** [comment]
...interesting on Paramiko. I read that as more that Fabric supports it and you can build it using Paramiko (i.e. it could be implemented, but you would have to reverse engineer what Fabric did).

You can implement this in a separate SSH config file (i.e. you can decouple from ~/.ssh/config). The ConnectHandler argument is `ssh_config_file=/path/to/file`. So I am not understanding the issue (i.e. why do you care if you have to specify the arguments in a file versus directly in your code)?

If you want to you can have your Python write the file or even possibly write an in-memory file and read the config from there?

**Comment by 1-61803** [comment]
I mentioned `ProxyJump` as an enhancement to `netmiko`. In my experience, I had 1 or 2 jump hosts at the very least and end nodes reachable through different jump hosts. Of course, I could work around this like you propose, but that's not very elegant code-wise. In case you change your mind, you can always ask `fabric`'s developer who also happen to be `paramiko`'s.

**Comment by 1-61803** [comment]
I don't know what you mean by "in-memory file", given the `ConnectHandler` argument is `ssh_config_file=/path/to/file` and won't accept the content of such a config file as a plain string — I'm thinking of [StringIO](https://docs.python.org/3/library/io.html?highlight=stringio#io.StringIO).
I could use [tempfile](https://docs.python.org/3/library/tempfile.html), but if `ssh_config_file` would also accept a string for the ssh config parameters itself, that would suffice.

**Comment by ktbyers** [comment]
Yes, I was thinking of `StringIO` or something similar. Yeah, you're right that won't work given how Netmiko handles this.

You would probably need to create a new class that inherits from Netmiko and then overwrite the _use_ssh_config() method. That might work.
