### ISSUE TITLE
Add NetMiko to PIP

### ISSUE THREAD

**Issue by supertylerc** [ktbyers/netmiko#53]
Pip is generally the default ecosystem for installing Python modules.  Putting NetMiko in pip could make it easier/more familiar to install and update NetMiko for end users.

**Comment by coxley** [comment]
+1

**Comment by lamiskin** [comment]
+1

**Comment by ktbyers** [comment]
@lamiskin Working on it...there are some issues that I want to fix with IOS-XR code and commits before I do this, however.

**Comment by rbenigno** [comment]
+1

**Comment by ktbyers** [comment]
Yeah, I need to get this done....

**Comment by ktbyers** [comment]
Finally uploaded to pypi -- :-)

**Comment by anash28** [comment]
@ktbyers Omg this is so cool!
