### ISSUE TITLE
Not able to SSH to Extreme Device

### ISSUE THREAD

**Issue by Ayushrimoh** [ktbyers/netmiko#535]
Could you help me with the below issue. Thanks for the help in advance.

>>> net_connect = ConnectHandler(device_type='extreme',ip='10.241.50.171',username='***',password='<***>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 150, in __init__
    self.establish_connection()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 506, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: extreme 10.241.50.171:22

I am able to ssh the ip.

**Comment by ktbyers** [comment]
@Ayushrimoh Try turning on logging and see if that gives you more clues as to what happened?

See here for details on enabling logging.
https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

What kind of Extreme device is it?

**Comment by Ayushrimoh** [comment]
It is a : 
System Type:      BD-X8
Image   : ExtremeXOS version 15.7.2.9

**Comment by Ayushrimoh** [comment]
Hi Kirk,

FYI, I am not able to SSH the device using PUTTY. I need to use some other
tool like a bastion host to SSH the device. Could that be causing any issue.

Also do you have any idea about Pexpect library?

Thanks and regards,
Ayush

**Comment by ktbyers** [comment]
@Ayushrimoh Here is how to SSH proxy with Netmiko

https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

With a modification here:

https://github.com/ktbyers/netmiko/releases/tag/v1.4.0
