### ISSUE TITLE
Getting error while getting output from Cisco router net_connect.send_commad("sh ip int br")

### ISSUE THREAD

**Issue by kvishu17** [ktbyers/netmiko#539]
I am getting output error below for net_connect.send_commad("sh ip int br")
>>> net_connect = ConnectHandler(**cisco_881)
>>>
>>>
>>> net_connect.find_prompt()
'Infi_Lab_RTR2800#'
>>> output = net_connect.send_commad("sh ip int br")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'CiscoIosBase' object has no attribute 'send_commad'

**Comment by 191801737** [comment]
@kvishu17 you can try this 
```
from netmiko import ConnectHandler
cisco_881 = {
    'device_type': 'cisco_ios',
    'ip':   '10.10.10.10',
    'username': 'test',
    'password': 'password',
    'port' : 8022,          # optional, defaults to 22
    'secret': 'secret',     # optional, defaults to ''
    'verbose': False,       # optional, defaults to False
}
net_connect = ConnectHandler(**cisco_881)
output = net_connect.send_command('show ip int brief')
print(output)
```

**Comment by ktbyers** [comment]
@kvishu17 Yes, just looks like you have a typo (i.e. it needs to be `send_command` not send_commad.

**Comment by kvishu17** [comment]
Yes...I got mistake...Thanks for help.
