### ISSUE TITLE
super mode - comware

### ISSUE THREAD

**Issue by s1405** [ktbyers/netmiko#542]
hi, I tried both the enable method with a value for the secret key in the dictionary mode, and the send_command method passing 'super' as the argument, seems not getting past.

**Comment by ktbyers** [comment]
@s1405 Can you show me what you are trying to do from the CLI (i.e. post the CLI behavior here)?

**Comment by s1405** [comment]
>>> s
{'username': 'admin', 'ip': '192.168.56.11', 'secret': 'sooper', 'password': 'manage', 'device_type': 'hp_comware'}

>>> c = ConnectHandler(**s)

>>> c.enable()
u'system-view\r\r\nSystem View: return to User View with Ctrl+Z.\r\r\n[sw1]'
# this isn't going to the enable/super mode, instead it gets into the config/sys mode

>>> c.exit_enable_mode()
u'return\r\r\n<sw1>'

>>> c.send_command('super')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 811, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: \<sw1\>

>>> c.send_command_expect('sup')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 819, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 811, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: \<sw1\>


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by s1405** [comment]
>> s
{'username': 'admin', 'ip': '192.168.56.11', 'secret': 'sooper', 'password': 'manage', 'device_type': 'hp_comware'}
>> c = ConnectHandler(**s)
>> c.enable()
u'system-view\r\r\nSystem View: return to User View with Ctrl+Z.\r\r\n[sw1]'
# this isn't going to the enable/super mode, instead it gets into the config/sys mode
>> c.exit_enable_mode()
u'return\r\r\n<sw1>'
>> c.send_command('super')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 811, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: \<sw1\>
>> c.send_command_expect('sup')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 819, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 811, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: \<sw1\>

**Comment by s1405** [comment]
>> s
{'username': 'admin', 'ip': '192.168.56.11', 'secret': 'sooper', 'password': 'manage', 'device_type': 'hp_comware'}
>> c = ConnectHandler(**s)
>> c.enable()
u'system-view\r\r\nSystem View: return to User View with Ctrl+Z.\r\r\n[sw1]'
# this isn't going to the enable/super mode, instead it gets into the config/sys mode
>> c.exit_enable_mode()
u'return\r\r\n<sw1>'
>> c.send_command('super')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 811, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: \<sw1\>
>> c.send_command_expect('sup')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 819, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 811, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: \<sw1\>

**Comment by s1405** [comment]
o1=c1.send_command('sup\npassword\n')... it worked via this. but I think it would be more relevant to get that worked through the enable method. as of now both enable and config_mode lead to the same place

**Comment by ktbyers** [comment]
@s1405 Can you show me what this looks like manually when you SSH in and do it from the CLI?  

It is much easier for me to understand the behavior/problem this way.

**Comment by s1405** [comment]
@ktbyers 

here is a sample output from the cli

--

<sw1>sup
Password:

--

# levels 0 to 15 possible

<sw1>super level-3
Password:
User privilege role is level-3, and only those commands that authorized to the role can be used.
User privilege role is network-admin, and only those commands that authorized to the role can be used.
<sw1>

--

we only type "quit" to get out of this mode

**Comment by nmweizi** [comment]
Huawei device also has this problem.
Recommended implementation.
Suggest:

def enable(self, *args, **kwargs):
        """Huawei has no enable mode."""
 return super(HuaweiSSH, self).enable(check_string='super')

or 

send_command_timing('super')
send_command(secret)

But huawei did not provide the function after the super successfully detected

**Comment by ktbyers** [comment]
@nmweizi Okay, I will try to look into this. It will probably be late September of October before I get to it though.

**Comment by nmweizi** [comment]
sorry，
cmd='super'
not check_string='super'

**Comment by rsg7** [comment]
I have very old huawei devices with 'super' as enable mode. More over this devices has only telnet access.
I could not find telnet support for huawei in netmiko, but hp_comware has it.

I done some ugly modification in hp_comware.py, for support 'super' mode and 'save' command for huawei.

Unfortunately huawei does not change CLI while enter to super mode. My idea is call command 'super 3',
and if device ask me password, that mean my current mode is not 'super'.

Also some modification done at save_config method. Huawei have no command 'save force'. After 'save' command you need say 'YES'.

May be my code will useful for some  marginals like me. ;)

One more things, without entering in super mode I could not do session preparation (like switch off paging etc.).

```
--- hp_comware_original.py	2019-03-31 14:02:14.427926100 +0300
+++ hp_comware.py	2019-03-31 14:19:21.020368100 +0300
@@ -2,9 +2,10 @@
 from __future__ import unicode_literals
 import time
 from netmiko.cisco_base_connection import CiscoSSHConnection
-
+import re
 
 class HPComwareBase(CiscoSSHConnection):
+
     def session_preparation(self):
         """
         Prepare the session after the connection has been established.
 
@@ -68,21 +67,60 @@
         self.base_prompt = prompt
         return self.base_prompt
 
-    def enable(self, cmd="system-view"):
-        """enable mode on Comware is system-view."""
-        return self.config_mode(config_command=cmd)
+    def enable(self, cmd='super 3'):
+        """enable mode on Comware is super 3."""
+        super(HPComwareBase, self).enable(cmd=cmd)
+        self.session_preparation()
+        return True
 
-    def exit_enable_mode(self, exit_command="return"):
+    def exit_enable_mode(self, exit_command='return'):
         """enable mode on Comware is system-view."""
         return self.exit_config_mode(exit_config=exit_command)
 
-    def check_enable_mode(self, check_string="]"):
-        """enable mode on Comware is system-view."""
-        return self.check_config_mode(check_string=check_string)
+    def check_enable_mode(self, check_string=']',pattern='assword'):
+        """enable mode on Comware is super 3."""
+        self.write_channel(self.normalize_cmd('super 3\n'))
+        try:
+            output=self.read_until_prompt_or_pattern(pattern=pattern)
+            if re.search(pattern,output):
+
+                for i in range(3):
+                    self.write_channel(self.normalize_cmd('\n'))
+                    output=self.read_until_prompt_or_pattern(pattern=pattern)
+
+                self.write_channel(self.normalize_cmd('\n'))
+                output=self.read_until_prompt()
+                return False
+            else:
+                return True
+        except NetMikoTimeoutException:
+            raise ValueError('Failed to check enable mode.')
 
-    def save_config(self, cmd="save force", confirm=False):
+    def save_config(self, cmd='save', confirm=False, confirm_pattern='Are you sure to continue'):
         """Save Config."""
-        return super(HPComwareBase, self).save_config(cmd=cmd, confirm=confirm)
+        if not confirm:
+            cmd +=' force'
+            return super(HPComwareBase, self).save_config(cmd=cmd, confirm=confirm)
+        else:
+           """
+           Save command at HUAWEI look like:
+
+           <75061_SWITCH_01>save
+           The current configuration will be written to the device.
+           Are you sure to continue?[Y/N]Y
+
+           """
+           self.write_channel(self.normalize_cmd(cmd))
+           try:
+               output=self.read_until_prompt_or_pattern(pattern=confirm_pattern)
+               if re.search(confirm_pattern,output):
+                   self.write_channel(self.normalize_cmd('Y'))
+                   self.read_until_prompt()
+                   return True
+           except NetMikoTimeoutException:
+               raise ValueError('Failed to enter enable mode.')
+               return False
 
 
 class HPComwareSSH(HPComwareBase):
```

**Comment by carlniger** [comment]
@rsg7 Huawei telnet support was recently added so feel free to check that out. Going to close this as its quite old.
