### ISSUE TITLE
Need help netmiko - Failed log to login

### ISSUE THREAD

**Issue by vantruongsinh** [ktbyers/netmiko#543]
Hi All,
I am new to Netmiko. I have to develop the script to push config to the switch and router.
The weird thing about my script is sometimes it works fine, sometimes it had errors and rerun exactly the same script and it works. I also add the 'global_delay_factor': 2 in the ConnectHandler. All devices are Cisco routers/switches

Let's say my script named scriptX.py. I am using raw_input to input name of router I need to config.
I am not using multi thread or multi process at all. Just when I got a call do it for site A, I ran the script for site A: 
Open cmd
python scriptX.py
input router: siteA_router_name

then if site B, I do exactly same thing open another cmd... just input different router name.
And the scriptX is running parallel. Is that OK to do that or it will cause some issues?
One more thing is siteA is totally independent of siteB.

I know it is a general question but I would love to provide more information if you need to clarify.

```
def connection_create_ssh(current_IP_address, username, password):
    cisco = {
        'device_type' : 'cisco_ios',
        'ip' : current_IP_address,
        'username': username,
        'password': password,
        'global_delay_factor': 2,
    }
    connect = ConnectHandler(**cisco)
    return connect
```

the method I used is send_config_set
Most likely I have some problem with login. There are more but I just remember some of those
eg :
No existing session
Unable to find prompt: 
Error reading SSH protocol banner[Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by ktbyers** [comment]
@vantruongsinh Can you provide the stack trace of a specific failure?

**Comment by vantruongsinh** [comment]
@ktbyers Can you tell me exactly code that I need to add :) 
Thanks

**Comment by ktbyers** [comment]
@vantruongsinh Can you show me exactly what happens when you try to execute your code (i.e. the messages that appear on your screen).

**Comment by vantruongsinh** [comment]
Hi @ktbyers,
I have added the exception of NetMikoTimeoutException and NetMikoAuthenticationException to handle the normal error.

Other errors I just put it into Exception in general and print them to the screen to understand what wrong with it.

```
complete = False
        while not complete:
            try:
                   #Connect and Push config
            except NetMikoTimeoutException:
                print "Host unreachable"
            except NetMikoAuthenticationException:
                print "Authentication Error"
                print "Login using username:" + username
            except Exception as e:
                print "RUN INTO ERROR "
                error_log(device + " - " + str(commands) )
                error_log("Error: " + str(e))
                answer = ""
                answer = raw_input("Do you want to re run the step ? (y/Other)")
                if answer != "y" :
                    complete = True 
``` 
As I said, sometimes the code works, sometimes not. Just rerun the step and it will pass.

I am not sure about how I can save the log to record what happened with the code.
Can you suggest any way to log the error so I can provide it to you to have a look?

**Comment by ktbyers** [comment]
Also it is probably helpful to get rid of this (at least for testing)

```
            except Exception as e:
                print "RUN INTO ERROR "
                print device + " - " + str(commands) 
                print "Error: " + str(e)
                answer = ""
                answer = raw_input("Do you want to re run the step ? (y/Other)")
                if answer != "y" :
                    complete = True 
```

i.e. comment that out and just let your program crash so that it generates the stack trace when it fails.

**Comment by vantruongsinh** [comment]
I am able to log in normal in the router CISCO2911 using ssh.

```
Traceback (most recent call last):
  File "fix_error.py", line 135, in <module>
    main()
  File "fix_error.py", line 124, in main
    test_store(store, username_so, password_so)
  File "fix_error.py", line 77, in test_store
    connnection = connection_create_ssh(router, username_so, password_so)
  File "fix_error.py", line 35, in connection_create_ssh
    connect = ConnectHandler(**cisco)
  File "C:\Python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 151, in __init__
    self.session_preparation()
  File "C:\Python27\lib\site-packages\netmiko\cisco\cisco_ios.py", line 11, in session_preparation
    self.set_base_prompt()
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 645, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 657, in find_prompt
    self.write_channel("\n")
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 218, in write_channel
    self._write_channel(out_data)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 207, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data))
  File "C:\Python27\lib\site-packages\paramiko\channel.py", line 831, in sendall
    sent = self.send(s)
  File "C:\Python27\lib\site-packages\paramiko\channel.py", line 785, in send
    return self._send(s, m)
  File "C:\Python27\lib\site-packages\paramiko\channel.py", line 1169, in _send
    raise socket.error('Socket is closed')
socket.error: Socket is closed
```

Log from logging:

> DEBUG:paramiko.transport:starting thread (client mode): 0x6040970L
> DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.2.1
> DEBUG:paramiko.transport:Remote version/idstring: SSH-1.99-Cisco-1.25
> INFO:paramiko.transport:Connected (version 1.99, client Cisco-1.25)
> DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
> DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
> DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
> DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
> DEBUG:paramiko.transport:MAC agreed: hmac-sha1
> DEBUG:paramiko.transport:Compression agreed: none
> DEBUG:paramiko.transport:Got server p (2048 bits)
> DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
> DEBUG:paramiko.transport:Switch to new keys ...
> DEBUG:paramiko.transport:Adding ssh-rsa host key for on7204ar101: c91dd8224d58e02e8efb6ca74fc9d830
> DEBUG:paramiko.transport:userauth is OK
> INFO:paramiko.transport:Auth banner: 
> 
> #===============================================================================#
> 
> #                   >>   UNAUTHORIZED ACCESS PROHIBITED   <<                    #
> 
> #                     THIS IS A MONITORED NETWORK RESOURCE                      #
> 
> #===============================================================================#
> #                            Authorised Access Only                             #
> #===============================================================================#
> 
> #                        >>   Security  Disclaimer   <<                         #
> 
> #===============================================================================#
> 
> #  Unauthorized access, unauthorized attempted access, or unauthorized use of   #
> 
> #  this device is not permitted and may be subject to prosecution.  Individuals #
> 
> #  using this system without authority, or in excess of their authority, are    #
> 
> #  subject to having their activities on this system monitored and recorded by  #
> 
> #  system personnel. In the course of system maintenance, troubleshooting or    #
> 
> #  security investigations, the activities of authorized users may also be      #
> 
> #  logged. Anyone using this system expressly consents to such monitoring and   #
> 
> #  is advised that if such monitoring reveals possible evidence of criminal     #
> 
> #  activity, legal action may be taken.                                         #
> #================================================================================
> 
> 
> INFO:paramiko.transport:Authentication (password) successful!
> DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
> DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
> DEBUG:paramiko.transport:Secsh channel 0 opened.
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:[chan 0] EOF received (0)
> DEBUG:paramiko.transport:[chan 0] EOF sent (0)
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: % Authorization failed.
> 
> 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:netmiko:read_channel: 
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:paramiko.transport:EOF in transport thread
> DEBUG:paramiko.transport:EOF in transport thread

**Comment by ktbyers** [comment]
@vantruongsinh What does an SSH session look like if you login manually (please show the entire login process until you have the router prompt).

You can hide any confidential information like passwords.

**Comment by vantruongsinh** [comment]
Hi @ktbyers 
I stripped out some line in the banner in the comment above.

```
[c:\~]$ ssh on7204ar101
Host 'on7204ar101' resolved to 10.78.45.254.
Connecting to 10.78.45.254:22...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.

#===============================================================================#
#                   >>   UNAUTHORIZED ACCESS PROHIBITED   <<                    #
#                     THIS IS A MONITORED NETWORK RESOURCE                      #
#===============================================================================#
#                            Authorised Access Only                             #
#                            HOSTNAME:  on7204ar101                             #
#===============================================================================#
#                        >>   Security  Disclaimer   <<                         #
#===============================================================================#
#  Unauthorized access, unauthorized attempted access, or unauthorized use of   #
#  this device is not permitted and may be subject to prosecution.  Individuals #
#  using this system without authority, or in excess of their authority, are    #
#  subject to having their activities on this system monitored and recorded by  #
#  system personnel. In the course of system maintenance, troubleshooting or    #
#  security investigations, the activities of authorized users may also be      #
#  logged. Anyone using this system expressly consents to such monitoring and   #
#  is advised that if such monitoring reveals possible evidence of criminal     #
#  activity, legal action may be taken.                                         #
#================================================================================
#            Emergency Support Contact:  1300 136 364 or 03 8575 1304           #
#                          After hours:  +61 3 85751222                         #
#================================================================================


on7204ar101#
on7204ar101#
on7204ar101#
```

**Comment by ktbyers** [comment]
Are you using SSH keys?

I don't see any username / password prompts in this output?

**Comment by vantruongsinh** [comment]
@ktbyers sorry forgot to mention that I am using Windows and the software that I am using is Xshell. It has window popup to ask for my password. That's why it is not displayed here.
The below output from Putty

```
login as: sonssv1

#===============================================================================                                                                                                                                                             #
#                   >>   UNAUTHORIZED ACCESS PROHIBITED   <<                                                                                                                                                                                 #
#                     THIS IS A MONITORED NETWORK RESOURCE                                                                                                                                                                                   #
#===============================================================================                                                                                                                                                             #
#                            Authorised Access Only                                                                                                                                                                                          #
#                            HOSTNAME:  on7204ar101                                                                                                                                                                                          #
#===============================================================================                                                                                                                                                             #
#                        >>   Security  Disclaimer   <<                                                                                                                                                                                      #
#===============================================================================                                                                                                                                                             #
#  Unauthorized access, unauthorized attempted access, or unauthorized use of                                                                                                                                                                #
#  this device is not permitted and may be subject to prosecution.  Individuals                                                                                                                                                              #
#  using this system without authority, or in excess of their authority, are                                                                                                                                                                 #
#  subject to having their activities on this system monitored and recorded by                                                                                                                                                               #
#  system personnel. In the course of system maintenance, troubleshooting or                                                                                                                                                                 #
#  security investigations, the activities of authorized users may also be                                                                                                                                                                   #
#  logged. Anyone using this system expressly consents to such monitoring and                                                                                                                                                                #
#  is advised that if such monitoring reveals possible evidence of criminal                                                                                                                                                                  #
#  activity, legal action may be taken.                                                                                                                                                                                                      #
#===============================================================================                                                                                                                                                             =
#            Emergency Support Contact:  1300 136 364 or 03 8575 1304                                                                                                                                                                        #
#                          After hours:  +61 3 85751222                                                                                                                                                                                      #
#===============================================================================                                                                                                                                                             =
Using keyboard-interactive authentication.
Password:

on7204ar101#
on7204ar101#

```

**Comment by hydandata** [comment]
@ktbyers I am hitting a similar issue on ASA, but the issue seems to be in https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L970-L991

The problem in my case is that the banner displayed when connecting is multi-page, it has `<--- More --->` in it. 

Since this happens before `disable_paging` can run, netmiko/paramiko bails.

**Comment by ktbyers** [comment]
@hydandata You should open a separate issue, this issue is old and not active any longer.

I am going to close this issue...you should open a separate issue.
