### ISSUE TITLE
Netmiko and python

### ISSUE THREAD

**Issue by amangoel6** [ktbyers/netmiko#545]
Hi I am using Netmiko and pyhton to get clock and version of ASA, router and a switch.
Below is the error that I a getting. Any help will be appreciated.

Traceback (most recent call last):
  File "cmdrunner.py", line 40, in <module>
    print(connection.send_command(command))
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 811, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: LABASA\#

**Comment by amangoel6** [comment]
Below is my script that I copied from one of your vedios

#!/usr/bin/env python

from __future__ import absolute_import, division, print_function

import time
import json
import netmiko
import mytools
import signal
import sys

# signal.signal(signal.SIGPIPE, signal.SIG_DFL)  # IOError: Broken pipe
# signal.signal(signal.SIGINT, signal.SIG_DFL)  # KeyboardInterrupt: Ctrl-C


if len(sys.argv) < 3:
    print('Usage: cmdrunner.py commands.txt devices.json')
    exit()

netmiko_exceptions = (netmiko.ssh_exception.NetMikoTimeoutException,
                      netmiko.ssh_exception.NetMikoAuthenticationException)

username, password = mytools.get_credentials()

with open(sys.argv[1]) as cmd_file:
    commands = cmd_file.readlines()

with open(sys.argv[2]) as dev_file:
     devices = json.load(dev_file)

for device in devices:
    device['username'] = username
    device['password'] = password
    try:
        print('~' * 79)
        print('Connecting to device:', device['ip'])
        connection = netmiko.ConnectHandler(**device)
        for command in commands:
            print('## Output of ' + command)
            print(connection.send_command(command))
            time.sleep(2)
            print()
        connection.disconnect()
    except netmiko_exceptions as e:
        print('Failed to ', device['ip'], e)

**Comment by ktbyers** [comment]
You need to show your external commands file also.

**Comment by suliman317** [comment]
I had a similar issue, what i did was created a virtual env instead of using my own pip env.
http://docs.python-guide.org/en/latest/dev/virtualenvs/

######
git clone https://github.com/ktbyers/netmiko.git
cd netmiko/
virtualenv -p /usr/bin/python2.7 asa_upgrade
source asa_upgrade/bin/activate
pip install requests
pip install Paramiko==1.13+
pip install Paramiko==1.13
pip install scp==0.10.0
pip install pyyaml
pip install pytest

**Comment by ktbyers** [comment]
Closing due to not getting sufficient information (external commands file).
