### ISSUE TITLE
ASA fails to disable paging

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#546]
get IOError: Search pattern never detected in send_command_expect:

```
#!/usr/bin/env python
from netmiko import ConnectHandler
from getpass import getpass

ip_addr = raw_input("Enter IP Address: ")

device = {
'device_type': 'cisco_asa',
'ip': ip_addr,
'username': 'admin', # replace with your username
'password': getpass()
'global_delay_factor': 2,
}

net_connect = ConnectHandler(**device)
print(net_connect.send_command_expect("show version"))
```
     

I ran find_prompt to find my prompt and then i figured out it was stuck at -------more--------
So when i set my terminal pager to 0 it started working.

Is there any other solution to this?

**Comment by ktbyers** [comment]
@amangoel6

**Comment by ktbyers** [comment]
It should do the disable of paging automatically?

https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_asa_ssh.py#L19


Can you enable logging so we can see what happened, see here for how to enable logging:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by amangoel6** [comment]
Thank you very much Kirk.
I tried above mentioned and setup log as well. It works just fine as it
suppose to be.

**Comment by ktbyers** [comment]
@amangoel6 So are you still having an issue then?

**Comment by amangoel6** [comment]
Nope, It's all fine now. Script is running just fine No errors and no
issues. Really appreciate your help.
I am new with Netmiko and Python so I am playing in my Lab with different
scenarios. As of now it looks pretty good.

Once again, Really appreciate your work.

Regards,
Aman Goyal.
