### ISSUE TITLE
Better auto-detection mechanism

### ISSUE THREAD

**Issue by wisotzky** [ktbyers/netmiko#549]
Just a bit confused, why the routerOS auto-detection rules are provided as part of _snmp_autodetect.py_, which is a central file shared for all implementations. I would really prefer, if any NAPALM driver could just contribute its own rule-set. So if you install a new driver, you would not need to update _snmp_autodetect.py_ as well.

Also there might be situations, where there are different configuration modes for the same routerOS. So just to detect the routerOS might not be sufficient.

In addition, there are other variants of auto-detection, such as running a "show version" CLI command. I believe a hybrid approach using SNMP to detect and later CLI to manage is a bit misleading for tools like NAPALM, as you need to activate SNMP just for that single purpose - and potentially need extra credentials just for SNMP (e.g. some SPs are enforcing usage of SNMPv3 with proper authentication and privacy option enabled). And starting with hybrid management, you potentially want to include NETCONF at some stage - which potentially again would require another user-account (potentially cert-based auth) to dial-in...

**Comment by ktbyers** [comment]
@wisotzky Shouldn't you have created this issue in NAPALM and not in Netmiko? I don't see on the face of it, what it has to do with Netmiko?

Netmiko has two auto-detect mechanisms one that is SNMP based; the other that is SSH based. People are free to use them or not use them.

Do you have some reference where this auto-detection is currently being used in NAPALM?

**Comment by wisotzky** [comment]
Sorry for the confusion... You are right it should be mapped against NAPALM.
