### ISSUE TITLE
Juniper doesn't implement `check_config_mode()`

### ISSUE THREAD

**Issue by supertylerc** [ktbyers/netmiko#55]
The Juniper methods do not implement `check_config_mode()`.  This causes unexpected behavior and unnecessary duplication of code when trying to implement other features.  The current `config_mode()` method in the Juniper file, for example, could be eliminated and a `config_mode(config_command="configure")` (from **ssh_connection.py**) could be used instead.  I can work on this later, but here are a few notes.

The existing `check_config_mode()` method should be usable like this: `check_config_mode(check_string='[edit')`.  That should enable certain methods to be written like this:

```python
def config_mode(self):
    '''
    First check whether currently already in configuration mode.

    Enter config mode (if necessary)
    '''

    if not self.check_config_mode(check_string='[edit'):
        output += self.send_command('configure\n', strip_prompt=False, strip_command=False)
        if 'unknown command' in output:
            raise ValueError("Failed to enter configuration mode")
        if not '[edit' in output:
            raise ValueError("Failed to enter configuration mode")

    return output
```

Other methods could be written as well to take advantage of the `check_config_mode()` method, such as `exit_config_mode()`.  `commit()` could probably be rewritten to use `check_config_mode()` as well as it doesn't make much sense to check to see if you're in config mode, then enter config mode if you're not, then commit the config.  That's typically not a valid workflow, and there typically isn't a use case for committing nothing.  Maybe there's one I haven't considered, though.

**Comment by supertylerc** [comment]
This is done.  I'll submit a PR later.

**Comment by ktbyers** [comment]
Okay, I think is done. The commit() workflow issue we can just address in the commit() design issue.
