### ISSUE TITLE
User Input Error handling issue

### ISSUE THREAD

**Issue by networkguy22** [ktbyers/netmiko#550]
I am trying to prompt the user for the information pertaining to the device ip and credentials, and then pass that input into the ssh session. I hate having credentials listed in scripts for security reasons, plus asking for raw_input allows scalability and less admin overhead if an organization requires credential changes on a rotating period. Add a little error handling to ensure the raw_input is an integer value within a certain range for the IP or host address portion, and bam you got yourself a nice scalable script.

However under Base_Connection.py this is giving me issues as I don't believe raw_input has a default value, which is making it throw errors.
```

  if ip:
            self.host = ip
            self.ip = ip
        elif host:
            self.host = host
        if not ip and not host:
            raise ValueError("Either ip or host must be set")
        if port is None:
            if 'telnet' in device_type:

```

**Comment by ktbyers** [comment]
@networkguy22 Can you post your raw_input() code and how you tie it into Netmiko?
