### ISSUE TITLE
Cisco 3650 - IOError send_command_expect

### ISSUE THREAD

**Issue by acon1831** [ktbyers/netmiko#552]
Hello,

I'm trying Netmiko and I'm unable to run any show commands using send_command() or send_command_expect() on a Cisco 3650.  Below are my configs and the error I'm receiving when I run both commands:

#!/usr/bin/env python
from netmiko import ConnectHandler
import getpass

username = raw_input('Please enter your username: \n')
password = getpass.getpass('Please enter your password: \n')

cisco_core = {
    'device_type': 'cisco_ios',
    'ip':    '10.128.252.14',
    'username': username,
    'password': password,
}

self = ConnectHandler(**cisco_core)

output = self.send_command("show version")
print output
self.disconnect()

***********  Error  ***********

Traceback (most recent call last):
  File "./cisco_test.py", line 17, in <module>
    output = self.send_command("show version")
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 811, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: TUKDDSW02\#

***********************************
Here is the output when I print out the result of find.prompt()

TUKDDSW02#

Interestingly enough, the same script works on my Dell N3048 switch.  Any help with this would be much appreciated.  Thanks!

**Comment by acon1831** [comment]
Looks like the backslash got omitted in the IOError section on my original post.
<p>
IOError: Search pattern never detected in send_command_expect: TUKDDSW02\# 
</p>
<p>
Looks like my issue is expecting TUKDDSW02\# not TUKDDSW02#. 
</p>

**Comment by ktbyers** [comment]
@acon1831 Which version of netmiko are you using?

```
$ python
Python 2.7.12 (default, Sep  1 2016, 22:14:06) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__version__
u'1.4.2'
```

Can you turn on logging and see if we can get additional details on what is happening?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by acon1831** [comment]
Version:

Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__version__
>>> 4.2'

Please see attached for log.

Thank you!

Allan

**Comment by ktbyers** [comment]
@acon1831 I don't see a log file. Did you attach it?



Kirk

**Comment by acon1831** [comment]
Yes I did. I looked at my original email and it's attached with file name
test.log.

Thanks

**Comment by ktbyers** [comment]
@acon1831 Okay, there is no file in GitHub nor in my email as far as I can tell. Please post the file directly into GitHub (or attach the file directly in GitHub).

**Comment by amangoel6** [comment]
@acon1831 ]
Most probably it is terminal pager issue.

Try to use below command before send_command and let us know the result.

self.disable_paging() 
output = self.send_command("show version")

**Comment by ktbyers** [comment]
Never received the logging file. It looks like it should have worked from the code originally posted.
