### ISSUE TITLE
Timeout Exception in CiscoXR devices because colon and hostname being dropped in config mode to accommodate larger config string

### ISSUE THREAD

**Issue by shreyashah** [ktbyers/netmiko#553]

**Comment by shreyashah** [comment]
I am connecting to Cisco ASR9k router and this is my config:

configs = ['redundancy',
          'iccp',
          'group 11',
          'backbone',
          'interface GigabitEthernet0/0/1/19']

/usr/local/lib/python3.6/site-packages/paramiko/channel.py:665: in recv
    out = self.in_buffer.read(nbytes, self.timeout)
/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py:160: in read
    raise PipeTimeout()
E   paramiko.buffered_pipe.PipeTimeout
During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py:299: in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER).decode('utf-8', 'ignore')
/usr/local/lib/python3.6/site-packages/paramiko/channel.py:667: in recv
    raise socket.timeout()
E   socket.timeout
During handling of the above exception, another exception occurred:
issue.py:37: in <module>
    dev.config('\r'.join(configs))
../../../lib/topology/devices/device.py:1153: in config
    return handle.config(cmd_list=cmd_list, *args, **kwargs)
../../../lib/topology/connection/connection.py:478: in config
    self._end_config(**kwargs)
../../../lib/topology/connection/connection.py:427: in _end_config
    nm_handle.exit_config_mode()
/usr/local/lib/python3.6/site-packages/netmiko/cisco/cisco_xr.py:180: in exit_config_mode
    if skip_check or self.check_config_mode():
/usr/local/lib/python3.6/site-packages/netmiko/cisco_base_connection.py:33: in check_config_mode
    pattern=pattern)
/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py:954: in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py:360: in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py:303: in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
E   netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by shreyashah** [comment]
It is because the hostname from the prompt when in configuration mode gets truncated


[2:50]  
This is my hostname:      RP/0/RSP0/CPU0:asr9k-peer-infra#


[2:51]  
RP/0/RSP0/CPU0:asr9k-peer-infra#-Debug---2017-08-16-T14-14-24[Timer]>elapsed time: 5.67 s
-Info----2017-08-16-T14-14-24[connection]>configuring.. vty 
###############output =  config term
Wed Aug 16 14:11:14.206 UTC

########################____________________________
###############pattern =  RP/0/RSP0/CPU0:a.*config
###############output =  config term
Wed Aug 16 14:11:14.206 UTC
Current Configuration Session  Line       User     Date                     Lock
00000011-3cf7f17e-00000164     netconf    root     Wed Aug 16 14:11:08 2017

########################____________________________
###############pattern =  RP/0/RSP0/CPU0:a.*config
###############output =  config term
Wed Aug 16 14:11:14.206 UTC
Current Configuration Session  Line       User     Date                     Lock
00000011-3cf7f17e-00000164     netconf    root     Wed Aug 16 14:11:08 2017 
RP/0/RSP0/CPU0:asr9k-peer-infra(config)#
########################____________________________
###############pattern =  RP/0/RSP0/CPU0:a.*config
-Debug---2017-08-16-T14-14-27[Timer]>config 2.68 s
-Debug---2017-08-16-T14-14-28[Timer]>commit 1.23 s
###############output =  
RP/0/RSP0/CPU0(config-redundancy-group-iccp-backbone)#
########################____________________________
###############pattern =  RP/0/RSP0/CPU0:
-Debug---2017-08-16-T14-14-36[Timer]>end 8.17 s
-Debug---2017-08-16-T14-14-36[Timer]>elapsed time: 12.07 s
collected 0 items / 1 errors


[2:51]  
Lines starting with ###### are my own debug statements

**Comment by shreyashah** [comment]
before entering config mode, this is the prompt:
RP/0/RSP0/CPU0:asr9k-peer-infra#

In the config mode, the prompt changes to:
RP/0/RSP0/CPU0(config-redundancy-group-iccp-backbone)#


like mentioned earlier, colon and hostname(:asr9k-peer-infra) are dropped to accommodate the large config string (config-redundancy-group-icc-backbone)

**Comment by shreyashah** [comment]
@ktbyers : Hi, any idea if this is fixed or in progress. Please let me know. Thanks.

**Comment by ktbyers** [comment]
@shreyashah No I still need to look at this.


Kirk

**Comment by carlniger** [comment]
closing as this is very old. please re-open if this is an issue on modern netmiko
