### ISSUE TITLE
Netmiko exits sub-config

### ISSUE THREAD

**Issue by taylor2464** [ktbyers/netmiko#554]
Hello,

We are running into an issue with Netmiko where if we need to send configuration commands, it can send them just fine in (config) but once you enter a sub config such as (config-if), Netmiko won't send the command and exit (config) all together. We are using Netmiko 1.4.2 with Python 3.6.1. I have also tested this on Python 3.5 with the same results. This occurs on both IOS-XE 03.06.03.E and IOS 7200 15.0(1)M4. Maybe I just don't understand how to send config changes through Netmiko.

Some sample code I have tried using:

```
net_connect = ConnectHandler(**machine)
net_connect.enable()
net_connect.config_mode()

print(net_connect.find_prompt())

net_connect.send_config_set("int gi1/20", "shutdown")
print(net_connect.find_prompt())

# net_connect.send_config_set("shutdown")
# print(net_connect.find_prompt())

net_connect.exit_config_mode()

print(net_connect.find_prompt())

net_connect.disconnect()
```

Thank you,

Taylor

Edit: Formatted code.

**Comment by ktbyers** [comment]
@taylor2464 `send_config_set()` automatically enters/exists config mode. Also your commands in send_config_set need to be a list of commands i.e. ["int gi1/20", "shutdown"]

See comments here:

```
# not needed as Netmiko will handle this automatically
net_connect.config_mode()
print(net_connect.find_prompt())

# needs to be list of commands
net_connect.send_config_set(["int gi1/20", "shutdown"])

# at this point Netmiko will have exited config mode
print(net_connect.find_prompt())

# not needed as you will already be out of config mode
net_connect.exit_config_mode()
print(net_connect.find_prompt())
net_connect.disconnect()
```

Does that fix your issue?

**Comment by taylor2464** [comment]
@ktbyers Thank you! That was pretty obvious looking back on it.

**Comment by vjuagar** [comment]
Hello, I have a similar problem, I configure an interface I cannot get out of its configuration to configure another one, that is, it does not execute the exit command and I have tried with the command "net_connect.exit_config_mode ()" and with it I can exit the interface settings.
