### ISSUE TITLE
Cannot install config: Router prompt not found on Cisco 2911

### ISSUE THREAD

**Issue by b2sweety** [ktbyers/netmiko#555]
Hi All,
I am running a playbook to push configurations onto a Cisco 2911 switch.  I am getting the below error:
TASK [commit] **********************************************************************************************************************************************************
fatal: [firstrouter]: FAILED! => {"changed": false, "failed": true, "msg": "cannot install config: Router prompt not found: Rollback failed.Reverting back to the original configuration: flash:mybackupAug-18-17-05-15.343-15 ..."}

Playbook:

      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      dev_os: "ios"
      config_file: new_switch1.conf
      commit_changes: True
      replace_config: True
      diff_file: initial.diff

Solutions tried:
1. Changed global_delay_factor: 2
2 Added below 2 lines to base_connection.py in netmiko under : def session_preparation(self):
 time.sleep(2)
 self.clear_buffer()
3. Added timeout=180 in the playbook
 
using netmiko version: netmiko (1.4.2)
Python 2.7.5 

SSH to the switch works good through the same console.  
If i run netmiko commands individually , it works fine and am able to commit the changes to the switch. But if I run the playbook to commit configuration changes, it fails giving router prompt not found error.
Further, get_facts and initial.diff gets generated successfully using the playbook. 
Can someone please help me with this.

**Comment by ktbyers** [comment]
How big is new_switch.conf (how many lines)?

Are you changing the hostname as part of this?

What happens when you perform the configure replace manually?

```
configure replace flash:/candidate_config.txt force revert trigger error
```

Note, make sure the candidate_config.txt matches the file you are trying to push before you do this. You can probably achieve this by setting `commit_changes: False`.

Also you might have a different file system than `flash:`

**Comment by b2sweety** [comment]
Hi Kirk, 

Thank you for the response. 
Yes, You are right. I was changing the hostname in the new config file. I removed it and am able to restore the config successfully which now brings me to another question . How do we make a restore config successful when a user wants to change the hostname as part of this. 
For the other questions:  The config file new_switch1.cfg contains 163L and I had removed the top 3 lines until version. 
I tried manually running the command and her is the output:
R1#configure replace flash:/candidate_config.txt force revert trigger error
Total number of passes: 1
Rollback Done

**Comment by ktbyers** [comment]
@b2sweety How long does the configure replace take to complete? I think I allocated 12 seconds for it to complete when there is a hostname change.

You can double this time by specifying the `optional_args = {'global_delay_factor': 2}`.

I would try that and see if it works.

**Comment by b2sweety** [comment]
Yes, specifying optional_args = {'global_delay_factor': 2} worked good. The hostname changed perfectly fine. Thank you for your help!

**Comment by ktbyers** [comment]
@b2sweety Okay, thanks for letting me this know...please keep this issue open as I think I might want to adjust the default time on napalm-ios to give a bit more time than I currently am providing.

**Comment by ktbyers** [comment]
This was a napalm-ansible issue and there has been work in this area in napalm subsequent to this...so am going to close here.
