### ISSUE TITLE
Cisco IOS-XR repainting line multiple times: unable to get desired output

### ISSUE THREAD

**Issue by kaushikrp** [ktbyers/netmiko#556]
Hi, I am getting below output for the code executed
Sun Aug 20 00:29:39.358 ist
drop paks: 26493,  drop_bytes: 13144301
drop paks: 0,  drop_bytes: 0
drop paks: 0,  drop_bytes: 0
drop paks: 0,  drop_bytes: 0
drop paks: 8199371,  drop_bytes: 8194252327
drop paks: 0,  drop_bytes: 0
drop paks: 0,  drop_bytes: 0
drop paks: 12796452,  drop_bytes: 12766476682
##############################################################

Sun Aug 20 00:29:39.962 ist
drop paks: 1159794364,  drop_bytes: 157333372363
##############################################################

Sun Aug 20 00:29:40.595 ist
drop paks: 0,  drop_bytes: 0
drop paks: 4,  drop_bytes: 445
drop paks: 0,  drop_bytes: 0
drop paks: 0,  drop_bytes: 0
drop paks: 13112434,  drop_bytes: 13126035635
drop paks: 0,  drop_bytes: 0
drop paks: 9112287,  drop_bytes: 8760532104
drop paks: 0,  drop_bytes: 0
##############################################################

4#show controllers np
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/0/CPU0
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/0/CPU0 |
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/0/CPU0 | include
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/0/CPU0 | include "drop
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/0/CPU0 | include "drop paks"

Sun Aug 20 00:29:46.695 ist

##############################################################

4#show controllers np
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/1/CPU0
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/1/CPU0 |
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/1/CPU0 | include
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/1/CPU0 | include "drop
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/1/CPU0 | include "drop paks"

Sun Aug 20 00:29:47.302 ist

##############################################################

#show controllers np
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/10/CPU0
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/10/CPU0 |
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/10/CPU0 | include
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/10/CPU0 | include "drop
RP/0/RP0/CPU0:MHPUNVGANCR04#show controllers np tm counters all location 0/10/CPU0 | include "drop paks"

CODE:

from __future__ import print_function
from netmiko import ConnectHandler
import sys
import time
import select
import paramiko
import re

fd = open(r'C:\NewdayTest.txt','w')
old_stdout = sys.stdout   
sys.stdout = fd 
platform = 'cisco_xr'
username = 'kaushik' 
password = 'kaushik20'

ip_add_file = open(r'C:\IPAddressList.txt','r')

for host in ip_add_file:
    host = host.strip()
    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
    output = device.send_command('terminal length 0')
    output = device.send_command('show controllers np tm counters all location 0/0/CPU0 | include "drop paks"')
    print(output)
    print('##############################################################\n')
    output = device.send_command('show controllers np tm counters all location 0/1/CPU0 | include "drop paks"')
    print(output)
    print('##############################################################\n')
    output = device.send_command('show controllers np tm counters all location 0/10/CPU0 | include "drop paks"')
    print(output) 
    print('##############################################################\n')

fd.close()

**Comment by kaushikrp** [comment]
I am getting desirable output for 1st node but not for 2nd mentioned in IPAddressList.txt

**Comment by ktbyers** [comment]
@kaushikrp So the failure is you are getting the repainting of the line (and not getting the output)?

**Comment by Kaushikrpatel** [comment]
Yes, I have entered 4 hosts in the file from where I want to get the output of line cards, however I am getting output of just 1st device properly and for other the command is repainted

**Comment by ktbyers** [comment]
@Kaushikrpatel Can you turn on logging so I can see what is happening:

```
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
```

This will create a file named test.log in the current directory.

**Comment by kaushikrp** [comment]
@ktbyers I have sent you the requested output on your email id

**Comment by ktbyers** [comment]
@kaushikrp Okay, I think I have an IOS-XR bug here that I need to fix. It will probably be two to three weeks before I fix this.

**Comment by kaushikrp** [comment]
Thank you Kirk for your valuable inputs.

Regards,
Kaushik Patel

**Comment by carlniger** [comment]
Going to close this as its very old and I'm pretty sure its been fixed for a long time. Feel free to let us know if its still an issue!
