### ISSUE TITLE
Socket closed error when the router is left in idle state for more than 10 minutes

### ISSUE THREAD

**Issue by shreyashah** [ktbyers/netmiko#557]
I m using a 6 router topology.  The steps to reproduce this issue.

Connect to each router.
Take a router and configure all the feature corresponding to it.
After certain time (approx ~ 10 mins) when we are in 4- 5 th router trying to configure the features, during the config we realize that the connection socket has been closed and no longer available.
Because of which we are not able to configure the router and proceed further.

feature_obj.push_config()
../../lib/feature_lib/ifmgr/ifmgr_xr_cli.py:56: in push_config
    self.device.config(_cfg, max_timeout = 300)
../../lib/feature_lib/feature_base.py:29: in config
    self._device.config(cfg,self._handle,*args,**kwargs)
../../lib/topology/devices/device.py:1153: in config
    return handle.config(cmd_list=cmd_list, *args, **kwargs)
../../lib/topology/connection/connection.py:469: in config
    max_timeout=max_timeout)
../../lib/topology/connection/connection.py:349: in _config
    verbose=True,
/auto/cafy/cafykit/cafy-exec/lib/python3.4/site-packages/netmiko/cisco/cisco_xr.py:55: in send_config_set
    **kwargs)
/auto/cafy/cafykit/cafy-exec/lib/python3.4/site-packages/netmiko/base_connection.py:1109: in send_config_set
    output = self.config_mode()
/auto/cafy/cafykit/cafy-exec/lib/python3.4/site-packages/netmiko/cisco/cisco_xr.py:42: in config_mode
    pattern=pattern)
/auto/cafy/cafykit/cafy-exec/lib/python3.4/site-packages/netmiko/cisco_base_connection.py:64: in config_mode
    pattern=pattern)
/auto/cafy/cafykit/cafy-exec/lib/python3.4/site-packages/netmiko/base_connection.py:1043: in config_mode
    self.write_channel(self.normalize_cmd(config_command))
/auto/cafy/cafykit/cafy-exec/lib/python3.4/site-packages/netmiko/base_connection.py:252: in write_channel
    self._write_channel(out_data)
/auto/cafy/cafykit/cafy-exec/lib/python3.4/site-packages/netmiko/base_connection.py:241: in _write_channel
    self.remote_conn.sendall(write_bytes(out_data))
/auto/cafy/cafykit/cafy-exec/lib/python3.4/site-packages/paramiko/channel.py:813: in sendall
    sent = self.send(s)
/auto/cafy/cafykit/cafy-exec/lib/python3.4/site-packages/paramiko/channel.py:767: in send
    return self._send(s, m)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <paramiko.Channel 0 (closed) -> <paramiko.Transport at 0xceab6358 (unconnected)>>, s = b'config term\n', m = paramiko.Message(b'^\x00\x00\x00\x01')

    def _send(self, s, m):
        size = len(s)
        self.lock.acquire()
        try:
            if self.closed:
                # this doesn't seem useful, but it is the documented behavior
                # of Socket
>               raise socket.error('Socket is closed')
E               OSError: Socket is closed

**Comment by ktbyers** [comment]
@shreyashah I responded to this in Slack...if that doesn't work, you can re-open here.
