### ISSUE TITLE
send command wait for prompt or string

### ISSUE THREAD

**Issue by botanicvelious** [ktbyers/netmiko#559]
I have the following code that i use to get a 'show run'

```
return_text = net_connect.send_command_expect(all_devices[args.type]['show_run'], strip_prompt=True, strip_command=False)

output = return_text

while all_devices[args.type]['delimiter'] in return_text:
    if all_devices[args.type]['delimiter'] == '':
        break
    # Send an 'space'
    return_text = net_connect.send_command_timing(' ', strip_prompt=True, strip_command=False,max_loops=100, normalize=False)
    output += return_text

```

as sometimes i get a prompt and sometimes i get the delimited string (the next page message) it seems this isn't possible to handle currently? I found read_until_prompt_or_pattern however that doesn't seem to work with send_command, is this correct or is there another way to handle this?

**Comment by ktbyers** [comment]
@botanicvelious What kind of devices are you connecting to?
