### ISSUE TITLE
Multiple Configuration Modes

### ISSUE THREAD

**Issue by supertylerc** [ktbyers/netmiko#56]
Juniper's CLI supports multiple configuration modes.  The more common ones:

* private
* exclusive
* shared

The `config_mode()` method should incorporate these three common modes.  I can work on this later, but an (untested) example is below.

```python
def config_mode(self, mode=''):
    '''
    First check whether currently already in configuration mode.

    Enter config mode (if necessary), specifying the appropriate mode.  `mode` is blank
    by default (global config mode).
    '''

    supported_modes = ("", "private", "exclusive")
    if mode not in supported_modes:
        raise ValueError("Unsupported mode: {0}".format(mode))

    output = self.send_command('\n', strip_prompt=False, strip_command=False)
    if not '[edit' in output:
        command = "configure " + mode + "\n"
        output += self.send_command(command, strip_prompt=False, strip_command=False)
        if 'unknown command' in output:
            raise ValueError("Failed to enter configuration mode")
        if not '[edit' in output:
            raise ValueError("Failed to enter configuration mode")

    return output
```

**Comment by supertylerc** [comment]
It turns out that IOS XR also supports **configure exclusive**.  It may support others, but my IOS XR expertise is limited.

**Comment by ktbyers** [comment]
Okay, I will open up an issue related to Junos and IOS-XR commit, confirm,
rollback as a design spec. We can spec out how this should work here and
then implement it.


Kirk

On Sat, Mar 7, 2015 at 9:48 AM, Tyler Christiansen <notifications@github.com
> wrote:

> It turns out that IOS XR also supports *configure exclusive*. It may
> support others, but my IOS XR expertise is limited.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/56#issuecomment-77700588>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by ktbyers** [comment]
Should be done.
