### ISSUE TITLE
send commands: change in prompt breaks script

### ISSUE THREAD

**Issue by adieball** [ktbyers/netmiko#560]
Hi

I'm connecting to Aerohive Accesspoints to send several commands. One of these commands is changing the hostname and therefor changing the prompt.
I'm using the device type "linux".
This is confusing netlike as it expects the prompt it has learned when it connected first:

>  Traceback (most recent call last):
>   File "aerostaging.py", line 186, in <module>
>     main()
>   File "aerostaging.py", line 152, in main
>     net_connect.send_command("hostname %s" % m_list[i]['HOSTNAME'])
>   File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 811, in send_command
>     search_pattern))
> OSError: Search pattern never detected in send_command_expect: AH\-2de300\#

How can I tell netlike that the prompt it should expect has changed?

I learned that I can send a config set but as far as I understood, that automatically enters a config mode which is not available on the Accesspoint.

any help is highly appreciated.

thanks

**Comment by ktbyers** [comment]
`send_command()` has an argument (IIRC) named `expect_string` where can change the default pattern it looks for (by default it will look for part of the trailing prompt.

You can also use `send_command_timing()` method to change the prompt (this method is entirely delay based so it doesn't care that you changed the prompt).
