### ISSUE TITLE
huawei device disable_paging

### ISSUE THREAD

**Issue by nmweizi** [ktbyers/netmiko#562]
some huawei device  disable_paging  command  is
command="screen-length disable" 
not "screen-length 0 temporary"

add disable_paging=''  in class BaseConnection(object)  \__init___ function parameter ?

**Comment by ktbyers** [comment]
@nmweizi Do you know what category of devices are this way (i.e. some sort of a platform name / product name)? 

I need this so I can differentiate between products that do one way versus another way.

**Comment by nmweizi** [comment]
h3c sr8812
h3c sr6608

**Comment by ktbyers** [comment]
Did you try the `hp_comware` device type? They look to be fundamentally Comware Devices.

**Comment by nmweizi** [comment]
This method is ok.
