### ISSUE TITLE
Pagination / Paging cannot be disabled PowerConnect 6248

### ISSUE THREAD

**Issue by ckllr** [ktbyers/netmiko#563]
In the firmware version I am using, PCT6248's are no longer capable of disabling pagination. I am tasked with running diagnostics on quite a few of these switches and am expecting multi-page outputs. As this is quite a serious impediment, and I am unauthorized to downgrade said switches, how might one work around this?

I eagerly await anyone's suggestions.

**Comment by nmweizi** [comment]
Active call
disable_paging(command=disabling pagination command)

**Comment by ckllr** [comment]
@nmweizi Right, that command that disables pagination does not work. These switches have no ability to disable pagination through ANY command.

**Comment by ktbyers** [comment]
Talk to Dell; they need to fix their product.

Netmiko won't support them, if they can't disable output paging.

You could try to work around it, by mimicking what you do manually...but that won't be incorporated into Netmiko (as too much of a kludge).

**Comment by ckllr** [comment]
@ktbyers I am quite new to python. While I don't expect you to do work for free, could you let me know or show me how I could send a command followed by a keypress? I've tried x.send_command(command) followed by a few x.send_command('m')'s in a loop without any results.

**Comment by ktbyers** [comment]
Probably something like (where net_connect is the Netmiko connection object).

```
net_connect.write_channel("m")
```

Multiple times, you might also need to add some sort of time.sleep(1) in there to wait for the device to output more data. 

This assumes "m" is the character you hit to keep paging through the output.
