### ISSUE TITLE
Commit Confirm

### ISSUE THREAD

**Issue by supertylerc** [ktbyers/netmiko#57]
Both Junos and IOS XR support the Commit Confirm feature.  This may be a feature worth implementing it as it can save you from a lot of things.  One use case is a commit confirm with a sufficient timeout to run automated tests, at which point the automated tests (or scripts or whatever) can commit the configuration permanently.  This can save you from committing a bad change that kills connectivity to the box.

**Comment by ktbyers** [comment]
Incorporating into master issue #60
