### ISSUE TITLE
SSH version 1, can not connect

### ISSUE THREAD

**Issue by hoyeunglee** [ktbyers/netmiko#572]
when switch only accept SSH version 1 , it can not connect

do it support SSH version 1?

**Comment by ktbyers** [comment]
@hoyeunglee Paramiko doesn't support SSHv1 so Netmiko has no SSHv1 support. 

SSHv2 has been around for over 10 years (probably longer since 2006 is when it was approved as a standard and standards bodies are very slow moving).
