### ISSUE TITLE
multiprocessing on comware

### ISSUE THREAD

**Issue by s1405** [ktbyers/netmiko#574]
@ktbyers this is the code:

from multiprocessing import Process
from netmiko import ConnectHandler, NetMikoAuthenticationException, NetMikoTimeoutException
from getpass import getpass
import time

def ssh(ip, u, p, s):
    conn = ConnectHandler(ip = ip, username = u,     password = p,               device_type = 'hp_comware')
    print(conn.send_command('su\n{0}\ndisplay arp'.format(s)))

if __name__ == '__main__':
    ips = '''
        192.168.56.11
        192.168.56.12
        192.168.56.13
        '''.strip().splitlines()
    
    u = raw_input('login: ')
    p = getpass('password: ')
    s = getpass('super: ')

    prs = []
    
    for ip in ips:
        pr = Process(target=ssh, args=(ip, u, p, s))
        prs.append(pr) 
        pr.start()

    while any(pr.is_alive() for pr in prs):
        time.sleep(0.1)

    for pr in prs:
        pr.join()

it executes only the first process, and not the rest, can you see what the issue could be

c:\py\test>python process.py
login: admin
password:
super:
Process Process-3:
Traceback (most recent call last):
  File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "c:\py\test\process.py", line 7, in ssh
    conn = ConnectHandler(ip = ip, username = u,     password = p,               device_type = 'hp_comware')
  File "c:\python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "c:\python27\lib\site-packages\netmiko\base_connection.py", line 150, in __init__
    self.establish_connection()
  File "c:\python27\lib\site-packages\netmiko\base_connection.py", line 506, in establish_connection
P rocess Process-2:
   raise NetMikoTimeoutException(msg)
TNraceback (most recent call last):
etMikoTimeoutException: Connection to device timed-out: hp_comware         192.168.56.13:22
  File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "c:\py\test\process.py", line 7, in ssh
    conn = ConnectHandler(ip = ip, username = u,     password = p,               device_type = 'hp_comware')
  File "c:\python27\lib\site-packages\netmiko\ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "c:\python27\lib\site-packages\netmiko\base_connection.py", line 150, in __init__
    self.establish_connection()
  File "c:\python27\lib\site-packages\netmiko\base_connection.py", line 506, in establish_connection
    raise NetMikoTimeoutException(msg)
NetMikoTimeoutException: Connection to device timed-out: hp_comware         192.168.56.12:22
vilege role is network-admin, and only those commands that authorized to the role can be used.
<switch1>display arp
  Type: S-Static   D-Dynamic   O-Openflow   R-Rule   M-Multiport  I-Invalid
IP address      MAC address    VLAN     Interface                Aging Type
192.168.56.1    0a00-2700-0029 N/A      MGE0/0/0                 8     D
192.168.56.12   4c2f-848d-0201 N/A      MGE0/0/0                 14    D
192.168.56.13   5e69-a227-0305 N/A      MGE0/0/0                 13    D

**Comment by ktbyers** [comment]
It looks like you connected to multiple devices:

# These devices there was nothing on port 22:
```
NetMikoTimeoutException: Connection to device timed-out: hp_comware 192.168.56.13:22
NetMikoTimeoutException: Connection to device timed-out: hp_comware 192.168.56.12:22
```

# This one worked:
```
display arp
Type: S-Static D-Dynamic O-Openflow R-Rule M-Multiport I-Invalid
IP address MAC address VLAN Interface Aging Type
192.168.56.1 0a00-2700-0029 N/A MGE0/0/0 8 D
192.168.56.12 4c2f-848d-0201 N/A MGE0/0/0 14 D
192.168.56.13 5e69-a227-0305 N/A MGE0/0/0 13 D
```

**Comment by s1405** [comment]
I could login to those individually or sequentially. But not simultaneously - only the first process works, rest say timeout

**Comment by ktbyers** [comment]
@s1405 Are these real devices or virtual?

You might want to turn on logging and see if they provide you clues:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

You might also want to watch the SSH session from the network device perspective.

You might also want to try adding a very small delay between starting each of the processes and see if that makes a difference.
