### ISSUE TITLE
Not Recognizing Prompt

### ISSUE THREAD

**Issue by bgile** [ktbyers/netmiko#578]
I am trying to delete all config within a hierarchy in with Netmiko, but it is not recognizing the prompt:

[edit groups this-group]
user@device# delete
Delete everything under this level? [yes,no] (no) 

Instead of executing 'yes' it will just hang.  Is there some method for recognizing a follow up prompt like this?

Thanks

**Comment by ktbyers** [comment]
@bgile Probably use `send_command_timing`:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#show-commands-that-prompt-for-more-information

**Comment by bgile** [comment]
Thanks.  I was also able to fudge it with the remote_conn.sendall and remote_conn.recv , but was looking for something maybe a little more cleaner.  I will look at your link.  Thanks for the quick response :)
