### ISSUE TITLE
ValueError: Failed to enter configuration mode

### ISSUE THREAD

**Issue by pennydoll** [ktbyers/netmiko#587]
Hello Kirk,

I am learning Python with netmiko and getting this error while running the script
root@NetworkAutomation-1:~# python netmiko2.py 
Traceback (most recent call last):
  File "netmiko2.py", line 19, in <module>
    output = net_connect.send_config_set(commands_to_send, delay_factor=4)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 957, in send_config_set
    output = self.config_mode()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 43, in config_mode
    pattern=pattern)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 908, in config_mode
    raise ValueError("Failed to enter configuration mode.")
ValueError: Failed to enter configuration mode.

Script:
#!/usr/bin/env python

from netmiko import ConnectHandler

with open('syd-axs-10_config') as f:
        commands_to_send = f.read().splitlines()

ios_devices = {
        'device_type': 'cisco_ios',
        'ip': '192.168.122.101',
        'username': 'xxx',
        'password': 'xxx'
}

all_devices = [ios_devices]

for devices in all_devices:
        net_connect = ConnectHandler(**devices)
        output = net_connect.send_config_set(commands_to_send, delay_factor=4)
        print output

**Comment by ktbyers** [comment]
@pennydoll Try turning on logging and see if this provides you more information:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Does the user that logs in have permissions to go into configuration mode?

**Comment by pennydoll** [comment]
Thanks Kirk, I enabled the debug and the script ran successfully with no errors, don't know why I was seeing that y'day. But Now I have another concern, when I ran the script, I was not seeing anything displayed on my screen. Why is that? 

Also when the script is pulling the configs from a file, how can I split the configs and display them on screen, like for example:
Configuring AAA........
----list of AAA commands executed here-----
Configuring VLANs.......
-----list of VLAN Commands executed here....
Configuring Interfaces.......
-----list of interface command and the config.....
and so on and so forth...

**Comment by ktbyers** [comment]
@pennydoll Can you give me an example command that you are not seeing anything from?

In other words, you have this:

```
commands_to_send = f.read().splitlines()
```

But I have no visibility into what `commands_to_send` is?

**Comment by pennydoll** [comment]
I sent a whole bunch of commands including - AAA Commands, VLAN IDs, interface range with access and voice vlan's and ACLs.

**Comment by ktbyers** [comment]
Okay, can you provide the exact commands from the command file? You can obfuscate anything that is confidential.

Also I assume your print statement is inside the for loop?

**Comment by ktbyers** [comment]
Closing as there was no response.
