### ISSUE TITLE
enable() function challenges...

### ISSUE THREAD

**Issue by jscobbie73** [ktbyers/netmiko#589]
I'm having issues with the .enable() function on 2 different platforms.  

On the SG 300's I am  unable to get the .enable() function to work properly.  I'm wondering if the issue is caused by the standard prompt already having a terminating #?  If I create an account that is priv 15 everything works as expected (as I don't need to use the .enable() function

I'm also using the cisco_ios module on a different platform that is "IOS Like".  I'm wondering if there is an issue parsing it's enable prompt as it is slightly different.

Input enable Password: 

is the output provided when you type enable in the CLI.  When I use the .enable() function I get a number of errors 

`>>> device.enable()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 17, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 871, in enable
    if not self.check_enable_mode():
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 13, in check_enable_mode
    return super(CiscoBaseConnection, self).check_enable_mode(check_string=check_string)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 863, in check_enable_mode
    output = self.read_until_prompt()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 334, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 289, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.`

Any assistance would be appreciated on either platform.

**Comment by ktbyers** [comment]
@jscobbie73 Can you show what the CLI sessions looks like on these two devices (for going into enable mode)?

**Comment by jscobbie73** [comment]
For the IOS Like device

> ZebOS version 7.8.2 IPIRouter 06/07/17 16:16:12
> idf03.site3>en
> Input enable Password:
> idf03.site3#

for the SG-300

> PSZ20321KWT-swi-0...#en
> Password:********
> PSZ20321KWT-swi-0…#

The hostname for the SG300 is long as it starts with the device SN (a whole different problem) and has site ID data appended to that.

**Comment by ktbyers** [comment]
Why does your SG300 respond with a '#' prompt when not in enable mode? I don't think mine does that? Is that something in your configuration?

Missed (or didn't fully understand) your initial message about the '#' when you originally posted the issue.

**Comment by ktbyers** [comment]
The ZebOS looks like it should work with Netmiko 1.4.3 for enable(). 

What error do you see when using ZebOS?

**Comment by jscobbie73** [comment]
I have no idea, I changed the hostname to something shorter (switch) and it still did.  Show Ver and Show System as below...

> SW version    1.4.7.6 ( date  07-Dec-2016 time  18:37:03 )
> Boot version    1.3.5.06 ( date  21-Jul-2013 time  15:12:10 )
> HW version    V05

> System Description:                       SG300-10 10-Port Gigabit Managed Switch
> System Up Time (days,hour:min:sec):       42,04:27:40
> System Contact:
> System Name:                              PSZ20321KWT-swi-0015-cam-ma-us
> System Location:
> System MAC Address:                       00:87:31:f0:2b:0e
> System Object ID:                         1.3.6.1.4.1.9.6.1.83.10.1

> Fans Status:                              N/A

**Comment by PackeTsar** [comment]
I have a SG300-52P-K9 and there is no "enable" functionality. It drop you directly into privileged mode automatically.

**Comment by ktbyers** [comment]
@PackeTsar Yes, that would work fine from a netmiko perspective, but is not what he sees (as per above). What you see is consistent with what I am seeing.

Here is what I see:

```
sf-dc-sw1#show priv
Current privilege level is 15
sf-dc-sw1#enable
% Unrecognized command

sf-dc-sw1#show version
SW version    1.3.5.58 ( date  10-Oct-2013 time  17:15:41 )
Boot version    1.3.5.06 ( date  21-Jul-2013 time  15:12:10 )
HW version    V02

sf-dc-sw1#show system 
System Description:                       SG300-10 10-Port Gigabit Managed Switch
System Up Time (days,hour:min:sec):       463,03:04:49
System Contact:                           
System Name:                              sf-dc-sw1
System Location:                          
System MAC Address:                       c0:7b:bc:65:27:2e
System Object ID:                         1.3.6.1.4.1.9.6.1.83.10.1

Fans Status:                              N/A
```

**Comment by ktbyers** [comment]
If I intentionally go to priv1, I get this:

```
sf-dc-sw1#disable 1
sf-dc-sw1>
sf-dc-sw1>
sf-dc-sw1>
sf-dc-sw1>enable 
Password:
```

**Comment by ktbyers** [comment]
@jscobbie73 On the SG300, what does `show priv` show you?

**Comment by jscobbie73** [comment]
> PSZ20321KWT-swi-0...#show priv
> Current privilege level is 7

That to me is expected as the user is created with a Priv 7

As far as the ZebOS box, I pasted the errors I get in the original post.

**Comment by vascojcm** [comment]
hi @ktbyers, 

I also have a challenge/request that looks pretty simple to add into enable functionality. 

I have a Cisco ASA and I want to enter enable mode but only with privilege level 5 (it defaults to 15)
Now, when I add the secret it goes directly to enable privilege 15. 
Can you add the functionality to specify which privilege level to enter when enabling on a Cisco ASA?

Something like this

device = {
    'device_type': 'cisco_asa',
    'ip': "192.168.96.2",
    'username': 'noc',
    'password': 'T3st_sc3N4rl0)',
    'secret': 'I3wW!p5g~+uV-Z',
    'secret_level': '5'   <<<---------------- New_feature (???)
    'port': 22
}

then I guess that on the class CiscoAsaSSH (cisco_asa_ssh.py)
(...)
    def session_preparation(self):
        """Prepare the session after the connection has been established."""
        self._test_channel_read()
        self.set_base_prompt()
        if self.secret:
          if self.secret_level: <<<<--------- New_feature (???)
            self.enable(cmd='enable 5')  <<<<--------- New_feature (???)
          else:
               self.enable()


This makes sense to you ?
Thanks

**Comment by ktbyers** [comment]
You should be able to just call:

```
output = net_connect.send_command_timing('enable 5')
```

And handle the password yourself.

I don't think it is a common enough use case to integrate in.
