### ISSUE TITLE
SH arp and return true if ip is on csv?

### ISSUE THREAD

**Issue by jsb515** [ktbyers/netmiko#590]
Is it possible to have a send command for sh arp | inc Vlan100 and with the IP addresses listed from the arp command search a csv and return a true statement?

**Comment by ktbyers** [comment]
Yes...that should be pretty straightforward. There is a CSV python library and you would probably need to use some regular expression parsing of the output data.

**Comment by jsb515** [comment]
i'm still new to python and learning lol any direction on any articles for doing this? :)

**Comment by ktbyers** [comment]
Python regular expressions, the Google University Python Course is pretty good for this content and my free course, class7 covers regular expressions.

CSV library probably is pretty straightforward.

Netmiko my tutorial and the Readme on the GitHub page.

Other Python fundamentals, my free course, Automate the Boring Stuff book (looks pretty good, haven't read it, but glanced through it quite a bit), also Matt Harrison book on Python Fundamentals is good.

**Comment by PackeTsar** [comment]
I have found the Python RE doc to be relatively straightforward for how to use the regex (re) module in Python.   https://docs.python.org/3/library/re.html

**Comment by PackeTsar** [comment]
I haven't had to use a CSV library yet but I know somebody who has. I will ask and get back to you.

**Comment by PackeTsar** [comment]
OK it was pretty obvious.... `import csv`

**Comment by ktbyers** [comment]
I have some CSV example code here:

https://github.com/ktbyers/pynet-ons-jul17/tree/master/csv_example

It won't totally match what you are doing though.
