### ISSUE TITLE
Understanding read_channel and write_channel

### ISSUE THREAD

**Issue by hardcorecoder27** [ktbyers/netmiko#594]
@ktbyers If pass a wrong show command in write channel and then try to read it using read channel. Does it display the error message?? I cant get a clear working knowledge of these commands.

**Comment by ktbyers** [comment]
@hardcorecoder27 Thanks for opening new issue :-)

Yes, you will retrieve the output that is displayed on the screen.

But...make sure you follow your show command with '\n' (or you won't have hit enter...so there won't be any output to see except for the character echo of the command and possibly the original prompt).

Also, make sure you sleep some amount of time before you try to read the output (as your script will be faster than the router).

**Comment by hardcorecoder27** [comment]
Thanks a lot...Its pretty clear now.
