### ISSUE TITLE
TypeError when doing send_config_set on arista

### ISSUE THREAD

**Issue by solotronics** [ktbyers/netmiko#595]
When doing send_config_set on Arista EOS I get this TypeError

Thanks!
-Gene

`>>> test2 = spawn_arista_netmiko(ip='10.198.203.7',user=usr,password=pw)`
`>>> r1 = test2.send_config_set('management api http-commands','no protocol http','protocol` `https','no shutdown')`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/share/virtualenv_networking/lib/python2.7/site-packages/netmiko/base_connection.py", line 972, in send_config_set`
`    time.sleep(delay_factor * .5)`
`TypeError: can't multiply sequence by non-int of type 'float'`

**Comment by hazelfire5** [comment]
What is going on within the function spawn_arista_netmiko()? I think what you are trying to do is something sort of like below:
```
from netmiko import ConnectHandler

net_connect = ConnectHandler(**device)

device = {
	'device_type':'arista_eos',
	'ip':'10.198.203.7',
	'username':usr,
	'password':pw
}

configset = ['management api http-commands','no protocol http','protocol https','no shutdown']

output = net_connect.send_config_set(configset)

print output
```
A TypeError due to multiplying a delay_factor seems like something was improperly configured on set up options.
