### ISSUE TITLE
net_connect.enable() not working and throws the error  - netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by tamsel2017** [ktbyers/netmiko#598]
I am facing net_connect.enable() issue with the following timeout exception error in Dell Force10 switch:

Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__version__
u'1.4.3'
>>> dell_switch = {  'device_type': 'dell_force10', 'ip' : 'x.x.x.x',   'username': 'xxxx', 'password': 'xxxx'}
>>> net_connect = ConnectHandler(**dell_switch)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ConnectHandler' is not defined
>>> from netmiko import ConnectHandler
>>> net_connect = ConnectHandler(**dell_switch)
>>> net_connect.enable()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/netmiko/cisco_base_connection.py", line 17, in enable
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 891, in enable
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 364, in read_until_prompt
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 320, in _read_channel_expect
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

Please let me know if this is a limitation in the Switch or any bug ?

**Comment by tamsel2017** [comment]
When I pass an individual command - "show ip int brief" it is working and am able to print the output. Please see the below output:

>>> from netmiko import ConnectHandler

>>> dell_switch = {  'device_type': 'dell_force10', 'ip' : 'x.x.x.x',   'username': 'xxxxx', 'password': 'xxxxx' , 'verbose' : True}

>>> net_connect = ConnectHandler(**dell_switch)
SSH connection established to xx.xx.xx.xx
Interactive SSH session established

>>> output = net_connect.send_command('show ip int brief')

>>> print output
Interface                     IP-Address      OK  Method Status                Protocol
TenGigabitEthernet 1/1        unassigned      NO  Manual up                    down
TenGigabitEthernet 1/2        unassigned      NO  Manual administratively down down
TenGigabitEthernet 1/3        unassigned      NO  Manual up                    down
TenGigabitEthernet 1/4        unassigned      NO  Manual administratively down down
TenGigabitEthernet 1/5        unassigned      NO  Manual up                    down
TenGigabitEthernet 1/6        unassigned      NO  Manual up                    down
TenGigabitEthernet 1/7        unassigned      NO  Manual up                    down
TenGigabitEthernet 1/8        unassigned      NO  Manual administratively down down
TenGigabitEthernet 1/9        unassigned      NO  Manual administratively down down

**Comment by ktbyers** [comment]
@tamsel2017 What does it look like on the CLI when you login and go into enable mode?

Can you copy and paste the CLI session here (for logging in / entering enable mode)?


Kirk

**Comment by tamsel2017** [comment]
Hi Kirk,

Please find the CLI session for logon / enable mode.

Thanks,
Tam

=================================================================
xxxx@login-01:~$ telnet xx.xx.xx.xx
Trying xx.xx.xx.xx...
Connected to xx.xx.xx.xx.
Escape character is '^]'.
Login: user_id
Password: 
test-switch-xxx>enable
Password:

Here is a MOTD banner displayed while logon.

test-switch-xxxx#
test-switch-xxxx#
=================================================================

**Comment by ktbyers** [comment]
@tamsel2017 Is that what the MOTD actually says? Is there a reason you switched to telnet there?


Kirk

**Comment by tamsel2017** [comment]
Hi Kirk,

I tried duplicating the issue using telnet, unfortunately I didnt used SSH. 

I resolved the issue. I missed sending the "enable" password for the Switch in the below dictionary and it was failing when I sent the net_connect.enable(). I included the 'secret' : 'xxxx' and  it started working.

dell_switch = { 'device_type': 'dell_force10', 'ip' : 'x.x.x.x', 'username': 'xxxx', 'password': 'xxxx'}

Thanks,
Tam

**Comment by mdanish101** [comment]
Hi Guys , 
I am going through the same issue . 
I have supplied multiple enable secrets via a list and I want to know which one is correct enable secret . 
But the problem is when any incorrect enable secret is passed in net_connect.enable() it is throwing error. 
How can I skip the error and continue loop execution ?


var=['cisco123','cisco']
for i in var:
    new_rtr = {
 'device_type': 'cisco_ios_telnet',
 'ip': '10.10.10.1'
 'username': 'cisco',
 'password': 'cisco',
 'secret': i
     }
    net_connect=ConnectHandler(**new_rtr)
    output= net_connect.enable()
    print(output)

**Comment by mdanish101** [comment]
My router correct enable secret is 'cisco' , but script is throwing error when it is picking 'cisco123' . Any way to come out of this problem?

**Comment by ktbyers** [comment]
You are setting it the variable `i` here:

```
'secret': i
```

So it is going to be what you set it to. If you want it to be 'cisco123' then:

```
'secret': 'cisco123'
```

You probably should complete remove your `for` loop.

**Comment by mdanish101** [comment]
Thanks Kirk , 
Purpose of my code : I have supplied multiple enable secrets via a list and I want to know which one is correct enable secret . That is the reason I am using 'for' loop . Now problem is when first wrong enable secret is selected my code throwing error but I want to skip this error and continue loop execution for other available passwords in list.

**Comment by ktbyers** [comment]
@mdanish101 Use a Python `try / except` statement to catch the exception and then move onto the next secret.
