### ISSUE TITLE
Netmiko: ConnectHandler() method is taking almost 7 to 8 seconds. Is this expected?

### ISSUE THREAD

**Issue by dpasupathi** [ktbyers/netmiko#599]
Hi,

I am trying to use the Netmiko ssh for Brocade_Netiron device and we consistently see that the ConnectHander() method takes 7-8 sec? Is there a way we can tune some parameters to get better result or is this expected?

**Comment by ktbyers** [comment]
@dpasupathi Can you give more context on what you are doing (i.e. post your code or make reference to it).

Screen-scraping (and APIs for that matter) are probably going to be a bit slow...so 7 seconds doesn't sound all that out of the ordinary.

How are you using it (just trying to get a better understanding on why the 7 seconds matters in your context)?

Hopefully, in Netmiko 1.5.0 I will have a better mechanism to make it go somewhat faster. Currently it is probably challenging, but if you post your code, I can probably make some suggestions.

**Comment by dpasupathi** [comment]
@ktbyers :  My use case is very simple but bunch of actions which configures the switches and comes out i.e connect to the switch, execute few commands and come out.  But the problem comes i will be using this consecutive workflows in a script. Here i end up connecting to the switch multiple times. Given the limitation in my framework is there a way i can improve the ssh connection less than 7 sec?
========== My code snippet as follows =============
opt = {'device_type': 'brocade_netiron'}
            opt['ip'] = self.host
            opt['username'] = self._auth[0]
            opt['password'] = self._auth[1]
            opt['global_delay_factor'] = 0.5
            net_connect = None
            net_connect = ConnectHandler(**opt)
===========================

**Comment by ktbyers** [comment]
@dpasupathi Is there a reason why you don't leave the connection open?

You are probably going to have a hard time getting it to be much less than 7 seconds (and have it work reliably) for those series of actions.

You can try modifying both `global_delay_factor` and `delay_factor` (if you are using `send_command` or `send_command_timing` methods).

You could try values of .25 and .5 and see if it improves your situation or not.

**Comment by dpasupathi** [comment]
@ktbyers: I tried the global_delay_factor but of no improvement. Wondering if there is any python based connection manager which can persist the connection pool and manage it.  So that instead of creating connection every time i can get it from cache.

**Comment by ktbyers** [comment]
You can just save your connection objects and then reuse them. So store them in a dictionary where the key is some identifier to the device. Then retrieve the connection and use it.

**Comment by xavierhardy** [comment]
There's an issue, some delay factors are indeed hardcoded, causing the delay, take a look at my issue please: #714.

**Comment by ktbyers** [comment]
@xavierhardy It is unlikely that #714 is directly related to this (at least in a significant way).

On Cisco IOS I can execute show commands using Netmiko on the order of 2-3 seconds and Brocade NetIron shares the Cisco connection code.

The 2-3 second delay I see with Cisco IOS is to be expected. I will comment about that more in issue #714.

**Comment by ninjaboss69** [comment]
> it

i do exactly like that, but when i reused the objects, i am getting error like "Socket is closed".

**Comment by ninjaboss69** [comment]
> You can just save your connection objects and then reuse them. So store them in a dictionary where the key is some identifier to the device. Then retrieve the connection and use it.

i do exactly like that, but when i reused the objects, i am getting error like "Socket is closed".
