### ISSUE TITLE
Design spec for Junos and IOS-XR on commit/confirm/rollback

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#60]
This issue will be the design spec for Junos and IOS-XR on commit/confirm/rollback

What needs to be included here (please add items I am missing):

1. Standard commit (no confirm):
     a. Messages on exit when no commit (JunOS and IOS-XR are opposite here)

2. Commit with confirm
     a. Should have a parameter for how many minutes the confirm must come in

3. Rollback
     a. Default is rollback 0. Should have a parameter for rollback number

4. Lock / unlock mechanism

5. Juniper Private config mechanism

6. Should be probably cover / consider new Arista commit/confirm/locking mechanism.

7. Unit tests including (Junos and IOS-XR where appropriate)
     a. commit
     b. rollback
     c. failed commit / no commit
     d. commit confirm
     e. lock / unlock
     f. Juniper shared / exclusive / private
     g. IOX-XR exclusive
     h. commit message

**Comment by ktbyers** [comment]
Other references issues, issue #57 (commit confirm).

**Comment by supertylerc** [comment]
There is also an IOS XR and Junos `configure exclusive` to lock the candidate config from other users.

**Comment by ktbyers** [comment]
commit() is currently a separate method both for Juniper and IOS-XR.

For Juniper it has a delay_factor attribute which defaults to 10 (give sufficient time for commit to complete. 

It is also used by send_config_set(). Note, send_config_set() has no way to modify the delay_factor.

IOS-XR currently has no delay_factor.

**Comment by ktbyers** [comment]
commit() method parameters should have:

# JUNIPER
delay_factor      (integer)
confirm              (boolean)
confirm_delay   (how many minutes to wait for confirm, defaults to 10) -- need to verify what default is for IOX-XR
check                 (boolean), defaults to False, has precedence over confirm (i.e. if check = True) then confirm is N/A.
comment            Message to commit log

Do we need 'commit at ?'  -- I would say probably not as a person could always manually do something via send_command(), if needed (open to discussion on this)

**Comment by supertylerc** [comment]
I think `send_config_set()` should not call `commit()`.  "Do one thing and do it well."  IMHO (and feel free to disagree since you're the creator/maintainer :)), this should be a framework around which solutions are built.  Trying to do too much magic overcomplicates said framework and potentially reduces its flexibility for building tools.

**Comment by supertylerc** [comment]
Also, one issue to be aware of is what happens if someone calls it like this:

`commit(delay_factor=10, confirm_delay=5)`

`confirm` will need to be set to `True` any time `confirm_delay` is used but `check` is not.

**Comment by ktbyers** [comment]
I agree on the send_config_set(), commit should not be a part of this.  Besides your "do one thing well statement" which I agree with. It also will really complicate the passing of arguments for commit.

**Comment by ktbyers** [comment]
commit(delay_factor=10, confirm_delay=5) --> should generate an exception

So confirm_delay will need to default to None (good point on this). We can then use the platform's default confirm_delay (i.e. only pass in a confirm_delay if the end-user specified an argument). This is a better way to do it.

commit(confirm=True, delay_factor=10) --> send to juniper  'commit confirmed'

commit(confirm=True, confirm_delay=5, delay_factor=10) --> send to Juniper 'commit confirmed 5' 

Let me know if you see issues with this.

**Comment by supertylerc** [comment]
Looks good to me.

**Comment by ktbyers** [comment]
Juniper is done. Still need to do IOS-XR.

**Comment by ktbyers** [comment]
Closing this issue. See issue #89 for IOS-XR.
