### ISSUE TITLE
Context manager exception handling issues

### ISSUE THREAD

**Issue by markgoddard** [ktbyers/netmiko#601]
Create a connection using a `with` context manager, and raise an exception that takes multiple arguments within the context:

```
import netmiko

class MyException(Exception):
    def __init__(self, a, b):
        pass

with netmiko.ConnectHandler(...) as c:
    raise MyException(1, 2)
```
We see the following exception:

```
Traceback (most recent call last):
  File "t.py", line 8, in <module>
    raise MyException(1, 2)
  File "/home/stack/ngs-stress/venv/lib/python2.7/site-packages/netmiko/base_connection.py", line 166, in __exit__
    raise exc_type(exc_value)
TypeError: __init__() takes exactly 3 arguments (2 given)
```

Two problems:
1. The `__exit__()` method of `netmiko.BaseConnection` should just `raise exc_value` in order to reraise.
2. The `__exit__()` method of `netmiko.BaseConnection` should return, and python will reraise the exception automatically.

**Comment by ktbyers** [comment]
Feel free to create a PR on it...or I will fix.

**Comment by markgoddard** [comment]
I'll create a PR in the next day or two.
