### ISSUE TITLE
Issue when trying to use copy FTP Command with Nexus Switches

### ISSUE THREAD

**Issue by mrkcmo** [ktbyers/netmiko#603]
I am trying to do the following which is to upload an NXOS image to a Nexus switch if the image doesn't exist or to recognize if it does exist already in flash. Here is the code:

```
output = device.send_command('copy ftp://%s@%s/%s bootflash:/%s vrf management'% (ftpuser, ftpserver, oldimage, oldimage), max_loops=1000, delay_factor=20)
if 'Switch is booted' in output:
    sys.stderr.write('Step 2b: Old Image Already Present and Set for Boot\n')
elif 'Warning:' in output:
    sys.stderr.write('Step 2b: Old Image Already Present\n')
    output += device_send_command('n\r')
elif 'Password: ' in output:
    sys.stderr.write('Step 2b: FTP Password needed and sent\n')
    output += device.send_command('%s\r'% ftppassword)
 print(output)
```
[code.txt](https://github.com/ktbyers/netmiko/files/1392450/code.txt)

The issue I am having is that the first two conditions work and return correctly but if I need to do the FTP of the image the "Password:" prompt is never found and therefore never sends the password. It just eventually times out. Any help would be great!

Thanks!

Chris

**Comment by mrkcmo** [comment]
@ktbyers  Any thoughts?

**Comment by ktbyers** [comment]
Old issue, but solution to this is to use the expect_string argument to send_command or alternatively use send_command_timing and some additional logic.
