### ISSUE TITLE
Allow a way in send_config_set to change the expected_prompt that comes back

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#604]

**Comment by Sandeepsr** [comment]
@ktbyers , is there a fix going to come soon for this?

**Comment by ktbyers** [comment]
@Sandeepsr Can you explain your use case where this is causing you an issue?

**Comment by Sandeepsr** [comment]
@ktbyers , I am not sure if my issue was entirely related to this bug. But I had problems with cisco XR while entering admin mode , as it changes the prompt when we send the command 'admin'.

Did something this to fix, no more a issue.
self.connection.send_command('admin', expect_string=search_pattern)

**Comment by ktbyers** [comment]
@Sandeepsr Yes, I am probably not handing `admin` mode on IOS-XR.

I wonder if this would work:

```
net_connect.send_command_timing(admin)
net_connect.set_base_prompt()
```
