### ISSUE TITLE
AdTran Support?

### ISSUE THREAD

**Issue by bgile** [ktbyers/netmiko#607]
Hi Kirk

I have seen a couple posts about you messing with AdTran CLI and what to expect back.  Has anything been implemented to effectively send commands to an AdTran device?  If not, do you have suggestions on how one might go about this?  We use a lot of AdTran gear and I would love to extend the functionality of Netmiko to AdTran CLI. 

Thanks

**Comment by ktbyers** [comment]
If it is close enough to Cisco IOS, it might work using a `device_type='cisco_ios'`.

For more details on adding a new vendor see:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md

**Comment by bgile** [comment]
Thanks for the info!
