### ISSUE TITLE
Problems with send_command() on Huawei

### ISSUE THREAD

**Issue by oysteingy** [ktbyers/netmiko#609]
Hi, 

Thanks for the nice API.

I'm experiencing some problems with send_command on Huawei:
VRP (R) software, Version 5.160 (NE40E&80E V600R008C10SPC300)
```python
>>> huawei = {'device_type': 'huawei', 'ip':   '10.129.194.12', 'username': 'user', 'password':  'pass', 'port': 22,  'verbose': True}
>>> net_connect = ConnectHandler(**huawei)
>>> net_connect.find_prompt()
u'<TST2PE6>'
>>> net_connect.send_command("display current-configuration")
u"                 ^\nError: Unrecognized command found at '^' position."
'''

I've enabled logging;


>>> logging.basicConfig(filename='test.log', level=logging.DEBUG)



DEBUG:netmiko:Pattern found: TST2PE6 screen-length 0 temporary
         ^
Error: Unrecognized command found at '^' position.
<TST2PE6>

DEBUG:netmiko:screen-length 0 temporary
         ^
Error: Unrecognized command found at '^' position.
<TST2PE6>
DEBUG:netmiko:write_channel: display current-configuration
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: display current-configuration

Looks like the issue is "assymetric" ? send_config_set() works perfectly, this appears to be a problem to read from the terminal.

**Comment by ktbyers** [comment]
@oysteingy What happens if you set the global_delay_factor?

```
huawei = {
    'device_type': 'huawei', 
    'ip': '10.129.194.12', 
    'username': 'user', 
    'password': 'pass', 
    'global_delay_factor': 2,          # Try 2, 4 and and 8
    'port': 22, 
    'verbose': True}
net_connect = ConnectHandler(**huawei)
```

**Comment by oysteingy** [comment]
`
>>> huawei = {'device_type': 'huawei', 'ip': '10.129.194.12', 'username': 'user', 'password': 'pass, 'verbose': True, 'global_delay_factor' : 8}
>>> net_connect = ConnectHandler(**huawei)
SSH connection established to 10.219.94.12:22
Interactive SSH session established
>>> net_connect.send_command("display current-configuration")
u"                 ^\nError: Unrecognized command found at '^' position."

`

**Comment by oysteingy** [comment]
(Sorry, hit the 'Close and comment' button instead of 'Comment')

**Comment by corvis84** [comment]
Hello,
Any update on this topic ? I'm starting to use netmiko to interact with Huawei devices MA5600T Series OLTs and I'm facing the exact same issue.

**Comment by ktbyers** [comment]
@corvis84 Can you enable the session_log and show what you are seeing?

You would enable the session_log using code similar to this:

```python
huawei = {
    'device_type': 'huawei', 
    'ip':   '10.10.10.12', 
    'username': 'user', 
    'password':  'pass', 
    'session_log': 'output.txt',
}
net_connect = ConnectHandler(**huawei)
```

That should create a file named output.txt in the current working directory. Can you post the contents of that file here (you can obfuscate anything that is confidential).

**Comment by nyash** [comment]
Huawei SmartAX GPON/EPON devices do not use the same OS (Huawei VRP). It would be necessary to add a new handler just for these devices (SmartAX)

Things to note:

To automate It is necessary to run these commands after login (They only affect the current session):
_undo idle-timeout
undo smart 
undo interactive 
scroll 512_ 

Explaination:
_undo idle-timeout_ disables the idle timeout after which the session gets disconnected (by default its 5 min of inactivity)
_undo smart_ disables displaying of the command parameters.

Normally even if you type a full valid command it will display the possible parameters to which you need to press enter to proceed or type one of the additional possible parameters.

huawei#display current-configuration
{ <cr>|ont<K>|port<K>|section<K>|service-port<K>|simple<K>||<K> }:

with _undo smart_ after entering "display current-configuration" it would instantly display the current config

undo interactive  this for example disables confirmation dialogs. 
huawei>quit
  Check whether system data has been changed. Please save data before logout.
Are you sure to log out? (y/n)[n]:

with "undo interactive" it would quit instantly

The most annoying part is that it is not possible to disable paging completely. We can increase the amount of data that gets displayed without paging by entering **scroll 512**.  The valid range for this command is 10 to 512 (24 being default)

For example if I display version:
huawei#display version

  VERSION : MA5600V800R015C10
  PATCH   : SPC101
  PRODUCT : MA5603T

  Active Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area B
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
  Program Area B Version : MA5600V800R015C10

  Data Area A Version : MA5600V800R015C10
  Data Area B Version : MA5600V800R015C10
  --------------------------------------------------

  Standby Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area A
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
---- More ( Press 'Q' to break ) ----

It ends with ---- More ( Press 'Q' to break ) ---- to which you can press spacebar to fetch next X lines defined by _scroll X_ command, Q to stop, or any other button to fetch just one additional line.

Here's a brief session from one device (SSH):

--connected--
huawei>enable
huawei#config
huawei(config)#dba-profile add profile-name ftth_dba type3 assure 8192 max 20480 
huawei(config)#ont-lineprofile gpon profile-name ftth 
huawei(config-gpon-lineprofile-1)#tcont 4 dba-profile-name ftth_dba 
huawei(config-gpon-lineprofile-1)#gem add 11 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 12 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 13 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 14 eth tcont 4
huawei(config-gpon-lineprofile-1)#commit 
huawei(config-gpon-lineprofile-1)#quit 
huawei(config)#quit
huawei>quit
--disconnected--

For telnet, the initial login prompt is:

Warning: Telnet is not a secure protocol, and it is recommended to use Stelnet.

**>>User name:**myusername
**>>User password:**mypass

**Comment by nyash** [comment]
> 
> 
> Hello,
> Any update on this topic ? I'm starting to use netmiko to interact with Huawei devices MA5600T Series OLTs and I'm facing the exact same issue.

Huawei SmartAX GPON/EPON devices do not use the same OS (Huawei VRP). It would be necessary to add a new handler just for these devices (SmartAX)

Things to note:

To ease automation It is necessary to run these commands after login (They only affect the current connected session):

**undo idle-timeout
undo smart 
undo interactive 
scroll 512**

Explaination:

_**undo idle-timeout**_ disables the idle timeout after which the session gets disconnected (by default its 5 min of inactivity)
_**undo smart**_ disables displaying of the command parameters.

Normally even if you type a full valid command it will display the possible parameters to which you need to press enter to proceed or type one of the additional possible parameters.

```
huawei#display current-configuration
{ <cr>|ont<K>|port<K>|section<K>|service-port<K>|simple<K>||<K> }:
```

with _**undo smart**_ after entering "display current-configuration" it would instantly display the current config

_**undo interactive**_  this for example disables confirmation dialogs. 
```
huawei>quit
  Check whether system data has been changed. Please save data before logout.
Are you sure to log out? (y/n)[n]:
```

with _**undo interactive**_ typed in before it would quit instantly

The most annoying part is that it is not possible to disable paging completely. We can increase the amount of data that gets displayed without paging by entering **scroll 512**.  The valid range for this command is 10 to 512 (24 being default)

For example if I display version:
```
huawei#display version

  VERSION : MA5600V800R015C10
  PATCH   : SPC101
  PRODUCT : MA5603T

  Active Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area B
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
  Program Area B Version : MA5600V800R015C10

  Data Area A Version : MA5600V800R015C10
  Data Area B Version : MA5600V800R015C10
  --------------------------------------------------

  Standby Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area A
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
---- More ( Press 'Q' to break ) ----
```

It ends with ---- More ( Press 'Q' to break ) ---- to which you can press **spacebar** to fetch next X lines defined by _scroll X_ command, Q to stop, or any other button to fetch just one additional line.

Here's a brief session from one device (SSH):

```
--connected--
huawei>undo idle-timeout
huawei>undo smart 
  Interactive function is disabled
huawei>undo interactive 
  Interactive function is disabled
huawei>scroll 512
huawei>enable
huawei#config
huawei(config)#dba-profile add profile-name ftth_dba type3 assure 8192 max 20480 
huawei(config)#ont-lineprofile gpon profile-name ftth 
huawei(config-gpon-lineprofile-1)#tcont 4 dba-profile-name ftth_dba 
huawei(config-gpon-lineprofile-1)#gem add 11 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 12 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 13 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 14 eth tcont 4
huawei(config-gpon-lineprofile-1)#commit 
huawei(config-gpon-lineprofile-1)#quit 
huawei(config)#quit
huawei>quit
--disconnected--
```

For telnet, the initial login prompt is:

```
Warning: Telnet is not a secure protocol, and it is recommended to use Stelnet.

>>User name:myusername
>>User password:mypass
```
Hope this will be helpful if someone wants to implement it.

**Comment by nyash** [comment]
Huawei SmartAX GPON/EPON devices do not use the same OS (Huawei VRP). It would be necessary to add a new handler just for these devices (SmartAX)

Things to note:

To ease automation It is necessary to run these commands after login (They only affect the current connected session):

**undo idle-timeout
undo smart 
undo interactive 
scroll 512**

Explaination:

_**undo idle-timeout**_ disables the idle timeout after which the session gets disconnected (by default its 5 min of inactivity)
_**undo smart**_ disables displaying of the command parameters.

Normally even if you type a full valid command it will display the possible parameters to which you need to press enter to proceed or type one of the additional possible parameters.

```
huawei#display current-configuration
{ <cr>|ont<K>|port<K>|section<K>|service-port<K>|simple<K>||<K> }:
```

with _**undo smart**_ after entering "display current-configuration" it would instantly display the current config

_**undo interactive**_  this for example disables confirmation dialogs. 
```
huawei>quit
  Check whether system data has been changed. Please save data before logout.
Are you sure to log out? (y/n)[n]:
```

with _**undo interactive**_ typed in before it would quit instantly

_**scroll 512**_ defines the amount of that that gets displayed without paging. Note that it is is not possible to disable paging completely! We can increase the amount of data that gets displayed without paging by entering **scroll 512**.  The valid range for this command is 10 to 512 (24 being default).

It is also possible to type "undo scroll". In the manual it says that this disables automatic scrolling so it would fetch just the default 24 lines and you need to use spacebar to fetch next lines.

For example if I display version (without previous modification by scroll command):
```
huawei#display version

  VERSION : MA5600V800R015C10
  PATCH   : SPC101
  PRODUCT : MA5603T

  Active Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area B
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
  Program Area B Version : MA5600V800R015C10

  Data Area A Version : MA5600V800R015C10
  Data Area B Version : MA5600V800R015C10
  --------------------------------------------------

  Standby Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area A
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
---- More ( Press 'Q' to break ) ----
```

It ends with ---- More ( Press 'Q' to break ) ---- to which you can press **spacebar** to fetch next X lines defined by _scroll X_ command, Q to stop, or Enter button to fetch just one additional line.

Here's a brief session from one device (SSH):

```
--connected--
huawei>undo idle-timeout
huawei>undo smart 
  Interactive function is disabled
huawei>undo interactive 
  Interactive function is disabled
huawei>scroll 512
huawei>enable
huawei#config
huawei(config)#dba-profile add profile-name ftth_dba type3 assure 8192 max 20480 
huawei(config)#ont-lineprofile gpon profile-name ftth 
huawei(config-gpon-lineprofile-1)#tcont 4 dba-profile-name ftth_dba 
huawei(config-gpon-lineprofile-1)#gem add 11 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 12 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 13 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 14 eth tcont 4
huawei(config-gpon-lineprofile-1)#commit 
huawei(config-gpon-lineprofile-1)#quit 
huawei(config)#quit
huawei>quit
--disconnected--
```

For telnet, the initial login prompt is:

```
Warning: Telnet is not a secure protocol, and it is recommended to use Stelnet.

>>User name:myusername
>>User password:mypass
```
Hope this will be helpful if someone wants to implement it.

**Comment by nyash** [comment]
> 
> 
> Hello,
> Any update on this topic ? I'm starting to use netmiko to interact with Huawei devices MA5600T Series OLTs and I'm facing the exact same issue.

> 
> 
> @corvis84 Can you enable the session_log and show what you are seeing?
> 
> You would enable the session_log using code similar to this:
> 
> ```python
> huawei = {
>     'device_type': 'huawei', 
>     'ip':   '10.10.10.12', 
>     'username': 'user', 
>     'password':  'pass', 
>     'session_log': 'output.txt',
> }
> net_connect = ConnectHandler(**huawei)
> ```
> 
> That should create a file named output.txt in the current working directory. Can you post the contents of that file here (you can obfuscate anything that is confidential).

Huawei SmartAX GPON/EPON devices do not use the same OS (Huawei VRP). It would be necessary to add a new handler just for these devices (SmartAX)

Things to note:

To ease automation It is necessary to run these commands after login (They only affect the current connected session):

**undo idle-timeout
undo smart 
undo interactive 
scroll 512**

Explaination:

_**undo idle-timeout**_ disables the idle timeout after which the session gets disconnected (by default its 5 min of inactivity)
_**undo smart**_ disables displaying of the command parameters.

Normally even if you type a full valid command it will display the possible parameters to which you need to press enter to proceed or type one of the additional possible parameters.

```
huawei#display current-configuration
{ <cr>|ont<K>|port<K>|section<K>|service-port<K>|simple<K>||<K> }:
```

with _**undo smart**_ after entering "display current-configuration" it would instantly display the current config

_**undo interactive**_  this for example disables confirmation dialogs. 
```
huawei>quit
  Check whether system data has been changed. Please save data before logout.
Are you sure to log out? (y/n)[n]:
```

with _**undo interactive**_ typed in before it would quit instantly

_**scroll 512**_ defines the amount of that that gets displayed without paging. Note that it is is not possible to disable paging completely! We can increase the amount of data that gets displayed without paging by entering **scroll 512**.  The valid range for this command is 10 to 512 (default 24).

The default is "undo scroll". In the manual it says that this disables automatic scrolling so it would fetch just the default 24 lines and you need to use spacebar to fetch next lines.

For example if I display version (without previous modification by scroll command):
```
huawei#display version

  VERSION : MA5600V800R015C10
  PATCH   : SPC101
  PRODUCT : MA5603T

  Active Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area B
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
  Program Area B Version : MA5600V800R015C10

  Data Area A Version : MA5600V800R015C10
  Data Area B Version : MA5600V800R015C10
  --------------------------------------------------

  Standby Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area A
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
---- More ( Press 'Q' to break ) ----
```

It ends with ---- More ( Press 'Q' to break ) ---- to which you can press **spacebar** to fetch next X lines defined by _scroll X_ command, Q to stop, or Enter button to fetch just one additional line.

Here's a brief session from one device (SSH):

```
--connected--
huawei>undo idle-timeout
huawei>undo smart 
  Interactive function is disabled
huawei>undo interactive 
  Interactive function is disabled
huawei>scroll 512
huawei>enable
huawei#config
huawei(config)#dba-profile add profile-name ftth_dba type3 assure 8192 max 20480 
huawei(config)#ont-lineprofile gpon profile-name ftth 
huawei(config-gpon-lineprofile-1)#tcont 4 dba-profile-name ftth_dba 
huawei(config-gpon-lineprofile-1)#gem add 11 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 12 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 13 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 14 eth tcont 4
huawei(config-gpon-lineprofile-1)#commit 
huawei(config-gpon-lineprofile-1)#quit 
huawei(config)#display version 

  VERSION : MA5600V800R015C10
  PATCH   : SPC101
  PRODUCT : MA5603T

  Active Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area B
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
  Program Area B Version : MA5600V800R015C10

  Data Area A Version : MA5600V800R015C10
  Data Area B Version : MA5600V800R015C10
  --------------------------------------------------

  Standby Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area A
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
  Program Area B Version : MA5600V800R015C10

  Data Area A Version : MA5600V800R015C10
  Data Area B Version : MA5600V800R015C10
  --------------------------------------------------

  Uptime is 82 day(s), 15 hour(s), 1 minute(s), 14 second(s)

huawei(config)#quit
huawei>quit
--disconnected--
```

For telnet, the initial login prompt is:

```
Warning: Telnet is not a secure protocol, and it is recommended to use Stelnet.

>>User name:myusername
>>User password:mypass
```
Hope this will be helpful if someone wants to implement it.

**Comment by nyash** [comment]
> 
> 
> Hello,
> Any update on this topic ? I'm starting to use netmiko to interact with Huawei devices MA5600T Series OLTs and I'm facing the exact same issue.

> 
> 
> @corvis84 Can you enable the session_log and show what you are seeing?
> 
> You would enable the session_log using code similar to this:
> 
> ```python
> huawei = {
>     'device_type': 'huawei', 
>     'ip':   '10.10.10.12', 
>     'username': 'user', 
>     'password':  'pass', 
>     'session_log': 'output.txt',
> }
> net_connect = ConnectHandler(**huawei)
> ```
> 
> That should create a file named output.txt in the current working directory. Can you post the contents of that file here (you can obfuscate anything that is confidential).

Huawei SmartAX GPON/EPON devices do not use the same OS (Huawei VRP). It would be necessary to add a new handler just for these devices (SmartAX)

Things to note:

To ease automation It is necessary to run these commands after login (They only affect the current connected session):

**undo idle-timeout
undo smart 
undo interactive 
scroll 512**

Explaination:

_**undo idle-timeout**_ disables the idle timeout after which the session gets disconnected (by default its 5 min of inactivity)
_**undo smart**_ disables displaying of the command parameters.

Normally even if you type a full valid command it will display the possible parameters to which you need to press enter to proceed or type one of the additional possible parameters.

```
huawei#display current-configuration
{ <cr>|ont<K>|port<K>|section<K>|service-port<K>|simple<K>||<K> }:
```

with _**undo smart**_ after entering "display current-configuration" it would instantly display the current config

_**undo interactive**_  this for example disables confirmation dialogs. 
```
huawei>quit
  Check whether system data has been changed. Please save data before logout.
Are you sure to log out? (y/n)[n]:
```

with _**undo interactive**_ typed in before it would quit instantly

_**scroll 512**_ defines the amount of that that gets displayed without paging. Note that it is is not possible to disable paging completely! We can increase the amount of data that gets displayed without paging by entering **scroll 512**.  The valid range for this command is 10 to 512 (default 24).

The default is "undo scroll". In the manual it says that this disables automatic scrolling so it would fetch just the default 24 lines and you need to use spacebar to fetch next lines.

For example if I display version (without previous modification by scroll command):
```
huawei#display version

  VERSION : MA5600V800R015C10
  PATCH   : SPC101
  PRODUCT : MA5603T

  Active Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area B
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
  Program Area B Version : MA5600V800R015C10

  Data Area A Version : MA5600V800R015C10
  Data Area B Version : MA5600V800R015C10
  --------------------------------------------------

  Standby Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area A
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
---- More ( Press 'Q' to break ) ----
```

It ends with ---- More ( Press 'Q' to break ) ---- to which you can press **spacebar** to fetch next X lines defined by _scroll X_ command, Q to stop, or Enter button to fetch just one additional line.

Here's a brief session from one device (SSH):

```
--connected--
huawei>undo idle-timeout
huawei>undo smart 
  Interactive function is disabled
huawei>undo interactive 
  Interactive function is disabled
huawei>scroll 512
huawei>enable
huawei#config
huawei(config)#dba-profile add profile-name ftth_dba type3 assure 8192 max 20480 
huawei(config)#ont-lineprofile gpon profile-name ftth 
huawei(config-gpon-lineprofile-1)#tcont 4 dba-profile-name ftth_dba 
huawei(config-gpon-lineprofile-1)#gem add 11 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 12 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 13 eth tcont 4 
huawei(config-gpon-lineprofile-1)#gem add 14 eth tcont 4
huawei(config-gpon-lineprofile-1)#commit 
huawei(config-gpon-lineprofile-1)#quit 
huawei(config)#quit
huawei#display version 

  VERSION : MA5600V800R015C10
  PATCH   : SPC101
  PRODUCT : MA5603T

  Active Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area B
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
  Program Area B Version : MA5600V800R015C10

  Data Area A Version : MA5600V800R015C10
  Data Area B Version : MA5600V800R015C10
  --------------------------------------------------

  Standby Mainboard Running Area Information:
  --------------------------------------------------
  Current Program Area : Area A
  Current Data Area : Area A

  Program Area A Version : MA5600V800R015C10
  Program Area B Version : MA5600V800R015C10

  Data Area A Version : MA5600V800R015C10
  Data Area B Version : MA5600V800R015C10
  --------------------------------------------------

  Uptime is 82 day(s), 15 hour(s), 1 minute(s), 14 second(s) 

huawei#quit
--disconnected--
```

For telnet, the initial login prompt is:

```
Warning: Telnet is not a secure protocol, and it is recommended to use Stelnet.

>>User name:myusername
>>User password:mypass
```
Hope this will be helpful if someone wants to implement it.

**Comment by Stiwar0098** [comment]
Could you share the solution, I have the same problem with net_connect.send_command_timing(display current-configuration ont 0/2/4 17) Applying this net_connect.send_command_expect(display current-configuration ont 0/2/4 17)  I got the following  : 
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'display\\ current\\-configuration\\ ont\\ 0/2/4\\ 17' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

**Comment by ktbyers** [comment]
@Stiwar0098 You are trying to execute a show command while in configuration mode and that is causing a failure.

Note, this issue was closed 5+ years ago with the end-user not responding (i.e. you should create a new issue instead of commenting here).
