### ISSUE TITLE
Static Analysis

### ISSUE THREAD

**Issue by supertylerc** [ktbyers/netmiko#61]
Invest in static analysis tools which will help improve code readability, maintainability, and extensibility.

As an example, here's the final output of `pylint` against Netmiko's (current) master branch:

```
Global evaluation
-----------------
Your code has been rated at 6.08/10 (previous run: 6.08/10, +0.00)
```

Besides the CLI tool `pylint`, other tools that integrate with GitHub include:

* [Travis CI](https://travis-ci.org/recent)
* [Scrutinizer CI](https://scrutinizer-ci.com/)
* [Landscape](https://landscape.io)

There are many other tools, but those are ones I've used.  They do things like:

* Run unit tests for you
* Analyze code health
* Graph results over time
* Suggest ways to clean up code
* Review pull requests and perform all of the above for every pull request
* Review all branches

**Comment by yourteamneedsadam** [comment]
My vote on static analysis tools is [flake8](https://flake8.readthedocs.org/en/2.3.0/). It wraps PyFlakes, pep8, and mccabe.

@ktbyers If adding static analysis is something you want to do I'm happy to put together a PR. Just let me know if that's something you'd like in the project.

**Comment by ktbyers** [comment]
I am currently just using pylint. What is the advantage of using flake8?



On Thu, Jul 9, 2015 at 4:34 PM, Adam Burns <notifications@github.com> wrote:

> My vote on static analysis tools is flake8
> <https://flake8.readthedocs.org/en/2.3.0/>. It wraps PyFlakes, pep8, and
> mccabe.
>
> @ktbyers <https://github.com/ktbyers> If adding static analysis is
> something you want to do I'm happy to put together a PR. Just let me know
> if that's something you'd like in the project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/61#issuecomment-120174478>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by yourteamneedsadam** [comment]
It'll be a tradeoff - pylint seems to flag a broader range of things than PyFlakes (what flake8 uses under the hood), whereas PyFlakes has a reputation for being faster and simpler. Flake8 includes the mccabe script, which let's you flag parts of the code that have high complexity (e.g. too many nested loops and ifs to be readable).

**Comment by ktbyers** [comment]
Using Travis-CI. Probably will start using flake8 (have been mostly using pylint up to now).
