### ISSUE TITLE
Avaya VSP needs an enable

### ISSUE THREAD

**Issue by apepelis** [ktbyers/netmiko#619]
VSP-XXXX:1>enable
VSP-XXXX:1#

class AvayaVspSSH(CiscoSSHConnection):
    def session_preparation(self):
        """Prepare the session after the connection has been established."""
        self._test_channel_read()
        self.set_base_prompt()
        **self.send_command("enable", strip_prompt=False, auto_find_prompt=False)**
        self.disable_paging(command="terminal more disable\n")

**Comment by ktbyers** [comment]
@apepelis Does just calling the `enable()` method work:

```
net_connect = ConnectHandler(**device)
net_connect.enable()
```

You would pass in a `secret` argument in the `device` dictionary.

**Comment by apepelis** [comment]
I tried just an enabled originall and it didn't work. It paused because the prompt changing or something. I can try running it again with just an enable. I only got it to work with the options above.

**Comment by ktbyers** [comment]
@apepelis Can you show me the error you get on the `enable()` call?

**Comment by apepelis** [comment]
strike that. It was a versioning thing. Version 0.5.X that enable() wasn't working. 1.4.3 just adding an enable() works in the Avaya VSP class.
