### ISSUE TITLE
Strip Additional Juniper Prompts

### ISSUE THREAD

**Issue by supertylerc** [ktbyers/netmiko#62]
There are Juniper prompts that are currently not stripped from output.  See below.

```
 ❯ ssh 10.10.1.1
--- JUNOS 12.1X44-D25.5 built 2013-10-24 20:59:21 UTC
No alarms currently active

{primary:node0}
tyler@fw1.example.com> start shell
% rlogin -T node1
�
--- JUNOS 12.1X44-D25.5 built 2013-10-24 20:59:21 UTC

No alarms currently active

{secondary:node1}
tyler@fw1.example.com>
```

The method `strip_context_items()` does not currently strip these from output.  I will submit a PR for this.

**Comment by supertylerc** [comment]
It looks like the prompt isn't being stripped after running a command as well:

```
>>> ip_interfaces = dev.send_command("show interfaces terse | grep inet")
>>> print(ip_interfaces)

ge-0/0/0.0              up    up   inet     10.0.2.15/24
sp-0/0/0.0              up    up   inet
                                   inet6
sp-0/0/0.16383          up    up   inet     10.0.0.1            --> 10.0.0.16
ge-0/0/1.0              up    up   inet     172.16.0.1/31
ge-0/0/2.0              up    up   inet     192.168.0.200/24
lo0.16384               up    up   inet     127.0.0.1           --> 0/0
lo0.16385               up    up   inet     10.0.0.1            --> 0/0

ansible@apples>
>>>
```

**Comment by supertylerc** [comment]
This should've been mostly fixed by #63.  The only thing that isn't fixed is the presence of the final prompt.

**Comment by Ragsboss** [comment]
Hi Tyler, I'm seeing for EOS, the final prompt is present - but not always. Is this a known issue? I'm issuing a command that's producing JSON output and when the prompt is present, JSON parsing fails. We are using version 0.4.3 and target device is 

```
Arista DCS-7050QX-32-F
Hardware version:    02.11
Software image version: 4.16.6M
```

Any help is appreciated

**Comment by ktbyers** [comment]
@Ragsboss Please open a separate issue on this. You need to test the issue using Netmiko 1.1.
