### ISSUE TITLE
Login retry attempts for telnet method

### ISSUE THREAD

**Issue by zeepi222** [ktbyers/netmiko#621]
Hello,

I am connecting to a mix of SSH and Telnet enabled devices. 
I noticed that SSH method does not retry failed login attempts, whilst the telnet method will retry failed logins up to three times. I am concerned that multiple telnet failures could potentially lock out my TACACS account. 

Is it possible to control / set the number of login retry attempts used by the telnet method?

Example ...
```
In [29]: try:
    ...:         cli_session = ConnectHandler(ip="10.2.3.5",
    ...:                                      username="user1",
    ...:                                      password="passwd1",
    ...:                                      device_type="cisco_ios_telnet",
    ...:                                      port=23,
    ...:                                      verbose=True)
    ...:         print cli_session.find_prompt()
    ...:     
    ...: except Exception as err:
    ...:     logging.exception(err)
    ...:     
DEBUG:netmiko:read_channel: 

User Access Verification

Username: 
DEBUG:netmiko:write_channel: user1

DEBUG:netmiko:read_channel: user1
Password: 
DEBUG:netmiko:write_channel: passwd1

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
% Login invalid

Username: 
Username: 
Username: 
Username: 
Username: 
DEBUG:netmiko:write_channel: user1

DEBUG:netmiko:read_channel: user1
Password: 
DEBUG:netmiko:write_channel: passwd1

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
% Login invalid

Username: 
Username: 
Username: 
Username: 
Username: 
DEBUG:netmiko:write_channel: user1

DEBUG:netmiko:read_channel: user1
Password: 
DEBUG:netmiko:write_channel: passwd1

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
% Login invalid

DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

ERROR:root:Telnet login failed: 10.2.3.5
Traceback (most recent call last):
  File "<ipython-input-29-aa7d7a5876ce>", line 7, in <module>
    verbose=True)
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 129, in __init__
    self.establish_connection()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 525, in establish_connection
    self.telnet_login()
  File "/usr/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 114, in telnet_login
    raise NetMikoAuthenticationException(msg)
NetMikoAuthenticationException: Telnet login failed: 10.2.3.5

In [30]:
```

Thanks.

**Comment by ktbyers** [comment]
@zeepi222 

You can probably overwrite the telnet_login method and make a custom method (i.e. make a custom class and in that class create a telnet_login method). 

There will be certain reliability problems here if you reduce the number of attempts you try to login...so I am pretty reluctant to add that as an argument.

**Comment by zeepi222** [comment]
Thanks for confirming this was not a bug. I thought the fact that SSH raises an Exception after one authentication failure whilst telnet raises an Exception after three authentication failures was not intentional. It's useful to know that that login behaviours may not be consistent between protocols.
I will try your suggestion, thanks.

**Comment by ddisisto** [comment]
I've been looking into this also and found that it's `CiscoBaseConnection.telnet_login()` not noticing the error at all, it just sees the repeated Username: prompt following it, so goes ahead and keeps responding to it with the username (and then password) until `max_loops` is hit. There was one specific error message that was being matched, but in my PR this changes raise on anything that looks like an error.

**Comment by ddisisto** [comment]
I've submitted a new PR for this, which is a better and cleaner approach compared to my last effort. I still believe that any retries that occur should at least be controllable by the user, while the current implementation is unpredictable, being a factor of a) `max_loops` variable & b) how many loops are actually required get through the prompts on any given login attempt. 

Even better IMO is for the user to wrap the connection in a try/except and do their own retries if desired.

I hope it's not bad form to either comment on a closed issue or raise a new/replacement PR in this way, I'm still learning the ropes, so please feel free to let me know if so.
