### ISSUE TITLE
issue with connect.send_command

### ISSUE THREAD

**Issue by hardcorecoder27** [ktbyers/netmiko#626]
I have written script only to extract data of PID and Serial no of Cisco device[only the chassis] using "show inventory" 
Please find my code below.

connect.send_command("terminal length 2")
show_inventory1 = connect.send_command("show inventory")
fo = open('log.txt', "a")
fo.write(str(show_inventory1))

I know send_command will keep waiting to receive data until the network device prompt is detected.
All i need is the first two lines of output of "show inventory" command.
Is it possible?

It would be nice if you could correct me if my second line of code is wrong or give me the right piece of code.

If this can be done, it would also help me getting the version of Cisco IOS from the "show version" command.

**Comment by zeepi222** [comment]
Hi,

I think you may have more success, if you collect the full output of "show inventory" and "show version" using netmiko and then parse these output afterwards to extract the data fields you need.
There are python modules like pyparsing or TextFSM that can assist you with this.

Regards
Zee

**Comment by ktbyers** [comment]
@hardcorecoder27 The `terminal length 2` command will cause issues (as it will turn on the paging of output).

You should be able to just do:

```
show_inventory1 = connect.send_command("show inventory | inc PID")
```

**Comment by hardcorecoder27** [comment]
@ktbyers I am using python regular expressions to extract only the PID and serial number of the chassis.
That can be done using the second line of show inventory output. 

Show inventory | inc PID will give me the inventory of chassis as well as the internals of the device[which i dont want].

@zeepi222 i am using python regular expressions to extract data from the show version and show inventory output.

**Comment by ktbyers** [comment]
@hardcorecoder27 Yes, you get this back and then you process it using regular expressions or using .split()

```
$ show inventory | inc PID
PID: CISCO881-SEC-K9   , VID: V01 , SN: FTX0000038X
```

Do you have a question?

**Comment by hardcorecoder27** [comment]
When i give show inventory | inc PID. The output is not just one line that shows the details of just chassis, but also the second line that contains PID and SN of the internal parts. For example in 1921 router in the first line i get the chassis PID and SN and in the second line i get the PID and SN of HWIC-2T card.

All i need is the first line that contains chassis details.

Thanks for the suggestion. I will try .split(). :D

**Comment by ktbyers** [comment]
Can you post your `show inventory` output?

**Comment by hardcorecoder27** [comment]
Router#sh inventory
NAME: "CISCO1921/K9", DESCR: "CISCO1921/K9 chassis, Hw Serial#: ABHFY876GAJ, Hw Revision: 1.0"
PID: CISCO1921/K9      , VID: V05 , SN: ABHFY876GAJ
NAME: "Wan Interface Card BRI S/T (3086) on Slot 0 SubSlot 0", DESCR: "Wan Interface Card BRI S/T (3086)"
PID: WIC-1B-S/T-V3     , VID: V01 , SN: JIOHDF654JD
NAME: "WAN Interface Card - HWIC Serial 2T on Slot 0 SubSlot 1", DESCR: "WAN Interface Card - HWIC Serial 2T"
PID: HWIC-2T           , VID: V04 , SN: HGUV12HJFU
Router#sh inv | i PID
PID: CISCO1921/K9      , VID: V05 , SN: ABHFY876GAJ
PID: WIC-1B-S/T-V3     , VID: V01 , SN: JIOHDF654JD
PID: HWIC-2T           , VID: V04 , SN: HGUV12HJFU

**Comment by zeepi222** [comment]
Try;
match = re.search(r'PID:\s([A-Z0-9/]*).*SN:\s([A-Z0-9]*)', output, re.M)
PID = match.group(1)
SN = match.group(2)

where output is the contents of your show inventory output.

**Comment by hardcorecoder27** [comment]
Thanks alot @ktbyers . The re.search worked well.

**Comment by hardcorecoder27** [comment]
@zeepi222 I will try it and let you know.

**Comment by kelmarshall** [comment]
Do you have to add something in the beginning of the file?  I get the following error;
NameError: name 'connect' is not defined
show_inventory1 = connect.send_command("config extender-controller extender")

**Comment by ktbyers** [comment]
@kelmarshall Can you post your entire code (or at least the part before this where you are setting up the connection)?

**Comment by ktbyers** [comment]
It doesn't look like there is anything else to do here.
