### ISSUE TITLE
ssh gateway without proxyCommand

### ISSUE THREAD

**Issue by lodpp** [ktbyers/netmiko#633]
Hi,

This is a Question/Feature.

I'm in a case that I must use a jumphost/bastion ( or more ) to connect to the end devices.
proxyCommand is not working due to the fact that those bastion are not "neutral" is the ssh auth process.
My app just have to connect to the first bastion with given creds, and bastion are doing the magic ( even thought I could specify the next creds if needed ).

Path might be like:
myApp <-- user1 + key1 or pwd1 --> bastion1 <--user2 + key2 or pwd2--> bastion2 <--user3+ key3 or pwd3--> end device
or
myApp <-- user1 + key1 or pwd1 --> bastion1 <--user2+ key2 or pwd2--> end device

As of today I do this manually, ssh via bastion1 to bastion2 ( where I have a shell ) then ssh to the end device.
It works, but in an effort of automation, I would be able to use netmiko ( +ansible on top of it ) to connect to the end device by specifying the different gateways

Is there a way to do this with Netmiko ?

Best regards,
Lodpp

**Comment by ktbyers** [comment]
@lodpp Netmiko should support whatever `~/.ssh/config` supports so as long as you can get it working manually with that, then Netmiko should support it.

Note, I think for the intermediate `bastion` devices `~/.ssh/config` will require SSH keys and you won't be able to use passwords.

You could also try to programmatically do the logs for all of these along the chain, but it is going to be a lot harder.

Here is an article on SSH proxy in Netmiko
https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

Also see the Netmiko 1.4.0 release notes (as a few things changed).

**Comment by lodpp** [comment]
Thanks @ktbyers , I've already checked that post of yours ( that was the initial trigger to try using netmiko over the bastion I have :) )
Main thing and I should have stated it in the first post, It seems I can't use anything in ssh_config to act the gateway role without the proxyCommand that can't work :/
The only way I got is to start the "one liner" like : ssh -i path/to/idfile user@bastion1 -p xxxx -t -- user2@end-device and then do manually the config.

I know that it should be doable with proxyCommand, as explained both in ssh_config documentation and your article.
But as the bastion is in my case not "transparent" for security reason. ( I don't know what is running on the bastion for that purpose, I just need to live with it .... ) I'm 'stuck' 

So the request is, if I can formulate it that way: is it possible to tell netmiko to start the connection by mimicking the one-liner approach instead of the ssh_config file ?

**Comment by ktbyers** [comment]
@lodpp Netmiko can't start the one liner.

You could probably control the SSH session entirely through Netmiko, however. In other words use Netmiko to SSH from your machine to `bastion1` using the `linux` device_type. Then use Netmiko to execute another SSH session to the end device (you would need to manually handle the password here).

In other words, you would have netmiko execute something like `ssh -l admin 10.10.10.10` on the bastion. You would then have netmiko handle the password authentication.

After you logged in, you could call the Netmiko `redispatch()` to redispatch with the right end device type.

**Comment by lodpp** [comment]
Thanks @ktbyers for the lead, I'm testing this out asap

**Comment by ktbyers** [comment]
This is pretty much the same issue except she was using a router as the intermediate device to access an ASA:

https://github.com/ktbyers/netmiko/issues/470
