### ISSUE TITLE
Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by 929440925** [ktbyers/netmiko#634]
‘’‘ from django.shortcuts import render
from .models import Huawei, mingling
from netmiko import ConnectHandler
# Create your views here.

def index(request):
    hua_list = Huawei.objects.all()
    # hua_names = Huawei.hua_name
    for i in hua_list:
        ci = i.type
        ips = i.ip
        usernames = i.username
        passwords = i.password
        ports = i.port

        print(i.username)

        cisco = {
            'device_type': ci,
            'ip': ips,
            'username': usernames,
            'password': passwords,
            'port': ports,
        }
        net_connect = ConnectHandler(**cisco)
       # connect=net_connect.get_content_charset('utf-8')
        output = net_connect.send_command('ifconfig')
        if hasattr(output,'900'):
            return render(request, 'index.html', context={'hua_list': hua_list,
                                                          'msg': '有'
                                                          })
        else:
            return render(request, 'index.html', context={'hua_list': hua_list,
                                                          'msg': '没有'
                                                          })
        print(output)
’‘’
django==1.11.3
Huawei

![_20171122101701](https://user-images.githubusercontent.com/31470297/33106678-4c1d2fc2-cf6e-11e7-96e5-c8b7a6d8b553.png)

**Comment by ktbyers** [comment]
@929440925 It looks like it is probably a Paramiko issue. What version of Paramiko are you using?

```
pip list | grep paramiko
```

You also should probably try a Python script for the SSH outside of Django so you get a better stack trace.

**Comment by 929440925** [comment]
@ktbyers  paramiko (2.4.0)

**Comment by ktbyers** [comment]
Can you post the full stack trace from a Python perspective (i.e. take it out of Django and run the SSH connection part of your script directly from Python)?

**Comment by 929440925** [comment]
@ktbyers Thank you. The problem has been solved

**Comment by ktbyers** [comment]
What was it?

**Comment by zeepi222** [comment]
Was it related to an rsa certificate not being installed on the device?
