### ISSUE TITLE
Comware7 screen-length disable permission denied

### ISSUE THREAD

**Issue by etem** [ktbyers/netmiko#635]
Hello, 

When trying to use the script on Comware7 I see in the logs that it's getting "Permission denied" after executing "screen-length disable". The command works just fine if I log on to the switch and execute it manually. 

I've tried with net_connect.send_command('screen-length disable') but no luck.

**Comment by etem** [comment]
Sorry it was a configuration issue. I've fixed that with executing "super level-15" command before screen-length disable.

**Comment by ktbyers** [comment]
@etem Thanks...I think have an issue in that I am not going into "enable" mode i.e. `super level-15` before I execute the `screen-length disable` command.

I think this PR pertains to this:

https://github.com/ktbyers/netmiko/pull/624/files

And there might be a separate issue on this in Netmiko also.
