### ISSUE TITLE
netmiko telnet cisco router

### ISSUE THREAD

**Issue by redmage123** [ktbyers/netmiko#636]
Hi.  

What is the status of netmiko and telnet.  I've trying to connect to a virtual cisco router using dynamips on an ubuntu 16.04 system.  I saw that (supposedly) netmiko should work with telnet.  I've written some code that looks like this:

#!/usr/bin/env python3

from netmiko import ConnectHandler

cisco_7200 = {
              'device_type': 'cisco_ios_telnet',
              'ip': '127.0.0.1',
              'port':2015,
              'global_delay_factor':2,
}
net_connect = ConnectHandler(**cisco_7200)

Unfortunately, it come back with an error that it can't find the prompt.  

raceback (most recent call last):
  File "./netmiko_example.py", line 13, in <module>
    net_connect = ConnectHandler(**cisco_7200)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 130, in __init__
    self.session_preparation()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco/cisco_ios.py", line 11, in session_preparation
    self.set_base_prompt()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 672, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: '*Nov 22 22:47:40.047: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse from (tftp://255.255.255.255/router3-confg) failed'

Note that I can telnet into the router manually by simply doing telnet localhost 2015

**Comment by zeepi222** [comment]
What does the output look like when you manually telnet to the virtual router on port 2015 ?

**Comment by redmage123** [comment]
root@python-server1:~# telnet localhost 2015
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connected to Dynamips VM "R3" (ID 0, type c7200) - Console port
Press ENTER to get the prompt.
nfg (Timed out)
*Nov 22 23:03:28.067: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3-confg) failed
%Error opening tftp://255.255.255.255/router3.cfg (Timed out)
*Nov 22 23:04:06.071: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3.cfg) failed
%Error opening tftp://255.255.255.255/network-confg (Timed out)
*Nov 22 23:08:28.039: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/network-confg) failed
%Error opening tftp://255.255.255.255/cisconet.cfg (Timed out)
*Nov 22 23:09:06.043: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/cisconet.cfg) failed
%Error opening tftp://255.255.255.255/router3-confg (Timed out)
*Nov 22 23:09:44.071: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3-confg) failed
%Error opening tftp://255.255.255.255/router3.cfg (Timed out)
*Nov 22 23:10:22.075: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3.cfg) failed
%Error opening tftp://255.255.255.255/network-confg (Timed out)
*Nov 22 23:15:14.043: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/network-confg) failed
%Error opening tftp://255.255.255.255/cisconet.cfg (Timed out)
*Nov 22 23:15:52.047: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/cisconet.cfg) failed
%Error opening tftp://255.255.255.255/router3-confg (Timed out)
*Nov 22 23:16:30.075: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3-confg) failed
%Error opening tftp://255.255.255.255/router3.cfg (Timed out)
*Nov 22 23:17:08.079: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3.cfg) failed
%Error opening tftp://255.255.255.255/network-confg (Timed out)
*Nov 22 23:22:30.051: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/network-confg) failed
%Error opening tftp://255.255.255.255/cisconet.cfg (Timed out)
*Nov 22 23:23:08.055: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/cisconet.cfg) failed
%Error opening tftp://255.255.255.255/router3-confg (Timed out)
*Nov 22 23:23:46.079: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3-confg) failed
%Error opening tftp://255.255.255.255/router3.cfg (Timed out)
*Nov 22 23:24:24.083: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3.cfg) failed
%Error opening tftp://255.255.255.255/network-confg (Timed out)
*Nov 22 23:30:16.055: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/network-confg) failed
%Error opening tftp://255.255.255.255/cisconet.cfg (Timed out)
*Nov 22 23:30:54.059: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/cisconet.cfg) failed
%Error opening tftp://255.255.255.255/router3-confg (Timed out)
*Nov 22 23:31:32.083: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3-confg) failed
%Error opening tftp://255.255.255.255/router3.cfg (Timed out)
*Nov 22 23:32:10.083: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3.cfg) failed
%Error opening tftp://255.255.255.255/network-confg (Timed out)
*Nov 22 23:38:32.063: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/network-confg) failed
%Error opening tftp://255.255.255.255/cisconet.cfg (Timed out)
*Nov 22 23:39:10.067: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/cisconet.cfg) failed
%Error opening tftp://255.255.255.255/router3-confg (Timed out)
*Nov 22 23:39:48.083: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3-confg) failed
%Error opening tftp://255.255.255.255/router3.cfg (Timed out)
*Nov 22 23:40:26.087: %SYS-4-CONFIG_RESOLVE_FAILURE: System config parse
from (tftp://255.255.255.255/router3.cfg) failedxxtteerrmpp
         ^
% Invalid input detected at '^' marker.

router3#

**Comment by zeepi222** [comment]
Perhaps automatic config download is causing an issue. Can you disable service config and try again?

Router#config terminal
Enter configuration commands, one per line.  
Router(config)#no service config
Router(config)#exit
Router#copy running-config startup-config

**Comment by ktbyers** [comment]
Telnet support is fine. This looks like you are connecting via terminal server (GNS3 console, however). In other words, the above behavior is not the normal behavior for a Cisco router and telnet (which would prompt for a username/password).

You probably want to use the following device_type instead:  `generic_termserver_telnet`

You can then use `read_channel` and `write_channel` to read all of the extra messages on the screen and to hit enter (`\n`).

After you are fully logged in then you can use a redispatch to `cisco_ios_telnet`.

See this for more details:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#does-netmiko-support-connecting-via-a-terminal-server

**Comment by redmage123** [comment]
Hi.

Thanks for the info.  I've gotten a bit farther, but i'm still getting an
error about not finding the prompt.  i've modified my code accordingly...

import time

cisco_7200 = {
              'device_type': 'generic_termserver_telnet',
              'ip': '127.0.0.1',
              'port':2015,
}


net_connect = ConnectHandler(**cisco_7200)
net_connect.write_channel ('\r\n')
time.sleep(1)
net_connect.write_channel ('\r\n')
time.sleep(1)
output = net_connect.read_channel()
print (output)
net_connect.write_channel ('\r\n')
time.sleep(.5)

redispatch(net_connect, device_type = 'cisco_ios') # I've also tried
'cisco_ios_telnet'
new_output = net_connect.send_command('show ip int brief')

But I'm still getting the error:

Traceback (most recent call last):
  File "./netmiko_example.py", line 26, in <module>
    redispatch(net_connect, device_type = 'cisco_ios_telnet')
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py",
line 149, in redispatch
    obj.session_preparation()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco/cisco_ios.py",
line 11, in session_preparation
    self.set_base_prompt()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py",
line 670, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py",
line 707, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt:
