### ISSUE TITLE
Redispatch - connect back to the terminal server. 

### ISSUE THREAD

**Issue by etem** [ktbyers/netmiko#639]
I'm running a script on Windows workstation which connects to a terminal server, switches and and gets some output. It works perfectly fine on a single switch.
But I would like to improve the script to run on multiple devices.  
For example : 

```
redispatch(net_connect, device_type='hp_comware')
do something.... 
net_connect.send_command('quit') 
redispatch(net_connect, device_type='terminal_server') 

```
From the logs I see that the last redispatch is not working. Any ideas on how to fix that?

**Comment by ktbyers** [comment]
@etem Can you show me what the log shows?

**Comment by etem** [comment]
@ktbyers  Here are the logs : 

`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:write_channel: b'quit\n'`
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: quit`

`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: Connection to X.X.X.X closed.`


`[01;32jumpserverhostname[01;33m ~ $ [00m`
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `
`DEBUG:netmiko:read_channel: `

I also added a print() debugging message after last redispatch()  statement but it's never executed.

**Comment by etem** [comment]
This is what I'm trying to do. 

```python
parser = argparse.ArgumentParser("Execute commands and extract output from Comware based network devices.")
parser.add_argument('-d', '--devices', help='Specify a file with devices to connect.', required=True)
parser.add_argument('-c', '--command', help='Command to execute.', required=True)
args = vars(parser.parse_args())


devicesList = args.get('devices')
command = args.get('command')


def run_commands(command, devicelist): 
	output = ''
	with open(devicelist, 'r') as devicelist:
		for device in devicelist:
			#Strip the newline character.
			device = device.strip('\n')
			net_connect.write_channel('ssh ' + device + '\n')
			time.sleep(5)
			redispatch(net_connect, device_type='hp_comware')
			print("Succesfully connected to device " + net_connect.find_prompt())
			time.sleep(5)
			net_connect.write_channel('super level'+ '\n')
			time.sleep(5)
			net_connect.send_command('screen-length disable') 
			time.sleep(5)
			print()
			print()
			####
			print("Executing command " + command)
			output += device + "------------------"
			output += command
			output += net_connect.send_command(command)
			output += '\n' + '\n'
			time.sleep(1)
			net_connect.send_command('quit')
			time.sleep(3)
			redispatch(net_connect, device_type='terminal_server')
			print("Connected back to the jumpstation")
			time.sleep(1)
	return output



# Launch SSH connection the connection to the jump server
net_connect = ConnectHandler(**jumpserver)

# Run the commands and save output to variable.
output = run_commands(command, devicesList)

# Save command output to a file. 
with open("Script" + "-" + time.strftime("%d" + "-" +"%m" + "-" + "%H" + "-" + "%M") + ".txt", 'w+') as file:
	file.write(output)
	file.close()
	print("Output succesfully saved to file " + "Script" + "-" + time.strftime("%d" + "-" +"%m" + "-" + "%H" + "-" + "%M") + ".txt")
````

I'm trying to create a script which needs to read a list with devices from a text file(devices will be delimited using a newline), execute a user specified command on each device and save the command output to a text file.

**Comment by ktbyers** [comment]
Try changing this:

```
net_connect.send_command('quit') 
```

To
```
net_connect.send_command_timing('quit') 
```

By default send_command is trying to find the trailing prompt of the hp_comware and when you quit it never occurs.

Let me know if that fixes your original issue.

**Comment by etem** [comment]
@ktbyers It's working perfectly! 
Thank you! Appreciate your help. 

I'm just curious, are there any other differences between `send_command()` and `send_command_timing()` except that the first one is waiting for the trailing prompt and second one is executing commands with a delay?
 
Is the operation of `send_command_timing()` is affected by the global_delay_factor setting in BaseConnection?

**Comment by ktbyers** [comment]
@etem In general `send_command` works more reliably and generally should be used in cases when the router's prompt is returned. `send_command` also has an argument for a regular expression pattern to detect (instead of the trailing prompt).

`send_command_timing` is entirely timing based and tries to figure out when the command is done based on no more data being available. I use it in cases like the above or in situations where the router prompts for more information in a command.

Pretty much all delays in Netmiko are affected by `global_delay_factor` so yes send_command_timing's delays would be modified by this.
