### ISSUE TITLE
establish_connection verbose message inaccurate. 

### ISSUE THREAD

**Issue by plucena24** [ktbyers/netmiko#64]
establish_connection method in BaseSSHConnection prints "SSH connection established to {0}:{1}" even if the device the session is attempting to connect to is not a valid host on the network. Perhaps this message should be moved down right before line 96:

self.remote_conn = self.remote_conn_pre.invoke_shell()

**Comment by ktbyers** [comment]
Just send a pull request on it :-)


Kirk

On Sun, Mar 8, 2015 at 4:57 PM, plucena24 <notifications@github.com> wrote:

> establish_connection method in BaseSSHConnection prints "SSH connection
> established to {0}:{1}" even if the device the session is attempting to
> connect to is not a valid host on the network. Perhaps this message should
> be moved down right before line 96:
>
> self.remote_conn = self.remote_conn_pre.invoke_shell()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/64>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by plucena24** [comment]
lol will do =)
