### ISSUE TITLE
IOError: Search pattern never detected in send_command_expect: router\_1\(config\)\#

### ISSUE THREAD

**Issue by tafiela** [ktbyers/netmiko#641]
Hi,

I am trying to write a script to change hostnames and deploy a configuration template (on cisco devices).  After fighting and fixing one issue after the other (im new to python), i am finally stuck.

i was able to deploy the template from a file, this was successful. Where im having issue is the simple one command change (hostname <name>). please any suggestion to improve my script or to fix the issue would be much appreciated. 

"

import getpass
from netmiko import ConnectHandler

uname = raw_input('Please Enter your username: ')
password = getpass.getpass()

os.chdir('/Python_Network_scripts/Network_SSH_Prep')
devices = {'172.16.137.131':'RTR1','172.16.137.132':'RTR2'}

file = '/Python_Network_scripts/Network_SSH_Prep/config_file.txt'

for ip, name in devices.items():

	print "We are working now with IP: {}".format(ip)
	switch = {
		'device_type': 'cisco_ios',
		'ip': ip,
		'username': uname,
		'password': password,
	}

	print "\nEstablishing the SSH now ... "
	network_connect=ConnectHandler(**switch) #established an SSH session with Switch, we used ** since there is mulitple arguments inside switch varibale thats are required

	print "Connected"
	#network_connect.enable()
	#network_connect.config_mode()
	#network_connect.send_command('config t\n')
	network_connect.send_command('hostname {}\n'.format(name)) #this is where the issue is

	f=open(file, 'rb')
	f.seek(0)
	

	print "\nSending configurations from file : {}".format(file)
	output = network_connect.send_config_set(f.read()) #should use set if you want to send a list of file content

	print "\nSaving Configurations ..."
	
	

	print "="*52
	print "\n"
	print "Configuration completed on {}".format(ip)
	print "\n"
	print "="*50
"

**Comment by ktbyers** [comment]
Given what you have above, you can just do this:

```
network_connect.send_command_timing('hostname {}\n'.format(name))
```
