### ISSUE TITLE
Juniper - ValueError: Router prompt not found: '%'

### ISSUE THREAD

**Issue by Zalek-Git** [ktbyers/netmiko#643]
I am trying to use netmiko on a Juniper SRX but I am hitting Router prompt not found: error. Any help is appreciated.

Below is the exact error

```
  File "/home/user/eclipse-workspace/PyEZ/NetMiko-2.py", line 17, in <module>
    net_connect = ConnectHandler(**a_device)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 152, in __init__
    self.session_preparation()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/juniper/juniper_ssh.py", line 25, in session_preparation
    self.set_base_prompt()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 672, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: '%'
```

Below is my code

```
from netmiko import ConnectHandler
from datetime import datetime

juniper_srx = {
    'device_type': 'juniper',
    'ip':   '10.1.34.130',
    'username': 'root',
    'password': 'Password',
    'port': 22,               # there is a firewall performing NAT in front of this device
    'verbose': False,
    } 

all_devices = [juniper_srx]

start_time = datetime.now()
for a_device in all_devices:
    net_connect = ConnectHandler(**a_device)
    print ("1")
    output = net_connect.send_command("show interfaces terse")
    print ("\n\n>>>>>>>>> Device {0} <<<<<<<<<").format(a_device['device_type'])
    print (output)
    print (">>>>>>>>> End <<<<<<<<<") 
    
end_time = datetime.now()

total_time = end_time - start_time 
print (total_time)
```

**Comment by ktbyers** [comment]
@Zalek-Git What does your shell look like after you login?

In other words, when you SSH in as root can you post the very beginning of the session (what it looks like when you do this manually)?

**Comment by Zalek-Git** [comment]
login as: root
Using keyboard-interactive authentication.
Password:
Last login: Fri Dec  1 01:09:28 2017 from 10.1.34.72

--- JUNOS 15.1X49-D45 built 2016-04-25 07:29:58 UTC
% cli

root@SRX300-1> configure 
Entering configuration mode
Users currently editing the configuration:
  root terminal u0 (pid 1755) on since 2017-11-30 22:16:42 UTC, idle 16:25:05
      [edit]

[edit]
root@SRX300-1#

**Comment by Zalek-Git** [comment]
Is this what you wanted or smt else?

**Comment by Zalek-Git** [comment]
Btw I am running this on Python 3.6, does it matter or should I try it with Python 2?

**Comment by tonypnode** [comment]
Looks like the prompt netmiko should be looking for is # rather than a % (see the last line in the error)

**Comment by tonypnode** [comment]
I bet if try changing the device type to cisco_ios as a test, it might work. I’m looking through the code to see if you can override the prompt rather than specifying the device type as Cisco

**Comment by tonypnode** [comment]
After a little digging, can you check your base_connection.py lines 657 -676. From what im gathering the pri_prompt_terminator should be set to ‘#’. It looks like yours is Set to ‘%’

**Comment by Zalek-Git** [comment]
Hi Tony
Thank you a lot for looking into it. I will see what I can do. I am not sure where base_connection.py lies, but I will dig around and update.

Regards

**Comment by Zalek-Git** [comment]
Hi Tony

I think I might need to add _%_ to the set_base_prompt function, because in when you first login you first end up in linux shell (%), and it seems it is what the code is not recognizing.

**Comment by Zalek-Git** [comment]
Ok I have edited base_connection.py lines. Adding shell_promt_terminator='%' to function set_base_promt and adding it to the list seems to solve that error I was experiencing earlier.

But now I am getting the below error
show:command not found 


I think this is because I go into Linux Shell in my Juniper device and not to the operational mode (>) where I can run that command.

I added the below to my code, which I was hoping would put me into operational mode, so I could run the show command
cli = net_connect.send_command("cli")

But got the error below
Traceback (most recent call last):
  File "/home/user/eclipse-workspace/PyEZ/NetMiko-2.py", line 18, in <module>
    cli = net_connect.send_command("cli")
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 828, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: \%

At this point I feel like I am making things worse.

Current Code
```
from netmiko import ConnectHandler
from datetime import datetime

juniper_srx = {
    'device_type': 'juniper',
    'ip':   '10.1.34.130',
    'username': 'root',
    'password': 'Password',
    'port': 22,               
    'verbose': False,
    } 

all_devices = [juniper_srx]

start_time = datetime.now()
for a_device in all_devices:
    net_connect = ConnectHandler(**a_device)
    cli = net_connect.send_command("cli")
    print (1)
    output = net_connect.send_command("show interfaces terse")
    print (2)
    #print ("\n\n>>>>>>>>> Device {0} <<<<<<<<<").format(a_device['device_type'])
    print (output)
    print (">>>>>>>>> End <<<<<<<<<") 
    
end_time = datetime.now()

total_time = end_time - start_time 
print (total_time)

**Comment by tonypnode** [comment]
Gotcha...I wanted to make sure that your netmiko code base wasn't changed.  The fact that you got a little further does point us in a direction though. 

I recommend changing it back. I would also recommend reinstalling or upgrading netmiko to ensure you are on the latest codebase. 

Also, just so I am clear, (I am unfamiliar with Juniper), are you deviating from the normal management of a Juniper device? The reason I ask is, you said you are going into the Linux shell. Which sounds like the prompt delimiters will be different from common device operation. Netmiko takes in the specific device type "'device_type': 'juniper',".  This tells netmiko to look for those specific prompts. If you send a command that changes the expected prompts from Juniper prompts to a Linux prompt, that may need to be a feature request.

**Comment by ktbyers** [comment]
@Zalek-Git Can you test out the new develop branch?

I added this fix:

https://github.com/ktbyers/netmiko/commit/06a57747d93d640baf67e6118ce5abbf886f7808

Basically, my SRX100 shows `root@%` when I login to the shell so I was looking for the `root@` pattern. I also added the following pattern `%` (i.e. a completely blank c-shell prompt).

For my information did you customize your c-shell or is that just how it defaulted on your device.

Anyways let me know if that change fixes it.

**Comment by Zalek-Git** [comment]
@tonypnode 

I have installed netmiko only a week ago but I will reinstall it just in case.

Getting into Linux Shell is normal when loging into a Juniper device. The steps are
1) Linux shell (%)
2) Enter the command "cli". This gets you into operational mode (>) where you can run _show_ commands etc
3) Enter "conf" to enter configuration mode (#) to configure the device


@ktbyers

I have not played with the shell of the Juniper box, it is default. I will try the code and put an update.

I have checked the login on SRX300 and some other devices as well (Except QFX10K). It is as you said `root@%` or `root@<hostname>:%` if you have hostname configured. On devices with multiple routing engines you also have the added :RE:X if that matters. On QFX10K it is # even in shell.

SRX300
--- JUNOS 15.1X49-D100.6 built 2017-06-28 07:08:37 UTC
root@%


EX3300
--- JUNOS 12.3R3.4 built 2013-06-14 00:06:34 UTC
root@LAB3300-1:RE:0%


QFX5100
--- JUNOS 14.1X53-D40.8 built 2016-11-09 02:13:22 UTC
root@QFX5100-BACKUP:RE:0%


QFX10K
--- JUNOS 15.1X53-D63.9 Kernel 64-bit FLEX JNPR-10.1-20160825.336113_builder_stable_10-331042
root@QFX10k-Spine-02:~ #

**Comment by ktbyers** [comment]
@Zalek-Git So why are you seeing only `%` for the prompt? That is inconsistent from the above?

All of the above should work with the release Netmiko version.

**Comment by Zalek-Git** [comment]
No the mention of % was based on the error I was getting, and it was a guess of the cause
ValueError: Router prompt not found: '%'

I rebuilt the code instead of using the one in junos pyez cookbook. I just used the bare essentials to test and it works. I will look into the code in the book to see what was causing the error later.

```
from netmiko import ConnectHandler  # import a connection handler from NetMiko
from datetime import datetime   #Import time. Used to calculate total program run time.

#Device details
juniper_srx = {
    'device_type': 'juniper',
    'ip':   '10.1.34.130',
    'username': 'Automation',
    'password': 'Password',
    }    

#List containing all device info
device_list=[juniper_srx]

#Start time of the program
start_time = datetime.now()



#Connect to the device using Device details
for device in device_list:
    net_connect = ConnectHandler(**device)
    
    # Enter operational mode commands
    interfaces = net_connect.send_command("show interfaces terse | except down | match ge- ")   #Show interfaces that are up
    print (interfaces)
    
    chassis = net_connect.send_command("show chassis hardware") #Show chassis information
    print (chassis)
    
    #Enter configuration Mode - JunOS only
    net_connect.config_mode()
    
    #Add commands
    description = net_connect.send_command("set interfaces ge-0/0/0 description NetMIKO-TEST-1") #Add description to interface
    
    #Commit commands
    commit = net_connect.commit()
    
    #Compare Configuration and Print changes
    compare= (net_connect.send_command("show | compare rollback 1"))
    if str(compare)== "\n":
        print ("No Changes\n")
    else:
        print (compare)
    
    
    
    #Exit Configuration mode
    net_connect.exit_config_mode()
    
    #End SSH session
    net_connect.disconnect()

#Calculate Total program time
end_time = datetime.now()
total_time = end_time - start_time 
print (total_time)
```

**Comment by ktbyers** [comment]
@Zalek-Git You posted this above:

```
login as: root
Using keyboard-interactive authentication.
Password:
Last login: Fri Dec 1 01:09:28 2017 from 10.1.34.72

--- JUNOS 15.1X49-D45 built 2016-04-25 07:29:58 UTC
% cli

root@SRX300-1> configure
Entering configuration mode
```

with a prompt of `%`...so this is not what it looked like?

**Comment by Zalek-Git** [comment]
That was the output from the putty session log, so I am a bit confused as well now. Because now when I login to the same device I get. I can not replicate the same output.

Using keyboard-interactive authentication.
Password:
Last login: Fri Dec 15 15:19:40 2017 from 10.1.34.99
--- JUNOS 15.1X49-D100.6 built 2017-06-28 07:08:37 UTC

root@% cli
root> configure
Entering configuration mode
Users currently editing the configuration:
  root terminal u0 (pid 2818) on since 2017-12-13 09:43:57 UTC, idle 4d 18:50
      [edit]

[edit]
root#

**Comment by Zalek-Git** [comment]
However, I did upgrade the SRX300 from D45 to D100 software, maybe that might explain the difference in behaviour

**Comment by ktbyers** [comment]
Okay, I think this issue should be resolved. If not, let me know.

**Comment by vpalurii** [comment]
Hi Kirk,

I am having a similar problem 
regress@dummy:~$ 

How to fix this?

**Comment by ktbyers** [comment]
@vpalurii Why are you logging into the shell and not into the router CLI?


Kirk

**Comment by vpalurii** [comment]
This is my script

 device = ConnectHandler(device_type='juniper', ip=baserou, username='regress', password='MaRtInI')
output = device.send_command("show version")#sending the command

Below is the error which i am getting 

Traceback (most recent call last):
  File "recurse.py", line 70, in <module>
    device = ConnectHandler(device_type='juniper', ip=baserou, username='regress', password='MaRtInI')
  File "/Users/vpaluri/anaconda2/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/vpaluri/anaconda2/lib/python2.7/site-packages/netmiko/base_connection.py", line 208, in __init__
    self.session_preparation()
  File "/Users/vpaluri/anaconda2/lib/python2.7/site-packages/netmiko/juniper/juniper.py", line 26, in session_preparation
    self.set_base_prompt()
  File "/Users/vpaluri/anaconda2/lib/python2.7/site-packages/netmiko/base_connection.py", line 856, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: u'regress@samp-re0:~$'

**Comment by ktbyers** [comment]
@vpalurii Yes, your username is configured to login to the shell and not to the device's CLI. Was there a reason for this?


Kirk

**Comment by vpalurii** [comment]
It started working after changing the content of file netmiko/juniper/juniper_ssh.py

**Comment by vpalurii** [comment]
from            if re.search(r'root@', cur_prompt) or re.search(r"^%$", cur_prompt.strip()):
to             if re.search(r'root@', cur_prompt) or re.search(r"^%$", cur_prompt.strip()) or re.search(r"$", cur_prompt.strip()):

**Comment by ktbyers** [comment]
@vpalurii So it works now or is still broken?

**Comment by ktbyers** [comment]
What version of Netmiko are you using?

**Comment by ktbyers** [comment]
Okay, let me fix it...I see the issue.

**Comment by vpalurii** [comment]
Thanks @ktbyers

**Comment by vpalurii** [comment]
HI @ktbyers, Did you get a chance to fix it?

Thanks

**Comment by ktbyers** [comment]
@vpalurii Nope, feel free to submit a pull request on it though.

You should also be able to work around it, by using a user that doesn't log into the shell (i.e. use a user that logs directly into the router CLI).

**Comment by vpalurii** [comment]
Hi Kirk,

I am currently using work around to get my work done.
But it would be better to have it in mainline as there are more platforms
which will need these going further.

Will raise a pull request.

Thanks,

**Comment by forloop5** [comment]
I am also having this issue and I just installed netmiko 2 days ago.

**Comment by forloop5** [comment]
Thank you for accommodating the juniper login!
