### ISSUE TITLE
Multiple SSH connections using same session

### ISSUE THREAD

**Issue by himanshuvaish** [ktbyers/netmiko#648]
I am very new to Python. Our current requirement is that we have to do multiple SSH on the same session to reach a gateway. I am able to conenct to gateway and display output on CLI. I want to pop open the last telnet session so that the engineer can continue work and interact with Cisco iOS CLI.

import paramiko
import time
from paramiko_expect import SSHClientInteraction
import time
import sys
import getpass
import pexpect

ip_address = "#IPaddress"
username = "HIdden"
password = "hidden"
ssh_client = paramiko.SSHClient()
ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh_client.connect(hostname=ip_address,username=username,password=password)
remote_connection = ssh_client.invoke_shell()
print ('Successful connection', ip_address)
remote_connection = ssh_client.invoke_shell()
time.sleep(1)
remote_connection.send("\n")
time.sleep(1)
remote_connection.send("telnet ip\n")
time.sleep(2)
remote_connection.send(username + "\n")
time.sleep(1)
remote_connection.send(password +"\n")
time.sleep(1)
remote_connection.send("sh run\n")
time.sleep(5)
outputd=remote_connection.recv(65535)
print (outputd)

**Comment by ktbyers** [comment]
Maybe look at Salt...there has been some (small) amount of work to integrating a Netmiko session reuse/locking for Salt.

**Comment by rishabhsen** [comment]
can any please help me how to open a text file in peramiko which contain multiple IP address

**Comment by ktbyers** [comment]
@rishabhsen This issue has been closed for over 1.5 years so you should probably open up a separate issue as long as it is related to Netmiko. 


Regards, Kirk

**Comment by jogindergur** [comment]
@rishabhsen paramiko will not open a file for addresses. you need to do it via basic python then pass it to paramiko
