### ISSUE TITLE
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.

### ISSUE THREAD

**Issue by NedySuprianto** [ktbyers/netmiko#649]
Dear Ktbyers,

I have a issue that tell me to pass the **secret** argument when i wan to telnet to catalyst 2900 series it's **_stack switch_**, but i already pass the secret argument and then, i try to reopen my program and try to connect again and its work. 

**Error Message**
```
  File "C:\Users\User\Python 3.5.3\lib\site-packages\netmiko\cisco_base_connection.py", line 17, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "C:\Users\User\Python 3.5.3\lib\site-packages\netmiko\base_connection.py", line 895, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.
```

**Code** 
```
# connect to device
net_connect = ConnectHandler(device_type=list.device_type, ip=list.ip, username=list.username,
                                                         password=list.password, secret=list.secret)
# enable mode
net_connect.enable()
```

Thanks.

**Comment by BigPat** [comment]
Personally in my code I use the same password for password and secret.  If they are the same then try doing this.
```
net_connect = ConnectHandler(device_type=list.device_type, ip=list.ip, username=list.username,
                                                         password=list.password, secret=list.secret)
```
I personally do mine like this:

```
username = input('what is the username') # user enters username
password = input('What is the password') # user enters password
device = 'cisco_ios'
ipadd = '0.0.0.0' # I will also import from a list 

net_connect = netmiko.ConnectHandler(device_type=device, ip=ipadd, username=username, password=password, secret=password, port=22)

net_connect.enable()
```

**Comment by ktbyers** [comment]
@NedySuprianto Can you try setting the `global_delay_factor=2` (or 4) to ConnectHandler.

This will help isolate if it is a timing issue.

**Comment by NedySuprianto** [comment]
@BigPat i'm use different password for password and secret.

@ktbyers so i need to set the `global_delay_factor=2` to ConnectHandler like this?

```
net_connect = ConnectHandler(device_type=list.device_type, ip=list.ip, username=list.username,
                                                         password=list.password, secret=list.secret, global_delay_factor = 2)
```

**Comment by ktbyers** [comment]
@NedySuprianto Did the global_delay_factor change work?

**Comment by ktbyers** [comment]
Just re-open if still having issue.

**Comment by hpant1987** [comment]
I am facing the same issue. I tried setting global delay factor to 4. Still the issue exists. I am using Cisco 1941 Router

**Comment by ktbyers** [comment]
@hpant1987 Please open a new issue. Post your code and post your exception.

**Comment by shabin75** [comment]
It will work for me..
when i give **secret="123"**

device = ConnectHandler(device_type="cisco_ios", ip="192.168.10.1", username="shabin", 
                         password="123", global_delay_factor=2,secret="123")

**Comment by vibraniumSwaleh** [comment]
> Personally in my code I use the same password for password and secret. If they are the same then try doing this.
> 
> ```
> net_connect = ConnectHandler(device_type=list.device_type, ip=list.ip, username=list.username,
>                                                          password=list.password, secret=list.secret)
> ```
> 
> I personally do mine like this:
> 
> ```
> username = input('what is the username') # user enters username
> password = input('What is the password') # user enters password
> device = 'cisco_ios'
> ipadd = '0.0.0.0' # I will also import from a list 
> 
> net_connect = netmiko.ConnectHandler(device_type=device, ip=ipadd, username=username, password=password, secret=password, port=22)
> 
> net_connect.enable()
> ```

Thank, this helped me big time.!! and many thanks to everyone involved

**Comment by ktbyers** [comment]
@dayanandColt Can you create a new issue, this issue is several years old and closed.

In your new issue, please post your full exception stack trace.

**Comment by dayanandColt** [comment]
Thank you for the reply.. Issue was from our side, it was related to permission..
After proper permission we are not see this issue.
