### ISSUE TITLE
auto add SSH keys policy

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#65]
Not a secure way to do this. Should allow for a secure way for this to be accomplished.

**Comment by ogenstad** [comment]
Have you thought about how this will be implemented in terms of how the module is used. I.e will we need to add a parameter to force higher security or will the default be changed so that currently insecure implementations might break?

**Comment by ktbyers** [comment]
I probably would try to maintain backwards compatibility (as the security risks are probably low for most people).

**Comment by ktbyers** [comment]
Fixed 241f9512d33608f25347d8d185bada547e74378d

**Comment by superloopnetwork** [comment]
Hi Kirk,

If I'm configuring a device via console and I enable SSH management for the very first time, how would netmiko be able to access it if it doesn't have it's keys' saved? Any flags I can use to "auto add" the keys as suggested above?

Thanks.

**Comment by superloopnetwork** [comment]
Sorry, I just tested and I think you have made it auto add by default.. Saves me the headache.. :)
