### ISSUE TITLE
Need to Pop open remote SSH window

### ISSUE THREAD

**Issue by himanshuvaish** [ktbyers/netmiko#653]
Our current requirement is that we have to do multiple SSH on the same session to reach a gateway. I am able to conenct to gateway and display output on CLI. I want to pop open the last telnet session so that the engineer can continue work and interact with Cisco iOS CLI.

Ktbyers said:"Maybe look at Salt...there has been some (small) amount of work to integrating a Netmiko session reuse/locking for Salt."

But as i mentioned, i am new to programming. I cannot find anything related to "salt" for popping open the current SSH session.

Thanks
Himanshu

**Comment by ktbyers** [comment]
You are probably going to have to build something. There probably isn't what you want already pre-made.
