### ISSUE TITLE
Support for Juniper Screen OS

### ISSUE THREAD

**Issue by zhtan** [ktbyers/netmiko#656]
Very new to this library. Does the library support Juniper Screen OS?

**Comment by ktbyers** [comment]
No, unfortunately, there isn't any support for Screen OS. I think someone tried at one point...but were some issues (this is from a long-time ago though...).

**Comment by zhtan** [comment]
I see. Thank you for the quick response!

**Comment by ktbyers** [comment]
No worries :-)
