### ISSUE TITLE
Issue for running command output in Nxos

### ISSUE THREAD

**Issue by Swandip** [ktbyers/netmiko#658]
Hi @ktbyers 

I am able to get output of sh run and sh mac address-table by using 

 output = device.send_command('sh run') or  output = device.send_command('sh mac address-table')

But when i try to output = device.send_command('sh int status  | i connected | count') 

It fails is their any other way of doing it.

**Comment by wmann** [comment]
You could get the whole output and do the filtering in your python code. What error do you get?

**Comment by ktbyers** [comment]
@Swandip ...that should work...what error do you see?



Kirk

**Comment by ktbyers** [comment]
No follow-up response...so closing.
