### ISSUE TITLE
Error to connet witch switch Allied Telesis 

### ISSUE THREAD

**Issue by vjuagar** [ktbyers/netmiko#660]
Hi, I'm trying to establish a connection with an Allied Telesis 8000s switch and I can not get it. with the same code I tried a server and I was able to make the connection without problems and execute a command. I think the problem is because the switch asks me for a loggin before the user. Thank you

**Comment by ktbyers** [comment]
Someone will need to create an Allied Telesis driver. The process for creating a new driver is here:

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md
