### ISSUE TITLE
SCP File Transfer - Unsupported device type 'cisco_xe'

### ISSUE THREAD

**Issue by ghmj2417** [ktbyers/netmiko#661]
Previously, device type 'cisco_xe' was supported for SCP file transfers.  Now I receive 'Unsupported device type: currently supported platforms are:'.  The funny thing, my device type is listed in the output and I am pretty sure I know why.

The FileTransfer function checks for any device types in here:
FILE_TRANSFER_MAP = {
    'arista_eos': AristaFileTransfer,
    'cisco_asa': CiscoAsaFileTransfer,
    'cisco_ios': CiscoIosFileTransfer,
    'cisco_nxos': CiscoNxosFileTransfer,
    'juniper_junos': JuniperFileTransfer,
}
Then it appears you create additional keys with _ssh appended and assign the new_mapper dict to the FILE_TRANSFER_MAP keys.
new_mapper = {}
for k, v in FILE_TRANSFER_MAP.items():
    new_mapper[k] = v
    alt_key = k + u"_ssh"
    new_mapper[alt_key] = v
FILE_TRANSFER_MAP = new_mapper

You then assign the following variables which will be used to check for the device type in your FileTransfer function:
scp_platforms = list(FILE_TRANSFER_MAP.keys())
scp_platforms.sort()
scp_platforms_str = "\n".join(platforms_base)
scp_platforms_str = "\n" + platforms_str

And here is the check:
if device_type not in scp_platforms:
        raise ValueError('Unsupported SCP device_type: '
                         'currently supported platforms are: {}'.format(scp_platforms_str))

Based on the code above, I can see why my device type 'cisco_xe' is not working anymore.  However, your supported platforms list says it should be supported.  The reason being is because scp_platforms_str is getting its values from platforms_base which is getting its values from CLASS_MAPPER_BASE which has all types.

Two things: First, since XE is a train of IOS and the CLI commands are almost identical, would you be against adding it as a supported file transfer type?  Second, you may want to change the scp_platforms_str string to show the actually supported types not all class types.

**Comment by ktbyers** [comment]
@ghmj2417 This is just a bug...i.e. I forgot to map ios_xe (as it should behave identical to cisco_ios here). I would just use a `device_type` of `cisco_ios` until I fix it.

**Comment by ghmj2417** [comment]
@ktbyers That's what I did (changed my device type to cisco_ios).  I just wanted to make sure you were aware and I provided you with enough info for what I was seeing.  Too many times I see people open issues stating something doesn't work and that is it.  They don't explain what steps they have used to duplicate the problem, and what investigation they have completed to help resolve the problem.

**Comment by ktbyers** [comment]
@ghmj2417 Yes, definitely thanks for reporting it (I wasn't aware that I had done this)...also I think you reported a second issue as well (i.e. that I am not reporting SCP support for failed device types). In other words, for Secure Copy I should indicate which platforms are supported there.

**Comment by ghmj2417** [comment]
@ktbyers Yes, the second issue is that the supported types are not being shown.  You are showing all types.  Would you like me to create an additional issue?

**Comment by ktbyers** [comment]
@ghmj2417 No, this is fine...I should remember it from this issue.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/netmiko/commit/9f0bc19c29912dfbd881b011c206413aa2d1485a

and here:

https://github.com/ktbyers/netmiko/commit/a505dc78095700b68f8dfc23ca46fbe33772b764
