### ISSUE TITLE
Connect via SSh to ASA

### ISSUE THREAD

**Issue by RamVic** [ktbyers/netmiko#662]
Hello ,I have a problem when I try to conecct to my ASA , I have a simple script only for connect , when I connect via ssh to my ASA I have to put -oKexAlgorithms=+diffie-hellman-group1-sha1  , I dont know if that have some relation.

Traceback (most recent call last):
  File "prueba.py", line 10, in <module>
    device = ConnectHandler(device_type=platform, ip=host,username=username,password=password )
  File "build/bdist.freebsd-10.3-RELEASE-p20-i386/egg/netmiko/ssh_dispatcher.py", line 167, in ConnectHandler
  File "build/bdist.freebsd-10.3-RELEASE-p20-i386/egg/netmiko/base_connection.py", line 188, in __init__
  File "build/bdist.freebsd-10.3-RELEASE-p20-i386/egg/netmiko/cisco/cisco_asa_ssh.py", line 19, in session_preparation
  File "build/bdist.freebsd-10.3-RELEASE-p20-i386/egg/netmiko/base_connection.py", line 747, in disable_paging
  File "build/bdist.freebsd-10.3-RELEASE-p20-i386/egg/netmiko/base_connection.py", line 445, in read_until_prompt
  File "build/bdist.freebsd-10.3-RELEASE-p20-i386/egg/netmiko/base_connection.py", line 384, in _read_channel_expect
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

Thankssss  in advance-

**Comment by RamVic** [comment]
Ohh I forget a secret , now is connected :D , I have some questions , 
1) I need the script to connect to some FWs ASA and make a copy start-up config tftp: xxxxxxxx , as script to automatic backup . 
How can I make it?
How can I hide the pass and user ?

Thanks a lot

**Comment by ktbyers** [comment]
Use 

```
net_connect.send_command_timing("copy start-up config tftp: xxxxxxxx")
```

See https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#show-commands-that-prompt-for-more-information

I assume you mean hide the password in your code? Use:

```
from getpass import getpass

password = getpass()
```

To prompt for a password upon script execution.

**Comment by RamVic** [comment]
#! /usr/bin/python

from netmiko import ConnectHandler

platform = 'cisco_asa'
host = '10.54.116.248'
username = 'xxxxxx'
password = 'xxxxxxx'
secret = 'xxxxxxxx'
net_connect = ConnectHandler(device_type=platform, ip=host,username=username,password=password ,secret=secret )

output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")
print output

When I execute the scrip  the tfpt ask for some parameters

root@xxxxsvpla020:/tmp/Config_Routers # python2.7 prueba.py

Address or name of remote host [10.54.248.56]?


How could I put enter or something in the scrip?

Thanks a lot ktbyers

**Comment by RamVic** [comment]
I try to make this but is not working

output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")
if 'address or name of remote host' in output:
  output += net_connect.send_command_timing("10.54.248.56")

**Comment by RamVic** [comment]
I made this 

net_connect = ConnectHandler(device_type=platform, ip=host,username=username,password=password ,secret=secret )

output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")
if  'Address or name of remote host [10.54.248.56]?' in output:
   output += net_connect.send_command_timing("10.54.248.56")
if 'Destination filename [startup-config]?' in output:
    output += net_connect.send_command("prueba")
print output

But I get an error
root@ardc1svpla020:/tmp/Config_Routers # python2.7 prueba.py
Traceback (most recent call last):
  File "prueba.py", line 18, in <module>
    output += net_connect.send_command("prueba")
  File "build/bdist.freebsd-10.3-RELEASE-p20-i386/egg/netmiko/cisco/cisco_asa_ssh.py", line 54, in send_command
  File "build/bdist.freebsd-10.3-RELEASE-p20-i386/egg/netmiko/base_connection.py", line 967, in send_command
IOError: Search pattern never detected in send_command_expect: \!\!\!\!\!\!\!\!\!

**Comment by RamVic** [comment]
Now seems it working, But I can't find the file in the server .

root@ardc1svpla020:/tmp/Config_Routers # python2.7 prueba.py
76122 bytes copied in 0.490 secs

net_connect = ConnectHandler(device_type=platform, ip=host,username=username,password=password ,secret=secret )

output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")
if  'Address or name of remote host [10.54.248.56]?' in output:
   output += net_connect.send_command_timing("10.54.248.56")
if 'Destination filename [startup-config]?' in output:
    output=net_connect.send_command("pruebauno")

print output

**Comment by ktbyers** [comment]
@RamVic Have you done the entire process manually? Do you see the file on the server then?

Then just repeat that process in code and verify it was done identically via looking at print(output).

Note, here...I would do this instead:

```
output += net_connect.send_command_timing("pruebauno")
print(output)
```

**Comment by ktbyers** [comment]
Does it work properly when you do it manually?

**Comment by RamVic** [comment]
Do you say manually from the FW?? Yes, works
and from server too
root@ardc1svpla020:/tmp/Config_Routers # python2.7 prueba.py
Address or name of remote host [10.54.248.56]?
Destination filename [startup-config]? !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
176122 bytes copied in 0.460 secs

But I see the name startup-config and not pruebauno , can I pass a FW'hostname to the name ?? something like this:

hostname=net_connect.send_command_timing("show hostname")
print hostname
output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")
if  'Address or name of remote host [10.54.248.56]?' in output:
   output += net_connect.send_command_timing("10.54.248.56")
if 'Destination filename [startup-config]?' in output:
    output += net_connect.send_command_timing("%hostname")

**Comment by ktbyers** [comment]
@RamVic Can you post the entire manual CLI session?

**Comment by RamVic** [comment]
#! /usr/bin/python

from netmiko import ConnectHandler
#f = open ('/home/igord/firewall_list','r')
#mensaje = f.readlines()
#print mensaje


platform = 'cisco_asa'
host = '10.54.116.248'
username = 'xxxxxxxx'
password = 'xxxxxxx'
secret = 'xxxxxxx'

net_connect = ConnectHandler(device_type=platform, ip=host,username=username,password=password ,secret=secret )

hostname=net_connect.send_command_timing("show hostname")
print hostname
output=net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")
if  'Address or name of remote host [10.54.248.56]?' in output:
   output += net_connect.send_command_timing("10.54.248.56")
if 'Destination filename [startup-config]?' in output:
    output += net_connect.send_command_timing("pruebauno")

print output

**Comment by ktbyers** [comment]
Not your code...the manual CLI session i.e. exactly what it looks like when you do it manually.

**Comment by RamVic** [comment]
manually from the FW??? or executing the script?

**Comment by ktbyers** [comment]
Yes, manual from the FW (i.e. from the CLI).

**Comment by ktbyers** [comment]
If your script isn't showing the same result as manual, then your script is doing something different than when you do it manually.

**Comment by RamVic** [comment]
ARDC134FW000003-Internet# copy startup-config tftp://10.54.248.56

Address or name of remote host [10.54.248.56]?

Destination filename [startup-config]? pruebauno
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
176122 bytes copied in 0.560 secs

and I see in the server the file
root@ardc1svpla020:/tmp/Config_Routers # ls -la /tftpboot/pruebauno
-rw-r--r--  1 nobody  wheel  176122 Dec 20 17:13 /tftpboot/pruebauno

**Comment by ktbyers** [comment]
And what do you see when you print `output` from your code execution?

**Comment by RamVic** [comment]
root@ardc1svpla020:/tmp/Config_Routers # python2.7 prueba.py
ARDC1FW000003-Internet


Address or name of remote host [10.54.248.56]?
Destination filename [startup-config]? !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
176122 bytes copied in 0.500 secs

**Comment by ktbyers** [comment]
I would change this section:

```
hostname = net_connect.send_command_timing("show hostname")
print hostname

output = net_connect.send_command_timing("copy startup-config tftp://10.54.248.56")
if 'Address or name of remote host' in output:
    # print is for debugging
    print "Found address line"
    output += net_connect.send_command_timing("\n")
if 'Destination filename' in output:
    print "Found Destination filename line"
    output += net_connect.send_command_timing("pruebauno")

# Just to separate the collected output from the debugging.
print "#" * 80
print output
print "#" * 80
```

**Comment by RamVic** [comment]
Good day Kirk, I did the change and now is working :O , the only change that I'm seeing is 
output += net_connect.send_command_timing("\n").   . that was a problem??

I make the last question , How can I make to the file have the hostname of the ASA??

Thanks very much for your patience.

**Comment by ktbyers** [comment]
I assume you mean the saved file on the TFTP transfer. Just use the `hostname` variable you have above (process it to make sure it is what you want) and then send that as the name of the file when the router prompts you (where you are sending "pruebauano" now).
