### ISSUE TITLE
send_config_set hostname changes add unit tests for Cisco IOS

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#663]
Looking for trailing router prompt in check_config_mode

**Comment by vitofly** [comment]
Just wondering if the issue has been fixed? What is the best way to change device hostnames via netmiko?

**Comment by ktbyers** [comment]
@vitofly Okay, I think it is fixed here for Cisco devices (in general).

https://github.com/ktbyers/netmiko/pull/820

I think there is possibly an issue with Cisco WLC and I need to add unit tests that test this (at least for Cisco IOS).

**Comment by carlniger** [comment]
Should be sorted for some time now. Closing.
