### ISSUE TITLE
Improve Handling of Uncommon Prompt Terminators

### ISSUE THREAD

**Issue by tyler-8** [ktbyers/netmiko#673]
There should be a way to customize or look for additional prompt terminators other than `#` and `$`, particularly for Linux driver as it's possible to customize the terminator on most Linux machines.

Line in question: https://github.com/ktbyers/netmiko/blob/develop/netmiko/linux/linux_ssh.py#L22

**Comment by ktbyers** [comment]
The following environment variables were just added for Linux:

```
LINUX_PROMPT_PRI = os.getenv("NETMIKO_LINUX_PROMPT_PRI", "$")
LINUX_PROMPT_ALT = os.getenv("NETMIKO_LINUX_PROMPT_ALT", "#")
LINUX_PROMPT_ROOT = os.getenv("NETMIKO_LINUX_PROMPT_ROOT", "#")
```

Based on the PR #984 that you submitted.
