### ISSUE TITLE
Device is slow to connect via SSH and times out

### ISSUE THREAD

**Issue by BigPat** [ktbyers/netmiko#674]
I have a device that takes about 10-15 seconds to establish connection with. The issue is that netmiko throws a timeout exception before it can connect. 

How can I increase the time that the connection handler will wait until it times out?  

I have searched all over your issues and cannot find a solution.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BigPat** [comment]
Based on the log it failed while running “net_connect.enable().  No other devices failed when running this. I have global_delay_factor set to 5 right now and yet it still fails. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ktbyers** [comment]
@BigPat Can you post the relevant section of your code and the exception message that you get?

**Comment by ktbyers** [comment]
I am going to close, if you are still having an issue, please re-open. Also post the version of the code that you are using.
