### ISSUE TITLE
If output returns empty

### ISSUE THREAD

**Issue by nahian166** [ktbyers/netmiko#679]
Hi,
I am trying to get the output from the remote host of the following lines,

```
output1= net_connect.send_command('ovs-appctl fdb/show br-int | grep -i {0} | cut -d " " -f 4'.format(mac))

output2= net_connect.send_command('ovs-appctl fdb/show br-int | grep -i {0} | cut -d " " -f 8'.format(mac))
```
And those commands are inside a for loop, so for some iterations there are some output at the remote host and for some other iteration there are no output at the remote host. But I am getting output1 =4 and output2 =8 for those values which has no output at remote host. And I am getting output1= 4 25 (two output with the correct one) and output= 8 31 while I am expecting only 25 as output1 and 31 as output2.

mac is a variable.

Any idea what can be the error?

**Comment by ktbyers** [comment]
@nahian166 I would try turning on Netmiko debugging and see if that helps. This will log the reads and writes on the SSH channel.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by nahian166** [comment]
I have done some logging, And I found following unusual thing,

```
DEBUG:netmiko:write_channel: ovs-appctl fdb/show br-int | grep -i fa:16:3e:c5:59:b4 | cut -d " " -f 4

DEBUG:netmiko:read_channel:
c5:59:b4 | cut -d " " -f 4: ovs-appctl fdb/show br-int | grep -i fa:16:3e
```:


And then the next writes became unusual too,

```
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = u'ovs-appctl fdb/show br-ext | grep -i fa:16:3e: \rc5:59:b4 | cut -d " " -f 4\r\nroot@*******:~# '
c5:59:b4 | cut -d " " -f 4 ovs-appctl fdb/show br-ext | grep -i fa:16:3e:
root@*******:~#
DEBUG:netmiko:repr = u'ovs-appctl fdb/show br-ext | grep -i fa:16:3e: \rc5:59:b4 | cut -d " " -f 4\r\nroot@*******:~# '
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel:
```

*** Just replaced the domain name.

So should I use some other method except send_command() ?

**Comment by nahian166** [comment]
This is the output I am getting,

```
>> ip=192.168.0.3 mac=fa:16:3e:70:e4:62 port_prefix=258f6776-9393-476b-889d-5314c0f9c09d
   ovs_int_port= '
31   ovs_int_vlan= 8
31   ovs_int_action=1
   ovs_ext_port= 4   ovs_ext_vlan= 8   ovs_ext_action= ,11
>
   ovs_tun_action=s
actions=strip_vlan,set_tunnel:0x9a,output:10
```

Here, I am expecting ovs_int_port =31 and this kind of output for all, here ovs_int_vlan should be empty, but it returns 8, other output are also not entirely correct.
Such as I am expecting, ovs_tun_action=action=strip_vlan,set_tunnel:0x9a,output:10

**Comment by ktbyers** [comment]
@nahian166 Can you post the entire logfile.

Can you show me what the commands and output looks like when you execute them on the CLI of the remote device.

**Comment by carlniger** [comment]
inactive. closing.
