### ISSUE TITLE
No module named netmiko

### ISSUE THREAD

**Issue by t2okve** [ktbyers/netmiko#682]
Hi! Great Work!

I'm having this issue where I'm not able to run any code from netmiko as I'm unable to import it.
Doing a search in Lib and in Lib/site-packages seems that there is no netmiko.py file anywhere. Tried reinstalling netmiko with no luck
![image](https://user-images.githubusercontent.com/35410943/34911275-0e549408-f8a6-11e7-9f0e-7950fc7fb950.png)

Also tried finding this file everywhere in this github but can't seemd to find it.

I'm sure there's a simple solution to this as I'm a newbie on python.

Keep up the great work

**Comment by ktbyers** [comment]
@t2okve What happens when you do this?

```
$ python
Python 3.6.2 (default, Nov  2 2017, 19:37:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__version__
'2.0.1'
```

**Comment by t2okve** [comment]
it seems this was my newbie mistake, I did not install in the venv. After doing this it worked. Thank you
