### ISSUE TITLE
Pull 678 - missing file

### ISSUE THREAD

**Issue by solotronics** [ktbyers/netmiko#684]
Pull 678 fails because there is no file HuaweiVrpv8SSH.py in netmiko/huawei
https://github.com/ktbyers/netmiko/pull/678

**Comment by ktbyers** [comment]
The class is defined in `./netmiko/huawei/huawei_ssh.py` so there is no need for a separate file. 

I am not seeing an issue?

```
>>> from netmiko.huawei import HuaweiVrpv8SSH
>>> HuaweiVrpv8SSH
<class 'netmiko.huawei.huawei_ssh.HuaweiVrpv8SSH'>
```

**Comment by solotronics** [comment]
My apologies if I am doing something incorrectly. I have my fork / develop up to date with your branch develop and I am missing HuaweiVrpv8SSH.py

It appears to be missing from develop on yours as well? https://ibb.co/hKyibm

 agaddy@AGADDY-OSX2  ~/Downloads/netmiko/netmiko   junos_shell_mode ● ?  git checkout develop                                                                                          128 ↵  5805  11:20:09
M	netmiko/base_connection.py
M	netmiko/juniper/juniper_ssh.py
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.

 agaddy@AGADDY-OSX2  ~/Downloads/netmiko/netmiko   develop ● ?  ls -l huawei                                                                                                               ✓  5806  11:20:15
total 16
-rw-r--r--  1 agaddy  staff   147 Jan 16 10:42 __init__.py
-rw-r--r--  1 agaddy  staff  3989 Jan 16 10:42 huawei_ssh.py

 agaddy@AGADDY-OSX2  ~/Downloads/netmiko/netmiko   junos_shell_mode ● ?  python3                                                                                                           ✓  5803  11:14:59
Python 3.6.4 (default, Dec 25 2017, 14:57:56)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssh_dispatcher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/agaddy/Downloads/netmiko/netmiko/ssh_dispatcher.py", line 36
    from netmiko.huawei import HuaweiSSH HuaweiVrpv8SSH
                                                      ^
SyntaxError: invalid syntax

**Comment by solotronics** [comment]
oh shoot I wasn't working in a virtualenv and it was referencing the PIP install netmiko and not this develop one. I will close this. sorry!
