### ISSUE TITLE
Using Windows Jump Server From Windows PC to Network Device. 

### ISSUE THREAD

**Issue by viperbmw69** [ktbyers/netmiko#687]
I have not been able to get a working script to Jump through a windows jump server running OpenSSH into a Cisco Router. This is being run from a Windows Machine to start. There is No Linux Servers in the path. I am forced to try to make this work as my company only uses Windows Jump servers. Prompt on Login is as below

administrator@XXXXXXXX C:\Users\Administrator>

I have tried a bunch of device types and I have not found one work yet. 

Thanks

**Comment by ktbyers** [comment]
@viperbmw69 I responded via email (with this content) as well:

This is the standard way I do this:

https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html


Don't know what will work that Windows OpenSSH server though.

You could potentially SSH to the Windows server and then from their SSH to your end devices (all using Netmiko).

If you do this, you might want to look at the terminal_server device_type and using redispatch.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#does-netmiko-support-connecting-via-a-terminal-server


The terminal_server device_type as it doesn't try to do anything post SSH login (so you can manually control what you want to happen until you reach the end device).


Kirk
