### ISSUE TITLE
Show command on Netmiko not displaying any output!!!

### ISSUE THREAD

**Issue by larby22** [ktbyers/netmiko#688]
I ran the following commands below , please help

user@ubuntu:~$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> from netmiko import ConnectHandler
>>> CiscoASR = {
...     'device_type':'cisco_xr',
...     'ip':'192.168.X.X',
...     'username':'verify',
...     'password':'Verify',
...     'port':'22',
...     'verbose': False,
... }
>>> net_connect = ConnectHandler(**CiscoASR)
>>> output = net_connect.send_command('show version')
>>> print output
0/CPU0:MY_ASR9K#show version

Thu Jan 18 18:11:00.878 WAT

>>> output = net_connect.send_command('show ip int brief')
>>> print output
0:IKY_PE_ASR9K_01#show ip
RP/0/RSP0/CPU0:MY_ASR9K#show ip int
RP/0/RSP0/CPU0:MY_ASR9K#show ip int brief

>>>

**Comment by larby22** [comment]
@ktbyers kindly help

**Comment by ktbyers** [comment]
@larby22 Try this:

```
# code above here is the same...
net_connect = ConnectHandler(**CiscoASR)
net_connect.ansi_escape_codes = True
output = net_connect.send_command('show version')
print output
print '-' * 80
print repr(output)
```

**Comment by larby22** [comment]
@ktbyers thanks for checking see output below. It's still not displaying any output.

>>> from netmiko import ConnectHandler
>>> import netmiko
>>> CiscoASR = {
...     'device_type': 'cisco_xr',
...     'ip': '192.168.x.x',
...     'username': 'verify',
...     'password': 'verify',
...     'port': 22,
...     'verbose': False,
... }
>>> net_connect = ConnectHandler(**CiscoASR)
>>> net_connect.ansi_escape_codes = True
>>> output = net_connect.send_command('show version')
>>> print output
0/CPU0:MY_ASR9K#show version

Tue Jan 23 01:27:02.174 WAT

>>> print '-' * 80
--------------------------------------------------------------------------------
>>> print repr(output)
u'0/CPU0:MY_ASR9K_01#show version\n\nTue Jan 23 01:27:02.174 WAT\n'
>>>

**Comment by ktbyers** [comment]
What does the actual show version look like when you do it manually?


Kirk

**Comment by larby22** [comment]
@ktbyers see below sample extract. 

MY_ASR9K_01#show version
Tue Jan 23 01:43:17.548 WAT

Cisco IOS XR Software, Version 5.3.4[Default]
Copyright (c) 2017 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 10.50(c) 1994-2014 by Cisco Systems,  Inc.

MY_ASR9K_01 uptime is 10 weeks, 6 days, 11 hours, 53 minutes
System image file is "disk0:asr9k-os-mbi-5.3.4.sp3-1.0.0/0x100305/mbiasr9k-rsp3.vm"

cisco ASR9K Series (Intel 686 F6M14S4) processor with 33554432K bytes of memory.
Intel 686 F6M14S4 processor at 1899MHz, Revision 2.174
ASR 9010 8 Line Card Slot Chassis with V2 DC PEM

4 Management Ethernet
2 FastEthernet
2 MgmtMultilink
2 SONET/SDH
52 Serial network interface(s)
1 Multilink network interface(s)
40 GigabitEthernet
48 TenGigE
48 DWDM controller(s)
48 WANPHY controller(s)
375k bytes of non-volatile configuration memory.
6271M bytes of hard disk.
25012208k bytes of disk0: (Sector size 512 bytes).
25012208k bytes of disk1: (Sector size 512 bytes).

Configuration register on node 0/RSP0/CPU0 is 0x2102
Boot device on node 0/RSP0/CPU0 is disk0:
Package active on node 0/RSP0/CPU0:
iosxr-infra-5.3.4.sp3, V 1.0.0[SMU], Cisco Systems, at disk0:iosxr-infra-5.3.4.sp3-1.0.0
    Built on Wed Jun 14 19:02:45 WAT 2017
    By iox-lnx-007 in /san1/EFR/sp_r53x_5_3_4/workspace for pie

asr9k-base-5.3.4.sp3, V 1.0.0[SMU], Cisco Systems, at disk0:asr9k-base-5.3.4.sp3-1.0.0
    Built on Wed Jun 14 19:02:45 WAT 2017
    By iox-lnx-007 in /san1/EFR/sp_r53x_5_3_4/workspace for pie

iosxr-mgbl-5.3.4.sp3, V 1.0.0[SMU], Cisco Systems, at disk0:iosxr-mgbl-5.3.4.sp3-1.0.0
    Built on Wed Jun 14 19:02:45 WAT 2017
    By iox-lnx-007 in /san1/EFR/sp_r53x_5_3_4/workspace for pie

iosxr-ce-5.3.4.sp3, V 1.0.0[SMU], Cisco Systems, at disk0:iosxr-ce-5.3.4.sp3-1.0.0
    Built on Wed Jun 14 19:02:45 WAT 2017
    By iox-lnx-007 in /san1/EFR/sp_r53x_5_3_4/workspace for pie

asr9k-fwding-5.3.4.sp3, V 1.0.0[SMU], Cisco Systems, at disk0:asr9k-fwding-5.3.4.sp3-1.0.0
    Built on Wed Jun 14 19:02:45 WAT 2017
    By iox-lnx-007 in /san1/EFR/sp_r53x_5_3_4/workspace for pie

**Comment by ktbyers** [comment]
@larby22 Can you turn on logging and find what you see.

I suspect the prompt is getting messed up because of ANSI escape codes which is causing Netmiko to not properly find the command output.

**Comment by larby22** [comment]
Thanks @ktbyers I am quit new to netmiko . Kindly help point me to how i can enable logging.  Thanks in advance

**Comment by ktbyers** [comment]
@larby22 My bad...I forgot to include the link of how to enable logging earlier...

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by fahadf** [comment]
@ktbyers Sir, I followed your steps here any I still not see the output. Can you please advice? I got the test.log file but I don't see any error or anything out of place.

**Comment by ktbyers** [comment]
You need to post the debugging log. Obscure out any confidential information. @fahadf

**Comment by fahadf** [comment]
```
from netmiko import ConnectHandler
import csv
import getpass
import time
import logging

logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")


username = raw_input('what is your username?!:')
password = getpass.getpass(prompt = 'What is your password?! ')

fw01 = {
	'device_type':'paloalto_panos',
	'ip': '10.10.10.5',
	'username': username,
	'password': password,
}
net_connect = ConnectHandler(**fw01)
net_connect.ansi_escape_codes = True
output = net_connect.send_command('show ntp | match synched')
print (output)
print '-' * 80
print repr(output)


```



> DEBUG:paramiko.transport:starting thread (client mode): 0xb3ae990L
> DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.0
> DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_12.1
> INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_12.1)
> DEBUG:paramiko.transport:kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
> DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
> DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
> DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
> DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
> DEBUG:paramiko.transport:Compression agreed: none
> DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
> DEBUG:paramiko.transport:Switch to new keys ...
> DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.10.10.5: mykey10d7e8e
> DEBUG:paramiko.transport:userauth is OK
> INFO:paramiko.transport:Auth banner: *************************************************************************************
> ************************** Company-FW1, Site  ********************************
> *************************************************************************************
> This is a private system that is the property of the Company, Inc. 
> and its global affiliates (Company). It is for authorized use only.
> 
> To the fullest extent allowable by applicable law, any or all uses of this 
> system and all files on this system may be intercepted, monitored, recorded, 
> copied, audited, inspected, and disclosed to authorized Company personnel, 
> law enforcement personnel and authorized officials.  Company conducts 
> monitoring for the following purposes: to investigate allegations of 
> misconduct, fraud or other wrongdoing; for technical maintenance purposes; 
> to provide system security; to comply with Company policy or legal 
> requirements; for any other lawful business reason. By using this system, 
> the user consents to any such lawful interception, monitoring, recording, 
> copying, auditing, inspection, and disclosure at the discretion of Company.
> 
> If you are a Company authorized user, you acknowledge and agree to Company Acceptable Use Policy.
> 
> Unauthorized or improper use of this system may result in civil and criminal 
> penalties, and disciplinary action under Company policies. By continuing 
> to use this system you acknowledge and agree to these terms and conditions of 
> use. LOG OFF IMMEDIATELY if you do not agree to the conditions stated herein.
> *************************************************************************************
> 
> INFO:paramiko.transport:Authentication (password) successful!
> DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
> DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
> DEBUG:paramiko.transport:Secsh channel 0 opened.
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:netmiko:read_channel: Last login: Tue Feb 13 17:31:12 2018 from 10.54.78.34
> 
> 
> Number of failed attempts since last successful login: 0
> 
> 
> FWadmin@SitedeviceCFW01P(active)> 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: 
> 
> DEBUG:netmiko:read_channel: 
> FWadmin@SitedeviceCFW01P(active)> 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:In disable_paging
> DEBUG:netmiko:Command: set cli pager off
> 
> DEBUG:netmiko:write_channel: set cli pager off
> 
> DEBUG:netmiko:Pattern is: FWadmin\@SitedeviceCFW01P\(active\)
> DEBUG:netmiko:_read_channel_expect read_data: set 
> [KFWadmin@SitedeviceCFW01P(active)> set cli 
> [KFWadmin@SitedeviceCFW01P(active)> set cli pager 
> [KFWadmin@SitedeviceCFW01P(active)> set cli pager off
> 
> DEBUG:netmiko:Pattern found: FWadmin\@SitedeviceCFW01P\(active\) set 
> [KFWadmin@SitedeviceCFW01P(active)> set cli 
> [KFWadmin@SitedeviceCFW01P(active)> set cli pager 
> [KFWadmin@SitedeviceCFW01P(active)> set cli pager off
> 
> DEBUG:netmiko:set 
> [KFWadmin@SitedeviceCFW01P(active)> set cli 
> [KFWadmin@SitedeviceCFW01P(active)> set cli pager 
> [KFWadmin@SitedeviceCFW01P(active)> set cli pager off
> 
> DEBUG:netmiko:Exiting disable_paging
> DEBUG:netmiko:read_channel: FWadmin@SitedeviceCFW01P(active)> 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: 
> 
> DEBUG:netmiko:read_channel: 
> FWadmin@SitedeviceCFW01P(active)> 
> DEBUG:netmiko:In strip_ansi_escape_codes
> DEBUG:netmiko:repr = u'\r\nFWadmin@SitedeviceCFW01P(active)> '
> DEBUG:netmiko:new_output = 
> FWadmin@SitedeviceCFW01P(active)> 
> DEBUG:netmiko:repr = u'\r\nFWadmin@SitedeviceCFW01P(active)> '
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:write_channel: show ntp | match synched
> 
> DEBUG:netmiko:read_channel: 
> DEBUG:netmiko:read_channel: show 
> [KFWadmin@SitedeviceCFW01P(active)> show ntp 
> [KFWadmin@SitedeviceCFW01P(active)> show ntp | 
> [KFWadmin@SitedeviceCFW01P(active)> show ntp | match 
> [KFWadmin@SitedeviceCFW01P(active)> show ntp | match synched
> 
> DEBUG:netmiko:In strip_ansi_escape_codes
> DEBUG:netmiko:repr = u'show \r\x1b[KFWadmin@SitedeviceCFW01P(active)> show ntp \r\x1b[KFWadmin@SitedeviceCFW01P(active)> show ntp | \r\x1b[KFWadmin@SitedeviceCFW01P(active)> show ntp | match \r\x1b[KFWadmin@SitedeviceCFW01P(active)> show ntp | match synched\r\n'
> DEBUG:netmiko:new_output = show 
> FWadmin@SitedeviceCFW01P(active)> show ntp 
> FWadmin@SitedeviceCFW01P(active)> show ntp | 
> FWadmin@SitedeviceCFW01P(active)> show ntp | match 
> FWadmin@SitedeviceCFW01P(active)> show ntp | match synched
> 
> DEBUG:netmiko:repr = u'show \rFWadmin@SitedeviceCFW01P(active)> show ntp \rFWadmin@SitedeviceCFW01P(active)> show ntp | \rFWadmin@SitedeviceCFW01P(active)> show ntp | match \rFWadmin@SitedeviceCFW01P(active)> show ntp | match synched\r\n'
> DEBUG:paramiko.transport:EOF in transport thread
>

**Comment by ktbyers** [comment]
And what exception do you see when you execute your code.

**Comment by fahadf** [comment]
Oh I don't see anything at all. Here is the output:

> 
> MacBook-(2):py_scripts rootuser$ python netmikotesting.py 
> what is your username?!:FWadmin
> What is your password?! 
> 
> show 
> 
> --------------------------------------------------------------------------------
> u'show \n'
> MacBook-(2):py_scripts rootuser$ 
> MacBook-(2):py_scripts rootuser$ 
>

**Comment by ktbyers** [comment]
What does that `show ntp | match synched` look like on the CLI (i.e. what is its CLI output)?

Also what happens if you use `send_command('show ntp')` without the match synced.


Kirk

**Comment by fahadf** [comment]
> FWadmin@SitedeviceCFW01P(active)> show ntp | match synched
>     NTP synched to 10.10.10.10
>         status: synched


> FWadmin@SitedeviceCFW01P(active)> show ntp
> 
> NTP state:
>     NTP synched to 10.10.10.10
>     NTP server: 10.10.10.10
>         status: synched
>         reachable: yes
>         authentication-type: none
>     NTP server: 10.10.10.11
>         status: available
>         reachable: yes
>         authentication-type: none
> 
> FWadmin@SitedeviceCFW01P(active)> 

> 
> 
> Here is the output of the script without the "| match synched":
> 
> MacBook(2):py_scripts rootuser$ python netmikotesting.py 
> what is your username?!:FWadmin
> What is your password?! 
> show 
> 
> 
> --------------------------------------------------------------------------------
> u'show \n\n'
>

**Comment by ktbyers** [comment]
Okay, it looks like the PAN-OS device keeps repainting the line for some reason. This is causing Netmiko to see the trailing router prompt multiple times (which causes it to conclude it has all of the output it needs).

Here is the PAN-OS repainting:

```
DEBUG:netmiko:read_channel: show
�[KFWadmin@SitedeviceCFW01P(active)> show ntp
�[KFWadmin@SitedeviceCFW01P(active)> show ntp |
�[KFWadmin@SitedeviceCFW01P(active)> show ntp | match
�[KFWadmin@SitedeviceCFW01P(active)> show ntp | match synched
```

Is there a way to turn of that line repainting on PAN-OS?

**Comment by fahadf** [comment]
I've noticed that as well. I'm not sure why it does this. "Line repeating" does not look like a feature in PanOS.
I can ask around.

**Comment by fahadf** [comment]
And it looks like netmiko is sending on word at a time in my command and not the whole command at once.

**Comment by ktbyers** [comment]
@fahadf That is panos doing that...it is repainting the line (i.e. echoing the characters that were sent multiple times).

Here is what Netmiko wrote down the SSH channel:

```
DEBUG:netmiko:write_channel: show ntp | match synched

```

**Comment by larby22** [comment]
Hello @ktbyers , 
Kindly find attached debug  output. The debug output displays the expected output in the log but not on the terminal. 
[Debug_log_netmiko.txt](https://github.com/ktbyers/netmiko/files/1730633/Debug_log_netmiko.txt)

larby@ubuntu:~$ sudo python pecheck3.py
>>>>>>>>>> SHOW LOG OF LAST 100_10.10.20.17 <<<<<<<<<<<
Y_ASR9K#show logging
RP/0/RSP0/CPU0:MY_ASR9K #show logging last
RP/0/RSP0/CPU0:MY_ASR9K #show logging last 100


>>>>>>>>>>END OF LAST 100 LOGS_10.10.20.17 <<<<<<<<<<

**Comment by ktbyers** [comment]
I am going to delete all of the PanOS comments from this issue (as two separate possible issues are getting conflated together and it is confusing).

**Comment by larby22** [comment]
Sorry for the mixed up @ktbyers  . I have updated the log with the show version log output (see attached). 
Also find below output from terminal 


from netmiko import ConnectHandler
import netmiko
import logging

logging.basicConfig(filename='test.log',level=logging.DEBUG)
logger = logging.getLogger("netmiko")

CiscoASR = {
'device_type': 'cisco_xr',
'ip': '192.168.20.17',
'username': 'owolabiabu',
'password': 'LarbyARM@224',
'port': 22,
'verbose': False,
 }
net_connect = ConnectHandler(**CiscoASR)
net_connect.ansi_escape_codes = True
output = net_connect.send_command('show version')
print output
[Debug_log_netmiko(show version).txt](https://github.com/ktbyers/netmiko/files/1734567/Debug_log_netmiko.show.version.txt)

**Comment by larby22** [comment]
Hi @ktbyers sorry for the mix up. I have attached the log output for "show version" . 

Also kindly find below output on the terminal
>>>from netmiko import ConnectHandler
>>>import netmiko
>>> import logging
>>>
>>> logging.basicConfig(filename='test.log',level=logging.DEBUG)
>>> logger = logging.getLogger("netmiko")
>>>
>>> CiscoASR = {
... 'device_type': 'cisco_xr',
... 'ip': '192.168.2.1',
... 'username': 'verify',
... 'password': 'verify',
... 'port': 22,
... 'verbose': False,
...  }
>>> net_connect = ConnectHandler(**CiscoASR)
>>> net_connect.ansi_escape_codes = True
>>> output = net_connect.send_command('show version')
>>> print output
0/CPU0:MY_PE_ASR9K_01#show version

Sun Feb 18 10:39:05.001 WAT

>>>

[Debug_log_netmiko(show version).txt](https://github.com/ktbyers/netmiko/files/1734570/Debug_log_netmiko.show.version.txt)

**Comment by ktbyers** [comment]
Do you have timestamps turned on (for this device)? If so I would probably turn those off.

@larby22

**Comment by artyomovs** [comment]
Hi guys. 
@larby22 @ktbyers  
Did you figure this out? I've got the same issue. No output in netmiko send_command. 
Here is my script: 
`from netmiko import ConnectHandler
cli = ConnectHandler(   device_type='cisco_ios_telnet',
                        ip='10.0.20.1',
                        username ='cisco',
                        password= 'cisco',
                        secret= 'cisco')

cli.enable()
cli.ansi_escape_codes = True
result = cli.send_command('show ip int br')
print(result)`

output is empty.

**Comment by ktbyers** [comment]
@artyomovs Are you using Netmiko 3.0.0? It just recently came out. If not, can you re-test with Netmiko 3.0.0.

Thanks, Kirk
