### ISSUE TITLE
I can't set expert password on checkpoint firewall

### ISSUE THREAD

**Issue by samzeg** [ktbyers/netmiko#689]
Hi Experts,

I appreciate the effort that has been done to get us this valuable tool. I'm new to pythona dn I work a lot on checkpoint products and I want to use netmiko to automate stuff.
I was able to use the connethandler() fine and connect just fine to the device , even sending clish to show information or set configuration.

The issue that I'm running into is when I send the command "set expert-password" the firewall will return a prompt with Enter new password:, I didn't now how to pass the password using send_command and send_command_expect(). it just sits there and timeout.

The flow should like this:

send the command "set expert-password" after that the firewall will prompt the following Enter new expert password:

after you enter the password it is going to prompt you again with Enter new expert password (again): to confirm.

here is a screenshot from my lab machine when using the commands manually

![image](https://user-images.githubusercontent.com/35621210/35180472-b8a0fd8c-fd76-11e7-9dd2-8e491e868391.png)

I' didn't know how to del with interactive prompt asking questions and looking for input

Thanks

**Comment by ktbyers** [comment]
@samzeg Use the `send_command_timing` method. Something like:

```
output = net_connect.send_command_timing("set expert-password")
if 'new expert password' in output:
    output = net_connect.send_command_timing(expert_password)
if 'new expert password (again)' in output:
    output = net_connect.send_command_timing(expert_password)
```

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#show-commands-that-prompt-for-more-information

**Comment by samzeg** [comment]
Hi Ktbyers,
It seems the function send_command_timing() didn't do the trick, the program still stucked waiting on input.

here is my code
import netmiko
ckp = {
	   'device_type':'checkpoint_gaia',
	   'ip':'192.168.19.100',
	   'username':'admin',
	   'password':'vpn123',
}

net_connect = netmiko.ConnectHandler(**ckp)
output = net_connect.send_command_timing("set expert-password")
print (output)
pwd ='vpn123456'
pwd2= 'vpn123'
output2 =''
cmd = 'lock database override'
output = net_connect.send_command(cmd)

if 'Enter current expert password:' in output:
	output = net_connect.send_command_timing(pwd, delay_factor = 3)
	output2 = output
	print (output2)

print (output2)	
	
if 'Enter new expert password:' in output:
    output = net_connect.send_command_timing(pwd2, delay_factor = 3)
    output2 = output
    print (output2)

print (output2)	    
if 'Enter new expert password (again):' in output:
	output = net_connect.send_command_timing(pwd2, delay_factor = 3)
	output2 = output
	print (output2)
	      	      
output2 = net_connect.send_command_timing("save config")
print output2



results:
+++++

Enter current expert password:

Any help on this much appreciated?

Thanks



[Finished in 21.044 seconds]

**Comment by ktbyers** [comment]
@samzeg You can't do this:

```
net_connect = netmiko.ConnectHandler(**ckp)
# You send the `set expert-password` command
output = net_connect.send_command_timing("set expert-password")
print (output)
pwd ='vpn123456'
pwd2= 'vpn123'
output2 =''
# You then try to send this other command, but the device is already waiting for the password.
cmd = 'lock database override'
output = net_connect.send_command(cmd)
```

You are trying to send another command down the channel `local database override` after you have entered the `set expert-password` (i.e. the device is waiting for you to enter in the password twice)

**Comment by samzeg** [comment]
Thanks for the reply. You are right, I had a typo. the steps should be:

1-  Sending the command "lock database override"  to be able to make modification to the config
2-  Sending the command "set expert-password" which the device should wait on me to type the "Enter current expert password:" and press enter after that the device will wait on me to type the new password "Enter the new expert password:" and press enter after that the device wait on me to confirm the password "enter the new expert password (again):" and press enter.

My problem is "I don't know how to respond to the device when it waits on me" my mistake I'm sending the password as a command, i'm not sure how to send the response when the device is waiting on me.


Thanks

**Comment by ktbyers** [comment]
@samzeg Not sure I understand your question, just do something like this:

```
expert_password = 'new_password'
output = net_connect.send_command_timing("set expert-password")
if 'new expert password' in output:
    output = net_connect.send_command_timing(expert_password)
if 'new expert password (again)' in output:
    output = net_connect.send_command_timing(expert_password)
```

**Comment by samzeg** [comment]
Hi Ktbyers,
I tried the provided solution but I still facing the same results, the Program stops when the device asking me to "Enter current  expert password:" . here is my code

import netmiko
ckp = {
	   'device_type':'checkpoint_gaia',
	   'ip':'192.168.19.100',
	   'username':'admin',
	   'password':'vpn123',
}

net_connect = netmiko.ConnectHandler(**ckp)

expert_password = 'vpn123'
expert_password_new = 'vpn123456'


# send the command lock database override to enable DB editing


output = net_connect.send_command_timing("lock database override")

print output

# send the command set expert-password
output = net_connect.send_command_timing("set expert-password")

# The device will ask me for the current expert password
if ' Enter current expert password:' in output:
    output = net_connect.send_command_timing(expert_password)

print output

# The device will ask me for the new password
if 'new expert password ' in output:
    output = net_connect.send_command_timing(expert_password_new)

print output

# The device will ask me for the new password again for confirmation
if 'new expert password (again) ' in output:
    output = net_connect.send_command_timing(expert_password_new)

print output

# send the command save config to save the changes

output = net_connect.send_command_timing("save config")

print output


Here is the Execution results
===================

CLICMD0201  Config lock is already turned on.
Enter current expert password:
Enter current expert password:
Enter current expert password:

![image](https://user-images.githubusercontent.com/35621210/35604616-a2a1ecae-0608-11e8-8b3d-501a5d82052f.png)


Thanks

**Comment by ktbyers** [comment]
@samzeg Please reformat your markdown above correctly using the \`\`\` to enclose code. It should look like this when done:

```
# An example of code in markdown
if 'new expert password (again) ' in output:
    output = net_connect.send_command_timing(expert_password_new)
print output
```

**Comment by samzeg** [comment]
Thanks for the comment I did correct the previous comment

**Comment by ktbyers** [comment]
@samzeg Can you show me the entire CLI output when doing the exact same set of commands you are trying to do in the script. So you need to include `lock database override` command.

Also note, your two screenshots are different...the first one using `set expert-password` didn't prompt for the current password; the second one did.

**Comment by samzeg** [comment]
Hi ktbyers,
Here is the CLI output of the commands that I'm trying to send using the script
![image](https://user-images.githubusercontent.com/35621210/35949054-42d1d14e-0c35-11e8-918f-b1b065279945.png)

The first screenshoot, show the setup of the expert password when the device is fresh installed and the password was never set.

The second screenshot was prompting  for the current expert password because the expert password was already set and we wanted to change it.

Thanks for your help

**Comment by maughanc** [comment]
Samzeg,

Did you get this working? I have the same problem.

**Comment by maughanc** [comment]
I tried this:
output = net_connect.send_command("set expert-password", expect_string='Enter current expert password: ')
print(output)

Which results in this:
Traceback (most recent call last):
  File "ChangePass.py", line 26, in <module>
    output = net_connect.send_command("set expert-password", expect_string='Enter current expert password: ')
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 1322, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: Enter current expert password:

Otherwise, I was getting the same as you:
Enter current expert password:
Enter current expert password:
Enter current expert password:

Either way, stuck at the moment.

**Comment by samzeg** [comment]
maughanc,

I gave up on that. However, I found another way. I log in to checkpoint manager using python after that I generate an md5 salt hash for the wanted password. finally, I use the cprid_util on the manager to execute any commands on the firewalls.
You can follow these links:
This link will show you how to generate the md5-salted-hash for a password without working in interactive mode:
https://stackoverflow.com/questions/28729457/use-grub-md5-crypt-in-a-script-where-user-is-prompted-for-password-to-encrypt

The following link will show you how to execute commands remotely and change the password using clish set-expert-password-hash command

https://itblogsec.com/checkpoint-fw-gaia-remote-adminexpert-password-reset/

you can combine the information from both links and iterate over csv file or any other information where you store the gateways IPs  to send commands to all firewalls from central location.

good Luck

**Comment by satishmantri** [comment]
Hi samzeg,

can you share the log in to checkpoint manager using python script for password changes
Thanks
sa
