### ISSUE TITLE
hp_procurve should check for enable mode before

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#694]
executing enable command.

**Comment by jcrotts** [comment]
would this be a check in the beginning of enable() such as:
`if self.check_enable_mode():
    return true`

**Comment by ktbyers** [comment]
@jcrotts You would need to look at the prompt (i.e. does it end in `>` or does it end in '#') or the privilege level).


Basically, if the prompt ends in `#` the device is in enable mode and the `check_enable_mode` method would return True. If not the `check_enable_mode` would return False.

Then in the `enable` function we would call this `check_enable_mode()` and only try to go into enable mode if we weren't already there.

I am making some assumptions here about ProCurves so I would need to check their behavior.

**Comment by jcrotts** [comment]
Okay, I can double check the ProCurve behavior. Could I just add this to the existing PR I have, or should I put it in a new one?

**Comment by ktbyers** [comment]
A separate one...your previous PR is already a part of that branch I am working on (so I wouldn't get your additions).

Also they are two separate areas so better to have separate PRs for them.

**Comment by ktbyers** [comment]
@jcrotts You should be able to see existing patterns in `base_connection.py` and in `cisco_base_connection.py`.

**Comment by jcrotts** [comment]
@ktbyers Right, okay I'll do that, and I'll look at the existing patterns in base_connection.py and cisco_base_connection.py.

**Comment by jcrotts** [comment]
Based on the following doc:
ftp://ftp.hp.com/pub/networking/software/Mgmt-Oct2005-59906023-Chap04.pdf
<img width="805" alt="screen shot 2018-02-01 at 2 16 28 pm" src="https://user-images.githubusercontent.com/29685007/35706457-a6e21dfe-075a-11e8-8e94-e2c9b612d618.png">


It looks like the HP ProCurve enable prompt is identical to Cisco's. Should I create a new check_enable_mode method inside the HP ProCurve class using super, or just use the CiscoBase check_enable_mode?

**Comment by ktbyers** [comment]
Here is the current code for HP ProCurve:

```
    def enable(self, cmd='enable', pattern='password', re_flags=re.IGNORECASE,
               default_username='manager'):
        """Enter enable mode"""
        output = self.send_command_timing(cmd)
        if 'username' in output.lower() or 'login name' in output.lower() or \
                'user name' in output.lower():
            output += self.send_command_timing(default_username)
        if 'password' in output.lower():
            output += self.send_command_timing(self.secret)
        log.debug("{}".format(output))
        self.clear_buffer()
        return output
```

Notice, I check for username, login name, or user name (in addition to checking for the password prompt).

This makes me think the behavior is different than Cisco IOS.

I would add a check_enable_mode() method and see if I was already at the '#' prompt before sending the enable command. So the end `enable` method would look like this:

```
    def enable(self, cmd='enable', pattern='password', re_flags=re.IGNORECASE,
               default_username='manager'):
        """Enter enable mode"""
        if check_enable_mode():
           return ''
        output = self.send_command_timing(cmd)
        if 'username' in output.lower() or 'login name' in output.lower() or \
                'user name' in output.lower():
            output += self.send_command_timing(default_username)
        if 'password' in output.lower():
            output += self.send_command_timing(self.secret)
        log.debug("{}".format(output))
        self.clear_buffer()
        return output
```

**Comment by jcrotts** [comment]
Okay that makes sense!
