### ISSUE TITLE
TFTP

### ISSUE THREAD

**Issue by tetzispa** [ktbyers/netmiko#696]
Hello,

as the "scp_transfer" on your example, is there a way to do some transfer with tftp protocol ?

and, i dont see any IP for the SCP server, so, how the device knows where he should download his file ?

im trying to do some tftp transfer on HP comware, if netmiko cant, i should do all the scripting ? :)

thx for the reply

**Comment by ktbyers** [comment]
@tetzispa You can also use Netmiko `send_command` and `send_command_timing` to execute commands on the network device. So you should be able to execute a TFTP session in this way.

The transfer in both directions is controlled via the Linux machine where the script runs. So the file would be transferred to/from that machine.


Kirk
