### ISSUE TITLE
FTD connection - prompt issue?

### ISSUE THREAD

**Issue by hawthorn** [ktbyers/netmiko#698]
The prompt is a u'>'

In [89]: new_dict = {'device_type': 'cisco_asa', 'ip': 'IP_Address',
    ...:     'username': 'admin', 'password': 'passwd',
    ...:     'port': 22, 'verbose': False}
In [90]: net_connect = ConnectHandler(**new_dict)
In [91]: net_connect.ansi_escape_codes = True
In [92]: output = net_connect.send_command('show version')
In [93]: output
Out[93]: ''
In [106]: net_connect.find_prompt()
Out[106]: '\x07'

I am also unable to modify the prompt:

In [73]: net_connect.set_base_prompt(u'>')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-73-f104e5b1688b> in <module>()
----> 1 net_connect.set_base_prompt(u'>')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/cisco/cisco_asa_ssh.py in set_base_prompt(self, *args, **kwargs)
     71         happens the trailing '(config*' needs stripped off.
     72         """
---> 73         cur_base_prompt = super(CiscoAsaSSH, self).set_base_prompt(*args, **kwargs)
     74         match = re.search(r'(.*)\(conf.*', cur_base_prompt)
     75         if match:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py in set_base_prompt(self, pri_prompt_terminator, alt_prompt_terminator, delay_factor)
    784         prompt = self.find_prompt(delay_factor=delay_factor)
    785         if not prompt[-1] in (pri_prompt_terminator, alt_prompt_terminator):
--> 786             raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
    787         # Strip off trailing terminator
    788         self.base_prompt = prompt[:-1]

ValueError: Router prompt not found: '\x07'

**Comment by ktbyers** [comment]
@hawthorn What does the CLI look like? 

Can you show a CLI-SSH session starting from the remote machine until completely logged in. Also please execute a some show command.

A prompt of just '>' will likely break the existing ASA driver.


Kirk

**Comment by hawthorn** [comment]
ssh admin@XXXXXXXXXXXXX
You have accessed a PRIVATE NETWORK which contains confidential
information. All unauthorized users of this network or of information
contained within will be prosecuted.

Password: 
Last login: Thu Feb  8 08:10:47 2018 from XXXXXXXX

Copyright 2004-2017, Cisco and/or its affiliates. All rights reserved. 
Cisco is a registered trademark of Cisco Systems, Inc. 
All other trademarks are property of their respective owners.

Cisco Fire Linux OS v6.2.2 (build 11)
Cisco ASA5508-X Threat Defense v6.2.2 (build 81)

> 
> show version 
-------[ XXXXXXXXXXX ]--------
Model                     : Cisco ASA5508-X Threat Defense (75) Version 6.2.2 (Build 81)
UUID                      : XX-XX-XX-XX-XX
Rules update version      : 2018-02-05-001-vrt
VDB version               : 287
----------------------------------------------------

>

**Comment by hawthorn** [comment]
ssh cli prompt is: 
prompt = u'> '

> 


In [39]: net_conn.write_channel('show ip arp\n')
In [40]: output = net_conn.read_channel()
In [41]: print(output)
showiparp
In [42]: net_conn.find_prompt()
Out[42]: '\x07'


DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^G
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x07'
DEBUG:netmiko:new_output = ^G
DEBUG:netmiko:repr = '\x07'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'show version\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: show^Gversion^G
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'show\x07version\x07'
DEBUG:netmiko:new_output = show^Gversion^G
DEBUG:netmiko:repr = 'show\x07version\x07'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: ^G^G
DEBUG:netmiko:write_channel: b'show arp\n'
DEBUG:netmiko:read_channel: show^Garp^G
DEBUG:netmiko:write_channel: b'show arp\r\n'
DEBUG:netmiko:read_channel: showESCE^Garp^G^G
DEBUG:parso.python.diff:diff parser start
DEBUG:parso.python.diff:diff parser calculated
DEBUG:parso.python.diff:diff: line_lengths old: 1, new: 1
DEBUG:parso.python.diff:diff replace old[1:1] new[1:1]
DEBUG:parso.python.diff:parse_part from 1 to 1 (to 0 in part parser)
DEBUG:parso.python.diff:diff parser end
DEBUG:parso.python.diff:diff parser start
DEBUG:parso.python.diff:diff parser calculated
DEBUG:parso.python.diff:diff: line_lengths old: 1, new: 1
DEBUG:parso.python.diff:diff replace old[1:1] new[1:1]
DEBUG:parso.python.diff:parse_part from 1 to 1 (to 0 in part parser)
DEBUG:parso.python.diff:diff parser end
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^G
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\x07'
DEBUG:netmiko:new_output = ^G
DEBUG:netmiko:repr = '\x07'
DEBUG:netmiko:read_channel: 
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)

**Comment by carlniger** [comment]
Closing as this is old and a dup of #1067
