### ISSUE TITLE
cannnot connect to Cisco Nexus

### ISSUE THREAD

**Issue by yunithon** [ktbyers/netmiko#700]
Hi,  @ktbyers 

I am not able to connect to Cisco Nexus.
I am using 
Netmiko version 2.0.1
Python 3.4.

I am trying the below script:
 <br>
 <br>

from netmiko import ConnectHandler
from datetime import datetime

cisco = {
    "device_type": "autodetect",
    "ip": "IP",        # IP
    "username": "USER",      # login user
    "password": "PASS",  # login user password
    "secret": SECRET",   # enable password
}

net_connect = ConnectHandler(**cisco)
net_connect.enable()

print("--- [BF Check] ---")
output = net_connect.send_command("show run int vlan 1")
print(output)

print("\n--- [AF Check] ---")
output = net_connect.send_command("show run int vlan 1")
print(output)

net_connect.disconnect()

 <br>
 <br>
 I am getting the following error:
 <br>
 <br>
--- [BF check] ---
               ^
% Invalid input detected at '^' marker.

--- [AF check]---
               ^
% Invalid input detected at '^' marker.
 <br>
 <br>
Thank you in advance.

**Comment by ktbyers** [comment]
@yunithon Can you get rid of the `autodetect` and try it with `cisco_nxos` and see if it works?

**Comment by ktbyers** [comment]
You can't use autodetect in that way...you use autodetect to find the device_type, but then you need to reconnect:

```
>>> from netmiko.ssh_autodetect import SSHDetect
>>> from netmiko.ssh_dispatcher import ConnectHandler
>>> remote_device = {'device_type': 'autodetect',
                     'host': 'remote.host',
                     'username': 'test',
                     'password': 'foo'}
>>> guesser = SSHDetect(**remote_device)
>>> best_match = guesser.autodetect()
>>> print(best_match) # Name of the best device_type to use further
>>> print(guesser.potential_matches) # Dictionary of the whole matching result

# Netmiko connection creation section
>>> remote_device['device_type'] = best_match
>>> connection = ConnectHandler(**remote_device)
```

**Comment by yunithon** [comment]
Thank you for your replay.
Okay I got how to use autodetect.
 
I changed autodetect to cisco_nxos, but it seems it does not work...I got the same results.

And I think it cannot get into enable mode.
Becuse I put net_connect.find_prompt() as below, but also I got the same.

net_connect = ConnectHandler(**cisco)
net_connect.enable()
net_connect.find_prompt()

<br>
<br>

--- [BF check] ---
               ^
% Invalid input detected at '^' marker.

--- [AF check]---
               ^
% Invalid input detected at '^' marker.

**Comment by ktbyers** [comment]
@yunithon You probably should enable logging so you can better see what is happening:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by yunithon** [comment]
I was able to solve it.
The  problem was the host name of Nexus. 
It included #, so just the proglam was not able to read corectly, I think.
thank you for your kind help.
