### ISSUE TITLE
Configuration commands not being sent to NX-OS, receiving traceback

### ISSUE THREAD

**Issue by NtwkEngineer** [ktbyers/netmiko#702]
Hi Kirk:

I am seeing the following when trying to send configuration commands to an NX-OS device (Nexus 3048 running 6.0(2)U3(7)):

>net_connect = ConnectHandler(device_type='cisco_nxos', ip='192.168.1.1', username='a_username', password='a_password', secret='a_password')

>net_connect.config_mode()

u'config term\r\r\nEnter configuration commands, one per line.  End with CNTL/Z.\r\n\rNexus3K(config)# '

>if_name = 'Ethernet1/48'

>net_connect.send_command('interface %s' % if_name)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 967, in send_command
IOError: Search pattern never detected in send_command_expect: Nexus3K\(config\)\#

>net_connect.send_command('interface Ethernet1/48')

u''

Given that it's returning a unicode '', I was able to work around this in my script by using the 'expect_string' option in .send_command():

> net_connect.send_command('interface %s' % if_name, expect_string='') 

u''

Is this expected behavior, or should netmiko be handling this differently?

Thanks!

-Matt

**Comment by NtwkEngineer** [comment]
And actually, I'm seeing the same issue with IOS-XE on a 4500-X running 03.06.00.E.  Same workaround as well.

**Comment by ktbyers** [comment]
@NtwkEngineer You should use `send_config_set()` method to send configuration changes and not try to manually enter/exit config mode.

`send_config_set()` will automatically enter/exit config mode.

For example:

```
config_commands=[cmd1, cmd2]
net_connect.send_config_set(config_commands)
```

**Comment by NtwkEngineer** [comment]
Perfect, thanks Kirk!
