### ISSUE TITLE
netmiko_tools error - missing 'ipaddress' module

### ISSUE THREAD

**Issue by opnine** [ktbyers/netmiko#703]
Hello,
Im using  netmiko_toosl the command netmiko-show --cmd but I get this error,
     No handlers could be found for logger "paramiko.transport"
I did an ssh to the devices and I have no problem I can connect, but I also tried  this script lines
#!/usr/bin/env python
 
from netmiko import ConnectHandler
 
iosv_l2_s1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.1.10',
    'username': 'cisco',
    'password': 'cisco',
}
 
net_connect = ConnectHandler(**iosv_l2_s1)
output = net_connect.send_command('show ip int brief')
print(output)

And got this error

o handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    net_connect = ConnectHandler(**iosv_l2_s1)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 168, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 187, in __init__
    self.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 650, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 545, in start_client
    raise e
ImportError: No module named ipaddress

Any help is appreciated.

Thanks

**Comment by ktbyers** [comment]
It looks like you are missing the module `ImportError: No module named ipaddress`.

You might want to `pip install paramiko==2.4.0`

And then if that doesn't fix it...`pip install ipaddress`

**Comment by opnine** [comment]
hello,
from  the pip list
i have paramiko (2.4.0) & ipaddress (1.0.19)
Thanks.

**Comment by ktbyers** [comment]
Does `python -m pip list` show the same thing? The `paramiko` exception above is complaining that it can't import the `ipaddress` module.

**Comment by opnine** [comment]
Hi 
this is the output or the pip

 python -m pip list
ansible (2.4.3.0)
apt-xapian-index (0.45)
argparse (1.2.1)
asn1crypto (0.24.0)
bcrypt (3.1.4)
certifi (2018.1.18)
cffi (1.11.4)
chardet (3.0.4)
colorama (0.2.5)
configobj (4.7.2)
cryptography (2.1.4)
enum (0.4.6)
future (0.16.0)
html5lib (0.999)
idna (2.6)
ipaddress (1.0.19)
Jinja2 (2.10)
jtextfsm (0.3.1)
junos-eznc (2.1.7)
Landscape-Client (14.12)
lxml (4.1.1)
MarkupSafe (1.0)
napalm (2.3.0)
ncclient (0.5.3)
netaddr (0.7.19)
netmiko (2.0.1)
PAM (0.4.2)
paramiko (2.4.0)
pip (1.5.4)
ply (3.4)
pyasn1 (0.4.2)
pycparser (2.18)
pyeapi (0.8.1)
pyIOSXR (0.52)
PyNaCl (1.2.1)
pynxos (0.0.3)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.12)
requests (2.18.4)
scp (0.10.2)
setuptools (38.5.1)
six (1.5.2)
ssh-import-id (3.21)
textfsm (0.3.2)
Twisted-Core (13.2.0)
urllib3 (1.22)
wheel (0.24.0)
wsgiref (0.1.2)
zope.interface (4.0.5)

**Comment by ktbyers** [comment]
What happens if you try to:

```
python
Python 2.7.12 (default, Nov  2 2017, 19:20:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
```

**Comment by ktbyers** [comment]
FYI, the paramiko logger warning is not relevant.

**Comment by ktbyers** [comment]
You might to try turning on logging:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Also you might want to try building a new virtual environment from scratch. 

Also, what does this show you?

```
$ python
Python 2.7.12 (default, Nov  2 2017, 19:20:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipaddress
>>> ipaddress.__file__
```

**Comment by opnine** [comment]
I get this output
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> import ipaddress
>>> ipaddress.__file__
'/usr/local/lib/python2.7/dist-packages/ipaddress.pyc'
>>> 
The issue is not the logging for me the issue is after i get the error from the logging the I cant connect to any of my devices, I tried ssh only and it works.

When I have a new linux I normally install the following packages. please let me know if I should add more 
sudo apt-get install python-pip
sudo apt-get install python-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev python-pip
sudo pip install enum
sudo python -m pip install netmiko
sudo pip install napalm
sudo apt-get install -y --force-yes libssl-dev libffi-dev python-dev python-cffi

**Comment by opnine** [comment]
hello 
I did the reinstall and is working, I only have one question, can I change the output color?

**Comment by ktbyers** [comment]
Yes, there are some Python libraries for coloring terminal output.
