### ISSUE TITLE
How to Handle a Firewall Failover

### ISSUE THREAD

**Issue by ncutting** [ktbyers/netmiko#706]
Good afternoon,

I have adapted parts your firewall upgrade script - although I have to make it work on fail-over ASA pairs that may have one ONE IP address.  Probably 20 percent of our hundreds of firewalls may have only one public IP - so we need to upgrade the pairs using the "failover" method.

I have it all working except for when I failover the firewall - I am connected to the primary device - then when I issue the no failover active command - the connection drops as the IP address is moved to the secondary.  

Even with a disconnect() directly after the command - I think that netmiko is waiting for the prompt to return from the previous command.  Is there a way to make it disconnect without waiting for the prompt to return? It will never return as the firewall has changed IP (often to nothing) while netmiko was connected.

My code is as below: 
```python
ssh_conn = ConnectHandler(**net_device)

output = ssh_conn.send_command('show failover | in Ready')

if 'Standby Ready' in output:
	print('Failing Over Firewall')
	output = ssh_conn.send_command('no failover active')
	ssh_conn.disconnect()
else:
	print('Fix your Failover before trying to failover\nExiting')
	exit()
```
It eventually times out with:

> failover.py
Failing Over Firewall
Traceback (most recent call last):
  File "I:\Netmiko Scripts\ASA-UPGRADE\test.py", line 9, in <module>
    output = ssh_conn.send_command('no failover active')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\netmiko\cisco\cisco_asa_ssh.py", line 54, in send_command
    output = super(CiscoAsaSSH, self).send_command(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\netmiko\base_connection.py", line 967, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: ISPFW01\/sec\/act\#

**Comment by ktbyers** [comment]
@ncutting Use `send_command_timing()` here (so Netmiko just sends it and doesn't wait for a response).

```
output = ssh_conn.send_command_timing('no failover active')
```

Also don't try to `disconnect()` as that will probably try to send the `exit` command and the SSH session is probably already terminated.

**Comment by ncutting** [comment]
Thank you - this worked fine.
