### ISSUE TITLE
HPComware enable issue

### ISSUE THREAD

**Issue by asdfhxc** [ktbyers/netmiko#712]
<s5500-1>?
User view commands:
  cfd      Connectivity fault detection (IEEE 802.1ag) 
  cluster  Run cluster command
  display  Display current system information
  ping     Ping function 
  quit     Exit from current command view
  ssh2     Establish a secure shell client connection 
  super    Set the current user priority level 
  telnet   Establish one TELNET connection 
  tracert  Trace route function 
<s5500-1>

def enable(self, cmd='system-view'):
        """enable mode on Comware is system-view."""
        return self.config_mode(config_command=cmd)

if super password has set ,the user privi is not level 3 ,the cmd='system-view' is Unrecognized ,cmd='super'，eg:

<s5500-1>super
Please input the password to change the privilege level. Press CTRL_C to abort.
 Password:
User privilege level is 3, and only those commands can be used 
whose level is equal or less than this.
Privilege note: 0-VISIT, 1-MONITOR, 2-SYSTEM, 3-MANAGE
<s5500-1>

so what should we do ?

**Comment by carlniger** [comment]
Going to close this as I think its reasonable to assume that netmiko has appropriate privileges to disable paging and such. Feel free to reopen if anyone disagrees / this warrants more discussion!
