### ISSUE TITLE
Non configurable hardcoded delay factors

### ISSUE THREAD

**Issue by xavierhardy** [ktbyers/netmiko#714]
I'm taking a look at netmiko's performance issues as you might have noticed. I have taken a look at paramiko, and it seems to perform quite well, despite being mostly in Python, so the issue has to be in netmiko. Indeed, as expected most of the slowdowns come from `sleep` calls. My opinion is that they should be all configurable to be able to tune netmiko speed. It should be clearly documented that decreasing delays will make the process use more CPU. However, it seems that the `global_delay_factor` is not enough to limit delays.

I tested the following code in a Docker container with `sshd` running locally and I have given netmiko access to this server by giving it a private key.

```py
#!/usr/bin/env python

from netmiko import ConnectHandler

ssh_conn = ConnectHandler(
    device_type="linux",
    ip="127.0.0.1",
    username="root",
    use_keys=True,
    verbose=False,
    global_delay_factor=0,
)
output = ssh_conn.send_command("ls", delay_factor=0)
```
It connects to the local SSH server and executes `ls`. The global delay factor as well as the delay factor in `send_command` are set to 0. It speeds up the execution as expected but still took almost 3 seconds to execute, so I ran a profiler to check where it spent time sleeping.

```bash
# python -m cProfile -s time netmiko_test.py > results.txt
```
```bash
# grep -P "\d*[1-9]\.\d+" results.txt 
         64737 function calls (62675 primitive calls) in 2.919 seconds
       87    2.598    0.030    2.598    0.030 {time.sleep}
        1    0.000    0.000    2.920    2.920 netmiko_test.py:3(<module>)
        1    0.000    0.000    2.203    2.203 base_connection.py:397(_read_channel_timing)
        1    0.000    0.000    2.203    2.203 base_connection.py:679(_test_channel_read)
        1    0.000    0.000    2.620    2.620 base_connection.py:36(__init__)
        1    0.000    0.000    2.413    2.413 base_connection.py:531(session_preparation)
        1    0.000    0.000    2.620    2.620 ssh_dispatcher.py:167(ConnectHandler)
        1    0.000    0.000    2.413    2.413 linux_ssh.py:13(session_preparation)
```
As it can be seen here, `self.session_preparation` causes the slowdown, more exactly, `self.set_base_prompt` has `delay_factor` left by default to 1, which is therefore, though it is given as an argument, hardcoded here.

I had a look at the code to find other instances of this issue, and I have found several functions being called without a configurable `delay_factor`: `serial_login`, `telnet_login`, `_read_channel_timing` . I have also found an instance where a hardcoded value was given as a `delay_factor` (in scp_handler.py).

I'm not sure how to tackle this issue as the original delay factor must not be changed in order not to break anything. Should a new delay factor be created? or should it be `global_delay_factor` used everywhere? or anything else?

**Comment by xavierhardy** [comment]
Take a look at #715 which proposes a possible solution. I'll try to implement it ASAP.

**Comment by carlniger** [comment]
Going to close this as #715 has all the relevant conversation.

**Comment by pvalois** [comment]
i've discovered that most of the lost times  is during the net_connect.disconnect()

if i sys.exit(0) without disconnecting, i get 3s for the script running, and 11s if i disconnect properly.
