### ISSUE TITLE
netmiko wrong output when command character longer than 50

### ISSUE THREAD

**Issue by atmoskr** [ktbyers/netmiko#717]
I am trying to use netmiko under windows 10 with python 2.7. When I try to use send_command_set which is including over than 50 character in commands, some special character is including in the output. Because of this wrong output, automation test script is misleading.

Could anybody let me know how to solve the problem?

(For your information, I am testing DASAN device but since netmiko doesn't support DASAN device, I am using as cisco ios type instead.)

```
from __future__ import absolute_import, division, print_function
import netmiko

output = conn.send_config_set([
    'no service dhcp',
    'service dhcp',
    'ip dhcp option format circuit_id',
    'attr 3 type 0 length-hidden 6 value string 2412533'])

device = {
"device_type": "cisco_ios_telnet",
"ip": "10.47.250.57",
"username": "admin",
"password": ""
}

conn = netmiko.ConnectHandler(**device)
conn.enable()
output = conn.send_config_set(['ip dhcp option format circuit_id',
        'attr 3 type 0 length-hidden 6 value string 2412533'])
print(output)
conn.disconnect()
```

Here is output having unexpected special character ("?[K3" in the end)
```
config term
SWITCH(config)# ip dhcp option format circuit_id
SWITCH(dhcp-opt[circuit_id])# attr 3 type 0 length-hidden 6 value string 2412533
?[ASWITCH(dhcp-opt[circuit_id])# attr 3 type 0 length-hidden 6 value string 241253?[K3
SWITCH(dhcp-opt[circuit_id])# end
SWITCH#
```

If I use 49 character instead, it works fine.
```
config term
SWITCH(config)# ip dhcp option format circuit_id
SWITCH(dhcp-opt[circuit_id])# attr 3 type 0 length-hidden 6 value string 241253
SWITCH(dhcp-opt[circuit_id])# end
SWITCH#
```

**Comment by carlniger** [comment]
@atmoskr as this is quite old ill mark this pending close, however it may be worth looking into how that platform handles terminal width -- including your prompt that is 80 characters long so the default width may cause wrapping that netmiko can't handle (this occurs in ASA platform too which is why netmiko handles this (or tries to)). HTH

**Comment by carlniger** [comment]
inactive. closing.
