### ISSUE TITLE
having trouble with config of vsan database on CISCO MDS 9710

### ISSUE THREAD

**Issue by dmlancaster** [ktbyers/netmiko#718]
CISCO MDS 9710 v8.1

Need to be able to send vsan commands:

I can get into the write mode in config using 
            net_connect.config_mode()
            net_connect.send_command(command_string="vsan database", auto_find_prompt=False)

and I can see the prompt gets set to:
            myswitch(config-vsan-db)#

(which is expected)

Then when I send a command i.e.:
            net_connect.send_command(command_string="'vsan 666 interface fc1/1",auto_find_prompt=False)

I get errors like:
IOError: Search pattern never detected in send_command_expect: myswitch

I've tried using an expect pattern i.e. çonfig-vsan-db  and auto_find_prompt=True, various other things but can get vsan commands to work

Looking for any clues (I can attach full copy of text if needed just need to replace names ..... etc)

**Comment by ktbyers** [comment]
@dmlancaster You should use `send_config_set` for executing config changes.

```
net_connect.send_config_set('vsan 666 interface fc1/1')
```

Note, Netmiko will automatically enter/exit config mode and you shouldn't try to do it yourself (in the context of `send_config_set`).

I assume you are using the 'cisco_nxos' device_type? 

Note, I don't know how much MDS have been used on Netmiko. Are there are much behavioral differences from a CLI perspective from the MDS to other NX-OS switches?

**Comment by dmlancaster** [comment]
Thanks Kirk, incidentally I changed to using send_config_set('vsan database','vsan 666 interface fc1/1')   as you suggested  and it works, from cli it is equiv to:
conf t
vsan database
vsan 666 interface fc1/1
exit

so send_config_set output looks like:
Enter Configuration commands, one per line. End with CNTL/Z
myswitch(config)# vsan database
myswitch(config-vsan-database)# vsan 666 interface fc1/1
myswitch(config-vsan-database)# end
myswitch#

which is correct, I think where I went wrong was assuming the prompt changing to 'config-vsan-database' would cause a fault when actually send_config_set/underlying code deals with it correctly

Cheers, thanks, happy to close this

**Comment by dmlancaster** [comment]
and sorry, yes, this is set to 'cisco_nxos' for device_type

**Comment by ktbyers** [comment]
Okay, that makes sense and looks reasonable.

I assume you sent the commands in as a list of commands:

```
cfg_commands = ['vsan database', 'vsan 666 interface fc1/1']
send_config_set(cfg_commands)
```
