### ISSUE TITLE
Improve Test Suite for Other Users

### ISSUE THREAD

**Issue by supertylerc** [ktbyers/netmiko#72]
Currently, tests require a module that's not part of the repository (for security reasons).  However, there's no documentation (other than a note in an issue) as to how to supply the necessary information.  Additionally, the tests have hard-set expectations for prompts (and possibly other items).  See excerpt below.

```python
    module.EXPECTED_RESPONSES = {
        'base_prompt'      : 'pynet-rtr1',
        'user_exec_prompt' : 'pynet-rtr1>',
        'enable_prompt'    : 'pynet-rtr1#',
        'interface_ip'     : '10.220.88.20',
        'config_mode'      : '(config)',
    }
```

This means that if a user contributing code (and new tests) wants to actually test his/her changes, he/she must have a device setup precisely this way.  Being able to parse a YAML file (in `.gitignore`) with credentials, expected prompts, IPs, etc. would significantly increase the flexibility and accessibility of these tests.

**Comment by ktbyers** [comment]
I agree let's work out a way so that tests our less hard-coded to a particular environment and create a TESTING.md in github so people understand how to create and run tests.

**Comment by supertylerc** [comment]
I've done a bit of work on this.  You can see the branch I'm working on [here](https://github.com/supertylerc/netmiko/tree/feat/gh72-more-accessible-tests).  Results so far are promising.  I'll know more as I continue down this path.

Here's the output of the test after I rewrote the Juniper tests to be more extensible.

```
 ❯ py.test -s -v test_juniper_srx.py                                                                                                                                      [16:47:19]
================================================================================ test session starts ================================================================================
platform darwin -- Python 2.7.9 -- py-1.4.26 -- pytest-2.6.4 -- /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
collected 8 items

test_juniper_srx.py::test_disable_paging SSH connection established to 10.169.81.177:22
Interactive SSH session established
PASSED
test_juniper_srx.py::test_verify_ssh_connect PASSED
test_juniper_srx.py::test_verify_send_command PASSED
test_juniper_srx.py::test_base_prompt PASSED
test_juniper_srx.py::test_strip_prompt PASSED
test_juniper_srx.py::test_strip_command PASSED
test_juniper_srx.py::test_normalize_linefeeds PASSED
test_juniper_srx.py::test_clear_buffer PASSED

============================================================================= 8 passed in 16.57 seconds =============================================================================
>>> elapsed time 17s
 ❯
```

**Comment by supertylerc** [comment]
@ktbyers, if you think this is the wrong way to go, let me know and I'll stop working on it and reconsider.

**Comment by ktbyers** [comment]
I will try to look at this this weekend. I glanced at it yesterday.


Kirk

On Thu, Mar 12, 2015 at 4:51 PM, Tyler Christiansen <
notifications@github.com> wrote:

> @ktbyers <https://github.com/ktbyers>, if you think this is the wrong way
> to go, let me know and I'll stop working on it and reconsider.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/72#issuecomment-78700750>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by ktbyers** [comment]
The test suite should be reasonably good now (revamped in ~Q1).
