### ISSUE TITLE
could not parse arista eos prompt correctly

### ISSUE THREAD

**Issue by aroelaroel** [ktbyers/netmiko#720]
it looks like netmiko could not process this kind of prompt (hostname+timestamp) on arista eos:
>>> net.find_promt()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'AristaSSH' object has no attribute 'find_promt'
>>> net.find_prompt()
u'upp306.17:16:58>'
>>> out = net.send_command('show ip int br')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 967, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: upp306\.17\:17\:14\>
>>>

**Comment by ktbyers** [comment]
@aroelaroel So your have a prompt that contains a timestamp in the prompt (i.e. it changes on every command).

Yes, you will want to change the configuration on that (i.e. that will cause problems with Netmiko).
