### ISSUE TITLE
Netmiko on Kali Linux

### ISSUE THREAD

**Issue by DilrajSK** [ktbyers/netmiko#723]
Hi @ktbyers, I know you might have received a lot of issue regarding this. I went through all the threads 
 which I thought could be related to my issue but that didn't help me.

I too am new to Network Automation using Phython and was following https://pynet.twb-tech.com/blog/automation/netmiko.html to try-out some stuff.

While doing so, I got stuck at the error which says: ModuleNotFoundError: No module named 'netmiko'

Below is what I have tried till now to check the issue:

- ran "sudo apt-get install netmiko" on kali Terminal (This was successful)
- ran "python -m pip install netmiko". The output said "Requirement already Satisfied: netmiko in /usr/lib/python2.7/dist-packages"
- ran "pyhon -m pip install cryptography==1.8.1" (This throw a lot of stuff in red font. Basically it generated an exception with the summary as "TypeError": unsupported operand type(s) for -=; 'Retry' and 'int')

The output of some of the commands:

- python
_Python 2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118] on Linux2_

- netmiko.__version__
_Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
NameError: name 'netmiko' is not defined_

- import netmiko (on Kali Terminal)
This is getting executed without any output. Seems like it has taken the command. But when I go to idle Shell and run "import netmiko", its throwing error as ModuleNotFoundError: No module named 'netmiko'

NOTE: At the end, I want to execute all the steps as shared in the link: https://pynet.twb-tech.com/blog/automation/netmiko.html, but since the basic stuff is not working I am not able to proceed.

Please excuse if this is something too silly. Your help on this would be greatly appreciated.

Regards,
DILRAJ

**Comment by mrkcmo** [comment]
DILRAJ,

What OS platform are you using? Centos? Redhat?

Also – can you run the following? “sudo python –version” and provide the output? (two dashes before version)

Chris Fortner

**Comment by DilrajSK** [comment]
Hi Chris,

Its Kali version 2017.1

The output of  “sudo python –version” is "Python 2.7.13"

**Comment by mrkcmo** [comment]
Please do the following:

sudo apt-get install python-pip
sudo pip install Netmiko

If that doesn’t work then do:

sudo apt-get install python-netmiko

Once this is done then do the following:

python -i
from netmiko import ConnectHandler

If there are no errors then you are good to go…

Chris Fortner

**Comment by DilrajSK** [comment]
Hi Chris,

I don't get any error when I do it on Kali Terminal but when I run the import on Python Shell I get the error.

**Comment by ktbyers** [comment]
I would probably start by creating a clean Python virtual environment and then re-install it using PIP.

You should be able to use this document for how to create a virtual environment and how to activate it:

https://python-guide-cn.readthedocs.io/en/latest/dev/virtualenvs.html

After that do:

```
python -m pip install netmiko
```

**Comment by DilrajSK** [comment]
[Vir Env Output.txt](https://github.com/ktbyers/netmiko/files/1746151/Vir.Env.Output.txt)

I did as you suggested. See the txt file to check the series of commands I executed.
Result: Still the same

**Comment by ktbyers** [comment]
@DilrajSK What happens when you do this:

```
python
Python 2.7.9 (default, Feb 10 2015, 03:28:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__version__
u'2.0.0'
```

This is using the python associated with the virtual environment that you just created.

**Comment by DilrajSK** [comment]
[Output.txt](https://github.com/ktbyers/netmiko/files/1746287/Output.txt)
Output Attached.

**Comment by ktbyers** [comment]
Yes, that is right. So what is the issue?

**Comment by ktbyers** [comment]
What does this show you:

```
$ python
Python 3.6.2 (default, Nov  2 2017, 19:37:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__file__
'/home/gituser/netmiko/netmiko/__init__.py'
```

**Comment by ktbyers** [comment]
FYI, your Output.txt above does not look like it was using the virtual environment (i.e. it looks like you were using the wrong Python).

**Comment by DilrajSK** [comment]
Please see the answers in-line:
-------------------------------------------------------------------
Yes, that is right. So what is the issue?

Comment: When I run the "import netmiko" command on idle terminal I am getting the error.  On OS(Kali) terminal its fine. As we see.
-------------------------------------------------------------------
What does this show you:

$ python
Python 3.6.2 (default, Nov  2 2017, 19:37:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> netmiko.__file__
'/home/gituser/netmiko/netmiko/__init__.py'

Comment: See below:

traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'netmiko' is not defined
-------------------------------------------------------------------
FYI, your Output.txt above does not look like it was using the virtual environment (i.e. it looks like you were using the wrong Python).

Comment: Yes, I deactivated the Venv after trying your initial suggestion.

**Comment by ktbyers** [comment]
Can you show me what you are doing in your `idle terminal` (i.e. what did you do to generate the above traceback)?

**Comment by DilrajSK** [comment]
Please see the attached:
![capture](https://user-images.githubusercontent.com/36675499/36556875-a7c84a62-182c-11e8-90f8-8e840f62e1aa.PNG)

**Comment by ktbyers** [comment]
You are installing Netmiko into a different Python than IDLE is using (note, how that is Python3.6.4). Your previous output was Python3.6.2.

This is not a Netmiko issue, it is an environment management issue.

**Comment by DilrajSK** [comment]
ok, Any suggestion how do I install the package in the version same as idle? I guess, it's installing the netmiko package in the default python env (i.e. 2.7.13)

**Comment by DilrajSK** [comment]
Got it working:

Removed IDLE 3.6.4 >> Installed IDLE 2.7.13 using the below command:

sudo apt-get install idle-python2.7

Thanks for your help :)
