### ISSUE TITLE
Adding some vendors

### ISSUE THREAD

**Issue by tiix95** [ktbyers/netmiko#727]
Hello ! 

Don't know if this can be of any help, but I develop some scripts by myself to backup some network devices. I currently have : 

  - F5 (SSH command & file transfer)
  - Fortigate, Fortimanager, Fortianalyzer (ssh command & file transfer)
  - Tufin (file transfer)
  - Wallix (file transfer)
  - Avaya (ssh command, telnet command)
  - Aruba (ssh command)
  - Netscaler (ssh command & file transfer)

I am not very comfortable with git and its features neither with adding some functions to someone else code, but if you have some time I will be pleased to forward you some of my script for you to include them into netmiko. 

Your git litterally saved my life for avaya VSP devices, as I was struggling since many days on them.

Please let me know if you're interested !

**Comment by DamienOConnell** [comment]
Hello wondering if you got to submit the netscaler device type, that is one I am really keen to have working right now.  
If you have such file, i'd be keen to see it. 
thanks

**Comment by ktbyers** [comment]
@DamienOConnell There is a 'netscaler_ssh' device type that already exists. It is in the 'citrix' folder in the repository.


Kirk

**Comment by carlniger** [comment]
inactive. closing.
