### ISSUE TITLE
send_command with expect_string and command text longer than 54 chars fails

### ISSUE THREAD

**Issue by pmeyerson** [ktbyers/netmiko#734]
...
eof = re.compile('([\*\^]*\>')
x=net_con.send_command("really long command string", expect_string=eof)

 
 File "/home/x/.local/lib/python3.5/site-packages/netmiko/base_connection.py", line 954, in send_command
    pattern = search_pattern + r'.*$'
TypeError: unsupported operand type(s) for +: '_sre.SRE_Pattern' and 'str'

If I shorten the command text by one character it works (although then the command is wrong.
I can also remove the expect_string and the command will execute correctly, just not on all of my switches (issue on our end).

Or am I doing something wrong here?
Thanks. I have netmiko 2.1.4 installed and python3.

**Comment by ktbyers** [comment]
You can't use an expect_string that is an re.compile object (i.e. it needs to be a raw string).

Note, re.compile doesn't really save you any performance (Python automatically compiles the regular expressions).

So use this:

```
x=net_con.send_command("really long command string")
```

Or use a valid expect_string (Python raw string).

**Comment by pmeyerson** [comment]
Thanks, sorry must have misread something.

**Comment by ktbyers** [comment]
@pmeyerson No worries.
