### ISSUE TITLE
Issue to execute script

### ISSUE THREAD

**Issue by michelvio** [ktbyers/netmiko#736]
Hi,

I tried to execute this script to connect in cisco asa and send the command show version.

When I run the script and follow error message is displayed in my terminal.

[root@oc8405627148 Desktop]# ./asatest.py
Enter IP address: 158.98.17.164
Enter username: mavio
Enter SSH password: 
Enter enable password: 
Traceback (most recent call last):
  File "./asatest.py", line 18, in <module>
    print output
NameError: name 'output' is not defined
[root@oc8405627148 Desktop]#

**Comment by michelvio** [comment]
Script 

[root@oc8405627148 Desktop]# cat asatest.py
#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass

ip_address = raw_input("Enter IP address: ")
username = raw_input("Enter username: ")

device = {
    'device_type': 'cisco_asa',
    'ip': ip_address,
    'username': username,
    'password': getpass('Enter SSH password: '),
    'secret': getpass('Enter enable password: '),
    'port': 22,
}

print output
net_connect = ConnectHandler(**device)
output = net_connect.send_command_expect('show version')

[root@oc8405627148 Desktop]# 


Could you help me ?

**Comment by ktbyers** [comment]
@michelvio You are printing the `output` variable before it is defined.

Move the `print output` to the last line in the program (after the send_command_expect statement).
