### ISSUE TITLE
netmiko cannot handle "admin display-config" output

### ISSUE THREAD

**Issue by cctsay** [ktbyers/netmiko#740]
Got the problem to run netmiko to "admin display-config" (like Cisco IOS "show run").
Anyway to work around?
As you can see below, "show time" and "show version" can get the support no problem.

```
>>> r1 = {'ip':'7750sr12-2','device_type':'alcatel_sros', 'username':'test', 'password':'test'}
>>> import netmiko
>>> nc = netmiko.ConnectHandler(**r1)
>>> nc.send_command('show time')
'\nMon Mar 12 21:58:05 UTC 2018'
>>> nc.send_command('show version')
'\nTiMOS-C-14.0.R5-1 cpm/hops64 Nokia 7750 SR Copyright (c) 2000-2017 Nokia.\nAll rights reserved. All use subject to applicable license agreements.\nBuilt on Thu Aug 10 09:10:28 PDT 2017 by builder in /rel14.0/b1/R5-1/panos/main'
>>> nc.send_command('admin display-config')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cctsay/miniconda3/lib/python3.6/site-packages/netmiko-2.0.1-py3.6.egg/netmiko/base_connection.py", line 967, in send_command
OSError: Search pattern never detected in send_command_expect: \*B\:alu7750sr12\-2\#
>>> 
```

Thanks!
C.

**Comment by ktbyers** [comment]
@cctsay Does it work if you do:

```
 nc.send_command('admin display-config', expect_string='#')
```

Also what does this sequence of commands look like if you do it manually via SSH from the CLI (just so I can see what is going wrong).

**Comment by cctsay** [comment]
Great and that's the solution.
Looked like SROS has the special # statements in the beginning so netmiko don't know howto handle.

>>> nc.send_command('admin display-config', expect_string='#')
'\n# TiMOS-C-14.0.R5-1 cpm/hops64 Nokia 7750 SR Copyright (c) 2000-2017 Nokia.\n# All rights reserved. All use subject to applicable license agreements.\n# Built on Thu Aug 10 09:10:28 PDT 2017 by builder in /rel14.0/b1/R5-1/panos/main\n\n# Generated FRI MAR 16 17:01:45 2018 UTC\n\nexit all\nconfigure\n#--------------------------------------------------\necho "System Configuration"\n#--------------------------------------------------\n    system\n        name "alu7750sr12-2"\n        contact "Mitch Crowell x81563"\n        location "Lab RR10.5"\n        chassis-mode d\n        dns\n        exit\n        load-balancing\n            l4-load-balancing\n            lsr-load-balancing lbl-ip\n            system-ip-load-balancing\n            mc-enh-load-balancing\n        exit\n        ptp\n            shutdown\n            profile ieee1588-2008\n            clock-type ordinary master\n        exit\n        snmp\n            packet-size 9216\n        exit\n        time\n            sntp\n                server-address 100.80.32.7 \n                no shutdown\n            exit\n            zone UTC \n        exit\n        thresholds\n            rmon\n            exit\n        exit\n        script-control\n            script "y1731-dmm-scr"\n                description "delay measurement with y1731"\n                location "ftp://automation:iplab@10.248.16.2/home/alustats/y1731/y1731.scr"\n                no shutdown\n            exit\n            script "saa-cli-cmd_scr"\n                description "lsp ping script"\n    
.
.

**Comment by cctsay** [comment]
Doh looked like it can help some but not "all" so it cannot be the solution.
If there is a lot of configs between #sections then it cannot go so stop.
I did try to turn off the paging but it cannot help.

I can upload the whole "admin display-config" output so you can analyze.
Let me send it to your email.

**Comment by cctsay** [comment]
Please see attached and let me know what you need.
It's just similar to Cisco "show run" but the output may be tricky to
capture through netmiko.

​​​
 sr12-2-admin-display.txt
<https://drive.google.com/file/d/1hawwycFxmEnI6jt07gOr1wlBuXrFN9yH/view?usp=drive_web>
​

**Comment by ktbyers** [comment]
That file is enormous...what does the prompt look like one line to the next i.e. how does the prompt change from command 1 to command 2 to command 3.

How many lines are in that output?

**Comment by cctsay** [comment]
Is it what you're looking for?
I'm not that clear why netmiko can collect whole config on Cisco IOS and
Juniper Junos no problem but no go on Alcatel SROS.

Anyway, let me know if you need any else so we can get the support on  Alcatel
SROS.

Thanks!
C.

*B:alu7750sr12-2# show time
Fri Mar 16 18:18:19 UTC 2018
*B:alu7750sr12-2# show version
TiMOS-C-14.0.R5-1 cpm/hops64 Nokia 7750 SR Copyright (c) 2000-2017 Nokia.
All rights reserved. All use subject to applicable license agreements.
Built on Thu Aug 10 09:10:28 PDT 2017 by builder in
/rel14.0/b1/R5-1/panos/main
*B:alu7750sr12-2# show config
WARNING: CLI This command has been removed for security reasons, please use
"admin display-config".
*B:alu7750sr12-2# admin dis
disconnect      display-config
*B:alu7750sr12-2# admin display-config
# TiMOS-C-14.0.R5-1 cpm/hops64 Nokia 7750 SR Copyright (c) 2000-2017 Nokia.
# All rights reserved. All use subject to applicable license agreements.
# Built on Thu Aug 10 09:10:28 PDT 2017 by builder in
/rel14.0/b1/R5-1/panos/main

# Generated FRI MAR 16 18:19:14 2018 UTC

exit all
configure
#--------------------------------------------------
echo "System Configuration"
#--------------------------------------------------
    system
        name "alu7750sr12-2"
        contact "Mitch Crowell x81563"
        location "Lab RR10.5"
        chassis-mode d
        dns
        exit
        load-balancing
            l4-load-balancing
            lsr-load-balancing lbl-ip
            system-ip-load-balancing
            mc-enh-load-balancing
        exit
        ptp
            shutdown
            profile ieee1588-2008
            clock-type ordinary master
        exit
        snmp
            packet-size 9216
        exit
        time
            sntp
                server-address 100.80.32.7
                no shutdown
            exit
            zone UTC
        exit
        thresholds
            rmon
            exit
        exit
        script-control
            script "y1731-dmm-scr"
                description "delay measurement with y1731"
                location "
ftp://automation:iplab@10.248.16.2/home/alustats/y1731/y1731.scr"
                no shutdown
            exit
            script "saa-cli-cmd_scr"
                description "lsp ping script"
                location "
ftp://automation:iplab@10.248.16.2/home/alustats/saa-cli-cmd"
                no shutdown
            exit
            script-policy "y1731-dmm-act"
                results "
ftp://automation:iplab@10.248.16.2/home/alustats/7750sr12-2/y1731-two-way-dmm
"
Press any key to continue (Q to quit)

**Comment by ktbyers** [comment]
I assume that this:

```
Press any key to continue (Q to quit)
```

goes away if you do this:

```
environment no more
```

How many lines are in the output of `admin display-config`?
How long (roughly) does it take to complete?

Does it prompt you for anything as part of the command or does it run to completion (after you have done the `environment no more`)?


Kirk

**Comment by cctsay** [comment]
Correct. I can just turn of the paging with "environment no more" and it
will keep scrolling till it ends. No it will not prompt me for any if no
paging.

It really depends on if you have large config file or not. For here, it's
indeed huge.(>25M config file)
Yes it took me around 5 minutes for the output is done.(Will be longer if I
don't turn off paging.)

**Comment by ktbyers** [comment]
@cctsay Okay, try this:

```
nc.send_command('admin display-config', delay_factor=2, max_loops=2000)
```

That should allow for roughly 800 seconds for it to complete.

If that fails please post the stack trace.

**Comment by cctsay** [comment]
Yep it's working now:)

Thanks!
C.

Fri Mar 16 12:57 cctsay@kenny:~]tail -10 alu7750sr12-1.cfg
            exit
            no shutdown
        exit
    exit


exit all

# Finished FRI MAR 16 18:56:59 2018 UTC

Fri Mar 16 12:57 cctsay@kenny:~]head -10 alu7750sr12-1.cfg

# TiMOS-C-14.0.R5 cpm/hops64 Nokia 7750 SR Copyright (c) 2000-2016 Nokia.
# All rights reserved. All use subject to applicable license agreements.
# Built on Wed Sep 28 15:57:18 PDT 2016 by builder in
/rel14.0/b1/R5/panos/main

# Generated FRI MAR 16 18:55:59 2018 UTC

exit all
configure
#--------------------------------------------------
Fri Mar 16 12:57 cctsay@kenny:~]ls -l alu7750sr12-1.cfg
-rw-r--r-- 1 cctsay users 16270344 Mar 16  2018 alu7750sr12-1.cfg
Fri Mar 16 12:58 cctsay@kenny:~]
Fri Mar 16 12:58 cctsay@kenny:~]
Fri Mar 16 12:58 cctsay@kenny:~]ls -l alu7750sr12-2.cfg
-rw-r--r-- 1 cctsay users 0 Mar 16  2018 alu7750sr12-2.cfg
Fri Mar 16 12:58 cctsay@kenny:~]ls -l alu7750sr12-2.cfg
-rw-r--r-- 1 cctsay users 26221796 Mar 16  2018 alu7750sr12-2.cfg
Fri Mar 16 12:59 cctsay@kenny:~]
