### ISSUE TITLE
find_prompt with high latency connection with command authorization

### ISSUE THREAD

**Issue by tjhannin** [ktbyers/netmiko#741]
Not sure if this is a known issue, but it seems find_prompt is unreliable when talking to device via a high latency/jitter connection with AAA command authorization enabled. Things get slightly better by increasing the delay_factor, but it seems this is still somewhat unreliable.

The gist of the issue seems to be that the find_prompt function sends X number of newlines, gets the last line as the prompt, then waits a moment and clears the buffer - however if there's delay (for example for AAA command authorization), the "moment" might not be enough and additional prompts arrive into the buffer after it has been cleared, which then of course means the send_command function sees an unexpected prompt and things get completely out of sync.

I modified a local copy of the find_prompt function so that it counts the number of prompts it has received and compares this to the number of newlines that were sent before the prompt was found - this seems to work with the (Cisco) devices I've been testing with, but wondering if there's a better way to do this. I'd be happy to post the changes I made here if that would be useful.

thanks!

**Comment by ktbyers** [comment]
AAA authorization and automation do not go very well together. The TACACS+ server is unable (generally to keep up with the requirements of automation). It will be even more of a problem if you start trying to do things concurrently (to multiple devices).

You could try adding a global_delay_factor to your ConnectHandler call. Start at 2, then 4, then 8 and keep increasing it upwards. This will slow Netmiko down (i.e. increase the amount of sleep time).

You could also with send_command use an expect_string argument and specify the pattern to use (to indicate that the command is done). This will cause Netmiko to stop sending the newlines to discover the prompt (in send_command method).

**Comment by tjhannin** [comment]
The AAA authorization in this case is really more because we need to be able to support multiple access levels to the devices, and doing that with modifying command privilege levels isn't really a workable solution. Not really seen issues with AAA itself when running around 50 concurrent threads, but not tried to take concurrency higher than that.

I'm actually using netmiko via napalm, which limits options even more - but at the same time, it also means the AAA servers don't need to handle that many commands per change as the merge operations don't seem to cause AAA authorization requests for individual changes. 

I was thinking first that I'd do something that estimates latency to each device and increases the delay factor accordingly, but that seemed like too much of a kludge so tested to change the prompt detection instead (as that was what seemed to be causing the issue) - it seems to work, but don't know if the approach will cause other issues down the line.

**Comment by ktbyers** [comment]
@tjhannin Are you doing concurrency here or just to a single device?

NAPALM should support all Netmiko arguments to ConnectHandler (at least when this pull request is approved https://github.com/napalm-automation/napalm/pull/673)

It should support global_delay_factor also, but yes it will limit your options quite a bit (as far as send_command arguments).

Your problem would be you would have to keep continually making that local change whenever you upgraded Netmiko.

**Comment by tjhannin** [comment]
I'm doing concurrency, but I can reproduce this issue with a single device as well.

I agree it doesn't sound optimal to have to customize Netmiko every time it's upgraded - I might go back and see if I can figure out a way to avoid that, but at the same time trying to avoid having to go with a high delay factor if I can. If I go on that path, might need to go with something like 20 for some devices to cause a 2 second wait at the end of find_prompt, but thinking that might slow things down too much. 

And it'll of course add another layer of complexity to customize the delay factor separately for each device, and might still cause unexpected results in some cases if for whatever reason the prompts don't come back quickly enough.

I would have the hostnames of all the devices available separately, so theoretically would know how the prompt is (should) always going to look at the devices, but with NAPALM in between I'm not sure if that helps.

**Comment by ktbyers** [comment]
Have you tried just increasing global_delay_factor to a value of 2 or 4 (that is probably the easiest fix)?

**Comment by tjhannin** [comment]
Yes, I did experiment with a few different values and it does seem like setting that to 4 will work most of the time. It still feels a bit like hit and miss though, especially because network conditions might of course vary.

FWIW, here's the extra stuff I added into find_prompt when I was experimenting with trying to make sure it doesn't leave extra "prompts" behind. "prompt_pre" is a copy of the "prompt" from line 891 of the original code (to get the number of prompts the function has already seen at that point):

        # count has how many newlines we've sent. Make sure we've gotten as many prompts back
        still_needed = count - prompt_pre.split(self.RETURN).count(prompt)
        max_wait = delay_factor * 2
        waited = 0
        output = ''
        while still_needed > 0 and waited < max_wait:
           new_data = self.read_channel()
           if new_data:
              if self.ansi_escape_codes:
                 new_data += self.strip_ansi_escape_codes(new_data).strip()
              output += self.normalize_linefeeds(new_data)
              found = output.split(self.RETURN).count(prompt)
              still_needed -= found
           time.sleep(delay_factor * .1)
           waited += delay_factor * .1

        if still_needed > 0:
          raise ValueError("Mismatch with prompts: {} missing".format(still_needed))

**Comment by ktbyers** [comment]
@tjhannin Another option is to specify an expect_string argument to send_command and then find_prompt() will not be executed on each send_command() execution

```
net_connect.send_command("show ip int brief", expect_string=r"#")
```

You would need a pattern that you could deterministically know that the command was done.

Alternatively, you could find the prompt once with a high delay factor and then use this for your expect_string.

**Comment by tjhannin** [comment]
Thanks. Yeah, that would work if I wasn't using Netmiko via NAPALM. Suppose something like that might make sense inside NAPALM too when it calls Netmiko though.

Anyways, I'm happy for this to be closed - I'm going to use the hacked version of the code for now but will think about just using the higher delay_factor in the future.
