### ISSUE TITLE
Impossible to connect to Dell S55 switches

### ISSUE THREAD

**Issue by viviengraffin** [ktbyers/netmiko#742]
Hello,

I am unable to connect on my s55 switches using netmiko. I have also s4810 switches but it's working without any issue. The only difference is the FTOS version (8.3.5.6 for the s55 and 9.9 for the s4810)

When I try to connect with netmiko, I have this message:

Oops, unhandled type 3

Then I got an EOFError.

Has anyone already got this issue ?

Thank you for your attention in this matter.

**Comment by ktbyers** [comment]
Try the solution that is referenced here and see if it works:

https://github.com/ktbyers/netmiko/issues/373

Which looks like setting `look_for_keys=True` in ConnectHandler call (in addition to sending a username/password).

**Comment by viviengraffin** [comment]
It don't works. I have this error.
TypeError: __init__() got an unexpected keyword argument 'look_for_keys'

**Comment by ktbyers** [comment]
@viviengraffin Post your code please. Thanks.

**Comment by viviengraffin** [comment]
def sshConnect(ip,username,password,enable_password,typ,ts):
	li={
		"device_type":typ,
		"ip":ip,
		"username":username,
		"password":password,
		"secret":enable_password,
	}
	if ts=="dell_s55":
		li["look_for_keys"]=True
	ssh=ConnectHandler(**li)
	ssh.enable()
	if ts=="dell_n2000":
		ret=DellN2000(ssh,ip)
	elif typ=="dell_force10":
		ret=DellForce10(ssh,ip)
	elif typ=="dell_powerconnect":
		ret=DellPowerConnect(ssh,ip)
	return(ret)

This is my source code of connection

**Comment by ktbyers** [comment]
What is this conditional about?

```python
	if ts=="dell_n2000":
		ret=DellN2000(ssh,ip)
	elif typ=="dell_force10":
		ret=DellForce10(ssh,ip)
	elif typ=="dell_powerconnect":
		ret=DellPowerConnect(ssh,ip)
```

I am assuming that `typ` here is dell_force10, what is this class you are wrapping this in here?

Can you post the full stack trace of your exception also.

**Comment by viviengraffin** [comment]
For the s55 switches, I use the DellForce10 class.

Traceback (most recent call last):
  File ".\prog.py", line 33, in <module>
    ssh=sshConnect(ips[i],username,password,enable_password,types[i],tss[i])
  File "C:\Users\vgraffin\Desktop\sauvegarde switchs\swdriver.py", line 38, in sshConnect
    ssh=ConnectHandler(ip=ip,username=username,password=password,device_type=typ,secret=enable_password,look_for_keys=True)
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\ssh_dispatcher.py", line 173, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'look_for_keys'

**Comment by ktbyers** [comment]
@viviengraffin Try:

```
use_keys=True
```

instead of look_for_keys.

**Comment by viviengraffin** [comment]
I have this error.

```
Oops, unhandled type 3
Traceback (most recent call last):
  File "prog.py", line 33, in <module>
    ssh=sshConnect(ips[i],username,password,enable_password,types[i],tss[i])
  File "C:\Users\vgraffin\Desktop\sauvegarde switchs\swdriver.py", line 34, in sshConnect
    ssh=ConnectHandler(**li)
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\ssh_dispatcher.py", line 173, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 187, in __init__
    self.establish_connection()
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 669, in establish_connection
    self.remote_conn = self.remote_conn_pre.invoke_shell()
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\client.py", line 510, in invoke_shell
    chan = self._transport.open_session()
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\transport.py", line 767, in open_session
    timeout=timeout)
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\transport.py", line 891, in open_channel
    raise e
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\transport.py", line 1872, in run
    ptype, m = self.packetizer.read_message()
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\packet.py", line 426, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "C:\Users\vgraffin\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\packet.py", line 276, in read_all
    raise EOFError()
EOFError
```

**Comment by carlniger** [comment]
Tagging pending close as this is quite old. Let us know if this is still an issue, otherwise we'll close this out in a bit.

**Comment by drommc** [comment]
@ktbyers I was reading #373 and seems **networkpadawan** did not update with last working code. 

I've been at this for at least 3 days and finally got it to work. Yes, sending the keys before sending the password will allow me to connect to a Dell Force10 S55 running 8.3.5.6 (which interestingly enough is Dell Network OS 9 or dellos9)

For ansible, at least 2.8.0 which is what I'm using, setting the following var:

**ansible_ssh_private_key_file**

To a valid key file will do the trick. Ansible will attempt to look for keys and thus solve the bug.

**Comment by ktbyers** [comment]
@drommc So just to verify--the solution here was to send both the SSH keys and the username/password will cause this to work?

Something similar to the following:

```
ssh.connect('10.10.10.10',username='user', password='password',
        look_for_keys=True, allow_agent=True)
```

I assume it is still doing password authentication i.e. that the sending of the SSH keys just gets past the breakage, but the username/password are still used for the actual authentication?

**Comment by drommc** [comment]
@ktbyers just to confirm I have created a simple test script using netmiko:

```
from netmiko import ConnectHandler

dell_881 = {
    'device_type': 'dell_force10',
    'ip':   '10.10.10.10',
    'username': 'admin',
    'password': 'your_secret_here',
    'verbose': True,
    'use_keys': True,
    'allow_agent': True,
    'key_file': '/root/key.pem'
}

net_connect = ConnectHandler(**dell_881)
```

Not until I used key_file and use_keys,  was I able to get rid of 

> Oops, unhandled type 3 ('unimplemented')

allow_agent does not seem to make a difference. The stdout with the above code is

> SSH connection established to 10.10.10.10:22 
> Interactive SSH session established

Yes, I'm only interested in doing password authentication right now, I have not tested the actual key authentication yet.

**Comment by ktbyers** [comment]
Okay, nice thanks.
