### ISSUE TITLE
get layer 2 information based on layer3 IP

### ISSUE THREAD

**Issue by jacob2717** [ktbyers/netmiko#751]
hello Kirk!

I am trying to create an script that help in searching an mac address of a server on the LAN switch environment and provide interface details on where it is connected to.

Initially I made two scripts - juniper.py and show_mac-address.py
Juniper.py

from netmiko import ConnectHandler
from datetime import datetime

juniper_junos = {
	'device_type': 'juniper_junos',
	'ip': '10.6.254.53',
	'username': 'juniper',
	'password': 'juniper',
}

net_connect = ConnectHandler(**juniper_junos)
output = net_connect.send_command('show arp no-resolve | match 10.6.2.71')
output_mac = output[0:18]
print output_mac

=======This provide the mac address of the server from IP information from layer 3 device====

Now, I have to use that mac address and use below script to search the port information - 

from netmiko import ConnectHandler

cisco_nxos = {
	'device_type': 'cisco_nxos',
	'ip': '10.6.2.11',
	'username': 'jkedari',
	'password': 'Kaju@123#',
}

net_connect = ConnectHandler(**cisco_nxos)
output = net_connect.send_command('show mac address-table address 00:2a:6a:98:d4:21')
print output

=========This provide the interface details======

NOW THE ISSUE IS - 

I want to combine both the scripts, I tried and could reach upto here, but unfortunately could'nt get desired output - script name get-port.py

SCRIPT
=====

from netmiko import ConnectHandler

juniper_junos = {
	'device_type': 'juniper_junos',
	'ip': '10.6.254.53',
	'username': 'jkedari',
	'password': 'Kaju@123#',
}

net_connect = ConnectHandler(**juniper_junos)
output = net_connect.send_command('show arp no-resolve | match 10.6.2.79')
output_arp = output[0:18]
print output_arp

cisco_nxos = {
	'device_type': 'cisco_nxos',
	'ip': '10.6.2.11',
	'username': 'jkedari',
	'password': 'Kaju@123#',
}

net_connect = ConnectHandler(**cisco_nxos)
output_mac = 'show mac address-table address ' + output_arp
print output_mac
output_mac1 = net_connect.send_command('output_mac')
print output_mac1

===========OUTPUT==============

PS C:\Python-Scripts> python get-port.py

00:2a:6a:98:d4:21
show mac address-table address
00:2a:6a:98:d4:21
                    ^
% Invalid command at '^' marker.
PS C:\Python-Scripts>

**Comment by ktbyers** [comment]
It looks like you have a newline(s) on your mac-address. Just do a `output_arp.strip()` and then try your show command again

**Comment by jacob2717** [comment]
Thank you Kirk, appreciate your help!!!! it worked cheers!!

Below is the script I modified as advised and got the desired output:

SCRIPT:

from netmiko import ConnectHandler

juniper_junos = {
	'device_type': 'juniper_junos',
	'ip': '10.6.254.53',
	'username': 'jkedari',
	'password': 'Kaju@123#',
}

net_connect = ConnectHandler(**juniper_junos)
output = net_connect.send_command('show arp no-resolve | match 10.6.2.79')
output_arp = output.strip()[0:18]
print output_arp

cisco_nxos = {
	'device_type': 'cisco_nxos',
	'ip': '10.6.2.11',
	'username': 'jkedari',
	'password': 'Kaju@123#',
}

net_connect = ConnectHandler(**cisco_nxos)
output_mac = net_connect.send_command('show mac address-table address ' + output_arp)
print output_mac

===============OUTPUT===========

PS C:\Python-Scripts> python port.py
00:2a:6a:98:d4:21
Legend:
        * - primary entry, G - Gateway MAC, (R) - Routed MAC, O - Overlay MAC
        age - seconds since last seen,+ - primary entry using vPC Peer-Link
   VLAN     MAC Address      Type      age     Secure NTFY   Ports/SWID.SSID.LID
---------+-----------------+--------+---------+------+----+------------------
+ 30       002a.6a98.d421    dynamic   0          F    F  Po1
PS C:\Python-Scripts>
