### ISSUE TITLE
Juniper configuration send_command save to file

### ISSUE THREAD

**Issue by Jajao555** [ktbyers/netmiko#753]
When I use send_command for configuration commands I wanted them to be saved to a file as a log to track that they all go successfully but it only seems to output the prompt and skips all the command and then outputs the commit complete confirmations.

Here's a snippet of some of the code with how I'm sending the commands and saving to a file. If I run logger with DEBUG set I can see where its sending the commands and it actually works fine. Just can't figure out why it won't actually show the output. It works fine doing it the same way with Cisco. I'm a noob at Python so that may also have something to do with it.

session.find_prompt()
output=session.send_command('request system configuration rescue save', delay_factor=5)
output=session.config_mode()
output=session.send_command('rollback 0')
output=session.send_command('delete system syslog')
output=session.send_command('set snmp trap-group traps targets 10.x.x.x')
output=session.send_command('show | compare | no-more', delay_factor=2)
output=session.commit(and_quit = True)
o.write(output)

This is all I get in my txt file.

20180322_09:42:39:341331 - Logged into Juniper PE-MX480-1 - 192.x.x.x
commit and-quit 
re0: 
configuration check succeeds
re1: 
commit complete
re0: 
commit complete
Exiting configuration mode

{master}
test@PE-MX480-1> 20180322_09:42:39:341331 - Finished Juniper PE-MX480-1 - 192.x.x.x

**Comment by ktbyers** [comment]
@Jajao555 You shouldn't really be using `send_command` for sending configuration commands use `send_config_set` instead:

```python
output = session.send_command('rollback 0')
cfg_commands = [
    'delete system syslog',
    'set snmp trap-group traps targets 10.x.x.x',
]
output += session.send_config_set(cfg_commands)
output += session.commit(and_quit = True)
with open("output_file.txt") as f:
    f.write(output)
```

In your above code, you are overwriting the output variable each time (so it will only have the content from the last command).

After the first command you should do:

```
output = output + session.send_command('delete system syslog')
```

Or

```
output += session.send_command('delete system syslog')
```

The += essentially does the same thing (i.e. adds the new output onto the end of the existing output string).

**Comment by ktbyers** [comment]
I missed your first `rescue` command in the new solution I posted using `send_config_set`

**Comment by Jajao555** [comment]
Awesome! Thanks.
