### ISSUE TITLE
use_textfsm is not working when exporting path using ~ symbol

### ISSUE THREAD

**Issue by d3nisko** [ktbyers/netmiko#756]
Hi, I'm using ntc templates to transform output of the "show interfaces status" command. 

First case: ntc templates cloned into home dir.
**NET_TEXTFSM=/home/testuser1/ntc-templates/templates**
Behavior: Everything is working as expected. Dict returned. 

Second case: ntc templates cloned into the working dir with the script. full path specified.
**NET_TEXTFSM=/home/testuser1/scripts/learn/automation/python_for_ne/excercises/lesson_6/ntc-templates/templates**
Behavior: Working as expected. Dict returned. 

Third case: ntc templates cloned into the home dir. ~ is used to indicate the path to home dir
**NET_TEXTFSM=~/ntc-templates/templates**
Behavior: exception appeard -

> > Traceback (most recent call last):
>   File "6_5.py", line 17, in <module>
>     output = net_conn.send_command('show interfaces status', use_textfsm=True)
>   File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 973, in send_command
>     command=command_string.strip())
>   File "/usr/local/lib/python2.7/dist-packages/netmiko/utilities.py", line 219, in get_structured_data
>     template_dir = get_template_dir()
>   File "/usr/local/lib/python2.7/dist-packages/netmiko/utilities.py", line 202, in get_template_dir
>     raise ValueError(msg)
> ValueError: 
> Valid ntc-templates not found, please install https://github.com/networktocode/ntc-templates
> and then set the NET_TEXTFSM environment variable to point to the ./ntc-templates/templates
> directory. 
> 

Fourth case: ntc templates cloned into working dir. ~ is used to indicate the path to home dir
**NET_TEXTFSM=~/scripts/learn/automation/python_for_ne/excercises/lesson_6/ntc-templates/templates** 

> Traceback (most recent call last):
>   File "6_5.py", line 17, in <module>
>     output = net_conn.send_command('show interfaces status', use_textfsm=True)
>   File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 973, in send_command
>     command=command_string.strip())
>   File "/usr/local/lib/python2.7/dist-packages/netmiko/utilities.py", line 219, in get_structured_data
>     template_dir = get_template_dir()
>   File "/usr/local/lib/python2.7/dist-packages/netmiko/utilities.py", line 202, in get_template_dir
>     raise ValueError(msg)
> ValueError: 
> Valid ntc-templates not found, please install https://github.com/networktocode/ntc-templates
> and then set the NET_TEXTFSM environment variable to point to the ./ntc-templates/templates
> directory.

Python 2.7.12
netmiko (2.1.0)

**Comment by jayceechou** [comment]
I have the same problem here.... =(

**Comment by ktbyers** [comment]
@jayceechou Until it is fixed, the workaround is just to specify the full path to the home directory (i.e. /home/user).

**Comment by d3nisko** [comment]
Correct, full path is working fine.

**Comment by jayceechou** [comment]
I did. But the **output** still return as a **string type**. In fact, it's **unicode type**. So, **use_textfsm=True** didn't get enabled or some reason. 
Does anyone have the same problem?

**Comment by d3nisko** [comment]
Could you please share the code and output?
It started working for me as soon as I have updated path.

**Comment by jayceechou** [comment]
Yes. Here it is:
```
from netmiko import Netmiko
from getpass import getpass

password = getpass()
my_device = {
    'host': '10.10.10.3',
    'username': 'admin',
    'password': password,
    'device_type': 'cisco_ios'
}

net_conn = Netmiko(**my_device)
output = net_conn.send_command("show arp", use_textfsm=True)
print(output)

```

Here is the output:
```
$ ipython -i textfsm_test.py
Password:
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  10.10.10.1           208   0000.0c07.acaa  ARPA   Vlan570
Internet  10.10.10.2            16   706e.6d61.1b41  ARPA   Vlan570
Internet  10.10.10.3             -   706e.6d68.51c1  ARPA   Vlan570
Internet  10.10.10.4             0   0010.dbff.b003  ARPA   Vlan570


In [1]: type(output)
Out[1]: unicode

In [2]: output
Out[2]: u'Protocol  Address          Age (min)  Hardware Addr   Type   Interface\nInternet  10.10.10.1           208   0000.0c07.acaa  ARPA   Vlan570\nInternet  10.10.10.2            16   706e.6d61.1b41  ARPA   Vlan570\nInternet  10.10.10.3             -   706e.6d68.51c1  ARPA   Vlan570\nInternet  10.10.10.4             0   0010.dbff.b003  ARPA   Vlan570'
```

So, after I have 'use_textfsm=True', I still get the output in a **string/unicode** format. I thought it should be in a **list** format.

Thanks for helping me out here! I really wish to use textfsm for getting better format.

**Comment by ktbyers** [comment]
@jayceechou Try, `show ip arp` for the command.

You might need to look at the index to see the naming of the command that is supported:

https://github.com/networktocode/ntc-templates/blob/master/templates/index

This also includes which abbreviations of the command are supported.

**Comment by jayceechou** [comment]
ahh.. i see. My bad! So, there is no 'show arp' template, but 'show ip arp'. Got you! Thank you so much!!! I guess I'll need to look it up whether it's supported before I want to use it.

**Comment by sliddjur** [comment]
```
In [7]: os.environ['NET_TEXTFSM']
Out[7]: '/home/olof/git/ktbyers_python/week6/ntc-templates/templates/'

In [8]: output = connection.send_command(command, use_textfsm=True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-77379a4ed1cc> in <module>()
----> 1 output = connection.send_command(command, use_textfsm=True)

/home/olof/.local/lib/python3.6/site-packages/netmiko/base_connection.py in send_command(self, command_string, expect_string, delay_factor, max_loops, auto_find_prompt, strip_prompt, strip_command, normalize, use_textfsm)
   1116         if use_textfsm:
   1117             output = get_structured_data(output, platform=self.device_type,
-> 1118                                          command=command_string.strip())
   1119         return output
   1120

/home/olof/.local/lib/python3.6/site-packages/netmiko/utilities.py in get_structured_data(raw_output, platform, command)
    217 def get_structured_data(raw_output, platform, command):
    218     """Convert raw CLI output to structured data using TextFSM template."""
--> 219     template_dir = get_template_dir()
    220     index_file = os.path.join(template_dir, 'index')
    221     textfsm_obj = clitable.CliTable(index_file, template_dir)

/home/olof/.local/lib/python3.6/site-packages/netmiko/utilities.py in get_template_dir()
    200 and then set the NET_TEXTFSM environment variable to point to the ./ntc-templates/templates
    201 directory."""
--> 202         raise ValueError(msg)
    203     return template_dir
    204

ValueError:
Valid ntc-templates not found, please install https://github.com/networktocode/ntc-templates
and then set the NET_TEXTFSM environment variable to point to the ./ntc-templates/templates
directory.
```

where are files located?
```
olof@olof-ubuntu ~/g/k/week6> pwd
/home/olof/git/ktbyers_python/week6
olof@olof-ubuntu ~/g/k/week6> ls ntc-templates/templates/
hp_procurve_show_arp.template  hp_procurve_show_vlans.template
```

This is what output looks like when using `use_textfsm=False`.
```python
In [1]: output = connection.send_command(command, use_textfsm=False)

In [2]: output
Out[2]: '\n IP ARP table\n\n  IP Address       MAC Address       Type    Port\n  ---------------  ----------------- ------- ----\n  172.16.179.1     e48d8c-7d58e5     dynamic 3   \n  172.16.179.100   10e7c6-72ad7c     dynamic 4   \n\n'

In [3]: output = connection.send_command('show vlans', use_textfsm=False)

In [4]: print(output)

 Status and Counters - VLAN Information

  Maximum VLANs to support : 256
  Primary VLAN : DEFAULT_VLAN
  Management VLAN :

  VLAN ID Name                             Status       Voice
  ------- -------------------------------- ------------ -----
  1       DEFAULT_VLAN                     Port-based   No
  29      T-OFFICE                         Port-based   No
  43      TG-VOIP                          Port-based   No
  1806    1806-LINK                        Port-based   No
  1808    1808-LAN                         Port-based   No
```

**Comment by ktbyers** [comment]
Fixed in above PR
