### ISSUE TITLE
NetMikoAuthenticationException: Telnet login failed

### ISSUE THREAD

**Issue by Selvam02cs33** [ktbyers/netmiko#758]
unable to telnet to the device. getting authentication issue, please help. I was able to login successfully with same user name and password via putty. 

Script 👍 
```

from netmiko import ConnectHandler
import logging
logging.basicConfig(filename='logg.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")
iblre3s2 = {'device_type': 'cisco_ios_telnet', 'ip': 'EDMOTOM12AZ-S4', 'username': 'admin', 'password': '*****', 'port':'23'}
ConnectHandler(**iblre3s2)
```

Logs:

DEBUG:netmiko:read_channel: 

C

CCC

      ---------------------------------------------------

                          ATTENTION

                   This is a private system.

         Access by unauthorized personnel is prohibited

                 and may result in prosecution.

      ----------------------------------------------------

UserName: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 

UserName: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 

UserName: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 

Tacacs authentication failed 

DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:read_channel: CC

**Comment by ktbyers** [comment]
@Selvam02cs33 What model/platform are you connecting to?


Kirk

**Comment by clovehitch** [comment]
I'm getting a similar issue on a Cisco C2950G (IOS 12.1(9)EA1)

===LOG===
UserName: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

UserName: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

UserName: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

Tacacs authentication failed 
================================================
It looks when the username prompt is shown it doesn't recognize it and then continues to send '\r\n'

Any thoughts on this?

**Comment by Selvam02cs33** [comment]
Cisco IOS Software, Catalyst 4500 L3 Switch Software (cat4500-IPBASE-M), Version                                                                                                                                                              15.0(2)SG10, RELEASE SOFTWARE (fc1)

**Comment by Selvam02cs33** [comment]
Cisco IOS Software, C3550 Software (C3550-IPSERVICES-M), Version 12.2(25)SEE2, R                                                                                                                                                             ELEASE SOFTWARE (fc1)

**Comment by ktbyers** [comment]
I think it doesn't like the:

```
UserName:
```

With the capital 'Name' that is different than other IOS devices.

I will see if I can put a fix in for it.

**Comment by clovehitch** [comment]
@ktbyers Do you know where I can look to make this change? I can test it out to see if it works.

**Comment by ktbyers** [comment]
@clovehitch Probably changes this line:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L525


To read:

```python
                if re.search(username_pattern, output, flags=re.I):
```

**Comment by David-Geurts** [comment]
Hey guys,
I had the same issue on a Cisco 3560 switch running 15.0(2)SE9
I fixed it by updating the username match patterns on line 64 of cisco_base_connection.py.

FROM: username_pattern=r"(?:[Uu]ser:|sername|ogin|User Name)",
TO:       username_pattern=r"(?:[Uu]ser:|sername|ogin|User Name|UserName)",

**Comment by ktbyers** [comment]
@David-Geurts Thanks. 

Yes, those two solutions should be equivalent (as the flags=re.I says to ignore capitalization).

**Comment by ktbyers** [comment]
I put in a fix here:

https://github.com/ktbyers/netmiko/commit/aff352c81d35a52c4e4f60e337e76f1171f6f36c

Let me know if anyone can test and verify it works properly.

**Comment by ktbyers** [comment]
The develop branch should have the proper fixes now.

**Comment by Eve320** [comment]
I'm having a similar problem when telneting to iosxr.

----------------------------------------------------------------------------------------

from netmiko import ConnectHandler 
import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")


ciscoxr = { 
	'device_type': 'cisco_xr_telnet', 
	'ip': '10.10.20.173', 
	'username': 'cisco',
	'password': 'cisco',
   }

net_connect = ConnectHandler(**ciscoxr)

------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "myfile.py", line 14, in <module>
    net_connect = ConnectHandler(**ciscoxr)
  File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 302, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/base_connection.py", line 344, in __init__
    self._open()
  File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/base_connection.py", line 349, in _open
    self.establish_connection()
  File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/cisco/cisco_xr.py", line 9, in establish_connection
    super().establish_connection(width=511, height=511)
  File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/base_connection.py", line 908, in establish_connection
    self.telnet_login()
  File "/home/aurora/Documents/Netmiko/netmiko/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 169, in telnet_login
    raise NetmikoAuthenticationException(msg)
netmiko.ssh_exception.NetmikoAuthenticationException: Login failed: 10.10.20.173


-------------------------------------------------
Here's the log file
------------------------------------------------------

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 


IMPORTANT:  READ CAREFULLY
Welcome to the Demo Version of Cisco IOS XRv (the "Software").
The Software is subject to and governed by the terms and conditions
of the End User License Agreement and the Supplemental End User
License Agreement accompanying the product, made available at the
time of your order, or posted on the Cisco website at
www.cisco.com/go/terms (collectively, the "Agreement").
As set forth more fully in the Agreement, use of the Software is
strictly limited to internal use in a non-production environment
solely for demonstration and evaluation purposes.  Downloading,
installing, or using the Software constitutes acceptance of the
Agreement, and you are binding yourself and the business entity
that you represent to the Agreement.  If you do not agree to all
of the terms of the Agreement, then Cisco is unwilling to license
the Software to you and (a) you may not download, install or use the
Software, and (b) you may return the Software as more fully set forth
in the Agreement.


Please login with any configured user/password, or cisco/cisco


User Access Verification

Username: 

Username: 



DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:
