### ISSUE TITLE
How do I use raw_input and getpass for my script

### ISSUE THREAD

**Issue by jacob2717** [ktbyers/netmiko#759]
Hi Kirk,

This is the similar script from my last issue I reported and which was fixed, and now I am trying to integrate import subprocess into it, meaning how do I use raw_input and get.pass instead of mentioning my own username and password into the script, because in an enterprise network for bigger organisation it wouldn't be best practice to save individuals or service accounts credentials in the script instead when we run the script it should prompt for username and password : 

SCRIPT==========
from netmiko import ConnectHandler
import subprocess
import getpass

juniper_junos = {
	'device_type': 'juniper_junos',
	'ip': '10.6.254.53',
	'username:' raw_input("Enter your Username:"),
	'password:' getpass.getpass',
}

net_connect = ConnectHandler(**juniper_junos)
output = net_connect.send_command('show arp no-resolve | match 10.6.2.79')
output_arp = output.strip()[0:18]
print output_arp

cisco_nxos = {
	'device_type': 'cisco_nxos',
	'ip': '10.6.2.11',
	'username:' raw_input("Enter your Username:"),
	'password:' getpass.getpass',
}

net_connect = ConnectHandler(**cisco_nxos)
output_mac = net_connect.send_command('show mac address-table address ' + output_arp)
print output_mac

=========output===========

PS C:\Python-Scripts> python port_v1.py
  File "port_v1.py", line 9
    'username:' raw_input("Enter your Username:"),
                        ^
SyntaxError: invalid syntax
PS C:\Python-Scripts> python port_v1.py
  File "port_v1.py", line 9
    'username:' raw_input("Enter your Username:"),
                        ^
SyntaxError: invalid syntax

================================

I am not sure what I am missing or I may be thinking wrong completely.. Your help would be highly appreciated!!!

**Comment by ktbyers** [comment]
@jacob2717 You enclosed the colon inside the string quotes:

```
'username:' raw_input("Enter your Username:"),
```

You need to have:

```
'username': raw_input("Enter your Username:"),
```

**Comment by jacob2717** [comment]
Nice catch, also I re-did my script and it works awesome!!! again thanks a lot for you help!!


==========SCRIPT=========

from netmiko import ConnectHandler
import getpass
import subprocess

user1 = raw_input('Username: ')
p = getpass.getpass()
	
juniper_junos = {
	'device_type': 'juniper_junos',
	'ip': '10.6.254.53',
	'username': user1,
	'password': p,
}

net_connect = ConnectHandler(**juniper_junos)
output = net_connect.send_command('show arp no-resolve | match 10.6.2.79')
output_arp = output.strip()[0:18]
print output_arp

cisco_nxos = {
	'device_type': 'cisco_nxos',
	'ip': '10.6.2.11',
	'username': user1,
	'password': p,
}

net_connect = ConnectHandler(**cisco_nxos)
output_mac = net_connect.send_command('show mac address-table address ' + output_arp)
print output_mac

==========OUTPUT===========
PS C:\Python-Scripts> python test.py
Username: *****
Password:
00:2a:6a:98:d4:21
Legend:
        * - primary entry, G - Gateway MAC, (R) - Routed MAC, O - Overlay MAC
        age - seconds since last seen,+ - primary entry using vPC Peer-Link
   VLAN     MAC Address      Type      age     Secure NTFY   Ports/SWID.SSID.LID
---------+-----------------+--------+---------+------+----+------------------
+ 30       002a.6a98.d421    dynamic   0          F    F  Po1
