### ISSUE TITLE
Juniper show | compare doesn't print

### ISSUE THREAD

**Issue by Jajao555** [ktbyers/netmiko#760]
I can't figure out why the show | compare output doesn't get printed in a logger DEBUG log file or to a saved txt file. I'm also having a similar issue with request rescue save command but I do see it being sent in the logger file.

Here's my script:
```python
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

# Create console handler with a higher log level
ch = logging.StreamHandler()
ch.setLevel(logging.INFO)

# Create file handler which logs even debug messages
fh = logging.FileHandler('./python_work/zlogger.log')
fh.setLevel(logging.DEBUG)

# Create formatter and add it to the handlers
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
fh.setFormatter(formatter)
ch.setFormatter(formatter)

# Add the handlers to the logger
logger.addHandler(ch)
logger.addHandler(fh)

sttime = datetime.now().strftime('%Y%m%d_%H:%M:%S:%f - ')
output_file_name = './python_work/zmgmt_output_file.txt'
o = open(output_file_name,'a')

session = netmiko.ConnectHandler( device_type=device_type, ip=node['ip'], username=username, 
    password=password, global_delay_factor=2)
output = session.find_prompt()
output += session.send_command('request system configuration rescue save')
juniper_cmdset = ['rollback 0',
                                'delete system syslog',
                                'set system syslog user * any emergency',
                                 # ---------other commands------------------
                                'set snmp trap-group traps targets 10.x.x.x',]
output += session.send_config_set(juniper_cmdset, exit_config_mode=False)
output += session.send_command('show | compare | no-more')
output += session.commit(and_quit = True)
o.write(output + '\n')
```
This is all I get in my txt file:

test@vSRX-2>
configure 
Entering configuration mode

[edit]
test@vSRX-2# rollback 0 
load complete

[edit]
test@vSRX-2# set snmp trap-group traps targets 10.x.x.x 

[edit]
test@vSRX-2# 
commit and-quit 
commit complete
Exiting configuration mode

test@vSRX-2> 

I can see the rescue save in the logger file but don't see the show | compare happening in either of them.

**Comment by LongBeachHXC** [comment]
I'm not familiar with your platform but for the 'output += session.send_command('show | compare | no-more')' command did you try 'send_command_expect?' I know on Cisco devices when you are trying to run a show command you have to use the 'send_command_expect' method.

**Comment by Jajao555** [comment]
Thanks! That worked.

```python
sttime = datetime.now().strftime('%Y%m%d_%H:%M:%S:%f - ')
output_file_name = './python_work/zmgmt_output_file.txt'
o = open(output_file_name,'a')

session = netmiko.ConnectHandler( device_type=device_type, ip=node['ip'], username=username, 
    password=password, global_delay_factor=2)
output = session.find_prompt()
output += session.send_command('request system configuration rescue save')
juniper_cmdset = ['rollback 0',
                                'delete system syslog',
                                'set system syslog user * any emergency',
                               #----------------------other commands---------------
                                'set snmp trap-group traps targets 10.x.x.x',]
output += session.send_config_set(juniper_cmdset, exit_config_mode=False)
output += session.send_command_expect('show | compare | no-more' + '\n')
output += session.find_prompt()
output += session.commit(and_quit = True)
o.write(output + '\n')
```
Output saved to txt file.

{master}[edit]
test@PE-MX480-1# set snmp trap-group traps targets 10.x.x.x

{master}[edit]
test@PE-MX480-1# 
[edit system]
+   syslog {
+       user * {
+           any emergency;
+       }
+       host 10.x.x.x {
+           any info;
+       file interactive-commands {
+           interactive-commands any;
+       }
+   }
test@PE-MX480-1#commit and-quit 
re0: 
configuration check succeeds
re1: 
commit complete
re0: 
commit complete
Exiting configuration mode

{master}
test@PE-MX480-1>

**Comment by ktbyers** [comment]
@Jajao555 @LongBeachHXC  Note, send_command and send_command_expect are the exact same thing in Netmiko (one method just points to the other) so that is not an explanation for this issue.

This is for any version of Netmiko >= 1.0.0.

Basically I am saying that is not an explanation for your issue (unless you were using a very old version of Netmiko).

**Comment by ktbyers** [comment]
It sounds like you have it working...so just let me know if you want to dig into what was going on in more detail.

**Comment by Jajao555** [comment]
Ya I'd be interested in digging into it more. What else would you want troubleshoot?

I have Netmiko 1.4.3 installed and I'm using Python 2.7.12 on Linux Mint 18.3.

Also for some reason the request system configuration rescue save doesn't print. Not sure if its because it's an operational command? I even tried send_command_expect. It shows up in the logger file.

**Comment by Jajao555** [comment]
Still doesn't show the actual show | compare output. Just shows the command and prompt.

```
{master}[edit]
test@PE-MX480-1# set snmp trap-group traps targets 10.x.x.x

{master}[edit]
test@PE-MX480-1# show | compare 

{master}[edit]
test@PE-MX480-1# test@PE-MX480-1#commit and-quit 
re0: 
configuration check succeeds
re1: 
commit complete
re0: 
commit complete
Exiting configuration mode

{master}
test@PE-MX480-1> 
```

**Comment by Jajao555** [comment]
Actually that did fix it. I forgot to rollback before running it again so nothing showed up because nothing changed lol. Sorry :( Thanks for the help!
