### ISSUE TITLE
Use netmiko to login GNS3 virtual IOS router via telnet successfully, but can NOT print prompt and finally timeout 

### ISSUE THREAD

**Issue by jerryliu0866** [ktbyers/netmiko#761]
Does netmiko support this usage?
netmiko timeout when try to print prompt, errror messages are:

ipython3 -i netmiko-exercise1.py
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
Enter host to connect to: 127.0.0.1
Password:
------------------------------------------------------------------
NetMikoTimeoutException          Traceback (most recent call last)
~/myenv/netmiko-exercise1.py in <module>()
     13 logging.basicConfig(filename='test.log', level=logging.DEBUG)
     14 logger = logging.getLogger("netmiko")
---> 15 net_connect = netmiko.ConnectHandler(host=host, username="pyclass", password=getpass(), device_type="cisco_ios_telnet", port=5000)
     16 print(net_connect.find_prompt())

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py in ConnectHandler(*args, **kwargs)
     98                          'currently supported platforms are: {0}'.format(platforms_str))
     99     ConnectionClass = ssh_dispatcher(kwargs['device_type'])
--> 100     return ConnectionClass(*args, **kwargs)
    101
    102

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py in __init__(self, ip, host, username, password, secret, port, device_type, verbose, global_delay_factor, use_keys, key_file, allow_agent, ssh_strict, system_host_keys, alt_host_keys, alt_key_file, ssh_config_file, timeout)
    121         if '_telnet' in device_type:
    122             self.protocol = 'telnet'
--> 123             self.establish_connection()
    124             self.session_preparation()
    125         else:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py in establish_connection(self, width, height)
    523             return ""
    524         else:
--> 525             raise NetMikoTimeoutException("Timed out waiting for data")
    526
    527     def select_delay_factor(self, delay_factor):

NetMikoTimeoutException: Timed out waiting for data

test.log file:

DEBUG:netmiko:read_channel: Connected to Dynamips VM "R1" (ID 1, type c3725) - Console port
Press ENTER to get the prompt.
isco.com.

Cisco 3725 (R7000) processor (revision 0.1) with 124928K/6144K bytes of memory.
Processor board ID FTX0945W0MY
R7000 CPU at 240MHz, Implementation 39, Rev 2.1, 256KB L2, 512KB L3 Cache
4 FastEthernet interfaces
4 Serial(sync/async) interfaces
DRAM configuration is 64 bits wide with parity enabled.
55K bytes of NVRAM.
Installed image archive

% Crashinfo may not be recovered at flash:crashinfo
% This file system device reports an error

Press RETURN to get started!

*Mar  1 00:00:07.407: %SW_VLAN-4-IFS_FAILURE: VLAN manager encountered file operation error: call = ifs_open/read / code = 3588 (No device available)
    / bytes transfered = 0
*Mar  1 00:00:07.431: %LINEPROTO-5-UPDOWN: Line protocol on Interface VoIP-Null0, changed state to up
*Mar  1 00:00:07.435: %LINK-3-UPDOWN: Interface Serial0/0, changed state to up
*Mar  1 00:00:07.439: %LINK-3-UPDOWN: Interface Serial0/1, changed state to up
*Mar  1 00:00:07.443: %LINK-3-UPDOWN: Interface Serial0/2, changed state to up
*Mar  1 00:00:07.447: %LINK-3-UPDOWN: Interface Serial0/3, changed state to up
*Mar  1 00:00:07.451: %LINK-3-UPDOWN: Interface FastEthernet1/0, changed state to up
*Mar  1 00:00:07.455: %LINK-3-UPDOWN: Interface FastEthernet2/0, changed state to up
*Mar  1 00:00:07.459: %LINEPROTO-5-UPDOWN: Line protocol on Interface IPv6-mpls, changed state to up
*Mar  1 00:00:08.563: %LINEPROTO-5-UPDOWN: Line protocol on Interface Serial0/0, changed state to down
*Mar  1 00:00:08.563: %LINEPROTO-5-UPDOWN: Line protocol on Interface Serial0/1, changed state to down
*Mar  1 00:00:08.563: %LINEPROTO-5-UPDOWN: Line protocol on Interface Serial0/2, changed state to down
*Mar  1 00:00:08.567: %LINEPROTO-5-UPDOWN: Line protocol on Interface Serial0/3, changed state to down
*Mar  1 00:00:08.567: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet1/0, changed state to up
*Mar  1 00:00:08.567: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet2/0, changed state to down
*Mar  1 00:00:08.587: %SYS-5-CONFIG_I: Configured from memory by console
*Mar  1 00:00:08.795: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback0, changed state to up
*Mar  1 00:00:08.939: %SYS-5-RESTART: System restarted --
Cisco IOS Software, 3700 Software (C3725-ADVENTERPRISEK9-M), Version 12.4(15)T14, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2010 by Cisco Systems, Inc.
Compiled Tue 17-Aug-10 12:08 by prod_rel_team
*Mar  1 00:00:08.955: %SNMP-5-COLDSTART: SNMP agent on host R1 is undergoing a cold start
*Mar  1 00:00:09.023: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback1, changed state to up
*Mar  1 00:00:09.023: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback2, changed state to up
*Mar  1 00:00:09.027: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback3, changed state to up
*Mar  1 00:00:09.031: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback4, changed state to up
*Mar  1 00:00:09.035: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback5, changed state to up
*Mar  1 00:00:09.039: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback6, changed state to up
*Mar  1 00:00:09.039: %LINK-3-UPDOWN: Interface FastEthernet0/1, changed state to up
*Mar  1 00:00:09.047: %LINK-3-UPDOWN: Interface FastEthernet0/0, changed state to up
*Mar  1 00:00:09.983: %LINK-5-CHANGED: Interface Serial0/0, changed state to administratively down
*Mar  1 00:00:10.039: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet0/1, changed state to up
*Mar  1 00:00:10.043: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet0/0, changed state to up
*Mar  1 00:00:10.131: %LINK-5-CHANGED: Interface Serial0/1, changed state to administratively down
*Mar  1 00:00:10.139: %LINK-5-CHANGED: Interface Serial0/2, changed state to administratively down
*Mar  1 00:00:10.147: %LINK-5-CHANGED: Interface Serial0/3, changed state to administratively down
*Mar  1 00:00:10.187: %LINK-5-CHANGED: Interface FastEthernet2/0, changed state to administratively down
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 

User Access Verification

Username: 
DEBUG:netmiko:write_channel: b'pyclass\r\n'
DEBUG:netmiko:read_channel: pyclass
Password: 
DEBUG:netmiko:write_channel: b'cisco\r\n'
DEBUG:netmiko:read_channel: 
R1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'

**Comment by ktbyers** [comment]
@jerryliu0866 Is the device super slow to respond?

In your debug, I see use send <enter> (\n) around 30 times and the router never responds (after the first one)?

Possibly try setting `global_delay_factor=2` or 4 (this is an argument to ConnectHandler).

**Comment by jerryliu0866** [comment]
No, respond is normal. Maybe is because of console telnet in GNS3, NOT real telnet? I also tried to set global_delay_factor=4, but still failed with the same issue.

**Comment by ktbyers** [comment]
If it is the console-telnet, then you probably need to use the `terminal_server` device type and redispatch.

See example here:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#does-netmiko-support-connecting-via-a-terminal-server

**Comment by ktbyers** [comment]
@jerryliu0866 Yes, you need to use the latest version of Netmiko (2.1.1).


Kirk

**Comment by jerryliu0866** [comment]
I had to use special port 5xxx to telnet to console of IOS router in GNS3, so seems 'terminal server' mode did NOT fit. Error messages: "Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position 0: invalid start byte"

********************************************************
In [1]: from __future__ import unicode_literals, print_function
   ...: import time
   ...: from netmiko import ConnectHandler, redispatch
   ...: net_connect = ConnectHandler(
   ...:     device_type='terminal_server',        # Notice 'terminal_server' here
   ...:
   ...:     ip='127.0.0.1',
   ...:     username='pyclass',
   ...:     password='cisco',
   ...:     port=5000)
   ...:
Exception: Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2044, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py", line 359, in readline
    return u(buf)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/py3compat.py", line 143, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 1893, in run
    self._check_banner()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2049, in _check_banner
    'Error reading SSH protocol banner' + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py in _check_banner(self)
   2043             try:
-> 2044                 buf = self.packetizer.readline(timeout)
   2045             except ProxyCommandFailure:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py in readline(self, timeout)
    358             buf = buf[:-1]
--> 359         return u(buf)
    360

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/py3compat.py in u(s, encoding)
    142         if isinstance(s, bytes):
--> 143             return s.decode(encoding)
    144         elif isinstance(s, str):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

During handling of the above exception, another exception occurred:

SSHException                              Traceback (most recent call last)
<ipython-input-1-db55c36f5104> in <module>()
      7     username='pyclass',
      8     password='cisco',
----> 9     port=5000)
     10

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py in ConnectHandler(*args, **kwargs)
    176                          'currently supported platforms are: {}'.format(platforms_str))
    177     ConnectionClass = ssh_dispatcher(kwargs['device_type'])
--> 178     return ConnectionClass(*args, **kwargs)
    179
    180

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py in __init__(self, ip, host, username, password, secret, port, device_type, verbose, global_delay_factor, use_keys, key_file, allow_agent, ssh_strict, system_host_keys, alt_host_keys, alt_key_file, ssh_config_file, timeout, session_timeout, blocking_timeout, keepalive, default_enter, response_return, serial_settings)
    205
    206             self._modify_connection_params()
--> 207             self.establish_connection()
    208             self.session_preparation()
    209

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py in establish_connection(self, width, height)
    687             # initiate SSH connection
    688             try:
--> 689                 self.remote_conn_pre.connect(**ssh_connect_params)
    690             except socket.error:
    691                 msg = "Connection to device timed-out: {device_type} {ip}:{port}".format(

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/client.py in connect(self, hostname, port, username, password, pkey, key_filename, timeout, allow_agent, look_for_keys, compress, sock, gss_auth, gss_kex, gss_deleg_creds, gss_host, banner_timeout, auth_timeout, gss_trust_dns, passphrase)
    390             sec_opts.key_types = [keytype] + other_types
    391
--> 392         t.start_client(timeout=timeout)
    393
    394         # If GSS-API Key Exchange is performed we are not required to check the

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py in start_client(self, event, timeout)
    543                 e = self.get_exception()
    544                 if e is not None:
--> 545                     raise e
    546                 raise SSHException('Negotiation failed.')
    547             if (

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py in run(self)
   1891                 self.packetizer.write_all(b(self.local_version + '\r\n'))
   1892                 self._log(DEBUG, 'Local version/idstring: {}'.format(self.local_version)) # noqa
-> 1893                 self._check_banner()
   1894                 # The above is actually very much part of the handshake, but
   1895                 # sometimes the banner can be read but the machine is not

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py in _check_banner(self)
   2047             except Exception as e:
   2048                 raise SSHException(
-> 2049                     'Error reading SSH protocol banner' + str(e)
   2050                 )
   2051             if buf[:4] == 'SSH-':

SSHException: Error reading SSH protocol banner'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [2]:

**Comment by ktbyers** [comment]
Which version of Paramiko do you have installed?

**Comment by jerryliu0866** [comment]
Version: 2.4.1

**Comment by ktbyers** [comment]
@jerryliu0866 Try:

```
from __future__ import unicode_literals, print_function
import time
from netmiko import ConnectHandler, redispatch

net_connect = ConnectHandler(
    device_type='generic_termserver_telnet'        # changed
    ip='127.0.0.1',
    username='pyclass',
    password='cisco',
    port=5000)
```

**Comment by jerryliu0866** [comment]
Failed and error messages are:

Traceback (most recent call last):
  File "./netmiko_consoleTelnet.py", line 54, in <module>
    redispatch(net_connect, device_type='cisco_ios')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 196, in redispatch
    obj.session_preparation()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/cisco/cisco_ios.py", line 16, in session_preparation
    self._test_channel_read(pattern=r'[>#]')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netmiko/base_connection.py", line 756, in _test_channel_read
    raise NetMikoTimeoutException("Timed out waiting for data")
netmiko.ssh_exception.NetMikoTimeoutException: Timed out waiting for data
Macintosh:Python_Projects Jerry$

**Comment by ktbyers** [comment]
@jerryliu0866 Please post your code associated with your above exception.

**Comment by jerryliu0866** [comment]
Please refer to the below, Thank you!

from __future__ import unicode_literals, print_function
import time
from netmiko import ConnectHandler, redispatch

net_connect = ConnectHandler(
    device_type='generic_termserver_telnet',        # changed
    ip='127.0.0.1',
    username='pyclass',
    password='cisco',
    port=5000)

# Manually handle interaction in the Terminal Server
# (fictional example, but hopefully you see the pattern)
# Send Enter a Couple of Times
net_connect.write_channel("\r\n")
time.sleep(1)
net_connect.write_channel("\r\n")
time.sleep(1)
output = net_connect.read_channel()
print(output)                             # Should hopefully see the terminal server prompt

# Login to end device from terminal server
net_connect.write_channel("connect 1\r\n")
time.sleep(1)

# Manually handle the Username and Password
max_loops = 10
i = 1
while i <= max_loops:
    output = net_connect.read_channel()

    if 'Username' in output:
        net_connect.write_channel(net_connect.username + '\r\n')
        time.sleep(1)
        output = net_connect.read_channel()

    # Search for password pattern / send password
    if 'Password' in output:
        net_connect.write_channel(net_connect.password + '\r\n')
        time.sleep(.5)
        output = net_connect.read_channel()
        # Did we successfully login
        if '>' in output or '#' in output:
            break

    net_connect.write_channel('\r\n')
    time.sleep(.5)
    i += 1

# We are now logged into the end device
# Dynamically reset the class back to the proper Netmiko class
redispatch(net_connect, device_type='cisco_ios')

# Now just do your normal Netmiko operations
new_output = net_connect.send_command("show ip int brief")

**Comment by ktbyers** [comment]
So it fails on the redispatch, did you verify you are in the correct state prior to this point? i.e. fully logged into the end-device?

You might want to turn on logging and see if that gives you more clues as to what is happening.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by jerryliu0866** [comment]
At the beginning, it seems login failed but finally it log on successfully. Then lots of read/write channel, same as using "telenet" mode.

DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: Connected to Dynamips VM "R1" (ID 1, type c3725) - Console port
Press ENTER to get the prompt.
ption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco 3725 (R7000) processor (revision 0.1) with 124928K/6144K bytes of memory.
Processor board ID FTX0945W0MY
R7000 CPU at 240MHz, Implementation 39, Rev 2.1, 256KB L2, 512KB L3 Cache
4 FastEthernet interfaces
4 Serial(sync/async) interfaces
DRAM configuration is 64 bits wide with parity enabled.
55K bytes of NVRAM.
Installed image archive

% Crashinfo may not be recovered at flash:crashinfo
% This file system device reports an error


Press RETURN to get started!


*Mar  1 00:00:06.099: %SW_VLAN-4-IFS_FAILURE: VLAN manager encountered file operation error: call = ifs_open/read / code = 3588 (No device available)
    / bytes transfered = 0
*Mar  1 00:00:06.115: %LINEPROTO-5-UPDOWN: Line protocol on Interface VoIP-Null0, changed state to up
*Mar  1 00:00:06.119: %LINEPROTO-5-UPDOWN: Line protocol on Interface IPv6-mpls, changed state to up
*Mar  1 00:00:06.123: %LINK-3-UPDOWN: Interface Serial0/0, changed state to up
*Mar  1 00:00:06.127: %LINK-3-UPDOWN: Interface Serial0/1, changed state to up
*Mar  1 00:00:06.131: %LINK-3-UPDOWN: Interface Serial0/2, changed state to up
*Mar  1 00:00:06.135: %LINK-3-UPDOWN: Interface Serial0/3, changed state to up
*Mar  1 00:00:06.139: %LINK-3-UPDOWN: Interface FastEthernet1/0, changed state to up
*Mar  1 00:00:06.143: %LINK-3-UPDOWN: Interface FastEthernet2/0, changed state to up
*Mar  1 00:00:07.155: %SYS-5-CONFIG_I: Configured from memory by console
*Mar  1 00:00:07.287: %LINEPROTO-5-UPDOWN: Line protocol on Interface Serial0/0, changed state to down
*Mar  1 00:00:07.291: %LINEPROTO-5-UPDOWN: Line protocol on Interface Serial0/1, changed state to down
*Mar  1 00:00:07.291: %LINK-3-UPDOWN: Interface FastEthernet0/1, changed state to up
*Mar  1 00:00:07.295: %LINEPROTO-5-UPDOWN: Line protocol on Interface Serial0/2, changed state to down
*Mar  1 00:00:07.295: %LINK-3-UPDOWN: Interface FastEthernet0/0, changed state to up
*Mar  1 00:00:07.299: %LINEPROTO-5-UPDOWN: Line protocol on Interface Serial0/3, changed state to down
*Mar  1 00:00:07.299: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet1/0, changed state to up
*Mar  1 00:00:07.303: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet2/0, changed state to down
*Mar  1 00:00:07.427: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback0, changed state to up
*Mar  1 00:00:07.539: %SYS-5-RESTART: System restarted --
Cisco IOS Software, 3700 Software (C3725-ADVENTERPRISEK9-M), Version 12.4(15)T14, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2010 by Cisco Systems, Inc.
Compiled Tue 17-Aug-10 12:08 by prod_rel_team
*Mar  1 00:00:07.551: %SNMP-5-COLDSTART: SNMP agent on host R1 is undergoing a cold start
*Mar  1 00:00:07.619: %LINEPROTO-5-UPDOWN: Line protocol on Interface Loopback1, changed state to up
*Mar  1 00:00:08.291: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet0/1, changed state to up
*Mar  1 00:00:08.295: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet0/0, changed state to up
*Mar  1 00:00:08.651: %LINK-5-CHANGED: Interface Serial0/0, changed state to administratively down
*Mar  1 00:00:08.795: %LINK-5-CHANGED: Interface Serial0/1, changed state to administratively down
*Mar  1 00:00:08.803: %LINK-5-CHANGED: Interface Serial0/2, changed state to administratively down
*Mar  1 00:00:08.803: %LINK-5-CHANGED: Interface Serial0/3, changed state to administratively down
*Mar  1 00:00:08.843: %LINK-5-CHANGED: Interface FastEthernet2/0, changed state to administratively down

User Access Verification

Username: 
Username: 
DEBUG:netmiko:write_channel: b'connect 1\r\n'
DEBUG:netmiko:read_channel: connect 1
Password: 
DEBUG:netmiko:write_channel: b'cisco\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
% Login invalid

Username: 
Username: 
DEBUG:netmiko:write_channel: b'pyclass\r\n'
DEBUG:netmiko:read_channel: pyclass
Password: 
DEBUG:netmiko:write_channel: b'cisco\r\n'
DEBUG:netmiko:read_channel: 
R1#
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'

**Comment by ktbyers** [comment]
So what it is showing is that you keep hitting enter and are not getting any response back. Is this device super slow?

Maybe try setting a global_delay_factor of 4 in ConnectHandler?

You could also maybe try setting the default_enter to '\r\n' in case that is messing up the terminal server, console connection in some way.

```
net_connect = ConnectHandler(
    device_type='generic_termserver_telnet',        # changed
    ip='127.0.0.1',
    username='pyclass',
    password='cisco',
    global_delay_factor=4,
    default_enter='\r\n',
    port=5000)
```

**Comment by jerryliu0866** [comment]
It Works! Thank you very much! BTW, it also works under device_type="cisco_ios_telnet" mode. default_enter='\r\n' setting is the key, it also works without  global_delay_factor=4 setting.

**Comment by ktbyers** [comment]
Nice...

yes, I forgot that telnet probably already changes the default_enter.
