### ISSUE TITLE
Zones in firewalls

### ISSUE THREAD

**Issue by jacob2717** [ktbyers/netmiko#767]
Good morning Kirk,

I am trying to strip information with respect to what ZONE and IP belongs to but len or output.strip doesnt seem to helping out here.

jkedari@DC1F3_Int_NP0_FW01> show interfaces reth0.50               
  Logical interface reth0.50 (Index 113) (SNMP ifIndex 565)
    Description: Confidential VLAN
    Flags: SNMP-Traps 0x0 VLAN-Tag [ 0x8100.50 ]  Encapsulation: ENET2
    Statistics        Packets        pps         Bytes          bps
    Bundle:
        Input :     437583334         10  303705060650        26424
        Output:     487018181          8  481691860326        12024
    Adaptive Statistics:
        Adaptive Adjusts:          0
        Adaptive Scans  :          0
        Adaptive Updates:          0
    Security: Zone: Confidential
    Allowed host-inbound traffic : ping traceroute
    Protocol inet, MTU: 1500
      Flags: Sendbcast-pkt-to-re
      Addresses, Flags: Is-Preferred Is-Primary
        Destination: 10.6.6/23, Local: 10.6.6.1, Broadcast: 10.6.7.255
    Protocol multiservice, MTU: Unlimited

Now is you see above output I am only interested in Security Zone name: i.e., Confidential how do I store only that information in an variable. I tried using len and output.strip but it seems for other zone the length size varies if the ZONE name is Internal then the length size reduces, hence need your help with this regards....

My Script - 

from netmiko import ConnectHandler
import getpass
import subprocess

user1 = raw_input('Username: ')
p = getpass.getpass()
	
juniper_junos = {
	'device_type': 'juniper_junos',
	'ip': '10.6.254.53',
	'username': user1,
	'password': p,
}

Source_IP_Add = raw_input('Source_IP_Add: ')
net_connect = ConnectHandler(**juniper_junos)
output = net_connect.send_command('show route ' + Source_IP_Add)
Source_Route_output = output.strip()[189:197]
print Source_Route_output

S_Zone_output = net_connect.send_command('show interface ' + Source_Route_output)
Source_Zone_output = S_Zone_output.strip()[536:550]
print Source_Zone_output

========OUTPUT===========

FIRST OUTPUT FOR FIRST ZONE which worked smoothly, but for second output since the name is with small length size it shows output which is not intended.
PS C:\Python-Scripts> python firewall_test.py
Username: jkedari
Password:
Source_IP_Add: 10.6.6.138
reth0.50
Confidential

SECOND OUTPUT for other ZONEs*******************
PS C:\Python-Scripts> python firewall_test.py
Username: jkedari
Password:
Source_IP_Add: 10.6.6.138
reth0.50
Confidential

Destination_IP_Add: 10.6.8.22
reth0.60
rnal       <======== It should have shown Internal
    Allow

**Comment by ktbyers** [comment]
Use the split() method but match a pattern like:

```python
output.split('Security: Zone:')
```

Or use regular expression parsing. I talk about this quite a bit in my free Python course.
