### ISSUE TITLE
Can we pass multiple show commands by using a file with send_commands module?

### ISSUE THREAD

**Issue by DilrajSK** [ktbyers/netmiko#769]
I am getting an error while trying to achieve this. Below is the exception:

`AttributeError: 'list' object has no attribute 'rstrip' `

**Comment by ktbyers** [comment]
@DilrajSK You create a for loop, read the file and call send_command with each individual command. `send_command` takes a command string, not a list.

**Comment by DilrajSK** [comment]
Thanks!
