### ISSUE TITLE
cisco_ios tries to exit_config_mode on disconnect?

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#770]
disconnect() call causes this?

```
63 DEBUG:netmiko:exit_config_mode:
64 DEBUG:netmiko:write_channel: b'exit\n'
 ```

Why?

**Comment by jcrotts** [comment]
Isn't this caused by the cleanup function in cisco_base_connection ?

**Comment by ktbyers** [comment]
I think the oddity is that I wouldn't have expected that sequence.

I would have expected it to go into exit_config_mode() and then hit an enter to determine whether we are currently in config_mode, but this has exit right after the exit_config_mode call in the logging debug.

It looks like this would probably happen if the connection was already dead for some reason (i.e. the SSH session was already terminated).

I probably just need to look at the logs again on a session disconnect() and see what happens.

**Comment by jcrotts** [comment]
Interesting, I'll see if I can replicate it, what device were you using?

**Comment by ktbyers** [comment]
Enable logging configuration is here:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel
