### ISSUE TITLE
ssh/telent within a router/switch

### ISSUE THREAD

**Issue by adityamoon** [ktbyers/netmiko#772]
Hi folks, so my connectivity is like this :We have OSS switch and from there all my networking devices gets logged on via telnet/ssh. So I first need to login to OSS switch and than other devices.

I have reached into login prompt of OSS switch by using basic netmiko commands but now how to create a python script using netmiko to achieve the desired target ? 

Below is my rough attempt : 

from netmiko import ConnectHandler
cisco_oss = {
    'device_type':'cisco_ios',
    'ip':'10.7.x.y',
    'username':'oss_ad',
    'password':'krypt1',
    'verbose':True,
}
net_connect = ConnectHandler(**cisco_oss)
net_connect.find_prompt()
output = net_connect.send_command('ssh -v 2 -l ciscouser 10.7.x.y') #to access further devices from here
if 'Password:' in output: # because it displays Password prompt here 
    net_connect.send_command('Blue')
    net_connect.find_prompt()
    output = net_connect.send_command("sh int des")
    print (output)
    print (net_connect)
    
	SSH connection established to 10.7.x.y:22
	
Interactive SSH session established
          ^
% Invalid input detected at '^' marker.

<netmiko.cisco.cisco_ios.CiscoIosSSH object at 0x0564D770>

**Comment by ktbyers** [comment]
@adityamoon You probably need to do something more like this:

https://github.com/ktbyers/pynet/blob/master/presentations/dfwcug/examples/case13_term_server/term_server.py

You won't be able to do this:

```
output = net_connect.send_command('ssh -v 2 -l ciscouser 10.7.x.y')
```

as send_command is expecting the current devices prompt to come back. You could try it with send_command_timing, but you would still need to do the `redispatch` show in the reference code above after you have logged in.

**Comment by zhecho** [comment]
Hello all,

Maybe you should check proxy_command() in paramko. it's more convenient to
use ssh keys for the hopping station.

Best regards.

**Comment by byunkook** [comment]
Here's another way I found to run show run from a ssh session within intermediate router.

Whole configuration involving SSH proxy was too much for me.

#-----------------------------------------------------
import sys
from netmiko import ConnectHandler

intermediate_ios = {
    'device_type': 'cisco_ios',
    'ip': '123.13.123.13',
    'username': 'UN',
    'password': 'PW',
    'secret': 'SECRET',
    'session_log': sys.stdout,
}
#List of commands to execute
commands = [
'do ssh 192.168.56.253',
'PW_FOR_SSH',
'terminal length 0',
'sh run',
]

net_connect = ConnectHandler(**intermediate_ios)
net_connect.enable()
output = net_connect.send_config_set(config_commands=commands)

#---------------------------------------------------

**Comment by ktbyers** [comment]
@byunkook You should use `redispatch` if you use the above pattern (at least if the device_type is different between the intermediate network device and the end network device). This is a common pattern for non SSH-proxy situations.
