### ISSUE TITLE
unable to execute the command through netmiko tools

### ISSUE THREAD

**Issue by francisjes** [ktbyers/netmiko#773]
I created the inventory file based on the example provided. below is output of netmiko-grep --list-devices. but i can't directly login to the below devices and can be login through jumphost. so any changes has to be done in netmiko tools files netmiko-cfg  netmiko-grep  netmiko-show for logging the devices through jumphost? if any sample programs availables for netmiko tools using loging the devices trhough jumphost

Devices:
----------------------------------------
XXXXXXXX            (alcatel_sros)
YYYYYYYYY                    (juniper)

Groups:
----------------------------------------
alcatel
juniper
all

while executing the command netmiko-show --cmd "show version" juniper, it's not running and getting the below error

^CTraceback (most recent call last):
  File "/home/uadmin/netmiko_tools/netmiko_tools/netmiko-show", line 181, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/uadmin/netmiko_tools/netmiko_tools/netmiko-show", line 164, in main
    grepx(my_files, pattern, grep_options)
  File "/home/uadmin/netmiko_tools/netmiko_tools/netmiko-show", line 48, in grepx
    proc.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 797, in communicate
    self.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

**Comment by ktbyers** [comment]
It looks like you control-C out of the operation (i.e. KeyboardInterrupt). Can you let it fail and see what happens.

Have you double checked the IP address, and username and password in the .netmiko.yml file?


Kirk

**Comment by francisjes** [comment]
yeah i interrupt the operation since this command was not executing for long. yeah ipaddress username password is correct, but only the problem is don't know how to define my jumpserver? since first we need to login to jumpserver and then login to corresponding devices.

**Comment by ktbyers** [comment]
@francisjes So you are trying to run netmiko-tools through a Jump server?

Is your login to your jump server transparent? By this I mean using SSH keys and not requiring any manual username/password entry?

**Comment by francisjes** [comment]
i'm using username password only to login jumpserver. my setup was working fine if i'm using netmiko only. when started using netmiko tools having an issue. can you please advice if we need to add anything in your main program?

**Comment by francisjes** [comment]
Do we need to define jump server information in netmiko-cfg file?  

we generally use below code in netmiko
jumpserver = {'device_type': 'terminal_server','ip': 'IP','username': 'UN','password': xx,'global_delay_factor':5}
        nc = ConnectHandler(**jumpserver)
        nc.find_prompt()
        nc.write_channel('ssh  UN@%s\n' % ipaddrs[sros_name])
        nc.read_until_pattern('password:')
        nc.write_channel(xxx\n')
        redispatch(nc, device_type='alcatel_sros')
        nc.find_prompt()
   
Can you advice what changes has to be done on netmiko-cfg file to login first jumpserver first and then login to nw devices.
--------------------------------------------------------------------------------------------
                                      netmiko-cfg file
--------------------------------------------------------------------------------------------
def ssh_conn(device_name, a_device, cfg_command, output_q):
    try:
        net_connect = ConnectHandler(**a_device)
        net_connect.enable()
        if isinstance(cfg_command, string_types):
            cfg_command = [cfg_command]
        output = net_connect.send_config_set(cfg_command)
        net_connect.disconnect()
    except Exception:
        output = ERROR_PATTERN
    output_q.put({device_name: output})

--------------------------------------------------------------------------------------------

**Comment by ktbyers** [comment]
@francisjes Yes, you won't be able to do that with netmiko_tools (you would have to have an SSH proxy setup similar to this for it to possibly work):

https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

Basically, netmiko tools would have to be able to login all the way to the end device without any extra glue code being added in Python (so it would have to be entirely in .netmiko.yml and in the SSH config file).

**Comment by francisjes** [comment]
yeah i made changes to ssh config file and able to login the devices directly bypassing jumphost now.
but am still having an same issue. can you please advice if we can enable any logging to see where exactly the program is stuckup?

**Comment by ktbyers** [comment]
Logging configuration is here:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

You will have to add it into the netmiko tools code for the relevant command.


Can you post your .netmiko.yml (just obscure any passwords/ip addresses).

**Comment by francisjes** [comment]
i removed ipaddress password hostname from the output

# Dictionaries are devices
device1:
  device_type: alcatel_sros
  ip: IP
  username: UN
  password: PWD
  port: 22

device2:
  device_type: alcatel_sros
  ip: IP
  username: UN
  password: PWD
  port: 22

device3:
  device_type: juniper
  ip: IP
  username: UN
  password: PWD
  port: 22

# Lists are groups of devices
Alcatel:
  - device1
  - device2
Juniper:
  - device3

**Comment by francisjes** [comment]
Thanks for your help and support. However i need to mention password here and can use ssh_config_file to login the device bypassing jumpserver. i tried this option also but no luck. any other idea?

**Comment by ktbyers** [comment]
Just to verify your Jumpserver doesn't require any username/password correct (i.e. you are authenticating here using SSH keys)?

Please post your updated .netmiko.yml (strip PWD and IP addresses) and your ssh_config file.

**Comment by francisjes** [comment]
yeah jumpserver doesnt require any username and password. you can see below as i'm able to successfully login to the device by providing only password and bypassing jumpserver

uadmin@uadmin-virtual-machine:~/netmiko_tools/netmiko_tools$ ssh UN@Device1 
Password:
--- JUNOS XXXXX built XXXX 19:59:57 UTC
{master}
UN@Device1>

-------------------------------------------------------------------------------------
            netmiko.yml
-------------------------------------------------------------------------------------
Device1:
  device_type: juniper
  ip: IP
  username: UN
  password: PWD
  ssh_config_file: "/home/uadmin/.ssh/config"
  port: 22
-------------------------------------------------------------------------------------

----------------------------------------------------------------------------------
           ssh config file
---------------------------------------------------------------------------------
uadmin@uadmin-virtual-machine:~/netmiko_tools/netmiko_tools$ cat /home/uadmin/.ssh/config
host jumpserver    
  IdentityFile ~/.ssh/id_rsa
  user UN
  hostname XXXX

host Device1
  user UN
  hostname Device1
  Port 22
  ProxyCommand ssh jumpserver nc %h %p

**Comment by ktbyers** [comment]
Okay, that looks right...looking into it some more.

**Comment by ktbyers** [comment]
Okay, your identifier here is the IP. So your SSH config needs to use that identifier.

```
# SSH config
host jumpserver    
  IdentityFile ~/.ssh/id_rsa
  user UN
  hostname XXXX

host IP
  user UN
  hostname IP
  Port 22
  ProxyCommand ssh jumpserver nc %h %p
```

**Comment by ktbyers** [comment]
This worked for me:

```
---

# .netmiko.yml
pynet_rtr1:
  device_type: cisco_ios
  host: test1.twb-tech.com
  username: admin
  password: foo
  ssh_config_file: "/home/gituser/EP/ssh_config_test2"
  port: 22
```

```
host jumphost
  IdentityFile ~/.ssh/test_rsa
  user gituser
  hostname 54.241.72.159

host test1.twb-tech.com
  user admin
  hostname test1.twb-tech.com
  Port 22
  ProxyCommand ssh jumphost nc %h %p
```

**Comment by francisjes** [comment]
Thank you. i',m not sure even my ssh config and .netmiko.yml is correct why its not working in my setup

**Comment by francisjes** [comment]
File "./netmiko-show", line 181, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./netmiko-show", line 164, in main
    grepx(my_files, pattern, grep_options)
  File "./netmiko-show", line 48, in grepx
    proc.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 797, in communicate
    self.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)

**Comment by francisjes** [comment]
please ignore my previous command, its working now.

Thank you very much for your support and help.

**Comment by ktbyers** [comment]
What was the last issue?

**Comment by francisjes** [comment]
after adding ssh config file parameter, i wrongly added ip address instead of hostname. so below format is correct

-------------------------------------------------------------------------------------
            netmiko.yml
-------------------------------------------------------------------------------------
Device1:
  device_type: juniper
  ip: IP
  username: UN
  password: PWD
  ssh_config_file: "/home/uadmin/.ssh/config"
  port: 22
-------------------------------------------------------------------------------------

----------------------------------------------------------------------------------
           ssh config file
---------------------------------------------------------------------------------
uadmin@uadmin-virtual-machine:~/netmiko_tools/netmiko_tools$ cat /home/uadmin/.ssh/config
host jumpserver    
  IdentityFile ~/.ssh/id_rsa
  user UN
  hostname XXXX

host Device1
  user UN
  hostname Device1
  Port 22
  ProxyCommand ssh jumpserver nc %h %p
