### ISSUE TITLE
save_config on Cisco WLC no longer working

### ISSUE THREAD

**Issue by rehlers** [ktbyers/netmiko#774]
Hello, it looks like a couple of months back, an update was done on the save_config function to make a more generic save_config method in the CiscoBaseConnection class and have each subclass just pass in the correct parameters.

The generic save_config was added to CiscoBaseConnection, but the cisco_wlc_ssh.py file with the CiscoWlcSSH class is a subclass of BaseConnection (not CiscoBaseConnection). BaseConnection does not have the generic save_config implemented, so now calling save_config on Cisco WLC devices raises a Not Implemented exception.

I don't know what the right solution here is, as the Cisco WLC interface is really nothing like anything else Cisco makes. 
Moving the generic save_config from CiscoBaseConnection to BaseConnection? 
Adding a CiscoWlcBaseConnection subclass of BaseConnection in cisco_base_connection.py that just has the save_config?
Making CiscoWlcSSH a subclass of CiscoSSHConnection instead?

**Comment by ktbyers** [comment]
Yes, that is a bug...let me look at it some more regarding what solution makes sense for fixing it.

**Comment by jcrotts** [comment]
You could also just override the save_config method in CiscoWlcSsh, since there probably won't be a need to subclass CiscoWlc.

**Comment by jcrotts** [comment]
I can work on a PR for this, any preference on the above stated solutions?

**Comment by rehlers** [comment]
great thanks so much for working on getting that issue resolved!
