### ISSUE TITLE
Sending Config T commands. Confused! 

### ISSUE THREAD

**Issue by nfordhk** [ktbyers/netmiko#776]
Hi Everyone! First timer here. A bit confused on how to send config t commands. I followed the notes but it doesn't seem to be working properly? Here's a piece of the code having problems. It runs through the code but it never changes the interface's vlan. 

#DEBUG HERE
if changeDecision == 'Yes':
    vlanNumber = input ('\nPlease assign VLAN number: ') #User enters VLAN number
    print ('\nEntering Config t')
    config_commands = ['config t']
    print ('\nEntering the interface specified')
    config_commands = ['Interface '+interface]
    print ('\nAssiging VLAN number')
    config_commands = ['switchport access vlan '+vlanNumber]	
    config_commands = ['exit']
    config_commands = ['exit']
    print ('\nSaving Configuration...')
    config_commands = ['exit'] #Saves configuration
    print ('\nShowing New Configuration')
    print (output) #Prints new output
else:
    net_connect.disconnect()

**Comment by ktbyers** [comment]
@nfordhk Right after this:

```
	config_commands = [
		'Interface ' + interface,
		'switchport access vlan ' + vlanNumber, #User enters VLAN number
		]
```

Add the following:

```
net_connect.send_config_set(config_commands)
```

**Comment by nfordhk** [comment]
@ktbyers I went ahead and updated the github code :) 
https://github.com/nfordhk/Network-Automation/blob/master/vlanChange

**Comment by ktbyers** [comment]
@nfordhk You are disconnecting the SSH session here:

https://github.com/nfordhk/Network-Automation/blob/master/vlanChange#L67

And then you later try to use the SSH session (even though you already disconnected).

**Comment by nfordhk** [comment]
@ktbyers wow! Can't believe I left that line there. It works! thanks so much!
