### ISSUE TITLE
running command from file

### ISSUE THREAD

**Issue by fixlensmith** [ktbyers/netmiko#782]
i want to send command from file

if i use net_connect.send_config_from_file it will enter to config mode.. so i cannot use user with privilege 4, because it will failed to enter configuration mode

is there any function to load command from file without enter config mode?

**Comment by Jajao555** [comment]
I have this question as well. 

I'm using Ciena which is similar to Cisco but you don't need to enter config mode to enter configuration commands. I'm using the ciena_saos device type but it gives me an error saying it couldn't enter config mode and doesn't send the commands from the file.

**Comment by ktbyers** [comment]
@fixlensmith Just read the file using Python and then create a for-loop and use `send_command()`

**Comment by ktbyers** [comment]
@Jajao555 Can you open a separate issue on that. That sounds like a bug in the ciena driver.

**Comment by fixlensmith** [comment]
@ktbyers do you have example for this?

**Comment by ktbyers** [comment]
@fixlensmith Which part are you struggling with?


Kirk
