### ISSUE TITLE
config_mode generates AttributeError: 'NoneType' exception

### ISSUE THREAD

**Issue by adamfitzhugh** [ktbyers/netmiko#783]
Hi,

I am new to Python programming so excuse my lack of knowledge, but I am trying to create a basic python script which logs onto a Cisco device, checks the output from '#show interface status', and if any of the interfaces are shown as 'connected' then on interface Eth0/3, shut it down, otherwise disconnect from the device (I just wanted something visible to test to show it works). 

It looks as though the code works to an extent as the interface does shut down,, but i get an AttributeError: 'NoneType' object has no attribute 'sendall' on the following line:

"device.config_mode()"

The code I have used is as follows:
```
from netmiko import ConnectHandler


platform = 'cisco_ios'
host = '192.168.161.10'
username = 'cisco'
password = 'cisco'
device = ConnectHandler(device_type=platform, ip=host, username=username, password=password, secret=password)

device.enable()

output = device.send_command('show interface status')
output = output.strip().splitlines()
config_list = ['interface eth0/3', 'shutdown', 'end', 'wr mem']


for lines in output:
	words = lines.split()
	if 'connected' in lines:
		device.config_mode()
		device.send_config_set(config_list)
		output = device.send_config_set(config_list)
		print output
		device.disconnect()
	elif not lines:
		device.disconnect()
```

**Comment by ktbyers** [comment]
@adamfitzhugh Can you post your exception stack trace?

**Comment by adamfitzhugh** [comment]
Hi Kirk,

This is the exception I get. It seems to suggest that there's no data to collect from device.config_mode() but i'm not sure...


Traceback (most recent call last):
  File "/Users/<username>/Desktop/test", line 20, in <module>
    device.config_mode()
  File "build/bdist.macosx-10.6-intel/egg/netmiko/cisco_base_connection.py", line 42, in config_mode
  File "build/bdist.macosx-10.6-intel/egg/netmiko/base_connection.py", line 1206, in config_mode
  File "build/bdist.macosx-10.6-intel/egg/netmiko/cisco_base_connection.py", line 31, in check_config_mode
  File "build/bdist.macosx-10.6-intel/egg/netmiko/base_connection.py", line 1188, in check_config_mode
  File "build/bdist.macosx-10.6-intel/egg/netmiko/base_connection.py", line 290, in write_channel
  File "build/bdist.macosx-10.6-intel/egg/netmiko/base_connection.py", line 268, in _write_channel
AttributeError: 'NoneType' object has no attribute 'sendall'
[Finished in 32.2s with exit code 1]
[shell_cmd: python -u "/Users/<username>/Desktop/test"]
[dir: /Users/<username>/Desktop]
[path: /Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands]

**Comment by adamfitzhugh** [comment]
@ktbyers OK so I think I have 'half' worked out what happened here. 

After doing some testing, it turns out that the way i've coded it, it only looks for ONE entry of the word 'connected' from #show interface status. If there's more than one entry in the output of 'connected' then it throws up the error. I tested this theory and it worked.

Is there a way I can tweak the code to say "if there is 1 or more entries of the same word, then......"?

**Comment by ktbyers** [comment]
@adamfitzhugh You need to move your disconnect() call to be outside of your for loop. Something like:

```
# Netmiko will automatically exit config mode and you should
# execute 'wr mem' outside of send_config_set
config_list = ['interface eth0/3', 'shutdown']

for intf_line in output:
	if 'connected' in intf_line:
                # You don't need to enter config_mode manually send_config_set will
                # do this automatically
		output = device.send_config_set(config_list)
		print output
                # I am assuming that once you have shutdown eth0/3 you are done
                break        # exits for loop

device.disconnect()
```

**Comment by adamfitzhugh** [comment]
@ktbyers Thats great thanks mate. Only last thing is the else statement, so if 'connected' isn't in the output, then just do nothing, and disconnect from the device altogether.

Does this part of the statement work:

	elif not lines:
		device.disconnect()          #if 'connected' isn't in the output, then disconnect from the device.

**Comment by ktbyers** [comment]
@adamfitzhugh No, that `elif` statement will cause issues.

 You would want the disconnect() at the very end of your script (i.e. outside the for-loop).

Either you found 'connected', made your change, and want to disconnect. Or you didn't find 'connected' and want to disconnect.

You don't want to disconnect, however, while the for loop is still ongoing (as once you disconnect, your SSH session is no longer active, and you will get an error if you try to use the SSH session).


Kirk

**Comment by adamfitzhugh** [comment]
Hi @ktbyers it works perfectly now thank you. How would you apply this to multiple switches at the same time? I.e. i'd like to run the #show interfaces eth0/3 command, and then check on each switch if the interface is 'connected' then shut it down, otherwise move onto the next switch. The first part of the loop works, i.e. running #show interfaces eth0/3 and printing the output, it's just the configuration only sends to ALS-1. I have pasted my code below:




from netmiko import ConnectHandler

als_1 = {
	'device_type': 'cisco_ios',
	'ip': '192.168.161.15',
	'username': 'cisco',
	'password': 'cisco',
	'secret': 'cisco',
}

als_2 = {
	'device_type': 'cisco_ios',
	'ip': '192.168.161.20',
	'username': 'cisco',
	'password': 'cisco',
	'secret': 'cisco',
}

als_3 = {
	'device_type': 'cisco_ios',
	'ip': '192.168.161.30',
	'username': 'cisco',
	'password': 'cisco',
	'secret': 'cisco',
}

all_devices = [als_1, als_2, als_3]

config_list = ['interface eth0/3', 'shutdown']

for a_device in all_devices:
	device = ConnectHandler(**a_device)
	first_output = device.send_command('show interface eth0/3')
	split_output = first_output.strip().splitlines()
	print first_output
	for a_device_2 in all_devices:
		device = ConnectHandler(**a_device_2)
		if 'connected' in first_output:
			device.enable()
			output = device.send_config_set(config_list)
			device.send_command('wr mem')
			print output
			break

device.disconnect()
