### ISSUE TITLE
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

### ISSUE THREAD

**Issue by francisjes** [ktbyers/netmiko#784]
getting below error and logging output also shared below. it seems like able to successfully login to jumphost but its not going through after that.

uadmin@uadmin-virtual-machine:~/runbook$ python runbook.py device1.yml
logging to: health_check_2018_04_12_12_28_59.txt
connecting to jumphost: jumphost1
connecting to: device1
Traceback (most recent call last):
  File "runbook.py", line 271, in <module>
    do_runbook(string)
  File "runbook.py", line 223, in do_runbook
    vars=dispatch_function(key,vars)
  File "runbook.py", line 207, in dispatch_function
    vars=func(vars)
  File "runbook.py", line 109, in connectto
    vars.nc.read_until_pattern('assword:')
  File "/home/uadmin/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 467, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/uadmin/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 403, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
================================================================
debug file output

jumphost1>
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: ssh username@device1
DEBUG:netmiko:write_channel: 

DEBUG:netmiko:Pattern is: assword:
DEBUG:netmiko:_read_channel_expect read_data: ssh username@device1
DEBUG:netmiko:_read_channel_expect read_data: 

DEBUG:paramiko.transport:EOF in transport thread

**Comment by francisjes** [comment]
For other device, getting below debug logs
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: ssh username@device2

DEBUG:netmiko:Pattern is: assword:
DEBUG:netmiko:_read_channel_expect read_data: ssh username@device2

DEBUG:netmiko:_read_channel_expect read_data: jumphost1>
jumphost1>ssh
DEBUG:netmiko:_read_channel_expect read_data:  username@de
DEBUG:netmiko:_read_channel_expect read_data: vice2

DEBUG:netmiko:_read_channel_expect read_data: ssh: device2: node name or service name not known

DEBUG:netmiko:_read_channel_expect read_data: jumphost1>
DEBUG:paramiko.transport:EOF in transport thread

**Comment by ktbyers** [comment]
Your jumphost is saying it doesn't understand this command:

```
ssh username@device2
```

It doesn't know what `device2` (i.e. that is not resolving in DNS).

**Comment by ktbyers** [comment]
Just re-open if there is still an issue.
