### ISSUE TITLE
Send Config from file error for Ciena

### ISSUE THREAD

**Issue by Jajao555** [ktbyers/netmiko#785]
I have script that runs a "config search string" command and from that output parses out the ports I want and creates and file with the ports concatenated into new configuration commands to do the change I want. Getting the search output and parsing it and saving to a file all seem to work fine.

I'm getting an error when I try to use send_config_from_file saying failed to enter configuration mode. Ciena doesn't require you to enter config mode to do config changes there is a configuration prompt but it's only a hierarchy for changes to the "configuration" section if that makes sense. Also this is on 6.11 SAOS code so that may have changed they are up to 6.17 now.

Error I'm getting:
`(<type 'exceptions.ValueError'>, ValueError(u'Failed to enter configuration mode.',), <traceback object at 0x7fa7602836c8>)`

Parts of script:
```python
    port_list = ['port 1', 'port 2', 'port 3', 'port 4', 'port 1.20', 'port 1.21', 'port 1.23', 'port 1.3',]

    session = netmiko.ConnectHandler( device_type='ciena_saos', ip=node['ip'], username=username, password=password, global_delay_factor=1)

    try:
        output = session.find_prompt()
        output += session.send_command('config search string "virtual-switch ethernet add"')
        matches = {x for x in port_list if x in output}
        matches_list = list(matches)
        print(matches_list)
        parsing_file_name = './python_work/zlldp_' + node['name'] + '_' + node['ip'] + '.txt'
        print ('Writing output to file', parsing_file_name)
        with open(parsing_file_name,'w') as f:
            for item in matches_list:
                f.write('lldp set port ' + item + ' mode tx-rx notification off' + '\n')
        output += session.find_prompt()
        output += session.send_config_from_file(parsing_file_name)
        output += session.send_command('config save')
        session.disconnect()

```
Output:
```
20180412_10:17:08:976704 - Logged into Ciena LAB-5150-MES1.NMD - 172.x.x.x

['port 1.21', 'port 1.20', 'port 1.23', 'port 1']
('Writing output to file', './python_work/zlldp_LAB-5150-MES1.NMD_172.x.x.x.txt')
20180412_10:17:08:976704 - Unexpected error: LAB-5150-MES1.NMD - (<type 'exceptions.ValueError'>, ValueError(u'Failed to enter configuration mode.',), <traceback object at 0x7f697842b6c8>) 

Run Finished...

```

Commands I parse to get and read from the /python_work/zlldp_LAB-5150-MES1.NMD_172.x.x.x.txt' file:
```
lldp set port port 1.21 mode tx-rx notification off
lldp set port port 1.20 mode tx-rx notification off
lldp set port port 1.23 mode tx-rx notification off
```

**Comment by ktbyers** [comment]
@Jajao555 Can you show me what making these config changes look like in the CLI on this Ciena device?

i.e. just show me a reference CLI session.

**Comment by daanvdsanden** [comment]
I create Pull request #1088 that extends Saos support and fixes this bug

**Comment by Jajao555** [comment]
Thanks! I'll test it out.

**Comment by carlniger** [comment]
Going to close this and handle whatever else in #1088
