### ISSUE TITLE
How to connect ssh to devices

### ISSUE THREAD

**Issue by fixlensmith** [ktbyers/netmiko#786]
Hi, i've some device that unlisted in netmiko, like radware, mikrotik, nortel, and linux.

can i connect to that device using ssh? and apply the command? do you have example for that.. i tried using paramiko, but cannot get the output.
this is my script.

```
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('1.1.1.1', username = 'test', password='test123')
stdin, stdout, stderr = client.exec_command("ifconfig")
for line in stdout:
    print(line)
```

**Comment by ktbyers** [comment]
Linux is supported in Netmiko.

There is also a NAPALM mikrotik driver.

See this article for directly using Paramiko (I always use invoke_shell() in Netmiko)

https://pynet.twb-tech.com/blog/python/paramiko-ssh-part1.html
