### ISSUE TITLE
Issue installing netmiko

### ISSUE THREAD

**Issue by rahulgadre** [ktbyers/netmiko#788]
I have been trying to install netmiko on a Centos VM. However, I am getting the following error.
Could someone please help? Thanks in advance. 

Command used to install netmiko: pip install netmiko

Requirement already satisfied: netmiko in /usr/lib/python2.7/site-packages/netmiko-2.1.1-py2.7.egg
Requirement already satisfied: paramiko>=2.0.0 in /usr/lib/python2.7/site-packages (from netmiko)
Collecting scp>=0.10.0 (from netmiko)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Could not fetch URL https://pypi.python.org/simple/scp/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/scp/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)) - skipping
  Could not find a version that satisfies the requirement scp>=0.10.0 (from netmiko) (from versions: )
No matching distribution found for scp>=0.10.0 (from netmiko)

**Comment by ktbyers** [comment]
Which version of PIP are you using:

```
pip list | grep pip
pip (9.0.1)
```

It looks like it is possibly this issue.

https://github.com/pypa/pip/issues/3415

**Comment by rahulgadre** [comment]
pip (9.0.3)

**Comment by ktbyers** [comment]
What happens when you do:

```
pip install scp
```

**Comment by rahulgadre** [comment]
I came across the same issue after running pip install scp
 
pip install scp
Collecting scp
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)': /simple/scp/
  Could not fetch URL https://pypi.python.org/simple/scp/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/scp/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)) - skipping
  Could not find a version that satisfies the requirement scp (from versions: )
No matching distribution found for scp

**Comment by ktbyers** [comment]
@rahulgadre Did you try this fix referenced in the issue that I linked to:

```
My /etc/ssl/certs/ca-certificates.crt file was empty so I ran sudo update-ca-certificates which populated the ca-certificates.crt file and then everything started working.
```

**Comment by rahulgadre** [comment]
Yes, I did try to fix it using the same  reference but sudo update-ca-certificates is not working on my CentOS machine.  It says command not found after running the above command.  Also, looking on the internet to see if there's any fix.

**Comment by rahulgadre** [comment]
Here's the output:

update-ca-certificates
bash: update-ca-certificates: command not found...

These are the only commands starting with the word update:
update-alternatives      update-desktop-database  update-pciids
update-ca-trust          update-gtk-immodules     update-smart-drivedb
updatedb                 update-mime-database

I double checked to make sure if ca-certificates were installed and those are installed.

Package ca-certificates-2017.2.14-71.el7.noarch already installed and latest version
Nothing to do

**Comment by ktbyers** [comment]
@rahulgadre Yes, it looks like some sort of Centos, PIP, and PyPI issue (i.e. not a Netmiko issue).

What version of CentOs is this?

**Comment by rahulgadre** [comment]
CentOS 7.4

**Comment by ktbyers** [comment]
Yes, definitely doesn't look like a Netmiko issue. Looks like something pertaining to Centos and PIP/PYPI.


Kirk

**Comment by rahulgadre** [comment]
Thanks for your suggestion. I looked around and fixed that ssl issue. Now when I run pip install netmiko, I get this. Does it mean netmiko is installed?

 pip install netmiko
Requirement already satisfied (use --upgrade to upgrade): netmiko in /usr/lib/python2.7/site-packages/netmiko-2.1.1-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): paramiko>=2.0.0 in /usr/lib/python2.7/site-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): scp>=0.10.0 in /usr/lib/python2.7/site-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib64/python2.7/site-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): pyserial in /usr/lib/python2.7/site-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): textfsm in /usr/lib/python2.7/site-packages (from netmiko)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.1 in /usr/lib64/python2.7/site-packages (from paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/lib64/python2.7/site-packages (from cryptography>=1.1->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko>=2.0.0->netmiko)
Cleaning up...

**Comment by ktbyers** [comment]
Yes, you should be good.

Do you have a link to the fix (in case someone sees this issue in search results)?

**Comment by rahulgadre** [comment]
Thanks for your quick feedback. In my case, the issue was with the pip version. Since it was a higher version of pip, it was doing ssl checks. Also, update-ca-certificates didn't work in my case. Therefore, I uninstalled pip and reinstalled a lower version using the alternate method mentioned in the link below.
https://pip.readthedocs.io/en/1.2.1/installing.html

**Comment by rahulgadre** [comment]
I am now up and running with Netmiko. I managed to run a few basic commands on some of our networking devices and those worked fine. I have a quick question though. Is there any documentation or example which would show how Netmiko works with Ansible on Avaya networking devices?

**Comment by dominicfillmore** [comment]
For anyone else that comes across this problem, my issue was that my ubuntu VM wasn't picking up time from my host and so was 8 hours behind which was causing this to fail. Set the timezone manually in Ubuntu which fixed the PIP SSL problem
