### ISSUE TITLE
Checking Cisco Uplink Redundancy

### ISSUE THREAD

**Issue by BigPat** [ktbyers/netmiko#789]
This is not necessarily an issue but I am trying to build a script that will login to a device, do a "show cdp neighbor" and determine if a device has dual connections to two different devices above.  I am trying to utilize netmiko with xlsxwriter for the output and build logic to determine fails due to the massive lists of hosts I have (in the thousands).  I am trying to make sure they all have uplink redundancy and that each uplink is on a different module or switch in the device.

Example: Access-SW-A connects to core-sw-A from interface gi1/0/1 and connects to core-sw-B from interface gi1/1/1.

**Comment by ktbyers** [comment]
@BigPat I am not sure what your question is?

**Comment by denialmx** [comment]
@BigPat I do not believe this is a netmiko issue at all, but more something you would like to build using netmiko. Do you have a sample script to look at? is this failing you somewhere?

**Comment by BigPat** [comment]
This was old looking more for suggestions. I’ll close it out.
