### ISSUE TITLE
cisco_ios_telnet usage for d-link  switch  DES-3010G/DES-3028

### ISSUE THREAD

**Issue by ya-zero** [ktbyers/netmiko#790]
host='192.168.0.10'
tel=telnetlib.Telnet(host)
tel.set_debuglevel(1)
print ('user:',tel.read_very_eager())
tel.read_until(b'UserName:',timeout=1)
tel.write(b'admin'+b'\r\n')
print ('pass',tel.read_very_eager())
tel.read_until(b'PassWord:',timeout=1)
tel.write(b'rekom'+b'\r\n')
tel.write(b'sh switch'+b'\n')
time.sleep(1)
parse_sw=tel.read_very_eager()

-------------------------------------
 python ./telnet_connect_1.py
Telnet(192.168.0.10,23): recv b'\xff\xfd\x03\xff\xfb\x03\xff\xfb\x01\x1b[0m\x1b[1;1H\x1b[2J\rD\r \n\r '
Telnet(192.168.0.10,23): IAC DO 3
Telnet(192.168.0.10,23): IAC WILL 3
Telnet(192.168.0.10,23): IAC WILL 1
Telnet(192.168.0.10,23): recv b' DES-3010G Fast Ethernet Switch Command Line Inte'
Telnet(192.168.0.10,23): recv b'rface\n\r\n\r Firmware: Bui'
Telnet(192.168.0.10,23): recv b'ld 4.20.B27\n\r Copyright(C) 2007 D-Link C'
Telnet(192.168.0.10,23): recv b'orporation. All rights reserved.\n\rUserName:'
user: b'\x1b[0m\x1b[1;1H\x1b[2J\rD\r \n\r DES-3010G Fast Ethernet Switch Command Line Interface\n\r\n\r Firmware: Build 4.20.B27\n\r Copyright(C) 2007 D-Link Corporation. All rights reserved.\n\rUserName:'
Telnet(192.168.0.10,23): recv b'\xff\xfe\x03'
Telnet(192.168.0.10,23): IAC DONT 3
Telnet(192.168.0.10,23): recv b'\xff\xfc\x03'
Telnet(192.168.0.10,23): IAC WONT 3
Telnet(192.168.0.10,23): recv b'\xff\xfc\x01'
Telnet(192.168.0.10,23): IAC WONT 1
Telnet(192.168.0.10,23): send b'admin\r\n'pass b''
Telnet(192.168.0.10,23): recv b'a'
Telnet(192.168.0.10,23): recv b'dmin\n\rPassWord:'
Telnet(192.168.0.10,23): send b'rekom\r\n'
Telnet(192.168.0.10,23): send b'sh switch\n'
Telnet(192.168.0.10,23): recv b'*********\n\r\n\rDES-3010G:4#sh switch\n\rCommand: show '
Telnet(192.168.0.10,23): recv b'switch\n\r\n\rDevice Type : DES-3010G Fast Ethe'
Telnet(192.168.0.10,23): recv b'rnet Switch\n\rMAC Address : 00-22-B0-63-43-3'
Telnet(192.168.0.10,23): recv b'0\n\rIP Address : 192.168.0.10 (Manual)\n\rVLA'
Telnet(192.168.0.10,23): recv b'N Name : vlan2\n\rSubnet Mask : 255.'
Telnet(192.168.0.10,23): recv b'255.255.0\n\rDefault Gateway : 192.168.0.254\n\rBoo'
Telnet(192.168.0.10,23): recv b't PROM Version : Build 1.01.009\n\rFirmware Version'
Telnet(192.168.0.10,23): recv b' : Build 4.20.B27\n\rHardware Version : A3\n\rSyst'
Telnet(192.168.0.10,23): recv b'em Name : \n\rSystem Location : \n\rSystem C'
Telnet(192.168.0.10,23): recv b'ontact : \n\rSpanning Tree : Disabled\n\rLoop'
Telnet(192.168.0.10,23): recv b'Back Detection : Enabled\n\rIGMP Snooping : Ena'
Telnet(192.168.0.10,23): recv b'bled\n\rVLAN trunk : Disabled\n\r802.1X '
Telnet(192.168.0.10,23): recv b' : Disabled\n\rTELNET : Enabled(TCP'
Telnet(192.168.0.10,23): recv b' 23)\n\rWEB : Enabled(TCP 80)\n\rRMON'
Telnet(192.168.0.10,23): recv b' : Disabled\n\rSSH : Di'
Telnet(192.168.0.10,23): recv b'sabled\n\rPassword Encryption: Enabled\n\r\n\rDES-3010G:'
Telnet(192.168.0.10,23): recv b'4#'
----result----
['Device Type ', ' DES-3010G Fast Ethernet Switch']
['MAC Address ', ' 00-22-B0-63-43-30']
['IP Address ', ' 192.168.0.10 (Manual)']
['VLAN Name ', ' vlan2']
['Boot PROM Version ', ' Build 1.01.009']

------------------------------------------------------------

try netmiko     + logging

DES-3010G Fast Ethernet Switch Command Line Interface
                            Firmware: Build 4.20.B27
           Copyright(C) 2007 D-Link Corporation. All rights reserved.

UserName:
DEBUG:netmiko:write_channel: b'admin\r\n'
DEBUG:netmiko:read_channel: admin

PassWord:
DEBUG:netmiko:write_channel: b'rekom\r\n'
DEBUG:netmiko:read_channel: **********

Fail!

UserName:
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:

PassWord:
DEBUG:netmiko:write_channel: b'rekom\r\n'
DEBUG:netmiko:read_channel: *********

**Comment by ktbyers** [comment]
Is there a question here? 

There is no DLink-telnet or SSH support. You are welcome to create a driver, but it currently doesn't exist.

**Comment by ya-zero** [comment]
more models vendor d-link  support netmiko 
DES 1210-28/ME
DES 1228/ME
DES 3200-10
DES 3200-26
DES 3200-28
DES 3200-52

what's step to create driver ?

**Comment by ya-zero** [comment]
i'm add in  cisco_base_connection  
      def telnet_login (   
       username_patter   add " |:"  )
result true

**Comment by ktbyers** [comment]
@ya-zero General process for creating a driver is detailed here;

https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md


Kirk

**Comment by carlniger** [comment]
Going to close this. If you'd like to contribute a driver please open a PR following the link above!
