### ISSUE TITLE
Netmiko device type (cisco_ios, paloalto_panos etc) doesn't work?

### ISSUE THREAD

**Issue by cansripuv1976** [ktbyers/netmiko#791]
I am not sure if someone else has already figured it out...but i found today that the netmiko device type doesn't seem to work correctly...For instance, i use the device_type as paloalto_panos and create a ConnectHandler instance connecting to a Cisco Nexus 9K switch. It deosn't fail rather it connects and also gives me the "#" prompt. But it doesn't allow me to enter config mode which makes sense. However, should it even allow the ConnectHandler instance to succeed in the first place? is it not something misleading?

**Comment by ktbyers** [comment]
@cansripuv1976 Yes, you need to make sure your device_type is correct. It won't correct this for you.

And since a lot of platforms are very Cisco-IOS like, it might sort of work (until it doesn't).

Regards, Kirk
