### ISSUE TITLE
huawei_ssh // lack of connection information

### ISSUE THREAD

**Issue by akarakul** [ktbyers/netmiko#792]
Hello, 
Thanks for the amazing API.
I've a little issue I am experiencing. I'm currently using your huawei_ssh.py class, But I've found that it's missing a connection to a huawei device.

What I'm saying is, I'm trying to establish a connection to a huawei device via only using your "huawei_ssh.py" class.

P.S:
The reason why I'm failing to do this project on my own is: Whenever I try to use "net_connect.send_command("system-view")" while connected to a huawei system, I'm receiving "prompt failure".

**Comment by akarakul** [comment]
huawei = {'device_type': 'huawei','ip': ip_addr,'username': 'gece_altan',    'password': 'Qq1122!', #password,
    'port': 22,    'ssh_config_file': '~/.ssh/config',    'verbose': False,}

net_connect = ConnectHandler(**huawei)
net_connect.find_prompt() + "screen-length 0 temporary"
print(net_connect.find_prompt() + 'dis int br')
output = net_connect.send_command('dis int br')
print(output)
print(net_connect.find_prompt() + 'system-view')
output = net_connect.send_command('system-view')
print(output)
print(net_connect.find_prompt() + 'interface Eth-Trunk1')
output = net_connect.send_command('interface Eth-Trunk1')
print(output)

console output
----------------
Tunnel0/0/56                up    up           0%     0%          0          0
Tunnel0/0/57                up    up           0%     0%          0          0
Tunnel0/0/58                up    up           0%     0%          0          0
Tunnel0/0/61                up    up           0%     0%          0          0
Tunnel0/0/62                up    up           0%     0%          0          0
Virtual-Template0           up    up(s)        0%     0%          0          0
<Huawei-Router-1>system-view
Traceback (most recent call last):
  File "C:\Users\Documents\Eclipse Neon\SSH\ssh.py", line 116, in <module>
    output = net_connect.send_command('system-view')
  File "C:\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 1051, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: \<Huawei\-Router\-1\>

**Comment by ktbyers** [comment]
@akarakul Use `send_config_set()` method with a list of configuration changes instead of trying to manually send `system-view` via `send_command`.

Just re-open if you still have an issue.
