### ISSUE TITLE
On Arista when using pipe json

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#793]
```
show ip arp | json
```

The output doesn't always have a newline between the end of the JSON and the router prompt. This causes the strip_prompt to strip the entire output.

Library would return a blank string from the output.

It looks like the behavior is OS version dependent.

**Comment by carlniger** [comment]
@ktbyers know if this is still an issue or what version it is/was an issue on? Tested against our EOS boxes and works as it should. We are currently running: 4.20.10M.

**Comment by carlniger** [comment]
Haven't seen this crop up lately per @ktbyers  -- so we'll deal w/ it if it comes back up :)
