### ISSUE TITLE
Connection timed-out vs connection refused

### ISSUE THREAD

**Issue by tjhannin** [ktbyers/netmiko#795]
Hi,

Not sure if this is a known issue, but it looks like netmiko doesn't differentiate between a real time-out (ie no response) and connection refused, which can make the NetMikoTimeoutException message thrown from establish_connection when it gets a socket.error a bit misleading.

I poked around a bit more, and it seems part of the issue is that paramiko mangles the exceptions so netmiko can't see the actual error codes, but wondering if either the wording on the error message should be changed, or if netmiko should try to find "timed out" from the socket.error to see if the exception was caused by an actual timeout, or if the connection failed for some other reason?

thanks

**Comment by ktbyers** [comment]
@tjhannin Feel free to submit a PR on it.

**Comment by Alan-R** [comment]
I'll submit a PR for this in a few minutes - including specific Python3 support while maintaining Python2 compatibility.

**Comment by Alan-R** [comment]
There is now a clear, clean, Pythonic MR to fix this behavior, which works well in Py2 and Py3.

**Comment by ktbyers** [comment]
@Alan-R Yes, we haven't forgotten about this--just haven't got to it yet.


Regards, Kirk

**Comment by Alan-R** [comment]
Didn't mean this as criticism. This was more for the original poster than you. I also have a driver for the Casa CMTS I've written. Should be sending it along as soon as we have it in production here (probably a few weeks).

**Comment by ktbyers** [comment]
@Alan-R No worries.  Regards, Kirk
