### ISSUE TITLE
cant run tftp backup iosxr

### ISSUE THREAD

**Issue by seshuchkv** [ktbyers/netmiko#796]
Trying to run backup and XR is expecting i have given expect_string.

checkbackup = [net_connect.send_command_expect("copy running-config tftp:", expect_string='Host name or IP address (control-c to abort): []?'),
                        net_connect.send_command_expect("x.x.x.x", expect_string='Destination file name (control-c to abort): [running-config]?'),
                         net_connect.send_command_expect("/backup/asr9k-b_Running-Config_2018-04-19")]

ERROR:
File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 1069, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "C:\Python27\lib\site-packages\netmiko\base_connection.py", line 1044, in send_command
    if re.search(search_pattern, output):
  File "C:\Python27\lib\re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "C:\Python27\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
error: unexpected end of regular expression

**Comment by ktbyers** [comment]
@seshuchkv This is a regular expression pattern:

```
expect_string='Host name or IP address (control-c to abort): []?'
```

So things like the parenthesis, square bracket, and question mark will have special meaning. You will probably be better of doing something like:

```
expect_string=r'to abort'
```
