### ISSUE TITLE
ValueError: Failed to enter configuration mode

### ISSUE THREAD

**Issue by rahulgadre** [ktbyers/netmiko#797]
Hello Kirk,

I have been trying to run some commands on Avaya networking devices.  Here's the code that I have been using to access a remote device.

#!/usr/bin/env python
from netmiko import ConnectHandler

sw_11 = {
    'device_type': 'avaya_vsp',
    'ip': '1.2.3.4',
    'username': 'uname',
    'password': 'pass'
}

with open('config') as f:
    lines = f.read().splitlines()
print lines

all_devices = [sw_11]

for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    output = net_connect.send_config_set(lines)
    print output

config.close()

After running the above python file, I get the following error:

['show vlan members']  ------ This is the only line in the config file which is being read in the above python code.
Traceback (most recent call last):
  File "conf.py", line 24, in <module>
    output = net_connect.send_config_set(lines)
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 1292, in send_config_set
  File "build/bdist.linux-x86_64/egg/netmiko/cisco_base_connection.py", line 42, in config_mode
  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 1210, in config_mode
ValueError: Failed to enter configuration mode.

I added the following lines after referring to similar issues like this. Now the top part of the python file looks like this: 
#!/usr/bin/env python

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

from netmiko import ConnectHandler
(followed by the same code written above) 

Would you please tell me what's wrong? Also, have I added the debug code correctly? 

Respectfully,
Rahul

**Comment by rahulgadre** [comment]
Forgot to add that I get the same error after adding the below lines:

import logging
logging.basicConfig(filename='test.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

**Comment by rahulgadre** [comment]
@cgruelle Thanks for your feedback. 😃   
 The code worked fine after adding that line.

**Comment by rohitgarg1402** [comment]
@cgruelle , Worked on arista device as well. Thanks!!

**Comment by sliddjur** [comment]
Worked on EdgeSwitch aswell @cgruelle 
HOwever, looking at the output of send_config_set(lines), it exists the config-mode.

And the second time I dont need to do the net_connect.enable(), why is that?

**Comment by ktbyers** [comment]
@sliddjur Netmiko automatically enters/exits config mode for `send_config_set`, but it does not automatically enter/exit enable mode.

**Comment by sliddjur** [comment]
```
In [13]: set_domain = net_connect.send_config_set(set_domainname)

In [14]: print(set_domain)
configure

(UBNT EdgeSwitch) (Config)#domain-name my.domain

(UBNT EdgeSwitch) (Config)#exit

(UBNT EdgeSwitch) #
```

Looks like it exists enable mode to me?
