### ISSUE TITLE
Move pyyaml to tests_require and extras_require

### ISSUE THREAD

**Issue by KalleDK** [ktbyers/netmiko#799]
As i see yaml is only used in tests and only imported in utilities load_yaml_file - which is not used anywhere.

https://github.com/ktbyers/netmiko/search?q=yaml

**Comment by ktbyers** [comment]
It is used in load_devices function (in utilities.py) which is used by netmiko_tools.

**Comment by KalleDK** [comment]
I missed that - though load_devices is not used anywhere then ;) Again I would fell this is an extra - not essential for the packet to be used :)

**Comment by KalleDK** [comment]
Then change the requirements there to :)

`netmiko[yaml]>=1.0.0`

As I understand netmiko_tools is not needed for netmiko usage ?

**Comment by ktbyers** [comment]
Is there some reason it matters significantly?

netmiko_tools isn't installed via pypi so I expect not auto installing pyyaml with Netmiko will cause issues for end-users.

Realistically I should probably move netmiko_tools to be integrated directly into Netmiko and install them as part of netmiko, but I probably am not going to do this (as it just isn't a high enough priority).

**Comment by ktbyers** [comment]
Okay, you convinced me...please submit a PR on it.


Kirk

**Comment by carlniger** [comment]
Closing, see #1289
