### ISSUE TITLE
Add a rollback mechanism for IOS-XR

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#8]

**Comment by ktbyers** [comment]
Need a way to rollback a change
IOS-XR
Juniper

**Comment by ktbyers** [comment]
Another solutions is to just use send_command and manually send the command to do the rollback

**Comment by supertylerc** [comment]
It seems that it would be trivial to create a `rollback()` method that just invokes `send_command()` to roll the change back.

**Comment by ktbyers** [comment]
Referencing from #60 (design spec for commit/confirm/rollback).
