### ISSUE TITLE
Checkpoint device_type ?

### ISSUE THREAD

**Issue by irom77** [ktbyers/netmiko#80]
What about adding checkpoint device_type. I can test on : 
1.CP 1100
2.Edge UTM-1
3. VSX

**Comment by ktbyers** [comment]
@irom77 Can you provide a capture of an SSH session from one of these checkpoint devices including the logging in process (I don't need to see your username/password just the prompts that Checkpoint uses). 

Also execute one 'show' command on the device.

**Comment by irom77** [comment]
Sure , see attached. I gave three examples. First one from legacy Edge UTM-1 which is not Linux based
The other two examples are Checkpoint Gaia appliances , small CP1100 and large VSX. Practically same thing for ssh. Both have two options:1. ssh as clish user and then switch to expert mode with 'expert' (in fact both are de facto write modes;)2. ssh as bash user and go directly to bash 
I think you can refer to these examples as 'Checkpoint Edge', and then just 'Checkpoint Gaia' Let me know if you have questions. I will look for older Checkpoint SPLAT (SecurePlatform, predecessor of  Checkpoint Gaia), it's also Linux based
Thnx      From: Kirk Byers <notifications@github.com>
 To: ktbyers/netmiko <netmiko@noreply.github.com> 
Cc: Irek Romaniuk <irek.romaniuk@gmail.com> 
 Sent: Tuesday, March 17, 2015 7:29 PM
 Subject: Re: [netmiko] Checkpoint device_type ? (#80)
   
@irom77 Can you provide a capture of an SSH session from one of these checkpoint devices including the logging in process (I don't need to see your username/password just the prompts that Checkpoint uses). Also execute one 'show' command on the device.—
Reply to this email directly or view it on GitHub.   

  

###1. UTM-1 Edge 
[me@nms02 ~]$ ssh -l admin a.b.c.d
admin@a.b.c.d's password: 
Welcome to EdgeW, 32 nodes 8.1.37x 00:08:da:73:8b:5e
YYY >info device
[700000] Device Information for YYY:

Hardware:
    Appliance Type:  SBox-200
    Version:         1.2G
General:
    Name:            YYY
    Uptime:          14 days, 21:41:08
    CPU Usage:       26%
    Flash Usage:     14%
License:
    Product Name:    EdgeW, 32 nodes
Firmware:
    Running:         8.1.37x
    Primary:         8.1.37x
    Backup:          8.0.39x
    Bootcode:        37
    Debug Firmware:  No
Total Memory:
    Main:            50MB
Free Memory:
    User:            779K
    Kernel:          1393K
    Firewall:        231K
VStream Database:
    Main:            Not installed
    Daily:           Not installed


YYY >quitReceived disconnect from a.b.c.d: 11: Logged out.

###2. CP1100, VSX (all newer, Linux/Gaia based appliances)

##a. with bash shell
[me@nms02 ~]$ ssh -l admin 1.2.3.4
admin@1.2.3.4's password: 

[Expert@MyCP1100]# cat /etc/passwd | grep admin
admin:x:0:0:Linux User,,,:/:/bin/bash

[Expert@MyCP1100]# clish -c 'show software-version'
This is Check Point 1100 Appliance R75.20.60 - Build 984
[Expert@MyCP1100]# exit
logout
Connection to 1.2.3.4 closed.

##b. with clish shell
[me@nms02 ~]$ ssh -l admin 10.196.123.1
admin@10.196.123.1's password: 
A001C7F26CF2A> expert
Enter expert password: 

You are in expert mode now.

[Expert@A001C7F26CF2A]# cat /etc/passwd | grep admin
admin:x:0:0:Linux User,,,:/:/bin/clish

##c. another example with clish (VSX)
[me@nms02 ~]$ ssh -l admin x.y.z.v
This system is for authorized use only.
admin@x.y.z.v's password: 
Product version Check Point Gaia R77.20 
Permission denied, please try again.
admin@x.y.z.v's password: 
Last login: Wed Mar 18 06:01:12 2015 from nms02.xxx.com

VSX-1:0> show version product
Product version Check Point Gaia R77.20 
VSX-1:0> expert
Enter expert password:

Warning! All configuration should be done through clish
You are in expert mode now.
 
[Expert@VSX-1:0]#

**Comment by ktbyers** [comment]
@irom77 

I am going to close this issue.

I would need access to the platform so that I can add in the support (or someone with access to the platform to add in the support and to submit a PR).

**Comment by nrm21** [comment]
Sorry I know this issue has been closed for over a year but just commenting for the benefit of anyone who googles this (like I did).

Netmiko can connect to Checkpoint Gaia r77.30 just fine if you:
Make sure the account you're logging in with is set to go directly to bash (expert mode) in the config
Make sure you are using  'device_type': 'linux'
