### ISSUE TITLE
Netmiko with python3.. "ImportError: No module named 'netmiko' "

### ISSUE THREAD

**Issue by lmazsar** [ktbyers/netmiko#805]
Hi,

Would like to understand what is the proper way to install netmiko to be used together with python3.
Got no issues when using with python version 2.7.

When trying to run a script that contains netmiko import, I face an error when running the script as python v3.

Example:

root@NetworkAutomation-1:~# more test.py
import sys
import threading
from netmiko import ConnectHandler
from getpass import getpass
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import NetMikoAuthenticationException

No problem with v2 >>
root@NetworkAutomation-1:~# python test.py

This is when running with v3 >>

root@NetworkAutomation-1:~# python3 test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from netmiko import ConnectHandler
ImportError: No module named 'netmiko'

Netmiko is installed.
Python v2 and v3 also..

It seems the "pip install netmiko" places relevant packeges in folder "python2.7" which may be the reason that I am not able to run it with v3.

root@NetworkAutomation-1:~# pip install netmiko
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: netmiko in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: paramiko>=1.13.0 in /usr/local/lib/python2.7/dist-packages (from netmiko)
Requirement already satisfied: scp>=0.10.0 in /usr/local/lib/python2.7/dist-packages (from netmiko)
Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages (from netmiko)

root@NetworkAutomation-1:~# python --version
Python 2.7.12

root@NetworkAutomation-1:~# python3 --version
Python 3.5.2

I am using GNS3's "network automation appliance" as test environment for my scripts. But have the exact same issue on my local PC I am using, which is why may not be gns3/docker related..
Rather my incorrect way of installing netmiko.

thanks for your help

**Comment by lmazsar** [comment]
I was seriously doing some search on google prior submitting this question, but as Murphy's law I got to find the proper installation commands after posting my questions here.. :S

After these two I am able to use netmiko with v3

python3 -m pip install netmiko
apt-get install python3-pip -y

**Comment by ktbyers** [comment]
@lmazsar No worries. 

You might also want to look into Python virtual environments (if you are not using them).
