### ISSUE TITLE
Netmiko Telnet login failed issue

### ISSUE THREAD

**Issue by Phxntxm** [ktbyers/netmiko#807]
I'm hitting an issue with some specific devices, where it seems to be hitting an error as it logs in....the logs are here:
```


CMS username: 
DEBUG:netmiko:write_channel: b'********\r\n'
DEBUG:netmiko:read_channel: ********
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
CMS password: 

Enter old password: 
DEBUG:netmiko:write_channel: b'*******\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:write_channel: b'\r\n'
DEBUG:netmiko:read_channel:
```
I tested this a bit manually, and I believe the issue is all the carriage returns between the username and password; if I hit enter twice after entering the username (when testing manually) it will hit exactly what Netmiko hit here, and start changing the password instead of trying to enter the password.

**Comment by ktbyers** [comment]
@Phxntxm What type of device is it?

Why is it doing this?

```
CMS password: 

Enter old password: 
```

**Comment by Phxntxm** [comment]
It's a cisco IOS device, the only one as far as I'm aware that has telnet support right now.

As for the second question that's kind of the issue, the only thing I can think of is what I explained in the original post. If I enter the username, and hit enter twice, it brings up the changing password prompt....which I think is what Netmiko is simulating. If I just hit enter once after entering the username, it just asks for the password like normal. In the same regard if I hit enter once after entering the username, am on the password prompt, then hit enter without typing anything, it will ask for the "Enter old password" prompt.

**Comment by ktbyers** [comment]
Can you post 'show version' output from the device?

Can you post what a normal telnet login to that device looks like (including the username/password handling)? You can obfuscate the password in your post here.

**Comment by ktbyers** [comment]
FYI, there is Netmiko telnet support for some other platforms (this is in ssh_dispatcher.py):

```

# Add telnet drivers
CLASS_MAPPER['brocade_fastiron_telnet'] = RuckusFastironTelnet
CLASS_MAPPER['brocade_netiron_telnet'] = BrocadeNetironTelnet
CLASS_MAPPER['cisco_ios_telnet'] = CiscoIosTelnet
CLASS_MAPPER['arista_eos_telnet'] = AristaTelnet
CLASS_MAPPER['juniper_junos_telnet'] = JuniperTelnet
CLASS_MAPPER['calix_b6_telnet'] = CalixB6Telnet
CLASS_MAPPER['dell_powerconnect_telnet'] = DellPowerConnectTelnet
CLASS_MAPPER['generic_termserver_telnet'] = TerminalServerTelnet
CLASS_MAPPER['extreme_telnet'] = ExtremeTelnet
CLASS_MAPPER['ruckus_fastiron_telnet'] = RuckusFastironTelnet
```
