### ISSUE TITLE
Valid ntc-templates not found, even it's checked out (Clone) in PyCharm

### ISSUE THREAD

**Issue by chesean** [ktbyers/netmiko#812]
Hi,
I tried to get the following code running in PyCharm 2018 latest version on MAC. netmiko is running fine but can't use use_textfsm from ntc-templates as PyCharm is complaining it can't find ntc-templates. 

# ConnectHandler
from netmiko import Netmiko
from getpass import getpass

my_device = {
    'host':'10.10.151.122',
    'username':'admin',
    'password': getpass(),
    'device_type': 'cisco_nxos',
}

net_connect = Netmiko(**my_device)

output = net_connect.send_command("show cdp neighbors", use_textfsm=True)
print(output)

net_connect.disconnect()

ValueError: 
Valid ntc-templates not found, please install https://github.com/networktocode/ntc-templates
and then set the NET_TEXTFSM environment variable to point to the ./ntc-templates/templates
directory.

I did set NET_TEXTFSM in Python Console-->Environment variables: 
NET_TEXTFSM=/Users/ABC/Sites/project2/ntc-templates/templates

Any help is much appreciated!

**Comment by ktbyers** [comment]
@chesean Can you test it outside of PyCharm and see if it works (i.e. execute `python` from the MacOs terminal after you set the NET_TEXTFSM environment variable)?

You could also test it inside of PyCharm by looking at the environment variables that exist from a Python perspective.

```
$ export NET_TEXTFSM=/Users/ABC/Sites/project2/ntc-templates/templates
Kirks-MacBook-Pro-2:~ ktbyers$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['NET_TEXTFSM']
'/Users/ABC/Sites/project2/ntc-templates/templates'
```

**Comment by chesean** [comment]
Hi Kirk,

I finally get it working by modifying utilities.py in netmiko package. See my modification with utilities.py below.

If I use original template_dir = os.environ[‘NET_TEXTFSM’] and I set Python console environment variables: NET_TEXTFSM =/Users/ABC/Sites/project2/ntc-templates/templates, by debugging, I see template_dir becomes "/Users/ABC/Sites/project2/ntc-templates/templates /templates’, so there’s one extra space there and one templates (red) there. To fix that, I use str.strip(os.environ[‘NET_TEXTFSM’]) to remove the extra space in the end, and set environment variables to be 'NET_TEXTFSM=/Users/Sean/Sites/project2/ntc-templates’. 

After these changes, the ‘template_dir’ becomes "/Users/ABC/Sites/project2/ntc-templates/templates” which reflect the correct directory of ntc-template location.

def get_template_dir():
    """Find and return the ntc-templates/templates dir."""
    try:
        template_dir = str.strip(os.environ['NET_TEXTFSM’]) <—— My new code
        #template_dir = os.environ['NET_TEXTFSM’]<—— Original code
        index = os.path.join(template_dir, 'index')

        if not os.path.isfile(index):
            # Assume only base ./ntc-templates specified
            template_dir = os.path.join(template_dir, 'templates')
    except KeyError:
        # Construct path ~/ntc-templates/templates
        home_dir = os.path.expanduser("~")
        template_dir = os.path.join(home_dir, 'ntc-templates', 'templates')

    index = os.path.join(template_dir, 'index')
    
    if not os.path.isdir(template_dir) or not os.path.isfile(index):
        msg = """
Valid ntc-templates not found, please install https://github.com/networktocode/ntc-templates
and then set the NET_TEXTFSM environment variable to point to the ./ntc-templates/templates
directory."""

Not sure if this is best solution. but it works fine so far.

Thanks,
Sean

**Comment by chesean** [comment]
Issue was fixed by modifying template_dir variable in utilities.py which is from netmiko package.
