### ISSUE TITLE
Installing and running nekmiko with Python 3.6 and Windows or MAC

### ISSUE THREAD

**Issue by programpee** [ktbyers/netmiko#817]
I am unable to get Netmiko working on 2 platforms and have tried a few methods with the same error across the board. 
Am I using the wrong version on Python or have I missed a trick? I feel like I have missed some fundamentals of setting this up. 

Tried

Windows Build
>>> netmiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'netmiko' is not defined

Pycharm Console Environment (on Windows) Python 3.6
Project Interprter Installed netmiko/paramiko/pip
>>>netmiko
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'netmiko' is not defined

MAC
>>>netmiko
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'netmiko' is not defined

$pip install netmiko

Requirement already satisfied: netmiko in /Li........

**Comment by jcrotts** [comment]
Make sure you are importing netmiko at the top of your file/REPL session.
`import netmiko`

**Comment by doncrea** [comment]
sudo pip3 install -U netmiko for fedora

**Comment by ktbyers** [comment]
@programpee Are you still having an issue? 

I am going to close, but if you still have an issue, you can re-open.
