### ISSUE TITLE
Support for ssh parameter BindAddress

### ISSUE THREAD

**Issue by Wallpix** [ktbyers/netmiko#818]
Would it be possible to add support for the 'BindAddress' client option for SSH?  We have management consoles with multiple interfaces and we need to specify which 'source ip address' for the ssh session with the 'BindAddress' statement.  Even though paramiko/netmiko supports user ssh config files, the code does not seem to handle the 'BindAddress' statements.  Ref; https://www.ssh.com/ssh/config/#sec-Listing-of-client-configuration-options

This is already documented on https://github.com/paramiko/paramiko/issues/206

**Comment by Wallpix** [comment]
You are absolutely right.  I found that 'paramiko' issue afterward.  But that issue has been opened since 2013!  Doesn't look like it's getting any traction.

**Comment by ktbyers** [comment]
I am going to close as it doesn't look like there is a further action for me to do on it.
