### ISSUE TITLE
IOError: Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by CharlesZuo01** [ktbyers/netmiko#821]
Hi,

I apologize in advance if I could've found the answer to this elsewhere, but I've exhausted Google and reddit and couldn't find an answer so I thought I would ask here.

I'm trying to delete files from flash from a catalyst 3850 running 3.6.5.  

Here's the issue:

```
>>> net_connect = ConnectHandler(device_type=device_platform, ip=current_device, username=un, password=password)
>>> output = net_connect.send_command('delete flash:cat3k_caa-base.SPA.03.03.02SE.pkg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/czuo/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 1051, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: DEVICE\HOST\NAME\#
```

I tried increasing the delay_value and max_loops, but I got this error instead:

`IOError: Search pattern never detected in send_command_expect: Delete\ flash\:\/cat3k\_caa\-base\.SPA\.03\.03\.02SE\.pkg\?\ \[confirm\]`

How do I resolve this issue?

Thanks

**Comment by ktbyers** [comment]
@CharlesZuo01 The problem is that the above IOS command prompts you to confirm (i.e. the router prompt is not returned which is what Netmiko is expecting).

Here is one solution to that problem:

https://github.com/ktbyers/netmiko/blob/develop/examples/handle_prompts/handle_prompts.py


Kirk

**Comment by CharlesZuo01** [comment]
@ktbyers 

Thank you!  This solved my problem!

**Comment by sajangml** [comment]
@ktbyers  Hi  The link you have provided as the solution of this problem is not available. Can you post the solution as a comment here?

**Comment by ktbyers** [comment]
https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-timing

And

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#handling-commands-that-prompt-expect_string

**Comment by sajangml** [comment]
@ktbyers Thanks this resolved my issue :)

**Comment by AbdelnasserMostafa** [comment]
Chnge "net_connect.send_config" to "net_connect.send_config_set"
That worked for me.
