### ISSUE TITLE
ImportError: cannot import name ConnectHandler

### ISSUE THREAD

**Issue by jomaralexis41** [ktbyers/netmiko#822]
Hi,
 
  I am having problem with this below.
I am trying to figure out why cannot import the ConnectHandler.
Can you help me on this please?

  from netmiko import ConnectHandler
ImportError: cannot import name ConnectHandler 

##THIS IS THE BASIC CONFIG
root@Ubuntu-1:~# cat netmiko1.py 
from netmiko import ConnectHandler

cisco_router = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.200',
    'username': 'jomar',
    'password': 'jomar',
    'secret': 'jomar',
}

net_connect = ConnectHandler(**cisco_router)
output = net_connect.send_command('show ip int brief')
print(output

## ISSUE BELOW
 root@Ubuntu-1:~# python netmiko1.py 
Traceback (most recent call last):
  File "netmiko1.py", line 1, in <module>
    from netmiko import ConnectHandler
ImportError: cannot import name ConnectHandler

**Comment by jomaralexis41** [comment]
@ktbyers  can help me on this please? Thanks!

**Comment by jcrotts** [comment]
Are you able to run this example 
`#!/usr/bin/env python
from __future__ import print_function, unicode_literals

# Netmiko is the same as ConnectHandler
from netmiko import Netmiko
from getpass import getpass

my_device = {
    'host': 'host.domain.com',
    'username': 'pyclass',
    'password': getpass(),
    'device_type': 'cisco_ios',
}

net_connect = Netmiko(**my_device)

output = net_connect.send_command("show ip int brief")
print(output)

net_connect.disconnect()`

**Comment by ktbyers** [comment]
Do you have a file named netmiko.py or any netmiko.pyc files. Assuming that you have Netmiko installed using:

```
pip install netmiko
```

Then the most common cause is you named some other Python file netmiko.py and it is importing this and not the Netmiko library.

**Comment by ktbyers** [comment]
There wasn't any additional response on this issue...so closing it.

**Comment by venjercode** [comment]
Hello @ktbyers , I am having this exact issue. Tried resetting, recreating the Automation box in GNS3. Nothing works. Deleted packages, reinstalled. Still same error. Please help out ! Thanks

 root@NetworkAutomation-1:~#  ls -a
.  ..  .bash_history  .bashrc  .cache  .gns3_perms  .nano  .profile  .ssh  __pycache__  exam.py  netmiko.py

root@NetworkAutomation-1:~# more netmiko.py
from netmiko import ConnectHandler

iosv_l2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.72',
    'username': 'david',
    'password': 'cisco'
}

net_connect = ConnectHandler(**iosv_l2)
output = net_connect.send_command('show ip int brief')
print (output)

config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print (output)

for n in range (2,21):
    print ("Creating VLAN " + str(n))
    config_commands = ['vlan ' + str(n), 'name Python_VLAN ' + str(n)]
    output = net_connect.send_config_set(config_commands)
    print (output)

root@NetworkAutomation-1:~# python3 netmiko.py
Traceback (most recent call last):
  File "netmiko.py", line 1, in <module>
    from netmiko import ConnectHandler
  File "/root/netmiko.py", line 1, in <module>
    from netmiko import ConnectHandler
ImportError: cannot import name 'ConnectHandler'




root@NetworkAutomation-1:~# pip install netmiko
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: netmiko in /usr/local/lib/python2.7/dist-packages (2.3.3)
Requirement already satisfied: setuptools>=38.4.0 in /usr/local/lib/python2.7/dist-packages (from netmiko) (41.0.1)
Requirement already satisfied: paramiko>=2.4.2 in /usr/local/lib/python2.7/dist-packages (from netmiko) (2.4.2)
Requirement already satisfied: scp>=0.10.0 in /usr/local/lib/python2.7/dist-packages (from netmiko) (0.13.2)
Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages (from netmiko) (3.11)
Requirement already satisfied: pyserial in /usr/local/lib/python2.7/dist-packages (from netmiko) (3.4)
Requirement already satisfied: textfsm in /usr/local/lib/python2.7/dist-packages (from netmiko) (0.4.1)
Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from netmiko) (1.1.2)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/dist-packages (from netmiko) (1.0.16)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/dist-packages (from paramiko>=2.4.2->netmiko) (0.1.9)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python2.7/dist-packages (from paramiko>=2.4.2->netmiko) (3.1.6)
Requirement already satisfied: cryptography>=1.5 in /usr/local/lib/python2.7/dist-packages (from paramiko>=2.4.2->netmiko) (2.6.1)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from paramiko>=2.4.2->netmiko) (1.3.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/dist-packages (from bcrypt>=3.1.3->paramiko>=2.4.2->netmiko) (1.10.0)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python2.7/dist-packages (from bcrypt>=3.1.3->paramiko>=2.4.2->netmiko) (1.12.3)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.5->paramiko>=2.4.2->netmiko) (0.24.0)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.4.2->netmiko) (2.19)

**Comment by venjercode** [comment]
> Hello @ktbyers , I am having this exact issue. Tried resetting, recreating the Automation box in GNS3. Nothing works. Deleted packages, reinstalled. Still same error. Please help out ! Thanks
> 
> root@NetworkAutomation-1:~# ls -a
> . .. .bash_history .bashrc .cache .gns3_perms .nano .profile .ssh **pycache** exam.py netmiko.py
> 
> root@NetworkAutomation-1:~# more netmiko.py
> from netmiko import ConnectHandler
> 
> iosv_l2 = {
> 'device_type': 'cisco_ios',
> 'ip': '192.168.122.72',
> 'username': 'david',
> 'password': 'cisco'
> }
> 
> net_connect = ConnectHandler(**iosv_l2)
> output = net_connect.send_command('show ip int brief')
> print (output)
> 
> config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
> output = net_connect.send_config_set(config_commands)
> print (output)
> 
> for n in range (2,21):
> print ("Creating VLAN " + str(n))
> config_commands = ['vlan ' + str(n), 'name Python_VLAN ' + str(n)]
> output = net_connect.send_config_set(config_commands)
> print (output)
> 
> root@NetworkAutomation-1:~# python3 netmiko.py
> Traceback (most recent call last):
> File "netmiko.py", line 1, in 
> from netmiko import ConnectHandler
> File "/root/netmiko.py", line 1, in 
> from netmiko import ConnectHandler
> ImportError: cannot import name 'ConnectHandler'
> 
> root@NetworkAutomation-1:~# pip install netmiko
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> Requirement already satisfied: netmiko in /usr/local/lib/python2.7/dist-packages (2.3.3)
> Requirement already satisfied: setuptools>=38.4.0 in /usr/local/lib/python2.7/dist-packages (from netmiko) (41.0.1)
> Requirement already satisfied: paramiko>=2.4.2 in /usr/local/lib/python2.7/dist-packages (from netmiko) (2.4.2)
> Requirement already satisfied: scp>=0.10.0 in /usr/local/lib/python2.7/dist-packages (from netmiko) (0.13.2)
> Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages (from netmiko) (3.11)
> Requirement already satisfied: pyserial in /usr/local/lib/python2.7/dist-packages (from netmiko) (3.4)
> Requirement already satisfied: textfsm in /usr/local/lib/python2.7/dist-packages (from netmiko) (0.4.1)
> Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from netmiko) (1.1.2)
> Requirement already satisfied: ipaddress in /usr/lib/python2.7/dist-packages (from netmiko) (1.0.16)
> Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/dist-packages (from paramiko>=2.4.2->netmiko) (0.1.9)
> Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python2.7/dist-packages (from paramiko>=2.4.2->netmiko) (3.1.6)
> Requirement already satisfied: cryptography>=1.5 in /usr/local/lib/python2.7/dist-packages (from paramiko>=2.4.2->netmiko) (2.6.1)
> Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from paramiko>=2.4.2->netmiko) (1.3.0)
> Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/dist-packages (from bcrypt>=3.1.3->paramiko>=2.4.2->netmiko) (1.10.0)
> Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python2.7/dist-packages (from bcrypt>=3.1.3->paramiko>=2.4.2->netmiko) (1.12.3)
> Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.5->paramiko>=2.4.2->netmiko) (0.24.0)
> Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.4.2->netmiko) (2.19)

OK... I read through your other forums & found the Answer,, Thanks !!!
but now I am getting this...


root@NetworkAutomation-1:~# python3 ssh.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 864, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 192.168.122.72

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ssh.py", line 10, in <module>
    net_connect = ConnectHandler(**iosv_l2)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 242, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 312, in __init__
    self._open()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 317, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 870, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 192.168.122.72:22

**Comment by quetech94** [comment]
I was able to get this to work by downgrading netmiko to 2.4.2 and it works with David Bombal netmiko1.py using NetworkAutomation as well as from unbuntu container in gns3.  

command:
pip install netmiko==2.4.2

**Comment by ktbyers** [comment]
Please don't overload closed issues with new issues instead create a new, separate Github issue.
