### ISSUE TITLE
yaml or json device info entry

### ISSUE THREAD

**Issue by h-rasi** [ktbyers/netmiko#823]
Hello everyone. First I want to say that I am in the starting point with netmiko and python.
My question is, which is the type of file to read as a dictionary or table the information of each devices for connecting by netmiko? 
My data for the devices that I am going to get from the file are: ip,device_type and host and two port number. each device has different configuration.
Thank you.

**Comment by ktbyers** [comment]
I would just construct a dictionary from the information in your file and then pass them into ConnectHandler using **kwargs format.

There should be examples of this for Netmiko online.
