### ISSUE TITLE
Procurve switches time out when copying running-config to tftp server

### ISSUE THREAD

**Issue by jamesb2147** [ktbyers/netmiko#825]
I'm literally only running the following commands:

end
write mem
\n (carriage return)
copy running-config tftp 1.1.1.1 test.txt

Run with send_config_set this fails on the last command. If I close the session immediately before the command to backup the config, then open a new session and backup the config, then close that session, everything is fine. I therefore have and am using a workaround (close the session, open a new one to specifically run the backup job), but it is odd, and I suspect as I continue adding new commands that I'll find more that I have to break apart from the rest of my command block.

FWIW I'm connecting to ProCurve 3800-48G PoE+ units.

**Comment by ktbyers** [comment]
@jamesb2147 You probably shouldn't use `send_config_set()` for this. That method is for making configuration changes to the device.

For these commands I would look to use:

1. save_config() for the wr mem command
2. send_command() for the copy running-config tftp command

Does the `copy running-config tftp` prompt you for anything or does it just execute directly? If it prompts you to confirm or for other info (you might need to use send_command_timing() method).

Also if the `copy running-config tftp` command is slow, you might need to add the delay_factor=2 argument.


Kirk
