### ISSUE TITLE
Netmiko NetMikoAuthenticationException timeout

### ISSUE THREAD

**Issue by horseinthesky** [ktbyers/netmiko#834]
Hello.
I have a simple example : 
```
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoAuthenticationException, NetMikoTimeoutException

CONNECTION_PARAMS = {'ip': 'cloud-myt-qrator-6s254.yndx.net', 'username': 'netinfra-mon', 'timeout': 10, 'use_keys': True, 'key_file': '/home/netinfra-mon/.ssh/id_rsa', 'device_type': 'juniper'}

try:
    with ConnectHandler(**CONNECTION_PARAMS) as ssh:
        result = ssh.send_command('sh ver')
        print(result)
except (NetMikoAuthenticationException, NetMikoTimeoutException):
    print('Failed to connect to {}'.format(CONNECTION_PARAMS['ip']))
```

I can change connection timeout(**NetMikoTimeoutException**) with **timeout** parameter but it doesn't effect **NetMikoAuthenticationException**. 

SSH on this device is enabled but there is no such user so **NetMikoAuthenticationException** is in place.
As I can see it is **60** seconds by default:
```
time ./bla.py
Failed to connect to cloud-myt-qrator-6s254.yndx.net

real    1m0.413s
user    0m0.296s
sys     0m0.024s
```

And I can't find if there is a parameter to change failed auth timeout.

**Comment by horseinthesky** [comment]
@ktbyers Thank you but `blocking_timeout` made no effect.

I also marked something I can't explain: from one user timeout in 30 seconds and from another is 60.
```
horseinthesky@cloudvessel:~$ time sudo -u netinfra-mon python3 /home/netinfra-mon/scripts/bla.py
Failed to connect to cloud-myt-qrator-6s254.yndx.net

real    0m31.441s
user    0m0.260s
sys     0m0.024s 

horseinthesky@cloudvessel:~$ sudo su netinfra-mon

netinfra-mon@cloudvessel:/home/horseinthesky$ time python3 ~/scripts/bla.py   
Failed to connect to cloud-myt-qrator-6s254.yndx.net

real    1m0.440s
user    0m0.292s
sys     0m0.020s
```

Script now look like this:
```
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoAuthenticationException, NetMikoTimeoutException

CONNECTION_PARAMS = {'ip': 'cloud-myt-qrator-6s254.yndx.net', 'username': 'netinfra-mon', 'timeout': 10, 'use_keys': True, 'key_file': '/home/netinfra-mon/.ssh/id_rsa', 'device_type': 'juniper', 'blocking_timeout': 8}

try:
    with ConnectHandler(**CONNECTION_PARAMS) as ssh:
        result = ssh.send_command('sh ver')
        print(result)
except (NetMikoAuthenticationException, NetMikoTimeoutException):
    print('Failed to connect to {}'.format(CONNECTION_PARAMS['ip']))```

**Comment by ktbyers** [comment]
@horseinthesky Okay, yes I will have to look at this some more. 

Are you actually failing authentication or connecting to a device/ip that doesn't exist (or something else)? I can't tell since you are catching the exception.

**Comment by horseinthesky** [comment]
Oh sorry. I'm connecting to a QFX box that has no user **netinfra-mon** so it is **NetMikoAuthenticationException**.

**NetMikoTimeoutException** is handled by **timeout** parameter perfectly fine.

**Comment by TomCos** [comment]
I'm also having the same issue.  I have two pieces of code, a Paramiko and Netmiko one used for connection to a device, the Paramiko succeeding and the Netmiko failing.  After reading through base_connection.py, I've matched up the Netmiko code to be 1:1 with the Paramiko implementation:

ssh.connect(hostname='10.1.1.1', username='root', password='somepass', timeout=5, auth_timeout=60, look_for_keys=False, allow_agent=False)

net_connect = netmiko.ConnectHandler(device_type='terminal_server', host='10.1.1.1', username='root', password='somepass', timeout=5, use_keys=False, allow_agent=False)

The difference, auth_timeout.  If it's not set in the Paramiko code, it will fail and pass BadAuthenticationType, but really what's happening is paramiko.ssh_exception.AuthenticationException: Authentication timeout.

I see in _connect_params_dict you're passing a lot of these variables directly to Paramiko unmodified.  Could we sneak in auth_timeout, and just default it to None?

Also, you're code is really awesome!  Thanks for the constant upkeep!

**Comment by ktbyers** [comment]
I assume your device is really slow to authenticate for some reason (since we don't have this issue generally)?

Solution sounds reasonable. Feel free to submit a PR on it.


Kirk

**Comment by TomCos** [comment]
Yes correct, slow to authenticate for a number of reasons (distance, inefficient routing, bad firmware, etc)

**Comment by TomCos** [comment]
Let me know what you think:
https://github.com/ktbyers/netmiko/pull/926

**Comment by carlniger** [comment]
Closing since this has been merged.
