### ISSUE TITLE
Privilege Escalation for a Cisco like device

### ISSUE THREAD

**Issue by newsera** [ktbyers/netmiko#838]
```
File "/home/ubuntu/.local/lib/python3.5/site-packages/netmiko/base_connection.py", line 1051, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: \(test\-com\-access\-sw11\)\ \>
```

I believe this is breaking since it unusually has parenthesis for hostname and also has a space between ) and > 

How can I get this working assuming I use "cisco_ios" as device type? I have already provided the secret parameter but the privilege escalation isn't happening since it never detects ">"

Device Interaction through SSH looks as follows: 
(test-com-access-sw11) >enable
Password:*********

(test-com-access-sw11) #

**Comment by newsera** [comment]
I can try  net_connect.enable() before sending the command. But how can we improve the search detection here so that it does it automatically?

**Comment by newsera** [comment]
```
  File "/home/ubuntu/.local/lib/python3.5/site-packages/netmiko/base_connection.py", line 1069, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/netmiko/base_connection.py", line 1051, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: \(test\-com\-access\-sw11\)\ \#
```

After using  net_connect.enable(), no luck in getting the commands executed. also tried send_command_expect()

**Comment by ktbyers** [comment]
@newsera What type of device is it?

What is the command you are sending in 'send_command'? Can you include your code?



Kirk

**Comment by newsera** [comment]
Its a Whitebox Switch running custom OS. 

Found the issue. It was getting stuck when the code was unable to retrieve a multi paged command output. Passing "terminal length 0" fixed the issue, but I was under the impression that "cisco_ios" already takes care of "terminal length 0"

```
from netmiko import ConnectHandler

comm = {
    'device_type': 'cisco_ios',
    'ip':   'test',
    'username': 'testuser',
    'password': 'testpass',
    'port' : 22,          # optional, defaults to 22
    'secret': 'testpass',     # optional, defaults to ''
    'verbose': True,       # optional, defaults to False
}

net_connect = ConnectHandler(**comm)
output = net_connect.send_command('show ip int brief')
print(output)
net_connect.enable()
output = net_connect.send_command('terminal length 0')
output = net_connect.send_command('show ver')
print(output)
```

**Comment by newsera** [comment]
It would be nice if ">" in hostname is automatically detected for sending net_connect.enable(). Since the device name "(test-com-access-sw11) >" looks different than a Cisco device, it has to be done manually. But why "terminal length 0" is not being sent even though the device type is "cisco_ios" remains a mystery. 

Thanks Kirk for your quick response.

**Comment by ktbyers** [comment]
@newsera The most likely cause is that the device is doing something that is not consistent with 'cisco_ios' behavior in some way.

You can turn on logging to see more details on what is going on:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

The cisco_ios driver does automatically execute 'terminal length 0'.

You probably need to make a Netmiko device_type as it looks like its behavior has some differences from Cisco IOS that are causing you issues.
