### ISSUE TITLE
Connecting to device using telnet when the device is not reachable causes telnetlib to throw [Errno 113] No route to host

### ISSUE THREAD

**Issue by rismanchicm** [ktbyers/netmiko#839]
This could be executed in a better way to raise a Netmiko exception when trying to establish telnet connection.
Here is the current base_connection.py def establish_connection(self, width=None, height=None):
```python
        if self.protocol == 'telnet':
            self.remote_conn = telnetlib.Telnet(self.host, port=self.port, timeout=self.timeout)
            self.telnet_login()
        elif self.protocol == 'serial':
```
Here is the what the updated base_connection.py def establish_connection(self, width=None, height=None): could look like
```python
        if self.protocol == 'telnet':
            try:
                self.remote_conn = telnetlib.Telnet(self.host, port=self.port, timeout=self.timeout)
            except socket.error:
                msg = "Connection to device timed-out: {device_type} {ip}:{port}".format(
                    device_type=self.device_type, ip=self.host, port=self.port)
                raise NetMikoTimeoutException(msg)
            self.telnet_login()
        elif self.protocol == 'serial':
```

**Comment by ktbyers** [comment]
Current behavior seems reasonable...what is the value of your proposed solution.

**Comment by rismanchicm** [comment]
The proposed solution is in the previous comment. The issue is if using telnetlib calling Telnet() to a device that is not reachable, telnetlib will throw a socket.error. If it does you should raise NetMikoTimeoutException. You already do this for ssh but not telnet. That way it is easier for someone to handle the exception. It stumped me for a bit and I think there was atleast one other issue that was opened on Netmiko that would have fixed it. I think it was someone who was looping through devices trying to telnet and said their code would randomly fail....
