### ISSUE TITLE
Allow session with a device to be recorded

### ISSUE THREAD

**Issue by jobec** [ktbyers/netmiko#842]
It would be very handy to have netmiko log the session with a device to a specific file. Allowing to keep a log of every device session for logging/auditing/troubleshooting purposes. Like for example keeping all communications of the last month.

Because:

* **Threading/Multiprocessing:** using the logging feature that's implemented now (standard python logging) results in scrambled log files. All threads write at random in the log file. You can't make up what was send to which device.

* **Auditing/review:** For forensics, auditing, logging, troubleshooting... purposes you often need a single file of what happened towards a device. What commands were sent, what was returned. 

* **Current Logging:** With the current logging implementation, it's rather difficult to see at a glance what was sent. You first need to remove a lot of extra information from the logs.

* **Debug log levels:** At the moment you have to enable debugging log levels while I believe this kind of logging should not depend on a debug setting. If you want to do this logging always and in a structured way, you can't do it. Also, by sending this data to the logging subsystem of Python, you risk that it gets send to a remote syslog server. Given the amount of log messages it produces this is not a good idea.

**Comment by jobec** [comment]
Example of a log file (with multithreading, 3 devices at once) with the default netmiko log output:
https://gist.github.com/jobec/ca17b0be5212dfbcfd7b45ff7f8fcd2a

Example of how a session log file could look like without other information, and only for a single device.
https://gist.github.com/jobec/a39b061cf29101cc037cfe9a9189d380

**Comment by jobec** [comment]
A work around could be to write a wrapper around netmiko and implement all methods that send "something" to a device. Capture the command on the way in and out and write it to a file. But that is much more complex then doing it in the `_write_channel` and `_read_channel` methods. And it also doesn't allow you to capture things like disabling the screen paging and such.

Also, having this inside netmiko itself allows it to bubble up towards packages like napalm and ansible, where it's now very cumbersome to enable this kind of logging without drowning is log messages or breaking things.

**Comment by ktbyers** [comment]
```
Threading/Multiprocessing: using the logging feature that's implemented now (standard python logging) results in scrambled log files. All threads write at random in the log file. You can't make up what was send to which device.
```

That is on the code writer i.e. you need to have a thread dedicated to this and some sort of an ID. I don't think the library is the proper place to handle this.

```
Auditing/review: For forensics, auditing, logging, troubleshooting... purposes you often need a single file of what happened towards a device. What commands were sent, what was returned.
```

Can't logging handle this (assuming you handle the concurrency issue?

```
Current Logging: With the current logging implementation, it's rather difficult to see at a glance what was sent. You first need to remove a lot of extra information from the logs.
```

You can you show me what you want versus what you are getting? I like the current logging, but I also am usually looking at it from a Netmiko debugging perspective.

```
Debug log levels: At the moment you have to enable debugging log levels while I believe this kind of logging should not depend on a debug setting. If you want to do this logging always and in a structured way, you can't do it. 
```

Can you explain what you mean by a "structured way" versus not a structured way here? I am just trying to understand the difference between the current behavior versus what you are interested in?

```
Also, by sending this data to the logging subsystem of Python, you risk that it gets send to a remote syslog server. Given the amount of log messages it produces this is not a good idea.
```

It seems pretty unlikely you would log to the syslog server? Can you show me an example of how this would happen accidentally?

**Comment by jobec** [comment]
> you need to have a thread dedicated to this and some sort of an ID

This is not possible with the python logging framework. You cannot handle the logging in a separate thread. Also, if you change a logging handler to write to some other file, it changes for all threads because there's only 1 logger for netmiko with and attached handler.

> Can't logging handle this (assuming you handle the concurrency issue?

No, it cannot because of the above.

> You can you show me what you want versus what you are getting?

Have a look at the 2 gists in my second reply.

> Can you explain what you mean by a "structured way"

With structured, I mean that every session netmiko creates with a device (optionally) results in a separate file with only the communication with that device. You can name these files in some way so you can find them back easily and see what happened during the communication with the device.

For example, imagine running netmiko as part of Celery tasks. Every task does some kind of change on a device. Like configuring an interface based on user input on 3000 devices.

Now, imagine that 3% of those tasks fail because netmiko somehow didn't properly understand the response of the device. (slight difference in response between software version, latency related issues, ...) You could then go and look in the file for that specific task and see what the device responded and where it went wrong.

This is nearly impossible to do when you cannot split the conversation with a device in a separate file.

> It seems pretty unlikely you would log to the syslog server

Well, in case you run netmiko inside of Django and your Django code already emits log message to a syslog server, you could end up with syslogging all debug messages of netmiko.
There's also another part to this story. Because netmiko sends those logs out as DEBUG messages, you're forced to also set the overall logging level to DEBUG. Every package apart from Django and Netmiko that you use and that emits debug logs will all of a sudden also become visible.

Besides all that, the context I'm talking about is "not" for debugging netmiko. It's for keeping a record of communications with devices. So the focus is different.

**Comment by jobec** [comment]
In pull request #855 I've implemented what I'm talking about.
Maybe this brings more clarity.

**Comment by ktbyers** [comment]
@jobec Okay, nice, clear response and my comments/questions were clearly misguided.

Let me look at your PR.
