### ISSUE TITLE
regarding send_command_timing

### ISSUE THREAD

**Issue by hellnor** [ktbyers/netmiko#846]
I need to use send_command_timing instead if send_command because the router im collecting data from sometimes waits couple of seconds after  it generates some of the outputs then continues to generate rest but i think send_command method thinks it reached to end of the  output and drops the following error:

  File "build/bdist.linux-x86_64/egg/netmiko/base_connection.py", line 1051, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: <that part is router prompt>

But when i use send_command_timing it works fine so question is whats the wait time for it with the default delay factor so that i can use it for some long outputs aswell?

**Comment by ktbyers** [comment]
`send_command` is searching for a pattern in the output to determine a command is done. By default, this is based on the network device's prompt (you can modify this by using the `expect_string` argument).

`send_command_timing` tries to guess how long to wait. 

For the situation you describe `send_command` should generally be a better solution.

`send_command_timing` will wait for two additional seconds once there is no new data available. This is using a delay_factor of 1. A delay_factor of 2 will double this (4 will quadruple, et cetera).

**Comment by hellnor** [comment]
Yeah, actually send_command is ideal one but for some reason sometimes it says:

IOError: Search pattern never detected in send_command_expect: < this is the router prompt >

By the way device is IOS-XR, is there a kind of well known bug or something when it comes to grab router prompt? Because find_prompt also sometimes returns system clock instead of router prompt.

**Comment by ktbyers** [comment]
@hellnor Yes, your send_command issue is the expected pattern not coming back for some reason. You could probably look at it in more detail by using logging.

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel


There is a configuration in IOS-XR that timestamps every show command. You should probably turn that off. That timestamp is probably messing up Netmiko from properly finding the prompt in some way. You should open up a separate issue if you want to look into that more (though the fix might be that time-stamping has to be turned off).

**Comment by hellnor** [comment]
@ktbyers , i found something interesting with the debugs, i see sometimes command output comes with delay , at the very beginning of next command output like this:

ie ; i send show platform but it returns empty but after the next command "show controllers np counters all" i see its attached to that command output in read channel:



2018-07-06 13:40:12,453:DEBUG:write_channel: show platform

2018-07-06 13:40:12,654:DEBUG:read_channel: show platform  >>>>>>>>>>> should be here but not

2018-07-06 13:40:12,855:DEBUG:read_channel: 
2018-07-06 13:40:16,859:DEBUG:read_channel: 
2018-07-06 13:40:16,860:DEBUG:read_channel: 
2018-07-06 13:40:16,860:DEBUG:write_channel: show controllers np counters all >>>>> next command i send

2018-07-06 13:40:16,960:DEBUG:read_channel: 
2018-07-06 13:40:18,963:DEBUG:read_channel: Fri Jul  6 13:40:17.770 
Node            Type                      State            Config State  >>>>>>>>>>>>>>>>>> platform output here
-----------------------------------------------------------------------------
0/RP0/CPU0      A99-RP2-TR(Standby)       IOS XR RUN       PWR,NSHUT,MON
0/RP1/CPU0      A99-RP2-TR(Active)        IOS XR RUN       PWR,NSHUT,MON
0/0/CPU0        A9K-2x100GE-TR            IOS XR RUN       PWR,NSHUT,MON

RP/0/RP1/CPU0:Router#show controllers np counters all
Fri Jul  6 13:40:18.516 

2018-07-06 13:40:19,063:DEBUG:read_channel: 
2018-07-06 13:40:21,067:DEBUG:read_channel: 
                Node: 0/0/CPU0:
----------------------------------------------------------------

Show global stats counters for NP0, revision v2

Last clearing of counters for this NP: NEVER 

Read 58 non-zero NP counters:
Offset  Counter                                         FrameValue   Rate (pps)

**Comment by ktbyers** [comment]
Please post your current code that is associated with that debugging output. You can obfuscate any confidential information likes IP addresses, and passwords.

**Comment by hellnor** [comment]
Sure here it is, please note that its not happening always, a random issue.

from netmiko import ConnectHandler
import re
import multiprocessing as mp
import time
import sys
from time import ctime
import logging


def get_platform(arg):

    output2= arg.send_command_timing('show platform',delay_factor=2)
    platform_output=output2.splitlines()

    Dict_LC={}
    LC_type=""
    for lines in platform_output[4:]:
        LC_type=re.search(r'(0\/.*CPU0)\s+(\S+)',lines)
        if LC_type:
            Dict_LC['{}'.format(LC_type.group(1))]=LC_type.group(2)
    return Dict_LC

def get_np_counters(arg):

    output= arg.send_command_timing('show controllers np counters all')
    np_counters_output_list=output.splitlines()
    return np_counters_output_list


def Check(IP):

    platform = 'cisco_xr'
    host = '{}'.format(IP)
    username = 'xxx'
    password = 'xxx'

    logging.basicConfig(filename=x, level=logging.DEBUG,format="%(asctime)s:%(levelname)s:%(message)s")
    logger = logging.getLogger("netmiko")


    device = ConnectHandler(device_type=platform, ip=host, username=username, password=password, global_delay_factor=1)

    LC_PID=get_platform(device)

    np_counters_output=get_np_counters(device)
  


hostIP=['...']


processes = []

for IP in hostIP:
    processes.append(mp.Process(target=Check, args=(IP,)))
for p in processes:
    p.start()
for p in processes:
    p.join()
print(ctime())

**Comment by ktbyers** [comment]
@hellnor You can't use `send_command_timing` for this type of thing (or you will have this type of issue).

You will need to use `send_command`.

If `send_command` is not working...then that is an issue we can potentially debug.
