### ISSUE TITLE
get show time at HP Procurve 

### ISSUE THREAD

**Issue by SharonYeuda** [ktbyers/netmiko#847]
Hi,
The prompt(hostname) of my switch is S-ACC-SW03.
when I send print(connection.send_command('show time')) to the switch, I'm getting SW03#.
Somehow it's splitting by '-'.
only if i send the command again I'm getting the time result.
any idea?

**Comment by ktbyers** [comment]
@SharonYeuda Can you enable logging and then post the results here:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

You can obfuscate anything that is confidential.

Hopefully this will provide more details on what is going wrong.

**Comment by carlniger** [comment]
@SharonYeuda Can you let us know if this is still an issue on the current dev branch, and if so update with logging detail?

**Comment by carlniger** [comment]
I'm going to go ahead and close this now. Feel free to reopen if its still an issue.
