### ISSUE TITLE
overwrite_file=True in file_transfer (scp_handler.py)

### ISSUE THREAD

**Issue by Wallpix** [ktbyers/netmiko#848]
Hi, I am trying to figure out if the 'overwrite_file' in the file_transfer class in scp_handler.py is actually implemented in the current version.  I've updated to 2.1.1 and I don't see this option in the init

```
class BaseFileTransfer(object):
    """Class to manage SCP file transfer and associated SSH control channel."""
    def __init__(self, ssh_conn, source_file, dest_file, file_system=None, direction='put'):
        self.ssh_ctl_chan = ssh_conn
        self.source_file = source_file
        self.dest_file = dest_file
        self.direction = direction
```

**Comment by ktbyers** [comment]
It in the file_transfer function:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/scp_functions.py#L23-L24

See article here for more details:

https://pynet.twb-tech.com/blog/automation/netmiko-scp.html


Kirk
