### ISSUE TITLE
Expose Full Output

### ISSUE THREAD

**Issue by jonesbra** [ktbyers/netmiko#851]
I am interested in seeing the full device output from beginning to end of the SSH session. This could be as simple as creating a property of the Base Connection class containing the full output, and anytime data is received from the stream appending to that property. I looked into the paramiko module and seen that they have a "makefile" method that can be used on channels such as Netmiko's remote_conn property of the base class to create "file-like objects". Would it be possible to use this to redirect output to a variable or file?

**Comment by ktbyers** [comment]
@jonesbra The closest thing I have is probably this:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by ktbyers** [comment]
Yes, @jobec proposal in PR #855 should be very close to what you are requesting.

It is probably better to do what @jobec proposed in his PR as Netmiko also uses telnetlib and can use a serial channel (i.e. it would be good to make the session log independent of Paramiko.

Let us know if what is proposed in PR #855 solves your issue.

**Comment by jonesbra** [comment]
That will work fine, thank you.
