### ISSUE TITLE
WLC , no admin rights -how do I bypass "--More-- or (q)uit" which blocks my sessions

### ISSUE THREAD

**Issue by 1001QAdotNET** [ktbyers/netmiko#852]
Hi Kirk

I am trying to collect stats from WLCs and it seems that if I am not admin and I do not disable the paging then if the command has a longer output my script gets stuck at "--More-- or (q)uit"

Is there a workaround for this? I am coming to netmiko from exscript and there I could wait for a string and react to that ...Is this possible with Netmiko?

thanks
1K1

**Comment by ktbyers** [comment]
@1001QAdotNET send_command() method has an expect_string argument (which is a regular expression) so you could use that and then piece together the entire output.

Alternatively, you could probably write a for-loop and use the read_channel() and write_channel() methods directory.

**Comment by 1001QAdotNET** [comment]
Thank Kirk
After posting here I started reading these and i came to the same conclusion. now I am having a programming issue because I could use send with expect string or prompt but it is not clear for me how should I stop the loop
It would be something like:

cumulativeoutput=send_command(command)
While "(Cisco Controller) >" not in cumulativeoutput
       
       output=send_command_expect_propmpt_or_match_regex( " ", regex)       # sending space as command to move to next screen of the output"
         cumulativeoutput=cumulativeoutput+output

**Comment by ktbyers** [comment]
@1001QAdotNET My logic would be to read the channel. If I detect the '--More--' string, then I keep reading.

If I detect the trailing prompt, then I stop reading.

So in psuedo-code, something like:

```
while True:
    new_data = net_connect.read_channel()
    output += new_data                       # record everything that has been received
    if '--More--' in new_data:
        net_connect.write_channel(' ')   # Send space character down the channel
        time.sleep(1)
    elif 'Cisco Controller' in new_data:
         break
```

**Comment by 1001QAdotNET** [comment]
OK thank you, I will try that sound like a better idea

**Comment by ylebiannic** [comment]
Hi,

I do have this issue for a old dell that does not support disable paging method.
I do something like that : 
```
    def _command(self, cmd, previous_output='', **kwargs):
        try:
            #command can take more time on dell device
            output = self._session.send_command(cmd, **kwargs)
            if '--More--' in output:
                output = re.sub('.*\-\-More\-\-.*', '', output)
                output = previous_output + output
                return self._command(' ', previous_output=output, **kwargs)
            return previous_output + output
```

it works pretty well on my devices.
