### ISSUE TITLE
Finding vulnerabilities in network devices

### ISSUE THREAD

**Issue by riddhi2910** [ktbyers/netmiko#853]
Hello ktbyers,

I am doing network automation project where i need to find vulnerabilities of different vendor devices and show it. I have to use netmiko for ssh. Any idea how should i start?

**Comment by Collisio-Adolebitque** [comment]
If you're planning on using netmiko for this type of task and don't know where to start, I'd suggest that this might be a task that you're a little under equipped for.  This isn't a good use of netmiko unless you have serious software development skills and are building and entire vulnerability assessment toolkit around it.  

You might start looking at what current [vulnerabilities](https://cve.mitre.org/) there are out there and [some of the options you have for finding them](https://www.networkworld.com/article/2176429/security/security-6-free-network-vulnerability-scanners.html).

**Comment by Collisio-Adolebitque** [comment]
What words do you hope to get from a network device SSH session that will advise you on vulnerabilities?

**Comment by riddhi2910** [comment]
thanks Again Collisio, I want to search network interface,error message etc,that we use with | (pipe) and some regex in CLI.

**Comment by Collisio-Adolebitque** [comment]
How does that help you find vulnerabilities?  Do you actually mean you're looking for errors, not vulnerabilities?
