### ISSUE TITLE
Netmiko as a Service

### ISSUE THREAD

**Issue by fixlensmith** [ktbyers/netmiko#858]
Hi, 
i want to ask, how to make my script as service, for example : 
i want to ping every 5 minutes to x.x.x.x, 
so i just send_command 'ping x.x.x.x'
and make cron job to running the script every 5 minutes.
so the flow like this
 running every 5 minutes (Cron ---> Python Execute ----> Login to devices ----> send the command)

how to make the flow become like this
Python Execute -----> Login to devices -----> Running Every 5 minutes (send Command)

so no need for me to always login every 5 minutes, just 1 time login, and running the command every 5 minutes..

how to make this happen?

**Comment by ishtiaqk** [comment]
Response inline below;

Regards,
Ishtiaq Khan

> On Jul 1, 2018, at 8:33 PM, fixlensmith <notifications@github.com> wrote:
> 
> Hi,
> i want to ask, how to make my script as service, for example :
> i want to ping every 5 minutes to x.x.x.x,
> so i just send_command 'ping x.x.x.x'
> 

do a nested for loop one with device list other with commands Or just use in script given number of devices and ping command to be executed..u will find many examples on github for this

Use netmiko for connection handling and capture output
> and make cron job to running the script every 5 minutes.
> so the flow like this
> running every 5 minutes (Cron ---> Python Execute ----> Login to devices ----> send the command)
> 
Put a cron job to execute e.g. 
python3 ping.py

**Comment by ktbyers** [comment]
You would just write a continuously running Python program that had a main loop in it that was always running (and probably with a builtin 5 minute sleep inside that main loop).

You would probably use something like `supervisord` to ensure that your program was always running and restart it if it failed.

Note, I probably wouldn't try to keep the connection to the device always alive; I would probably just login to the device every 5 minutes; do what you need to do; and then disconnect.

If you want to keep the connection to the device always alive, then you are going to need to add logic into your program and checks if the connection is alive or not. If the connection is not alive, then you will need to re-connect. You might also need to check that other things like firewalls and VTY timers don't tear down the connection automatically.
