### ISSUE TITLE
Verify if the command was accepted by router

### ISSUE THREAD

**Issue by kochargs** [ktbyers/netmiko#861]
Hello,

I want to write a code that pushes a config set to a router and it should tell me which command was succesfully configured on the router and which one failed due to any reason.... The syntax was wrong or there was spelling mistake in the command whatever may be the reason i just would like to know the command that was not accepted by the router.

Is there a feature that allows me to implement something like this ?

Thanks for your help.

**Comment by kochargs** [comment]
May be i could read test.log and look for the line above "                              ^" to see which command was not accepted by the device or just log the net_connect.send_config_set to a file and read it afterwards rather than enabling debugging ?

config term
Enter configuration commands, one per line.  End with CNTL/Z.
CiscoIOUL215.2d-1(config)#interface e1/1
CiscoIOUL215.2d-1(config-if)#strichport
                              ^
% Invalid input detected at '^' marker.

CiscoIOUL215.2d-1(config-if)#end

Is there a built in boolean that is returned against a command if it was successful or not ?
It would be nice to have this feature though if it doesn't exist already.

**Comment by ktbyers** [comment]
Netmiko (by design) has no intelligence about the commands that you send down the SSH channel so you would need to search the output that is returned and determine if errors occurred.

send_config_set() will return the CLI output of what happened so you could capture the output of that and then search for errors in it.
