### ISSUE TITLE
How can I connect to Linux Jump server using RSA Token with ssh？

### ISSUE THREAD

**Issue by VishiMishra** [ktbyers/netmiko#867]
Team,

I am new in script world and have a requirement to automate network device. Please refer below connection and advise suitable scripts. 

Linux(Machine)----->>>>>>>(RSA Token enabled)Linux(Jump Server)------>>>>>Device(Cisco)

Below is the code which gives me error.

from netmiko import ConnectHandler

RSA_PASSCODE = raw_input("Enter RSA passcode:")
Jump_server = {
'device_type': 'linux',
'ip': '10.10.10.227',
'username': 'cisco',
'password': 'cisco',
'passcode':'RSA_PASSCODE'
} 
net_connect = ConnectHandler(**Jump_server)
net_connect.find_prompt()
output = net_connect.send_command("ls -l)
print output

**Comment by ktbyers** [comment]
@VishiMishra What does a manual SSH session to your Linux-Jump Server look like?

**Comment by VishiMishra** [comment]
When I ssh to Jump server it first asks for RSA PASSCODE and then prompts for password. 

Let me know it helps you to understand the issue.

**Comment by ktbyers** [comment]
And the password in this context is the Jump server password?

**Comment by VishiMishra** [comment]
Actually the Jump server gets authenticated through AD, yes the password is mine

**Comment by ktbyers** [comment]
Yes, Netmiko can't do that directly...you can see if you can figure out a way to pass the RSA code manually (you should be able to do this).

I think the netmiko/dell/dell_powerconnect.py file probably has a model you could follow for how to do this:

You could also look/research what Paramiko users do about this in a Linux context (for ideas of how it would need to be implemented in Netmiko).

**Comment by Muadiv** [comment]
I have a similar issue, also I want to log with my rsa key file, but not sure how. I did it with Paramiko, but I can't with Netmiko :( 

`import paramiko

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
host = '192.168.1.1'
port = 22
ssh.connect(host, port=port,  username='admin', allow_agent=True)
my_command = "ls -l"

pre_command = ""
command = pre_command + my_command

stdin, stdout, stderr = ssh.exec_command(command)

# print(stdout.read())
# print(stderr.read())

sshdata = stdout.readlines()

for line in sshdata:
    print(line)

ssh.close()
`

**Comment by VishiMishra** [comment]
@Muadiv, I have different issue, I wanted to connect jump server using RSA secure ID instead of RSA key file.

**Comment by Muadiv** [comment]
I did like this now and is working. Only to connect to the jump server, entering manually the rsa key: 

```
from __future__ import print_function, unicode_literals
from netmiko import Netmiko
from getpass import getpass

#host = input("Enter host to connect to: ")
host = "192.168.1.2"
password = getpass()
device = {
    'host': host,
    'username': 'admin',
    'password': password,
    'device_type': 'autodetect',
}

command = 'ls -l'
net_connect = Netmiko(**device)
output = net_connect.send_command(command)
print(output)
```

**Comment by VishiMishra** [comment]
@Muadiv , Thanks but  I'm looking for two factor authentication , first secure ID(RSA) and second password(TACACS or AD)

**Comment by napstercc** [comment]
@VishiMishra Did you find a solution?

**Comment by Muadiv** [comment]
Hey @VishiMishra and @napstercc  check my solution here: 
https://github.com/ktbyers/netmiko/issues/1040#issuecomment-450103248
 
I have kind of the same environment. And with this is working :smile:

**Comment by napstercc** [comment]
> Hey @VishiMishra and @napstercc check my solution here:
> [#1040 (comment)](https://github.com/ktbyers/netmiko/issues/1040#issuecomment-450103248)
> 
> I have kind of the same environment. And with this is working 😄

It's intersting, but it opens and closes the app. It would nice to have an RSA module which could generate the key from a given token. Not sure it that exists.

**Comment by carlmontanari** [comment]
Going to close this as #1040 has some more details/conversation about this!
