### ISSUE TITLE
Issue installing Netmiko in GNS3 on a Network Automation docker container

### ISSUE THREAD

**Issue by bdbrown69** [ktbyers/netmiko#871]
I am having an issue trying to resolve installing netmiko on a Network Automation docker in GNS3. Here is the output I receive when trying to install netmiko:

root@NetworkAutomation-1:~# python3 -m pip install netmiko
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting netmiko
  Downloading https://files.pythonhosted.org/packages/96/f8/4ecb91398a14bc1942322e87203859b04421cdb2b8b5c7d9b3fc9a168e21/netmiko-2.1.1.tar.gz (71kB)
    100% |################################| 71kB 1.1MB/s
Collecting paramiko>=2.0.0 (from netmiko)
  Downloading https://files.pythonhosted.org/packages/3e/db/cb7b6656e0e7387637ce850689084dc0b94b44df31cc52e5fc5c2c4fd2c1/paramiko-2.4.1-py2.py3-none-any.whl (194kB)
    100% |################################| 194kB 1.5MB/s
Collecting scp>=0.10.0 (from netmiko)
  Downloading https://files.pythonhosted.org/packages/ef/8c/399c5ddffc8c1bd2593ee6c8937ed31f005dcfa0c591da149f7b4b993f14/scp-0.11.0-py2.py3-none-any.whl
Collecting pyyaml (from netmiko)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |################################| 276kB 2.1MB/s
Collecting pyserial (from netmiko)
  Downloading https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl (193kB)
    100% |################################| 194kB 2.4MB/s
Collecting textfsm (from netmiko)
  Downloading https://files.pythonhosted.org/packages/a1/0d/a1b490503545b3b4600b965eae5d44cc2b6ce27cfb44f4debc563dbb56d3/textfsm-0.4.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python3.5/dist-packages (from paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): bcrypt>=3.1.3 in /usr/local/lib/python3.5/dist-packages (from paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): pynacl>=1.0.1 in /usr/local/lib/python3.5/dist-packages (from paramiko>=2.0.0->netmiko)
Collecting cryptography>=1.5 (from paramiko>=2.0.0->netmiko)
  Downloading https://files.pythonhosted.org/packages/ec/b2/faa78c1ab928d2b2c634c8b41ff1181f0abdd9adf9193211bd606ffa57e2/cryptography-2.2.2.tar.gz (443kB)
    100% |################################| 450kB 1.4MB/s
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python3.5/dist-packages (from bcrypt>=3.1.3->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1 in /usr/local/lib/python3.5/dist-packages (from bcrypt>=3.1.3->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.1 in /usr/local/lib/python3.5/dist-packages (from cryptography>=1.5->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): asn1crypto>=0.21.0 in /usr/local/lib/python3.5/dist-packages (from cryptography>=1.5->paramiko>=2.0.0->netmiko)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.0.0->netmiko)
Installing collected packages: cryptography, paramiko, scp, pyyaml, pyserial, textfsm, netmiko
  Running setup.py install for cryptography ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x02kahmv/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p3yna2ee-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-x86_64-3.5/cryptography
    creating build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/mac.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/bindings
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends/openssl
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/twofactor
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives/asymmetric
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/bindings/openssl
    running egg_info
    writing src/cryptography.egg-info/PKG-INFO
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing top-level names to src/cryptography.egg-info/top_level.txt
    writing requirements to src/cryptography.egg-info/requires.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.5/_padding.c'
    creating build/temp.linux-x86_64-3.5
    generating cffi module 'build/temp.linux-x86_64-3.5/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-3.5/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-3.5/build
    creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/_openssl.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.linux-x86_64-3.5/_openssl.c:22:24: fatal error: pyconfig.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x02kahmv/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p3yna2ee-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-x02kahmv/cryptography/
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@NetworkAutomation-1:~#
root@NetworkAutomation-1:~# python3 netmiko1.py
Traceback (most recent call last):
  File "netmiko1.py", line 1, in <module>
    from netmiko import ConnectHandler
ImportError: No module named 'netmiko'
root@NetworkAutomation-1:~#

**Comment by ktbyers** [comment]
It looks like you are missing this header file that you need:

```
pyconfig.h: No such file or directory
compilation terminated.
```

**Comment by bdbrown69** [comment]
So after running  apt-get install python-dev libxml2-dev libxslt-dev

I then tried to install netmiko again and this time received a lot more errors it seems like. I'm new to this so any advice you can offer, I'm most grateful! (See below output)


root@NetworkAutomation-1:~# python3 -m pip install netmiko
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting netmiko
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 787, in _validate_conn
    conn.connect()
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7972881908>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 512, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 273, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 442, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 400, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 545, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 648, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 757, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@NetworkAutomation-1:~#

**Comment by bdbrown69** [comment]
Essentially I'm trying to run this script:

from netmiko import ConnectHandler

iosv_l2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.72',
    'username': 'bart',
    'password': 'cisco'
}

net_connect = ConnectHandler(**iosv_l2)
output = net_connect.send_command('sho ip int brief')
print (output)

config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print (output)

for n in range (11,21):
    print ("Creating VLAN " + str(n))
    config_commands = ['vlan database', 'vlan ' + str(n), 'name Pyton_VLAN ' + $
    output = net_connect.send_config_set(config_commands)
    print (output)


but when I run the script, this is all I get:

root@NetworkAutomation-1:~# python3 netmiko1.py
Traceback (most recent call last):
  File "netmiko1.py", line 1, in <module>
    from netmiko import ConnectHandler
ImportError: No module named 'netmiko'

and have been unsuccessful in getting netmiko installed!

**Comment by ktbyers** [comment]
Yes, you have some sort of an OS or connectivity issue that is preventing you from getting Netmiko installed.

Does installing any package via PIP work?

**Comment by Collisio-Adolebitque** [comment]
I'm getting the same issue, I have Internet access from the Network Automation container:

```
root@NetAutomate-1:~# curl www.pynet.twb-tech.com
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://advancedsearch2.virginmedia.com/main?ParticipantID=jqlc435patgs4w79dx7g33u8otdryt35&FailedURI=http%3A%2F%2Fwww.pynet.twb-tech.com%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=uk"/><script type="text/javascript">url="http://advancedsearch2.virginmedia.com/main?ParticipantID=jqlc435patgs4w79dx7g33u8otdryt35&FailedURI=http%3A%2F%2Fwww.pynet.twb-tech.com%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=uk";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>root@NetAutomate-1:~#
```
However I get the same error: 

![screen shot 2018-07-15 at 20 07 31](https://user-images.githubusercontent.com/25212666/42737589-e1337270-886d-11e8-9148-ca587290173f.png)

**Comment by ktbyers** [comment]
@Collisio-Adolebitque Great...thanks!

@bdbrown69 Does a similar process work for you?

**Comment by ktbyers** [comment]
So your process was (if I read it right...as I looked at it pretty quickly):

```
apt-get upgrade
apt-get install python3-venv
apt-get install python3-dev

pip3 install -U netmiko
```

**Comment by Collisio-Adolebitque** [comment]
@ktbyers Well, it just looks easy when you write it like that.  :-)

**Comment by bdbrown69** [comment]
Thank you all for your assistance and I apologize for not responding back earlier...work pulled me away!

Here are the steps I had to perform.

I first had to do the following:

nano /etc/apt/sources.list

Then uncomment the following two lines:

# deb http://archive.canonical.com/ubuntu xenial partner
# deb-src http://archive.canonical.com/ubuntu xenial partner

save the file, then: 

apt-get update
apt-get install python3-venv
apt-get install python3-dev

next type this:


python3 -m pip install netmiko


Now when I try to run my initial script I no longer get the 
ImportError: No module named 'netmiko'

I get this error which I'm try to troubleshoot:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 689, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 357, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 192.168.122.72

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netmiko1.py", line 10, in <module>
    net_connect = ConnectHandler(**iosv_l2)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 207, in __init__
    self.establish_connection()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 693, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios 192.168.122.72:22
root@NetworkAutomation-1:~#

**Comment by Collisio-Adolebitque** [comment]
Can you ping and SSH to the switch with IP: 192.168.122.72 from the network automation container?

**Comment by bdbrown69** [comment]
Ping and SSH work now!

It helps to double check the configuration on the switch...I had to enable SSH. Once that was done, the script was able to run successfully.

All - thanks again for your input and assistance! I've been in networking for a number of years and am now just learning Python and how it can help automate a lot of my daily tasks...I'm hooked!

**Comment by Jason-Engel** [comment]
> The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. 

Are you still seeing this issue?  I ended up reinstalling the GNS3 VM entirely because in every project I created, the folder/file permissions in the Network Automation docker belonged to "1000:1000" instead of "root:root"  

Type` ls -la` or `ll` into the Network Automation device and see if anything in the home directory belong to someone other than root.  This issue was recursive into folders like .ssh .gns3_perms and so forth.  Each time I'd start up, I would change the owner of those folders, but the 'fix' wouldn't persist.

**Comment by ktbyers** [comment]
@Jason-Engel Can you explain what your issue is? 

Is it a file-system permissions issue or is there something else going on?

**Comment by Jason-Engel** [comment]
What led me to reading this Issue/Discussion was actually caused by pip within the Network Automation appliance in GNS3 2.1.8, and not a netmiko issue directly.  (Pip was causing issues while I was trying to get netmiko up and running).  After reviewing the thread a bit more, what I was experiencing doesn't belong in a netmiko discussion per se.

While struggling with dependencies in the Network Automation appliance, so that I could get netmiko working, I was noticing that the appliance was launching with Linux file/folder permissions set to 1000:1000 instead of root:root which was causing ssh, apt and pip3 operations to fail.  Sorry for the confusion, and veering off-topic.

**Comment by vickyprabhat** [comment]
> Essentially I'm trying to run this script:
> 
> from netmiko import ConnectHandler
> 
> iosv_l2 = {
> 'device_type': 'cisco_ios',
> 'ip': '192.168.122.72',
> 'username': 'bart',
> 'password': 'cisco'
> }
> 
> net_connect = ConnectHandler(**iosv_l2)
> output = net_connect.send_command('sho ip int brief')
> print (output)
> 
> config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
> output = net_connect.send_config_set(config_commands)
> print (output)
> 
> for n in range (11,21):
> print ("Creating VLAN " + str(n))
> config_commands = ['vlan database', 'vlan ' + str(n), 'name Pyton_VLAN ' + $
> output = net_connect.send_config_set(config_commands)
> print (output)
> 
> but when I run the script, this is all I get:
> 
> root@NetworkAutomation-1:~# python3 netmiko1.py
> Traceback (most recent call last):
> File "netmiko1.py", line 1, in 
> from netmiko import ConnectHandler
> ImportError: No module named 'netmiko'
> 
> and have been unsuccessful in getting netmiko installed!

I am trying to run the same and it does not show any error related to import but it shows following error, which i am not able to understand properly neither i have found any solution to this.

root@UbuntuDockerGuest-1:~/temp# python3 netmikoo.py
  File "netmikoo.py", line 7
    'device type': 'cisco_ios',
                 ^
SyntaxError: invalid syntax


Here is my file netmikoo.py

from netmiko import ConnectHandler

def netmiko_connection(ip):
        return(
        'device type': 'cisco_ios',
        'ip': ip,
        'username': 'cisco',
        'password': 'cisco'}
list1 = {192.168.122.72,192.168.122.73}

for ip in list1:
        ios = netmiko_connection(ip)
        print(ios)
        print('connecting'+ ip)
        net_connect= ConnectHandler(**ios)
        output= net_connect.send_command('sh ip int brief')
        print(output)
