### ISSUE TITLE
Error: cannot import name connecthandler

### ISSUE THREAD

**Issue by ashokkatam** [ktbyers/netmiko#873]
Hi,

Hi i tried to use netmiko connecthandler in my python program but i am getting error that no module named connecthandler in netmiko. 

I installed git in ubuntu docker and downloaded netmiko by using 

$ git clone https://github.com/ktbyers/netmiko 
$ cd netmiko 
$ python setup.py install 

Still i am not able to use connecthanlder in my program. Can you please suggest me what needs to be done.

**Comment by smk4664** [comment]
Ashokkatam,
Did you try ConnectHandler, the module is case sensitive.

**Comment by ktbyers** [comment]
@ashokkatam You need to post your Exception stack trace and your code.
