### ISSUE TITLE
Cisco WLC send_config_set has excessive delays embedded in it

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#885]
It should be updated in a similar manner as base_connection.py was.

**Comment by carlmontanari** [comment]
wlc sleeps for delay factor * .5 -- whereas base connection sleeps for delay factor * .05

from my limited experience with controllers I think they are generally a bit more sluggish than a router/switch, but probably not this slow. given the recent tweaks we've been making I think we could probably just drop this to make it inline w/ the base connection. Thoughts?
