### ISSUE TITLE
Mellanox Switch add snmp autodetect

### ISSUE THREAD

**Issue by SharonYeuda** [ktbyers/netmiko#887]
Hi,

Can you please add Mellanox Switch to snmp_autodetect?

If you use  1.3.6.1.2.1.1.*1*.0 for Mellanox switch, you will receive
.1.3.6.1.2.1.1.1.0
= STRING: "*Onyx,MSN2410*,SWv3.6.6102"
But for other models you can get 1.3.6.1.2.1.1.1.0 = STRING: "*Mellanox *
MSN2700,MLNX-OS,SWv3.6.4112".
you can do regex to find  *Onyx,MSN2410* or  *Mellanox *and use
.1.3.6.1.2.1.1.*1*.0
Alternatively , you can use  1.3.6.1.2.1.1.*2*.0 and find  .*33049 * at the
result to identify Mellanox switches.
It's up to you.

Thanks.

**Comment by carlniger** [comment]
Going to close as this is almost a year old. Feel free to raise a PR on this if its still useful!
