### ISSUE TITLE
getting errors while running tests in test_netmiko_config.py in develop branch

### ISSUE THREAD

**Issue by mvsiva** [ktbyers/netmiko#892]
getting errors while running tests..

    def test_save_response(net_connect, commands, expected_responses):
        '''
        Test save config with the confirm response parameter.
        '''
        confirm_response = commands['save_config_response']
        save_verify = expected_responses['save_config']

>       cmd_response = net_connect.save_config(confirm_response=confirm_response)
E       TypeError: save_config() got an unexpected keyword argument 'confirm_response'

test_netmiko_config.py:135: TypeError

**Comment by ktbyers** [comment]
@mvsiva Yes, the develop branch has some issues on the save_config tests that I need to fix.

**Comment by ktbyers** [comment]
I would probably just comment out all of the `test_save_*` tests for now (in test_netmiko_config.py).

**Comment by mvsiva** [comment]
Think I have corrected test_netmiko_config.py as part of PR #893 . You can review and pull the changes if they are ok..

**Comment by mvsiva** [comment]
As save_config tests are now decoupled, closing this issue.
