### ISSUE TITLE
SSH to Aruba 2930 switch and enable snmpv3, error while waiting for string to come back

### ISSUE THREAD

**Issue by vigilne** [ktbyers/netmiko#895]
I am very new to python and scripting in general and I am connecting via ssh to an Aruba 2930F switch, I can ssh to the switch. When I send snmpv3 enable command to the switch it prompts you questions that the user must respond to in order to complete the snmpv3 setup in the command line. I keep getting error in waiting for the return string for the script to execute in order to move on with the rest of the script.

**From the cli it looks like this**
aruba_sw(config)# snmpv3 enable 
SNMPv3 Initialization process.
Creating user 'initial'
Authentication Protocol: MD5
Enter authentication password: **prompted here for string**
Privacy protocol is DES
Enter privacy password: **prompted here for string**
User 'initial' has been created
Would you like to create a user that uses SHA? [y/n] **prompted here for string**
User creation is done.  SNMPv3 is now functional.
Would you like to restrict SNMPv1 and SNMPv2c messages to have read only
access (you can set this later by the command 'snmpv3 restricted-access')? [y/n] **prompted here for string**
**************************************************************

my script to try and do this is below. My script does not work. What am I doing wrong? It errors out on line 12 with the first read_channel. I am sure I am doing something incorrectly. Any guidance is appreciated.

from netmiko import ConnectHandler
aruba_sw = {
    'device_type': 'hp_procurve',
    'ip': '172.16.2.5',
    'username': 'whatever',
    'password': 'whatever',
}

net_connect = ConnectHandler(**aruba_sw)

output = net_connect.send_command('snmpv3 enable')
output = net_connect.read_channel('Enter authentication password:')
output = net_connect.write_channel('somestring' + '\n')
output = net_connect.read_channel('Enter privacy password:')
output = net_connect.write_channel('somestring' + '\n')
output = net_connect.read_channel('[y/n]')
output = net_connect.write_channel('n' + '\n')
output = net_connect.read_channel('[y/n]')
output = net_connect.write_channel('y' + '\n')

with open('usal_snmparuba_commands.txt') as f:
    lines = f.read().splitlines()
print lines

output = net_connect.send_config_set(lines)
print output

net_connect.disconnect()

**Comment by mvsiva** [comment]
You should not be using read_channel and write_channel. Instead use send_command with expect_string. 
An example for a command which requires multiple user prompt is explained here in the below link. 

https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html

**Comment by NINJAX3X** [comment]
`import netmiko
from netmiko import ConnectHandler
import sys
import time

aruba_osswitch = {
                    "device_type": "aruba_osswitch",
                    "ip": "ip address",
                    "username": "username",
                    "password": "password",
                    "global_delay_factor" : 2,
                                                        }

net_connect = ConnectHandler(**aruba_osswitch)


commands = [
            'configure terminal',
            'snmpv3 enable',
            'initial',
            'initial',
            'n',
            'y',
                                                            ]

output = net_connect.send_multiline_timing(commands, multiline = True)

print(output)

print("\n""Done")

net_connect.disconnect()`

This code will work for the Aruba OS switches to enable SNMPv3 on it and will handle the prompts that comes with it
