### ISSUE TITLE
Netmiko list issue -unable to connect the multiple devices

### ISSUE THREAD

**Issue by smaheshggn** [ktbyers/netmiko#897]
Hello Ktbuyrs

I am running the below script to ssh the routers but when i am using the list script only pushes the config in device R2 .As per the script both devices should be connected.

please check and advise.

```python
from netmiko import ConnectHandler,redispatch

R1 = {
'device_type' : 'cisco_ios',
'ip' : '30.0.0.10',
'username' : 'cisco',
'password' : 'cisco',    
}
R2 = {
'device_type' : 'cisco_ios',
'ip' : '30.0.0.20',
'username' : 'cisco',
'password' : 'cisco',
}
routers = [R1,R2]
for routerslist in routers :
 net_connect = ConnectHandler(**routerslist)

config_commands = ['interface Loopback6','ip address 20.1.1.1 255.0.0.0']
output = net_connect.send_config_set(config_commands)
print output
```

**Comment by ktbyers** [comment]
FYI, I edited your original post to enclose it in triple backticks, but did not change the indentation from what you posted.

**Comment by ktbyers** [comment]
Given the above, it looks like that only this line is inside the for-loop:

```
for routerslist in routers :
 net_connect = ConnectHandler(**routerslist)
```

These lines are outside the for-loop so they will only be executed on the last device (i.e. whichever device was last in the for-loop):

```
config_commands = ['interface Loopback6','ip address 20.1.1.1 255.0.0.0']
output = net_connect.send_config_set(config_commands)
print output
```

You need to put all of those lines inside the for-loop.

Also please make sure you use four-spaces for indentation.

**Comment by smaheshggn** [comment]
Thanks Ktbuyrs

i have done correction in identation and it works fine now.
