### ISSUE TITLE
IOError: Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by KSBolton** [ktbyers/netmiko#898]
Hello all.

I've been using Paramiko in order to automate the backups of Cisco Catalyst and SGx00 switches and I'd like to translate that into Netmiko for cleaner code. It seemed to have worked fine for the SGx00 side of it but I'm facing an issue when I try for my Catalyst devices.

Code is as follows:

`with open('LP_Cat_Sw.txt', 'r') as ff:
	Cat_IPs = ff.read().splitlines()	
for ip2 in Cat_IPs:

	now = datetime.datetime.now()
	strtime = now.strftime("%Y-%m-%d_%H%M")

	cat_sw1 = {
		'device_type': 'cisco_ios',
		'ip': ip2,
		'username': username,
		'password': password,
		# 'secret': secret,
	}

	# if ip2 == "10.0.99.10" or ip2 == "10.0.99.6":
	# 	is_core = "yes"

	net_connect = ConnectHandler(**cat_sw1)
	# time.sleep(3)
	# net_connect.clear_buffer()
	# print(net_connect.base_prompt)
	# nameit = net_connect.find_prompt()
	# devname = nameit[:-1]
	devname = net_connect.base_prompt

	# if is_core == "yes":
	# 	net_connect.enable()

	output = net_connect.send_command("copy running-config <tftp server path>" + devname + "/" + devname + "_" + strtime + ".cfg")
	print output

	lg = open("py_lp_logging.log","a+")
	lg.write(output)`

It results in the error:
IOError: Search pattern never detected in send_command_expect: WGL\-LP1\# even though my prompt SHOULD say WGL-LP1.

As you can probably see, I've tried a couple fixes I've seen suggested on here, but to no avail. Could someone please point me in the right direction?

**Comment by mvsiva** [comment]
does copy command in catalyst requires any confirmation??

**Comment by KSBolton** [comment]
Oh, yes. That's a great point @mvsiva 

Ok, I amended it to look like this:

`output = net_connect.send_command("copy running-config <tftp server path>" + devname + "/" + devname + "_" + strtime + ".cfg")
output = net_connect.send_command("\n")
time.sleep(0.2)
output = net_connect.send_command("\n")`

It still seems to throw the same error. There's a long pause in which I assume send_command_expect is searching for the prompt and then the IOError shows up. Is there another way to answer confirmation messages in Netmiko?

**Comment by mvsiva** [comment]
you will need to use send_command_timing in that case. Please refer to Issue #846 for more details..

**Comment by KSBolton** [comment]
Currently trying send_command_timing like this:
```
output = net_connect.send_command_timing("copy running-config <tftp server path>" + devname + "/" + devname + "_" + strtime + ".cfg")
if "Address or name" in output:
  output += net_connect.send_command_timing("\n")
  if "Destination filename" in output:
    output += net_connect.send_command_timing("\n")
```

This prints the two confirm prompts but doesn't actually copy the running-config. Looking into what could be causing that.

**Comment by mvsiva** [comment]
if you want to avoid confirmation for copy command, you can issue this command before.
router(config)#file prompt quiet

**Comment by KSBolton** [comment]
Success. I'm showing my novice here, I didn't add a disconnect to the Netmiko object so it does the file copy. Now my only issue is the logging. I usually wrote to a log file the results of the copy that you'd normally see at command line. Now the log is now only including the confirmation message "Address or hostname of remote host...". 

I imagine that has to do with send_command_timing and the use of +=. Does that make sense?

As for file copy confirmation, I'm afraid that has to remain. I could do it then negate it after the fact but I created a specific account for these backups to avoid it having any access to global config.

**Comment by ktbyers** [comment]
The issue is that Netmiko doesn't know that the command is done. By default Netmiko is waiting for the trailing router prompt to come back to determine the command is done. You can change this behavior by using the `expect_string` argument, see this example here:

https://github.com/ktbyers/netmiko/blob/develop/examples/use_cases/case4_show_commands/send_command_expect.py

Note, expect_string takes a regular expression pattern so your probably should use a raw Python string and you should be careful with respect to using special regular expression characters.

You will need to use the expect_string argument to handle the confirmation prompt that the Catalyst is sending.

Let me know if this works.

I talk about issues around this in this article:

https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html

**Comment by KSBolton** [comment]
@ktbyers Thank you! The documents you shared cleared up a lot of confusion. I've been able to get both the commands and logging working without issue. I can now appreciate the delay factor as well. Thank you again.
