### ISSUE TITLE
Console Server Login via Console Port

### ISSUE THREAD

**Issue by bgile** [ktbyers/netmiko#909]
Hello

I have been looking all over with no luck as to whether I can telnet to a console server with a specific port so I can access devices in my lab.  I have noticed there is a terminalserver driver, but I couldn't find much on it.  I also saw in BaseConnection there is some serial_settings, but the 'read the docs' page didn't have any info on it.  What I am looking to do is this:

telnet exmaple.com 2121  -- where 2121 is the port on the console server I need to access

Anything you can point me to would be appreciated.

**Comment by ktbyers** [comment]
Use a device_type='generic_termserver_telnet' and port=2121 in your ConnectHandler arguments.

**Comment by bgile** [comment]
Thanks for the update.  Added that into my code but my command is returning None.  

When logging into my console server, once you are in you then need to enter in another set of admin and password for the juniper device.  

Here is the code I am using:

def console_connect (host, username, password, admin_pass):
    '''Make connection to the console server on a particular port'''
    console = {
            'device_type': 'generic_termserver_telnet',
            'ip': host,
            'username': username,
            'password': password,
            'port': '2002'
        }
    net_connect = ConnectHandler(**console)
    print("LOGIN Successful **\n")
    net_connect.write_channel('\r')
    time.sleep(1)
    net_connect.write_channel('\r')
    time.sleep(1)
    print("Entering in the admin username **\n")
    net_connect.write_channel('admin' + '\n')
    print("Entering in the admin password **\n")
    net_connect.write_channel(admin_pass + '\n')
    output = net_connect.write_channel('show version' + '\n')

    print(output)

def main ():
    username = input("what is the username to the console server? --> ")
    password = getpass("What is the password to the console server? -->")
    admin_pass = getpass("what is the admin password --> ")
    console_connect('198.27.200.30', username, password, admin_pass)

if __name__ == "__main__":
        main()

**Comment by ktbyers** [comment]
Yes, you won't be able to do that:

```
    output = net_connect.write_channel('show version' + '\n')
    print(output)
```

You are not reading anything back from the device. Your output there is from the output of `write_channel`. Also you really shouldn't be using write_channel/read_channel for anything beyond handling the login process.

**Comment by bgile** [comment]
Normally I would use send_command, but there was always exception issues.

I apologize that I am not understanding how this is suppose to work when using this specific device_type.  
After the device connection, should I be able to switch over to using send_command to pass the admin and admin_pass?

**Comment by ktbyers** [comment]
@bgile So assuming that I am understanding correctly what you are doing. I would try this:

1. Add a session_log so you can see better what is happening.

```
    console = {
            'device_type': 'generic_termserver_telnet',
            'ip': host,
            'username': username,
            'password': password,
            'port': '2002',
            'session_log': 'output_file.txt',
        }
```

2. Change this:

```
    output = net_connect.write_channel('show version' + '\n')
    print(output)
```

To this (to see where we are at)

```
    output = net_connect.find_prompt()
    print(output)
```

Regards, Kirk

**Comment by bgile** [comment]
@ktbyers 

Not sure if it would be better to call std_login directly? I tried myself with no luck but maybe it can be used differently?

`class TerminalServerTelnet(TerminalServer):
    """Generic Terminal Server driver telnet."""
    def telnet_login(self, *args, **kwargs):
        # Disable automatic handling of username and password when using terminal server driver
        pass

    def std_login(self, *args, **kwargs):
        return super(TerminalServerTelnet, self).telnet_login(*args, **kwargs)`

It really seems like the first definition is passing the base connection username and password and then telnet_login happens and it tries to use my secondary username and password for the Juniper device instead based on the output file.  Thoughts?

**Comment by ktbyers** [comment]
Yes, usually I will step through the login process...step-by-step. By this I will use writes and reads to make sure I am getting the 'login' request, and the 'Password' request and sending the right information at the right time.

A lot of times I couple this with loops (i.e. the timing can get out sync so loops can help to make sure you only move on if you are in the right state).

You very likely need to sleep between these two actions as your program will be faster than the network device:

```
    print("Entering in the admin username **\n")
    net_connect.write_channel('admin' + '\n')
    print("Entering in the admin password **\n")
    net_connect.write_channel(admin_pass + '\n')
```

You can try to call the telnet_login(), but you would have to do a few things to call it.

Here is the telnet_login signature (in cisco_bas

```python
    def telnet_login(self, pri_prompt_terminator=r'#\s*$', alt_prompt_terminator=r'>\s*$',
                     username_pattern=r"(?:user:|username|login|user name)", pwd_pattern=r"assword",
                     delay_factor=1, max_loops=20):
```

Note, the std_login and telnet_login are disabled in the terminal_server driver class itself (as terminal servers have a huge variety in the login process). So you would need to call the parent class...I can show you how to do this (if you are still working on it).

**Comment by bgile** [comment]
I'm still interested in making this work with Netmiko. I can try some loops to match on read output, it's not a bad idea.   I'm still a little puzzled why in the session logging I never see the username and password from the device_type dictionary entered in.

I'll try out calling the parent class if you want, I'm open to anything. 

Thanks,

**Comment by bgile** [comment]
@ktbyers 

So I have narrowed this down to a terminal issue.  I never got past the first conditional as I suspected was the case so decided to tcpdump the session and upon looking at the TELNET data I see this from the console server: Won't Terminal Type, meaning the sender is refusing to send terminal information. 

This I believe is linked to telnetlib, which kind of explains why I couldn't get telnetlib to work on its own when I was testing without netmiko.  I can use telnetlib if it's just straight port 23, but any other port seems to have issues. 

Any thoughts?

**Comment by cgruelle** [comment]
I had a similar issue trying to telnet to an Avaya/Nortel switch. Telnetlib
responds to all options with don’t or won’t, but It has the ability to set
a callback function to set the options you need. I needed to tell the
switch to “DO ECHO” in order for netmiko to read any data.

**Comment by ktbyers** [comment]
@cgruelle Can you link to your code that you were using for that? I think that might help @bgile.

**Comment by cgruelle** [comment]
@ktbyers @bgile 
Here is the code I am using.

Setup the callback here
https://github.com/cgruelle/netmiko/blob/45ab2ff5a6ad1adf44002ca65f6821bce09186b1/netmiko/avaya/avaya_ers.py#L61-L65

The callback function
https://github.com/cgruelle/netmiko/blob/45ab2ff5a6ad1adf44002ca65f6821bce09186b1/netmiko/avaya/avaya_ers.py#L169-L172

**Comment by bgile** [comment]
Ok this gives me something to mess around with.  Plenty of other people experiencing the same issue and using the callback function so I have some more examples to look at to make this work.  I'm not looking to do any class work in this script, trying to keep it really simple since its just for ansible to use for a quick initial login and IP config for an interface so I can get IP reachability.

Thanks I feel we are good to close this issue @ktbyers Hopefully if anyone experiences this issue this thread will help.
