### ISSUE TITLE
 If config_commands contains Chinese, Chinese will become a empty character after execution

### ISSUE THREAD

**Issue by labulaka521** [ktbyers/netmiko#914]
```
>>>d = ['ldap server ldap', 
          'login-dn cn=test,ou=opsa,ou=运维开发,ou=后端开发,ou=技术部,ou=domain,dc=domain-inc,dc=local', 
          'search-base-dn ou=opsa,ou=运维开发,ou=后端开发,ou=技术部,ou=domain,dc=domain-inc,dc=local',
         'ip 10.120.100.100', 'login-password  sim 1234567', 'user-parameters user-name-attribute samaccountname', 'ldap scheme ldap', 'authentication-server ldap', 'domain test', 'authentication login ldap-scheme ldap', 'authorization login none', 'accounting login none', 'role default-role enable']
>>>net_connect.send_config_set(d)
```
return result

```
'system-view\nSystem View: return to User View with Ctrl+Z.\n
[SJSD-WW-6800]ldap server ldap\n
[SJSD-WW-6800-ldap-server-ldap]
login-dn cn=test,ou=opsa,ou=,ou=,ou=,ou=domain,dc\n=domain-inc,dc=local\n
[SJSD-WW-6800-ldap-server-ldap]search-base-dn ou=opsa,ou=,ou=,ou=,ou=domain,dc=d\nomain-inc,dc=local\n
[SJSD-WW-6800-ldap-server-ldap]ip 10.120.100.100\n
[SJSD-WW-6800-ldap-server-ldap]login-password  sim 1234567\n
[SJSD-WW-6800-ldap-server-ldap]user-parameters user-name-attribute samaccountnam\ne\n
[SJSD-WW-6800-ldap-server-ldap]ldap scheme ldap\n
[SJSD-WW-6800-ldap-ldap]authentication-server ldap\n
[SJSD-WW-6800-ldap-ldap]domain test\n
[SJSD-WW-6800-isp-test]authentication login ldap-scheme ldap\n
[SJSD-WW-6800-isp-test]authorization login none\n
[SJSD-WW-6800-isp-test]accounting login none\n
[SJSD-WW-6800-isp-test]role default-role enable\n
[SJSD-WW-6800]return\n<SJSD-WW-6800>'
```
chinese become a  empty character
```
<SJSD-WW-6800>display current-configuration configuration ldap-server
#
ldap server ldap
 login-dn cn=test,ou=opsa,ou=,ou=,ou=,ou=domain,dc=domain-inc,dc=local
 search-base-dn ou=opsa,ou=,ou=,ou=,ou=domain,dc=domain-inc,dc=local
 ip 10.120.100.100
 login-password cipher $c$3$1iaGanaJ9owLPJSpox99TkLe5ky7d0o+Jtc=
 user-parameters user-name-attribute samaccountname
#
ldap server ldap'
#
return
```

**ou=运维开发,ou=后端开发,ou=技术部**    -->
**ou=,ou=,ou=**

**Comment by ktbyers** [comment]
You probably need to turn on the Netmiko session_log and see what Netmiko actually configures. I don't think I modify that in Netmiko (i.e. I don't think I do any modification of send_config_set except for possibly what is used for the enter character at the end of the line).


I assume you are using Python3.

Add session_log='some_file.txt' to your ConnectHandler call and that should show you what happened in the SSH session.

**Comment by labulaka521** [comment]
@ktbyers firstly,thanks you replay me,yes, I use python3,
 next, the execution of my tracking code found out why chinese becode empty, look 
this url [https://github.com/ktbyers/netmiko/blob/develop/netmiko/utilities.py#L165](url) ,when variable out_data contain chinese,it will return result and chinese will be instead empty character.
I see ascii only display letter digital and Punctuation on wiki, i think this is why chinese become empty character,
so after i change  `out_data.encode('ascii', 'ignore')` to  `return out_data.encode('utf-8')` , it meet my expected results

**Comment by labulaka521** [comment]
if you agree me, i want to pr for you, thanks you

**Comment by ktbyers** [comment]
@labulaka521 Yes, agreed...that is a problem. Yes, please submit a PR on it.

Thanks.

**Comment by ktbyers** [comment]
This was fixed earlier.
