### ISSUE TITLE
'show log' returns: '% Incomplete command.' error

### ISSUE THREAD

**Issue by moemanson** [ktbyers/netmiko#915]
The ssh access is confirmed success and other commands are working normally. But the command show log is not going through for some reason:
Here is the line that I am using:
output = ssh_sess.send_command("show log")

and I have tried this too, and it gives the same error:
output = ssh_sess.send_command_expect("show log")

Any advice?

**Comment by ktbyers** [comment]
`% Incomplete command` is from the relevant networking device (so the command you sent is invalid for some reason on your platform).

What does 'show log' manually executed using SSH on this device show you. Also make sure you have the proper privilege level.

For example, on Cisco IOS, I get this if I am at privilege level1:

```
pynet-rtr1>show log
% Incomplete command.

pynet-rtr1>
```

**Comment by moemanson** [comment]
@ktbyers 
You are right ! 
the problem was that the command 'show log' requires the Privileged EXEC mode. So I needed to execute the command enable and then provide the password and finally execute the '' command successfully.
Here is it:
I was just doling: 

ssh_sess= ConnectHandler(**cisco_881)
output = ssh_sess.send_command("show log")

Which was giving the '% Incomplete command' error, and to overcome that I needed to do:

ssh_sess= ConnectHandler(**cisco_881)
pass_example = 'some_pass'
output = net_connect.send_command_timing('enable')
if 'Password:' in output:
    output += net_connect.send_command_timing(pass_example)
output = ssh_sess.send_command("show log")

and to confirm we can use the command:
output = net_connect.send_command("show privilege")
print(output)
