### ISSUE TITLE
NetMikoAuthenticationException on SunOS ssh.server 5.10

### ISSUE THREAD

**Issue by bboylord** [ktbyers/netmiko#916]
I am trying to connect to a server "SunOS ssh.server 5.10" using SSH and I always have an authentication failed exception, through putty I can connect to Putty's log attachment and Netmiko's log. If you can help me identify the issue I'm committing, I'd appreciate it.

Netmiko Log:

DEBUG:paramiko.transport:starting thread (client mode): 0x2b9edd0L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.0.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Sun_SSH_1.1.4
INFO:paramiko.transport:Connected (version 2.0, client Sun_SSH_1.1.4)
DEBUG:paramiko.transport:kex algos:[u'gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes128-cbc', u'arcfour', u'3des-cbc', u'blowfish-cbc'] server encrypt:[u'aes128-ctr', u'aes128-cbc', u'arcfour', u'3des-cbc', u'blowfish-cbc'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib'] server compress:[u'none', u'zlib'] client lang:[u'en-CA', u'en-US', u'es', u'es-MX', u'fr', u'fr-CA', u'i-default'] server lang:[u'en-CA', u'en-US', u'es', u'es-MX', u'fr', u'fr-CA', u'i-default'] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-md5
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.10.10.10: e4c539c6426fa5513718ca969c14909e
DEBUG:paramiko.transport:userauth is OK
**INFO:paramiko.transport:Authentication (password) failed.**
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:paramiko.transport:starting thread (client mode): 0x2c4edb0L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.0.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Sun_SSH_1.1.4
INFO:paramiko.transport:Connected (version 2.0, client Sun_SSH_1.1.4)
DEBUG:paramiko.transport:kex algos:[u'gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes128-cbc', u'arcfour', u'3des-cbc', u'blowfish-cbc'] server encrypt:[u'aes128-ctr', u'aes128-cbc', u'arcfour', u'3des-cbc', u'blowfish-cbc'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib'] server compress:[u'none', u'zlib'] client lang:[u'en-CA', u'en-US', u'es', u'es-MX', u'fr', u'fr-CA', u'i-default'] server lang:[u'en-CA', u'en-US', u'es', u'es-MX', u'fr', u'fr-CA', u'i-default'] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-md5
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.10.10.10: e4c539c6426fa5513718ca969c14909e
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) failed.
DEBUG:paramiko.transport:EOF in transport thread

Log with Putty:

2018-08-14 19:13:20	Looking up host "10.10.10.10"
2018-08-14 19:13:20	Connecting to 10.10.10.10 port 22
2018-08-14 19:13:20	We claim version: SSH-2.0-PuTTY_Release_0.67
2018-08-14 19:13:21	Server version: SSH-2.0-Sun_SSH_1.1.4
2018-08-14 19:13:21	Using SSH protocol version 2
2018-08-14 19:13:21	Doing Diffie-Hellman group exchange
2018-08-14 19:13:21	Doing Diffie-Hellman key exchange with hash SHA-1
2018-08-14 19:13:21	Host key fingerprint is:
2018-08-14 19:13:21	ssh-rsa 1024 e4:c5:39:c6:42:6f:a5:51:37:18:ca:96:9c:14:90:9e
2018-08-14 19:13:21	Initialised AES-128 SDCTR client->server encryption
2018-08-14 19:13:21	Initialised HMAC-SHA1 client->server MAC algorithm
2018-08-14 19:13:21	Initialised AES-128 SDCTR server->client encryption
2018-08-14 19:13:21	Initialised HMAC-SHA1 server->client MAC algorithm
2018-08-14 19:13:22	Using SSPI from SECUR32.DLL
2018-08-14 19:13:22	Attempting GSSAPI authentication
2018-08-14 19:13:22	GSSAPI authentication initialisation failed
2018-08-14 19:13:22	The target was not recognized.
2018-08-14 19:13:22	Attempting keyboard-interactive authentication
**2018-08-14 19:13:22	Access granted**
2018-08-14 19:13:22	Opening session as main channel
2018-08-14 19:13:22	Opened main channel
2018-08-14 19:13:22	Allocated pty (ospeed 38400bps, ispeed 38400bps)
2018-08-14 19:13:22	Started a shell/command

Netmiko Script:

from netmiko import ConnectHandler

import logging
logging.basicConfig(filename='Debug_log.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

ipadd = '10.10.10.10'
username = 'jumpserver'
password = 'jumpserver'

device = {}
device['ip'] = ipadd
device['device_type'] = 'terminal_server'
device['username'] = username
device['password'] = password

print "Connecting using linux (" + ipadd + ")\n"
net_connect = ConnectHandler(**device)

hostname = net_connect.find_prompt()
command_result = net_connect.send_command("uname -a")
print command_result

**Comment by ktbyers** [comment]
Probably should use a device_type = 'linux' (at least that is probably the best guess).

The failure above indicates a password failure. If the Sun Server is going to be a jump server, you should look at this and see it works from an SSH proxy perspective.

https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

**Comment by carlniger** [comment]
inactive. closing.
