### ISSUE TITLE
Transferring IOS file to multiple devices at same time

### ISSUE THREAD

**Issue by chiragvyas50** [ktbyers/netmiko#917]
First of all, Thank you very much for your great explanation about the function that you have created!
The code that you have put under file "asa_upgrade.py" is perfect if we want to push IOS to device one by one. 
What is the best way to just push IOS to multiple devices at same time?

**Comment by ktbyers** [comment]
You should look to use Nornir with the netmiko_file_transfer plugin.

**Comment by chiragvyas50** [comment]
Thanks Kirk!
Do you have any document/URL that i can refer to?

**Comment by ktbyers** [comment]
@chiragvyas50 Probably need to read this:

https://pynet.twb-tech.com/blog/nornir/intro.html

Then here is some reference code:

https://github.com/ktbyers/nornir_test/blob/attributes_refactor/nornir_test/netmiko_examples/case3_file_transfer/netmiko_file_transfer.py

Note the inventory in that directory is for Nornir 2.0 so it will be a bit different than what is referenced in the article.

**Comment by chiragvyas50** [comment]
Thanks Kirk for this info!

I will go through these docs and will let you know how things goes on my end! We are actually planning to do IOS upgrade on Multiple Cisco devices/location so trying to setup Script/Process that helps best for organization environment.
