### ISSUE TITLE
HP Procurve no page and enable issues

### ISSUE THREAD

**Issue by jbhowerton** [ktbyers/netmiko#919]
Hi there,

 I'm a network engineer dabbling in python for automation and love it.  I've hit a bit of a snag with some HP Procurves.

According to the netmiko debug, the netmiko:read_channel: is stuck in a loop.  The issue is this:

On this particular HP (any many others I will run this script on), the 'no page' command built into netmiko will not execute in non-enable mode, so paging doesn't get turned off and the output hangs on the page alert "-- MORE --, next page: Space, next line: Enter, quit: Control-C" .  To solve it, I need to do one of the following:

Get to enable mode and then manually run the 'no page' command:

I've tried this with net_connect.enable() and it passes the 'manager' as the username, i need it to pass the username specified in the device dictionary because enable mode is tied to TACACS, is this possible?  

OR

Send the 'space bar' command when the output hits this snag so the output can continue.

OR 

Change terminal length settings?  it seems that this is erroring out in the logs as well but I'm not sure

Attached is my code and netmiko log.  The read_channel starts looping after the "show system" command is sent.   Thanks!

[netmiko.log](https://github.com/ktbyers/netmiko/files/2291959/netmiko.log)

[hp_login.txt](https://github.com/ktbyers/netmiko/files/2291954/hp_login.txt)

**Comment by ktbyers** [comment]
We have this currently for the HP ProCurve driver:

```
     def enable(self, cmd='enable', pattern='password', re_flags=re.IGNORECASE,
                 default_username='manager'):
```

So you could call:

```
net_connect.enable(default_username='whatever')
```

I can hard-code the enable() call to happen automatically on login (as I need paging to be disabled automatically).

But I think the logical choice would probably be to use 'manager' for the username (as opposed to using the SSH username). That wouldn't work in your case, but I suspect that is the more common case.

Just let me know if you disagree however. As my ProCurve experience/knowledge is limited so I am definitely making assumptions on which case is more common.

That would force you into manually calling enable (as per what I posted above) after login.

Does that make sense?

**Comment by carlniger** [comment]
Looks like this is as sorted as it can be at the moment :) Closing!
