### ISSUE TITLE
DEBUG:paramiko.transport:Global request denied.

### ISSUE THREAD

**Issue by Wallpix** [ktbyers/netmiko#925]
I have a script which uploads (via netmiko scp) a file to a devices.
As soon as the SCP is completed and the script proceeds to disable the “ip scp server” on the device, I hit an “ssh connection timeout” traceback issue related to the router’s “line vty exec-timeout” being shorter than the time it takes to upload the file to the device. (paramiko/channel.py", line 1170, in _send  raise socket.error('Socket is closed') ).

I then turned-on netmiko keepalive (30 seconds as a test with a device line vty timeout of 2 minutes) hoping to maintain the ssh connection alive in background while the transfer is happening.
Unfortunately, as seen in the netmiko debug, during the scp file transfer, “paramiko.transport” sends me a “Global request denied” message for each keepalive sent. As a result, the ssh connection has timed out and I still get a traceback.

DEBUG:netmiko:config term
Enter configuration commands, one per line.  End with CNTL/Z.
AUTO-LAB-SWT01(config)#ip scp server enable
AUTO-LAB-SWT01(config)#end
AUTO-LAB-SWT01#
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Global request denied.
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Global request denied.
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:Global request denied.
DEBUG:paramiko.transport:Sending global request "keepalive@lag.net"
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:EOF in transport thread

Any idea why paramiko I receive Global request denied from paramiko transport?
Is there a better way to proceed?

```
device_info = {'device_type': Dev_type, 'ip': device, 'username': username, 'password': password, 'keepalive' : 30}
ssh_dev_connection = ConnectHandler(**device_info)

[Omiited lines]

with FileTransfer(ssh_dev_connection, source_file=New_Image, dest_file=dest_image_name,
                  file_system=file_sys) as scp_transfer:
    if not scp_transfer.check_file_exists():
        if not scp_transfer.verify_space_available():
            msg = 'Insufficient space available on remote device'
           OK_to_Go = False
            return msg, OK_to_Go, The_outputs
        #
        # Enabling SCP
        ena_output = device_scp_handler(ssh_dev_connection, mode='enable')
        #
        # Transferring file
        scp_transfer.transfer_file()
        scp_output = '\nSCP Transfer of ' + dest_image_name + ' on ' + file_sys + ' completed'
        #
        # Disabling SCP
        dis_output = device_scp_handler(ssh_dev_connection, mode='disable')
```

**Comment by ktbyers** [comment]
@Wallpix yes, I don't know what is causing that.

Probably the easy fix is just have your script set the exec-timeout to a large value and then re-set it when your file transfer is done.

**Comment by Wallpix** [comment]
Yeah that's what we did but were wondering if there was a cleaner way.  Thanks.

**Comment by ktbyers** [comment]
Yes, unfortunately some of these SSH issues get really difficult to debug. 

And a lot of time the answer is the network vendor is really doing something they shouldn't be doing with no real fix to it.
