### ISSUE TITLE
I cannot install netmiko in python3 (ubuntu 16.04)

### ISSUE THREAD

**Issue by e-thibault** [ktbyers/netmiko#927]
I initially reprted my issue in issue #733 which was closed so I report it in a new issue :

as suggested in issue #733 I have issued :
python3 -m pip install netmiko
I had the reply :
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;file='/tmp/pip-build-za4f6yn5/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(file).read().replace('\r\n', '\n'), file, 'exec'))" install --record /tmp/pip-o9fehnkx-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-za4f6yn5/cryptography/

and also :
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

I upgraded pip using : pip install --upgrade pip
the upgrade work but after I still have the same message :
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

and when I want to check If I have netmiko for python3 I get :

thibault@R2D2compact:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.

from netmiko import ConnectHandler
Traceback (most recent call last):
File "", line 1, in 
ImportError: No module named 'netmiko'

what should I do then to have netmiko for python3 ?

**Comment by e-thibault** [comment]
later on I tried the command :
pip3 install netmiko

among the output I get :
...
creating build/temp.linux-x86_64-3.5/build
  creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/_openssl.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/_openssl.o -Wconversion -Wno-error=sign-conversion
  build/temp.linux-x86_64-3.5/_openssl.c:498:30: fatal error: openssl/opensslv.h: Aucun fichier ou dossier de ce type
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
Installing collected packages: pycparser, cffi, six, pynacl, idna, asn1crypto, cryptography, bcrypt, pyasn1, paramiko, scp, pyyaml, pyserial, textfsm, netmiko
  Running setup.py install for cryptography ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-snvcap61/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ysofmyk1-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-x86_64-3.5/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-x86_64-3.5/cryptography
    creating build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-x86_64-3.5/cryptography/x509
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/bindings
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-x86_64-3.5/cryptography/hazmat/backends
    creating build/lib.linux-x86_64-3.5/cryptography/hazmat/primitives
...

with :
"  Failed building wheel for cryptography"
in red

and at the end :
...
    creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/_openssl.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.linux-x86_64-3.5/_openssl.c:498:30: fatal error: openssl/opensslv.h: Aucun fichier ou dossier de ce type
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-snvcap61/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ysofmyk1-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-snvcap61/cryptography/

with:
"Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-snvcap61/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ysofmyk1-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-snvcap61/cryptography/"
in red

**Comment by ktbyers** [comment]
It looks like you are missing:

```
fatal error: openssl/opensslv.h
```

You will need to fix that (probably using apt-get) and get the cryptography library to properly install.

**Comment by e-thibault** [comment]
OK thanks for the hint.

searching google for "ubuntu 16.04 how to get openssl/opensslv.h"
it return the url :
https://askubuntu.com/questions/797351/fatal-error-openssl-opensslv-h-no-such-file-or-directory-compiling-mitmproxy

where it was advised :
Install openssl : sudo apt-get update && sudo apt-get install libssl-dev

which I did that solved the issue :

thibault@R2D2compact:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from netmiko import ConnectHandler
>>> 

Thanks a lot
Thibault
