### ISSUE TITLE
Add a way in send_command to send a list of commands

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netmiko#928]
This would work better with Nornir

Also potentially allow there to be a list of regex patterns that can be matched i.e. command one matches regex1, command2 matches regex2, et cetera.

If only a single regex pattern is specified then all commands are executed and match occurs at the end.

Also update send_command_timing to allow a list of commands.

**Comment by AndersBallegaard** [comment]
If no one is working on this i would like to do it

**Comment by ktbyers** [comment]
@AndersBallegaard I started working on this here in this PR https://github.com/ktbyers/netmiko/pull/939

I think it is mostly done except I need to write unit tests for it .

**Comment by carlniger** [comment]
Going to close and can carry on in #939 !   (🌮 <- I just realized I could use this emoji in GitHub markdown. that is unrelated but its exciting to me!)
