### ISSUE TITLE
vlan database in Cisco Router

### ISSUE THREAD

**Issue by farhanahmed77** [ktbyers/netmiko#935]
I am using the Cisco 3745 Multi-service router in GNS3 and creating vlans.
To create vlans I need to send these commands in priv exec mode.

```
S3#vlan database
S3(vlan)#vlan 10 name my_vlan
VLAN 10 added:
    Name: my_vlan
S3(vlan)#exit
S3#
```

I am using the below code with NETMIKO:

```
for n in range (2,21):
   print "Creating VLAN " + str(n)
   config_commands = ['vlan database', 'vlan ' + str(n) + ' name Python_VLAN_' + str(n)]
   output = net_connect.send_config_set(config_commands)
   print output 
```

The problem is that if I use **.send_config_set** it will enter the config mode, whereas the vlan database command works in exec mode.

If I use **.send_command**

```
config_commands = ['vlan database', 'vlan ' + str(n) + ' name Python_VLAN_' + str(n)]
output = net_connect.send_command(config_commands)

```
the code doesn't work and I have to ctrl+c to stop the script.

It seems that the code is executed and as it enters the "vlan database" mode it is unable to execute the next commands.

**Comment by ktbyers** [comment]
@farhanahmed77 Probably the easiest solution is to use the config_mode_command argument to send_config_set.

```python
config_commands = ['vlan Python_VLAN_10',]
output = net_connect.send_config_set(config_commands, config_mode_command='vlan database')
```

Let me know if that works.

**Comment by farhanahmed77** [comment]
@ktbyers 
Thanks that worked.
So, we are specifying manually the config mode to '**vlan database**' instead of **conf t**.

**Comment by ktbyers** [comment]
Yes, you can override the default command (for going into config mode).

**Comment by farhanahmed77** [comment]
Alright Thanks.

**Comment by pdeizel** [comment]
kt, can you help a brother out. I am using Cisco 3640's for my GNS3 work, and I am also having issues with the priv mode vlan database.
------------------------------------------------------------


from netmiko import ConnectHandler

newlib = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.72',
    'username': 'patrick',
    'password': 'cisco'
}

net_connect = ConnectHandler (**newlib)

for n in range (2,21):
    print ("Creating VLAN " + str(n))
    config_commands = ['vlan ' + str(n) + ' name Python_VLAN_' + str(n)]
    output = net_connect.send_config_set(config_commands, config_mode_command='vlan database')
    print(output)

**Comment by asirajahmed** [comment]
Well, here is the exact solution which works
------------------------------------------------------

from netmiko import ConnectHandler

iosv_l2 = {
        'device_type': 'cisco_ios',
        'ip': '192.168.122.51',
        'username': 'siraj',
        'password': 'cisco',
}

net_connect = ConnectHandler(**iosv_l2)

config_commands = ['vlan 11 name Python_VLAN_11', 'exit']
output = net_connect.send_config_set(config_commands, config_mode_command='vlan database')

------------------------------------------------------------------------------------------------------
