### ISSUE TITLE
RFE - setting custom missing key policy

### ISSUE THREAD

**Issue by merlinthp** [ktbyers/netmiko#936]
Currently netmiko allows us to choose between the AutoAdd and Reject missing key policies using the ssh_strict flag.  I'd like to be able to supply my own missing key policy handler.  I'd want to be able to pass the handler instance in, so that I can initialise it first, rather than passing in the class and having netmiko instantiate it.

I'm happy to work up a PR for this.  My first thought is a key_policy_handler option or similar, that overrides the ssh_strict setting if not-None.

**Comment by ktbyers** [comment]
@merlinthp Yes, please submit a PR on it and I will review. It has been a while since I have looked at some of this behavior in Paramiko.
