### ISSUE TITLE
Issue connecting to ASA

### ISSUE THREAD

**Issue by MikalFurnell** [ktbyers/netmiko#940]
Hello,

I am having an issue connecting to an ASA using netmiko. This is my first thing I have built in python so it might be obvious but I don't have enough experience to really understand what I am missing. Also at this point I am not doing much I just wanted to get the connection working before I actually ran all the commands I am going to be running against the devices. The connection to switches and routers works fine it is just the ASA, which I can putty into with no issue. I don't know if this is something that would effect it but I am using an ACS server attached to LDAP for authentication and the enable password is blank.

This is the code that I use to get the error further below:

```python
import netmiko
import csv
import getpass

username = input('ACS username: ')
password = getpass.getpass(prompt='ACS Password: ', stream=None)
enable_password = getpass.getpass(prompt='Enable Password: ', stream=None)
shift = input('Enter shift: ')
basedir = "Y:\Get_ALL_Configs"
version = []

with open('E:\Scripts\Devices.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    data = [r for r in reader]


for device in data:
            d1 = device
            d1.update({'username': username, 'password': password})

def FirewallInfo( firewall ):
    firewall_connect = netmiko.ConnectHandler(**firewall)
    firewall_command = firewall_connect.send_command("sh ver")
    version.append(firewall_command)
    firewall_connect.disconnect()

def SwitchInfo( switch ):
    switch_connect = netmiko.ConnectHandler(**switch)
    switch_command = switch_connect.send_command("sh ver")
    version.append(switch_command)
    switch_connect.disconnect()

for device in data:
    if device['device_type'] == 'cisco_asa':
        print(device['ip'])
        device.update({'secret': enable_password, 'port': 22})
        FirewallInfo(device)
    elif device['device_type'] == 'cisco_ios':
        print(device['ip'])
        SwitchInfo(device)
    else:
        print('Device %s is not recognized' % device['ip'])

print(version)    
```

Error: 
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\paramiko\channel.py", line 683, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Program Files\Python36\lib\site-packages\paramiko\buffered_pipe.py", line 160, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\netmiko-2.2.2-py3.6.egg\netmiko\base_connection.py", line 442, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "C:\Program Files\Python36\lib\site-packages\paramiko\channel.py", line 685, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Scripts/Test_GetDevice.py", line 37, in <module>
    FirewallInfo(device)
  File "E:/Scripts/Test_GetDevice.py", line 22, in FirewallInfo
    firewall_connect = netmiko.ConnectHandler(**firewall)
  File "C:\Program Files\Python36\lib\site-packages\netmiko-2.2.2-py3.6.egg\netmiko\ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\netmiko-2.2.2-py3.6.egg\netmiko\base_connection.py", line 246, in __init__
    self.session_preparation()
  File "C:\Program Files\Python36\lib\site-packages\netmiko-2.2.2-py3.6.egg\netmiko\cisco\cisco_asa_ssh.py", line 19, in session_preparation
    self.disable_paging(command="terminal pager 0")
  File "C:\Program Files\Python36\lib\site-packages\netmiko-2.2.2-py3.6.egg\netmiko\base_connection.py", line 863, in disable_paging
    output = self.read_until_prompt()
  File "C:\Program Files\Python36\lib\site-packages\netmiko-2.2.2-py3.6.egg\netmiko\base_connection.py", line 510, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\netmiko-2.2.2-py3.6.egg\netmiko\base_connection.py", line 450, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by ktbyers** [comment]
It looks like it fails on `disable_paging`. Unfortunately ASA requires priv 15 for disable paging to work. Here is what the code does.

```python
        self._test_channel_read()
        self.set_base_prompt()
        if self.secret:
            self.enable()
        else:
            self.asa_login()
        self.disable_paging(command="terminal pager 0")
```

That blank secret is potentially going to cause an issue as it will not do enable call and instead will try to do a `login` with your username and password to get elevated privileges.

One fix is to set the secret to something and then pass the 'secret' into ConnectHandler.

**Comment by MikalFurnell** [comment]
I will be working on this the next few days trying to add a non-empty secret and then retesting. I will let you know whether it fixes it for me.

**Comment by MikalFurnell** [comment]
So I was able to test this out. It ended up being a AAA statement on the firewall itself and not something I could have changed by myself in the ACS so after I got a networking person that had access to change it I was able to run it successfully.

Quick question. Im used to powershell so this might be a bad question but is everything returned by Netmiko a string? I am basically going to be converting a horribly written VBS that takes close to 50 minutes to run into python to try to get it closer to 15 minutes and part of that is it runs different variations of "show version" and "show bgp summary" specific information so I am just trying to figure out the best way to parse the data after running it once.

**Comment by ktbyers** [comment]
In general in Netmiko you would use `send_command("show version")` to execute the above command and it would return a string.

You could couple this with TextFSM (ntc-templates) parsing and then you could potentially get structured data returned. See here for more details on this:

https://pynet.twb-tech.com/blog/automation/netmiko-textfsm.html

Regards, Kirk

**Comment by MikalFurnell** [comment]
Thank you! I will definitely take a look at that.

**Comment by cdzr** [comment]
@ktbyers , Is there a way to send "alternate" credentials once connected to an ASA? 
I use the <code>login</code> option instead of <code>enable</code> and use a different username and password to enter privileged mode than what I originally logged in to the device with, from your comment above, I understand that the script will use the <code>username</code> and <code>password</code> inside the dictionary ( which is used to login ). Is this correct?

**Comment by ktbyers** [comment]
@cdzr Nope that is not supported in Netmiko (at least directly). We support straight .enable() call using an enable() secret.

We also support asa_login() using username and password that you used to SSH to device.

I guess you could try to subclass the `CiscoAsaSSH` and then over-write the `asa_login` method. You would have to tell Netmiko to then use this class instead of the default one for the ASA.


Regards, Kirk

**Comment by cdzr** [comment]
Thank you so much Kirk!

I'll look into the subclass.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
