### ISSUE TITLE
failed import in virtualenv

### ISSUE THREAD

**Issue by 1-61803** [ktbyers/netmiko#942]
I made a virtualenv with virtualenvwrapper and installed netmiko by doing

  pip install git+https://github.com/ktbyers/netmiko.git@v2.2.2

but importing it into python 2.7.14 gives the following error

  ImportError: dlopen(/Users/db/.virtualenvs/netmiko/lib/python2.7/site-packages/nacl/_sodium.so, 2): Symbol not found: _memset_s
    Referenced from: /Users/db/.virtualenvs/netmiko/lib/python2.7/site-packages/nacl/_sodium.so
    Expected in: /usr/lib/libSystem.B.dylib
   in /Users/db/.virtualenvs/netmiko/lib/python2.7/site-packages/nacl/_sodium.so

I'm on 10.8 and use python 2.7.14.

**Comment by ktbyers** [comment]
This is not really a Netmiko issue. It looks like you have an issue with pynacl library which is required by Paramiko.

You might want to try to manually reinstall pynacl and see if it works.

I assume you are using homebrew?

**Comment by 1-61803** [comment]
Yeah, it's not really a netmiko issue, but I thought it might be worth tracking.

I have `pynacl` installed via MacPorts — the `virtualenv` won't reference it at `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nacl/_sodium.so`, because it installs its own, which in turn seems to expect some symbols on a system library?

Any ideas?

**Comment by ktbyers** [comment]
I pretty much always use homebrew on a Mac though I haven't been using my Mac much for development lately.

There are quite a few references to this issue in the context of paramiko.

Yes, the virtual environment won't try to use the library in the other path. It will (generally) try to download and install it from pypi. And some of the cryptography related libraries require compilation (in that context).

**Comment by 1-61803** [comment]
I did install netmiko 2.2.2 with virtualenvwrapper using MacPorts on 10.13 (I should probably update my 1.4.2 portfile after all). I now realized that there's no formula on homebrew for netmiko neither. Are you aware that both macOS' main package managers lack netmiko? I'll see if I can update and upload it to MacPorts. A brew formula shouldn't be much of hassle to write either.

**Comment by ktbyers** [comment]
Okay, sounds good. I never really had any issue on Mac using Homebrew to install a new Python and then using a virtual environment and pip install. I haven't really been doing any active development on my mac in quite a while though.
