### ISSUE TITLE
disconnect() function add 2 second slower

### ISSUE THREAD

**Issue by fixlensmith** [ktbyers/netmiko#944]
Hi,

want to ask, is it important use .disconnect() function on Netmiko?
i have more than 50+ devices, so i need to close the connection after execute the command..so i put disconnect() function.

but it make the script slower 2 second per devices.
if i not use disconnect() it takes only 5 second, but if we use disconnect() it takes 7 second.

**Comment by ktbyers** [comment]
You could potentially use all of the VTY ports on a device as it might take much longer for the connection to close (i.e. be unable to SSH in until the exec-timeout expires for the given connection). That is the main issue.
