### ISSUE TITLE
NetMiko "Connection" passed as return value from Django view to Ajax and back to 2nd Django View

### ISSUE THREAD

**Issue by maheshkudva** [ktbyers/netmiko#945]
Problem: Connect to the end device Firewall

My desktop/laptop ---> SSH to a Linux Jumpserver ---> SSH to a Firewall/Router

With Django, I have a been able to create a UI which takes username, password and jumpserver as inputs and creates an SSH connection. Once the connection is good, the AJAX framework with Jquery is able to display the next set of UI for getting the Firewall login credentials. SSH with NetMiko is created and returned to AJAX with the following code

```python
        nmssh = {
            'device_type': 'autodetect',
            'ip':   nmd,
            'username': nmu,
            'password': nmp,
            'verbose': False,
            'allow_agent': True,
            'global_delay_factor': 2,
            'secret': ''
            }
        dev = netmiko.ConnectHandler(**nmssh)
        data = { 'nmssh' : str(dev) }
        return JsonResponse(data)
```

Now the issue is that the variable "dev" is not a standard object hence i need to convert it to a string. When I call the second function passing this argument from AJAX, it does not work. I understand i converted the object "dev" to just a string stripping it from its attributes.

I am forced to go with this approach since my jumpserver and my firewalls are using 2 factor authentication using RSA

How can I pass this connection variable without loosing its attributes?

This webapp will be used by atleast 20-30 simultaneously

**Comment by ktbyers** [comment]
Why do you need to pass the connection object via AJAX? The connection object is not serializable.

**Comment by maheshkudva** [comment]
Yes. its not serializable

Here is what happens
1)SSH to the NodeManager/ jump server - This authentication is using the
RSA token (token can be hard or soft)
2) Once I ssh to the jumpserver, I then SSH to the router/firewall/end
device. This authentication is also using the RSA token

On the webui, first form asks for the jumpserver credentials. IF this SSH
to the jumpserver is successful, AJAX(using jquery) unhides/presents the
second form for detail to login to the devices. So the SSH
channel/connection objects needs to be passed on to the other functions.
The NodeManager/Jumpserver login function will need to be used to handled
SSH to other NodeManager/Jumpservers as well. Hence i am keeping the
jumpserver login function independent.

Regards
Mahesh S Kudva
http://in.linkedin.com/in/maheshkudva

**Comment by ktbyers** [comment]
This doesn't sound like a Netmiko issue.
