### ISSUE TITLE
How to break ping or traceroute if got any expected character and send next command

### ISSUE THREAD

**Issue by tkdebnath** [ktbyers/netmiko#950]
I was writing script and if I send command for particularly ping I get the result properly , as I have multiple ping and trace statements , and I am sending each ping statement one by one , but problem comes when when there is no ping response and I want to break the current ping process and execute the next statement.
example:
ping = net_connect.send_command("ping 10.10.10.3 re 200")
ping1 = net_connect.send_command("ping 10.10.10.4 re 200")
ping2 = net_connect.send_command("ping 10.10.10.5 re 200")
print(ping, '\n' , ping1 , '\n' , ping2)

now 

I exactly want to break the execution of first ping if I get eg. 5 or 4 continuous drops "....." and move on to next ping statement  if there are drops in it too then break this and move to next command . And in the same way I want to do same for traceroute if I get 2 or 3 blank hops and don't want the execution to go till 30 hops break and move to next command

**Comment by ktbyers** [comment]
Try using write_channel() method and then send this:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/__init__.py#L33

**Comment by ktbyers** [comment]
Re-open if this is still an issue.
