### ISSUE TITLE
Unintended configuration change on Fortinet devices

### ISSUE THREAD

**Issue by Herc53** [ktbyers/netmiko#954]
https://github.com/ktbyers/netmiko/blob/fc288ff26efb67e06cc7098329e0c92d4c5c8358/netmiko/fortinet/fortinet_ssh.py#L21

Hi Guys,

however innocence this line may seems, it actually modifies device configuration and renders it "Out of sync" in Fortimanager. It's easy solution, but not the right way to do it if you plan to use this library in parallel with Fortimanager. Better solution is to capture those "-- more --" lines and send " " until you get prompt again. That would be complicated, but clean approach.

Regards,
Pawel

**Comment by ktbyers** [comment]
Yes, this is how Netmiko operates. It disables output paging. It doesn't try to manually handle it.

It is really on Fortinet to come up with a better solution if disabling output paging causes adverse side-effects with their other management tool.
