### ISSUE TITLE
get_interfaces_counters for Junos

### ISSUE THREAD

**Issue by ric79** [ktbyers/netmiko#956]
Hello,
when I run the command I don't see the entries for bundles (aexx.yyy) but only for phisical itf

Instead, for Cisco IOSXR, I get them. 

Is this behaviour expected?
Riccardo

Edit: Junos: 17.4R2.4

**Comment by ktbyers** [comment]
@ric79 Did you intend to file this against NAPALM and not Netmiko?

**Comment by carlniger** [comment]
inactive. closing.
