### ISSUE TITLE
IOError: Search pattern never detected in send_command_expect: \#t

### ISSUE THREAD

**Issue by wizard-31** [ktbyers/netmiko#957]
I am running a script to check some details from Cisco Switches. When I manually login into the device on command line, I am able to get the details. If I try from IDLE it works, but when I pass the command as a string to **device.send_command(cmd1)** it throws an error. 

The problem is it doesn't throw the error on the same switch when I run the script again. It throws this error after working with ~10 switches. I have to fetch the details from 50 switches. 

I always use netmiko.ConnectHandler() and disconnect() for each switch. 

It'll be great if you can help me out.

**Comment by ktbyers** [comment]
You will need to post your code (at least the relevant section of it), the command that is failing, and the full exception stack trace.

**Comment by wizard-31** [comment]
```
def SSHProcess(switchname):
	device = netmiko.ConnectHandler(device_type='cisco_ios', ip=switchname, username=username, password=password)
	command1 = "sh run | i ^template"
	Mode = device.send_command(command1)
        ModePkt = Mode.split("\n")
        ModePkt = u','.join(ModePkt)
	if condition in ModePkt:
		print something
        command2 = "sh cdp ne | c SEP"
	SEP = device.send_command(command2)
        SEP = SEP.split(' ')
	CountSEP = SEP[-1]

```

Stack trace 
**Traceback (most recent call last):
  File "test.py", line 126, in <module>
    read_input()
  File "test.py", line 104, in read_input
    switch_from_site(l)
  File "test.py", line 24, in switch_from_site
    enabled,modetyp,phonecount = SSHProcess(switch)
  File "test.py", line 43, in SSHProcess
    Mode = device.send_command(command2)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 1112, in send_command
    search_pattern))
IOError: Search pattern never detected in send_command_expect: usr2\-in\-sw1\#sh\ run\** 

And the error is not specific to a single command. Sometimes it fails at the first command, and then sometime in the second. 
As you can see, it shows that command2 is being called in the trace, but it displays a part of command1 along with the device prompt of the switch.

**Comment by wizard-31** [comment]
Update : I am able to run the code for now, I added expect_string and delay factor in the send_command().
@ktbyers  
But now I encounter a different issue, where I have two different types of prompts at the end. 
One set of switches have '#' as the end, while others have '>' as the end.

How to set two different type of expect string in a single command? Or will the function by default detect it?

**Comment by ktbyers** [comment]
expect_string takes regular expressions so you just need to do a regular expression "or" for that so probably:

```python
expect_string = r"(>|#)"
```
