### ISSUE TITLE
OS Error: Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by seju7** [ktbyers/netmiko#961]
Hi,

I am trying to distribute several NXOS to a bunch of devices. As the files are up to 350MB it can take several time for the upload to complete. I have tried send_command, send_command_timing and send_command_expect and played around with the delay_factor and sleep command, but I keep running into the OS Error.

#821 - There does not seem to be a promt, when uploading the files
#687 - I already tried the delay_factor, but it does not seem enough

```
try:
	print('Installing ' + image['Name'] + ' on ' + device + '...\n')
	print(connection.base_prompt)
	output = connection.send_command('copy tftp://xxx/n5k_update/' + image['Name'] + ' bootflash: vrf management',delay_factor=4)
	time.sleep(60)
	connection.clear_buffer()
	log.append(output)
except OSError as error:
	print(error)
	time.sleep(60)
```

Any idea how I can force netmiko to wait till the upload is completed?

Python: 3.7.0
Netmiko: 2.2.2
Paramiko: 2.4.2

Thank you very much for your help.

BR Seb

**Comment by ktbyers** [comment]
@seju7 How long does the transfer take if you do it manually?

**Comment by seju7** [comment]
Thanks for the quick reply. Great work you did there, Kirk.

The biggest(350mb) file took about 35min. 

Would it make sense to calculate a delay_factor by file size?
Or is it possible to make netmiko wait for the promt?

Thank you very much.

**Comment by ktbyers** [comment]
@seju7 I would try:

```python
output = connection.send_command('copy tftp://xxx/n5k_update/' + image['Name'] + ' bootflash: vrf management', delay_factor=10, max_loops=1500)
```

That should wait about 3000 seconds (50 minutes)

You can read more about the fundamental behavior here:

https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html
