### ISSUE TITLE
cisco_nxos_ssh output cut off

### ISSUE THREAD

**Issue by TomCos** [ktbyers/netmiko#962]
Wanted to discuss if anyone else is seeing this behavior.  I've only been writing code against NX-OS devices right now, versions anywhere from v5-v9 across the 3k, 5k, 6k, 7k, 9k, so milage may very.  I am using Napalm to run the commands, but the Napalm backend for nxos_ssh is just netmiko cisco_nxos_ssh from what I can tell.

While it's not happening all that much, I sometimes have output return cut off, and only showing the last couple lines of the prompt (hostname cut off).  I also sometimes have the same issue, but sometimes the command I entered, plus a newline, will be in the output as well.  Examples:
Running show version on a couple devices (none of those are the full hostnames):
{"show version": "r216-acc-1# "}
{"show version": "r215-acc-1# show version\n"}
{"show version": "r318-acc-1# "}
{"show version": "r422-acc-1# show version\n"}
{"show version": "st-1# show version\n"}

Tried to do copy run start (prompt cut off like above, but looks like newline was spammed):
{"show users": "c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# \nhostname-masked-c1r422-acc-2# show users\n"}

Tried to get show run (barely grabbed anything):
{"startup": "", "running": "c-1# ", "candidate": ""}

I've been adding sleep timers before all command runs to try to limit this from happening, but I don't think it's helping.

Just wanted to see if this is behavior anyone else is seeing commonly.  Again, it's not happening all the time, but it does happen and is unpredictable.

**Comment by ktbyers** [comment]
Have you tried setting the 'global_delay_factor' argument and see if that improves things. I would probably try it at 2 and also at 5.

I suspect something about the device is overly slow which is causing netmiko to get confused.

in napalm, you pass in the global_delay_factor using optional_args which you pass into the napalm driver arguments.

```
optional_args = {'global_delay_factor': 2}
```

Here are some more details on global_delay_factor

https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html

**Comment by TomCos** [comment]
Yes I've been default to a global delay factor of 2 in both Napalm and Netmiko.  It does help a bit, but the issue is still there.  I agree that it's likely just scraping a bit too much, however it does always seem to be at the same length.  I ended up just writing some post-command-run code that checks the first couple characters of the output and any of that character sequence is in the prompt or the command, re-run the command, but it's still risky and at a cost of runtime.  Any other recommendations outside of global_delay_factor?  I'm up for suggestions :D

**Comment by ktbyers** [comment]
@TomCos Try enabling the session_log and see if this gives you more information as to what is happening. This is an argument to ConnectHandler and will write a file regarding what happened during the session.

You can do this per device.

For example, 

```python
# Use some unique identifier per device (hostname, IP address, et cetera).
session_log = './{}'.format(hostname)
```

**Comment by TomCos** [comment]
Closing for now.  It's random generating the issue, so let me start logging and see if I can grab something worth investigating.
