### ISSUE TITLE
fast_cli="False" Problems

### ISSUE THREAD

**Issue by Amdpowered** [ktbyers/netmiko#964]
For some NXOS devices with fast_cli="True" or "False", there isn't any problems. However there are other NXOS devices where if fast_cli="False" causes the prompt detection to think "terminal length 0" is the prompt. This terminal length 0 is set by the base_connection class.

If I remove the fast_cli option from my connection json file, then prompt detection is correct. I understand why fast_cli=True would cause issues, but why would fast_cli="False" cause problems?

Code is very simple:
```
conn = ConnectHandler(**device)
prompt = conn.find_prompt()
print("Prompt is " = prompt)
```

As previously mentioned, in the failure scenario, the output will be "Prompt is terminal length 0".

**Comment by ktbyers** [comment]
Can you post your `device` dictionary? Just obfuscate any confidential information.

Remember you need to use `fast_cli=False` i.e. a Python boolean and not "False" which is a string and not a boolean (and actually would be treated as a boolean true by Python).

**Comment by Amdpowered** [comment]
You're right. I made the mistake you've described. I've confirmed that when corrected there is no problems.
