### ISSUE TITLE
Cisco ASA - Unable to Login

### ISSUE THREAD

**Issue by bjohnson9** [ktbyers/netmiko#968]
```
>>> from netmiko import ConnectHandler
>>> cisco_asa={
... 'device_type':'cisco_asa',
... 'ip':'10.52.95.140',
... 'username':'username',
... 'password':'password',
... 'secret':'secret',
... }
>>> net_connect=ConnectHandler(**cisco_asa)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/netmiko/ssh_dispatcher.py", line 190, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 245, in __init__
    self.establish_connection()
  File "/Library/Python/2.7/site-packages/netmiko/base_connection.py", line 749, in establish_connection
    raise NetMikoAuthenticationException(msg)
netmiko.ssh_exception.NetMikoAuthenticationException: Authentication failure: unable to connect cisco_asa 10.52.95.140:22
Authentication timeout.
```

**Comment by tonypnode** [comment]
That error `NetMikoAuthenticationException: Authentication failure: unable to connect cisco_asa 10.52.95.140:22 Authentication timeout.` is usually a an indication of either bad usernam/password. Can you ssh from the same device to the ASA manually from the same box you are trying to use Netmiko?

**Comment by bjohnson9** [comment]
I figured it out. I didn't need the enable password. Once I removed the enable password from my Python script, it worked fine.


________________________________

**Comment by tonypnode** [comment]
Awesome! 👍 

if you're all good, please close this issue.

**Comment by bjohnson9** [comment]
Thanks

**Comment by YMont** [comment]
Dear bjohnson9:

I have the same problem too,when I run this code --> net_connect = ConnectHandler(**my_device)

...
paramiko.ssh_exception.AuthenticationException: Authentication failed.
During handling of the above exception, another exception occurred:
...
and python system show about "Authentication failure: unable to connect cisco_ios..."

How could I figured out this problem? Please help

Thanks 

by ed
