### ISSUE TITLE
Possible faster auto discovery

### ISSUE THREAD

**Issue by TomCos** [ktbyers/netmiko#969]
Wanted to propose slightly re-writing the auto-discovery function.  Right now, there are only 5 unique commands out of 12 commands being run across the various platforms.  I have some more in commit, but again, more repeat.  I've been reviewing the code for the ssh_autodetect.py and while I'm not quite sure how it would be re-written, is it worth discussing separating the list cmds from SSH_MAPPER_BASE autodetect_dict and after each command run, running against a the list of device_type and autodetect_dicts (should provide a quick auto-discovery in the end)?  The only issue I see if the dependency on 'dispatch' per device type, but dispatchers could also be looped over if needed.  Again, this is another one of those where I've been looking at it, but can't quite get it to work, and would rather not break it, so just wanted to see some opinions.

**Comment by ktbyers** [comment]
I didn't understand the above, but it already cache's the results so it will only run `show version` and the other commands once (for each unique command).

**Comment by TomCos** [comment]
My bad, guess I misunderstood, but it makes more sense now

**Comment by ktbyers** [comment]
Yes, the code is a bit tricky there on how it is cacheing the results...
