### ISSUE TITLE
Problem in receiving output

### ISSUE THREAD

**Issue by gmu-msk** [ktbyers/netmiko#97]
What does this loop actually do in send_command method?

```python
while (not_done) and (i <= max_loops):
    time.sleep(1*delay_factor)
    i += 1
    # Keep reading data as long as available (up to max_loops)
    if self.remote_conn.recv_ready():
        output += self.remote_conn.recv(MAX_BUFFER).decode('utf-8')
    else:
        not_done = False

```
It seems that loop breaks when ```remote_conn.recv_ready() == False```

As a result we stop reading data in case when after one second (by default) we don't get all the data from remote device.

One second is enough in most cases, but if run a command that need more time to be executed,  ```show run``` on Cisco IOS for example, in approximately 50% cases i got only
```
Load for five secs: 26%/0%; one minute: 15%; five minutes: 15%
Time source is NTP, 14:03:28.766 MSK Sat May 30 2015

Building configuration...
```
instead of full output.

**Comment by ktbyers** [comment]
@gmu-msk 
The loop keeps reading data as long as data is present to be read (with a 1/2 second delay between loop iterations--delay_factor defaults to .5). Once there is no more data present to be read, the program will fall out of the loop.

You probably need to adjust "delay_factor" in the send_command() method so that you give the device sufficient time to have data available. Try it with a delay_factor of 4 or 8 and see what happens.

**Comment by gmu-msk** [comment]
After looking closer to this problem I see that loop works well.
But is there any way to make sure that I got full output for every command?

**Comment by ktbyers** [comment]
I would think the default delay factor should work for most commands. You
will need to modify delay_factor for commands you know are slow.

If this is too cumbersome, let me know...


Kirk

On Sunday, May 31, 2015, gmu-msk <notifications@github.com> wrote:

> After looking closer to this problem I see that loop works well.
> But is there any way to make sure that I got full output for every command?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/97#issuecomment-107134963>.
>


-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by gmu-msk** [comment]
Don't You think it also depends on some other factors? For example link delay between ssh-client and ssh-server....or packets may need to be retransmitted because of link congestion...

**Comment by ktbyers** [comment]
You will have 1 second to have some initial data available and 1/2 second to have more data available. The latency/retries of the link shouldn't matter as the script waits for the time and then checks the channel (so if there is latency/retries that would happen during the SSH channel check i.e. after the delay has already happened).

You can default to longer delays, however, if this amount of time is not sufficient (using the delay_factor argument). The trade-off is that your script will be slower to execute.

I will create an issue in GitHub to have a GLOBAL default (i.e. one place where you could adjust the delay factor that would affect all devices for that script execution). In this way, if the default delay is not sufficient, then you can adjust it more easily.

I am definitely interested in what you see in practice so if you are seeing big problems with the default delay or adjusting the delay, just let me know.

**Comment by ktbyers** [comment]
See issue #98
