### ISSUE TITLE
Cisco 2960 enable failed

### ISSUE THREAD

**Issue by virgil246** [ktbyers/netmiko#976]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\virgi\Anaconda3\lib\site-packages\netmiko\cisco_base_connection.py", line 18, in enable
    return super(CiscoBaseConnection, self).enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "C:\Users\virgi\Anaconda3\lib\site-packages\netmiko\base_connection.py", line 1223, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.

`from netmiko import ConnectHandler`
```
cisco2 = {
    'device_type': 'cisco_ios',
     'host': 'IP', 
    'username': 'USER', 
    'password': 'PASS', 
    'secret': 'PASS',
	 )
```
`net_connect = ConnectHandler(**cisco2)`
`net_connect.enable()`

then I got error  PLZ HELP ME

**Comment by ktbyers** [comment]
Probably add the session_log and see what went wrong:

```python
from netmiko import ConnectHandler

cisco2 = {
    'device_type': 'cisco_ios',
     'host': 'IP', 
    'username': 'USER', 
    'password': 'PASS', 
    'secret': 'PASS',
    'session_log': 'my_output.txt',
}

net_connect = ConnectHandler(**cisco2)
net_connect.enable()
```

This should create a file named my_output.txt in the current directory. Look at that file and see what it shows.

Also double check your 'secret' you are passing in is correct.

**Comment by virgil246** [comment]
sorry i got wrong secret for enable QQ
