### ISSUE TITLE
TELNET_RETURN not being used always

### ISSUE THREAD

**Issue by TomCos** [ktbyers/netmiko#978]
We've been working on developing internal code for automating on NCS2006 environment.  We're working on enabling SSH, but for now, we're stuck with telnet due to Cisco compatibility.

I'm testing some code to use the generic_termserver_telnet (and would hopefully like to develop an actual driver for TL1 in the future), but we're having issues getting data back.  After some testing, I think the issue is find_prompt.  find_prompt is not getting anything back, but I think that's because it's using the default RETURN variable, instead of the TELNET_RETURN one.

I have a sample to show.  The prompt is '>':
>>> net_connect = netmiko.ConnectHandler(device_type='generic_termserver_telnet', host='SOMEHOST', timeout=10, port=3083)
>>> net_connect.clear_buffer()
>>> net_connect.write_channel(net_connect.TELNET_RETURN)
>>> net_connect.read_channel()
'\r\n> '
>>> net_connect.clear_buffer()
>>> net_connect.write_channel(net_connect.RETURN)
>>> net_connect.read_channel()
''
>>> net_connect.RETURN
'\n'

You'll see, if using regular RETURN, you'll get nothing, but because it is a telnet connection, if you use TELNET_RETURN, you get what we expect.  My question is, is there any reason why we don't do something like this?:
self.RETURN = "\n" if default_enter is None else default_enter
if self.protocol == "telnet":
    self.RETURN = "\r\n"

I ask because, find_prompt and a few other functions are hard coded to use self.RETURN regardless of TELNET_RETURN, which might cause issues.

**Comment by ktbyers** [comment]
@TomCos You can just pass in the `default_enter` argument to ConnectHandler and set it to `\r\n`.

The other option we could do is if `telnet` is the device_type then could set `self.RETURN = self.TELNET_RETURN` (as long as default_enter in ConnectHandler was not set)
