### ISSUE TITLE
Add new vendor - Pica8

### ISSUE THREAD

**Issue by packetshooter** [ktbyers/netmiko#980]
Request to add support for whitebox vendor Pica8. I'll fork out a branch to try to create a driver, feedback and/or help will be welcome.

**Comment by packetshooter** [comment]
[https://github.com/packetshooter/netmiko](url) link to fork I have to create pica8 driver

**Comment by carlniger** [comment]
I'm going to close this since its pretty old. If you'd like to add a vendor please follow the guide [here](https://github.com/ktbyers/netmiko/blob/develop/VENDOR.md) and open a PR for it; be sure to include test data/output as well!
