### ISSUE TITLE
Unable to ssh

### ISSUE THREAD

**Issue by net9000** [ktbyers/netmiko#983]
New to all of this and trying to just do basic stuff but not having much luck.  I want to just login to a router using python/netmiko and pieced this together from the web but it doesn't seem to work. 

`>>> from netmiko import ConnectHandler
>>>
>>>
>>> platform = 'cisco_ios'
>>> host = 'r1-2911.domain.com'
>>> username = 'admin'
>>> password = 'admin'
>>> device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
`

Tried this as well:
`>>> from netmiko import ConnectHandler
>>> cisco_2911 = {
... 'device_type': 'cisco_ios',
... 'ip': '10.10.1.1',
... 'username': 'admin',
... 'password': 'admin',
... }
>>> netconnect = ConnectHandler(**cisco_2911)
`
After running it either way it just returns the python prompt.  I got it to fail once when it couldn't resolve the host name but now it doesn't fail but it doesn't seem to succeed either.  I am missing something but not sure what?

**Comment by tonypnode** [comment]
It sounds like you just connected and that's it. You'll probably want to have it do something like 

```
output = device.send_command('show version')
print(output)
```

**Comment by net9000** [comment]
Include that with the initial commands?  Or after its connected?  I guess I was just expecting to say "connected to xyz via ssh..."

**Comment by tonypnode** [comment]
```
from netmiko import ConnectHandler

cisco_2911 = {
    'device_type': 'cisco_ios',
    'ip': '10.1.1.1',
    'username': 'admin',
    'password': 'admin',
}
netconnect = ConnectHandler(**cisco_2911)

myconfig = netconnect.send_command(command_string='show version')

print(myconfig)
```

**Comment by net9000** [comment]
> ```
> from netmiko import ConnectHandler
> 
> cisco_2911 = {
>     'device_type': 'cisco_ios',
>     'ip': '10.1.1.1',
>     'username': 'admin',
>     'password': 'admin',
> }
> netconnect = ConnectHandler(**cisco_2911)
> 
> myconfig = netconnect.send_command(command_string='show version')
> 
> print(myconfig)
> ```

**Comment by tonypnode** [comment]
it uses markdown :)

so if you put multiple code lines in between three tick marks ` it will format your code :) 

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by tonypnode** [comment]
It looks like you are using legacy python (<3.0). I would recommend switching to python 3.4 or above.

**Comment by net9000** [comment]
Thanks man!  How I switch to newest python?  I am complete amateur when it comes to coding. 

```>>> cisco_2911 = {
... 'device_type': 'cisco_ios',
... 'ip': '10.10.10.1',
... 'username': 'admin',
... 'password': 'admin',
... }
>>> net_connect = ConnectHandler(**cisco_2911)
>>> net_connect.find_prompt()
ur12911>'
>>> output = net_connect.send_command("show ip int brief")
>>> print output
Interface                  IP-Address      OK? Method Status                Protocol
Embedded-Service-Engine0/0 unassigned      YES NVRAM  administratively down down
GigabitEthernet0/0         122.33.9.83   YES NVRAM  up                    up
GigabitEthernet0/1         10.10.10.1     YES NVRAM  up                    up
GigabitEthernet0/2         unassigned      YES NVRAM  up                    up

**Comment by tonypnode** [comment]
no worries! We've all been there :)

Instead of going through it on here, please close this issue and you can get a lot better info to get that done pretty fast on the networkToCode slack channel.

http://www.networktocode.com/community/
