### ISSUE TITLE
Fortinet Accept Disclaimer After Login

### ISSUE THREAD

**Issue by neveragain2003** [ktbyers/netmiko#988]
All of our Fortinets have a disclaimer you have to accept by pressing 'a' after logging in.  When I try to connect with netmiko, I get  a Socket is Closed error.  It hangs on the 
net_connect = netmiko.ConnectHandler(**devices) line below.  Any suggestions?

import netmiko

devices = {
    'device_type': 'fortinet',
    'ip': '10.1.1.1',
    'username': 'admin',
    'password': 'xxxxxxxxx',
}

net_connect = netmiko.ConnectHandler(**devices)
output = net_connect.send_command('a')
output = net_connect.send_command('show full-configuration')
print(output)

**Comment by ktbyers** [comment]
@neveragain2003 Can you show me what this looks like for a manual SSH session? You can obscure text to hide anything that is confidential.

Is this something you have to configure on the fortinet?


Kirk

**Comment by neveragain2003** [comment]
This is something that is configured on the Fortinet.  It's kind of like the MOD on Cisco devices but you actually have to accept the terms.  When I login with a manual SSH session I get the following:

P O S T W A R N I N G W A R N I N G W A R N I N G W A R N I N G 
This is a private computer system. Unauthorized access or use 
is prohibited and subject to prosecution and/or disciplinary 
action. All use of this system constitutes consent to 
monitoring at all times and users are not entitled to any 
expectation of privacy. If monitoring reveals possible evidence
of violation of criminal statutes, this evidence and any other 
related information, including identification information about 
the user, may be provided to law enforcement officials.
If monitoring reveals violations of security regulations or
unauthorized use, employees who violate security regulations or
make unauthorized use of this system are subject to appropriate 
disciplinary action.
P O S T W A R N I N G W A R N I N G W A R N I N G W A R N I N G
 
(Press 'a' to accept):

**Comment by neveragain2003** [comment]
When I run the same code with a device that does not have the login banner, it works perfect.

**Comment by neveragain2003** [comment]
Yes.

**Comment by volkovski** [comment]
Hi,
I think a disclaimer banner is before entering username/pass. 
Until you enter 'a' to accept this you are not allowed to insert U/P.

**Comment by neveragain2003** [comment]
It's a post login banner.  We do also have a pre-login banner but that only shows in the web GUI.  The attached screenshot is from logging in with PuTTY.
![fortinet login with banner](https://user-images.githubusercontent.com/23296020/47968513-a53b9e80-e030-11e8-9b7e-a28fdad6d4a5.PNG)

**Comment by jaaacck** [comment]
I've got this issue as well. I've tried the "find_prompt()" on the connect handler but this is occurring before the connection is established to the firewall. So the find_prompt() never actually gets a chance to run.

```
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group14-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-ed25519
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-ed25519 host key for IP_HERE:
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:read_channel:
****************************************************
*       You must manaully copy config changes from *
*    this device to the Mirrored firewall in       *
*               ##FIREWALL_NAME_HERE##      *
****************************************************

(Press 'a' to accept):
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:netmiko:read_channel:

```

Error raise:

```

    raise socket.error("Socket is closed")
OSError: Socket is closed


```

Current script:

```
        print("connecting...")
        net_connect = ConnectHandler(**firewall) ##<<This is as far as it gets
        time.sleep(1)

        output = net_connect.find_prompt() # look for the current prompt, expecting a banner
        print(output)
        if "(Press \'a\' to accept):" in output: #If a banner comes up, accept it
            net_connect.write_channel("a\r")

        version = net_connect.send_command(command_string='get system status | grep Version:')
        net_connect.disconnect()
```

Happy to run any further tests if required.

**Comment by ktbyers** [comment]
@jaaacck Why does the fortinet require you to manually copy config changes to the mirrored firewall? That statement sounds self-contradictory?

Also on the face of it, this behavior is very bad by the Fortinet (as in one case you have a message you totally don't care about and are forced to hit "a"). In the second case you also hit "a", but you probably care about that message.

Though it is possible I am just misinterpreting this?

**Comment by jaaacck** [comment]
@ktbyers This is an internal thing within the company I work at. Replication between datacenters is sometimes a manual process unfortunately. This isn't something Fortinet have forced upon us, this is manually configured notice on some devices.

This banner could say anything like the usual "Data protection... unauthorized access prohibited... press 'a' to accept", the same as @neveragain2003 has in their screenshot.

**Comment by ktbyers** [comment]
@jaaacck Okay, I misunderstood that (i.e I didn't realize it was just an internal banner you had created).

Someone will need to make a PR on this to handle the "Press 'a' to accept" message. You can look at the HP ProCurve driver as a reference example since HP ProCurve does something similar.

**Comment by jaaacck** [comment]
Created a PR - https://github.com/ktbyers/netmiko/pull/1192

**Comment by carlniger** [comment]
Thanks @jaaacck  -- going to close this and we'll handle the rest in the PR!
